### ISSUE TITLE
Calling "cart/removeFromCart" with a quantity does not decrement the quantity

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1003]
### Expected behavior
Calling "cart/removeFromCart" with a quantity should decrement the quantity for that cartItem

### Actual Behavior
Quantity is not decremented

### Steps to Reproduce the Behavior
I don't believe this functionality is currently used in the stock shop since we don't currently allow you to change quantities.

1. Add an item to the cart
2. Execute `ReactionCore.Collections.Cart.findOne()` in the browser console to get the current cart
3. Observe the quantity is 1
4. Store the cart Item ID
5. Execute Meteor.call("cart/removeFromCart", <youritemID>, 1);
6. Observe there is no error
7. Execute `ReactionCore.Collections.Cart.findOne()` again (or however you want to look at the db)
8. Observe that the quantity is still 1

Additionally there probably needs to be a check that if the decrement brings the quantity to `<= 0` that the item should just be removed. I also don't see a test for this but I will try to add one if it's missing.

Looking at the method code I can't see why this isn't working. The Mongo call returns a 1 and the values seem to be correct.

**Comment by zenweasel** [comment]
There's a note in the cart tests
        // fixme: we expect decrease the number of items, but this does not
        // occur by some unknown reason

**Comment by aaronjudd** [comment]
@jshimko @zenweasel I think this should make into 0.14.. what do you think?

**Comment by zenweasel** [comment]
Closed via #1273
