### ISSUE TITLE
Missing Currency & Localization

### ISSUE THREAD

**Issue by Roshdy** [reactioncommerce/reaction#1006]
I'm amazed by the effort spent and the work done on this project. 
(All the below comments are from the Dashboard control,..i didn't touch the code yet)
However, i was trying to test the application by making simple customizations, I am in Kuwait now, and i can't find the KWD (Kuwait Dinar) on the currencies list. Also when changing the language to "Arabic" nothing is actually localized. the layout only goes RTL, and it's a bit messy (try to add a product with arabic language).

On another end, i tried to make the application name in 'Arabic' (only for viewing), instead it changed it in the URL (which messed up the routing). I suggest that you make it possible for a display name, and an App name (separate), to be able to fulfill such customization.

**Comment by aaronjudd** [comment]
@roshdy thanks for the feedback. Leaving this open as an issue, we're aware the RTL is a little messy at the moment, it's on short list to give it all another review.  The url issue is documented elsewhere, and we'll fix as a critical bug in 0.13.  Leaving this open to track this stuff.

**Comment by Roshdy** [comment]
Thanks @aaronjudd. Looking forward to this version 😃

**Comment by mikemurray** [comment]
RTL issues for the product detail and some navigation drop-downs have been resolved in PR #1095.

**Comment by aaronjudd** [comment]
I believe the url routing is now resolved as well.  updated in 0.14.

**Comment by mikemurray** [comment]
The Arabic language not loading is due to it being added to the `translations` collection with a null `shopId`. When we try to select the language in the dropdown, it fails to return because the publication is fetching translations by `shopId` and `i18n`(name).

**Comment by mikemurray** [comment]
Related to https://github.com/reactioncommerce/reaction/issues/960 missing shopId
