### ISSUE TITLE
Product grid multi-select issues

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1007]
For bugs, please fill out the three following sections completely

### Expected behavior
Shift + Click or Ctrl + Click on a product in the grid should alloy you to multi select a product.

### Actual Behavior
Shift + Click or Ctrl + Click does nothing.

### Steps to Reproduce the Behavior
Shift + Click or Ctrl + Click on a product in the grid.

**Comment by aaronjudd** [comment]
I think this works...
