### ISSUE TITLE
Add support for custom domain names

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#101]
As a store administrator, I want to be able to use custom domain name(s) for my shop(s)

**Comment by aaronjudd** [comment]
This additional functionality is really related to to #236.

**Comment by kirkins** [comment]
Any advice for someone new to Docker wanting to do this? Do I use 'docker attach' and then run that command, or do I have to start the install process all over again?

**Comment by aaronjudd** [comment]
@kirkins see https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-docker, the ROOT_URL is an ENV url that can be passed whenever you start the Docker container.
