### ISSUE TITLE
Populating Shops.domains via fixture is not possible

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#1017]
For bugs, please fill out the three following sections completely

### Expected behavior

The usecase is to create a document of the db.Shops collection via data fixture. Additionally the shop is intended to run with a ROOT_URL different than localhost.

e.g.

 `ROOT_URL=http://tsp.dyn.projekt-und-partner.de ./reaction --port 8000`

Executing this command should update the shop document in database and run the shop with the domain given in ROOT_URL. The shop document does contain:

`    "domains" : [
        "tsp.dyn.projekt-und-partner.de"
    ],
`

### Actual Behavior

On startup, I get this error over and over:

`INFO Reaction: No shopId, waiting one second...`

This is because the default Shop document coming from loadPackages (and adhering to the Shop schema) does prepopulate the domain with `localhost`. This problem is somewhat related to https://github.com/reactioncommerce/reaction/issues/548.

### Steps to Reproduce the Behavior

Even without fixture it is reproducable. Get a fresh copy of RC and run:

 `ROOT_URL=http://tsp.dyn.projekt-und-partner.de ./reaction --port 8000`

I would expect to be able to load a shop data fixture either in onCoreInit or afterCoreInit. Neither will work.

**Comment by spencern** [comment]
We experienced this issue as well and had to adjust the default value here:
https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-schemas/common/schemas/shops.js#L177

**Comment by prinzdezibel** [comment]
@spencern: I could resist to do that for now. But if the problem hurts too much, I'll do that as well 👍

**Comment by zenweasel** [comment]
I believe that SimpleSchemas and `defaultValue` are somehow at the heart of this issue. It's only elements with a default that seem to have an issue. Correct me if I am wrong.

**Comment by prinzdezibel** [comment]
Yes, It has to do with the defaultValues of the schema and how that translates to database upserts.

This problem is addressed with the filed PR.
