### ISSUE TITLE
Documentation for customization of existing form

### ISSUE THREAD

**Issue by megastef** [reactioncommerce/reaction#102]
I read the section about templates/ironrouter etc. still it is not clear to me to find the best way to adapt the "product/variants/variantsForm" - could you please advise about the best way to change the form that it shows additional custom fields (I like to do location field with geo-lookup and calendar for rental items) - without changing the form in reaction-core package directory.  And I don't want to touch existing logic at this moment, basically a new template.

**Comment by aaronjudd** [comment]
See http://docs.reactioncommerce.com.  New docs issues should be place on https://github.com/reactioncommerce/reaction-docs
