### ISSUE TITLE
Improve Address validation

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1021]
I am able to enter the number 1 for all fields in the Billing/Shipping address form. Seems like it should check zip and phone for US addresses?

**Comment by aaronjudd** [comment]
General Tax

1.  Address Validation
2.  TaxCode Mapping
3.  Returns
4.  VAT Calculations


AvaTax
http://developer.avalara.com/avatax/testing-your-integration/
 
- Certified Checklist http://developer.avalara.com/avatax/certification/
- Create an Account http://developer.avalara.com/avatax/api-reference/onboarding/v1/



# Address Validation

For Shipping and Taxes we need USPS-certified Delivery Point Validation of addresses.

These are not just mappable addresses, but must be valid shippable addresses.

We also need international address validation.  Validation should work without configuration, but allow for configuration of services that provide better/more accurate information.

## Functionality

- Should use a free service  (Google) as default for OSS
- Should use Google API credentials (stored in Core->Settings)

- Should allow for configuration of alternate services
	- Should use service provided by Shipping service as configuration
	- Should register potential providers and configuration in Core -> Settings
- Should store ZIP+4 for US addresses
- Should save "validated: true" as part of the addressBook record
- Should save "residential" vs "commercial" flag
- Should validate international addresses (perhaps alternate provider)
- Should validate US phone numbers (possibly international)
- Should provide user error handling
- Should supply language and shop locale as preferred

## UIX
- Should pre-populate Country, Region/State in addressBook
- Should validate during input, autocorrect
- Should fallback to regular input fields if there is no validation service for locale
- If there are multiple matches of address, let user select correct address.

## Dashboard

I think that these settings, plus the Google API, and the "Allow guest checkout" options could move into a "Checkout" configuration card. Let's discuss.

## Service providers

Many, many more... but here's a few for reference.

- Strikeiron
- QAS
- CDYNE
- MelissaData
- Satori Software
- SmartyStreets
- Avalara
- USPS
- Lob
- EasyPost
- Shippo

**Comment by aaronjudd** [comment]
We should also implement https://goshippo.com/docs/address-validation for Shippo.  I think this issue should become a `impact-major` soon...?

**Comment by zenweasel** [comment]
I'm going to create a separate issue for the Shippo implementation so we can gather all the Shippo improvements/fixes into one place

**Comment by zenweasel** [comment]
I was looking at them just because the name was hilarious but "SmartyStreets" might be another good one to build a test implementation on. At least for US

**Comment by zenweasel** [comment]
This is not really an integrations issue I think. We may want to work together on integrations with address validation services though. But I think the basic UI needs to come from core and probably needs to have better definition before this gets worked on.

**Comment by aldeed** [comment]
I'm going to close this. Although there are many things mentioned in this issue, it's rather old and I think the two main points are complete:
- Core has a robust address validation API and UI that you can easily plugin third party validation services into
- The storefront starter kit UI includes (in next release) address validation by default, if enabled on the server.

If anything mentioned elsewhere in this issue is still relevant, please submit as a separate smaller GH issue.
