### ISSUE TITLE
Allow users to turn off "multishop" URL's

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1022]
As a user who only has one shop, I want to have an option to turn off requiring my shop name to be in the URL

**Comment by tdecaluwe** [comment]
Or, equivalently, add the ability to add a default shop?

**Comment by aaronjudd** [comment]
or if there is just one shop in the db... don't use the shop prefix.

**Comment by tdecaluwe** [comment]
@aaronjudd I agree, don't complicate things that don't have to be complicated.
