### ISSUE TITLE
i am getting error while running ./reaction 

### ISSUE THREAD

**Issue by useralive003** [reactioncommerce/reaction#1029]
i am getting error while running ./reaction 

root@dev-app-server:~/reaction# ./reaction
Starting Reaction using '/root/reaction/settings/dev.settings.json'.
[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected mongo exit code null. Restarting.
bin/run: line 30:  8520 Killed                  meteor $CMD --raw-logs --settings $DEVCONFIG $ARGS

**Comment by zenweasel** [comment]
@sreemohan003 Can you please provide some details about your operating system, versions, etc. as no one else is seeing this issue?

**Comment by sreemohan003** [comment]
i am getting error while running ./reaction

root@dev-app-server:~/reaction# ./reaction
Starting Reaction using '/root/reaction/settings/dev.settings.json'.
[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected mongo exit code null. Restarting.
bin/run: line 30: 8520 Killed meteor $CMD --raw-logs --settings $DEVCONFIG $ARGS


operating system linux

**Comment by aaronjudd** [comment]
Looks like an error starting Mongo on you linux (so a Meteor installation issue, not necessarily Reaction specific).  

Take a look at http://stackoverflow.com/questions/15610385/meteor-unexpected-mongo-exit-code-100

There are likely other's with the same issue.  What version of Linux are you running?  Is it a VM or a Docker Container?  

 Try running just `meteor` instead of `reaction`, and see if you get different results..

**Comment by sreemohan003** [comment]
if i run meteor i am getting like this and am not using mongodb i am using mlab 
Unexpected mongo exit code null. Restarting.
Killednloading vsivsi:job-collection@1.3...  \

my dev.settings.json 

{
  "ROOT_URL": "",
  //"MONGO_URL": "",
  "MONGO_URL": "mongodb://root:Password@ds055564.mlab.com:55564/mohanda",
  "MAIL_URL": "",
  "reaction": {
    "REACTION_USER": "",
    "REACTION_AUTH": "",
    "REACTION_EMAIL": ""
  },
  "isDebug": "info",
  "public": {}
}

**Comment by jshimko** [comment]
Try running:
```sh
MONGO_URL="mongodb://root:Password@ds055564.mlab.com:55564/mohanda" meteor
```
(with the correct db password, of course)

**Comment by sreemohan003** [comment]
when i put 
MONGO_URL="mongodb://XXX:XXX@ds055564.mlab.com:55564/mohanda" meteor

i am getting 
[[[[[ ~/reaction ]]]]]

=> Started proxy.
Killednloading vsivsi:job-collection@1.3...  \

after that i put    ./reaction i am getting below error

[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected mongo exit code null. Restarting.

/root/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at Object.exports.spawn (child_process.js:746:9)
    at spawnMongod (/tools/runners/run-mongo.js:45:24)
    at launchOneMongoAndWaitForReadyForInitiate (/tools/runners/run-mongo.js:468:12)
    at launchMongo (/tools/runners/run-mongo.js:682:7)
    at MongoRunner._startOrRestart (/tools/runners/run-mongo.js:789:19)
    at [object Object].<anonymous> (/tools/runners/run-mongo.js:857:14)
    at runWithEnvironment (/tools/utils/fiber-helpers.js:112:21)

**Comment by jshimko** [comment]
Most likely an issue connecting to your database.

Please try just running:
```
meteor
```

**Comment by sreemohan003** [comment]
i run oly meteor 

root@dev-app-server:~/reaction# meteor
[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected mongo exit code null. Restarting.
Killednloading vsivsi:job-collection@1.3...  -
root@dev-app-server:~/reaction#
  
after that what can i do ???

**Comment by jshimko** [comment]
This is a fresh clone of Reaction with no modifications?  What OS are you using ("Linux" can mean a pretty long list of options).

**Comment by sreemohan003** [comment]
i am using 3.13.0-57-generic GNU/Linux

**Comment by jshimko** [comment]
That's the operating system kernel.

**Comment by sreemohan003** [comment]
i did't understand what are you asking . please help me out to move  forward

**Comment by sreemohan003** [comment]
if i run ./reaction i am getting error 
Starting Reaction using '/root/reaction/settings/dev.settings.json'.
[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected mongo exit code null. Restarting.
bin/run: line 30: 10781 Killed                  meteor $CMD --raw-logs --settings $DEVCONFIG $ARGS

**Comment by jshimko** [comment]
We need more info to be able to make suggestions.  Nobody else appears to be experiencing this issue, so it is likely something on your end.  Without knowing more details, I'm afraid there's very little I can suggest.

Linux is not an operating system.  It's a [kernel](http://stackoverflow.com/questions/2013937/what-is-an-os-kernel-how-does-it-differ-from-an-operating-system).  It's a _part_ of an operating system.  Ubuntu, Fedora, OpenSUSE, Alpine, etc. are examples of Linux operating systems (all of which have the Linux kernel in them).  And every one of them has a long list of differences that make their troubleshooting steps unique. 

To help you solve a problem that only you are experiencing, we will need the exact steps that it takes to reproduce the issue from the point where you download Reaction code from Github.  Without knowing which OS you're running the app on or whether you've altered Reaction code, I'm just trying to guess a solution with no context.

**Comment by sreemohan003** [comment]
i followed this github 
https://github.com/reactioncommerce/reaction

and i did these steps
curl https://install.meteor.com | /bin/sh # installs Meteor
git clone https://github.com/reactioncommerce/reaction.git
cd reaction
meteor npm install
./reaction

**Comment by jshimko** [comment]
Ok.  I just copy/pasted those exact commands and it works fine for me, so I still need to know more about your OS environment.

**Comment by sreemohan003** [comment]
how can i get that can you please help me out for this

**Comment by jshimko** [comment]
Where is the machine you are running this on?

**Comment by sreemohan003** [comment]
server is running in digitalocean

**Comment by jshimko** [comment]
Ok.  You needed to specifically choose an operating system when you started that server.  What was it?

**Comment by sreemohan003** [comment]
sir how can i check that sir

**Comment by sreemohan003** [comment]
actually i don't have knowledge in server side sir . help me out to get run reaction commerece give me the steps for install

**Comment by sreemohan003** [comment]
my node version -  v0.12.7
npm version - 2.11.3
git version -1.9.1

**Comment by newsiberian** [comment]
@sreemohan003, hello, could you show the output of this command: `uname -a`?

**Comment by sreemohan003** [comment]
@newsiberian if i run uname -a  

Linux dev-app-server 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zenweasel** [comment]
Hi @useralive003 ,

This is not an issue with Reaction but an issue without your particular installation. We would be glad to help you troubleshoot this problem further, however a Github issue is not the appropriate place. Please visit our chat channel https://gitter.im/reactioncommerce/reaction where we can continue the conversation in real time.
