### ISSUE TITLE
deploy to Heroku: default credentials

### ISSUE THREAD

**Issue by dgavigan** [reactioncommerce/reaction#1041]
Howdy, 

I've deployed to herkou just fine, but I can't get access to the default credentials. I am aware it should log those out in the console during install, but when I kick off the heroku deploy I don't get that information back. 

I am also aware I can set it in the settings config file, but every time I do that, my deploy goes wrong. 

I see the user created in the DB, but obviously I can't get to the hashed password value

Does anyone with experience on deploying to heroku have any advice/tips/suggestions? 

Thanks!

**Comment by aaronjudd** [comment]
You can also set the settings using environment (config) variables. This is the way that I'd recommend configuration for any environment, not specifically heroku, but should work there as well.

**Comment by dgavigan** [comment]
Sweet. Thanks for the advice. Ill post and look around on the forum.

**Comment by stunjiturner** [comment]
i worked both angles the past day using environment variables and creating a settings/settings.json and changing the .gitignore file to exclude, still no user found or in the database. How do you create a default admin user? in the database there is an admin user created called qedjrj4f@goattee.herokuapp.com, where goatee is the name app created on heroku. but access to the password i never get in the startup logging for heroku in terminal
