### ISSUE TITLE
Add "pageTitle" param to routes registry

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1044]
Allow users to set the page title (and maybe description) in the "routes" section of the registry rather than having to write/modify a helper file.

**Comment by aaronjudd** [comment]
To be added to the "Router" routes collection.. when we build this out.  The registry is fine for app functionality and can use defaults from there, but in reality where page title will matter is not in dashboard/app pages (*you don't need seo there do you?*)

**Comment by jshimko** [comment]
Great point

**Comment by aaronjudd** [comment]
Closing - insufficient details.
