### ISSUE TITLE
Issues On "module-structure" branch

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#1045]
For bugs, please fill out the three following sections completely

### Expected behavior
As a window user After removing api.use("oauth-encryption") from package.js both in accounts and core RC package, should be able to build app. (i do this as installing Open ssl and Visual C++ distro is too comburesome and never worked for me)
### Actual Behavior
start up process failing with below message
 ****Error: The operating system cannot run %1.

 C:\Users\hrathore\AppData\Local\.meteor\packages\npm-node-aes-gcm\0.1.3_6\npm\node_modules\node-aes-gcm\bu**

     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:312:12)
     at Module.require (module.js:364:17)
     at require (module.js:380:17)
     at Object.Npm.require (D:\rcesmodules\reaction2\.meteor\local\build\programs\server\boot.js:182:18)
     at Package (packages/npm-node-aes-gcm/packages/npm-node-aes-gcm.js:10:1)
     at Package (packages/npm-node-aes-gcm/packages/npm-node-aes-gcm.js:25:1)
     at packages/npm-node-aes-gcm/packages/npm-node-aes-gcm.js:25:1
     at packages/npm-node-aes-gcm/packages/npm-node-aes-gcm.js:25:1
     at D:\rcesmodules\reaction2\.meteor\local\build\programs\server\boot.js:283:10
     at Array.forEach (native)**
### Steps to Reproduce the Behavior
On dev branch it is all working fine as it removes and add whenever a change is made in package.js file. On module-structure branch on fresh clone and meteor npm install and meteor --settings settings/set.json gives this error message.

Not sure which import is causing this.  If it is Meteor issue then it should manifest on dev  branch as well.

**Comment by jshimko** [comment]
The `module-structure` branch is definitely not ready for public consumption at this point.  It's in the middle of a major refactor right now.  It's coming together very quickly, but we need a couple more weeks before anyone should expect it to work.  More importantly, it's going to be significantly different after we rebase the development branch into it and restructure some things, so nobody should get too comfortable with the current folder/file structure until that stuff settles down.

So feel free to poke around in the branch, but it's unlikely to work for you right now and we won't be working on any issues for it until it's actually ready for testing.  For now, the official recommendation is to stick with the `development` branch if you want to run the latest code.

**Comment by hrath2015** [comment]
Thanks for quick response.  I will wait till it is merged with Dev. Sorry for the trouble.

**Comment by jshimko** [comment]
No prob.  Thanks!
