### ISSUE TITLE
Example payment provider missing label for "default payment" drop down

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1049]
### Expected behavior
All payment methods in "default payment method" dropdown should have friendly labels.

### Actual Behavior
Label for "Example Payment Provider" says admin.dashboard.examplePaymentProviderLabel
<img width="472" alt="screenshot 2016-05-27 08 59 32" src="https://cloud.githubusercontent.com/assets/72819/15594603/a7a72d7a-23e9-11e6-8454-f50f93c22d35.png">

(also, should this option only allow enabled methods?)

### Steps to Reproduce the Behavior
With the Example Payment Provider enabled go to Default Payment Provider in the dashboard, observe the mislabeled option.

**Comment by aaronjudd** [comment]
@brent - sorry I was already in there..
