### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#105]
As a user and as a shop administrator, I want to be able to search for products by tag/keyword across the whole store.

**Comment by ScyDev** [comment]
This is ready? It's two years old and breaks with "Uncaught TypeError: ReactionCore.registerPackage is not a function".

**Comment by aaronjudd** [comment]
`ready` as in: "the issue is ready to be worked".... in our road map. The existing `reaction-search` package was probably won't work without some upgrades, and probably isn't really in line with how we are going to do it now.  We'll be adding into /reaction/packages by v0.13

**Comment by ramusus** [comment]
@ScyDev you may take a look https://github.com/ramusus/reaction-filtration/ it supports simple search by title and filtration functionality. You can integrate with current dev version, using this PR reactioncommerce#743

**Comment by aaronjudd** [comment]
Closing in favor of #903 and #277
