### ISSUE TITLE
"Import" button in dashboard does not work

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1050]
### Expected behavior

Import button should allow you to upload a file and import the data within An error should be shown if you try to upload an invalid file type.
### Actual Behavior

You can choose a file but when you click on the "Import" button nothing happens
### Steps to Reproduce the Behavior
1. Go Dashboard -> Core -> Import
2. Choose a file
3. Press the "Import" button
4. Observe that nothing seems to happen

**Comment by aaronjudd** [comment]
I'm not 100% sure what intended to happen, but clearly there should be some progress feedback..

**Comment by aaronjudd** [comment]
@tdecaluwe do we have an example import file that we can test with this?  I'd like to review and fix this for 0.15rc

**Comment by tdecaluwe** [comment]
This was a WIP, it should perhaps not have landed in an official release. It actually imports images, not JSON data. I think it matches the name of the image to a variant barcode to make the correct links. I know it worked like this "once upon a time" but with all the recent changes I'm not sure what would happen now.

**Comment by aaronjudd** [comment]
ok I think we should just remove it for now, and work on an image import and flat file/feed importer.

**Comment by tdecaluwe** [comment]
I completely agree. Or move the extra code to a separate branch.
