### ISSUE TITLE
More of  Confirmation of  changed Behavior of default admin creation flow

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#1055]
### Expected behavior
When Default Admin User is created Both objects ie  Roles.GLOBAL_GROUP and shopId  used to have complete entries(default roles+package name+registry+permissions)
### Actual Behavior
Now with latest release Roles.GLOBAL_GROUP  gets only 25 entries (4 default and 21 package name) 
### Steps to Reproduce the Behavior
From MongoDB check in user collections for default admin roles: **number of entries are not equaI**. if this is expected behavior will close issue if not will send a PR. As per me, Ideally global group should have everything enabled.
For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by aaronjudd** [comment]
I think this is the expected behaviour, GLOBAL_GROUP is just a default group for the initial admin/owner.  All other users should be using the shopID groups.
