### ISSUE TITLE
cannot start reaction

### ISSUE THREAD

**Issue by yigubigu** [reactioncommerce/reaction#1056]
I followed guidance from https://docs.reactioncommerce.com/reaction-docs/master/installation#reaction. 

BTW, I am running vagrant-ubuntu-trusty-64. 
### Expected behavior
When run ./reaction, the server is expected to be started. But exception is thrown. 

### Actual Behavior
vvagrant@vagrant-ubuntu-trusty-64:~/reaction$ ./reaction
Starting Reaction using '/home/vagrant/reaction/settings/dev.settings.json'.
[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected mongo exit code null. Restarting.

/home/vagrant/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at Object.exports.spawn (child_process.js:746:9)
    at spawnMongod (/tools/runners/run-mongo.js:45:24)
    at launchOneMongoAndWaitForReadyForInitiate (/tools/runners/run-mongo.js:468:12)
    at launchMongo (/tools/runners/run-mongo.js:682:7)
    at MongoRunner._startOrRestart (/tools/runners/run-mongo.js:789:19)
    at [object Object].<anonymous> (/tools/runners/run-mongo.js:857:14)
    at runWithEnvironment (/tools/utils/fiber-helpers.js:112:21)
vagrant@vagrant-ubuntu-trusty-64:~/reaction$ mongo
MongoDB shell version: 2.4.9
connecting to: test
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
> exit

### Steps to Reproduce the Behavior
curl https://install.meteor.com | /bin/sh
git clone https://github.com/reactioncommerce/reaction.git
cd reaction
reaction pull
reaction

**Comment by jshimko** [comment]
Thanks for the report.  I can confirm that Mongo errors sometimes happen on Ubuntu Trusty.  However, I get a different error with a little more info...
```sh
./reaction

Starting Reaction using '/reaction/settings/dev.settings.json'.
[[[[[ /reaction ]]]]]

=> Started proxy.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Can't start Mongo server.
MongoDB failed global initialization

Looks like MongoDB doesn't understand your locale settings. See
https://github.com/meteor/meteor/issues/4019 for more details.
```
If you go read [the Meteor issue it mentions](https://github.com/meteor/meteor/issues/4019), there are several recommendations for fixing the locale issue.  The one that worked for me was running this command:
```sh
locale-gen en_US.UTF-8
```
Once I did that, the app started right up with `./reaction`.  

[More info on locale-gen on Ubuntu](https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu).  Let me know if that does the trick for you.

**Comment by yigubigu** [comment]
thanks a lot, it works now
