### ISSUE TITLE
navbar tags stay in editing mode

### ISSUE THREAD

**Issue by ahaghdan** [reactioncommerce/reaction#1057]
I think I have a found a potential bug with toggle editing mode.

### Expected behavior
Signing in as administrator and toggling editing mode, one can edit the tags in the navbar. If you in this mode decide to sign out and forget to toggle off editing mode, the shopping cart should automatically disable editing mode.
 
### Actual Behavior
If you sign in and toggle editing mode, then logout immediately, the navbar tags stay in editing mode, even when guests view the site.

### Steps to Reproduce the Behavior

1. Sign in as admin
2. Toggle Editing Mode
3. Add or remove some navbar tags (but leave at least one tag).
4. Leave the Toggle Editing Mode On and Sign out 
5. Navbar tags are still in editing mode and shown as such for customers/guests.

**Comment by aaronjudd** [comment]
This appears to now be resolved in development.  Most likely by #1122 as the Router is reloaded.

**Comment by Capt-Slow** [comment]
Verified this no longer occurs in development.
