### ISSUE TITLE
eMails not styled for GMail / Outlook

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#1059]

**Comment by prinzdezibel** [comment]
All eMail templates should be piped through CSS Inliner, because clients like GMail and Outlook do strip out `<style>` tags.

http://foundation.zurb.com/emails/inliner.html

When inlining the styles, they are displayed correctly in GMail.

**Comment by spencern** [comment]
We've had to do this as well and it fixed our gmail/outlook problems.

**Comment by zenweasel** [comment]
Should happen as part of #1429

**Comment by zenweasel** [comment]
Will be done as part of #1429
