### ISSUE TITLE
Getting error and no HTML output when using `spiderable` packages

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1063]
### Expected behavior
Spiderable should render HTML for the site
### Actual Behavior
Receive this error at the console when doing `curl http://localhost:3000/?_escaped_fragment_=`

```
spiderable: phantomjs failed at http://localhost:3000/: null
stderr:
stdout:
```

### Steps to Reproduce the Behavior

1. Clone reaction
2. Uncomment the `spiderable` package in .meteor/packages
3. Visit http://localhost:3000/?_escaped_fragment_= in the browser or do `curl http://localhost:3000/?_escaped_fragment_=`
4. See the error in the console.

Tried with both `ongoworks:spiderable` and `spiderable` with the same result

**Comment by aaronjudd** [comment]
It's been a long time since I updated https://github.com/ongoworks/spiderable and it's not been tested with a recent version of Reaction but I think it's still in pretty wide usage so I'd expect to see some issues reported if this wasn't a Reaction specific issue.  Related, I think is https://forums.meteor.com/t/server-error-from-ongoworks-spiderable/24417 (although I suspect that's being used with an older version of Reaction (or some other project)).  

There's good debugging info here http://www.meteorpedia.com/read/spiderable but I suspect we'll need to dig into spiderable.

**Comment by zenweasel** [comment]
I swear that I just helped some people get this working and it was working locally for me then so I am confused as to why it's not working now. The issue is sort of just a placeholder till I can revisit and get some more/better info

**Comment by aaronjudd** [comment]
Should note, that ongoworks:spiderable is meant to work with Docker and port mapping.  I don't remember if it worked locally, or only in the production environment but spiderable should work locally.

**Comment by aaronjudd** [comment]
@jshimko we need to verify this is still working, probably update ongoworks:spiderable and ensure that this is including in our docker builds for launchdock.

**Comment by zenweasel** [comment]
Comment from @aaronjudd from Slack conversation:
"just installed phantomjs  + spiderable, and it’s working for me.  sort of. our router is trying to use the `?_escaped_fragment_=` as part of our route.. so we need to fix our routes to ignore that…
but I am getting source.."

**Comment by aaronjudd** [comment]
Testing with `ongoworks:spiderable`, seems to be working without issue for me:

![view-source_localhost_3000_reaction_product_example-product__escaped_fragment___and_example-product_and_1__reaction_reset____reaction__node_](https://cloud.githubusercontent.com/assets/439959/17422421/baff1abe-5a66-11e6-96bb-c8451027518d.png)

**Comment by aaronjudd** [comment]
I say we close this, as it does seem to be working now, and moving forward we can focus on #1249

**Comment by zenweasel** [comment]
Closed, can't reproduce
