### ISSUE TITLE
MONGO_URL not working as expected

### ISSUE THREAD

**Issue by PolGuixe** [reactioncommerce/reaction#1068]
I have set up an external mongoDB in `settings/settings.json`, however when I run `./reaction` the meteor still uses the default local DB. 

Is this behaviour normal?

**Comment by jshimko** [comment]
I don't see it being used anywhere in the app, so that may be leftover from old functionality.  You can just run this instead:

```sh
MONGO_URL=mongodb://your-url meteor
```

**Comment by jshimko** [comment]
Or...

```sh
MONGO_URL=mongodb://your-url ./reaction
```

**Comment by zenweasel** [comment]
We probably need to update the documentation then? https://docs.reactioncommerce.com/reaction-docs/master/configuration
