### ISSUE TITLE
Theme less variables override

### ISSUE THREAD

**Issue by PolGuixe** [reactioncommerce/reaction#1070]
Following the Guide in the [docs](https://docs.reactioncommerce.com/reaction-docs/master/tutorial#adding-custom-css). Trying to override `less variables`, from the `core-theme`, doesn't work, as in some cases they get overridden again by other packages e.g. [reaction-ui](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-ui/client/styles/variables.less)

**Comment by aaronjudd** [comment]
Should be fixed in `development` as we've rewritten this.  However, we still need to validate before closing this issue. (and update docs if needed)

**Comment by kieckhafer** [comment]
I was able to validate that this is fixed. I was able to change colors to over-ride the defaults by following the instructions in the docs (with minor changes to the docs) ![screen shot 2016-07-13 at 4 35 16 pm](https://cloud.githubusercontent.com/assets/4482263/16823289/d374ca72-4917-11e6-8961-6926477a5520.png)
