### ISSUE TITLE
Should not be able to create multiple tags with same slug

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#1072]
For bugs, please fill out the three following sections completely
### Expected behavior

Case should behave consistently tags / hashtags. Case should either be respected (`Camping` is a different tag than `camping` is different than `CAMPING`) or should be normalized (`Camping` is the same tag as `camping`).
### Actual Behavior

If I create an uppercase tag called `Camping` and then add a lowercase tag `camping` both tags are created and both have a slug `camping` but visiting `/tag/camping` only filters products connected to the first `camping` tag by ID.
### Steps to Reproduce the Behavior

Add a few products to project. Add a capitalized tag to Product A, add lowercase tag to Product B. Visit `/tag` route.

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by aaronjudd** [comment]
We need to validate against the slug, not the name.. the slug is lowercased automatically.

**Comment by zenweasel** [comment]
Fixed via #1247
