### ISSUE TITLE
Firefox kill my CPU server!

### ISSUE THREAD

**Issue by jujes** [reactioncommerce/reaction#1073]
Someone know why Firefox kill my cpu server? here a video using **htop**

### Expected behavior

**Opera && Chrome performance**

### Actual Behavior

**_Firefox 46.01_**
**CPU 100% node ./main.js**

### Here the link video to Reproduce the Behavior

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/bQ3pQlF1R8w/0.jpg)](http://www.youtube.com/watch?v=bQ3pQlF1R8w)

**Comment by jshimko** [comment]
Are there any errors in the browser console?  This happens from a fresh clone of the development branch?

**Comment by jshimko** [comment]
Also, what OS are you using?

**Comment by jshimko** [comment]
I'm going to assume this is all set and close the issue for now.  If you continue to have the issue and have any more detail you can share with us, feel free to reopen this issue and post your details.
