### ISSUE TITLE
Some fix suggestions on Module refactor Rebase branch

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#1079]
@jshimko  I know "**Module refactor Rebase**" is not available  for consumption.  Still I was playing with it  would like to share my observation which u can incorporate in next  change.

1.  Need to bring back the check similar to v.13 as below in **lib\collections\helpers.js** file.  It is causing error "can not read rate " .  In **cartTotal()** method, 
``let shippingTotal = 0;
    if (this.shipping && typeof this.shipping[0].shipmentMethod === "object") {
      shippingTotal = getSummary(this.shipping, ["shipmentMethod", "rate"]);
    }``
 **Replace cartShipping() method as** 
``cartShipping() {
    // loop through the cart.shipping, sum shipments.
    if (this.shipping && typeof this.shipping[0].shipmentMethod === "object"){
       return parseFloat(getSummary(this.shipping, ["shipmentMethod", "rate"]));
   }
   return 0;
  }``

2.Import  ``import { _ } from "underscore"`` in client\modules\checkout\templates\cart\cartDrawer\cartItems\cartItems.js 

thanks

**Comment by aaronjudd** [comment]
@hrath2015 I think the cartTotal check is fixed in my `paypal-import` branch, and also updated all the _ underscore imports.

**Comment by hrath2015** [comment]
thanks. Closing it
