### ISSUE TITLE
Users with dashboard but not owner permissions are listed as Guests

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#1083]
For bugs, please fill out the three following sections completely

### Expected behavior
Users with dashboard permissions should appear in the `Shop Members` section of the accounts dashboard.

### Actual Behavior
Users with dashboard permissions appear in the `Guest` section of the accounts dashboard.

### Steps to Reproduce the Behavior
Create a user with dashboard permissions but not owner or admin permissions. User remains in the Guest section of the accounts dashboard.

**Comment by aaronjudd** [comment]
I see what you did.. and makes sense.. 

from a conversation about this elsewhere:

`/dashboard/accounts should not be publishing all accounts, rather only accounts that have been invited to be admins. if you are not an admin, you are only getting one record returned in the publication. I believe that we had decided it should return all guests, but not anonymous users, - I’m guessing that only got implemented in the client?…. seems like it should be added to admin queries...`

**Comment by spencern** [comment]
I won't disagree with that line of thought.

If that's the direction, then there needs to be a process to promote a user to admin/invite a user to be an admin (either existing users, or new via Email)

Currently the `dashboard` permission is effectively the admin flag for our admins, and we limit their role based on packages/routes that we turn on and off. Before this fix, it felt pretty accidental that only `owners` showed up in the accounts list (especially when looking at the code for it).
