### ISSUE TITLE
Analytics package should track pageviews and ecommerce metrics

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#1092]
Working on a big improvement to the analytics package that will track all pageviews (a la okgrow:analytics) out of the box as well tracking ecommerce events. Also it will fix a few bugs causing the analytics package not to work at all.
- [x] Pageview Tracking
- [x] Ecommerce Events
- [ ] Identify events for people tracking in Mixpanel
- [ ] Refactor to module structure

**Comment by rymorgan** [comment]
Related to #1846

**Comment by zenweasel** [comment]
Closing in favor of: https://github.com/reactioncommerce/reaction/issues/2301
