### ISSUE TITLE
Why demo has been turned off?

### ISSUE THREAD

**Issue by perpi** [reactioncommerce/reaction#1104]
Is the [demo](http://demo.reactioncommerce.com/) no longer available? It was helpful;

**Comment by aaronjudd** [comment]
@perpi agree.  we're working on getting demo stores back online. we've been sidetracked by the major refactors needed to keep up with Meteor 1.3-1.4, but are just wrapping up our 0.14 release.  We'll have the demo and trials shops back online with our 0.15 release.  In the meantime..  we're hoping the install process is easy enough to do local demos.
