### ISSUE TITLE
Add "Statement Descriptor" as a configurable option to Stripe

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1116]
Migrating this issue from Stripe repo.

Stripe allows you to customize what show's up on the Customer's credit card statement by passing in the "statement_descriptor" field. Seems like this should be a customizable option.

**Comment by zenweasel** [comment]
@spencern I saw this as a way to control what appears on a customer CC statement in a marketplace scenario. Is that handled in Stripe Connect?

**Comment by spencern** [comment]
@zenweasel Stripe connect permits the use of Statement Descriptors

**Comment by spencern** [comment]
For non Stripe Connect users, Stripe does support per-charge statement descriptors, but users can also set their Statement Descriptor in their Shop Settings from within the Stripe.com web interface

**Comment by zenweasel** [comment]
Closing as this is a feature that no one cares about.
