### ISSUE TITLE
logout and login inline page behavior

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1122]
For bugs, please fill out the three following sections completely

### Expected behavior

Whenever a user logs out, we should redirect to the home page.
A login box should display and message should display when a user access a url they are not authorized to access.
When a login box is displayed inline, a user should be able to login on first try.
When a user logins the correct page should display, not the login.

### Actual Behavior

The user is shown a `Oops! You don't have permission to view this content.` and a login box.

The login does not appear to work on the first try, but subsequent attempts do.

Once you login the page displayed is still the login, although admin menu bars etc display.

### Steps to Reproduce the Behavior

A) Login in as admin view dashboard, log out.
B)  go to: 
`http://localhost:3000/reaction/dashboard`
and login.

**Comment by aaronjudd** [comment]
Actually this might be a bit of a bigger issue.  When you logout, you are redirected to the home page, but shown a login page, where you obviously should have access (as everyone does to the home page).

**Comment by aaronjudd** [comment]
Not a blocker for 0.14, I'm going to work some more on this after release 0.14

**Comment by Capt-Slow** [comment]
Verified this is reproducible in development.

**Comment by Capt-Slow** [comment]
Verified this has been fixed in development.
