### ISSUE TITLE
"cart/checkout" from server with specified userId

### ISSUE THREAD

**Issue by prafulc** [reactioncommerce/reaction#1125]
I am creating a payment gateway for fastspring. Fastspring doesn't redirect after payment completion instead it sends a callback to server with post data. Now I have all the data from server but I am unable to call method "cart/checkout" because I am on server side and it is using Meteor.userId() for getting userId. I have tried to login via helper but nothing work there. Any help

**Comment by zenweasel** [comment]
@prafulc Take a look at https://github.com/reactioncommerce/reaction-stripe. The Stripe calls are all server side. That should help guide you in how to create a server-side payment method. If you need more help, please feel free to ask in our Gitter channel [here](https://gitter.im/reactioncommerce/reaction)
