### ISSUE TITLE
PaypalExpress checkout: After returning, the complete app is reloaded

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#1132]
Which is not good as it
-  takes long
- wipes the whole client session (e.g. chosen language and other keys)

Branch: Devlopment

**Comment by zenweasel** [comment]
Testing this now it doesn't take very long at all but it does refresh the page when it goes to the `/done`. Not sure how that can be avoided since it's a redirect from another site. But agreed that we shouldn't be losing Session status.

**Comment by zenweasel** [comment]
Testing this now with version 1.1.0 I am not seeing this losing session status. Closing.
