### ISSUE TITLE
Increase build stability

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#114]
In the [installation docs](https://github.com/ongoworks/reaction-core/blob/master/docs/installation.md), there are two places where it says to do `mrt update`. As the project becomes more stable and is used by more people, I think it would be good to begin committing the `smart.lock` file to the reaction repo, and change the installation instructions to `mrt install` rather than `mrt update`.

This prevents the scenario where things seem to be working stably during development, but then someone pulls the repo and runs `mrt update` and nothing is working because they received a brand new version of one of the dependencies, which reaction code has not yet been updated for. By doing `mrt install` instead, only the specific versions listed in the `smart.lock` file are pulled. One of the reaction devs can periodically run `mrt update`, make sure things still work, and then commit the updated `smart.lock` file.

Eventually this will be the norm, once the new packaging system is released, but it would be good in the meantime, too.

**Comment by aaronjudd** [comment]
@aldeed I think we're good here now, but I'd appreciate another review and your thoughts but I'm closing this.  I might just have gotten used to stuff.. it happens. If you think we need to take another pass, please reopen.

**Comment by aldeed** [comment]
Agree this is resolved.
