### ISSUE TITLE
Capture not working for Payflow Pro

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1146]
For bugs, please fill out the three following sections completely

### Expected behavior
When you click on the "Capture" button after approving an order the dashboard totals should change to reflect the captured amount and the refund button should appear.

### Actual Behavior
Errors in the server console and the "Approve" button reappears.

### Steps to Reproduce the Behavior
1. Place an order using Payflow Pro
2. Go to the Admin panel
3. Select the order and view details
4. Click "Approve" and then "Capture". 
5. Observe the server logs.

**Comment by aaronjudd** [comment]
I think this might have actually been what I meant to describe in #1100 - but the problem is only in payflow pro as far as I can see.

**Comment by zenweasel** [comment]
so something definitely changed a long the way because the code as it is now would never work. As far as I can tell and according to the docs [here](https://developer.paypal.com/docs/integration/direct/capture-payment/). You can create an authorization by creating a `payment` with the `intent` set to “authorize” and that should include a document with an “authorization” id (which is not the same as the transactionID which is what the current code tries to use, so it makes sense that I get a 404).

So all well and good, just change the code to use this (new?) id. Except even when setting the intent, I never get a response with an authorization ID.  I tried it with Python as well just to see if it was an error in the SDK and the same thing happens.

I notice there were some changes around refund that also reference authorizationID so wanted to see if there was any info there

**Comment by aaronjudd** [comment]
Yes, I reached the same conclusion and didn't have time to fix it before my travels.. Hence the issue.

**Comment by zenweasel** [comment]
Opened issue on Node SDK https://github.com/paypal/PayPal-node-SDK/issues/168

**Comment by zenweasel** [comment]
Also opened this as well https://github.com/paypal/PayPal-Python-SDK/issues/143 since it doesn't seem to work in Python either which threw me off.

**Comment by aaronjudd** [comment]
👍  looks good to me, refunds passing now.

**Comment by kieckhafer** [comment]
👍  was able to refund my order with no errors, looks good
