### ISSUE TITLE
Should not be able to discount an amount greater than order.

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1149]
### Expected behavior
UI and methods should not allow a discounts amount that is greater than the order, or a previously created approval.

### Actual Behavior
Admin is permitting values larger than the order to be entered into the discounts input and applied.
No error is shown.

### Steps to Reproduce the Behavior

Create an order, sign in as admin, apply an larger than order discounts value and apply.

**Comment by aaronjudd** [comment]
![orders](https://cloud.githubusercontent.com/assets/439959/16779793/93036e98-4828-11e6-8df2-43daf04ebca1.png)

**Comment by zenweasel** [comment]
That screenshot doesn't reflect a refund but a discount because that's not how refunds show up in the dashboard.

The UI does allow an amount greater than the order though, and it didn't used to.

**Comment by aaronjudd** [comment]
I don't think we're referring to the refund here, but the discount that was applied. Perhaps I should have capture the screen before this as well.

**Comment by kieckhafer** [comment]
What do we want the upper limit to be for discounts to be? I think the options are:

Sub-total
Sub-total + shipping
Sub-total + taxes
Sub-total + shipping + taxes (total amount)

**Comment by zenweasel** [comment]
Are we talking refunds or discounts? Those are really two different sets of business rules. 

But for discounts we want the customer to be able to discount the order completely in cases of a replacement order. I can see some people wanting to put more fine-grained permissions around this but for now an admin should be able to do this.

Refunds of course are always upper bound by the amount captured.

**Comment by kieckhafer** [comment]
Talking discounts here, that seems to be where this error / ticket is. I'll make sure refunds aren't affected, but testing them earlier it seemed Discounts were the ones allowing any amount, refund was capped at the total price (although error / info messaging around that will need to be updated, the refund silently adjusted to the full price when I did anything over full price.)

I'll go ahead and make the discount reference Total price. (Sub-total + shipping + taxes).

**Comment by zenweasel** [comment]
Refunds also allow (wrongly) this. I can attempt a refund more than the total captured price. (I know this because I used this quirk to test the error handling for Stripe). But we shouldn't be allowing this on the front-end and it didn't in the past.

**Comment by kieckhafer** [comment]
OK, I'll do some more testing with refunds and fix that as well.

**Comment by aaronjudd** [comment]
See #1148 regarding refunds.
