### ISSUE TITLE
nsp audit fails for authorize.net module

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1151]
Authorize.net module has an unpatched vulnerability.  We should report, patch and submit to https://www.npmjs.com/package/authorize-net

### Expected behavior
```
npm install nsp --global
nsp check  
```
Should not return any vulnerabilities.

### Actual Behavior

`nsp check` returns **1 vulnerabilities found** 
https://nodesecurity.io/advisories/77
![1__aaronjudd_asj-mbp-4____ongoworks_reaction__zsh_](https://cloud.githubusercontent.com/assets/439959/16812469/158f3572-48e2-11e6-8175-220120c77438.png)

### Steps to Reproduce the Behavior
Run nsp check.

**Comment by zenweasel** [comment]
Filed PR with authorize.net package
https://github.com/continuous-software/node-authorize-net/pull/18

**Comment by zenweasel** [comment]
Verified vulnerability removed via `nsp check`. Closing.

**Comment by aaronjudd** [comment]
Re-opening.  tough-cookie warnings still appear, and @zenweasel says #1214 is unrelated...

**Comment by zenweasel** [comment]
Where is the tough-cookie warning in this ticket? The PR resolves the vulnerability identified by `nsp`.

**Comment by jshimko** [comment]
Looks like we need to update the `request` dep in authorize to [2.74.0](https://github.com/request/request/commits/master/package.json).

Note that `snyk` sometimes returns vulnerabilities that `nsp` doesn't (and sometimes vice versa).

```sh
$ snyk test

✗ High severity vulnerability found on tough-cookie@2.2.2
- desc: ReDoS via long string of semicolons
- info: https://snyk.io/vuln/npm:tough-cookie:20160722
- from: reaction@0.14.2 > authorize-net@1.0.6 > request@2.73.0 > tough-cookie@2.2.2
```

**Comment by zenweasel** [comment]
Assigning to @jshimko per Slack conversation:

aaronjudd [7:31 AM]  
`reaction@0.14.2 > authorize-net@1.0.6 > request@2.73.0 > tough-cookie@2.2.2`

[7:31]  
just gave @jeremy access to that repo, I think he’s grabbing this..

[7:31]  
started with a conversation with him...

**Comment by zenweasel** [comment]
@jshimko Updated to 2.74, confirmed message is no longer there in `development`. Closing.
