### ISSUE TITLE
Add .gitignore entry for imports/plugins/custom

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1171]
All files in this directory should be ignored.

**Comment by jshimko** [comment]
What if people want to commit their custom stuff to their own branch?  (probably most people)  Forcing the use of `!/imports/plugins/custom/my-plugin` in another gitignore file doesn't feel ideal.  That requires manual `git add`'s for every new file.  That was often painful when we had that in the packages dir.

Core will never commit to that folder, so do we definitely need to ignore it?

**Comment by aaronjudd** [comment]
@jshimko agree - the point of the custom folders is that WE will never touch them...

**Comment by mikemurray** [comment]
Do you mean and entire copy of `reaction` or just their custom plugin?

If its just their plugin, then they can just "cd imports/plugins/custom/my-plugin" and the .gitignore will not apply.

They can open the folder of their custom plugin in Atom, Sublime, or <insert-favorite-editor> alongside and edit it separately from the reaction app itself.

They could also remove the .gitignore file from their custom branch if they wanted to have all of reaction and their custom plugins committed.

**Comment by aaronjudd** [comment]
.gitkeep is just a convention, not an official thing at all anyways. and yes, we want to ignore all the contents from our own commits, and I think .gitignore is needed for this isn't it?

**Comment by aaronjudd** [comment]
Closed and released in 0.14.0
