### ISSUE TITLE
Product detail page editing workflow improvements

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1178]
Simple publishing workflow for products and variants.

Goals:
- [ ] Allow the admin users to edit a product without having changes showing up immediately for all users.
- [ ] Save any changes to a product as a draft revision in the `Revisions` Collection.
- [ ] Use a "Publish Changes" button to publish all draft changes to a product and all variants with a draft.

**Comment by aaronjudd** [comment]
Here's some remaining items we need to discuss on this:

- confirmation color (green) on auto save
- collapse inactive sections of the product edit control
- image revision control 
- remove blank arrays in "Show Changes"
- ensure publish changes publishes all / updates icons
- RevisionArchive - after publishing move revisions to archive
- Begin/End revision publishing
- Capture user during revisions
- migration strategy 
- docs

**Comment by mikemurray** [comment]
To help with migration, I added the ability to enable / disable revision control.
