### ISSUE TITLE
Add admin mode toggle

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#119]
It would be nice for an admin to be able to quickly toggle between "admin mode" and "normal mode" to see definitively what the shopper will see.

I get that this request goes against the idea behind the inline editing approach. I think I want it primarily because I'm paranoid from years of using bad software, where what you see is never what you get. The ability to sneak a peak at the "true view" allows the admin to relieve stress, when the admin is like me and always assumes he did something wrong.

**Comment by aaronjudd** [comment]
I believe this is resolved with the new "console" mode.

**Comment by aaronjudd** [comment]
We've been discussing adding a toggle that shows "admin view" or "user view".  I'm thinking the easy way to manage this might be to add a new role "admin-view"  that the  "admin" (or owner) roles can toggle (literally add /remove role).  the admin-view role can control permissions to the editable view items,  and should be reactive.  I'm thinking that we  can just repurpose 'hasAdminAccess'  and to use the different role.
