### ISSUE TITLE
Add "loading installation" message to install process

### ISSUE THREAD

**Issue by markoshust** [reactioncommerce/reaction#1192]
I tried both this installation method:
https://docs.reactioncommerce.com/reaction-docs/development/installation

and this method:
https://github.com/reactioncommerce/reaction#installation

Running both installation processes leads to the same resolution. It appears the installation has completed, however when executing `reaction` afterwards, I receive the following:

```
Marks-MacBook-Air:newecom markshust$ reaction

Using settings file at settings/dev.settings.json

[[[[[ ~/Sites/newecom ]]]]]

=> Started proxy.
=> Started MongoDB.
```

It appears to just hang at this point. Trying to access the site at http://localhost:3000/ doesn't bring up reaction, it just times out.

**Comment by markoshust** [comment]
Ahg! Moments after posting this, I saw the installation complete:

```
I20160722-15:32:48.543(-4)? 19:32:48.371Z  INFO Reaction: Client import found for checkout
I20160722-15:32:48.723(-4)? 19:32:48.373Z  INFO Reaction: Server import found for checkout
I20160722-15:32:48.724(-4)? 19:32:48.373Z  INFO Reaction: Registry file found for checkout
I20160722-15:32:48.724(-4)? 19:32:48.374Z  INFO Reaction: Client import found for dashboard
I20160722-15:32:48.725(-4)? 19:32:48.374Z  INFO Reaction: Registry file found for dashboard
I20160722-15:32:48.725(-4)? 19:32:48.375Z  INFO Reaction: Client import found for layout
I20160722-15:32:48.725(-4)? 19:32:48.375Z  INFO Reaction: Server import found for layout
I20160722-15:32:48.726(-4)? 19:32:48.375Z  INFO Reaction: Registry file found for layout
...
```

There should really be a "loading installation..." message or etc after the "Started MongoDB" message. This will probably irritate a lot of new time users.

I've updated this ticket name to reflect this.

**Comment by zenweasel** [comment]
@markoshust  Hi Mark, that part of the process is where Meteor is starting and basically we have no control over what happens there. It's important to remember that Meteor is a build tool as well so it does take some time to process files.

**Comment by AllenBird** [comment]
@zenweasel Hi, I found Meteor is so slow when I edit code. If there any fast way for developing?
