### ISSUE TITLE
Initial login after installation doesn't redirect user to dashboard

### ISSUE THREAD

**Issue by markoshust** [reactioncommerce/reaction#1193]
For bugs, please fill out the three following sections completely

### Expected behavior
- Install Reaction
- Login box opens
- Logging into login box redirects user to http://localhost:3000/reaction/dashboard

### Actual Behavior
- Install Reaction
- Login box opens
- Logging into login box shows right sidebar, doesn't redirect user
- Appears as though login didn't work
- Refreshing page confirms user is logged in

### Steps to Reproduce the Behavior
- Install Reaction
- Login using provided credentials

**Comment by zenweasel** [comment]
@markoshust Hey Mark. That behavior is actually "as designed". Most of product editing and admin is not done within the dashboard but in the product list and details screens which is why we don't redirect to the dashboard. The display of the admin sidebar shows you that you are logged in.
