### ISSUE TITLE
Make sending email async

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1200]
In several places (most notably at order completion) the application fully blocks on sending email. This makes the app appear to stall. (also when marking an order shipped)

Sending of email should be moved into job so that it can be properly retried if there is an actual failure and proper logs are sent.

We have talked about this a couple of times just creating this ticket this so it might get worked on as part of the RC 16 email goals.

**Comment by aaronjudd** [comment]
Resolved by #1282
