### ISSUE TITLE
"This page was not found" Error on first visit

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1201]
For bugs, please fill out the three following sections completely

### Actual Behavior
I am running the recent version 0.14 with the beesknees customization. After loging any first page visit shows error message "This page was not found" , immediately second visit works fine. This is consistent with all page visits I checked.
### Steps to Reproduce the Behavior
Login and click on Product page .

**Comment by zenweasel** [comment]
If this error only happens with the `beesknees` plugin, can you please open this issue against that repository since it's not an issue with Reaction?

**Comment by 3Maestros** [comment]
Not a reaction issue will open a separate bug against beesknees repo.
