### ISSUE TITLE
resolve tough-cookie warning

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1214]
resolve warning in 0.14.1 development, seen when running `reaction reset && reaction`

```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

a number of security warnings are related: https://snyk.io/test/github/reactioncommerce/reaction/963dbe9bcd462282382ca6e1ee243cf63035b4e7?fromStatus=true

**Comment by jshimko** [comment]
This is because of a dependency on `request` in `node-loggly`.  I've submitted a PR to `node-loggly` that updates the patched version.  Hopefully is gets merged soon...

https://github.com/winstonjs/node-loggly/pull/60

**Comment by aaronjudd** [comment]
I think we should fork `winstonjs/node-loggly` -> doesn't seem to be any sense of security urgency there.  I'd like this in our 0.15

**Comment by jshimko** [comment]
Well, that's only part of the problem.  [`MauriceButler/bunyan-loggly`](https://github.com/MauriceButler/bunyan-loggly) is the other dependency in front of that that we were using.  (I started from the vulnerability source and was working backward).  However, that second one is just a small bunyan adaptor for loggly.  The [whole package is only 69 lines](https://github.com/MauriceButler/bunyan-loggly/blob/master/index.js), so I'm thinking maybe we fork `node-loggly` and copy the `bunyan-loggly` package.

**Comment by aaronjudd** [comment]
agreed, that make sense to me.

**Comment by aaronjudd** [comment]
should be resolved as we removed the bunyan-loggly dependency.  we can revisit if we decide to use loggly again.

**Comment by aaronjudd** [comment]
@zenweasel 
`"authorize-net": "github:ongoworks/node-authorize-net"` wasn't this supposed to take care of this issue?

**Comment by zenweasel** [comment]
No. Unrelated.

**Comment by zenweasel** [comment]
@jshimko Updated to 2.74, confirmed message is no longer there in `development`. Closing.
