### ISSUE TITLE
Upgrade to jquery-ui@1.12.0

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1215]
Upgrade to jquery-ui@1.12.0 to resolve security warnings.

This will also require some updates to ui implementation as the npm package structure has changed. 

In scope would be refactoring and importing only the actual UI methods required.

Pay particular attention to easing errors in the console when testing checkout, order fulfillment.

See: https://snyk.io/test/github/reactioncommerce/reaction/963dbe9bcd462282382ca6e1ee243cf63035b4e7?fromStatus=true

**Comment by aaronjudd** [comment]
@jshimko here you go.

**Comment by jshimko** [comment]
Thanks?  ;)

**Comment by aaronjudd** [comment]
I'm happy to take it.. should be quick and fun

**Comment by mikemurray** [comment]
This might not need to happen since I plan on updating the product detail page, and move/update more of the editing functionality to the sidebar. And also update to sortable.js and some react based auto complete instead.

**Comment by jshimko** [comment]
Fixed in #1310
