### ISSUE TITLE
Replace or maintain CollectionFS

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1221]
Goal is to evaluate alternate file uploading packages, or write our own, or take over maintenance of CollectionFS.

Reason is that support for CollectionFS has stopped and the project has been deprecated. 

Current with Meteor 1.4 the inclusion of CFS is producing an error:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
 (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
```

This is identified in the Meteor issue https://github.com/meteor/meteor/issues/7477

The package needs to support:
- MongoDB blob storage
- Alternate, configurable CDN storage. AWS S3 is the minimum requirement.
- Transforms for variety of configurable sized upon upload
- Video
- All image formats
- Metadata storage with images
- multiple file uploads
- import from file system (probably through Reaction.import)

Tasks involve replacement, then updating the image gallery uploader and template image helpers.

**Comment by zenweasel** [comment]
In terms of possible replacements I am putting this here because I keep forgetting it. Suggested by @newsiberian: https://github.com/VeliovGroup/Meteor-Files

**Comment by aaronjudd** [comment]
Here's another Meteor package:  [UploadFS](https://github.com/jalik/jalik-ufs).  I'm only adding because I stumbled across it in a Meteor forum thread. Doesn't seem as mature as Meteor-Files

**Comment by spencern** [comment]
If we build our own solution based on npm packages there doesn't seem to be anything that does both of these things well out of the box.

We could consider using something such as https://www.npmjs.com/package/gridfs-stream (or  https://www.npmjs.com/package/gridfs-locking-stream if we need to support locking) to get started with GridFS support and then using an npm S3 lib (maybe https://github.com/andrewrk/node-s3-client) to support AWS S3.

Would be more work than dropping in another meteor lib, but might be more sustainable in the long run.

**Comment by spencern** [comment]
It looks like the core of https://github.com/CollectionFS has been merged back into a single repo and the individual meteor packages that we are currently using are "deprecated" - though it doesn't appear that the single core package has had any additional work done.

**Comment by aldeed** [comment]
Note to self: Also remove `raix:ui-dropped-event` (the custom "dropped" event) as part of this

**Comment by aldeed** [comment]
Will remove the `Media` collection hooks as part of this, too
