### ISSUE TITLE
"Double discount" being applied when Stripe is the payment provider

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1233]
### Expected behavior

When an order is authorized with Stripe, and a discount is applied to the order, we should apply that discount one time on payment capture.

### Actual Behavior

When an order is authorized using Stripe, if a discount is given before the order is captured, it is being applied a second time, as a "Refund", once the order is captured. From (Stipe's Documentation)[https://stripe.com/docs/api#capture_charge], it seems that this is due to stripe using the authorization as the basis for the charge, and instead of changing the amount that was authorized for the capture, they "refund" the difference - at least on paper that's how they present the data to us.

### Steps to Reproduce the Behavior

1) Use Stripe to purchase an item
2) Apply a discount to the order before Capturing the payment
3) Capture the payment
4) See that the discount is applied a second time as a "refund", and the "adjusted total" is actually the Total - (discount x 2), instead of Total - discount.

**Comment by aaronjudd** [comment]
Did we make any progress on this in? Move to 0.16 or is this a blocker?

**Comment by kieckhafer** [comment]
Discussed in chat, but just for documentation - very close to creating a PR on this, I expect it to be ready early in the day tomorrow.
