### ISSUE TITLE
Shipping (and other charges) should be broken out when sent to PayPal Express

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1236]
![screen shot 2016-08-02 at 3 59 50 pm](https://cloud.githubusercontent.com/assets/4482263/17348471/30963f84-58cb-11e6-8cf0-6913f36ee807.png)
### Expected behavior

When logging into the PayPal Express dashboard, you should see a broken down list of charges.
### Actual Behavior

There is one lump sum for the "item amount", and no breakdown of taxes, shipping, handling, etc.
### Steps to Reproduce the Behavior

Purchase a product with PayPal Express, and log in to the PayPal dashboard to view.

**Comment by kieckhafer** [comment]
@spencern @zenweasel is this something that will be taken care of by a marketplace issue?

**Comment by spencern** [comment]
Not that I'm aware of, this seems to be an issue directly with the paypal implementation.

**Comment by Akarshit** [comment]
Working on a PR for this, have made the code changes. 
Still need to test them because the PayPal credentials doesn't work for me and I can't get past the "Security Check" screen on the API creds generation page on PayPal.

**Comment by Akarshit** [comment]
Still not able to test this. PayPal docs are a nightmare.
Will get this done soon.

**Comment by Akarshit** [comment]
Paypal's site is broken on the part where I get password for the sandbox account. Waiting for that to be fixed.

**Comment by Akarshit** [comment]
PayPal is working today, so this should get done today.

**Comment by zenweasel** [comment]
Closed via #3859
