### ISSUE TITLE
Router does not always use overridden layout template and shows 404

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1239]
### Expected behavior

If you set `Session.set("DEFAULT_LAYOUT", "myDefaultLayout");` it should always use that record to review the layout record.
### Actual Behavior

Sometimes (quite often) on the first request it is searching for "coreLayout" causing the page to return a 404, if you refresh that page it then renders properly.
### Steps to Reproduce the Behavior

Check out the `reaction-example-plugin` repo into `imports/plugins/custom` and restart. Visit any page and you will (often) get a 404. YMMV as terms of how often you get it since it seems like a race-condition but it happens pretty regularly.

**Comment by mikemurray** [comment]
It may just be the speed of my machine, but I cannot get this to happen.
