### ISSUE TITLE
Add processing state feedback to order capture payment

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1243]
It would be nice if the "Capture Payment" button in the order fulfillment workflow gave some feedback ala loading indicator. In particular, PaypalExpress transactions take a bit to capture, and it's not obvious that we're waiting on a remote response (and the button is still enabled).

**Comment by zenweasel** [comment]
Same is sort of true for refunds. You view the order then look away and it's "Oh hai refunds"
