### ISSUE TITLE
First installation: Cannot find module bluebird

### ISSUE THREAD

**Issue by newdesignideas** [reactioncommerce/reaction#1256]
### Expected behavior

Smooth installation of Reaction Commerce according to the instructions given in the Docs.

### Actual Behavior

After **reaction init** we get  **Cannot find module 'bluebird'** .. - See the entire error at [http://imgur.com/a/ym7Ij](http://imgur.com/a/ym7Ij)  The error happens on **line 327 of module.js**

Tried on both a Droplet on Digital Ocean running Ubuntu and 2 machines running Windows.

### Steps to Reproduce the Behavior

Try to install ReactionCommerce on a Windows 64 machine or a blank Ubuntu installation. 

#### Notes:

- manually installing the bluebird module via npm does not fix the issue

**Comment by aaronjudd** [comment]
Can you provide the output of `reaction -v`?

**Comment by newdesignideas** [comment]
Hi Aaron,

sure thing. Thanks for gving a helping hand. On one of the Windows installations I am receiving the exact same bluebird error as output for `reaction-v` 

See the screenshot at [http://imgur.com/a/jkfzb](http://imgur.com/a/jkfzb)

**Comment by aaronjudd** [comment]
How about `npm -v` and `node -v`?    I just tested on an Ubuntu install and was unable to replicate..  perhaps you can rerun `npm i -g reaction-cli` and see if it was just a networking error? (maybe you already did..)

**Comment by jshimko** [comment]
Should be fixed.  Please `npm i -g reaction-cli` again and upgrade to 0.4.3.

**Comment by newdesignideas** [comment]
Thanks, it is fixed.
