### ISSUE TITLE
reaction deploy

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1257]
planning issue for v0.18+ reaction deployment tooling.

basic proposal:
## reaction-cli

```
reaction build --image <name>
reaction run --image  <name>
reaction deploy  --image <name>  [--settings settings.json] 
```

Follow the same format as Meteor run, build and deploy, change the default workflow to a Docker build and push flow.
### build workflow

Where you could have the option of building and testing the image locally, wrap up all the docker build commands into a `reaction build`, but perhaps map the current directory as the volume app source.

Check / install docker-toolbox.
pull a reaction dev image (nicely preconfiged)
build local app image, map volume.
### deploy workflow

Ideally a process where multiple version of sites can be deployed with a easy approval process.
- add source
- build image
- push to repo
  - private registry (LD)
  - docker hub
- deploy (launchdock)
  - launchdock cluster config
  - use existing live db, unless option
- approve (launchdock)
  -  change proxy to point to this cluster / version
  -  approve from Connect in Reaction
## webhooks

Ideally, I'd see the deploy functionality as both a launchdock webhook and cli implementation.  

User authorized Git repos, and provide for settings file / LD Connect configuration of autobuild, autodeploy setup for public/private branches.  It'd be reasonable to hope for Git hosts other than GitHub, but perhaps not to start.
## services / plugins

I think our end goal will be to be able to deploy individual Reaction packages/plugins as docker managed micro services.  Forward progress appears to be blocked by Meteor not yet fully adopting a npm based package architecture, but we should continue to strive for this goal and explore options.

**Comment by aaronjudd** [comment]
Related to https://github.com/reactioncommerce/launchdock/issues/4 and original issue
https://github.com/reactioncommerce/launchdock-connect-deprecated/issues/10

**Comment by zenweasel** [comment]
@aaronjudd @jshimko Hey, look at this issue that is probably super-ready to be closed?

**Comment by zenweasel** [comment]
Done!
