### ISSUE TITLE
resolve cookie-tossing warning

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1260]
After a reaction reset, or server restart, a blank page is presented with the console error:

```
Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]
fast_render.js:98 Uncaught Error: seems like cookie tossing is happening. visit here: http://git.io/q4IRHQ
```

This is from fast-render, and appears to be a band-aid security patch.

https://github.com/kadirahq/fast-render#cookie-tossing

We should research and address the issue, so that a restart of Reaction doesn't produce any interruption to the user experience, particularly when we're switching domains from a temporary domain to a new live domain, or localhost.

**Comment by owenhoskins** [comment]
I ended up forking fast-render and commenting out that band-aid since as far as I could see it was only applicable to apps hosted on the now defunct meteor cloud. Might not be a viable for Reaction in the long run but maybe a good stop gap solution.

**Comment by aaronjudd** [comment]
yeah, that's basically what I had in mind.. did you just drop the fork in`packages`?  I'm looking for a way that allows us to leave our `packages` folder pristine..

**Comment by owenhoskins** [comment]
Yep, I dirtied the packages folder :O

**Comment by aaronjudd** [comment]
@mikemurray you probably resolved this with React router...  as in, flow-router was including fast-render as a dependency, and as of v1.2.0, flow-router is deprecated...
