### ISSUE TITLE
Add server side methods for reading/store, query encrypted records

### ISSUE THREAD

**Issue by Capt-Slow** [reactioncommerce/reaction#1271]
This ticket is in reference to #344.

This will require some investigation.

**Comment by aaronjudd** [comment]
discussed with @Capt-Slow and closing as we're not really even sure what the original idea was here.. I think it's more about "a guideline" than an actual task, to ensure methods are secure.

**Comment by zenweasel** [comment]
I think this task could be changed to "determine what data should be encrypted", and then "encrypt that data". Step 1 is important as we may have very limited data that we actually need to encrypt.

**Comment by aaronjudd** [comment]
Sure, but I think that might be identified in #1272 ?

**Comment by zenweasel** [comment]
@aaronjudd Yes, you are correct. My mistake.
