### ISSUE TITLE
"meteor run ios" not working

### ISSUE THREAD

**Issue by fisherman818** [reactioncommerce/reaction#1277]
Hi, I tried to `meteor run ios` to run Reaction on iOS simulator, but it failed, with this error message: 
> no such file or directory, stat '/Users/macpc/meteor/reaction/.meteor/local/cordova-build/www/*

So is this intentionally done, or just a bug?

thank you!

**Comment by aaronjudd** [comment]
See #1213, we've not been testing this, but have an issue to get builds working in a future release

**Comment by fisherman818** [comment]
ok. saw that. thanks
