### ISSUE TITLE
Challenges overriding cart workflow.

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#1278]
### Expected behavior

I'd like to be able to use non-default templates for the checkout workflow without having to rewrite or remove existing core templates such as `checkoutLogin` or `checkoutAddressBook`. We've written our own namespaced templates (e.g. `goCheckoutLogin`) that we'd like to be able to use instead of the core templates.

I'd also like to change the order of the cart workflow by adding additional workflow items. For example we have a workflow step `0` that we've added that permits customers to review the items in their cart before continuing with the checkout process. We also have a workout step `4.5` that requires users to agree to our Terms of Service before continuing on to entering their payment information. Currently we've had to hack these additional steps on to existing steps, but ideally they should be their own workflow steps.

I've been hacking at this for a day and a half now and have determined now that there is no way forward that doesn't involve changing core templates significantly. There are some simple changes we can make that will solve some of issues that make overriding these templates difficult (see: #1269) , but there are other bigger problems that I didn't see until getting deeper that seem to require significant changes to solve.

We've been able to override the existing templates to an extent with the method described in #1269, but in order to change the order, insert new steps, remove existing steps or otherwise modify an existing workflow, it seems there will need to be significant changes to core.
#### Significant Challenges
1. Core cart methods have `coreCartWorkflow` steps built in. [mergeCart](https://github.com/reactioncommerce/reaction/blob/development/server/methods/core/cart.js#L212-L215),
   [copyCartToOrder](https://github.com/reactioncommerce/reaction/blob/development/server/methods/core/cart.js#L618-L624),
   and [setShipmentMethod](https://github.com/reactioncommerce/reaction/blob/development/server/methods/core/cart.js#L700-L701) all call `workflow/pushCartWorkflow` and have existing - core - workflow steps built in.
2. Workflow steps are directly tied to their template. In fact, as far as I can tell, the workflow template _is_ the workflow step. There doesn't seem to be any way to decouple a core template from a workflow step. If there was a way to overwrite named workflow steps with alternative templates, perhaps we could build around the limitation in step one.
#### Solutions?

I'm not really sure what the best way to solve these problems, but I doubt our organization is the only one that will be interested in changing these workflows.

It seems like the first step might be to decouple workflows from the templates that they serve, but I'd imagine that's a fairly complicated process.

There also seems to be a need for cart methods that move workflows along, both forward and in reverse be cognizant of the steps of the workflow they are updating and to remove the assumption that the workflow will be identical for every install. Perhaps there is need for different shops within the same install to have different workflow, but that can be a later discussion.

**Comment by zenweasel** [comment]
This is still a valid issue but should be address in Reaction:Next
