### ISSUE TITLE
Create a Mock Search API to provide result data to pass to the UI (v1)

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1285]
As a first step in implementing search, we should mock up an API that will stub / return (not sure if those are the right terms) data to test with the UI portion of search.

**Comment by zenweasel** [comment]
Also need to add in enough phony products for search to be meaningful

**Comment by zenweasel** [comment]
So in this first pass,what @kieckhafer and I have so far for the "API" for search is a SearchResults publication that looks like this:

``` javascript
Meteor.publish("SearchResults", function (collection, searchTerm, facets) {
 // magic happens
  results = [productResults, hashtagResults];
  return results;
```
Where results is a array of product ids and weights, and the hashtags associated with the results. `facets` is an optional array of hashtags that would filter the results even farther.

Even though we may not use it we may want to have an additional `filters` parameter (similar to the `Products` publication) for any other optional filters.

So any plugins that wants to implement search just needs create this publication and any UI that wants to use it just needs to consume it.
