### ISSUE TITLE
No operations in bulk error on inventoryBackorder

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1288]
This error is occuring whenever inventory goes into a backorder (negative qty) state. It's replicable by adding more qty than exists of a product to the cart,  It also appears in `reaction test` but strangely doesn't cause any tests to fail.

```
Exception in callback of async function: MongoError: Invalid Operation, No operations in bulk
...
0160812-21:11:23.287(-7)?     at packages/meteor/helpers.js:118:1
I20160812-21:11:23.288(-7)?     at [object Object].inventoryBackorder (imports/plugins/included/inventory/server/methods/statusChanges.js:272:32)
I20160812-21:11:23.288(-7)?     at packages/check/match.js:107:1
```

which seems to be thrown here on the execute batch.

```
    const batch = Inventory.
      _collection.rawCollection().initializeUnorderedBulkOp();
    while (i < backOrderQty) {
      let id = Inventory._makeNewID();
      batch.insert(Object.assign({ _id: id }, newReservation));
      i++;
    }

    const execute = Meteor.wrapAsync(batch.execute, batch);
```

Perhaps related we've seen this in #722

**Comment by zenweasel** [comment]
I think it doesn't fail a test because the exception happens in a collection hook and those errors don't bubble back up (nor should they in this case imho). I think it's the "reduce quantity in cart" test that causes this error and I have a version of the test I am working on that doesn't cause the error because that's not what it's trying to test. But we probably need to have a separate test case and deal with "negative backorders" properly. It's probably sort of a blessing that this error is throw.

**Comment by zenweasel** [comment]
I removed a faulty check for bulk operation support which always fails, but I notice that no matter how many items I put in the cart, it only get **at most** 19  as the `backOrderQty` (if it's less it's accurate) which would appear to be broken. So I am going to fix that as well.

**Comment by zenweasel** [comment]
Closed via #1929

**Comment by zenweasel** [comment]
Not fixed. The core issue (now) is that negative quantities are being passed into the backorder method. We need to fix that issue to fix this issue.

**Comment by zenweasel** [comment]
Why was this closed?

**Comment by kieckhafer** [comment]
My fault, in waffleboard it said there was a PR on this that was already merged, so I moved it to done.

**Comment by zenweasel** [comment]
All the currently open tickets relating to inventory/backorder need to get consolidated and put into one and they very closely related I believe. #1935 #1928

**Comment by zenweasel** [comment]
The `no operations in bulk` error has been fixed. So this ticket should be closed. There are other tickets covering the backorder quantity issue.
