### ISSUE TITLE
Add cash on delivery payment method

### ISSUE THREAD

**Issue by eahefnawy** [reactioncommerce/reaction#129]
While that may not be super important in most developed countries, but the rest of the world need it. It's also easier for testing the full purchasing cycle without needing credit cards or payment processors.

**Comment by aaronjudd** [comment]
being worked on by @Gouthamve

**Comment by Gouthamve** [comment]
A basic, working version at: https://github.com/Gouthamve/reaction-cod

But changes need to be made in the orders page clearly showing which orders are COD. Currently, there is no way the shop-owner knows which orders are COD.
This is important as the shop-owner needs to give the carrier separate instructions for COD orders.
See: [other issues](https://github.com/Gouthamve/reaction-cod/issues) 

Also most shops charge extra when COD is chosen. Need to see where this charge needs to be added in the Invoice schema.

Also closes #194

**Comment by jhmac** [comment]
I am not sure if this is the right place or not but seems as close as I could find. What about a customer check out like a pos where you could be at a artist market and you could select the items from the site that people want to buy and be able to swipe their cards and pay like the square pos and it would take it out of inventory automatically.  Sorry if it has been talked about before I searched and nothing came up.

**Comment by aawaheed** [comment]
is this done? if not then I would like to contribute

**Comment by Gouthamve** [comment]
@aawaheed I have a package which I use here: https://github.com/Gouthamve/reaction-cod

It does have a couple of issues open which you could fix or maybe you could test the package to see if you can find some issues

**Comment by aawaheed** [comment]
@Gouthamve OK.. I'll check. Might need your help as I am totally new to contribution scene

**Comment by 1rohittiwari** [comment]
I added the package , but when I log in as admin I dont see the cash on delivery option. When I try checking out it says "No payment methods are configured. Configure now." . As admin I cant find any place to configure or enable this. @Gouthamve

**Comment by aaronjudd** [comment]
@1rohittiwari in the admin dashboard, there should be a dashboard panel with configuration options (similar to the others there). I've not tested reaction-cod, but this is how the packages are designed to work.

**Comment by 1rohittiwari** [comment]
@aaronjudd That is where I looked for the configuration options. Admin > Dashboard. I can see other payment options such as paypal and stripe but Not Cash on Delivery.

**Comment by ovidb** [comment]
I would also love to see this feature implemented. I've tried the package but it doesn't work for me either. I see only Stripe and PP but no COD. @Gouthamve are there other stuff we must do to make your package work?

**Comment by Laboratory** [comment]
Is there any news about cash payment?

**Comment by zenweasel** [comment]
Not currently on the roadmap, but we would welcome a PR that added this feature. If somebody just wanted to convert  https://github.com/Gouthamve/reaction-cod to a Reaction plugin following these instructions: https://docs.reactioncommerce.com/reaction-docs/master/converting that would be great. I might try to do this in my spare time but I wouldn't count on it.
