### ISSUE TITLE
Order fulfillment review should not display individual items

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1293]
In order fulfillment, we should not display a row for each qty, but a total qty for each item.
### Expected behavior

![account_profile](https://cloud.githubusercontent.com/assets/439959/17666358/bdf0a84a-62b4-11e6-9be1-993785cfbdf1.png)
### Actual Behavior

![orders](https://cloud.githubusercontent.com/assets/439959/17666373/cb498624-62b4-11e6-96ae-0797b304ea87.png)
### Steps to Reproduce the Behavior

Add multiple of the same item and create an order

The display that is now occurring was meant to be part of a split order functionality I think.

**Comment by zenweasel** [comment]
Resolved in #2119 (and actually earlier in Joy's changes to the display but...)
