### ISSUE TITLE
Use Extended Schemas in Validation

### ISSUE THREAD

**Issue by paulgrever** [reactioncommerce/reaction#1296]
### Summary

We have extended a number of collections (Cart, Orders, Products) to make Reaction more customized to our needs. But many of the checks performed in the Inventory adjustment methods check only against a Single Schema. Especially in `statusChange.js`. 
### Expected Behavior:

I expect when a Collection is extended with a schema, that the Checks look at all of the Collections's schemas not the default one.
### Actual Behavior

Throws error: `Error: Match error: Match error: variants.gender is not allowed by the schema in field [0]`

``` js
  "inventory/addReserve": function (cartItems) {
    check(cartItems, [Schemas.CartItem]);
    return Meteor.call("inventory/setStatus", cartItems);
  },
```

**Comment by jshimko** [comment]
I’ve got a couple ideas cooking here trying to work out this issue, but one thing that just occurred to me is I think we probably can’t ever have an arg check use a core schema directly...

```js
// bad
check(cart, Schemas.Cart);
```

It really has to always use a final attached schema so we will always be checking the result of any custom schemas being added.

So something more like this instead…

```js
// good
check(cart, Cart.simpleSchema());
```
https://github.com/aldeed/meteor-collection2/#schema-format

**Comment by jshimko** [comment]
Apparently there's an issue standing in the way of using that `.simpleSchema()` method when you have multiple schemas attached to the same collection...

https://github.com/aldeed/meteor-collection2-core/issues/6

And it's been there since March with no maintainer response.  :(

**Comment by jshimko** [comment]
Oh geez.  Apparently this exists now...

https://github.com/aldeed/node-simple-schema

I smell an inevitable refactor...

**Comment by paulgrever** [comment]
of course there is....

**Comment by zenweasel** [comment]
I think we might want to keep this one open (or open another just for the transition to `node-simple-schema`?

**Comment by aaronjudd** [comment]
@zenweasel you mean like #1343?

**Comment by zenweasel** [comment]
Hmmmm, yes. Very much like that.
