### ISSUE TITLE
"Print Invoice" page shows an un-rounded number for total price

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1297]
### Expected behavior
A rounded, 'human-readable' total price should be shown on the Print Invoice

### Actual Behavior

On some occasions, an un-rounded amount will show on the Print Invoice screen

![screen shot 2016-08-15 at 2 23 30 pm](https://cloud.githubusercontent.com/assets/4482263/17680278/389934d8-62f4-11e6-88c3-3f09e79ff207.png)

**Comment by zenweasel** [comment]
I can't replicate using those exact parameters so maybe this got fixed? Or we can reopen with some replication instructions.
