### ISSUE TITLE
Some Dashboard Cards Not working

### ISSUE THREAD

**Issue by deearcodes** [reactioncommerce/reaction#1309]
### Expected behavior
Should navigate to selected card (i.e Inventory)

### Actual Behavior
Some Cards don't navigate to any route

http://g.recordit.co/eQY6F9j9jj.gif

### Steps to Reproduce the Behavior
docker reaction:latest fresh install

**Comment by zenweasel** [comment]
The `Routing`, `Inventory`, and `Layout` cards all do nothing. The `Catalog` card allows you do disable it which I am not sure what effect that would have.

**Comment by aaronjudd** [comment]
I added these intentionally and want to keep them.  They are there as reminders -> that we have functionality that is yet to be developed.  They don't need Routes or enable/disable though.

**Comment by zenweasel** [comment]
It just seems to be causing confusion now as I get the same question every couple of days that people think that something's not working or they can't manage the catalog because the card doesn't work. Can we mark these as WIP or something to make it clearer? I get wanting to leave a placeholder.

**Comment by aaronjudd** [comment]
I had an equal number of questions about where were these packages when they weren't visible.. I sort of view it as a forceful reminder.. of things to come.   The "Catalog" one in particular though, is more questionable.. I'm open to hiding that one.

**Comment by jshimko** [comment]
Short term, we could change the `cursor` css prop on any of those that don't have an actual URL to go to.  That would probably at least curb the "why doesn't this link work" question.

**Comment by aaronjudd** [comment]
@jshimko works fine, feels almost good enough that not sure it won't be a long term solution (what's that saying about quick fixes?)

**Comment by jshimko** [comment]
👍
