### ISSUE TITLE
Auto-completed tags in nav should be filtered so you cannot see already used tags

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1313]
### Expected behavior

Tags that have already been used in the navigation should not show up in the auto-complete dropdown.
### Actual Behavior

When adding new tags into the navigation, the auto-complete feature shows tags that have already been used. When you click on an already used tag, it just kind of disappears and nothing happens.
### Steps to Reproduce the Behavior

Add new tags to a product or the nav. Try to add the same tag again, and see it show up in the auto-complete dropdown.

![screen shot 2016-08-19 at 10 08 54 am](https://cloud.githubusercontent.com/assets/4482263/17817972/11e7040a-65f6-11e6-8743-59810c9febad.png)

**Comment by zenweasel** [comment]
@kieckhafer Are you still working on this?

**Comment by kieckhafer** [comment]
@zenweasel yeah, this still needs to be done. I'll get going on it again.

**Comment by zenweasel** [comment]
@kieckhafer If you are still working on other things can we take this back from you? We want to start working in the Navbar React rewrite.

**Comment by kieckhafer** [comment]
Yes please do... I just removed myself from the assignment.

**Comment by impactmass** [comment]
will be fixed in #2043

**Comment by impactmass** [comment]
resolved in #2306
