### ISSUE TITLE
navbar tag edit drag visibility

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1316]
Introduced in #1310 
### Expected behavior

![](http://g.recordit.co/oTV6VrLSjx.gif)
### Actual Behavior

![8hriibougg](https://cloud.githubusercontent.com/assets/439959/17829275/c7a88cf6-665e-11e6-8df1-fa5779dbb2c3.gif)
### Steps to Reproduce the Behavior

Drag navbar tags....

**Comment by mikemurray** [comment]
This issue seems to have been resolved in development
