### ISSUE TITLE
There should be a way to delete the user you sent the invite to (Guests)

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1321]
For bugs, please fill out the three following sections completely
### Expected behavior

Delete option against the user you sent the invite to
### Actual Behavior

Delete is missing

**Comment by aaronjudd** [comment]
Related to / duplicate of #566

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
