### ISSUE TITLE
Product variant must have a option to inherit picture from parent

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1322]
For bugs, please fill out the three following sections completely
### Expected behavior

Product variant must have a option to inherit picture from parent 
### Steps to Reproduce the Behavior

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by aaronjudd** [comment]
@3Maestros I can confirm that this is the expected  behaviour, _but only in USER view_, if you are logged in as admin it will not inherit from parent..  so that you are able to identify which product variants do have images..

**Comment by 3Maestros** [comment]
@aaronjudd  yes for admin,by default it may be inheriting from parent but there should be simple "check box" that says inherit image from parent.

**Comment by mikemurray** [comment]
Child variants in the published product are not inheriting the parent images if non is set.

**Comment by kieckhafer** [comment]
Fixed by #1664.
