### ISSUE TITLE
throw exception  MongoError: Cannot update 'createdAt' and 'createdAt' at the same time when use upsert to update collections

### ISSUE THREAD

**Issue by xusai2014** [reactioncommerce/reaction#1324]
we are using the older version, so i give up listing excepted behavior and actual behavior

The issue is as below:
``` javascript
`"createdAt": {
    type: Date,
    autoValue: function () {
      if (this.isInsert) {
        return new Date;
      } else if (**this.isUpsert) {
        return {
          $setOnInsert: new Date**
        };
      }
    },
    denyUpdate: true
  }
````
Why to add the condition? the createdAt should keep unchanged.

Now ,i meet the questions that `throw exception  MongoError: Cannot update 'createdAt' and 'createdAt' at the same time when use upsert to update collections`

can you give me some advice? thank you very much!

**Comment by jshimko** [comment]
Can you please provide more details?  The issue template helps us come up with answers faster without having to ask a lot of the same questions.

What were you doing when this happened?  What didn't work (other than the insert)?  What's the output of running `reaction -v`?

**Comment by aaronjudd** [comment]
also please note that the logic here says:

_If this is an upsert and we are inserting, add a new date, but not if we are just updating..._

**Comment by xusai2014** [comment]
Okay, thanks a lot!
