### ISSUE TITLE
phantomjs prebuilt + spiderable failing on docker images

### ISSUE THREAD

**Issue by callmephilip** [reactioncommerce/reaction#1325]
### Expected behavior

Navigating to ```/reaction/product/example-product?_escaped_fragment_=``` should render all the html during the initial page load 

### Actual Behavior

Initial page does not contain full html and gets rendered client side. Server logs contain the follow ing message:

```
spiderable: phantomjs not installed. Download and install from http://phantomjs.org/
```

### Steps to Reproduce the Behavior

- added ongoworks:spiderable to .meteor pakages
- built and image and pushed to docker hub
- launched app on the remote server using the new image
- confirmed that phantomjs has been successfully installed on the remote machine

**Comment by callmephilip** [comment]
As per installation logs, resulting phantomjs binary is located at ```/opt/nodejs/bin/phantomjs```. I attempted to both add ```/opt/nodejs/bin``` to PATH and symlink /opt/nodejs/bin/phantomjs to /bin/phantomjs and restarting the container but this did not seem to work

**Comment by aaronjudd** [comment]
I just tested this locally last week, and everything worked.  How did you install phantomjs on the docker image?

**Comment by callmephilip** [comment]
I believe Phantomjs installation is done automatically: https://github.com/reactioncommerce/reaction/blob/master/.reaction/docker/reaction.prod.dockerfile#L29

**Comment by aaronjudd** [comment]
ok, just wasn't sure if you were using that file.  we're taking a look right now. we're seeing a similar issue with a different docker installation as well.

**Comment by jshimko** [comment]
Yes, if `INSTALL_PHANTOM` is [set to true](https://github.com/reactioncommerce/reaction/blob/master/.reaction/docker/reaction.prod.dockerfile#L7), then it's installed in this script...

https://github.com/reactioncommerce/reaction/blob/master/.reaction/docker/reaction.prod.dockerfile#L7

**Comment by callmephilip** [comment]
I've been digging a bit deeper into this and there is something i do not understand. Since phantomjs is installed via npm using [phantomjs-prebuilt](https://github.com/reactioncommerce/reaction/blob/master/.reaction/docker/scripts/install-phantom.sh#L9), then shouldn't it be used via js API as per [the documentation](https://github.com/Medium/phantomjs#running-via-node)? Instead ongoworks:spiderable [assumes](https://github.com/ongoworks/spiderable/blob/master/spiderable_server.js#L112) that phantomjs binary is in a location that is on system's PATH which is not the case, I believe. Unless I am missing something

**Comment by aaronjudd** [comment]
This sounds familiar to me, in that our old docker builds installed phantomjs with `apt-get`. `ongoworks:spiderable` was specifically built just for that docker build, so it's probably true that it's not compatible with `phantomjs-prebuilt`

**Comment by callmephilip** [comment]
I have a patched version of RC [here](https://github.com/bakery/reaction/tree/feature/patched-spiderable) that uses a local version of ongoworks:spiderable which in turn relies on phantomjs-prebuilt. 

I am able to get part of the page rendered correctly when going to (/reaction/product/example-product?_escaped_fragment_=). In fact both header and footer are rendered properly while central section remains blank
![reaction-blank](https://cloud.githubusercontent.com/assets/492025/18170444/49cc6b70-7056-11e6-8d0f-846b2ef06700.png)

**Comment by jshimko** [comment]
Our Docker build installs `phantom-prebuilt` globally via npm.  Which I'm fairly sure means that the executable should be available in the system `$PATH`.

https://github.com/reactioncommerce/reaction/blob/master/.reaction/docker/scripts/install-phantom.sh#L9

**Comment by aaronjudd** [comment]
@jshimko as we've discussed.  Docker images, not just reaction, are not working as currently configured.  phantom-prebuilt is not found, for whatever reason... but spiderable IS working with a locally installed phantomjs in all my tests.

**Comment by spencern** [comment]
I think we're seeing this as well. Currently deploying this https://github.com/spencern/reaction/commit/01e83cbee634a2beddbaee7991994a1fe61afa1c as a fix on our dev server to see if it does the trick.
