### ISSUE TITLE
Making a new template

### ISSUE THREAD

**Issue by nmarmon** [reactioncommerce/reaction#1326]
Hi there

Maybe this is not the place for ask this but I put it here anyway. I'm trying to make a template with two rows, one filtering with the tag "Bestsellers" and "Latest Items". Is there a helper that takes the value of the tag and show it as a title in each row? And how I can filter the products by these tags?
I don't need that someone makes for me the template, only show how I could do it. 

Thanks for your help. Regards

**Comment by aaronjudd** [comment]
Better discussion for https://forums.reactioncommerce.com .. but if you look at the products publication you'll see that there are a number of filters available on the products.  maybe for a fast way to do this, you could copy that publication into a new one, adjust your parameter in the new publication to match the results you want, and then subscribe to that publication in the onCreated event of your new "best sellers" template, etc..

**Comment by zenweasel** [comment]
Request for support, moved to the forums.
