### ISSUE TITLE
UX: There must be a easy way to increment the quantity of item in the cart, this is missing

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1327]
### Expected behavior

UX: There must be a easy way to increment the quantity of item in the cart, this is missing
### Actual Behavior

Not available

**Comment by aaronjudd** [comment]
Agree, most of that functionality is part of this issue: 

https://github.com/reactioncommerce/reaction/issues/287

It's really just a UI implementation though, the methods exist for updating the quantity.

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
