### ISSUE TITLE
Little UI bug in produc't details

### ISSUE THREAD

**Issue by zimaah** [reactioncommerce/reaction#1328]
Hi everyone!

First I want to congratulations the people behind Reaction Ecommerce, It's a great project.

I'm developing my own e-commerce with RE and I found an UI issue during my tests.
The title of the section details still showing, but the content (the details itself) are hidden in mobile devices visualizations.

This happens in Chrome and Firefox browsers (I'm on Ubuntu).
![captura de tela de 2016-08-25 12-00-20](https://cloud.githubusercontent.com/assets/7024585/17974210/8822768a-6abb-11e6-8365-ea1eacb4f9e8.png)

**Comment by jshimko** [comment]
Good catch.  Thanks @zimaah!

**Comment by zimaah** [comment]
Another issue: Can you add a detail's section for each product's variant?
How could you see I do some "hack" to separate each detail in my UI.

Thx advance :)

**Comment by mikemurray** [comment]
This issue is fixed in development and master with the new React product detail page.
