### ISSUE TITLE
notFound template renders on initial load of "tag" route as new user (incognito window)

### ISSUE THREAD

**Issue by owenhoskins** [reactioncommerce/reaction#1334]
### Expected behavior

Navigating directly to a route such as "tag" as a new user (e.g. incognito window) should show the route
### Actual Behavior

notFound route is shown until refresh
### Steps to Reproduce the Behavior
1. reaction init 
2. cd reaction && reaction 
3. open a new incognito window in Chrome 
4. paste http://localhost:3000/reaction/tag/example-product into URL bar 
5. notFound route renders
6. refresh (tag route renders)

**Comment by zenweasel** [comment]
Can't replicate in current version. Closing.
