### ISSUE TITLE
Totals are displaying negative numbers after a complete discount is given

### ISSUE THREAD

**Issue by Capt-Slow** [reactioncommerce/reaction#1340]
For bugs, please fill out the three following sections completely

### Expected behavior
Order total should become $0.00.

### Actual Behavior
Order total will then become '$-0.00'. It appears the value being saved in billing.invoice.total is `-3.5527136788005e-15`. Also it has been observed this does not occur if billing address is not valid and zero taxes are added.

### Steps to Reproduce the Behavior
1) Login as Admin.
2) Complete an AuthorizeNet order using the following billing address:
2110 Main Street.
Santa Monica 90405
3) Navigate to Orders page.
4) Give order 100% discount.
5) Click 'Approve'.

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by Capt-Slow** [comment]
#1315

**Comment by zenweasel** [comment]
Closing. Verified fixed
