### ISSUE TITLE
update simple-schema to node-simple-schema

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1343]
Migrate from the [meteor-simple-schema](https://github.com/aldeed/meteor-simple-schema) to [node-simple-schema](https://github.com/aldeed/meteor-simple-schema).

Before implementing this, we'll want to review the current state of affairs for GraphQL and Apollo integration as well.

**Comment by aldeed** [comment]
Closing this as dup of #2917
