### ISSUE TITLE
Integrate acceptance tests into CircleCi

### ISSUE THREAD

**Issue by Capt-Slow** [reactioncommerce/reaction#1346]
Now that we have acceptance tests, we need to get them running on CircleCi.

**Comment by Capt-Slow** [comment]
@jshimko Maybe you and I can schedule sometime next week and see if we can get these tests up and running. From what I recall our CI already has PhantomJS installed? So it might just be a matter of getting these tests working with Phantom.

**Comment by jshimko** [comment]
👍

**Comment by Capt-Slow** [comment]
#1348
