### ISSUE TITLE
Speed acceptance tests up

### ISSUE THREAD

**Issue by Capt-Slow** [reactioncommerce/reaction#1347]
Tests right now have a 22min runtime. Fix this.

**Comment by Capt-Slow** [comment]
So after removing a lot of the pauses, it came as no surprise to me that the waitFor functions are proving unreliable. So I am having to troubleshoot a new series of issues/failures.

**Comment by zenweasel** [comment]
Closed via https://github.com/reactioncommerce/reaction/pull/1355
