### ISSUE TITLE
Product page should have some indicator if the product is already added to cart

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1354]
For bugs, please fill out the three following sections completely
### Expected behavior

Product page should have some indicator if the product is already added to cart, plus a esay way to increment the count right there.
### Actual Behavior

Missing
### Steps to Reproduce the Behavior

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by rymorgan** [comment]
This isn't in our current roadmap. We'd welcome a contribution on this one.

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
