### ISSUE TITLE
Decide on the boundaries of reaction-core: Which new features to be packaged vs which will be added to reaction-core

### ISSUE THREAD

**Issue by eahefnawy** [reactioncommerce/reaction#136]
this is a discussion about which new features are best suited as part of reaction-core other than developing into their own packages. 

If you have a feature in mind that you think should be part of core, submit your argument here.

**Comment by aaronjudd** [comment]
**Reaction Apps** 
 
- replace "core,apps",etc with release status.
- methods for integration with core
- See updated docs for packages https://github.com/reactioncommerce/reaction-core/blob/development/docs/packages.md
