### ISSUE TITLE
Unable to go into product edit page 

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#1361]
For bugs, please fill out the three following sections completely
### Expected behavior

From the main product management page, I should be able to click on any product to have it take me into the edit page for a specific product.
### Actual Behavior

Nothing happens when I click on a product to take me into the edit product page. 
### Steps to Reproduce the Behavior

This only happens after I've already gone into a product edit page. In order for it to start working again, I need to refresh/restart the app but stops working again after I go into one edit page. 

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by mikemurray** [comment]
It seems to happen when you make a new product, and there is no metadata. An error in the console shows up and saying it cant find metadata.

**Comment by aaronjudd** [comment]
I'm unable to replicate this in [development](https://github.com/reactioncommerce/reaction/commit/83fc331afcf9d2eb35dff8b67ebc23632acbb7fb)

**Comment by zenweasel** [comment]
I'm unable to duplicate on the current `release-0.18.0` branch (and I've created a **lot** of products)

@cindyfirestone or @mikemurray can you verify that this is fixed, or provide more detailed replication steps?

**Comment by zenweasel** [comment]
Confirmed with @cindyfirestone , can't replicate. Closing.
