### ISSUE TITLE
rename Packages to Registry

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1365]
Rename `Packages` methods, collections, helpers, etc. to a [non reserved keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar) for code clarity.  `package` being a reserved keyword, and while `Packages` is legal and works fine, it's also less indicative of what the purpose of this functionality now is.  Similar logic to #1364 

This would make a breaking change for existing packages, but I suspect the _real packages_.. being _Atmosphere packages_ are aware of our migration to npm and modules, and/or that they are not being maintained.

**Comment by aldeed** [comment]
Won't do
