### ISSUE TITLE
IDEA for Reaction Development

### ISSUE THREAD

**Issue by roclesy1983** [reactioncommerce/reaction#1366]
Hello,

I just wonder which IDEA(Eclipse or Intellij) is better to build a online shop with Reaction?

Thanks,

**Comment by zenweasel** [comment]
There's a discussion of this [here](https://forums.reactioncommerce.com/t/using-an-ide-to-develop-meteor-sites-recommendations/28), you may want to check it out. 

There are a few of us that use WebStorm (based on IntelliJ) that like it though.
