### ISSUE TITLE
Only subscribe to Inventory if Inventory package is installed

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1382]
Inventory should be an optional package but the app throws an error if the package is removed

`Error invoking SubsManager.subscribe("Inventory"):  Subscription 'Inventory' not found`

**Comment by hbakhtiyor** [comment]
i deployed newest master branch to heroku and got the error
how to resolve it?

**Comment by hbakhtiyor** [comment]
found the same issue https://github.com/reactioncommerce/reaction/issues/1363

**Comment by zenweasel** [comment]
If you are not using the inventory plugin you can just comment out that line as a temporary workaround.

**Comment by andela-oadebayo** [comment]
@zenweasel  am having this same issue, where will i comment out the inventory plugin line, can't seem to find it. Thank you

**Comment by zenweasel** [comment]
It's right here: https://github.com/reactioncommerce/reaction/blob/da4a379586c347a39adb3984d842490a210c7392/client/modules/core/subscriptions.js#L41-L41

**Comment by vigyano** [comment]
commenting the subscribe inventory does not work, just a blank page is showing up if master, development, and other branches

**Comment by zenweasel** [comment]
@aaronjudd This can be closed can't it?
