### ISSUE TITLE
restructure/regroup dashboard cards

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1383]
The grouping of utilities, core, etc feels like rather than bringing organization, instead feels disorganized and likely to grow worse over time. My sense is that the dashboard cards need a general organizational update. 

My proposal is that we remove the current grouping of dashboard cards, removing the current use of **priority**, but discuss a way to re-introduce a grouping on the page, maybe even tags if we can come up with a useful (and personalized) layout for the admin. 

This should leave us with single dashboard group.  We can repurpose the existing **priority** field in a way that makes sense by using it for card sort order.  We've discussed ideas like featured plugins, personalization, versions, etc and just priority probably isn't enough data for those kinds of groups in any case. 

Also, I think we should group cards by  **provides**, as is implemented for Taxes already. 
(see taxSettings)

```
    {{#each reactionApps provides='taxSettings'}}
```

All plugins would require a settings object to manage enabled status. This is a different "enabled" than `autoEnable: true` (which is meant to just set the initial status).

```
  settings: {
    avalara: {
      enabled: false,
      apiLoginId: ""
    }
  },
```

For example, this should be an easy update for the payment packages to bring them all under one card. We'll just need to add a new "payments" package to serve as the "parent" in core. 

One downside of combining the packages would be that if we did want add a full route to a plugin specific page (rather than just settings), we'd probably need to treat it like we do with orders, with any navigation being in the dashboard title area (ie, a landing page, with navigation).

**Comment by rymorgan** [comment]
Need meeting to determine where we can consolidate.

**Comment by aaronjudd** [comment]
@mikemurray grab this, once the priority is resolved, this can move to review.
