### ISSUE TITLE
Theme exploration and default LESS variable cleanup

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1385]
Review and possible overhaul of our default colors and variables used throughout the app.

**Comment by rymorgan** [comment]
Further notes: 
Create a separate theme for admin. In the process implement new style guide features (typeface, spacing, button styles, dropdowns cards etc).

**Comment by rymorgan** [comment]
I'm working on finalizing colors, and a few styles (like card styles for dashboard) but I think we should be ready to start putting in the theme stuff as we go. @mikemurray & @kieckhafer -- Let me know when you run into components that need design. I've attached a few mocks that are getting close to where we are going. Let's discuss in standup. 
![pdp desktop color v2](https://cloud.githubusercontent.com/assets/20409254/21736579/854bce00-d426-11e6-9573-2ec2c709c641.png)
![cart reorganize](https://cloud.githubusercontent.com/assets/20409254/21736583/8c309516-d426-11e6-9da7-046a8aaaccc0.png)
![dropdown](https://cloud.githubusercontent.com/assets/20409254/21736591/99f287c2-d426-11e6-8c7b-a86bd9737517.png)

**Comment by kieckhafer** [comment]
PR #1712 begins to cleanup LESS variables.
