### ISSUE TITLE
Add Route Management utilities

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1394]
The routing table (FlowRouter(_routes) is being dynamically populated from the Packages registry.

Add UIX for managing routes additional routes.

Our minimal goals should:
- view existing routes (products, content)
- add alias to existing (more than one route)
- enable/disable route
- redirect a route 
- validate if route/alias is in use, re-asssign to new route

**Comment by mikemurray** [comment]
- [ ] Import package routes to Routes collection
- [ ] Updated router to use Routes collection
- [ ] Associate templates with routes in Routes collection
- [ ] Update coreLayout to support React components at top level

**Comment by aaronjudd** [comment]
Feature request that requires more definition to meet our current issue guidelines.
