### ISSUE TITLE
Visibility glitch with Search results

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1402]
### Expected behavior
Results should scroll under search bar

### Actual Behavior
Intermittently search results scroll on top of search bar and obscure it

### Steps to Reproduce the Behavior
1. Use current `development` branch
2. Navigate to "Basic Reaction Product" detail page
3. search for "basic"
4. Scroll results above search bar then scroll back down. Observe this glitch:

<img width="987" alt="example-product" src="https://cloud.githubusercontent.com/assets/72819/18620736/fe9c72a0-7e4a-11e6-8c8b-1ab6790dc43a.png">

5. In addition, if you are already on a product page, the underlying page seems to mix with results in a way that's confusing. This might be because I am a relatively small monitor. (15" MBP)

**Comment by 3Maestros** [comment]
Even I am seeing this exact behavior.

**Comment by kieckhafer** [comment]
I cannot replicate on my machine, but I have seen this error in action on another machine, and think we have a fix in the branch (search-ui-updates)[https://github.com/reactioncommerce/reaction/tree/search-ui-updates].

**Comment by kieckhafer** [comment]
This is fixed in PR #1410. Closing this issue.

**Comment by zenweasel** [comment]
Closed via #1410

**Comment by 3Maestros** [comment]
Awesome confirmed this is fixed, thank you!
