### ISSUE TITLE
Shipping Dashboard Panels

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1404]
As we're preparing to add additional shipping providers, we need to make some UIX updates to the Shipping dashboard panels, here's a few...
- [ ] Open / Close collapse of provider panel. 
- [ ] Sort Disabled to bottom so that custom/active providers are first
- [ ] Use a priority to determine order of enabled providers

Use case:
I have three providers:
- Local Home Delivery
- Shippo
- Flat Rates

Where "LHD" is a custom plugin, and Shippo is enabled, but I don't want to see it's panel contents, not my disabled Flat Rates. "LHD" is the panel that my shop uses for tracking shipping.

Each of these should also respect viewing permissions from the user's package/role.

**Comment by kieckhafer** [comment]
In reference to UIX standup, we will be adding merchandising to the actionView as part of this ticket.
