### ISSUE TITLE
Cannot see the shopping cart items if total discrete items are more than 4

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1405]
### Expected behavior
All items in the cart should be visible.

### Actual Behavior
Cannot see the shopping cart items if total discrete items are more than 4

### Steps to Reproduce the Behavior
Add more then 4 items to the cart and then click the cart, the 5th items not visible.

**Comment by aaronjudd** [comment]
Can you provide a screenshot?  Are you referring to the cart drawer? (If so, this has a swipeable behaviour, but might not be sufficient for a large amount of products).

**Comment by 3Maestros** [comment]
Yes the cart drawer,

**Comment by zenweasel** [comment]
Unless I don't understand what you are talking about, it looks like you can see as many products as there are (although admittedly you need a pretty wide monitor if you had a lot of products)

![fourth_product](https://cloud.githubusercontent.com/assets/72819/21253547/83f37afe-c39a-11e6-8091-0846501dcaa0.png)

**Comment by aaronjudd** [comment]
and the contents are swipable/scrollable..  not sure if this is a issue we'd solve without a UI redo..

**Comment by kieckhafer** [comment]
We are doing some updates on the cart in ticket #1627. Closing this ticket in favor of those updates, please add comments on that ticket if you wish.
