### ISSUE TITLE
GraphQL implementation research

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1407]
Research [GraphQL](http://graphql.org) implementation approaches,  DDP replacement / augmentation, and api use cases.   

This issue is mainly a placeholder, discussion thread, at least until this is assigned at which point we can break out into tasks (if we're agreeing to move forward with GraphQL).

**Comment by janat08** [comment]
https://github.com/peerlibrary/meteor-peerdb
I belief that having declarative schema that will then denormolize collections will make plugins and simplicity of code incredible. It requires oplog and meteor. With mongoDB release of 3.6 that will begin supporting oplog like functionality as it is purposed in meteor, there's little reason to change to graphql (I belief I saw discussion, I don't know where it's gone).

**Comment by jshimko** [comment]
@janat08 Have you ever refactored a large javascript/Meteor app to use either PeerDB or GraphQL data layers?  I'm curious how you're so confident PeerDB is worth the large amount of developer effort it would take to convert Reaction's data layer to use it.

And you're suggesting that it solves enough of the same problems as GraphQL that it makes GraphQL irrelevant?  That's a pretty big statement.  I'm wondering what real world context you could share to make the case for that.

Then there's also the important detail that `meteor-peerdb` has seen [less than a dozen trivial commits in the last year](https://github.com/peerlibrary/meteor-peerdb/commits/master) (and zero commits in the last 6 months).  It's kind of hard to picture doing a massive data layer refactor to use a Meteor-only library that doesn't appear to be actively developed anymore.

So, we're absolutely always open to considering newer/better ways of doing things, but I'm far from being convinced that PeerDB is an obvious choice here - especially when compared to all of the advantages GraphQL offers (relations, multiple databases or API's as the backend, relations across those multiple data sources, more thorough schema definitions, etc.).  

To be completely honest, I don't even consider GraphQL/PeerDB to be in the same league.  But we're happy to hear you out if you'd like to make the case.  It just needs to more than "the readme sounds like it'd be perfect".  There would be a lot of developer time required to make that a reality and those kinds of decisions can't be made lightly.

**Comment by janat08** [comment]
So I don't know how GraphQL offers relations short of imperatively defining the same calls you would in a method.

I'm convinced that in between advantages of Mongo 3.6 and PeerDB, there's little reason to trash all of back-end that you've written so far for something that also lets you define relations schema, and perhaps avoid call loops, while permitting subscriptions. PeerDB is much less difficult to implement, rather than "refractor" as with GraphQL.

I'm not sure what relations PeerDB doesn't support that GraphQL would within it's schema, so it works and so doesn't require commits, besides cross DBs and APIs.

**Comment by jshimko** [comment]
PR's are always welcome.  Feel free to submit some code that makes the case.

**Comment by aaronjudd** [comment]
Closing - in progress as part of reaction next architecture.

**Comment by j** [comment]
@aaronjudd do you have any writeups on what's "next" ?
