### ISSUE TITLE
anonymous user cleanup job

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1411]
anonymous users are not cleaned up currently. 

the cleanup job should incorporate some abandoned cart functionality and ping abilities.

**Comment by zenweasel** [comment]
From a conversation/debugging session with @spencern. We can probably purge empty carts/users pretty aggressively (7 days, 1 day?) , and then longer for populated carts/account. Probably configurable in shop settings.

**Comment by aaronjudd** [comment]
We could be using the cart aging.. every session will get a cart, so if you said..
cart.created > 30 days, where there are no items, delete where cart.userId from roles, users, carts, sessions if user role = anonymous.

**Comment by spencern** [comment]
I think this should work. We deleted old carts + users, Accounts, Sessions and it cleaned up our db pretty well. Anon carts are pretty small though so we also purged accounts where cart.updatedAt was > 30 days even if there were items in it.

**Comment by zenweasel** [comment]
Let's double-check that Jobs are being removed from the Job collection when they are completed

**Comment by andela-aatanda** [comment]
I have been able to grasp a full understanding of this issue and I've implemented it locally and currently testing it to make sure it's in an okay state.

**Comment by andela-aatanda** [comment]
I'll have to populate the database with dummy data to adequately tests current implementation. All seems fine at the moment

**Comment by andela-aatanda** [comment]
@zenweasel jobs are currently been removed as soon as they are completed. I've been able to check that.

**Comment by andela-aatanda** [comment]
This ticket has been completed with a pull request [here](https://github.com/reactioncommerce/reaction/pull/2013)
