### ISSUE TITLE
use reaction-cli in ci tests

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1422]
Any reason we shouldn't just install reaction-cli in CI and use it to install, run tests?  Seems that would be cleaner than the current scripts...

**Comment by zenweasel** [comment]
Fixed. Closing

![reactioncommerce_reaction__5049_-_circleci](https://cloud.githubusercontent.com/assets/72819/25115561/d1fbfe2e-2439-11e7-9a5f-b5349858b220.png)
