### ISSUE TITLE
Translations.json - the shopId is not populate at shop creation time

### ISSUE THREAD

**Issue by EpifaniaCollection** [reactioncommerce/reaction#1424]
### Expected Behavior
shopId filed in the Translations.json should be filled it when a brand new shop created when a brand new env is created.

### Actual Behavior
shopId is null at startup of a clean env => language change is not saved.

### Steps to Reproduce the Behavior

`docker-compose -f docker-compose-reactioncommerce-dev.yml up`
and check the created mondgo

**Comment by jshimko** [comment]
This was "fixed" multiple times, but I believe we finally got it in #2224.  The changes are in the development branch now.  If you're still experiencing this issue, make sure to try the development branch from any time after 13 days ago.

I'm closing this for now, but feel free to reopen if the problem returns.
