### ISSUE TITLE
Create Transactional Email templates

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1429]
Create Transactional Email templates as defined in #423 

These templates are:

| Template Event | Template Type | Implementation Status |
| --- | --- | --- |
| New shop admin invite | Basic Text Template | Shop owner inviting another admin to the account (with various levels of permissions) |
| Welcome (shopper) | Basic Text Template | Shopper registers at shop and receives welcome email (checkbox at checkout to register for this email) |
| Change PW/Password Reset (shopper) | Basic Text Template |  |
| Order canceled | Order Confirmation (variation) |  |
| Order confirmation (shopper) | Order Confirmation |  |
| Order refund | Order Confirmation (variation) |  |
| Shipment notification (shopper) | Order Confirmation (variation) |  |
| Subscription Activation |  | Not yet |
| Recurring Charge Confirmation |  | Not yet |
| Upcoming Charge |  | Not yet |
| Charge declined | Basic Text Template |  |
| Card Expired |  | Not yet |
| Subscription Cancellation |  | Not yet |
| Out of stock | Basic Text Template | Not yet |
| Refunds | Same as order refund above? |  |
| Abandoned Cart |  | Not Yet |

The template type should define which variables are expected to be available for use in the template.

**Comment by zenweasel** [comment]
All email templates should create emails which display properly in Gmail / Outlook as described in #1059

**Comment by zenweasel** [comment]
This ticket also includes ensuring that the email is sent at the appropriate time. A lot of that should already be happening but we should verify.

**Comment by kieckhafer** [comment]
Resovled in RP #1585
