### ISSUE TITLE
Product list view should skip dummy image if there is no image associated with the product

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1430]
For bugs, please fill out the three following sections completely
### Expected behavior

Product view should skip dummy image if there is no image associated with the product
### Actual Behavior

It displays a dummy image and occupies the space.
### Steps to Reproduce the Behavior

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by zenweasel** [comment]
Displaying the placeholder image when no image is assigned is the expected behavior. You are free to modify this behavior if you wish.
