### ISSUE TITLE
Add a additional instruction field for a product to be filled at order time

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1431]
### Expected behavior
Add a additional instruction field for a product to be filled at order time.

Ex: Special order request that may be available as optional on request.

### Actual Behavior
Missing.

**Comment by 3Maestros** [comment]
@mikemurray @aaronjudd @zenweasel  Can you review this issue and vote if this is some this is something that would be useful for reaction community , If soI will request a PR.

**Comment by zenweasel** [comment]
I think this is a reasonable feature to add as long as it's configurable whether it gets shown or not as many retailers will not want it.

**Comment by zenweasel** [comment]
I see this more on the order than on the product, is that what you mean?

**Comment by 3Maestros** [comment]
I meant on the product as shopper my want a specific customization done on the product.

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
