### ISSUE TITLE
I failed to clone and log still shows it's successful

### ISSUE THREAD

**Issue by IamGabrielWu** [reactioncommerce/reaction#1433]
I'm trying to reaction init as below and it failed but log still says it's successful. i don't get it.

```
1010deiMac:Github gabriel$ reaction init

Cloning the master branch of Reaction from Github...
Cloning into 'reaction'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

Installing NPM packages...
/bin/sh: line 0: cd: reaction: No such file or directory

Reaction successfully installed!

To start your Reaction instance, just run: 

 cd reaction
 reaction

```
### Expected behavior
It's not supposed to say "Reaction successfully installed!"
### Actual Behavior
**Reaction successfully installed!**
### Steps to Reproduce the Behavior
And every time when i need to create a reaction app, i have to clone, i don't know why you don't use Yoeman to create it instead.
And it's better reaction app can be generated locally just using reaction-cli, because every time when create a reaction app, it's downloading from internet, it's slow and takes too much time.

**Comment by jshimko** [comment]
@IamGabrielWu sorry to hear about your issues.  Thanks for taking the time to report it.  It looks like git errors aren't throwing a proper exit code when the process fails.  I'll look into it.

As for Yeoman... I think you might be underestimating the complexity of Reaction or overestimating how flexible Yeoman is.  Yeoman is typically only for scaffolding an app structure as a starting point.  Yeoman also requires you to write a proprietary template structure of the whole app.  That would also require a whole separate repo for us that we'd regularly have to keep in sync with the latest version of Reaction. We'd also have to publish it to npm after every Reaction update.  Aside from the fact that publishing to npm is not currently possible for a Meteor app, a Yeoman app scaffold template and a fully functional Meteor app are two fundamentally different things.

As for having to clone every time you run `reaction init`, how often is that really going to happen in the average use case?  That's not really an every day command unless you're Reaction contributor.  In many (most?) cases, that may not even happen more than once.

Also, the CLI does a lot more than just clone the app.  It'd be pretty tough to make the case for having to use/support a whole separate CLI tool and maintain a separate repo for the proprietary scaffold template just to make a single command faster.  So I'll certainly fix that git error handling, but I think our efforts would be far better spent on fixing/optimizing the existing tools.  Perhaps a good solution for avoiding the full clone each time is we can cache the repo locally and then just pull any changes that exist when `reaction init` is run.  

Until we get a chance to build that... if you really do need to run that command regularly, you can keep an untouched clone somewhere on your filesystem and copy it to a new working directory as needed (which is essentially what the caching idea I mentioned would be doing).

Can you please try running `git clone` directly and let me know if you get any errors?  If that works, please try `reaction init` again too.  I suspect it was a network connectivity issue, so I wouldn't be surprised if the issue didn't happen every time.

Thanks again for reporting the issue!

**Comment by IamGabrielWu** [comment]
@jshimko thank you for your reply. And yes it is  " network connectivity" issue i couldn't smoothly clone it by reaction init.  I can clone it just by git clone, it works faster.  I could have a repo backup and any time if i want to run reaction init,  i could just use my backup instead of cloning from internet. But i still have doubts what else steps i need to take to make sure the clone from my backup will be the same like the running the command reaction init.  Really appreciate your answer on this.

**Comment by jshimko** [comment]
You can `cd` into the clone you save and run `git pull` to get the latest code updates.

**Comment by IamGabrielWu** [comment]
@jshimko  all right. after i get the latest code, what else does reaction init do so i can use git clone and git pull instead ?

**Comment by jshimko** [comment]
`reaction init` does this...

```sh
git clone https://github.com/reactioncommerce/reaction.git
cd reaction
meteor npm install
```

Using those commands directly is identical to the shorter `reaction init` command.  It offers absolutely no performance advantage because `reaction-cli` is running the exact same thing under the hood.  Any time difference is highly likely to just be a coincidence.  But certainly feel free to do whatever you prefer.  It won't break anything to run them manually.

**Comment by aaronjudd** [comment]
Closing issue, has manual fix. Re-open if necessary.

**Comment by phearakthefoundry** [comment]
I don't know why it show like that
![image](https://user-images.githubusercontent.com/61926624/95938451-1e8ac100-0e04-11eb-850f-c2f3eb5d2c72.png)

**Comment by loan-laux** [comment]
@phearakthefoundry You're using the Reaction CLI which was deprecated a long time ago. You should use the new `Makefile` from `reaction-development-platform` instead.

**Comment by Heanphearak** [comment]
git clone git@github.com:reactioncommerce/reaction-development-platform.git
cd reaction-development-platform
make
After I run make command it show like image below, I use window 10.
![image](https://user-images.githubusercontent.com/40253277/96022422-0904ae00-0e7b-11eb-9ba2-e46d146afa47.png)

**Comment by loan-laux** [comment]
@Heanphearak If you're running `reaction-development-platform` on Windows, you need to do it through WSL 2. I would also recommend that we move the discussion to the `reaction-development-platform` repo or to Gitter if you still have issues with this.

**Comment by phearakthefoundry** [comment]
Hi @loan-laux, how can I customize reaction commerce ? I try to update UI but it not change.

**Comment by loan-laux** [comment]
Hi @phearakthefoundry, could you please open an issue in the correct repo and tag me there? Or simply ask on our Gitter channel to get an instant response. This thread is very old so I'd rather not have it brought back to life.
