### ISSUE TITLE
Allow search by tag also

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1434]
### Expected behavior
Allow search by tag also , so that you can search all products that are tagged with a specific tag to help with search.

### Actual Behavior
Not supported.

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
