### ISSUE TITLE
A registered shopper should be able to save his shopping settings

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1436]
### Expected behavior
A registered shopper should be able to save his shopping settings so that he can order the same product again just a click of a button.

### Actual Behavior
Not Available

**Comment by zenweasel** [comment]
What "shopping settings" are should be better defined, but at this point we do not have any plans to save credit card numbers because of PCI compliance issues.

**Comment by aaronjudd** [comment]
Closing - insufficient details.
