### ISSUE TITLE
Deleting product A deleted B

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1438]
For bugs, please fill out the three following sections completely
### Expected behavior

Deleting product A should delete "A" only.
### Actual Behavior

Deleting product A deleted B
### Steps to Reproduce the Behavior
- Click on the edit icon for product A
- In the "Product Settings" page click on trash can and confirm for delete.
- Product "B" is deleted.
  I am running 16.1.
  For enhancements or other issues, please describe in as much detail as
  possible how the app should be changed and how this would benefit
  users/developers

**Comment by zenweasel** [comment]
Cannot reproduce using `release-0.18.0` branch
