### ISSUE TITLE
Shopping Cart is hidden when you launch reaction site from  you phone

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1439]
For bugs, please fill out the three following sections completely
### Expected behavior

It should be reactive, all components on the page must be visible.
### Actual Behavior

Shopping Cart is hidden when you launch reaction site from  you phone
### Steps to Reproduce the Behavior

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by aaronjudd** [comment]
seems to work fine on all our test devices and on hello.reactioncommerce.com. closing without specific device information. we can re-open if you have specific cases to replicate.
