### ISSUE TITLE
There should be a central Tag manager so it's easy to make changes

### ISSUE THREAD

**Issue by 3Maestros** [reactioncommerce/reaction#1440]
### Expected behavior
There should be a central Tag manager so it's easy to make changes rather than making the changes visiting every product which isn't scalable.
### Actual Behavior

Changing a tag from ABC to XYZ requires you to edit every product in the catalog and update to use the new tag.

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
