### ISSUE TITLE
Email settings in ENV vars override those in dashboard

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1442]
### Expected behavior

If credentials from ENV vars will override the mail settings in the dashboard, then they should be displayed in the dashboard.

### Actual Behavior
- Credentials from ENV override settings in dashboard, but the dashboard does not reflect that.

### Steps to Reproduce the Behavior
- Export bad mail settings
- Reset and run reaction
- See errors in terminal when emails fail to send

```
export MAIL_URL="smtp://postmaster%40sandboxXXXX.mailgun.org:BAD_PASSWORD@smtp.mailgun.org:587"
```

**Comment by rstegg** [comment]
And email form should probably be more consistent, keeping API Key and credentials [as an option or dully marked _not all inputs are always necessary_].  For example, send grid can use API key or user credentials.

**Comment by aaronjudd** [comment]
Closing - insufficient details.
