### ISSUE TITLE
product rearrangement: ignored at load time

### ISSUE THREAD

**Issue by EpifaniaCollection** [reactioncommerce/reaction#1443]
### Expected behavior

When the gallery is loaded, before the "load more products" is clicked, it should show the correct first products. When "load more products" is clicked, all the new products are added to the lower part of the page only, and not mixed with the already presented products.

### Actual Behavior

It loads the products in the order they were created; they are only filtered based on the order provided.
This way, each time "load more products" is clicked, products get rearranged, and some of the new products are added between the products which were already listed.

Why it's important: the client won't scroll back to the first part of the page to see the newly added products between the first lines, therefore not aware of those new ones, between the already seen ones.

### Steps to Reproduce the Behavior

1. Load more products (e.g. 30+).
1. Rearrange products as administrator (e.g. put last added ones in the beginning of the page).
1. View the page an observe the order once the "load more products" is clicked.

One may try see the behavior website: https://shop.maryhit.com

**Comment by zenweasel** [comment]
@kieha Hopefully this was just fixed in the rewrite. Can we verify that this was fixed?

**Comment by kieha** [comment]
@zenweasel tested it out with the rewrite and it works as expected for me.

**Comment by kieha** [comment]
Update:
- Followed this to productsContainer (https://github.com/reactioncommerce/reaction/blob/2b1c3a50cbbf628f86ff2ad988b7f46cd2955501/imports/plugins/included/product-variant/containers/productsContainer.js#L135). The query to find products doesn't seem to comply with the results. Might have something to do with revisions, not 100% sure though.
