### ISSUE TITLE
viewing experience of multiple images of a variant/product

### ISSUE THREAD

**Issue by EpifaniaCollection** [reactioncommerce/reaction#1444]
For bugs, please fill out the three following sections completely
### Expected behavior

When an product option has multiple images (e.g. 4), the small pictures should not change positions when clicked on them. In this case, all 4 thumbnails should should be shown, (not only 3), and when clicking on one of them it gets shown in the bigger view, without changing its position in the list of thumbnails.
### Actual Behavior

Out of 4 images, only 3 out of all 4 have thumbnails listed at any given time. Should one click a thumbnail of the 3 under the main view, the positions of the thumbnails is changed, making the user very confused: which picture did he see, and which not.
Moreover, when the mouse is moved, the pictures are swapped, adding to the confusion.
### Steps to Reproduce the Behavior

Add 4+ images to an option, try to view them.

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by kieckhafer** [comment]
Closing in favor of #1615. @EpifaniaCollection I've copied your comment over to 1615.
