### ISSUE TITLE
E mails:Welcome Mail to admin is missing in code 

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#1447]
### Expected behavior
When Default Admin user is created,  welcome mail should be sent 
### Actual Behavior
Mail is not sent.  
### Steps to Reproduce the Behavior
Fresh start of reaction with  user id and name provided using settings.

This used to be there in earlier releases.

**Comment by aaronjudd** [comment]
Duplicate, the task on these is in #1429 (a subset of #423).  We're starting on these next week for 0.18.
