### ISSUE TITLE
Invitation Mail--User Name should be invited user not logged in user

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#1448]
### Expected behavior

Invitation should be  extended to invited user and not logged in user
### Actual Behavior

Logged in user name is used.
### Steps to Reproduce the Behavior

Invite an user from Admin Dashboard and check the mail sent by system.

the issue is from below line where meteor.user() is passed. 
https://github.com/reactioncommerce/reaction/blob/development/server/methods/accounts/accounts.js#L371

**Comment by aaronjudd** [comment]
Should be addressed in #1429 but I'll leave open in for tracking.

**Comment by kieckhafer** [comment]
Verified this is working correctly. Added name "Erik Test" as the invitation, this is what came through:

**Comment by hrath2015** [comment]
Thanks.  Is this merged in Dev.  I tested it on latest Dev and not getting(seeing) pretty mailer as yours in GMAIL.  There is no Get Started button and no Logo.

**Comment by hrath2015** [comment]
See below image for later part of content;
![image](https://cloud.githubusercontent.com/assets/14071646/20075300/afa76840-a559-11e6-9ae5-86e4bed37d4e.png)

**Comment by kieckhafer** [comment]
@hrath2015 this is not yet merged into dev, it's in our working `release-0.18.0` branch. It is currently slated to officially go out with the 0.18 release.
