### ISSUE TITLE
Unable to start reaction

### ISSUE THREAD

**Issue by sylc** [reactioncommerce/reaction#1450]
Hi,
when i did `reaction init,` i had a successful Reaction message however some error were present as well.
These errors can also be reproduced by also doing `meteor npm i`:

```
C:\Users\Sylvain\Documents\App\Projects\ecommerce\reaction\reaction>meteor npm i
npm ERR! git clone C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-90f8e8d5 C:\Users\Sylvain\AppData\Local\Temp\npm-12048-ff3f2333\git-cache-30786998\9c5a29ff037c28af07479eaa27591f1b4a0e5b66: Cloning into 'C:\Users\Sylvain\AppData\Local\Temp\npm-12048-ff3f2333\git-cache-30786998\9c5a29ff037c28af07479eaa27591f1b4a0e5b66'...
npm ERR! git clone C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-90f8e8d5 C:\Users\Sylvain\AppData\Local\Temp\npm-12048-ff3f2333\git-cache-30786998\9c5a29ff037c28af07479eaa27591f1b4a0e5b66: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-90f8e8d5 C:\Users\Sylvain\AppData\Local\Temp\npm-12048-ff3f2333\git-cache-30786998\9c5a29ff037c28af07479eaa27591f1b4a0e5b66: fatal: unable to fork
npm ERR! git clone C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-90f8e8d5 C:\Users\Sylvain\AppData\Local\Temp\npm-12048-ff3f2333\git-cache-30786998\9c5a29ff037c28af07479eaa27591f1b4a0e5b66:
npm ERR! git fetch -a origin (https://github.com/ongoworks/node-authorize-net.git) fatal: Unable to find remote helper for 'https'
npm ERR! git clone --template=C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ongoworks/node-authorize-net.git C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-e88b3c4b: Cloning into bare repository 'C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-e88b3c4b'...
npm ERR! git clone --template=C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ongoworks/node-authorize-net.git C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-e88b3c4b: error: cannot spawn ssh: No such file or directory
npm ERR! git clone --template=C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ongoworks/node-authorize-net.git C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-e88b3c4b: fatal: unable to fork
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Sylvain\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Sylvain\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ongoworks/node-authorize-net.git C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-e88b3c4b
npm ERR! Cloning into bare repository 'C:\Users\Sylvain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ongoworks-node-authorize-net-git-e88b3c4b'...
npm ERR! error: cannot spawn ssh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     ....reaction\reaction\npm-debug.log
```

when i start reaction with reaction, i have:
```
Using settings file at settings/dev.settings.json

Setting up plugin imports...

[[[[[ C:\Users\Sylvain\Documents\App\Projects\ecommerce\reaction\reaction
]]]]]

=> Started proxy.
=> Started MongoDB.
```
then it hangs.

i'm on windows 10. i have installed all required tools. node/win32 SSL/MS build tools/Git/Imagemagick
```
reaction -v 
Node: 5.0.0
NPM: 3.9.0
Reaction: 0.16.1
Reaction CLI: 0.4.20
```

**Comment by aaronjudd** [comment]
Seems to be related to #1245 and the temporary fork that we're using https://github.com/ongoworks/node-authorize-net

perhaps you could try doing `meteor npm install -s authorize-net`, before running `reaction`, to manually install (or at least see if you get errors from a manual installation).

**Comment by hrath2015** [comment]
do this in project directory.
``npm install authorize-net@github:ongoworks/node-authorize-net``
Will solve the issue.

**Comment by jshimko** [comment]
Maybe we should just publish that to the `@reactioncommerce` org on npm for now?

**Comment by jshimko** [comment]
@sylc and @hrath2015 can you both try the new branch I just published and let me know if the authorize-net error goes away?

```sh
reaction init -b authorize-on-npm
cd reaction
reaction
```

**Comment by hrath2015** [comment]
error as below: (Not in NPM registry) Shall wait and try after some time.

npm ERR! 404 Not found : @reactioncommerce/authorize-net
npm ERR! 404
npm ERR! 404  **'@reactioncommerce/authorize-net' is not in the npm registry.**
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'reaction'

**Comment by jshimko** [comment]
Yeah, just discovered that too in CI.  It's because org packages are automatically set to private by default.  I didn't have the issue because I have access to the org.  But I apparently don't have the rights to make it public, so I'm waiting on @aaronjudd to take a look with his account.  I'll let you know when it's all set.

**Comment by hrath2015** [comment]
OK. thanks

**Comment by jshimko** [comment]
Nevermind.  Apparently you can only set the access level at the time of publishing the package.  So I had to bump the version number and republish just to set it to public.  No UI available for that on npm.  Nice one, npm...

Give it another try.

**Comment by aaronjudd** [comment]
@zenweasel and I discussed if we should wanted to publish that as a package or use the git remote, but we'd decided we didn't want to pollute our org with a bunch of packages that we can never get rid of…  this issue feels like it's more likely a network error…  since npm fully supports pulling direct from the repo (and this has been in place for the last several releases). @hrath2015 have you always had an issue with this and done the manual install, or were you just making a recommendation?   After the package is published on npm, it might be hard to say conclusively that the issue is solved...

**Comment by hrath2015** [comment]
I had this issue after this change was made due to security and only  on windows env. 
 ``meteor npm install``  does not work instead i have to do ``npm install``

**Comment by jshimko** [comment]
Interesting.  I bet the older version of npm that Meteor uses has a bug with Github pulls on Windows.

**Comment by hrath2015** [comment]
all good 👍

**Comment by sylc** [comment]
`reaction init -b authorize-on-npm` removed the previous error. 

I have now an error with bcrypt, but reaction is working. It takes at least 6 mins to start but it could be linked to the bcrypt error, which i'm investigating further

thanks!


```
Using settings file at settings/dev.settings.json

Setting up plugin imports...

[[[[[ C:\Users\Sylvain\Documents\App\Projects\ecommerce\reaction\test4
]]]]]

=> Started proxy.
=> Started MongoDB.
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
W20160930-12:54:08.962(8)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20160930-12:54:09.123(8)? (STDERR) While this implementation will work correctly, it is known to be
W20160930-12:54:09.124(8)? (STDERR) approximately three times slower than the native implementation.
W20160930-12:54:09.125(8)? (STDERR) In order to use the native implementation instead, run
W20160930-12:54:09.125(8)? (STDERR)
W20160930-12:54:09.125(8)? (STDERR)   meteor npm install --save bcrypt
W20160930-12:54:09.126(8)? (STDERR)
W20160930-12:54:09.127(8)? (STDERR) in the root directory of your application.
I20160930-12:54:14.912(8)? 04:54:14.910Z  INFO Reaction: Load default data from /private/data/
I20160930-12:54:15.657(8)? 04:54:15.655Z  INFO Reaction: JobServer started
I20160930-12:54:15.677(8)? 04:54:15.661Z  WARN Reaction: Skipped loading settings from reaction.json.
I20160930-12:54:18.895(8)? 04:54:18.864Z  INFO Reaction: Starting createDefaultAdminUser
I20160930-12:54:18.982(8)? 04:54:18.979Z  INFO Reaction: Using meteor --settings to create admin user
I20160930-12:54:20.766(8)? 04:54:20.765Z  WARN Reaction:
```

when i do `meteor npm install --save bcrypt`
I get
 `> bcrypt@0.8.7 install C:\Users\Sylvain\Documents\App\Projects\ecommerce\reaction\test4\node_modules\bcrypt
> node-gyp rebuild

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\Sylvain\Documents\App\Projects\ecommerce\rea
ction\test4\node_modules\bcrypt\build\bcrypt_lib.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sylvain\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Sylvain\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Sylvain\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Sylvain\Documents\App\Projects\ecommerce\reaction\test4\node_modules\bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Sylvain\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Sylvain\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "bcrypt"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.`

**Comment by hrath2015** [comment]
U need to have python installed and try.

**Comment by hrath2015** [comment]
@jshimko  @aaronjudd  I remember a discussion where  we wanted to remove this bcrypt dependency and use what comes with meteor.  Any update?

**Comment by sylc** [comment]
I have python installed. The main issue was with node-gyp. VS2015 build tools have break the build and node-gyp needed to be upgraded to 3.4.0. I finally upgraded npm to 3.10.8, which upgraded node-gyp. and the compilation went through. It is ok now. removing bcrypt will reduce the install requirement for first time users . +1 if it can be removed. thanks
