### ISSUE TITLE
stripeapi.js promises fixes.

### ISSUE THREAD

**Issue by joseconstela** [reactioncommerce/reaction#1452]
Stripeapi.js promises return unexpected values. See issue #1337 - PR #1449 

Also affecting `listRefunds` and `captureCharge`.

**Comment by joseconstela** [comment]
With this fixes, all works fine. But without them, I've been able to process charges multiple times.

As this charges where already processes by Stripe, their API returned an error, but stripeapi.js didn't catch it, so the frontend didn't show any error notification thing.

The lack of catching exceptions can be easily replicated by faking variables like `transactionId`

**Comment by aaronjudd** [comment]
@joseconstela these updates look good, should be merging into development today after some more testing. These updates should also help resolve the error handling issue #1117
