### ISSUE TITLE
[PDP] Revisions for Tags

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1457]
Task from https://github.com/reactioncommerce/reaction/pull/1356

Tags need a revision state ->  when is this product visible / searchable using this tag?  Not until after the product is published.  (and vice versa for remove).

**Comment by zenweasel** [comment]
So testing this you already have a revision workflow in that if you create a tag and put it on a product, it's not on that product until you publish changes. While technically the tag is published, it's not used anywhere, you still need to add it to a product and/or to the nav. Spoke to @aaronjudd and we agreed that building a separate workflow for Tag revisions doesn't make sense, so closing this ticket for now.
