### ISSUE TITLE
Example Payment/Stripe Uncaught ReferenceError

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1459]
In checkout, the example payment causes an `Uncaught ReferenceError` when submitted with invalid fields.

### Expected behavior

In checkout, the example payment should validate and handle the error event, letting the user update invalid fields.

### Actual Behavior
`example.js:95 Uncaught ReferenceError: submitting is not defined`

![cart_checkout](https://cloud.githubusercontent.com/assets/439959/19009778/056b7af6-872c-11e6-95a9-495c76cbb38e.png)

After this the inputs are disabled as well and the user cannot update invalid inputs.

### Steps to Reproduce the Behavior

Checkout and submit an example payment without required fields.

**Comment by zenweasel** [comment]
This is also happening with Stripe as well

**Comment by zenweasel** [comment]
Closed via #1461
