### ISSUE TITLE
Reaction Apps install manager

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#146]
(rapp = reaction app)

In app gallery, we can enable/disable, which turns on/off the UI related to that rapp. We can also `meteor remove` the pkg. But afaik, we can't currently "uninstall" the rapp. That is, if the rapp has stored data in its own collections or in reaction collections, we should be able to remove that data.

* UI: Possibly ask when disabling whether the rapp's data should be deleted?
* Code: Provide a way for a rapp to register a function that reaction-core will call to request full data removal. Should handle any and all schema versions.

This is related to the idea of dynamically adding and removing rapps, which we have discussed. If we were to provide a way within the UI to remove a rapp (not just disable), then this should call the rapp's data removal function before removing the rapp code.

**Comment by aaronjudd** [comment]
See also: #247,  version upgrade, delete, revision  history probably all come into play here as well.

**Comment by aaronjudd** [comment]
Resolved with #1112
