### ISSUE TITLE
[PDP] update productDetail.js scope and structure

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1462]
bitHound discovered 2 LintIssues in [imports/plugins/included/product-variant/client/templates/products/productDetail/productDetail.js](https://github.com/reactioncommerce/reaction/blob/2fdb23f2c5e84bd752c87ffebfcc4375b1e056a8/imports/plugins/included/product-variant/client/templates/products/productDetail/productDetail.js). For details go to [bitHound](https://www.bithound.io/github/reactioncommerce/reaction/blob/2fdb23f2c5e84bd752c87ffebfcc4375b1e056a8/imports/plugins/included/product-variant/client/templates/products/productDetail/productDetail.js). 

---

Related to #1258

**Comment by mikemurray** [comment]
This is the old PDP page so do we proceed with resolving the issues, or eventually depreciate the package in favor of the new, React PDP page?
