### ISSUE TITLE
[PDP] When creating product, prices don't display in grid

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1483]
### Expected behavior

Price range or price should display
### Actual Behavior

No price is shown for non-admin
Although the price is a price range, only one product is shown

<img width="831" alt="the_first_product" src="https://cloud.githubusercontent.com/assets/72819/19177908/10a915e6-8c80-11e6-9348-339cde6a3d9c.png">
### Steps to Reproduce the Behavior
1. Login as administrator
2. Create product and only create prices on variants
3. Publish changes and make product visible
4. Observe that price is shown in PDP admin but not the correct range
5. Observe that for non admins no price is shown

**Comment by zenweasel** [comment]
Actually, the variants aren't showing up at all

**Comment by mikemurray** [comment]
Hmm wonder if the variants are not they're not visible, and the product was allowed to be published irregardless.

This is also related to the ticket, products should be purchasable without needing a variant. #500

**Comment by zenweasel** [comment]
Yeah, it looks like even when this is published, the variant is still set as `isVisible: false` so all queries for it as a non-admin are empty.

Also noticed this where the logic is so that the `priceRange` is always set to `ReactionProduct.getVariantPriceRange()`. Would be relevant if `selectedVariant` was ever not an empty array.

https://github.com/reactioncommerce/reaction/blob/7f8cfd298a4717ed09b41bb9f0bf2b8511fe7171/imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js#L226

**Comment by zenweasel** [comment]
Also seems to happen when you **do** create a variant and an option, both the variant and the options show up as `isVisible: false`. Which means it's basically impossible to create a product? That's a bummer. Testing this on the latest `development`.

**Comment by mikemurray** [comment]
I did a reset and tried this with the latest development branch and everything worked as expected. Yesterday, however, I was having the same issues as described above.

**Comment by zenweasel** [comment]
This was user error, here's @mikemurray's steps that work below. Changing this bug to be that you can publish a product that is not complete/not purchasable which you didn't used to be able to do.

1. reaction init -b development "reaction"
2. cd reaction
3. reaction
4. -- Reaction loads and gives you the goodies.. (credentials) --
5. Navigate to localhost:3000 in chrome
6. -- On Product grid
7. Sign in with credentials
8. -- Sill on product Grid -- (get logged out because of the stupid login bug... log back in.,...)
9. click the + sign in the toolbar
10. click "Add Product"
11. Fill in some basic information 

![](https://i.imgur.com/JK978FD.png)

12. Publish changes
13. At this point the product should be visible to the customer... but the variant will not be visible

![](https://i.imgur.com/fZ0a53w.png)


14. Back in the product, click the eye button on the variant to make it visible

![](https://i.imgur.com/DmyGiT6.png)

15. Publish changes
16. Profit!

![](https://i.imgur.com/h6KM5rE.png)

**Comment by zenweasel** [comment]
Okay, was retesting this while testing the tag workflow and this is still broken. The steps above work but if you view the product in an incognito window or another browser the prices still don't show up. Not really sure this is an issue with Revisions though as all the variants appear to be set to `isVisible: true`.

**Comment by zenweasel** [comment]
This issue got a little messy with a bunch of overlapping issues, but the final issue is simple so replacing with #1576
