### ISSUE TITLE
submitting credit card form without all fields results in submit button permanently disabled 

### ISSUE THREAD

**Issue by tdmoneybanks** [reactioncommerce/reaction#1485]
For bugs, please fill out the three following sections completely

### Expected behavior
click the submit button: error messages pop up about unfilled fields and submit button is able to be clicked again

### Actual Behavior
click the submit button: error messages pop up about unfilled fields but submit button remains disabled with a loading spinner showing on the right

### Steps to Reproduce the Behavior
go through the checkout flow with the example payment and leave some credit card fields blank when submitting the form.

**Comment by jshimko** [comment]
This was reported in #1459 and fixed in #1461.  And the fix has been merged to development.

**Comment by tdmoneybanks** [comment]
alright closing now!
