### ISSUE TITLE
Brand logic for handling images

### ISSUE THREAD

**Issue by hydrotik** [reactioncommerce/reaction#1486]
### Expected behavior

When a user uploads an image, the text shouldn't be rendered and only the image is shown within the href. The site name text should be included in SEO/Alt copy.

For example:

``` html
<template name="coreNavigationBrand">
  <a class="brand" href="{{pathFor '/'}}" title="{{siteName}}">
    {{#if logo}}
      <div class="logo">
        <img src="{{logo.url}}" alt="{{siteName}}">
      </div>
    {{else}}
      <span class="title">{{siteName}}</span>
    {{/if}}
  </a>
</template>
```
### Actual Behavior

When uploading an image, the image shows along with the name of the site in live text.
### Steps to Reproduce the Behavior

Upload image into core dashboard settings.

Also be aware of the comment here:
http://blazejs.org/guide/spacebars.html#Each-in
regarding usage of #with

Also it would be helpful to understand how one would choose to customize this without affecting the core code through themes/plugins/layouts etc? I am new to Reaction, but this seems like something that would be done through that process otherwise I'd offer a PR:)

**Comment by hydrotik** [comment]
Reading the info on plugin creation which seems to be the proper way of handling this.

**Comment by zenweasel** [comment]
This would be a customization which, as mentioned, could be handled with a plugin.
