### ISSUE TITLE
[PDP] Upgrade from 0.16.0 product

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1488]
Upgrading from a shop with 0.16.0 product causes some unexpected visibility issues.

### Expected behavior
That a product from a pre 0.17.0 release should smoothly migrate without issue to a 0.17.0 product with revisions.
### Actual Behavior

Product grids display "No products found".

### Steps to Reproduce the Behavior

something like this...
```
reaction init -b master
reaction
git checkout development
```

**Comment by zenweasel** [comment]
I am pretty sure it has something to do with this: https://github.com/reactioncommerce/reaction/blob/8b005c8e5fb9fcaf7b4e6a6f008d5bdf53fa4ae9/server/publications/collections/products.js#L83-L83

Possibly just a migration to add this field and set it to `false` would do the trick?

**Comment by zenweasel** [comment]
Or am I just stating the suuuper obvious here

**Comment by aaronjudd** [comment]
or just `isDeleted: {$in: [null, false]},`?

**Comment by zenweasel** [comment]
Does that work if the field doesn't exist? If so, yeah that's way better. I'm testing now.

**Comment by aaronjudd** [comment]
Product view would need an update as well, https://github.com/reactioncommerce/reaction/blob/8b005c8e5fb9fcaf7b4e6a6f008d5bdf53fa4ae9/server/publications/collections/product.js#L25 could be `  selector.isDeleted = {$in: [null, false]};`

**Comment by zenweasel** [comment]
So I also noticed when on this migrate path I get the old PDP page rather than the new version. Is that intentional or do I need to turn revisions on somewhere?

**Comment by zenweasel** [comment]
I have revision control enabled but get the old PDP page so no revision control.
