### ISSUE TITLE
Issue starting Reaction Commerce on meteor/windows

### ISSUE THREAD

**Issue by auBusinessDaD** [reactioncommerce/reaction#1496]
Hi All,

Firstly, thanks for creating what looks to be an awesome offering.

I have downloaded the git.zip and un-packaged it. When i first tried starting the application (using the meteor command in CMD) it had a few packages it struggled getting - I installed each of these, but am still not able to start the server.

### Expected behavior
I would expect, that opening the command prompt, navigating to the directory and typing the standard start command ("meteor") would just work.

### Actual Behavior
`C:\Users\danie\reactionCommerce>meteor
[[[[[ C:\Users\danie\reactionCommerce ]]]]]

=> Started proxy.
=> Started MongoDB.
                                                                                                                  Building local pa                                                             Warning: unable to resolve "stage-2" in presets of /C/Users/danie/reactionCommerce/.babelrc
W20161014-16:12:37.043(11)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20161014-16:12:37.180(11)? (STDERR) While this implementation will work correctly, it is known to be
W20161014-16:12:37.183(11)? (STDERR) approximately three times slower than the native implementation.
W20161014-16:12:37.188(11)? (STDERR) In order to use the native implementation instead, run
W20161014-16:12:37.191(11)? (STDERR)
W20161014-16:12:37.194(11)? (STDERR)   meteor npm install --save bcrypt
W20161014-16:12:37.199(11)? (STDERR)
W20161014-16:12:37.203(11)? (STDERR) in the root directory of your application.
W20161014-16:12:38.596(11)? (STDERR) WARNING: npm peer requirements (for react-meteor-data) not installed:
W20161014-16:12:38.600(11)? (STDERR)  - react@15.x not installed.
W20161014-16:12:38.603(11)? (STDERR)  - react-addons-pure-render-mixin@15.x not installed.
W20161014-16:12:38.605(11)? (STDERR)
W20161014-16:12:38.611(11)? (STDERR) Read more about installing npm peer dependencies:
W20161014-16:12:38.614(11)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20161014-16:12:38.617(11)? (STDERR)
W20161014-16:12:38.621(11)? (STDERR) C:\Users\danie\reactionCommerce\node_modules\fibers\future.js:280
W20161014-16:12:38.624(11)? (STDERR)                                            throw(ex);
W20161014-16:12:38.626(11)? (STDERR)                                            ^
W20161014-16:12:38.631(11)? (STDERR)
W20161014-16:12:38.634(11)? (STDERR) Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20161014-16:12:38.636(11)? (STDERR)     at Object.Npm.require (C:\Users\danie\reactionCommerce\.meteor\local\build\programs\server\boot.js:198:17)
W20161014-16:12:38.641(11)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20161014-16:12:38.644(11)? (STDERR)     at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
W20161014-16:12:38.647(11)? (STDERR)     at Module.Mp.import (C:\Users\danie\AppData\Local\.meteor\packages\modules\0.7.6_1\npm\node_modules\reify\lib\runtime.js:70:16)
W20161014-16:12:38.652(11)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (C:\Users\danie\reactionCommerce\.meteor\local\build\programs\server\packages\react-meteor-data.js:210:180)
W20161014-16:12:38.654(11)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20161014-16:12:38.656(11)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20161014-16:12:38.659(11)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
W20161014-16:12:38.663(11)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20161014-16:12:38.666(11)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20161014-16:12:38.668(11)? (STDERR)     at C:\Users\danie\reactionCommerce\.meteor\local\build\programs\server\packages\react-meteor-data.js:258:15
W20161014-16:12:38.673(11)? (STDERR)     at C:\Users\danie\reactionCommerce\.meteor\local\build\programs\server\packages\react-meteor-data.js:269:3
W20161014-16:12:38.677(11)? (STDERR)     at C:\Users\danie\reactionCommerce\.meteor\local\build\programs\server\boot.js:292:10
W20161014-16:12:38.680(11)? (STDERR)     at Function._.each._.forEach (C:\Users\danie\reactionCommerce\node_modules\underscore\underscore.js:103:9)
W20161014-16:12:38.685(11)? (STDERR)     at C:\Users\danie\reactionCommerce\.meteor\local\build\programs\server\boot.js:128:5
=> Exited with code: 1`

### Steps to Reproduce the Behavior
This occurs the same way every time I try and start meteor (using command "meteor") when in the reactionCommerce directory

Any help would be appreciated. I am just wanting to actually check this out and see if it is at a stage where some of my acquaintances can start using it.

**Comment by zenweasel** [comment]
You should be using the `reaction` command to start Reaction. This enables the plugin loader which is required for Reaction to work.

**Comment by auBusinessDaD** [comment]
Thank you for such a quick reply.

I did try using the `reaction` command, but it resulted in the following;

`C:\Users\danie\reactionCommerce>reaction
'reaction' is not recognized as an internal or external command,
operable program or batch file.`

I am guessing I would need to add reaction as a command, but have no idea how this is done.

Thanks for any help on this.

**Comment by zenweasel** [comment]
Issues are not a great place to get or give support. I would be happy to help you in our [Gitter chat room](https://gitter.im/reactioncommerce/reaction?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or in our [forums](https://forums.reactioncommerce.com) 

Closing this ticket.
