### ISSUE TITLE
Failing cart to order completion without a billing address.

### ISSUE THREAD

**Issue by nenti** [reactioncommerce/reaction#1498]
### Expected behavior

In some e-commerce scenarios shipping address is not required and thus you can remove the workflow step in the checkout process. 
### Actual Behavior

When converting the cart to order on completing the checkout process an error occures and order never completes.
### Steps to Reproduce the Behavior

Remove workflow step 2 from the checkout process. Checkout a shopping cart.

This issue is related to a wrong handling in method "cart/submitPayment" where a missing billing address is handled with a wrong mongo query.

**Comment by aaronjudd** [comment]
Thanks @nenti makes sense, we need to allow for payments that don't require a billing address.

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #2](https://github.com/reactioncommerce/reaction-feature-requests/issues/2) via [**ZenHub**](https://www.zenhub.com/)
