### ISSUE TITLE
Can't delete shop logo after uploading

### ISSUE THREAD

**Issue by sophiehe** [reactioncommerce/reaction#1505]
### Expected behavior

![screen shot 2016-10-18 at 4 54 56 pm 2](https://cloud.githubusercontent.com/assets/20484811/19500613/af895fdc-9553-11e6-8652-7e7ccfe5d03f.png)

When you upload a file, you should have the option of being able to delete it. 
### Actual Behavior

![screen shot 2016-10-18 at 4 45 28 pm 2](https://cloud.githubusercontent.com/assets/20484811/19500547/27a91076-9553-11e6-82a8-f06a0e81979e.png)

However, the trash icon disappears once you've successfully uploaded one. 
### Steps to Reproduce the Behavior

Upload a shop logo in the dashboard and check the box. There won't be any way to delete the logo, unless you go into the database and delete it manually from there.

**Comment by zenweasel** [comment]
This has been fixed
