### ISSUE TITLE
Revision Control - Archive change history

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#151]
Copy any object being changed to a historical archive before and after edits are made.

-  Add archive collection 
-  Add to all update methods
-  Record time, user with change.
-  Roll back to any revision
-  History UI / UX for reviewing revisions / reverting actions

**Comment by aaronjudd** [comment]
If anyone wants to merge this in https://github.com/reactioncommerce/reaction-core/compare/development...eahefnawy:revision-control 
it looks like will need some refactoring, but nothing too major. A PR would be gladly be accepted.

**Comment by tdecaluwe** [comment]
Does this still work with reaction >= 0.11?

Are there any thoughts on how this should be ideally implemented? Specifically, storing diffs versus storing complete document copies. It seems to me that storing complete document copies should simplify a lot of thing. This would make it rather easy to, for example, view a shop at a certain date in the past.

**Comment by aaronjudd** [comment]
We have been actively discussing this http://stackoverflow.com/questions/4185105/ways-to-implement-data-versioning-in-mongodb approach with revisioning being a changeset collection implemented at lower level, probably at the Mongo driver before Meteor.collections.
