### ISSUE TITLE
itemTypes

### ISSUE THREAD

**Issue by zoshe** [reactioncommerce/reaction#152]
For example the itemType api is an enumeration with these possible values: default, non_inventory, serialized_assembly, assembly, serialized, box .

ITEMTYPE
Item type determines specific behavior for various special types of items.
1. default :
   Items behave normally.
2. non_inventory :
   Inventory for these items is not tracked and no inventory options are displayed on the user interface. Non Inventory items with TaxClass = Labor are treated specially on workorders as tasks instead of items.
3. serialized :
   Serialized entries are stored for these items. These track serial numbers that are in stock or have been sold to customers. On the sales screen these serial numbers are displayed and new serial numbers can be entered.
4. assembly :
   ItemComponents are used to build Assembly items. Think of an assembly line where a certain set of component items are taken out of inventory to build one final item.
5. serialized_assembly :
   Combines serialized and assembly functionality to create items from components that have serial numbers.
6. box :
   Box items can be broken down into single items that are contained within the box (ItemComponents are the singles). Think of a six pack of soda. The six back is a 'box' and the single cans are the 'singles'.

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
