### ISSUE TITLE
Don't subscribe to all media all the time

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1530]
Currently we just [publish/subscribe](https://github.com/reactioncommerce/reaction/blob/da4a379586c347a39adb3984d842490a210c7392/client/modules/core/subscriptions.js#L37-L37) to all Media for a shop even when the products are not visible which when using CollectionFS means we also subscribe to all the binary data (including 3 different versions of the same image). 

If a store has a lot of media data loading this can take a long time. Probably this subscription should be limited to products that are visible.

**Comment by aaronjudd** [comment]
Is CFS subscribing to all Media data, or just to media _metadata_ as published in `cfs.Media.filerecord` (where files are not actually stored)?  That's the only subscription data I see when looking at active client subscriptions.

**Comment by zenweasel** [comment]
Yes, I think that's correct. It's still a ton of data to try and pipe down on first load though so I think it still makes sense to move it to template level subscriptions. @spencern said he did this on their site and it really helped their first load time.

![example-product](https://cloud.githubusercontent.com/assets/72819/20370900/1d5567d6-ac9c-11e6-81a6-0494f7e9bc26.png)

**Comment by spencern** [comment]
not 100% sure that it's all data vs all metadata, but we noticed significant improvement moving this off of global to template subs.

**Comment by zenweasel** [comment]
Being worked on in #1815. Closing as duplicate.
