### ISSUE TITLE
Unexpected behavior when signing-in with Facebook login if user is already registered by email-password signup.

### ISSUE THREAD

**Issue by prosf** [reactioncommerce/reaction#1540]
### Expected behavior
If a user is already registered by using  the default email-password signup, and then tries to sign-in with facebook login (which uses the same email address)  he should sign-in in reaction’s app, and the new facebook accessToken / infos should merge with his existing account.

### Actual Behavior
After the user has sign-up with regular email-password registration ,if he tries to sign in with Facebook login (using a Facebook account that has the same email registered)  he is unable to (the same sign-in prompt reappears) .  
Furthermore, a new object is created in the Accounts table but not in the users table each time he retries to sign in with the “Facebook login” .
No errors are returned to the Login form, or to the Server’s log.

**Comment by aldeed** [comment]
Closing because Facebook login will no longer be in core
