### ISSUE TITLE
Feature Request: Points Reward

### ISSUE THREAD

**Issue by joelchen** [reactioncommerce/reaction#1545]
Following #1512, a Points Reward feature similar to https://woocommerce.com/products/woocommerce-points-and-rewards is highly desired. I can fully transition my client's E-Commerce website to Reaction Commerce with the addition of this feature.

**Comment by aaronjudd** [comment]
Good idea, I'll keep this in mind. 
Do you know of any services that might provide this functionality? Always looking for good integrations..

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #1](https://github.com/reactioncommerce/reaction-feature-requests/issues/1) via [**ZenHub**](https://www.zenhub.com/)
