### ISSUE TITLE
Error when deploying to Heroku.

### ISSUE THREAD

**Issue by andela-oadebayo** [reactioncommerce/reaction#1546]
Am trying to deployed a version of reactioncommerce to heroku, the deployment process works fine on Heroku, but when i try running the heroku app, i get this error.
<img width="1680" alt="screen shot 2016-11-01 at 2 26 47 pm" src="https://cloud.githubusercontent.com/assets/9655574/19891302/c5a8f204-a03f-11e6-8e6f-a7221765cee1.png">

This is major line of the error
`Error: Cannot find module '/andela-project-daini-56fca7b/imports/plugins/core/orders/server'`

Please i would appreciate any help with this.

Thank you.

**Comment by jshimko** [comment]
What buildpack are you using?

**Comment by jshimko** [comment]
Also, see this issue for discussion on the only supported buildpack...
https://github.com/reactioncommerce/reaction/issues/1363

Specifically, you need to use this fork of the horse buildpack.
https://github.com/swrdfish/meteor-buildpack-horse

Which can be used with...
```sh
heroku buildpacks:set https://github.com/swrdfish/meteor-buildpack-horse.git
```

**Comment by andela-oadebayo** [comment]
@jshimko thank you for the swift reply,  am using that same buildpack.

To get to this point i had to comment out this line : 
https://github.com/reactioncommerce/reaction/blob/da4a379586c347a39adb3984d842490a210c7392/client/modules/core/subscriptions.js#L41-L41

i dont know if that could have caused some issues

**Comment by jshimko** [comment]
Sounds like the plugin loader script isn't being used.  Does it run locally?

**Comment by andela-oadebayo** [comment]
@jshimko yes it does run locally

**Comment by jshimko** [comment]
And you're positive that you're using the _fork_ of the horse buildpack and not the original, right?  If that inventory line needs to be commented out, that's usually because the plugin loader didn't run and load the inventory plugin.  Also, the plugin loader is the entire reason that buildpack fork was created.

Other than that, I'm not sure what else to recommend.  Heroku usually works, but it isn't officially supported by the Reaction team (Docker is the recommended production deployment method).  It sounds like the app runs fine in every other environment, so you may want to [file an issue over at that buildpack repo](https://github.com/swrdfish/meteor-buildpack-horse/issues) and see if anyone else is experiencing the same problem.

**Comment by chluke123** [comment]
Tried with the **swrdfish** buildpack with no success.

Then tried the following and it deploys for me:

- set buildpack: https://github.com/AdmitHub/meteor-buildpack-horse.git#beta
- update app to: meteor update --release 1.4.2.1-beta.0
- set env: BUILDPACK_CLEAR_CACHE=1

But then I get following errors when loading the main page:
- Subscription 'Inventory' not found
- warning: unknown template "coreLayout"

Any ideas?

**Comment by zenweasel** [comment]
That error is the one that was fixed by the the `swrdfish` buildpack.

**Comment by carlos-olivera** [comment]
I have problems deploying to heroku as well, I identify  "moment": "^2.15.1" as a problematic module.

I have the same problem with other meteor apps (no reaction), deleting the module, app deploys.

With previous versions I had no problems, are you using this module recently?

**Comment by carlos-olivera** [comment]
I am using swrdfish buildpack (https://github.com/swrdfish/meteor-buildpack-horse.git)

Previous deploy with a old version of reaction, deployed without problems.

`Writing location.js file
remote: Phantom installation failed { [Error: EACCES: permission denied, open '/tmp/build_c94675ab13d9c5c927682726e5894c03/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js']
remote:   errno: -13,
remote:   code: 'EACCES',
remote:   syscall: 'open',
remote:   path: '/tmp/build_c94675ab13d9c5c927682726e5894c03/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js' } Error: EACCES: permission denied, open '/tmp/build_c94675ab13d9c5c927682726e5894c03/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js'`

**Comment by carlos-olivera** [comment]
I forced the module momentjs to version 2.14.1 and I was able to deploy, last version is 2.15.2 with the  issue.

**Comment by zenweasel** [comment]
Fixed in development.
