### ISSUE TITLE
Variable Scopes

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#155]
Right now, reaction-core puts different "global" variables in different places on the `window` object (and on the `global` object on the server, to a lesser extent).

For example, `Meteor.app`, `Packages` (easily confused with Meteor's `Package`), `Media`, `currentProduct`, etc. are all on `window` and thus available everywhere.

A few points about this:

* It would be easier for reaction package/plugin creators if everything were exported in an organized way on a single window/global variable. For example, `ReactionC` is exported and plugins can use `ReactionC.Collections.Media`, `ReactionC.getCurrentProduct()`, etc. This is one place where I think a hierarchy and overly verbose names makes sense. As a plugin creator, it's helpful to be able to, for example, examine `ReactionC.Collections` and get an instant idea of all the reaction collections available. We can always assign the long variable chains to a shorter file-scoped variable name at the top of any file.
* The difference between `@x` and `share.x`, I think, is that the former puts `x` on `window` or `global`, which increases the chances of variable contention with other packages, libraries, etc. that might be added by the user. `share.x` makes `x` available in all files in the current package but does not pollute the window/global scope with them unless we `api.export` them from the package. So...
    * We should use `share.x` instead of `@x` everywhere. Or, better yet, create a single `.js` file that loads first and has just a list of package-scope variable initializations set to null. We later define them in the other files.
    * `ReactionC` (or whatever you want to call the one variable that we export) can be defined the same way as the other package-scope variables, but we'll additionally `api.export` it so the plugin packages can access it.
* This is kind of implied by the two points above, but by allowing the plugins to access only everything exported on `ReactionC`, we're providing a limited and manageable API and thus preventing the kinds of issues that might arise when plugins mess with variables that we really intended to be used only by reaction-core. Also easier to document a limited and consciously exported API.

If there is agreement on this, I can make these adjustments.

**Comment by aaronjudd** [comment]
This issue is mostly resolved, but considering the discussion here https://github.com/reactioncommerce/reaction/issues/320  we'll probably revisit this again.  At least by moving back to JS we should be able to restrict the scope more naturally.
