### ISSUE TITLE
I18n for PT-BR

### ISSUE THREAD

**Issue by ltouro** [reactioncommerce/reaction#1553]
Portuguese language is little different on Portugal and Brazil. I suggest to have a PT-PT I18n for Portugal and a PT-BR I18n for Brazil. 

If this is acceptable, I shall send a PR.

**Comment by aaronjudd** [comment]
@ltouro this would be good.  I've not tested with i18next with language variations but this should be pretty straightforward.  If you take a look in the release-0.18.0 branch as well, we're starting to implement translations on a per package basis, so we've added `loadTranslation` and `loadTranslations` that can be used for individual loading (that aren't from the /private/data/i18n folder).
