### ISSUE TITLE
What is the value of the future feature "Extend DDP methods with RESTful endpoints"?

### ISSUE THREAD

**Issue by andela-kakpobome** [reactioncommerce/reaction#1554]
Hi, fantastic platform, really a breath of fresh air in the e-commerce space.

I'm looking to contribute to the platform and have taken a look at the [future road map](https://reactioncommerce.com/features). One of the features listed there and I'm interested in is described as: **Extend Meteor DDP methods and provide restful API.**

**Concern(s)**
One of the key  pillars of ReactionCommerce I believe is the realtime nature of things. If RESTful endpoints are built to extend/mirror the DDP methods, they won't have realtime capabilities by default, is this deliberate?

If that's not the case(and I believe it isn't seeing how awesomely reactive the platform is now), that'll mean some other socket connection (different from Meteor's implementation ) would have to be used to maintain the realtime data flow for the RESTful endpoints, which begs the question why have another web socket implementation.

**Question**
Can you please shed some light as to what the plan is with this feature and how the it would create value for the platform? It'ld really help provide context and set proper expectations to have a clearer picture of what success look like. Thanks in advance for your time, really looking forward to contributing!

**Comment by zenweasel** [comment]
@andela-kakpobome The intent here is not to replace DDP with REST but to allow external systems (e.g. alternate front-ends, accounting systems, other languages) to interface with Reaction Commerce. So if you are working in Meteor it will have no effect on how you work.

**Comment by andela-kakpobome** [comment]
@zenweasel thanks for the swift response. So with an Android app for instance, it would be able to consume those RESTful endpoints conveniently, but how would the app be updated in realtime when relevant data is updated by some other user? Would/should the endpoints have a web sockets implementation for that or some other pub/sub thing? Or there's no such plan to make non-meteor clients have a realtime experience as well?

**Comment by aaronjudd** [comment]
There are DDP clients for other than Meteor available, so you actually don't need to use a restful API for this.  See: http://meteorpedia.com/read/DDP_Clients

This is why the RESTful endpoints have been a low priority, but we'd still like to have them for cases where external systems need a more traditional endpoint.

A simple way to provide this right now is https://github.com/stubailo/meteor-rest/blob/master/packages/rest/README.md

Closing this as it's more of a conversation than an issue.

**Comment by andela-kakpobome** [comment]
Noted @aaronjudd & thanks for the clarification.
