### ISSUE TITLE
Deleted variant photo shows up on main product grid

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#1560]
### Expected behavior
When variant detail and photos are removed from a product, the photo should also be removed from the main product grid. 

### Actual Behavior
The deleted product photo shows up again in the main product grid. 

### Steps to Reproduce the Behavior
1. Added two variant details, and two variant option under each detail. 
1. Deleted the 2nd variant detail and published my change. The main product grid then only shows the image from my first variant. 
1. Deleted the first variant options (there should be no images left) but when I went back to the main product grid the image from the 2nd variant now shows up.

**Comment by zenweasel** [comment]
@cindyfirestone When I tested this, I added images to the options and they are not displayed at all. Can you provide me some screenshots of what you are seeing?

**Comment by zenweasel** [comment]
Closed. Can't reproduce
