### ISSUE TITLE
Failed to reset plugin file reaction/client/plugins.js

### ISSUE THREAD

**Issue by NerdKid** [reactioncommerce/reaction#1567]
### Actual Behavior
When i run this command reaction to start , it says following error 
"Failed to reset plugins file at /home/user/node/reaction/client/plugins.js"

**Comment by zenweasel** [comment]
Hey @NerdKid , you'll need to give us a little more detail as I am running this constantly and not having any issue. What platform are you on? What are the result of `reaction -v`? Possibly this would be better answered in our Gitter channel.

**Comment by NerdKid** [comment]
@zenweasel hi, Im using ubuntu 16.04 , my reaction -v :
Node: 4.2.6
NPM: 3.5.2
Reaction: 0.17.1
Reaction CLI: 0.5.1
everything installed successfully, but when i try to run "reaction" in command line , it says that "Failed to reset plugins file at /home/user/node/reaction/client/plugins.js".

**Comment by jshimko** [comment]
Sounds like a permissions issue.  I'm assuming you ran something with `sudo` that you shouldn't have.

What do you get from this?

```sh
ls -la /home/user/node/reaction
```

**Comment by NerdKid** [comment]
@jshimko okey:
drwxr-xr-x  17 root root  4096 Nov 10 17:47 .
drwxrwxr-x   6 duk  duk   4096 Nov 10 17:35 ..
-rw-r--r--   1 root root    54 Nov 10 17:46 .babelrc
-rw-r--r--   1 root root  1678 Nov 10 17:46 .bithoundrc
-rw-r--r--   1 root root  1895 Nov 10 17:46 circle.yml
drwxr-xr-x   9 root root  4096 Nov 10 17:59 client
-rw-r--r--   1 root root   430 Nov 10 17:46 .codeclimate.yml
drwxr-xr-x   4 root root  4096 Nov 10 17:46 custom
-rw-r--r--   1 root root   302 Nov 10 17:46 docker-compose.yml
-rw-r--r--   1 root root   150 Nov 10 17:46 Dockerfile
-rw-r--r--   1 root root   145 Nov 10 17:46 .dockerignore
-rw-r--r--   1 root root   295 Nov 10 17:46 .editorconfig
-rw-r--r--   1 root root    72 Nov 10 17:46 .eslintignore
-rw-r--r--   1 root root 10103 Nov 10 17:46 .eslintrc
drwxr-xr-x   8 root root  4096 Nov 10 17:46 .git
drwxr-xr-x   2 root root  4096 Nov 10 17:46 .github
-rw-r--r--   1 root root   475 Nov 10 17:46 .gitignore
-rw-r--r--   1 root root     0 Nov 10 17:46 .gitmodules
drwxr-xr-x   3 root root  4096 Nov 10 17:46 imports
-rw-r--r--   1 root root   543 Nov 10 17:46 .jsbeautifyrc
drwxr-xr-x   5 root root  4096 Nov 10 17:46 lib
-rw-r--r--   1 root root 35178 Nov 10 17:46 LICENSE.md
drwxr-xr-x   3 root root  4096 Nov 10 17:46 .meteor
drwxr-xr-x 514 root root 20480 Nov 10 17:48 node_modules
-rw-r--r--   1 root root  3580 Nov 10 17:46 package.json
drwxr-xr-x   3 root root  4096 Nov 10 17:46 packages
drwxr-xr-x   7 root root  4096 Nov 10 17:46 private
drwxr-xr-x   5 root root  4096 Nov 10 17:46 public
-rw-r--r--   1 root root   871 Nov 10 17:46 .pullapprove.yml
-rwxr-xr-x   1 root root   342 Nov 10 17:46 reaction
drwxr-xr-x   4 root root  4096 Nov 10 17:59 .reaction
-rw-r--r--   1 root root  7498 Nov 10 17:46 README.md
drwxr-xr-x   9 root root  4096 Nov 10 17:59 server
drwxr-xr-x   2 root root  4096 Nov 10 17:46 settings
drwxr-xr-x   4 root root  4096 Nov 10 17:46 tests

**Comment by NerdKid** [comment]
@jshimko any idea?

**Comment by jshimko** [comment]
Yeah, none of that should belong to `root`.  Actually, nothing in a non-root user's home directory should belong to root.  You'll need to fix those permissions.

Assuming your non-root user's name is `node` and its home directory is `/home/node` you would do that like this...

```sh
sudo chown -R node:node /home/node
```

But based on your path above (`/home/user/node/reaction`) it looks like your user's name is "user".  Not sure what you have going on there, but I do know you need to update permissions so none of that is owned by root.

https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-permissions

Since this isn't a problem with Reaction and nothing appears to be broken, I'm going to close this issue.  Good luck!
