### ISSUE TITLE
Price does not show up in product grid when price is not a range

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1576]
### Expected behavior
Price should always show up like it does in the PDP

### Actual Behavior
When there is a single product rather than a range, price is not displayed

### Steps to Reproduce the Behavior
1. Create a product with a single top-level variant
1. Visit the product grid, e.g. the home page
1. Observe that price is not displayed

**Comment by aaronjudd** [comment]
Related to #1521 and  #1519?

**Comment by zenweasel** [comment]
Yes. I think this is a duplicate of #1519. The issue being that the `price` field is not getting updated on the parent product.
