### ISSUE TITLE
SQLITE_CANTOPEN 

### ISSUE THREAD

**Issue by NerdKid** [reactioncommerce/reaction#1577]
Hi guys,
Few days ago i installed reaction ecommerce, but it has error so that i could not run it. and then i removed it and installed it again. But while im installing , it says following error:

I ran this command :reaction init

Cloning the master branch of Reaction from Github...
Cloning into 'reaction'...

Installing NPM packages...
Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)

Can u helps me guys?
Im using Ubuntu 16.04

**Comment by NerdKid** [comment]
And when i type "reaction" in command line:
reaction

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)
Retrying after error { [Error: SQLITE_CANTOPEN: unable to open database file]
errno: 14, code: 'SQLITE_CANTOPEN' }
Retrying after error { [Error: SQLITE_CANTOPEN: unable to open database file]
errno: 14, code: 'SQLITE_CANTOPEN' }
/home/duk/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;

**Comment by zenweasel** [comment]
That's a puzzler, because we don't have anything to do with Sqlite.

**Comment by NerdKid** [comment]
@zenweasel so what should i do now? any idea??

**Comment by zenweasel** [comment]
Looks like it may be permissions, check out this issue question on SO http://stackoverflow.com/questions/31817177/sqlite-cant-open-meteor-create-app

**Comment by NerdKid** [comment]
@zenweasel thnks, it is now working well , really appreciate it
