### ISSUE TITLE
[Marketplace] Ban account + Close account functionality

### ISSUE THREAD

**Issue by lcampanis** [reactioncommerce/reaction#1578]
Adding functionality for Ban and Close account.

**Ban account**
In a marketplace setup - Allow admins and other moderator roles to ban a user account from the site.

- The account will be blocked without notice
- Email is blocked from sign in and register
- Username is unavailable
- Products related to that user account are unpublished (not deleted for safety, but also for the ability to reinstate an account easily in the future)
- Disable Shop in Marketplace

Future enhancements:
Enhancements for email templates and other hooks can be added in the future.

**Close account**
For single shop and marketplace: Allow all users (except the admin) to Close their account at will.
- Warn users about the consequences of closing their account
- Delete user account entirely
- Delete all associated products
- Delete Shop in Marketplace
- Keep orders (Implications of removing invoices may vary between countries)
Question: Keeping orders is safe, but can an order exist in Reaction if the user, shop and products are deleted entirely? And is it necessary?

**UI**
- Ban account button can sit under Accounts > Manage Account in a new panel above Permissions.
- Close account can sit in the Account > Profile page at the bottom of the page
- Templates for both will be available so that buttons can be added anywhere 

We'll be taking this one on this week. 

Has this been discussed or thought of before? 
Any thoughts?

**Comment by lcampanis** [comment]
While we are trying to do this as a standalone plugin, in some cases it is needed to alter core. 
In this case dashboardAccounts so that the Ban User button is part of the manage user settings screen, but most importantly so that banned users are not in the list of Guests under accounts.

So far the only way I have found is to override reaction templates entirely in the new package, but this doesn't cut it as the package will always have to update its views every time reaction updates them.
This will require some Template hooks, for something say the registry provides: "settings" renders in settings when the same route is used, with a topToBottom priority?
Here's an example in action.
![image](https://cloud.githubusercontent.com/assets/670954/20383475/a4fe5d48-acb8-11e6-824d-0a1e3886f874.png)

**Comment by lcampanis** [comment]
This will need some core changes to get it done correctly. I am putting it on hold for now as we need to sort out some marketplace issues before.

**Comment by spencern** [comment]
@lcampanis This may be more feasible from a plugin now with the new accounts components and group based permission features. Let me know if there's anything I can do to help you deliver this feature

**Comment by aaronjudd** [comment]
Closing - insufficient details, see new user management utilities.
