### ISSUE TITLE
i18n / schema translations fail to load

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1593]
Some AutoForm forms are not getting i18n translations. 

The payment method form in checkout is an example.  This form's schema is never loaded during the i18n getLabels startup process, and so this form's labels are never translated.

There's a couple of quick fix solutions.. adding span tags in manually or creating a shared payment component that doesn't use AutoForm would be easy and should probably done and both a step forward, and a quick resolve of this. 

However, the loading of i18n labels for schemas that are imported in a package doesn't occur, because the schema hasn't been exported to a global namespace and thus isn't available when the i18n startup runs getLabels().  Presumably this requirement is why `ReactionCore` lingers as a "phantom" global, and is still in use.   We need to look at how schemas, collections, etc are defined shared between independent packages (and slowly break out those from core) -> but I think it's also worth considering updating the i18n/localization to it's own package as well.  In any case, we need to deprecate `ReactionCore` as it's a temporary solution at best.

**Comment by spencern** [comment]
Related #2917 #3034
