### ISSUE TITLE
Receive validation error when trying to change email template in Dashboard

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1594]
### Expected behavior
No errors when valid form submitted

### Actual Behavior
Receive "Name is required" error when submitting form even when name field is filled and not been changed

### Steps to Reproduce the Behavior
1. Edit a template
1. Don't change anything (or do, no difference)
1. Hit update
1. Observe error

**Comment by kieckhafer** [comment]
Fixed in PR #1600

**Comment by zenweasel** [comment]
Closed via #1600
