### ISSUE TITLE
Create content menu persists after focus is lost.

### ISSUE THREAD

**Issue by Redmega** [reactioncommerce/reaction#1598]
### Expected behavior

On focus loss, add menu should disappear.

### Actual Behavior

On focus loss, menu persists. Seems to be two separate menus for the responsive design, i can open it on fullscreen and then make the window smaller to make the menu hide, but when i maximize again it reappears. If i open the menu when the window is small, and then maximize, the same behavior occurs in reverse. If i open it in both the menu never goes away.

<img width="1280" alt="screen shot 2016-12-02 at 11 06 58 am" src="https://cloud.githubusercontent.com/assets/662951/20841183/d7749e62-b880-11e6-8c3c-002b70f7e520.png">

### Steps to Reproduce the Behavior

Click on the "+" button (Create Content). Click anywhere else. Resize screen.

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

Bad UX to not have the create content menu disappear.

<hr>

If someone can point me to where that code is I can investigate. I'm just starting to hack on this framework so I'm not familiar with where everything is yet.

**Comment by Redmega** [comment]
I tried changing https://github.com/reactioncommerce/reaction/blob/c842d27fde639e3fd5709db99c261a7d59647c8d/imports/plugins/core/layout/client/templates/layout/admin/admin.js#L64
> instance.dropInstance.open();

to 

> instance.dropInstance.toggle();

as per the Drop docs, but that didn't seem to work. Are any core drop functionalities being overwritten anywhere?

**Comment by aaronjudd** [comment]
I think we're going to remove that UI element anyways, originally we thought we'd add additional creation options (create content, product,etc), but we're working on some new UI updates here and this is something that just doesn't feel "right".

**Comment by alexsuslov** [comment]
2 sec. auto hide ?
setTimeout(() => instance.dropInstance.remove(), 2 * 1000 );
