### ISSUE TITLE
Receive error when adding email to anonymous order

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1602]
### Expected behavior
No error in console

### Actual Behavior
Receive error:
`Error invoking Method 'orders/sendNotification': Access Denied [403]`

### Steps to Reproduce the Behavior
1. Place order as guest
1. Put email in "Add your email" field
1. Observe error message

**Comment by aaronjudd** [comment]
@kieckhafer I can confirm this (and I know why).

**Comment by zenweasel** [comment]
Closed via #1607
