### ISSUE TITLE
Move the publish bar on the PDP to the top of the page

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1624]
1. Move publish bar to the top. 
2. Use Toggle for customer view with label 'Preview'
3. Undo as icon with tool-tip for those that don't understand the icon
4. Use eye icon for Public/Private

See Attached Mock-up
![publish-bar](https://cloud.githubusercontent.com/assets/20409254/21153997/ad548a80-c121-11e6-8143-119e03ddf91a.png)

**Comment by rymorgan** [comment]
Updated version of the publish bar. 

Moving this to the top of the waffleboard. I think we should get these into a branch as soon as possible to facilitate the UI cleanup. 

![publish bar](https://cloud.githubusercontent.com/assets/20409254/21736699/72686c52-d427-11e6-983c-ab453832ec9e.png)

**Comment by mikemurray** [comment]
This ticket https://github.com/reactioncommerce/reaction/issues/1598 will be resolved with consolidation of the publish bar and the side toolbar.
