### ISSUE TITLE
Add CC Validation

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1626]
Add CC Validation in cart. Perhaps using: http://kenkeiter.com/skeuocard/

**Comment by aaronjudd** [comment]
![1__rc__node__and_cart_checkout](https://cloud.githubusercontent.com/assets/439959/21704507/c78b448e-d36e-11e6-8d4f-8b3e882ee848.png)


Also fix validation so that the full error/reason is displayed.  May need our own error code list.

**Comment by kieckhafer** [comment]
Closing in favor of #2198, which will add validation.
