### ISSUE TITLE
Move Icon Tool bar to opposite side of the Sidebar

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1628]
For  the flow of Reaction. We want to experiment with moving separating the icon toolbar from the sidebar.

**Comment by rymorgan** [comment]
Moving these to the top of the waffleboard. I think we should get these into a branch as soon as possible to facilitate the UI cleanup.

**Comment by kieckhafer** [comment]
No longer relevant, as we are moving the icons inside the sidebar to another location.
