### ISSUE TITLE
When visiting the URL for an archived product, receive endless spinner

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1630]
### Expected behavior
Receive some sort of "product could not be found" message

### Actual Behavior
Just a white page with an endless spinner

### Steps to Reproduce the Behavior
1. Archive a product and publish the change
1. Visit the url for the product
1. Observe the endless spinner

**Comment by kieckhafer** [comment]
Looks like moving to a React based PDP, and using react-komposer, was causing some issues. `composeWithTracker` allows use for a Loading page (in our case, the spinner), to appear while we are waiting for `onData` to be called. `onData` was only being called when a product was found, so when a product wasn't found, `onData` would never be called, and the spinner would live on forever.

#1725 fixes this by calling an empty `onData` if no product is found, which triggers the loading screen to go away. 1725 also converts our previous Blaze `notFound` template into a React `ProductNotFound` component.
