### ISSUE TITLE
Checkout Page: getting hung up on shipping step

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1631]
Console error: 
Download the React DevTools for a better development experience: https://fb.me/react-devtools
meteor.js?hash=e3f53db…:930 Error invoking Method 'accounts/addressBookUpdate': Internal server error [500]

See attached terminal error:
<img width="810" alt="screen shot 2016-12-14 at 9 36 41 am" src="https://cloud.githubusercontent.com/assets/20409254/21193635/ce21b8d0-c1e1-11e6-936f-a9032c46dffd.png">

See attached screen shot of checkout page:
<img width="1282" alt="screen shot 2016-12-13 at 2 45 22 pm" src="https://cloud.githubusercontent.com/assets/20409254/21193670/e9569274-c1e1-11e6-854d-624597f4cfa4.png">

**Comment by zenweasel** [comment]
I've tried every permutation of shipping/billing addresses and can't seem to replicate it.
