### ISSUE TITLE
Prices not localized in order emails sent to users

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1634]
### Expected behavior
All displayed prices to be in localized currency

### Actual Behavior
All prices are except for the prices in the "Thank you" page

### Steps to Reproduce the Behavior
1. Switch your currency by changing your locale
1. Place an order all the way through to completion
1. Observe that totals are displayed in store currency, not localized currency

**Comment by chluke123** [comment]
Also the both the order confirmation / sent emails display $ rather than the currency of the order.

**Comment by kieckhafer** [comment]
To accomplish displaying the correct currency in emails, we need to store the user selected currency, as well as the currency exchange rate (1.0 if currency is the same as store) at the time of purchase, along with the order data when an order is processed.

Then inside the emailData object, we'll need to do the conversions to display inside the email.

**Comment by kieckhafer** [comment]
@zenweasel agreed, title changed.
