### ISSUE TITLE
When only Paypal Express is enabled, checkout shows "No Payment methods configured"

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1636]
Someone should duplicate this as this seems like this recently worked fine. On the current `release-0.18.0`

**Comment by aaronjudd** [comment]
![banners_and_alerts_and_cart_checkout](https://cloud.githubusercontent.com/assets/439959/21411672/04c0d516-c79f-11e6-9420-4f418cc0e3e1.png)

Not able to replicate in 0.18 now.

**Comment by zenweasel** [comment]
Doesn't happen to anybody but me. Closing.
