### ISSUE TITLE
Dashboard package list and Toolbar should reflect permissions

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1642]
### Expected behavior
If I don't have permissions to an item, I shouldn't see them in the sidebar

### Actual Behavior
All items (Dashboard, Orders, and Accounts) are shown, but clicking on them gives me the "You don't have permissions" screen

### Steps to Reproduce the Behavior
1. Register a guest user
1. As an admin, give that user Dashboard access
1. Observe that the guest user now sees all "admin" icons but clicking on Orders or Accounts will give you a login screen.

**Comment by mikemurray** [comment]
related to https://github.com/reactioncommerce/reaction/issues/841

In standardizing the toolbar buttons, permissions for showing these buttons can fixed as well.

**Comment by mikemurray** [comment]
These icons have moved to the top toolbar

**Comment by kieha** [comment]
On release-0.19.0, the experience is totally different. The dashboard now appears on the side, and when a guest is given dashboard access, they can practically see everything the admin sees. But when they, say, click `Orders`, they don't get an error or the "You don't have permissions" screen, they get a blank screen.

**Comment by kieckhafer** [comment]
Related to #1651

**Comment by impactmass** [comment]
At this time, the issue described here is not happening anymore (see comment above), although there are still some issues with permissions which will be addressed in #1651 + #2075

It's fine to close this ticket.
