### ISSUE TITLE
filter base on metadata

### ISSUE THREAD

**Issue by gpgmbh** [reactioncommerce/reaction#1645]
We have only 3 levels categories with tags structure. It's not bad to add the filter function base on metadata of products. With the filter would only the filtered products be showed.

**Comment by zenweasel** [comment]
@gpgmbh Not sure what you mean when you say "3 levels categories". And what filtering are you talking about?

**Comment by gpgmbh** [comment]
@zenweasel  we have 3-level categories on tag-nav base on tag structure, f.e make-up -> eye -> eyeliner. With hastags field we can also add some other tags. But from products grid, it's not possible to show only special products, for example:

- show only make-up products of L'oreal Paris
- show only eyeliner products of L'oreal Paris
- show only eye products of L'oreal Paris

idea: make filter function somewhere, save product special infomation in metadata field of product. filter products base on the selected tag and metadata of product.
