### ISSUE TITLE
During checkout, shipping options display error briefly while loading

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1650]
Smooth out the transitions in the checkout.

**Comment by kieckhafer** [comment]
When checking out, and moving from the address step to the shipping step, there is a very brief flash (sometimes not even noticeable) of our error message that shows before the subscription is ready and our shipping options are loaded.

![cart_checkout](https://cloud.githubusercontent.com/assets/4482263/21373654/702dc46e-c6d5-11e6-962e-dfa65e8fe615.png)

I think the best fix for this is using `instance.subscriptionsReady()` to determine if the shipping subscription is ready yet, and if it's not, show a loader until it is. It's still going to be a brief flash, but better a brief loader flash than a red error box.
