### ISSUE TITLE
Settings title bar sometimes does not change to match new settings panel opening

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1653]
For bugs, please fill out the three following sections completely

### Expected behavior
When a new settings panel is opened in the dashbaord, the title bar should change to reflect the new panel.

### Actual Behavior
Sometimes the title bar changes, sometimes it does not.

### Steps to Reproduce the Behavior
Log in as an admin
Open Search settings (click the settings cog)
Open Templates settings

![dashboard](https://cloud.githubusercontent.com/assets/4482263/21363063/d7310a08-c69f-11e6-9fbe-97c36cfffd52.png)

**Comment by aaronjudd** [comment]
This is because of missing i18n translations.

**Comment by kieckhafer** [comment]
This has been cherry-picked and merged into version 0.18.1
