### ISSUE TITLE
Bitcoin payment support

### ISSUE THREAD

**Issue by kwikiel** [reactioncommerce/reaction#166]
This is meteor package for bitcoin support.
https://github.com/codebounty/bitcoin-meteor

Meteor payment will be cool (instant payments)

**Comment by aaronjudd** [comment]
This should be easier to implement now with v0.2.2 allowing multiple payment packages. I'm taking this out of a specific milestone as I'd like to see if anyone in the community will develop this.

**Comment by bluerabbbit** [comment]
Questions I have come up with.
For automation purposes:
Verify a transaction has taken place?
Vendor, if multi-tenancy app?
Add a conversion rate from a trusted Bitcoin vendor.

I'm sure once I started with implementing this a lot more questions will come up.

**Comment by zenweasel** [comment]
Not currently on the roadmap, but we would welcome a PR that added this feature.
