### ISSUE TITLE
Implement discount limit handling

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1662]
Resolve limit handling requirements of #149 and #1512 

- Store discount applied counters on Discounts, after discount is used in copyCartToOrder.
- Store pending counter stats on Discounts when discount applied to order.
- Credit counters if removed from an order.
- Display invalid code notification if attempt to use in DiscountForm component

**Comment by zenweasel** [comment]
@aaronjudd Okay to close? Pretty sure this was completed.
