### ISSUE TITLE
Why reactioncommerce is updating DB this way?

### ISSUE THREAD

**Issue by gepolv** [reactioncommerce/reaction#1665]
https://github.com/reactioncommerce/reaction/blob/master/server/methods/catalog.js

```js
// Line 848:

return Products.update(productId, {
  $push: {
    hashtags: existingTag._id
  }
}, {
  selector: {
    type: "simple"
  }
});
```

Note the first parameter **productId**, should It be {_id: productId}? Is it a bug?

**Comment by jshimko** [comment]
The first argument can be an object ID string or a standard Mongo query object.  Both of these are valid:

```js

Products.update(productId, modifier)
// or
Products.update({ _id: productId }, modifier)
```

http://docs.meteor.com/api/collections.html#Mongo-Collection-update

**Comment by gepolv** [comment]
Maybe a dumb question:

But how "productId" in the first case can identify which field is being searched in collection?
Does the usage in first case imply every document in a collection has a "_id" filed?

**Comment by gepolv** [comment]
I see:
These selectors match the document with that value in its _id field.

**Comment by jshimko** [comment]
Not sure if I understand your question.  Every document in the database has a unique `_id` field, so there isn't a more specific field than that for queries.
