### ISSUE TITLE
Social authentication plugins?

### ISSUE THREAD

**Issue by matheo** [reactioncommerce/reaction#1671]
Just a little question:

Is there a possibility to integrate social authentication?

I just met Reaction and I'm already loving it
but I wondering about the Authentication stuff
as I didn't see anything about it on the docs.

Thanks in advance and thanks for Reaction :)

**Comment by aaronjudd** [comment]
Social authentication can be enabled for Google, Twitter, Facebook in the Dashboard "Account Settings".   You can also add additional authentication methods.  See http://docs.meteor.com/api/accounts.html and https://docs.reactioncommerce.com/reaction-docs/master/reaction-user-accounts

**Comment by matheo** [comment]
Wow, that's awesome!
It's not clear to me because I'm new to Meteor and Reaction but I'm loving this stuff!
Thanks a lot :)
