### ISSUE TITLE
can't install the reaction on ubuntu 14.04 and latest metor

### ISSUE THREAD

**Issue by helxsz** [reactioncommerce/reaction#1673]
For bugs, please fill out the three following sections completely
I followed the instructions of installation

```
# install CLI
npm install -g reaction-cli

# clone Reaction, install NPM dependencies
reaction init

# move into the new app directory
cd reaction

# start Reaction
reaction
# or
reaction run
```

### Actual Behavior

when I run in the non-root role in
`reaction run 
`

it just shows me

> Using settings file at settings/dev.settings.json
> 
> Setting up plugin imports...
> 
> Failed to reset plugins file at /home/xisizhe/Desktop/reaction/client/plugins.js

when I run in the root privilege in 
`reaction run 
`

how could I install it ? 

> Using settings file at settings/dev.settings.json
> Setting up plugin imports...
> You are attempting to run Meteor as the 'root' superuser. If you are
> developing, this is almost certainly *not* what you want to do and will likely
> result in incorrect file permissions. However, if you are running this command
> in a build process (CI, etc.), or you are absolutely sure you know what you are
> doing, set the METEOR_ALLOW_SUPERUSER environment variable or pass
> --allow-superuser to proceed.
> Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
> directory will be incorrect if you ever attempt to perform any Meteor tasks as
> a normal user. If you need to fix your permissions, run the following command
> from the root of your project:
>   sudo chown -Rh <username> .meteor/local

I did the tried 
`sudo chown -Rh helxsz .meteor/local
`
and then tried
`reaction run --allow-superuser --unsafe-perm
`
it didn't work 

### Steps to Reproduce the Behavior

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by jshimko** [comment]
Sounds like you installed things as root that you should not have.  You need to make sure the entire app directory is owned by your non-root user.  Not just `.meteor/local`

**Comment by helxsz** [comment]
thanks, @jshimko
