### ISSUE TITLE
The not tag-related products are showed with click on a tag.

### ISSUE THREAD

**Issue by gpgmbh** [reactioncommerce/reaction#1675]
### Expected behavior

After click a tag, the tag related products should be showed as items of products grid .

### Actual Behavior

The not tag related products are also showed .

### Steps to Reproduce the Behavior

1. Add some products and set some tags for the products.
2 Go to a product detail and click a tag of the product.
   or click  a tag on tag-nav.

**Comment by gpgmbh** [comment]
More about the issue:

With the Guest account the tag related products showed right as wanted. but some product images are not showed. I can see only 37 products with Images. There are about 80 products.

With the Admin account has tag no role, admin see all products and now i see all products with it's image.

**Comment by gpgmbh** [comment]
After some tests:

without admin permission have some products no product images. Tags works well.
with admin permission all products have there product images. But some products are rendered for all tags, although they have  only some tags on db.

**Comment by aaronjudd** [comment]
Are you testing with the `development` branch, or `master`?

**Comment by gpgmbh** [comment]
development branch

**Comment by gpgmbh** [comment]
The reason is the unpublished products.

I have the follow questions:

- Why are some products published, but other not after import from some data source?

- How to make all products published at the same time?
