### ISSUE TITLE
Once checking out no back button

### ISSUE THREAD

**Issue by DarkBlaez** [reactioncommerce/reaction#1677]
Once I am in the process of checking out it would be nice to have a back button or option to go back to cart. Many times I am in the process of checking out and decide I want to add a few more items. Usually the cart icon is visible still or option to back up a step to get to cart. I am not seeing this and perhaps it's an over site on my part.

thanks
DB

**Comment by aaronjudd** [comment]
the checkout has it's own layout, so this could be easily customized.  Design wise though, this is a common choice on the checkout though, the point being that there should be no ui/nav distractions on the checkout (ala amazon).

**Comment by aaronjudd** [comment]
@rymorgan we may want to revisit this, but the back button isn't standard, so I think we're good here for now. @darkblaez minor update though, so if you want to PR, we'll take a look
