### ISSUE TITLE
product details page bad rendered on mobile divice

### ISSUE THREAD

**Issue by gpgmbh** [reactioncommerce/reaction#1679]
product details page bad rendered on mobile divice, tested with develop branch.

**Comment by gpgmbh** [comment]
the page redered right with iphone simulation of google developer tools. but redered bad with my iphone 6.

**Comment by gpmall** [comment]
tested with safari on ios 8.3.

**Comment by gpmall** [comment]
after update ios to 10.2. the issue is as https://github.com/reactioncommerce/reaction/issues/1695

Summary:

bad render of product details page with safari on ios 8.3.
safari flex-wrap not working with iso 10.2

**Comment by kieckhafer** [comment]
We are closing this in favor of #1695.
