### ISSUE TITLE
Tax completion filing for orders

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1692]
Implement order completion for AvaTax and [TaxCloud](https://dev.taxcloud.com/guides/the-most-important-step-order-completion). 

Most likely just a hook on copyCartToOrder that submits the completed status.

More details in #972.

- [x] Avalara #1704
- [x] TaxCloud
- [ ] TaxJar

This is biggest single item remaining in this issue to consider these tax modules ready for RC-1.

**Comment by aaronjudd** [comment]
@zenweasel should we close this, and add some specific items for completing a TaxCloud implementation?  @Itsneilpatil what say you?

**Comment by zenweasel** [comment]
I would vote for creating a TaxCloud specific ticket/milestone.
