### ISSUE TITLE
IOS / safari flex-wrap not working

### ISSUE THREAD

**Issue by chluke123** [reactioncommerce/reaction#1695]
The flex-wrap IOS safari issue is pretty well known and unfortunately it seems to be having an impact of the reactioncommerce platform. 

BTW: on a Mac chrome, firefox and safari seem ok and on mobile chrome works as well. The only time I find this error is on an iPhone.

Two example and fixes I would like to share include:

Example 1 - 
Viewing the product details like in the screenshot below, the page is trying to render 2 columns which isn't wrapping. The easiest way I found to fix this is to force the flex-basis to 100% either with .flex(1 1 100%) or -webkit-flex-basis: 100%.

Solution:

.rui.items.flex .item.half {
  flex: 1 1 50%;
  @media @mobile {
    -webkit-flex-basis: 100%;
  }
}
<img width="319" alt="screen shot 2017-01-07 at 11 27 59 am" src="https://cloud.githubusercontent.com/assets/20023331/21739411/fdfc301e-d4cc-11e6-9c72-6bc01c5847bd.png">

Example 2 - 
Product grid...
Solution:

  // Small product: default
  &.product-small {
    @media screen and (max-width: @screen-xs-max) {
      -webkit-flex-basis: 100%;
    }
  }

<img width="318" alt="screen shot 2017-01-07 at 11 38 41 am" src="https://cloud.githubusercontent.com/assets/20023331/21739477/73283fee-d4ce-11e6-96e7-0a9f5c3a80c6.png">

**Comment by kieckhafer** [comment]
Hey @chluke123 thanks for the comment. We love contributions from the community, maybe you could create a PR with your fix in it, and we can pull it in?
