### ISSUE TITLE
reaction-cli doesn't take hyphen separated options

### ISSUE THREAD

**Issue by nenti** [reactioncommerce/reaction#1696]
### Expected behavior
Start reaction with debug port setting for meteor. For using the debugger of vs-code.
Command: reaction --debug-port 5858

### Actual Behavior
--debugPort: unknown option.

### Steps to Reproduce the Behavior
Start reaction with debug port listener enabled on port 5858

I am using a MacOS.
When I use the meteor command to start the reactioncommerce server with --debug-port it works fine.

**Comment by hrath2015** [comment]
you have to use the command `reaction debug`   by default it will listen on port 5858 for server process debugging.

**Comment by hrath2015** [comment]
It is fixed by @jshimko already. Please do `npm install -g reaction-cli` to upgrade to 0.5.3

**Comment by jshimko** [comment]
Thanks @hrath2015!

**Comment by nenti** [comment]
Worked for me.
