### ISSUE TITLE
PDP UX for Shipping, Taxes

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1699]
For implementation of #1618,  we need UX for designed for the following information on product details page:

Dimensions [Width (x) Length, Depth]
Customs Category (select from list)
Tax Code Category  (select from list)

@rymorgan this is likely some additional fields, in the same area vein as the existing inventory, pricing.

**Comment by aaronjudd** [comment]
@lcampanis your feedback on additional fields for customs here would be great.

**Comment by prosf** [comment]
Hi aaronjudd

The Shippo fields required for any type of label (Shipping & Customs) to be generated are:
# weight
# mass_unit (kg, oz, ...)  (Available from Shop's BaseUOM)
# length
# width
# height
# distance_unit (cm, in, ...) (Need Shop's BaseUOM for distance)
Height, length, width and weight of parcel (shippingParcel schema) are the ones needed in the UI.

For international orders requiring a customs declaration, the minimum required fields are :
# mass_unit of item (Available from Shop's BaseUOM)
# value_currency (Available from Shop's currency)
# origin_country (https://en.wikipedia.org/wiki/Country_of_origin)
# description of item (e.g. T-shirt)
`origin_country` and `description of item` are also needed in the UI.

These are just the required ones,in my opinion. More fields are available here:
https://goshippo.com/docs/reference#customs-items-create
https://goshippo.com/docs/reference#customs-declarations

**Comment by aaronjudd** [comment]
@prosf great, thanks. we're discussing the best way to present these in the product detail page, and should begin implementing this week (along with some additional stuff for taxes,etc)

**Comment by zenweasel** [comment]
I think we should probably add a "Tax Description" field that's optional but when filled in is passed along to the tax provider rather than the stock title/description.

**Comment by aaronjudd** [comment]
See the parcel object for shipping: https://goshippo.com/docs/reference#parcels

We'll need all that dimensional data.

**Comment by rymorgan** [comment]
Here's a mock w/ measurements added. And a dropdown for tax codes. For the measurements I added a selector to change your unit of measurement. Check out: https://github.com/reactioncommerce/reaction/issues/1647

![sidebar - pdp reorg - edit variant](https://cloud.githubusercontent.com/assets/20409254/23086739/c90f9108-f523-11e6-9419-0e716280a789.png)
![sidebar - pdp reorg - w unit selector](https://cloud.githubusercontent.com/assets/20409254/23086798/2b5c8762-f524-11e6-8e36-2d23c19cd4b0.png)

**Comment by zenweasel** [comment]
Disregard references to Customs on this ticket. This has now been moved to #1862. Should just be dimensions plus Tax Code.

**Comment by kieha** [comment]
@rymorgan this is what the PDP will look like once I'm done with this ticket
![screen shot 2017-02-24 at 12 59 11 pm](https://cloud.githubusercontent.com/assets/19430095/23299184/99df9b8a-fa91-11e6-9c7a-e7cd49c5fe16.png)

**Comment by rymorgan** [comment]
@kieha This meets the requirement for adding the fields. The UI refactor and cleanup has been broken into another ticket.  See issue below. 
https://github.com/reactioncommerce/reaction/issues/1905

**Comment by kieha** [comment]
@rymorgan noted.
