### ISSUE TITLE
Site name "reaction" hardcoded in notifications "view all" link

### ISSUE THREAD

**Issue by chluke123** [reactioncommerce/reaction#1700]
reaction/imports/plugins/included/notifications/client/components/notificationDropdown.js

Site name "reaction" hardcoded in "view all" link.

**Comment by andela-oakinseye** [comment]
@andela-akolawole 
You may want to look through this ☝️

**Comment by aaronjudd** [comment]
already have a PR in that resolves this..

**Comment by andela-oakinseye** [comment]
Good job @aaronjudd.
