### ISSUE TITLE
[Documentation] How to implement multi seller?

### ISSUE THREAD

**Issue by vivacarvajalito** [reactioncommerce/reaction#1703]
I have read the documentation, and there is no explanation for adding multiple sellers. So please ask if you can help me.

**Comment by ltouro** [comment]
When the Shop is enabled to multi-seller, Users can promote themselves to "Become a Seller". They will gain permissions to perform operations like adding new products, etc.

**Comment by vivacarvajalito** [comment]
Thanks for your answer, what happens is that I do not see where to modify to enable the multi-seller, I also read that there is a module marketplace, that I am reading how to speak it, I have read the documentation and I did not find it, since I thank you very much.

**Comment by mateomorrison** [comment]
Never received a response. How to enable this project @ltouro

**Comment by zenweasel** [comment]
Work on this feature is being done in the `marketplace` branch. It is expected to be integrated after our 1.0 release.

**Comment by mateomorrison** [comment]
@zenweasel Any date whatsoever?

**Comment by spencern** [comment]
Hi @mateomorrison 
We're working on Marketplace / Multi Vendor functionality currently and you are welcome to follow and contribute on the `marketplace` branch.

**Comment by spencern** [comment]
Getting started with marketplace WIP docs available here. Subject to change at any time. 

https://docs.reactioncommerce.com/reaction-docs/spencer-marketplace-docs/getting-started-with-reaction-marketplace

**Comment by zenweasel** [comment]
The docs are available [here](https://docs.reactioncommerce.com/reaction-docs/master/merchant-shop-setup) now. Closing this issue.

**Comment by gorfadvijay** [comment]
any updates on this ???
