### ISSUE TITLE
Avalara tax reporting

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1704]
Implement Avalara Tax reporting.  

Currently we've implemented rate look up, the next part of the process is reporting the rates when an order has been completed.  TaxCodes (assignment on the PDP, and submission during lookup) are also a requirement for implementation. 

Documentation: http://developer.avalara.com/avatax/

Related to #1692 and #1699.

**Comment by zenweasel** [comment]
Should reporting be something that you have an option to turn on/off or just happens automatically when you are using this API?

**Comment by aaronjudd** [comment]
Good question, I guess it would be nice to have it as an option that could be disabled.  I can see just wanting to use the tax rate lookups, and nothing else.

**Comment by zenweasel** [comment]
Closed via #1733 . Next stage in #1793
