### ISSUE TITLE
Create "getPackageData" global helper

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1707]
So that we don't need all of these versions of this:

```
+Template.myTempalte.helpers({
 +  packageData() {
 +    return Packages.findOne({
 +      name: "reaction-xxxxxx",
 +      shopId: Reaction.getShopId()
 +    });
 +  },
```

**Comment by aaronjudd** [comment]
I think @lcampanis made something like this didn't he?

**Comment by lcampanis** [comment]
Not a exactly a global helper, but the function behind it - might want to bring that in along with a new global helper
https://github.com/reactioncommerce/reaction/pull/1669/files#diff-e0509424f4672c76deaab12707ba478dR226

**Comment by zenweasel** [comment]
Need to verify this is done

**Comment by zenweasel** [comment]
We have `getPackageSettings` and `getPackageSettingsWithOptions`. Closing
