### ISSUE TITLE
Some i18n mapping fixes

### ISSUE THREAD

**Issue by chluke123** [reactioncommerce/reaction#1708]
Two that I have found so far:

1. In "notificationDropdown.js" it refers to "notifications.body.noNotifcations" but should be "notifications.body.**noNotifications**"

2. "availableOptions" should be under "productDetail" and not shop

**Comment by aaronjudd** [comment]
i18n also needs to move into `import/plugins/include/notifications/server/i18n` as well (the i18n doesn't need to be in the `private/data/i18n`.
