### ISSUE TITLE
A few UI related change suggestions (Will help a lot with mobile devices)

### ISSUE THREAD

**Issue by ch-luke** [reactioncommerce/reaction#1710]
1. In dropdown.js when logging out redirect to home page (else you may get some permissions error or info page). Also do a page reload as the home / landing page seems to lock if you don’t.
`"click #logout": (event, template) => {
  event.preventDefault();
  template.$(".dropdown-toggle").dropdown("toggle");
  // Meteor.logoutOtherClients();
  Meteor.logout((error) => {
    if (error) {
      Logger.warn("Failed to logout.", error);
    }
    // Always return to home page
    Router.go("/");
    Router.reload();
  });
},`

2. In full screen mode (i.e. 992px and over) when logged in as Admin and open any product the screen width is distorted and Admin column / panel is hidden.

3. Changing the quantity in the “Add to cart” button is pretty difficult to do on a mobile. One possible suggestion is to include + and - buttons like the image below

<img width="586" alt="screen shot 2017-01-12 at 1 00 52 pm" src="https://cloud.githubusercontent.com/assets/20023331/21880181/179a81cc-d8d0-11e6-9130-eca3d90da363.png">

4. Profile page doesn’t fit / wrap on mobile. Suggest changing the primary div class from "flex flex-column flex-align-center flex-2x container-lg” to “… container-xs”

5. Footer does not stay down. Impacts many pages including both admin sections like accounts but also front end customer pages like notifications and even the product grid (if you only have a few products ). A solution to this could be to implement a flex-box for the main tag.

E.g.
`.page #main {
  height: 100vh;
  display: flex;
  flex-flow: column;

  .header {
    .flex(0 1 88px);
  }

  // Main section which grows to fit 100% of remaining gap
  .section {
    .flex(1 1 auto);
  }

  .footer {
    .flex(0 1 150px);
  }
}`

6. Using the 375px media break (aka iPhone) for the following discussion. I have found with a few changes the theme / layout can handle mobile, but we need to incorporate the following guidelines:

- Look at reducing padding / margin sizes in general (i.e. even 20px padding left and right really reduces screen real-estate. (e.g. main menu icons - cart, notifications & product details …)

- Dropdown boxes like notifications, language select (which I show even on this small media), login & account details, search etc need some tweaking ...
i. Reduce the min-width size to 250px (e.g. the notifications dropdown in 290 and half hidden)
ii. Move lesser important items to the vertical menu (e.g. search & lang select)
iii. For all screen sizes change dropdown position (e.g. right edge of dropdown is in-line with the right-edge of the menu icon:
.notify-drop.dropdown-menu {
  left: auto !important;
  right: 0px;
  margin-top: 0px;
  min-width: 250px !important;
}
And then for 375 media add "right: -50px !important;" (edges don’t align but at least full boxes are shown )

**Comment by aaronjudd** [comment]
We are in the middle of a UIX focused release.  We're trying to get through as many of the issues that are labeled UIX, https://waffle.io/reactioncommerce/reaction?label=UIX but are primarily focused updated the dashboard, admin, and product management (release 0.19 + UIX): https://waffle.io/reactioncommerce/reaction?label=UIX&milestone=v0.19.0

We'll be continuing a focus on UI in 0.20, so some of this items may be addressed in these next two releases (particularly admin and dashboard items).
