### ISSUE TITLE
[Marketplace] Add shop settings panel in Profile page for Sellers to change their default shop settings

### ISSUE THREAD

**Issue by lcampanis** [reactioncommerce/reaction#1711]
In a marketplace setup where the Marketplace module is enabled, Sellers should be able to change their default shop settings. 

The `sellerShopSettings` template will be part of the Marketplace module in order to differentiate the parent from the child shop and allow for granularity between shop settings.

The seller shop settings will consist primarily of the following fields:
- Brand Image
- Shop Name
- Primary Contact Email
- Keywords
- Description
- Default Currency (new)
- Shop URL (domain, subdomain, path - soon)
For simplicity, this will be placed in the User Profile and be visible once the user has `Become a Seller`.
![image](https://cloud.githubusercontent.com/assets/670954/21894508/27a7c120-d8e8-11e6-87f3-46b4727c111d.png)

With those settings in place, it should be easy to port this functionality over to the existing Shop General Settings ActionView (https://github.com/reactioncommerce/reaction/blob/release-0.19.0/imports/plugins/core/dashboard/client/templates/shop/settings/settings.html#L35-L47), so that any shop owner can change their default currency as well.

The following is currently under development, any thoughts please let us know..

**Comment by lcampanis** [comment]
PR submitted for review #1758

**Comment by spencern** [comment]
Closing this as we merged #1758
