### ISSUE TITLE
Fix defaultRoles typo in RC docs

### ISSUE THREAD

**Issue by lcampanis** [reactioncommerce/reaction#1721]
In https://docs.reactioncommerce.com/reaction-docs/development/plugin-routes-6
```javascript
function addRolesToVisitors() {
  // Add the about permission to all default roles since it's available to all
  Logger.info("::: Adding about route permissions to default roles")
  const shop = Shops.findOne(Reaction.getShopId());
  Shops.update(shop._id, {
      $addToSet: { "defaultVisitorRole": "about"}
    }
  );
  Shops.update(shop._id, {
    $addToSet: { "defaultRole": "about"}
  });
}
```
Change `"defaultRole": "about"` to `"defaultRoles": "about"` (notice `s`)

This can soon be replaced with: https://github.com/reactioncommerce/reaction/pull/1669/files#diff-8efd71b38bf2153707a7eb6da1e58579R242

**Comment by zenweasel** [comment]
@aaronjudd @lcampanis Should we move this to an issue on `reaction-docs`?
