### ISSUE TITLE
[Marketplace] Catalog

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1731]
A new implementation of main layout that uses a (new) Catalog collection, and when enabled a catalog layout would replace (or augment) the shop specific product grid #799.  The Catalog collection (really, the publication and Client collection) should be a normalized product + content catalog.  All shared common properties of the content and product catalog could potentially be normalized here to allow  shop specific way filtering content that can be cross merchandised. It would will be useful for this to be a server collection that would be populated by `Products` and `Content` collection hooks when items are published. The catalog can implement some additional logic for a publishing workflow (publish to my shop, publish to other shops, don't accept content published by others, and provide for bulk editing of mutual property values ). 

The catalog layout will contain both content and products, so there will be some additional layout option controls need, possibly just a version of the current product grid ++, but I'd likely looking for a pure React implementation here.

**Comment by aldeed** [comment]
No longer relevant
