### ISSUE TITLE
Fix addBodyClass on notFound page

### ISSUE THREAD

**Issue by lcampanis** [reactioncommerce/reaction#1734]
Since the "not found" page isn't a registered route, there is no way of getting the routeName or theme for that route and the function breaks when the Not Found page is loaded.

`addBodyClass` should add an `app-not-found` class to the body when loading that view.

Note: There is still no clear way of how to get the current route theme though, since there is no route declared for not found. There should be a declared notFound route with a theme assigned or a global DEFAULT_THEME (food for thought)

**Comment by mikemurray** [comment]
Merged changes into 0.19.0
