### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by SotirisValogiannis** [reactioncommerce/reaction#1768]
I see in the files that there is a a greek translation but I don't see it a menu item in the languages? Is not ready yet or something else? I can help with this.

**Comment by aaronjudd** [comment]
Hi! Yes, that's a recent addition, I'll add to the default data for 0.19.  

In the meantime,  you can add ```
 {
      "label": "Διάλεξε γλώσσα",
      "i18n": "el",
      "enabled": true
  } 
```

in the `private/data/Shops.json` `languages` object to add Greek.

**Comment by SotirisValogiannis** [comment]
Thank you!
