### ISSUE TITLE
Add enable/disable currency settings under localization

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1773]
Since the drop-down, just a few currencies are disabled by default, but we actually a support a ton of currencies, so shop operators should be able to configure which ones they want to support.

**Comment by kieckhafer** [comment]
Language and currency dropdown should not show if only one of the respective options is active. Currency should replicate language dropdown functionality.

**Comment by rymorgan** [comment]
We can add a component like the one from: https://github.com/reactioncommerce/reaction/issues/1797

**Comment by rymorgan** [comment]
Let's use the same kind of sidebar design we're using for localization. 

![currency-sidebar](https://cloud.githubusercontent.com/assets/20409254/23671080/d0a3b882-031e-11e7-9f95-a7e4d7b92236.png)
