### ISSUE TITLE
Standard PayPal payments

### ISSUE THREAD

**Issue by shtefcs** [reactioncommerce/reaction#179]
Hi guys,

I installed yesterday reaction on my DO. Is there anyway users can pay with their paypal balance, and not only with CC ?

**Comment by aaronjudd** [comment]
@shtefcs we've made a bunch of updates to the payment packages, and I was looking at this request.  Did you make any progress on your own?

**Comment by shtefcs** [comment]
Hey @aaronjudd . I didn't as we talked , I started creating my own shop app. But could use some help or points from Reaction.

**Comment by aaronjudd** [comment]
@shtefcs cool, well @bstocks is going to take this one as he's been working on payment packages.

**Comment by shtefcs** [comment]
super :)

**Comment by aaronjudd** [comment]
See: https://github.com/reactioncommerce/reaction-paypal/issues/7 and https://github.com/reactioncommerce/reaction/issues/96

**Comment by aaronjudd** [comment]
@jgladch @aldeed I think @bstocks and @evliu got this almost completed but couldn't get the callback to return to the checkout page.

**Comment by aaronjudd** [comment]
Also saw a bug in the error handling.  Enter an invalid cvv entry (use "asd"), client handles the error ok but the server handling is a bit messy.

**Comment by aldeed** [comment]
@aaronjudd where is this at? Have you merged? Do you need any more review or development from me?

**Comment by aaronjudd** [comment]
there is one remaining problem case, everything works fine with a single test session, but open two sessions in the same browser -> there are some issues with the token, sometimes it works, but eventually the state of the cart becomes broken.  I could merge this now, as it's working to the 80%, but it's a scenario that needs to be fixed.

**Comment by aaronjudd** [comment]
@aldeed if you want to take a look, or see if you can replicate I will hold off merging for a few hours, let me know. otherwise I'll merge this and create an issue for that scenario

**Comment by aldeed** [comment]
Can you merge and create an issue for that problem and assign it to me?

**Comment by aaronjudd** [comment]
will do

**Comment by aaronjudd** [comment]
Merged https://github.com/reactioncommerce/reaction-paypal/pull/10
Created https://github.com/reactioncommerce/reaction-paypal/issues/11
Closing this issue as we're not looking at supporting outgoing payments with this, and project goal of an paypal express is now implemented.
