### ISSUE TITLE
Action view always visible at certain screen widths

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1791]
Between 770px & 950px, the actionView is slightly visible off to the side of the screen.

Not sure why or how, but it looks like it's getting set with an embedded `<style>` tag:

`@media only screen and (max-width: 949px){ .rmq-459cc65c{width: 100vw !important;}}`

**Comment by mikemurray** [comment]
Those styles are from Radium (CSS-in-JS) related to resizing the action view based on contents.
