### ISSUE TITLE
Standardize use of cards to use react component

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1795]
For sidebar panels, we want to add the toggle to all panels including toggle on panels.

**Comment by rymorgan** [comment]
We want to convert all card components in the sidebar to consistently use the below component. The first card in the panel sequence. @mikemurray Need to document the react component.  

Instead of using: 
![shop-cards](https://cloud.githubusercontent.com/assets/20409254/22902277/5b79008a-f1e9-11e6-95d8-9705ab352816.png)
![email-card](https://cloud.githubusercontent.com/assets/20409254/22902428/d5e29868-f1e9-11e6-8577-193ec674d3d5.png)
![payment](https://cloud.githubusercontent.com/assets/20409254/22902723/db17142a-f1ea-11e6-812f-94b811f5d8f4.png)
![analytics](https://cloud.githubusercontent.com/assets/20409254/22902797/253986dc-f1eb-11e6-95d2-04b11c7e3a72.png)

We want to use:
![cards-good](https://cloud.githubusercontent.com/assets/20409254/22901364/4250e4b8-f1e6-11e6-8169-97e2202709b3.png)

**Comment by kieckhafer** [comment]
Related to #1835 and #1795. There may not be any work on this ticket in addition to the others mentioned here.

**Comment by kieckhafer** [comment]
Closing in favor of #1835
