### ISSUE TITLE
Localization Sidebar Fix

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1797]
Put all languages is in the card component. 
<img width="404" alt="screen shot 2017-02-07 at 11 23 23 am" src="https://cloud.githubusercontent.com/assets/20409254/22707520/e03add28-ed27-11e6-8f07-20913e9f94eb.png">

**Comment by kieckhafer** [comment]
Is the UI for #1773

**Comment by rymorgan** [comment]
![v1 - sidebar - localization](https://cloud.githubusercontent.com/assets/20409254/23285734/e465bde2-f9e7-11e6-861f-1ae740dd6d41.png)
![v1_-_sidebar_-_localization-annotated](https://cloud.githubusercontent.com/assets/20409254/23285735/e46654d2-f9e7-11e6-94f5-73cf3f038e7b.png)
