### ISSUE TITLE
Remove react-bootstrap

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1836]
`react-bootstrap` should be removed as our own core ui framework duplicates many of the components.

Namely in the `core/email` package.

**Comment by kieckhafer** [comment]
Taking this opportunity to standardize the `Email` dashboard card while removing react-bootstrap.

**Comment by kieckhafer** [comment]
Also taking this opportunity to standardize the SMS dashboard card while removing react-bootstrap.
