### ISSUE TITLE
Sidebar Context Bugs (Grid select bug)

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1838]
If the sidebar is open to another panel besides the grid settings panel, and you navigate to the grid page you should be able to click a product on the grid page and have the settings come up. It doesn't, and instead the previous state persists.

**Comment by impactmass** [comment]
Hi @rymorgan 

I need clarification about how to reproduce this behavior. I currently cannot recreate following the steps described up there.

Here's what I've tried currently:
- From the profile page. I open up the sidebar to "Dashboard"
- Then I click the home link which takes me to a product list grid (I assume this is what you mean by `and you navigate to the grid page`)
- The sidebar switches to "Grid settings" and shows the currently selected product and size settings.


Another approach I tried:
- From the home page, open up the sidebar to "Dashboard"
- Then I click out of the dashboard and immediately the sidebar switches to "Grid settings"
(that doesn't go along with the steps you described)

Please confirm the steps provided.

**Comment by impactmass** [comment]
After further discussions, the issue to fix here is as follow:

Anytime the actionView (i.e the sidebar that opens up for admin actions), is open, it should have some sort of context in it. Right now, sometimes it’s blank. For instance, if the dashboard is open on the PDP page, and then you start to do an order and make it to checkout, you will see the actionView is blank. 

This context should change based on where you are in the checkout… so in this image, while we are at step 3, the actionPanel should show shipping settings:
![](http://i.ato.la/skitch/Cart_checkout_1E6607E1.png)

In this other example, while in step 5, it should show payments: 
![](http://i.ato.la/skitch/Cart_checkout_1E66082B.png)
