### ISSUE TITLE
Endless spinner when going to the product grid in Firefox

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1845]
### Expected behavior
The product grid should always render

### Actual Behavior
If you are an admin user and go to the Dashboard and then try to return to the product grid you an error in the console and the product grid never renders

### Steps to Reproduce the Behavior
1. Login in as admin (in FF)
1. Go to the dashboard
1. Return to the product grid by clicking on "Reaction" in the upper left.
1. Observe endless spinner
1. Observe error in console.

**Comment by kieckhafer** [comment]
Probably something with this error: `ReferenceError: event is not defined`
