### ISSUE TITLE
Clarify Analytics dashboard panels

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1846]
Currently we two panels labeled "Analytics" that both appear to be settings panels. (I think one is supposed to be the analytics dashboard and the other one settings)

**Comment by rymorgan** [comment]
Yes, we're using this for an analytics dashboard. Worked with @spencern to come up with some of the basic analytic we'd like to include: 
Sales stat.	
Aging - Unfulfilled orders w/ in last week (for example), Aging returns for returned items received, 
Coupon Codes - Best selling, time left, User limits, How many left
Best Selling products	
Abandoned carts - last day, week month, date picker
Attribution channels - Social, affilates, product review, search, direct, app, paid ads

**Comment by rymorgan** [comment]
First pass at an analytics dashboard. I am planning on iterating on these to make the analytics more contextual and actionable. 

Zepplin link: 
https://zpl.io/1NYpcJ

Screenshots:
![analytics - dashboard](https://cloud.githubusercontent.com/assets/20409254/26074187/b28384f4-3965-11e7-974e-82b02bd5b79d.png)
![analytics - pdp](https://cloud.githubusercontent.com/assets/20409254/26074188/b463461a-3965-11e7-891e-69ea4d1d7c3d.png)

**Comment by carlos-olivera** [comment]
WOOOW! :)

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #4](https://github.com/reactioncommerce/reaction-feature-requests/issues/4) via [**ZenHub**](https://www.zenhub.com/)
