### ISSUE TITLE
Create "Tax Detail" view in Orders dashboard

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1857]
Related to #1793 

We need to have a view where it can display the taxes charged per line item. There will probably need to be an "Inventory Detail" view and others so we may want to create a UI around that.

**Comment by joykare** [comment]
@rymorgan Some design help on this would be awesome

**Comment by rymorgan** [comment]
![closed-state](https://cloud.githubusercontent.com/assets/20409254/23469494/9e11bb78-fe58-11e6-89bd-b2cc65320d14.png)
![open-state](https://cloud.githubusercontent.com/assets/20409254/23469492/9d4b42ae-fe58-11e6-8979-3ccb0b9e185c.png)

**Comment by rymorgan** [comment]
![open-state](https://cloud.githubusercontent.com/assets/20409254/23469610/e4333550-fe58-11e6-8fb1-6261f85b6c85.png)

**Comment by rymorgan** [comment]
![line-items](https://cloud.githubusercontent.com/assets/20409254/23470065/456f0e10-fe5a-11e6-8978-02058f9602e6.gif)

**Comment by rymorgan** [comment]
@joykare Let me know if you have questions. There are some other clean up items in here that I have been working on too w/ the layout of the type left right. Etc. I want the items to rollover to light grey onhover so that the user knows they are clickable. This action can mimic what happens to lists.

**Comment by joykare** [comment]
@rymorgan cool will hit you up.

**Comment by zenweasel** [comment]
@joykare Can I get an update on the status of this?

**Comment by joykare** [comment]
@zenweasel currently working on it. Its not yet complete.

**Comment by rymorgan** [comment]
![invoice captured - no refund](https://cloud.githubusercontent.com/assets/20409254/23733951/9ed06fd6-0430-11e7-8814-8b2da698484c.png)
![invoice captured - refund applied](https://cloud.githubusercontent.com/assets/20409254/23733952/9ed44372-0430-11e7-8c55-b68c8a219240.png)

**Comment by rymorgan** [comment]
Here's my thinking. Captured total with refund field below it. Then you enter a refund amount, shows a spinner. Refund amount appears inline with the other line items. Feels much easier to read. And I like have the captured and adjusted totals next to each other for clarity for business users.

**Comment by rymorgan** [comment]
@joykare Two small updates to the UI on this. Added a bit more space between the items and the totals. Also added a light grey bg behind the totals/taxes for more visual separation from the items. Thanks! 

![invoice captured - no refund](https://cloud.githubusercontent.com/assets/20409254/23813834/7eef65a8-0595-11e7-9463-af8dcc12203b.png)
![refund](https://cloud.githubusercontent.com/assets/20409254/23813839/856c795c-0595-11e7-9de9-c8f7e66b29b1.png)

**Comment by joykare** [comment]
@rymorgan okay updating that

**Comment by joykare** [comment]
Related to #1849

**Comment by zenweasel** [comment]
Closed via #2005
