### ISSUE TITLE
Add new tax-specfic fields to Accounts management screen

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1860]
Related to #1793 

Making this a separate issue since I don't see exactly where this could go as "Manage Accounts" is pretty much just setting permissions.

We need these new fields under accounts:

* Exemption Code (we have a code here rather than a tax exempt boolean)
* Entity/Use Code (see [this](http://developer.avalara.com/avatax/handling-tax-exempt-customers/) page for a list of standard code, but customers can also create custom code and input their own,.

When these are entered, they need to be passed in along with the cart/order so that the tax amount is reflected correctly.

Additionally the Account ID needs to be displayed and identified.

**Comment by zenweasel** [comment]
There is a problem with this. I did this:

1. Added a customer use type on one customer (my default admin account) and then did an order and it was reported properly.
1. Added another customer

This customer does not display properly and when I submitted an order, that order also used the Customer Use Type from the first account which improperly reported it as Tax Exempt

![cart_completed](https://cloud.githubusercontent.com/assets/72819/23534700/a9094026-fff4-11e6-8fe4-e1f74c1886e3.png)

Also I am also getting a few hundred of this error:

![cart_completed](https://cloud.githubusercontent.com/assets/72819/23534668/78356344-fff4-11e6-8792-9188fcf63698.png)

This is blocking me from completing the audit

**Comment by impactmass** [comment]
Thanks @zenweasel. I'll look into these right away.

To clarify what was said and things to be done:
- Tax Settings should be set at the customer level
- Should the tax settings form be moved to the view seen when the "Manage" button in front of each account is clicked?

**Comment by zenweasel** [comment]
It's not matter of where they show up, but that they only show up for one customer.

**Comment by zenweasel** [comment]
In other words, it seems like the "Tax Settings" screen only shows once for all customers rather than for each customer.

**Comment by impactmass** [comment]
Okay. Got it.

**Comment by impactmass** [comment]
I've resolved the above issues. It's on the main `brent-seun-avalara-taxcompliance-1793` branch. 

The only pending part left is a design modification (this can up after my checkin with Ryan). 

**Design Feedback:**
* Instead of having the form under each user account, show the form in the sidebar that slidesout when the "Manage" button is clicked.

**Comment by impactmass** [comment]
This is now moved to the "Manage" section. It also now works with all accounts (newly added and old). 
I need a review on the approach I took: https://github.com/reactioncommerce/reaction/commit/6c389a57671a9f9f44d4b56295e32af6ed6c6b21

**Comment by impactmass** [comment]
Resolved in #1793

**Comment by zenweasel** [comment]
This has been completed.
