### ISSUE TITLE
Add Shippo customs declaration

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1862]
As originally noted in #1699

Add customs declaration for international shipments in Shippo.

See: https://goshippo.com/docs/international

Will require creating a declaration and attaching to the createTransaction method in `imports/plugins/included/shippo/server/methods/shippoapi.js`

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #5](https://github.com/reactioncommerce/reaction-feature-requests/issues/5) via [**ZenHub**](https://www.zenhub.com/)
