### ISSUE TITLE
review default data, product images

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1864]
Clean up and review default data generally, and revise / update the default example product data, with several products in different configurations, and associated images.

**Comment by spencern** [comment]
Todo:
* [ ] Define New Products
* [ ] Copywriting for new products
* [ ] Images for new products

**Comment by aldeed** [comment]
@zenweasel suggested using the [catalog sample data set](https://github.com/reactioncommerce/reaction-catalog-sample-data) as the default. Makes sense to me.

**Comment by spencern** [comment]
This makes sense, but currently that is a private repo.

**Comment by zenweasel** [comment]
Also, it's all in Mongo backup format which I am not sure we could do as part of our bootstrap process. Would need to be converted to JSON or something.

**Comment by aldeed** [comment]
Moved to https://github.com/reactioncommerce/reaction-feature-requests/issues/72
