### ISSUE TITLE
Out of stock when quantity > 0 & replenishing stock

### ISSUE THREAD

**Issue by amyamber** [reactioncommerce/reaction#1867]
### Expected behavior: 

When I add a product variations with quantity more than 0, eg. 5, 7, 12 I expect to see that product available for sale once it's published. When quantity reaches 0 I would like to have an option to replenish the stock instead of creating new stock item from scrap.

### Actual Behavior:

 When I add product variations with quantity more than 0 I can see 'sold out' icon on the item. Once 'sold out' is visible I cannot change the quantities. 

### Steps to Reproduce the Behavior: 

Add a product with (eg. colour) variations.

**Comment by kieckhafer** [comment]
Once a product has options / 2nd level variations, the inventory is stored on each of these options, instead of on the top level product.

**Comment by kieckhafer** [comment]
Closing this ticket, @amyamber please re-open if you believe this doesn't fix your issue.
