### ISSUE TITLE
UI: In Product Page in Administrator mode, the Product's featured-image template doesn't get updated properly when the image gets deleted

### ISSUE THREAD

**Issue by lcampanis** [reactioncommerce/reaction#1871]
This behaviour can be seen in two scenarios

**A. Scenario:**
1. Upload the first image of the product (don't publish it).
2. Delete this image.
3. Upload a new image.
Instead of the new image, the deleted one will be shown again in the featured-image template

**B. Scenario:**
1. Upload more than one images (don't publish them)
2. Delete the Featured one
The thumbnail of the image will be removed correctly, but the deleted image will not be removed from the featured-image template

**Comment by kieckhafer** [comment]
This is fixed in the latest release. It was fixed at some point in `0.19.0`, and I just tested in the current `development` branch
