### ISSUE TITLE
Support multiple products/tags with same title/name

### ISSUE THREAD

**Issue by katiebvogel** [reactioncommerce/reaction#1873]
We need to be able to import and display multiple products with the same title.
We also need to be able to import and display multiple tags with the same name.

**Comment by aaronjudd** [comment]
to recap offline conversation about this, the imports accept a "key" parameter. The product itself is fine with duplicated title, but the import should not use "title" alone in the key in this case.

**Comment by aaronjudd** [comment]
This is a duplicate of #2061
