### ISSUE TITLE
Build Avalara-specific logger, log viewer and log pruner

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1875]
Related to #1793 

Part of the Avalara requirement is that we log all requests/responses in a separate logger which should be visible from the admin interface. And since this will create a lot of log entries this will need to be automatically pruned by a set time interval (default 30 days) that should be configurable from the admin interface.

**Comment by aaronjudd** [comment]
Can't we just a bunyan logger?  (if they want this functionality, they could use a log viewer?)..

**Comment by zenweasel** [comment]
Yes, I will be using a bunyan logger. Not sure what "they could use a log viewer" means though. So are you suggesting they use a log viewer to view their logs? Hold up now.....

**Comment by aaronjudd** [comment]
Loggly.

**Comment by zenweasel** [comment]
The Avalara requirement says "so it needs to be retrievable by an end user (or an administrator) It should be specifically Avalara service calls."

So do you think sending to Loggly meets that requirement?

**Comment by aaronjudd** [comment]
> Enables detailed AvaTax transaction logging within the application including capture of round-trip processing time.We need the complete xml request/response for each call made to Avalara services. It does not need to run all the time as we understand the DB will grow unnecessarily large – you are free to only log the last week, 30 days, custom, or have a control for the next N hours, etc. The spirit of the requirement is to assist customers and support in troubleshooting exercises, so it needs to be retrievable by an end user (or an administrator) It should be specifically Avalara service calls.

I guess this sounds more like the email logging... reusable?

**Comment by zenweasel** [comment]
Yeah, that more along the lines of what I was thinking.

**Comment by zenweasel** [comment]
Completed
