### ISSUE TITLE
Sort Dashboard panels

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1877]
Maybe I am missing something but it feels like these should be sorted alphabetically?

**Comment by aaronjudd** [comment]
I actually asked the same thing in a design meeting, but I forgot the answer. They're sorted by priority though (for which I believe there is a plan for the order). If it was alphabetically, does that work for all languages? (they'd be sorted by the untranslated package text).

**Comment by aaronjudd** [comment]
We have agreed NOT to sort alphabetically. as it doesn't work for all languages. The design direction is to focus on the "natural" steps that one needs to configure the shop.  We need to just update the labels to reflect @rymorgan's (spreadsheet of labels).
