### ISSUE TITLE
Receive "Email Notification Sent" when submitting an incorrect refund

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1881]
### Expected behavior
When a refund fails it shouldn't tell you that an email notification was sent.

### Actual Behavior
I receive "Email Notification Sent" toast

### Steps to Reproduce the Behavior
1. Place an order
1. Approve and capture the order
1. Try to issue a refund for more than order total
1. Observe "Email Notification Sent" message

**Comment by michael-alade** [comment]
A WIP has been opened for this #2200

**Comment by michael-alade** [comment]
Currently fixing little nitpicks on the PR #2200

**Comment by zenweasel** [comment]
Closed via #2200
