### ISSUE TITLE
npm update - nodemailer

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1895]
v3+ of nodemailer will potentially be a breaking change. We need to carefully update.

**Comment by jshimko** [comment]
We currently can't update to Nodemailer 3.x.  It's Node >= 6 only.

**Comment by aaronjudd** [comment]
We should fork nodemailer 4.0.1 as it's now no longer maintained and update the engine/requirements back to our node... (well, at least look at this).

**Comment by jshimko** [comment]
Fixed in #2427.  Nodemailer has been forked and added to Reaction.
