### ISSUE TITLE
Minifier related deployment issues

### ISSUE THREAD

**Issue by ch-luke** [reactioncommerce/reaction#1896]
Please need your help, as of now my live site is down.

Been struggling to build a docker image the last 2 days, with errors related to code minification. After a bit of research it seemed to be related to the standard-minifier-js package and the handling of es2015 related code/packages. I'm also aware of the new Meteor update as well.

Looked through the reaction dev commit history and there are some changes that suggested to switch the package to abernix:standard-minifier-js, guess this is good short term solution. 

Great! Can now publish to docker hub again and the site looks good. No browser console errors and nothing showing in the docker / app logs. Website works on the desktop using safari & chrome and in the IOS simulator and my iPhone 6 & iPad.

But then my friends let me know that it doesn't work for them on their Android phone since I updated the site and also it doesn't load on my iPhone 5. Since switching the packages the site doesn't really want to load on most mobiles.

Have you had any problems with testing  abernix:standard-minifier-js?
Any suggestions on how to debug this?

**Comment by zenweasel** [comment]
@chluke123 Are you still having this issue?

**Comment by aaronjudd** [comment]
Replaced abernix:standard-minifier-js in #2371 with the standard-minifier-js@2.1.0.

**Comment by aaronjudd** [comment]
Closing in favor of #2629
