### ISSUE TITLE
aftership.com - Tracking solution

### ISSUE THREAD

**Issue by shtefcs** [reactioncommerce/reaction#190]
I just found https://www.aftership.com/ tracking solution and seems really useful for tracking orders. They support 217 couriers and prices seems okay for me https://www.aftership.com/pricing. Also they provide API https://www.aftership.com/docs/api/4.

What do you think about integrating with Reaction ?

**Comment by aaronjudd** [comment]
We've now added a Shipping schema and some wiring for some more complex rate calculating, as well as multiple shipping packages. I'm working still on the shipping package, but it should be reasonably easy to start a package like this now.
