### ISSUE TITLE
App tests should not use local private settings

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1900]
When running app tests, it will use the local `reaction.json` which can result in inconsistent results.

We should probably create a `test_settings.json` file and have tests run against that if it exists.

**Comment by aaronjudd** [comment]
@jshimko this should also be considered in env loading of settings.

**Comment by aldeed** [comment]
Closing this because I'm pretty sure it's fixed, and if not, Meteor tests are on their way out.
