### ISSUE TITLE
please receive a patch soon for this section. And thank the development team more.

### ISSUE THREAD

**Issue by longnguyenit94** [reactioncommerce/reaction#1903]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Steps to Reproduce the Behavior

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by jshimko** [comment]
Since this doesn't follow the criteria for submitting an issue, I'm going to close this for now.  Feel free to reopen it if you have an actual issue and all of the required details are filled out.

> For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.
