### ISSUE TITLE
Top-Level Tags Menu Side-Bar Glitch

### ISSUE THREAD

**Issue by katiebvogel** [reactioncommerce/reaction#1906]
When screen size forces Tags navigation to be a left-hand menu, we should be able to scroll and click.

Currently, we have to click, on a top-level tag to see the secondary options.  When we go to scroll through the secondary/tertiary tags, the options "grey out". 

![screen shot 2017-02-27 at 12 10 03 pm](https://cloud.githubusercontent.com/assets/16321291/23373864/6ee289ee-fce7-11e6-96fe-fc52bd7ce120.png)
![screen shot 2017-02-27 at 12 13 24 pm](https://cloud.githubusercontent.com/assets/16321291/23373877/78bb8326-fce7-11e6-98f2-f5daa4f2971d.png)
![screen shot 2017-02-27 at 12 13 33 pm](https://cloud.githubusercontent.com/assets/16321291/23373889/87005402-fce7-11e6-84ff-8ae85e0e6d1f.png)

**Comment by impactmass** [comment]
Description of the bug I've seen here:
* When there are many tags with children tags under them, only the last parent tag's children is clickable. The other tags' children cannot be clicked because the brown overlay covers them (as shown in the screenshots posted above).

**Comment by impactmass** [comment]
This is fixed and merged into the working release-20 branch `wip-release-0.20.0`.
Should we close this out @kieckhafer?
