### ISSUE TITLE
Cannot set property 't' of undefined. Labels missing

### ISSUE THREAD

**Issue by colmandesilva** [reactioncommerce/reaction#1908]
I am brand new to Reaction. Really eager to try it out. I got everything installed and running. However, when i navigate around I get the below console error.

![image](https://cloud.githubusercontent.com/assets/2522005/23382472/4b921044-fd10-11e6-9915-5f4e8fafc66c.png)

### Expected behavior
No javascript errors

### Actual Behavior
Uncaught TypeError: Cannot set property 't' of undefined ----- modules.js?hash=c4f639d…:53710

### Steps to Reproduce the Behavior
Fresh install

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by zenweasel** [comment]
Fixed via #1902
