### ISSUE TITLE
Downloadable digital products

### ISSUE THREAD

**Issue by joseangeljimenez** [reactioncommerce/reaction#191]
Hi all,

First of all, kudos to all of you (core team and contributors) for your great effort!
I could not find a feature in the roadmap or vision cards, which I think may be a great addition to your feature set: support for downloadable digital products with one or many files. Few eCommerce frameworks support this, however, it is a growing area of global ecommerce.

I apologize if this is not the right way to suggest a new feature.

Best regards,
José Ángel Jiménez

**Comment by MBybee** [comment]
Not seeing a whole lot of progress on this. I might just take a crack at it, as I need this too. Is there a plugin framework guide somewhere for Reaction?

**Comment by aTylerRice** [comment]
Any progress on this? I may take a crack at it if not

**Comment by aaronjudd** [comment]
@aTylerRice I don't think so.  @reactioncommerce/core will be happy to help guide you if you start a PR and hit some rough spots. This is a common request.

**Comment by aTylerRice** [comment]
should I fork the dev branch or the stable or it doesn't matter? I need it on a stable branch myself though

**Comment by aaronjudd** [comment]
start with the `development` branch, there's some [guidelines in our docs](https://docs.reactioncommerce.com/reaction-docs/master/contributing-to-reaction), and lot other info you'll need.   We keep `development` in a stable pre-release state.  Release/Feature branches is where we break stuff.

**Comment by aTylerRice** [comment]
Can I just git clone that branch and the reaction cli will still work?

**Comment by aaronjudd** [comment]
`reaction init -b development` will do the trick.

**Comment by aTylerRice** [comment]
oh awesome thanks! i'll try to get this done by tomorrow night. Seems really straight forward. I actually built a digital asset store with meteor from scratch and decided I needed a lot more features then I found you all!

**Comment by aTylerRice** [comment]
Alright so took my a while to familiarize myself with the code base a bit more and to get up and running!

I want to stick to all your conventions.

I was thinking that maybe variantmedia could be used to store the digital downloads for a product? Or a new collection could be made as well? Whats everyones thoughts? Trying to put together a rough overview of how to approach this...

**Comment by zenweasel** [comment]
Not currently on the roadmap, but we would welcome a PR that added this feature.

**Comment by gnarhard** [comment]
@zenweasel I am seeing the "wontfix" label on this and it got me REAL bummed out. Is there any talk of bringing back the digital download product feature?

**Comment by brent-hoover** [comment]
@GraysonE No idea as I haven't worked at RC for a while. I would think that this would be something that RC would expect implementors or 3rd party intgegrators to implement, but again I have no insight into what the focus will be since the acquisition by MailChimp

**Comment by kieckhafer** [comment]
Thanks @zenweasel!

@GraysonE, as commented, at this time, this would be something a third party would need to implement. [Extending ](https://docs.reactioncommerce.com/docs/how-to-extend-product) our [products plugin](https://github.com/reactioncommerce/api-plugin-products/tree/trunk/src) and / or [creating a fulfillment method for digital products](https://docs.reactioncommerce.com/docs/how-to-create-a-fulfillment-methods-plugin) would probably be the best place to start.
