### ISSUE TITLE
Strange dashboard display when cancelling out of Paypal Express

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1916]
### Expected behavior
Dashboard should display normally

### Actual Behavior
When you return from cancelling a Paypal Express order the dashboard displays on the left below the checkout.

![cart_checkout](https://cloud.githubusercontent.com/assets/72819/23406111/55135126-fdf8-11e6-93fa-b09588f90f77.png)

### Steps to Reproduce the Behavior
1. Login as administrator
1. Create an order and start to checkout using Paypal Express
1. When login screen loads, cancel out.
1. Click on Dashboard icon
1. Observe some seriously wacky dashboard display

**Comment by kieha** [comment]
When canceling from PayPal, one is redirected to the checkout page. However, when the `coreAdminLayout` is rendered, the `onDestroyed` method is called as well:
```
Template.coreAdminLayout.onDestroyed(() => {
  $("body").removeClass("admin");
});
```
 and it removes the `admin` class from the body which it needs for the styling. This is why the dashboard is muddled. However, when you refresh the page, it works perfectly and the `onDestroyed` method is not called unnecessarily.
So on the initial redirect, the body has the classes `app-cart-checkout default`, but on refresh, and how it should be, is `app-cart-checkout default admin`.

**Comment by zenweasel** [comment]
While this **is** a regression, it also will **only** happen to admins who cancel out of Paypal payments, and then they would just need to refresh. So I feel like this should be really low priority ticket.

**Comment by aanchirinah** [comment]
Followed the reproduction steps thoroughly and still couldn't experience the Dashboard glitch. After consulting with @zenweasel, I will close this ticket.
