### ISSUE TITLE
Update read-only Quantity in top-level variant when children are present

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1919]
When a Variant has options / second-level variants, inventory is moved away from the top-level, and onto the child.

However, in the Edit Variant screen, we still show the most recent quantity of top-level variant products, never updating it to use the combination of second-level variants, which is the true inventory count.

We should update the top level variant field to show the correct inventory numbers.

![inventory](http://i.ato.la/skitch/Basic_Reaction_Product_1E661984.png)

Related to #1867

**Comment by zenweasel** [comment]
Closed via #2065
