### ISSUE TITLE
Meteor 1.4.3.x update

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1924]
Update to Meteor 1.4.3.x 

Currently blocked by https://github.com/meteor/meteor/issues/8427

```

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /tools/fs/optimistic.js:204:17
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/Users/a
```

**Comment by stunjiturner** [comment]
any fix coming? workaround  i would like to test the new application 0.19

**Comment by aaronjudd** [comment]
@stunjiturner `meteor update --release 1.4.3.2-beta.0` has a patch for this (according to the progress on 8427)
