### ISSUE TITLE
"Deny when out of stock" behavior improvements

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1928]
I just noticed two issues with this behavior that probably need to be fixed. One minor and one sort of important.

1. If I have 5 in stock and I add 10 of something to my cart my quantity is reduced to 5 (which makes sense) but I don't receive any sort of alert that my quantity has been changed and the "Added to Cart" alert shows the original quantity, not the adjusted quantity. This could lead to user confusion. I feel like at one time there was an alert that said "Your quantity has been adjusted".

2. If I have 5 in stock and I add 10 to my cart my quantity is reduced to 5. If I add another 20, the total quantity is now 10. So the "Deny when out of stock" is only the affecting the quantity I can add to cart, not the quantity **in** my cart. So I could have 10 in my cart even though there are only 5 in-stock, which I would think is exactly what "Deny when out of stock" is trying to avoid.

**Comment by joykare** [comment]
related #1935

**Comment by joykare** [comment]
Added an alert that pops up when quantity is adjusted. Working toward changing the checkout pop up to signal exactly how many items have been added to cart.

**Comment by zenweasel** [comment]
Closed via #2034
