### ISSUE TITLE
Making a stripe package

### ISSUE THREAD

**Issue by yanndebelgique** [reactioncommerce/reaction#193]
Hi,

Have you thought about making a stripe package as well? That would be sweet.
I would love to contribute and make this package but would need some directions at first.

Cheers

**Comment by aaronjudd** [comment]
Closing, see (needs testing): 
@eahefnawy
https://github.com/reactioncommerce/reaction-stripe
https://github.com/reactioncommerce/reaction-braintree

@aaronjudd
https://github.com/reactioncommerce/reaction-paypal

@taylorsmithgg
https://github.com/taylorsmithgg/reaction-auth-net
