### ISSUE TITLE
How to go about making your own order validation and processing without credit card payment

### ISSUE THREAD

**Issue by yanndebelgique** [reactioncommerce/reaction#194]
Hi,

I looking into a solution that would allow certain types of users to place orders where the client pays cash in the store. We are a brick and mortar gourmet business so we have a lot of people who come in for advice before placing an order. What is the best way to do this? How is an order processed ? What in the code in should I need to change to allow this?

**Comment by aaronjudd** [comment]
Cash payments in #129. Package docs,etc have been updated since this issue was created, but a some diagrams, workflow schemas are still needed.
