### ISSUE TITLE
Standardize index template and default layout customization

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#1943]
### Expected behavior

Replacing the index route layout / templates should be updated to use the `Reaction Registry` and `ReactionLayout`. This will put them in line with how all other templates and layouts are defined.

### Actual Behavior

Index layout, default layout, default workflow are all hardcoded in code `client/defaults.js` and the only way to override them is to use Session variables.

**Comment by aaronjudd** [comment]
Closing - insufficient details.
