### ISSUE TITLE
Update User Preferences to store per shop

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1950]
Currently, we are storing user preferences in an object on the user profile, but not specifying which shop the preferences are related to.

We need to update how we do this to add another level to the object, to store preferences per shop.

For instance, in `core/main.js`

```
setUserPreferences(packageName, preference, value) {
    if (Meteor.user()) {
      return Meteor.users.update(Meteor.userId(), {
        $set: {
          [`profile.preferences.${packageName}.${preference}`]: value
        }
      });
    }
    return false;
  },
```

Should be
```
setUserPreferences(packageName, preference, value) {
    if (Meteor.user()) {
      return Meteor.users.update(Meteor.userId(), {
        $set: {
          [`profile.preferences.shopIdGoesHere.${packageName}.${preference}`]: value
        }
      });
    }
    return false;
  },
```

**Comment by aldeed** [comment]
User prefs are no longer used at the moment. They may be reimplemented in the future, but this is done for now.
