### ISSUE TITLE
Dashboard panel keeps re-opening during checkout

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1953]
### Expected behavior
If I have configured shipping already, the shipping configuration panel should not keep opening

### Actual Behavior
Every time I move along a step (go to enter an address, choose shipping) the dashboard opens to the shipping panel.

### Steps to Reproduce the Behavior
1. `reaction reset` to `wip-release-0.20.0` branch
1. Configure shipping and payment (Flat Rate and Shipping)
1. Attempt to checkout
1. Observe dashboard panel keeps opening (shipping panel when in address and shipping, payment when in payment area)

**Comment by impactmass** [comment]
This wasn't 100% solved, so re-opening it.
Discovered that sometimes shipping still opens up the sidebar when it should not.

**Comment by impactmass** [comment]
Fixed in #2010
