### ISSUE TITLE
Dashboard Icon/Cart disappears at some widths as admin

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1958]
### Expected behavior
Dashboard icon and cart should be visible at all time

### Actual Behavior
At around 900px and then at around 1200 the dashboard icon and cart disappear. This does not happen as a non-admin (cart is always visible).

http://g.recordit.co/XDIi2opUX8.gif

### Steps to Reproduce the Behavior
1. Login as admin
1. Adjust the width of your browser window as seen in gif
1. Observe that dashboard icon and cart are not always visible

**Comment by zenweasel** [comment]
This isn't a regression as it appears in the current `master`

**Comment by Akarshit** [comment]
Not able to reproduce in `release-1.8.0`.

**Comment by zenweasel** [comment]
Closed can't reproduce. @Akarshit in the future if you can't reproduce please close the ticket.
