### ISSUE TITLE
Formatting broken on completed page when using non-USD

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1960]
### Expected behavior
All currencies should be formatted correctly

### Actual Behavior
Subtotals wrap strangely
![cart_completed](https://cloud.githubusercontent.com/assets/72819/23819452/6732f202-0641-11e7-9fba-aaba730225c4.png)

### Steps to Reproduce the Behavior
1. `reaction reset -n`
1. Change currency via dropdown to PHP (probably works with Euros as well)
1. Place an order
1. Observe formatting on completed page

It doesn't seem to be related to # of digits as I did an order for $133,000.00 and it still formatted correctly.

**Comment by andela-aatanda** [comment]
I'll reproduce this behavior and work on solving it over the next couple of days

**Comment by andela-aatanda** [comment]
@zenweasel I can't seem to find `PHP` in the currency dropdown. Has `PHP` been deprecated?

**Comment by zenweasel** [comment]
It works with any non-USD currency but also

![cart_completed](https://cloud.githubusercontent.com/assets/72819/24408725/083960ba-1401-11e7-9b2b-6741787c2fbc.png)

**Comment by andela-aatanda** [comment]
Gotcha

**Comment by zenweasel** [comment]
Closed via #2062
