### ISSUE TITLE
Lots of Browser Console Messages when Paypal is enabled.  Is it Normal?

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#1963]
### Expected behavior
Browser Console should not have so many messages.
### Actual Behavior
See the Pic Attached.
### Steps to Reproduce the Behavior
enable paypal and see it in browser console on checkout page. 
![consolepaypal_li](https://cloud.githubusercontent.com/assets/14071646/23824771/9899f5fa-06a2-11e7-8dc1-dcc48335888f.jpg)

**Comment by aaronjudd** [comment]
Yes, that's normal output from PayPal. They're quite messy. That's only when using the sandbox.
