### ISSUE TITLE
Reaction freezes when starting first time at "setting up style imports.."

### ISSUE THREAD

**Issue by hmouhtar** [reactioncommerce/reaction#1964]
### Expected behavior

Should start the app on the port 3000

### Actual Behavior

It just stays on "setting up style imports.." when I run the command `reaction run`

### Steps to Reproduce the Behavior

Install reaction-cli, start a new reaction folder and use the command `reaction run`

![bug](https://cloud.githubusercontent.com/assets/15305350/23826686/1a5853aa-0678-11e7-8554-1ba10987d791.png)

**Comment by anooj1483** [comment]
Same issue here.

**Comment by zenweasel** [comment]
@hmouhtar From your screenshot can I assume you are using Windows? Have you installed all the requirements as described in the docs?

**Comment by hmouhtar** [comment]
@anooj1483 I solved it out just tipping "meteor" on reaction root dir, it seems that meteor wasn't installed or something like that.

**Comment by hrath2015** [comment]
As confirmed on gitter by @hmouhtar  closing this.
