### ISSUE TITLE
[PDP]  Origin Country Selector Issues

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1978]
z-index issue on selector:

![basic_reaction_product_and_google_hangouts](https://cloud.githubusercontent.com/assets/439959/23914090/23690fd0-08a2-11e7-9d00-c5304b927ebd.png)

Duplicate field on product variant.. (is this supposed to be here? If so, why isn't a select?)

![basic_reaction_product_and_new_issue_ _reactioncommerce_reaction](https://cloud.githubusercontent.com/assets/439959/23914171/61df927a-08a2-11e7-9cca-8b75d1cce52d.png)

**Comment by zenweasel** [comment]
I removed the duplicate field, but @mikemurray and @kieckhafer are discussing how to resolve the z-index issue

**Comment by zenweasel** [comment]
Closed via #1986
