### ISSUE TITLE
Email logging panel closes every time an email is sent

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1985]
When the email logging panel is open, and a new email is sent - aka the publication is updated - the email logging panel automatically closes.

**Comment by zenweasel** [comment]
It also closes every time the browser is resized.

**Comment by andela-aatanda** [comment]
There's a PR open for this [here](https://github.com/reactioncommerce/reaction/pull/2205)

**Comment by zenweasel** [comment]
Closed via #2205
