### ISSUE TITLE
Panel expander arrows display on top of other elements (z-index issue?)

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#1987]
In the dashboard, the circle + arrow buttons sometimes show on top of other elements

![](https://cloud.githubusercontent.com/assets/439959/23914090/23690fd0-08a2-11e7-9d00-c5304b927ebd.png)

( initially logged in #1978 )

**Comment by zenweasel** [comment]
@kieha What's the status on this? Are you working on it?

**Comment by kieha** [comment]
Had picked it to start working on it while my PR was being reviewed, but I had to put it on hold to make changed on the PR.

**Comment by andela-aatanda** [comment]
There's a PR for this issue [here](https://github.com/reactioncommerce/reaction/pull/2211)
