### ISSUE TITLE
Tax Code field not styled correctly when populated

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1988]
### Expected behavior
All fields should have consistent styling

### Actual Behavior
When populated, Tax Code field is not using the proper styling.

![basic_reaction_product](https://cloud.githubusercontent.com/assets/72819/23928198/61debd52-0959-11e7-916f-b5b2a2d16daa.png)

### Steps to Reproduce the Behavior
1. Enabled a tax provider that provides tax codes (e.g. Avalara or TaxCloud)
1. Go to PDP
1. Observe Tax Code field

Seen in PR #1974

**Comment by kieha** [comment]
@zenweasel by the proper styling you mean `code | description`?

**Comment by zenweasel** [comment]
No, if you look closely you can see the styling of the box itself (border color, box size, etc) is different than the rest of the fields on the PDP

**Comment by zenweasel** [comment]
I think it's the styling that happens when you attach the `form-control` class. Probably getting lose because it's not technically an autoform field at that point.

**Comment by kieha** [comment]
Alright. Got it.
