### ISSUE TITLE
PDP: Holding Mouse to Drag vertical/Horizontal scroll bar does not work.

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#1995]
### Expected behavior
Should be able to move the scroll bar while holding the mouse.
### Actual Behavior
No response while holding the `mouse over` and moving the bar.
### Steps to Reproduce the Behavior
Try this On Fresh RC0.20.0 install on Dev branch.  Login As  admin. Open PDP.  Move scroll bar while holding the mouse. To test Horizontal scroll, open dashboard.

**Comment by kieckhafer** [comment]
Can you provide an example of what you're trying to do, with visuals if possible? When testing, we were able to scroll while holding the mouse.

**Comment by zenweasel** [comment]
No details provided. @hrath2015 Can you please reopen if you are still seeing this?
