### ISSUE TITLE
Import was skipped.

### ISSUE THREAD

**Issue by dshitik** [reactioncommerce/reaction#1999]
Import was skipped (import "./styles/main.less") in the file - ../imports/plugins/included/default-theme/client/index.js
Because of this, the default theme styles are not enabled.

**Comment by zenweasel** [comment]
@dshitik I am not able to replicate this using the current `master`, Do you have the latest version of the `reaction-cli`?

**Comment by dshitik** [comment]
In the latest version, everything is fine.
