### ISSUE TITLE
Error when reordering variants

### ISSUE THREAD

**Issue by dshitik** [reactioncommerce/reaction#2004]
Look. When I change the location of product variants in the product card and press the "publish" button, I get the following error:
Exception in delivering result of invoking 'revisions / publish': TypeError: Can not read property 'handle' of undefined

Version of product - v.1
![2017-03-16 11-38-59](https://cloud.githubusercontent.com/assets/9960071/23987959/3a17ab50-0a3d-11e7-9d2b-8330ef85a14e.png)

**Comment by zenweasel** [comment]
@dshitik Can you provide some replication instructions so we can properly try to debug this?

**Comment by dshitik** [comment]
1. I create 2 or more variants in the card product.
2. Swap variants.
3. I click the "publish" button.
The following occurs:
A notification appears that the data has been saved, but it gives the above error.
In the correction to the previous message - all the same, I can change the data and publish the individual options and if I click the "publish" button, the data will be correctly saved to the database. However, this error only applies to the user interface, it does not display up-to-date information about which options are published.

**Comment by dshitik** [comment]
And just want to say that when moving options from place to place, icons with pencils remain yellow. Total: it is necessary to correct ui.

**Comment by zenweasel** [comment]
@dshitik Can you explain what you mean when you say "swap variants"?

**Comment by dshitik** [comment]
I explain, moving variants of product from place to place. Sorry for my english.

**Comment by zenweasel** [comment]
I have verified I get this when I add a variant and then reorder.

### Steps to reproduce

1. `reaction reset`
1. Navigate to the PDP
1. Add a couple more variants
1. Publish
1. Reorder variants
1. Publish
1. Observe error

**Comment by zenweasel** [comment]
Closed via PR #2033
