### ISSUE TITLE
Get 404 error when attempting to create an option on a new product

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2008]
### Expected behavior
An option should be created

### Actual Behavior
Receive "Oops. This is not the product you were looking for"
![add_option_404](https://cloud.githubusercontent.com/assets/72819/24023941/8c3d28d0-0aea-11e7-8340-e0ce0aac63da.gif)

### Steps to Reproduce the Behavior
1. Fresh db on `master` branch
1. Create a new product
1. Enter title, description, etc.
1. Click on the pencil icon next to "Label"
1. Click on the plus icon to add a new option
1. Observe the error message and it's not possible to create a new option

**Comment by andela-aatanda** [comment]
I've been able to confirm this behavior and I think we need to look into the cause of this behavior.

**Comment by zenweasel** [comment]
Closed via #2021
