### ISSUE TITLE
Meteor installation performance

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2011]
Look at CDN, caching, distribution solutions for distributing reaction faster.  Meteor and Atmosphere can be unbelievably slow to download in some places, and I feel like we could do a better job if we just bundled and distributed this ourselves along with our own Meteor build/release.
Looks at solutions that can include all the dependencies as well for the current reaction release.

**Comment by spencern** [comment]
@aaronjudd is this an issue that you'd still like someone to investigate or is it resolved better by our removal of major Atmosphere dependencies and migration towards npm style imports?

**Comment by aaronjudd** [comment]
We're moving to docker caching, so this will be pretty irrelevant soon.
