### ISSUE TITLE
Archive Product function still labeled "Delete Product"

### ISSUE THREAD

**Issue by NahomAgidew** [reactioncommerce/reaction#2014]
When in edit mode, I tried to delete a product by clicking on the delete (red trash can) button but instead it asks if I want to archive the product and it will archive it. Even when I hover over the trash can button it has a tooltip that says: "Delete Product".

**Comment by andela-akolawole** [comment]
@NahomAgidew What version of reaction are you running?

**Comment by NahomAgidew** [comment]
The latest i.e v 1.0

**Comment by zenweasel** [comment]
We don't allow deleting a product once it's been created, but agreed it should say Archive everywhere, not Delete.

**Comment by zenweasel** [comment]
Closed via #2030
