### ISSUE TITLE
Can't enter a credit card number like it says you should

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2015]
### Expected behavior
You should be able to enter a card like the placeholder says you should and have it work
![cart_checkout](https://cloud.githubusercontent.com/assets/72819/24086425/1aaca8be-0d4a-11e7-9ef2-db98a9b3e542.png)

In reality you should be able to enter a card number with or without space, with or without dashes and have it work.

### Actual Behavior
Depending on the payment processor either you can't enter it that way before running out of room or it throws an error.

### Steps to Reproduce the Behavior
1. Start Reaction
1. Configure shipping and payment as Authorize.net
1. Enter address and select shipping
1. Observe that if you enter a card with spaces you get an error
1. Select Stripe as Payment processor
1. Observe that you can't enter a credit number with spaces without running out of room

**Comment by jshimko** [comment]
There are several great libraries out there for that.  A couple I've looked at in the past...

https://jessepollak.github.io/card/
https://creditcardjs.com/

**Comment by zenweasel** [comment]
Yeah, this seems like a great chance to replace this with a component rather than having 5 or 6 different versions for each payment method? @mikemurray

**Comment by aaronjudd** [comment]
See #2040

**Comment by kieckhafer** [comment]
Closing in favor of #2198 , which will provide validation.
