### ISSUE TITLE
Develop and codify an LTS strategy

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2016]
Going forward we probably need to declare certain versions as "LTS" (or whatever we want to call it) and ensure we backport all bug fixes to that version. This will allow users to get bugfixes without having to always upgrade to the current version, or cherry-pick bugfixes like Spencer does.

And we just need to write up some sort of document that makes it clear what we do and do not support and for how long.

This might already be in the works, not sure.

**Comment by spencern** [comment]
This is definitely something that will be highly valuable. Will make it much easier on developers who for some reason or another are not updating to later versions of the code.

**Comment by aaronjudd** [comment]
This is part of a larger discussion, but this seems like a lot of work, versus, enforcing a smooth update / migration / transition approach for updates.

**Comment by zenweasel** [comment]
Let's publish our policy that "To be able to upgrade and have Long Term Support you need to have your changes in a plugin and upgrade regularly, if you can't do something with a plugin, please open an issue"

**Comment by zenweasel** [comment]
@machikoyasuda Is this documented somewhere? I wonder if we can close this now?

**Comment by zenweasel** [comment]
Closing to Review roadmap
