### ISSUE TITLE
Unable to add manual shipping methods

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2018]
Unable to add manual shipping methods, error match failed validation.

Originally reported by @cindyfirestone

**Comment by zenweasel** [comment]
I'm not able to replicate this in the current `master`
Should I work with @cindyfirestone on this directly?

I did see this issue when using an older version of the `example-plugin` which had an older `Shipping.json`.

**Comment by zenweasel** [comment]
I can see this issue on `hello.reactioncommerce.com`. It doesn't look like `Shipping.json` was properly imported (there are no existing methods). Although I am not entirely sure why that causes this error (adding a new method).

**Comment by zenweasel** [comment]
Closed via #2025
