### ISSUE TITLE
Redesign Admin Dashboard

### ISSUE THREAD

**Issue by federicocrivellaro** [reactioncommerce/reaction#2020]
Dashboard cannot have the same layout as the customer website. 

Customers and Administrators have completely different needs.

For example a customer will mostly look at products by imagen, but the administrator will probably search by SKU, if the ecommerce has many products. 

In this case a vertical table of products with a SKU column will improve considerably the readibility of the SKU making easier to search for a product. 

My suggestion is to have a Shopify like dashboard which is considered one of the best on the market in terms of Usability.

**Comment by loanlaux** [comment]
I agree with @federicocrivellaro. Reaction's dashboard is a bit confusing in terms of UX.

**Comment by zenweasel** [comment]
@federicocrivellaro / @loanlaux Thanks for your input.

In our next big push we will be working on a Catalog feature which will have a lot of tools much more targeted at administrator so I think you will like some of the things that are coming out of that. I don't have anything to point to right now but I should in the next week or so.

In terms of the UX of the Dashboard, we did just finish a whole re-work/redesign of the layout of the dashboard so we probably won't be going back to the drawing board any time soon. However if you have specific suggestions we certainly would welcome those, or even better, a PR.

Right now this ticket doesn't really contain any actionable items so I am not really sure what we can do with it. If you could give us some specific feedback on what you feel is confusing that would be helpful.

**Comment by aaronjudd** [comment]
Closing this issue, as it's covered in many of the ongoing design elements we're adding (list views, etc).   All good points though.
