### ISSUE TITLE
Revisit import scripts

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2024]

**Comment by zenweasel** [comment]
We need a way to selectively backup and restore the registry and translations files as well as a simple solution to export/backup data (including orders, etc).

Right now the only option is a `reaction reset` which is not going to be a viable option for people in production obviously.

**Comment by mikemurray** [comment]
Some thoughts

- Through the UI / CLI, be able to update registry / layout data / re-import default settings
- Ability to reset / update settings for any package?
- The reaction importer should only import once for anything. Subsequent imports should not overwrite changed data. This works for registry, but doesn't seem to apply to Shops, Tags, Products, etc.
- Packages should have examples of migrations to help with upgrades
- Maybe `Reaction.registerPackage()` could be able to be called with a version number and work like a migration (wrap the migration functionality)?
- Maybe allow a setting for the importer to allow for `import once` / `import always`, so you can better control when data will get reimported.

**Comment by aldeed** [comment]
Closing this as mostly done in 2.0.
