### ISSUE TITLE
How can we run it as a Service through SERVICE command?

### ISSUE THREAD

**Issue by w3update** [reactioncommerce/reaction#2028]
I am trying by creating **reaction.service** at /etc/systemd/system
with following script.
-------------------------------------------------------------------------------------
[Unit]
Description=reaction
[Service]
WorkingDirectory=<FullDirectoryLocation>/reaction
ExecStart=/usr/bin/node reaction
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
-------------------------------------------------------------------------------------
but its not working.
Is there any working version?

**Comment by jshimko** [comment]
This isn't really an issue with Reaction, so [the forum](https://forums.reactioncommerce.com/) is probably a better place for a support discussion like this.

However, right off the top of my head, it looks like you're trying to run a development version of the app as if it were a production build.  Running `/usr/bin/node reaction` is not a thing.  The `reaction` command is a CLI for local development.  It's not an entrypoint of a Node app.

If you're trying to set up a production deployment, I recommend you check out [our Docker deployment docs](https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-docker).  That's the official deployment method and the only one we can provide support for.  It's certainly not the only way to deploy, but it's significantly simpler than any of the alternatives.  Creating a production bundle and running it as a Node app is advanced developer territory.  Using Docker completely takes care of that for you.

The simplest thing you can do to run a production image...
```sh
# on your production host
docker run -p 80:3000 -d reactioncommerce/reaction:latest
``` 
The app will then be available at `http://<your_host_ip>`

I also highly recommend familiarizing yourself with how [Meteor](https://www.meteor.com/) works.  It's the foundation of Reaction and is not quite like any other framework you may have used in the past.

Core concepts and app structure
https://guide.meteor.com/

API docs
http://docs.meteor.com/

And definitely get to know Docker if you're going to be dealing with deployment...
https://docs.docker.com/

Good luck!
