### ISSUE TITLE
Move/add variant icon buttons.

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2031]
1. Move Public/Private icon button from body of the page to sidebar. 
2. When the variant is set to private, fade it out
3. Change placement of icon buttons for variant options in sidebar
4. Add ability to clone a variant option

![pdp_-_action_view-2](https://user-images.githubusercontent.com/20409254/30404551-fefeaee0-989b-11e7-94fb-63a52704d442.png)
![pdp_-_action_view-1](https://user-images.githubusercontent.com/20409254/30404550-fefe8014-989b-11e7-930e-9f4d0cf67bd4.png)

**Comment by rymorgan** [comment]
Related to https://github.com/reactioncommerce/reaction/issues/1647

**Comment by aaronjudd** [comment]
Demo'ed this morning... so assigned to @kieckhafer

**Comment by kieckhafer** [comment]
^^ Yes this is done in PR #2893

**Comment by kieckhafer** [comment]
Closed by #2893
