### ISSUE TITLE
Create Admin Log/Revision History

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2035]
It's like `git blame` but for product/shop administration.

There needs to be a way to log every change made to product/ shop configuration, who made it, etc., and possibly revert that change.

Since this can add a lot of overhead I see this as an "optional" plugin that could be disabled and mostly implemented with hooks. Obviously `revisions` started this but there is no history there (or is there?)

**Comment by spencern** [comment]
From Shopify's admin panel
![image](https://cloud.githubusercontent.com/assets/1203639/24930363/7619c7f8-1ec6-11e7-9f19-7676656da2f4.png)

**Comment by aaronjudd** [comment]
Feature request that requires more definition to meet our current issue guidelines.

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #18](https://github.com/reactioncommerce/reaction-feature-requests/issues/18) via [**ZenHub**](https://www.zenhub.com/)
