### ISSUE TITLE
Convert navigation bar to react and keep all current functionality.

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2041]
Convert navigation bar to react and keep all current functionality. 

Related to #2040

**Comment by andela-aatanda** [comment]
I'm going to work on this over the next couple of days.

**Comment by zenweasel** [comment]
So just for discussion purposes here is my breakdown of the pieces of the navigation bar

![reaction_and_slack_-_reaction](https://cloud.githubusercontent.com/assets/72819/25656075/00cd4bda-302a-11e7-8923-07dd964be881.png)

So there are tickets for Tag navigation, Alert and Dropdowns. Cart drawer is already converted as is the Content Bar. So is this ticket just for converting the top level Navbar pieces? And I wonder should we [ull in the Search modal into this portion of the rewrite?

**Comment by joykare** [comment]
Notes:
Work on branch `joykare-main-navbar-2041`
- Changed `brands` template into react (thats the `REACTION` tag on the nav)
- Moving over the functions into a container
- This particular branch can't be merged in before the other navbar parts have been converted to react
