### ISSUE TITLE
Convert to react: Tag navigation

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2043]
Convert to react: Tag navigation related to #2040

**Comment by mikemurray** [comment]
There are React components available for the tag navigation (listed below). They are currently used for the PDP admin view, and should be able to be used for the tag navigation.

**here**
`imports/plugins/core/ui/core/client/compnents/tags/`
`imports/plugins/core/ui/core/client/containers/tagListContainer`

**Comment by impactmass** [comment]
Some notes:
* Working Folder: `imports/plugins/core/ui-tagnav/`
* Existing `tags` component is very tailored to Product page. Needs to made a little more generic to be extended as tagNav.

Current progress: [branch](https://github.com/reactioncommerce/reaction/tree/seun-tagnav-react-conversion-2043). Still largely WIP.

**Comment by impactmass** [comment]
Status: Getting close to finishing. 
- Tags List is in place
- Dropdown (on hover) is in place 

Todo:
- [ ] Editing functionality (in-prog) -- 
* Setting up the editing functions in d component
* Edit button permission
- [ ] Responsiveness on mobile screens

**Comment by impactmass** [comment]
I'm not done with this ticket yet. I'm getting close... but I keep discovering a few more things to resolve around the nesting of the Tags (parent and subTags). 

Currently, it looks like: 
![screenshot 2017-05-09 22 57 46](https://cloud.githubusercontent.com/assets/5229321/25874548/f6e39846-350a-11e7-9f33-e8081b02640b.jpg)

The styles are not perfect yet... and the saving of the tag still broken. So.. I'll have to hold off making a WIP PR and resolve those first (but that will be alongside fixing issue on permissions #2231).

**Comment by impactmass** [comment]
Pending: 
* Fix re-rendering bug (doesn't show newly added subtag until refresh)
* Drag and drop on tagGroups
* Styling fixes (edit button, hamburger icon)

**Comment by impactmass** [comment]
Resolved in #2306
