### ISSUE TITLE
Convert to react: Alerts, Language and other dropdowns

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2044]
Convert to react: Alerts, Language and other dropdowns related to #2040

**Comment by zenweasel** [comment]
@rymorgan Can you clarify what you mean by Alerts here? Do you mean the notifications?
![reaction](https://cloud.githubusercontent.com/assets/72819/25654704/b3574c3e-3024-11e7-8a23-1e21ca4e5ef9.png)

**Comment by joykare** [comment]
Notes:

- Branch `joykare-navbar-dropdowns-2044`
- @rymorgan hoping that alerts means the notifications. If so its already in React.
- Starting with the currency dropdown /client/modules/i18n/templates/currency

**Comment by joykare** [comment]
Notes:
- Using DropDownMenu Component on  `/imports/plugins/core/ui/client/components/menu`
- Working on the language dropdown `/client/modules/i18n/templates/header/i18n.html`

**Comment by joykare** [comment]
@mikemurray I'm using <DropDownMenu /> component for the drop downs and I'm trying to figure out a way to close the `menu` when one of the `menuitems` is selected. Any ideas on how to make that happen?

**Comment by mikemurray** [comment]
**This will require some additions to both DropDownMenu and the Popover component**

1. The Popover manages state for the open / close status. That will need to be exposed to props so it could/should be managed by the parent component. __Probably best to remove all the state management from that component and replace with callbacks, and accept the open/close state as props.__
1. The dropdown itself menu should have an open/close state var. 
1. In the `handleMenuItemChange` callback in the dropdown would set the open/close state and pass that to the popover component via props.

**Comment by joykare** [comment]
Thanks that worked @mikemurray
