### ISSUE TITLE
Update Summary Card for Orders

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2045]
Put summary into collapsable card. 
Clean up layout of panel typography
Add order customer name and order number to top of card
Add status label  

![orders summary card](https://cloud.githubusercontent.com/assets/20409254/24380790/fedd0d5a-1301-11e7-91fc-e2d84cd3883a.png)

**Annotated card**

![orders_summary_card-annotated](https://cloud.githubusercontent.com/assets/20409254/24380877/6207c744-1302-11e7-82da-ad8b0bfc06ac.png)

**Comment by joykare** [comment]
@rymorgan @mikemurray Could I just change this over to react? Changing the templates would be just as much code refactor.

**Comment by mikemurray** [comment]
You are free to make anything and everything React!

**Comment by rymorgan** [comment]
Looking really good! A couple of small things to finish it up.  See notes below. 

<img width="752" alt="2045-notes" src="https://cloud.githubusercontent.com/assets/20409254/24931537/84693630-1ec2-11e7-9b55-09c5590406db.png">

**Comment by rymorgan** [comment]
@mikemurray We should put this in the `<SettingsCard>` component in another PR. So if you can fix the gap we're good to go on this issue.

**Comment by zenweasel** [comment]
Closed via #2105
