### ISSUE TITLE
Product Grid React conversion

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2050]
Part of #2040 and takes care of `Product Grid` and parts of `Search`

---

The product grid to be converted to a set of react components.

Things it must do:

- Merge the product grid and search grid into the same set of components. Product grid to receive the hover-over-preview of the search grid.
- Still support the multiple sizes of product images
- Work at least as well as they do now

**Comment by michael-alade** [comment]
I understand the logic of how this should be implemented.

#### Questions
- Should this productGrid component get it's only data through a container component or should it expect it from another parent component or blaze template?
- Should the multiple sizes be disabled for search modal?

@mikemurray

**Comment by mikemurray** [comment]
@michael-alade 

- Product grid should get data from some parent container component
- Search grid should only be one size

**Comment by kieha** [comment]
Notes:
* branch name - `kieha-product-grid-conversion-2050`
* Main folder - `imports/plugins/included/product-variant/client/templates/products/productGrid`
* Approach - start with `item.js` and work my way up
