### ISSUE TITLE
Update login views to react

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2055]
Part of #2040 and takes care of part of `Checkout` and `Navigation bar`

---

Login views to be converted to react

Things it must do:

- Work as well as it does now 
- Defaults to sign in for dropdown / 404 page
- Defaults to register for checkout page
- Hopefully clean up some of the logic by moving to react. ( This is an OLD OLD OLD blaze component, so it uses some old techniques )

**Some views to be converted**
- Sign in, including (password, google, facebook, twitter)
- Register, including (password, google, facebook, twitter)
- Reset password
- The modal that pop up when using a verification email. ( you can get this when you invite a user from the accounts admin )

**Places it's used**

- 403 page
- login dropdown in navigation bar #2044
- checkout login panel #2052

**Comment by kieha** [comment]
Notes:
- Branch: `kieha-login-views-to-react-2055`
- Starting with converting the sign in page `client/modules/accounts/templates/signIn`

**Comment by kieha** [comment]
Update:
- Finished sign in and sign up conversion
- Working on reset password

**Comment by kieha** [comment]
Update:

- Sign in/sign up/reset password forms all done
- Working on modal that pops up when resetPaswordLink/registerLink sent in email is clicked

**Comment by kieha** [comment]
#### Notes
- For some reason, the `onClick` call on the Register/Sign In/ResetPassword/Social Login links/buttons doesn't work. Currently looking into it. I've used `onDoubleClick` on them instead.

**Comment by kieha** [comment]
Update:

- Solved the `onClick` problem: it now works. Work on this ticket is done.

**Comment by kieha** [comment]
Closed via #2306
