### ISSUE TITLE
When a product is made visible its variants remains invisible in database

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2059]
### Expected behavior
when a product is made visible all the variants should also be made visible
### Actual Behavior
Only top level product is updated in DB.
### Steps to Reproduce the Behavior
Create a new product
Add variants.
Click the eye icon in toolbar to make is visible.
Check in DB(revisions) only Top Level product is set to `isVisible=true`

**Comment by michael-alade** [comment]
A PR has already been opened for this issue #2222

**Comment by zenweasel** [comment]
Closed via #2222
