### ISSUE TITLE
Bug: After tracking # added, saved to db with null val

### ISSUE THREAD

**Issue by evliu** [reactioncommerce/reaction#206]
After a successful transaction, the order is shown in the admin Orders dashboard page, and after a tracking number is added, it doesn't move over to "prepare for shipping" nor does the tracking number actually save when checked through mongo. Tested on v0.2.1 branch right now of reaction-core.

I have another instance where the orders did move to "prepare" section, but there's no way to move it to the next sections nor delete the orders or manipulate it. Thx!

**Comment by aaronjudd** [comment]
from @taylorsmithgg
The problem in workflow where the order gets stuck in payment processing
```
 Template.stateHelperPayment.events
  'click .btn': () ->
    OrderWorkflow.shipmentShipped @
```
There we are.
Add that
```
 <template name="stateHelperPayment">
    <span class="pull-right">
      <button class="btn btn-success">Order Shipped</button>
    </span>
</template>
```
And that
