### ISSUE TITLE
Importing products with similarly named options causes those options to be overwritten

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2061]
### Expected behavior
You can have options that have any name and they should export/import properly

### Actual Behavior
Receive error on startup and documents are destroyed
```
02:12:13.150Z  WARN Reaction: Error while importing to Products: After applying the update to the document {_id: "XsaJDRK3YqjA9FpkG" , ...}, the (immutable) field '_id' was found to have been altered to _id: "TFT7bsxtbKqKZjNbv"
```

### Steps to Reproduce the Behavior
1. Create two products each with identically named options (like Size 9, Size 10, etc)
1. Export those products to replace the default products
1. `reaction reset`
1. Start Reaction
1. Observe that one of the products will show sold out as it no longer has any options

**Comment by Akarshit** [comment]
@zenweasel I am not able to follow the reproduction steps.
> Export those products to replace the default products

How do I do this?

**Comment by zenweasel** [comment]
https://docs.reactioncommerce.com/reaction-docs/master/plugin-fixtures-5

**Comment by Akarshit** [comment]
@zenweasel This is happening because [here](https://github.com/reactioncommerce/reaction/blob/release-1.8.0/server/startup/load-data.js#L40) we are saying to load the products with `title` as the identifier. 
So if a product with the same `title` already exists we update it [here](https://github.com/reactioncommerce/reaction/blob/release-1.8.0/server/api/core/import.js#L426).

Should I change the "identifier" to use a combination of `title` and `_id`?

**Comment by zenweasel** [comment]
I thought it only used that to determine which collection but if that's how it's determining uniqueness can we use `handle` which I believe needs to be unique, or `handle` + `shopid`?

**Comment by Akarshit** [comment]
@zenweasel I checked it again because I saw a piece of code written to prevent this(the issue) from happening.
I am not able to reproduce this issue in `release-1.8.0`.

**Comment by zenweasel** [comment]
@Akarshit If you can't reproduce something with older issues like this, just make that note and go ahead and close. We can always reopen if it pops up again, but there's nothing else that can be done here.
