### ISSUE TITLE
Propose/Implement React client testing framework

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2066]
Since we are doing a full push to convert to React, this seems like a prime time to get some testing in place before we end up with 100+ components without tests. The main thrust of this ticket is not to have every component be tested, but to have something in place where developers can quickly and easily write tests for new components they create (and then we will go back and add tests for existing components).

Steps to complete this ticket

1. Evaluate current options for React testing that will work from the command line and in CI
1. Propose a framework/tooling
1. Create a few example tests for existing components
1. Have these run in CI
1. Write a tutorial on how to create tests for components that also includes best practices

**Comment by joykare** [comment]
Looked into Jest-Enzyme testing.
- Installed jest and enzyme into project on `joykare-react-testing-2066`
- Testing order summary component on same branch (test-run)

**Comment by joykare** [comment]
Hit blocker on testing containers, majorly because of `react-komposer`. Working that out.

**Comment by joykare** [comment]
Pivoted, @zenweasel advised to do example tests on components first.
- Using *selenium-webdriver* for headless browser to run tests on.
- Currently working out integration with CI and reaction CLI

**Comment by joykare** [comment]
@mikemurray I have some babel presets installed for tests to run but when I configure them in the `.babelrc` file `reaction` command fails. Help?

**Comment by joykare** [comment]
*Blockers encountered*
With the babel presets if you run `reaction` the app crashes:
- Babel presets were linked to `.tgz` files on `package.json` so I changed that and linked them to npm. <Still didnt resolve the issue>

*Testing*
To run unit tests that exist:
- `meteor npm install`
- Install `jest` globally on your machine
- Run command `jest`

**Comment by zenweasel** [comment]
Closed via #2170
