### ISSUE TITLE
Hooks are queued and not fired....

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2068]
### Expected behavior
Revision should be created when Product is updated
### Actual Behavior
I added an option to Mid Variant and same time was checking DB for updates.  Found that  no revision created for the  product.  After moving around from Grid back to PDP, I added one more options. Now 2 revisions I could see in DB
### Steps to Reproduce the Behavior
I observed some times in past and today. Not very often though. 
Using ROBOMongo to see DB. Local DB on Dev machine.

**Comment by spencern** [comment]
Can you give more specific steps to reproduce? Even if it involves looking directly at the db, it would be helpful for us if you can list a specific set and order of actions to recreate this problem.

I'm also a little unclear about exactly what kind of update is happening (there are many types of Product updates) and what revision is expected.

**Comment by hrath2015** [comment]
As I said it happens sometimes and I  came across it while investigating  an issue on Price  Display. Sorry no specific steps.  May we can close it for now if comes up again then look into it.
