### ISSUE TITLE
Create spreadsheet of Rules and what functionality they are given permission to

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2075]
This is the first step in getting some framework for validating permissions and writing some tests. While I would like to see functions listed, our first step should be validating user-facing functionality.

I think this ticket can/should replace #797 

Starting out we need something that says something like

### Rule: `createProduct`

 * Sees "create product" icon in top bar
 * Can call `products/createProduct`
 * Can call `products/archiveProduct`

I would prefer something that is included in the code base somehow rather than in a Google doc that's not public. (maybe something in `reaction-docs`?)

**Comment by aaronjudd** [comment]
(oh and yeah, this should be a public doc to make this more clear...)

**Comment by impactmass** [comment]
I'm focused more on #1651 (which is related to this). So this is not getting much of my attention at the moment.

**Comment by impactmass** [comment]
closing in favor of work done in [epic 55](https://github.com/reactioncommerce/reaction/milestone/55)
