### ISSUE TITLE
Meteor dependency!?

### ISSUE THREAD

**Issue by blaasvaer** [reactioncommerce/reaction#2084]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Expected behavior
To have installed reaction dependencies

### Actual Behavior
$ reaction init

Cloning the master branch of Reaction from Github...
Cloning into 'reaction'...

Installing NPM packages...
/bin/sh: meteor: command not found

Error: Node modules were not successfully installed. Exiting.

### Steps to Reproduce the Behavior
Follow instructions on website.

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by jshimko** [comment]
@blaasvaer Please see the install/requirements docs for Reaction.  `reaction-cli` doesn't do all of the initial setup steps for you.  You still need to install the base dependencies yourself.

https://docs.reactioncommerce.com/reaction-docs/master/requirements

Also, in your "steps to reproduce", what instructions are you referring to?  The requirements link above is the official list of dependencies.

**Comment by jshimko** [comment]
`reaction-cli` has been updated to point out how to install Meteor when running `reaction init`.  But please see the requirement docs because almost everything in them isn't optional.
