### ISSUE TITLE
Blank Page on first visit in Safari

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2088]
### Expected behavior
Safari should load the app on the first visit.

### Actual Behavior
Safari shows blank page on first load. Upon a refresh, the app loads.

![image](https://cloud.githubusercontent.com/assets/1203639/24722050/15c538c0-19f7-11e7-9761-54f9fdd82bf6.png)

### Steps to Reproduce the Behavior
Start a new app.
Clear Application Data/Local Storage/Cookies
Visit in safari.

**Comment by lcampanis** [comment]
@spencern we managed to fix this for now by forking it on github. You can fork it into RC or simply replace https://github.com/reactioncommerce/reaction/blob/master/package.json#L94
with: `"transliteration": "git+https://github.com/artlimes/transliteration.git"`, until it's officially fixed.

**Comment by spencern** [comment]
I think we ended up finding the root cause of this (Anonymous users not getting created) and fixed it in #2089

**Comment by zenweasel** [comment]
@spencern Okay to close this ticket?

**Comment by spencern** [comment]
Should be fixed by #2089 so yes.
