### ISSUE TITLE
Phantomjs / prerender.io render blank page

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2090]
This is a port of a bug we had at GetOutfitted

### Expected behavior
prerender.io should be able to render and capture pages from the app.

### Actual Behavior
There's an ES6 javascript error 
```
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
(anonymous function) (f4aee29dfb6196571f0fb3982680e06d921b77b3.js , line 18)
```

### Steps to Reproduce the Behavior
Deploy stock reaction and use prerender.io

**Comment by zenweasel** [comment]
Closed via #2091
