### ISSUE TITLE
Convert to React Router

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2099]
Part of #2040 and takes care of part of `Router`
Related to #2049

---

Convert from FlowRouter to React Router.

Things it must do:

- Must not be a breaking change for those that used the registry to populate their custom routes. 
- Must render a react layout, which means the main app layout needs to be wrapped inside a react component at least.

**This will be a breaking change for those that may have defined routes by means other than the Reaction Registry.**

**Comment by aaronjudd** [comment]
Some other items to consider are documented in #1394
