### ISSUE TITLE
Update to React 15.5

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2100]
Upgrade React 15.5 and fix all depreciation warnings.

More info.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ modules.js:9836
modules.js:9836 Warning: VelocityComponent: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

- Stop use of `React.createClass`
- `PropTypes` must be imported from the `prop-types` package.
- Update all npm packages that have depreciation warnings / make tickets in the respective repos.

**Comment by spencern** [comment]
I experienced this issue when installing today. In addition to the warnings, I experienced missing icons in the admin view.

![image](https://cloud.githubusercontent.com/assets/1203639/24882196/6f694dbc-1dfd-11e7-851f-dba1c99dd366.png)

I pinned react and these packages to `15.4.2` and the icon issues went away too, so I think they are related.
```
── react-addons-create-fragment@15.4.2
├── react-addons-pure-render-mixin@15.4.2
└── react-dom@15.4.2
```

**Comment by aaronjudd** [comment]
@mikemurray  closing.
