### ISSUE TITLE
Orders Page: Update Card Component to Settings Card Component

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2111]
<img width="752" alt="orders - settings card components" src="https://cloud.githubusercontent.com/assets/20409254/24932556/d929bbfa-1ec6-11e7-8864-7c4b99468577.png">

**Comment by spencern** [comment]
@rymorgan is this similar to #2161?

**Comment by rymorgan** [comment]
closing in favor of #2161
