### ISSUE TITLE
Currency and Language dropdown are not disabled on first start

### ISSUE THREAD

**Issue by l0qii** [reactioncommerce/reaction#2113]
### Expected behavior
When I create a Shops.json with only 1 currency and 1 language enabled and start reaction for the first time, the currency and language menus in the header should be disabled

### Actual Behavior
The currency and language menus are still active, each with just the single option showing that I had enabled in the Shops.json

### Steps to Reproduce the Behavior
Copy my Shops.json to private/data
reaction reset
reaction
goto localhost:3000, you will see the menus each with a single option

[Shops.zip](https://github.com/reactioncommerce/reaction/files/915235/Shops.zip)

**Comment by zenweasel** [comment]
I verified that this is true. However as a workaround if you click on "All Off" on both Currency and Language both dropdowns disappear for everyone.

**Comment by kieckhafer** [comment]
Yeah, good idea @zenweasel, I didn't see that ticket initially. I'll pick it up.

**Comment by zenweasel** [comment]
Closed via #2148
