### ISSUE TITLE
Inconsistent Product Image of Cart Items

### ISSUE THREAD

**Issue by andela-aatanda** [reactioncommerce/reaction#2115]
### Expected behavior
When Cart Icon is clicked and drawer opens, products should retain their uploaded images when any of the items in cart are clicked

### Actual Behavior
When one of two products with an uploaded image in Cart is clicked, the other product defaults to the Basic Reaction Product image and vice versa.

### Steps to Reproduce the Behavior
1. Add an image to an option in the Basic Reaction Product
1. Create a new product and upload an image for it.
1. Publish your changes and toggle edit mode
1. Add both the Basic Reaction Product that has an image and the New Product to cart
1. Open your cart and click any of the product and observe that the product image of the other item defaults to no image and vice versa

PS: The following error appears in console: 
```
TypeError: Cannot read property 'refs' of undefined
    at ProductField.<anonymous> (app.js:20270)
    at CallbackQueue.notifyAll (modules.js:89661)
    at ReactUpdatesFlushTransaction.close (modules.js:89384)
    at ReactUpdatesFlushTransaction.closeAll (modules.js:90820)
    at ReactUpdatesFlushTransaction.perform (modules.js:90767)
    at ReactUpdatesFlushTransaction.perform (modules.js:89414)
    at flushBatchedUpdates (modules.js:89497)
    at ReactUpdatesFlushTransaction.close (modules.js:89372)
    at ReactUpdatesFlushTransaction.closeAll (modules.js:90820)
    at ReactUpdatesFlushTransaction.perform (modules.js:90767)`
```

**Comment by zenweasel** [comment]
I was able to reproduce using the instructions provided.

![product_imges](https://cloud.githubusercontent.com/assets/72819/24987519/f79a493e-2032-11e7-8ddc-48c543e9123a.gif)

**Comment by andela-aatanda** [comment]
This behavior is caused by the `href` in the anchor as I noticed that data is been re-fetched for `cartItems` when trying to fetch data for `PDP`

**Comment by andela-aatanda** [comment]
As a last resort on this, `cartDrawer` will be closed when the `PDP` is visited.

**Comment by andela-aatanda** [comment]
Querying the `Media` Collection seems to be generating inconsistent result as redirecting to `PDP` resends query to `Media` Collection

**Comment by andela-aatanda** [comment]
I was able to work around the `PDP` removing images of other product by using a new Pub/Sub for `cartItemImage`
