### ISSUE TITLE
Error storing file to the image store: quota exceeded

### ISSUE THREAD

**Issue by dshitik** [reactioncommerce/reaction#2120]
I got this error: Error storing file to the image store: quota exceeded
An error occurred when pouring media files.

GridFS - ERROR! { [MongoError: quota exceeded]
name: 'MongoError',
message: 'quota exceeded',
driver: true,
index: 0,
code: 12501,
errmsg: 'quota exceeded' }

**Comment by rosygupta** [comment]
Hey how did you solve this?

**Comment by jack2ky** [comment]
I just got this error too. What's going on. I use mlab.

**Comment by jack2ky** [comment]
It looks the problems is most likely because you have the "sandbox" version and you used up the space available.

You get a half a gigabyte https://mlab.com/plans/pricing/
