### ISSUE TITLE
Email address not verified for new users after clicking through email

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2125]
### Issue
When creating a new user, an email is sent out with a link to "Get Started". This link does not mark the user's email as "verified"

![image](https://cloud.githubusercontent.com/assets/1203639/25052955/c44f7cc2-2111-11e7-8aa3-464123d51db8.png)

![image](https://cloud.githubusercontent.com/assets/1203639/25053010/0697feec-2112-11e7-9edb-498d8a71b428.png)

I'd expect that after clicking the "Get Started" link in the email, the email address would be verified.

### Reproduction Steps
1. Clone from dev
2. Add email provider via dashboard
3. Create new user
4. Follow link in email
5. Observe database showing email is still `verified: false`

**Comment by michael-alade** [comment]
A PR #2216 has been opened for this issue.

**Comment by michael-alade** [comment]
@spencern After attaching a verification link to the "Get Started" button for the welcome email, everything seemed to be fine with having a new user verifying his account via email. But we discovered that if an admin tries inviting a new user the user gets two emails, the add welcome email and the add password email. At this point, it's a little bit confusing what should be done about verification because this might have its effect on the marketplace feature. What's your opinion?

**Comment by spencern** [comment]
My opinion is that we should try to combine the welcome email and the create password email into a single email when invited. This email should accomplish a few things:
1. Notify the user that they've been invited to join shop {shopname} by {user that invited them}
2. Provide the user with an opportunity to finish filling out their account details, username, password, address, etc
3. Verify the users email address if they choose to use the email they were invited with, OR send an new verification email if the user chooses to use a different email address than they were invited with.
4. If the user was added into any permission groups/audiences or given any shop specific permissions, make sure those are granted.

5. *Future feature - Trigger drip tutorial campaign based on the permissions the user has been granted. E.g. shop owner campaign might get a set of emails like this over the next month ["Setting up your shop", "adding your first product", "automate shipping with Shippo", "fulfilling orders", "understanding reaction analytics", "how to effectively market your shop", etc]

**Comment by spencern** [comment]
@michael-alade When at all possible we should try to accomplish trigger based actions ("verify email address", etc) with existing emails ("welcome to Reaction / your shop").

**Comment by michael-alade** [comment]
@spencern I think the new functionality for the invite email should be created as a new issue.

**Comment by zenweasel** [comment]
Closed via #2216
