### ISSUE TITLE
`reaction` command hangs on Ubuntu 16.04 with Node 6.10.2

### ISSUE THREAD

**Issue by Stat1c14** [reactioncommerce/reaction#2127]
Running `reaction` hangs on Ubuntu 16.04 with Node 6.10.2.

### Expected behavior

```
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Meteor 1.4.4.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.

...

=> Started your app.

=> App running at: http://localhost:3000/
```

### Actual Behavior

```
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~/reaction ]]]]]

=> Started proxy.
=> Meteor 1.4.4.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
```

### Steps to Reproduce the Behavior

1. Start Vagrant machine using the following Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 3000, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", privileged: false, keep_color: false, inline: <<-SHELL
    echo "**********************************-**********************************"
    echo " "
    echo "   Installing Reaction with Meteor on Node 6.10.2, Ubuntu 16.04LTS   "
    echo " "
    echo "**********************************-**********************************"
    echo "-> Installing dependency packages..."
    sudo apt-get update
    sudo apt-get -u dist-upgrade
    sudo apt-get install -y --no-install-recommends build-essential bzip2 curl ca-certificates git graphicsmagick python libssl-dev
    echo "-> Installing nvm..."
    curl -s -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
    source ~/.nvm/nvm.sh
    echo "source ~/.nvm/nvm.sh" >> ~/.bashrc
    echo "-> Installing Node 6.10.2..."
    nvm install 6.10.2 &>/dev/null
    echo "-> Installing Meteor..."
    curl -s https://install.meteor.com/ | sh
    meteor update --all-packages
    meteor update --patch
    echo "-> Optimizing Meteor filewatcher..."
    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    echo "-> Installing Reaction..."
    npm install -g reaction-cli
  SHELL
end
```
2. Run `reaction init`
3. `cd reaction`
4. `reaction`

**Comment by jshimko** [comment]
I don't actually see an error anywhere.  Looks like you didn't wait long enough for the build.  The spot at the end of your logs is where the app is building all dependencies for the first time.  This often takes several minutes the first time it happens.  What's the CPU share on that VM?  That could explain a slower than normal build time too.

Aside from that, is there any particular reason why you're doing your development inside a VM?

**Comment by Stat1c14** [comment]
How long should the initial build take? ~10+ minutes? CPU share would be consistently at 100% on the machine.

I'm doing development with Vagrant because I wanted to experiment quickly with Reaction in production and needed a development environment to mimic my VPS setup. I've never used it, but would you recommend Docker instead?

**Comment by jshimko** [comment]
1000% yes on using Docker.  It is the officially recommended deployment method and the only one we support.  It completely avoids all of that setup you have in your Vagrantfile and consistently works on any OS.  Just note that if you're doing customization, you'll still need to run the development setup on your local machine though (which is easier than dealing with a VM anyway).  

The setup you did above is also not a production deployment, by the way.  You just set up a development environment on another machine.  Production has a bunch of additional build steps (which you can see in the scripts in [our Docker base image](https://github.com/reactioncommerce/base)).

You clearly already know how to set up your dev environment, so you can just do that same thing on your local machine.  For a production build, you simply run:

```sh
reaction build reactioncommerce/reaction:latest
# or
docker build -t reactioncommerce/reaction:latest .
```
(those commands are identical)

Then you can run your new build using its built-in database like this:

```sh
docker run -p 3000:3000 -d reactioncommerce/reaction:latest

# available on http://localhost:3000
```

See the extended docs on how to configure for a real production deployment on a remote server.

https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-docker

Essentially, the only difference is setting more environment variables.

```sh
docker run -d \
  -p 80:3000 \
  -e ROOT_URL="http://<your app url>" \
  -e MONGO_URL="mongodb://<your mongo url>" \
  -e REACTION_EMAIL="youradmin@yourdomain.com" \
  -e REACTION_USER="admin-username" \
  -e REACTION_AUTH="admin-password" \
  reactioncommerce/reaction:latest
```

Also, if you're not actually customizing any code, you can skip all of those install/build steps and just run [our official Docker image](https://hub.docker.com/r/reactioncommerce/reaction/).  That is always the latest official release of Reaction.
