### ISSUE TITLE
Mailchimp integration

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#213]
Initially:

Connect a Mailchimp account to your Reaction shop.
Enable opt-in/opt-out for newsletters/marketing during checkout

Possible future feature:
Drag and drop email form for contact pages or hero areas. (part of CMS functionality)

**Comment by aaronjudd** [comment]
@Gouthamve I think this could easily be done, just by using the mailchimp package as you mentioned, and then adding register.coffee, and up some templates for settings, subscribe box, etc. there.

**Comment by Gouthamve** [comment]
I finally published my mailchimp package. https://atmospherejs.com/gouthamve/reaction-mailchimp. Looking for some feedback.

**Comment by faddat** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

May take me a few days, but I'll try and get you some feedback :).

On 05/08/2015 11:58 PM, Goutham Veeramachaneni wrote:
> I finally published my mailchimp package. 
> https://atmospherejs.com/gouthamve/reaction-mailchimp. Looking for
> some feedback.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/reactioncommerce/reaction/issues/213#issuecomment-
100298384>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJVTY/PAAoJEJtT834c35oWIigQAJy2skg5Sxx6kB9Q1uXN4ZqF
bhcT8XtpLm6Wlzun20ZoF3S2nMKWesfMpDToS6k9J73IdCSnLPzBtHHF8HkvQRam
Pcf0kR7mydeg0HIN/dP9bxJxRw870V9+eBj3AilDlcrgvyaEmDEJ5f7mLM5yiFTP
4UHoC0LtHkF/3J2jz0peIYj2ytcm9VkFznlkjL+CdF+2roKxYROnqtomOZfudgxq
TWImlHkiyJ+461OIm2+pTXm8ZK9ddommozTbUsvBMOwJipYkpLT3VjM0BJkKOGre
XDvFc0CLHqPHj4y0sBz0gdFXTiD9At7JOOE5p4+s8J0kDnqUJ7pegM10glFMcLnk
kkmLK93bxQyn8U/iKPb3xHQ0SpvS3RWrj+bXQdNj7RJ3lXDLaa2rP7qlD8Wsj/Ov
plbji8ivsFIgraw8t4ra9nvei0G4i4DkHBjVsdo0X5oYGwiygI9s2hQ1sEFakEU4
PTgatFoRUN4ywUXr6STCksGkMCHzj8M2b1KKmdt2jQ4nVsObcr85YzCFl+C2ZVNf
NUAR28Xb+64eD07hIaLPC8yXwwHlj/57miPNAHK3x0O6xolv+ne7kHSPeMy2qGhf
Un6AIRNPm4EmpFu3VRiurmwaaGvyWuWY57v9mIzurxrTroUTf2xh5BTNydBkhNA3
KtUOOnwp5HDw59Im/TTr
=PbHG
-----END PGP SIGNATURE-----

**Comment by abhisheksoni27** [comment]
Is this working? Or Do I need a seperate implementation?

**Comment by Gouthamve** [comment]
It is working, I just tested it. Just follow the instructions in the readme to get it working. And while it works, I would love to know get some feedback!

**Comment by aaronjudd** [comment]
@Gouthamve Great, we're going to go over this soon and make it part of the regular distribution.  Creating another issue to add some tests and do a UI review on this.

**Comment by aaronjudd** [comment]
This package is now outdated, and not really necessary as we have also segment integration and smtp.
