### ISSUE TITLE
Email panel shows Status as red even though email is working

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2131]
### Expected behavior
If email config is valid and working (e.g. you've already sent emails) the status should show as green.

### Actual Behavior
Status shows as red until you save your config. Which in a production site using a `reaction.json` you wouldn't normally do.
![cart_completed](https://cloud.githubusercontent.com/assets/72819/25112144/e20961d4-2421-11e7-8f33-635320e8417f.png)

### Steps to Reproduce the Behavior
1. Start a fresh reaction with a `reaction.json` that has a valid email config in it.
1. Login as admin
1. Go to "Email" panel
1. Observe status shows as red.

**Comment by andela-aatanda** [comment]
@zenweasel I discovered that this happens as a result of the `mail service` not set in `reaction.json`. As when I specified it, `Status` became `green`

**Comment by zenweasel** [comment]
Verified correct. Closing.
