### ISSUE TITLE
Create "Option-pricing" product type

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2134]
Putting this here as a placeholder because multiple people have requested it in the Gitter chat.

Beyond the simple T-shirt/Shoe single price product type we have now, we should create a configurable product type that allows you select multiple options which affect the top-line price.

An example might be purchasing a car, where you want to have "add-ons" where choosing each one will increase the price.

Additionally a more advanced implementation would allow groupings. An example might be purchasing a computer where you select from CPU/memory, etc. where you choose one option from multiple choices in each category, each affecting the price.

**Comment by aaronjudd** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #12](https://github.com/reactioncommerce/reaction-feature-requests/issues/12) via [**ZenHub**](https://www.zenhub.com/)
