### ISSUE TITLE
No product settings access without product revisions

### ISSUE THREAD

**Issue by janat08** [reactioncommerce/reaction#2143]
It's impossible to create tags for new products if product revisions is off, and so the yellow sticker for product settings is gone since you've already committed changes.

**Comment by aaronjudd** [comment]
@mikemurray @rymorgan  should revisions now even be an option now?  (probably should, but how does the PDP components handle this?)

**Comment by andela-aatanda** [comment]
@janat08 It would be appreciated if you can give a step by step way of reproducing this issue as I've not been able to reproduce it.

**Comment by janat08** [comment]
I you enable automatic product revision upsert, what that means is that some of gateway edit element no longer appear since youre no longer "editing" products (the green circular button). What that means is that you can't access tags and some of other editing options.

**Comment by andela-aatanda** [comment]
@janat08 Please take a look at this gif and let me know what I might be missing. Thanks
![out](https://cloud.githubusercontent.com/assets/10584060/25960383/b0ed0a4c-366e-11e7-957a-6e7136b5d37a.gif)

**Comment by janat08** [comment]
I suggest you close this, as 21 days back only way to access side bar was only through one of green buttons near text fields which didn't occur in this mode.

**Comment by andela-aatanda** [comment]
Seems this issue has been fixed by Reaction Commerce latest release. I'll be closing this but feel free to reopen with steps to reproduce if this issue reoccurs. Thanks
