### ISSUE TITLE
Orders page - Large View Redesign

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2150]
Add new layout for large view 
![orders - large view](https://cloud.githubusercontent.com/assets/20409254/25297245/64452490-26a1-11e7-848c-cdea5bd1a0dc.png)

Annotated Designs in Zeplin: 
Web: https://zpl.io/1Bhq7d
App: zpl://screen?pid=58af8900737c137280322bd6&sid=58fa864cf7863b791bedfc49

Related to: #2046

**Comment by kieckhafer** [comment]
Large view completed in #2400
