### ISSUE TITLE
Orders: Add Search and filtering

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2152]
![orders - search](https://cloud.githubusercontent.com/assets/20409254/25299357/eeea1072-26b2-11e7-98cb-8234780d4d04.png)

Annotated Designs in Zeplin:
Web: https://zpl.io/1r0Vvm
App: zpl://screen?pid=58af8900737c137280322bd6&sid=58fa9b08c1ee69df600c0469

Related to: #2046

**Comment by zenweasel** [comment]
Don't we already have a ticket for this?

**Comment by rymorgan** [comment]
@spencern Do we still need this issue or is it covered with Marketplace Orders issues?

**Comment by spencern** [comment]
@rymorgan I think this is covered by the Marketplace Orders Searching, Filtering, and Sorting issues.

Closing in favor of:
#2353 #2354 #2355  #2357 #2359 #2360 #2361 #2363
