### ISSUE TITLE
Orders / Fulfilment / Shipping Flow: Componetize all "after approval" actions

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2153]
![shipping flow 1](https://cloud.githubusercontent.com/assets/20409254/25299403/a238e914-26b3-11e7-8c1c-e64aed9db2d7.png)
![shipping flow 2](https://cloud.githubusercontent.com/assets/20409254/25299402/a237add8-26b3-11e7-83b2-5ae4ee18cee4.png)
![shipping flow 3](https://cloud.githubusercontent.com/assets/20409254/25299401/a2379280-26b3-11e7-9fda-6f0cc8be4c7a.png)

Related to: #2046

**Comment by aldeed** [comment]
@kieckhafer @rymorgan I think you've done some recent work on this

**Comment by kieckhafer** [comment]
Related: https://github.com/reactioncommerce/reaction/issues/5285

**Comment by kieckhafer** [comment]
Closed via #5157
