### ISSUE TITLE
Terms & Conditions and Privacy Policy templates

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#216]
Minimum functionality:

Ability for shop/business name to be inserted into templates for Terms & Conditions and Privacy Policy.

**Comment by Gouthamve** [comment]
None of the static pages in the footer are loading. It seems to be a simple bug.

And are we sure we want standard T&Cs and Privacy Policy for all reaction shops? Different shops will have different terms. So, how do you want the template to work?

**Comment by aaronjudd** [comment]
See:  #148  and https://github.com/reactioncommerce/reaction-core/blob/development/docs/packages.md#registry as well for some implementation ideas.

**Comment by aaronjudd** [comment]
Not relevant anymore, see https://docs.reactioncommerce.com/reaction-docs/master/layout
