### ISSUE TITLE
Docker image fails to build on remote docker-machine host

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#2169]
### Expected behavior
docker build -t imagename . builds the image sucessfully.

### Actual Behavior
While this works on my local host, it fails to run on my remote server that I set up with docker-machine and its generic driver. It stops at:
`ERROR: Service 'reaction' failed to build: The command '/bin/sh -c cd $APP_SOURCE_DIR && bash $BUILD_SCRIPTS_DIR/build-meteor.sh && bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1`

### Steps to reproduce
Set up a docker-machine with the generic driver, try to build the docker image.

### Version
Reaction 1.1.1 on Debian 8

**Comment by jshimko** [comment]
Can you please provide exact reproduction steps?  Since this is an isolated issue that nobody else appears to be having, we're going to need to know exactly how you set up the machine to reproduce it.
