### ISSUE TITLE
Option images are not revision controlled

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2181]
### Expected behavior
Option images should not be visible to non-admins until those changes are published

### Actual Behavior
Option images are immediately visible to non-admins

### Steps to Reproduce the Behavior
1. login as admin
1. Create a product with options
1. Publish the product
1. Add an image to an option but do not publish those changes
1. Open an incognito window
1. Observe that the option image is visible.

### Versions
```
Node: 7.4.0
NPM: 4.0.5
Docker: 17.03.1-ce
Reaction CLI: 0.8.0
Reaction: 1.1.1
Reaction Branch: development
```

**Comment by andela-aatanda** [comment]
Can't seem to reproduce this locally. I'll see if I can reproduce it in a remote `docker` container
