### ISSUE TITLE
[Marketplace] Registry should permit group based permission allowance

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2185]
When authoring a registry item that creates a new permission context, it should also be permitted to add an array of groups that are granted said permission by default.

Perhaps something like this:
Borrowed from the product-detail-simple plugin. `imports/plugins/included/product-detail-simple/register.js
```
  registry: [{
    route: "/product/:handle/:variantId?",
    name: "product",
    template: "productDetailSimple",
    workflow: "coreProductWorkflow",
    permissionGroups: ["guest", "customer"]
  }],
```

Adding a new registry item with permissionGroups to an existing should should assign permissions to all existing users that fit those groups.

**Comment by spencern** [comment]
@impactmass and I discussed this a bit and I think this issue should probably be postponed until we figure out how groups and permission assignment works for multiple shops.

**Comment by aldeed** [comment]
This was done a while ago with `addRolesToGroups`
