### ISSUE TITLE
[Marketplace] Inviting someone to create a new shop or affiliate shop should automatically grant that user appropriate permissions when registered

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2186]
**Update - June 29**
This issue is about _inviting_ a user to create a _new shop_.
On the UI side, we should probably add a checkbox or similar for `[ ] New Shop` when inviting a new user.

If checked, the invite would then create a new shop - `shops/createShop`, and assign the newly created user as an "owner" of the new shop.

This issue is _related_ but not the same as #2187 which is focused on adding administrative users to your existing shop.

**Original Issue**
When an invite is created for someone to create a new Shop or Affiliate shop on a marketplace the invited user should automatically be granted appropriate group permissions once they have finished registering. This should take place such that when the user has created an account they can immediately start acting on their new shop.

Ideally this could be fulfilled with a token so that they can register with any method and not exclusively with the email address to which the invite as sent and still have their account granted appropriate permissions.

**Comment by impactmass** [comment]
Note: I started on this yesterday. I'll be posting an update about the state of this later today when I make a WIP PR.

**Comment by impactmass** [comment]
Status: PR for this is currently in review #2538 ...

**Comment by impactmass** [comment]
closed by #2538
