### ISSUE TITLE
Marketplace, Shop, and Affiliate shop owners should be able to add administrators

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2187]
**Update June 29**
This issue is focused on inviting new admins to existing shops.

5 thoughts from a chat @impactmass and I had

1. This invitation will be sent via the “accounts” dashboard (or the new dashboard that’s created to manage shop users).
2. An email is generated and sent to the user.
3. I think the flow might be:
  - Invitation is created
  - New user is generated with existing permissions and with the email specified in the invitation
  - User clicks from email to join -> is logged in via token -> lands on password set/reset
  - User sets new password -> routed to user profile

4. The invitation form will need a dropdown (I think @rymorgan is working on this/has finished this) to select the correct group to invite the new user to
5. ‘Appropriate group permissions’ means permissions for the group the user was invited to.
6. If the user already exists (as a customer or other shop admin), they should be given permissions for the site and sent an email, but an additional user should not be created.

**Original Issue**
Marketplace, Shop, and Affiliate shop owners should be able to invite people to become administrators. 

Newly invited administrators should be granted appropriate permissions based on the marketplace, shop, or affiliate user that invited them. E.g. If a shop owner invites a new admin, that admin should be granted admin permissions for that shop only.

If adding an user or email that is already connected to a Reaction account on this app, we should grant permissions to the existing user.

If we are adding a user or email that does not exist yet, we should grant the new account permissions upon activation.

**Comment by spencern** [comment]
Seems like a lot of overlap between #2186

**Comment by impactmass** [comment]
Resolved by #2588
