### ISSUE TITLE
[Marketplace] Owner permission should be transferable

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2188]
Marketplace, Shop, and Affiliate shop owners should be able to transfer ownership to another administrator of their marketplace or shop.

#### Rules:
-   Should not be able to remove permissions from the owner except by transferring the owner title. -   Each shop should only be able to have one owner.
-   If there are no other administrators in a given shop, owner can not be transferred.
-   Process for transferring ownership to a non admin user should be: Add user to admin group, then transfer ownership, then new owner can remove previous owner from admin group.

**Comment by impactmass** [comment]
This is largely done. The PR is here - #2609, but it depends on #2538 being merged first

**Comment by impactmass** [comment]
closed by #2609
