### ISSUE TITLE
[Marketplace] New permissions added to an existing RC app should update existing users permissions appropriately

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2195]
When new permissions are added to existing permission groups (e.g. through the registry), existing users should have their permissions updated appropriately.

This could possibly be accomplished by checking and updating a permission group for authorization rather than that each user has a specific permission if the user is in a specific group.

Currently when new permissions are added to `defaultRoles` existing users are not granted those permissions.

**Comment by spencern** [comment]
@impactmass - I _think_ this is partially completed by your groups PR as changing the permissions in the dashboard will update all users with that group, correct?

What is not completed here is if you use the `addRolesToGroups` method I don't think that checks existing users.

**Comment by impactmass** [comment]
Yes. Changing it in the dashboard updates the users. The pending part is `addRolesToGroups`.

**Comment by spencern** [comment]
Closed by #2606
