### ISSUE TITLE
Convert settings panels to React

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2198]
The Example Payment is already React so just convert Paypal, Braintree, Authorize, and Stripe. Add validation to Example Payment. Use @mikemurray's Reaction-Autoform

**Comment by zenweasel** [comment]
I realize that this is not the most critical thing to work on right now, but looking for something to get me up to speed on writing React components from scratch. Thus I am assigning it to myself.

**Comment by zenweasel** [comment]
This should be done by using the `<Form>` component rather than the way it was done in Example Payment (and example payment should be rewritten to do this as well).

This should work so that in most cases unless you have advanced needs that you only need to define your schema and your settings panel should be generated automatically. So this may require extending the `<Form>` component some.

If this gets too big because some settings panels are more complicated (e.g. Avalara) then we can create additional tickets.

**Comment by foladipo** [comment]
Here's a WIP list of the parts of the Settings panel that are yet to be converted:
- Actions
    - Analytics

**Comment by zenweasel** [comment]
Can drill down one level further? The sections under Payment, Shipping, Tax and others would all be separate panels.

**Comment by foladipo** [comment]
@zenweasel I've added more detail to the list.

**Comment by foladipo** [comment]
Update: I have started work on converting the "Analytics" panel to React.

**Comment by zenweasel** [comment]
Just to document this here: 

Let start with Taxcloud, Search and SMS. These are all simple panels just a couple of text fields and/or booleans. If those go smoothly then let's move on from there.

**Comment by aldeed** [comment]
This is currently reflected in newer and more specific issues
