### ISSUE TITLE
Orders page doesn't show variant type

### ISSUE THREAD

**Issue by Stat1c14** [reactioncommerce/reaction#2199]
The Order page in the Reaction admin does not show the variant type selected, it only shows the product itself. This is a major platform flaw and needs to be address immediately.

### Expected behavior

Order page shows selected variant for order.

### Actual Behavior

Only the selected product name is listed.

<img width="1163" alt="screen shot 2017-05-02 at 8 36 11 am" src="https://cloud.githubusercontent.com/assets/5795116/25619790/20d91014-2f1a-11e7-828e-8a374f81b4e2.png">

### Steps to Reproduce the Behavior

Download the latest Docker build and place a test order. I'm using Stripe, so I just used their test API key and test card numbers.

### Versions

Ubuntu 16.04
Node: 6.2.2
NPM: 4.0.5
Docker: 17.03.1-ce
Reaction CLI: 0.8.0

**Comment by jshimko** [comment]
If this needs to be addressed immediately, you should know that we're always open to contributions.  Feel free to submit a pull request with your fixes.

**Comment by Stat1c14** [comment]
Of course. I'll dig into this later and see if I can't figure it out.

**Comment by aaronjudd** [comment]
Probably needs to be both, the full product and the option name.

**Comment by zenweasel** [comment]
Testing this on `development` and the variant title does in fact display in the order panel. Is it possible you didn't supply a `title` when you created the product?

![cart_completed](https://cloud.githubusercontent.com/assets/72819/25734142/ae8e307c-3192-11e7-854e-0aea13877448.png)

**Comment by zenweasel** [comment]
Not a bug. Option titles are shown correctly when they are entered. Works as designed.
