### ISSUE TITLE
Long strings in options label not handled correctly

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#2203]
### Expected behavior

Long strings in options label should not spill out of the container.

### Actual Behavior

Long strings spill out.

### Steps to Reproduce the Behavior

1. Go to PDP
2. Open variant to edit its child(ren)
3. Type in a very long name as its title
4. Observe that it spills out of the container

<img width="230" alt="screen shot 2017-05-03 at 1 26 51 am" src="https://cloud.githubusercontent.com/assets/19430095/25641980/a039152c-2f9f-11e7-8b89-01197cd8c21f.png">

**Comment by abdulsemiu-atanda** [comment]
Closed via #2266
