### ISSUE TITLE
Order Summary not showing the correct data

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2207]
When using Reaction as an Admin, the Orders panel is not correctly displaying order information in the Summary section.

1) If you have not yet attached an Address to your Admin account, then the summary section does not display at all

![pasted_image_at_2017_05_03_04_10_pm](https://cloud.githubusercontent.com/assets/4482263/25684184/e507063a-3014-11e7-89cd-a738ace59c3a.png)

2) If you have an address attached to your Admin account, then the Summary panel displays the address of the Admin, not the address attached to the order.

![pasted_image_at_2017_05_03_04_12_pm](https://cloud.githubusercontent.com/assets/4482263/25684232/0c359ca8-3015-11e7-9506-699522002ad6.png)

**Comment by spencern** [comment]
Was able to confirm the issue.
My Repro steps:

1. clone `development` branch
2. setup shipping and payment, do not setup admin account address
3. Checkout with non-admin account (incognito, anonymous checkout works fine)
4. Attempt to fulfill order. Note that Summary is empty.
5. Add address to admin account - make sure it's different than the address you checked out with.
6. Re open order from admin account. Ship To address and all other address information will be related to administrator address, not customer address in the summary panel.

**Comment by zenweasel** [comment]
@kieckhafer @spencern This is ready to be closed right? Do I need to confirm fixed?

**Comment by kieckhafer** [comment]
Yes this can be closed.
