### ISSUE TITLE
On a fresh windows 10 install reaction not started due to vsivsi:job-collection 

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2210]
### Expected behavior
Reaction App Should start
### Actual Behavior
Application Start  Stuck without any message. (**Most Frustrating part**) 
### Steps to Reproduce the Behavior
On a fresh windows 10 install reaction not started due to vsivsi:job-collection.
When pinned(downgraded ) `vsivsi:job-collection`  from 1.5.1 to 1.4.0, it worked.
### Versions
Node: 6.3.1
NPM: 3.10.3
Reaction CLI: 0.8.0
Reaction: 1.1.1
Reaction Branch: development

**Comment by zenweasel** [comment]
Have you looked at/commented on https://github.com/vsivsi/meteor-job-collection/issues/231
Seems like you aren't the only one.

**Comment by hrath2015** [comment]
@zenweasel  thanks for pointing it out and referencing the issue as well.  I was away for almost 3 weeks and after coming back started to get all kind of problems 😟 while building the RC locally.    felt this one should be logged. Lots has changed in 3 weeks `(reaction-cli, meteor version upgrade and vsivsi).` 
thanks again...

**Comment by aaronjudd** [comment]
@hrath2015 @zenweasel if we want to pin to 1.4.0 -> what's the downside?

**Comment by hrath2015** [comment]
RC Master branch  is  still using 1.4.0.  I tested it with a fresh clone `reaction init` and `reaction run` and versions file has `vsivsi:job-collection@1.4.0`.

Also looked at changes between 1.5.1 and 1.4.0 at https://github.com/vsivsi/meteor-job-collection/blob/master/HISTORY.md . Not much changes there.  I feel  we can pin it to 1.4.0 and hoping we have a solution in near future.  
@zenweasel   request your views as well.   If decision is to pin then I will send a PR.

**Comment by zenweasel** [comment]
@hrath2015 Have you tried pinning the current `development` version to 1.4? I think the decision was to pin it to 1.4 if there was no other downside. We did need to fix one bit of syntax that changed from 1.4 to 1.5, but not sure if it's backwards compatible

**Comment by hrath2015** [comment]
@zenweasel  Yes I did  pin on development branch and saw no issues.

**Comment by zenweasel** [comment]
Closed via #2228
