### ISSUE TITLE
Variant Template Design

### ISSUE THREAD

**Issue by evliu** [reactioncommerce/reaction#222]
I tried reusing the ```variant``` template and stick it in a table to view all products with editable fields, and it seems the template is specifically styled for just the ```productDetail``` page, meaning things show up all funky when used elsewhere, for instance, in my table, lol.

The specific thing I was wondering in ```variant.html```, is that the progress-bar on line 5 is its own <span>, then the ```variant-title``` and ```variant-price``` spans follow it, but wouldn't it make more sense for those to be inside the ```progress-bar``` span if they are going to be text inside the progress bar?

for instance:
```html
<span class="progress-bar {{progressBar}}" role="progressbar" aria-valuenow="{{inventoryQuantity}}" aria-valuemin="0" aria-valuemax="{{inventoryTotal}}" style="width: {{inventoryPercentage}}%">
     <span class="variant-title">{{title}}</span>
     <span class="variant-price">{{formatPrice displayPrice}}</span>
(and possibly the variant-edit pencil here instead of next to the progress bar:)
     <div class="variant-edit hidden-xs">
          <i class="fa fa-pencil fa-lg" data-id="{{_id}}"></i>
      </div>
</span>
```
instead of
```html
<span class="progress-bar..."></span>
<span class="variant-title..."></span>
<span class="variant-price..."></span>
<div class="variant-edit hidden-xs">
     <i class="fa fa-pencil fa-lg" data-id="{{_id}}"></i>
</div>
```

Right now the variant styling seems a little hacky. The price could use the bootstrap class ```pull-right``` instead of doing a ```position: absolute; right: -25px;``` and so forth. I'm still new to web dev styling so I'm not sure what the normal practices are (coming from J2EE and iOS dev). I can also be completely wrong, haha. Maybe I should make an html file that lists out all the templates to see what templates don't display correctly outside of parent template styling. I'm just thinking of the modularity of template views.

**Comment by aaronjudd** [comment]
@evliu any further comments, or shall I close this?

**Comment by evliu** [comment]
hmm, i forgot about this, but this can be closed. it seems the components are much more decoupled than when this was first an issue.
