### ISSUE TITLE
Emails are missing logo

### ISSUE THREAD

**Issue by Stat1c14** [reactioncommerce/reaction#2220]
Any emails sent out by Reaction are missing a logo.

### Expected behavior

The logo appears on email messages.

### Actual Behavior

<img width="638" alt="screen shot 2017-05-05 at 7 50 33 pm" src="https://cloud.githubusercontent.com/assets/5795116/25767961/3a2016da-31cc-11e7-89b1-fb476272ec49.png">

### Steps to Reproduce the Behavior

1. Run the latest Docker build of Reaction.
2. Upload a custom logo.
3. Do some action that triggers mail to be sent.

### Versions

Node: 6.2.2
NPM: 4.0.5
Docker: 17.03.1-ce
Reaction CLI: 0.8.0

**Comment by aaronjudd** [comment]
What's the URL on the image? Possibly.. `localhost`? Is the URL accessible (from the email client)?

**Comment by aaronjudd** [comment]
I think this is should probably be closed.  Bear in mind, the urls are local for images are local, and are using the Meteor.absoluteUrl() as the root/prefix.  We can re-reopen if we can reproduce on a product / public docker where the image is accessible, but in a local/dev env we know this won't work.
