### ISSUE TITLE
Translations not reactively updating in some React components

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction#2229]
Since the translated label props that get passed into the React components are just an i18n key that doesn't change, the components aren't re-rendering the new language.

For example, I switched to Spanish, reloaded the page, then switched to Chinese.  This is what I get on the PDP.

![image](https://cloud.githubusercontent.com/assets/3077956/25861317/6025ee20-34b2-11e7-9e64-baf7b3ff2781.png)

If you take a look in the React devtools, you can see why the re-render didn't happen...

<img width="1192" alt="basic_reaction_product" src="https://cloud.githubusercontent.com/assets/3077956/25861356/7763e95c-34b2-11e7-8a48-7f680c5ad4fa.png">

So we need to do something to invalidate the props when the language changes.  Perhaps it makes sense to have the current language loaded in [React context](https://facebook.github.io/react/docs/context.html) and then create a helper that watches for the change and forces a re-render on any i18n items.  This would also be a great use case for Redux, but that's a lot more steps at this point (and probably not practical until the entire tree is React).

**Comment by jshimko** [comment]
Or maybe...

https://github.com/i18next/react-i18next

**Comment by mikemurray** [comment]
Might need to use the `<TranslationProvider />` and the `<Translation />` component. or someday, maybe redux.

**Comment by kieckhafer** [comment]
@jshimko I believe this is fixed in PR #2283, in [this commit](https://github.com/reactioncommerce/reaction/pull/2283/commits/3a2201bda99df49fd17ef0a4e79c7042f75fa524), which wraps the entire app inside the `TranslationProvider`. Once `1.2` is merged you should see the fix in `master`.

Closing for now, can re-open if needed.
