### ISSUE TITLE
Duplicated profile shortcut and corrupted profile panel

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2233]
### Expected behavior
Only one profile shortcut in dropdown and no artifacts in profile admin screen

### Actual Behavior

![account_profile](https://cloud.githubusercontent.com/assets/72819/25882070/67fa68bc-3573-11e7-80cf-38199c8d3032.png)

![account_profile](https://cloud.githubusercontent.com/assets/72819/25882063/56f36eec-3573-11e7-9a45-934c91280c1a.png)

### Steps to Reproduce the Behavior
1. Login
1. Observe two profile links
1. If you are on `development` you can observe the artifacts in the Profile panel. Both `master` and `development` have the two `Profile` links.

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.1
Reaction: 1.1.1
Reaction branch: development
Docker: 17.03.1-ce
```

**Comment by aaronjudd** [comment]
I'm not able to reproduce, as @spencern reported that he'd seen this, I'd say we need some more steps to reproduce

**Comment by zenweasel** [comment]
I can't reproduce this now so I am closing until I can reproduce it again

**Comment by spencern** [comment]
Seems good. I haven't seen this since working on stuff with GetOutfitted, so I doubt what I saw would have been the same issue.
