### ISSUE TITLE
[development] order/completed displays login to authenticated user

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2243]
Check out by registering a user and using PayPal Express as the payment method. `order/completed` displays a login page, instead of displaying the expected order.
![reaction-paypal_paypaldone_and_reaction](https://cloud.githubusercontent.com/assets/439959/25928403/e8668c0a-35b0-11e7-9ede-2330d1aa3874.png)

**Comment by zenweasel** [comment]
Yes, I was seeing this error as well but thought it was related to #1638

**Comment by aaronjudd** [comment]
Sort of related, but not the same, that page ("Order processing") should not exist. 1) it's not our spinner, but 2) it displays at times like in #1638 where it should in fact, be displaying the login... (so the opposite of this issue)

**Comment by aaronjudd** [comment]
`registered` user.. (to be clear: create an account in the checkout.., I'm not specifically testing as a "guest" here..)
