### ISSUE TITLE
Setting or changing a products perma-link causes hard refresh

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2246]
### Expected behavior
When I publish a product, I'd expect the app to do so without refreshing

### Actual Behavior
http://g.recordit.co/DwTDf6K2O9.gif
When updating a product's permalink (even for the first time), the app refreshes upon publish.

### Steps to Reproduce the Behavior
1. Clone `development`
2. Login as admin
3. Create a new product.
4. Set variant label to something
5. Click the edit button next to the social icons
6. Open the product settings accordion
7. Set the product title (and the perma-link will be set as well)
8. Hit publish
9. Observe hard refresh.

### Versions
```
Node: 7.8.0
NPM: 4.5.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.1
Reaction: 1.1.1
Reaction branch: development
Docker: 17.03.1-ce
```

**Comment by michael-alade** [comment]
A PR has been opened for this issue, but removing the hard reload seems to affect the product grid after I've clicked on the brand name to return to the product grid. I came up with a solution but it needs to be reviewed and accepted by the core team members. I would be posting a detailed description of the two possible solutions for the issue.

**Comment by zenweasel** [comment]
@michael-alade What's the status on this?

**Comment by michael-alade** [comment]
@zenweasel I joined the daily sit-down to convince the team about using the `.direct` method when updating a product after clicking publish. But I was told to check out subscription manager to try and reset the subscription cache as that might be the cause of the revisions not showing on the product grid.

**Comment by zenweasel** [comment]
As we had discussed, please make notes on this ticket regarding your progress and where we are leaving this.

**Comment by michael-alade** [comment]
Having tried to use the `Route.go` for redirect the seller to the new product permalink after publishing the product, I still got another issue with the product not being found. Also, for the product grid, I tried using subscription manager but it seems to be the wrong approach. We think this is caused by the Revisions collection being updated when publishing the product.

**Comment by aaronjudd** [comment]
@michael-alade is this resolved?
