### ISSUE TITLE
Can't set price or quantity for a variant with archived options

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2247]
### Expected behavior
If all options of a variant are archived, I should be able to control price and quantity at the variant level.

### Actual Behavior
http://recordit.co/8stYPXQbyt

Once a variant option has been created, I am no longer able to adjust quantity or price at the variant level.

![image](https://cloud.githubusercontent.com/assets/1203639/25932517/f090cc74-35ce-11e7-8c4f-7a9cd8fee092.png)

### Steps to Reproduce the Behavior

1. Clone `development`
2. Login as admin
3. Create a new product.
4. Edit the price and quantity of the variant
5. Create a variant option for this variant
6. Archive the variant option you just created
7. Attempt to edit the price and quantity of the variant again. Fail.

### Versions
```
Node: 7.8.0
NPM: 4.5.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.1
Reaction: 1.1.1
Reaction branch: development
Docker: 17.03.1-ce
```

**Comment by zenweasel** [comment]
The issues was that options were not being published between archiving the option and trying to edit the price.
@rymorgan Usability needs review to reflect when we need to publish and and what is blocking a publish. Let's create a new issue to take a step back and look at the UI
