### ISSUE TITLE
Admin Dropdown icons showing for guest accounts

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#2252]
### Expected behavior
Only show icons for guest access level

### Actual Behavior
Admin icons also show up in dropdown

![screenshot 2017-05-11 18 50 04](https://cloud.githubusercontent.com/assets/5229321/25963866/c104620c-367a-11e7-89d2-ed7b37fbc72f.jpg)

Bug related to the revert of #2145

**Comment by spencern** [comment]
Closed by #2253
