### ISSUE TITLE
Customer notifications show order being processed before processing has started

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2254]
#### Customer notification shows order is being processed
![image](https://cloud.githubusercontent.com/assets/1203639/25968511/fdf6299c-364e-11e7-8d3a-6d1ab82468cc.png)

#### Admin panel shows order processing has _not_ started
![image](https://cloud.githubusercontent.com/assets/1203639/25966985/e5c294e6-3649-11e7-9a42-93d7cd3c0ad4.png)

### Expected behavior
I'd expect that I would get notified that Processing on my order has started once the order processing has started.

### Actual Behavior
I'm notified that my order has started processing as soon as the order is placed.

### Steps to Reproduce the Behavior
1. Checkout `development`
2. Create a non-admin account.
3. Place a new order with this new account.
4. As soon as the order has gone through - you'll observe a notification informing you that your order is being processed.

### Versions
```
Node: 7.8.0
NPM: 4.5.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.1
Reaction: 1.1.1
Reaction branch: development
Docker: 17.03.1-ce
```

**Comment by aaronjudd** [comment]
See also see #2142 and #2136

**Comment by michael-alade** [comment]
A PR has been opened for this issue #2290 .
