### ISSUE TITLE
Openshift v3 support

### ISSUE THREAD

**Issue by xelfe** [reactioncommerce/reaction#2262]
I would like to add [Openshift V3](https://www.openshift.org/) support like extra feature. 
Openshift is a cloud platform base on [Google Kubernetes](https://kubernetes.io/) in collaboration with Red Hat, inc.

It's a great platform that can manage efficiently resources and give a easy way for developing and deploying cloud stuff.

**Comment by aaronjudd** [comment]
We support Docker and Heroku images. We actually use Kubernetes as part of the Reaction Commerce managed platform as well (so, yes, we support Kubernetes).  

We have a channel for this discussion: https://gitter.im/reactioncommerce/deployment

And docs (updates coming soon): https://docs.reactioncommerce.com/reaction-docs/asj-updates/deploying
