### ISSUE TITLE
Extended filters (multi dimensional)

### ISSUE THREAD

**Issue by janat08** [reactioncommerce/reaction#2263]
I'm looking for multidimensional filters, such that you can look for category of merchandise and then merchandise parameters as in: categories vape liquids, vape equipments as categories, and then manufacturers and price ranges and such.

Your average webstore will be organized in this way, and supporting multidimensional browsing doesn't require that there's any kind of reordering of schema since they can still use tags (make category tags mandatory though).

**Comment by aaronjudd** [comment]
A couple thoughts here.. we've seen people build this functionality, extending the tag based search we have as a default.  I'd also say that this is a better case for something like ElasticSearch as an external search/index, that could a quickly added as a plugin to Reaction.  I'd suggest that this currently isn't an enhancement that we're looking to add to the core, but it is a common request.

**Comment by janat08** [comment]
I'd be curious to see what you've seen.

**Comment by janat08** [comment]
From what I see you're halfway there with branching categories> vape -> [liquids/equipment]. That's what multi dimensional filters stand for, but I'd be willing to stretch it further with price filters, and other product param filters (make/color).

**Comment by janat08** [comment]
price search is missing

**Comment by aaronjudd** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #19](https://github.com/reactioncommerce/reaction-feature-requests/issues/19) via [**ZenHub**](https://www.zenhub.com/)
