### ISSUE TITLE
Image does no show up in product grid after uploading

### ISSUE THREAD

**Issue by erichen510** [reactioncommerce/reaction#2264]
**Expected behavior**

Image should show up in the grid view.

**Actual Behavior**

After uploading the image in the product page, it failed to load in the product grid view.

**Steps to Reproduce the Behavior**

1 upload the picture
2 publish 
3 go back to the home page

I have installed all the requirement on my machine(windows). 
According to [https://github.com/CollectionFS/Meteor-cfs-graphicsmagick/issues/12](url) , I reinstalled imageMagick in my D:\\. 

Anyone has some idea?

Node: 6.10.2
NPM: 3.10.10
Meteor Node: 4.8.1
Meteor NPM: 4.4.4
Reaction CLI: 0.8.2
imageMagick 7.0.5 Q16

![screencapture-localhost-3000-1494834280089](https://cloud.githubusercontent.com/assets/16681583/26047883/8fdb325e-3987-11e7-8697-e8ad19558c8d.png)
![screencapture-localhost-3000-reaction-product-mian-da-ban-t-xu-1494834373232](https://cloud.githubusercontent.com/assets/16681583/26047882/8fd934d6-3987-11e7-9956-37787b1fd40d.png)

**Comment by abdulsemiu-atanda** [comment]
@erichen510 please take a look at this `gif` and let me know what I might be missing as it seems I cannot reproduce this issue
![product](https://cloud.githubusercontent.com/assets/10584060/26072739/912362c2-39a4-11e7-8925-a5e62ba4a872.gif)

**Comment by erichen510** [comment]
It seems like something only happen on Windows.
I did another fresh install, and the same thing happened.
![screencapture-localhost-3000-1494931388636](https://cloud.githubusercontent.com/assets/16681583/26102484/bf5ad47c-3a67-11e7-88f3-db96fa3e7166.png)

**Comment by hrath2015** [comment]
@erichen510  when u click and open the product page it shows right?

**Comment by erichen510** [comment]
yes

**Comment by hrath2015** [comment]
@erichen510 @abdulsemiu-atanda 

I am able to reproduce it on windows 10 machine.  Did some more investigation and found out that the file chunks are created only for default image store.  Other  configured stored (Large, Medium, Small, Thumbnail) are not  getting the binary data populated hence you are not seeing images in Grid and other views. 

I also tried the  branch **`cfs-fix`** to see if it helps but issue still there.   Need to do further investigation.

**Comment by hrath2015** [comment]
Found the issue. It is because of, imagemagic and  windows' combination, and the way `cfs:graphicsmagick` package is making global scope of `**gm**` available to true.

my suggestion would be : instead of `imagemagic` try `graphicsmagic`

**Comment by erichen510** [comment]
Thanks for the advice, it really works. Others can have a try @hrath2015
