### ISSUE TITLE
WIP - Reaction Style Guide

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2267]
Need a style guide for reaction to clarify design guidelines and document components.

**Comment by rymorgan** [comment]
Suggested structure for the style guide. We may need to move or rename a few of these to line up with the components in the codebase. 

**Guidelines**	
	Design Principles	
**Style**		
	Typography	
	Icons	
	Color	
	Motion	
	Illustration	
		
**Get Started/Customization**		
	Layout Guide	
	Homepage	
	PDP	
	Catalog	
	Cart	
	Checkout	
	Footer	
		
**Components**	
	Forms	
		Buttons
		Icon Buttons
		Selects
		Dropdowns
		Inputs
		Radio Buttons
		Checkmarks
		Toggle
		Calendar Picker
	Lists	
		Sidebar Lists
		Big Left Area Lists
		Bulk Action and Selection
	Feedback/Alerts	
		Inline alerts
		Badges (status alerts)
		Publish Status
		Toast Alerts
		Tool Tips
		Progress Bars/Spinners
		Hints/Tips
	Popovers	
		Screen Popover
		Inline Popover
	Cards	
		Basic
		Card w/ Switch
	Navigation	
		Shop Navigation
		Tabs
		Search
		Filters
		Pagination 
	Sidebar	
		Sidebar
		Icon Sidebar
	Tags	
		Search
		Product Tags
		Tag Editing Form
	Image Uploader	
		Sidebar
		Product
		Bulk
		Image Editor 
		Image Library and Manger
	Structure	
		Layout*
		Grid
	Containers	
	Translations

**Comment by rymorgan** [comment]
Here's a mockup for page structure and navigation structure. 

![style-guide-layout](https://cloud.githubusercontent.com/assets/20409254/26076590/1a3816f2-396e-11e7-8946-1cb24897ebac.png)

**Comment by zenweasel** [comment]
@machikoyasuda @rymorgan Do we want to keep this stuff here or move it over to the Reaction Component Library repo now?

**Comment by rymorgan** [comment]
@zenweasel @machikoyasuda -- y'all's call. I didn't know about that repo. I lean in favor of consolidation but I defer to whatever you think.

**Comment by machikoyasuda** [comment]
I vote we move it to the component library.

**Comment by machikoyasuda** [comment]
Closing this b/c we have a new component library repo
