### ISSUE TITLE
How to create a review by user and description in Products?

### ISSUE THREAD

**Issue by tien77** [reactioncommerce/reaction#2268]
I only see basic edit when add new products.

If I want to add review(comment system in admin) and description with more info about this products(can be custom HTML).

Like this image.

![capture](https://cloud.githubusercontent.com/assets/18161658/26079684/d84510b2-39ed-11e7-9566-224df11a1362.PNG)

Demo link at: https://www.ubertheme.com/magento-themes/ub-megamall/#details

Have any method to do this?

**Comment by zenweasel** [comment]
This is on our roadmap (user reviews). We will be publishing an updated roadmap this week. We'd love to get your involvement. Stay tuned for more details.

If this is something you need in the really short-term, then this is something you would want to build as a plug-in. Possibly integrate with one of the third-party review services.
