### ISSUE TITLE
Still logged in as Admin user after reaction reset

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2269]
### Expected behavior
When I preform a `reaction reset`, I should be logged out of my admin account.

### Actual Behavior
On some occasions, a `reaction reset` doesn't seem to fully reset. I need to [run another command](http://stackoverflow.com/questions/12238382/how-to-stop-meteor) to fully kill meteor in order for a true reset.

### Steps to Reproduce the Behavior
This does not happen all the time...
1) Use Reaction normally as an admin user
2) Do a `reaction reset`.
3) Sometimes, you'll see you're still logged in as an admin when you restart. EDIT: Settings and products are also still there, it's as if nothing was reset.

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.1
Reaction: 1.2.0
Reaction branch: release-1.2.0
Docker: 17.03.1-ce
```

**Comment by aaronjudd** [comment]
@jshimko status update on this issue?

**Comment by jshimko** [comment]
@kieckhafer I've tried several times and I can't reproduce this.  Is it possible you didn't refresh the browser after the db reset?  If I start the app and login, then kill the app, do a reset, and go back the browser, I can still click around a bit with the client side cache from my previous session.  It appears as if I'm signed in, but it's really just a stale client side cache with no connection to the server.  Hard refreshing the page drops the cache, invalidates my token, and logs me out.

Next time this happens to you, can you try refreshing your browser after the reset/restart? (if you haven't done this already)  Once you do, you should the see your token in localStorage get invalidated and you should get this error in the console...

```
Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]
```

**Comment by kieckhafer** [comment]
Yeah, I'll try that next time, this happens frequently though, and it's not just me. I made the ticket after we discussed in a meeting, but all of us there had experienced it before. I end up having to do a full meteor kill from [here](https://stackoverflow.com/questions/12238382/how-to-stop-meteor): `kill -9 `ps ax | grep node | grep meteor | awk '{print $1}'` - before i'm fully reset and logged out.

**Comment by zenweasel** [comment]
Are we talking about after getting the `toString` error?

**Comment by kieckhafer** [comment]
No, this issue is after I do a reset, I restart the app and I'm still logged in as an admin, and still have all my products and settings saved. It's like Meteor never actually reset, it just stopped and started again even though I did the reset command.

**Comment by zenweasel** [comment]
This happens to me sometimes when I do `rrr` and don't watch the output carefully to make sure it actually resets. The failed `reset` doesn't fail the command in a `reaction reset && reaction`

**Comment by kieckhafer** [comment]
^^ This is occuring with `rrr`'s for me. I'll start using `reaction reset && reaction` for the next few days and see if it occurs at all.

**Comment by zenweasel** [comment]
You can't use `reaction reset && reaction`, that's what doesn't work (I don't think I said it clearly enough above). You would need to do it on two separate lines (or just watch for an error more carefully). It would be great if the CLI would throw an error on this rather than just chugging along.

**Comment by zenweasel** [comment]
I believe in bash that when you do `command && anotherCommand` that if `command` fails it should not execute `anotherCommand`. But I don't think bash sees a failed `reaction reset` as a failure.

**Comment by jshimko** [comment]
It looks like there wasn't proper exit code handling for the `meteor reset` command when `reaction-cli` runs it.  [Now there is](https://github.com/reactioncommerce/reaction-cli/commit/6ff482ebfe81cc997a97037ce5e9536a102cc49e).  Update the CLI to v0.9.2 and let me know if this issue happens again.  If the database reset fails, you should now see an error message and whatever command you have after the `&&` won't happen.

**Comment by aaronjudd** [comment]
@jshimko (I think) this resolved now, can you re-open if not?
