### ISSUE TITLE
Fix validation on PDP

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2274]
All fields that are required or have a set type need to provide some user feedback.

**Comment by zenweasel** [comment]
This should be part of the style guide, but for now we need a way to consistent display errors that require action.

**Comment by zenweasel** [comment]
Right now everything is just being thrown up in a toast. This is actually a regression for some of these fields like price and dimension where we would see the field highlighted, etc.
![dumb_product](https://cloud.githubusercontent.com/assets/72819/26132329/231b1480-3ad2-11e7-81cb-1ee174354192.png)

**Comment by zenweasel** [comment]
I should be able to enter $0.00 as a valid price on a product. Sometimes things are free. Right now I get a "Price is required" toast.

**Comment by zenweasel** [comment]
We don't need to wait for design here, I think we all know the basics of how validation should work. The field should be focused, the error should show next to the field, etc.

**Comment by rymorgan** [comment]
@zenweasel totally agree. If you guys take a stab at it and send it my way when it's done. But yes it should just as you describe.

**Comment by zenweasel** [comment]
I just talked to @kieckhafer and he is willing to take this on. Hopefully we can expand the Autoform replacement work that @mikemurray has been working on

**Comment by rymorgan** [comment]
@kieckhafer let me know when you work on this and we can talk through how the validation should be styled. I'm hoping this is something that does some automatic validation magic with our forms so we're consistent everywhere.

**Comment by aaronjudd** [comment]
Removed "critical impact" with the merge of #2531

**Comment by mikemurray** [comment]
This PR (https://github.com/reactioncommerce/reaction/pull/2893) should be able to close this issue once it's merged

**Comment by mikemurray** [comment]
Also assigned @kieckhafer since he's fixing this in his PR #2893

**Comment by kieckhafer** [comment]
Closed by #2893
