### ISSUE TITLE
Shipping Rates Not Configured Message when checking out multiple times with same guest account

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2275]
### Expected behavior
When at least one shipping rate is setup properly, I should never see the "Shipping Rates are not configured" message

### Actual Behavior
When checking out with a guest two carts in a row, the second and future carts will display the shipping rates are not configured message.
![image](https://cloud.githubusercontent.com/assets/1203639/26091037/7ae2e898-39bd-11e7-8042-cf6e803bb0c0.png)

No server error thrown.

### Steps to Reproduce the Behavior
0. Checkout `release-1.2.0`
1. Make sure shippo is configured and flat rate is off
2. Checkout as a new user (create new account while checking out)
3. After checking out, add another product to your account and click "check out"
4. Observe that shipping rates are missing.

### Versions
```
Node: 7.8.0
NPM: 4.5.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.1
Reaction: 1.2.0
Reaction branch: release-1.2.0
Docker: 17.03.1-ce
```

**Comment by spencern** [comment]
Well, it looks like by the time i took a screenshot, the rates had loaded. Not sure what happened. @aaronjudd had seen this error before as well.

**Comment by zenweasel** [comment]
Are we sure this isn't because there is no, ahem, spinner?

**Comment by cindyfirestone** [comment]
I'm getting this error again on my local version and on the client build, anyone else seeing this issue?
