### ISSUE TITLE
Router Table (Router.routes) keeps on growing in single browser session

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2278]
### Expected behavior
Router Table entries (Router.routes) should remain same if router registry doesn't change.   
### Actual Behavior
Router.routes keeps on growing with each logout-login
### Steps to Reproduce the Behavior
Login in RC in Chrome.
**Reading 1**: run command on Browser console. `ReactionRouter.routes` && `ReactionRouter.reactComponents` note the number of objects.
Log out. 
**Reading 2**: run command on Browser console. `ReactionRouter.routes` && `ReactionRouter.reactComponents` note the number of objects.
Login again
**Reading 3**: run command on Browser console. `ReactionRouter.routes`  && `ReactionRouter.reactComponents`. note the number of objects.
In all readings(1,2,3) number of objects are increasing for  `ReactionRouter.routes`  and does not change for `ReactionRouter.reactComponents`.

### Versions
Node: 6.3.1
NPM: 3.10.3
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.1.1
Reaction branch: development

**Comment by zenweasel** [comment]
@mikemurray Was this closed by #2279

**Comment by mikemurray** [comment]
Yup.
