### ISSUE TITLE
MAIL_URL without authentication not supported

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#2281]
### Expected behavior
When using a MAIL_URL without authentication, i.e. smtp://mail.mycompany.com:25, I would expect Reaction to still be able to use nodemailer.

### Actual Behavior
When RC starts up and calls server/api/core/emails/config.js's getMailConfig(), this error is thrown: Exception in setTimeout callback: TypeError: Cannot read property 'split' of null.

### Steps to Reproduce the Behavior
Set the MAIL_URL environment variable to smtp://mail.mycompany.com:25, startup the app, see the server log.

### Versions
(run `reaction -v` from your reaction directory)
1.1.0

I haven't used nodemailer, but is the fix simply checking if there's auth specified, and if not, not including the auth property in getMailConfig()'s return object? If so, I can make a PR. Thanks!

**Comment by spencern** [comment]
@dancastellon `nodemailer` is a little more @jshimko's territory, but we might be willing to accept a PR on this.

Why do you not want to use one of the many free or nearly free supported smtp mail services out there?

[Mailgun](mailgun.com), [Postmark](postmarkapp.com) and the like are purpose built for sending transactional emails

**Comment by dancastellon** [comment]
Hi @spencern thanks for the reply - mine is somewhat of an edge case. I'm building an internal software subscription site for a large corporate client that insists on using their mail server for sending emails. In any other case I'd use Mailgun.

I'll make a pull request, thanks!

**Comment by jshimko** [comment]
@dancastellon For what it's worth, you should probably also remind your client that in that scenario they'll be sending emails completely unencrypted with no authentication.  That's certainly up to them, but it's a bit of a security risk considering things like password reset emails and purchase receipt emails get sent this way.  That's like sending passwords to a website with no SSL.  No bueno.

But anyway... yes, you're right, parsing the auth part of the `MAIL_URL` string is what's throwing that error.  

https://github.com/reactioncommerce/reaction/blob/master/server/api/core/email/config.js#L81

You'll have to add some logic there to account for no auth existing.  Also, see [the url module](https://www.npmjs.com/package/url) for details on the object that gets returned from the parsed string.

Changing that will possibly break a few other parts of the config parsing too, so make sure to test all possible email settings if you end up submitting a PR.  For example, try setting a "custom" provider in the UI and leave the username/password fields blank.  As things are right now, that will likely result in an error with Nodemailer.

Also, I'm on vacation for the rest of this week, but I'd be happy to review any submissions when I get back.

Thanks!

**Comment by jshimko** [comment]
@dancastellon, the `MAIL_URL` parsing has been updated in #2330 to fix your use case.  Please give it a test drive when you have a moment.  Thanks!

```sh
# clone the PR branch
reaction init -b mail-url-without-auth mail-test

cd mail-test

# start the app with your mail url
MAIL_URL="smtp://mail.mycompany.com:25" reaction
```

**Comment by dancastellon** [comment]
@jshimko thanks for this! I'll test it on my client's env and report back!
