### ISSUE TITLE
Confusing messaging when quantity is below "Warn at" level

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2289]
### Expected behavior
Should see consistent messaging between product grid and product detail page

### Actual Behavior
I see a badge for "Limited Supply" on the product grid (which I _think_ is correct) and "Backorder" on the PDP (which I _think_ is wrong)

### Steps to Reproduce the Behavior
1. Create a product
1. Set a "warn at" quantity at the variant level
1. Set quantity for an option below that level
1. Publish, publish, publish, publish
1. Observe this product on product grid and then detail

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.2.0
Reaction branch: release-1.2.0
Docker: 17.03.1-ce
```

**Comment by aaronjudd** [comment]
@abdulsemiu-atanda  status update on this issue?

**Comment by abdulsemiu-atanda** [comment]
I couldn't reproduce this consistently on the development branch and the time I could reproduce, it happened because for some reason the page didn't reload after publishing the product.

**Comment by zenweasel** [comment]
Nobody has been able to reproduce. Reopen if it comes up again
