### ISSUE TITLE
[PDP] Receive an error when clicking on FB icon in the PDP

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2291]
### Expected behavior
I actually don't 100% know what's supposed to happen (I assume a "Share this") but I don't think an error is what we expect

### Actual Behavior
Error in the pop-up browser
![error_and_dumb_product_](https://cloud.githubusercontent.com/assets/72819/26133236/470abd72-3ad8-11e7-9bea-38c2f17449ed.png)

### Steps to Reproduce the Behavior
1. Configure Facebook sharing in the Dashboard
1, Sign into FB (or sign in when prompted later)
1. Create a product
1. Publish that product
1. Go to the PDP
1. Click on the FB icon
1. Observe the error message

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.2.0
Reaction branch: release-1.2.0
Docker: 17.03.1-ce
```

**Comment by mikemurray** [comment]
May need to try this on a live site. FB may be trying to lookup the localhost:3000 site and getting an error.

**Comment by aaronjudd** [comment]
Tested in 1.3.0 Cannot reproduce.
