### ISSUE TITLE
[PDP] Google+ message not carried over to G+ when sharing

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2292]
### Expected behavior
Message should be the default subject of the share

### Actual Behavior
Message is not used

### Steps to Reproduce the Behavior
1. Configure G+ sharing in Dashboard
1. Create a product
1. Add a message to the G+ sharing
1. Publish
1. Click on G+ message
1. Observe that this message is not used

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.2.0
Reaction branch: release-1.2.0
Docker: 17.03.1-ce
```

**Comment by rnandhakumar1995** [comment]
update the "const url" in "get url" method, which is present in the file "imports/plugins/included/social/client/components/googleplus.js", with the following 
const url = encodeURIComponent(preferredUrl+"&text="+this.props.description);

**Comment by zenweasel** [comment]
Or maybe just remove Google+? Who uses Google+ in 2018?

**Comment by Akarshit** [comment]
@zenweasel Should I remove G+?

**Comment by zenweasel** [comment]
That's a product question. Let's get it working if we can
