### ISSUE TITLE
Setting route permissions via the registry doesn't work

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2297]
### Expected behavior
You should be able to specify permissions/audience in a route in `register.js` and have it take affect.

### Actual Behavior
It doesn't work, you need to programmatically add these.

### Steps to Reproduce the Behavior
1. Create a plugin with a route (you could use the `reaction-example-plugin` as a starting point).
1. Add permissions to the route according to the documentation
1. Observe you still get an error

**Comment by michael-alade** [comment]
This was caused due to the change from Flow Router to React Router.

**Comment by aaronjudd** [comment]
Closed in #2388
