### ISSUE TITLE
Dashboard analytics settings not working.

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2301]
The settings for analytics are not working in the dashboard. They can be configured in reaction.json, but the UI is broken. 

<img width="1005" alt="basic_reaction_product" src="https://cloud.githubusercontent.com/assets/439959/26169262/d6c03366-3af1-11e7-8538-79d2db381d3d.png">

## Versions:
Node: 7.5.0
NPM: 4.1.2
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.2.0
Reaction branch: 1863-toolbar-take2
Docker: 17.03.1-ce

**Comment by efalayi** [comment]
@zenweasel has this issue been re-opened?

**Comment by zenweasel** [comment]
@efalayi I don't understand your question. This issue has not been closed.

**Comment by efalayi** [comment]
I was looking at the referenced issue. My mistake.

**Comment by aaronjudd** [comment]
@zenweasel you self assigned - is this actually in progress? if not... please un-assign.

**Comment by zenweasel** [comment]
No actual work has begun. Unassigning.

**Comment by spencern** [comment]
The real work to be done here should be removing the current implementation of analytics. 
Part two would be a feature that implements analytics in a way that works with our React UI, but that should be done in a separate ticket.
