### ISSUE TITLE
Allow loader passed in to composeWithTracker to render

### ISSUE THREAD

**Issue by Pheonix7284** [reactioncommerce/reaction#2304]
No custom LoadingComponent would appear when passed to composeWithTracker due to reversed logic statement. 

### Expected behavior
A custom loading component that was passed to composeWithTracker should appear before the product fully loads.

### Actual Behavior
No custom loading component appears when passed to composeWithTracker (as render is never reached.)

### Steps to Reproduce the Behavior
No loader is shown when :
export default composeWithTracker(composer, Loader)(Component);
So an example is when loading the Product Details page.  No loader appears before product content loads.

### Versions
Node: 6.10.2
NPM: 3.10.10
Meteor Node: 4.8.1
Meteor NPM: 4.4.4
Reaction CLI: 0.8.2
Reaction: 1.1.1
Reaction branch: development
Docker: 17.03.1-ce

**Comment by zenweasel** [comment]
@mikemurray This was closed with #2303 wasn't it?

**Comment by mikemurray** [comment]
yes it was!
