### ISSUE TITLE
Social login not working (Facebook)

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#2307]
### Expected behavior

When signing up with Facebook, you should be redirected to the Facebook auth page, accept the terms, and be redirected back to the site having been already logged in.

### Actual Behavior

When signing up with Facebook for the first time, it redirects to the Facebook auth page, and on accepting the terms, it redirects back to the site but dies not log the user in. It throws the error `User already exists`

### Steps to Reproduce the Behavior

* As admin, activate Facebook social login using credentials in `reaction.json`
* Log out
* Use `Login with Facebook` button to login
* Observe that on redirect to app, you are not logged in

![fb](https://cloud.githubusercontent.com/assets/19430095/26222011/16c8d3ac-3c21-11e7-8954-341b5d51f318.gif)

### Versions
Node: 6.2.2
NPM: 3.10.9
Docker: 1.13.0
Reaction CLI: 0.6.18
Reaction: 1.2.0
Branch: master

**Comment by zenweasel** [comment]
@kieha Can you specify which branch you are seeing this one? If you were using a more recent version of the CLI it would do that for you.

**Comment by kieha** [comment]
@zenweasel I tested it out on master, development, and kieha-login-views-to-react. I got the same outcome. But I opened this one from master.

I'll update my Reaction CLI though. Thanks.

**Comment by michael-alade** [comment]
@kieha I tested this out and it seems to be working fine on both master and development branch.

**Comment by aaronjudd** [comment]
Facebook is working for me as well.
