### ISSUE TITLE
Completed order screen should break items out by vendor / shop

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2308]
The order completed template that is shown to customer when an order has been completed or when viewing historical orders should split the display of line items, taxes and subtotals on a vendor by vendor basis for orders with multiple vendors.

For single vendor shops, there should be no indication that it's possible to have multiple shops represented in the order.

For multiple vendor shops where an order contains items from a single vendor exclusively, there should be an indicator as to which shop the items are coming from.

Estimated delivery time, taxes paid, and the subtotal should be displayed for each shop. 

The total amount paid should be listed separately from each shop and should be associated with the marketplace.

**Comment by rymorgan** [comment]
**Links for designs below** 

Reaction core team link: 
https://zpl.io/21ICk7

Public link: 
https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/59407f5ea520df15babe054b

**Comment by zenweasel** [comment]
Closed via #2645
