### ISSUE TITLE
Unprocessed items in a completed order that has not been captured should permit user initiated cancellation

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2310]
For orders that have not been processed or had their payments captured, users should be able to cancel an item from the order completed template.

This should be on a line item by line item basis. E.g. can cancel a single line item without affecting other line items.

This should be toggle-able - shop owners should be able to enable or disable this functionality (off by default).

If the payment provider accepts it, this should reduce the amount paid prior to the capture going through.

Once the order has entered the "processing" state, the user should not be able to automatically do this.

**Comment by aldeed** [comment]
It's not currently configurable, but this was otherwise implemented by https://github.com/reactioncommerce/reaction/pull/5010

**Comment by spencern** [comment]
I don't think its too important to be configurable
