### ISSUE TITLE
Order managers should be able to toggle between list and detail view in the order Dashboard

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2323]
Users with permissions to view the list of orders should be able to toggle between list and detail view.

The list view is a "rolled up" view of each order but should still show the most relevant information
* Order ID
* Customer Name
* Order Status
* Order Date
* Order Risk Assessment if `elevated` or `high`
* Transit Status if SHIPPED
* 

#### Resources
- [Orders List View Design](https://app.zeplin.io/project/58af8900737c137280322bd6/screen/58fa9274e553b1e86274a106)
- [Orders Detail View Design](https://app.zeplin.io/project/58af8900737c137280322bd6/screen/58fa864cf7863b791bedfc49)

**Comment by rymorgan** [comment]
Reaction Core Team Link:
https://zpl.io/Z2x3lkS

Public Link: 
https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/58fa9274e553b1e86274a106

**Comment by joykare** [comment]
**Notes:**
- Track progress on branch `joykare-orders-listview-2323`

**Comment by joykare** [comment]
**Notes**
- Merged in Erik's branch to use Sortable Table for list view

LeftOvers
_ General styling -> Including rows
_ Add i18n Translations
_ Re-organising code

**Comment by joykare** [comment]
**Notes**
_Figure out_
-  table border styling
- check-boxes roll-over (Where the avatars change to checkboxes you can select)

**Comment by rymorgan** [comment]
@joykare - When you work on the check box roll-over can you sync with @michael-alade? He's working on a similar interaction on refunds. We should use consistent code and consistent styling. 

Here's a reference for his task: 
https://zpl.io/2pc5sL

**Comment by joykare** [comment]
**Notes**
- WIP PR open for this:
    _ @kieha working off this branch to add some order functionality (the search and filters)
- Styling bits left on the orders:
    _ Pagination on orders list design should be on the top ... using <SortableTable /> the pagination component is rendered at the bottom 
    _ When the orders sideview is open the table doesn't collapse enough to let the whole view be visible
     _ The sorting indicator on each column is different (should be carat-down and up right now its a bar that changes position)

**Comment by kieha** [comment]
Update: 
- filter/search functionality to be added in a separate branch/ticket.
