### ISSUE TITLE
Order managers should be able to export orders to CSV

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2324]
Users with orders export permissions should be able to export a list of orders to a CSV file.

The order export should permit the following
* [ ] Selection of fields that users want exported
* [ ] Date range to include in the export (before, after, between)
* Export filters
  * [ ] Orders with specific status
  * [ ] Orders with value (above, below or between)
  * [ ] Orders with taxes paid
  * [ ] Orders shipping or billing to specific locale
  * [ ] Orders with specific products

We _may_ limit the number of orders exported at a time for performance reasons if there is a need, but we should test that and implement with specific performance goals in mind and not arbitrarily.

#### Resources
* [Papa Parse CSV Lib](http://papaparse.com/)
* [Shopify Export Orders](https://help.shopify.com/manual/orders/export-orders)

**Comment by zenweasel** [comment]
@spencer how do we think we are going to handles nested objects in CSV?

**Comment by spencern** [comment]
@zenweasel 

This is a good question.

I'd like to design the export in that permits us to "import" anything that we export.

The way that Shopify does this and the current way I'm thinking about it is that nested objects turn into new lines in the CSV.

We may need to export "type" columns to identify the different parts of an order that would be nested.

I've seen this done in a couple ways:
### 1) No duplicate content, orders linked by OrderId on every line
| orderId | email                | createdAt | status     | total  | lineItemId | lineItemStatus | shippingAddress               | billingAddress                |   |   |   |
|---------|----------------------|-----------|------------|--------|------------|----------------|-------------------------------|-------------------------------|---|---|---|
| ABC123  | customer@example.com | 1/1/2018  | Processing | 100.93 |            |                | 123 Anywhere St (shipping[0]) | 123 Somewhere Ln (billing[0]) |   |   |   |
| ABC123  |                      |           |            |        | DEF123     | Shipped        |                               |                               |   |   |   |
| ABC123  |                      |           |            |        | DEF456     | Packed         |                               |                               |   |   |   |
| ABC123  |                      |           |            |        |            |                | 345 Other St(shipping[1]      |                               |   |   |   |
| ABC123  |                      |           |            |        |            |                |                               | 22 Billing Pl(billing[1])     |   |   |   |
|         |                      |           |            |        |            |                |                               |                               |   |   |   |

### 2) All primary order fields/content should be duplicated across any sub-object lines. I prefer this because it allows more easily determining certain data without having to massage the csv file manually. (e.g. what items are popular in what zipcodes, by date, etc)
| orderId | email                | createdAt | status     | total  | lineItemId | lineItemStatus | shippingAddress               | billingAddress                |   |   |   |
|---------|----------------------|-----------|------------|--------|------------|----------------|-------------------------------|-------------------------------|---|---|---|
| ABC123  | customer@example.com | 1/1/2018  | Processing | 100.93 |            |                | 123 Anywhere St (shipping[0]) | 123 Somewhere Ln (billing[0]) |   |   |   |
| ABC123  | customer@example.com | 1/1/2018  | Processing | 100.93 | DEF123     | Shipped        |                               |                               |   |   |   |
| ABC123  | customer@example.com | 1/1/2018  | Processing | 100.93 | DEF456     | Packed         |                               |                               |   |   |   |
| ABC123  | customer@example.com | 1/1/2018  | Processing | 100.93 |            |                | 345 Other St(shipping[1]      |                               |   |   |   |
| ABC123  | customer@example.com | 1/1/2018  | Processing | 100.93 |            |                |                               | 22 Billing Pl(billing[1])     |   |   |   |
|         |                      |           |            |        |            |                |                               |                               |   |   |   |

----------------------------------------------------------------------------------------------------

I hope it's clear that these are _not_ all of the fields that we should have in the export, just a subset to describe how I can see nested objects working. The link to Shopify in the issue resources should have a good list of possible fields that users might want, but really we should be giving the option to export any field that's connected to an order.

There's probably even more we can do to make this useful, but hopefully this is enough to start

**Comment by aanchirinah** [comment]
@rymorgan could you please make a design for this feature. I need a mockup to work with.

**Comment by aanchirinah** [comment]
@spencern and @zenweasel I have been able to implement the _Papa Parse_ library in this experiment branch `audax-export-orders-to-csv`, to try it out just navigate to your orders action view panel click the `EXPORT TO CSV` button and it will download `.csv` file with the orders. Its a work in progress but I would like to sync up with @spencern for more discussions on the implementation.

- I added a server side meteor method to handle the fetching of orders from the Orders collection [here](https://github.com/reactioncommerce/reaction/blob/audax-export-orders-to-csv/server/methods/core/orders.js#L1144)

- I also added these helper functions to handle the parsing and download of the csv file ,[here](https://github.com/reactioncommerce/reaction/blob/audax-export-orders-to-csv/imports/plugins/core/orders/client/helpers/index.js#L185)

**Comment by zenweasel** [comment]
So discussing this with @spencern I think we decided that we want to make this an initial simple version that could be used for simple order reporting. But we also want to define an architecture to allow people to build out their own exporters as most people will have specific requirements.

1. We should have a structure similar to `shipping` or `payments` where we have a `core` plugin that manages all the different export plugins and then specific implementations (e.g `simple-order-csv`).
1. This initial implementation should just included flattened, "top-level" values such as id, date, name, billing and shipping address (broken out), order totals (items, tax, discount, shipping, and grand total), and email. I think this should satisfy the needs of people who want a simple export for order reporting.

Also just to document our discussions, this should select orders for a date range, or by unexported, it should put the task in a job and give them the options to either download to the client, or place in a location on the server somewhere (for when the file might be large). Also it should set an `exported` flag once complete so that we can select all orders that haven't been exported.

**Comment by zenweasel** [comment]
This was moved to a [separate repo](https://github.com/reactioncommerce/reaction-export-orders-csv). Closing this ticket here
