### ISSUE TITLE
Order managers should be able to select orders to from the orders list

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2325]
Users with permissions to view the orders list should be able to select or "check" orders within the order list.

There should be a method to select all orders currently listed, taking current filters or search criteria into account. 

There should be a method to check or uncheck individual orders within the order list.

#### Resources
* [Orders Bulk Actions Design](https://app.zeplin.io/project/58af8900737c137280322bd6/screen/58faa0e175ba8a9495284660)

**Comment by rymorgan** [comment]
**Link for designs below** 

Reaction core team link: 
https://zpl.io/Z1MCuWh

Public link: 
https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/58faa0e175ba8a9495284660

**Comment by kieha** [comment]
Notes:
- Track progress on `kieha-select-orders-2325`

**Comment by kieha** [comment]
Updates:
- Select multiple orders/all orders listed functionality implemented
- Checking/unchecking functionality implemented
- Have most of the designs implemented

**Comment by kieha** [comment]
Updates:
- PR: https://github.com/reactioncommerce/reaction/pull/2549

**Comment by rymorgan** [comment]
Here are my notes for the design implementation so far. 
![orders-list-select](https://user-images.githubusercontent.com/20409254/28093887-58753bae-664e-11e7-8c27-26d7ff480482.png)

**Comment by rymorgan** [comment]
@kieha Here's an example for the implementation of the uncheck/check I got from @mikemurray 

Example:
<IconButton toggle={true} toggleOn={true} icon="fa fa-times" onIcon={"fa fa-star"} onToggle((event, isToggledOn) => {}) />`
https://styleguide.reactioncommerce.com/reaction/guide/button

**Comment by kieha** [comment]
@rymorgan not entirely sure what you mean by `rectangle for unchecked` on the checkbox unchecked status. Mind giving a visual example, like a checkbox with the rectangle in it perhaps?

**Comment by rymorgan** [comment]
@kieha And I talked this through on slack. And I added notes to zeplin here: 
https://zpl.io/RwXUT

**Comment by kieha** [comment]
@rymorgan I made the improvements as requested. The PR is ready for another design review.

**Comment by kieha** [comment]
Closed by #2549
