### ISSUE TITLE
Tests should report consistent outcome  across platforms/OS(s)

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2326]
### Expected behavior
Consistent behavior across platforms
### Actual Behavior
Different results
### Steps to Reproduce the Behavior

- On windows 10, latest Master.  The Stat is (130 Passing, 10 Pending, 138 Failing).
   `meteor test --once --full-app --headless --driver-package dispatch:mocha`
     `reaction test` does not work on windows

-  On unbuntu 16.04 
     `reaction test` failed with time out error.  **timeout of 6000ms exceede.**
    `meteor test --once --full-app --headless --driver-package dispatch:mocha` reports   stat of 264 
     passing, 11 pending,  5 failing.

**Comment by aaronjudd** [comment]
@zenweasel please review, verify tests run on windows platform correctly.

**Comment by zenweasel** [comment]
Running tests on this windows box I get:
```
I20180206-09:06:13.980(8)?   186 passing (1m)
I20180206-09:06:13.981(8)?   22 failing
```
Which of course makes no sense

So they don't appear to be running correctly. @hrath2015 Do you see the same thing?

**Comment by hrath2015** [comment]
For me final few lines are:
```js
I20180206-22:39:44.654(5.5)?
I20180206-22:39:44.655(5.5)?
I20180206-22:39:44.656(5.5)?   302 passing (1m)
I20180206-22:39:44.657(5.5)?
I20180206-22:39:44.657(5.5)? Load the app in a browser to run client tests, or set the TEST_BROWSER_DRIVER environment variable. See https://github.com/DispatchMe/meteor-mocha/blob/master/README.md#run-app-tests
INFO: Could not find files for the given pattern(s).
```

**Comment by zenweasel** [comment]
Ok, I am taking @hrath2015's confirmation that this is fixed and closing.
