### ISSUE TITLE
Cascading Effect of 1 Failed Test Case on others (mostly all fail)

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2348]
### Expected behavior
If 1 test case fail than there should be no impact on others.
### Actual Behavior
That is is not the case.  Tested  both on windows 10 and Linux Ubuntu 16.04. 
### Steps to Reproduce the Behavior
Change code at below line  to fail the test.
https://github.com/reactioncommerce/reaction/blob/development/imports/plugins/included/search-mongo/server/publications/searchresults.app-test.js#L132
 **like:**
`//expect(results.count()).to.equal(1);`
     ` expect(0).to.equal(1);`

Now your results will be  130 passing and 138 failing.

In Most cases  the failures message is:
**Attempted to wrap hasPermission which is already wrapped**

### Versions
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.4
Reaction: 1.2.0
Reaction branch: development

**Comment by spencern** [comment]
@zenweasel @hrath2015 Closing this issue. Open it back up if #2349 did not fix it.
