### ISSUE TITLE
Search orders by orderId

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2353]
Users with permissions to view orders dashboard should be able to quickly search orders by OrderId. In small shops, the first 4-5 characters of an `orderId` should likely be sufficient to identify a single order, in large shops, it may require 6-8 characters, but still the most simple way to look them up.

Users should be able to type the first few characters of an orderId and hit enter:

If there is more than one order with a matching id `/^${searchString}/i` -  the search UI should replace the existing list of orders in the orders dashboard with the results of the search. **Any existing custom sorting (e.g. sort by recently shipped, customer name, etc) or filtering (filter by status, between dates, etc) the user has done should persist.**

If there is exactly one order with a matching id, the matching orderId **should be opened in the action view panel (i.e order summary panel)** if the user has permission to view that order.

If there are no matching orders, there should be a "No orders found with that ID" message displayed inline to the user. The user should also be prompted if there are any filters enabled that might hide results.

I think this search should be case insensitive. It does increase the possibility of false positives, but not by much. A single extra character is more than likely enough to permit case insensitive search at the same level of accuracy for most order sets.

Extends #2152 with specifications.

Annotated Designs in Zeplin:
Web: https://zpl.io/1r0Vvm
App: zpl://screen?pid=58af8900737c137280322bd6&sid=58fa9b08c1ee69df600c0469

Related to: #2046

**Comment by impactmass** [comment]
Update: WIP PR on this #2717. Needs #2688 to be merged first.

**Comment by zenweasel** [comment]
Closed via #2717

**Comment by aaronjudd** [comment]
@zenweasel ok, so then we should close it?
