### ISSUE TITLE
Search orders by customer information

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2354]
Users with permissions to view orders dashboard should be able to quickly search orders by customer information.

Users should be able to type:
-  Customer first or last name
-  Customer phone number
-  Customer email address
-  Last 4 of customer credit card (Maybe useful?)

If there is more than one order with a matching customer information - the search UI should replace the existing list of orders in the orders dashboard with the results of the search. Any existing custom sorting (e.g. sort by recently shipped, customer name, etc) or filtering (filter by status, between dates, etc) the user has done should persist.

If there is exactly one order with matching customer information, the matching orderId should be opened in the action view panel if the user has permission to view that order.

If there are no matching orders, there should be a "No orders found" message displayed inline to the user. The user should also be alerted if there are any filters enabled that might hide results and the alert should permit the user to turn off all filters and run the search again.

This search should be case insensitive.

Extends #2152 with specifications.

Annotated Designs in Zeplin:
Web: https://zpl.io/1r0Vvm
App: zpl://screen?pid=58af8900737c137280322bd6&sid=58fa9b08c1ee69df600c0469

Related to: #2046

**Comment by impactmass** [comment]
Update: WIP PR on this #2717. Needs #2688 to be merged first.

**Comment by zenweasel** [comment]
Closed via #2717
