### ISSUE TITLE
Search orders by product, variant, or option title

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2355]
Users with permissions to view orders dashboard should be able to quickly search orders by the order items.

This search should be fuzzy and case insensitive.

Users should be able to type:
-   Product Title
-   Variant Title / Label
-   Option Title / Label

If there is more than one order with matching products - the search UI should replace the existing list of orders in the orders dashboard with the results of the search. Any existing custom sorting (e.g. sort by recently shipped, customer name, etc) or filtering (filter by status, between dates, etc) the user has done should persist.

If there is exactly one order with matching customer information, the matching orderId should be opened in the action view panel if the user has permission to view that order.

If there are no matching orders, there should be a "No orders found" message displayed inline to the user. The user should also be alerted if there are any filters enabled that might hide results and the alert should permit the user to turn off all filters and run the search again.

Extends #2152 with specifications.

Annotated Designs in Zeplin:
Web: https://zpl.io/1r0Vvm
App: zpl://screen?pid=58af8900737c137280322bd6&sid=58fa9b08c1ee69df600c0469

Related to: #2046

**Comment by aaronjudd** [comment]
Closed in #2717
