### ISSUE TITLE
New Tags Menu SideBar Glitch 

### ISSUE THREAD

**Issue by katiebvogel** [reactioncommerce/reaction#2356]
It looks like this is related to some previous issues that HAVE been fixed.  One more detail that doesn't seem to be what we'd expect: 

When in small screen view, the drop down side bar appears and allows us to view all tags (parent and child-level).  We should be able to select the parent-level tag by clicking on "View All" 

When selecting "View All", we see "#"   added to the url, but no re-route to the list page. 

![screen shot 2017-05-26 at 2 01 08 pm](https://cloud.githubusercontent.com/assets/16321291/26509533/c09a246e-421e-11e7-9d16-f6c939031c0f.png)

**Comment by aaronjudd** [comment]
@rhenshaw56  Note that the nav bar has been rewritten in React, so this needs to be reproduced/investigated with 1.3.0..

**Comment by zenweasel** [comment]
Closed via #2472
