### ISSUE TITLE
Multi-ownership functionality - user generated multi-stores functionality

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#236]
I would like make a multi-ownership ecommerce platform based on reaction.
Like ebay with user-generated content with very basic functionality.
This requires to add a feature of creating and managing products by owners of them.

Does anyone have any suggestions or approaches to this feature? 
What the best way to inject ownership into code? How this functionality could be plugged in?
External application or part of core with settings?

Any suggestions are apreciated!

**Comment by aaronjudd** [comment]
We actually designed from the scratch to work this way, and had code to handle but removed when iron-router wouldn't support subdomain routing (we figured we'd just postpone this functionality).  The `Shops` collection + `shopId` combined with roles collections should be examined to see how this was implemented.  In theory, it should work to add additional shops to the Shops collection, and see if the roles are still working properly.  In this case, each user gets their own "shop".  If you didn't want to have unique "shops", you could alter the product grid to display all products (and not a specific shops), but still retain the "shops" filters when editing/adding products (to associate with their shop). 

Another approach, we were thinking of a 'marketplace' approach in the future, where we'd use DDP to get products from each list shop, into another "master marketplace". This could work without altering much of the core, but we'd need to remove the fixture shopId and create a new one for each new shop.

**Comment by ramusus** [comment]
Thanks, @aaronjudd, this clarified a lot for me. I don't need subdomain support

**Comment by kelemenbalazs** [comment]
That would be awesome if the subdomains will be supported in this feature, maybe later with ssl support.
