### ISSUE TITLE
Sort Orders by Column

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2363]
Users with permissions to view orders dashboard should be able to quickly sort the list of orders by clicking the column header for any column in the orders list.

When clicking the column header the orders should be sorted according to that column.

First click should sort the column in ascending order, second click should sort the column in descending order. A third click on the column should clear any sorting by that column and return to the default sorting.

Clicking a different column when one column is already sorted should reset the click order and sort the column just clicked in ascending order.

Clearing all filters should also reset the sort order (#2358)

**Comment by rymorgan** [comment]
**Links for designs below** 

Reaction core team link: 
https://zpl.io/1r0Vvm

Public link: 
https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/58fa9b08c1ee69df600c0469

**Comment by spencern** [comment]
@rymorgan can this issue be closed?

**Comment by rymorgan** [comment]
Yep!
