### ISSUE TITLE
Orders should be splittable and support multiple partial orders

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2367]
*Note: this may turn into an Order Splitting Epic and be moved out of the general Marketplace Orders epic*

**NOTE: THIS TICKET IS A WORK IN PROGRESS - TALK to @spencern BEFORE WORKING ON THIS TICKET**

## Order Splitting Proposal

To support split shipments, orders from multiple vendors, and marketplace style orders, we should update our order system to support order splitting in some way.

The first case for this is that there is a need for traditional, single-seller shops to support shipping items out in multiple groups or at multiple times. There are a few specific use cases we must support in this case.
-   Selling items from multiple warehouses or shipping locations
-   An order where some items are back ordered, but not waiting to ship the rest of the order
-   Splitting a shipment because there are multiple shipping requirements (e.g. Express part of the order, ship the rest via Ground)

The second case for this is for a marketplace implementation where a single order can have multiple vendors represented.

## How to accomplish Order Splitting technically
Order splitting could be accomplished in a few ways
1.  We could keep track of status on an item-by-item basis (I think we should do this anyway) and *split* orders by creating a data subscription that only permits view of the "partial" order.
    -   **Positives**
        -   Only one document to lookup for each full order, including partials
        -   We don't need a separate process to split orders when they are created
        -   Views of orders are based on permissions and can be split by witholding information from publication/subscription
        -   Works with current schema
        -   Doesn't require breaking changes
    -   **Negatives**
        -   Looking at an order in DB doesn't provide as full of a picture
        -   Single orderId
        -   May be harder to have multiple partials showing up separately in the orders list. (e.g After one partial has shipped, but another still needs to be packed)
        -   Partial order status must be reduced from status of order items
2.  We could split orders into a parent order and child orders and have separate database documents for each, with each child order containing only the information required.
    -   **Positives**
        -   Each child or partial order can carry it's own status.
        -   Unique orderIds for each partial
        -   Easier to show multiple partials as unique in orders list
    -   **Negatives**
        -   More complicated
        -   To lookup all parts of an order requires accessing multiple documents
        -   Permissions checks and smart publications still required for many roles
        -   Requires re-architecting the data schemas
        -   May be a breaking change or a lot of work to make migrations
3.  Some hybrid of the two.

I think that option 1 is probably the way to go, but we should discuss these options and determine if there's anything missing that option 1 won't be able to support.

#### Shop Configuration
-   Shop owners should be able to configure additional fulfillment services such as:
    -   Warehouse / Shipping Location: Each shipping location could be viewed as a separate fulfillment service.
    -   Drop Shipper: Enter an email of the drop shipper fulfilling the product and automatically setup a fulfillment account for them. (Automatically setup for Reaction Cloud Catalog based products?)
    -   3PL: Enter an API Key and a URL to POST to (May need a semi-unique plugin for each 3PL) and we send the partial order to that URL.

#### Product Configuration
-   Shop owners should be able to specify a fulfillment service for each product (Default, ships from shop)
-   Shop owners should be able to specify multiple fulfillment services / locations for a single product (e.g. ships from Warehouse 1, or Warehouse 2)

#### Automatic Order Splitting
-   When an order is placed with multiple fulfillment services - a partial order should be created for each fulfillment service

#### Order Processing
-   An item which has fulfillment executed by a third-party entity (Drop Shipper, 3PL, etc) that item should not be fulfillable by the shop, but users with appropriate access should be able to view fulfillment status.
-   A third-party fulfillment provider should be able to process an order from their dashboard without seeing order details that aren't specifically needed for fulfillment (price, billing info, items they are not fulfilling, etc)
-   A third-party fulfillment provider should be able to mark items as fulfilled, or update the steps along the way (Picked, packed, etc) via API.
-   A user with order fulfillment permissions should be able to split an order's shipments based on which items have been picked already (see Diag. 1)
    -   Splitting an order's shipments should create two partial orders, one which is now "Picked" and the other which should be reset to new.
![image](https://cloud.githubusercontent.com/assets/1203639/26594501/12cece0c-4525-11e7-988a-88c0297cf6e9.png)
-   When all partials of an order have reached a status threshold, (e.g. all shipped), the order should be marked as having reached that threshold. Otherwise the order should show a partial state for the furthest along partial. (e.g. Partially Shipped).

#### Automatic Order Splitting
-   When an order is placed with multiple vendors represented - a partial order should be created for each vendor

#### Marketplace Order Processing
-   Each vendor should only be able to view their specific partial order.
    -   Vendors should have no knowledge of any details of the larger order.
    -   Each order should appear to the vendor as if their order is the entire order.
    -   Each vendor should only be able to fulfill or take action on their specific part of the order.
-   Marketplace owners should be able to see all aspects of all orders, including each sub order and which vendor is responsible for each sub order.
    -   Marketplace owners should be able to cancel an entire order, cascading that cancellation down top the sub-orders.
    -   Marketplace owners should be able to refund an entire order, with refunds cascading to sub orders as well
    -   Marketplace owners should be able to take action on any part of any order.

## Questions:
1.  Are there any *use cases* for order splitting that are not represented here?
2.  Are there any *requirements* for order splitting that are not represented here?
3.  How many different levels of permissions are required for these features?
4.  What are the most important features for your shops?
5.  Which of these requirements are not priorities for the first release of split orders?

**Comment by zenweasel** [comment]
@spencern Can we update this ticket to reflect the new approach that you and I talked about? I wonder if this isn't something that you or I should work on or at least work closely with someone.

**Comment by spencern** [comment]
@aldeed @kieckhafer  this is an ancient ticket, but I'm curious how it matches up with the work y'all did recently on order splitting.

**Comment by kieckhafer** [comment]
The work would definitely be a start to get this ticket accomplished, however I don't believe that there is currently any code to split the shopId of an order, or an order item, in any of the new mutations. This ticket seems like it's probably more of an extension of the work @aldeed did on the order splitting.

**Comment by aldeed** [comment]
@spencern Agree with @kieckhafer. Much of this is done now and other pieces can no longer be done because we no longer allow items from multiple shops in the same order. It may be worth a short discussion at some point to go through this list of requirements and identify which are still valid, to make a smaller and updated epic.

**Comment by spencern** [comment]
Thanks @aldeed and @kieckhafer  I'll close this for now, but we can reference it in the future if we need.
