### ISSUE TITLE
Smart Tags

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2368]
Navigation level tags should have the option of showing products from multiple tags.

e.g. clicking navigation tag "Sweaters" should have the option of showing tags "knitwear", "sweaters", and "sweatshirts"

**Comment by aaronjudd** [comment]
Perhaps, like elasticsearch we could build a synonyms library?  Or is this really just an routing task?

**Comment by mikemurray** [comment]
This PR https://github.com/reactioncommerce/reaction/pull/2747, which adds additional fields to tags schema, may help with this.

**Comment by spencern** [comment]
I think having metafields on tags will help a lot with this.

"Smart Tags" would probably be a good candidate for a plugin at this point and I think could be accomplished with metafields

**Comment by aaronjudd** [comment]
Feature request that requires more definition to meet our current issue guidelines.

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #21](https://github.com/reactioncommerce/reaction-feature-requests/issues/21) via [**ZenHub**](https://www.zenhub.com/)
