### ISSUE TITLE
I need to add "text input" to products oder.

### ISSUE THREAD

**Issue by nygava** [reactioncommerce/reaction#2370]
I apologize If I am posting this question in the wrong place, I am a new user.  I did search to find if someone asked same.

My shop is selling custom t-shirts, and customers will provide me the text and the image before they order, and I print them after taking their payment.

I deployed a standard reaction shop, all I want to add is, a Text Input and an upload image input from the customer that orders a product.

Is this already done or do I need to code for that? how hard it is to have something like that ?

**Comment by spencern** [comment]
Hi @nygava 
This is possible by adding a component to the product detail page, which you can find in the templates collection. 

@mikemurray @kieckhafer, can't find the docs on this, can one of you point @nygava in the right direction?

**Comment by nygava** [comment]
@spencern thank you so much, what I am confused is, how can I make that be inserted to the database? and be showed on the order, so when someone goes to process to order have that information.

does that mean we will need to edit the database schema?

is this a super easy thing to do ? is there any way you help us to make this as example plugin? I am sure a lot of other people will love to follow this as an example plugin to build more great thigns on the top of reaction commerce.
