### ISSUE TITLE
Refund returned orders

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2374]
users with orders permissions should be able to refund orders that have a return processing.

Once an RMA has been generated and the order has a status of Returning, it should be possible to refund the order (if the whole order has been returned) or a part of the order (if only part of the order has been returned) with one click.

Refunding the order should update the order status as either Refunded or Partially Refunded.

Refunding the order should trigger an Order Refunded event.

The Order Refunded event should send an email to the customer and add a notification to their notification list.

**Comment by rymorgan** [comment]
**Links for designs below** 

Unopened refund panel
https://zpl.io/Z1BR2E7

Nothing selected for refund  
https://zpl.io/Z1o9ExU

Items selected for refund
https://zpl.io/Z10oeN1

For reaction core members, all of this is in the orders project if you have the Zeplin app. 

Public link to work on orders: 
https://scene.zeplin.io/project/58af8900737c137280322bd6

And public link to work on returns: 
https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/59360099e99b7a2f61696c59

**Comment by aldeed** [comment]
This feature exists as of 2.0.0
