### ISSUE TITLE
Copy order link to the clipboard

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2379]
Users with orders permissions should be able click a link or button to copy the order link to the clipboard from the order detail page.

This also implies that it should be possible to directly link to any given order.

**Comment by kieckhafer** [comment]
The <ClickToCopy /> component is now available in `development`. We still need to figure out how we want to use a URL to open the panel.

**Comment by spencern** [comment]
I created a new issue for opening the action view to a specific panel and section from a url.
https://github.com/reactioncommerce/reaction/issues/2859
