### ISSUE TITLE
Error: Node modules were not successfully installed. Exiting.

### ISSUE THREAD

**Issue by boubex** [reactioncommerce/reaction#2380]
when i do
   `react init`

i get the following error on osx

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bititawehoaboubakar/.meteor/packages/meteor-tool/.1.4.4_3.c3mu53++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/.npm/_logs/2017-06-01T05_46_26_563Z-debug.log

> Error: Node modules were not successfully installed. Exiting.

**Comment by jshimko** [comment]
Have you installed all of the requirements for macOs already?

https://docs.reactioncommerce.com/reaction-docs/master/requirements

**Comment by zenweasel** [comment]
Hey @boubex let us know if you are still having this issue and you can reopen or better yet get support in our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead
