### ISSUE TITLE
Display split view for orders that have multiple shipments or vendors

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2383]
For users that have permissions to view multiple parts of an order that has multiple shipments, vendors, or one or more refunds, the UI should split the display of each part of an order.

Users that have view into only a single part of the order, should see that part as the whole order.

**Comment by rymorgan** [comment]
Users that don't have permissions see the standard view for orders. Users that have permissions to see the whole order, see the below designs: 

**Links for designs below** 

Reaction core team link: 
https://zpl.io/gc2GJ

Public link: 
https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/593b33c95da8f4f5eceb85f3

**Comment by spencern** [comment]
@zenweasel This issue was waiting on your mongo aggregate PR correct?

**Comment by aaronjudd** [comment]
@spencern is this really a blocker for `marketplace-alpha`?

**Comment by spencern** [comment]
@aaronjudd You're probably right, I don't think this blocks a single-shop instance of Reaction, so I'll remove the `marketplace v1.5.0` label.

**Comment by aldeed** [comment]
No longer applicable in 2.0.0+
