### ISSUE TITLE
reaction test

### ISSUE THREAD

**Issue by asholly129** [reactioncommerce/reaction#2397]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Versions
(run `reaction -v` from your reaction directory)

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by zenweasel** [comment]
@asholly129 Can you provide a little more detail?
