### ISSUE TITLE
Unclear how to remove product option and a little UI bugginess

### ISSUE THREAD

**Issue by MaxPleaner** [reactioncommerce/reaction#2404]
While looking at the default generated product, I tried to remove the red/green variants but had a hard time doing so. All I saw was the "archive" button, and even then, the UI looked buggy:

(all three are archived here, and the labels are not spaced correctly and/or responsively)

![reaction](https://user-images.githubusercontent.com/5035719/26852991-082c6f04-4ac5-11e7-9ffc-dfea70f59d41.png)

Eventually I realized that it is possible to remove options by setting the name to an empty string. This
seems to not be a very intuitive way to do it, though. Seems like there should be a button for it. 

### Versions

1.2.0

**Comment by MaxPleaner** [comment]
Also, I'm not sure how to delete the Variants themselves, as shown in this screenshot:

![reaction 2](https://user-images.githubusercontent.com/5035719/26853476-07a0bd90-4ac7-11e7-9903-4c51925a631e.png)

**Comment by aaronjudd** [comment]
@rymorgan this needs some review and some design direction before we fix this... two things here: UI layout of the labels, and also the general behavior...

**Comment by rymorgan** [comment]
Yep, totally. This has always bugged me.

**Comment by spencern** [comment]
@MaxPleaner 
We're aware that this is a pretty big UX issue. 

To "fix" your problem, you probably just need to hit the "Publish" button in the upper right hand corner of the screen. If that doesn't work, check for server errors and/or client console errors.

**Comment by stunjiturner** [comment]
the ability to reorder product options would be helpful as well, ex, if i add 3XL to a product line it will not show up after S

**Comment by spencern** [comment]
@stunjiturner - this is a good suggestion, would you mind creating a new issue for it so it doesn't get lost?

**Comment by stunjiturner** [comment]
Will do

S. Tunji Turner
sightuary

**Comment by kieckhafer** [comment]
The UI bugginess (overlapping) was fixed by @machikoyasuda . In addition, we'll be removing some of the icons from this area and moving them over to the sidebar in PR #2893, so more of the UI issues will be fixed.

**Comment by Akarshit** [comment]
The icons/badges have been moved around to fix this.
1. The visibility badge is replaces by setting the opacity of the variant/option.
2. Backorder badge is removed and is now only available in the sidebar.

These changes fix the problem as can be seen in the screenshot below.
<img width="560" alt="screen shot 2018-02-09 at 1 50 11 pm" src="https://user-images.githubusercontent.com/7762605/36018106-8378bb38-0da0-11e8-861c-c87d967b97a2.png">
