### ISSUE TITLE
Testing reaction with velocity

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#241]
Implementing testing frameworks in reaction, using velocity + testing tools for Reaction.

Continuing issue discussion from https://github.com/reactioncommerce/reaction-core/issues/57

**Comment by ramusus** [comment]
> @ramusus I merged the tests pull requests. Couple of thoughts - I changed the symlinks to use package names as cloned from github, so that you can checkout directly into packages, or symlink direct into package dir - naming doesn't matter there, as long as you use the name: key in the package declaration.

> Also saw that you added mocha and jasmine. From the velocity docs: We currently do not recommend installing both Jasmine and Mocha at the same time. Not sure what the results will be. 

I tried to move tests from mocha to jasmine and remove mocha dependency completely. The result was braking 2 jasmine tests with recommendation in error to use Fiber for some reason. It seems to be very strange, that existance of some tests brakes another, so I give up that problem for a while. Imho syntax of mocha is more readable, then jasmine. But I'm not sure if mocha support all of jasmine capabilities.

> To me, velocity isn't really focused on package testing, but rather app testing. I've mentioned this before, and am not sure what's been done about this, but I sort of hate the fact that we have to add symlinks in the app, really tests existence should be automatically detected by velocity. Perhaps we could add a bash script, or even a build plugin to detect packages with tests and add them at the app level.

Completely agree with you about symlinks. It makes complicated or even impossible to add tests from all packages. I'm thinking this is temporary solution, just helps me to start writing tests and execute and keep them in right place.

**Comment by ramusus** [comment]
Good news! Velocity team merge my PR with autodiscovering packages tests to the **develop** branch of application. https://github.com/meteor-velocity/velocity/pull/231
So we don't need symlinks in the tests directory as soon as **develop** will merge with **master** branch.

**Comment by aaronjudd** [comment]
That's awesome, that will save a lot of headaches

**Comment by boboci9** [comment]
Hi I had a look at your code in https://github.com/reactioncommerce/reaction-core/tree/development/tests but I am getting error at Fixtures: ReferenceError: Fixtures is not defined and if I comment out the Fixtures I get "Error: Expected function to throw { error: 403, reason: 'Access Denied' }, but it threw TypeError: Cannot call method 'apply' of undefined." from this line expect(function() {
return Meteor.call("flushTranslations");
}).toThrow(new Meteor.Error(403, "Access Denied"));
Can you tell me how are you having access to Fixtures?
I also realized that if I try to use spyOn(Products, 'find'); it is working fine but spyOn(Orders, 'find'); is giving me an error ReferenceError: Orders is not defined. Do you know why could that be?
Thanks!

**Comment by ramusus** [comment]
@boboci9 Yes tests are passed successfully in my current environment. And Fixtures are defined and in the current scope.
I found there is difference in scopes for tests in client and server directories. Jasmine integration tests in the server directory and on that side Fixtures should be available.

Could you provide applications versions you use?

**Comment by spencern** [comment]
Had some issues getting the velocity tests to run on current development branch. Couldn't end up getting them to run at all from symlinked directories. Have the jasmine tests running now by copying the tests from the reaction-core folders to the tests directory in the reaction app. Biggest issue right now is that the tests aren't running when files change and I have to restart the meteor server to get them to run.
When I run `meteor --test`
I get this error before the tests run.
`stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED

After this error, the tests run fine once, but don't rerun when files change. Not sure if they are related or not.

A lot of the tests are currently failing, but that seems to be due to the addition of checks for variables in certain meteor.methods.

Failing tests are incredibly verbose. (see pastebin: http://pastebin.com/v2UQzUk3)

**Comment by spencern** [comment]
Accidentally found a way to get tests to work from symlinked directories, but had to trick the system to do it.
1. Renamed the symlink to jasmine-sym
2. Create identically structured folder within the main reaction app. `tests/jasmine/server/integration/methodsSpec.coffee`
3. Start meteor
4. Rename directory within reaction app to jasmine-foo
5. Rename symlink to jasmine

At this point I can change code within the reaction-core test folders and it will update on the system, but if I restart the server, I have to do that process over again. 

Looking forward to being able to use Velocity with packages without having to move tests.

**Comment by aaronjudd** [comment]
With the recent release of velocity 0.6 the package tests are now passing (without any special configuration).  

```
mike:mocha
sanjo:jasmine
```

I'm thinking we should start leaving these enabled in ./meteor/packages by default, and start working on coverage. There will probably need to be some detailed guidelines, but generally, start requiring some coverage for all future new or *changed* functionality, and packages.

**Comment by ramusus** [comment]
Completely agree with that. Today I updated reaction and reaction-core to the last development branch and gonna help with coverage

**Comment by aaronjudd** [comment]
@ramusus thanks!  this is a big step forward.  I've added some new tests continuing where you left off (https://github.com/reactioncommerce/reaction-core/pull/129) and enabled jasmine by default (seems mocha has some remaining issues).  

The only downside to having jasmine added by default, is that if you checkout reaction, and are running the package version of core you get the velocity test console, but no tests.  Easily, and understandably - you just need to clone the reaction-core package,etc.. 

Oh, and, of course code changes are twice as slow to refresh as well.

**Comment by aaronjudd** [comment]
I think this issue should be closed now,  I've created a new issue for coverage https://github.com/reactioncommerce/reaction/issues/373
