### ISSUE TITLE
Add <Avatar /> component to NavBar

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2410]
After PR #2400 is merged, use the new <Avatar /> component to replace gravatar in the Nav:

https://github.com/reactioncommerce/reaction/pull/2306/files/24cdc7dce132a93718a70fda6fb69c48c452d7c2#diff-4368d0dc7ddd23433d47710609d997eb

**Comment by kieckhafer** [comment]
New component is now called `<ReactionAvatar />

**Comment by zenweasel** [comment]
@kieckhafer Did we do this already?

**Comment by kieckhafer** [comment]
@zenweasel just made a PR for it.

**Comment by zenweasel** [comment]
Nice

**Comment by kieckhafer** [comment]
PR'd in #3149
