### ISSUE TITLE
Search doesn't work well when the item is in Chinese

### ISSUE THREAD

**Issue by allanjsx** [reactioncommerce/reaction#2419]
### Expected behavior

Partial search of item title in Chinese should show results. For example, if the item's title is "奥迪汽车"（Audi Car），when you search “奥迪” （Audi），the item should show up。

### Actual Behavior

the item doesn't show up unless your search query match the full name

### Steps to Reproduce the Behavior

1. Create a item with title：“奥迪汽车”
2. Search “奥迪”

**Comment by aaronjudd** [comment]
See: https://docs.mongodb.com/manual/reference/text-search-languages/

>Changed in version 3.2: MongoDB Enterprise includes support for Arabic, Farsi (specifically Dari and Iranian Persian dialects), Urdu, Simplified Chinese, and Traditional Chinese. To support the new languages, the text search feature uses the three-letter language codes defined in ISO 636-3. To enable support for these languages, see Text Search with Basis Technology Rosette Linguistics Platform.

There are other approaches, of course, such as elasticsearch, etc...
