### ISSUE TITLE
Standardize, implement logging library

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#242]
Implement Bunyan as a logging library (likely a new meteor package), and replace all instances of `console.log` with call to new library. 

Choice of Bunyan is for native json format being useful potentially for sharing activity data -> into a collection with a reactive view for instance, or tracking across a cluster. Could be tied to moments in the revisions history logs as well.

**Comment by evliu** [comment]
do you mean Bunyan? Bunyon looks like it hasn't been updated in 2 years

**Comment by aaronjudd** [comment]
Yes :+1: , updated.
