### ISSUE TITLE
Non-admin user not able to add/edit/remove product tag in Product details

### ISSUE THREAD

**Issue by vigyano** [reactioncommerce/reaction#2426]
### Expected behavior
Non-admin user who can manage the product should be able to add/edit/remove product Tags in Product details page

### Actual Behavior
Non-admin users are not able to manage(add/edit/remove) the Product Tags for new or existing products

### Steps to Reproduce the Behavior
1) Clone https://github.com/reactioncommerce/reaction-example-plugin.git
2) Create new Account and provide all permissions to that account
3) Verify Email for new account
4) Login with new account
5) Edit existing product
5) Click Tags on right side panel
6) Only the Tags are read-only and not able to add/edit/remove any tags.

### Versions
$ reaction -v

Node: 4.4.7
NPM: 2.15.8
Docker: 1.12.6
Reaction CLI: 0.7.9
Reaction: 1.2.0

**Comment by zenweasel** [comment]
@vigyano Does this happen who you don't have the example-plugin installed? When you say "all permissions", what exact permissions are you providing?

**Comment by vigyano** [comment]
It happens both with example plugin and as well as my custom plugin.
All permissions I meant, admin enabling the permissions for that account. First I enabled UI Nav but still the tags are not editable and then enabled all and still the same issue.

**Comment by zenweasel** [comment]
Could you provide me a screenshot of which permissions you have enabled exactly?

**Comment by vigyano** [comment]
Here is the screenshots of all permissions enabled for the account.

![image](https://user-images.githubusercontent.com/12378687/27123241-1ad27724-50a2-11e7-9359-a0cb239a23cd.png)

![image](https://user-images.githubusercontent.com/12378687/27123250-24c5aaee-50a2-11e7-80d5-37f493fb66f5.png)

![image](https://user-images.githubusercontent.com/12378687/27123259-2fea23fa-50a2-11e7-8c86-f3f75e43b10d.png)

**Comment by spencern** [comment]
@vigyano I'm currently looking into this as I've seen similar issues for admins from non-primary shops in our `marketplace` branch

**Comment by vigyano** [comment]
@spencern any updates on this issue?

**Comment by spencern** [comment]
@vigyano I'm looking at this from the marketplace perspective and we've recently fixed this issue for multi-shop marketplaces, though it will be a while until any of that is merged into development (2.0 or later). 

The issue in marketplace came down to a permissions mismatch and checking the wrong shopId. I have my doubts that it's the same issue you're experiencing.

**Comment by vigyano** [comment]
I see, if the fix is going to take a while to be released, can you point me to the code fix in marketplace branch and if possible to it's related master branch code?

**Comment by vigyano** [comment]
@spencern any updates on how to deal this issue intermediate.  Can you point me to the code fix in marketplace?

**Comment by spencern** [comment]
@vigyano Looking into this now.

**Comment by spencern** [comment]
@vigyano I don't think your issue and the marketplace issue were the same after looking into it a bit more. In the marketplace branch, the issue was that we were checking a static shopId (the first shop created) for permission checks even if the user had permissions for a second or third shop. When we added a way to select the "active" shop within marketplace, a lot of the permissions issues were cleared up.

I _do_ think this is still likely a bug, but don't have better news than that currently.

**Comment by vigyano** [comment]
@spencern thanks for the update. So, will leave this bug open.

**Comment by vigyano** [comment]
@zenweasel - is anyone working on this issue?

**Comment by spencern** [comment]
@vigyano to give you an update, I don't think that this will be fixed in the development branch, but it _should_ be fixed in the marketplace branch. Our timeline for merging that into master is probably 1-2 months and it will be Reaction 2.0.0

**Comment by aaronjudd** [comment]
This seems like a bug from `1.2` and not specifically a `marketplace` blocker, and is also marked as `needs to be reproduced`@spencern recommend removing label

**Comment by spencern** [comment]
I'm removing the `marketplace v1.5.0` tag on this issue as this was a bug reported for `1.2.0` and as far as I'm aware has not been reproduced on the current `marketplace` branch.

**Comment by aanchirinah** [comment]
This will be fixed with #3066

**Comment by spencern** [comment]
@aanchirinah does this mean you’ve been able to reproduce this on our `release-1.5.0` branch?

**Comment by aanchirinah** [comment]
@spencern , Yes I have been able to reproduce it on `release-1.5.0` branch

**Comment by zenweasel** [comment]
Closed via #3066
