### ISSUE TITLE
Visual glitching when you have unpublished product changes

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2432]
### Expected behavior
No change in margins when mousing over the "Publish" button

### Actual Behavior

![publish_button](https://user-images.githubusercontent.com/72819/27128272-6ea7db08-5130-11e7-90aa-e649c4eedd45.gif)

### Steps to Reproduce the Behavior
1. Login as admin using Chrome or FF
1. Edit product so there are unpublished changes
1. Mouse over "Publish" button
1. Observe glitching

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.9.3
Reaction: 1.2.0
Reaction branch: development
Docker: 17.03.1-ce
```

**Comment by zenweasel** [comment]
This bug does not happen in `master`

**Comment by spencern** [comment]
Confirmed that there's an issue on development. Not exhibiting this issue on current `marketplace` branch either which has not yet merged the navbar react conversion. Seems to point to that as the cuplrit

**Comment by zenweasel** [comment]
No one can reproduce and @spencern opened an issue for the scroll bar so
