### ISSUE TITLE
Can't run "reaction run", issue with fibers\future.js:280 > TypeError: Not a string or buffer

### ISSUE THREAD

**Issue by naveen1941** [reactioncommerce/reaction#2441]
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ C:\Users\akash\projects\chenethasantha ]]]]]

=> Started proxy.
=> Started MongoDB.
C:\Users\akash\projects\chenethasantha\node_modules\fibers\future.js:280
throw(ex);
^

TypeError: Not a string or buffer
at TypeError (native)
at Hash.update (crypto.js:70:16)
at C:\tools\fs\watch.js:263:30
at Array.forEach (native)
at C:\tools\fs\watch.js:263:10
at sha1 (C:\tools\fs\watch.js:261:10)
at Builder.write (C:\tools\isobuild\builder.js:268:22)
at C:\tools\isobuild\bundler.js:2461:13
at C:\tools\isobuild\bundler.js:2848:22
at C:\tools\utils\buildmessage.js:271:13
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:264:29
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:262:18
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:253:23
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.capture (C:\tools\utils\buildmessage.js:252:19)
at bundle (C:\tools\isobuild\bundler.js:2681:31)
at C:\tools\isobuild\bundler.js:2628:32
at Object.withCache (C:\tools\fs\files.js:1652:12)
at Object.exports.bundle (C:\tools\isobuild\bundler.js:2628:16)
at C:\tools\runners\run-app.js:588:36
at Function.run (C:\tools\tool-env\profile.js:490:12)
at bundleApp (C:\tools\runners\run-app.js:587:34)
at [object Object]..extend.runOnce (C:\tools\runners\run-app.js:631:35)
at [object Object]..extend.fiber (C:\tools\runners\run-app.js:890:28)
at C:\tools\runners\run-app.js:417:12

**Comment by hrath2015** [comment]
Can you provide output of `reaction -v` please. Please fill the complete details as per issue templates.

**Comment by naveen1941** [comment]
$ reaction -v

Node: 4.2.4
NPM: 5.0.3
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.9.3

**Comment by hrath2015** [comment]
Can u please do it from project directory. I am guessing u are on branch master and meteor version is  1.5.
 Please start fresh.
reaction init and 
reaction run
**`do not update the meteor at all.`**

**Comment by naveen1941** [comment]
From project directory-
$ reaction -v

Node: 4.2.4
NPM: 5.0.3
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.9.3
Reaction: 1.2.0
Reaction branch: master

**Comment by naveen1941** [comment]
Could you please tell me which branch of reaction and which version of meteor should I use to run my first app?

**Comment by naveen1941** [comment]
$ reaction -v

Node: 4.2.4
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.9.3
Reaction: 1.2.0
Reaction branch: Meteor-1.5



I am getting the following error:

$ reaction

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ C:\Users\akash\projects\chenethasantha ]]]]]

=> Started proxy.
=> Started MongoDB.
Warning: unable to resolve "es2015" in presets of /C/Users/akash/projects/chenethasantha/.babelrc
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):

   C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\bab                                                            el-core\lib\transformation\file\logger.js:41:11:
   [BABEL]
   imports/plugins/core/discounts/lib/collections/schemas/config.js:
   Unknown option: foreign.Children. Check out
   http://babeljs.io/docs/usage/options/ for more information about
   options.

   A common cause of this error is the presence of a configuration options
   object without the corresponding preset name. Example:

   Invalid:
   `{ presets: [{option: value}] }`
   Valid:
   `{ presets: [['presetName', {option: value}]] }`

   For more detailed information on preset configuration, please see
   http://babeljs.io/docs/plugins/#pluginpresets-options.
   at Logger.error
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\logger.js:41:11)
   at OptionManager.mergeOptions
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\options\option-manager.js:226:20)
   at
   C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\bab                                                            el-core\lib\transformation\file\options\option-manager.js:265:14
   at
   C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\bab                                                            el-core\lib\transformation\file\options\option-manager.js:323:22
   at Array.map (native)
   at OptionManager.resolvePresets
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\options\option-manager.js:275:20)
   at OptionManager.mergePresets
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\options\option-manager.js:264:10)
   at OptionManager.mergeOptions
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\options\option-manager.js:249:14)
   at OptionManager.init
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\options\option-manager.js:368:12)
   at File.initOptions
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\index.js:212:65)
   at new File
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\file\index.js:135:24)
   at Pipeline.transformFromAst
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\ba                                                            bel-core\lib\transformation\pipeline.js:69:16)
   at transform
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\me                                                            teor-babel\index.js:53:30)
   at compile
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\me                                                            teor-babel\index.js:77:14)
   at Cache.Cp.get
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\me                                                            teor-babel\cache.js:102:19)
   at Object.compile
   (C:\Users\akash\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\me                                                            teor-babel\index.js:28:23)
   at Object.Babel.compile (packages/babel-compiler.js:52:24)
   at packages/babel-compiler.js:178:22
   at Function.time (C:\tools\tool-env\profile.js:305:10)
   at profile (packages/babel-compiler.js:221:20)
   at BabelCompiler.BCp.processOneFileForTarget
   (packages/babel-compiler.js:177:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:109:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget
   (packages/babel-compiler.js:108:14)


   While processing files with ecmascript (for target os.windows.x86_32):

**Comment by jshimko** [comment]
@naveen1941 can you run `meteor npm i` without errors?

**Comment by jshimko** [comment]
Also, why are you on the `Meteor-1.5` branch?  That's a pull request branch that was merged last week.  It's not being used or updated anymore.  You should be on either master or development.

**Comment by zenweasel** [comment]
Closing. No reply to request for more info
