### ISSUE TITLE
Navbar profile no longer shows user's name

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2445]
Navbar Profile always says either "Admin" or "Guest", it no longer says my name / initials / display name.

I don't see this being an issue for "Admin" (although I liked seeing my initials insteadd), but I think it's kind of impersonal for registered non-admins to always say "Guest".

![reaction](https://user-images.githubusercontent.com/4482263/27192809-89c20cd4-51b1-11e7-9cd9-9d35875a41c0.png)
![reaction](https://user-images.githubusercontent.com/4482263/27192814-937fa768-51b1-11e7-81f5-2a2b8bcadb78.png)

**Comment by awadesmoline** [comment]
Hi @kieckhafer, I don't think this is an issue. 
A user doesn't register with a name, but with only email and password. And if you get invited (which means you are given a name), and you click the link in the email to update your password, you are automatically signed in, and your name actually shows on the navbar, instead of showing Guest or Admin.
So a user without a name will be Guest or Admin. If there is a name, it shows on the navbar. These are the steps I have taken to verify the bug.
Are there any other steps I could take to reproduce it?

**Comment by spencern** [comment]
Sorry to butt in here, I do agree that "Guest" is not an ideal label to give a user. At the least it shoudl be trivial for the user to change their name. We could also show their email there.

**Comment by kieckhafer** [comment]
@spencern i think that in the past it was the email address if there was no name associated with the account.

@awadesmoline

I do believe this is an issue. I set my name through our `settings.json` file, so it should be automatically populated (and it did used to be automatically populated) when I first sign in. It is not. Even after I add an address / name, my name still does not show as an admin or as a guest.

ADMIN
![account_profile](https://user-images.githubusercontent.com/4482263/27238872-7c77ef4e-5283-11e7-81df-cf1ce97a688d.png)

GUEST
![account_profile](https://user-images.githubusercontent.com/4482263/27238936-b26512c6-5283-11e7-8f86-7e1cd7ecb4db.png)

**Comment by jshimko** [comment]
The dropdown and the top of the profile both come from the user document `name` field `Meteor.user().name` (previously, it was `username` field).  And the only way that gets set is either when an admin manually invites someone or you set the `REACTION_USER_NAME` for your default admin.  After either of those scenarios, your full name _does_ show up in the dropdown and profile.

Also, the name in your address below is stored somewhere else entirely, so those 3 different pieces of UI won't ever match unless you change them to start pulling the name from the same place.

**Comment by awadesmoline** [comment]
You are right @kieckhafer, I just tested and confirmed it too.

Following what @jshimko wrote, I will see if I can change the name on the navbar to pull from the updated name in the user's address.

**Comment by jshimko** [comment]
Not sure if that's exactly what you want either though.  Then it'll say "Guest" until they've entered that address info.  You probably want to have it check the address entry for a name first, then the `user.name`, then the email.  That way the name is always populated in the UI by something other than "Guest".  The moment we have a name, email, or full name (from the address), they're technically not a guest anymore, so we can at least should show one of them.

**Comment by jshimko** [comment]
FYI, the dropdown name logic is here:

https://github.com/reactioncommerce/reaction/blob/development/client/modules/accounts/containers/dropdown/mainDropdownContainer.js#L106-L127

**Comment by awadesmoline** [comment]
Okay @jshimko. Thanks

**Comment by aaronjudd** [comment]
Keep an on this will all the social logins..  they do set user name, and should continue to show the user's real name.

**Comment by rnandhakumar1995** [comment]
Update the following files with corresponding data:

_**client/modules/accounts/templates/signUp/signUp.js**_
-->Add the line "const username = template.$(".login-input-username").val().trim();"
-->Replace "const newUserData" with  
**const newUserData = {
      // username: username,
      email: email,
      password: password,
      "profile.name":username,
      username:username
    };**
_**client/modules/accounts/templates/signUp/signUp.js**_
-->Add the following lines above the email input tag.
 **<div class="form-group form-group-username {{hasError messages.errors.username}}">
      <label for="username-{{uniqueId}}" class="control-label">Username</label>
      <input id="username-{{uniqueId}}" class="form-control login-input-username" type="text">
    </div>**

**Comment by vivekmore89** [comment]
![111](https://user-images.githubusercontent.com/6220344/27317412-cf5c1e4c-55a3-11e7-9454-a52abd2a39ea.png)

**Comment by awadesmoline** [comment]
Paused work on this complete Critical Issue.

**Comment by zenweasel** [comment]
Closed via #2455
