### ISSUE TITLE
Horizontal Scroll Bar on index page

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2446]
### Expected behavior
Should not be  seen. (I guess)
### Actual Behavior
![image](https://user-images.githubusercontent.com/14071646/27194898-09d3f8ea-5222-11e7-8ebc-0db3406ee474.png)

Deploy latest image and open in chrome browser.

**Comment by spencern** [comment]
I think this is probably connected to #2432 and likely an issue created during the navbar conversion to React.

**Comment by zenweasel** [comment]
Closed via #2458

**Comment by hrath2015** [comment]
👍 tested works.

**Comment by spencern** [comment]
While this does fix this issue, it might be worth trying to determine what was causing the overflow as well.
