### ISSUE TITLE
Node Module install not working on Dev branch  host key verification failed

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2447]
### Expected behavior
reaction init should   complete successfully.
### Actual Behavior
meteor npm install is failing on Development branch. windows 10
### Steps to Reproduce the Behavior
reaction init -b development
![image](https://user-images.githubusercontent.com/14071646/27201464-60aaee76-523b-11e7-8255-2e528e898831.png)

### Versions
(run `reaction -v` from your reaction directory)

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by hrath2015** [comment]
master branch is fine.

**Comment by hrath2015** [comment]
"braintree": "^2.0.2" is causing this. Not sure why.

**Comment by hrath2015** [comment]
It is similar to issue we had with **authorize-net@github:ongoworks/node-authorize-net** module. #1450

command `npm install braintree` works and `meteor npm install braintree` fails.  In recent version 2.1.1 , of braintree a change is made where 
`let wrapPrototype = require('wrap-promise').wrapPrototype;`
 is  changed to
`let wrapPrototype = require('**@braintree/wrap-promise**').wrapPrototype;`
when it connects to git as meteor npm results in error.

**Comment by awadesmoline** [comment]
I have tried reproducing this issue on mac, but I didn't get the error. Need a windows 10 OS to reproduce.

**Comment by hrath2015** [comment]
@awadesmoline    May be you can co ordinate  with Mike Murray,  he  knows how to reproduce windows issues  by launching  a windows VM.

**Comment by Tyler-Churchill** [comment]
I had this issue today

It happened when using the reaction-cli with "reaction init" 
I also had the same "Host key verification failed" messaged when I cloned directly with git
On windows 10 Home 1607 14393.1480 64 bit

I reinstalled meteor/git and the problem has disappeared.

**Comment by tdxiong** [comment]
![qq 20170814105404](https://user-images.githubusercontent.com/23134286/29256725-1dcec532-80df-11e7-97d7-82f3f7dfe8f1.jpg)
![qq 20170814105527](https://user-images.githubusercontent.com/23134286/29256726-1dff2d1c-80df-11e7-8273-5bc3d9b8e14a.jpg)

I am also having this kind of error on Win 10 64bit, by following the requirements and installation instructions on the Reaction doc page. Anyone has a solution?

**Comment by zenweasel** [comment]
Verified this is fixed in latest `master`
