### ISSUE TITLE
Icon tool bar UI Bug

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2452]
At smaller page heights the icon toolbar overlaps the second icon with the Reaction Dashboard icon.  

Steps to reproduce: 
Make, your page smaller or inspect and open your console. 

<img width="1361" alt="air_presto_and_reaction_ _node_ _node__usr_local_bin_rc_ _158x36_and_reactioncommerce_reaction" src="https://user-images.githubusercontent.com/20409254/27241913-969f19e0-528f-11e7-9407-6162f2f7398a.png">

**Comment by zenweasel** [comment]
Closed via #2460
