### ISSUE TITLE
Remove theme editor and dependencies.

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2468]
We should remove/ move postcss and other remnants of the theme editor into a stand alone package, with it's own dependencies. We're importing postcss and referencing it in the client, but I'm not sure we're actually using this anymore... (@mikemurray?)

**Comment by aldeed** [comment]
@aaronjudd @zenweasel @spencern @mikemurray 

I would like to do this ticket as well as creating a new component/style guide repo based on [React Storybook](https://github.com/storybooks/storybook) as part of performance epic. I know there are still many decisions to be made about UI and style guide, but I think agreeing on managing the component library in a separate project and creating that project is the first step. This will then give us a place to quickly iterate on new components for any that we identify as slow at runtime, or slow to develop with.

Any thoughts? Are there existing issues for separating the component library and standardizing components more, other than this one?

**Comment by zenweasel** [comment]
@aldeed My team has a project to create this new component library. We've been using Styleguidist but no real work on components have been done yet. https://github.com/reactioncommerce/reaction-component-library

**Comment by zenweasel** [comment]
Here is the other main ticket re: styleguide. I think we will probably be moving all issues over to this new repo: https://github.com/reactioncommerce/reaction/issues/2267

**Comment by aldeed** [comment]
I think can also remove `juliancwirko:postcss` as part of this

**Comment by aaronjudd** [comment]
@nnnnat @mikemurray wrote this originally, and would be good to connect with first.
