### ISSUE TITLE
I cant find out Buy Button, if there is no Buy button then how to add...pls help

### ISSUE THREAD

**Issue by vivekmore89** [reactioncommerce/reaction#2470]

**Comment by zenweasel** [comment]
@vivekmore89 Could you please fill out the issue template? We can't really help you unless you provide us with enough information.

**Comment by vivekmore89** [comment]
![sony222](https://user-images.githubusercontent.com/6220344/27317724-e29f9964-55a5-11e7-8833-d099f0974f84.png)
i want to add a button after Add to Cart.

**Comment by amrutraj** [comment]
@vivekmore89 You mean a "Buy Now" button like this. https://www.flipkart.com/samsung-galaxy-on5-gold-8-gb/p/itmedhx3uy3qsfks?pid=MOBECCA5FHQD43KA&srno=b_1_1&otracker=nmenu_sub_Electronics_0_Samsung&lid=LSTMOBECCA5FHQD43KAK2QMJD

This should take you directly to the payments page.

I dont think reactioncommerce has this built in. Its more like amazon.com 
https://www.amazon.com/CafePress-REARDEN-STEEL-Unique-Coffee/dp/B00QP8AMTK/ref=sr_1_2?s=kitchen&ie=UTF8&qid=1497941524&sr=1-2&keywords=atlas+shrugged

**Comment by zenweasel** [comment]
Incomplete information. Closing due to no response.
