### ISSUE TITLE
App do not render with Docker Image built with TOOL_NODE_FLAGS="--max-old-space-size=4096"

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#2475]
It is catch 22.  Without  `TOOL_NODE_FLAGS="--max-old-space-size=4096"` option **not able to build the image at all.**  I tried it on VPS(1 vCPU, 4.75 GB memory) and Linux multicore Laptop with 8GB RAM.  

When I used the suggested flag I am able to build the image but when deployed app do not render.  I tried following ways to build the image

1.  `docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=4096" -t reactioncommerce/reaction:latest .`  **on VPS**
2. `TOOL_NODE_FLAGS="--max-old-space-size=4096" reaction build reactioncommerce/reaction:latest` **on VPS**
3. `mup deploy`  passing TOOL_NODE_FLAGS as env variable with abernix/meteord:base  as image.
4. deploying `reactioncommerce/prequel:latest`  image as it is.

In all the above scenarios,  app do not render.  

Also please note when I use  `debug=true`  in 3rd method, it bypasses the minification and deploy with source code and render fine.  So mup deploy  works for reaction even with other meteor image. 

Screen shot for error when going through proxy:

![image](https://user-images.githubusercontent.com/14071646/27323485-5e14e28e-55bf-11e7-98eb-b03c626af955.png)

Screen shot when trying to access on local host.

![image](https://user-images.githubusercontent.com/14071646/27323551-8c73f520-55bf-11e7-9652-2ec212cd2038.png)

**Comment by jshimko** [comment]
This should be fixed by #2486

**Comment by hrath2015** [comment]
verified  scenario 3 and 4. working fine 👍
