### ISSUE TITLE
Alert component doesn't respect the autohide parameter

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2481]
### Expected behavior
<Alert> Component should respect the `autohide` parameter and fadeout after the specified time

### Actual Behavior
It doesn't fade out

### Steps to Reproduce the Behavior
Utilize the `<Alert>` component and pass in the `autohide` parameter

We came across this trying to fix a bug that required adding this Alert and could not get it to work nor able to fix the component, so we fell back to using the Blaze one. This is a placeholder ticket to fix the React component

**Comment by rhenshaw56** [comment]
@zenweasel So the `Alert` component works well on the Accounts Dashboard,  Here's it being used https://github.com/reactioncommerce/reaction/blob/marketplace/imports/plugins/core/accounts/client/components/adminInviteForm.js#L135

And here's how those prop options are being passed to it
https://github.com/reactioncommerce/reaction/blob/marketplace/imports/plugins/core/accounts/client/components/adminInviteForm.js#L54
