### ISSUE TITLE
clicking tag link on PDP causes hard refresh

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction#2482]
### Expected behavior

Clicking link should immediately render page.

### Actual Behavior

The browser does a hard refresh and downloads/re-renders the entire app (which takes several seconds instead of milliseconds).  This is most likely related to #2246 and probably caused by the recent Router updates.

### Steps to Reproduce the Behavior

Visit the product detail page, click a tag link under the product image.

### Versions

Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: Release-1.3.0
Docker: 17.03.1-ce

<img width="794" alt="basic_reaction_product" src="https://user-images.githubusercontent.com/3077956/27392104-bcfbb17e-5673-11e7-9f60-e778cc86bab9.png">

**Comment by spencern** [comment]
Was able to reproduce
