### ISSUE TITLE
Payment processor API key error shown to customers

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction#2483]
### Expected behavior

When the payment provider is misconfigured, give the customer a generic error that tells them to contact the site admin.

### Actual Behavior

When an API key doesn't work for a payment provider (Stripe, in my example) the customer gets an alert in the UI that says `Oops! Invalid API key provided:  ACTUAL_API_KEY_HERE`.  Not only is that something that makes no sense to a customer, an API key should never be revealed on the client side to non-admin user (and this was even a guest user in my case).

Ideally, this should never happen in a real production shop, but if an API key ever got revoked on the payment provider end, this could actually happen.

### Steps to Reproduce the Behavior

Add an invalid API key to the Stripe config, add a product to your cart, and checkout.  When you try to submit payment, you receive:

<img width="374" alt="cart_checkout" src="https://user-images.githubusercontent.com/3077956/27392039-87939c4a-5673-11e7-9f9e-759f39b9a325.png">

### Versions

Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: Release-1.3.0
Docker: 17.03.1-ce

**Comment by zenweasel** [comment]
Closed via #2499
