### ISSUE TITLE
SMS Notifications not sent.

### ISSUE THREAD

**Issue by michael-alade** [reactioncommerce/reaction#2485]
### Expected behavior
SMS should be sent after an order event is fired.

### Actual Behavior
Currently, Twilio has updated their library of which the API documentation is different from the previous one. This is now causing the SMS not be sent.

### Steps to Reproduce the Behavior
- Login as admin
- Go the SMS notification settings
- Choose an SMS Provider and account credentials
- Sign up as a new user and make an order
- After the order is completed, the SMS is not sent.

### Versions
```
Node: 6.10.0
NPM: 3.10.10
Reaction CLI: 0.8.0
Reaction: 1.3.0
Reaction Branch: updated-packages-1.3.1
```
**Approach for testing**
The `sms/send` meteor method should be tested to ensure that the SMS notifications are sent. The SMS library callback result should be returned.

**Comment by zenweasel** [comment]
Closed via #2508
