### ISSUE TITLE
Error when trying to Create Shop and confusing success message

### ISSUE THREAD

**Issue by abdulsemiu-atanda** [reactioncommerce/reaction#2495]
**Expected Behavior**
Create a new shop for user when `Become A Seller Button` is clicked

**Current Behavior**
Displays`Your Shop is ready` success message and throws the following error in terminal:

`ERROR Reaction: Failed to shop/createShop
  Error: Address book must be an array
      at getErrorObject (packages/aldeed_collection2-core.js:480:15)
      at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
      at [object Object].Mongo.Collection.(anonymous function) (packages/aldeed_collection2-core.js:214:25)
      at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/dispatch_run-as-user.js:325:19)
      at [object Object].shopCreateShop (server/methods/core/shop.js:86:28)
      at packages/check.js:129:16
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
      at packages/ddp-server/livedata_server.js:719:19
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at packages/ddp-server/livedata_server.js:717:40
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at packages/ddp-server/livedata_server.js:715:46
      at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
      at packages/ddp-server/livedata_server.js:559:43`

**Steps to Reproduce**
- Clone `marketplace` branch
- Run Reaction
- Register as a new user
- Go to your profile and update your address then click `Become A Seller` Button

**Comment by spencern** [comment]
@abdulsemiu-atanda This _should_ be fixed with the latest version of `marketplace`. Can you pull marketplace and try again?

**Comment by abdulsemiu-atanda** [comment]
@spencern I've updated my branch with the `marketplace` branch and in addition to the error above, I'm getting 
`Exception in delivering result of invoking 'shop/createShop': clickDataEventActionButtonClickBecomeSeller/<@http://localhost:3000/app/app.js?hash=f6128b19b3b9bf7de49208f82021709a778fa237:9615:9
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?hash=27829e936d09beae3149ecfbf3332c42ccb1596f:1105:17
_maybeInvokeCallback@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:3678:7
dataVisible@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:3708:5
_runAfterUpdateCallbacks/<@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:4559:7
_.forEach@http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149:7
_runAfterUpdateCallbacks@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:4558:5
_performWrites@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:4548:5
_flushBufferedWrites@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:4511:5
_livedata_data@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:4477:7
onMessage@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:3525:89
_launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:2908:9
_.forEach@http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149:7
_launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:2907:41
sockjs-0.3.4.js/SockJS</REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:142:13
sockjs-0.3.4.js/SockJS</SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:1309:9
sockjs-0.3.4.js/SockJS</SockJS.prototype._didMessage@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:1375:21
sockjs-0.3.4.js/SockJS</SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:1531:13`

**Comment by spencern** [comment]
I cannot reproduce this on a fresh install of `marketplace`

Have you reset your database and installed fresh?

http://g.recordit.co/92RbJ28XI1.gif

**Comment by abdulsemiu-atanda** [comment]
I'll do that. Thanks

**Comment by abdulsemiu-atanda** [comment]
@spencern I've reset the database and this issue no longer occurs when I did. I'll be closing this
