### ISSUE TITLE
Top Navbar Dropdowns Don't Close On Click

### ISSUE THREAD

**Issue by curranabell** [reactioncommerce/reaction#2496]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Expected behavior
Navbar dropdowns close on click of primary dropdown item
### Actual Behavior
Dropdown does not close 
### Steps to Reproduce the Behavior
Click Navbar Dropdown
### Versions
(run `reaction -v` from your reaction directory)
1.3
<img width="438" alt="screen shot 2017-06-23 at 8 56 06 am" src="https://user-images.githubusercontent.com/16485679/27496514-03181cfe-57f2-11e7-8405-4c29e9899962.png">

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by zenweasel** [comment]
I can't replicate this on `development`

![navbar](https://user-images.githubusercontent.com/72819/27525934-a4b19b56-5a74-11e7-97e2-12bc8cecc7c5.gif)

**Comment by curranabell** [comment]
I realized that the top level navbar items have never actually closed when you click them again. I was really just talking about having the navbar item close when you click the top level navbar item again but you can just click outside of the area.

**Comment by spencern** [comment]
@rymorgan This might be something you want to have input on, I can reproduce it, and I think I agree with @curranabell that it might be better if it toggled.

http://g.recordit.co/pj9ixT1X5k.gif

**Comment by rymorgan** [comment]
I agree with @zenweasel , it's a little weird but not a bug.
