### ISSUE TITLE
Docs: broken links 'Payments' page

### ISSUE THREAD

**Issue by louwers** [reactioncommerce/reaction#2498]
The links on [the 'Payments' page](https://github.com/reactioncommerce/reaction-docs/blob/master/developer/core/payments.md) are all broken.

**Comment by zenweasel** [comment]
Closing. Opened #207 on Docs repo

**Comment by louwers** [comment]
My bad and thank you.

Link: https://github.com/reactioncommerce/reaction-docs/issues/207
