### ISSUE TITLE
Clear cart shipping calculations if cart items / qty changes

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#250]
Clear cart shipping calculations and reset workflow on change of
- cart items
- cart quantity
- addressbook

This is to support fetching new rates (not just flat rates) from external services on address or cart item / qty change.

**Comment by zenweasel** [comment]
This issue is **not** fixed by https://github.com/reactioncommerce/reaction/pull/636

**Comment by aaronjudd** [comment]
also referenced in #669

**Comment by newsiberian** [comment]
@zenweasel, What part of this is not fixed for you?

**Comment by zenweasel** [comment]
If I clear cart of change quantities the shipping calculations are not reset. Is it working for you?

**Comment by zenweasel** [comment]
@aaronjudd I talked to @newsiberian about this and I think we saw this slightly differently. The way it currently works (with the latest changes) is that the shipping amounts would be recalculated when we have a shipping method that does recalculation. For some reason I was thinking that the shipping method would be unselected and you would need to reselect it (the reset workflow part). If recalcing is all we expected then we can go ahead and close this ticket.

**Comment by aaronjudd** [comment]
@zenweasel ok, I agree that this accomplishes the goal.  we'd have to be still running through that workflow if the address changes, but if we're ending up with the same selected shipping method as prior to any cart qty or address changes then that would make sense for the 80% of shops, and easily customized to clear the workflow (for example: where there may be a charge to fetch rates). I'd think some shipping packages will need want that option.
