### ISSUE TITLE
ACK Failure: Security header is not valid

### ISSUE THREAD

**Issue by vivekmore89** [reactioncommerce/reaction#2500]
![ack](https://user-images.githubusercontent.com/6220344/27535020-a290a03a-5a86-11e7-8d2d-24992c16802f.png)

**Comment by jshimko** [comment]
Please fill out ALL of the sections in the issue template that you deleted.  Failure to do so will result in the issue being closed with no further comment.  Help us help you.

**Comment by zenweasel** [comment]
No response to request for more info. Closing. Please reopen if you can give us more info. Thanks.
