### ISSUE TITLE
[Marketplace] Custom Permission Groups

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#2509]
If a user's permissions are customized by an admin, the user should be removed from any groups associated with a specific set of permissions and re-granted individual permissions that match the customized set of permissions they now have. The user should no longer be associated with a Permission Group in the Accounts dashboard but should instead be labeled as having a Custom Permissions set in the Accounts dashboard. Multiple users with Custom Permissions may be grouped together, but should not be assumed to have similar permission sets.

Related to: #2184 
Part of epic: Marketplace Permissions #2183

**Comment by spencern** [comment]
This is not what I meant by Custom Permission Groups. While this would be a nice-to-have feature, I don't think it's top priority right now. 

What we need in terms of custom permission groups is for any shop owner to be able to create a new `group` for that particular shop with a _custom_ set of permissions that defines that group. The shop owner could then add or assign users to this newly created "custom" group.

We don't need a way for users to have a custom, non-group, set of permissions right now.

Going to close this in favor of https://github.com/reactioncommerce/reaction/issues/2194 for now as I think that gets at the core of what is needed right now.
