### ISSUE TITLE
Need clarification for Chinese language translation

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#251]
Migrated from Google Group thread (https://groups.google.com/d/msg/reaction-talk/XPpzKCbbh9Y/0192QSZXPAsJ). 

From Rob L, regarding the json translation file: 

Almost done now, while I have some questions here, better to be solved before I commit:

1. Not sure what's variantList, not know the context and meaning of 'Create Variant'. Does it mean 'alternatives'?

2. cartDrawerItems.left, does it mean left for "left right", or 'remaining'?

3.  Not sure about the context of 'accountsUI.and', does it mean 'joining' or 'in addition'?

4. error.minChar, this message doesn't sound making sense to me, does it mean '7 is minimum length of a password', but the previous error saying 6 is minimum

5. error.oldPasswordFormat, I don't understand what's the idea of 'password format', and it seems having a time expiration? There are some similar error messages containing terminologies or short+obscure, which is not user-friendly, hoping they are for b/e debug purpose only, not to show to end-users. 

6. error."Password may not be empty", this one has spaces in the symbol, not consistent with others. I won't change the symbol, just mention the issue here.

**Comment by bstocks** [comment]
I can answer a few of these off the bat:

1. A "variant" is the term we are using to describe a specific version of a product, such as differing sizes or differing colors. For example, if you have a shirt that comes three different sizes, each size would be a "variant". Each variant can have it's own price, inventory, etc.
2. remaining
3. in addition

I'll have to get back about the others after digging into the code a bit and getting input from @aaronjudd

**Comment by aaronjudd** [comment]
4,5,6 probably need review, they came from the [account-y9n](https://github.com/softwarerero/meteor-accounts-t9n) translations, and I must not have caught them in my cleanup. I'll add another issue to review them
