### ISSUE TITLE
How to login in Frontend page in Reaction?

### ISSUE THREAD

**Issue by vanloc0301** [reactioncommerce/reaction#2510]
I install Reaction success.

But I can't find any method to run frontend pages like Magento or Prestashop.

I can't find the theme for Reaction.
Have any tutorial to create the theme on Reaction?

I see on artlimes.com have a custom view.
Can we make the custom theme for Reaction?

Thanks.

**Comment by kieckhafer** [comment]
Hi @vanloc0301 , here are some references for you, however I think this is better discussed in our Gitter channel as opposed to this issue: https://gitter.im/reactioncommerce/reaction

> Logging in

You should see your login information in your terminal when you first start reaction, use that info to long in as an admin.

> Customizing

The theme we use is located at `/imports/plugins/included/default-theme/`... Check out the docs for a customization guide: https://docs.reactioncommerce.com/reaction-docs/master/creating-a-theme

**Comment by vanloc0301** [comment]
Thanks @kieckhafer
