### ISSUE TITLE
How to add carousel on home screen like snapdeal?

### ISSUE THREAD

**Issue by vivekmore89** [reactioncommerce/reaction#2520]
![snapdeal](https://user-images.githubusercontent.com/6220344/27825027-ecdee3a4-60cb-11e7-9325-1e670d75c8b2.png)

**Comment by zenweasel** [comment]
Sorry, we need more information than this to be able to help you. This isn't a bug or enhancement request so I am closing it. You can reopen it if you can add more detail like exactly what you would like us to do.
