### ISSUE TITLE
Setting product visibility is not reflected in the Product Grid reactively

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2522]
### Expected behavior
Setting a product as "visible" or "invisible" should be reflected immediately in the product grid when published.

### Actual Behavior
Changes are only shown on reload

### Steps to Reproduce the Behavior
1. Create a product, set it to visible and publish
1. Observe it in the Product grid
1. Set it to "Private" and publish
1. Observe that the Product Grid does not change
1. Reload page and observe that the changes are visible

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: master
Docker: 17.06.0-ce
```

**Comment by awadesmoline** [comment]
Closed via #2561
