### ISSUE TITLE
Use Badge component on Product Grid

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2528]
We should transition our product grid / search grid to use our `Badge` component for the `Sold Out` and `Low Inventory` quantity badges

`imports/plugins/included/product-variant/components/gridItemNotice.js`

https://docs.reactioncommerce.com/reaction-docs/master/badge

**Comment by zenweasel** [comment]
@machikoyasuda Any status update on this?

**Comment by machikoyasuda** [comment]
Unassigning myself

**Comment by aldeed** [comment]
Assigned to @dancastellon since this will be done as part of his catalog grid PR

**Comment by kieckhafer** [comment]
Grid has been removed... RIP.
