### ISSUE TITLE
Relational DB Support

### ISSUE THREAD

**Issue by behrad** [reactioncommerce/reaction#253]
My customer has a force to use it's department Oracle as their ecommerce solution, I have read that there's no support for Relational DB Support in meteor, however would like to ask if there's a chance to replace/bind to Oracle in the reactioncommerce design/code?

**Comment by evliu** [comment]
jdbc is for java; future implementations of db connectors will depend on the main meteor project at github.com/meteor/meteor as this current project uses the built-in framework

**Comment by behrad** [comment]
my appologies @evliu I fixed the topic, I'm looking to switch mongo with Oracle, how much effort that needs?

**Comment by aaronjudd** [comment]
There is a mysql package in the works for Meteor, I don't think it's too far away that Meteor will be supporting other (relational) databases https://github.com/numtel/meteor-mysql - something that you could look at for inspiration at least. 

Another approach might be (to write) a package that mirrors the mongo data to a relational database. You could extend the collection object, and write something to convert / translate the nosql query to SQL, and store in a log that you could use.   

Just some ideas...

We have no plans to support anything that isn't well supported by Meteor just yet, but I do know other databases are coming to Meteor, and once they are stable and semi-official we'll certainly try to support them.

**Comment by evliu** [comment]
At this point, you would need to roll out your own adapter and utility to connect to something like Oracle13, but the meteor-mysql is a good place to start. I'd also say you should look at any Oracle node.js packages for more hints.

**Comment by aaronjudd** [comment]
We do define schemas as well, so that should help -> it's not like it's just freeform nosql.
