### ISSUE TITLE
TaxCloud: Tax codes dropdown is empty after api configuration.

### ISSUE THREAD

**Issue by rnandhakumar1995** [reactioncommerce/reaction#2533]
### Expected behavior
Tax codes from tax cloud should load into the `tax code` dropdown in the product detail page after the tax cloud API has been configured.

### Actual Behavior
This does not happen.

### Steps to Reproduce the Behavior
1. Start reaction
2. Configure taxcloud API
3. Access tax codes dropdown in product detail page

### Versions
(run `reaction -v` from your reaction directory)
???

[Updated 7/10/2017 by @spencern]

**Comment by spencern** [comment]
Hi @rnandhakumar1995 
Please fill out all of the fields in this bug report. (`Expected behavior`, `Actual behavior` and detailed `Steps to Reproduce the Behavior`) and then copy the output from running `reaction -v` into this bug.

We cannot track down causes for bugs without this information.

**Comment by rnandhakumar1995** [comment]
When we configure the **taxcloud api**, the **taxcodes** from **tax cloud** does not load into the **taxcode** dropdown, under **taxable** option in **product detail** page.

**Comment by zenweasel** [comment]
@rnandhakumar1995 that description does not seem to match the description in the title.

**Comment by spencern** [comment]
@rnandhakumar1995 I've updated your original report to reflect the information you've given us in this comment. Can you run `reaction -v` for us and provide the output?

**Comment by rnandhakumar1995** [comment]
**reaction -v**
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.9.2
Reaction: 1.2.0
Reaction branch: master

**Comment by jm-wanja** [comment]
Working on this issue I have been able to populate the TaxCode collection with the tax-codes from TaxCloud, and they are viewable on the dropdown. I have however encountered an error on the browser console due to duplicate keys, also the tax description is not showing. @zenweasel

**Comment by spencern** [comment]
@jm-wanja how is this issue coming along?

**Comment by jm-wanja** [comment]
@spencern I was able to display the taxcodes on the dropdown but I am yet to display the tax descriptions

**Comment by aanchirinah** [comment]
Will sync with @kieha to fix this issue

**Comment by spencern** [comment]
Ok, thanks @aanchirinah. I'd like to see a status update as often as possible on this issue as it's currently a blocker for our `1.5.0` release

**Comment by spencern** [comment]
Resolved by #2973
