### ISSUE TITLE
Order workflow reverts to processing

### ISSUE THREAD

**Issue by nbaldwin** [reactioncommerce/reaction#2539]
### Expected behavior
When clicking the order action button, the order workflow should not change to "processing" for completed or cancelled orders.

![Clicking order action on completed order](https://user-images.githubusercontent.com/373151/27989805-4a17a34c-6407-11e7-8785-7750bb2a81dc.png)

### Actual Behavior

When clicking the order action button, the order workflow **always** changes to "processing", even if the order is completed or cancelled. There is no way to bring the order back to completed once this happens.

![Clicking order action on completed order](https://user-images.githubusercontent.com/373151/27989804-3669a19c-6407-11e7-9d6b-07e8081bec4b.png)

### Steps to Reproduce the Behavior
Complete or cancel an order, then click the action button for that order in the order list.

### Versions
Node: 8.0.0
NPM: 5.0.1
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.8.2
Reaction: 1.3.0
Reaction branch: development
Docker: 17.06.0-ce

**Comment by zenweasel** [comment]
Closed via #2541
