### ISSUE TITLE
Safari shows blank page when running with reactioncommerce/reaction:latest docker image

### ISSUE THREAD

**Issue by jaden-chen** [reactioncommerce/reaction#2546]
### Expected behavior
We should see reaction commerce site on Safari (both iOS and Mac)

### Actual Behavior
Safari shows blank page. Looking at the console, the error is:
`SyntaxError: Cannot declare a const variable twice: 'e'.`

Digging in the bundled js file, the exception happened in this function
`
!function() {
    var e = Package.meteor.Meteor,
        n = Package.meteor.global,
        t = Package.meteor.meteorEnv,
        i = Package["modules-runtime"].meteorInstall,
`

### Steps to Reproduce the Behavior
- Run the docker image  (I use docker-compose to link to a `mongodb` container
- Load the webpage in Safari

### Versions
(run `reaction -v` from your reaction directory)
v1.3.0

OS Info:
macOS Sierra
Version 10.12.3
Safari (Version 10.0.3)

**Comment by spencern** [comment]
@jaden-chen thanks for the report.

I'm thinking this might be related to #2535 which is being fixed in #2545

**Comment by jaden-chen** [comment]
@spencern 
good to know. I just tried it on IE11 and yes, the console error is the same.

Since this is affecting the current stable version `v1.3.0`, and it's causing major service outage, , should this fix be patched instead of waiting for the next release?

**Comment by spencern** [comment]
@jaden-chen yes, I've added the `critical impact` label to this bug as it's affecting users of both IE11 and Safari. We've got @rhenshaw56 working on it already (as it's the same as #2535)

**Comment by jaden-chen** [comment]
Thanks so much! Looking forward to seeing this resolved.

**Comment by zenweasel** [comment]
Hey @jaden-chen Could you try changing your entry for transliteration in your `package.json` to be `    "transliteration": "github:zenweasel/transliteration",` and see if that fixes the problem. That's a fork of the transliteration package that includes some fixes for minification problems.

We will either see if we can get the changes merged in or we will create an "official" fork if that turns out to be the solution.

**Comment by spencern** [comment]
Should be fixed by #2553.
We will have to release a patch version and update our latest docker image before this will be live on `reactioncommerce/reaction:latest`, but you should be able to load our development branch on both IE11 and Safari now.

**Comment by zenweasel** [comment]
@jaden-chen You should be able to just test with the current `development` branch now. If that works for you we will try to get a release out shortly.

**Comment by jaden-chen** [comment]
@zenweasel @spencern I just verified that it's now working correctly on Safari and IE11 with the changes in `development` branch. Thanks all for the promptly resolution.

FYI (Different issue): It seems like websocket connection fails to establish On Safari
`[Error] Refused to connect to ws://localhost:3000/sockjs/418/kkt124_m/websocket because it does not appear in the connect-src directive of the Content Security Policy.`

**Comment by zenweasel** [comment]
@jaden-chen Thanks for the update.

**Comment by spencern** [comment]
This should be fixed on our docker build with the release of 1.4 https://github.com/reactioncommerce/reaction/releases/tag/v1.4.0
