### ISSUE TITLE
UI bug on Safari: navbar links not vertically centered

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#2547]
### Expected behavior

The Shop `tag link` text should be vertically centered relative to the navigation bar.

### Actual Behavior

In Safari, the link is not vertically centered. The issue stems from the parent `div`'s height: the `navbar-item` height should be 100% of the navbar, but that attribute is not being rendered by Safari.

### Steps to Reproduce the Behavior

1. open http://localhost:3000 in Safari and Chrome on desktop
2. compare the navbar on both browsers:

![screen shot 2017-07-11 at 1 55 16 pm](https://user-images.githubusercontent.com/3673236/28090454-2c68ee3c-6641-11e7-92ed-ae4c6c2d0016.png)

### Versions

```
Node: 7.0.0
NPM: 3.10.8
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.2
Reaction: 1.3.0
Reaction branch: master
```

Browser versions:
Chrome 59 on OS X 10 http://whatsmybrowser.org/b/OKAUJ6M
Safari 10 on OS X 10 http://whatsmybrowser.org/b/KFCF49L

**Comment by zenweasel** [comment]
Closed via #2551
