### ISSUE TITLE
Add Instagram Login / registration as an option

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2559]
We'd like to add the option to login / register for Reaction with Instagram. There are existing packages that should be looked into:

https://atmospherejs.com/packages/instagram

We'll also need to add a field into the admin which allows the shop owner / admin to add their Instagram developer api key / access token, similar to what we have for Facebook, Twitter, etc.

<img width="487" alt="reaction" src="https://user-images.githubusercontent.com/4482263/28234065-9230e3ca-68b0-11e7-947f-9086f5b197d8.png">

When choosing permissions, we'd like to be able to access as much Instagram information as possible, but most importantly the users Profile Photo (https://www.instagram.com/developer/endpoints/users/) and Photo Feed (https://www.instagram.com/developer/endpoints/media/).

**Comment by zenweasel** [comment]
Closed via #2562
