### ISSUE TITLE
Products created with the same name will have the same url

### ISSUE THREAD

**Issue by ottomMT** [reactioncommerce/reaction#2560]
Sometime,we will have the same general name with the product,so they got the same url, then ,we will just reach the one of them.

So can we add a number or other label to differ their url?

**Comment by zenweasel** [comment]
We have talked about doing this automatically, but currently you can change the URL for a product here:

![dc_men_s_pure_se_skate_shoe](https://user-images.githubusercontent.com/72819/28252351-ef101b50-6ac3-11e7-9224-c90584547bb7.png)

**Comment by ottomMT** [comment]
Got it,thanks!

**Comment by aaronjudd** [comment]
I think this is a valid issue..  more of an enhancement than a bug, but this should get tasked.. it'd obviously similar to the copy functionality when cloning products.

**Comment by Akarshit** [comment]
Hey guys, I am working on this issue. I dave a working version ready, just polishing it.

**Comment by spencern** [comment]
@Akarshit did #2846 resolve this issue?

**Comment by Akarshit** [comment]
@spencern There is still a case that has not been fixed, which is tracked in #3007

**Comment by Akarshit** [comment]
Fixed in #2846 

A test case still leads to duplication of `handle` and is tracked separately in #3007
