### ISSUE TITLE
Warning/Errors in Safari in private browsing mode

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2568]
If you visit Reaction in Safari in private mode you see the following error messages in the console. Not sure what functionality issues this causes if any but we probably want to track them down a silence the warnings if they aren't pertinent.

![reaction_swag_shop_and_reaction_swag_shop](https://user-images.githubusercontent.com/72819/28297050-60290c4a-6b9e-11e7-8d99-cbb0ea92ee05.png)

**Comment by aaronjudd** [comment]
Tested with Reaction 1.7.0 and Safari Version 11.0.3 (13604.5.6). Unable to replicate.

**Comment by prinzdezibel** [comment]
@aaronjudd Obviously they changed the local storage behavior in Safari. In former versions it would not have been possible to do this in a private browser console without an error being throwed:
```
localStorage.testKey = "testValue"
```

This does work now. This does probably render this old PR as meaningless:
https://github.com/reactioncommerce/reaction/pull/2518

Could probably be removed..
