### ISSUE TITLE
Issue with reactivity on badges on Orders Detail View

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#2579]
### Expected behavior
- When the workflow status of an order changes the badge on the orders detail view should change accordingly.

### Actual Behavior
 - Badges on orders detail view remain unchanged after workflow status is changed.

Example: 
 - Workflow status is shipped `completed` but badge on the detail view is still `new`

![cart_completed](https://user-images.githubusercontent.com/72819/28399585-9a5c35e2-6d40-11e7-813a-e26929da97ad.png)

### Steps to Reproduce the Behavior
- Make an order
- Navigate to detail view on orders 
- Open order sideview 
- Approve and capture payment
- Under "shipping" Add tracking number then click on "Pack all items"
- Notice that on the "order summary" badge is "Completed" but badge on the order detail view remains as "New"

**Comment by zenweasel** [comment]
Looks like this only happens on the "expanded detail view". The "summary" view works fine.

**Comment by joykare** [comment]
Fixed it PR #2519
