### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by lil5** [reactioncommerce/reaction#2586]
If you are using es6 and react js

Aren't these helpful enough to remove jquery?

_Sent from my Wileyfox Swift using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by aaronjudd** [comment]
Reaction does not have a direct jquery dependency, but Meteor Blaze does. We'd love to see it gone, but it's a dependency of Blaze templates. Once we've converted the entire UI to React (almost there) there won't be any need for it, but I'm betting we have some Meteor dependencies that will still be including jquery - and we'll work through updating/removing as we identify those dependencies.
