### ISSUE TITLE
iDeal payment option (incl. Bitcoin)

### ISSUE THREAD

**Issue by lil5** [reactioncommerce/reaction#2587]
Mollie is the only one I know that has an api for nodejs

Mollie website:
<https://www.mollie.com/nl/>

Nodejs Mollie api:
<https://github.com/mollie/mollie-api-node> 

See here all the [Pricing and payment options](https://www.mollie.com/nl/pricing/)

**Comment by aaronjudd** [comment]
We don't have any plans to add additional payment methods to the core, but would be happy to re-open with a PR.
