### ISSUE TITLE
i18n and currency elements not all updating on change

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2593]
Change currency or i18n in a page where there are multiple localized elements, and you will see many of the components are not update on language / currency changes.  
Behavior was introduced in #2536.

<img width="1193" alt="reaction" src="https://user-images.githubusercontent.com/439959/28579879-c2fc3364-7112-11e7-9251-e267477da1ed.png">
<img width="920" alt="basic_reaction_product" src="https://user-images.githubusercontent.com/439959/28579966-f789ecc0-7112-11e7-982c-62f195bc5708.png">

**Comment by aaronjudd** [comment]
Verified not in `master` -> discussed with @mikemurray @kieckhafer as well in components meeting.

**Comment by aaronjudd** [comment]
@mikemurray @jshimko assigning this to you guys, whomever gets there first.

**Comment by zenweasel** [comment]
Closed via #2742
