### ISSUE TITLE
Can you add Indian payment gateways like paytm etc. and also provide indian currency.

### ISSUE THREAD

**Issue by Makinsane** [reactioncommerce/reaction#2594]
Can you add an extension for indian currency too. 
I would also like if the templating engine docs are a simpler

**Comment by kieckhafer** [comment]
Hi @Makinsane,

Check out this recent PR for an example of how to add a currency: https://github.com/reactioncommerce/reaction/pull/2517

If you'd like to do that and create a PR into our repo, we'd be happy to review it and pull it in.

We also have a tutorial in our docs specifically geared towards adding a payment provider: https://docs.reactioncommerce.com/reaction-docs/master/creating-a-payment-provider

If you have questions on how to develop either of those, please check out our Gitter Channel: https://gitter.im/reactioncommerce
