### ISSUE TITLE
Possible Open Source Drag n Drop Javascript Page Builder 

### ISSUE THREAD

**Issue by curranabell** [reactioncommerce/reaction#2600]
It would be great if there was a drag and drop page builder for users who don't want to learn how to build custom pages and especially clients. Here's an open source npm package that is pretty cool. A little complicated though.

https://github.com/artf/grapesjs

**Comment by curranabell** [comment]
Meant to put this in the content creation milestone.

**Comment by spencern** [comment]
This could be a good community sponsored plugin if there is interest in this.

For the core product, we're moving towards a component based content management. Currently we don't have an open issue for this, but would welcome ideas for third-party components that might help us achieve this goal.

For now I'm going to close this issue for now, but feel free to keep adding more details to this issue if you want to flesh out this idea more.
