### ISSUE TITLE
Previous / Next buttons not working in sortableTable

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2603]
![somedays_velvet_bomber_jacket](https://user-images.githubusercontent.com/4482263/28684326-d3b70f9c-72b8-11e7-90f0-bf583013b665.png)

The onClick functionality of sortableTables Previous and Next buttons seems to be broken. 

I've been chatting in React Table's Gitter room trying to figure out the issue. It looks like even the built in Prev / Next buttons aren't working, so I think the issue is bigger than just our custom pagination.

**Comment by aaronjudd** [comment]
Which version? Marketplace? 1.5.0? master?

**Comment by kieckhafer** [comment]
This is working again, seems to be that it was an issue with ReactTable iteself, not on our end, and when their latest release fixed it.

Closing.
