### ISSUE TITLE
Add new migration for splitting order payments and shipments

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2604]
Once we've got the schema and data model ironed out for split orders, split payment, & split shipments, we need a migration to upgrade old orders to use the new model.

Initial PR for this is #2524

**Comment by impactmass** [comment]
This was created [mostly] to serve as reminder to setup migration. I'll create a new issue detailing the things I've found that need to be migrated.

**Comment by impactmass** [comment]
closing in favor of #2938
