### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by augmen** [reactioncommerce/reaction#2607]
i run the command 
'reaction run'

`You are attempting to run Meteor as the 'root' superuser. If you are
developing, this is almost certainly *not* what you want to do and will likely
result in incorrect file permissions. However, if you are running this command
in a build process (CI, etc.), or you are absolutely sure you know what you are
doing, set the METEOR_ALLOW_SUPERUSER environment variable or pass
--allow-superuser to proceed.

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local`

**Comment by jshimko** [comment]
This isn't an error.  It's just a warning.  And I'm not sure I can say much about it that isn't already in the warning itself.

In general, you shouldn't be developing as a root user on your development machine, but if you want to, all of the contents of that warning apply.  It mostly just means that if you start working as root, you'll have to either _always_ run as root or you'll have to fix file permissions later to run as a non-root user.   

If you're new to managing Linux permissions...
https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-permissions

To ignore the warning and continue building/starting the app as root...

```sh
export METEOR_ALLOW_SUPERUSER=true

reaction
```

**Comment by augmen** [comment]
what is the standard practice . to use as root user or non root user. also guide us on the codes for standard practice. Thanks

**Comment by zenweasel** [comment]
@augmen Standard practice is to not run as superuser in development. The instructions don't state to run as `root` so I think you can take that as implicit guidance to run as a normal user.

**Comment by augmen** [comment]
so whats the exact code to run as normal user ?

**Comment by zenweasel** [comment]
You would need to be logged in as a normal user in whichever operating system you are using. It has nothing to do with the command per se, but who your current user is.

**Comment by augmen** [comment]
logged in to VPS as root user . `ssh -t roo@ipaddress`.

**Comment by zenweasel** [comment]
It's beyond the scope of what we do here to explain how to use your operating system, but you would need to go through whatever process is required to create a "normal" user and then login using that user. The documentation for your operating system is the best source for that information.

**Comment by augmen** [comment]
thanks appreciated
