### ISSUE TITLE
[Marketplace] Notification page not found

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#2614]
### Expected behavior

When I click on the notifications icon on the navbar, Clicking on `View All` should take me to the notifications page.

### Actual Behavior

Clicking on `View All` takes me to the `Not found` page.

### Steps to Reproduce the Behavior

1. Make an order (as admin or non-admin)
2. Click on the notifications icon on the navbar
3. Click on the `View All` link
4. Observe that you're re-directed to the `Not Found` page

### Versions

Node: 6.2.2
NPM: 3.10.9
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 1.13.0

**Comment by zenweasel** [comment]
Closed via #2673
