### ISSUE TITLE
[Marketplace] Payment gets stuck on "Order Processing" spinner when checking out with Authorize

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2616]
### Expected behavior
1. "Order Completed" page should load after order is complete

### Actual Behavior
Endless spinner(s). Order **does** complete however, and a refresh loads the correct page.
![cart_completed](https://user-images.githubusercontent.com/72819/28849207-9f1ae418-7748-11e7-9138-f90578cbe07e.png)

### Steps to Reproduce the Behavior
1. Login as admin and set payment method to Authorize
1. Attempt to checkout
1. Observe that "Completed Order" page is never served.

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
```

**Comment by zenweasel** [comment]
Verified that orders go through fine when using Braintree.

**Comment by foladipo** [comment]
This was a confirmed bug that was reported by a couple of people. But it suddenly stopped occuring  after some updates to the `marketplace` branch, and that has been confirmed by several people too. So, I will be closing it.
