### ISSUE TITLE
[Marketplace] When using "collapsed" order view, order detail is not always visible.

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2617]
### Expected behavior
Order detail panel should always be visible

### Actual Behavior
Order detail panel appears not to open because it is hidden. The main list view area should shrink to accomodate the expanded panel. Moving to "expanded" view shows the panel however.
![order-detail-panel](https://user-images.githubusercontent.com/72819/28849572-2b96f6ce-774a-11e7-8f98-852b7cee6fca.gif)

### Steps to Reproduce the Behavior
1. Place an order
1. Make browser width around 1133px.
1. Go to order view
1. Click on an order
1. Observe that panel appears now to open

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
```

**Comment by mikemurray** [comment]
This is fixed.
