### ISSUE TITLE
[Marketplace] Cannot issue refunds

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2618]
### Expected behavior
You should be able to issue refunds

### Actual Behavior
Just receive an endless spinner

### Steps to Reproduce the Behavior
1. Place an order
1. Approve and Capture the order
1. Attempt to create a refund
1. Observe that it never completes

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: ek-dataDataData
Docker: 17.06.0-ce
```

**Comment by foladipo** [comment]
## Note
Due to ongoing work on #2590, fixing this bug has been put on the backburner for now. When the work on that PR is completed, this issue will be revisited.

**Comment by kieha** [comment]
@zenweasel I have tried reproducing this issue with all available payment providers, and I have been able to successfully issue refunds with Stripe and PayPal Express.

<img width="397" alt="screen shot 2017-09-14 at 3 15 44 am" src="https://user-images.githubusercontent.com/19430095/30406602-8ae24926-98fb-11e7-9c4e-e69f9d89ac26.png">

<img width="394" alt="screen shot 2017-09-14 at 3 16 02 am" src="https://user-images.githubusercontent.com/19430095/30406610-96c02646-98fb-11e7-802e-76e4a4554ea8.png">

Braintree has this message

`Braintree does not allow refunds until transactions are settled. This can take up to 24 hours. Please try again later.`

Authorize.net has this

`Reaction does not yet support direct refund processing from Authorize.net. Please visit their web portal to perform this action`

Example Provider cannot issue refunds, and there's an issue with capturing payments using PayPal Payflow, so I'm not able to reach the refund step.

<img width="1426" alt="screen shot 2017-09-14 at 3 05 43 am" src="https://user-images.githubusercontent.com/19430095/30406428-5c6d321e-98fa-11e7-8e2b-4e08fb99f50b.png">

Could you confirm if this is still happening?

**Comment by zenweasel** [comment]
What happened with that screenshot of the error? Did you take a picture of your screen?

**Comment by kieha** [comment]
@zenweasel I don't quite follow. What do you mean?

**Comment by zenweasel** [comment]
I can't read that screenshot.

**Comment by kieha** [comment]
It's basically just throwing an error when I tried capturing the payment with Payflow.

**Comment by zenweasel** [comment]
You're testing on `marketplace`?

**Comment by kieha** [comment]
Yes.

**Comment by zenweasel** [comment]
In order to test Payflow Pro you need to use the "magic" credit card that's in the wiki.

![cart_completed](https://user-images.githubusercontent.com/72819/30412025-60727868-9947-11e7-8117-d8fbb5d45190.png)

**Comment by zenweasel** [comment]
If you are asking me if it's okay to close this issue: If you have tested this with the latest marketplace and they all work it's good with me.

**Comment by kieha** [comment]
Somewhere along the way, this must have gotten fixed. Refunds work on the current `marketplace` branch. 
Feel free to reopen it if the issue happens again.
