### ISSUE TITLE
Tax rates by country/region

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#263]
Admins can create Tax Rates by Country/Region and have taxes automatically calculated by Reaction platform for shoppers

Edit/override by County/Municipal/State/Sub-region with inheritance from parent if no specific rate defined for sub-region

**Comment by bstocks** [comment]
Also the ability to create a tax rate by tag that then applies to a specific region/sub-region. For example, "food" my be taxed differently than "apparel" for a given region.

**Comment by bstocks** [comment]
* [ ] write tests

**Comment by aaronjudd** [comment]
Close in favor of #972
