### ISSUE TITLE
[Marketplace] Unable to change Email Settings

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2630]
### Expected behavior

No Errors, Editable email settings

### Actual Behavior

There appears to be no errors in marketplace and you are unable to edit the email settings.

[marketplace]
![reaction](https://user-images.githubusercontent.com/439959/28933826-744285e8-7833-11e7-8884-d27378b789cd.png)
[seun-change-owner-2188]
![reaction](https://user-images.githubusercontent.com/439959/28933508-21c41512-7832-11e7-92a7-a9624f08b8cf.png)

### Steps to Reproduce the Behavior
Default install, with or without `reaction.json` settings, attempt to edit email settings.
### Versions
Node: 6.11.1
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: seun-change-owner-2188 (and markeplace)
Docker: 17.06.0-ce

**Comment by spencern** [comment]
@kieckhafer @impactmass this looks like the same type of issue that you guys solved for the other files that hadn't migrated to the new `Components.component` style

**Comment by kieckhafer** [comment]
Closing via the PR's above

**Comment by zenweasel** [comment]
Im retesting this now and can reconfigure mail w/o issue
