### ISSUE TITLE
Dynamically load transliteration module

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2634]
Reduce application load time by implementing dynamic loading of the `slugify` and `transliteration` modules in the `getSlug()` methods.

### Expected behavior

Use [slugify package](https://www.npmjs.com/package/slugify) by default for western languages, and only load [transliteration](https://www.npmjs.com/package/transliteration) modules when it is needed for languages that require the full transliteration data. This would result in a ~250k reduction.  This can be determined by the shop's settings default language.

**Comment by spencern** [comment]
This should be based on the base language of the primary shop. It only affects the slugs and does not impact the i18n labels that are generated.

**Comment by nnnnat** [comment]
@aaronjudd @spencern  I think I follow what needs to be done here, I want to make sure I'm heading in the right direction. Is the idea to check against the primary shop's base lang then set the `slugify` method to the correct package? 

Something kinda like this
```javascript
let slugify;
async function lazyLoadSlugify() {
  if (slugify) return;
  const mod = (shopLang === "en") ? await import("slugify") : await import("transliteration");
  slugify = mod.default; // not sure this will work yet cause transliteration is using exports.slugify and not exports.default for it's modules
}

function getSlug(slugstring) {
  Promise.await(lazyLoadSlugify());
  return slugstring ? slugify(slugstring) :  "";
}
```
