### ISSUE TITLE
PDP / Dashboard components i18n

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2641]
As reported in #2623

Take a look at "Available Options" on the PDP -> you'll see the field only translates on refresh after i18n update.

![basic_reaction_product_and_2__reaction_reset_-y____reaction__node_](https://user-images.githubusercontent.com/439959/28950909-62f31e58-787c-11e7-99d7-234963a8078f.png)
![basic_reaction_product_and_2__reaction_reset_-y____reaction__node_](https://user-images.githubusercontent.com/439959/28950916-6ad7dc62-787c-11e7-928b-9a7c0cb5f59f.png)

**Comment by mikemurray** [comment]
Some things seem fixed, some things do not.

Working
- Tooltips seem to work RTL / LTR
- Available options seem to be translated
- "Dashboard" translation works

Not Working?
- "Product Revisions" still not translated.

New Issues discovered
- Enter / Leave animation is incorrect for the action view LTR. Needs to be reversed

**Comment by spencern** [comment]
Is this issue being worked on or should it be worked on as part of #3009? 

@kieckhafer do you think the translation issues for Product Revisions is due to the same issue you discovered in #2983 ?

**Comment by kieckhafer** [comment]
No, I think #2983 will only fix SimpleSchema generated form labels translations.

**Comment by kieckhafer** [comment]
I think this is all working. As @mikemurray mentioned, Tooltips are RTL and LTR, Dashboard is translated, available options is translated, and I'm also seeing "product revisions" as translated, which was his only "not working" note.

**Comment by kieckhafer** [comment]
@spencern I think this is all working. As @mikemurray mentioned, Tooltips are RTL and LTR, Dashboard is translated, available options is translated, and I'm also seeing "product revisions" as translated, which was his only "not working" note.

**Comment by spencern** [comment]
@kieckhafer thanks closing this issue.
