### ISSUE TITLE
Manage tax settings by region/sub-region

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#265]
Tax settings can be set globally or overridden by "rules" for a given region/sub-region:

* [ ] Apply tax to all prices
* [ ] Apply tax to shipping
* [ ] Ability to toggle to show rate in label by rule

There will also need to be tests written (depends on #241)

**Comment by bstocks** [comment]
* [ ] write tests

**Comment by aaronjudd** [comment]
Closed in favor of #972
