### ISSUE TITLE
The arguments passed to userIsInRole() seems in the wrong order.

### ISSUE THREAD

**Issue by tespher** [reactioncommerce/reaction#2657]
In master branch, release 1.4.0.
reaction/imports/plugins/core/checkout/client/templates/checkout/login/login.js
line 21:
const anonUser = Roles.userIsInRole(**"anonymous", Meteor.user()**, Reaction.getShopId());

According to the Role API document :
http://alanning.github.io/meteor-roles/classes/Roles.html#method_userIsInRole
_userIsInRole ( user  roles  [group] ) Boolean
Defined in roles/roles_common.js:254_

The order of 1st and 2nd argument should be reversed:
const anonUser = Roles.userIsInRole(**Meteor.user(), "anonymous"**, Reaction.getShopId());

The consequence of this issue is:  
   When I checkout without logged in and click "Continue as Guest" in first step, the  "Welcome, it's so good to see you." message will be displayed and go to 2nd step.(checkoutLoginCompleted returned true)

   If userIsInRole is invoked with correct argument order, the 1st step will keep its display and just go to 2nd step.(checkoutLoginCompleted returned false)

I am not sure which one is the expected behavior.

**Comment by aaronjudd** [comment]
We should also be replacing `Roles.userIsInRole` with `Reaction.getPermission()` in all cases now that Meteor 1.5.1 supports use of `Meteor.getUserId()` within publications.

**Comment by spencern** [comment]
Resolved by #2752
