### ISSUE TITLE
Double Scrollbars in Admin Dashboard

### ISSUE THREAD

**Issue by curranabell** [reactioncommerce/reaction#2658]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Expected behavior
1 Scrollbar
### Actual Behavior
2 scrollbars in Admin Dashboard
### Steps to Reproduce the Behavior
Fresh install of Reaction Commerce than navigate to admin dashboard. There are two scrollbars on the product details page.
<img width="1433" alt="screen shot 2017-08-08 at 8 41 23 pm" src="https://user-images.githubusercontent.com/16485679/29108331-2428ff92-7c7a-11e7-9c17-a1ede083ce3f.png">

### Versions
(run `reaction -v` from your reaction directory)

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by zenweasel** [comment]
@curranabell Isn't this a duplicate of https://github.com/reactioncommerce/reaction/issues/2494 which was just closed in `marketplace`?

**Comment by curranabell** [comment]
@zenweasel I did not notice this was just fixed in the marketplace branch. I will close this. Thanks for fixing this!
