### ISSUE TITLE
[Marketplace] Add in-app notification & confirmation to newly promoted account

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#2661]
As mentioned during review of #2651 

Send in-app notification to newly promoted account. We currently send only email, 
Also and ask for their confirmation/acceptance before making them an admin.

Related to #2195

**Comment by omedale** [comment]
Hi, I have used reaction for a few weeks now, I think I can work on this and send a PR in few days

**Comment by aldeed** [comment]
Closing as "won't do" for now. This can be reevaluated after Reaction 3.0 auth changes are finished
