### ISSUE TITLE
use dynamic import in registerComponent

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2666]
Reaction UI components should use [dynamic imports](https://blog.meteor.com/dynamic-imports-in-meteor-1-5-c6130419c3cd) and defer loading modules by default. Perhaps we could add that functionality to registerComponent. See #2487

**Comment by mikemurray** [comment]
A few thoughts.

1. `import("tool")` might need to be a literal string vs being done dynamically through a variable.
1. Our usage of `import { something } from "somewhere"` may lead bigger than necessary modules, depending on babel config.
1. Splitting every UI component into a module may end up in a lot of duplicated imports per module depending on how the code it split by meteor/babel.

**Comment by spencern** [comment]
@aaronjudd 
Can I close this in favor of the more specific #2634, #2635, #3595, #3594, or should we update this ticket to address anything more specifically?

**Comment by spencern** [comment]
Closing in favor of the more specific issues.
