### ISSUE TITLE
[Marketplace] After accepting shop owner invite, currency is forced to locale currency and won't change

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2668]
### Expected behavior
Should use Shop currency unless changed

### Actual Behavior
Use "detected" currency, doesn't change even when changing in currency drop-down

### Steps to Reproduce the Behavior
1. Use VPN or some other method so you are in a non-US locale
1. Invite a shop owner
1. Using incognito accept invitation
1. Create a product
1. Observe that product now displays in locale currency
1. Change dropdown, observe that currency does not change.

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
```

**Comment by aaronjudd** [comment]
The expected behavior is that the currency and language should be defaulted to the marketplace owner's shop's default.

**Comment by jm-wanja** [comment]
I have been able to default the currency and language to the marketplace owner's shop's default, but changing the currency on the dropdown, does not change the created product's currency to the new currency. @zenweasel 
You can test this on branch [wanja-fix-issue-2668](https://github.com/reactioncommerce/reaction/tree/wanja-fix-issue-2614)

**Comment by zenweasel** [comment]
@jm-wanja If this is ready to test, you want to open a PR?
