### ISSUE TITLE
There should be some way to close the "cart drawer" besides going to checkout

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2671]
Once you open the cart drawer that screen real estate is lost and no matter what you do can't get it back without going to checkout. Seems like there should be a close/open switch. Or maybe there is one and I am too stupid to see it.

**Comment by jshimko** [comment]
Clicking the cart button again closes it.  But yeah, definitely agree there could be more options.  Ideally something like clicking outside of the drawer closes it (like a modal or popup)

**Comment by aaronjudd** [comment]
@rymorgan should be considered in #1627

**Comment by rymorgan** [comment]
Added an X-out for closing the cart drawer. I also think we should add the ability to close the drawer by clicking on the page. 

Reaction Links: 
Top - https://zpl.io/2vnqvr2
Side - https://zpl.io/2j4omra

Public Links:
Top - https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/5956f1e66f9912b81a8ce384
Side - https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/5956f1e6e6bddfc30f60cf2a

**Comment by rnandhakumar1995** [comment]
Add these lines inside cartDrawer template in cartDrawer.html

```
<div class="text-right">
    <a class=" text-danger"><i class="fa fa-times fa-lg" id="closeCart"></i></a>
  </div>
```

and the following lines to cartDrawer.js


**Template.cartDrawer.events({
  "click #closeCart": function(event, instance) {
    return $("#cart-drawer-container").fadeOut(300, function () {
      return Reaction.toggleSession("displayCart");
    });
  }
});**

**Comment by zenweasel** [comment]
@rnandhakumar1995 Actually most of that code is not in that file anymore. It's been converted to React.
https://github.com/reactioncommerce/reaction/blob/8d1740ce76d5ad06d0f01b79b1480306aaf9ca1d/imports/plugins/core/checkout/client/templates/cartDrawer/cartDrawer.html#L16

**Comment by aldeed** [comment]
Resolved in new storefront UI
