### ISSUE TITLE
Translations issues in dashboard

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2672]
Most translations were fixed by PR #2642 , these are the few remaining.

![](https://user-images.githubusercontent.com/4482263/28988165-6b881076-7923-11e7-83d9-46e165a225a0.png)

![](https://user-images.githubusercontent.com/4482263/28988167-6d123cf0-7923-11e7-9fc0-2586ae35ccf6.png)

![](https://user-images.githubusercontent.com/4482263/28988177-75474b86-7923-11e7-8017-b18178a2b74a.png)

**Comment by zenweasel** [comment]
Closed via #2695
