### ISSUE TITLE
Updates to User Profile page

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2674]
We'd like to make updates to our user profile page to allow users to update information.

We'd like to add the following:

1) Ability to change profile image
~2) ability to add / change email address~
3) ability to add social account after an email account is created
4) ability to change display name

**Comment by aaronjudd** [comment]
[- redacted private image ]
![29294025-351fccc2-8102-11e7-9a49-df3187dd732c_png__1666x1318__and_sharing_frame_window](https://user-images.githubusercontent.com/439959/29296325-6b65ec88-810e-11e7-8ceb-c094dad53575.png)

**Comment by kieckhafer** [comment]
[- redacted private image pt 2 ]
![new](https://user-images.githubusercontent.com/4482263/29296379-bc7047d6-810e-11e7-8c2e-cf544fd585be.png)

**Comment by cindyfirestone** [comment]
Ability to change my display name 
Add an "About Me/Bio" Field

![account_profile](https://user-images.githubusercontent.com/22083616/29688144-83c49a50-88d3-11e7-8ead-0be6b752725f.png)

**Comment by kieckhafer** [comment]
Ability to change email address is completed in PR #2745

**Comment by aaronjudd** [comment]
@kieckhafer status update on this issue? I think we can close?

**Comment by kieckhafer** [comment]
Only the email address updates are done, the rest has not yet been done. @rymorgan are there any tickets for your ideas to update this page?

**Comment by rymorgan** [comment]
@kieckhafer No there aren't. I have nearly completed designs for the User Profile pages. Having said that, I think this is a lower priority for a while as long as base functionality is there.  I don't know if we want to leave this open as a placeholder for the future though?

**Comment by kieckhafer** [comment]
Account profile is now in the starterkit, not needed in this repo.
