### ISSUE TITLE
Write docs for shipping label printing

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#268]
depends on #260

**Comment by nlcluigi** [comment]
Hi,
I manage 3 marketplace stores - Amazon, Opencart and woocommerce - and for labels I'm using https://shiprobot.com/ to generate UPS and CanadaPost (contract and mastercard account types) labels. They also have an options to generate labels from a csv.
From my point of view a first step in having the shipping label feature will be to have an option to export orders to a .csv file.

Regards,
Luigi

**Comment by aaronjudd** [comment]
Looks like an API integration into shiprobot would be very simple to do.  I don't think you'd need to export to CSV first. However, you can use the mongo shell to export CSV as well as json. 
for example you could do:
```mongoexport --csv --db meteor --collection orders```
