### ISSUE TITLE
Deprecate the`development` branch, change release flow

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2685]
As a team, we find the `development` branch to be a struggle, and after much discussion have decided to deprecate the `development` branch. 

While we never adopted gitflow, we came pretty close to it, more a homecrafted variant, but ever since we switched back to actually having `master` be master, it's been a "needlessly complex" solution. Many of the issues (and solutions) are covered in  [this post](http://endoflineblog.com/gitflow-considered-harmful) which captures the problem and some solutions nicely.

The proposed flow could be:

- `master` is `master`
- `release` branches (branched from master),
-  selected pull requests squash-merged to the`release` branches
-  cherry-picked items can be merged to a `release` branch from`feature` branch if an earlier release is needed.
- `feature` branches - branched from master, (suggest rebase to keep current(?))
 will be used for epics (breaking changes, epic features, architectural updates, etc)

I believe [this post is the summary](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow) (simple version) of what we've long been discussing implementing. It feels like we've been using some version of "Variation - develop + master", while we could just move to a `master` first flow.

As is pointed out in the one flow post, this could be an issue with CD, in that it's still a bit heavy using `release` branches, but I think we adapt as needed. 

I have some concerns about the downstream effect of how we handle `development` so I'd suggest we remove it from the protected branches and rename with something like `deprecated-dev`. 

some other suggestion I have:

- get rid of PRs for feature branches -> commit direct, CI must pass... (assuming features have more than one developer, everyone learns to run tests locally first before pushing)
- code reviews performed on feature branches, hot patches etc.
- PR's / Patches/ Fixes can be made to `master`, we'll just change them to whatever `release`  they are to be shipped with.
- adopt a branch naming standard

I'd also like to see us add the updated release process to our documentation, so it's clear to everyone...

**Comment by machikoyasuda** [comment]
I'm going to update `redoc` and `reaction-docs` repositories to also follow whatever flow for what we decide here.

**Comment by joshuacox** [comment]
+1 LGTM

**Comment by joshuacox** [comment]
+1 LGTM

**Comment by kieckhafer** [comment]
![image](https://user-images.githubusercontent.com/4482263/29632780-de1e2394-87f8-11e7-8395-1e494213bd3c.png)

**Comment by zenweasel** [comment]
Before we do this I feel like we need to make sure we have all the bug-fixes that were on `development` cherry-picked over to `marketplace`. It's probably not a lot but I feel reasonably sure there are some and I would hate to just lose all that work.

**Comment by aaronjudd** [comment]
This is in progress now, we're finishing a merge of development into master, and coming soon..

**Comment by aaronjudd** [comment]
`development` branch has been unprotected and deleted.  Everyone should keep an eye out and review and docs,etc.  I will publish an updated abbreviated version of this discussion to the contributor docs, but the short version is:   contributor PR's, bugs, patches, etc should be made to master now.

**Comment by aaronjudd** [comment]
`development` branch has been unprotected and deleted.  Everyone should keep an eye out and review and docs,etc.  I will publish an updated abbreviated version of this discussion to the contributor docs, but the short version is:   contributor PR's, bugs, patches, etc should be made to master now.
