### ISSUE TITLE
Publish all without label doesn't let know which product is missing label

### ISSUE THREAD

**Issue by janat08** [reactioncommerce/reaction#2690]
### Expected behavior
If there are problems with a product during publish all, an informative error message would be displayed that indicates what needs to be done

### Actual Behavior
error is produced, but there's no immediate indication of where user attention is required

### Steps to Reproduce the Behavior
1. Login as Admin
1. Create a product but leave "Label" blank
1. Navigate to the product grid
1. Hit "Publish All"
1. Observe that the products don't publish, but there is no indicator what the problem is or which product is problematic.

### Versions
Node: 6.11.2
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.1
Reaction branch: master

**Comment by janat08** [comment]
Also spamming add products may block out publish all.

**Comment by spencern** [comment]
Thanks for reporting this,
We've got an open issue to redesign the way we validate errors when editing or creating a product.
#2274 

Additionally #2404 gets into this issue a bit as well, though not specifically in regards to the label.

**Comment by zenweasel** [comment]
@rymorgan It would be great to get some design input on how this error message should show up. My first idea was just a red X on the products that are problematic but maybe there is something better/more informative.

**Comment by janat08** [comment]
Filtering out products that are okay, or not part of publication draft is good.

**Comment by rymorgan** [comment]
@zenweasel What would be ideal is you show a red dot instead of the sea green dot on the products. And open the sidebar and, highlight the field and that needs is required with an inline alert that explains what the user needs to do to finish the publishing process. In the case of multiple products missing the label field, we would have to show that inline alert above the grid and say where they need to edit the fields.

**Comment by aaronjudd** [comment]
@jm-wanja what's the status of this?

**Comment by jm-wanja** [comment]
@aaronjudd I haven't worked on this yet, I've been dealing with #2533 in the past couple of days.

**Comment by jm-wanja** [comment]
@rymorgan should the red button completely replace the sea green button(which shows changes made to the product that have not been published) or the red button should show that the product is missing the variant Label? @zenweasel

**Comment by rymorgan** [comment]
@jm-wanja Yes, it should look like this, where teh sea green changes to a danger red (@rui-danger). 
![reaction-lable-indicator](https://user-images.githubusercontent.com/20409254/30079798-47b04782-9236-11e7-9cfa-6e0a718e815b.png)

**Comment by zenweasel** [comment]
Reopened by #3021

**Comment by zenweasel** [comment]
This is still a valid ticket, we just need to ensure that the "red dots" are only shown when the product is actually invalid and double check that creating products in a marketplace shop show up correctly.

**Comment by zenweasel** [comment]
Closed via #3147
