### ISSUE TITLE
Template rendered twice

### ISSUE THREAD

**Issue by rnandhakumar1995** [reactioncommerce/reaction#2698]
![screenshot from 2017-08-18 11 07 09](https://user-images.githubusercontent.com/17358198/29445736-df171e82-8405-11e7-9caa-f6373ff8c84e.png)
![screenshot from 2017-08-18 11 07 31](https://user-images.githubusercontent.com/17358198/29445737-df1cb248-8405-11e7-84d1-d476f678c76b.png)

### Expected behavior 
Only one time the template should render. While entering to the above mentioned URL, the accountDashboard render twice but dashboardHeader renders only once. The expected result should render only one accountDashboard template. I don't know where the exact problem lies.

### Actual Behavior
When I go to **http://localhost:3000/reaction/dashboard/accounts** the template render twice

### Steps to replicate 
1. Login as admin
1. Go to the Account section in dashboard.
1. Observe the template is rendered twice.

### Versions
Node: 7.10.1
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.9.2
Reaction: 1.2.0
Reaction branch: master

**Comment by rnandhakumar1995** [comment]
I need some help.

**Comment by zenweasel** [comment]
Fixed in current version

**Comment by rnandhakumar1995** [comment]
But I have customised previous version. So please provide me some solutions to fix this.
