### ISSUE TITLE
Checkout should break down items by Shop

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2700]
Customers should see their Cart broken down by Shop during Checkout

**Comment by aaronjudd** [comment]
@rymorgan we should resurrect #2052 and apply updated designs that handle selected of shipping methods for multiple shipments in the marketplace check out.

**Comment by rymorgan** [comment]
Here are some mocks for how to handle split shipments in the checkout. We can ignore other updates to this page for now :) Just working on some ideas to further streamline our already streamlined checkout. 

Reaction Internal Link: 
https://zpl.io/aNvQNQa

Public Link: 
https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/599f50c0ae99011042902eb0

**Comment by spencern** [comment]
As this works for a single-shop instance, I'm not sure it needs to be part of the `marketplace v1.5.0` release, though it is important for marketplace shops.
@rymorgan's internal link wasn't working for me, but this is the screen this issue refers to: https://scene.zeplin.io/project/58af8900737c137280322bd6/screen/59a9ace08202ee79d860baaf

**Comment by rymorgan** [comment]
Here's the Zeplin link again: 
Internal - https://zpl.io/2jo7M4V

**Comment by kieha** [comment]
@zenweasel a bit of clarity on this ticket: the designs linked to this are for the splitting the checkout shipping per shop, but the description talks of the cart. Should this cover both instances?

**Comment by zenweasel** [comment]
@kieha I really meant Checkout but it really should be both Cart and checkout as the changes to cart should be very minimal and can probably be lifted/reused from Completed Order.

And just to be clear, this task involves a rewrite to React and along with settings is the last vestige or Blaze.

**Comment by kieha** [comment]
@zenweasel noted.

Update:

- Starting with checkout split shipping as there are already designs for that in place. 
- @rymorgan there should probably be designs for a split cart per shop as well.

**Comment by rymorgan** [comment]
I'm not 100% sure we need to split by shop in cart, that's why we don't have designs. Amazon, does not split by shop in the cart, as they want to look like they are the marketplace. Google express does do that because it's heavily driven by known brands. What's the 80/20 for us?

**Comment by spencern** [comment]
Pretty sure we decided _not_ to split by shop in cart.

**Comment by spencern** [comment]
Split in checkout should probably be based on _fulfillment_ rather than shop (though shop is a good 80% start to that for marketplace)

**Comment by rymorgan** [comment]
Discussed this with Aaron, and he wants to split in cart, but the priority here is the checkout part of the task.

**Comment by zenweasel** [comment]
This is a pretty big issue with some implied requirements (different shippers per shop). Do we want to break this down any and spec it out a little more than just the one design?

**Comment by rymorgan** [comment]
@zenweasel -- yes, that would be great. Maybe the cart/checkout should be separate issues.

**Comment by zenweasel** [comment]
Cart is broken out into a separate issue in #3096

**Comment by zenweasel** [comment]
Will not fix
