### ISSUE TITLE
PeerDB promotion

### ISSUE THREAD

**Issue by janat08** [reactioncommerce/reaction#2706]
### Expected behavior
Denormolizes relational data, and keeps the sync by watching oplog. There're more powerful features for establishing relations.

### Actual Behavior
Hacking some of backend functionality can get ugly in marketplace, and especially as far as plugins are concerned. I took a peek at collections and there was not insignificant amount, surely performance benefits alone would make it count, the declarative relationships aside. I would bet some of those collections don't change enough that they deserve to be normalized.

**Comment by zenweasel** [comment]
Establishing relational data in a document database is a performance anti-pattern. "Joins" are extremely expensive and don't work across partitions. Our long-term plan for our database is towards GraphQL/Apollo. If you want to see where are going you should take a look at: https://github.com/reactioncommerce/reaction-api-base.

In addition we are no longer any adding any Meteor packages as dependencies as both Reaction and Meteor migrate towards NPM.

**Comment by janat08** [comment]
It says it denormolizes instead of doing joins. It meant references as joins, the ones you have now.
