### ISSUE TITLE
[Marketplace] Receive 404 when completing checkout using Paypal Express

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2708]
### Expected behavior
You should be able to complete an order on the `marketplace` branch when using Paypal Express

### Actual Behavior
Receive a 404 after payment is complete

### Steps to Reproduce the Behavior
1. Login as admin
1. Enable Paypal express
1. Attempt to checkout
1. Observe 404 when server-side payment is complete

The return URL just needs to be changed to not use the shop prefix.

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
```

**Comment by aaronjudd** [comment]
Status on this? seems blocked by the #2710 which seems to be abandoned...

**Comment by aaronjudd** [comment]
btw - I am able to, and do checkout with express every day, all the time.. on marketplace, so maybe this is "cannot reproduce?"

**Comment by zenweasel** [comment]
This was definitely broken at some point but it could have been fixed by some other PR. If nobody can reproduce we can close. I will try to reproduce today and close if I can't.

**Comment by zenweasel** [comment]
Testing on current `marketplace` in a single-shop setup and not seeing this issue.
