### ISSUE TITLE
[Marketplace] Checking out as merchant shop owner doesn't load shipping rates

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2713]
### Expected behavior
I should be able to checkout as any user, including merchant users.

### Actual Behavior
Checking out as a merchant shop owner, I receive no shipping methods configured error, clicking into the dashboard causes errors because merchant shops shipping packages are disabled by default.
![image](https://user-images.githubusercontent.com/1203639/29546486-ffa4bdd6-86b1-11e7-840f-17fa21d04178.png)

### Steps to Reproduce the Behavior
Invite a new shop owner
Accept invite and then add a product to cart and try to checkout as a shop owner

### Versions
```
Node: 7.8.0
NPM: 5.0.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: spencer-stripe-connect-merchant-signup
Docker: 17.06.0-ce
```

**Comment by zenweasel** [comment]
Closed via #2741
