### ISSUE TITLE
[Marketplace] Update aliases and scope naming convention

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2714]
Suggest that aliases and scope used with Reaction should be: `@reaction/package` and not `@reactioncommerce/package`.  Where @reaction package/namespace/scope belongs to the @reaction application, @reactioncommerce should be probably be reserved for more other tools built by Reaction Commerce

**Comment by spencern** [comment]
@aaronjudd is this a blocker for the Marketplace release for you?

**Comment by aaronjudd** [comment]
It might be, but I really can't answer that until next week, so ..`not for now`
