### ISSUE TITLE
[EPIC] Shopify Connector Sync and Import

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2718]
This development is meant to serve as an example for how to create connectors to other commerce platforms or data sources.

Phase 1 is completed and provides the framework necessary to extend and customize the Shopify importer.

Phase 2 and 3 will get scheduled as we have capacity and would make great candidates for a community contribution (that means you!).

If you have any specific needs you'd like to see integrated into the Shopify connector sync or import, feel free to leave a comment.

### Phase 1. #2808 (Complete)
- Add dashboard settings panel with the following settings 
  - "Update inventory when Shopify Order is placed" checkbox
    - When this is checked, we will attempt to keep products on Reaction that were imported from Shopify in sync with their counterparts on Shopify
  - "Setup Sync" button that creates webhooks for all integrations (just one to start)
  - "Stop Sync" button that destroys webhooks for all integrations
imported from Shopify to match the current Shopify inventory quantity
- When Shopify order is placed, update inventory quantity on Reaction via webhook for the products that are involved

### Phase 2. Export Orders #3322 (Complete)
- When Reaction order is placed, update inventory on Shopify
  - "Sync orders to Shopify checkbox
    - When this is checked, we will push orders created on Reaction to Shopify
- When Reaction order is placed, create order on Shopify with status ?? and tagged "reaction-generated-order"

### Phase 2A- Sync Inventory and Fulfillment Status [TBD]()
- Update Dashboard settings panel with the following settings
  - Inventory Buffer Number Field
    - This field will control the difference between the Reaction and Shopify Inventories. Set it to zero to keep them identical. A positive number will cause that Reaction products will show \[number\] less inventory than Shopify.
- Sync Inventory Now button that will update all products and variants on Reaction that have been 
- When Reaction order payment is captured update payment status on matching Shopify order 
- When Shopify order fulfillment event happens, check Reaction for matching order and update Reaction order fulfillment status.

### Phase 3. [TBD]()
- Create unlisted Shopify App to make setup easier for sellers on Shopify.
  - https://www.shopify.com/partners/blog/17056443-how-to-generate-a-shopify-api-token
- When Shopify order is refunded
  - check Reaction for matching order and update workflow to "refunded" if matches
  - check Reaction for order items that match and update item workflow if match
  - check Reaction for product variants that match and if "restock" was selected, update inventory appropriately

### Future
- Sync customers with Shopify
- Sync product/variant content updates to Shopify

### Notes
- Shopify has pretty good API docs. Available here: https://help.shopify.com/api/reference
- We're using this npm lib to interact with  https://www.npmjs.com/package/shopify-api-node

**Comment by tom-gerken** [comment]
For shopify orders, they should populate with the customer name and address, as well as the following fields;

fulfillment_status:"unfulfilled",
note:“Order Processed by <<Store name, ie Foray Collective>>”,
financial_status:“paid”,

Possibly?
"landing_site": "<<ROOT URL of reaction site>>”,

for reference:
https://help.shopify.com/api/reference/order

**Comment by spencern** [comment]
From @tom-gerken 

We should consider creating an unlisted Shopify App to make onboarding easier.

**Comment by lauragobrightly** [comment]
+1 on the unlisted Shopify app. Most Shopify merchants who connect to external marketplaces do this via Shopify apps (which can be costly to develop)

**Comment by zenweasel** [comment]
@spencern Is this something we still want to continue on? Seems like an integrations issue but I am not sure if Shopify is on our priority list right now?

**Comment by spencern** [comment]
Happy to look at a PR to add this functionality.

**Comment by lauragobrightly** [comment]
As the following functionality does not appear to be in place (correct me if I'm wrong!), my team is investigating contributing to the Shopify feature by also allowing the following:

- When the user places an order on Reaction, the order in its' entirety is sent to the vendor's Shopify dashboard
- When the vendor updates the status of the order on Shopify, the same order information is updated in Reaction (Fulfilled, Shipped, etc.) 
- Email notifications to the user will be sent through Reaction as the order is updated/shipped by the vendor via Shopify

**Comment by spencern** [comment]
@lauragobrightly This looks like a good list of additional features. Seems like you and your team might have the right business case to better define a good set of requirements for the Shopify plugin.

If you are interested in contributing to that plugin, let us know how we can help.

**Comment by zenweasel** [comment]
This plugin has been moved to https://github.com/reaction-contrib/meteor-connector-shopify. Should we close this now?

**Comment by spencern** [comment]
Closed.
