### ISSUE TITLE
Extending Orders to be accessible as the other reaction collections

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#272]
Hi,

Are you planning to export the Orders collection the same way as the other reaction collections in the future?
Right now I am only able to access them via ReactionCore.Collections.Orders and not as simple Orders?
Am I doing something wrong or the implementation is different from the other collections for example: Products.
Thanks!

**Comment by aaronjudd** [comment]
`ReactionCore.Collections.Orders` is the correct way, we've been migrating away from exporting the `short` version, and probably will stop using the short version altogether in the near future, so the safe thing to do is to use the name-spaced long form for other collections as well.

Other than convenience, I can't really think of a good reason to keep the short version, and the namespaced version should prevent any conflicts down the road.

**Comment by aaronjudd** [comment]
As noted, declare in locally and use  `Orders = ReactionCore.Collections.Orders`.
