### ISSUE TITLE
[Marketplace] Permission list duplicated for marketplace shops

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2728]
### Expected behavior
Should show only the permissions available for the current shop.

### Actual Behavior
Shows primary shop permissions, followed by all marketplace shops.

### Steps to Reproduce the Behavior
1) Add one or more marketplace shops
2) Switch to your new shop, and back to the primary shop in the shop switcher dropdown
3) Open accounts and search the list and you'll see `Account` or `Account View` duplicated in the list for as many shops as you've added/switched to without refreshing the page.

![permissions](https://user-images.githubusercontent.com/42217/29639576-0f67ea22-8810-11e7-9c16-43196ea7027b.png)

**EDIT** Doesn't seem to happen by default, but when switching shop context in the dropdown. Maybe related to https://github.com/reactioncommerce/reaction/issues/2726

### Versions
Node: 7.2.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.1-ce

**Comment by mikemurray** [comment]
@impactmass can you verify this behavior.

**Comment by impactmass** [comment]
Verified. Working on it now

**Comment by impactmass** [comment]
Fixed by #2734
