### ISSUE TITLE
[Marketplace] Can create shop with same name as another shop

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2736]
### Expected behavior
Shops should not be able to share a name / slug, each should have a unique name / slug to access it

### Actual Behavior
Adding two shops with the same name causes an issue where only 1 of the shops shows up. The second (or third or fourth...) shop is still inside the database, so the info is saved, we just pull the data from the most recently added.

### Steps to Reproduce the Behavior
1) Invite a new shop to marketplace
2) Sign in with your new shop
3) Name your shop "Test Reaction Shop" (or anything)
4) Invite a second new shop to marketplace
5) Sign in with your new shop
6) Name your shop the same name as you did the previous new shop ("Test Reaction Shop")
7) See that only the most recently added shop is available

### Possible solution
We do not save a shops slug on the shop object, we dynamically create it by slugifying the shop name. If we were to save a shop slug, we could save this as a unique field, which would allow two shops to have the same name.

Or... we just don't allow two shops to have the same name

### Versions
Node: 4.2.6
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.1-ce

**Comment by aaronjudd** [comment]
Probably should set schema to `unique:true` as well.

**Comment by zenweasel** [comment]
Closed via #3745
