### ISSUE TITLE
Uncaught TypeError: Cannot read property 'public' of undefined  with android  version

### ISSUE THREAD

**Issue by blackjack0v0** [reactioncommerce/reaction#2748]
when I run `meteor build`  and **get a apk** ,I run it on my mobile ,then I get this, I clone the official repo,and 
**it work perfect on browser**,but just can't fire up in android ,is there any way  to fix this problem 
```
Uncaught TypeError: Cannot read property 'public' of undefined     app.js:101250 
Uncaught TypeError: Cannot read property 'Subscriptions' of undefined  app.js:98323 
Error: Error parsing asset manifest
    at http://localhost:12760/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js:36:21
    at Object.cordova.callbackFromNative (http://localhost:12760/cordova.js:293:58)
    at <anonymous>:1:9     webapp.js:72 
```

**Comment by blackjack0v0** [comment]
@queso @dearfrankg @mikemurray @actuosus @zenweasel

**Comment by blackjack0v0** [comment]
the problem code in app.js
` if (_Reaction.Subscriptions.Shops.ready() `

**Comment by spencern** [comment]
Hi @blackjack0v0,

Please do not tag users in issues like this, it is unhelpful and spammy behavior and will not result in your issue being looked into any faster.

Additionally, please fill out the new issue template that you deleted when filing this issue. We cannot proceed on a reported issue without that information.

Thanks for checking out Reaction.
