### ISSUE TITLE
 fail to work on mobile after built with meteor cli 

### ISSUE THREAD

**Issue by blackjack0v0** [reactioncommerce/reaction#2757]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Expected behavior
working  on mobile(android) after built with meteor cil using
`meteor build`

### Actual Behavior
build successful but bootstap fail with error 

```
Uncaught TypeError: Cannot read property 'public' of undefined     app.js:101250 
Uncaught TypeError: Cannot read property 'Subscriptions' of undefined  app.js:98323 
Error: Error parsing asset manifest
    at http://localhost:12760/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js:36:21
    at Object.cordova.callbackFromNative (http://localhost:12760/cordova.js:293:58)
    at <anonymous>:1:9     webapp.js:72 
```
  
the problem code in app.js
`if (_Reaction.Subscriptions.Shops.ready()`

![2017-08-27 18-36-42](https://user-images.githubusercontent.com/27153331/29822218-48662374-8cfd-11e7-9d9a-eae0a9aaa9aa.png)

### Steps to Reproduce the Behavior
1.run `meteor build` in the project root directory and get a apk version app
2. install the apk on mobile 

### Versions
(run `reaction -v` from your reaction directory)
```
Node: 6.9.3
NPM: 4.0.5
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.1
Reaction branch: master

```
For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by blackjack0v0** [comment]
anyone have some ideas?

**Comment by jshimko** [comment]
You may need to take this to the Meteor forums.  We don't currently support doing builds of Reaction using Meteor's Cordova integration.  None of us have ever used it and it has been my experience that it's fairly hard to get it working.  That doesn't mean you _can't_ get it working, but I'm afraid the internal Reaction team won't be of much help.

I assume you've already seen these, but you should definitely read every bit of these two sources of info...

General guide
https://guide.meteor.com/mobile.html

API reference
https://docs.meteor.com/api/mobile-config.html

Mobile category on the forum
https://forums.meteor.com/c/mobile

Not sure if this actually builds/works, but Meteor has an example app with the mobile stuff configured.  You can test that and possibly use it as a reference
https://github.com/meteor/todos

**Comment by blackjack0v0** [comment]
@jshimko thank you for your help,I will try it out.
