### ISSUE TITLE
Marketplace orders dashboard broken

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#2758]
### Expected behavior

 - Can select multiple orders

### Actual Behavior

 - Cannot select multiple orders (Code missing due to merge issue)

### Steps to Reproduce the Behavior

- Make order
- Open orders dashboard and try select an order
- Observe that it doesn't happen

### Reaction Version
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by kieha** [comment]
Closed by #2759
