### ISSUE TITLE
Proposal to refactor Reaction.hasPermission method

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2761]
This is a proposal to discuss refactoring the `Reaction.hasPermission` method
The `hasPermission` method exists on both the [server](https://github.com/reactioncommerce/reaction/blob/marketplace/server/api/core/core.js#L154) and the [client](https://github.com/reactioncommerce/reaction/blob/marketplace/client/modules/core/main.js#L175)

The current method signature for hasPermission looks like this `hasPermission([arrayOrStringOfPermissions], userId, shopIdOrGlobal)`
userId defaults to the current user, and shopId defaults to the current shop.

Within marketplace it is far more common to check a shopId that is not current than a different userId. 

I'd like to suggest that we switch the last two params of this method  so that it becomes `hasPermission([permissions], shopId, userId)`

**Comment by aldeed** [comment]
Done in 2.0.0
