### ISSUE TITLE
Handle discount by Shop

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2763]
Right now we really only handle discounts defined at the primary shop level. We need to determine if merchant shops are allowed to set discounts and how they would be applied and if we want have configuration options to disable this.

Just looking to get some specific clarity and a spec on this

**Comment by spencern** [comment]
Here are the main challenges I see regarding discounts at a marketplace level:

1. Permitting the primary marketplace to set discounts doesn't work well with Stripe Direct style charges. These charges are made on behalf of a merchant and the merchant is ultimately responsible for the charge. The marketplace cannot send additional money as part of this transaction, so it becomes very difficult to apply marketplace-wide coupons.

2. To permit marketplace-wide discounts, I think a payment provider implementation more similar to Stripe Connect Custom would be necessary. [Stripe Connect Custom Accounts](https://stripe.com/docs/connect/custom-accounts) permit the marketplace owner to make transfers to the connected accounts for more than the amount of the transaction, this would allow a marketplace to run promotions and use discounts while still providing merchants with the full purchase amount.

3. We enable the discounts plugin for each merchant. This should be a simple update to the server side code, but will require a more involved client checkout page update. Right now the checkout page supports a single discount code, while the backend supports multiple. We'd need to update the client to accept one (or more) discount codes per shop involved in a transaction.
It seems that this would need to have some marketplace configuration options as well, as some marketplace owners may not want each merchant providing their own discount codes.

**Comment by zenweasel** [comment]
@aaronjudd Per our discussion we are only doing discounts at the marketplace level and let marketplaces and merchants work out the business rules.

**Comment by aaronjudd** [comment]
@spencern we should remove the marketplace label here, as long as discounts are working for single shops, we are good for 1.5.0, and generally, we need to implement some marketplace logic/rules. mainly @spencern #3 is on target, the logic already handles multiple code, it's really just a UI issue if this isn't exactly working as expected.  I think it's up to the merchants to allow/disallow merchants having discounts (I'd assume most won't want this), but we'd perhaps need to look at precedence - ie, a merchant discount can only apply to their products, not the whole cart.

**Comment by aldeed** [comment]
This is done for now but will be done properly in the new promotions project
