### ISSUE TITLE
Update Avalara tax methods to work with Marketplace

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2764]
Should work how the current "Custom Tax Rates" package works in marketplace.

We also need to figure out how to accomodate the situation where merchant shops may have a different Nexus than the primary shop. I spoke with Avalara and their preliminary answer was "we don't really do that".

**Comment by spencern** [comment]
The multiple nexus scenario is the most challenging part I think.

The "custom tax rates" package works in marketplace by enabling each merchant to set their own rates for regions and postal codes. This effectively permits shops to use tax rates that are specific to one or more Nexus of business they operate.

**Comment by spencern** [comment]
We should figure out what our solution is for plugins or third-party service providers that don't really support marketplaces. Do we disable them if Marketplace is enabled? Do we need a flag for a plugin that is `marketplaceCompatible` or similar?

**Comment by zenweasel** [comment]
Maybe a set of Marketplace-specific settings (like `enabledForMerchantShops`) that if they don't exist the package is not Marketplace-aware?

Some packages don't need to be marketplace aware?

**Comment by aaronjudd** [comment]
perhaps we should be using a "provides" value that is different  `marketplace` specific packages.
ie, not "provides: payment" but `"provides": "marketplace-payment"`?  Feels like adding a bunch of things like "marketplace: enabled" to be anti-pattern.

**Comment by spencern** [comment]
@aaronjudd I agree that that seems to be a better pattern. A package could then have a `provides: "payment"` as well as a `provides: "marketplace-payment"` or similar.

Part of this challenge here is that for packages that provide marketplace functionality, most will also provide single-shop functionality

**Comment by aaronjudd** [comment]
we could update provides to handle an array. `provides: [payment, marketplace-payment]`. That'd be a big functional update, but probably only touched in a few publications.

**Comment by spencern** [comment]
That could be cool. Would enable some new functionality, and if separate templates, routes, permissions etc were needed you could still separate them.

**Comment by spencern** [comment]
We should revisit this with #2930 being (almost) ready to merge now.

It seems that using `marketplace-taxes` etc would be the way to go. Now we should decide how we want to determine if a shop is using Marketplace or not. I'd think a switch to turn it on would be the way to go, with a confirmation for turning the switch off if there is at least one merchant shop. When marketplace is `on` we could check for `marketplace-` prefixed payment, taxes, shipping, etc packages to know that we're only loading packages that are ready.

**Comment by aaronjudd** [comment]
@zenweasel @spencern #2930 merged in over this past weekend. 👍

**Comment by spencern** [comment]
This probably isn't a blocker for `1.5.0` as we need more clarity on the approach to marketplace taxation. I'm not convinced that Avalara and TaxCloud don't support this, and it seems crazy that they don't. Let's revisit this after shipping 1.5

**Comment by zenweasel** [comment]
Won't fix. Avalara no longer part of the core offering
