### ISSUE TITLE
Update Data Fetching in Order Dashboard Table

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#2768]
Order Dashboard Table is currently using ReactTable's way of passing publication/collection as opposed to passing it the actual data

This is to change that approach to passing the data to the table using the `otherData` prop as explained here #2631 (to follow similar way it's done in Accounts dashboard). 

After this is done, ensure that all current parts of the table works as is (i.e the filters, search etc).
Also, when this is done, we should be able to easily achieve the last bit of the search requirements (#2355): 
> If there is exactly one order with matching customer information, the matching orderId should be opened in the action view panel if the user has permission to view that order.

**Comment by joykare** [comment]
#2872
