### ISSUE TITLE
Implement sorting and filtering of search results

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#277]
After a search is completed, a user should be able to further refine through sorting and filtering of:

* [ ] Tag
* [ ] Brand
* [ ] Price
* [ ] Best sellers
* [ ] NewestColor

**Comment by lovetostrike** [comment]
I think one option that is usually lacking for ecommerce sites is 'exclude'. It would be great to have a UI to toggle between include-exclude.

**Comment by evliu** [comment]
+1 on lovetostrike's suggestion. on some sites that implement google search engine, you can add a NOT or minus sign in front of words, but it's not common

**Comment by aaronjudd** [comment]
Reviving this very old issue,  to track the completion of product range search, where results should be inclusive of all matching variants in the product price range results. 

Default product price range query should pass  `http://localhost:3000/reaction/tag/shop?price.min=12.99&price.max=19.98`

Tests need to be added for all the queries created for https://github.com/reactioncommerce/reaction/pull/875 and https://github.com/reactioncommerce/reaction/pull/743
