### ISSUE TITLE
Updated copy for email update verification email

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2778]
There is a new email that is sent out when a user updates their email address ( PR #2745 ). We need updated copy to go in this email.

**Comment by sophiehe** [comment]
Subject line: Verify your new email address

Hi [firstname],

Your email address was recently updated in Reaction. To complete the update, please verify your email, [emailaddress]. 

CTA: Verify Email

We'll always reach out when there's activity on your Reaction account. 

Don't recognize this request? [Contact](https://gitter.im/reactioncommerce/reaction) us, [email](hello@reactioncommerce.com) us, or [file](https://github.com/reactioncommerce/reaction/issues) an issue. 

Thanks!
The Reaction Team

**Comment by aaronjudd** [comment]
@kieckhafer ok to close this?
