### ISSUE TITLE
Marketplace Shipping Rates

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2781]
This issue is part of the Marketplace Checkout milestone

There is a [marketplace flag](https://github.com/reactioncommerce/reaction/blob/marketplace/imports/plugins/included/marketplace/register.js#L56) `merchantFulfillment` which defaults to `true`. When this flag is true, there should be a shipment created for each shop represented in an cart and order.

There are two scenarios we need to cover in this circumstance.
1. Each merchant is responsible for setting their own shipping rates.
    - In this case, the shipping rates for the shipment associated with each merchant should come from that merchant's shipping settings.
    - There should be some type of fallback or error handling if a merchant does not have shipping rates setup. My suggestion would be that that merchant gets flagged as not ready and their products are not published and not available for checkout. Another option would be to fall back to the marketplace shipping rates.
    - All shipment integration plugins should be either disabled for marketplace, or should support providing shipping rates by shopId.
   - We will need to update the existing Shippo and Flat Rate plugins

2. The marketplace sets shipping rates.
    - Shipping rates for the shipment associated with each merchant should come from the primary shop's shipping settings
    - My guess is that this would need to have the marketplace cover payment for shipments when a third-party integration is used, e.g. Shippo because there will be a single API key used.
    -  Flat Rate shipping here should work fine and the payment will still get made to each merchant. Merchants will not be able to set their own flat rates in this scenario.

There is a `merchantShippingRates` flag in the marketplace plugin as well, but it will need to work in conjunction with adding or removing the shipping packages (shippo, flat rate, etc) to the merchant shops to make this truly toggle-able.

In either scenario we need to make sure that the correct shipment method is associated with each invoice and that the charges that get created are correct for each shop.

We should also be grouping items by their shipment in the review, the order confirmation, and the fulfillment section. This grouping is 

When "No Shipping Rates are configured" we should be performing any permission checks against the shop that is setup to provide the rates. #2265

An indicator that some bit of code is not ready for this would be seeing the `order/cart.shipping[0]` line of code with the 0th index hard coded.

#### Related Issues
- This should be part of the Conversion of the checkout to React #2052
- Items should be broken down by shop #2700 
- Removing hardcoded 0th indexes in shipping #2770
- Refreshing cart when shipping method changes should be more nuanced if there are multiple shops involved. #2232

#### Additional Concerns for discussion:
1. We could theoretically support unique shipping addresses per shipment, should we?
2. We don't currently support shipping on an item-by-item basis, but should probably add support for that soon. That would involve splitting shipments up by shipping method within each shop. The use case for this would be if a customer wanted to Express ship one item and Ground ship the rest.

@rymorgan's designs (WIP) for shipping rates can be seeing here https://app.zeplin.io/project/58af8900737c137280322bd6/screen/59a9ace08202ee79d860baaf

**Comment by aldeed** [comment]
Closing because marketplace is no longer a core plugin in 2.0.0
