### ISSUE TITLE
Product catalog images are randomly not displayed

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2783]
### Expected behavior
All images stored in the database should be displayed in the products listing.

### Actual Behavior
Images in the products listing are randomly displayed and randomly not displayed.
This behavior can be observed on our staging web site.

### Steps to Reproduce the Behavior
1. Import enough products and images into the shop.
2. Open the Web shop.
3. Navigate to the products listing.

### Versions
1.4.1

I suspect that this can happen due to one of the following conditions which can be checked to debug this issue (given by the probability to catch the reason for the bug):
1. Image size.
2. Image count.
3. Network connection performance.
4. Image format.

**Comment by aaronjudd** [comment]
Thanks for the report, I feel like is a duplicate report, but couldn't find another issue on this...

**Comment by aldeed** [comment]
I believe this has since been resolved, but we can reopen if anyone still sees this in 2.0 release
