### ISSUE TITLE
Need to render product options in different ways

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2785]
### Expected behavior
The following behavior is possible in various shops for product options:
1. A product option is a check-box which confirms one (single) buyer's intention. For example, when the option is the only option - render it like a check-box.
2. A product option is for choosing from several criteria groups (https://zzperformance.com/sonic/electronics/premium-canbus-hid-conversion-kit-2.html). Each choice affects price and SKU.

### Actual Behavior
1. Only choosing one of the list of options is possible.

### Steps to Reproduce the Behavior
1. Navigate to a product having product options.
2. Choose some product options.

### Versions
1.4.1

**Comment by spencern** [comment]
Hey @andrew-mikhailov-videal 
This should be pretty simple by replacing components in the current PDP or by creating your own PDP. 

The way I would go about this would be to store the currently selected (or lowest if none selected) variant price in a variable client-side, and then render the price of each option relevant to the currently selected price.

**Comment by aldeed** [comment]
No longer relevant since the example storefront is meant to be customized as of 2.0.0
