### ISSUE TITLE
Need to distinguish tags of different type

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2787]
### Expected behavior
Tags are proposed to be used for:
- store views;
- product categories;
- product custom attribute values.

Is should be easy to distinguish tags of different type while editing products, viewing products and for navigation.

### Actual Behavior
After importing store views, categories and custom attribute values, the product will have many tags and it is not obvious which tag represents which part of the data.

### Steps to Reproduce the Behavior
1. Run Magento import.
2. Open one imported product in the edit mode.
3. Scroll to the tags section.
4. Click the tags edit button.

### Versions
1.4.1

**Comment by cindyfirestone** [comment]
product categories = tags 
product custom attribute = details on a PDP 
![old_skool_hi-top](https://user-images.githubusercontent.com/22083616/30188185-0065dde4-93e2-11e7-99ea-af58ba539bf2.png)

can you clarify what you mean by store views?

**Comment by spencern** [comment]
@andrew-mikhailov-videal 
Could you share what Magento importer you are using?

It may be that the importer is not creating tags correctly or perhaps we need to update the core tag methods to handle more data.

**Comment by andrew-mikhailov-videal** [comment]
@cindyfirestone, Thank you for the answer. I will implement custom attributes as you suggest.

**Comment by andrew-mikhailov-videal** [comment]
@spencern, @cindyfirestone

In our Magento importer "store views" correspond to Magento "store views" directly.
From the business-rules perspective it corresponds to a use-case when a Web shop's Web site has multiple stores in it. Magento has this feature, osCommerce has, big custom shops we have previously developed have this feature and so on...
From  our customer's perspective, it corresponds to car "brands". I have made it filterable by the "tag" I have created in Reaction. And in the customer's Magento shop it was implemented using store views.

So, after Cindy's answer on custom attributes, we still have the situation when we have tags for categories and tags for store views. Now it is less critical to distinguish them. But still, it could be nice to have.

**Comment by spencern** [comment]
Yes, I think that's a good direction re: custom tags.

Not sure if you've seen this, but @mikemurray recently added some fields to the Tag schema in #2747 and I think this would go a long way towards solving problem.

Some of this will be on the UI side as well, determining how to display or hide tags with certain properties, but I think from a navigation perspective you should be able to achieve most of your goals with tags and metafields.

**Comment by aldeed** [comment]
Closing this as solved by new navigation in 2.0.0, as well as shift to having an example storefront that should be customized.
