### ISSUE TITLE
Need more fields for product categories

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2789]
### Expected behavior
The shop administrator may wish to edit product category description, name, image, etc.

### Actual Behavior
Product categories are represented with tags. So, only name can be changed.

### Versions
1.4.1

**Comment by spencern** [comment]
Hi @andrew-mikhailov-videal 
I think my response to #2787 should get you moving in the right direction. Because product categories are represented with tags as you say, you'll just need to add some meta information to the tags and create a UI for this. Check #2747 for the update to Tags
