### ISSUE TITLE
Analytics for Search

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#279]
For Beta, this could be as simple as properly configured Google Analytics events.

**Comment by aaronjudd** [comment]
Closing, N/A

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #13](https://github.com/reactioncommerce/reaction-feature-requests/issues/13) via [**ZenHub**](https://www.zenhub.com/)
