### ISSUE TITLE
Upgrade `react-measure` to version 2.x

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2792]
Bithound is showing this as an outdated dependency and I tested just straight upgrading it and it does break the MediaGallery (the one file it's currently used in).

It's probably not a big task to adapt to the new API but it should probably be done soon.

**Comment by kieckhafer** [comment]
It's a little more complicated than just following their docs. @jshimko pointed out the issue in #2592  , we can't just wrap their new `ref` prop, like they mention in their docs... we'd actually have to rewrite the way our MediaGallery works. We currently use a react component, `MediaItem`, inside the gallery, and `react-measure` doesn't allow a nested react component, it only works on straight `DOM` elements.

@janus-reith mentioned a replacement for `MediaGallery` in the above mentioned issue... replacing `MediaGallery` is something we've discussed before, if we are moving forward with looking into a replacement, its probably best to hold off on updating `react-measure` until then, I don't know if it's worth rewriting the current media gallery just to work with `react-measure 2.0`

**Comment by zenweasel** [comment]
Whoops. Should have searched before creating this issue. It's a dupe. Closing.

**Comment by janus-reith** [comment]
@kieckhafer I answered in https://github.com/reactioncommerce/reaction/issues/2592
