### ISSUE TITLE
Break Password setting Template into separate "initial/onboarding" and "reset" flows

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2797]
Currently, we use the same Template (Blaze wrapped around React) for setting a password both the first time a user is able to - after they receive their initial welcome email - and anytime they are resetting their password.

We should:

1) Convert this fully to React (Issue #2746 )
2) Break this out to have two separate workflows depending on if this is an "onboarding" password set, or a password reset.

The Blaze templates are rendered here (currently in a PR branch, look for this same file in `master` when this gets pulled in:
https://github.com/reactioncommerce/reaction/blob/ek-accountsPatch/imports/plugins/core/accounts/client/templates/updatePassword/updatePassword.js#L16-L34

**Comment by kieckhafer** [comment]
After diving in, I think the best course of action on this is to not split up the password reset flow into two completely separate templates / components, but rather, at least for now, add a `type` prop that will allow for subtle changes between the two templates.

Feedback is welcome.

**Comment by spencern** [comment]
Resolved by #3166
