### ISSUE TITLE
Use consistent language for items in cart/order" across the app.

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2798]
This issue surfaced in #2645 but is older than that.

The language we should be using to talk about the number of items in a cart or an order is 
"Items in cart" or "Items in order"

Anywhere we use the term "Quantity Total" or other terms than the "Items in ..." need to be updated across the app.

This means we need to update at least the following locations:
* Order Completed Page
* Process Order Action View

**Incorrect**
![image](https://user-images.githubusercontent.com/1203639/30125145-b76e6fd6-92f4-11e7-8390-79639ee3870d.png)

![image](https://user-images.githubusercontent.com/1203639/30125125-a201f104-92f4-11e7-99fe-e8efb5dcc717.png)

**Correct**
![image](https://user-images.githubusercontent.com/1203639/30125169-c7e18812-92f4-11e7-916e-3a61719b11ce.png)

**Comment by codejockie** [comment]
@spencern what should I replace the text "Quantity Total" with? "Items in order" or "Items in cart"?

**Comment by spencern** [comment]
@rymorgan

**Comment by rymorgan** [comment]
Once a cart has been completed, language should change to "Items in order"

**Comment by codejockie** [comment]
@rymorgan all is done. PR for this has been raised.
