### ISSUE TITLE
Deprecate `Roles.userIsInRole`

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2800]
Remove and replace all instances of `Roles.userIsInRole` with `Reaction.hasPermission`.

This is now possible as of Meteor 1.5.1 as `Meteor.user` is now available in publications.

**Comment by zenweasel** [comment]
@machikoyasuda Are you working on this?

**Comment by machikoyasuda** [comment]
@zenweasel yes!

**Comment by machikoyasuda** [comment]
@zenweasel no! un-assigning myself.

**Comment by trojanh** [comment]
@aldeed I think this one can be closed as we do not have any `userIsInRole` usage in v3.
