### ISSUE TITLE
Login dropdown shows "Sign In" even when you are signed in

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2803]
### Expected behavior
After you sign in you should see your username/profile

### Actual Behavior
Dropdown shows "Sign In" but if you refresh you are shown as logged in

### Steps to Reproduce the Behavior
I have seen this other places but this is how I was seeing it most consistently
1. Invite a shop owner
1. Open the invite email and copy the link
1. In an incognito session open the invite link
1. Supply a password
1. Observe that even though you are now signed in the dropdown says "Sign In"
1. Hard refresh
1. Observe that your profile info shows

![not_signed_in](https://user-images.githubusercontent.com/72819/30147562-a9b323ae-93d1-11e7-8298-9590b4d9df28.gif)

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
```

**Comment by impactmass** [comment]
closed by #2884
