### ISSUE TITLE
After simple-schema update, Re-enable validation

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2806]
From @zenweasel on the #2791 PR

> Note It should be super awesome if we could have Simple-Schema enforce that all shipping records need to contain a shopId but I could not get this to work. (I removed the blackbox record to make it validate, but it threw all sort of errors). I don't think this should block us now but I would like to revisit this as soon as we make the change to node-simple-schema.

When we update to node-simple-schema in #1343, we should check to make sure that we're validating all records on cart and orders as well. Mostly by removing `blackbox: true` on most subschemas

**Comment by zenweasel** [comment]
I would make this broader to re-enable all validations that are currently disabled with `blackbox: true`

**Comment by spencern** [comment]
Some of the `blackbox: true` settings are so that we can handle future plugins that may not fit a given schema I think - e.g. payment transactions.

**Comment by zenweasel** [comment]
Right, so maybe not **all**, but certainly in the cases where we rely on the data being consistent.

**Comment by aldeed** [comment]
Resolved in 2.0.0
