### ISSUE TITLE
Better error handling for marketplace shops using incompatible packages

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2809]
In #2791 I noticed that errors are thrown when attempting to checkout with a single item from the primary shop while having marketplace enabled and at least one other shop installed and using a payment provider that is incompatible/not updated to work with marketplace yet.

That's not really a use case that we support yet, but it highlights the need for better handling of errors that arise from a misconfigured shop, as well as the need for some type of setting to note packages that work in multi-shop or marketplace installations vs packages that only work in single-shop installations. 

There is some discussion about how to identify such plugins in #2764

**Comment by spencern** [comment]
#2930 provides support for multiple values for a `provides` entry in the registry. I think that a good start for this issue could be to update all packages that are compatible with multiple shops/marketplace to include a `marketplace-` prefix in addition to their standard `provides` value. This will permit us to filter apps by marketplace or by traditional/single shop depending on the install.

**Comment by aldeed** [comment]
Resolved in 2.0.0
