### ISSUE TITLE
Limited supply label not working correctly in cart. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2811]
### Expected behavior
When you have a limited supply label it should show up in the cart and not wipe out the items in cart quantity. It could show up in a similar place on the product image in cart as it does on the product grid. 

### Actual Behavior
Limited supply shows different language and removes the product info and quantity in the cart. 

### Steps to Reproduce the Behavior
Created a product with limited supply and put it in the cart. 

<img width="1379" alt="labels don t match up with limited supply" src="https://user-images.githubusercontent.com/20409254/30227078-2e8099a2-948d-11e7-8555-60f7dd8b193b.png">

**Comment by machikoyasuda** [comment]
Split up this issue into 2 parts https://github.com/reactioncommerce/reaction/issues/2908

**Comment by aaronjudd** [comment]
@rymorgan @machikoyasuda let's be careful in the future to avoid starting development on issues that have not been triaged (by product and triage teams) yet.  @rymorgan is correct, that this a bug, but the solution here may not actually be the label (content).  "1 LEFT" maybe the correct label in the cart, versus the intended urgency that "Limited Supply" implies in the "pre-cart" experience. 
Needs further review.

**Comment by rymorgan** [comment]
@aaronjudd  Yep, sounds good!

**Comment by spencern** [comment]
@rymorgan @machikoyasuda is this closed by #2908? If not, what remains to be done?

**Comment by rymorgan** [comment]
@spencern We fixed a bug where the variant product name and quantity would not show up in the cart when there was a limited supply on that variant. What's still missing is the limited supply label doesn't' show up in cart. We need to decide what's the best way of handling that. Should it show a quantity left or should it simply show a label that says "Limited supply"? (see @aaronjudd comment above.) It's probably worth leaving this open but needs to be triaged properly.

**Comment by spencern** [comment]
I think the way it used to work was:
1. There was a set, shop-wide, or install-wide amount that meant to show "x left" in the cart.
2. The "warn at" amount was used to trigger the "Limited Supply" label, and could be any amount - completely up to the admin.

As far as the cart goes, my gut says that both labels could be shown, but if that's too crowded then perhaps the `x left` label trumps the `limited supply` label when there's not room to show both if the inventory is in a state where both labels are enabled.
