### ISSUE TITLE
User profile name changes when adding a billing address with a different name. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2812]
### Expected behavior
User profile name should stay the same. 

### Actual Behavior
When you change a user's billing address in checkout, it also changes the user profile name. 

### Steps to Reproduce the Behavior
Create an address with different billing name
See that the user profile name also changes. 

![user profile bug](https://user-images.githubusercontent.com/20409254/30227395-693bc71e-948e-11e7-890c-19c079c63998.gif)

**Comment by zenweasel** [comment]
@machikoyasuda Is there a status on this? Was this resolved by #2932? If you aren't going to be working on it could you unassign yourself?

**Comment by machikoyasuda** [comment]
Unassigning myself
