### ISSUE TITLE
As a registered user ability to sign in is inconsistent

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2815]
### Expected behavior
When I sign in I should reliably be signed in. 

### Actual Behavior
Every 3 or 4 times I sign in it gets hung up with no error. If I refresh I seem to be signed in but there's no way a user would know that. 

### Steps to Reproduce the Behavior

Create a registered user
Sign in
Sign out
Sign in
Repeat until you see the hang-up w/ no error

<img width="1437" alt="reaction_and_developer_tools_-_http___localhost_3000_" src="https://user-images.githubusercontent.com/20409254/30233042-eeb917d4-94a7-11e7-89cc-a585182bc68f.png">

**Comment by zenweasel** [comment]
I think this might be a duplicate of #2803

**Comment by rymorgan** [comment]
@zenweasel Yes, I think it is. Closing via #2803
