### ISSUE TITLE
When I place an order it flashed and empty cart page before giving the completed order page. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2816]
### Expected behavior
When placing an order it should spin then go directly the order complete screen. 

### Actual Behavior
When I place an order it flashed and empty cart page before giving the completed order page. 

### Steps to Reproduce the Behavior
Place an order
See the flashing page before order complete screen

![complete order flashing](https://user-images.githubusercontent.com/20409254/30233373-168cc8bc-94aa-11e7-8938-b5a65157275e.gif)

**Comment by kieha** [comment]
The issue here is that items are removed from the cart object and moved to the order object, so the brief period between the checkout process being over and the order being processed, the cart has no items, so the default template for the cart not having items is the empty cart page.

**Comment by kieha** [comment]
On looking into this further, it seems that the empty cart page only flashes when using Stripe as a payment method. I've tested with all the other payment methods and the loading state is shown before the completed orders page appears.

**Comment by spencern** [comment]
I paired with @kieha for an hour on this today and we figured out a solution. Pushing up a PR shortly

**Comment by spencern** [comment]
closed by #2967
