### ISSUE TITLE
Translations missing in orders admin panel

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2817]
### Expected behavior
Things should be translated in orders

### Actual Behavior
They're not

### Steps to Reproduce the Behavior
Select another language and see missing translations all over orders screen. 

<img width="1352" alt="translations issues in orders" src="https://user-images.githubusercontent.com/20409254/30233841-0e1c2e72-94ad-11e7-88b8-263055ae01a7.png">

**Comment by spencern** [comment]
@kieha Any update here?

**Comment by kieha** [comment]
Update:
- Verified that translations for this are present in the English translation file, but the translations haven’t been generated yet/added to the other files.
- I believe this is part of a larger issue of missing translations throughout the entire application.

**Comment by spencern** [comment]
@mikemurray did you happen to resolve this issue in #2919 ?

**Comment by spencern** [comment]
@kieckhafer will this be resolved by #3053 ?

**Comment by kieckhafer** [comment]
I don't think so. I think #3053 will only resolve missing translations on existing Autoform / SimpleSchema / Blaze forms

**Comment by kieckhafer** [comment]
These translations should be in the local translations file, not in the core file:

https://github.com/reactioncommerce/reaction/blob/release-1.5.0/private/data/i18n/en.json#L186-L187

**Comment by spencern** [comment]
by local do you mean in plugins?

**Comment by kieckhafer** [comment]
Yeah, they should be here: https://github.com/reactioncommerce/reaction/blob/release-1.5.0/imports/plugins/core/orders/server/i18n/en.json

**Comment by spencern** [comment]
Resolved by #3057
