### ISSUE TITLE
Report minifying app code error when docker build 

### ISSUE THREAD

**Issue by AllenBird** [reactioncommerce/reaction#2822]
### Expected behavior
I want build a reaction docker image.

### Actual Behavior
[-] Building Meteor application...

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

cfs:tempstore: updating npm dependencies -- combined-stream...
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...

Errors prevented bundling:
While minifying app code:

/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:4454:13:
Only one default export allowed per module. (1:1610334)
at Parser.pp$5.raise
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:4454:13)
at Parser.pp$1.raiseDuplicateExportError
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:2819:8)
at Parser.pp$1.checkDuplicateExports
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:2813:10)
at Parser.pp$1.checkExport
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:2712:12)
at Parser.pp$1.parseExport
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:2649:10)
at Parser.parseExport
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:5923:20)
at Parser.pp$1.parseStatement
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:1884:74)
at Parser.parseStatement
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:5835:22)
at Parser.pp$1.parseBlockBody
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:2268:21)
at Parser.pp$1.parseBlock
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:2247:8)
at Parser.pp$3.parseFunctionBody
(/root/.meteor/packages/abernix_standard-minifier-js/.2.1.0.13r4v7i++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:4235:22)
at Parser.parseFunctionBody

### Steps to Reproduce the Behavior
docker build -t

### Versions

Node: 6.10.0
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.1
Reaction branch: master
Docker: 17.06.1-ce

**Comment by aaronjudd** [comment]
Did you add any new packages, dependencies? In the past this issue has arisen around `abernix_standard-minifier` vs `standard-minifier`.  You might want to run `meteor update abernix:standard-minifier` to see if a newer version works with your build/bundle. This is a `meteor` issue though, and not likely reaction specific (as we're building on every commit...)

**Comment by zenweasel** [comment]
Closing as request for additional details not provided. Please reopen this issue if you are still having problems
