### ISSUE TITLE
Marketplace feature Completion date

### ISSUE THREAD

**Issue by coooolers** [reactioncommerce/reaction#2827]
Can I ask the contributors ... Approximately by which date the Marketplace will be finished and integrated in the Master branch?

Thanks

**Comment by spencern** [comment]
Hi Coolers, we're planning to have a release candidate by early next week and will release to master as soon as it feels stable after that.

**Comment by zenweasel** [comment]
Just for anybody finding this issue, generally opening an issue is **not** how one should try to get an answer to a question like this. This should be done through the forums or through Gitter. Thanks!
