### ISSUE TITLE
Backorder on product seems to be working opposite of how it should

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2828]
### Expected behavior
When `Allow Backorder` is true, products should show the backorder label.
When `Allow Backorder` is false, products should show a sold-out label`
### Steps to Reproduce the Behavior
- Create a product with inventory tracking.
- Make inventory 0.
- Toggle `Allow Backorder` to see badges.

### Versions
Node: 4.2.6
NPM: 5.4.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.2-ce

![basic_reaction_product](https://user-images.githubusercontent.com/4482263/30293301-e5c560cc-96ed-11e7-95a3-59bdee331a94.png)

![basic_reaction_product 2](https://user-images.githubusercontent.com/4482263/30293308-eb1b6e4a-96ed-11e7-819a-bf2919b940ab.png)

**Comment by spencern** [comment]
This may be more an issue of the way the i18n labels were implemented:
Allow Backorder is technically "Inventory Policy" on the schema.

If you read through the comments there, https://github.com/reactioncommerce/reaction/blob/marketplace/lib/collections/schemas/products.js#L179-L195

you can see that

`inventoryPolicy: true` - means enforce that inventory exists before selling
`inventoryPolicy: false` - means permit order of items that don't necessarily exist

So yes.. this is an issue, but IMO it's more of a terminology problem than a engineering problem.

**Comment by kieckhafer** [comment]
Yeah, that makes sense, seems like a terminology issue.

I feel like "Allow Backorder" is more clean and more easily decipherable than "Enforce Inventory Policy" though.

Do we "fake" it by displaying `!inventoryPolicy` as the toggle, or do do go with `Enforce Inventory Policy` or some other terminology?

**Comment by spencern** [comment]
Could change it to "Disallow Backorder?"

**Comment by rymorgan** [comment]
@spencern @kieckhafer I think it's weird UI to 'turn on' something that turns something off. I like the first idea better of fake displaying it (and annotating to any future devs what we did). If it worked correctly, what we have now will make the most sense to the user. Also, it should be "Allow backorder" (sentence case).

**Comment by spencern** [comment]
Not really sure how we got to "Allow Backorder" as the actual "label" field on the `inventoryPolicy` in the Schema is 
` label: "Deny when out of stock",`

**Comment by rymorgan** [comment]
@spencern I changed that b/c "Deny when out of stock" didn't make sense to me, nor to an end user. I think it got changed in partial pdp clean up a while ago, but without considering the whole picture of how it was functioning.

**Comment by rymorgan** [comment]
So, for now, I'd say we fake it and leave "Allow backorder" with the right function. Or "Do not allow backorder." Which, if we are leaving it backorder as the default and you have to toggle it off, might be the clearest way to go.

**Comment by rymorgan** [comment]
@aaronjudd You think "Deny when out of stock" is going to make sense to a user?

**Comment by kieckhafer** [comment]
I think PR #2380 makes it pretty clear what is happening without changing much at all.

**Comment by spencern** [comment]
@aaronjudd any strong thoughts here? I'm tempted to merge #2830 in which leaves the verbiage as it is, but flips the bit on the switch so that when it says "Allow Backorder" is on, it's permitting backorder or _not_ denying when out of stock.

I can also image that if this is the last time we touch this for a while that it could be the implementation for a while. 

There is currently an issue because we're mapping "Deny when out of stock" to "Allow Backorder" and those are opposite, so we should change something.

**Comment by spencern** [comment]
Closing as #2830 got merged. @kieckhafer re-open if I'm missing something

**Comment by vigyano** [comment]
We still see this issue in reaction 1.5.8  in Product grid page.
