### ISSUE TITLE
Basic fraud/risk analysis

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#283]
To begin this could be as simple as using IP logging to compare with billing address (ex: "warning, this order has a billing address in Brazil, but based on IP address the order was placed from Algeria").

Down the road more sophisticated scoring/rules could be valuable. (Braintree has a separate business, Kount, that does this)

**Comment by aaronjudd** [comment]
Closing, I think this going to be out of our scope for now.
