### ISSUE TITLE
Handle anonymous users with Stripe Connect

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2832]
@spencern has noted this a couple of places but it needs to get resolved somehow before Marketplace is launched.

With Stripe Connect users **must** have an email. Right now if you try to check out as anonymous you just receive the error `[Customer does not have default email]` when trying to checkout.

Probably we just need to not allow anonymous checkout in a Stripe Connect scenario.

**Comment by spencern** [comment]
A few thoughts here, this may need to be split into multiple issues. The biggest blocker having just run through a Stripe order for a non-marketplace shop is that the current implementation of Stripe requires an email address to make any charges, even if just for a single shop install. That's a regression, should be fixed prior to the `v1.5.0` release.

The issue of whether to permit "anonymous" users for a Stripe Connect checkout is a little more complicated. We should go with whatever will add the least amount of friction for a customer. My gut says that adding an option for marketplace to checkout without "creating an account"  but still requiring an email address might be the way to go. From a technical standpoint, there's very little difference, but from a customer standpoint, the gap between attaching an email to an order, and creating an account is pretty large.

I don't think that new experience is necessarily a requirement for this release.

**Comment by aaronjudd** [comment]
Just needs a variation in the registration to allow for email addition, in the exact way the orders/completed works. Should be a setting/options in shop/marketplace/checkout.

**Comment by kieha** [comment]
Notes:
- Stripe Connect requires user accounts to have emails when processing payments

Approach: 
- Check that Stripe Connect is the enabled payment method when users start checkout process/click on `Continue As Guest` button.
- If Stripe, render email form (similar to the `orders/completed` email form).

**Comment by kieha** [comment]
Resolved in #3035
