### ISSUE TITLE
Place order without paying

### ISSUE THREAD

**Issue by wathmal** [reactioncommerce/reaction#2833]
Hi, is there a way to just place the order via site so the merchant can tackle the payment manually?
Should I need to add a new plugin or is it bypassable?

There is no affordable IPGs in my country at my current level. :unamused:

**Comment by aaronjudd** [comment]
There are a number of related of issue: https://github.com/reactioncommerce/reaction/search?q=cod&type=Issues&utf8=%E2%9C%93

We also used the `example-payment-plugin` recently and built a simple "no payment" payment method for users that belong to a particular role. (I'd suggest this approach). This was easy and a quick adaption.   If you build a solution that can be re-used, we'd be happy to review a PR.
