### ISSUE TITLE
Selecting filtered orders not working properly

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#2837]
### Expected behavior

When there's a filter applied to the orders table and `select all` action performed, only the filtered orders should be selected.

### Actual Behavior

Even with a filter applied, `select all` selects all orders present in the table.

### Steps to Reproduce the Behavior

- Have a couple of orders in different states/stages
- Visit the orders dashboard (click on the orders icon in the sidebar)
- Apply any kind of filter to the orders e.g. search, paginate, filter by status
- Click `Select All` checkbox on order table header
- Observe that all the orders in the table are selected

### Versions
Node: 6.2.2
NPM: 3.10.9
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 1.13.0

**Comment by spencern** [comment]
@aanchirinah any update on this?

**Comment by joykare** [comment]
Solving this on #2768

**Comment by spencern** [comment]
@joykare if you're taking this (seems like you are in #2768) would you assign yourself to this ticket. 

@aanchirinah I'm removing you from this ticket.

**Comment by aanchirinah** [comment]
Sorry for the late response @spencern , I was tackling another issue forgot to un-assign myself when @joykare took it up to fix it
