### ISSUE TITLE
Flat Rate Shipping for multiple shops charges incorrect amount

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2838]
**To Reproduce:**
1. Setup `marketplace` branch with multiple shops using Stripe.
  a. Setup Stripe
  b. Setup Flat Rate Shipping Options for primary shop - enable at least one method that isn't free
  c. Invite and accept 2nd shop
  d. Connect stripe from 2nd shop
2. Create at least one product in 2nd shop.
3. Add a product from each shop to cart and checkout. Select a non-free shipping method. You must create an account with an email to checkout.

Observe that the amount charged for shipping _for each shop_ is equal to the shipping rate selected multiplied by the number of shops.

Not sure when this bug was introduced, but it was not present on the original marketplace payments implementation.

**Comment by aaronjudd** [comment]
@zenweasel is there an update for this issue? self-assigned 13 days ago, blocker for marketplace, should we move this to a critical-impact status?

**Comment by aaronjudd** [comment]
or should we remove this as a blocker (could go either way, but this isn't a blocker for 1.5.0) -> remember, goal for 1.5.0 is that it works, updates, and doesn't introduce regressions for a single-shop/single tenant version of RC.

**Comment by spencern** [comment]
I'm going to remove the `v1.5.0` tag here as it does not create issues for single shops as far as I'm aware. It is a critical bug for any muti-shop marketplace

**Comment by jm-wanja** [comment]
I observed that this is also happening for single shop, after adding a product to cart the `cart collection` has two shipping objects, and so the `reduce()` method that is used to calculate the shipping total (rates), iterates through both shipping objects and sums the totals of the two.

**Comment by spencern** [comment]
@jm-wanja will you please you provide clear reproduction steps for producing this in a single shop

**Comment by zenweasel** [comment]
This might be the result of the bug I introduced when creating shipping records and am fixing in https://github.com/reactioncommerce/reaction/pull/2847. I wonder if we shouldn't wait until that is resolved (hopefully today) and retest.

**Comment by jm-wanja** [comment]
**To reproduce in single shop**

1. In a single-shop set up any non free shipping method eg: flat-rate standard
2. Add a product to cart.
3. At checkout observe the shipping total to be twice the price of the shipping rate selected.

**Comment by rymorgan** [comment]
I'm seeing this too. Captured this in incognito mode with only flat rate shipping enabled. 
<img width="1227" alt="flat-rate-shipping-bug" src="https://user-images.githubusercontent.com/20409254/31188824-18779170-a8eb-11e7-94d1-d91f04619568.png">

**Comment by zenweasel** [comment]
@jm-wanja Can you or anyone test against #2847 and ensure it's not happening there? I'm not seeing it.

**Comment by rymorgan** [comment]
@zenweasel I just checked on your PR brand #2847 and it seems to be working there properly. 
<img width="1251" alt="allgood" src="https://user-images.githubusercontent.com/20409254/31201665-5521e8d6-a914-11e7-8c1b-d6bc67a270cd.png">

**Comment by zenweasel** [comment]
@rymorgan Thanks! Much appreciated.

**Comment by jm-wanja** [comment]
I have tested this on #2847 for both single shop and marketplace, and the shipping is now working correctly.
I had added a check on the `getTotalShipping()` to use successful shipments (since previously the second shipping object had an error status), should I remove that since the reason the bug was there has been resolved and close this issue? @zenweasel

**Comment by zenweasel** [comment]
Yes I think this bug was introduced by me so this issue will just get closed when that PR is merged. I don't think any additional code needs to be added.

**Comment by spencern** [comment]
#resolved by #2847
