### ISSUE TITLE
PDP/Grid When I click from the product grid to the PDP the product settings card should be open. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2848]
PDP/Grid When I click from the product grid to the PDP the product setting card should be open. 

<img width="1429" alt="screen shot 2017-09-13 at 2 10 39 pm" src="https://user-images.githubusercontent.com/20409254/30400956-6bb79e98-988d-11e7-9c99-1fd3eac927b9.png">

**Comment by kieckhafer** [comment]
@rymorgan I believe this was fixed in `release-1-5-0`, can you please re-check?

**Comment by rymorgan** [comment]
Verified fixed.
