### ISSUE TITLE
Order notes

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#285]
Administrators should be able to leave simple text notes on an order

**Comment by Gouthamve** [comment]
![screen shot 2015-04-14 at 10 20 45 am](https://cloud.githubusercontent.com/assets/7354143/7130556/176464d0-e290-11e4-8032-865ba5f45ad3.png)
This is my initial implementation of notes for the admin. Also I extended the orders schema added notes to it.
```javascript
ReactionCore.Schemas.Order = new SimpleSchema
  cartId:
    type: String
    optional: true
  history:
    type: [ReactionCore.Schemas.History]
    optional: true
  documents:
    type: [ReactionCore.Schemas.Document]
    optional: true
  notes:
    type: String
    optional: true
```
Any ideas/comments @aaronjudd @bstocks ?

**Comment by aaronjudd** [comment]
Maybe it should be [notes] array with auto timestamp and a userId, so that you could see a history?
