### ISSUE TITLE
Archive label showing when it shouldn't 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2850]
### Expected behavior
When I archive a variant, it should only label that variant as archived. 

### Actual Behavior
It labels all the variants as archived. 

### Steps to Reproduce the Behavior
Created a product with variants and variant options
Archive a variant 
Click on other variants and see that they are labeled as archived as well
*note if you click away from the page and back the labels will show properly

<img width="1380" alt="archive label bug" src="https://user-images.githubusercontent.com/20409254/30404112-d15dc6ee-9899-11e7-91b3-4c4ca555672b.png">

### Versions
Node: 4.5.0
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by zenweasel** [comment]
@rymorgan Can you verify that this issue has been fixed?

**Comment by rymorgan** [comment]
@zenweasel Yep, I just checked it. Fixed.
