### ISSUE TITLE
Inventory card opens at product details card on PDP

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2853]
### Expected behavior
The card in the PDP that I am clicking on should only open the card I click. 

### Actual Behavior
When I click on the 'taxable' or 'inventory tracking' card it also open the 'product details' card

### Steps to Reproduce the Behavior
Navigate to the PDP
Close the product details card
Click on either taxable or inventory tracking card to open
See that the product details card also opens

### Versions
![inventory card opens variant detaisl card](https://user-images.githubusercontent.com/20409254/30405186-56775566-989f-11e7-8825-931dd1439d37.gif)

**Comment by kieckhafer** [comment]
@kieha I've resolved this issue while fixing another issue, and it will be taken care of in PR #2893

**Comment by kieckhafer** [comment]
As previously mentioned, this is fixed in PR #2893

**Comment by kieckhafer** [comment]
Closed by #2893
