### ISSUE TITLE
On the PDP the sidebar should open and show where which variant or label is required

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2854]
It's a usability issue that when you publish you can't see which label is missing. When you try to publish without a label the sidebar should open and focus on the variant or variant option that is missing the label. 

If there are multiple labels missing, it should start at the top and each subsequent time you publish should open and focus on the field that is missing. 

We may also want to consider a red indicator dot on the actual PDP page in place of the info dot (for not published). That will give them two forms of feedback to guide them to correct the error. 

<img width="920" alt="lable-validation and error" src="https://user-images.githubusercontent.com/20409254/30405847-2f183824-98a3-11e7-8313-bb09f9352913.png">

**Comment by rymorgan** [comment]
@kieckhafer Here is another one. Not sure if the panel opening got in your PR or not.

**Comment by kieckhafer** [comment]
PR #2893 is open for this, coming across major `toString` issues at the moment so still jamming away trying to figure out why that's happening again.

**Comment by kieckhafer** [comment]
Closed by #2893
