### ISSUE TITLE
Docker build from tagged branches 

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2858]
When creating a tagged release (commit to master, making a new release using GitHub) our CI workflow should automatically push the successful build to Docker Hub.  I really don't think there is any need to have this logic be special to `master` or any other branch. Just any time we release/tag a branch we should build, push and label the image based on the tag name.  This might not be great if we're pulling `latest` in production, but that's not something I'd suggest we/people rely on anyways..  ie using `latest` is akin to always living in alpha state.

**Comment by aaronjudd** [comment]
Maybe this would also imply.. that we get rid of `prequel`?

**Comment by aaronjudd** [comment]
Not sure if it's helpful, but a "tag" https://developer.github.com/v3/activity/events/types/#createevent is different from a "release". https://developer.github.com/v3/activity/events/types/#releaseevent

**Comment by aaronjudd** [comment]
CircleCI in theory should support tags now (Aug 1).

https://circleci.com/changelog/#circleci-2-0-git-tags-support

`CircleCI will not run a job for a Git tag unless a tags filter is specified.

https://circleci.com/docs/2.0/configuration-reference/#tags

**Comment by spencern** [comment]
@jshimko any update here?

**Comment by jshimko** [comment]
The short answer is we either need to make sure to add the version tag to the merge commit once it's on the master branch or we just manually build/push the image after the fact like I did last time.  Either is an easy solution until I have time to refactor the CI config to use all of their new features.

The longer answer is I need to refactor the CI config to make use of Circle's new [workflows](https://circleci.com/docs/2.0/workflows/) feature (which supports parallel jobs, tag regex's, etc.).  I have that partially finished on a local branch, but I'm trying to get unburied with other more pressing blockers before I go down that rabbit hole for half a day.

**Comment by spencern** [comment]
@aaronjudd is this a blocker for our `1.5.0` release still?

**Comment by aaronjudd** [comment]
@impactmass Let's discuss, this might be a project you could take a look at...

**Comment by aldeed** [comment]
I have set up / worked on a few apps using circle workflows. I am not yet up to speed on how the current reaction build is set up, but I might be of some minimal help if you get stuck on the workflows config

**Comment by impactmass** [comment]
Started working on this with help from @aldeed. Approach is to:
- [x] Update our current circleci config.yml to use the workflow in v2 (done)
- [ ] Update the deploy job to use filters tag, to achieve this issue's goal
- [ ] Test & PR

**Comment by aldeed** [comment]
@aaronjudd @jshimko Can you think of any reason not to update the image for the "test" job to:

```
    docker:
      - image: circleci/node:8.9.1-browsers
```

The `-browsers` images have headless Chrome available for running client tests

**Comment by jshimko** [comment]
That seems reasonable to me.

**Comment by spencern** [comment]
@impactmass FYI #3629 may help out with this ticket.

**Comment by impactmass** [comment]
Thanks @spencern . #3629 actually solves the real problem of building from tagged branches.

So far, my work on #3618 will bring:
1. the circleci config.yml to use workflows which enables:
    - faster builds by running jobs within a workflow independently (except when jobs depend on another)
    - faster re-runs by allowing individual re-runs on each job
2. updates the test node image to a `-browsers` image that contains headless Chrome available for running client tests

I merged #3629 into #3618 and testing that everything works, then will open for review

**Comment by spencern** [comment]
@impactmass @ticean what's our status here? Can this be closed?

**Comment by ticean** [comment]
Yep. This can be closed now. We're pushing all builds to Docker Hub.

**Comment by aldeed** [comment]
@ticean I had worked with @impactmass on converting to Circle workflows as part of this, and that still hasn't been merged. Is that tracked elsewhere? Also, more importantly, the config still is not running `npm run lint` command, which it should, so lint errors keep sneaking in. Should I make an issue for that, or make a PR?

**Comment by impactmass** [comment]
@aldeed re: earlier work of updating the reaction repo to Circle workflows, it is being tracked in another issue. The plan is to have a similar [(template)](https://github.com/reactioncommerce/generator-reaction-next/blob/master/generators/circleci/templates/circleci/config-workflow-docker.yml) Circle config across all our repos. So I'll be making some changes to the earlier work before it gets merged (PR should come in for that tomorrow).
