### ISSUE TITLE
Need a way to link directly to specific panels and sections in the action view

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2859]
This is a feature request.

We need to be able to open a specific  panel and section in the action view from a url or link. 
This has been discussed in passing with regards to being able to link directly to orders, but the need is bigger than that.

I'm noticing this right now with the Stripe Connect integration, when a merchant is linked to the Stripe site to complete their signup, via logging in or creating an account, once they submit, we don't have a way to return them to the panel / section they initially linked from. Since there isn't a dashboard or admin route or page, we link directly to the root.

Ideally, I'd be able to send a user back to https://example.com/dashboard/shop/my-shop-settings, or any other panel in the action view given that the user has sufficient permissions. A user without sufficient permissions should be shown an access denied link and the opportunity to login I think.

This may be a combination of updates to our router and the action view.

**Comment by aldeed** [comment]
Resolved in 2.0.0
