### ISSUE TITLE
Right to left languages panel animation and css problems

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2879]
### Expected behavior
The action panel should work the same way left to right as it does right to left. 

### Actual Behavior
The action panel is missing borders and animation isn't reversed properly. When the panel animates out it should animate left to the right for right to left languages. See video, it should make sense. 

![panel animation](https://user-images.githubusercontent.com/20409254/30503953-2718817c-9a21-11e7-8087-24a55fcbc06b.gif)

<img width="825" alt="cart_completed_and_new_issue_ _reactioncommerce_reaction" src="https://user-images.githubusercontent.com/20409254/30504056-924747c6-9a21-11e7-8832-719949b2c4a2.png">

### Steps to Reproduce the Behavior
Open the panel for orders or account/user admin
Watch the panel animate in incorrectly. 
Also, notice the borders are in the wrong places

### Versions

Node: 4.5.0
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by jm-wanja** [comment]
Working on tracking why the action panel is behaving this way, I have tried altering the transform property of the action view using translate values, still trying to understand why the animation is not reversed on rtl.

**Comment by jm-wanja** [comment]
I have worked on understanding the VelocityTransitionGroup component in relation to the animation of the actionView, tried to have the animation transition property set to slideLeft for the rtl languages, but that hasn't worked out.

**Comment by rymorgan** [comment]
@mikemurray Can you give her a little help on this?

**Comment by jm-wanja** [comment]
On this [commit](https://github.com/reactioncommerce/reaction/commit/a6eb24138a0d8201555cf983ac36b6927ed35a92) I used the `querySelector()` to identify when the html classname is rtl, then set new states for the `rtl` enter/leave animation, this makes sure that the animation for right-to-left languages animates properly.

**Comment by aanchirinah** [comment]
I just experienced this bug just as described and I'm on it.

**Comment by zenweasel** [comment]
Closed via #3062
