### ISSUE TITLE
Make tests "Marketplace-aware"

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2883]
Most of our tests currently don't tests for a multi-shop scenario (I think there are actually a couple that do). Most of the tests around cart, etc. probably need to be revisited and either updated or new tests added for multi-shop.

**Comment by aldeed** [comment]
Marketplace is no longer a core plugin, and most tests now correctly test multi-shop scenarios. If you see a test that doesn't, please open a new issue identifying a specific test.
