### ISSUE TITLE
Order table previous/next buttons not working

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#2885]
### Expected behavior

The previous and next buttons on the order table pagination panel should navigate you to the previous/next page when applicable i.e. when you have more orders that the number of rows you have set for your table.

### Actual Behavior

The buttons do not work at all.

### Steps to Reproduce the Behavior

- Have 5+ orders 
- Set number of rows to 5
- Click on the active `Next` button to navigate to the next page
- Observe that nothing happens

### Versions

Node: 6.2.2
NPM: 3.10.9
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 1.13.0

**Comment by zenweasel** [comment]
Closed via #2904
