### ISSUE TITLE
Verify Graph API v2.5+ upgrade

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2886]
Review and verify Facebook  Graph API v.2.5 compatibility.  Updating as needed.

>Your App, Reaction Development, is currently accessing Graph API v2.4 which will reach the end of its 2-year lifetime on 09 October, 2017. We estimate 1 endpoint that Reaction Development calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.5 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.Visit our changelog to see the full list of changes in all Graph API versions.

**Comment by aldeed** [comment]
Closing this as I am unsure how/whether the Facebook Graph is still used anywhere in stock Reaction
