### ISSUE TITLE
[Marketplace] Cannot upload images as a guest seller

### ISSUE THREAD

**Issue by JoeyLyman** [reactioncommerce/reaction#2888]
### Expected behavior
When creating a product as a guest seller, I expect to be able to click on the default image (with the +) and upload an image. 

### Actual Behavior
Can select a file, but the image does not update on the product (the image stays as the placeholder, both on the product page and on the product grid).

### Steps to Reproduce the Behavior
Create a guest seller account (not admin), add a new product, and try to upload an image

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by kieha** [comment]
Was able to reproduce this error. Tried adding an image to a product created as an invited shop owner, and got these console errors:

<img width="407" alt="screen shot 2017-09-21 at 2 09 15 am" src="https://user-images.githubusercontent.com/19430095/30672038-aed4e510-9e72-11e7-8b34-5629dbcfd668.png">

**Comment by impactmass** [comment]
PR #2918 Referenced above is the PR for this issue .. currently going through review.

**Comment by impactmass** [comment]
resolved in #2918
