### ISSUE TITLE
[Marketplace] Guest sellers can create multiple shops

### ISSUE THREAD

**Issue by JoeyLyman** [reactioncommerce/reaction#2889]
### Expected behavior
As a guest, I expect to be able to create one shop, via my profile page and the button "Become a seller" and after creating a shop, I would expect this template area to let me know that I am currently a seller; leaving the "Become a seller" button makes me think that I currently am not a seller, even though I have a shop.

### Actual Behavior
As a guest, I can continue to go back to my profile page, and continue to click the "Become a seller" button, and create as many shops as I wish.  

### Steps to Reproduce the Behavior
Create a guest account
Go to profile
Click "Become a seller"
Go back to profile
Click "Become a seller" again

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by aaronjudd** [comment]
I think we've been discussing this should be removed, as this isn't the best path/entry into becoming a seller.  @rymorgan we've discussed, let's set a path forward for this.
@spencern re: multiple shops being created, this might be an optional setting (1 or more create?), or just prevented (easiest for now).

**Comment by spencern** [comment]
@JoeyLyman 
Thanks for reporting this, as @aaronjudd commented, this is a bit of a leftover from the way marketplace worked initially, but was actually meant to be removed.

We have a flag in the marketplace package `allowMerchantSignup` https://github.com/reactioncommerce/reaction/blob/marketplace/imports/plugins/included/marketplace/register.js#L53 that is off by default that apparently we're not checking right now. The primary path that we've been working on for onboarding new shops is for the primary shop owner to invite users to administer new shops. My gut is that that would solve some of the issues you've been experiencing with the marketplace branch, but you've probably uncovered a few real bugs as well.

If you're hoping to build a marketplace that permits any user to opt-in to becoming a seller as well, there may be a little bit of customization you'll have to do, mostly around the onboarding process once we get this `allowMerchantSignup` flag sorted out.

**Comment by JoeyLyman** [comment]
thanks guys, and thanks for all of the awesome work. 

Sounds good, and yes, I plan to have a marketplace where users can opt-in to become sellers

**Comment by impactmass** [comment]
It looks like the "Become A Seller" button is fixed on the current marketplace branch i.e it doesn't show when user is already a merchant.

But under Shop > Marketplace > Invite Owner, it's still possible to add an existing merchant's email to create a shop.... but it doesn't then use that email, it uses that of primary shop owner.

**Comment by spencern** [comment]
@impactmass that's an interesting report. Do you think that should that be a separate issue?

**Comment by spencern** [comment]
Resolved by #2969
