### ISSUE TITLE
Some files have names incompatible with Windows

### ISSUE THREAD

**Issue by zrisher** [reactioncommerce/reaction#2899]
### Expected behavior

On Windows 10, when I run `git status` within a freshly created (or freshly updated) reaction app, I should see no changes and receive "Already up-to-date." 

### Actual Behavior

Instead, after running `git status` I get this output:

```
c:\apps\..\..\some_app>git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       imports/test-utils/__mocks__/meteor/alanning
#       imports/test-utils/__mocks__/meteor/gadicc
#       imports/test-utils/__mocks__/meteor/kadira
#       imports/test-utils/__mocks__/meteor/tmeasday
nothing added to commit but untracked files present (use "git add" to track)
```

If I remove these extraneous files instead I encounter:

```
c:\apps\..\..\some_app>git status
# On branch master
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       deleted:    imports/test-utils/__mocks__/meteor/alanning:roles.js
#       deleted:    imports/test-utils/__mocks__/meteor/gadicc:blaze-react-component.js
#       deleted:    imports/test-utils/__mocks__/meteor/kadira:dochead.js
#       deleted:    imports/test-utils/__mocks__/meteor/tmeasday:publish-counts.js
#
no changes added to commit (use "git add" and/or "git commit -a")
```

### Steps to Reproduce the Behavior

On Windows, `reaction init`, `cd reaction`, `git status`.

### Versions
```
Node: 6.9.2
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.2
Reaction branch: master
```

### Root Issue

I believe this occurs because the `imports/test-utils/__mocks__/meteor` folder contains files with colons in their names, e.g. `alanning:roles.js`. The windows file system does not support colons in file names, and thus Windows users will **never** be able to match master wrt these files. I believe Git fails to create these files after pulling, and meteor creates them but drops the colon and everything following it from the name.

**Comment by aaronjudd** [comment]
We have a proposed update generally for naming conventions, still under review: https://github.com/reactioncommerce/reaction-docs/pull/241, that I hope addresses any internal instances that may be an issue for the application codebase. Input welcome.  Our goal is to run through the `marketplace` and update naming that might be incompatible.

Thanks for the research on this, it's a complicated issue -> Meteor chose this standard of using a `org:package` and they resolve this when transpiling on windows, but we needed to mock them out for jest, and had to use the package name as it's known to Meteor.   If this were a blocker for you, you could ignore or deleted that folder, and not use jest tests.  Those files are not using in the application code.

**Comment by zrisher** [comment]
@aaronjudd Thanks for the quick reply! I haven't been blocked by this issue yet, though I expect it may happen since various `git` commands cannot be run with a dirty branch, and there is literally no way to get my master branch to contain the committed files. But currently this is not a high-priority issue for me, and I'm glad progress is being made upstream.

**Comment by aldeed** [comment]
I believe the files referred to here are no longer part of Reaction. Even if they are, development on Windows is no longer officially supported. That said, anyone encountering this is free to submit a pull request with a fix.
