### ISSUE TITLE
Order filtering by status does not always refresh properly

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2902]
### Expected behavior
All orders which are true for the filter status should always show up

### Actual Behavior
After selecting one status then another, sometimes orders that are valid do not show up

### Steps to Reproduce the Behavior
1. Add some orders
1. Set some orders to different states
1. Select a filter for which no orders should show up ("Captured" is a good one)
1. Select a filter for which **some** orders should show up
1. Observe no orders show up
![order_filter](https://user-images.githubusercontent.com/72819/30623667-8de5b9ba-9deb-11e7-94f7-a2541829d08c.gif)

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: joykare-order-filtering-by-date-2359
Docker: 17.06.2-ce
```

**Comment by kieha** [comment]
Fixed by #2972
