### ISSUE TITLE
Limited Supply label in Cart should show Quantity left

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#2908]
### Expected behavior
When you have a `Limited Supply` label on a product item, it should show the `Quantity Left` in the cart correctly.

Split up this issue into a second part: https://github.com/reactioncommerce/reaction/issues/2811

Requirements to figure out:
- Should a `Limited Supply` label appear on a PDP's Variant Option selector?
- Should there be a `# left` label in PDP or Cart at all? And if so, how should that quantity be calculated (all of the Product or just that specific Variant + Variant Option combo)?

### Actual behavior

- No label on Cart at all
- `Limited Supply` label appears in two places: 1) Grid item, 2) PDP's Variant selector

**Comment by machikoyasuda** [comment]
Related: https://github.com/reactioncommerce/reaction/issues/2934

**Comment by aaronjudd** [comment]
I think this is debatable. I specifically required and designed this label to be "Limited Supply".

The goal is not one of communicating exact quantity, but of conveying percieved scarcity to a customer to encourage conversion.

**Comment by zenweasel** [comment]
@machikoyasuda What's happening on this issue? Can we close or classify as an enhancement?

**Comment by machikoyasuda** [comment]
@zenweasel Closing b/c the requirements are not done yet.
