### ISSUE TITLE
Search orders

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#291]
Search orders by:

* [ ] Date range
* [ ] Order number
* [ ] Payment State
    * [ ] Checkout (the checkout has not been completed)
    * [ ] Processing (the payment is being processed)
    * [ ] Pending (authorized but not captured)
    * [ ] Failed (card decline, etc.)
        * what about chargebacks?
    * [ ] Void
    * [ ] Completed
* [ ] Fulfillment State
    * [ ] Pending
    * [ ] Ready/Packed
    * [ ] Shipped
    * [ ] Canceled
* [ ] Status filter/search
    * [ ] Open
        * [ ] Pending/Picked (in process of being boxed)
        * [ ] Ready/Packed (in box)
        * [ ] Shipped/Processed (has label/shipping info)
            * [ ] In transit (based on shipping carrier information)
    * [ ] Completed
        * [ ] Delivered
        * [ ] Awaiting return (approved RMA)
        * [ ] Return received
    * [ ] All
    * [ ] Canceled (full order canceled)
* [ ] Customer email
* [ ] Customer name
* [ ] Ship-To Country
* [ ] By promotion

**Comment by aaronjudd** [comment]
@mikemurray I think we should just use https://github.com/aslagle/reactive-table for this, and products, customers.

**Comment by aaronjudd** [comment]
@kieckhafer we should review this original "Epic" and see how much of this is covered #1378 and #1376

**Comment by zenweasel** [comment]
I think ticket describes a completely different type of order search than what we built. This is really more of an enhancement to the order admin. It could probably still utilize the OrderSearch collection but needs an entirely different UI (multiple search boxes, date drop downs, etc).

**Comment by aaronjudd** [comment]
@zenweasel I think much of this could be built into the "filter" menu that already is being used for filtering orders. Maybe should be new issue that optimizes for the order admin.
