### ISSUE TITLE
Orders date picker responsiveness. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2910]
Also, it's not working responsively. 

**I think we should -** 
2. HIde shipping status on the phone (and maybe completely if it's not going to make it into marketplace)
3. Make the date picker dropdown fit on mobile. I'm cool with the arrow/triangle being centered?
4. Move the search text and icon to left align with orders. 

![orders-responsive-issue](https://user-images.githubusercontent.com/20409254/30617798-90cdc054-9d4c-11e7-8f91-a9ef30163b88.png)

### Expected behavior

The date picker dropdown on orders should work responsively. 

**I think we should -** 

1. Hide shipping status filter on the phone
2. Make the date picker dropdown fit on mobile. I'm cool with the arrow/triangle being centered. on both desktop and mobile to make this work. 
3. Move the search text and icon to left align with orders. 

### Actual Behavior

On mobile it gets cut off. 

![orders-responsive-issue](https://user-images.githubusercontent.com/20409254/30617798-90cdc054-9d4c-11e7-8f91-a9ef30163b88.png)

### Steps to Reproduce the Behavior

Look at the date picker on mobile. 

### Versions
Node: 4.5.0
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0

**Comment by spencern** [comment]
This is a blocker for marketplace for you @rymorgan ?

**Comment by rymorgan** [comment]
@spencern I'd say, I'd rather have this fixed then add the filter by shipping status.

**Comment by joykare** [comment]
**Status**
- PR open for this https://github.com/reactioncommerce/reaction/pull/2941
- Added design label for @rymorgan to review

**Comment by rymorgan** [comment]
Looks good for now. I think we need to do some more work on the mobile version of this, but that can be tackled in another issue.

**Comment by aaronjudd** [comment]
@rymorgan isn't this whole issue to fix responsiveness -> which really should be interpreted as "mobile", so I'd say it's worth a little more effort to fix correctly.

**Comment by aaronjudd** [comment]
@rymorgan I'm not really sure that these kind of "pop up" or "modal" interfaces will work well in mobile, is this a component that we know will be ok?

**Comment by rymorgan** [comment]
Here's the type of picker I was thinking we could use for mobile. 

![date-picker](https://user-images.githubusercontent.com/20409254/30835772-d964f708-a20e-11e7-943c-32aedb7a1bab.gif)

**Comment by spencern** [comment]
Closed by #2941 
@rymorgan please reopen if that fix does not close this issue
