### ISSUE TITLE
Inventory policy switch on variant does update options

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2911]
![image](https://user-images.githubusercontent.com/1203639/30670609-d0726a68-9e17-11e7-872e-5d873b641d53.png)
1. Toggling inventoryPolicy / "Allow Backorder" for a variant does _not_ cascade that choice into it's options

2. Options do not have a switch that will permit toggling the inventory policy. I had to edit the inventoryPolicy for the options in the database directly in order to permit backordering on the default product.

**Comment by spencern** [comment]
@kieckhafer I think this might be something that you could fix/are fixing within the work you are doing on the pdp admin right now.

**Comment by kieckhafer** [comment]
@spencern what do you think the best option is? To add the toggle to each variant, and control them each separately, or to make the toggle on the top level variant change the settings on all child variants?

**Comment by spencern** [comment]
I think the best option would be to have this either be set at the product level for all variants, or to have it on each option. To me it doesn't make sense to have it set at the variant level.

That being said, @aaronjudd has a lot more experience in designing these types of interfaces, so maybe there's a good reason that it's set where it is, and I'd defer to his expertise here.

If it's set at the product level, then I don't think it should be an option for variants/options and they should be updated to whatever the product is set to.

**Comment by spencern** [comment]
This is not fixed by #2893 

![image](http://g.recordit.co/D3IkEBCWIm.gif)

**Comment by kieckhafer** [comment]
Correct, it is not fixed in that PR, was looking for that discussion about best practice.

**Comment by spencern** [comment]
I think for now we should cascade from the variant down since that's the current UI, and then maybe create a design issue to re-design how it works.

**Comment by rymorgan** [comment]
I can see handling this with a similar idea as I suggested for handling the additional shipping fields on options. Which would be to have a checkmark or toggle to apply the backorder down the tree from the variant to your variant options. This would allow them to have the options be 'globally' controlled by the variant. Alternatively, you could have a toggle in the variant option which is defaulted off and when it's toggled on then that option's backorder status would override the variant.

**Comment by spencern** [comment]
@rymorgan I think this is something that we need to explore a bit as if we put too many checkboxes for turning on or off options I think it will start to clutter the variant a lot. I also feel these should be options that are controlled at the product level, or at the base variant (option, etc) but not at the middle variant level.

**Comment by rymorgan** [comment]
@spencern Yep, let's discuss, I think we might be saying similar things. My main goal is keeping everything as uncluttered as possible.

**Comment by spencern** [comment]
@kieckhafer - as this is a blocking issue for `1.5.0` do you think you can move forward with the functionality to cascade the decision made at the variant level to all of it's options (if any) and we can re-engineer this after the design is more ironed out?

**Comment by zenweasel** [comment]
Closed via #3004
