### ISSUE TITLE
Support Piwik in reaction-analytics

### ISSUE THREAD

**Issue by Sija** [reactioncommerce/reaction#2920]
Would you welcome contribution towards implementing such feature along Google Analytics and others?

I'd be happy to work on that if you'd find it worth having.

Thanks for a breath of fresh code in the marketplace area! 🎉

**Comment by aaronjudd** [comment]
@Sija good idea. we're reviewing the best approaches to an even more generic analytics reporting layer right now, where we can assign "connectors" pipelines to different data/analytics providers. I'll keep this open for a while as an enhancement and a reminder to myself as we document this strategy.

**Comment by jshimko** [comment]
FWIW, Segment has support for Piwik.

https://segment.com/integrations/piwik

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #22](https://github.com/reactioncommerce/reaction-feature-requests/issues/22) via [**ZenHub**](https://www.zenhub.com/)
