### ISSUE TITLE
Double lines and weird spacing in the permissions/account admin 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2921]
### Expected behavior
The cards in the action panel shouldn't have extra space or double lines. And the detail view, in general, should be working properly. 

### Actual Behavior
They have extra space and double lines. And the panel lines don't extend all the way down the page. 
![accounts](https://user-images.githubusercontent.com/20409254/30719683-40d48b62-9ed9-11e7-8043-344eeb2e8b3d.png)

### Steps to Reproduce the Behavior
Navigate to accounts. 

### Versions
Node: 4.5.0
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by rymorgan** [comment]
Also this: 

![accounts-2](https://user-images.githubusercontent.com/20409254/30721149-6b262280-9edf-11e7-9baf-18824d02e213.png)

**Comment by mikemurray** [comment]
This should function in much the same way the orders panel does where the left & right sides are scrollable independently of one another.

**Comment by zenweasel** [comment]
@rymorgan Was this issue closed by the above PR #2949?

**Comment by rymorgan** [comment]
Yea, and the leftover/underlying problems were put into another issue https://github.com/reactioncommerce/reaction/issues/2963
