### ISSUE TITLE
Better user group checking on client

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2923]
In some situations on the client, we need to determine what `group` that user is a member of for a shop other than the current. By default, the `Groups` publication, only publishes the groups for the active shop.

Let's say I have a page `/onboarding` and for "brands" who are shop owners, they should see something different from normal users. The only way to do this is to do following:

```
// Subscribe to accounts, just the be sure you're getting account info fresh
const accountSub = Meteor.subscribe("Accounts", Meteor.userId());

// Add another groups subscription just for this users group data
const groupSub = Meteor.subscribe("Groups", { shopId: user.shopId });

// The do some checks to make the user is part of the groups
...
```

It might be useful to to add/update some helpers & publications to help determine the type of user, and if they have elevated permission elsewhere.

**Comment by mikemurray** [comment]
@impactmass Was there a reason to limit the `Groups` publication to the currently active shop?

**Comment by impactmass** [comment]
At the time it was being implemented, it was about not publishing everything in the collection when it's not needed, since there is the shop switcher when managing shops . The use case you just talked about wasn't considered then. Looks like time to revisit.

**Comment by mikemurray** [comment]
The shop selector has to go away for production use, as its really only for dev. It may be moved into dev tools package at some point.

**Comment by aaronjudd** [comment]
@mikemurray that is not the necessarily the case.  A shop switch has always been part of the UX strategy for marketplaces.. ala, Google Express. It is not a development tool.

**Comment by mikemurray** [comment]
@aaronjudd I'm talking about that shop switcher in the toolbar for admins that silently switches the `shopId` for the app. It should be moved to the main navbar, and work with the router changes @spencern and I made to allow for marketplace routes.

Then the one in the toolbar would be moved to dev tools, so you can, "view this page as another shop owner", kinda like how we have the edit mode.

**Comment by aldeed** [comment]
Closing this as no longer relevant (pending rework of multi-shop support)
