### ISSUE TITLE
Variant options should have limited supply labels not just variants. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2934]
Right now only variants get a limited supply label. Limited supply labels should also apply to variant option. When the option has limit supply it should probably cascade down to the variant option vs variant and variant option. So, for example, if you have a red shoe as your variant and size 8 is in limited supply, the limited supply label should only apply to size 8 not the red shoe. I'm open to it applying to both too, but it seems like my first scenario makes more sense.

**Comment by kieckhafer** [comment]
No longer relevant in this repo. All customer facing UI is now in https://github.com/reactioncommerce/reaction/next-starterkit
