### ISSUE TITLE
New Chinese Locale

### ISSUE THREAD

**Issue by reidlai** [reactioncommerce/reaction#2935]
I am now looking for a way to implement Traditional Chinese instead of default Simplified Chinese.  Traditional Chinese is the standard Chinese variant of Taiwan and Hong Kong.  After my research of recent browser capabilities, RFC 4647 tag has already defined locale lookup priority as below:

1. zh-Hant-TW
2. zh-Hant
3. zh

My suggestion is that I'll create new PR which will rename default zh to zh-Hans and create additional language zh-Hant.

**Comment by aaronjudd** [comment]
@reidlai 👍  I would have sworn we'd implemented zh as the default before, but supporting the language variants has always been "the next item todo".  Happy to have this functionality and welcome your contributions.

**Comment by reidlai** [comment]
I nearly finished new zh-hans and zh-hant but I found that there is a minor problem.  Even changing language from English to Simplified Chinese or Traditional Chinese, the admin console still stays in English.  But there is no problem when changing to French or other default languages.  Did I miss any setting in mongo or mapping between browser locale and i18next?

**Comment by spencern** [comment]
Hi @reidlai 
Have you tried resetting the app - `reaction reset`

Another option would be to run:
Try `Meteor.call("i18n/flushTranslations")` from your browser console.

**Comment by aldeed** [comment]
There does not seem to be much point in tracking this request any longer, but if anyone needs this and would like to re-implement the `zh` split in the current Reaction release, please do so and submit a PR.
