### ISSUE TITLE
Git issues when running 'reaction init' on Windows 10 Pro 64-bit from command prompt

### ISSUE THREAD

**Issue by SebastianSativa** [reactioncommerce/reaction#2939]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Expected behavior
Regular reaction install

### Actual Behavior

CMD:

> Microsoft Windows [Version 10.0.15063]
> (c) 2017 Microsoft Corporation. Alle rettigheder forbeholdes.
> 
> C:\WINDOWS\system32>cd %userprofile%
> 
> C:\Users\Dell>reaction init
> 
> Cloning the master branch of Reaction from Github...
> Cloning into 'reaction'...
> Checking out files: 100% (2187/2187), done.
> 
> Installing NPM packages...
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: Cloning into 'C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f'...
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: git-upload-pack 'C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9': git-upload-pack: command not found
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: fatal: Could not read from remote repository.
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f:
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: Please make sure you have the correct access rights
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: and the repository exists.
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-5ec7c7d9 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-fccc9af1\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f:
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: Cloning into 'C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f'...
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: git-upload-pack 'C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7': git-upload-pack: command not found
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: fatal: Could not read from remote repository.
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f:
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: Please make sure you have the correct access rights
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f: and the repository exists.
> npm ERR! git clone C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-https-github-com-reactioncommerce-transliteration-git-114ccbd7 C:\Users\Dell\AppData\Local\Temp\npm-3340-8f64cbd8\git-cache-5d1a1845\699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f:
> npm ERR! git clone --template=C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/transliteration.git C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: Cloning into bare repository 'C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd'...
> npm ERR! git clone --template=C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/transliteration.git C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: Permission denied (publickey).
> npm ERR! git clone --template=C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/transliteration.git C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: fatal: Could not read from remote repository.
> npm ERR! git clone --template=C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/transliteration.git C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd:
> npm ERR! git clone --template=C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/transliteration.git C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: Please make sure you have the correct access rights
> npm ERR! git clone --template=C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/transliteration.git C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd: and the repository exists.
> npm ERR! code 128
> npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\_templates --mirror git@github.com:reactioncommerce/transliteration.git C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd
> npm ERR! Cloning into bare repository 'C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-reactioncommerce-transliteration-git-8d5184dd'...
> npm ERR! Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> npm ERR!
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR!
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.2\mt-os.windows.x86_32\dev_bundle\.npm\_logs\2017-09-25T19_29_27_409Z-debug.log
> 
> Error: Node modules were not successfully installed. Exiting.
> 
> C:\Users\Dell>

### Steps to Reproduce the Behavior
reaction init in a command prompt

### Versions
> Node: 8.5.0
> NPM: 5.3.0
> Meteor Node: 4.8.4
> Meteor NPM: 4.6.1
> Reaction CLI: 0.12.0
> Docker: 17.07.0-ce

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by jshimko** [comment]
We've now seen several Windows users run into a similar problem.  It appears that there's sometimes a problem with `npm` trying to install modules that get pulled from a git repo.  Can you try running `meteor npm install` from within the Reaction project directory?  (it should give the same error, but it's worth confirming just to isolate `reaction-cli` from the situation)

**Comment by zrisher** [comment]
I recall experiencing the same issue. I'm not sure what fixed it, but some combination of running `npm install`, running `meteor npm install`, and installing OpenSSH (e.g. from https://github.com/PowerShell/Win32-OpenSSH/releases) got me past it.

**Comment by jshimko** [comment]
Yep. Even though none of the git repos are being downloaded via SSH in this instance, git definitely requires you to have openssh when you clone via SSH.  So I'd definitely start there.  If that's not your problem now, it will be at some point.

**Comment by zrisher** [comment]
@jshimko OpenSSH should definitely be listed in the Windows requirements section of the docs then. As I Windows user, I never clone via SSH. The `git-credential-helper` app most of us use only works with HTTPS. It looks like SSH is baked into the meteor requirement download process?

**Comment by SebastianSativa** [comment]
Alright guys, now it works but when I run 'reaction' inside the folder, I always at some point get `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

**Comment by zrisher** [comment]
@SebastianSativa Did you see https://github.com/reactioncommerce/reaction/issues/2940? Might help you with the above error.
