### ISSUE TITLE
Out of Memory errors when running `reaction` on Windows

### ISSUE THREAD

**Issue by zrisher** [reactioncommerce/reaction#2940]
### Expected behavior

The application should start.

### Actual Behavior

Instead, I receive the following output:

```
c:\path\to\app>reaction

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ c:\path\to\app ]]]]]

=> Started proxy.
=> Started MongoDB.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

### Steps to Reproduce the Behavior

Run `reaction` inside a directory created by a successful run of `reaction init` on Windows 10. 

### Versions
```
Node: 6.9.2
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.2
Reaction branch: master
```

### Analysis

Clearly, this error is thrown when a node process runs out of memory. E.g. https://github.com/nodejs/node/issues/10137

After running the `reaction` command about 5 times on my laptop, this error stopped appearing and the app started fine (same experience as in https://github.com/reactioncommerce/reaction/issues/2820). 

However, I'm still getting the error on my desktop. When I get back there, I can continue trying to debug, though I can confirm running the process directly through node using `--max_old_space_size` up to 4 gigabytes did not solve the issue.

**Comment by spencern** [comment]
Seems like this issue might be related:
https://github.com/reactioncommerce/reaction-cli/issues/34

**Comment by spencern** [comment]
Also perhaps check this forum post: https://forums.reactioncommerce.com/t/1-4-2-fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory/532/18

**Comment by zrisher** [comment]
Hey @spencern, thanks for finding those related posts. That helped me understand that [meteor starts its own instances of Node and requires passing node args in the `TOOL_NODE_FLAGS` environment variable](https://stackoverflow.com/questions/42084472/meteor-build-running-our-of-memory/42694149#42694149). 

So to avoid this OOM issue, I'm now running reaction with: 

```
set TOOL_NODE_FLAGS="--max-old-space-size=40496" && reaction
```

I noticed 2 gigs wouldn't cut it.

That gets me past the "setting up imports" section much faster, but then it just silently quits:

```
c:\path\to\repo>set TOOL_NODE_FLAGS="--max-old-space-size=4096" && reaction

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

c:\path\to\repo>
```

I've tried setting the various Meteor & Node debugging variables to get a little more output:

```
c:\path\to\repo>set NODE_OPTIONS="--debug"

c:\path\to\repo>set METEOR_PROFILE=1

c:\path\to\repo>set METEOR_DEBUG_BUILD=1
```

But unfortunately that doesn't get me any additional output.

**Comment by spencern** [comment]
@zrisher I have seen this issue recently in our CI builds, but haven't seen it in my dev environment yet. I don't have a Windows box to test on (I'm on OSX) but does this seem to be the same issue? 
https://circleci.com/gh/reactioncommerce/reaction/8996

Can you also try pulling the latest version of our `marketplace` branch? We just updated to Meteor `1.5.2.2` and I'm curious if that does any better.

One more thing to try would be to run the `meteor` command without the `reaction` cli wrapper as the reaction-cli filters the output a little bit

`set METEOR_PROFILE=1 `
`set METEOR_LOG=debug`

and then run this instead of `reaction`
`meteor run --verbose`

**Comment by zrisher** [comment]
@spencern Thanks for your continued assistance here.

The error you linked above does look very similar to the one I was receiving, though the GC and functional details are different. I notice these change every time I receive the error, as well:

```
     START 2 linking
       START 3 computing assigned variables
       DONE 3 computing assigned variables took 13174
     DONE 2 linking took 13958               \
     START 2 linking
       START 3 computing assigned variables

<--- Last few GCs --->

  404335 ms: Mark-sweep 693.1 (735.2) -> 693.1 (735.2) MB, 798.2 / 0 ms [allocation failure] [GC in old space requested].
  405123 ms: Mark-sweep 693.1 (735.2) -> 693.1 (735.2) MB, 788.4 / 0 ms [allocation failure] [GC in old space requested].
  405920 ms: Mark-sweep 693.1 (735.2) -> 693.0 (735.2) MB, 796.1 / 0 ms [last resort gc].
  406709 ms: Mark-sweep 693.0 (735.2) -> 693.0 (735.2) MB, 788.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 07D25599 <JS Object>
    1: parseBindingList [C:\Users\Zach\AppData\Local\.meteor\packages\meteor-tool\1.5.2_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\babylon\lib\index.js:~3094] [pc=141B3F12] (this=0926D8F9 <a Parser with map 1BF8B91D>,close=223C8F11 <a TokenType with map 09423671>,allowEmpty=07D08099 <undefined>)
    2: arguments adaptor frame: 1->2
    3: parseFunctionParams [C:\Users\Zach\AppData\Local\.mete...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

So I think it's safe to assume that Meteor 1.5.2.1 has **something** going on that makes many parts of its startup process *generally* require more memory.

Our OSX-based engineers have had separate issues getting the `marketplace` branch running, which I believe are actually Meteor 1.5.2.2 issues, so moving to that is not an option for me right now. 

However, I actually solved this issue by playing around with various values for `max-old-space-size` until I found one that worked. For some values, meteor would immediately and silently exit. For others, it would immediately exit with an OOM error. And for others, it would run for a long time before exiting with an OOM error. Eventually, I tried `--max-old-space-size=1024` and it worked flawlessly. I think understanding the differences between these situations would probably require a deeper understanding of how V8 uses this flag than I currently possess. The documentation on this flag seems super spotty.

So, as confusing as all that was, at least the application is working for me right now!

As a takeaway from this process, here are some areas I believe Reaction could be improved:

* Node CLI options must be passed via the `TOOL_NODE_FLAGS` environment variable. For users unfamiliar with Meteor, this may come as a surprise. Perhaps this should be mentioned in the docs.
* Setting `max-old-space-size` may be required to run the current branch on windows 10, and you have to play around with values. Perhaps this should be mentioned in the docs.
* If the environment variable `REACTION_CLI_DEBUG` is set to (exactly) "true", the CLI will act in a more verbose manner. IMO this should be moved to a `--verbose` flag and listed in the `--help` documentation of the CLI.
* Windows Defender Real-time Protection has a habit of significantly slowing down Node processes that access a large amount of files, and meteor is definitely is doing that here. I've seen this on other projects and it manifest itself in https://github.com/meteor/meteor/issues/8803. This should definitely be mentioned in the Windows section of the Requirements page in the docs.

Let me know if you think any of those would be valuable as Issues and I'll create them.

**Comment by spencern** [comment]
@zrisher thank you for spending the time to track all of this down and give us a detailed write-up.

Regarding your specific areas that Reaction could be improved:
> Node CLI options must be passed via the TOOL_NODE_FLAGS environment variable. For users unfamiliar with Meteor, this may come as a surprise. Perhaps this should be mentioned in the docs.

I agree that this would be helpful to have in the docs. Would you open a PR to our docs with this information? @machikoyasuda can help you figure out the best place for it.

> Setting max-old-space-size may be required to run the current branch on windows 10, and you have to play around with values. Perhaps this should be mentioned in the docs.

If you can verify this with other Windows users, it seems like great information. @jshimko might be interested in this. Could be a good issue to create on the [reaction-cli](https://github.com/reaction/reaction-cli) repo.

> the environment variable REACTION_CLI_DEBUG is set to (exactly) "true", the CLI will act in a more verbose manner. IMO this should be moved to a --verbose flag and listed in the --help documentation of the CLI.

This would be a good [reaction-cli](https://github.com/reaction/reaction-cli) issue as well.

> Windows Defender Real-time Protection has a habit of significantly slowing down Node processes that access a large amount of files, and meteor is definitely is doing that here. I've seen this on other projects and it manifest itself in meteor/meteor#8803. This should definitely be mentioned in the Windows section of the Requirements page in the docs.

This would be another great PR for the docs.

**Comment by zenweasel** [comment]
Reopen this issue if passing the `TOOL_NODE_FLAGS` does not fix the memory issues
