### ISSUE TITLE
When checking out w/out being signed in, the cart should default to register. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2944]
### Expected behavior
When checking out w/out being signed in, the cart sign-in fields should default to register a user. 

### Actual Behavior
It defaults to sign in. 

### Steps to Reproduce the Behavior
Add something to cart
Go to checkout
See that the sign in is defaulted to "sign in" not register

### Versions
Node: 4.5.0
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by aanchirinah** [comment]
I will look into this issue and fix it

**Comment by spencern** [comment]
What's the status on this?
