### ISSUE TITLE
Address issue found in imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js [Opened by bitHound]

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2946]
bitHound discovered 1 LintIssue in [imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js](https://github.com/reactioncommerce/reaction/blob/04e3fe45826b743ef09c50189cf00959bc1a2596/imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js). For details go to [bitHound](https://www.bithound.io/github/reactioncommerce/reaction/blob/04e3fe45826b743ef09c50189cf00959bc1a2596/imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js).

**Comment by spencern** [comment]
Resolved by #2950
