### ISSUE TITLE
Running 'reaction' on Windows 10 Pro 64-bit results in: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by SebastianSativa** [reactioncommerce/reaction#2947]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Expected behavior
To have Reaction up and running

### Actual Behavior
Always at some point, I get:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

Bear in mind, I HAVE tried setting the environment variable NODE_TOOL_FLAGS to both --max-old-space-size=2048, --max-old-space-size=2047, --max-old-space-size=8091, --max-old-space-size=4096 - so far none of them have worked like they did when I tried in a Docker Debian image where I had the issue (only there I could not get bind mounts to work, so no access for development...)

### Steps to Reproduce the Behavior
in command prompt:
```
reaction init
cd reaction
reaction
```

### Versions
```
Node: 8.5.0
NPM: 5.3.0
Reaction CLI: 0.12.0
Reaction: 1.4.2
Reaction branch: master
Docker: 17.07.0-ce
```
For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by aaronjudd** [comment]
@SebastianSativa I have limited ability to test Windows, but there where a few build issues with Meteor 1.5.2.  I suggest testing our `release-1.4.3` branch, which contains Meteor 1.5.2.1 to see if this helps/resolves.

**Comment by SebastianSativa** [comment]
That exact branch didn't work (maybe because it doesn't exist?)

Anyway, I tried release-1.5.0 which is the version branch that DOES seem to exist, but still no luck. Constantly getting that pesky `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
`

**Comment by SebastianSativa** [comment]
Yes, I FINALLY got it working! I somehow fixed it by:

1. Reinstalling Git for Windows (making sure I checked enable symlinks option during install)
2. Adding the TOOL_NODE_FLAGS=--max-old-space-size=1024 environment variable
3. Deleting the reaction folder
4. Running `
    reaction init \
    && cd reaction \
    && reaction
 `
5. Deleting everything in %UserProfile%\AppData\Local\Temp
6. Deleting the reaction folder
7. Re-running `
    reaction init \
    && cd reaction \
    && reaction
 `
