### ISSUE TITLE
$("main").scroll() or on("scroll", ....) is not working

### ISSUE THREAD

**Issue by Falenos** [reactioncommerce/reaction#2951]
### Expected behavior
Jquery .scroll() to work

### Actual Behavior
Behaves like the event listener is not added

### Steps to Reproduce the Behavior
Just run from devTools
$("main").on("scroll", () => console.log("Hi!"));

### Versions
Node: 6.11.3
NPM: 3.10.10
Reaction CLI: 0.7.9
Reaction: 1.5.0

**Comment by aaronjudd** [comment]
Suggest you do not use jquery, as it will be removed when we remove blaze. However, to get it to work, you need to `import { $ } from "meteor/jquery"` in the client file.

**Comment by aaronjudd** [comment]
Also see: https://github.com/reactioncommerce/reaction/issues/2586 

This removed the global.
