### ISSUE TITLE
Order Table, extra empty rows added erroneously

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#2952]
### Expected behavior
Orders table should have the same number of rows as orders.
For example: If there are two orders, have just two rows displayed.

### Actual Behavior
Extra empty rows appear
![screen shot 2017-09-26 at 18 11 05 2](https://user-images.githubusercontent.com/19430074/30882097-a933969a-a310-11e7-8484-e4b52e6a8851.png)

### Steps to Reproduce the Behavior
Option 1:
- Create two orders 
- Open order dashboard, observe extra rows displayed

Option 2: 
- Have many orders and try using filter
- Observe extra rows on the order table

### Versions
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by kieckhafer** [comment]
@joykare I we set a default minimum rows number on the `minRows` prop in the `sortableTable` component. It's set to 0 if there is data in the table, so it should automatically expand to fit the correct amount of results, however, if there are 0 results, we set the `minRows` to `3`, just to make the table look better with the `No Results` message.

I'd take a look and see if somehow the results count isn't being updated correctly in the `orders` table, and the `minRows` prop is still set to `3`.

https://github.com/reactioncommerce/reaction/blob/marketplace/imports/plugins/core/ui/client/components/table/sortableTable.js#L245-L251

**Comment by rymorgan** [comment]
@kieckhafer So is that causing this: https://github.com/reactioncommerce/reaction/pull/2914#issuecomment-332239794

**Comment by joykare** [comment]
@rymorgan. scratch that, it shouldn't be the cause. Looking into it now.

**Comment by joykare** [comment]
Seen the problem: `order-count` is no longer published on order publication. Therefore its always zero.
Since this is happening on marketplace I'm re-opening this issue and solving it as a separate bug.

**Comment by spencern** [comment]
I think @zenweasel may have removed the order-count in #2855

**Comment by spencern** [comment]
Also, this is a pretty great example of something that we need automated testing for.

**Comment by kieckhafer** [comment]
I don't think that's required though. It should take the `order-count` if available, but should fallback to the `data.length` if it's not available.

**Comment by joykare** [comment]
At the moment, the order table still uses the old pub/sub way so till #2768 is done, we probably need to have some sort of count working in the meantime. @kieckhafer

**Comment by joykare** [comment]
Solving this on ticket #2768

**Comment by zenweasel** [comment]
Sorry, the fix for this was lost when I split up the Reactive Aggregate into a separate ticket. The container can just pass in `orderCount` as a prop. I'm not sure why we are trying to get it from the publication. That made sense for "PaginatedOrders" but makes no sense for this publication.
