### ISSUE TITLE
Cancel Order Workflow is confusing

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2957]
Right now the cancel order workflow is pretty confusing:

Once you click `cancel order` from the order action view, you're presented with two explicit options, and a third hidden option.

Option 1: Yes, but no restocking
Option 2: Yes, and restock.
Option 3: hidden (don't cancel, get me out of this flow)

**EDIT**: Fixed the i18n - which makes it a little better, but not good.
![image](https://user-images.githubusercontent.com/1203639/30889058-1b0ff090-a2e1-11e7-8771-d48a770c0a21.png)

I _think_ what's trying to be communicated here is a few different things that might be better served with checkboxes, or some other UI than this confirmation box.
1. Do you want to cancel this order?  - This is the primary concern here. Should be "yes" or "no" or similar language
2. Do you want to restock items? This should probably be connected to each line-item, and not a binary - restock everything, or restock nothing choice. Not sure what the default should be.

**Comment by aldeed** [comment]
Assigned @kieckhafer since I believe he's resolving this

**Comment by kieckhafer** [comment]
Will be resolved in #5158
