### ISSUE TITLE
Product prices that end in .00 are truncated and saved without the decimal

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2964]
### Expected behavior
When I set a product price to `10.00` (or any other price ending in `.00`), the product price should be saved as 10.00 in the database.

### Actual Behavior
When I set a price to `10.00`, the data is truncated and saved as just `10` inside the database.

### Steps to Reproduce the Behavior
- Change a product price to end in `.00`. 
- Look at data in database

![basic_reaction_product](https://user-images.githubusercontent.com/4482263/30930543-d8ce3b42-a376-11e7-81e2-0df5a30ebe52.png)

### Versions
```
Node: 6.11.3
NPM: 5.4.2
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: ek-updateVariantForm
Docker: 17.06.2-ce
```

**Comment by Akarshit** [comment]
@kieckhafer This would be occuring because, in JS `20 === 20.0` so as soon as the price value will be entering the JS system it would be getting truncated. That's why in most places prices are stored as `string`.

**Comment by aaronjudd** [comment]
@Akarshit In most places prices should be stored as numbers and checked for decimal and positions in formatting applied in the UI (parseFloat). 0.00 is not stored as "0" but can be stored as 0 -> as these are the same.  This should validated in the schema like this 
``` 
 price: {
    label: "Price",
    type: Number,
    decimal: true,
    defaultValue: 0.00,
    min: 0
  },```

**Comment by aaronjudd** [comment]
@kieckhafer can this issue be closed? I'm not sure I'm seeing the issue here. 10 vs 10.00 is formatting by currency (which the console isn't applying). right?

**Comment by kieckhafer** [comment]
Yes.
