### ISSUE TITLE
Some order statuses showing workflow string rather than "friendly" title

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2968]
### Expected behavior
Labels for order workflow and shipping workflow should show "friendly" statuses rather than the raw workflow status, e.g. "Processing" rather than "coreOrderWorkflow/processing".

### Actual Behavior
For Processing and Shipping, the raw workflow string is shown

### Steps to Reproduce the Behavior
1. Place an order
1. Click on the order so it's status changes to Processing
1. Observe that the workflow status is listed as "coreOrderWorkflow/processing"

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.2-ce
```

**Comment by aaronjudd** [comment]
Really this should take no longer than 20 minutes. If not, raise a hand.

**Comment by kieha** [comment]
If I'm not mistaken, this was fixed on another PR.

**Comment by zenweasel** [comment]
Yep, looks fixed. Closing.
