### ISSUE TITLE
Publish button is not consistantly displaying PDP or homepage

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#2975]
### Expected behavior
PDP and grid should always have publishing buttons (if appropriate)

### Actual Behavior
Publish button does not consistently display on PDP or grid. Sometimes it's there, sometimes it's not, although all other admin functions seem to always work regardless

### Steps to Reproduce the Behavior
- Log in as an Admin.
- Go to PDP
- Refresh, do some actions, see the button going in and out

### Versions
Node: 6.11.3
NPM: 5.4.2
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: ek-updateVariantForm
Docker: 17.06.2-ce

![basic_reaction_product](https://user-images.githubusercontent.com/4482263/30990473-39d5edf6-a456-11e7-975f-b7043ecc74bc.png)

**Comment by mikemurray** [comment]
Adding to this. While signed in, keep refreshing the homepage. Eventually, you'll get a grey screen in the middle area. The toolbars remain, but the navbar, product grid are gone.

This doesn't appear to happen for a signed out user.

**Comment by spencern** [comment]
@mikemurray Might be worth trying this with meteor `1.5.2.2` https://github.com/meteor/meteor/pull/9151 which has a fix for the bug where people were getting logged out. Not sure they'd be related, but maybe possible if we just started noticing this

**Comment by mikemurray** [comment]
@spencern meteor `1.5.2.2-rc.0` does not solve the issue, so my journey continues.

**Comment by mikemurray** [comment]
From what I can tell, part of the issue is the index route has no layout `structure` or incorrect structure in some cases, causing the grey screen.

**Comment by mikemurray** [comment]
Digging deeper into the router. Inside the "ReactionLayout" function the call to `Router.Reaction.getPrimaryShopId()` sometimes return `null` where `Router.Reaction.getShopId()` always returns the shopId.

Not sure why they would be, any ideas @spencern ?

**Comment by spencern** [comment]
Not sure why that would be either, but let's pair on this.

**Comment by mikemurray** [comment]
Fixed as part of #2971
