### ISSUE TITLE
Order dashboard corruption when viewing orders as merchant

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2976]
### Expected behavior
Order dashboard should be displayed correctly regardless of which shop you are in

### Actual Behavior
Missing values/buttons
![dumb_product](https://user-images.githubusercontent.com/72819/30996272-40956a76-a4f2-11e7-8170-f263d7aecb2d.png)

### Steps to Reproduce the Behavior
1. Create a shop, configure Stripe Connect  and create a product
1. As marketplace admin create an order with the Reaction Basic Product and your created product
1. Checkout
1. Go to the Order Dashboard and observe that everything looks fine
1. Go to your incognito window where you created the product and go to the Order Dashboard
1. Observe corrupted display

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.2-ce
```

**Comment by prinzdezibel** [comment]
Can't reproduce this behavior.

**Comment by zenweasel** [comment]
Tested and I can not reproduce either. Closing.
