### ISSUE TITLE
[Marketplace] Setting a Brand Asset results in error

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#2986]
On latest marketplace, setting a brand Image will make the whole cleint ui unusable.
The console throws: `TypeError: Cannot read property 'getShop' of undefined`
The error seems to be in this part of /core/ui/client/containers/navbar.js: (L21-24)

```
  if (shop && Array.isArray(shop.brandAssets)) {
    const brandAsset = _.find(this.getShop().brandAssets, (asset) => asset.type === "navbarBrandImage");
    brandMedia = Media.findOne(brandAsset.mediaId);
  } 
```

**Comment by janus-reith** [comment]
the `getShop() `function doesn't exist anymore in navbar.js.
`this.getShop() ` can simply be replaced with `shop`, as there is a var "shop" defined now, which will have the same value that `getShop()` returned.

**Comment by aaronjudd** [comment]
@janus-reith we tried to reproduce on the `marketplace` as of today.. couldn't. If you can, can you add steps to reproduce?

**Comment by janus-reith** [comment]
Weird, will try to clone the repo again and try without modifications - Although there were no New commits changing that file.
In imports/plugins/core/ui-navbar/client/containers/navbar.js there is the line const brandAsset = _.find(this.getShop().brandAssets, [...]
getShop is nowhere defined in that file.

**Comment by spencern** [comment]
@janus-reith can you confirm that #3030 resolves this?

**Comment by janus-reith** [comment]
Yes, the PR does exactly what I described in the first comment. Closing this as it's fixed :)
