### ISSUE TITLE
Huge resource hog on local development (Windows 10 Pro 64-bit)

### ISSUE THREAD

**Issue by SebastianSativa** [reactioncommerce/reaction#2987]
### Expected behavior
Medium to medium-high resource usage.

### Actual Behavior

Node.js server takes up ridiculous amounts of resources:

![image](https://user-images.githubusercontent.com/9719427/31058443-d4330a2e-a6f3-11e7-8573-17f29517ced8.png)

### Steps to Reproduce the Behavior

Simply run reaction locally on my windows 10 machine.

### Versions
```
Node: 8.6.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.1
Reaction: 1.4.3
Reaction branch: master
Docker: 17.06.2-ce
```

**Comment by zenweasel** [comment]
We do expect high resource usage in a development environment while it's rebuilding/watching. We are working on improving performance in the next two sprints, so let us know and reopen if you are still having problems after the release of 2.0.
