### ISSUE TITLE
Remove "Approve" step from orders workflow

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2988]
per @spencern "If you are waiting for official word, this is it"

Creating a separate issue because I think this actually touches quite a few places so want to make sure we understand the ramifications/effects and can test it separately from other changes.

**Comment by aaronjudd** [comment]
👍 Approved.

**Comment by aldeed** [comment]
@kieckhafer Not sure if your current work will resolve this, too?

**Comment by kieckhafer** [comment]
#5158 will "resolve" this by combining the `approve` and `capture` steps into a single click, i.e. Clicking `Capture Payment` will run both the `approve` and `capture` mutations. I looked into fully removing it during this PR, but the `approved` status was used in a few too many places that weren't fully related, so I didn't want to remove inside this PR. I can look into removing it completely in a separate PR after 5158 is done.
