### ISSUE TITLE
Order filters missing translations

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#2994]
### Expected behavior

Have i18n translations on the order dashboard.

### Actual Behavior

These i18n translations are no longer there/ deleted.

### Versions
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by spencern** [comment]
closed by #2995
