### ISSUE TITLE
PaypalExpress redirects to a 404

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3000]
When using PayPal express, you are redirected to a path that does not exist.

### Expected behavior
The redirect should go to `http://localhost:3000/paypal/done?token=XXX&PayerID=XXX`, which does exist.

### Actual Behavior
Redirect goes to`http://localhost:3000/reaction/paypal/done?token=XXX&PayerID=XXX`, which does not exist as the primary shop's is no longer prefixed.

### Steps to Reproduce the Behavior
1. Enable a shipping rates provider
2. Enable PayPal Express
3. Checkout
4. Get 404

### Versions
Node: 7.2.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Docker: 17.06.2-ce

### Possible Solution
PayPal express uses a server method `Reaction.getAbsoluteUrl` in here https://github.com/reactioncommerce/reaction/blob/marketplace/imports/plugins/included/payments-paypal/lib/api/express.js#L43

It's returning a URL with a prefix when it should not.

**Comment by mikemurray** [comment]
Updated `possible solution`

**Comment by spencern** [comment]
I don't doubt that this is a bug, but I was just able to checkout successfully with paypal express and got redirected correctly on `marketplace:latest`

**Comment by mikemurray** [comment]
Maybe it was fixed all stealth like. Will test again and report back.

**Comment by spencern** [comment]
This happens when there are multiple shops installed.

**Comment by mikemurray** [comment]
@spencern PR is here https://github.com/reactioncommerce/reaction/pull/3006 as I feel its sufficiently reproducible for me.

**Comment by spencern** [comment]
Resolved by #3006
