### ISSUE TITLE
Stripe should work with discounts for single shop

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3005]
See #2773 and #2763 

It appears that a bug was introduced during the Stripe Connect build out that prevents discounts working even when in a single shop instance.

**Comment by impactmass** [comment]
We have this "[TODO](https://github.com/reactioncommerce/reaction/blob/marketplace/lib/collections/transform/cartOrder.js#L208)" placed in the code about coming back to build out shop-by-shop discount.

Is that what we want to solve right now, or for now we want discount to work for just the primary shop? It looks like the focus is for single shop instance, but want to be clear.

**Comment by zenweasel** [comment]
@impactmass Yes. We only care about single shop discounts working now.
 https://github.com/reactioncommerce/reaction/issues/2763 is the multi-shop discount ticket.

**Comment by impactmass** [comment]
Okay, for now, the focus is getting discounts working for single shop installs.  [`getTotalByShop`](https://github.com/reactioncommerce/reaction/blob/marketplace/lib/collections/transform/cartOrder.js#L202) is where the change needs to happen.  

Before the total object is returned we can have a check to confirm that only one shop is featured in the order. Then apply any discount set. If more than a shop is in the featured in the order, for now, continue without discount. cc @spencern

**Comment by impactmass** [comment]
PR opened #3041

**Comment by spencern** [comment]
resolved by #3041
