### ISSUE TITLE
Validate product handle on publish

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3007]
### Expected behavior
Product handle should be unique.

### Actual Behavior
Product handle can sometimes be identical to another product's handle.

### Steps to Reproduce the Behavior
1. Create a product
1. Set the title to "Test Product"
1. Click Publish
1. Observe error "label is required", don't fix it
1. Look at the product, and see the slug say "test-product"
1. Create another product
1. Set title to "Test Product"
1. Click publish
1. Observe error "label is required", don't fix it
1. Look at the product, and see the slug say "test-product"
1. Fix the "label is required" error on the variants of both products and publish
1. Now 2 products have the same slug

This is probably an issue with the wrong handle making into a revision control document, that once published, will update the product with the duplicated handle.

### Versions
Node: 7.2.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.1
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.2-ce

**Comment by spencern** [comment]
Is this similar to #2831 ?

**Comment by Akarshit** [comment]
@spencern Yes it is similar, the only difference is on the cause side. That was happening because uniqueness of handle was not being checked across products(which has already been fixed). 

This issue is for tracking when the cause is because of the `revisions` flow.

**Comment by mikemurray** [comment]
@spencern what @Akarshit said :)

Yes, they similar. This issue points out the fact that it's probably a revision control issue with not validating that the handle is not already taken before publishing.

**Comment by kieckhafer** [comment]
@mikemurray is this taken care of by your new products admin work?
