### ISSUE TITLE
Broken translations when using data-i18n attribute

### ISSUE THREAD

**Issue by Falenos** [reactioncommerce/reaction#3011]
### Steps to Reproduce the Behavior
At the marketplace branch:
Inspect element on "profile" section 
Change from devtools an element with the data-i18n attribute
You can see that the value changes in the browser.

I think this functionality is provided by the jquery-i18next package.
In artlimes, all these translations are broken but the ones with i18next.t(...) seem to function correctly.

### Versions
Node: 6.11.3
NPM: 3.10.10
Reaction CLI: 0.7.9
Reaction: 1.5.0
marketplace branch

**Comment by spencern** [comment]
We did remove the non-meteor version of jquery recently 
https://github.com/reactioncommerce/reaction/pull/2948 you should still be able to use jquery with `import { $ } from "meteor/jquery"`

**Comment by Falenos** [comment]
Thanks Spencer, will test and get back to you about it

**Comment by zenweasel** [comment]
@Falenos Can you confirm if this issue has been fixed for you?

**Comment by stevaras** [comment]
@zenweasel Probably gets solved by https://github.com/reactioncommerce/reaction/pull/3068

**Comment by zenweasel** [comment]
@Falenos Should I close for now and you can reopen if it's still happening?

**Comment by stevaras** [comment]
@zenweasel Yeap for sure :)
