### ISSUE TITLE
Errant error indicator dot on products on the grid. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#3014]
### Expected behavior
If a product doesn't have an error I shouldn't see an error indicator on the product grid. 

### Actual Behavior
When I refresh a store with a publish/visible product with no errors I see an error indicator dot. 

![published-shows-error](https://user-images.githubusercontent.com/20409254/31139811-8c1f8e9e-a827-11e7-9e4d-bdc82d48828a.png)

### Steps to Reproduce the Behavior
Created a product 
Navigate to the product grid 
Refresh 
See that the product shows an error indicator

### Versions
Node: 4.5.0
NPM: 
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.1
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by zenweasel** [comment]
Yeah, I think this is sort of a duplicate of #2868. (that ticket talks about marketplace and this is all shops)

So I think what we are going to do for now is just remove the red dots and revisit this at a later time.

**Comment by rymorgan** [comment]
Redundant, closing.
