### ISSUE TITLE
show placeholder / default text in PDP social settings

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3016]
### Expected behavior
Default text should show in social settings fields on PDP

### Actual Behavior
No default text shows, you don't see it until you actually click the share button

![basic_reaction_products](https://user-images.githubusercontent.com/4482263/31141843-5c51924c-a82d-11e7-9d2a-960017f502e6.png)

**Comment by zenweasel** [comment]
Closed via #3087
