### ISSUE TITLE
Order Processing - dashboard widgets

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#302]
Add widget graphs for Orders. Shoot for 5.
-  Aging
-  Stages
-  Shipping method
-  Order Values (Avg, Sum,  Stages)
-  At risk (auth expires)

**Comment by rymorgan** [comment]
@aaronjudd Not sure I get what this is. Can you provide more  details?

**Comment by aaronjudd** [comment]
KPI Graphs...  this issue is basically, "add graphs".  It should be replaced with our designs for inline, contextual, actionable data representation.

**Comment by rymorgan** [comment]
@aaronjudd Gotcha, that's what I suspected.
