### ISSUE TITLE
[Marketplace] WIth Single Shops, the eMail verify Link for registrations is wrong

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#3028]
I get a link in the form of http://domain.tld//account/profile/verify?email=email@provider.tld
I guess that the double slashes occur because of some error in the shop prefixing.

**Comment by spencern** [comment]
@janus-reith do you think this is the same as https://github.com/reactioncommerce/reaction/issues/2623?

**Comment by janus-reith** [comment]
Yep, didn't notice that one.
