### ISSUE TITLE
review / update all dependencies

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3029]
Task to run `ncu -a` and update all dependencies when we begin using Meteor 1.6.

Right now, you can't just force update/install because there is varying versions of node deps/engines involved in some of our dependencies, which should be resolved with Meteor 1.6, as this is also an update to Node v8.x

**Comment by spencern** [comment]
ncu requires: https://www.npmjs.com/package/npm-check-updates

**Comment by aaronjudd** [comment]
Closed by https://github.com/reactioncommerce/reaction/pull/3615
