### ISSUE TITLE
Empty cart flashing when I register a new user

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#3036]
### Expected behavior
When I register a new user, I should stay on the same page, see a spinner (if there is a delay or pause) and not see a flashing empty cart. 

### Actual Behavior
When I register a user in checkout I hit submit and an empty cart screen flashes. 

![jujabxxuuq](https://user-images.githubusercontent.com/20409254/31205064-f6ecfde0-a923-11e7-84f9-b5badd03e918.gif)

### Steps to Reproduce the Behavior

Using an incognito window checkout as a guest 
See that an empty cart flashes. 

### Versions
[ALL]-1.5.0-rc.1

**Comment by rymorgan** [comment]
I confirmed it's not flashing anymore, but it's a jarring experience for small action like registering a user to have a spinner happen on the whole page. If a spinner is necessary it should happen on the component level.

**Comment by aaronjudd** [comment]
@zenweasel @spencern can we review this again, not sure that this PR to fix this actually does anything.

**Comment by zenweasel** [comment]
@aaronjudd Are there steps to replicate this in core as I cannot using the instructions in this ticket?

**Comment by Akarshit** [comment]
No "empty card flashing" screen when registering user. 
Checked in `release-1.8.0`
