### ISSUE TITLE
Inconsistent label spacing on pdp

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#3042]
### Expected behavior
Labels should have consistent spacing 

### Actual Behavior
Labels have inconsistent spacing. 

![spacing-bug](https://user-images.githubusercontent.com/20409254/31247576-ddf456ba-a9c5-11e7-9883-9a0d0500a9f4.png)

### Steps to Reproduce the Behavior
Create a new product with both backorder and archived labels. 

### Versions
Node: 4.5.0
NPM: 
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.1
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by aanchirinah** [comment]
@rymorgan , So I was able to get label spacing to appear as the image below,
![screen shot 2017-10-11 at 4 29 16 pm](https://user-images.githubusercontent.com/28437833/31450483-726d1e46-aea1-11e7-9b1f-466b51baae76.png)
Is this acceptable?

**Comment by aanchirinah** [comment]
@rymorgan should there be space too for the variant available options labels too?

**Comment by rymorgan** [comment]
@aanchirinah Yes, we should do the same for variant options.

**Comment by zenweasel** [comment]
Closed via #3088
