### ISSUE TITLE
Dashboard and Console enhancements

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#305]
- [ ] move view-specific tools into a new <toolbar> template (create, grid,list,etc)
 - [ ] persist on refresh
 - [x] update console toggle icon, directional
 - [ ] optional footer, sidebar placement
 - [ ] default bottom nav on mobile
 - [ ] Top KPI mini-graphs / realtime inside of app card
 - [ ] sort/conceal "not enabled" apps
 - [ ] move / pin app card
 - [x] only display cog when settings
 - [x] mousepointer on navbar elements
 - [ ] remove cog from console drawer
 - [ ] line in dropdown differentiating apps and actions

**Comment by aaronjudd** [comment]
- only display cog when settings
- mousepointer on navbar elements
- remove cog from console drawer
- line in dropdown differentiating apps and actions

**Comment by bstocks** [comment]
Related to this: 

The google analytics package can no longer be disabled and yet when it's not configured, the error message reads "Google Analytics Property is not configured. Configure now or disable the Google Analytics package."

Is the google analytics package supposed to be disable-able?

**Comment by aaronjudd** [comment]
I can enabled, disable it.  By default, it doesn't start enabled anymore.

**Comment by bstocks** [comment]
Hmm, I pulled the latest version and it is still set to autoEnable and can I can't disable it

**Comment by aaronjudd** [comment]
Oops, didn't push that, just updated.

**Comment by bstocks** [comment]
thanks!

**Comment by aaronjudd** [comment]
![pasted_image_4_17_15__5_31_pm](https://cloud.githubusercontent.com/assets/439959/7213156/2e9bdb32-e52a-11e4-8a2f-1200fe86d068.png)

**Comment by aaronjudd** [comment]
@mikemurray As we make ui updates,  let's use this issue to track updates to the dashboard (like in https://github.com/reactioncommerce/reaction-core-theme/commit/754f294ee5023345c3ac366fba87718cbbc1408e )

**Comment by aaronjudd** [comment]
This issue is now out of date, and mostly irrelevant. Closing.
