### ISSUE TITLE
Create admin option to force all anonymous users to provide an email address on checkout

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#3054]
As it currently stands, when checking out as an anonymous user, the user is not required to provide an email address at any point in the checkout process, and on `order/completed`, they are requested to provide an email, but this is optional.

However, in issue #2832, users are required to have an email when checking out with Stripe Connect, thus it becomes a problem for anonymous users to complete the checkout process. This is solved by PR #3035, where the first step for a user who opts to `Continue as guest` and not create an account, is that they provide an email address before they continue.

However, we need to add this as an option that a shop admin can use for any checkout, i.e. have an option in the shop settings that when set, forces anonymous users to provide an email address when checking out.

Possible solutions:

- In the shop settings, a checkbox below/as a sub-option of `Allow Guest Checkout` along the lines of `Guest Checkout Requires Email` that implements this functionality.
- As an extension of the implementation of `Allow Guest Checkout`, add this functionality.

**Comment by aldeed** [comment]
Closing this because in 2.0 you cannot create an order without an email
