### ISSUE TITLE
Currency dropdown displaying multiple values and not working

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3060]
![image](https://user-images.githubusercontent.com/1203639/31305590-9edfd09a-aafa-11e7-8e22-0a89e8934180.png)

This was introduced when we merged #2979

**Comment by kieckhafer** [comment]
This is how it's saved in the database, so it's not "wrong", per se. Perhaps we just need to split it and display USD only?

@mikemurray mentioned it's saved this way in the `Countries` collection, which then sends it to the shops.

![screenshot_10_9_17__10_24_am](https://user-images.githubusercontent.com/4482263/31350474-2aeb3fc4-acdc-11e7-91de-1ca59fc6da47.png)

**Comment by spencern** [comment]
@kieckhafer thanks for digging this up. @lcampanis had mentioned similarly in his PR. If we have been splitting the currencies, a la `currency.split(",")[0]` up to this point, I guess it's not a regression to continue to do that, but we also should figure out how we'd like to display/save currencies for countries that have multiple currency codes. I'll create another issue for this particular task (which may or may not be important) after doing another review of #3061

**Comment by aaronjudd** [comment]
`currency.split(",")[0]` is fine for now.  I wrote it this way because the vast majority doesn't use anything but that first indicator.. seems like an issue to tackle in future (and the future isn't now). Do we have a case where someone actually needs multiple currencies yet?

**Comment by spencern** [comment]
Not that I'm aware of, should I just leave that issue off the table until someone requests it?

**Comment by spencern** [comment]
Resolved by #3061
