### ISSUE TITLE
[Marketplace/release-1.5.0] Changing the base language (to german) breaks translations on the Orders Panel

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#3063]
If I switch my base language to german, and the display language in the dropdown to german aswell,
the Orders panel appareantly does not use fallbacks for the order status and the search placeholder.
E.g. it shows coreOrderWorkflow/processing instead of Processing.

If I set the base language to english, and the display language to german, it properly shows fallbacks for these fields, like "Processing".

Setting the base language to german, but the display language do english also works as expected.

Im on the lates commit of release-1.5.0 branch and have this pr merged already:
https://github.com/reactioncommerce/reaction/pull/3057

**Comment by janus-reith** [comment]
Just tried with Español, same isssue, so not related to german,

**Comment by spencern** [comment]
@janus-reith Thanks for reporting!

I think this may be an issue because we have not run some of the translations added through our `LingoHub` account which is the service that provides translations for newly added i18n definitions.

**Comment by janus-reith** [comment]
Well this would explain the missing translations that show an english string instead, but what about those that show the bare translation key?

**Comment by spencern** [comment]
Good question. @kieckhafer thoughts?

**Comment by kieckhafer** [comment]
I don't believe this is "broken", we just might need to update the fallback text.

The orders panel has new translations, and I don't know if they've been translated to all the languages yet.

The placeholder is `coreOrderWorkflow/processing` or `coreOrderWorkflow/new`, etc, it's not `Processing` or `New`.

We'll just need to update the `label` here, (if we want): https://github.com/reactioncommerce/reaction/blob/release-1.5.0/imports/plugins/core/orders/client/components/orderTableColumn.js#L110
https://github.com/reactioncommerce/reaction/blob/release-1.5.0/imports/plugins/core/orders/client/components/orderTableColumn.js#L121

**Comment by spencern** [comment]
I think this should be fixed by our i18n fixes (#3072, #3071) we pushed into `release-1.5.0` last night. @janus-reith can you check to see if these issues have been resolved?

**Comment by janus-reith** [comment]
Fixed, thank you :)
