### ISSUE TITLE
Order notification email should reflect Multi-shop

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3065]
It's possible I am missing it somewhere, but the "Order Notification" email (and others) needs to be modified to be reflect multi-shop. I did not find anything that mentioned this in https://github.com/reactioncommerce/reaction/issues/2219

Hopefully could repurpose the components, etc. from the "Completed Order" conversion.

**Comment by zenweasel** [comment]
@rymorgan Do we have a design for what a multi-shop version of the current notification email should look like? Probably needs design and review for terminology, etc.

**Comment by rymorgan** [comment]
@zenweasel No, I don't, but I can mock something up quickly for transactional emails. As far as the rest, I know we've updated some, mostly around inviting new shops and shop managers. I'm not sure what other emails need to be updated. We should probably test all of them, which I can do but have not been able to do b/c I can't get any email method working. I'll try and get someone to help me with that. I've also noted this as one of the tasks for cleaning up the marketplace UX in general.

**Comment by rymorgan** [comment]
@zenweasel -- here's a variation on what we currently use for confirmation emails showing multiple stores. 

![multistore-order-confirmation](https://user-images.githubusercontent.com/20409254/31469594-110e6f56-ae97-11e7-9b43-eeb5342bc532.png)

**Comment by aldeed** [comment]
Closing as an issue specific to marketplace setups, which is no longer a core feature
