### ISSUE TITLE
Shipping data area is blank on Cancelled orders

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3075]
### Expected behavior
Shipping area should do one of the following on a cancelled order (or really any order), if there is no data in the shipping area.

1. Be removed
1. Show a "No shipping info" message

### Actual Behavior
There is a blank box where the shipping data should be

### Steps to Reproduce the Behavior
As an admin, cancel an order before doing any shipping status updates.

### Versions
```
Node: 6.11.3
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.2
Reaction: 1.5.0
Reaction branch: release-1.5.0
Docker: 17.09.0-ce
```

![reaction](https://user-images.githubusercontent.com/4482263/31400063-29d13324-ada3-11e7-856b-455ef17750f8.png)

**Comment by iakhator** [comment]
@kieckhafer , Can You buttress more on how the shipping info should look like or be?

**Comment by kieckhafer** [comment]
@iakhator the info looks fine, if it's available. 

The change we need to make here is if there is no shipping status, we need to put a message there to say that, instead of the blank box.

A simple "No shipping information available" would suffice.

**Comment by iakhator** [comment]
alright.
