### ISSUE TITLE
Cart should be broken down by Shop during shopping

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3096]
Breaking this apart from #2700.

Customers should see which items are being purchased from which shop while Shopping (i.e. Cart Drawer and anywhere else it appears)

**Comment by spencern** [comment]
This is part of the `performance` epic as it's part of the conversion from Blaze to React

**Comment by aldeed** [comment]
Marketplace is no longer a core product, and breakdown by shop could be implemented on the storefront side in 2.0.0
