### ISSUE TITLE
Install Script error on Ubuntu 14.04

### ISSUE THREAD

**Issue by dofrance** [reactioncommerce/reaction#310]
curl -L http://getrxn.io/installreaction | /bin/sh
....................................
/bin/sh: 64: Bad substitution

**Comment by aaronjudd** [comment]
Updated script, please give a shot now.  I tested the update on barebones ubuntu:wheezy docker instance, was able install and run the server.

**Comment by aaronjudd** [comment]
```curl -L http://getrxn.io/installreaction | /bin/bash```

looks like `sh` works fine on osx because it's choosing `bash`, but ubuntu uses `dash` when using `/bin/sh`.

I'll see if I can get it compatible with sh.

**Comment by aaronjudd** [comment]
Updated to posix compatible. Should be ok now.

**Comment by dofrance** [comment]
Yes, it work nice!
