### ISSUE TITLE
Users should be able to "zoom" into a high-res image on the PDP

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3100]
When browsing the PDP, users should be able to click, over or pinch to zoom on the currently active product image.

**Comment by zenweasel** [comment]
Can we get a little more detail on how exactly this should work? Are we just using the original unresized images and just showing it in a modal on the desktop?

**Comment by spencern** [comment]
Ideally we should lazy load the high-res image when it's requested. I don't think we should be loading all high-res images when the PDP loads, especially on mobile devices.

I think a simple react component such as this https://github.com/ethanselzer/react-image-magnify could potentially work, but I have not evaluated this particular component for size or efficiency.

 https://ethanselzer.github.io/react-image-magnify/#/

**Comment by Akarshit** [comment]
Did a PR for this at #3343
