### ISSUE TITLE
PDP shows "pointer" cursor for non-admins when hovering over PDP image

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3101]
The PDP _should_ show a cursor for the admin, as there is an action that the admin can take by clicking on the PDP image gallery.

The PDP _should not_ show a cursor for the customer (until #3100) because there is no action that can be taken by clicking.

Related: #2469

**Comment by zenweasel** [comment]
@codejockie Remember to assign an issue to yourself if you are working on it so no one else starts working on it.

**Comment by codejockie** [comment]
That was an oversight @zenweasel . Won't happen again. Thank you.
