### ISSUE TITLE
"Failed to get currency exchange rates" error in server

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3103]
I get the `Failed to get currency exchange rates` error even though I don't have an Open Exchange Rates app ID set up. If I don't have that set up it should just not be fetching rates and not giving me that error.

### Steps to reproduce

1. Start Reaction without an open exchange rate ID loaded (e.g. don't use `reaction.json`).
1. Navigate around Reaction some (click on products, etc)
1. Observer the errors in the console

**Comment by codejockie** [comment]
@zenweasel any way to reproduce this issue?

**Comment by zenweasel** [comment]
Issue updated with steps to reproduce

**Comment by codejockie** [comment]
Issue fixed.
