### ISSUE TITLE
Order workflow: uniqueItem._id undefined

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3104]
Order created:  shippo + stripe + avalara.

Single item, single shop.  Seen in browser console when clicking the order in the order dashboard.

### Expected behavior
No errors

### Actual behavior

<img width="1668" alt="basic_reaction_product" src="https://user-images.githubusercontent.com/439959/31559279-eed2cfee-b004-11e7-86dc-a7aa4742713e.png">

### Steps to test
1. Login as admin
1. Enable Shippo shipment method
1. Enable Stripe payment
1. Enable Avalara Tax calculations
1. Place an order
1. Go to the Order Dashboard
1. Click on the order you placed
1. Observe the error

###
Node: 6.11.1
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.16.2
Reaction: 1.5.0
Reaction branch: master
Docker: 17.09.0-ce

**Comment by codejockie** [comment]
@aaronjudd please could you throw more light into this?

**Comment by zenweasel** [comment]
I think if you run through an order with Stripe, Shippo and Avalara enabled you should see that error.

**Comment by zenweasel** [comment]
I updated this ticket to fit the format

**Comment by codejockie** [comment]
@aaronjudd I could not reproduce this bug using the steps provided. Can you give more details about how to reproduce this?

**Comment by zenweasel** [comment]
I was just able to reproduce this today doing this. My instinct is that Avalara is the wild card here.

1. Login as admin
1. Create a new product
1. Set up payment as Stripe and Flat Method and Avalara enabled
1. Checkout pushing the new product
1. Go to the order dashboard
1. Observe this error
![cart_completed](https://user-images.githubusercontent.com/72819/32764406-37d29a86-c940-11e7-98f9-0407d0a044cd.png)

**Comment by codejockie** [comment]
This bug also made the Invoice section of the order not to be displayed.
