### ISSUE TITLE
Application not responding error

### ISSUE THREAD

**Issue by jeremyroberts0** [reactioncommerce/reaction#311]
I just created a new store and am getting an "Error 502 - Application Not Responding" error.  I've waited about an hour in case it took some time to provision / boot my instance, still no luck.  Here's the URL in question:
https://xibn2z8z.reactioncommerce.com/

**Comment by bstocks** [comment]
Hi @jeremyroberts0 - we are currently undergoing some updates to our server, stay tuned and we'll have things back up soon.

**Comment by jeremyroberts0** [comment]
Sounds good, thanks for the quick follow up!

**Comment by bstocks** [comment]
ok, it looks like your shop instance is now running. We are still working through some issues with more patches to come, but go ahead and give it a try now.
