### ISSUE TITLE
Login Url Redirection

### ISSUE THREAD

**Issue by lovetostrike** [reactioncommerce/reaction#312]
It could be nice to have the unauthenticated user redirected to a login page and take him/her to the requested url afterwards. For example,

http://reaction/dashboard(unauthenticated) -> http://reaction/login -> http://reaction/dashboard(logged-in)

**Comment by aaronjudd** [comment]
That would be pretty easy to do (we do it on reactioncommerce site for example).  My question would be is that the natural flow, or do most shoppers who login, just want to be logged for checkout ease, not necessarily to go to the dashboard.  I tend to login to shops where I know I have an account, just so my info is preloaded during checkout.

**Comment by lovetostrike** [comment]
I think the redirection to login page is only for required pages, that is dashboard, wishlist, order history etc like you said. Showing a separate access denied page can be disrupting for users. Any other pages should function as before.

**Comment by lovetostrike** [comment]
I saw the login-required pages are redirecting in v0.5.x. Should we close this now?

**Comment by aaronjudd** [comment]
Yes, with the exception of issue #348, where there are multiple login instances on a page.  Since that's a larger issue I think it makes sense to close this issue.
