### ISSUE TITLE
Order shipped email total undefined

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3120]
Order Total is `undefined` in the order completion email.  

![inbox__10_099_messages__164_unread_](https://user-images.githubusercontent.com/439959/31642104-0f9ea612-b29e-11e7-885d-8b4a2191de4b.png)

```
Node: 6.11.1
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.17.1
Reaction: 1.5.1
Reaction branch: release-1.5.1
Docker: 17.09.0-ce
```

**Comment by spencern** [comment]
Resolved by #3153
