### ISSUE TITLE
Make all `Meteor.Error` calls consistent

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3122]
This is just a "cleanup" task

`Meteor.Error` should be `Meteor.Error("short-message", "Long message with more detail");`

Currently we have a hodgepodge of different styles. Specifically we want to eliminate versions that use a number instead of a message as these don't really convey any helpful info.

**Comment by codejockie** [comment]
@zenweasel what about ones like this `Meteor.Error(`Undefined conditional operator ${operator}`);` with just a single argument?

**Comment by codejockie** [comment]
In the case of this style `Meteor.Error(403, "Access Denied");` would it be appropriate to remove the number like this: `Meteor.Error("Access Denied");` passing in just one argument?

**Comment by zenweasel** [comment]
No. There should always be two values, short string and long string. Sometimes the long string won't add a lot of value over the short one but they should still be there. We should be adding more detail to those messages when we can as long as we are being sensitive to what information we expose to the client.

**Comment by codejockie** [comment]
Resolved by #3195
