### ISSUE TITLE
Image names with spaces don't display in the homepage

### ISSUE THREAD

**Issue by bayareacoder** [reactioncommerce/reaction#3137]
### Expected behavior
Image with filename that has space(s) in it, when added from PDP, shows on PDP but not on product grid 

### Actual behavior
It should show

### Steps to reproduce the behavior
1. Login as admin
2. Add product and create product variant
3. Upload image from filename with one or more spaces in it & publish
4. See that it shows on PDP page but not on product grid
5. Change filename that it has no spaces
6. On PDP page, delete existing image. Add image w/o spaces in filename. Publish
7. Go to product grid and see that it shows

Note: this bug existed before. it is due to non-URL escaping of filenames in template (Issue #448) Seems to happen again...

### Versions
Mac OS High Sierra
Node: 6.11.4
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.18.0
Reaction: 1.5.1
Reaction branch: master
Docker: 17.09.0-ce

**Comment by codejockie** [comment]
I also noticed it's regardless of the image file name, even with file names without spaces it doesn't show after reproducing.

**Comment by spencern** [comment]
Resolved by #3157
