### ISSUE TITLE
Background image, fonts, colors etc.

### ISSUE THREAD

**Issue by mursalal** [reactioncommerce/reaction#3138]
Hello! Sorry for such a simple question anyway, can someone link me to how set fonts, background images, colors and so on? I didn't find in Docs.

**Comment by zenweasel** [comment]
Hi @mursalal ,

You can find that info here: https://docs.reactioncommerce.com/reaction-docs/master/creating-a-theme.

You should also try our [Gitter room](https://gitter.im/reactioncommerce/reaction) if you have further questions.
