### ISSUE TITLE
Refactor ReactionCore.registerPackage schema

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#314]
Refactor the `ReactionCore.registerPackage` package schema to be more structured.
Only `registry` is to be published to general client, while others (`settings`,`permissions`) would be published when admin.

```coffeescript
ReactionCore.registerPackage
  name: 'reaction-paypal' # usually same as meteor package
  autoEnable: false # auto-enable in dashboard
  settings: # private package settings config (blackbox)
    mode: false
    client_id: ''
    client_secret: ''
  registry: [
    # all options except route and template
    # are used to describe the
    # dashboard 'app card'.
    {
      provides: 'dashboard'
      label: 'PayPal'
      description: 'Accept PayPal payments'
      icon: 'fa fa-paypal'
      priority: '2'
      group: 'paypal'
    }
    # configures settings link for app card
    # use 'group' to link to dashboard card
    {
      route: 'paypal'
      provides: 'settings'
      group: 'paypal'
    }
    # configures template for checkout
    # paymentMethod dynamic template
    {
      template: 'paypalPaymentForm'
      provides: 'paymentMethod'
    }
  ]
  # array of permission objects
  permissions: [
    {
      label: 'Pay Pal'
      permission: 'dashboard/payments'
      group: 'Shop Settings'
    }
  ]


```

I'd like to attempt to resolve #53, #308, #178, #136, #245 as well in this refactor.

**Comment by dofrance** [comment]
Uvvâ‎Adct                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 e.                                                                                                                                                                                                                                         From: Aaron JuddSent: Tuesday, February 10, 2015 2:38 AMTo: reactioncommerce/reactionReply To: reactioncommerce/reactionSubject: [reaction] Refactor ReactionCore.registerPackage schema (#314)Refactor the ReactionCore.registerPackage package schema to be more structured.
Only templates need to be published to general client, while others (settings,dashboard) would be published when admin.

ReactionCore.registerPackage
  name: 'reaction-paypal'
  provides: ['paymentMethod']
  version: "0.3.1"
  settings: 
    route: 'paypal'
    mode: false
    client_id: ""
    client_secret: ""
  dashboard: 
    label: 'PayPal'
    description: 'Accept PayPal payments'
    icon: 'fa fa-paypal',
    priority: '2'
    hasWidget: true
    autoEnable: false
  templates: [
    template: "paypalPaymentForm"
    provides: "paymentMethod"
  ]
  permissions: [
    label: "Pay Pal"
    permission: "dashboard/payments"
    group: "Shop Settings"
  ]

I'd like to attempt to resolve #53, #308, #178, #136, #245 as well in this refactor.

—Reply to this email directly or view it on GitHub.

**Comment by dofrance** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Aaron JuddSent: Tuesday, February 10, 2015 2:38 AMTo: reactioncommerce/reactionReply To: reactioncommerce/reactionSubject: [reaction] Refactor ReactionCore.registerPackage schema (#314)Refactor the ReactionCore.registerPackage package schema to be more structured.
Only templates need to be published to general client, while others (settings,dashboard) would be published when admin.

ReactionCore.registerPackage
  name: 'reaction-paypal'
  provides: ['paymentMethod']
  version: "0.3.1"
  settings: 
    route: 'paypal'
    mode: false
    client_id: ""
    client_secret: ""
  dashboard: 
    label: 'PayPal'
    description: 'Accept PayPal payments'
    icon: 'fa fa-paypal',
    priority: '2'
    hasWidget: true
    autoEnable: false
  templates: [
    template: "paypalPaymentForm"
    provides: "paymentMethod"
  ]
  permissions: [
    label: "Pay Pal"
    permission: "dashboard/payments"
    group: "Shop Settings"
  ]

I'd like to attempt to resolve #53, #308, #178, #136, #245 as well in this refactor.

—Reply to this email directly or view it on GitHub.
