### ISSUE TITLE
Convert all `Packages.findOne` to `getPackageSettings`

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3144]
Another cleanup task. As long as it exists in the old code, people keep creating new versions of it.

**Comment by iakhator** [comment]
@machikoyasuda are you still working on this?

**Comment by machikoyasuda** [comment]
@iakhator No I am not! You can take it :D

**Comment by aldeed** [comment]
No longer relevant because Packages collection is removed in 3.0
