### ISSUE TITLE
Products sub not updating component reactively 

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#3146]
### Expected behavior

When you disable a shop, products of said shop should be hidden from view without having to refresh. 
The products sub is not being re-called on the component till a refresh is done.

### Actual behavior

You have to refresh for the products to be filtered out.

### Steps to reproduce the behavior

- Remove/delete filter in `productsContainer.js` https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/product-variant/containers/productsContainer.js#L179
- Notice that without the filter the component is not reactive

**Comment by codejockie** [comment]
@joykare could you please clarify on this issue, I've tried reproducing the issue but I'm unable to do that. The link you provided is dead.

**Comment by joykare** [comment]
@codejockie replaced the link. If you remove that snippet every time you disable a shop you need to refresh the page for changes to occur.
- You need to have the subscription run continuously if you want the changes to be reactive. What is happening now is that the subscription runs only once(when the component is rendered).

**Comment by codejockie** [comment]
@joykare Why is the `ProductsContainer` used in a Higher Order Component?

**Comment by aldeed** [comment]
No longer an issue in 2.0.0
