### ISSUE TITLE
Multi tenant

### ISSUE THREAD

**Issue by chrisformula** [reactioncommerce/reaction#3159]
Hi Guys am I just being dof, but where do you enable multi tenant functionality?

**Comment by spencern** [comment]
HI @chrisformula 
Multi-tenant functionality can be enabled from the "Shops" dashboard panel when logged in as an Admin panel

![image](https://user-images.githubusercontent.com/1203639/31952409-5e1de7ec-b895-11e7-99f1-8dad8bcb8d7d.png)
