### ISSUE TITLE
Error running app local

### ISSUE THREAD

**Issue by emerchan** [reactioncommerce/reaction#316]
Hello I have some errors when I tried to run the app locally, my meteor version is 1.0.3.1 I just follow the steps here: https://reactioncommerce.com/guide/reaction-core/installation

Thank you.

 
![screen shot 2015-02-10 at 5 33 37 pm](https://cloud.githubusercontent.com/assets/9324283/6138187/1177a916-b14d-11e4-8dbb-ec6f926416d1.png)

**Comment by aaronjudd** [comment]
Is the application actually running? ( http://localhost:3000 )?  I think that if there is an error with graphicsMagic it should be a silent error, but could you also try installing imagemagick or graphicsmagick and see if that gets rid of the errors?

**Comment by emerchan** [comment]
Yes, the app is running, but I the terminal doesnt shows me the admin user.

**Comment by aaronjudd** [comment]
You didn't mention what OS you are running, but I am seeing the same behavior on a fresh ubuntu install.  

On ubuntu you'll need to install `node` and `npm`, as well as  `graphicsmagick` to get rid of the warnings.

Node, npm install I used:
```
mkdir /nodejs && curl http://nodejs.org/dist/v0.10.33/node-v0.10.33-linux-x64.tar.gz | tar xvzf - -C /nodejs --strip-components=1
export PATH=$PATH:/nodejs/bin
apt-get install graphicsmagick
```

then you'll want to do `meteor reset` and run `meteor` again. (account info only displays the for a fresh db).


I'll update the docs with these more detailed requirements.

**Comment by emerchan** [comment]
Ok, my OS version is: 10.10.2 OS x Yosemite.
There is something addicional that I have to install?
Thanks

**Comment by aaronjudd** [comment]
I think maybe you just need to install node from the package `http://nodejs.org/dist/v0.12.0/node-v0.12.0.pkg`   

I use the node distribution,  vs 'brew install node".  For `graphicsmagick` , it not required but you can do `brew install graphicsmagick` (if you've installed http://brew.sh/).



To test if you have node and npm installed correctly, just type 'npm -v' and verify that you get the npm version.
