### ISSUE TITLE
Username/Password and Route to access the Admin panel

### ISSUE THREAD

**Issue by coooolers** [reactioncommerce/reaction#3170]
I am running “reaction” on my local machine. It just displays You are a guest user. I do not know what is the link/URL route/username/password to access the Admin panel.

Could anybody help me out?

Thanks

**Comment by zenweasel** [comment]
@coooolers You just need to login with the admin username/password and the admin dashboard will appear on the right side.

**Comment by coooolers** [comment]
What is the admin's default username/password?

**Comment by pablofmorales** [comment]
```
email: admin@localhost
pass: r3@cti0n
````

@coooolers
