### ISSUE TITLE
product detail page URL shown in URL bar does not work

### ISSUE THREAD

**Issue by bayareacoder** [reactioncommerce/reaction#3171]
### Expected behavior
The PDP page should be accessible from the URL shown in the address bar

### Actual behavior
It is not. The URL in the address bar returns no page. Tested only for a non-marketplace shop setup.

### Steps to reproduce the behavior
1.  Go to a PDP page. The URL will show as `http://<domain>/product/<product_slug>`. 
2. Open new browser window and load above URL - no page is found
3. Change URL to: `http://<domain>/shop/<shop_prefix>/product/<product_slug>`. This will work.

### Versions
Node: 6.11.4
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.18.0
Reaction: 1.5.1
Reaction branch: master
Docker: 17.09.0-ce

**Comment by zenweasel** [comment]
I tried to replicate this issue with my local install and I can't

**Comment by bayareacoder** [comment]
If you let me know your email address I'll email you with my public site URL where I observe this issue. (I don't want the site URL to be seen publicly). Thanks.

**Comment by zenweasel** [comment]
@bayareacoder I'm brent@reactioncommerce.com

**Comment by zenweasel** [comment]
@bayareacoder Do you have more than one shop in your `Shops.json`? You shouldn't be getting the prefix in your URL if you have only one shop.

**Comment by bayareacoder** [comment]
Attached the shops.json file from private/data directory.
I only setup 1 shop.

**Comment by bayareacoder** [comment]
One more input on this: while I did not setup more than 1 shop, I may have flipped the switch to 'marketplace' and back from the admin login (to see the effect on the UI). Maybe this has an impact.

**Comment by aldeed** [comment]
Closing this pending accurate reproduction steps
