### ISSUE TITLE
Back and Forward buttons/history not displaying contents when on Search page

### ISSUE THREAD

**Issue by coooolers** [reactioncommerce/reaction#3176]
### Expected Behavior
Back button should return you to the previous content

### Actual Behavior
Content is not displayed

### Steps to Reproduce
1. Add an item to a cart
1. Browse back to Shopping 
1. Click on Search
1. Press the Back button ... the URL changes but the corresponding content is not displayed
1. Press the Forward no content is idsplayed

**Comment by codejockie** [comment]
This issue is regardless of whether you have an item in cart.

**Comment by codejockie** [comment]
Fixed.

**Comment by spencern** [comment]
Resolved in release [v1.6.4](https://github.com/reactioncommerce/reaction/releases/tag/v1.6.4)
