### ISSUE TITLE
What is the admin's default username/password?

### ISSUE THREAD

**Issue by coooolers** [reactioncommerce/reaction#3177]

**Comment by stevaras** [comment]
@coooolers Whenever you do a Reaction reset, and afterwards run your application for the first time, it shows you the username and password in your console.
It used to be a random generated password but nowadays Reaction has a specific one which if I'm not mistaken is: 

    EMAIL/LOGIN: admin@localhost
    PASSWORD: r3@cti0n

![image](https://user-images.githubusercontent.com/13280180/32055332-2cf395aa-ba6a-11e7-96cc-fd0e6371935c.png)

You can also set your own password and username following Reaction's Docs and specifically the Configuration section provided here: https://docs.reactioncommerce.com/reaction-docs/master/configuration

**Comment by aaronjudd** [comment]
@stevaras is right on. @machikoyasuda https://docs.reactioncommerce.com/reaction-docs/master/installation . maybe we can refresh this with a new screenshot and the default info?

**Comment by machikoyasuda** [comment]
@aaronjudd done: https://github.com/reactioncommerce/reaction-docs/pull/320/files 

@stevaras thanks for answering this superfast!

**Comment by dheerajmpai** [comment]
Sorry for bumping the old question. Can I know what is the admin URL? Is it localhost:3000? I cannot find this anywhere in the documentation
