### ISSUE TITLE
Fix translation provider to move  from React.PropTypes to PropTypes

### ISSUE THREAD

**Issue by josx** [reactioncommerce/reaction#3179]
### Expected behavior
All RC code havent to use React.PropTypes becase are deprecated
Will no work on React >= 16
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

### Actual behavior
Shows an annoying message on console,

### Steps to reproduce the behavior
Open console, and look for message:
```Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs```

### Versions
```
Node: 4.2.4
NPM: 4.1.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction: 1.5.3
Reaction branch: deprecated_proptypes
Reaction CLI: 0.19.0
Docker: 17.03.0-ce
```

**Comment by spencern** [comment]
Resolved by #3180
