### ISSUE TITLE
Content for showcase page

### ISSUE THREAD

**Issue by sophiehe** [reactioncommerce/reaction#3181]
Here is a list of stuff to put on showcase page:

**Comment by sophiehe** [comment]
[IT Furniture Store](https://www.itfurniturestore.com/) 

https://blog.reactioncommerce.com/meet-the-developer-community-2/ 

[artlimes](https://artlimes.com/)

https://blog.reactioncommerce.com/meet-lorenzo-campanis-ceo-of-artlimes/

[Easy Wine](https://easy-wine.de/)

https://blog.reactioncommerce.com/meet-the-developer-community/

[Pin Up Magazine](https://shoppe.pinupmagazine.org)

In progress

**Comment by machikoyasuda** [comment]
Closing in favor of reaction-drive repo
