### ISSUE TITLE
Expand Featured Images to fit container in Product Detail view

### ISSUE THREAD

**Issue by glmaljkovich** [reactioncommerce/reaction#3185]
### Expected behavior
Product Images in the Product detail view fit the image container.

### Actual behavior
If the image is smaller than the container it displays in its actual size and aligned to the left.

### Steps to reproduce the behavior
Add a featured image to a product with a small resolution (lets say 250px x 250px)

### Versions
(run `reaction -v` from your reaction directory)
- Node: 8.1.3
- NPM: 5.0.3
- Meteor Node: 4.8.4
- Meteor NPM: 4.6.1
- Reaction CLI: 0.14.3
- Reaction: 1.5.3

I'll submit a PR right away.

**Comment by glmaljkovich** [comment]
#3186

**Comment by zenweasel** [comment]
@rymorgan  We probably need a little product direction around how exactly we should handle this. @glmaljkovich added a fix that expands that image but it doesn't look great with smaller images and it cutoff with vertical images. As @kieckhafer had noted on the PR I think the impetus is the shop admin to upload an image that is of appropriate resolution but we probably need to figure out how we want to handle these different sizes.

This is not really a bug but enhancing the behavior of an existing feature.

**Comment by rymorgan** [comment]
@zenweasel I made comments on the PR.

**Comment by aldeed** [comment]
Fixed in 2.0.0 example storefront
