### ISSUE TITLE
No Success Message Shown when Inviting New Shop Owner into Marketplace 

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#3189]
### Expected behavior
When inviting a shop owner to a marketplace, there should be a success message and the spinning should disasppeear when invitation is done.

### Actual behavior
The spinner persisted even after the email was already sent, and there was no success message toast.

### Steps to reproduce the behavior
Go into Shop > Marketplace > Invite Owner. Invite a new owner and try inviting a shop owner.
NB: This happened once, and did not happen on a second trial.

### Versions
Node: 7.10.0
NPM: 5.4.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.1
Reaction: 1.5.4
Reaction branch: master

**Comment by zenweasel** [comment]
Verified fixed.
