### ISSUE TITLE
Notification not being sent to customer

### ISSUE THREAD

**Issue by arsen3d** [reactioncommerce/reaction#3200]
### Expected behavior
Notification being sent to customer
### Actual behavior
Notification not being sent to customer

Oct 30 12:07:59 app/web.1: Exception while invoking method 'orders/sendNotification' TypeError: Cannot read property 'url' of undefined 
Oct 30 12:07:59 app/web.1:     at [object Object].ordersSendNotification (server/methods/core/orders.js:572:51) 
Oct 30 12:07:59 app/web.1:     at packages/check.js:128:16 
Oct 30 12:07:59 app/web.1:     at [object Object].EVp.withValue (packages/meteor.js:1134:15) 
Oct 30 12:07:59 app/web.1:     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41) 
Oct 30 12:07:59 app/web.1:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18) 
Oct 30 12:07:59 app/web.1:     at packages/ddp-server/livedata_server.js:719:19 
Oct 30 12:07:59 app/web.1:     at [object Object].EVp.withValue (packages/meteor.js:1134:15) 
Oct 30 12:07:59 app/web.1:     at packages/ddp-server/livedata_server.js:717:46 
Oct 30 12:07:59 app/web.1:     at [object Object].EVp.withValue (packages/meteor.js:1134:15) 
Oct 30 12:07:59 app/web.1:     at packages/ddp-server/livedata_server.js:715:46 
Oct 30 12:07:59 app/web.1:     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23) 
Oct 30 12:07:59 app/web.1:     at packages/ddp-server/livedata_server.js:559:43 
### Steps to reproduce the behavior
Click Resent Shipment Notification
### Versions
(run `reaction -v` from your reaction directory)
Reaction CLI: 0.19.1
Reaction: 1.5.4
Reaction branch: master
Docker: 17.09.0-ce

**Comment by zenweasel** [comment]
@arsen3d I am not able to reproduce this error. It looks like there may be an issue with your email configuration. Can you provide more detailed steps to reproduce including your email config?

**Comment by zenweasel** [comment]
Closing due to lack of detail and no response
