### ISSUE TITLE
Ok this time again this one throwing error for autoprefixer

### ISSUE THREAD

**Issue by oaulakh** [reactioncommerce/reaction#3213]
Now this error 

=> Errors prevented startup:
   
   While processing files with less (for target web.browser):
   imports/plugins/included/default-theme/client/styles/main.less:156: Unknown
   import: {}/node_modules/react-select/less/select.less
   
   While minifying app stylesheet:
   module.js:325:15: Cannot find module 'autoprefixer'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.require.resolve (internal/module.js:16:19)
   at Object.require (/tools/isobuild/bundler.js:1877:34)
   at packages/minifier-postcss/plugin/minify-css.js:52:37
   at Array.forEach (native)
   at getPostCSSPlugins
   (packages/minifier-postcss/plugin/minify-css.js:51:43)
   at packages/minifier-postcss/plugin/minify-css.js:155:36
   at Array.map (native)
   at mergeCss (packages/minifier-postcss/plugin/minify-css.js:139:23)
   at CssToolsMinifier.processFilesForBundle
   (packages/minifier-postcss/plugin/minify-css.js:109:18)
   
   
=> Your application has errors. Waiting for file change.

You can find detailed log here http://paste.ubuntu.com/25860359/

**Comment by aaronjudd** [comment]
in your full log I see: `Warning: unable to resolve "env" in presets of `,etc leads me to think modules weren't installed. run `meteor npm install` and it should reinstall all the required modules.

**Comment by oaulakh** [comment]
i'm sorry, but i followed your git tutorial, so yeah it's working now

thanks!
