### ISSUE TITLE
Cannot cancel orders processed using Authorize.net

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3216]
### Expected behavior
Should be able to cancel an order processed using any payment provider

### Actual behavior
Clicking on cancel does nothing and an error is shown in the server console
```
 Attempt for refund transaction failed WSoTNKWh4waDujT8P 60033194958 Reaction does not yet support direct refund processing from Authorize.net. Please visit their web portal to perform this action. https://account.authorize.net/
```
Basically, if a payment processor does not support refunds, it should not attempt to refund when cancelling.

### Steps to reproduce the behavior
1. Place an order using Authorize.NET
1. Approve and Capture the order
1. Click on "Cancel"
1. Observe that nothing happens except an error is thrown on the server

### Versions
```
Node: 7.10.0
NPM: 5.4.2
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.1
Reaction: 1.5.3
Reaction branch: itua-fix-issue-3075 (master)
Docker: 17.09.0-ce
```

**Comment by iakhator** [comment]
@zenweasel When the cancel button is clicked, for payment method that does not support refund, `should the cancel order process and no exception error thrown on the server` OR `the cancel order should not process and no exception error thrown on the server`?

**Comment by zenweasel** [comment]
@iakhator It should just proceed with the cancel and not attempt to process a refund.
