### ISSUE TITLE
Tag edit permission in add/edit product

### ISSUE THREAD

**Issue by Gary-Pan** [reactioncommerce/reaction#3217]
Hi,
I want to create a new group with permissions that can edit tag in add/edit product. But I can't complete this after I created a new group and enable all the permissions.
Is it possible to enable edit tag permission?

Reaction: 1.5.5

**Comment by zenweasel** [comment]
@Gary-Pan Right now we don't have permission that are that specific. We would need to add that as an enhancement. Right now you can grant the `createProduct` permission which should allow the user to edit tags as well as add/edit products.

**Comment by aldeed** [comment]
A permissions cleanup project is coming at some point, but for now I'm going to close this as not directly actionable since it requires the larger permissions discussion.
