### ISSUE TITLE
Payment method - Bank transfer

### ISSUE THREAD

**Issue by matteocrippa** [reactioncommerce/reaction#322]
I'm starting at looking at your product and I noticed that atm it is not supported a bank transfer way of payment. It would be interesting to add support for that too, it is for sure an async method where the user pre-order the product and the seller update the status manually once receives the payment.

**Comment by aaronjudd** [comment]
Do you have a particular service in mind?   I think the workflow wouldn't be to tough to adjust.  We're doing payment auth in checkout and trans in order completion flow, so I think it would fit in that flow.

**Comment by matteocrippa** [comment]
@aaronjudd as far as I know there are no service that can fit that, so probably the right way is to proceed like adding only a generic way of delayed payment that can be approved by the seller and at that very moment he/she can trigger the order status manually.

**Comment by danielgindi** [comment]
Orders that require approval by the seller are not that rare - and it is not only for bank transfers. There are a multitude of reasons, starting in Credit Card payments in "redirect" form where users can "cheat" the redirect response so the seller has to verify payment in the provider's console, and ending in users sending written checks in the mail.

The flow is not rare also technically - most eCommerce solutions support that, and it's just a matter of having a "pending approval" status for an order - which will be skipped for automatically approved order.
