### ISSUE TITLE
Responsive Sizing Issues 

### ISSUE THREAD

**Issue by arsen3d** [reactioncommerce/reaction#3221]
![screenshot 2017-11-01 14 57 52_preview](https://user-images.githubusercontent.com/298235/32300675-e5f5ee16-bf17-11e7-9ec7-5623429cf7d1.png)

**Comment by arsen3d** [comment]
Only works when margin is as big as the image

**Comment by zenweasel** [comment]
@arsen3d Can you fill out the issue template for this? I can't tell exactly what you are reporting here

**Comment by zenweasel** [comment]
Closing due to lack of detail and no response
