### ISSUE TITLE
Image for variant not showing when clicking on a product

### ISSUE THREAD

**Issue by arsen3d** [reactioncommerce/reaction#3227]
### Expected behavior
Product images to show
### Actual behavior
Placeholder images show
### Steps to reproduce the behavior
Click between products
https://hello.reactioncommerce.com/
Do not use back button
Do not click refresh.
Clicking refresh brings the image in.
### Versions
1.5
### Notes
I think the problem is at ReactionProduct in /lib/api/products.js.
The bug can be seen at function composer(props, onData) in imports/plugins/included/product-detail-simple/client/containers/social.js
//selectedProduct returns correct product
    const product = ReactionProduct.selectedProduct() || {};
//selectedVariant return wrong variant.
    const selectedVariant = ReactionProduct.selectedVariant() || {};

**Comment by arsen3d** [comment]
![screen recording 2017-11-02 at 12 09 53 pm](https://user-images.githubusercontent.com/298235/32345356-27b258e4-bfc7-11e7-82fd-303dad714c10.gif)

**Comment by arsen3d** [comment]
![screen recording 2017-11-02 at 12 09 53 pm 2](https://user-images.githubusercontent.com/298235/32345484-9006f76a-bfc7-11e7-8283-9dba379c85cd.gif)

**Comment by arsen3d** [comment]
Can someone label this as a bug with critical impact.

**Comment by arsen3d** [comment]
Note the file name in debugger, the function being called, and that varientId in console does not change as I click between products.
![screen recording 2017-11-02 at 1 47 53 pm](https://user-images.githubusercontent.com/298235/32349580-c045efdc-bfd4-11e7-870d-55b1d2e5750a.gif)

**Comment by arsen3d** [comment]
Looks like the video is too blurry. Here is a screenshot
![screen recording 2017-11-02 at 1 47 53 pm](https://user-images.githubusercontent.com/298235/32349679-212eec18-bfd5-11e7-926d-85c99aec3353.gif)

**Comment by arsen3d** [comment]
As you can see in the commented code, I've attempted  to resolve the problem by waiting for subscription to be ready. This did not solve the problem as it appears that ReactionProduct is being synchronized with autopublish in the background. Though it's not entirely clear to me about exactly how the underlying components are working.

**Comment by speedingdeer** [comment]
Same here

**Comment by arsen3d** [comment]
@speedingdeer I have not tested that. I suggest you make a new issue out of it. Make a video/gif if you can.

**Comment by speedingdeer** [comment]
@arsen3d I will create a new issue. np.

**Comment by speedingdeer** [comment]
FYI
<img width="1440" alt="screen shot 2017-11-09 at 12 53 34" src="https://user-images.githubusercontent.com/279544/32604237-40ee2b86-c54d-11e7-8a31-65a895e84105.png">

**Comment by arsen3d** [comment]
Submitted pull request that solved the problem: 
https://github.com/reactioncommerce/reaction/pull/3305

**Comment by zenweasel** [comment]
We only like to close issues when a PR has actually been merged

**Comment by spencern** [comment]
Resolved by #3267
