### ISSUE TITLE
a node js issue ; undefined value of an string key

### ISSUE THREAD

**Issue by Jawadwithw** [reactioncommerce/reaction#3229]
Hi all!
in the server side, i have these codes:

 

    data= Object {from: USER1,sendto: ﻿﻿USER2,message: hello}
    clients=Object { USER1: 'Df0BRydnLO1AcNgYAAAC', USER2: 'tvpEquFf7GwPBKS-AAAD' }
when I want to get the value of USER1, i type my code like this:

    var sendmsgto=data["sendto"];

    var user=clients[sendmsgto];
    console.log(user);
and the output of log is :

    undefined

**but** , when I Enter this code:

    var user=clients["USER1"];
    console.log(user);
in the output it works correct and gives me the right server id :

    Df0BRydnLO1AcNgYAAAC

**i really don't know why this is happening to me! anybody can help me please?!**

**Comment by jshimko** [comment]
I don't see an actual error with Reaction here.  This sounds like you're asking for help writing your custom code.  You should consider asking for help in Gitter or the forum.

You also didn't fill out the required issue template, so...
