### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3233]
# Performance Epic
## Planning
During the planning phase of this epic, our goal is to benchmark, document, and communicate these efforts. We need to be able to measure where we are starting and the progress we make.

[Kadira](https://github.com/kadira-io) is now an open source project. During the benchmarking and planning phase of this performance epic, we will set up Kadira and gather initial data.

## Goals
- 50% or greater improvement in performance 
- Documentation on progress towards goals, and measurable performance improvements
- A blog post or series of blog posts about how we've improved performance

## Projects
- Dynamic module loading (Research issue#: https://github.com/reactioncommerce/reaction/issues/3234, lead: @kieckhafer)
     - `registerComponent`: https://github.com/reactioncommerce/reaction/issues/2666
     - `moment-timezone`: https://github.com/reactioncommerce/reaction/issues/2635
     - `transliteration`: https://github.com/reactioncommerce/reaction/issues/2634
     - Research + blogging task: https://github.com/reactioncommerce/reaction/issues/3234 @kieckhafer 
     - This can be several different issues, one for each major component or section of Reaction that we split out to be loaded dynamically
- Meteor 1.6 (Research issue#: https://github.com/reactioncommerce/reaction/issues/3207, lead: @zenweasel)
   - How can we get Meteor 1.6 to run w/ Reaction and what are the performance gains?
   - Research + present: https://github.com/reactioncommerce/reaction/issues/3235 @zenweasel 
- Component re-rendering  (Research issue#: https://github.com/reactioncommerce/reaction/issues/3236, lead: @mikemurray)
   - Are the actions that are slow also the actions w/ re-rendering components?
   - Which components re-render the most in the app?
     - https://github.com/maicki/why-did-you-update
   - Look into `composeWithTracker` efficiency
     - https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/components/lib/composer/compose.js#L13-L16
- `cli` fix npm loader, add/remove Reaction packages (Research issue#: https://github.com/reactioncommerce/reaction-cli/issues/5, lead: @jshimko) 
   - Confirm if this is a performance gain at all
- npm package loading (Research issue#: , lead: @spencern)
   - Experimental branch from https://github.com/reactioncommerce/reaction-cli/commits/asj-experimental-pkg-linking
- Get kadira running on a local instance (Research issue#:https://github.com/reactioncommerce/reaction/issues/3237, lead: @jshimko)
   - What the rest of us have to do to run Kadira
- Create a MongoDB dump file to demo sample data to test shops, @zenweasel 
   - Standard blank shop, Shop with 100 orders/users, Shop with 10k orders/users   
- ADDITIONAL SUGGESTIONS WANTED:
   - Storage provider plugin so you can use S3 etc. CDNs to load images @impactmass https://github.com/reactioncommerce/reaction/issues/1815
   - Audit packages: Go through all packages and determine usefulness, weight, @joykare https://github.com/reactioncommerce/reaction/issues/3238

## How we're defining performance
1. Dev build time: Initial build time (`reaction init`), build time while you're developing
2. Prod build time: 
3. Time to first paint: Production build and development build
     - time
     - weight
4. General React responsiveness and component re-rendering: Add to Cart, Checkout, Scroll through Product Grid
     - sluggishness
     - excessive rendering
5. Memory footprint, app size
     - sub 2GB RAM
     - number of concurrent clients

## How we're measuring + testing performance
1. Dev build time: 
2. Prod build time: Measured in CircleCI, How long does the docker build take?
3. Time to first paint: https://developers.google.com/web/tools/lighthouse/#devtools performance tab
4. General React responsiveness and component re-rendering: 

### Tools
1. meteor-profile
2. meteor bundle profiler https://blog.meteor.com/announcing-meteor-1-5-b82be66571bb
3. Kadira
4. Chrome DevTools Network tab + Audits tab
5. https://github.com/maicki/why-did-you-update 
     - number of re-renders

### What personas measuring on
1. new: blank Reaction site
2. small: 100 products/orders/users
3. large: 10,000 products/orders/users

### What kind of apps
- local vs. remote MongoDB: replica set vs. single node

### What kind of users
- Mobile app
- Desktop of developer (Windows/Mac)

### What actions we're measuring
1. Add to Cart
2. Load more products
3. Grid to PDP
4. Cart to checkout
5. Checkout to complete (example payment provider)
6. Admin: open Accounts and Orders
7. Admin: Create a Product
8. Admin: Add a variant option
9. Admin: Selecting multiple products on a grid

### What instances we're measuring
1. Local server / 16GB instance
2. 2GB RAM instance

**Comment by roboto-cloud** [comment]
here!!! finally **performance** is a word what I can see  from a collaborator or member team  :)
this two issues can be closed...

https://github.com/reactioncommerce/reaction/issues/3220
https://github.com/reactioncommerce/base/issues/7

**Comment by aldeed** [comment]
Done
