### ISSUE TITLE
Research + present on migrating to Meteor 1.6

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#3235]
## Questions to answer
- What are the blockers in upgrading to Meteor 1.6?
- How long do you think this will take to get thru the blockers?
- What are the gains?

Part of https://github.com/reactioncommerce/reaction/issues/3233

**Comment by zenweasel** [comment]
Since @jshimko has already done this, assigning this to him.

**Comment by aaronjudd** [comment]
Assigned to @jshimko closing for him, as Meteor 1.6 was merged, released.
