### ISSUE TITLE
Research + present on auditing all packages

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#3238]
## Part of 
https://github.com/reactioncommerce/reaction/issues/3233

## Present
- What's our bundle size? 
- What are the top packages we're requiring + how can we lessen them?

**Comment by joykare** [comment]
Notes: 
- top packages/how big and how useful/alternatives
- npm packages usage/ how useful/alternatives if any
- blaze and code not used (e.g. Sliders)

**Comment by machikoyasuda** [comment]
Related: https://www.youtube.com/watch?v=dUKIO47iHF4
