### ISSUE TITLE
Unsuccessful on c9 

### ISSUE THREAD

**Issue by kosir** [reactioncommerce/reaction#324]
Hi, yesterday I tested your shop and it really looks like (it will be) AMAZING app. So I decided to play with it a little...
Installed on c9 and it looks ok:
kosirm@shop:~/workspace/reaction (development) $ meteor --port $IP:$PORT
[[[[[ ~/workspace/reaction ]]]]]              

=> Started proxy.                             
=> Started MongoDB.                           
I20150225-08:44:39.311(0)? => GraphicsMagick found
I20150225-08:44:39.990(0)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
=> Started your app.

=> App running at: http://0.0.0.0:8080/

But then (when I open app), I got these errors:

I20150225-08:45:05.186(0)? Exception from sub zJFBBEQEAG6oe59YZ Error: Did not check() all arguments during publisher 'ReactionSessions'
I20150225-08:45:05.187(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150225-08:45:05.187(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150225-08:45:05.187(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150225-08:45:05.187(0)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150225-08:45:05.187(0)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150225-08:45:05.188(0)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150225-08:45:05.188(0)?     at packages/ddp/livedata_server.js:546:1
I20150225-08:45:05.222(0)? Exception from sub R8FnkxrKqxke23AGN Error: Did not check() all arguments during publisher 'cart'
I20150225-08:45:05.223(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150225-08:45:05.223(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150225-08:45:05.223(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150225-08:45:05.223(0)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150225-08:45:05.223(0)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150225-08:45:05.223(0)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150225-08:45:05.223(0)?     at packages/ddp/livedata_server.js:546:1
I20150225-08:45:05.371(0)? Exception from sub KupeGLkJKmB2Mc5E6 Error: Did not check() all arguments during publisher 'Translations'
I20150225-08:45:05.371(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150225-08:45:05.371(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150225-08:45:05.371(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150225-08:45:05.371(0)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150225-08:45:05.371(0)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150225-08:45:05.371(0)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150225-08:45:05.371(0)?     at packages/ddp/livedata_server.js:546:1
I20150225-08:45:05.459(0)? Exception from sub ZSmE2Yq8hr7nDLSXD Error: Did not check() all arguments during publisher 'cart'
I20150225-08:45:05.459(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150225-08:45:05.460(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150225-08:45:05.460(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150225-08:45:05.460(0)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150225-08:45:05.460(0)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150225-08:45:05.460(0)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150225-08:45:05.460(0)?     at packages/ddp/livedata_server.js:546:1
I20150225-08:45:06.083(0)? Exception from sub AGKSbhNvdoPK4nA44 Error: Did not check() all arguments during publisher 'cart'
I20150225-08:45:06.083(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150225-08:45:06.083(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150225-08:45:06.083(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150225-08:45:06.083(0)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150225-08:45:06.083(0)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150225-08:45:06.083(0)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150225-08:45:06.084(0)?     at packages/ddp/livedata_server.js:546:1

... app is in eternal loading state.

Thanks in advance for any hint.
BR

**Comment by kosir** [comment]
Update: I installed core and theme package locally, update and reset - and now it's working like a charm. Consider this solved.

**Comment by aaronjudd** [comment]
@kosir when using the development branch, it's a little tricky because you have to make sure you're also using updated dependencies (packages).  Looks like you figured that out, but I've also revamped the docs a bit to help clarify this.  appreciate the feedback!

**Comment by kosir** [comment]
Thanks! Your app is a complete WOW to me! I'm so sorry I don't use coffeescript so I first "decaffeinated" source :) 
The only problem I have currently is with hot code push, mongo crouching with every file save.
I don't know how to disable meteor hot code push... Everything else is great. Need to explore sources.
Thanks!

**Comment by meteorplus** [comment]
Hello dear @jshimko :)
I am having the same issue here with the latest version!

Even do this `reaction --port $IP:$PORT` doesn't work at all!

thank you

**Comment by jshimko** [comment]
The `--port` argument only expects a port.  As in `reaction --port 4000`

**Comment by meteorplus** [comment]
I am still getting `Error 502 - Bad Gateway` now with 8080 which is the port used for c9

**Comment by aaronjudd** [comment]
@meteorplus I don't think this is an issue with Reaction, you'll probably get more useful responses elsewhere, like https://community.c9.io/t/getting-started-with-meteor/8240/12
As nobody in the core team uses C9, (we all use Atom locally).

**Comment by meteorplus** [comment]
@aaronjudd  thanks but this isn't even related to c9!

I am confused on how to set a different port and ip with Reaction that's all!

since with most meteor apps I could do that!

**Comment by aaronjudd** [comment]
@meladawy then this old closed issue regarding C9 is a confusing place to be posting.  Suggest our gitter chat is better.

`ROOT_URL` as an environment var is used to set the URL/IP.  `--port`.  We do not do anything different than Meteor, so if it worked on "most meteor apps", it should work with Reaction. (unless we have a yet unknown issue, which then please create a new issue.).

**Comment by jshimko** [comment]
To confirm...

```sh
$ reaction --port 4000

Using settings file at settings/dev.settings.json

Setting up plugin imports...

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:4000/

```

There's nothing wrong with Reaction or the `--port` arg.
