### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3244]
The release process should be simple, quick and not manual. Perhaps you could just put in a release number and PR numbers and it could:

1. Create the release branch
1. Rev the `package.json`
1. Merge the PR's into the release branch
1. Create the release PR with the release notes

Or alternately it could iterate through all open, non-WIP, approved PR's and ask "Ready to release?" for each to make it even less manual

**Comment by zenweasel** [comment]
Probably as a corollary to this, we should have some sort of simple, automated smoke testing that can be run at the command line

**Comment by kieckhafer** [comment]
We've greatly changed up our release process now that 3.0 has been released. Closing this.
