### ISSUE TITLE
Hide options card on Shop panel for Merchant Shops

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#3246]
### Expected behavior

Merchant shops should not have the ability to set shop options 
These include (all in the options card):
- [ ] Exchange rates 
- [ ]  Google Client Ids and passwords

### Actual behavior

Merchant shops can change these settings since card is visible to them

### Steps to reproduce the behavior

- Log in as merchant shop
- On the sidebar click on `shops` icon 
- Open options card/panel
- Change the provided fields and save

### Versions
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.0
Reaction: 1.5.5
Reaction branch: master
Docker: 17.03.1-ce

**Comment by spencern** [comment]
Resolved by #3247
