### ISSUE TITLE
Default Package Development Problem

### ISSUE THREAD

**Issue by psy21d** [reactioncommerce/reaction#325]
http://127.0.0.1:3000/product/example-product

I just install it: https://github.com/reactioncommerce/reaction-core/blob/master/docs/packages.md
All projects failed. Collection failed!
I check a lot of code. Ne pomogaet

I20150228-23:03:13.608(3)? Exception while invoking method 'updateVariant' Error: Match error: One or more properties do not match the schema.
I20150228-23:03:13.609(3)? at [object Object].SimpleSchema.condition (packages/aldeed:simple-schema/simple-schema.js:600:1)
I20150228-23:03:13.609(3)? at checkSubtree (packages/check/match.js:220:1)
I20150228-23:03:13.609(3)? at check (packages/check/match.js:32:1)
I20150228-23:03:13.610(3)? at [object Object].Meteor.methods.updateVariant (packages/reactioncommerce:core/server/methods/products/products.coffee:73:5)
I20150228-23:03:13.610(3)? at packages/check/match.js:109:1
I20150228-23:03:13.611(3)? at [object Object]..extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150228-23:03:13.611(3)? at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150228-23:03:13.611(3)? at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150228-23:03:13.612(3)? at packages/ddp/livedata_server.js:648:1
I20150228-23:03:13.613(3)? at [object Object]..extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150228-23:03:13.613(3)? Sanitized and reported to the client as: Match failed [400]
I20150228-23:03:13.613(3)?

: The latest version of Meteor, 1.0.3.2
: Yes, i make meteor meteor --settings settings/settings.json && meteor reset
Ne pomogaet

Please fix it recently.

**Comment by aaronjudd** [comment]
@psy21d thanks for the report.  should be a simple fix, one of the parameters isn't passing the 'check' validation. I'll try to get a patch up to development soon.

**Comment by psy21d** [comment]
Thank you! A lot of my work will be saved!
Please write where it would be fixed.

**Comment by aaronjudd** [comment]
If you have reaction-core package installed in packages directory locally (for development), you can comment out 'packages/reactioncommerce:core/server/methods/products/products.coffee:73:5'

``` check variant, ReactionCore.Schemas.ProductVariant```

This should be working, so it would be helpful if you can describe steps to reproduce.

**Comment by psy21d** [comment]
How better to make reactioncommerce theme? Where directories can create to place new .less .coffee .html files more better?
I need to replace all view.

How to make mongodb backups reliably?

**Comment by psy21d** [comment]
This should be working comment out 'packages/reactioncommerce:core/server/methods/products/products.coffee:73:5'

No, it is not work. I try it yesterday. 
I check a lot of code! I can not understood, what's that are bad...

I20150301-00:58:04.270(3)? Exception while invoking method 'updateVariant' Error: Did not check() all arguments during call to 'updateVariant'
I20150301-00:58:04.270(3)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150301-00:58:04.271(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150301-00:58:04.271(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150301-00:58:04.271(3)?     at packages/ddp/livedata_server.js:648:1
I20150301-00:58:04.271(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-00:58:04.272(3)?     at packages/ddp/livedata_server.js:647:1
I20150301-00:58:04.272(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-00:58:04.272(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150301-00:58:04.272(3)?     at packages/ddp/livedata_server.js:546:1

**Comment by psy21d** [comment]
I check all schemes and checking methods, it's all looks good (100% fine) but it is broken. Why?

\reaction-core\server\methods\products\products.coffee
\reaction-core\common\schemas\products.coffee

**Comment by psy21d** [comment]
Please, it very important for me, sure, lost a lot of work yesterday, I was use package at 01 feb dated, that is was work fine, but I lost some important files (WebStorm replace some files at server and files local by zero length files) and now I can not make working version at all. Used repository revert, used backups...
Thanks a lot!

**Comment by aaronjudd** [comment]
For theme information see:
https://github.com/reactioncommerce/reaction-core/blob/development/docs/themes.md

When using the development branch try testing with just the `development` branches "reaction-core-theme, reaction-core" packages, and also make sure you have pulled the `reaction` development branch as well.  (all the packages have to be `development`, when using the `development` branch).

Also try `meteor remove audit-argument-checks`.  Since you commented out the "check" statement, this might stop the validation error.

**Comment by psy21d** [comment]
meteor remove audit-argument-checks:
audit-argument-checks: removed dependency

I20150301-02:56:06.392(3)? { _id: 'SMr4rhDFnYvFMtDTX',
I20150301-02:56:06.392(3)?   title: 'Basic Example Variant',
I20150301-02:56:06.393(3)?   price: '2022.44',
I20150301-02:56:06.393(3)?   inventoryManagement: true,
I20150301-02:56:06.394(3)?   inventoryPolicy: true,
I20150301-02:56:06.394(3)?   updatedAt: Thu Apr 03 2014 23:46:52 GMT+0300 (MSK),
I20150301-02:56:06.394(3)?   createdAt: Thu Apr 03 2014 23:46:52 GMT+0300 (MSK),
I20150301-02:56:06.394(3)?   weight: 35,
I20150301-02:56:06.395(3)?   inventoryQuantity: 45,
I20150301-02:56:06.395(3)?   metafields: [ { key: null, value: null } ],
I20150301-02:56:06.396(3)?   taxable: false,
I20150301-02:56:06.397(3)?   parentId: '6qiqPwBkeJdtdQc4G',
I20150301-02:56:06.398(3)?   optionTitle: 'Yepp' }
I20150301-02:56:06.401(3)? Exception while invoking method 'updateVariant' Error: Match error: One or more properties do not match the schema.
I20150301-02:56:06.401(3)?     at [object Object].SimpleSchema.condition (packages/aldeed:simple-schema/simple-schema.js:600:1)
I20150301-02:56:06.401(3)?     at checkSubtree (packages/check/match.js:220:1)
I20150301-02:56:06.401(3)?     at check (packages/check/match.js:32:1)
I20150301-02:56:06.402(3)?     at [object Object].Meteor.methods.updateVariant (packages/reactioncommerce:core/server/methods/products/products.coffee:74:5)
I20150301-02:56:06.402(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
I20150301-02:56:06.402(3)?     at packages/ddp/livedata_server.js:648:1
I20150301-02:56:06.403(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-02:56:06.403(3)?     at packages/ddp/livedata_server.js:647:1
I20150301-02:56:06.403(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-02:56:06.403(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150301-02:56:06.403(3)? Sanitized and reported to the client as: Match failed [400]
I20150301-02:56:06.404(3)?

**Comment by psy21d** [comment]
after #check removed all works fine.
You save me! Thanks a lot!

**Comment by psy21d** [comment]
http://127.0.0.1:3000/product/new

  updateProductField: (productId, field, value) ->
    console.log productId
    check productId, String
    check field, String
    check value, String

I20150301-19:58:25.950(3)? null
I20150301-19:58:26.259(3)? Exception while invoking method 'updateProductField' Error: Match error: Expected string, got object
I20150301-19:58:26.259(3)?     at checkSubtree (packages/check/match.js:159:1)
I20150301-19:58:26.259(3)?     at check (packages/check/match.js:32:1)
I20150301-19:58:26.259(3)?     at [object Object].Meteor.methods.updateProductField (packages/reactioncommerce:core/server/methods/products/products.coffee:215:5)
I20150301-19:58:26.260(3)?     at packages/check/match.js:109:1
I20150301-19:58:26.262(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-19:58:26.262(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150301-19:58:26.263(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150301-19:58:26.263(3)?     at packages/ddp/livedata_server.js:648:1
I20150301-19:58:26.263(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-19:58:26.263(3)?     at packages/ddp/livedata_server.js:647:1
I20150301-19:58:26.264(3)? Sanitized and reported to the client as: Match failed [400]

productId is null

**Comment by psy21d** [comment]
http://127.0.0.1:3000/product/someproduct

updateProductTags: (productId, tagName, tagId, currentTagId) ->
    check productId, String
    check tagName, String
    check tagId, Match.OneOf(String, null)
    console.log currentTagId
    check currentTagId, Match.Optional(String)

I20150301-20:09:16.552(3)? null
I20150301-20:09:16.677(3)? Exception while invoking method 'updateProductTags' Error: Match error: Failed Match.OneOf or Match.Optional validation
I20150301-20:09:16.678(3)?     at checkSubtree (packages/check/match.js:244:1)
I20150301-20:09:16.679(3)?     at check (packages/check/match.js:32:1)
I20150301-20:09:16.679(3)?     at [object Object].Meteor.methods.updateProductTags (packages/reactioncommerce:core/server/methods/products/products.coffee:236:5)
I20150301-20:09:16.679(3)?     at packages/check/match.js:109:1
I20150301-20:09:16.679(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-20:09:16.680(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150301-20:09:16.680(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150301-20:09:16.680(3)?     at packages/ddp/livedata_server.js:648:1
I20150301-20:09:16.680(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-20:09:16.681(3)?     at packages/ddp/livedata_server.js:647:1
I20150301-20:09:16.681(3)? Sanitized and reported to the client as: Match failed [400]
I20150301-20:09:16.681(3)?

return Meteor.call("updateProductTags", selectedProductId(), val, this._id, currentTag, function(error, result) {
        if (error) {
          console.log("Error updating header tags", error);
        }

selectedProductId()
"t6JkkTihjsfkkjo27"

 Session.get("currentTag");
undefined

And more more errors.
It is error hell.
I can not do something with this.

Many Id's Is null, can not work with products at all.
Can not update tags, can not update images, fields, can not normally create products.

**Comment by psy21d** [comment]
Thank you a lot for the answers! I got email.

We can reproduce this bug simple, I work tonigt now (+4.00 GMT).
To reproduce that situation need install them by default-setup unstruction.
https://github.com/reactioncommerce/reaction-core/blob/master/docs/packages.md

My server:
(OpenSSH_6.0p1 Debian-4+deb7u2)
root@nodejs:~# node -v
v0.10.28

**Comment by aaronjudd** [comment]
@psy21d please pull the latest, this should be resolved now.

**Comment by psy21d** [comment]
AaaaHHhh! It Is Working! 

Thank you you save my ass.

**Comment by psy21d** [comment]
https://github.com/reactioncommerce/reaction/issues/328
