### ISSUE TITLE
Should be able to create products or modify configuration in marketplace shop when set to "new"

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3253]
Not sure this is really a "bug" so much as a "feature that doesn't work as expected" but writing as a bug for clarify.

### Expected behavior
Should be able to fully set up a shop including creating product before making the shop "active/visible". This is probably the most common use case.

### Actual behavior
All URL's that need the shop slug return `undefined` so you can't create a product or modify the configuration

### Steps to reproduce the behavior
1. Invite a shop owner but don't set the shop to "active".
1. Login as the shop owner and try to configure your shop or create a product
1. Observe the neither work
1. Observe that your shop is not visible in the drop down

Probably due to the work that was done for "disable shop". The publication probably needs to be updated to display shops/products when you are the shop admin.

### Versions
```
Node: 7.10.0
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch:master
Docker: 17.09.0-ce
```

**Comment by aldeed** [comment]
No longer an issue
