### ISSUE TITLE
Marketplace search

### ISSUE THREAD

**Issue by speedingdeer** [reactioncommerce/reaction#3254]
I have marketplace with three shops. When I search it always search ONLY within primary search context. I've tracked the search and the shopId is given as parameter but there is no option / navigation to change this context or search over all products.

### Expected behavior

When I search I search over all products or in the specific shop context.

### Actual behavior

Search modal always searches in the primary shop context.

### Steps to reproduce the behavior

- Create marketplace 
- Add and activate shop
- Add and publish products to marketplace shop
- Go to search and try to search for product from marketplace shop

### Versions

Node: 8.1.4
NPM: 5.0.3
Meteor Node: 4.8.5
Meteor NPM: 4.6.1
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch: master
Docker: 17.09.0-ce

**Comment by speedingdeer** [comment]
I'm happy to try to resolve it myself and send PR but I need you to guide a bit in terms of what that search strategy should be etc. I'm missing some context.

**Comment by aaronjudd** [comment]
@zenweasel you architected most of the search, maybe you can add some guidance here?

**Comment by zenweasel** [comment]
Sorry for the delay in responding to this. Meant to dive into this and couldn't find the time.

I don't know if ever got updated for Marketplace/Multi-shop.

In terms of the search strategy, I think the only wrinkle over what is there it the search needs to be shop specific except for the primary shop which should see everything. Just need to add some code that checks if you are in the primary shop then drop the shopId from the search parameter. The same should be done for account and order search as well.

**Comment by speedingdeer** [comment]
I've checked history and I don't think they were any significant changes for search in marketplace.

The search is hardcoded to use primary store always. Passing the shopId is fine, I'm just not sure if navigation works consistently. There might be several issues and the search is just at the end on the whole thing.

**Comment by impactmass** [comment]
Note: PR for this already approved in #3415, pending next release

**Comment by codejockie** [comment]
Fixed.

**Comment by spencern** [comment]
Resolved in release [v1.6.4](https://github.com/reactioncommerce/reaction/releases/tag/v1.6.4)
