### ISSUE TITLE
Eliminating dead code:  adminControlsFooter field in LayoutStructure schema.

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3256]
This is not a bug.

I've found that the layout registry has a property called `adminControlsFooter`. This field is found many times in the code base, yet it's not used anywhere.

I'd consider this a candidate to clean up the codebase.  It was used to allow customization of Blaze templates once upon a time, but I think it's not necessary any more. Especially when considering the new component API.

**Comment by prinzdezibel** [comment]
If you agree, please assign back to me for implementation.

**Comment by zenweasel** [comment]
@prinzdezibel I think we can add this ticket to this Epic for removing all Blaze. (If you don't have the ZenHub Chrome extension installed, you will probably want to do that)

**Comment by zenweasel** [comment]
@prinzdezibel What's the status on this? If you aren't actively working on this can you unassign?

**Comment by prinzdezibel** [comment]
Not working on that, because it was moved to backlog. Unassigning.

**Comment by prinzdezibel** [comment]
Going to close this, @zenweasel.  Feel free to re-open, if there's something that needs to be done on this.
