### ISSUE TITLE
Error Inviting New Organisation Member

### ISSUE THREAD

**Issue by Fixdit** [reactioncommerce/reaction#326]
When adding a new member to the organisation I receive the following error from the logs.

Error:
```
Exception while invoking method 'inviteShopMember' TypeError: Cannot call method 'shopMemberNotification' of undefined
    at [object Object].Meteor.methods.inviteShopMember (packages/reactioncommerce:core/server/methods/accounts/accounts.coffee:92:19)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
```

**Comment by aaronjudd** [comment]
@Fixdit thanks for the report.  Might be a failure to get email server credentials, but I've not looked into it yet.

**Comment by Gouthamve** [comment]
reactioncommerce/reaction-core#104

Even now I am not able to send the email. I am getting the following:

```html
I20150310-23:24:17.159(5.5)? ====== BEGIN MAIL #0 ======
I20150310-23:24:17.160(5.5)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
I20150310-23:24:17.161(5.5)? MIME-Version: 1.0
I20150310-23:24:17.161(5.5)? From: "Admin" <cs14btech11014@iith.ac.in>
I20150310-23:24:17.161(5.5)? To: gouthamve@gmail.com
I20150310-23:24:17.161(5.5)? Subject: You have been invited to join the REACTION staff
I20150310-23:24:17.161(5.5)? Content-Type: text/html; charset=utf-8
I20150310-23:24:17.161(5.5)? Content-Transfer-Encoding: quoted-printable
I20150310-23:24:17.161(5.5)? 
I20150310-23:24:17.163(5.5)? <template name=3D"shopMemberNotification">
I20150310-23:24:17.163(5.5)? <div style=3D"margin:0;padding:0 0 30px =
I20150310-23:24:17.163(5.5)? 0;background:#fff;line-height:24px;text-align:left">
I20150310-23:24:17.163(5.5)? =20=20<div class=3D"adM">
I20150310-23:24:17.171(5.5)? =20=20</table>
.
.
Lots of Template Content
.
.
I20150310-23:24:17.172(5.5)? </div>
I20150310-23:24:17.172(5.5)? </template>
I20150310-23:24:17.172(5.5)? ====== END MAIL #0 ======
```

I got this after I have configured my SMTP from reaction core. And then I went back `meteor reset` and tried using the settings.json. Even after that I am getting the same. I am using Mandrill for my SMTP.

**Comment by spencern** [comment]
I was having this issue too and had to export my MAIL_URL var.
`export MAIL_URL="smtp://user@domain.com:PASSWORD@smtp.domain.com:PORT`

I was unable to succeed in sending mail with the SMTP settings in the reaction-core admin panel.

**Comment by aaronjudd** [comment]
I'm updating both how fixture settings are loaded, and the admin panel in the guest-checkout branch. In the meantime, yes - use the env settings.

**Comment by Gouthamve** [comment]
I am sorry, but how do I export? I am getting this error:
```
While building package reactioncommerce:core:
   <runJavaScript-42>:148:11: server/fixtures.coffee:201: reserved word "export" (compiling server/fixtures.coffee) (at
   handler)
```

**Comment by spencern** [comment]
You need to run it in your shell. If you are on Unix/Linux you should be able to run it as I have in the comment:

`$ export MAIL_URL="smtp://user@domain.com:PASSWORD@smtp.domain.com:PORT`
`$ meteor`

**Comment by aldeed** [comment]
@aaronjudd, so you are fixing this one? Should it be assigned to you and in progress?

**Comment by aaronjudd** [comment]
@aldeed yes fixing now.

**Comment by hengsoheak** [comment]
Can I use Reactioncommerce for products website ecommerce application right?

**Comment by zenweasel** [comment]
@hengsoheak Yes
