### ISSUE TITLE
Merchant shops' email as a switch 

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#3265]
### Expected behavior
- Have a switch in marketplace where one can specify if they want emails from a merchant shop to be sent from either; the merchant shops owner's email or the marketplace shop owner's email.

Possible UI for this:
![pasted image at 2017_11_08 09_42 am](https://user-images.githubusercontent.com/19430074/32613174-398e24f8-c57b-11e7-853c-9cbd26290e58.png)

### Actual behavior
- Emails sent from a merchant shop are currently being sent from the marketplace owner's email address.

### Steps to reproduce the behavior
- Create a merchant shop 
- Perform an action that sends an email. E.g. Invite a shop manager
- Review to see that email is sent from the marketplace owner's email

### Versions
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.0
Reaction: 1.5.4
Reaction branch: master
Docker: 17.03.1-ce

**Comment by aldeed** [comment]
Closing this since marketplace is no longer a core plugin
