### ISSUE TITLE
Check to make sure S3 config exists in CircleCI config

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3277]
### Expected behavior
When a build completes on CircleCI, it should not fail if the S3 config does not exist.

### Actual behavior
The CircleCI build fails with the error `aws: error: argument --region: expected one argument` which causes the build to fail.
![image](https://user-images.githubusercontent.com/1203639/32637308-50be90ea-c576-11e7-9afe-17706ce81f47.png)

### Steps to reproduce the behavior
Perform a `master` branch CI build in a repo that does not have S3 configuration setup

### Versions
```
Node: 8.9.0
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch: master
Docker: 17.06.2-ce
```

**Comment by Akarshit** [comment]
Closed in #3278
