### ISSUE TITLE
Drop-Down menu dropping-up

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#3283]
### Expected behavior
When clicking the drop-down menu to invite a user to an admin group (in Accounts dashboard) I expect the menu to drop-down

NB: This also happens when you have marketplace turned on (in the Marketplace shops panel)

### Actual behavior
When you click the drop-down menu, the menu drop-up instead

![screenshot 2017-11-14 15 44 23](https://user-images.githubusercontent.com/5229321/32786084-4ff843be-c953-11e7-83a9-c2cdc77d5b78.jpg)

### Steps to reproduce the behavior
Log-in as admin, click on accounts, try and change type of user you are inviting

Node: 7.10.0
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.21.2
Reaction: 1.5.8
Reaction branch: master

**Comment by Akarshit** [comment]
Not able to reproduce this. It would be cool if you could post a screenshot of the drop-down that is being talked about.

**Comment by impactmass** [comment]
Thanks @Akarshit . I've updated the ticket description

**Comment by Akarshit** [comment]
Fixed in #3292

**Comment by impactmass** [comment]
Fixed in #3292
