### ISSUE TITLE
Non guest users should not have `guest` or `anonymous` roles

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3286]
When users are promoted or when admins/owners are created the `guest` and `anonymous` roles should be removed.

**Comment by Akarshit** [comment]
@spencern I was working on this and found [this](https://github.com/reactioncommerce/reaction/blob/master/server/api/core/core.js#L640)
Is that outdated?

**Comment by spencern** [comment]
@Akarshit I apologize I haven't had a chance to respond to this question yet. This issue may have some deep complications, I'll try to explain in depth tomorrow.

**Comment by aldeed** [comment]
"guest" and "anonymous" roles are no longer used in recent versions
