### ISSUE TITLE
Should CVV has type=password?

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#3287]
Many sites take CVV input as `type=password`. Would it make sense to do this to in reaction too?

**Comment by zenweasel** [comment]
In my opinion no, I personally find this really annoying, but I do see on a lot of sites.

**Comment by aaronjudd** [comment]
In my opinion, no, agree with @zenweasel and quick google of the topic, leans toward not masking.  I'll close this unless others want to revisit.
