### ISSUE TITLE
ReactionAvatar on profile page is not showing Instagram profile image when instagram is used as the login

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3289]
Instagram Profile pictures are not being used for ReactionAvatar on the users account profile page (http://localhost:3000/account/profile).

<img width="485" alt="account_profile" src="https://user-images.githubusercontent.com/4482263/32798873-ded58476-c92a-11e7-8dce-b8e324fa2df3.png">

### Expected behavior
On a users account profile page, if a user is logged into Reaction via Instagram, ReactionAvatar should show the users Instagram profile image

### Actual behavior
On a users account profile page, the `ReactionAvatar` is showing a Gravatar based on the users email address, not the users instagram profile image. If the user does not have a Gravatar linked with with email address from Instagram, it shows a placeholder.

### Steps to reproduce the behavior
- Login via instagram
- Visit your account page
- See your instagram profile picture is not the 

### The Fix
Pass the instagram profile image data (stored on a user profile) into the `src` prop of ReactionAvatar.

**Comment by wackywombaat12** [comment]
I am currenly working on this issue :)

**Comment by wackywombaat12** [comment]
I can't even get the gravatar to show when logged in with Instagram. 
My version:

Node: 7.7.3
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.22.5
Reaction: 1.5.8
Reaction branch: master

I have created an issue for this at #3294 
Is there something I am missing?

**Comment by kieckhafer** [comment]
Are there any log errors? Something should be showing up, a default at the very least.

**Comment by wackywombaat12** [comment]
Yeah the log says that 'address' in undefined
`Exception in template helper: TypeError: Cannot read property 'address' of undefined
    at Object.displayEmail (http://localhost:3000/app/app.js?hash=7232200f6b9a7b90ef91b0c2f2275f9604be22cb:41177:31)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3051:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1715:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3102:27
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:172:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:106:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:110:39)
    at Blaze.View._render (http://localhost:3000/app/app.js?hash=7232200f6b9a7b90ef91b0c2f2275f9604be22cb:40781:24)`

**Comment by kieckhafer** [comment]
Looks like the user has not yet set up an address. Seems like we need to add a check to see if address is defined or not before passing it in.

**Comment by wackywombaat12** [comment]
The instagram social login didn't pull in my email either which seems to be causing problems as shown in #3294

**Comment by kieckhafer** [comment]
Yeah, that definitely could be it - we should add a check for that though, like mentioned above, something to make sure it got pulled in, and if it didn't, show something default.

**Comment by wackywombaat12** [comment]
Sort of like a default email address? IE example@domain.com

**Comment by kieckhafer** [comment]
No, just a default blank string for the email if it's not there, it should show just initials. `ReactionAvatar` is a wrapper around React Avatar, you can see the props that get passed to it here: https://github.com/Sitebase/react-avatar

**Comment by zenweasel** [comment]
Closed via #3301
