### ISSUE TITLE
Re-enable Jest tests for React components

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3290]
When we added the `registerComponent` API we had to scrap the Jest testing that we just had started and it has not been put back in place. Unit testing of React components is one of the big wins of moving to components, so we should be trying to get this back in place as an engineering practice.

**Comment by aaronjudd** [comment]
Agreed, do you have any suggestions for the next steps to get this going again?

**Comment by zenweasel** [comment]
@jshimko Do you remember exactly what the challenge with this was? I think since now that we are pulling components dynamically, we needed to create some sort of framework to stub that out.

Really, we should be able to test real **components** without mocking out anything besides the props so maybe this can be the start of trying to cleanup/refactor some of the components that mix data and presentation.

Should we pick a simple component as a place to start? Like `<Icon>` or something similar? We could also combine this with trying to move some of these components to npm modules as we should be able to test them there with no Reaction-specific dependencies. Maybe combine with #3202?
