### ISSUE TITLE
Account page not working when logged in with Instagram

### ISSUE THREAD

**Issue by wackywombaat12** [reactioncommerce/reaction#3294]
Form below Name and Gravatar not showing when logged in with Instagram.

### Expected behavior

<img width="912" alt="screen shot 2017-11-15 at 9 51 18 pm" src="https://user-images.githubusercontent.com/5836953/32832840-fcf69496-ca50-11e7-8361-590abaaffbb8.png">

Should display the form and Gravatar on the account page.

### Actual behavior
<img width="789" alt="screen shot 2017-11-15 at 9 56 23 pm" src="https://user-images.githubusercontent.com/5836953/32832866-120364b8-ca51-11e7-9ad9-4b1bd37e8f6b.png">

Does not display the fields and Gravatar

### Steps to reproduce the behavior

- Login via instagram
- Visit your account page
- See that form and Gravatar not showing

### Versions
Node: 7.7.3
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.22.5
Reaction: 1.5.8
Reaction branch: master

**Comment by wackywombaat12** [comment]
It seems this is happening due to the Instagram Social login not grabbing an email address for my account as you can see in MongoDB.
<img width="747" alt="screen shot 2017-11-15 at 10 45 21 pm" src="https://user-images.githubusercontent.com/5836953/32834473-d6eb7914-ca56-11e7-8084-d067c7fd9f55.png">

**Comment by zenweasel** [comment]
Closed via #3301
