### ISSUE TITLE
Opening up admin sidebar when a product is clicked should not take many seconds 

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#3297]
### Expected behavior
Opening up admin sidebar when a product is clicked should not take many seconds 

### Actual behavior
There is an observable lag that happens when (as an admin) a product is clicked on the product grid. It takes about 5 - 7 secs from the time the product is clicked to the time the admin sidebar opens up. (NB: This was noticed while doing some testing on a shop with ~4k products, so possibly performance related)

### Steps to reproduce the behavior
- On a fresh setup, import a bunch of products. (I had ~4k when the behavior was noticed)
- Go to the product grid (either on the homepage or store page)
- Click on a product, then notice it takes a few seconds (without any feedback) before the sidebar pops out

### Versions
Node: 7.10.0
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.21.2
Reaction: 1.5.8
Reaction branch: master

**Comment by spencern** [comment]
@Akarshit is your PR https://github.com/reactioncommerce/reaction/pull/3463 working on this issue?

**Comment by spencern** [comment]
@Akarshit what's the status on this issue?

**Comment by Akarshit** [comment]
@spencern The PR would fix a small part of this, but not the whole thing.
I haven't tested with huge no. of products, but I will we working on this.

Will update once I find anything.

**Comment by zenweasel** [comment]
@Akarshit Can you link your PR properly? Also, I feel like the PR does in fact solve this issue? Can you explain how it doesn't and what you are waiting for? This should take top priority since it's a performance issue in the sprint.

**Comment by Akarshit** [comment]
@zenweasel The admin sidebar lags because many `Tracker.autorun` are executed before it is opened. With the single product configuration, 50% of the lag is in reloading translation(which #3463 fixes) while the rest is re-rendering many components.

I will have to check which components are getting re-rendered again and why.

**Comment by Akarshit** [comment]
I tried looking through the components but couldn't find any re-rendering that wasn't supposed to happen.

**Comment by zenweasel** [comment]
This ticket is pending the merge of this PR: https://github.com/reactioncommerce/reaction/pull/3463
