### ISSUE TITLE
Missing display of priceRange in product Detail page.

### ISSUE THREAD

**Issue by ushadev** [reactioncommerce/reaction#3303]
### Expected behavior
When we click on the products and route to the specific product detail page of the product we should see the priceRange of the product displayed. no matter how many times we select different products and go to the product detail page.

### Actual behavior
suppose 3 products are added to Shop tag. we logout of the admin. we navigate to the Shop Tag and click on any product. it leads to the product detail page of that specific product. the props(priceRange) is passed and we can see the priceRange in the product detail page.  now then on if we select any other product from the Shop tag and go to the product detail page the props (priceRange) is not passed and the priceRange is not displayed.  Only when we refresh the page the props (priceRange) is getting passed and then we can see the priceRange.

### Steps to reproduce the behavior

1.) Create 3 products under Shop tag.
2.) Signout.
3.) Go to Shop Tag. click on any product. it leads to the product Detail page of the respective product. here you can see the priceRange displayed.
4.) Go back to the Shop Tag and select a different Product. it leads to the product Detail page . here you can't see the priceRange value of the product. (this is the bug the props are not getting passed for the priceRange) but if you refresh the page (the props get passed and) the priceRange value is displayed.

### Versions
reaction 1.5 and above

**Comment by zenweasel** [comment]
I think this issue is related to: https://github.com/reactioncommerce/reaction/issues/3227 where the variant is not selected so the image/price is not shown unless you select a variant

**Comment by ushadev** [comment]
In the case i am referring to, i dont have any variants for my products, then it would be just the Top level variant for all my products.  so i need not select the variant.

**Comment by ushadev** [comment]
yes you are right the issue i raised is related to :#3227.  Got the fix pulled and tested and it worked. Thankyou.

**Comment by codejockie** [comment]
@zenweasel can this issue be closed since issue #3227 which is related to this one has been fixed with #3267?

**Comment by zenweasel** [comment]
@codejockie Have you verified that it's fixed?

**Comment by codejockie** [comment]
@zenweasel No I haven't but can verify it.

**Comment by codejockie** [comment]
@zenweasel verified, fixed.

**Comment by zenweasel** [comment]
Resolved via #3267
