### ISSUE TITLE
API + pattern for endpoint handling

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3304]
As we are expecting to be building a lot more connectors that rely on interfacing with endpoints like webhooks we should look at modularizing the handling and standardize on a documented pattern.  

The larger scope architectural task, before proposing a solution should also be to review and investigate solutions that help move us toward decoupling our packages into independent services.
 
 - messaging solutions (kafka, kinesis, rabbitmq, redux-streams)
 - graphql subscriptions
 - hey, even google-spreadsheets api might find it's home here

A more immediate task could be to create a standard pattern+method for webhook implementation, so that all the connectors handle this the same way.

As a documentation task, it could be a good topic to consolidate with docs also covering GraphQL([reaction-api-base](https://github.com/reactioncommerce/reaction-api-base)) and [REST](https://github.com/stubailo/meteor-rest) usage/patterns.

**Comment by aldeed** [comment]
A lot of this has been done, some is left to do, but in general this isn't an actionable issue, so I'm closing it.
