### ISSUE TITLE
Developer Docs - enhance with Class diagrams, method docs, schema docs

### ISSUE THREAD

**Issue by psy21d** [reactioncommerce/reaction#331]
Can you publish all classes reaction, reaction-core?
How can print it from sources? 

Thanks!

**Comment by aaronjudd** [comment]
I'm looking at implementing https://github.com/raix/docmeteor so that we can publish class/method docs. In the meantime most of the major methods have been documented here: https://github.com/reactioncommerce/reaction-core/blob/development/docs/methods.md

**Comment by psy21d** [comment]
Need to write new methods and fields for my projects on reactioncommerce, and fix some bugs.
I know, reactioncommerce not stable now but I sure this project have good future.

**Comment by aaronjudd** [comment]
Closing. Please review docs.reactioncommerce.com for new doc structure.  For API docs, WIP, see: https://github.com/reactioncommerce/redoc/issues/7

**Comment by psy21d** [comment]
OK so good!
