### ISSUE TITLE
Wrong image displayed on Grid Settings 

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#3310]
### Expected behavior

- When you select a product on the product grid, the image of the product should be the most current published/uploaded image of selected product.

### Actual behavior

- Image displayed for selected product is the first image uploaded for the product.

### Steps to reproduce the behavior

- Go to PDP page 
- Drag and drop an image, publish it
- Remove image and publish changes
- Upload a new image for product and publish
- Navigate to home page and select the product
- Notice that the image on the grid settings panel is different from the current image of product on the product grid

### Versions
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.21.2
Reaction: 1.5.8
Reaction branch: master
Docker: 17.03.1-ce

**Comment by spencern** [comment]
Resolved by #3311
