### ISSUE TITLE
Tax is not shown in Completed Order page when using Avalara

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3317]
### Expected behavior
Taxes should display as part of the order summary

### Actual behavior
They do not

### Steps to reproduce the behavior
1. Enable Avalara as Tax provider
1. Checkout as normal with an address that would be charged tax
1. Observe tax charged during checkout
1. Observe tax does not display on completed order page

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.22.5
Reaction: 1.5.8
Reaction branch: brent-fix-issue-2718 (master)
Docker: 17.09.0-ce
```

**Comment by Akarshit** [comment]
Did a quick and dirty fix for this in #3326. Have some doubts that I asked there.
