### ISSUE TITLE
Brazilian CPF support

### ISSUE THREAD

**Issue by mschipperheyn** [reactioncommerce/reaction#3318]
Brazilian shops are legally required to record and process the CPF (Brazilian Social Security number) of a consumer. Brazilian consumers should therefore add their cpf as part of the checkout process. 

A CPF number is usually entered in a masked way e.g. 111.222.000-80. Brazilian consumers are very used to input masked data entry. Some may just add the number, expecting it to be formatted. Some may actually enter the dots and hyphen. A CPF number can be validated with the following formula: 

```
function validaCPF(cpf)
  {
    var numeros, digitos, soma, i, resultado, digitos_iguais;
    digitos_iguais = 1;
    if (cpf.length < 11)
          return false;
    for (i = 0; i < cpf.length - 1; i++)
          if (cpf.charAt(i) != cpf.charAt(i + 1))
                {
                digitos_iguais = 0;
                break;
                }
    if (!digitos_iguais)
          {
          numeros = cpf.substring(0,9);
          digitos = cpf.substring(9);
          soma = 0;
          for (i = 10; i > 1; i--)
                soma += numeros.charAt(10 - i) * i;
          resultado = soma % 11 < 2 ? 0 : 11 - soma % 11;
          if (resultado != digitos.charAt(0))
                return false;
          numeros = cpf.substring(0,10);
          soma = 0;
          for (i = 11; i > 1; i--)
                soma += numeros.charAt(11 - i) * i;
          resultado = soma % 11 < 2 ? 0 : 11 - soma % 11;
          if (resultado != digitos.charAt(1))
                return false;
          return true;
          }
    else
        return false;
  }
```

This is a feature our team might be able to add early 2018.

**Comment by zenweasel** [comment]
@mschipperheyn This should be a step you should be able to add to the checkout workflow in your custom plugin(s).

https://docs.reactioncommerce.com/reaction-docs/master/plugin-workflow-7

**Comment by mschipperheyn** [comment]
Ok, this might be a nice one for me to get comfortable with the platform on.

**Comment by aldeed** [comment]
The recommendation for this in 2.0.0 would be to customize the storefront form and use a custom plugin on the API side to extend the Order schema to store this. Alternatively, orders have a `customFields` object you can use.
