### ISSUE TITLE
Page Title for Index page shows product title

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#332]
When we navigate back from a product that has no handle tag to the main page, we see the product title on the tab. Minor issue but might cause problems for SEO.

![screen shot 2015-03-05 at 4 50 05 pm](https://cloud.githubusercontent.com/assets/7354143/6504001/487bcb82-c358-11e4-865e-0c25352cb454.png)
![screen shot 2015-03-05 at 4 50 12 pm](https://cloud.githubusercontent.com/assets/7354143/6504002/4f87d4ac-c358-11e4-9f83-d8df68d6d8c4.png)

**Comment by aaronjudd** [comment]
@Gouthamve I've seen this, thanks for creating the issue.
