### ISSUE TITLE
Bug: Merchant Shop Settings from Profile Menu

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#3336]
### Background
When opening Shop Settings from the Profile drop-down menu, the Shop Settings panel has a few options that do not exist when you open the Shop > General Panel. Furthermore, the Base Currency, Base Unit of Measure, and Base Unit of Length have no options, preventing form submission.

### Expected behavior
🤔  I'm not sure.
There are a few options:

1. Populate those `<select>` fields, allowing Merchant Shops to have different settings than the Primary Shop.
2. Remove Shop Settings from the Profile drop-down (since it already exists in the right-navigation)
3. Hide the Base Currency, Base Unit of Measure, and Base Unit of Length options (matching the panel displayed from the right-navigation)

### Steps to reproduce the behavior
Profile Menu Display:
![image](https://user-images.githubusercontent.com/1158287/33083563-af6c2680-cead-11e7-82b6-debc0d501fc7.png)

(which displays)
<img width="592" alt="screen shot 2017-11-21 at 11 18 47 am" src="https://user-images.githubusercontent.com/1158287/33083609-d3ab318a-cead-11e7-9a7f-4e81d242c1c4.png">

(and on form submission)
![image](https://user-images.githubusercontent.com/1158287/33084436-fab80d6e-ceaf-11e7-94c1-4585a8be8fa4.png)

#### Right-Navigation Display
... as opposed to
![image](https://user-images.githubusercontent.com/1158287/33085088-a89dd7a0-ceb1-11e7-84f7-74b45daeb41c.png)

(which displays)
![image](https://user-images.githubusercontent.com/1158287/33085151-d8f342f0-ceb1-11e7-8c27-1209f5f6a6fd.png)

### Versions
has previously existed, but confirmed the behavior exists in v1.5.9

**Comment by codejockie** [comment]
@pmn4 are you logged in as admin or a shop owner?

**Comment by zenweasel** [comment]
@spencern @rymorgan  Is there a point in having the Shop settings duplicated in the Profile dropdown? Was this on purpose? Should we just remove it from the dropdown?

**Comment by rymorgan** [comment]
@zenweasel Yes, I think it should be removed from the drop-down. It only shows up in the dropdown when marketplace is on. I'm not sure what @spencern 's thinking was on including the localization stuff under shop settings. Elsewhere we do it under localization, and I think we should be consistent. The only use case I can think of here would be for a marketplace wide globally set localization vs each store settings on their own. But, again, not sure why you'd need that in the dropdown or why the dropdown would show different settings vs the icon navigation bar.

**Comment by Akarshit** [comment]
@spencern Is it OK if I remove the `Shop Settings` from the profile drop-down?

**Comment by prinzdezibel** [comment]
Right now, the link from the dropdown is leading to a differnet form than the one coming from dashboard.  It does feature fields the other doesnt' have , like "allow guest checkout"

When disabling it, those fields should be migrated to the other form.

There's a separate ticket for that: https://github.com/reactioncommerce/reaction/issues/3489

**Comment by pmn4** [comment]
completely agree.
A shop should be able to set it's own base UOM, etc, so we should not lose track of those inputs. When doing those, can we add an input for assigning the `domain` attribute, or should that be a separate ticket?

**Comment by prinzdezibel** [comment]
@pmn4 Not sure that's possible for all settings, specifically the base currency. This would probably involve quite a bit of conceptual work to have different currencies for different merchants. For instance the cart order functions getSummary, getSubTotal and so on are not written in a way that allows items with different currencies to be summed up.

**Comment by pmn4** [comment]
of course... I think I have the blinders on from my project, which would not face this issue.

for background, my Marketplace is more like a white-label store provider, and less like Amazon.com. Separate stores sell their own products. i.e., you do not shop from the Primary Shop... the Primary Shop has been turned into a showcase for the Merchant Shops.

anyway, thanks for taking a look at this

**Comment by spencern** [comment]
@pmn4 @Akarshit @zenweasel I'm okay with removing the shop settings from the drop-down. I'm not certain how it ended up there in the first place and it does already exist in the dashboard sidebar. If we do need to have shop-specific currencies, we can enable this again, but I think there's more work we will need to do before that's a viable option.
