### ISSUE TITLE
service worker infinite loop at first installation

### ISSUE THREAD

**Issue by abelspry** [reactioncommerce/reaction#3338]
I'm installing reaction for the first time and I'm getting a blank initial page that loops infinitely.
This is the browser console:

```
-> Navigated to http://localhost:3000/
-> The script has an unsupported MIME type ('text/html').
-> service-worker.js Failed to load resource: net::ERR_INSECURE_RESPONSE
```
I had to manually unregister the `service-worker.js` file to see the homepage.

### Expected behavior
See the demo site

### Actual behavior
I see a blank page that continuously refresh itself, like in a redirection loop that does not end. 

### Steps to reproduce the behavior
- install all the requirements except for MongoDB
- install `reaction-cli` globally
- run `reaction init` > `cd reaction` > `reaction`
- open the browser at `localhost:3000`

### Versions
MacBook Pro, early 2015
macOS Sierra (10.12)
Chrome v. 62.0.3202.94 (Official Build) (64-bit)

Node: 8.3.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.23.1
Reaction: 1.5.9
Reaction branch: master
Docker: 17.09.0-ce

Let me know if I'm doing something wrong or you need more info.
Thanks.

**Comment by zenweasel** [comment]
Can't reproduce and no follow-up from reporter.
