### ISSUE TITLE
[Marketplace] Setting up payment to other paypal accounts

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#334]
Hi,

Is there a possibility with reaction paypal to change the direction of the payment and send payments from the account specified in the package settings towards others, something like a refund or paying sellers their fees?

Thanks!

**Comment by spencern** [comment]
This is important for any type of marketplace shop. I'd like to have it implemented with Stripe as well. I've been looking into Stripe Connect which can do this, but haven't started building it out yet.

**Comment by boboci9** [comment]
Does anyone have any ideas about how this could be implemented?

**Comment by spencern** [comment]
I've started casually looking into it with Stripe. Stripe Connect is built for this purpose. Not sure how it would be done with paypal.

**Comment by ChadMartinson** [comment]
Paypal has what's called Adaptive Payments. https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/  Maybe the administrator could have the option controlling the payees on product setup.  This could also be a way to integrate Affiliate marketing tools.

**Comment by spencern** [comment]
Existing Solutions for this problem that just need integrations built:
* [ ] [Dwolla](https://www.dwolla.com/ach/marketplace-payouts/)
* [ ] [Stripe Connect](https://stripe.com/blog/instant-payouts-for-marketplaces)
* [ ] [Paypal](https://developer.paypal.com/docs/classic/use-cases/uc_marketplace-payouts/)
* [ ] [Braintree Marketplace](https://www.braintreepayments.com/products/braintree-marketplace)

**Comment by spencern** [comment]
Hey, we're going to leave the tag Pull Requests Encouraged and `needs-more-detail` on here, but we're going to close this issue because the requirements need to be defined better. If this is an issue that you would like to pursue, please create a new issue with more detail and more specific requirements and link to this old issue.
