### ISSUE TITLE
Console error for products without variants

### ISSUE THREAD

**Issue by kieha** [reactioncommerce/reaction#3349]
### Description

When you have a product with no variants, and you click on the product, the PDP may/may not load, and you get a browser console error.

(I discovered this issue while testing PR #3347)

### Expected behavior

When clicking on any product, the PDP of the product should load, and there should be no browser console errors.

### Actual behavior

When clicking on a product that has no variants, the PDP may/may not load, and you get the following browser console error:

```
TypeError: Cannot read property 'indexOf' of undefined
    at _variantIsSelected (products.js:84)
    at ReactiveDict.ReactionProduct.setProduct (products.js:169)
    at composer (productDetail.js:287)
    at tracker.js:37
    at Tracker.Computation._compute (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:339)
    at Tracker.Computation._recompute (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:358)
    at Object.Tracker._runFlush (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:532)
    at onGlobalMessage (meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:398)
```

### Steps to reproduce the behavior

- Create a new product
- Go to your database and delete the variant instance of the new product
- Visit the product grid and click on the product created above
- Observe the browser console error above

### Versions

Node: 9.2.0
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.22.5
Reaction: 1.5.10
Reaction branch: joykare-product-validation-fix
Docker: 1.13.0

**Comment by iakhator** [comment]
@kieha , I can't seem to reproduce this. whenever I delete the variant instance of the product and I try to reload the page before clicking it gives this  browser console error `isValid is undefined`.

**Comment by kieha** [comment]
@iakhator use the `joykare-product-validation-fix` branch to test as I pointed out because that branch/PR resolves the error you pointed out above.

**Comment by iakhator** [comment]
Sure, I am able to reproduce the error with my own branch. Though the error happen without refreshing the page. thanks.
