### ISSUE TITLE
Spiderable does not work

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#335]
When I do \_escaped_fragment\_ on my reaction shop, I got:
```javascript
I20150306-15:26:05.211(5.5)? spiderable: phantomjs not installed. Download and install from http://phantomjs.org/
W20150306-15:26:05.251(5.5)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20150306-15:26:05.251(5.5)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20150306-15:26:05.251(5.5)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
W20150306-15:26:05.252(5.5)? (STDERR)     at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
W20150306-15:26:05.252(5.5)? (STDERR)     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
W20150306-15:26:05.252(5.5)? (STDERR)     at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
W20150306-15:26:05.252(5.5)? (STDERR)     at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
W20150306-15:26:05.252(5.5)? (STDERR)     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
W20150306-15:26:05.252(5.5)? (STDERR)     at Object.router (packages/iron:router/lib/router.js:15:1)
W20150306-15:26:05.252(5.5)? (STDERR)     at next (/Users/goutham/.meteor/packages/webapp/.1.1.6.112vqtg++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20150306-15:26:05.252(5.5)? (STDERR)     at Object.Package [as handle] (packages/cfs:http-methods/http.methods.server.api.js:417:1)
```

After installing Phantom, I am still getting:

```javascript
I20150306-15:33:30.776(5.5)? spiderable: phantomjs failed: { [Error: Command failed: ] killed: false, code: null, signal: 'SIGKILL' } 
I20150306-15:33:30.776(5.5)? stderr: 
W20150306-15:33:30.812(5.5)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20150306-15:33:30.812(5.5)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20150306-15:33:30.813(5.5)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
W20150306-15:33:30.813(5.5)? (STDERR)     at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
W20150306-15:33:30.813(5.5)? (STDERR)     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
W20150306-15:33:30.814(5.5)? (STDERR)     at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
W20150306-15:33:30.814(5.5)? (STDERR)     at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
W20150306-15:33:30.814(5.5)? (STDERR)     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
W20150306-15:33:30.815(5.5)? (STDERR)     at Object.router (packages/iron:router/lib/router.js:15:1)
W20150306-15:33:30.815(5.5)? (STDERR)     at next (/Users/goutham/.meteor/packages/webapp/.1.1.6.112vqtg++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20150306-15:33:30.815(5.5)? (STDERR)     at Object.Package [as handle] (packages/cfs:http-methods/http.methods.server.api.js:417:1)
```

**Comment by kefirchik** [comment]
I can test it a bit later

**Comment by aaronjudd** [comment]
@Gouthamve how is that deployed? just a local `meteor run`?

**Comment by Gouthamve** [comment]
Yes, just a local `meteor`

**Comment by Gouthamve** [comment]
And I do have a proxy. But I am running locally so I don't think it should affect anything. But I think cfs:http-methods is causing that problem.

See: https://github.com/CollectionFS/Meteor-http-methods/issues/29

**Comment by aaronjudd** [comment]
Well, that sure looks like the issue.
There is this... https://github.com/meteor/meteor/issues/2429 which is why I asked about the environment. I wonder if the two issues are related.  

Any chance you are setting ROOT_URL?

**Comment by Gouthamve** [comment]
No, I am not setting the ROOT_URL anywhere. If it defaults to localhost it will be right.

**Comment by aaronjudd** [comment]
I've tested locally:  `curl http://localhost:3000/?_escaped_fragment_=` works fine there... so I think it's an environment issue with the proxy.  I've debugged this before - it's time consuming, but you can add the meteor spiderable package source into your `packages` and debug from there. I'm going to close this as I don't think this is reaction specific, but a `spiderable` issue.

**Comment by aaronjudd** [comment]
I forgot to mention that I published a "ongoworks:spiderable" package, that handles some of the proxy issues that I've encountered in docker deployments, but i'd almost be surprised if that worked since I haven't tested it with a release in a while.

**Comment by kefirchik** [comment]
I've just tested it at reactioncommerce demo site, and I've get `Internal server error`

**Comment by aaronjudd** [comment]
I don't think the demo reaction sites have spiderable installed, or at least not ongoworks:spiderable...  however reactioncommerce.com itself is using ongoworks:spiderable, 

see: https://reactioncommerce.com/?_escaped_fragment_=

**Comment by kefirchik** [comment]
Oh I see , thanks I'll check it out later a bit more deeper

**Comment by kefirchik** [comment]
I've spent many hours trying to figure out what is going wrong with phantomjs and spiderable, but with no luck :worried: 

I found disscussion here [iron-router#1192](https://github.com/iron-meteor/iron-router/issues/1192)

I think I would try to use [meteorhacks/meteor-ssr](https://github.com/meteorhacks/meteor-ssr) for seo, cause it is more native and lightweight solution

**Comment by chaksaray** [comment]
I have the same problem,, I spend long time to solve it, but i didn't get it fixed.

**Comment by zenweasel** [comment]
@chaksaray I've opened a new issue here: https://github.com/reactioncommerce/reaction/issues/1063 because that original issue is over a year old. Could you please let me know what you have tried and what your current environment is?
