### ISSUE TITLE
Spinning Container continually rerenders when clicking on navbar tag

### ISSUE THREAD

**Issue by Kazanz** [reactioncommerce/reaction#3352]
### Expected behavior

When clicking a tag in the navbar while in edit mode.  The page should load.

### Actual behavior

The page is stuck re-rendering the spinner container in a loop

Offending HTML:

```
<div>
    <div data-reactroot class="spinner-container spinner-container-lg>...</div>
</div>
```
Note there are no errors in the console on the client or backend.

### Steps to reproduce the behavior

1. Create a new product.
1. Pick the long layout.
1. Create a second product with a varient.
1. Archive the varient.
1. Click on the tag in the navbar that is a tag on the two items.

### Versions

Node: 7.6.0
NPM: 4.1.2
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.23.1
Reaction: 1.5.10
Reaction branch: master
Docker: 17.11.0-ce

**Comment by codejockie** [comment]
@Kazanz could you give better steps for reproducing this issue as I am unable to do that following the steps you provided.

**Comment by spencern** [comment]
This issue has been unable to be reproduced by @codejockie or @Akarshit. Closing.
Please re-open with more detail if you can reliably reproduce on the most current version.

**Comment by Kazanz** [comment]
To be honest I gave up on reaction commerce after this.

I will probably give it another go in the future when it will be more stable.
