### ISSUE TITLE
Firefox product performance issues

### ISSUE THREAD

**Issue by psy21d** [reactioncommerce/reaction#336]
In mozila firefox browser (my 36.0.1 and other versions) reactioncommerce make not-response.
When page reload, fields update all works so long and make browser unresponsible.
Goods images load partially and do not reload automatically

In chromium browsers all works fine and so fast (momentary).

**Comment by Gouthamve** [comment]
Hi, Even my firefox is 36.0.1 but I am not seeing any unresponsiveness.

My reaction is as smooth in firefox as it is in chrome or safari. That being said, I am testing with only 5 products.
How many products does your site have? And which specific fields are causing firefox to become unresponsive?

**Comment by psy21d** [comment]
127.0.0.1:3000/product/new 
Work in chromium good, work in firefox so poor (can not make product at all).
Fields helping messages (help to input values) not show in firefox.
In chromium browser can not create tags.

Updated mongodb from 2.0 to 2.6 has some positive effects.
Below 10 products.

**Comment by aaronjudd** [comment]
I'm unable to replicate issues in Firefox, but I'm in my checkout branch, so maybe some issues are resolved.  
![screenshot 2015-03-10 11 31 18](https://cloud.githubusercontent.com/assets/439959/6582224/2902635a-c719-11e4-82fb-69673c33ed11.png)

Can you describe your environment in more detail? (branch, packages, os, # of products, etc)?

**Comment by psy21d** [comment]
In chromium browser works better.
There photo can make big responsibility problems.
All 2Gb memory + 2 Gb swap died.
https://yadi.sk/d/2DOZxb-NfAKXN
Good idea is organize better streams  and restrictions for ImageMagick.
