### ISSUE TITLE
imagemagick issues with large images

### ISSUE THREAD

**Issue by psy21d** [reactioncommerce/reaction#337]
Uploading photos has many problems.
One problem is processor overload with development version.
3-5 photos make server down on 1-3 minutes, size: 2000x3000 px. This make PC with i7 8-core 100% CPU load. I think that is problem with parallel working with uploaded photos.

Second problem is denied of service on production version when you try to upload photo on server. 
When photos go to upload, it stopt doing anything with uploaded photos and page can not reload (f5, ctrl+f5) newer (lovely mozilla firefox, yea, it can not working at many points with reactioncommerce now). In chromium browser page reload works, but photo can not uploaded. If meteor restarted, pages can be loaded in firefox, photos show dummies. (Waiting not make profit).
I use this development  meteor instruction
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx

Thanks!

**Comment by psy21d** [comment]
Maybe that problem with uninstalled ImageMagick, but meteor production not make platform responsibilities. What we can do with?
Some photos make uploaded in chromium (10% at all) , another not (90%).

**Comment by psy21d** [comment]
![broken-photo-upload](https://cloud.githubusercontent.com/assets/11248900/6558153/5907d0dc-c68b-11e4-8c4e-d3c5b55c3f67.PNG)

**Comment by psy21d** [comment]
After install imagemagick — same situation.

**Comment by aaronjudd** [comment]
@psy21d can you attach the ./meteor/versions file to this ticket so I can see what CFS packages are being used?

**Comment by psy21d** [comment]
https://yadi.sk/d/JSb-6_Nrf9dSt
versions

**Comment by psy21d** [comment]
http://imagemagick.org/script/architecture.php

If you are dealing with large images, make sure the pixel cache is written to a disk area with plenty of free space. Under Unix, this is typically /tmp and for Windows, c:/temp. You can tell ImageMagick to write the pixel cache to an alternate location and conserve memory with these options:

$ convert -limit memory 2GB -limit map 4GB -define registry:temporary-path=/data/tmp ...

Good idea make settings for processes and organize fine queue.

**Comment by aaronjudd** [comment]
@psy21d have you also tried [graphicsmagick](http://www.graphicsmagick.org/)?

Are you saying you made those imagemagick adjustments and they solved your performance issue?

**Comment by psy21d** [comment]
Thank you! I try it today later. Does it need to remake some core-settings in reactioncommerce?

**Comment by i-a-n** [comment]
I tried this (uploading between 6 and 16 large images) on a Fedora 20 server with <2gb RAM and minimal CPU, and wasn't able to replicate any issue. The images processed as fast as my network could carry them. While one node thread shot to 20% of one CPU, it didn't impact asynchronous page loading.

 I also tried this with and without Imagemagick on my local OSX machine and saw no appreciable lag or CPU overuse. Is it possible your server had limits on CPU threading? I also notice that Imagemagick has pushed four or five optimization and caching updates since you opened this issue, it's possible they simply resolved inefficient processing.

Marking resolved for now. I could see possibly needing to re-engineer image processing when a single server is handling hundreds of shops and many dozens of uploads at once, but I think that'll be a new problem and a new ticket.

**Comment by psy21d** [comment]
Hi!
I found problem, it in FS collections code itself!
Imagemagick, Graphicsmagick is so fast and truly, stable.
But FS stack make me cry. Many threads create many problems.
I think alternate way can be make simple (for example, JQuery uploader) better alternative.

If file start to upload, item in collection create for it. Then, if many files, it can not upload full and make a big problem.  Only one way to drop it and recreate. On markets, where many items and automaic scripts it is outrageous situation!

**Comment by psy21d** [comment]
Little about RAM. Normally ram usage (overhead by upload process) when I setup simple one-thread uploader: 10 mb for 4-5 mb (each) photos. Quantity of simultaneously uploaded images no make difference. When I use FS uploader: 2 gb is not enough an system drops down a few minutes. I can not use this poor uploader in production at all! Quantity of simultaneously uploaded images have big problem: 3-5 normally, 6-10 stupid, 11-20 make perforated photos, 20+ make server down for several minutes. 
2Gb ram, e5 2hz octacore cpu used fully!
If I go to use this system on production site I kill itself by wall before...
No, never in production. That mechanism very bad for.

**Comment by psy21d** [comment]
https://github.com/tomitrescak/meteor-uploads
Include this option in your project and make big happiness for user experience

**Comment by aaronjudd** [comment]
@psy21d with

**Comment by psy21d** [comment]
Maybe your way is proper way.
Now situation not allow us to think about growth.
If I upload 100-200 photos (why not? I am just "stupid" user, for example) then server make 100% all CPU for manu minutes, and some photos never uploaded. 
Need to create proper upload mechanism. Maybe FS or S3 background, definitely need to make queue and give settings.

**Comment by aaronjudd** [comment]
Could we just resolve by limiting the max uploads to 20@5mb?  That would be easy enough and quick protection against unintentional user upload DOS attacks ;-)

**Comment by psy21d** [comment]
This is a temporary solution, in my opinion. Anyway the setting is better to store somewhere in the script file, my experience normally 5-6 uploadings at the same time maximum.

You are working on high-speed servers, Amazon (right?), and there is this problem which absolutely invisible for you, except necessary to pay 10 times more (compared to less energy-intensive code realizing process).

Thank you for understanding!

**Comment by aaronjudd** [comment]
See #403 - maybe this is the continuation of this discussion ;-)

**Comment by kefirchik** [comment]
P.S. @psy21d help me improve ru language pack please :wink:  It has some glitches with long strings :worried:

**Comment by psy21d** [comment]
Okay, what I deed to do for?

**Comment by kefirchik** [comment]
You can pm me in Russian, also u can suggest better translation for certain phrase and I can make a pr etc.

**Comment by kefirchik** [comment]
Oh, about language I can't really tell you, I have the same problem, but just stay tuned and you will find everything needed :wink:

**Comment by psy21d** [comment]
Give me your contact (email \ etc.) please, today I can make some work with ru lang.

**Comment by kefirchik** [comment]
@psy21d please join Reaction at [Gitter](https://gitter.im/reactioncommerce/reaction) and we can discuss it in private chatroom

**Comment by aaronjudd** [comment]
Closing in favor of #3482 which removes the gm/im dependency.
