### ISSUE TITLE
Have default log level include date

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3370]
It's super helpful when looking at logs on a remote server to know not just the time but the date. But loglevel `long` is a little **too** long. Currently you can override this at the environment variable level but only one of the predefined choices. It would also be great to set format via env.

**Comment by aldeed** [comment]
@zenweasel is this still valid?

**Comment by zenweasel** [comment]
It would appear that it is. We still just show time. :thinking: 
```
reaction_1  | 00:08:53.244Z  INFO Reaction: Running startup function "startup" for plugin "reaction-i18n".
```
