### ISSUE TITLE
Enable/Disable Packages for Shops in Marketplace

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#3372]
As a marketplace admin, I should be able to toggle on/off available packages for shops in the marketplace.

**Details:** Currently Packages can be enabled/disabled for all non-primary marketplace shops, but as a Marketplace owner/admin, I also need a way to enable/disable available packages at the level of each shop.

This can go along with the Active/New/Disable setting available for each shop in "Marketplace Shop" tab.

**Comment by rymorgan** [comment]
@impactmass I made a quick mock to give you direction on this. It would also be good to check out my zeplin file linked below for some notes on how this should work. 

zpl.io/V1M3Jnk
![marketplace settings](https://user-images.githubusercontent.com/20409254/33694954-b1741948-daaf-11e7-8dad-4fa0f390b6e0.png)

**Comment by impactmass** [comment]
@rymorgan I added a comment to the zeplin about the New, Active, Disable control

**Comment by rymorgan** [comment]
@impactmass Great. I also made comments in Zeplin about that. But for documentation, I'll paste them in here as well: 

For the New, active and disabled states. New feels to me like it's a notification for a marketplace admin. While Active/Inactive are states an admin will want to toggle between. If my understanding is correct then I'd rather handle it like we do in the mock and add a new notification when a new store has been added. This could remain for a period of time say, a few days or could be persistent until an action is taken.  

This would look something like this: 
![screen shot 2017-12-07 at 10 54 36 am](https://user-images.githubusercontent.com/20409254/33732974-121bd10e-db3d-11e7-9849-13187a601faf.png)

**Comment by impactmass** [comment]
I paused on this to tackle something else with higher priority. Current status is here #3377. 
- Some decisions/work around the packages to toggle, and the shop workflow is still needed.

**Comment by impactmass** [comment]
This use case of needing to "Enable/Disable Packages for specific Shops in Marketplace" came up during work on a project. It looks like it's low priority for now; and also maybe not as needed anymore, because the earlier need was solved by writing a afterCoreInit hook instead of the UI flow thought of here.

@spencern do you think this is still a need? I think we should close it if it's not.

The UI/UX update for the "New, Active, Disable control" that @rymorgan designed can be split into a new issue (and implemented there).

**Comment by spencern** [comment]
@impactmass This is still something that I see some value in, but it's not a high priority right now and we shouldn't work on it until we get our package management system figured out. I'll close for now.
