### ISSUE TITLE
Bitcoin Plugin Feature Request

### ISSUE THREAD

**Issue by arsen3d** [reactioncommerce/reaction#3387]
Add ability to take crypto currency via:
https://coingate.com/accept-altcoins
Here is a list of other carts that can do this:
<img width="1288" alt="screen shot 2017-12-10 at 2 42 41 pm" src="https://user-images.githubusercontent.com/298235/33810351-750abc76-ddb8-11e7-824a-9d43bdb466c0.png">

**Comment by zenweasel** [comment]
@arsen3d We don't have any plans to add any more payment providers. However you can follow the tutorial [here](https://docs.reactioncommerce.com/reaction-docs/master/creating-a-payment-provider) which walks you through creating your own. We would welcome a community plugin to provide this support.
