### ISSUE TITLE
Search only registers products from the main marketplace shop

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3389]
Search is only displaying products created by the main marketplace primary shop. Products created in any other merchant shop are not displayed in search.

### Expected behavior
Search should return results from all shops, not just the main marketplace shop

### Actual behavior
Search is only returning results from products created in the main marketplace shop.

### Steps to reproduce the behavior
- Invite a new shop
- Add products to both new shop, and main marketplace shop
- See only products created under the main shop are displayed in search

### Versions
Node: 9.2.1
NPM: 5.6.0
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.24.2
Reaction: 1.6.0
Reaction branch: master
Docker: 17.11.0-ce

**Comment by zenweasel** [comment]
Pretty sure this is a dupe

**Comment by kieckhafer** [comment]
I think you're correct, @zenweasel 

Duplicate of https://github.com/reactioncommerce/reaction/issues/3254
