### ISSUE TITLE
After checkout error when adding new item to cart

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#339]
Hi,

I have noticed that after you complete an order the cart is removed for the current user, and if the user goes back to the products and tries to add a new product to cart he can't because the new cart is not yet created. The console error is the following: 
'TypeError: Cannot read property 'cartCount' of undefined'
A refresh of the page fixes the issue for now.

**Comment by aaronjudd** [comment]
I'm working on this in #183.

**Comment by boboci9** [comment]
I also wanted to suggest emptying the "shipmentMethod" from the session when we initialize a new checkout because many times I have leftover shipping methods from previous orders selected as active but they are not added in the current order's shipment method and errors appear.

**Comment by boboci9** [comment]
Forgot to add the error: Uncaught event shipmentMethod inappropriate in current state orderCreated
