### ISSUE TITLE
Publishing indicator is in the wrong place on the PDP

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#3397]
### Expected behavior

The publishing indicator should be in right place

### Actual behavior

It's inside the product image instead of places on the corner. 

### Steps to reproduce the behavior

Change a product
See publishing indicator dot is in the wrong place. 

### Versions
Node: 6.11.4
NPM: 5.5.1
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.24.2
Reaction: 1.6.1
Reaction branch: master

Wrong -
![publish-indicator](https://user-images.githubusercontent.com/20409254/33915473-675e834a-df58-11e7-83ae-162e8faaad18.png)

Right -
![publish-indicator-correct](https://user-images.githubusercontent.com/20409254/33915480-6d92c974-df58-11e7-9a70-09c3f6b708e1.png)

**Comment by zenweasel** [comment]
@codejockie This looks to be caused by a change you made recently. Can you take a look at it?

**Comment by codejockie** [comment]
@zenweasel will do.

**Comment by codejockie** [comment]
Fixed.

**Comment by spencern** [comment]
Resolved in release [v1.6.4](https://github.com/reactioncommerce/reaction/releases/tag/v1.6.4)
