### ISSUE TITLE
Google Analytics Error on fresh x.reactioncommerce.com install

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#340]
I've not been able to get Google Analytics to work yet on the hosted reactioncommerce install. 

My error when I try to submit my tracking ID now is: Google Analytics update failed: MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}} [409]

It's different on my local though and just fails silently, and then complains that Google Analytics isn't set up yet.

![image](https://cloud.githubusercontent.com/assets/1203639/6609280/1879000a-c815-11e4-92d6-f0bbc9039af2.png)

I ended up rebuilding the plugin almost entirely on my local to get it to work and can issue a PR if you want it. Feel free to give me any feedback about anything that you'd like done differently, or if you've got something in the works to ignore it all-together. Helped me understand creating packages for reaction to rebuild it, and more of an exercise anyway. Followed the syntax of the Stripe plugin when rebuilding it rather than the existing GA plugin as it seemed newer, but not sure that's the case.

[Forked rebulid here.](https://github.com/spencern/reaction-google-analytics)

**Comment by aaronjudd** [comment]
@spencern this looks great.  I'll take the PR. I had updated just enough to get everything loading with the new branches but haven't been testing all the packages while working on the development / guest-checkout branch. You may want to test with guest-checkout (I'm close to merging). I added a comment about settings - we should switch to use the package.settings for all settings, and disregard Meteor.settings. In this case, you'll want a settings.public.propertyId. Other than that, this is great, and save me some time fixing this up for the next release.
