### ISSUE TITLE
Duplicate form ID DOM Error in console

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3418]
### Expected behavior
No errors in console

### Actual behavior
As of the latest version of Chrome I see several errors in the console which point out some poorly formed HTML in several forms:

```
[DOM] Found 2 elements with non-unique id #facebookSettingsClientId: (More info: https://goo.gl/9p2vKq) <input class=​"form-control" id=​"facebookSettingsClientId" type=​"text" name=​"appId">​ 
```

Happens in the Dashboard payment panel and the Social settings panel and perhaps other places (this list is not comprehensive)

### Steps to reproduce the behavior
1. Have the latest version of Chrome (Version 63.0.3239.84 or later)
1. Navigate to the Payment panel in the dashboard
1. Observe the errors in the console

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.2
Reaction branch: release-1.6.2
Docker: 17.09.1-ce
```

**Comment by wackywombaat12** [comment]
I am happy to work on this if no one else is :)

**Comment by zenweasel** [comment]
@wackywombaat12 Great! 💥

**Comment by michael-alade** [comment]
@wackywombaat12 Heads up, the payment plugins make use of the meteor autoforms. The ids are automatically generated, the best possible option would be to take them out and write a custom form. You should also checkout the social logins part, that relatively easy.

**Comment by zenweasel** [comment]
@wackywombaat12 I would contradict the statement by @michael-alade  as we have plans to rewrite these panels in React soon as well as refactor how some of the values are stored so if rewriting these turns out to be the only solution you should hold off.

**Comment by wackywombaat12** [comment]
@zenweasel @michael-alade yep after some investigating it looks like it is best to hold off until the conversion to React to avoid double handling the problem.

**Comment by cindyfirestone** [comment]
@zenweasel it's also happening in the tax panel

**Comment by Purnendusarkar97** [comment]
[DOM] Found 2 elements with non-unique id #_wpnonce: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"6ec9e8c297">​How to  Dom problem solve???

**Comment by jrussell1** [comment]
Just snooping and saw that the error is still there if anyone is still interested - 

DOM Found 2 elements with non-unique id #locale: (More info: https://goo.gl/9p2vKq)

**Comment by trojanh** [comment]
@aldeed since we no longer have admin UI in v3, does it make sense to close it now?
