### ISSUE TITLE
bug: Adding address during checkout as a new customer

### ISSUE THREAD

**Issue by evliu** [reactioncommerce/reaction#342]
Steps to reproduce:
* Create an account
* Add something to cart
* go to checkout page
* add an address
* hit "Save and Continue" button

Expected result:
* address selection for shipping/billing

Actual Result:
* stays on add address form

If I refresh the page, then I get the address selection screen

**Comment by Gouthamve** [comment]
Hmm, I am not getting this. I am correctly going to address selection/billing.

I am using firefox developer edition and have the latest development branch.

Thanks.

**Comment by aaronjudd** [comment]
@evliu Can you confirm this is resolved in https://github.com/reactioncommerce/reaction-core/pull/111

**Comment by evliu** [comment]
Fixed with newest pull
