### ISSUE TITLE
Product image doesn't always show up

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3421]
### Expected behavior
Product image should always show up

### Actual behavior
Sometimes it doesn't until you refresh

### Steps to reproduce the behavior
1. Visit https://swag.getreaction.io/ 
1. Click on a product
1. Observe that the product image does not show up and "long click to zoom" is displayed at the top

This was undoubtedly introduced in #3343. I saw this when testing but was reassured that this couldn't be reproduced.

### Versions
reaction-version: 1.6.3 (bug reproduced w/o my local machine)

**Comment by spencern** [comment]
Resolved in release [v1.6.4](https://github.com/reactioncommerce/reaction/releases/tag/v1.6.4)
