### ISSUE TITLE
Convert Search Modal to React

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3424]
This consumer-facing component is still in Blaze.

Part of #3203

**Comment by spencern** [comment]
@rymorgan do we have designs for contextual search?

**Comment by kieckhafer** [comment]
Designs for Account search: http://zpl.io/a3qJqA2

**Comment by zenweasel** [comment]
Is this Account search? I think this ticket is meant to deal with the main consumer-facing search. I think there is a separate ticket already for account search.

**Comment by kieckhafer** [comment]
@zenweasel Yes, it's for accounts, but moving accounts out of this modal, so it kind of makes sense to be here too. Part of converting this to React is removing `taco-table` from the modal, which is part of the account search.

Looks like #3119 and #2903 are related for accounts search.

**Comment by mikemurray** [comment]
Added PR https://github.com/reactioncommerce/reaction/pull/3801 as a blocker. While there are many ways to remove the need to use Blaze to inject the search modal into the dom tree, we should consider using React 16 portals to do that job.
