### ISSUE TITLE
Can we use reaction commerce as a package and use it as where we needed ?

### ISSUE THREAD

**Issue by adilsaeed31** [reactioncommerce/reaction#3432]
HI,

Can we use React Commerce as a package and use it as where we need the cart services. Is it possible.

Sorry I am posting my question here.

**Comment by zenweasel** [comment]
Generally I would say that you could but it's not really how the app was intended to be used. But you can use our API via Meteor methods. Check out the API docs here: http://api.docs.reactioncommerce.com/

If you want to continue this discussion please visits our [forums](https://forums.reactioncommerce.com/)
