### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3433]
The link to [requirements](https://docs.reactioncommerce.com/reaction-docs/master/requirements) in section "Getting started" is dead as target URL does not exist in docs.reactioncommerce.com

### Expected behavior
The link's target should exist

### Actual behavior
Page can't be displayed. Spinner is shown indefinitely.

**Comment by gezzz** [comment]
I am having the same issue page isn't loading. Spinner is spinning indefinitely .

**Comment by spencern** [comment]
Resolved in release [v1.6.4](https://github.com/reactioncommerce/reaction/releases/tag/v1.6.4)
