### ISSUE TITLE
Marketplace owner can't see all orders

### ISSUE THREAD

**Issue by tom-gerken** [reactioncommerce/reaction#3435]
As a marketplace owner, I want to be able to see orders for all shops in my marketplace when I click "Orders".  The specs would be the same as https://docs.reactioncommerce.com/reaction-docs/master/orders-admin but with all shops included

**Comment by zenweasel** [comment]
@tom-gerken Are you reporting this as a bug (i.e. "Marketplace owner can't see all orders"?). I believe the original intent was that marketplace admin could see all orders and actually that's what I am currently seeing but I need to dig a little deeper.

**Comment by tom-gerken** [comment]
@zenweasel I wasn't aware it was a bug, I thought it was not implemented yet.  To be clear, I am able to see orders for individual shops if I change the drop down to be logged in as a shop instead of Admin.  What I'm proposing is that if I am logged in as Admin, I see orders for all shops in my marketplace so I do not need to toggle through one by one.

**Comment by spencern** [comment]
This seems to be a feature request, and we would need more details before considering it.
