### ISSUE TITLE
Review user data handling

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#344]
perform a full review of the storage and treatment of user data (ie: carts, accounts, sessions, emails)

Some ideas:

- Encryption of all customer data (replace with plain text with encrypted data)
- Add server side methods for reading/store, query encrypted records
- add test for exposed customer data

**Comment by aaronjudd** [comment]
Related to #283

**Comment by aaronjudd** [comment]
Review this https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-collections/server/publications/accounts.js#L56-L75 and specifically https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-collections/server/publications/accounts.js#L78.  Meteor.user is using https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_common.js#L229.  Account.server I think is the new multi-server implementation and seems to be returning more than would be expected in the client when reviewing console `Accounts.user`.   Could be refactored to apply exported fields to all in the short term, and a larger refactor in  adding public social profile data to `ReactionCore.Collections.Accounts`.

**Comment by aaronjudd** [comment]
Note: I think the recommend approach here would be to remove this publication if possible, and rely on "Reaction.Accounts" but this would likely require a secure method of syncing those profile details, and replacing the functionality of `utilities:gravatar`, which might not be trivial  - as discussed with @mikemurray  and @newsiberian

**Comment by newsiberian** [comment]
I realized that we need to add `DDPRateLimit` to every method, which is accessible from client side. Now every of this methods can be looped that will be cause of server DDOS.
For example.
* normally user can't call "cart/addToCart" more than, say, 1 time in 5 seconds and
* he can't modify/add/remove his address more than 1 time in 2-5 seconds
but not 600 times per seconds.
I think we need to think about each method. How often it could be called normally? And implement this rate limits.

**Comment by zenweasel** [comment]
@Capt-Slow Josh, you and I should go over this ticket and extract some actionable items from it.

**Comment by zenweasel** [comment]
I think the tickets created here cover the issues brought up in this ticket so this ticket is no longer needed.
