### ISSUE TITLE
Currency selection doesn't work

### ISSUE THREAD

**Issue by liyucun** [reactioncommerce/reaction#3440]
### Expected behavior
By switching currency, it should change the displaying currency and amount.

### Actual behavior
The displaying currency cannot be changed, and it always shows base currency price. 

### Steps to reproduce the behavior
1. follow steps for running [reaction docker image]( https://hub.docker.com/r/reactioncommerce/reaction/) locally
2. access to the website, and change the currency

### Versions
The version is specified by docker image.

Would love to fix this bug and send a PR, and hope someone could point me to somewhere i can start to take a look at.

**Comment by zenweasel** [comment]
@liyucun Do you have an OpenExchangeRates API key inserted? As you need this for currencies to work. I cannot replicate this bug with the OpenExchangesRates key configured

**Comment by liyucun** [comment]
@zenweasel thanks! that solves my problem.

**Comment by zenweasel** [comment]
@lijiming Awesome
