### ISSUE TITLE
Changes to app registry system

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#345]
I think the current system is inadequate. The app can be active without the user enabling it.

Suppose I do something like ```customFooter replaces layoutFooter``` in an app. The footer is replaced irrespective of the app being enabled or disabled.

I don't think the app should be active unless enabled.

**Comment by aaronjudd** [comment]
@Gouthamve the `meteor` package management ("meteor add/remove") handles addition.  If you wanted to conditionally include portions, a check to the `enabled` status.   We've got an issue discussing packages enable/disable: reactioncommerce/reaction#146

**Comment by aaronjudd** [comment]
@Gouthamve can we close this in favor of #146?

**Comment by Gouthamve** [comment]
Yep. Absolutely.
