### ISSUE TITLE
Add Rocket.Chat integration for unlimited Live Chat and beyond

### ISSUE THREAD

**Issue by lindoelio** [reactioncommerce/reaction#3452]
**[Rocket.Chat](https://rocket.chat/)** is the leading free open source chat Slack alternative, unlimited. Provides a great LiveChat features, besides free audio and video conferencing, guest access, screen sharing, file sharing, LDAP Group Sync, two-factor authentication (2FA), E2E encryption, SSO, dozens of OAuth providers and unlimited users, guests, channels, messages, searches and files.

**Reaction Commerce** with **Rocket.Chat** can to deliver the best conversation experience between shoppers and sellers, in all levels, towarding to a growing conversion.

<span>&#x1f1e7;&#x1f1f7;</span> #ReactionBR

**Comment by gregorynicholas** [comment]
:+1:

**Comment by teralabs** [comment]
👍

**Comment by teralabs** [comment]
try, to allow crossdomain:
import { BrowserPolicy } from "meteor/browser-policy-common";

BrowserPolicy.content.allowOriginForAll("*");  //insecure, change to the chat domain

than add the rocket chat script to an includet html file

**Comment by aaronjudd** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #9](https://github.com/reactioncommerce/reaction-feature-requests/issues/9) via [**ZenHub**](https://www.zenhub.com/)
