### ISSUE TITLE
Include taxes and discounts on Total shown in Order emails

### ISSUE THREAD

**Issue by glmaljkovich** [reactioncommerce/reaction#3457]
Shouldn't taxes and discounts be added to the total too? Right now it just uses shipping and subtotals.

https://github.com/reactioncommerce/reaction/blob/33c3d5b59a88faa73250fac1445dc57b3ca9e12d/server/methods/core/orders.js#L771

**Comment by Akarshit** [comment]
### To Test
1. Run `reaction`
1. Set tax rate to `Custom tax rate` and set a rate of 10% at your pincode.
1. Place order for the `Example product` at the same pincode. An email will be sent to your email-id.
1. Check the email, which should buggy total calculation like shown in the screenshot.
<img width="270" alt="screen shot 2018-01-16 at 1 05 27 pm" src="https://user-images.githubusercontent.com/7762605/34977568-0db78dd0-fac1-11e7-88d7-aceca48bb581.png">
