### ISSUE TITLE
Change "Base Unit of Measure" to "Base Unit of Weight"

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3458]
### Expected behavior
The weight UOM should be called "Base Unit of Weight" similar to how Unit of Length is called "Base Unit of Length".

### Actual behavior
It's called "Base Unit of Measure" which is probably a legacy value from when we only cared about weight.

### Steps to reproduce the behavior
1. Login as an admin
1. Observe that the UOM for weight is called "Base Unit of Measure"
1. Despair

Note: Changing this for real involves changing the unlying schema and writing migrations for that

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.3
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by Yahyakiani** [comment]
@zenweasel Is this issue available. Would like to take a shot at it. First Timer

**Comment by Akarshit** [comment]
@Yahyakiani Hey! Thanks for taking the initiative to pick this up. The issue is still valid and doing a search for "Measure" should give you a few places where this is being used. That should be a good starting point.

**Comment by Shofiya2003** [comment]
Is this issue still open?

**Comment by jmutt78** [comment]
I would like to tackle this one.

**Comment by Akarshit** [comment]
@jmutt78 Sure, go ahead. Let me know if you need any help.
