### ISSUE TITLE
failed to run reaction run on windows 10

### ISSUE THREAD

**Issue by eladnm** [reactioncommerce/reaction#3469]
C:\Users\eladn\node\reaction>reaction run

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Installing dependencies for connectors-shopify...

up to date in 0.062s
Setting up style imports...

[[[[[ C:\Users\eladn\node\reaction ]]]]]

=> Started proxy.
cfs:tempstore: updating npm dependencies -- combined-stream...
=> Started MongoDB.
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
   Building for web.browser                  \
<--- Last few GCs --->

[12616:045B1748]   179573 ms: Mark-sweep 740.1 (882.5) -> 686.7 (881.0) MB, 543.6 / 0.2 ms  allocation failure GC in old space requested
[12616:045B1748]   180206 ms: Mark-sweep 686.7 (881.0) -> 686.6 (850.0) MB, 632.8 / 0.3 ms  last resort GC in old space requested
[12616:045B1748]   180788 ms: Mark-sweep 686.6 (850.0) -> 686.6 (848.5) MB, 582.4 / 0.2 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 28A1632D <JSObject>
    0: builtin exit frame: stringify(this=28A0FCA1 <Object map = 31905651>,3A1041A1 <undefined>,3A1041A1 <undefined>,5856DD9D <JSArray[2]>)

    1: arguments adaptor frame: 1->3
    3: _linkJS [C:\Users\eladn\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:1393] [bytecode=3F5E6BA9 offset=926](this=13D95615 <PackageSourceBatch map = 0084DDF5>,js...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
{ Error: Command failed: meteor --settings settings/dev.settings.json --raw-logs
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at _callee$ (C:\Users\eladn\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:79:43)
    at tryCatch (C:\Users\eladn\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\eladn\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\eladn\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\eladn\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:105:191)
    at C:\Users\eladn\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:105:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
  error: null,
  cmd: 'meteor --settings settings/dev.settings.json --raw-logs',
  file: 'C:\\WINDOWS\\system32\\cmd.exe',
  args:
   [ 'C:\\WINDOWS\\system32\\cmd.exe',
     '/s',
     '/c',
     '"meteor --settings settings/dev.settings.json --raw-logs"' ],
  options:
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     windowsVerbatimArguments: true,
     file: 'C:\\WINDOWS\\system32\\cmd.exe',
     args:
      [ 'C:\\WINDOWS\\system32\\cmd.exe',
        '/s',
        '/c',
        '"meteor --settings settings/dev.settings.json --raw-logs"' ],
     envPairs:
      [ 'ALLUSERSPROFILE=C:\\ProgramData',
        'APPDATA=C:\\Users\\eladn\\AppData\\Roaming',
        'ChocolateyInstall=C:\\ProgramData\\chocolatey',
        'ChocolateyLastPathUpdate=Wed Jan 10 00:26:14 2018',
        'CommonProgramFiles=C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
        'CommonProgramW6432=C:\\Program Files\\Common Files',
        'COMPUTERNAME=ELAD',
        'ComSpec=C:\\WINDOWS\\system32\\cmd.exe',
        'CUDA_PATH=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0',
        'CUDA_PATH_V8_0=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0',
        'GYP_MSVS_VERSION=2015',
        'HOMEDRIVE=C:',
        'HOMEPATH=\\Users\\eladn',
        'LOCALAPPDATA=C:\\Users\\eladn\\AppData\\Local',
        'LOGONSERVER=\\\\ELAD',
        'NUMBER_OF_PROCESSORS=8',
        'OneDrive=C:\\Users\\eladn\\OneDrive',
        'OS=Windows_NT',
        'Path=C:\\Users\\eladn\\AppData\\Roaming\\npm;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Micron Technology\\Micron Storage Executive;C:\\Program Files\\nodejs\\;C:\\xampp\\php;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files\\MongoDB\\Server\\3.4\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\PuTTY\\;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\eladn\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\eladn\\AppData\\Roaming\\npm;C:\\Users\\eladn\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\eladn\\AppData\\Local\\.meteor;C:\\Users\\eladn\\AppData\\Local\\.meteor\\',
        'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC',
        'PROCESSOR_ARCHITECTURE=AMD64',
        'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel',
        'PROCESSOR_LEVEL=6',
        'PROCESSOR_REVISION=9e09',
        'ProgramData=C:\\ProgramData',
        'ProgramFiles=C:\\Program Files',
        'ProgramFiles(x86)=C:\\Program Files (x86)',
        'ProgramW6432=C:\\Program Files',
        'PROMPT=$P$G',
        'PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
        'PUBLIC=C:\\Users\\Public',
        'SESSIONNAME=Console',
        'SystemDrive=C:',
        'SystemRoot=C:\\WINDOWS',
        'TEMP=C:\\Users\\eladn\\AppData\\Local\\Temp',
        'TMP=C:\\Users\\eladn\\AppData\\Local\\Temp',
        'USERDOMAIN=ELAD',
        'USERDOMAIN_ROAMINGPROFILE=ELAD',
        'USERNAME=eladn',
        'USERPROFILE=C:\\Users\\eladn',
        'VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\',
        'VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
        'windir=C:\\WINDOWS' ] },
  envPairs:
   [ 'ALLUSERSPROFILE=C:\\ProgramData',
     'APPDATA=C:\\Users\\eladn\\AppData\\Roaming',
     'ChocolateyInstall=C:\\ProgramData\\chocolatey',
     'ChocolateyLastPathUpdate=Wed Jan 10 00:26:14 2018',
     'CommonProgramFiles=C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
     'CommonProgramW6432=C:\\Program Files\\Common Files',
     'COMPUTERNAME=ELAD',
     'ComSpec=C:\\WINDOWS\\system32\\cmd.exe',
     'CUDA_PATH=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0',
     'CUDA_PATH_V8_0=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0',
     'GYP_MSVS_VERSION=2015',
     'HOMEDRIVE=C:',
     'HOMEPATH=\\Users\\eladn',
     'LOCALAPPDATA=C:\\Users\\eladn\\AppData\\Local',
     'LOGONSERVER=\\\\ELAD',
     'NUMBER_OF_PROCESSORS=8',
     'OneDrive=C:\\Users\\eladn\\OneDrive',
     'OS=Windows_NT',
     'Path=C:\\Users\\eladn\\AppData\\Roaming\\npm;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Micron Technology\\Micron Storage Executive;C:\\Program Files\\nodejs\\;C:\\xampp\\php;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files\\MongoDB\\Server\\3.4\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\PuTTY\\;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\eladn\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\eladn\\AppData\\Roaming\\npm;C:\\Users\\eladn\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\eladn\\AppData\\Local\\.meteor;C:\\Users\\eladn\\AppData\\Local\\.meteor\\',
     'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC',
     'PROCESSOR_ARCHITECTURE=AMD64',
     'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel',
     'PROCESSOR_LEVEL=6',
     'PROCESSOR_REVISION=9e09',
     'ProgramData=C:\\ProgramData',
     'ProgramFiles=C:\\Program Files',
     'ProgramFiles(x86)=C:\\Program Files (x86)',
     'ProgramW6432=C:\\Program Files',
     'PROMPT=$P$G',
     'PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
     'PUBLIC=C:\\Users\\Public',
     'SESSIONNAME=Console',
     'SystemDrive=C:',
     'SystemRoot=C:\\WINDOWS',
     'TEMP=C:\\Users\\eladn\\AppData\\Local\\Temp',
     'TMP=C:\\Users\\eladn\\AppData\\Local\\Temp',
     'USERDOMAIN=ELAD',
     'USERDOMAIN_ROAMINGPROFILE=ELAD',
     'USERNAME=eladn',
     'USERPROFILE=C:\\Users\\eladn',
     'VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\',
     'VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
     'windir=C:\\WINDOWS' ],
  stderr: null,
  stdout: null,
  pid: 10904,
  output: [ null, null, null ],
  signal: null,
  status: 3 }

Error: App failed to start

**Comment by zenweasel** [comment]
From the command line try
`set TOOL_NODE_FLAGS=’–max_old_space_size=1024`

and then try running Reaction again

In the future, our [docs](https://docs.reactioncommerce.com) or our [Gitter channels](https://gitter.im/reactioncommerce/installation) are the best places to get these sort of answers

**Comment by shastaclokey1** [comment]
I am producing the same error consistently. 

Reaction will fail the first (roughly) 5 times I run it, then it will start up just fine.

This repeated failure to start followed by success is independent of plugins loaded and occurs after
a fresh reaction init or reaction reset. 

This could be Windows caching data from the reaction run attempts and catching up to the failure 
at the ~5 iteration mark.

I have tried the "set TOOL_NODE_FLAGS='-max_old_space_size=1024' fix and it does not help the problem.

I think rc is a great platform! Hope this helps fix any potential bugs with the windows platform.
