### ISSUE TITLE
Cannot add to cart if logged in from different browsers.

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#347]
The cart does not work when logged in from different browsers. This could be a security setup but, even after you log out of all other sessions, the cart doesn't work.

Steps to replicate:
1. Create an account in one browser.
2. Log in from a another browser.
3. Try to add to cart or look at cart.

**Comment by aaronjudd** [comment]
![screenshot 2015-03-16 12 54 24](https://cloud.githubusercontent.com/assets/439959/6675107/9cdfdf2a-cbdb-11e4-9195-79b0dd30dfb7.png)

Works for me..   this might be related to another bug I am see though, some corrupted items are being put into the cart - I think when one of the users had nothing in the cart and merged during login looking into this now.
