### ISSUE TITLE
[Marketplace] Add Rating for Sellers and Buyers

### ISSUE THREAD

**Issue by lindoelio** [reactioncommerce/reaction#3476]
Add ability to provide rating for sellers and buyers, like already exists for products.

Both use cases are relevant: sellers rate buyers and buyers rate sellers.

<span>&#x1f1e7;&#x1f1f7;</span> #ReactionBR

**Comment by israeldboliveira** [comment]
Great feature to be implemented

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #37](https://github.com/reactioncommerce/reaction-feature-requests/issues/37) via [**ZenHub**](https://www.zenhub.com/)
