### ISSUE TITLE
RAM memory on GCP

### ISSUE THREAD

**Issue by rabas007** [reactioncommerce/reaction#3480]
I want to try to deploy RC on Google Cloud Platform.

Does anybody have experience with this and can share a guide?

Which Google Cloud Platform product specifications suits best? I read that too often there are RAM memory issues, but anything between 2-3GB should be OK I guess?

Thanks.

**Comment by zenweasel** [comment]
@rabas007  Sorry we don't have any experience deploying on Google Cloud. We do recommend that servers run with 2GB of RAM. You might be able to get away with less but 2GB is best.
