### ISSUE TITLE
Deprecate ImageMagick/GraphicsMagick dependency

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3482]
The requirement for using ImageMagick / GraphicsMagick for resizing images requires an additional dependency outside of our application environment, and there has always been a host of related issues... at the time there didn't appear to be any good Node modules available. 

http://sharp.pixelplumbing.com/en/stable/

It appears that [sharp](https://github.com/lovell/sharp) should be a drop in replacement and faster as well...

**Comment by aldeed** [comment]
I published `cfs:storage-adapter@0.2.4` Meteor package without the "gm is missing" message. Whoever does this development should update that dependency, too.

**Comment by aldeed** [comment]
@kieckhafer Why was this reopened? Is it because the Meteor package still needs to be removed?

**Comment by kieckhafer** [comment]
@aldeed I don’t recall re-opening this. Definitely didn’t do it on purpose. Could’ve accidentally changed columns on stand up on Friday. Reclosing.
