### ISSUE TITLE
Building custom docker image fails

### ISSUE THREAD

**Issue by munroe7** [reactioncommerce/reaction#3483]
I have been trying to create a custom docker image with my plugins that I have created. When I run the docker command provided in the docs, I get the following error:

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  7786    0  7786    0     0  46518      0 --:--:-- --:--:-- --:--:-- 46622
> 
> ... Installing Meteor 1.6.0.1
> 
> Downloading Meteor distribution
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> Retrying download in 5 seconds...
> The command '/bin/sh -c cd $APP_SOURCE_DIR &&             $BUILD_SCRIPTS_DIR/install-deps.sh &&             $BUILD_SCRIPTS_DIR/install-node.sh &&             $BUILD_SCRIPTS_DIR/install-phantom.sh &&
>           $BUILD_SCRIPTS_DIR/install-mongo.sh &&             $BUILD_SCRIPTS_DIR/install-meteor.sh &&             $BUILD_SCRIPTS_DIR/build-meteor.sh &&             $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1

This seems to be reported in other repos: [https://github.com/jshimko/meteor-launchpad/issues/69](https://github.com/jshimko/meteor-launchpad/issues/69)

Sub-question: The Dockerfile in the reaction repo includes reaction/base:v3.0.0. Is this a private image because I have navigated the reaction docker account and don't see it listed?

**Comment by jshimko** [comment]
That error is almost always a network issue while downloading Meteor. 

The base image is definitely public:  https://hub.docker.com/r/reactioncommerce/base/

**Comment by munroe7** [comment]
Ahh ok didn't see the other repos. As for the "network issue", what would cause this? I have a perfectly good connection to the internet.

**Comment by jshimko** [comment]
First of all, you definitely need to remove `bcrypt`.  That is guaranteed to fail your build.

I just cloned your repo.  I ran it in development and also built an image.  In both cases, I see your custom plugins loading.

```sh
git clone <your private repo>

reaction

# it works

docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t customshop .

# it works
```
Then create a `docker-compose.yml` with the following...

```yaml
reaction:
  image: customshop
  links:
    - mongo
  ports:
    - "3000:3000"
  environment:
    ROOT_URL: "http://localhost:3000"
    MONGO_URL: "mongodb://mongo:27017/reaction"

mongo:
  image: mongo:3.4
  command: mongod --storageEngine=wiredTiger
```

and run...

```sh
docker-compose up -d
```

App is available at `http://localhost:3000`

<img width="1680" alt="reaction" src="https://user-images.githubusercontent.com/3077956/34921757-46e7f25c-f954-11e7-8248-00c9c3d98f09.png">

**Comment by munroe7** [comment]
So removing bcrypt will allow it to build?

**Comment by jshimko** [comment]
Yes.

**Comment by munroe7** [comment]
Removing bcyrpt allowed me to build my image successfully!
