### ISSUE TITLE
Maketplace dropdown not working on clicking inside the tab.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#3487]
### Expected behavior
The dropdown should toggle when the user click anywhere(except for the on/off button)
### Actual behavior
The dropdown toggle only works when clicking right over the text `Marketplace`.
### Steps to reproduce the behavior
1. Run `reaction`.
1. Open Shops from the Action menu.
2. Click anywhere outside the area shown in the pic, dropdown will not open
<img width="400" alt="screen shot 2018-01-15 at 7 55 58 pm" src="https://user-images.githubusercontent.com/7762605/34946832-5deba004-fa2e-11e7-9004-ebb1e8c4315e.png">

**Comment by munroe7** [comment]
This is the case for all options under shop settings.

General, Address, and Options are also not toggling
