### ISSUE TITLE
Paypal express payment succeed without creating an order in Reaction

### ISSUE THREAD

**Issue by duanhong169** [reactioncommerce/reaction#3490]
### Expected behavior

If we failed to create an order, we should not confirm a paypal payment authorization.

### Actual behavior

We are using the `paypal-express` payment method.
The paypal payment authorization is confirmed before an order is created, then if some errors occur when creating the order, the method `cart/copyCartToOrder` may not be called normally, which left the user's cart in an invalid state(because Reaction use cartId as the INVNUM, so this user cannot checkout any more).

### Steps to reproduce the behavior

Throw an error after `confirmPaymentAuthorization` succeed.

### Versions
1.6.3

**Comment by zenweasel** [comment]
@duanhong169 Can you please provide some reproduction steps?

**Comment by zenweasel** [comment]
No detail provided. Closing.
