### ISSUE TITLE
Decide and document schema extension best practices

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#3494]
With the change to SimpleSchema 2.0, we need to solidify and document the proper way to do schema extensions. This is my proposal. Looking for feedback before updating docs and code as necessary.

## Basic extension

```js
import { SomeSchema } from "/lib/collections/schemas";
SomeSchema.extend({
  // my additional or override schema keys
});
```

This will mutate the schema everywhere it is used.

## Attaching an alternative schema

If you want to select from among multiple schemas based on a selector or a property in the document, then you need to use that feature of `attachSchema`, from the `aldeed:collection2-core` Meteor package. Refer to https://github.com/aldeed/meteor-collection2-core/#attaching-multiple-schemas-to-the-same-collection

```js
import { SomeCollection } from "/lib/collections";
import { SomeSchema } from "/lib/collections/schemas";
const mySpecialSchema = SomeSchema.clone().extend({
  // my additional or override schema keys
});
SomeCollection.attachSchema(mySpecialSchema, {selector: {type: "my-special-type"}});
```

In this case `mySpecialSchema` will be used only when the `type` prop equals "my-special-type".

## Guidelines for validation

In order to make sure both of these approaches will work, anywhere a schema related to a collection is used, it should be accessed by `collection.simpleSchema(doc)` rather than imported directly.

### incorrect

```js
CartSchema.validate(cart);

// OR

const validationContext = CartSchema.namedContext(name);
```

This would not respect any additional schemas attached by calling `attachSchema` with a selector.

### correct

```js
CartCollection.simpleSchema(cart).validate(cart);

// OR

const validationContext = CartCollection.simpleSchema(cart).namedContext(name);
```

**Comment by pmn4** [comment]
this looks great @aldeed.
It wasn't until I read this that I understood why you pass your data object to `.simpleSchema(data)`. Makes total sense now!

For anyone reading this who comes from Rails/ActiveRecord land, "Alternative Schemas" are a lot like Single Table Inheritance Models, or, Models that descend from parent classes which may have an additional attribute or two. You wouldn't want to validate an instance of the parent class and an instance of the child class with the same rules.
The most common use-case in Reaction is the Product/ProductVariant/Option Models. All share _some_ common properties, but Variants and Options have attributes that a Product does not, so it does not makes sense to validate a top-level Product against _all_ of the properties that could be stored in a mongo Document.

---
_(thanks for letting me think out loud!)_
