### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3495]
Got some queries from the community about when we are going to do this as people want to utilize some of the new features. This is a placeholder for any issue we encounter when trying to do that.

Theoretically this should be a painless upgrade but it depends on whether all of the dependent libraries are compatible.

**Comment by zenweasel** [comment]
Two libraries that don't support React 16 yet `react-addons-test-util` and `react-taco-table`

**Comment by kieckhafer** [comment]
`react-taco-table` is only used by `SortableTableLegacy`, and only in the search modal, for Accounts. If we can update that to use `SortableTable`, or even better, move account search to the accounts dashboard, we could remove that dependency.

**Comment by loanlaux** [comment]
In my opinion, moving the account search to the accounts dashboard makes a lot of sense. Coming from traditional e-commerce platforms, I remember being confused about this mixed search feature and I think lots of new users will be as well.

**Comment by spencern** [comment]
Closed by #3801
