### ISSUE TITLE
Checking out on marketplace does not check for valid email input

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#3500]
As a non-logged in consumer, when I try to check out as a guest in step q, it gives me an email field to fill out. However, this field is not required nor does it validate that my email is a real email address before moving on to step 2 of the checkout flow. 
![untitled](https://user-images.githubusercontent.com/22083616/35079457-8125c858-fbbc-11e7-8872-4ed07f2ae420.gif)

Since email is a requirement for checkout with Stripe Connect, the email field should be required and should validate that it is an email address before allowing the user to move on in the checkout process.

**Comment by zenweasel** [comment]
Closing. Dupe (although this one was first)
