### ISSUE TITLE
Strange behavior when saving settings for login services

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3501]
### Expected behavior
Field names shouldn't change

### Actual behavior
Field names change when other forms are saved
![2018-01-18_11-24-32-1](https://user-images.githubusercontent.com/72819/35080826-0098f2b6-fc4b-11e7-87bd-0483fd650f48.gif)

### Steps to reproduce the behavior
1. Login as admin
1. Open "login services" and open more than one panel
1. Save any service
1. Observe that the second field on all panels turns to "Secret"

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by Akarshit** [comment]
@zenweasel Not able to reproduce in `release-1.8.0`.

**Comment by zenweasel** [comment]
Closed. Can no longer reproduce.
