### ISSUE TITLE
Core Analytics Package

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#351]
##Analytics refactor##
- Create core-analytics package that provides collections and methods for tracking.
- Update and decouple google-analytics package that reactively updates with data collected with core analytics.
- Add some basic analytics to the "Reaction Apps" dashboard console widgets.

**Comment by spencern** [comment]
I've already started and done some work with this, it's alpha stage but successfully decoupled Google Analytics from the reaction package, and added hooks into the ReactionAnalytics collection that can trigger any future analytics package. See https://github.com/spencern/reaction-analytics and [published here](https://atmospherejs.com/spencern/reaction-analytics) for the base package. I've forked and branched the [reaction-google-analytics package](https://github.com/spencern/reaction-google-analytics/tree/decouple-analytics) to work with my decoupled base package as well.

Again, this is just a basic exploration of what this would look like. I've started looking into GA's enhanced ecommerce which will require us to do some more work with the core templates to ensure that we are recording all relevant events related to ecommerce, though I think this will be important anyway for recording and displaying relevant integrated analytics in the future anyway.

Would love to continue the discussion about what this looks like.

**Comment by aaronjudd** [comment]
What if core-analytics is a wrapper package for [analytics.js](https://segment.com/docs/libraries/analytics.js/) similar to the [okgrow:analytics](https://atmospherejs.com/okgrow/analytics).

I can see us wanting to combine the server log, a client log, and tracking into a datastore for reaction analytics, etc. So we could add a "reaction analytics" provider, that will handle reaction data that we'll use later to drive all dashboard widgets,etc.  

This approach has the added benefit of getting us setup for the https://segment.com/ eco system.

I think that with the addition of analytics.js to your package, convert the current event tracking bits to analytics.js format, and sprinkle on some setttings quickForms - we'd probably have the basic requirements fulfilled, and package we can expand on.

**Comment by spencern** [comment]
Sounds great. I've done some work with analytics.js/segment.io before.
Do we want to provide hooks for additional analytics platforms to connect with core or force other platforms to connect via segment.

I'll do some looking into okgrow:analytics and get something wired up.

**Comment by aaronjudd** [comment]
>@spencern "published an initial version of reaction-analytics that uses the build plugin to enable/disable libraries based on a JSON file. Works with Segment.io, Google Analytics, and Mixpanel and currently tracks pageviews, but opens up analytics.track()/ga()/mixpanel.track() to be used throughout the application.
the build plugin has a few weird limitations, but was able to follow Nemo64's route and create a subpackage reaction-analytics-libs that holds the analytics snippets and allows us to load them conditionally."

@spencern looks great!  the only gotcha I saw was that the package requires `custom.analytics.json`, if the file doesn't exist, the settings form breaks (well, ux wise).  The documentation you wrote more than covers this, but i'm occasionally guilty of adding packages without reading the docs.  It's good to have some kind of messaging there. maybe fallback instructions in the settings page is enough? (I used an annoying alert on the google analytics package).

In any case, I'd suggest we add 
```
{
    "libs": {
        "segmentio": true,
        "googleAnalytics": true,
        "mixpanel": true
    }
}
```
to `reaction-core` as `/client/analytics/custom.analytics.json`

In the same vein, missing configurations are more annoying when it's been deployed to production, and rebuilding or debugging isn't quite as easy, it might be good to have a build error if the file is missing,  to  at least let us know the issue.  Just been thinking about this issue right now with the themes. 

I need to hook up some accounts and take a look at the codebase, explore segment a bit as well.

:+1:  :+1: :100:

**Comment by spencern** [comment]
This is a good call, I'll issue a PR for adding some code to `reaction-core`.
googleAnalytics + Mixpanel enabled by default feels good to you?

**Comment by aaronjudd** [comment]
Yes, I think so, but easy enough to change if we get other feedback.

**Comment by spencern** [comment]
@aaronjudd Added this file to `reaction-core`, but it's not getting read by the build script. Seems to be necessary because of Meteor limitations for it to be in the project root. Haven't investigated too much, but when I stick the file in my base reaction project it works fine. Not sure if you are comfortable with that file existing in the root app, or if we need to try to find a workaround for it to exist in `reaction-core`

**Comment by aaronjudd** [comment]
Yes, that's where I'm putting it (reaction /client/analytics).  I think that's the correct place this (follows the format of themes).   I've got it local and will commit soon with some build updates, or you can PR it.

**Comment by aaronjudd** [comment]
I'm closing this, but there's a number of enhancements that can be made - we can just handle those as the separate issues.

**Comment by xusai2014** [comment]
`"click .enablePkg": function(event, template) {
    var self;
    self = this;
    event.preventDefault();
    return ReactionCore.Collections.Packages.update(template.data.packageId, {
      $set: {
        enabled: true
      }
    }, function(error, result) {
      if (result === 1) {
        Alerts.add(self.label + i18n.t("gridPackage.pkgEnabled"), "success", {
          type: "pkg-enabled-" + self.name,
          autoHide: true
        });
        if (self.route) {
          return Router.go(self.route);
        }
      } else if (error) {
        return Alerts.add(self.label + i18n.t("gridPackage.pkgDisabled"), "warning", {
          type: "pkg-enabled-" + self.name,
          autoHide: true
        });
      }
    });`

the err passed by callback is 'details : undefined error :403 errorType:"Meteor.Error" message:"Access denied [403]" reason:"Access denied"' when enable the reaction-analytics

**Comment by aaronjudd** [comment]
@xusai2014 I just tested in release v0.16.0 and was unable to replicate. Please create a new issue if you continue to have this problem, but this would be a permissions related message thrown from trying to do this `ReactionCore.Collections.Packages.update` in the client.  This looks like old code you are working with, I'd suggesting updating to our latest release if possible..
