### ISSUE TITLE
HOC returning ProductGridContainer should pass all properties to child component

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3511]
For HOCs it's best practice to pass all properties down to the child component.

See: https://reactjs.org/docs/higher-order-components.html#refs-arent-passed-through
(first sentence)

Also I face this need, because otherwise it's not possible to reuse the HOC without copying a lot of boilerplate code.

**Comment by zenweasel** [comment]
@prinzdezibel Remember to assign yourself to an issue when you start work on it just so someone else doesn't grab it thinking it's still open
