### ISSUE TITLE
Remove callbacks from most server db operations

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#3514]
There are a lot of server code blocks that look something like this:

```
Cart.update({ _id: cartId }, update, function (error) {
    if (error) {
      Logger.warn(`Error in setting shipping query status to "pending" for ${cartId}`, error);
      return;
    }
    Logger.debug(`Success in setting shipping query status to "pending" for ${cartId}`, rates);
  });
```

Providing a callback to insert/update/remove makes it asynchronous on the server, but yet there seem to be sequences of events that are assuming the previous line has already finished its update. So I would expect that this patterns leads to random timing errors a lot. It would be much better IMO to remove all the callbacks and wrap in try/catch instead.

```
// Synchronous
const id = Product.insert(doc);
const prod = Product.findOne(id); // prod will definitely be defined

// Asynchronous
const id = Product.insert(doc, callback);
const prod = Product.findOne(id); // prod may or may not be defined
```

There isn’t necessarily anything wrong with intentionally making it async for good reasons, but usually I default to everything being synchronous, and then if I make something async for performance reasons, I put a comment above it explaining that it was intentional.

In hooks I’d say it’s definitely better to be synchronous. In certain methods, where you want the method to return quickly and the user doesn’t really care whether the operation was successful, then those places could use a callback.

Along with searching for and fixing all instances of this issue, it would be a good idea to document these recommendations and explanation in the docs. Meteor docs reference: http://docs.meteor.com/api/collections.html#Mongo-Collection-insert

> On the server, if you don’t provide a callback, then insert blocks until the database acknowledges the write, or throws an exception if something went wrong. If you do provide a callback, insert still returns the ID immediately. Once the insert completes (or fails), the callback is called with error and result arguments. In an error case, result is undefined. If the insert is successful, error is undefined and result is the new document ID.

Performance implications: If operations within methods or method hooks are made synchronous, they may be a little slower to return from the server. But they will also be less error prone, which is part of perceived speed.

**Comment by zenweasel** [comment]
I think we should look at where we are using Collection hooks and possibly move these into more specific `Event.Hooks` that could be asynchronous. Anything that is just creating some sort of side-effect rather than manipulating the original data should be moved to an Event.Hook so that it's not coupled to the original implementation imho. Beyond the scope of this ticket but just an observation.
