### ISSUE TITLE
Broken reference to cfs-graphicsmagick

### ISSUE THREAD

**Issue by love-everyday** [reactioncommerce/reaction#3517]
Hi, I found a bug in  [collectionFS.js](https://github.com/reactioncommerce/reaction/blob/33c3d5b59a88faa73250fac1445dc57b3ca9e12d/lib/collections/collectionFS.js), the Meteor-CollectionFS made  `this.gm` is deprecating,  instead of global `gm`. Could someone check it ?

**Comment by aldeed** [comment]
I would not call it a bug, but yes, `this.gm` should be changed to `gm` to avoid seeing the deprecation warning.

**Comment by impactmass** [comment]
closed by #3554
