### ISSUE TITLE
Avalara does not catch address validation when API throws an error because of invalid address

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3518]
### Expected behavior
When the API throws an error that is about address validation that error should be bubbled up to the user and dealt with

### Actual behavior
Error is thrown in the server console, but not addressed in the client and checkout continues w/o calculating tax.

### Steps to reproduce the behavior
1. Login as admin
1. Enable Avalara
1. Add an item to cart and begin to checkout
1. For address enter this address
US
Fake Name
123 Main St.
LA, 90036
1. Observe that this error is thrown: 
```
Reaction: failed [400] {"error":{"code":"GetTaxError","message":"The address number is out of range","target
````
1. Observe that taxes are not calculated.

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: bug-3474-akarshit-tax-logic
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
Also similar error if you enter a large mismatch between postal code and city/state. (just change the state to a random one)

**Comment by Akarshit** [comment]
@zenweasel 
Whenever we update the shipping address, because of [this](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/taxes/server/hooks/taxes.js#L21) hook, the tax is recalculated. This is the place where we know if Avalara would be able to process tax for this or not, but this is done in async to the saving of address workflow so its a little difficult notify the user here.

One idea could be to do this in sync(before saving the address) and not let the user proceed until Avalara is able to process tax on the address.
Any other ideas?

**Comment by spencern** [comment]
@zenweasel does this still happen on the release-1.8.0 branch?

**Comment by zenweasel** [comment]
So digging more into this flow and it looks like the address validation may have been broken since we changed the `register.js` "provides" parameter from a string to an array. So validation errors were only being throw when we actually try to calculate tax which is why this error appeared. This is fixed now but there's more errors related to validation feedback that I want to take care of.

@rymorgan 
So I think we need to clarify this flow, there are two different scenarios we encounter with address validation. This is not really specific to Avalara as most address validators I looked worked similarly.

1. **API error level validation.**
This is the "I have no idea what to do with this address" error. For this sort of flow I think we need to 
 - Display the error to the user (although the Avalara ones are not always super meaningful but it's all we have)
 - Give them a chance to correct it by re-entering the address (i.e. take them back to the address "add") screen
 - Give them also a chance to say "bypass validation" if they know their address is valid but warn them that tax calculation will not work (should this be a user-configurable message?). I think we should also flag the order and have some way of displaying that flag in the order admin

2. **Address mismatch**

This is the better of the two scenarios although still not awesome. We handle this okay but still not great.

 - We currently compare the customer-entered address and the validation address and allow the customer to "reconcile the diff". This has the very possibly outcome of providing a now valid address.
 - After comparing addresses the address may still be invalid. We need another checkpoint here for "Ok, your address doesn't validate, do you still want to continue w/o tax calculation" and again record this bypass and display in the admin. This "bypass" doesn't exist, it just bypasses it once you submit your "diffed" address

Does that all make sense? I know we have this long standing plan to rewrite the cart but it's been a year since we touched this code and I think it makes sense to make this flow work solidly (and well-designed) once and for all.

In both cases where the customer have bypassed calculation we need to stop calling the calculate tax API because at least for Avalara, this has a cost per API call (although maybe not for errors).

I'm currently not blocked by getting direction as there are still some errors to fix and will get the basic skeleton of the above working but wanted to make sure we were on the same page before investing too much more effort into this.

**Comment by zenweasel** [comment]
An example of an Avalara address validation error:
"The physical location exists but there are no homes on this street. One reason might be railroad tracks or rivers running alongside this street, as they would prevent construction of homes in this location." 🤔

**Comment by zenweasel** [comment]
So here's what I mean. This address fails validation. They could bypass the validation by hitting the button or they can edit the address and resubmit by not bypassing. Bypass button doesn't work yet but you get the idea.

![2018-03-02_16-10-04](https://user-images.githubusercontent.com/72819/36889280-4e942e58-1e34-11e8-87e2-e510081d099c.png)

**Comment by rymorgan** [comment]
@zenweasel I generally agree with your approach. I'll dig into this a little today. It would be helpful if we could maybe talk this out really quick to make sure we're on the same page (aka, that if fully understand all the issues.)

**Comment by rymorgan** [comment]
>Give them also a chance to say "bypass validation" if they know their address is valid but warn them that tax calculation will not work (should this be a user-configurable message?). I think we should also flag the order and have some way of displaying that flag in the order admin

So question about the above. What happens to the store if someone puts in an address that Avalara can't calculate a taxes for? Like will there be penalties for the store? If we allow a user to bypass. I do think if we let them bypass we have to then flat the order. (Just not totally sure how, maybe, high-risk order?) 

In terms of error and bypass. We should show an error on the field or fields that aren't validating. Also, I think we should show a warning icon next to the button and change the button to say "Save without validation". We should also explain what this means to the user (though I'm not really clear what it means to the user, maybe something like "With an invalid address a store may consider your order to be high risk and not complete your order" 

What steps do I need to follow to get to scenario #2? 

Something like this - 
![group](https://user-images.githubusercontent.com/20409254/36929162-09f4b2dc-1e42-11e8-96f3-708c66a85f65.png)

**Comment by zenweasel** [comment]
Specifically the errors we are talking about are not field errors because we never get field-level validation back from Avalara which is why we have this issue in the first place. Avalara just says "I have no idea what this address is" and gives up when it returns API errors.

What we get back from Avalara when the address doesn't match is either

1. An error with the detail as above.
2. A "validated" address that may or may not match the address the customer put in (it almost never matches exactly in a way a computer can understand). 

In the second case sometimes the address is just a slightly corrected version of the address, sometimes it's a completely different address based on the computer guess at what you put in (for example if you put in Los Angeles, CO it will give you some city in Colorado, not tell you that your state is wrong)

**Comment by rymorgan** [comment]
@zenweasel - What steps do I need to follow to get the address validation?

**Comment by rymorgan** [comment]
@zenweasel 

>Give them also a chance to say "bypass validation" if they know their address is valid but warn them that tax calculation will not work (should this be a user-configurable message?). I think we should also flag the order and have some way of displaying that flag in the order admin

So question about the above. What happens to the store if someone puts in an address that Avalara can't calculate a taxes for? Like, will there be penalties for the store if we allow a user to bypass? I do think if we let them bypass we have to then flat the order. (Just not totally sure how, maybe, high-risk order?)

**Comment by zenweasel** [comment]
The penalty is that the shop is still responsible for the tax whether they collect it from the customer or not

**Comment by zenweasel** [comment]
> What steps do I need to follow to get the address validation?

What specifically are you looking for?

**Comment by zenweasel** [comment]
@rymorgan If you use
123 Main St.
Los Angeles, CA 90036
on the branch (`fix-3518-brent-fix-avalara-api-validation`) you should get that error

You need to have Avalara enabled using the configuration data

**Comment by rymorgan** [comment]
@zenweasel -- I was trying to figure out when how I see the "Address mismatch" scenario.

**Comment by rymorgan** [comment]
>The penalty is that the shop is still responsible for the tax whether they collect it from the customer or not

Then we absolutely have to tag the order. So that a shop can make a determination of what to do with the order. We should use this treatment: https://zpl.io/awlXg7b  

The label should read - "Tax not calculated"

**Comment by rymorgan** [comment]
This is a pretty awkward validation flow but I think I have a workable solution. 

Objectives: 

- Show that there is an error to the user
- Encourage the user to make sure that their address is actually entered as intended even though we don't have a specific error or specific way of helping them. That's why I'm hoping we can show all the fields have not validated. 
- Allow them to bypass the validation 
- Warn them that a store might have a problem with their order
- Warn the store that tax has not been calculated 

Here's a clickable prototype. 
https://sketch.cloud/s/kKvyO/all/page-1/edit-shipping-and-billing-no-error/play

Animated version of it: 
![3enhwsugok](https://user-images.githubusercontent.com/20409254/37068242-99ef6134-2162-11e8-8074-2fd928439a3b.gif)

**Comment by rymorgan** [comment]
![edit shipping and billing - no error](https://user-images.githubusercontent.com/20409254/37068378-3aa22cb0-2163-11e8-8493-66aab90ebc61.png)
![edit shipping and billing - avalara error copy](https://user-images.githubusercontent.com/20409254/37068379-3aba858a-2163-11e8-9c4a-525676e7481d.png)
![edit shipping and billing - avalara error](https://user-images.githubusercontent.com/20409254/37068380-3ad2d158-2163-11e8-97b9-e5ad0128c0df.png)

**Comment by zenweasel** [comment]
@rymorgan I feel like you are still assuming we get back info that would allow us to translate that into field-level validations. We don't. You may submit address:

Cool Dude
1234 Main Street.
Anytown, CA 94103

and get back as the "corrected address"

Cool Dude
1234 Main St.
Anytown, CA 94103-3649

Which is why we were allowing the customer to "reconcile" the two addresses. Am I missing something?

In terms of how to handle an order once we have flagged it "not tax validated", that all makes sense to me.

**Comment by zenweasel** [comment]
@rymorgan Let's try to talk today or tomorrow and try to finalize an approach (like you suggested above)

**Comment by rymorgan** [comment]
@zenweasel We'll talk when we sync, but I do get that we aren't getting field level validation in this case. But I was thinking we show all the fields as invalid to signal to the user that maybe they entered their address wrong and give them a chance to correct any errors before they bypass validation. I don't want there to be a case that's like oops I forgot to update the state/province.

**Comment by zenweasel** [comment]
I got the info I needed from Ryan. We both agreed that putting in place some client-side validation will hopefully limit our need to get to these server-side validations. I didn't make much progress on this today but will pick it up on Monday.

**Comment by zenweasel** [comment]
@rymorgan 
To see the address "close match" error you can enter

Cool Dude
8007 Norton Ave.
Los Angeles, CA 90046

And it will correct the city to "West Hollywood"

**Comment by zenweasel** [comment]
@rymorgan Here's this "reconciliation" screen which I think is from your design. This actually works although it's got some styling issues.


![2018-03-13_09-49-05](https://user-images.githubusercontent.com/72819/37318145-ce7f4914-26a3-11e8-94d5-02e5f20eb189.png)

**Comment by rymorgan** [comment]
Yea, we should fix the design above. That's pretty rough. I'll take a look at it. I know I have designs from before.

**Comment by Akarshit** [comment]
I am working on this form now on.

**Comment by spencern** [comment]
@Akarshit FYI @nnnnat has been working on a React conversion of the Address Book. Worth making sure that your work is compatible with #3990

**Comment by cassytaylor** [comment]
Here's the updated address reconciliation design - 

![address-validation](https://user-images.githubusercontent.com/36006187/37620712-433591e8-2b7a-11e8-9563-c3212fa628ed.png)

Like the current implementation, it would appear after hitting "Save and continue" after entering an incorrect address in the cart. We decided that the yellow (warn) alert color would be more appropriate than the teal alert here, and that it would make more sense to allow the user select the entire new suggested address (rather than go line-by-line) with a radio button. The errors in the entered address are highlighted in red. 

The user can choose to continue with the suggested address (selected by default), select the entered address and continue with it, or go back and edit the entered address.

**Comment by Akarshit** [comment]
@spencern Yes, I will be branching off his branch.

**Comment by Akarshit** [comment]
I have the UI for this ready, working on the server issues like
1. The taxCalculation was being done many times.
2. The cart object is updating with only the `updatedAt` field.
and some more.

**Comment by spencern** [comment]
@Akarshit I just learned that @jshimko is working on a way to implement address validation in an abstract way that could be implemented by any number of plugins, make sure that you two connect on this process.

**Comment by Akarshit** [comment]
Yes will do.
