### ISSUE TITLE
`reaction -v` shows the «INFO: Could not find files for the given pattern(s).» phrase

### ISSUE THREAD

**Issue by dmitry-fedyuk** [reactioncommerce/reaction#3526]
### Expected behavior
`reaction -v` should not show the «**INFO: Could not find files for the given pattern(s).**» phrase.

### Actual behavior
`reaction -v` shows the «INFO: Could not find files for the given pattern(s).» phrase

![02](https://user-images.githubusercontent.com/83204/35181123-49aa5e94-fde6-11e7-8520-1e2f8e51bcf7.png)

### Steps to reproduce the behavior
`reaction -v`

### Versions
> Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master

**Comment by zenweasel** [comment]
Valid bug, but should be created on the `reaction-cli` repo, not here. Will create there
