### ISSUE TITLE
The Stripe plugin should use `<input type='password'>` for the «API Secret Key» field

### ISSUE THREAD

**Issue by dmitry-fedyuk** [reactioncommerce/reaction#3527]
### Expected behavior
The Stripe plugin should use [`<input type='password'>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password) for the «**API Secret Key**» field.

### Actual behavior
The Stripe plugin uses `<input type='text'>` for the «**API Secret Key**» field.

### Steps to reproduce the behavior
![01](https://user-images.githubusercontent.com/83204/35183825-6b9122b0-fe16-11e7-8353-906bb45e5d97.png)

### Versions
> Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master

**Comment by zenweasel** [comment]
I for one don't agree. We expect that people editing fields in an admin environment are in a secure setting and this just makes it harder for the admin to ensure they have the correct credentials entered. But it's up to @rymorgan

**Comment by rymorgan** [comment]
I agree. Maybe we could take a beat to update the component to be able to toggle visibility. Then we are getting the best of both worlds. It's really annoying to enter a complicated key or password and not be able to see if you've made a typo. At the same time, it makes sense for this to be secure. 

Here's what I have in mind. 
<img width="450" alt="screen shot 2018-01-23 at 9 30 35 am" src="https://user-images.githubusercontent.com/20409254/35290824-49dbd1e0-0020-11e8-8cc2-e10420dc5c7e.png">

**Comment by aldeed** [comment]
Field no longer exists
