### ISSUE TITLE
Exception while invoking method 'inviteShopMember' TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by faktaochkunskap** [reactioncommerce/reaction#353]
I was trying to add a staff member true the dashboard and got Error sending email, possible configuration issue.Error: Internal server error [500].

I have both tried to add smtp settings in the dasboard and the settings file and also in the environemt. But has not yet succeded with adding a staff member. Tried with port: 25, 465, 587. I am using Google mail. Running local on a Mac.

This is my terminal consol log: 
App running at: http://localhost:3000/
I20150323-00:46:25.500(1)? Exception while invoking method 'inviteShopMember' TypeError: Cannot read property 'name' of undefined
I20150323-00:46:25.500(1)?     at [object Object].Meteor.methods.inviteShopMember (packages/reactioncommerce:core/server/methods/accounts/accounts.coffee:93:48)
I20150323-00:46:25.500(1)?     at packages/check/match.js:109:1
I20150323-00:46:25.500(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150323-00:46:25.501(1)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150323-00:46:25.501(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150323-00:46:25.501(1)?     at packages/ddp/livedata_server.js:648:1
I20150323-00:46:25.501(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150323-00:46:25.501(1)?     at packages/ddp/livedata_server.js:647:1
I20150323-00:46:25.501(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150323-00:46:25.501(1)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)

**Comment by faktaochkunskap** [comment]
Also my test site crashed and are not coming up after two restarts: https://td36nc9y.reactioncommerce.com/

**Comment by aaronjudd** [comment]
@faktaochkunskap the mail issue is a know bug with 4.x release.  It's fixed in 5.x which will be released in soon (maybe even today).

**Comment by faktaochkunskap** [comment]
Ok, great to hear! Then i can continue my evaluation, and soon contribute, hopefully!
