### ISSUE TITLE
Some countries (like Qatar) do not use postal codes, but Reaction Commerce forbids to place an order without a postal code

### ISSUE THREAD

**Issue by dmitry-fedyuk** [reactioncommerce/reaction#3530]
### Expected behavior
Reaction Commerce should not require a postal code for countries not using postal codes:

- [Countries without postal codes](https://gist.github.com/kennwilson/3902548)
- [List of postal codes](https://en.wikipedia.org/wiki/List_of_postal_codes)

### Actual behavior
Reaction Commerce requires postal codes for all countries.

### Steps to reproduce the behavior
![01](https://user-images.githubusercontent.com/83204/35187674-c2ca02fa-fe51-11e7-94b4-6258ca5c7c83.png)

### Versions
> Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master

**Comment by zenweasel** [comment]
That list would appear to be inaccurate as South Africa clearly has zip codes.
https://en.wikipedia.org/wiki/List_of_postal_codes_in_South_Africa
