### ISSUE TITLE
Multiple accounts data per shop with one user to manage it

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#354]
Hi,

In the latest reaction core schemas we have different accounts for different shops but there will be only one user managing these accounts, this could mean that the same user has a different profile info saved in on account than in the other -> to escape this issue we can have set the update account update all the entries in the Account collection which has the current user as userId but whouldn't it be wiser to have the shopId an array as well as the session and they we can have the same account information and we can also save the shops the user contacted or purchased from?
Just asking to see the bigger picture maybe I don't see it :) but for now I have several accounts in my DB for the same user and every time I  refresh the accounts page a different account is loaded mostly if I'm an admin as well.
Thanks in advance :)
Bogi

**Comment by aaronjudd** [comment]
what if it was just have one account per user (overall), but had a new account.profile for each shopId? that way it'd be easy to use change strategies between sharing across shops, or a per shop record adddressBook.

**Comment by boboci9** [comment]
Hi Aaron, since this question you had a new RC release where all the user data was moved to the accounts collection so I don't think this is relevant any more because we now have one account for one user all the time and I don't think we would need shopId in the address book for the multi vendor setup because the user will purchase items from several shops at a time so we wouldn't know what to save there. Sorry I forgot to close this after your release with one account per user.

**Comment by aaronjudd** [comment]
sounds good
