### ISSUE TITLE
Avalara: Fix bug on after hook call

### ISSUE THREAD

**Issue by glmaljkovich** [reactioncommerce/reaction#3540]
The MethodHooks.after("cart/copyCartToOrder") call in the `hooks.js` file return `options` instead of `options.result`. This causes problems when you do subsequent after hooks, since the return value is not the one from the original method call but the options object itself.

**To Test**
```js
MethodHooks.after("cart/copyCartToOrder", (options) => {
   Logger.info("After cart/copyCartToOrder:", options);
   return options.result;
});
```

**Comment by zenweasel** [comment]
Closed via #3539
