### ISSUE TITLE
Updated Lint rules - enforcing react rules

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3544]
From @aldeed 
> I highly recommend switching to the Airbnb style guide and base eslint config. You can have overrides for the few things you do differently. Probably 50% of code smells I've noticed on PR review would be caught by more restrictive linting. Also, Airbnb explains all their code style rules and why very well, so the Reaction code style docs can simply link out to their guide, and then have sections explaining each override choice.

**Comment by spencern** [comment]
@aldeed I'm going to close this in favor of the 9 new tickets that you opened specifically for this.
