### ISSUE TITLE
Audit and remove unused meteor packages

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3545]
Audit the `.meteor/packages` file and identify unused packages.

Any meteor package that is no longer used should be removed from the project.

We should take a long look at any package that provides UI resources to make sure that they are still needed. Create a new ticket for any additional packages that _should_ be removed but are still in use.

Here's a starter list of packages that are worth checking to make sure they are still needed
```
juliancwirko:postcss
underscore@1.0.10
mdg:validated-method
bozhao:accounts-instagram
jparker:gravatar
juliancwirko:s-alert
juliancwirko:s-alert-stackslide
kadira:dochead
natestrauser:select2
raix:ui-dropped-event
react-meteor-data@=0.2.9
gadicc:blaze-react-component
```

**Comment by aldeed** [comment]
Created issues:

- #3548
- #3550 
- #3551 

And removed some in #3552

I will get rid of `gadicc:blaze-react-component` as part of my autoform / blaze removal issue

Added `raix:ui-dropped-event` removal to CFS ticket

Added postcss removal to https://github.com/reactioncommerce/reaction/issues/2468

I think that covers this list. We will have a separate issue later for moving to non-Meteor accounts packages.
