### ISSUE TITLE
Endless loop of Launching first shop, this can take a couple seconds...

### ISSUE THREAD

**Issue by husayndharshi** [reactioncommerce/reaction#355]
Created an account for a demo and upon entering my account, I see an endless loop of "Launching first shop, this can take a couple seconds..." message at the top of the stores table and no changes.

I have tried:
 - sign out, and then signing back in (no change, same issue shows up)
 - adding a new store via the add button (no change, popup to say added to launch queue)

What could be the problem and/or what else can I try to resolve the issue?

**Comment by aaronjudd** [comment]
@husayndharshi thanks for reporting this. Should be fixed now, give another shot.
