### ISSUE TITLE
Remove "juliancwirko:s-alert" Meteor package

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#3550]
Goal:

Remove these two Meteor packages, to help remove Blaze dependency
- juliancwirko:s-alert
- juliancwirko:s-alert-stackslide

Work:

1. Update the alerts code to show the same alert/toast, but without needing these packages. This might mean copying some parts of the package code into the app.
  - /imports/plugins/core/layout/client/templates/layout/alerts/alerts.html
  - /imports/plugins/core/layout/client/templates/layout/alerts/reactionAlerts.js
  - Search for uses of `sAlert` global object in these files. That comes from this Meteor pkg.
2. Remove the Meteor pkgs and make sure tests still pass, alerts still works

**Comment by kieckhafer** [comment]
Julian wirko's react version: https://www.npmjs.com/package/react-s-alert

**Comment by spencern** [comment]
This should now be imported rather than a global, and should be dynamically imported where needed.
