### ISSUE TITLE
Evaluate revision control performance improvements

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3555]
We need to evaluate some ways we could improve the performance of the product grid, specifically for consumers.

1. What would it take to remove the current revision control implementation without losing any dynamic merchandising or admin product editing functionality?

2. What would it take to separate a "published products" collection for non-admins that could operate faster than the existing generic product/revisions publications.

3. What would re-implementing the revisions control look like? What if we versioned the products instead of storing diffs? 

@ticean @aaronjudd

**Comment by aaronjudd** [comment]
@spencern @ticean @mikemurray can we discuss today, and move this forward?

**Comment by spencern** [comment]
I'm happy to discuss this asap. My afternoon is open.

**Comment by ticean** [comment]
This afternoon works for me, too.

**Comment by spencern** [comment]
We have to do something to improve the performance of the product grid, but I think this issue still needs more clarity on exactly what should be done.

**Comment by spencern** [comment]
Not actionable. Closing
