### ISSUE TITLE
Remove unnecessary code in Media subscription

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3557]
After reading quite a bit of code and searching in our code base, I have the impression, that the global Media subscription is not used any longer.

Instead of subscribing explicitely to a subscription, Media metadata is pushed to the client through the publications "products.js" and "product.js". 

I think it's possible to delete the Media subscription and publication altogether.

EDIT: It turns out this publication is used for the brand image, but it can be stripped down significantly.

**Comment by zenweasel** [comment]
So since this subscription is actually used, do we want to close this ticket? Or can we have some more clarity on what we are trying to solve now?

**Comment by prinzdezibel** [comment]
Changed the title from "Media subscription not used any more" into 
"Remove unnecessary code in Media subscription", because that was a wrong assumption. It's still used for publishing of brand assets.

**Comment by zenweasel** [comment]
Closed via #3558
