### ISSUE TITLE
question: initializing product catalog from e.g. csv

### ISSUE THREAD

**Issue by tintoverano** [reactioncommerce/reaction#358]
hello guys,

is there a forum for reaction commerce?

anyway, I was searching the repo and the web but couldn't find any mention of importing loads of products instead of manually creating the product catalog

did anybody solve this already?

thanks,

tinto

**Comment by aaronjudd** [comment]
Come join us on https://gitter.im/reactioncommerce/reaction  (our chat room).

Fixtures can be loaded in private/data/, see: https://github.com/reactioncommerce/reaction-core/blob/development/docs/fixtures.md

**Comment by kefirchik** [comment]
Hi! We have successfully imported about 1500 products with little script, we can publish it a bit later ;)

**Comment by tintoverano** [comment]
@kefirchik would love that  :)

**Comment by alexagui** [comment]
@kefirchik I'd like to see that script as well ;)
