### ISSUE TITLE
Failed to install npm dependencies for plugin: connectors-shopify

### ISSUE THREAD

**Issue by coxw1** [reactioncommerce/reaction#3584]
### Expected behavior
For reaction to run

### Actual behavior
Got an error

### Steps to reproduce the behavior
cd reaction
reaction

### Versions

Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.25.0
Reaction: 1.6.6
Reaction branch: master

### Error:
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Installing dependencies for connectors-shopify...

/bin/sh: line 0: cd: /Users/waz/Sites/MMX: No such file or directory
Failed to install npm dependencies for plugin: connectors-shopify

**Comment by zenweasel** [comment]
@coxw1 Are you saying that Reaction is not starting for you? Because I'm definitely not seeing that.

**Comment by coxw1** [comment]
Yeah, its not starting and throws that error. I tried removing all the files and starting over, but it still throws the same error in the terminal.

Any ideas of how to fix?

**Comment by zenweasel** [comment]
@coxw1 You are doing `reaction init`? And you are on Windows?

**Comment by coxw1** [comment]
@zenweasel No on Mac. 
Yeah, I've done that. 

This is what i did in terminal:
`➜  MMX Group reaction init

Cloning the master branch of Reaction from Github...

Cloning into 'reaction'...
remote: Counting objects: 93975, done.
remote: Total 93975 (delta 0), reused 0 (delta 0), pack-reused 93975
Receiving objects: 100% (93975/93975), 39.25 MiB | 3.95 MiB/s, done.
Resolving deltas: 100% (52293/52293), done.

Installing NPM packages...


> dtrace-provider@0.8.5 install /Users/waz/Sites/MMX Group/reaction/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> fsevents@1.1.2 install /Users/waz/Sites/MMX Group/reaction/node_modules/fsevents
> node install

[fsevents] Success: "/Users/waz/Sites/MMX Group/reaction/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fibers@2.0.0 install /Users/waz/Sites/MMX Group/reaction/node_modules/fibers
> node build.js || nodejs build.js

`darwin-x64-57` exists; testing
Binary is fine; exiting
added 2152 packages in 29.843s

Reaction successfully installed!

To start your Reaction instance, just run: 

 cd reaction
 reaction


********************************************************************************
  Need help with deployment?
  Learn more about the Reaction Platform: http://getrxn.io/managed-platform
********************************************************************************

➜  MMX Group cd reaction 
➜  reaction git:(master) reaction

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Installing dependencies for connectors-shopify...

/bin/sh: line 0: cd: /Users/waz/Sites/MMX: No such file or directory
Failed to install npm dependencies for plugin: connectors-shopify
`

**Comment by zenweasel** [comment]
@coxw1 I was able to successfully `reaction init` and start reaction. So this does not seem like a bug with the project itself. For support with installation you can try our [Gitter Channel](https://gitter.im/reactioncommerce/installation) where we can continue to try and troubleshoot your installation.
