### ISSUE TITLE
Exit 8  V0.5.x On the First Run

### ISSUE THREAD

**Issue by bfMntr** [reactioncommerce/reaction#359]
I20150406-17:13:42.327(3)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
W20150406-17:13:42.623(3)? (STDERR)
W20150406-17:13:42.624(3)? (STDERR) events.js:72
W20150406-17:13:42.624(3)? (STDERR)         throw er; // Unhandled 'error' event
W20150406-17:13:42.624(3)? (STDERR)               ^
W20150406-17:13:42.624(3)? (STDERR) Error: spawn ENOENT
W20150406-17:13:42.625(3)? (STDERR)     at errnoException (child_process.js:1011
:11)
W20150406-17:13:42.625(3)? (STDERR)     at Process.ChildProcess._handle.onexit (
child_process.js:802:34)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

meteor test-packages :  runs perfectly  --  0 tests, no test available.
meteor --debug :  runs fine and suddenly crashes.

**Comment by aaronjudd** [comment]
This is running on windows?
ENOENT is usually a file/directory path error.  

I'll be upgrading all the packages and releasing new packages today, that hopefully capture all the updates made for Meteor 1.1 (windows support).

**Comment by bfMntr** [comment]
yes it  is (running on windows).

**Comment by aaronjudd** [comment]
Just an update, I didn't release updated packages after all, I'd like to implement automated builds #249 as part of the next complete package update, which should cover this windows compatibility issue as well (some packages need to be re-published, version incremented, with the meteor windows release).

**Comment by aaronjudd** [comment]
Closing in favor of #363
