### ISSUE TITLE
Validate phone numbers with country codes for SMS

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3597]
### Expected behavior

Phone numbers should be stored in a standard format so sending SMS messages do no result in an error.

### Actual behavior

Without the country code Nexmo fails to send SMS messages.

### Steps to reproduce the behavior

1. Sign up for a free Nexmo account
1. In the SMS setting panel, enter Nexmo API credentials and test `from` number
1. In user profile edit or add 1st address and enter your phone number without the country code.
1. Run `Meteor.call("sms/send", "TEST", Meteor.userId(), ReactionCore._shopId.get(), console.log.bind(console))`
1. Observe error in terminal
1. In user profile edit or add 1st address and enter your phone number **with** the country code.
1. Run `Meteor.call("sms/send", "TEST", Meteor.userId(), ReactionCore._shopId.get(), console.log.bind(console))`
1. Receive text message!!!

### Versions
Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.25.0
Reaction: 1.6.6
Reaction branch: master
Docker: 17.12.0-ce

**Comment by zenweasel** [comment]
We can use the libphonenumber-js library I recently added to do validation / formatting for phone numbers by county code
