### ISSUE TITLE
Apartment number is missing in the order confirmation email

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#3601]
### Expected behavior
When a user receives an order confirmation email, the address should include an apartment number if the user provided one.
### Actual behavior
Order confirmation is received and address is missing apartment number.
### Steps to reproduce the behavior
1. Select a product and start checkout
2. Add shipping address that includes an apartment number
3. Place order
4. Review order confirmation email
### Versions
Node: 8.9.1
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.25.0
Reaction: 1.6.6
Reaction branch: refactor-3570-willopez-fix-eslint-errors
Docker: 17.12.0-ce

**Comment by spencern** [comment]
@willopez this would be the `address2` field correct?

**Comment by willopez** [comment]
yes, that is correct

**Comment by prinzdezibel** [comment]
Moved to `ready` via https://github.com/reactioncommerce/reaction/pull/3643

**Comment by prinzdezibel** [comment]
Was merged, going to close.
