### ISSUE TITLE
ProductField is very difficult to target via CSS because of missing class name.

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3608]
### Expected behavior
It should be straightforward to overwrite the CSS styles of PDP fields like title, vendor or description through using class selectors. This is not possible in a straightforward manner. One could use CSS selectors like `.pdp.field:nth-child(n)`, but these would be very brittle.

### Actual behavior
No field specific class name is added to generic ProductFields in markup.

### Steps to reproduce the behavior
Go to page PDP. See HTML source of page.

![developer_tools_-_http___localhost_3000_product_reaction-mug_and_reaction_mug](https://user-images.githubusercontent.com/1733229/35507813-55b5fcfc-04ee-11e8-97fa-cba90820c79d.jpg)

**Comment by zenweasel** [comment]
Closed via #3609
