### ISSUE TITLE
Help with integration payment

### ISSUE THREAD

**Issue by Rafazeon** [reactioncommerce/reaction#3616]
https://github.com/moip/moip-sdk-node#api-reference
Has anyone tried to integrate this library yet? I needed to use the means of payment, as there are all those that are needed in Brazil, anyway I'm trying to do the integration too, thanks if anyone can help

**Comment by zenweasel** [comment]
Hi @Rafazeon, this is probably a topic more appropriate for the [forums](https://forums.reactioncommerce.com). You may also want to check out this tutorial on [creating a payment provider](https://docs.reactioncommerce.com/reaction-docs/master/creating-a-payment-provider)
