### ISSUE TITLE
Marketplace - allow sellers to signup - error on "Become a seller" click

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#3617]
### Expected behavior
When Marketplace is enabled, and the checkbox is checked to allow users to register themselves as sellers, users should be able to create a shop.

### Actual behavior
When "Become a seller" is clicked in a user's profile, the following error appears in console and the entire site is blank from there on out.

TypeError: Cannot read property 'name' of undefined
    at TagNav.renderShopSelect (tagNav.js:67)
    at TagNav.render (tagNav.js:108)

### Steps to reproduce the behavior

1. npm init, cd reaction, reaction
2. Login as admin, enable Marketplace, check checkbox to allow users to register as sellers
3. Logout and register a new acccount
4. Visit profile, click "Become a seller"

### Versions
(run `reaction -v` from your reaction directory)
Node: 6.2.2
NPM: 5.0.3
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
Docker: 17.09.1-ce

**Comment by zenweasel** [comment]
This is probably the same bug as #3652

**Comment by JoeyLyman** [comment]
I get this too
