### ISSUE TITLE
Shop Switcher Opens Off-Screen

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#3619]
It seems that once you get over `n` Shops, the Shop Switcher becomes too long, and is positioned above the label. (I'm not positive what _`n`_ needs to be to make this happen, but I have 24 currently)

![image](https://user-images.githubusercontent.com/1158287/35619723-e5728ed2-064c-11e8-83b9-eab1869a4571.png)

### Expected behavior
The drop-down to appear on the screen (and be scrollable, I guess?)

### Actual behavior
It appears above the selector, but since that is located in the navbar, it is rendered off screen, above the top of the page (see screenshot).

### Steps to reproduce the behavior
Create 24 Shops on a 13" MPB (that may not be the exact number, but that is what I have now and notice the issue)

### Versions
`master`

**Comment by aaronjudd** [comment]
Sounds like an issue with the dropdown component - probably not specific to the shop switcher itself?
