### ISSUE TITLE
Miscellaneous charges

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#362]
I think there should be a miscellaneous charges array in the schema. It would make things like #160 (gift-wrapping) and extra charge for COD or for other perks easy.

We can easily add a method in payment integrations and checkout to add these misc. charges to the total.

**Comment by aaronjudd** [comment]
This could be handled as a credit field for #215. Possibly that one of these could be closed.

**Comment by rymorgan** [comment]
Removing from design project. I don't think it needs a design phase.
