### ISSUE TITLE
Audit and fix / replace any npm or meteor packages which use moment or moment-timezone

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3621]
PR #3602 dynamically import moment and moment-timezone in all Reaction owned filed.

This ticket is to audit and discuss solutions for `npm` and `meteor` packages which use either `moment` or `moment-timezone`.

### Meteor
`aldeed:meteor-autoform`: Ticket #3034 is already removing this package

### npm
`bunyan` -> `moment`
`joi` -> `moment`
`node-loggly-bulk` -> `moment`
`react-dates` -> `react-moment-proptypes` -> `moment`
`twilio` -> `moment`

**Comment by kieckhafer** [comment]
@spencern @aldeed 

I spoke with @mikemurray about `react-dates`, and it's used only in our calendar picker. We can use `react-loadable` to dynamically import the Calendar Picker component where it's needed.

Thoughts on the others?

**Comment by spencern** [comment]
If we're importing the packages that include `moment` dynamically (e.g. Twilio), I would imagine that is enough to not load moment globally.

`joi` is not a top level dependency for us, and is included with `Nexmo` which I think we are now dynamically importing.

It looks like we use `bunyan` for our client logger, but perhaps we can rethink that choice or only import for certain `env`s 

`loggly` is used for our server logs, and we could try to find a logger that doesn't use moment, or we can just eat the cost on the server, for now. I'm definitely more concerned with moment on the client.

**Comment by kieckhafer** [comment]
Yes, Twilio and Nexmo are both loaded dynamically now via #3594 

So `bunyan` is the main culprit, and then `loggly` if we want it off the server as well?

**Comment by aaronjudd** [comment]
Loggly is  / should be an optional tool, perhaps you could avoid loading on client, use on server, and only if the ENV vars have been configured.  Bunyan should be available both client and server, but we could easily add a client logger that just sent the message to the server installation that feeds the client log data to a server-side Bunyan, thus removing the requirement for the client?   At this point though, bunyan remains a core requirement (but I could see us transferring responsibility to a service once that part of our next architecture is up and running)

**Comment by aaronjudd** [comment]
You may also want to consider http://moment.github.io/luxon/ instead of the full moment on client.

**Comment by kieckhafer** [comment]
@aaronjudd I've already got moment to load dynamically on everything we can control: #3602 , was just wondering about our npm and meteor packages here.

Do you think luxon is a better choice in the long run for our code?

**Comment by aldeed** [comment]
From what I can tell, moment is an optional dependency of bunyan, and it throws errors only if you use an option that requires it, which maybe we could avoid?

https://github.com/trentm/node-bunyan/blob/c0932196dd6846189ec82623c12d051eee799d4f/bin/bunyan#L29-L33

**Comment by aaronjudd** [comment]
@kieckhafer re: Luxon - maybe long term, but nothing to worry about now I think...

**Comment by kieckhafer** [comment]
Merged into `1.8`
