### ISSUE TITLE
Screen shifts awkwardly after adding more than 7 top-level categories

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3626]
### Expected behavior
You should be able to add/edit more than 7 top-level tags (number may depend on the length of the Tag name)

### Actual behavior
Screen shifts so that you can't edit tags any longer
![2018-02-01_11-30-32](https://user-images.githubusercontent.com/72819/35659842-89e9b598-0743-11e8-945f-c0b41a078b01.png)

### Steps to reproduce the behavior
1. Login as admin
1. Narrow browser width to something like 1024
1. In TagNav editor enter categories:

 - Apparel
 - Electronics
 - Kitchen
 - Sports
 - Bath & Body
 - Groceries & Pets
 - Motors
1. Observe that the screen shifts awkwardly

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
This also makes the login inaccessible when you have more than a few tags as we can see in load testing so bumping this up.

**Comment by aldeed** [comment]
The UI that had this issue is gone in 2.0.0
