### ISSUE TITLE
Cannot set Email Template language

### ISSUE THREAD

**Issue by joelquatro** [reactioncommerce/reaction#3627]
### Expected behavior
When setting the language field in Reaction.registerTemplate, it should be stored in the db alongside the rest of the fields.

### Actual behavior
Field gets ignored and does not impact in the db.

### Steps to reproduce the behavior
Reaction.registerTemplate({
    title: "Title",
    name: "name",
    type: "email",
    **language: "es",**
    template: "blaze template",
    subject: "subject"
  });

### Versions
(run `reaction -v` from your reaction directory)
Node: 8.9.3
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.3
Reaction branch: master
Docker: 17.09.0-ce

**Comment by zenweasel** [comment]
@joelquatro Can you clarify what exactly you were expecting. It seems like this is working correctly:

```
    const shopId = Reaction.getShopId();
    // Register template
    const sampleTemplate = {
      name: "test-template",
      template: "<div>Test</div>",
      language: "en",
      type: "template"
    };
    registerTemplate(sampleTemplate, shopId);

    const actualTemplate = getTemplateByName("test-template", shopId);
    console.log("actual template", actualTemplate);

    actual template { name: 'test-template',
    template: '<div>Test</div>',
    language: 'en',
    type: 'template',
    parser: 'handlebars'
}
```

**Comment by zenweasel** [comment]
Closing. Reopen if you are still having an issue.
