### ISSUE TITLE
Convert Products collection hooks to Hooks.Events

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#3634]
### Work

For the `Products` collection, convert all collection hooks to use `Hooks.Events`.

### Example

```js
Orders.before.insert((userId, order) => {
  const analyticsEvent = {
    eventType: "buy",
    value: order._id,
    label: "bought products"
  };
  AnalyticsEvents.insert(analyticsEvent);
});
```

becomes...

```js
Hooks.Events.add("beforeOrderInsert", (userId, order) => {
  const analyticsEvent = {
    eventType: "buy",
    value: order._id,
    label: "bought products"
  };
  AnalyticsEvents.insert(analyticsEvent);
});
```

And then search for all `Orders.insert` in the app, and immediately before call:

```js
Hooks.Events.run("beforeOrderInsert", userId, order);
```

### Direct Operations

If a call is direct, i.e., it does something like `Orders.direct.insert`, then that does NOT run the collection hooks. Therefore you MUST remove the `.direct` part but MUST NOT add `Hooks.Events.run` before or after it.

### Types of Hooks

See full list of hooks here: https://github.com/matb33/meteor-collection-hooks

For searching for them, searching for `<CollectionName>.before` and `<CollectionName>.after` should be enough.

**Comment by spencern** [comment]
@willopez why did this issue get moved from `In Progress` to `Icebox`?

**Comment by willopez** [comment]
Per our discussion in a stand up meeting, you suggested the move and to refactor using Meteor methods as hooks will not be provide all the functionality needed.

**Comment by spencern** [comment]
@willopez That is the case, but we still have resolve this issue. As far as I'm understanding, this issue is still in progress until otherwise noted. If you're not sure how to proceed from here, please ask someone to pair with you on it.

**Comment by willopez** [comment]
@spencern it was only in the icebox for the bug sprint, I was planning on resuming work on performance sprint two, so I am back on this one!

**Comment by spencern** [comment]
Perfect, thanks for the update @willopez
