### ISSUE TITLE
Product Images are using full res image and not the processed versions

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#3637]
When I was working on this [PR](https://github.com/reactioncommerce/reaction/pull/3631) I started to notice the full resolution product image was being used in almost every instance. I thought it was only in my branch but I've tested it on master and have seen it every time. Can someone test and confirm I'm not crazy?

### Expected behavior
- Product images should be referencing the appropriate image crop in the `src` attribute.
- For example, product images on the invoice page should be using the `thumbnail` crop
- The image `src` path should look something like this `/assets/files/Media/Z5v7ARFEjWKdoSymL/shoe.jpg?token=eyJhdXRoVG9rZW4iOiJwVnVKS2J5WVRjcG1yOG03QU4ybk15ZkFPb2VXUzJjaGh6Y0VERHZwckxvIn0%3D&store=thumbnail`

### Actual behavior
- Product images are only referencing the full resolution uploaded image
- Product image `src` path looks like this `/assets/files/Media/Z5v7ARFEjWKdoSymL/shoe.jpg?token=eyJhdXRoVG9rZW4iOiJwVnVKS2J5WVRjcG1yOG03QU4ybk15ZkFPb2VXUzJjaGh6Y0VERHZwckxvIn0%3D` without the `&store={size}`

### Steps to reproduce the behavior
- Run `reaction reset` to get a fresh reaction store.
- Login as admin and upload new product images to the sample product
- Upload images to each product variant
- Check the `src` and image info of the new product images to see it's referencing the original uploaded image and not the cropped version
- In another browser purchase both product variants as a guest
- On the invoice page, inspect the product thumbnails to see it referencing the full image and not the thumbnail version

**screenshots**
<img width="1680" alt="product-detail" src="https://user-images.githubusercontent.com/1135948/35709952-94ca8438-077a-11e8-9765-2c50e433be05.png">
example of small image referencing the og image

<br/>

<img width="614" alt="product-varient" src="https://user-images.githubusercontent.com/1135948/35710002-c84ae0dc-077a-11e8-95c8-c2af087bc40d.png">
product variant images referencing the og image and not the small square version

<br/>
<br/>

<img width="308" alt="invoice-thumbnails" src="https://user-images.githubusercontent.com/1135948/35710052-f7f9b3a8-077a-11e8-848b-935b4e5c999b.png">
product thumbnail on the invoice/receipt page using the og image and not the thumbnail version

### Notes
**Possible Cause**
I did some poking around the code base and I think the issue might be coming from these React Components ([media.js](https://github.com/reactioncommerce/reaction/blob/f40ff536c139d70da02ca10ae12655247452d658/imports/plugins/core/ui/client/components/media/media.js#L88) & [mediaGallery.js](https://github.com/reactioncommerce/reaction/blob/f40ff536c139d70da02ca10ae12655247452d658/imports/plugins/core/ui/client/containers/mediaGallery.js#L87)) I'm still pretty new to RC so I might be totally wrong about this.

**Possible related issue**
#3399 

**Images I used**
![bike](https://user-images.githubusercontent.com/1135948/35710409-ed06fa76-077c-11e8-965a-107b27526384.jpg)
![shoe](https://user-images.githubusercontent.com/1135948/35710410-ed1bb7e0-077c-11e8-8eaf-35eaa8328204.jpg)

### Versions
```shell
Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
```

**Comment by mattt416** [comment]
Had a quick peek, and every instance of the image on my dummy product (including on the invoice page) seems to have the exact same URL:

/assets/files/Media/hhXmgHnotqy98yASp/trek-bike.jpg?token=eyJhdXRoVG9rZW4iOiJ6MVNjVXBzZVJhUkkxR05oUExTV0V4Z0NTWmZBZWwxVGhwLWQ4THRjZW5sIn0%3D

```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by kieckhafer** [comment]
Notes for reference.

PDP:
![sweet_tee_s](https://user-images.githubusercontent.com/4482263/36123136-a03aff12-1000-11e8-8336-7e4af2590bc3.png)

Cart:
![sweet_tee_s](https://user-images.githubusercontent.com/4482263/36123195-c88c3314-1000-11e8-9bb7-988ccc73a939.png)

Post-cart Invoice:
![sweet_tee_s](https://user-images.githubusercontent.com/4482263/36123309-1363d996-1001-11e8-8478-e6423554bf85.png)

Order fulfillment: Large view orders list:
![sweet_tee_s](https://user-images.githubusercontent.com/4482263/36123356-3813c102-1001-11e8-8df9-4dd1cd5409d5.png)

Order fulfillment: Invoice Summary
![sweet_tee_s_and_boards_ _reactioncommerce_reaction](https://user-images.githubusercontent.com/4482263/36123419-6430602e-1001-11e8-9b8d-c01bd6755728.png)
