### ISSUE TITLE
Default reaction.json leaves stripe plugin state in limbo.

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3646]
### Expected behavior
Starting reaction with default reaction.json in /private/settings should lead to stripe payment processor to be disabled completely.

### Actual behavior
Stripe is apparently not disabled completely/properly. Instead the checkout process shows the email field when "Checkout as guest" is clicked. This email field should not appear here. Interestingly the stripe settings is not enabled in the admin backend. I think this happens, because the "enabled" property is redundant in the package collection and its boolean values differ:
```
{
    "name" : "reaction-stripe",
    "enabled" : true,
    "settings" : {
        "reaction-stripe" : {
            "enabled" : false
         }
     }
```

### Steps to reproduce the behavior
1) reaction reset
2) start reaction with default reaction.json
3) put an item to cart
4) go to checkout
5) choose "Checkout as guest"
6) See the email field gets active, even if it shouldn't (because stripe is not enabled [properly])

**Comment by prinzdezibel** [comment]
Noticed when working on #3638.

**Comment by zenweasel** [comment]
As noted in another ticket, these booleans are not redundant. One refers to whether it should show up in the dashboard, and one refers to whether it is actually enabled/disabled. Someone is probably checking the wrong value.

**Comment by prinzdezibel** [comment]
@zenweasel This is what I was thinking too. But then I've realized, that toggling stripe on/off
actually alters both booleans synchronously. Which doesn't quite make sense. Also the
plugin appears still in dashboard, even if the upper boolean is false. I guess that the behavior/intention of the booleans may have changed over time causing the inconsistent behavior we see now.

**Comment by spencern** [comment]
@zenweasel can you clarify for us if this is a bug or if this is expected behavior?

**Comment by aldeed** [comment]
No longer relevant in 2.0.0
