### ISSUE TITLE
Error in browser console when opening a Shop Manager invitation

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3652]
### Expected behavior
No errors in console

### Actual behavior
Receive a chain of errors all similar to this:
```

meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:992 TypeError: Cannot read property 'name' of undefined
    at TagNav.renderShopSelect (tagNav.js:67)
    at TagNav.render (tagNav.js:108)
    at modules.js?hash=e9468052767b9b2f8210b4edd369da11ea62eda7:141572
    at measureLifeCyclePerf (modules.js?
```

### Steps to reproduce the behavior
1. Login as admin and enable Marketplace
1. Invite a user
1. Using Incognito to open the link in the invitation
1. Observe errors in browser console

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by Akarshit** [comment]
@zenweasel This happens because when the shop has not been set to active(we only publish active shops to client).
What should be done in the case when the shop has not yet been activated and the admin of that shop is using the invite link?

**Comment by zenweasel** [comment]
Marketplace admins should have access to their shop even when it's not active

**Comment by Akarshit** [comment]
@zenweasel The problem is in the publishing of merchant shops, [here](https://github.com/reactioncommerce/reaction/blob/master/server/publications/collections/shops.js#L52) we are only publishing the `active` shops if the user doesn't have `admin` role for primary shop.
We need to change it so that all the shops that the user is `admin` for are published.
But now Shop Manager doesn't have `admin` role #3505, do we need to do something for the Shop Manager? Is Shop Manager supposed to see `inactive` shops?

**Comment by zenweasel** [comment]
Shop Managers should not see all inactive shops, but they should see **their** shop whether it is active or not. So you may need to modify the publication so that they see active shops + their shop (probably need to extend the query)

**Comment by Akarshit** [comment]
@zenweasel Is there some specific `role` having which the users would be able to see the shops(active shops + their shops).

**Comment by zenweasel** [comment]
Try inviting a shop owner and checking their roles to see what's there, I don't know off the top of my head

**Comment by Akarshit** [comment]
@zenweasel I did that, the roles that I think could be used to check are `core`, `dashboard` and `marketplaceShops`. Do you think any of these would work?

**Comment by zenweasel** [comment]
Dig a little deeper and determine if `marketplaceShops` is the role assigned to shop admins. Maybe @impactmass can help us?
