### ISSUE TITLE
React throws setState warnings for NotificationDropdown component

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3654]
### Expected behavior
There should be no setState in the console when using Reaction. This particular issue relates to the `setState` warnings seen in the `NotificationDropdown` component.

### Actual behavior
When loading Reaction, as a user who has notifications enabled, a `setState` warning is given as `moment` loading causes the component to unmount before the state is set.

### Steps to reproduce the behavior
- Login as a user who has notifications enabled.
- Open your console
- See errors when Reaction is loaded

**Comment by spencern** [comment]
Specific things to check with this issue:
Make sure that we're not loading moment while the dropdown is hidden.

**Comment by mikemurray** [comment]
This component doesn't exist in the new Operator experience.
