### ISSUE TITLE
Configuration for GeoIP lookup server URL should not be hardcoded

### ISSUE THREAD

**Issue by ticean** [reactioncommerce/reaction#3655]
The GeoIP server is hardcoded in the GeoIP module. Change this to use configuration from a setting or env.

The value is hardcoded in these locations:

1. [`server/api/geocoder.js`](https://github.com/reactioncommerce/reaction/blob/f40ff536c139d70da02ca10ae12655247452d658/server/api/geocoder.js)
2. [`imports/plugins/core/accounts/client/templates/addressBook/add/add.js#L13-L18`](https://github.com/reactioncommerce/reaction/blob/f40ff536c139d70da02ca10ae12655247452d658/imports/plugins/core/accounts/client/templates/addressBook/add/add.js#L13-L18)

---

Reference #1837

**Comment by aldeed** [comment]
This code was removed in 3.0
