### ISSUE TITLE
Right to left sidebar animation is not reversed as it should be. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#3656]
Right to left sidebar animation is not reversed as it should be. 

### Expected behavior
When I'm using the app in right to left language the sidebar animation should slide from the left not from the right. 

### Actual behavior
It does the reverse.

### Steps to reproduce the behavior

1. Switch to right to left language
2. Open side bar

See example: 
![vbqxz5uvkl](https://user-images.githubusercontent.com/20409254/35891148-ace9fe1e-0b57-11e8-9cc2-a21ff94fa629.gif)

### Versions

Node: 6.11.4
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.3
Reaction branch: master

**Comment by Akarshit** [comment]
Couldn't reproduce this on the `release-1.8.0` branch. 


![](http://g.recordit.co/MNMID4AoKT.gif)

**Comment by zenweasel** [comment]
@Akarshit What RTL language is being used in the original bug report there? I think @rymorgan did this in Hebrew? Can you try in this as well?

**Comment by Akarshit** [comment]
Yes, Hebrew is used in @rymorgan's GIF. Checked that too, the Action Menu animation is correct with that too.

**Comment by rymorgan** [comment]
I'm still seeing it. See if others can reproduce.

**Comment by rymorgan** [comment]
@kieckhafer Can't reproduce either so I'm going to close.

**Comment by zenweasel** [comment]
@rymorgan not sure why you tagged @kieckhafer but ok 😄

**Comment by rymorgan** [comment]
@zenweasel To annoy him with github notifications, obviously, lol.
