### ISSUE TITLE
Product URL not opening selected variant

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3660]
### Expected behavior
When you click the product in the cart, the PDP should open with the matching option/variant selected.

Generally - product urls are not working (from checkout or otherwise) to select variants.

### Actual behavior

Opens the first/default variant.
<img width="1291" alt="basic_reaction_product" src="https://user-images.githubusercontent.com/439959/35937114-0d67d318-0bfa-11e8-8451-22b307e5aa0a.png">

### Versions
Testing #3645 
```
Node: 8.9.3
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce
```

**Comment by spencern** [comment]
This could be an issue with the link from the cart or the way that the PDP resolves the route from the cart or both.
