### ISSUE TITLE
Cart's X is not aligned

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#3667]
### Visual bug: Screenshots

| Expected   	| Actual     	|
|----------	|:------------:	|
| <img width="316" alt="screen shot 2018-02-08 at 11 10 22 am" src="https://user-images.githubusercontent.com/3673236/35992979-c545c744-0cc0-11e8-966d-c839ee6cf6da.png">	| <img width="277" alt="screen shot 2018-02-08 at 11 10 51 am" src="https://user-images.githubusercontent.com/3673236/35992980-c55cf900-0cc0-11e8-8d04-541f3296a5ba.png">|

### Expected behavior
- The (X) icon should be centered, relative to the corner of the image.

### Actual behavior
- The (X) is a few pixels too far to the left.

### Steps to reproduce the behavior
1. Add an item to cart.
2. Click the cart. 
3. Observe cart.

### Versions

```
Node: 8.2.1
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.09.0-ce
```

- Google Chrome
- Mac OS X
- http://whatismybrowser.com/w/AX335CK

### QA

QA'd by @willopez + @machikoyasuda 

For enhancements or other issues, please describe, in as much detail as
possible, how the app should be changed, and how this would benefit other users and developers.

**Comment by cassytaylor** [comment]
It looks like this issue could be resolved by simply removing the 2px border on the "X" button.. or at least it would make any misalignment less noticeable :)  
<img width="505" alt="screen shot 2018-02-13 at 12 03 13 pm" src="https://user-images.githubusercontent.com/36006187/36168454-668bd08c-10b6-11e8-8937-2cdca898debf.png">

here's a mock with the button moved down a couple of pixels as well (so it's centered over the top edge of the product image); 
![cart-items 2x](https://user-images.githubusercontent.com/36006187/36168625-ef3d7b4c-10b6-11e8-9c4c-17eae51c703b.png)

**Comment by aaronjudd** [comment]
👍 I also saw this (new) ui issue.. @cassytaylor there is no reason to the current X UI -> except it's leftover from the most early days of creation, and can be safely updated as I also think this is the only representative of this ui anywhere -> maybe we could look at what the modal / popup X styling and converge on a normal "X"? In this case, I think that'd probably just mean removing the color background on the X as well.

**Comment by kieckhafer** [comment]
@cassytaylor Came into this ticket to assign it to myself. I fixed the alignment issue in #3740, happy to discuss updating the styling as well if we want to do that at this time.

**Comment by cassytaylor** [comment]
@aaronjudd @kieckhafer yeah, in terms of making it consistent with the next most similar "remove" X button - the one on the PDP product images in Edit mode - I think it would just require changing the background to white. 

I haven't done a full audit of all of the remove/close icons around the site, but it sounds like @rymorgan wants to move to a model in the cart where you'd edit the quantities of the items vs. clicking "X" to remove them, so the "X" buttons would generally be used to close things going forward - but that's probably a discussion for a different time :)

**Comment by kieckhafer** [comment]
@cassytaylor The PDP page does not have a border on it either, which makes it look a bit odd in the cart with a white background, when the image has a white background too:

![sweet_tee_s](https://user-images.githubusercontent.com/4482263/36178986-88450590-10cf-11e8-95f6-e475deacca49.png)

I think white background + 1px border (dropped from 2px) looks pretty good and more consisten, what do you think?

![sweet_tee_s](https://user-images.githubusercontent.com/4482263/36179032-aed72f12-10cf-11e8-8aa2-4a0c93265844.png)

**Comment by cassytaylor** [comment]
@kieckhafer hmm 🤔the designer in me wants to get rid of the border entirely, but I do agree with you that it works better for product images with white backgrounds (so generally, most all).. 

Maybe we could compromise and keep the pinkish gray background (but no border)? 

@rymorgan and I will be working on reining in all of these components with the style guide... so we'll create some rhyme and reason for all of these soon, haha.

**Comment by kieckhafer** [comment]
@cassytaylor 
![sweet_tee_s](https://user-images.githubusercontent.com/4482263/36181340-4fb87306-10d9-11e8-970e-e0621b543a13.png)

**Comment by cassytaylor** [comment]
@kieckhafer, works fer me!

**Comment by rymorgan** [comment]
I get the logic to where we ended up here, but it shouldn't be that yellow. I think it should be like 15% grey. We do need to revisit this whole ux flow for removing items from cart though.

**Comment by kieckhafer** [comment]
Updated to be grey.
