### ISSUE TITLE
Choosing between several Shipping/Billing addresses is blocked by UI lag

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#3672]
### Screenshot gifs

| Expected: 1.7   	| Actual: 1.8     	|
|----------	|:------------:	|
| ![out2](https://user-images.githubusercontent.com/3673236/35996604-d2415aa2-0ccb-11e8-9937-908f96896c30.gif)| ![out](https://user-images.githubusercontent.com/3673236/35996602-d224fdd0-0ccb-11e8-9204-76c2d56daa41.gif)|
|In 1.7, choosing between Shipping/Billing addresses should be fast and responsive. After I click on a different address, I see the blue icon to indicate that that address has been chosen.|In 1.8, after I click on a different address, the blue icon sometimes does not move. The UI is blocked by an operation on the back-end: tax calculation.|

### Steps to reproduce the behavior
1. Go through the steps of checking out as an anonymous or logged in user
2. Add a second address during Step 2
3. Toggle between the two addresses

### Versions

```
Node: 8.2.1
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.09.0-ce
```

Browser: http://whatismybrowser.com/w/KE449ZE

### QA

QA by @willopez + @machikoyasuda

**Comment by zenweasel** [comment]
We should probably try to make titles more descriptive than "is buggy". Maybe "is unresponsive" or "UI lags" or something? Makes is easier to find issues later on.

**Comment by machikoyasuda** [comment]
Retitled to `blocked by UI lag`

**Comment by kieckhafer** [comment]
This is also happening on the user profile page - which makes sense, since it is the same component.

My initial thought was shipping was recalculating in the background, and the lag was due to the calculations not being finished.

**Comment by spencern** [comment]
May be related to some of the collection hooks changes we've made recently.

**Comment by kieckhafer** [comment]
https://github.com/reactioncommerce/reaction/pull/3463 seems to alleviate the bulk of the issue here. There is still a small delay - it takes `~.5` - `1`s for the address to be "active" to be changed again after it's clicked, but it's much better.

**Comment by spencern** [comment]
I'm still seeing some issues where the selector freezes entirely. In some cases the database ends up in an invalid state
![image](https://user-images.githubusercontent.com/1203639/36322631-52059934-130b-11e8-8cf9-29898e4c677e.png)
