### ISSUE TITLE
Unneeded "Cancel" button visible on change password screen

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3674]
### Expected behavior
- There should be no "Cancel" button n the update password area of the User profile

### Actual behavior
- There is a "Cancel" button in the update password area of the User profile
- The cancel button does nothing

![account_profile](https://user-images.githubusercontent.com/4482263/36113101-8b521f60-0fe0-11e8-81ce-3e789a1c50cb.png)

### Steps to reproduce the behavior
1. Login as a registered user
2. Navigate to your user profile
3. See the cancel button in the password reset area

### Versions

```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 18.01.0-ce
```

Browser: http://whatismybrowser.com/w/KE449ZE

### QA

QA by @kieckhafer + @cassytaylor

**Comment by spencern** [comment]
@rymorgan @cassytaylor We probably need some design direction on whether this button should exist or not, and if so, what it should say and do.

**Comment by cassytaylor** [comment]
@rymorgan and I agree that the cancel button isn't needed here.

**Comment by zenweasel** [comment]
@cassytaylor Once design input is complete for a ticket can you unassign yourself? My folks won't grab a ticket that already has an assignee. Thanks!

**Comment by trojanh** [comment]
@aldeed we can close this as well maybe?
