### ISSUE TITLE
Show a warning before deleting an address from the user profile

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3676]
### Expected behavior
- There should be a warning alert / action shown before deleting an address from the address book

### Actual behavior
- No warning alert / action is shown before deleting an address book

### Steps to reproduce the behavior
1. Login as a registered user
2. Navigate to your user profile
3. Add an address (if one is not already there)
4. Delete the address

![delete addresses mov](https://user-images.githubusercontent.com/4482263/36002492-3569ee60-0cdf-11e8-80aa-b8c1d867b049.gif)

### Versions

```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 18.01.0-ce
```

Browser: http://whatismybrowser.com/w/KE449ZE

### QA

QA by @kieckhafer + @cassytaylor

**Comment by aldeed** [comment]
Old UI
