### ISSUE TITLE
Set primary shipping / billing address if only one address is left

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3677]
### Expected behavior
If my primary shipping / billing address is deleted, and there is only address left in the address book, it should automatically become my primary address

**OR**

I should not be able to delete my primary address, I should have to remove primary status before deleting an address

### Actual behavior
- When my primary shipping / billing address is deleted, a remaining address does not become the primary

### Steps to reproduce the behavior
1. Login as a registered user
2. Navigate to your user profile
3. Add two addresses
4. Delete your primary address

![delete addresses mov](https://user-images.githubusercontent.com/4482263/36002492-3569ee60-0cdf-11e8-80aa-b8c1d867b049.gif)

### Versions

```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 18.01.0-ce
```

Browser: http://whatismybrowser.com/w/KE449ZE

### QA

QA by @kieckhafer + @cassytaylor

**Comment by spencern** [comment]
@rymorgan we may need some design direction on this.

**Comment by aldeed** [comment]
Leaving this open because I think it's still something the API mutations should do and don't

**Comment by rymorgan** [comment]
The behavior should be the 2nd scenario 

> I should not be able to delete my primary address, I should have to remove primary status before deleting an address

**Comment by MohanNarayana** [comment]
The issue is not reproducible as the interface has changed. 
Note: Addresses are saved in DB without a flag indicating if it is primary or not. I suspect saving an address as primary is not a feature in the current work flow.
