### ISSUE TITLE
Bundle Product Type

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#368]
### Bundled Products Use Case

The most popular products that my company rents online are packages containing several products, but listed and added to the cart as an individual product.
#### Complete Outfit Example

We rent a number of 'Complete Outfits' to our customers. These products include a Jacket, Pants, Goggles, and Gloves. Ideally we can present these products to our customers as a single item, in the product catalog as well as on a product page.

We would need to have the ability to add additional images to the bundled product as well as pulling in the existing images of the products that make it up.

We would need to be able to pull in all of the options associated with the products that make up the bundle. The user should be able to select options for each part of the bundle as if they were viewing that individual product.
##### Womens Complete Outfit
- Jacket
  - Size
  - Color
- Pants
  - Size
  - Color
- Goggles
  - Lens Type
  - Glasses Compatible or nah
- Gloves
  - Size
  - Color
##### Inventory

The inventory should be linked between bundled product 'parts' and their corrosponding individual product. I think this could be done by actually having the bundled product reference the individual product. The bundle shouldn't need an independent inventory, but should calculate it's inventory based on the inventory of it's parts. If any 'part' for the bundled product is sold out, the bundle should be sold out as well. E.g. if there are no more goggles available, the bundle should be equally unavailable.
##### Price

Bundled product pricing should be independent of the products that compose the bundle. Bundles should be able to be priced lower that the sum of their parts.
##### Presentation

Bundled products should be able to be listed and priced as one-item in the cart with details including the products and options that are inside the bundle.
##### Products should be able to exist only as parts as well.

There is a use-case where a product exists exclusively as a part of a product-bundle as well. So ideally a hidden product could exist within a bundle while remaining hidden as an individual product.

An example could be a product launch where you can get certain limited-edition products if you purchase a "Collectors Edition" or something but the limited-edition products are not available on their own.
#### Other Ecommerce Bundle Examples

Spree Commerce does bundled products as one of it's spree-contrib add-ons. [spree-contrib/spree-product-assembly](https://github.com/spree-contrib/spree-product-assembly)

Shopify does not have bundled products built in, but a third-party has implemented it as part of a Shopify App. https://apps.shopify.com/product-bundles

I believe that there are many other use-cases for other types of ecommerce businesses as well.
#### Implementation Ideas?

Can we just add this to Product? What else would we need to do? Not sure if Schemas can self-reference like this or not. Could we just add a new `productType: 'Bundle'`

``` coffeescript
ReactionCore.Schemas.Product = new SimpleSchema
...
  products:
    type: [ReactionCore.Schemas.Product]
    optional: true
```

**Comment by pomaking** [comment]
Regarding pricing, there are use cases where users other than the shop owners create the bundles, in which case it may be impractical for bundles to be priced separately.  Or, perhaps, a discount-driven approach to pricing would be more appropriate in these circumstances, particularly if buyers have the ability to edit their bundle,

**Comment by rymorgan** [comment]
Closing this in favor of #762
