### ISSUE TITLE
Marketplace dropdown is showing in main nav on mobile

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#3681]
### Expected behavior
- When Marketplaces are not active the marketplace dropdown should not show in main mobile nav

### Actual behavior
- Marketplace dropdown is available in the main mobile nav

### Steps to reproduce the behavior
- With a fresh reaction shop that has marketplaces disabled
- In a mobile browser open the main navigation to see the marketplaces dropdown

![marketplace-mobile-nav](https://user-images.githubusercontent.com/1135948/36004253-60912dac-0cf7-11e8-81a3-d26dbb567aa5.gif)

### Versions
```shell
Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.8.0
Reaction branch: release-1.8.0
```

**Comment by aldeed** [comment]
Fixed
