### ISSUE TITLE
Toggling on Marketplace shifts the order of my dashboard icons

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#3682]
### Expected behavior
When I toggling on Marketplace, the order of my dashboard icons should remain the same. Any additional dashboard icons/items that appear due to toggling on marketplace should appear at the bottom of the list. 

### Actual behavior
Toggling on marketplace randomly shifts the order of my dashboard icons. 

### Steps to reproduce the behavior

1. Log in as marketplace owner
2. Navigate to shop and toggle on marketplace 
3. Notice the order of dashboard items have shifted 
![dashboard icons shifting](https://user-images.githubusercontent.com/22083616/36004529-05448674-0ce8-11e8-90bc-da8db181ce83.gif)

### Versions
```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.03.0-ce
```

**Comment by spencern** [comment]
Possible that this was introduced recently by a Package publication update adding or changing a sort.

@rymorgan how _should_ these be sorted?

**Comment by machikoyasuda** [comment]
This bug does not happen on 2.0 anymore. Closing.
