### ISSUE TITLE
Server crash when uploading a product JPEG on WIndows

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3683]
### Expected behavior
Should be able to load all sorts of images for products

### Actual behavior
Receive an error on the server and the browser

### Steps to reproduce the behavior
1. Login as admin
1. Upload a JPEG
1. Receive an error in the server console
1. Receive an error in the browser console

Server Error:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite (net.js:867:14)
=> Exited with code: 1
```

### Versions

Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce

**Comment by vwadher** [comment]
```

=> Meteor server restarted
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite (net.js:867:14)
=> Exited with code: 1
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
23:48:09.885Z  INFO Reaction: Load default data from /private/data/
23:48:10.014Z  INFO Reaction: JobServer started
23:48:13.228Z  WARN Reaction: Skipped loading settings from reaction.json.
23:48:15.884Z  INFO Reaction: Reaction Version: 1.7.0
23:48:15.996Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
23:48:16.003Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
23:48:16.353Z  INFO Reaction: Reaction initialization finished.
=> Meteor server restarted
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite (net.js:867:14)
=> Exited with code: 1
   Building the application

```

**Comment by vwadher** [comment]
![acclamator_class_ortho_by_unusualsuspex-d6w49uq](https://user-images.githubusercontent.com/35978747/36004613-bf653dfc-0cf0-11e8-9ceb-891a4fc92c01.jpg)

**Comment by zenweasel** [comment]
Was able to upload PNG's and smaller JPEG, but any image of a decent size caused a server crash

**Comment by spencern** [comment]
From @aaronjudd:

This issue is also repeatable by clicking the "clone" button and seems.

Additionally, because this bug report is targeting the `master` branch, it may be resolved or impacted by the work done to replace `gm`, `cfs` or any of the collection hooks.

This error that has been thrown appears to be a generic error and not specific to image uploading.

**Comment by spencern** [comment]
We should also consider "handling" these unhandled error events. @aldeed suggests that the Kadira project may have some code that could serve as a pattern for handling these types of errors.

**Comment by zenweasel** [comment]
I disagree that it's not related to uploading image as it only happened when we uploaded images over a particular size.

Also, I am able to clone products on Windows without any problems.

**Comment by vwadher** [comment]
+1 what Brent said

**Comment by spencern** [comment]
Closing as we've moved Reaction's Admin to a reactioncommerce/reaction-admin
