### ISSUE TITLE
Email Status doesn’t update until you navigate away from the email mail provider setting 

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#3685]
### Expected behavior
When I enter in my mail provider setting under the email icon of the dashboard, and the information is successfully entered, the `status` should change immediately from red to green. 

### Actual behavior
The `status` remains red until I navigate somewhere else on dashboard and then come back to the email settings or do a hard refresh and go back to the email settings - then it will display the `status` as green. 
![email status doesn t change](https://user-images.githubusercontent.com/22083616/36004698-d88bcfa6-0ce8-11e8-8171-72d5d078555c.gif)

### Steps to reproduce the behavior

1. Log in as marketplace owner
2. Navigate to email and enter edit mail provider settings 
3. Select Provider Name and enter in correct credentials for User and Password
4. Hit Save
5. See that Status icon remains red. 
6. Navigate to another item on the dashboard or do a hard refresh
7. Go back to email settings
8. See `Status` is now green. 

### Versions
```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.03.0-ce
```

**Comment by spencern** [comment]
This seems to be an issue with the status not getting updated reactively. I think this may be the same issue reported by #3701
