### ISSUE TITLE
Tag editor covers marketplace dropdown durning scroll

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#3686]
### Expected behavior
- Marketplace dropdown to either be above or behind the tag editor as it scrolls

### Actual behavior
- when scrolling through the tag editor on mobile the tag fields overflow the marketplace button

### Steps to reproduce the behavior
- You need to first create several tags/subtags to get a list of tags long enough to scroll
-  In a mobile browser log in as an Admin with edit mode on
- Open the main nav and click the edit tags button
- While the tag editor is active scroll up and down the list to see the marketplace button overflow

*chrome in iPhone7 responsive design mode*
![mobile-tag-editor](https://user-images.githubusercontent.com/1135948/36004869-7a52eeda-0cfa-11e8-89b9-b36fc23db14d.gif)

*Chrome on android device*
![screenshot_20180208-175905](https://user-images.githubusercontent.com/1135948/36004906-a8aad4aa-0cfa-11e8-8fb9-347064e7ebe7.png)

### Versions
```shell
Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.8.0
Reaction branch: release-1.8.0
```

**Comment by aldeed** [comment]
Tag editor UI is different now, so I'm closing this.
