### ISSUE TITLE
Package restrictions for the admin role

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#369]
Hi,
Is there a way to restrict a package's access to the admin? I know it seems like a strange request but in our the multi vendor hierarchy we have a super admin which has some setup packages other admins shouldn't have.
I am experimenting with the register.coffee's permission array but as I read admins have full permissions no matter this setup.

Thanks

**Comment by Gouthamve** [comment]
Also we need a way for each shop to have its own set of packages. As of now I don't see a way a shop owner could add packages for his shop. He needs to add them globally.

**Comment by aaronjudd** [comment]
If each shop needs it's own packages, we could add a shopId to the Packages collection, and just replicate as needed. 

@boboci9 the plan is to expand the implemenation of https://github.com/alanning/meteor-roles to cover your use case.  Each package has permissions so you would group permissions for the "other admin" role. Some of that is implemented, but not sure the current functionality of the roles (as we always just test admin and user).

**Comment by boboci9** [comment]
The shopId is already in the Packages collection but we would need a way to stop the recreation of the packages once we disable some of them based on the shopId.
I think the package replication issues come from the fact that I have more shops present in my system (but this I will write this more detailed for #350 ).

**Comment by aaronjudd** [comment]
@boboci9 https://github.com/reactioncommerce/reaction-core/tree/feature-roles-372 branch should now work for this.

It's a fairly complete rewrite of permissions to bring it up to speed with the current code base. 

I've got still got a some things to do before I merge it into dev, but should be fully functional for testing.

**Comment by boboci9** [comment]
Hi Aaron, I will test it and let you know what I find. Thanks.
