### ISSUE TITLE
Translation issue with brand asset

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3690]
### Expected behavior
Shows label rather than text

### Actual behavior
Shows translation key
`shopSettings.shopBrandAssetsSaved`

### Steps to reproduce the behavior
1. Upload a brand image
1. Observe the toast shows translation key

### Versions
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce

**Comment by aldeed** [comment]
Seems to be fixed
