### ISSUE TITLE
Order variant option labels overflow the edit button

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#3691]
### Expected behavior
- Variant option labels should not cover or block the edit button

### Actual behavior
- If variant option is sold out/backorder the label covers the edit button of the neighboring option

### Steps to reproduce the behavior
- As an admin create a new product and a new product variant
- select one of the variants and create an option with 0 quantity
- duplicate the new variant option to see option labels covering option edit buttons

<img width="406" alt="screen shot 2018-02-08 at 4 53 36 pm" src="https://user-images.githubusercontent.com/1135948/36005358-e7809834-0cfc-11e8-90d2-099b2765c62b.png">
<img width="518" alt="screen shot 2018-02-08 at 4 56 08 pm" src="https://user-images.githubusercontent.com/1135948/36005359-e7aca2c6-0cfc-11e8-9f99-50b175be3e82.png">

### Versions
```shell
Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.8.0
Reaction branch: release-1.8.0
```

**Comment by spencern** [comment]
@cassytaylor @rymorgan can you look at this and give us some design direction.

**Comment by aldeed** [comment]
This UI is gone in 2.0.0 so I'm closing this
