### ISSUE TITLE
Various translations not showing up and not falling back throughout order fulfilment

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3694]
### Expected behavior
- Translations should be available, or fallbacks should be available, throughout the app

### Actual behavior
- There are various locations where translations are not loading, and fallbacks are not either.

![image](https://user-images.githubusercontent.com/4482263/36005698-ac7ff978-0ced-11e8-9815-2bedc74c12d4.png)

![image](https://user-images.githubusercontent.com/4482263/36005706-ba8cd70c-0ced-11e8-8125-ec6655f37846.png)

![image](https://user-images.githubusercontent.com/4482263/36005725-d54e0214-0ced-11e8-9013-c26424675fd3.png)

![image](https://user-images.githubusercontent.com/4482263/36006355-364beb28-0cf1-11e8-8bbe-8e3015b1bcc3.png)

### Versions

```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 18.01.0-ce
```

### QA

QA by @kieckhafer + @cassytaylor

**Comment by prinzdezibel** [comment]
Moved to `ready` via https://github.com/reactioncommerce/reaction/pull/3724

**Comment by prinzdezibel** [comment]
@spencern Hi Spencer, is there a reason you put that back to "in progress" ? From my side this can be reviewed.

**Comment by spencern** [comment]
not on purpose, I think it did that automatically when I connected it to an issue. Has this been merged already?

**Comment by spencern** [comment]
@prinzdezibel is this finished? I see it was mentioned in #3724 but was not closed by that issue at the time.

**Comment by prinzdezibel** [comment]
@spencern Yes, it was merged in. Going to close this issue.
