### ISSUE TITLE
Language and currency drop down do not display scroll bar 

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#3698]
### Expected behavior
There should be a scroll bar for the language setting and currency setting in the top navigation bar if there are more items than what is displayed. 

### Actual behavior
There are no scroll bars to indicate that there are additional items below. The only time the scroll bar shows up is if I happen to scroll down, and then the scroll bar appears on the right. 
![localhost_3000](https://user-images.githubusercontent.com/22083616/36005049-9b107fee-0cea-11e8-89a6-834acdbfc0af.png)

![language scroll](https://user-images.githubusercontent.com/22083616/36007455-60f6eda4-0cf7-11e8-9f9c-cb2828e6acde.gif)

### Steps to reproduce the behavior
1. Log in as marketplace owner
2. Turn on all languages and all currencies
3. Go to Language under top navigation, see no scroll bar and not all language options are displayed
4. Go to Currency under top navigation, see no scroll bar and not all currency options are displayed

### Versions
```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.03.0-ce
```

**Comment by spencern** [comment]
@rymorgan do you want to force a scrollbar to show for these sections at all times?
Currently we're using `scroll: auto` which Windows 10 and OSX hide by default until the user has started scrolling. This is a setting that can be adjusted by each user.

We could also add an arrow at the bottom of these menus when there are additional items not shown, but will need some design direction on this.

**Comment by mikemurray** [comment]
This UI no longer exists in core Reaction. Language selection is now done in the admin interface as Reaction as of 2.0.0 is an admin only interface.
