### ISSUE TITLE
Alternative front-end frameworks for themes

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#370]
:point_up: [April 16 2015 4:29 PM](https://gitter.im/reactioncommerce/reaction?at=553045ce0e3138bb6be85a0a)
>@spencern I'm doing a port of the reaction structure to Zurb Foundation 5. Thought it would be complicated but after fighting with build-plugin for the analytics plugin, it's turned out to be pretty straightforward.
Couldn't find an issue for it, so it doesn't seem like a need for anyone else, but my company is on zf5 already, so it will be nice for us to have. Can start an issue for it if necessary.

>@aaronjudd the other thing I have been thinking about is moving the build dependency out of reaction-core so that reaction-core-theme could be installed independently and another theme could be used - I'm not sure if you have ideas or improvements to that
spencern

**Comment by spencern** [comment]
Running into some snags trying to finish up the Foundation port. Biggest issue right now is that many packages are responsible for structure and styling in addition to content. Payment packages are what is bringing this up, but I think it's going to be an issue with any non-core package.

Can you think of a better way to deal with this than rewriting each of these packages with a Foundation version?

**Comment by aaronjudd** [comment]
@spencern 
Design wise, it was a choice to either write our own ui guidelines/framework, or just use use an existing framework  (bootstrap). We'd need to code "pure" for core and packages, but you could add the framework later. My concern was that it might be really tough to test and enforce requirements for some uniformity in the UI elements in a package template. 

I'd like to think I chose Bootstrap from a practical, impartial viewpoint. I figured it was the most likely to have porting tools into other popular projects, just by the virtue of it being arguably the most widely adopted framework and that it has both Sass and Less source. (not to mention it was the meteor choice).

I have some vision of the reactionApps / registry functionality including widget UI controls (positions, placement, themes, um components) in the future using the registry as our UI own component library.
Eventually, I'd also like admin to be able to chose a theme (enable/disable package, edit properties), so need to think about how that might work as well.

 The components do need to have some default styling and structure, so I'm not sure there's anyway around including some BS3 styles when needed for compatibility.  I'd think you would only need to 
to extend with Sass to cover the BS3 elements. I'm wondering if we had Sass in the core would it be any easier? 

Maybe we could just make it easier to supply alternate registry templates for reactionApp +  themes? 

- add global Theme 
  ReactionCore.Theme = the current theme package in registry where "active:true"

- update registryHelper "reactionApps"
  * In the registryHelper for reactiveApps where theme matches current ReactionCore.Theme

  * handle if there is a compatible template
    - ie: render paymentMethod_<theme>

  * if there isn't a compatible template
     - console warn
     - ie: render bootstrap default package template,  add styles


Possibly, we'd be able to take this further and implement optimizations where we intelligently load the css as needed. I expect to see more functionality soon for lazyloading templates (and possibly other source)  See https://github.com/numtel/meteor-component-example and https://github.com/MiroHibler/meteor-preloader and the more official https://trello.com/c/24s6vyxo/55-incremental-loading and also for ui components. Might also just work to inject as needed at template render.

**Comment by spencern** [comment]
Here's a first run at a pluggable theme for Reaction Commerce that doesn't use the default bootstrap. Probably not the easiest way to start, but certainly learned a lot along the way. I'll plan to write-up some of the lessons I learned along the way, but wanted to get this out in public for now.

https://atmospherejs.com/getoutfitted/reaction-foundation-theme

It's not quite plug-and-play, but the readme should have everything that is necessary to install for now.

https://atmospherejs.com/getoutfitted/reaction-foundation-theme

I'm not sure if the long-term goal of these is for mass-use (e.g. someone who wants to use reactioncommerce.com / PaaS) or for people who want to write their own theme with scss or foundation but want a place to start.

Honestly we will probably continue to use a fork of reaction-core at least until it's easier to optimize just to avoid loading un-used templates and some of the complications that come with `Template.foo.replaces()`

**Comment by aaronjudd** [comment]
@mikemurray let's just keep this in mind while we refactor themes, less, etc.  this is all yours!

**Comment by mikemurray** [comment]
Got it. 

It seems it would help a bit if we built core-theme more like a framework instead of one off components. This could help the layout be more generic like existing frameworks and easier to extend.

**Comment by aaronjudd** [comment]
I've added issue #416  to begin the separation process for both themes and templates.  @spencern foundation-theme will probably need to be updated soon, @mikemurray has a bunch of stuff coming, and it will be interesting to see what the upgrade process will be like.  let me know if you want us to dig into it with you.

**Comment by mikemurray** [comment]
Closing this issue as we have implemented significant improvements theming and core ui frameworks.
