### ISSUE TITLE
JS NaN error when refunding individual items in order processing

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3702]
### Expected behavior
When processing an order, and trying to refund individual items, I should be able to use both the up / down quantity arrows, as well as type in a number to the input field to change the quantity.

### Actual behavior
When processing an order, and trying to refund individual items, I can use the up / down quantity arrows to change quantity, but when I try to type a number inside the input box, I get a `NaN` error.

### Steps to reproduce the behavior
- Create an order with multiple quantities of the same variant / option
- Begin to process the order
- Open the individual item processing flow by clicking the product image inside the processing dashboard
- Attempt to change the quantity by typing a number in the input box

![unknown-1](https://user-images.githubusercontent.com/4482263/36012524-8b714d38-0d13-11e8-9442-df83a90e7731.png)

### Versions

```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 18.01.0-ce
```

### QA

QA by @kieckhafer + @cassytaylor

**Comment by zenweasel** [comment]
@willopez You moved this to "In Progress" but did not assign yourself? Are you working on this?

**Comment by willopez** [comment]
@zenweasel Nat took over this one.
