### ISSUE TITLE
Order ID incorrect on order confirmation page

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3709]
### Expected behavior

Order ID on checkout confirmation page should match order ID in the confirmation email and order admin.

### Actual behavior

Order ID on checkout confirmation page **differs** from the order ID in the confirmation email and order panel.

<img width="742" alt="basic_reaction_product" src="https://user-images.githubusercontent.com/42217/36013858-8226449c-0d1b-11e8-9081-da32cb1130b2.png">

<img width="430" alt="basic_reaction_product" src="https://user-images.githubusercontent.com/42217/36013985-4b6cf03a-0d1c-11e8-95c6-787482b6069b.png">

<img width="720" alt="airmail" src="https://user-images.githubusercontent.com/42217/36013995-5b13bd34-0d1c-11e8-9a29-4e001f91a498.png">

### Steps to reproduce the behavior

1. As an admin, set up products, shipping, and payment methods.
1. As an anonymous user, add a product to cart and checkout.
1. Complete the checkout process
1. On the confirmation page, enter an email address if you are presented so you get a confirmation email.
1. Take note of the order id on the confirmation page. This id is wrong.
1. In the confirmation email, observe a different order id.
1. As an admin, view the order in the order dashboard.
1. Notice that order id matches the order id in the email. This is the correct id.

### Versions
Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce

**Comment by Akarshit** [comment]
This was happening because cartId was being displayed instead of orderId on the `orderCompleted` page.
