### ISSUE TITLE
Toast message not translated for several dashboard items

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3710]
### Expected behavior
Saving changes to the API credentials/username/password of the Shopify connector, Payment methods, and Shipping methods should result in a properly translated alert message.

### Actual behavior
The toast does display the i18n translation key instead of the translated message.

### Steps to reproduce the behavior
- log in as admin
- go to shopify setting, payment methods, or shipping methods in dashboard
- hit "Save changes" button
- see toast message in the lower left corner

![screen_shot_2018-02-09_at_10_04_09](https://user-images.githubusercontent.com/1733229/36020052-945c7bb6-0d81-11e8-803c-51f87ae0c77c.jpg)

**Comment by cindyfirestone** [comment]
This is also happening on Payment Settings and Account Settings

**Comment by zenweasel** [comment]
@cindyfirestone these should be in a separate issue rather than a comment on an existing one? Or edit this one to include it in the description?

**Comment by cindyfirestone** [comment]
@zenweasel updated the original description

**Comment by prinzdezibel** [comment]
This is most probably a duplicate of: https://github.com/reactioncommerce/reaction/issues/3694

**Comment by aldeed** [comment]
Closing as assumed fixed by https://github.com/reactioncommerce/reaction/issues/3694
