### ISSUE TITLE
Shopify-Connector: Import customers does not work as expected

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3711]
### Expected behavior
After importing customers from Shopify, I'd expect to have them shown up in the Accounts dashboard panel.

### Actual behavior
After importing customers from Shopify, they don't show up anywhere. They are inserted into database to the Accounts collection, though.

### Steps to reproduce the behavior
- Login as shop admin
- Specify Shopify credentials in dashboard settings
- Import customers from Shopify
- After successful import, navigate to the accounts settings in dashboard
- Imported customers are not shown up there.

See screenshots for details:

![localhost_3000](https://user-images.githubusercontent.com/1733229/36022416-5f9c7144-0d89-11e8-968c-30c43c59819c.jpg)
![localhost_3000 2](https://user-images.githubusercontent.com/1733229/36022418-60dff7a6-0d89-11e8-9c45-9c1b8f11c966.jpg)

**Comment by zenweasel** [comment]
@spencern Leaving out of the sprint milestone since I think this is sort of a judgement call whether this is a bug or an enhancement.

**Comment by zenweasel** [comment]
@prinzdezibel While I see that imported customers are not shown here, I also don't see customers who checkout here. Are you certain that we are supposed to see customers here?

**Comment by zenweasel** [comment]
I don't know if customers are supposed to show up here but shopify imported customers behave the same as regular customers so closing
