### ISSUE TITLE
Shopify-Connector: Typo

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3712]
### Expected behavior
`Shopify` should be written correctly

### Actual behavior
It's written "Shoify" in several language translation files

### Reproduce

See i18n keys `syncSetupFailure` and `hookSetupFailure` in /imports/plugins/included/connectors-shopify/server/i18n/*.json

![screen_shot_2018-02-09_at_11_22_39](https://user-images.githubusercontent.com/1733229/36023354-751962ae-0d8c-11e8-9e85-8f5c9c3d8cf1.jpg)

**Comment by zenweasel** [comment]
Not adding to sprint milestone since there is already a PR
