### ISSUE TITLE
Shopify Connector - Enabling sync hides hooks form.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#3716]
### Expected behavior
Setup Sync should not hide Setup Hooks
### Actual behavior
After clicking setup sync, Setup Hooks form is hidden
### Steps to reproduce the behavior
1. Add Shopify credentials in connector
1. Enable "Update Inventory when new Shopify order is placed"
1. Observe the `Setup Hooks` form is hidden

![](http://g.recordit.co/2t0UxKx8TA.gif)

**Comment by zenweasel** [comment]
Won't fix. Shopify connector no longer part of core.
