### ISSUE TITLE
Missing border in SMS notifications panel

### ISSUE THREAD

**Issue by sophiehe** [reactioncommerce/reaction#3719]
### Expected behavior
Panel should have border. 

### Actual behavior
![image](https://user-images.githubusercontent.com/20484811/36052653-6f85c992-0da3-11e8-82ce-7337b08eac74.png)

### Steps to reproduce the behavior
1. Click on SMS icon from the dashboard. Observe panel.

Versions
Node: 6.5.0
NPM: 3.10.3
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.19.0
Reaction: 1.8.0
Reaction branch: release-1.8.0

**Comment by aldeed** [comment]
SMS plugin was removed from the core product
