### ISSUE TITLE
Most recent search is saved to local storage

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3729]
### Expected behavior
Given a term that I've recently searched for using Reaction's search
1. If I log out, that search query should not be saved or persisted for other users of the same machine
2. I'm not sure what the value of persisting the most recent search term is at all, so potentially we should not persist that through a hard refresh either.

### Actual behavior
The most recent search term is stored and visible to any user of the same machine. This search term is persisted through user changes and hard refreshes.

### Steps to reproduce the behavior
1. Use the search feature, search for something like "test"
2. Hard refresh the page and click the search icon. Observer the same search term is still present in the input field.
3. Log in or log out. Observer that the search term is still present.
<img src="http://g.recordit.co/wl5qqkNXJ2.gif" />

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce
```

**Comment by aldeed** [comment]
This search UI was removed in 2.0.0
