### ISSUE TITLE
Unable to custom build image in my machine.

### ISSUE THREAD

**Issue by vineethEPM** [reactioncommerce/reaction#3734]
### Expected behavior
Building image should be successful, which is around 620MB+, however, I always get around 154MB
### Actual behavior
Building image should be successful
### Steps to reproduce the behavior
1. `reaction init easypeasy`
2. `cd easypeasy`
3. Added reaction swag shop code into imports/plugins/custom folder
4. Added payments-cod code into imports/plugins/custom folder
4. created docker machine using below command
```
docker-machine create \
  --driver digitalocean \
  --digitalocean-access-token <accesstoken> \
  --digitalocean-size 2gb \
  easypeasy
```
5. Ran below command:
`eval "$(docker-machine env easypeasy)"`

6. Tried to build custom image using below command
`docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t easypeasy .`

7. Got the below results as attached in the file below:
[Terminal Saved Output.txt](https://github.com/reactioncommerce/reaction/files/1718562/Terminal.Saved.Output.txt)

### Versions
(run `reaction -v` from your reaction directory)
1.7.0 onwards

I've asked around in Gitter, but could not find a solution. Code changes works absolutely fine in my local machine.
Would appreciate any help in this, as this is blocking me go live with the code.

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).
