### ISSUE TITLE
New uncommited README files in repo

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3743]
There are two uncommitted / untracked README files that show up in git whenever creating a new branch:

`public/plugins/README.md`
`private/plugins/README.md`

We should either commit / track
 these permanently, or not.

Related to #3335 

### Steps to Reproduce
1. `reaction init -b release-1.8.0 reaction-fresh`
1. `cd release-fresh`
1. `reaction`
1. Quit
1. Observe that there are two new README files that git wants us to commit or remove

### Versions
```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: fix-3668-kieckhafer-cartAlignmentIssues
Docker: 18.01.0-ce
```

**Comment by prinzdezibel** [comment]
@kieckhafer Can't reproduce this. Can you tell me the exact steps you've taken?

**Comment by zenweasel** [comment]
What I am seeing (after following the instructions above) is:
```
On branch release-1.8.0
Your branch is up to date with 'origin/release-1.8.0'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    private/plugins/README.md
	deleted:    public/plugins/README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

These are files being DELETED, not being added

**Comment by prinzdezibel** [comment]
Thank you! The asset provisionsing step should not delete them. I'll file a PR to reaction-cli.
