### ISSUE TITLE
Placeholder image doesn't show up in PDP when not in edit mode

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3762]
### Expected behavior
Placeholder image should show up everywhere

### Actual behavior
Doesn't show up on PDP when not in edit mode (or not logged in)

### Steps to reproduce the behavior
1. Go to PDP for the "Basic Reaction Product"
1. Observe that the placeholder image is not visible

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Docker: 17.12.0-ce
```

**Comment by Akarshit** [comment]
Closed via #3812
