### ISSUE TITLE
Artifact in order summary

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3763]
### Expected behavior
Should just display date without additional pipe character

### Actual behavior

![2018-02-16_12-59-54](https://user-images.githubusercontent.com/72819/36294088-503f4aec-1319-11e8-9d12-46710509138b.png)

Using a single pipe rather than a double-pipe for OR
https://github.com/reactioncommerce/reaction/blob/4fae50ddac1bc69474b90e98b9564f68a83f785a/imports/plugins/core/orders/client/components/orderSummary.js#L101

### Steps to reproduce the behavior
1. Place an order
1. Go to the admin
1. Observe the extra character

### Versions
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Docker: 17.12.0-ce

**Comment by zenweasel** [comment]
@Akarshit This was fixed? The PR was closed in favor of another?

**Comment by Akarshit** [comment]
Should be fixed by #3733
