### ISSUE TITLE
Items in Cart drawer go off screen

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3764]
### Expected behavior
You should be able to see items in the "Cart Drawer" at all time

### Actual behavior
When you have more than a few items in the cart, items go offscreen
![2018-02-16_13-06-44](https://user-images.githubusercontent.com/72819/36294263-7f0db0f6-131a-11e8-8410-8392619db43c.png)

Items sometimes go off to the right and you can't get to them at all (no scroll bar)
![2018-02-16_13-13-46](https://user-images.githubusercontent.com/72819/36294379-522be430-131b-11e8-9714-d8f8ecf7344a.png)

### Steps to reproduce the behavior
1. Add a few different items to the cart

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Docker: 17.12.0-ce
```

**Comment by aldeed** [comment]
This UI was removed in 2.0.0
