### ISSUE TITLE
Receive "No shipping methods defined" when checking out as guest

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3766]
### Expected behavior
Shipping methods should not show until you've entered an address

### Actual behavior
"No shipping methods are configured" displays even though, shipping methods are in fact configured. 

### Steps to reproduce the behavior
1. Visit the site in incognito mode
1. Add something to cart
1. Click on "Continue as Guest"
1. Observe that the "No shipping methods are configured. Please contact the store administrator." message displays
1. Once you enter your address the shipping methods display as expected

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
I don't know if this is a regression yet but will update shortly

**Comment by zenweasel** [comment]
Doesn't happen on `master`.

**Comment by prinzdezibel** [comment]
Has probably to do with this: https://github.com/reactioncommerce/reaction/pull/3640/files

**Comment by prinzdezibel** [comment]
@Akarshit Yup, I see you found it out already. Thank you!

**Comment by Akarshit** [comment]
@prinzdezibel Yes #3628 is still fixed with my changes.

**Comment by spencern** [comment]
@Akarshit @zenweasel This issue is also popping up when there is a "bad" address and no shipping results can be found for the address in question. 

http://recordit.co/yZQqnEtbH7

**Comment by Akarshit** [comment]
@spencern What should be displayed if no shipping results are found because of bad address?
Also I think this might be out of the scope of the issue as this issue is about the "Shipping method" stage being shown before the user enters the address. What do you think?

**Comment by Akarshit** [comment]
Closing this, please open a new issue if you think something needs to be added.
