### ISSUE TITLE
Add you-dont-need-lodash plugin and resolve errors

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3769]
**Summary**
Install the `eslint-plugin-you-dont-need-lodash-underscore` and resolve any problems that it finds.
We have some code that's still reliant on lodash/underscore methods when there is a prototype method that would do. This lint plugin identifies the spots where we're unnecessarily using lodash and suggests a native solution.

1.  Run 
```
npm install --save-dev eslint-plugin-you-dont-need-lodash-underscore
```
2. add a line `"plugin:you-dont-need-lodash-underscore/compatible"` to the `.eslintrc` file `extends` array.

3. Run `npm run lint` and resolve any issues that are identified.

**Comment by kieckhafer** [comment]
@spencern do we still want to add this for `v3.0`? I've added it locally to try it out, seems to work as expected, we currently have 9 lint issues thrown by this plugin, which would be do-able to fix before the release.
