### ISSUE TITLE
Use reaction behind proxy

### ISSUE THREAD

**Issue by dr-dimitru** [reactioncommerce/reaction#377]
Any idea how to keep DDP (without fallback to XHR) behind proxy like HAProxy, nginx, etc..?
On our end it falls back to XHR.

**Comment by aaronjudd** [comment]
http://meteorpedia.com/read/Main_Page

I think the relevant nginx entry is 

```
x_http_proxy_module.html#proxy_http_version
    # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
```

I'd love to update the docs with some details so let me know what you discover.

**Comment by dr-dimitru** [comment]
@aaronjudd still no luck here, meteor behind proxy falls to sock.js and long-polling

**Comment by kefirchik** [comment]
Hi! I found this in [Meteor Wiki](https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy)

**Comment by dr-dimitru** [comment]
@kefirchik unfortunately it is for dev stage

**Comment by dr-dimitru** [comment]
Hi all, issue was fixed in new nginx update (released 2-3 weeks ago)
