### ISSUE TITLE
Log IP address for each order

### ISSUE THREAD

**Issue by eziel** [reactioncommerce/reaction#3777]
Having the IP address from the computer creating the order could be very helpful for fraud detection and analysis. please add a field to the order collection with the users IP address.

Thank you.

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #23](https://github.com/reactioncommerce/reaction-feature-requests/issues/23) via [**ZenHub**](https://www.zenhub.com/)
