### ISSUE TITLE
Order Components not registered

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#3785]
### Expected Behaviors
All components that are part of the public API should be registered

### Actual Behavior
These components are not registered
1) completedOrder.js in directory/imports/plugins/core/checkout/client/components

2) ordersList.js in directory/imports/plugins/core/accounts/client/components
**[Update]** orderList is no longer directly called but part of `Component`

**Comment by prinzdezibel** [comment]
re 1) It's registered in as "CompletedOrder" in containers/comletedOrderContainer.js. This is done sometimes, if there's no usage for the unwrapped, bare-bone component. 

re 2) Dito. It's registered in as "OrdersList" in containers/usersOrdersListContainer.js.

**Comment by prinzdezibel** [comment]
@zenweasel From my understanding this isn't necessarily a bug. But I admin, it's counter-intuitive. What do you propose?

**Comment by willmoss1000** [comment]
I see, thanks for this. It's not a bug. Seems like this is how things are done with containers throughout -not sure why though? It means that whenever you want to replace/extend a component you have to add a file to do it with the container and import the HOCs too. But yep apologies for this please close it.

**Comment by willmoss1000** [comment]
Hi Both,

1. Replacing OrdersList will be possible after: https://github.com/reactioncommerce/reaction/pull/3848
- Issue was that it was called directly, so replacing the component had no effect

2. It is not possible to replace CompletedOrder
- I am experiencing the same issue as 1), but CompletedOrder is called directly in a lot more places.
- Is it OK to open this up again, such that someone from the team could take a look and make sure that it is possible to replace this component?

**Comment by zenweasel** [comment]
@willmoss1000 I am going to reopen this but I think we also would accept a PR to change the places where CompletedOrder is directly called

**Comment by willmoss1000** [comment]
@zenweasel sure. I'll have another go at this at some point this week. Assign it to me if you like - I don't see anyone else needing this urgently.

**Comment by willmoss1000** [comment]
I no longer require this and I don't see it being useful to many other users.
