### ISSUE TITLE
Box visible on top left in mobile navigation

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#3798]
### Expected behavior
No extra `div`

### Actual behavior
There is some box display near the top in mobile view when the user is not signed in.
<img width="557" alt="screen shot 2018-02-21 at 1 04 07 am" src="https://user-images.githubusercontent.com/7762605/36464355-74bb1c36-16f5-11e8-9d28-7cbde8dd3a98.png">

### Steps to reproduce the behavior
1. Switch to mobile view
2. Make sure you are logged out. See the weird box on top left.

### Versions
`release-1.8.0`

**Comment by zenweasel** [comment]
@Akarshit Can you point out to me exactly what you are seeing that shouldn't be there? Need a little more specifics than "see the weird box". 😄 An image with a box outlining it would be best.

**Comment by Akarshit** [comment]
@zenweasel Updated the screenshot.

**Comment by aldeed** [comment]
This UI is gone in 2.0.0
