### ISSUE TITLE
Checkout does not show shipping options?

### ISSUE THREAD

**Issue by bbogeul** [reactioncommerce/reaction#380]
Hi there, I am new to reaction and I am loving it. Made a few themes and templates and I am interested in contributing. Currently I have one running locally, and the shipping section of the checkout template works great. but once deployed, it doesn't show. I attached an image for reference. I have checked out as developer and master prior to deploy but no change. 
![selection_001](https://cloud.githubusercontent.com/assets/12481163/7741878/08439526-ff3b-11e4-9e79-d3dea3331c29.png)

**Comment by Gouthamve** [comment]
@bbogeul Good to know that you like Reaction! But could you put your templates in a gist or a repo? That would help us better solve the issue.

**Comment by bbogeul** [comment]
Thanks for the comment. I will get to that soon. The thing is, I just installed a plain reaction locally and deployed it right away to see if the problem persisted (no change to anything) and still get this error at the checkout. I upload it using meteor deploy

**Comment by Gouthamve** [comment]
Well, I couldn't even login as admin in your reaction. And for dev, it is best to clone the following repos into ```/packages``` (You have to create the folder).
```
https://github.com/reactioncommerce/reaction-core
https://github.com/reactioncommerce/reaction-core-theme
```

**Comment by aaronjudd** [comment]
Closing (as I know this works.. with the current development branch).
