### ISSUE TITLE
Cannot create password when invited to create account

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3805]
**Summary**
When being invited to create an account as a shop manager or a merchant shop owner, the password overlay spinner is never turned off.
![image](https://user-images.githubusercontent.com/1203639/36462722-4b07137c-1682-11e8-80c3-2ef5c30ab231.png)

It appears that the lifecycle method `componentWillReceiveProps` is never fired for this password overlay.

https://github.com/reactioncommerce/reaction/blob/release-1.8.0/imports/plugins/core/accounts/client/components/updatePasswordOverlay.js#L33

As seen in the gif here: http://g.recordit.co/F9BwrqGl2g.gif, if you manually set the state for "showSpinner" to false, you are able to enter your password and complete creating your account.

**Steps to reproduce**
1. Use branch `release-1.8.0`
2. invite a user to become a shop manager from the accounts screen
3. Follow that link in a new session (incognito or similar)
4. Observer spinner
5. In react devtools find the `Reaction(UpdatePasswordOverlay) component and set `showSpinner` to false
6. Input your password and see that your account is created

**Comment by zenweasel** [comment]
Closed via #3806
