### ISSUE TITLE
Removing database usage

### ISSUE THREAD

**Issue by mpaezmolina** [reactioncommerce/reaction#381]
Hi, this framework is awesome!

I wanted to know your comments on the idea of what we need to do. We have all the products, variants, carts, orders and so, being handle by a third party API. I was thinking that it would be nice to integrate Reaction with the API instead of its own Mongo database.
Do you see this possible, or you would not even recommend it? 

Also, I did not get the admin user on the first run on the console. Is there another way to create one?
Thanks!

**Comment by spencern** [comment]
If you can't remember your admin user info from the first run, you can run `meteor reset` and then start meteor again to generate a new one. This will reset your app to it's default state, but if you are just developing or testing that should be fine.

**Comment by markchipman** [comment]
@mpaezmolina ... with all due respect, this would be a terrible idea.  DDP messaging is integral with Mongo's trigger messaging events.  Taking the 'cool pieces' of Reaction Commerce like its smart drag and drop and tacking on a backend API to another system or database defeats the elegantness of meteor and Reaction Commerce upon which it is based.

**Comment by aaronjudd** [comment]
@mpaezmolina Thanks.  re @markchipman comments, that said..  we've had some "blue sky" discussions, where we've talked about what it would be like to build a real time integration to shopify or magento for instance. Might be useful for migrations, but not something I suggest as a long term solution - but I guess the point is that there is certainly the ability to build just about any kind of integration you want.  I suppose you could even map new collections on a remote db if you wanted.  Up to you do decide the wisdom of the approach though.
