### ISSUE TITLE
Unable to change localization settings

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#3811]
### Expected behavior
I should be able change my base currency. 

### Actual behavior
I am unable to change my base currency. 

### Steps to reproduce the behavior
Navigate to localization
Make sure you have multiple currencies enabled 
Attempt to change your base currency see that you can't. 

See here: 
![ufydbpcmsx](https://user-images.githubusercontent.com/20409254/36494787-fe87ad8e-16e7-11e8-8ccd-15716c9309f5.gif)

### Note
It works on Master 

### Versions
Node: 6.11.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0

For enhancements or other issues, please describe, in as much detail as
possible, how the app should be changed, and how this would benefit other users and developers.

**Comment by zenweasel** [comment]
Confirmed that this does not happen on `master`

**Comment by mikemurray** [comment]
This happens for all of those dropdowns. I cannot change any of them.

**Comment by zenweasel** [comment]
@Akarshit I am guessing that this is related to the way we changed how preferences are stored so I am assigning to you

**Comment by Akarshit** [comment]
Working on this.

**Comment by zenweasel** [comment]
@Akarshit Already fixed
