### ISSUE TITLE
Prices should not be converted in admin view

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3821]
### Expected behavior
The shop base currency should be honored for all prices shown in admin view.

### Actual behavior
If the shop's base currency is set to EUR and the admin does add a new product, the product's price get converted immediately from USD->EUR, because shop assumes that the entered value is USD.

EDIT: Strangely, the above stated does not happen reproducible

EDIT 2: Is happens reliably, if the currency selector in the nav bar doesn't match the shop base currency.

But the following seems to happen always:
Additionally it's not possible to enter the in the shop base locale, e.g. with a comma as separator for EUR currency.

### Steps to reproduce the behavior
- As an admin, set the shop base currency to EUR. And for good measure, also set the currency selector in the nav bar to EUR.
- Add a product
- Input a value
- The value gets converted as soon as the field blurs.

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.03.1-ce

### Analysis
It could have to do with this PR: https://github.com/reactioncommerce/reaction/commit/a9937023c911334d7cae5d6a84252666bd802b99

![implicit_conversion](https://user-images.githubusercontent.com/1733229/36535174-1c9b1aa4-17c9-11e8-9b0b-73beb3dc62d6.gif)

**Comment by prinzdezibel** [comment]
Entering formatted values in shop's base currency is not possible:
![locale_formatting](https://user-images.githubusercontent.com/1733229/36535644-a74c25a2-17ca-11e8-8b72-5461be17f7bd.gif)

**Comment by Akarshit** [comment]
Will fix this on monday.

**Comment by Akarshit** [comment]
The current idea is to use the `NumericInput` for the "currencyInput" component. Working on it, will be fixed today.

**Comment by Akarshit** [comment]
I have tested #3893 and once it gets merged we can reuse it's component(with a little modification) to fix the issue.

**Comment by Akarshit** [comment]
This will be done today.
