### ISSUE TITLE
Basic CMS Pages management

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#383]
I think there should be an ability to add and delete pages directly from the dashboard.

Like there will be a CMS package where we can control the pages shown in the footer through this package, And all the pages can be edited via https://github.com/ongoworks/meteor-content-areas and also there will be another field on the CMS package dashboard that will have settings for the routes and if this page should be available in the footer.

This will help people add new pages easily. 

I will first close #216 by implementing the content-areas and then proceed to creating routes via db and then the dashboard.

**Comment by kefirchik** [comment]
Is there any news? :smile: 
We actually trying to figure out how to make tags to look like a classic categories (a simple cms page with meta, content, seo, etc.).

Simple pages are done here [dukeondope/reaction-static-pages/](https://github.com/dukeondope/reaction-static-pages/)

**Comment by aaronjudd** [comment]
@kefirchik yes - we're planning to start next week on core-cms functionality. really!

**Comment by kefirchik** [comment]
Oh so glad to hear it :) actually we achieve some results with our extensions. I'll show it tomorrow

**Comment by HadenHiles** [comment]
Has there been any progress on this? The last comment was "a year ago" and this is a feature I need for my current project. The [reaction-flat-pages](https://atmospherejs.com/ramusus/reaction-flat-pages) package from atmosphere doesn't work with the latest Meteor/ReactionCommerce update that utilizes ES6 imports.

If anyone could point me in the right direction I would greatly appreciate it :)

**Comment by aaronjudd** [comment]
@HadenHiles CMS features are still on the roadmap(0.20), and we're still actively planning to build that functionality in the core. I'm not sure if that package is going to get ported over to the modules as is, but it shouldn't be that tough.

**Comment by terrelltechsup** [comment]
I do not know how far this has progressed, but I have been testing with the [Yootheme Pro static page and template builder](http://yootheme.com/pro/) and it may be something worth taking some queues from with regards to providing the non-dev end user the ability to add static content, control header/footer content, and style their templates visually.

**Comment by josx** [comment]
@aaronjudd  I will need this feature in the near future. 
How can we help to build it up?
Are you thinking to make a custom cms over reaction, or are going to integrate another cms?
what is you plan on this?

**Comment by zenweasel** [comment]
Closing to Review roadmap

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #15](https://github.com/reactioncommerce/reaction-feature-requests/issues/15) via [**ZenHub**](https://www.zenhub.com/)
