### ISSUE TITLE
Validate character validity and position in tags

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3831]
## Prerequisites
Issue reported in [Community Chat](https://gitter.im/reactioncommerce/reaction?at=5a918a798f1c77ef3a4d328d)

## Issue Description
When some characters are used when adding a tag, an exception is thrown, an inappropriate client error is displayed.  `Tag already exists, or is empty.`,  neither of which is true.

It may be that that the characters are not valid for URL character / position.

Witness that there is not an error when you use `{A` but an error is thrown when using a single character `{`. 

## Steps to Reproduce

1. Login in as admin
2. Using tag nav edit mode, attempt to create a tag starting with the `{` or the `}` character. 
3. Witness server console error
```
Exception while invoking method 'shop/updateHeaderTags' Error: Slug is required
    at getErrorObject (packages/aldeed_collection2-core.js:480:15)
    at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
    at ns.Collection.Mongo.Collection.(anonymous function) (packages/aldeed_collection2-core.js:214:25)
```
4. Witness client error `Tag already exists, or is empty.`

Nice that we caught an error, but the message isn't really correct in this case.

## Possible Solution
A suggested solution would be to validated tags as [valid allowed URL characters](http://www.ietf.org/rfc/rfc3986.txt) AND character position, and to catch and throw an appropriate informative client error.  `Cannot use xxx characters in tag`.

It may be that slugify should be able to handle converting non legal characters and position, so that be may something to look at.

### Versions
```
Node: 8.9.3
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.1.1
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by mori5ive** [comment]
my slug contain valid URL characters with Persian language alphabetic.. In version 1.7, this section worked properly

**Comment by mori5ive** [comment]
i not think that related to translation
i think slug validate regex incorrect

**Comment by Akarshit** [comment]
@zenweasel
This issue is happening because `transliteration` module is only loaded when the shop language is a non-latin language.
So if I set the language to arabic, I can name my tags in arabic(or anything) and it would work. 
But if the shop's language is set to English, I can only use english alphabets(and some symbols.) in the tags name.

The loading of `transliteration` on a "as need basis" was done to enhance the performance, so I don't think we should go back to remove it. But I don't see a way other than that.

**Comment by Akarshit** [comment]
@mori5ive @zzh1234567 
You can get the tags working in other languages by changing your shop's language(to the language you want.)
You can find the setting to change the language in the `Localization and i18n` menu of the Action bar.
