### ISSUE TITLE
Issues with email status notification on initial startup with no reaction.json, on first-time credential save

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3832]
## Prerequisites

Tested on 1.8.1 release

Some of the issues with the status notification have been partially resolved by PR https://github.com/reactioncommerce/reaction/pull/3781 when you're updated previously saved credentials.

## Issue Description

Email status notification doesn't turn green if you initialize a new reaction app with no `reaction.json` and try to set your email settings for the first time.

Every time after the first is fine.

## Steps to Reproduce

1. reaction init
1. Do not copy any settings into this new reaction, we want it clean of all pre-config
1. run `reaction`
1. after startup, sign in as the admin account
1. open email settings
1. enter known, valid email settings and save
1. see that the red circle didn't turn green
1. close and re-open email settings, and see the green circle next to status (if your settings were correct)
1. enter incorrect credentials, see status turn red (don't close the panel)
1. re-enter the proper credentials, see the status turn green

## Possible Solution

There may be some issues with the `componentWillReceiveProps` in https://github.com/reactioncommerce/reaction/blob/0f16a2c46ff0d89f5b91592beb7925b530d0f4ce/imports/plugins/core/email/client/containers/emailConfig.js#L39-L48

Or, perhaps in the Meteor call for check status, which could end up being on the server.

https://github.com/reactioncommerce/reaction/blob/0f16a2c46ff0d89f5b91592beb7925b530d0f4ce/imports/plugins/core/email/client/containers/emailConfig.js#L56-L72

### Versions

Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.1
Reaction branch: release-1.8.1
Docker: 17.12.0-ce

**Comment by nnnnat** [comment]
@zenweasel I haven't started on this yet feel free to have someone else take this.

**Comment by aldeed** [comment]
No longer relevant
