### ISSUE TITLE
Rebuild after file change of App takes 3times longer than actual build

### ISSUE THREAD

**Issue by nacron** [reactioncommerce/reaction#3834]
## Issue Description
Hello, I have a build performance issue. I am trying to create a custom theme/plugin. I am running the latest version and the rebuild when saving a file takes 4 times longer than the initial build. When I run METEOR_DEBUG_BUILD=1 meteor it shows that it takes 5 minutes alone to build local packages:
START 2 building local packages
DONE 2 building local packages took 313942

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Start reaction
2. Change a file
3. Wait for 7 minutes

### Versions
OSX: 10.13.3

Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.1
Reaction branch: master
Docker: 17.12.0-ce

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction itself but your local installation.

We would be glad to answer your questions, provide you more help via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com). Closing this issue.
