### ISSUE TITLE
Removing default product image doesn't re-prioritize additional images for that variant

### ISSUE THREAD

**Issue by i-a-n** [reactioncommerce/reaction#385]
Steps to reproduce:

1) Add a product, a variant, and multiple images.
2) Remove primary image for that variant.
3) Check cart "product list" view. 

While the "cart" and "product detail" views show the (formerly) secondary image as the new primary image, the "product list" view doesn't. It must not be re-prioritizing properly after a delete event. Hopefully an easy fix.

**Comment by aaronjudd** [comment]
Thanks for the report,  this should be an easy fix. It should be reactive like the rest, but I do remember doing something odd in the grid.  We're getting ready for a UI review, polishing, we can take a look as we go through the UI.
