### ISSUE TITLE
Can't publish changed product data more than once

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3851]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
It's not possible to publish changed product data after the first (successful) publishing process.
Changing fields a second time doesn't activate the "Publish" button anymore. It's not possible to publish again.

## Steps to Reproduce
1. As an admin, create a new product and publish it
2. As an admin, navigate to PDP in edit mode and change any field.
3. The Publish button will not become active again

### Observations
Works in v1.7.0, but not in v1.8.1

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.8.1
Reaction branch: master
Docker: 17.03.1-ce

**Comment by zenweasel** [comment]
Bumping this up to critical since publishing products is sort of a big deal

**Comment by zenweasel** [comment]
Closed via #3949
