### ISSUE TITLE
Admin should get a warning, if Discounts payment provider is used stand-alone

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3852]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The Discounts payment provider plugin is intended to be used in combination with another payment provider. Checkout will not be possible with just this provider enabled. This is by-design, but the admin should get informed about that.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. As an admin, add the Discounts payment method (and only that). Also add a shipping method.
2. As a user, create an order and checkout
3. Order can't be completed. In checkout step "payment" you'll hit a dead end.

## Possible Solution
Warn the admin about the consequences in case he doesn't check another payment provider.

**Comment by zenweasel** [comment]
There already is a check that if you are an admin it will tell you you need to configure a payment provider and open the correct admin panel. That check just needs to ignore discount payment types.

**Comment by zenweasel** [comment]
Classifying as a bug because the original check should have not included discount payment types, removing UIX since the UIX already exists if the check is done correctly.

**Comment by aldeed** [comment]
No longer relevant as of 2.0
