### ISSUE TITLE
Call to createHandle causes a maximum stack size error

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#3862]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues]

## Issue Description
When updating a product's handle(slug) a maximum stack size error is generated on the server.

`Exception while invoking method 'products/updateProductField' RangeError: Maximum call stack size exceeded
    at createHandle (server/methods/catalog.js:123:6)
    at createHandle (server/methods/catalog.js:158:14)
    at createHandle (server/methods/catalog.js:158:14)`

### Function call site
https://github.com/reactioncommerce/reaction/blob/3634-willopez-remove-product-collection-hooks/server/methods/catalog.js#L931

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Login as admin
2. double click on a product 
3. change the permalink and press the `Enter` key to save
4. Observe terminal error output, and notification on the client showing "Server Error"

## Possible Solution
Rewrite the `createHandle` function to prevent error, it's being called recursively which causes the error. 

## Note to Developer
To work on this issue, rebase from this branch: `3634-willopez-remove-product-collection-hooks`
 
### Versions
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.0
Reaction branch: 3634-willopez-remove-product-collection-hooks
Docker: 17.12.0-ce

**Comment by kieckhafer** [comment]
This seems to be resolved in #3825 

Leaving it open until that is merged.

**Comment by kieckhafer** [comment]
I am (still) unable to reproduce.

**Comment by spencern** [comment]
@willopez seems like we need more specific reproduction steps, either due to the state of the app when you're seeing this issue, or we need to consider this resolved.

**Comment by willopez** [comment]
@spencern @kieckhafer I am not able to reproduce it consistently. Closing this issue.
