### ISSUE TITLE
PDP Image gallery does not handle portrait sized images well

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3883]
## Prerequisites
*  [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
The PDP image gallery does not handle images that are taller than they are wide appropriately. As a non-admin, the images can block off other elements of the page.
Admin:
<img src="http://g.recordit.co/r4ZkRQrdL0.gif">

Non-admin:
<img src="http://g.recordit.co/j3qMwZduqn.gif">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. As an admin, visit the PDP for the default product
2. Upload an image that is taller than it is wide by a significant margin (4:3 or greater) 
3. Upload a few other images of various size.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.2
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
@spencern I'm having a hard time wrapping my head around this as a bug. Should we be getting a design/acceptance criteria from Design? Not sure what "done" looks like in terms of fixing this.

**Comment by spencern** [comment]
@zenweasel that's a good question. I don't remember this happening before, but it's probably a design / @rymorgan issue before we fix it.

**Comment by rymorgan** [comment]
I think we go with the simple solution that most marketplaces use. We proportionally constrain the image and center it w/in the PDP big image square target area. The pink outline represents the image square target area. 

![vertical](https://user-images.githubusercontent.com/20409254/37312946-3e3cc2b2-260a-11e8-97ba-e3962133b168.png)
![horizontal](https://user-images.githubusercontent.com/20409254/37312948-3e63d4ec-260a-11e8-9dff-400193c4e089.png)

**Comment by prinzdezibel** [comment]
Closed via https://github.com/reactioncommerce/reaction/pull/3993.
