### ISSUE TITLE
Open marketplace card automatically on enabling marketplace.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#3886]
## Issue Description
When enabling marketplace, the marketplace card doesn't open automatically(it opens when you click on it).
We should be opening the card when a user enables MarketPlace because the next action is most prob. be inviting a user.

## Steps to Reproduce
1. Login as owner
2. Enable marketplace
3. Observe that the card is still closed.

Already discussed with @rymorgan and he agrees.

**Comment by mikemurray** [comment]
This panel needs to be converted to React.

**Comment by aldeed** [comment]
This card/plugin has been removed
