### ISSUE TITLE
Customization and staying up to date with the master

### ISSUE THREAD

**Issue by mschipperheyn** [reactioncommerce/reaction#3888]
I'm just curious how to create customizations while staying up to date with the master.

You can create a plugin directory and merge the main line in, but it would be nice to be able to keep the custom code separate from the reaction core. Any suggestions on this?

**Comment by prinzdezibel** [comment]
Hi, you can symlink any custom plugins into  /imports/plugins/custom/*. That way your own code can live in a different place than the main line. Also these directories should be .gitignore(d), so it doesn't hurt to have them checked out in /imports/plugins/custom/ directly. Either way, you should always be able to merge in changes from master without affecting your own code.

**Comment by mschipperheyn** [comment]
Thanks!
