### ISSUE TITLE
Slow account authentication (login or creating user)

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#389]
is extremely sloooooooow. It takes between 30 and 60 seconds on a regular basis. That's for development and production mode.

Also it would be nice to have a spinner when pressing the button to let the user know the browser does something.

**Comment by Gouthamve** [comment]
This is something that happens to me from time to time. I didn't know it finishes, I just restart the server.

Usually it takes < 1sec for login. But this delay happens from time-to-time. And yes, a spinner for things that take would make sense.

**Comment by aaronjudd** [comment]
yeah, I see this randomly, not sure if it's the first time or what.   the entire accounts-ui is mostly the default meteor one with some minor tweaks.   We really need to rip it out I think and add our own.  I'm not sure what it's doing, but perhaps we can hook up kadira and debug the performance that way.  suspect either a pub/sub problem or a remote call that is timing out.

**Comment by aaronjudd** [comment]
I think this is just the first time - I'm wondering if it has something to do with waiting for velocity tests to finish.

**Comment by spencern** [comment]
I'm seeing this as well on a fresh upgrade after having performed a `meteor reset` and `bin/reset`

Additionally mine eventually logs in but my Velocity tests still haven't finished running

**Comment by Gouthamve** [comment]
I don't think this has anything to do with velocity.

I removed both ```sanjo:jasmine``` and ```velocity:html-reporter``` and this still happens.

**Comment by aaronjudd** [comment]
@mikemurray while you are looking at the accounts, can you keep an eye out for this little beastie?  I thought it was gone, but then I thought I saw it again...  in other words - I have no way to replicate but I'm pretty sure it's still an issue.

**Comment by prinzdezibel** [comment]
Still a problem with 0.6.3 here. Occasionally it takes ages to log in.

**Comment by spencern** [comment]
Saw it here too on 0.6.3 yesterday as well. Not every time, but occasionally.

**Comment by aaronjudd** [comment]
yeah, I suspect there's a blocking remote call somewhere, and it just depends on the remote being available.  I have my suspicions of the culprits.

**Comment by prinzdezibel** [comment]
It seems it's the utilities:avatar package. I removed it and I can't reproduce the problem anymore. Before that I've experienced prolonged times for every other login.

**Comment by prinzdezibel** [comment]
Need to revoke what I said above. It's still there :(

**Comment by aaronjudd** [comment]
been there, done that. lol - I suspected the gravatar lookups

**Comment by queso** [comment]
@prinzdezibel or @Gouthamve can you think of any steps to trigger the slowness? I just installed kadira and kadira debug and played around for 30 minutes or so and I can reproduce it.

**Comment by prinzdezibel** [comment]
@queso TYPO? You write you *can* reproduce it. Or do you actually mean *can not* ??

**Comment by aaronjudd** [comment]
yeah - I think he meant "can't"   ;-)  - but we know this ghost is in there!

**Comment by queso** [comment]
Sorry, yeah, meant can't. @prinzdezibel what OS are you running when it has happened for you?

**Comment by prinzdezibel** [comment]
@queso I'm running Chrome on top of OSX.

**Comment by queso** [comment]
perfect, thx. I've installed kadira and kadira debug to check all of this out as I work on other tickets. Hopefully I can reproduce it somehow :)

**Comment by prinzdezibel** [comment]
I'm experiencing the same very long delay (up to two minutes) from time to time unrelated to login procedure. It happens between page transitions and the spinner is loading and loading. Could that be related to some publishing action? Strangely it seems to occur more often on my iPad than with desktop browser. (I haven't ruled out connectivity issues, even though I'm running the application from my local network).
