### ISSUE TITLE
Unable to test sandbox paypal payment

### ISSUE THREAD

**Issue by rohit-wadhwa** [reactioncommerce/reaction#390]
Nothing happen when try to do payment on paypal sandbox account on live demo shop : 
https://2tod8zep.reactioncommerce.com/

I have Configure the sandbox configuration properly but nothing happen when click on "Complete your order" button always showing "Resubmit payment". Also same not working on local site.

**Comment by prinzdezibel** [comment]
Payflow Pro OR Express Checkout?

I've had the same problems yesterday. Do you see something in the log files? 

In my case it was a Test-Credit-Number that does not work well. And it seems there are a lot of them not suitable for testing payments. Some don't work  at all, others only in 1 of 10 runs. Try several different numbers.

But even if they're failing there should be an error message. I also didn't get this, only the mentioned "resubmit payment". That is not ideal. 

Also: Please be sure on your local branch to pull latest development and check out appropriate packages (paypal, reaction-core, ..) to the /packages folder as well (development branch) to use latest versions across the dependent packages.

**Comment by rohit-wadhwa** [comment]
Tried both : f
Payflow Pro : Showing "Resubmit payment"
Express Checkout? :  Not redirect to paypal site , only showing /# on same page.

No issue with Test-Credit-Number because, i am using paypal suggested sandbox buyer account credit-card number which have Balance: 9999.00 USD. 

Not see any ajax failing error and even their is not any paypal site ajax call.

You can check this here: https://2tod8zep.reactioncommerce.com/checkout

**Comment by rohit-wadhwa** [comment]
Also "Braintree Payment" TestGateway is also not working showing same issue "Resubmit payment' again and again.

Any one have any solution for this problem ? Maybe , i am doing something wrong.

**Comment by rohit-wadhwa** [comment]
Also "Braintree Payment" TestGateway is also not working showing same issue "Resubmit payment' again and again.

Any one have any solution for this problem ? Maybe , i am doing something wrong.

**Comment by aaronjudd** [comment]
These are working on the 0.6.0 release, which we'll publish to the "reactioncommerce" site in a few days.

**Comment by aaronjudd** [comment]
@lovetostrike in reference to gitter chat: 
this apparently was a leftover from 0.6.0, but we're working our way through writing tests cases for checkout (0.7.0 release), and checkout itself is going through a big revamp. currently, almost there but haven't got to the payment modules yet. It sounds like that issue though - I don't remember why I reopened the issue  ?! -but I'll take a look soon. If you can sleuth some more that’s always helpful as well

**Comment by lovetostrike** [comment]
@aaronjudd I will see what I can do about it. Might just need to show some error message if I'm providing wrong creds.

**Comment by zenweasel** [comment]
Putting an order through Paypal Sandbox (both Pro and Express) definitely works in the current version.

I am pretty sure this is related to https://github.com/reactioncommerce/reaction/issues/422 as if there is any issue with the process no message is returned to the user, the "Resubmit Payment" button just appears. Probably should add different handling for any processor-side returned errors (aka DECLINED) as opposed to a real Meteor.Error being thrown.

Since that is defined is a separate ticket I will close this one for now.
