### ISSUE TITLE
Import `reaction.json` from ENV

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3906]
Ability to pass `reaction.json` (reaction package registry entries) as **ENV**`REACTION_SETTINGS` variable  in addition to the /private/data/settings fixture file.

```
export REACTION_SETTINGS=$(cat /Users/aaronjudd/Projects/config/reaction.json)
```
This is how [`METEOR_SETTINGS`](https://docs.meteor.com/environment-variables.html) works, so it's sort of implied that `REACTION_SETTINGS` should work this way as well, and would have significant benefits like environment specific configuration, such as in could be used in testing/build processes, and for pre-configuration of Reaction instances being deployed in a self-provisioning process.

If the **ENV** var was set, skipping any FS or other imports would also be logical.

## Suggested Solution
* Add logic to the handling where we import `reaction.json`
* Skip file handling if ENV present

**Comment by kieckhafer** [comment]
@aaronjudd Is this the correct place to begin looking?

https://github.com/reactioncommerce/reaction/blob/master/server/api/core/core.js#L873

At first glance it seems we might already be doing this, we just call it `REACTION_REGISTRY` instead of `REACTION_SETTINGS`.

If this is the case, do we update it to be `REACTION_SETTINGS`? Or do we stick with what it is and just register the `env` variable as `REACTION_REGISTRY`?

**Comment by aaronjudd** [comment]
In hunting for the source of this, I think that I was the source of the mistaken name via a very old `.zshrc` entry I had stored locally, probably from the time before `REACTION_REGISTRY` was implemented...  then I propagated that in a discussion with @spencern  a few weeks ago.. as we were discussing how to easier use our configuration (without having files in the path).. ..  I (think) now that @jshimko and I had settled on `REACTION_REGISTRY` because it's really our package registry and is much more than `settings` in scope..  so I think it's correct to keep the naming as is.  The related issue #3934 will help clarify that these two settings are unrelated.. 

I'm cringing a bit, but it could be that we might want to alias `REACTION_SETTINGS` to `METEOR_SETTINGS` for the purpose of the initial user configuration.. this creates other questions though that I don't think we've really thought through yet.

**Comment by kieckhafer** [comment]
#3934 is ready for review now. As for this ticket, what I'm taking away is:

1) Do nothing right now
2) Discuss aliasing `REACTION_SETTINGS` to `METEOR_SETTINGS` at some point (standup perhaps)?

**Comment by jshimko** [comment]
I know this is still going through some discussions right now, but FYI for anyone that isn't aware, the Reaction registry and Meteor settings files can both be loaded into their associated env vars like this...

```sh
# loads stringified registry file contents into REACTION_REGISTRY
reaction --registry ./path/to/reaction.json

# uses the `--settings` flag when running the `meteor` command under the hood
# Meteor automatically sets the METEOR_SETTINGS env var with the contents
reaction --settings ./path/to/settings.json
```

**Comment by kieckhafer** [comment]
Closing out. We can re-open (or make new tickets) if we decide to alias `REACTION_SETTINGS` to `METEOR_SETTINGS`.
