### ISSUE TITLE
Create account profile UI that uses GraphQL data

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3907]
**Summary**
This ticket is for implementing an `account/profile` view utilizing the GraphQL API that we're creating. 

This implementation will need to mock the data coming from the `viewer()` GraphQL query, and will need to utilize the following GraphQL mutations to transmit data from the client to the server:
- ~`addAccountEmailRecord`~
- ~`removeAccountEmailRecord`~
- `addAccountAddressBookEntry`
- `removeAccountAddressBookEntry`
- `updateAccountAddressBookEntry`

This implementation _should not_ include the `Your orders` component which lists the `viewer`s orders.

It should implement the following:

- [ ] ~`Update Email Address` functionality [Maybe?]~
- [ ] ~`Update Password` functionality~
- [ ]  All Address Book functionality

This implementation should leverage whichever state management system is chosen in #3904 

The following is a thin slice for the account with editable full name field, currently a noneditable email, and flow for editing the flow. 
![user profile - account - password update](https://user-images.githubusercontent.com/20409254/37635052-92a5583a-2bb6-11e8-8cc0-592ebdea3ce1.png)
![user profile - account - password update open](https://user-images.githubusercontent.com/20409254/37635057-985e2d9c-2bb6-11e8-9fb5-221ba6c7745a.png)

## Acceptance Criteria
This ticket will be considered resolved once the account profile is usable (as described above) and uses the GraphQL API exclusively.

**Comment by spencern** [comment]
@rymorgan Here's the profile issue we discussed.

**Comment by rymorgan** [comment]
Here is the full design for where we are eventually going with user profile. We should be building toward this. Whoever picks this issue up, let's have a quick kick-off to clarify the designs. 

![user profile - account mobile menu open v2](https://user-images.githubusercontent.com/20409254/37635192-7b7307c4-2bb7-11e8-8d90-45ad4f1fb3f4.png)
![user profile - account mobile v2](https://user-images.githubusercontent.com/20409254/37635194-7b8ddd2e-2bb7-11e8-8866-aa6e22b9a936.png)
![user profile - account v2](https://user-images.githubusercontent.com/20409254/37635195-7ba64cc4-2bb7-11e8-8db6-d2003b5fc044.png)

**Comment by rymorgan** [comment]
@spencern This should be good to go.

**Comment by rymorgan** [comment]
Updated mock for this w/ initial limitations
![user profile - account - password update](https://user-images.githubusercontent.com/20409254/37688682-7b3ede84-2c5e-11e8-9acb-f6d65cfd22a4.png)
 - aka we no editing of name, email or password.

**Comment by cassytaylor** [comment]
The mocks for Address Book are up on Zeplin - https://zpl.io/2GzqRgd
(comments/annotations to come)

Static mocks below: 

Mobile-----------------------------------
![user profile - address book v2 mobile](https://user-images.githubusercontent.com/36006187/37729756-1fdd6a04-2cfb-11e8-92f8-a25644da8cb6.png)
![user profile - address book v2 mobile - open](https://user-images.githubusercontent.com/36006187/37729777-2c03b8f6-2cfb-11e8-8820-22db881ea0b1.png)

Desktop v2-----------------------------------
![user profile - address book v2](https://user-images.githubusercontent.com/36006187/37729830-4b0fafac-2cfb-11e8-943b-f1933228fd91.png)
![user profile - address book v2 open](https://user-images.githubusercontent.com/36006187/37729837-50546e76-2cfb-11e8-8435-70070b4f41e9.png)

Desktop-----------------------------------
![user profile - address book](https://user-images.githubusercontent.com/36006187/37729787-35c8c5e8-2cfb-11e8-82f5-4afa71f71e63.png)
![user profile - address book open](https://user-images.githubusercontent.com/36006187/37729804-3d84978a-2cfb-11e8-9bae-acbfa86b3084.png)

**Comment by rymorgan** [comment]
@cassytaylor is working on the address book flow and will be done soon. She's also documenting how the menu component will work for desktop/mobile.
