### ISSUE TITLE
Add users to organization

### ISSUE THREAD

**Issue by faddat** [reactioncommerce/reaction#391]
So I've never been able to do that-- anyone have any hints?  I click the button, nothing happens. 

ongoworks/reaction Docker on ubuntu 14.04

THanks!

**Comment by aaronjudd** [comment]
@faddat ongoworks/reaction is running 0.5.3.  0.6.0 has all the updates to add users, granular permissions.

**Comment by faddat** [comment]
The branch currently labeled as "development" is 0.6.0?  Or.... How would I get the latest most bleeding edge beta?

As a former employer once put it "the haemoraging edge"

**Comment by aaronjudd** [comment]
Yes, just checkout / pull from development.  I'll update the docker image though when development is merged to master (so when it's stable).   I'm attempting to make the docker build be part of the CI process, so in the near future I'm hoping we can keep it up to date with dev as well, but for now you'd need to build your own image if you wanted to get the dev codebase.

**Comment by aaronjudd** [comment]
Closing (closed in dev).
