### ISSUE TITLE
Create roles GraphQL query

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3916]
**Summary**
Create a `roles` query in GraphQL.

**Implementation**
The `roles` query should have the following signature
```
roles(shopId: ID!): [String]
```
It has one argument, `shopId` which is required, and returns an array of Strings which are roles associated with that shopId if the user requesting the groups has permissions to access those roles. For this ticket, it may be necessary to create a new function on the server to fetch the list of roles for this Query. These roles should be a filtered list of all roles available for this shop, where only roles for packages that are enabled are returned.

## Acceptance Criteria
Using GraphQL, I can use the `roles(shopId: ID!)` query to get an array of roles as `String`s by shopId.

**Comment by spencern** [comment]
@kieckhafer I think you are correct about this. 
I'm pretty sure that the roles that should be returned are represented in the `roles` collection in the db as seen in the following image:
![image](https://user-images.githubusercontent.com/1203639/37777012-304ecad4-2dac-11e8-80a5-f37ef4b50efc.png)

In this case, you're correct that an array of strings is not going to be sufficient and we probably need to look at a RolesConnection or something similar.

**Comment by aldeed** [comment]
@kieckhafer Yes, this is a connection as shown in the schema, but one change from the schema. You can delete `scalar RoleName` and change `name` to `String!`. We don't really have a regular expression pattern they follow, and even if we want to add one, we'll only need that validation on the mutation/input, and not on the query/type.

**Comment by kieckhafer** [comment]
@spencern @aldeed @ticean 

Can someone clarify a bit more exactly how we should be doing this? Roles themselves aren't attached to a shop. They are in the `roles` collection, and only have a unique `id` and `name`, no `shopId` attached to them.

ShopID's are really only attached on each individual user - and not in the `Accounts` collection, but in the `users` collection. Each `user` had a `roles` object, which has each shop as an array inside that object.

I'm not really sure where to begin at getting `roles` that are attached to a shop. Aren't all `roles` available on all `shops`?

**Comment by ticean** [comment]
It makes sense to me to specify the `shopId` from the `account`/`user`, And not providing when fetching `roles` from the detached, top-level. I've been learning this area with @spencern's help. What do you think, @spencer?

We've got a confusing situation around the `account` and `user` and I'm been discussing with the team to find the right way to resolve that. However we handle that, I think we resolve through `account` here, even though we may technically go through `user` in the db.

**Comment by aldeed** [comment]
@ticean I think the confusion here is over what this query is for. Is it getting the list of roles, or getting the list of roles for the current user for this shop (i.e., `Account.roles` rather than `Query.roles`)?

If this is just to get the complete role list, then there shouldn't be a shop ID involved because our roles are not currently shop-specific.

If this is to get roles for an account for a shop, then those would be grabbed off the `user.roles[shopId]` object.

**Comment by spencern** [comment]
@kieckhafer @aldeed @ticean 

This particular query I is just to get a list of potential roles for the account management page. As of right now, I'm not certain how this happens. Right now we seed a list of roles, but it seems to be somewhat dependent on the our register.js files. See this image for what we were thinking in terms of this query.

![image](https://user-images.githubusercontent.com/1203639/37800085-5bae4ffc-2de7-11e8-945f-e99f1f49c2bf.png)

@kieckhafer I think on the Meteor Reaction side of things, this might grab roles from the shop or packages somehow.

 Happy to pair with you on it to determine exactly what is going on if that's helpful.
