### ISSUE TITLE
Update icons on product details page

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#392]
Clone / duplicate icon is out of sync with the changes from #386. 

In addition to updating the icon, I added text to the buttons and changed the 'Add variant option' icon to a plus sign. I think it makes it a little clearer. Thoughts?

![reaction___guard_shack_tee](https://cloud.githubusercontent.com/assets/42217/8296706/e0ed803a-1908-11e5-81e6-a31b6b74f892.png)

After this is pushed, I'll update the development docs here: https://github.com/reactioncommerce/reaction/blob/development/docs/products.md

**Comment by aaronjudd** [comment]
:+1:  make sense - and not having text there has always been ugly.
