### ISSUE TITLE
Create a updateGroup mutation in GraphQL

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3923]
**Summary**
Create an `updateGroup` mutation in GraphQL.

**Implementation**

Signature:

```
updateGroup(input: UpdateGroupInput!): UpdateGroupPayload
```

Input argument:

```
  input UpdateGroupInput {
    # An optional string identifying the mutation call, which will be returned in the response payload
    clientMutationId: String

    # The group ID
    id: ID!

    # The ID of the shop this group belongs to
    shopId: ID!

    # The changes to apply to the group
    updates: GroupInput!
  }
```

It returns the `Group` that was successfully updated. This mutation should act on the groupId that matches the groupId supplied and where the shopId matches the shopId supplied.
It should only update the group if the user calling this mutation has the correct permissions.

## Acceptance Criteria
Using GraphQL, I can use the mutation to update the permissions or other details of a group.

**Comment by aldeed** [comment]
#5832 is a newer version of this ticket
