### ISSUE TITLE
Create a createGroup mutation in GraphQL

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3924]
**Summary**
Create a `createGroup` mutation in GraphQL.

**Implementation**
The `createGroup` mutation should have the following signature
```
createGroup(groupData: GroupInput!, shopId: ID!): Group`
```
It has two arguments:
- `groupData` which is required and is of type `GroupInput`
- `shopId` which is required and is of type `ID`

It returns the `Group` that was successfully created. This mutation should create a group for the shop which matches the shopId supplied.
It should only create the group if the user calling this mutation has the correct permissions for the shop associated with the supplied shopId

## Acceptance Criteria
Using GraphQL, I can use the `createGroup(groupData: GroupInput!, shopId: ID!)!)` mutation to create a group for a specified shop.

**Comment by aldeed** [comment]
#5831 is a newer version of this ticket
