### ISSUE TITLE
Remove use of Meteor._sleepForMs

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#3937]
Many tests use `Meteor._sleepForMs`. This isn't a great way to deal with waiting for async operations since it's not exact and leads to random false failures. Fortunately, most of these were due to use of collection-hooks, which we're getting rid of. 

#### Task

After #3547 is done, search for and remove all instances of `Meteor._sleepForMs`. Hopefully tests will pass without them. If not, figure out how to properly wait for the needed data operation to complete in each test that is failing.

#### Testing

Verify that no tests are using `Meteor._sleepForMs` anymore. Run tests twice locally and make sure all pass. Make sure they pass on CI as well.

**Comment by zenweasel** [comment]
Closed via #4161

**Comment by evolross** [comment]
It would be nice if in Meteor 3.x there was an easy to use `await Metoer._sleepForMsAsync(1000)`.
