### ISSUE TITLE
Product grid is passing data for all products to each product item component

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#3938]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The [ProductGrid](https://github.com/reactioncommerce/reaction/blob/766c97ebfacec67afecedb021cb3bac79658d1f1/imports/plugins/included/product-variant/components/productGrid.js#L14) component is applying all of its props via a spread operator to each [ProductGridItems](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/product-variant/components/productGridItems.js) component. This is causing each ProductGridItems component to not only have it's own product data but also have the `products` & `productIds` array attached to each grid item's props. This is probably causing a lot of unnecessary rendering of components in the product grid.

*ProductGridItems Component props in React devtool*
![screen shot 2018-03-07 at 3 23 12 pm](https://user-images.githubusercontent.com/1135948/37123412-c03c2080-2229-11e8-8cd1-72342d8d4e0c.png)

## Steps to Reproduce
*You'll need [React devtools](https://github.com/facebook/react-devtools) installed to reproduce*
1. Spin up a fresh RC shop.
2. Open React devtools and inspect the ProductGridItems component. (The node will be called `Reaction(ProductGridItems)`)
3. Verify that the `products`, `productIds` and `productsByKey` are all in the component props.

## Possible Solution
Removing the spread operator and passing down the explicit props to the ProductGridItems component.

### Versions
```sh
Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.2
Reaction branch: master
Docker: 18.02.0-ce
```

**Comment by zenweasel** [comment]
@nnnnat Is this ready to close? (just trying to go through all the `performance` tickets)

**Comment by nnnnat** [comment]
@zenweasel I think so
