### ISSUE TITLE
jquery font dependency not resolving

### ISSUE THREAD

**Issue by johnbendi** [reactioncommerce/reaction#394]
The call your jquery dependency is making to `http://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2` and `http://fonts.gstatic.com/s/opensans/v13/k3k702ZOKiLJc3WVjuplzOgdm0LZdjqr5-oayXSOefg.woff2` is not coming through. This is happening just as I finished the installation and started the server and navigating to the start page. It hangs as it waits for the above file and doesn't really display anything useful. Please verify.

**Comment by aaronjudd** [comment]
This is a dependency of core-theme. I'm not able to replicate (in fact those urls are working ok for me). If it doesn't download opensans there's a couple fallback fonts defined though, so it should work still.

**Comment by i-a-n** [comment]
The font definition from reaction-core-theme is Google-hosted [http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,700,300,600,800,400] so if you can load that file, but then not the font file itself, it's either a 1) localized browser/config/proxy problem or 2) one of Google's behemoth CDNs is down momentarily. I think in either case this would be quite rare and, in any case, can't think of a better solution than using Google Fonts.

Closing for now, we can revisit if Google ends up proving unreliable or changes how they distribute fonts.
