### ISSUE TITLE
Anonymous customer no longer added to "guest" group in release-1.9.0

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3946]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
In `master`, customers checking out were added to the `guest` group but in `release-1.9.0` they are not. 

## Steps to Reproduce
1. Checkout `master`, check out anonymously
1. Pull up `Accounts` and view that the Account created has the `guest` group added here
1. Checkout `release-1.9.0`, check out anonymously
1. Observe that this newly created Account does not have that group

**Comment by zenweasel** [comment]
I am not 100% sure of the impact because I don't know how this affects things downstream so I am cautiously making this `impact-major`

**Comment by prinzdezibel** [comment]
Can't confirm that this works in master. I'm on this commit:
`* master        766c97ebf [origin/master] Merge pull request #3855 from reactioncommerce/release-1.8.2`

**Comment by prinzdezibel** [comment]
Can't see that this works in master either. Going to downgrade it to impact-minor again and switching over to something more important.

**Comment by zenweasel** [comment]
If you can't reproduce, please close. We can always reopen.
