### ISSUE TITLE
Validation Error dot shows up when creating product and there's no validation error

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3955]
## Issue Description
When creating a product the "red dot" validation shows up even though there is no validation. Probably related to the `simple-schema` changes.
![2018-03-09_12-47-59](https://user-images.githubusercontent.com/72819/37191271-7f1b4e98-2399-11e8-91e2-5ef2e5a6bc67.png)

## Steps to Reproduce

1. Create a product
1. Observe the red appears
1. Fill out all information properly and publish
1. Observe the red dot never disappears

## Possible Solution
Probably this call to simple schema to check validation was not updated to fix the new API since it happens client side?

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce
```

**Comment by aldeed** [comment]
This UI is removed in 2.0.0
