### ISSUE TITLE
Deleting one shipping rate deletes all shipping rates

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3956]
## Issue Description
If you go to delete a shipping rates it actually deletes all of the included rates

## Steps to Reproduce

1. Login as admin
1. Go to shipping dashboard
1. Enable "Flat Rates" to open that panel
1. Select one of the included rates
1. Click on delete and confirm "delete rate"
1. Observe that all the rates are deleted

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
Confirmed that this doesn't happen in the current `master`

**Comment by spencern** [comment]
What I'm seeing is that it's deleting all shipping rates that are not enabled. I had one rate enabled and that rate persisted.

**Comment by kieckhafer** [comment]
Seeing the same thing.
