### ISSUE TITLE
Cloning products is not reactive

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3957]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
Cloning a product via clone button does apparently have no effect. Only refreshing the page shows that the product indeed has been cloned. 

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. As a admin, create a product
2. Navigate back to product grid
3. Clone the product in the `Grid settings` via clone button
4. See nothing happen
5. Refreshing the page shows up the cloned product, though

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.03.1-ce

**Comment by zenweasel** [comment]
I confirmed that this is not happening on `master`

**Comment by prinzdezibel** [comment]
Happens, because the publication itself is not reactive, but the observed cursor itself is dependent on another cursor.
Need to figure out how to deal with that without the need to pull in a meteor package like
https://github.com/peerlibrary/meteor-reactive-publish

**Comment by prinzdezibel** [comment]
@jshimko if you could find time for this one that would be great. I think Brent considered this as a blocker.

**Comment by jshimko** [comment]
Ok, are you saying you want me to fix this? Or was there a PR with a proposed fix?

**Comment by jshimko** [comment]
Never mind.  Found it.

**Comment by zenweasel** [comment]
@prinzdezibel Unassigning you since @spencern and I have decided we want to leave dealing with revisions issues up to the core team.
