### ISSUE TITLE
Error: Method 'reaction/getUserId' not found [404] on app startup

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3963]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
On startup, the following error is repeated over numerous times (100+). It does not seem to have any affect on anything.

```
W20180309-16:41:17.126(0)? (STDERR) (node:415) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Method 'reaction/getUserId' not found [404]
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Reset and start Reaction
2. See error in server console

### Versions
Node: 9.7.1
NPM: 5.7.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.2
Reaction branch: master
Docker: 18.02.0-ce

**Comment by aaronjudd** [comment]
Been seeing this in `reaction test` over the last several releases..

**Comment by zenweasel** [comment]
I've seen this error in test, but have never seen this while running the actual app
