### ISSUE TITLE
Avalara settings panel doesn't have api key field

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3967]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
Impossible to set Avalara API key settings from the UI.

![image](https://user-images.githubusercontent.com/1203639/37225335-8cfec1e4-2393-11e8-98ad-8d879dafb09d.png)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Remove settings.json
2. Start the app
3. Login as admin
4. Open Avalara panel. From here you should be able to set the API key

## Possible Solution
Not sure if this would be related to the schema updates or an issue with the React panel.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
Closed via #3969
