### ISSUE TITLE
Email configuration remains red even after correct information is entered

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3976]
## Issue Description
This appears to be the inverse of this issue (https://github.com/reactioncommerce/reaction/issues/3701). When you enter valid configuration settings and receive a success message, the red/green indicator still remain red.

## Steps to Reproduce
1. Go to email dashboard
1. Click on the gear icon to configure your email server
1. Select "Maildev"
1. Click Save
1. Observe success message
1. Observe that green/red indicator is still red

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
Not a regression because I don't recall this ever working correctly.

**Comment by aldeed** [comment]
I think this is the same issue described in #3832. Still an issue

**Comment by aldeed** [comment]
No longer relevant after 3.0 release. Only ENV can be used to configure email.
