### ISSUE TITLE
Inefficient Implementation of getChildVariants selector

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#3986]
When investigating why Products with a lot of Variants/Options increase load time so heavily,
I notices the following issue in this chain:

In `plugins/included/product-details-simple/client/selectors/variants.js`
The function getChildVariants() fetches all variants without specifing an id:
`const variants = ReactionProduct.getVariants();`

The function getVariants of ReactionProduct in `/lib/api/products.js` will pass this call to Catalog,
and as there was no id specified, it will call it with `ReactionProduct.selectedProductId()`

The function getVariants in `lib/api/catalog.js` will then return every variant of the selected Product, and not just query the variants that are child of the current selected variant.

## **The real issue here:**
**Imagine a Product with ten Variants, each Variant has e.g. 50 options/child variants.**

The options will display correctly under each Variant, as the getChildVariants selector will compare with
`variant.ancestors[1] === current._id`

But instead of going through 50 options that the variant has, the map function will map 50x10 = 500 items to display the options of a selected variant.
**So, when directly visiting the detail page of a product with the described scenario, initial load time will be enormous as not 50 but 500 variants would be iterated over.**

I hope the conclusions I made here are correct, and would really appreciate feedback where the best place in this chain would be to query for the variant's childs, and not the product's.

**Comment by aldeed** [comment]
Although this code hasn't yet been removed, it isn't used anymore and the new example storefront for 2.0.0 does not have this issue.
