### ISSUE TITLE
Limit returned fields for ShopMembers

### ISSUE THREAD

**Issue by queso** [reactioncommerce/reaction#399]
Redefine fields here: https://github.com/reactioncommerce/reaction-core/blob/development/server/publications.coffee#L120-L127

```
sort of not - these are all administrative roles where the full list of users was needed. however, we've made changes to move the user "profiles" into the "Accounts" collection,  maybe this could be pruned to just a list of _id,  that and then a join to the accounts collection for the actual profile data. 
could also update to: `permissions = ['dashboard/orders','owner','admin']` as 'dashboard/customers' is deprecated.
```

**Comment by queso** [comment]
@aaronjudd so my gut here says it is better to limit publications to the fields we need/care about, rather than exposing the whole record. Especially when it comes to the user and things like oAuth tokens or salted password hashes.

**Comment by aaronjudd** [comment]
yes, we can limit to just a list of userId joined to the Accounts collection- I don't think we need any of the `users` collection data.  So, just a list of userId, with a separate lookup for the individual record in Accounts.  However this is an administrator functionality, not for the regular user and should allow the editing of any user records by the admin.  Perhaps we can limit the fields from `Accounts` to email and addressBook.

**Comment by queso** [comment]
Ok. We can limit and I will take a little at Accounts too.

In general, we want to restrict sending stuff over the wire in case the install isn't running SSL. I guess given it is an e-commerce shop, they really should have SSL.

**Comment by aaronjudd** [comment]
yes, I'd assume that they are always running ssl.  (we used to include force-ssl as a default package, but now I bake that in the build when we deploy).
