### ISSUE TITLE
link it causes an error in Sass

### ISSUE THREAD

**Issue by nuruddinXbadawi** [reactioncommerce/reaction#3996]
## Issue Description
I was trying to make my own theme, but I need to style the theme by SCSS instead of Less, 
- first I create the my-theme directory in plugins/custom 
- I add the style inside client folder and I imported in index.scss like this `@import "styles/navbar";`
- I add Scss to the meteor ` meteor add fourseven:scss`.
- it shows me an error when I build, the error is 

>  While processing files with fourseven:scss (for target web.browser):
   /client/plugins.scss: Scss compiler error: File to import:
   /imports/plugins/custom/my-theme/client/index.scss not found in file:
   /Users/nuruddin/nur/projects/my-projects/talabi/{}/client/plugins.scss

 - I search I found the reaction generate plugins.scss file inside client root directory, it's import my theme style, like in the attached image.

<img width="707" alt="screen shot 2018-03-13 at 10 01 19 pm" src="https://user-images.githubusercontent.com/5736522/37363909-2b5c3172-270a-11e8-8e79-2e5380e0a485.png">

to fix the error above the importing should start with `{}/imports/.....`, I can't change it because it's loaded automatically by Reaction.

### Versions

Node: 9.7.1
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).
