### ISSUE TITLE
[Marketplace] Don't trust a passed in shop

### ISSUE THREAD

**Issue by queso** [reactioncommerce/reaction#400]
We are passing in a shop to the packages pub. https://github.com/reactioncommerce/reaction-core/blob/development/server/publications.coffee#L89

```
certainly make no sense as is, should as least be ` shop = shop || ReactionCore.getCurrentShop(@)`.    I think this is more a hint of the functionality needed for the marketplace(multi-shop)..  which might publications might need a shop param (or something like this https://github.com/DispatchMe/Meteor-restricted-find)
```

**Comment by queso** [comment]
@aaronjudd can you explain the concept of a multi-shop more? Is this something supported now, or planned for in the future?

**Comment by aaronjudd** [comment]
yes, see https://github.com/reactioncommerce/reaction/issues/357.

We've begun implementing parts of this. and there are other community members developing there own versions of this, and I feel like we should try at least add to the schema/model/publications handling, even if we don't build any UI for this right now.
