### ISSUE TITLE
Convert Avalara tax settings panel to React

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4003]
Refer to the conversation in https://github.com/reactioncommerce/reaction/pull/3998

The relevant files:

imports/plugins/included/taxes-avalara/client/accounts/exemption.html
imports/plugins/included/taxes-avalara/client/accounts/exemption.js

It also needs to be rendered wherever it was rendered prior to the parent conversion to React.

**Comment by zenweasel** [comment]
Wasn't this already done? I think this is already react?

**Comment by zenweasel** [comment]
The account setting was part of the account panel

**Comment by aldeed** [comment]
This is referring to the exemption autoform, which has the name "taxSettingsPanel", hence the name of this issue. I clarified the description. I did not see anything in React for this.

**Comment by zenweasel** [comment]
Won't fix. Avalara no longer part of Core.
