### ISSUE TITLE
Notifications link broken in single shop scenario

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4004]
## Issue Description
In a single-shop scenario we don't use the "shop slug" but the link for "Your order was accepted" uses it so returns a 404

## Steps to Reproduce
1. Place an order
1. Click on notifications icon
1. Click on "Your order was accepted"
1. Observe that the link goes to "http://localhost:3000/reaction/notifications" which doesn't exists so you get a 404

## Possible Solution
When a single shop is present the "shop slug" should be blank

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-c
```

**Comment by aldeed** [comment]
@zenweasel I'm seeing this go to `/shop/reaction/notifications` which correctly loads notifications page. Maybe this was fixed at some point and can be closed?
