### ISSUE TITLE
Numeric input in PDP is sometimes reverted

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4007]
## Issue Description
When clicking on numeric input it requires you to remove the initial `0` or sometimes the value you enter is changed back to 0.

## Steps to Reproduce
1. Go to PDP
1. Move to one of the numeric field and don't remove the `0`
1. Observe that sometimes your value is changed to 0

I will add a video for this. Trying to capture this for now

```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce
```

**Comment by aldeed** [comment]
@zenweasel do you still see this anywhere?

**Comment by aldeed** [comment]
Closing this. The form in question will be redone soon. This can be opened in reaction-admin repo if still a problem.
