### ISSUE TITLE
Product publication handle regex match issues with similar product handles

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4008]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

Product handle in `Product` publication matches using a regex, which causes issues if your product handle that is a subset of another product's handle.

With the two product handles below
1. `basic-example-product-copy`
2. `t-copy`

The product with handle `t-copy` will match `basic-example-product-copy` because of `t-copy`

## Steps to Reproduce

1. As an admin
1. Duplicate the default "Basic Reaction Product"
1. Create yet another new product
1. Set the product title to `t-copy`
1. fill out required fields and publish
1. notice all your variants for `t-copy` have now disappeared

## Possible Solution

Remove the regex match in the `Product` publication, in favor of an exact match.

### Versions

Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce

**Comment by spencern** [comment]
@mikemurray do you know if we can close this ticket now?

**Comment by kieckhafer** [comment]
@mikemurray can this be closed with your GQL products work?
