### ISSUE TITLE
Missing schema?

### ISSUE THREAD

**Issue by queso** [reactioncommerce/reaction#401]
So I was looking over the ordersSchema and noticed that it lacked any shopId definition...

https://github.com/reactioncommerce/reaction-core/blob/05a645877b876a1cceb9ca6fe6d293db2ee89a78/common/schemas/orders.coffee#L125-L137

But the Orders publication references finding by a shopId: https://github.com/reactioncommerce/reaction-core/blob/5398393b3bded36be256aa8685a7bf057dbf46de/server/publications.coffee#L158-L164.

I think I am missing something, but I am not seeing what. Thoughts @aaronjudd?

**Comment by aaronjudd** [comment]
See: https://github.com/reactioncommerce/reaction-core/blob/development/common/collections/collections.coffee#L71

**Comment by queso** [comment]
Ah, it is the cart that is providing the shopId definition.
