### ISSUE TITLE
Cannot make new product visible right after creating, need to refresh and retry

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4010]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

Cannot make product visible right after creating a new product, and then trying to make it visible from the PDP page. Refreshing the PDP page after creating the product and trying again seems to resolve the issue.

## Steps to Reproduce

<img width="379" alt="sadsad" src="https://user-images.githubusercontent.com/42217/37446742-b4b10912-27db-11e8-8ace-baaa44fb8354.png">

1. As an admin from the product grid...
1. Create a new product
1. Fill in product data
1. Click the eye icon to make the product visible
1. Click the Publish button
1. See changes published successfully message
1. Notes the eye icon, reverted back to its previous state with the slash
1. View the product grid as a customer incognito, or otherwise not signed in
1. See your product **is not** visible on the grid
1. Refresh the PDP page as the admin
1. Make the product visible
1. Publish again
1. Visibility button eye icon should not have reverted back to an eye with a slash.
1. View the product grid once again as a customer
1. See your product **is** visible on the grid

## Possible Solution

The publishContainer that controls the publish controls may be getting an incorrect list of products to watch for changes. The publish controls are supplied a list of document ids, usually products or media that it will publish when you click the "Publish" button.

### Versions
Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.9.0
Reaction branch: master
Docker: 17.12.0-ce

**Comment by ajporlante** [comment]
This no longer happens in `1.14.0`.
