### ISSUE TITLE
Modification indicators do not show when modifying certain fields

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4017]
## Issue Description
When you modify a previously purchased product the "pencil" icon is not lit

## Steps to Reproduce
1. Create a product and publish it
1. Go back to PDP and modify the subtitle and vendor
1. Observe that the "pencil" icon does not change color to indicate that the field has been modified

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: release-1.10.0
Docker: 17.12.0-ce
```

**Comment by aldeed** [comment]
Fixed in 2.0.0
