### ISSUE TITLE
docker + orchestration + meteor reaction deployment

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#402]
Production quality reaction deployment as a PaaS using Docker, Rancher or Tutum.

Meteor methods for creating and deploying reaction clusters using these orchestration services.

Testing giving each shop get it's own persistent 3 member replica set mongodb cluster service, and load balanced app servers running on docker containers.

Specs in progress with @jshimko, will add docs as we get the first prototype solution working.

**Comment by faddat** [comment]
No kidding!  Surprised and glad to see this :).

Well, I suppose you felt quite the same about it that I did.

:)

-Jake

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by faddat** [comment]
Tutum is also good-- I prefer that rancher is independent and of course that it is beer-free. , but tutum deserves a holler for coolness.  

Wiki will be up shortly, incidentally.  Would it be possible for me to docker up the rancher equivalent of Rancher's Build-Master dockerfile?  Any tips?

**Comment by jshimko** [comment]
@faddat, not totally clear what you're asking.  Are you asking how to deploy Rancher for the use case mentioned here?

**Comment by jshimko** [comment]
Our current progress on Launchdock has been officially open sourced, so we're going to close this issue and move the conversation over to the that repo instead.  (Setup docs coming very soon)  

[Check it out!](https://github.com/reactioncommerce/launchdock)
