### ISSUE TITLE
Disabled Quantity field displays strange values

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4022]
## Issue Description
Once the field is disabled this value turns to a strange value, binary?

![2018-03-16_14-58-50](https://user-images.githubusercontent.com/72819/37507669-bce5828e-292a-11e8-9808-3ddea0f0d103.png)

## Steps to Reproduce
1. Create a product
1. Add a variant
1. Add multiple options
1. Observe the strange value displayed in "Quantity" field

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: release-1.10.0
Docker: 17.12.0-ce
```

**Comment by aldeed** [comment]
No longer an issue as far as I've seen
