### ISSUE TITLE
Changing handle and hitting publish throw a 404

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4023]
## Issue Description
If you change the handle of a previously published product and hit publish you get a 404 error

## Steps to Reproduce
1. Create a product and publish
1. Change the title and handle
1. Publish
1. Observe the 404 error

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: release-1.10.0
Docker: 17.12.0-ce
```

**Comment by prinzdezibel** [comment]
Looks like part of the changes from [#2246](https://github.com/reactioncommerce/reaction/commit/52406afa2e6428aaa78392eaebec19608e405d2a#diff-f5e686b0d82a5ec56ad62d4b5c45913a) got lost [here](https://github.com/reactioncommerce/reaction/commit/1cf2f0c2c3eadae4f96d04d72ed3fbd548ba8978#diff-f5e686b0d82a5ec56ad62d4b5c45913a)

**Comment by ajporlante** [comment]
This will have to wait until v1.13 per @spencern and @aldeed in https://github.com/reactioncommerce/reaction/pull/4144
