### ISSUE TITLE
ProductGridItem (user role) is not replaceable

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#4026]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
It's not possible to replace ProductGridItem (user role)  via replaceComponent function of the Component API.

## Motivation
For swag shop upgrade to 1.9.0 I have the need to override ProductGridItem component.

## Steps to Reproduce
1. Putting this snippet into somewhere will produce an error, because the component `ProductGridItem` is not registered.
```
const ProductGridItem = (props) => <div>customized user product grid</div>;
replaceComponent("ProductGridItem", ProductGridItem);
```

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.9.0
Reaction branch: master
Docker: 17.03.1-ce

**Comment by spencern** [comment]
How is this a bug and an enhancement?

**Comment by prinzdezibel** [comment]
Let's call it bughancement. It's not that something is broken in core per se, but I can't updated the swag shop plugin without this fix.

**Comment by zenweasel** [comment]
I think not being able to replace a component via the Components API should always be considered a bug
