### ISSUE TITLE
CI: Run Jest and Meteor tests in parallel

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4028]
The `release-1.10.0` branch now has jest tests. CI config should be updated to run these in parallel with existing meteor tests.

1. Add a jest test step that runs `npm run test:unit`. There is no Meteor dependency for this one, but it needs the npm modules installed.
2. Change the existing test step to run `reaction plugins load` followed by `npm run test:app` (instead of `reaction test`)

**Comment by spencern** [comment]
Closed by #4030
