### ISSUE TITLE
Decouple `User(_id)`, `Account(_id)`, and `Account(userId)`?

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#4034]
Perhaps I misunderstand what `Account(userId)` is used for, but reading through the code, we expect `Account(_id)` to equal `User(_id)` (`Account(userId)` already equals `User(_id)`). This feels like a data integrity issue waiting to happen.

There are several lines which look like this:
``` JavaScript
Accounts.findOne({ _id: Meteor.userId() });
// or
Accounts.findOne({ _id: user._id });
// or
Accounts.findOne({ _id: userId });
// there are others as well
```
which could easily be replaced with
``` JavaScript
Accounts.findOne({ userId: Meteor.userId() });
Accounts.findOne({ userId: user._id });
Accounts.findOne({ userId: userId });
```

**Comment by zenweasel** [comment]
@pmn4 I don't understand exactly what exactly the issue is here. Are you saying that we just aren't using querying for account consistently? And is the solution to go through all the code and make it consistent?

**Comment by aldeed** [comment]
Mostly done
