### ISSUE TITLE
Inventory collection `inventory.status` not properly updated when canceling an order

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#4039]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When cancelling an order, and choosing to restock the inventory, the Inventory collection keeps the inventory marked as `Sold` instead of changing back to `new`. We had a similar PR, #3776, which updated the `Products` collection inventory numbers, but the `Inventory` collection was never updated.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Write down inventory numbers of product
2. Purchase `x` number of product
3. Approve and Capture payment on product
4. Cancel order, and choose `Restock`
5. Open Robo3T, and see that `x` number of products are listed with the `workflow.status` as `sold`

## Possible Solution
Use `Hooks.Events` to update Inventory collection when an item is returned to stock. Possible put the `Hook` call in `server/methods/core/orders.js`: https://github.com/reactioncommerce/reaction/pull/3776/files

### Versions
Node: 9.7.1
NPM: 5.7.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: release-1.10.0
Docker: 18.02.0-ce

**Comment by zenweasel** [comment]
Closing this since the inventory package is no longer part of Core and will not be updated.
