### ISSUE TITLE
1 is not a valid Win32 Application

### ISSUE THREAD

**Issue by abhisheksoni27** [reactioncommerce/reaction#404]
W20150709-13:00:15.384(5.5)? (STDERR) Error: %1 is not a valid Win32 application
.
W20150709-13:00:15.384(5.5)? (STDERR)
W20150709-13:00:15.384(5.5)? (STDERR) C:\Users\Abhishek\AppData\Local\.meteor\pa
ckages\npm-node-aes-gcm\0.1.3_6\npm\node_modules\node-aes-gcm\build\Release\node
_aes_gcm.node
W20150709-13:00:15.384(5.5)? (STDERR)     at Module.load (module.js:356:32)
W20150709-13:00:15.384(5.5)? (STDERR)     at Function.Module._load (module.js:31
2:12)
W20150709-13:00:15.385(5.5)? (STDERR)     at Module.require (module.js:364:17)
W20150709-13:00:15.385(5.5)? (STDERR)     at require (module.js:380:17)
W20150709-13:00:15.385(5.5)? (STDERR)     at Object.Npm.require (C:\Users\Abhish
ek\Desktop\reaction\.meteor\local\build\programs\server\boot.js:142:18)
W20150709-13:00:15.385(5.5)? (STDERR)     at Package (packages/npm-node-aes-gcm/
wrapper.js:2:1)
W20150709-13:00:15.386(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:33:4
W20150709-13:00:15.386(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:42:3
W20150709-13:00:15.386(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\boot.js:222:10
W20150709-13:00:15.387(5.5)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8
W20150709-13:00:38.038(5.5)? (STDERR)
W20150709-13:00:38.038(5.5)? (STDERR) C:\Users\Abhishek\AppData\Local\.meteor\pa
ckages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules
\fibers\future.js:245
W20150709-13:00:38.039(5.5)? (STDERR)
throw(ex);
W20150709-13:00:38.039(5.5)? (STDERR)
      ^
W20150709-13:00:38.039(5.5)? (STDERR) Error: %1 is not a valid Win32 application
.
W20150709-13:00:38.039(5.5)? (STDERR)
W20150709-13:00:38.039(5.5)? (STDERR) C:\Users\Abhishek\AppData\Local\.meteor\pa
ckages\npm-node-aes-gcm\0.1.3_6\npm\node_modules\node-aes-gcm\build\Release\node
_aes_gcm.node
W20150709-13:00:38.039(5.5)? (STDERR)     at Module.load (module.js:356:32)
W20150709-13:00:38.040(5.5)? (STDERR)     at Function.Module._load (module.js:31
2:12)
W20150709-13:00:38.040(5.5)? (STDERR)     at Module.require (module.js:364:17)
W20150709-13:00:38.040(5.5)? (STDERR)     at require (module.js:380:17)
W20150709-13:00:38.040(5.5)? (STDERR)     at Object.Npm.require (C:\Users\Abhish
ek\Desktop\reaction\.meteor\local\build\programs\server\boot.js:142:18)
W20150709-13:00:38.041(5.5)? (STDERR)     at Package (packages/npm-node-aes-gcm/
wrapper.js:2:1)
W20150709-13:00:38.041(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:33:4
W20150709-13:00:38.041(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:42:3
W20150709-13:00:38.041(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\boot.js:222:10
W20150709-13:00:38.041(5.5)? (STDERR)     at Array.forEach (native)
W20150709-13:00:49.535(5.5)? (STDERR) C:\Users\Abhishek\AppData\Local\.meteor\pa
ckages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules
\fibers\future.js:245
W20150709-13:00:49.535(5.5)? (STDERR)
W20150709-13:00:49.535(5.5)? (STDERR)
throw(ex);
W20150709-13:00:49.536(5.5)? (STDERR)
      ^
W20150709-13:00:49.536(5.5)? (STDERR) Error: %1 is not a valid Win32 application
.
W20150709-13:00:49.536(5.5)? (STDERR)
W20150709-13:00:49.536(5.5)? (STDERR) C:\Users\Abhishek\AppData\Local\.meteor\pa
ckages\npm-node-aes-gcm\0.1.3_6\npm\node_modules\node-aes-gcm\build\Release\node
_aes_gcm.node
W20150709-13:00:49.536(5.5)? (STDERR)     at Module.load (module.js:356:32)
W20150709-13:00:49.536(5.5)? (STDERR)     at Function.Module._load (module.js:31
2:12)
W20150709-13:00:49.537(5.5)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20150709-13:00:49.537(5.5)? (STDERR)     at require (module.js:380:17)
W20150709-13:00:49.537(5.5)? (STDERR)     at Object.Npm.require (C:\Users\Abhish
ek\Desktop\reaction\.meteor\local\build\programs\server\boot.js:142:18)
W20150709-13:00:49.537(5.5)? (STDERR)     at Package (packages/npm-node-aes-gcm/
wrapper.js:2:1)
W20150709-13:00:49.537(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:33:4
W20150709-13:00:49.537(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:42:3
W20150709-13:00:49.538(5.5)? (STDERR)     at C:\Users\Abhishek\Desktop\reaction\
.meteor\local\build\programs\server\boot.js:222:10
W20150709-13:00:49.538(5.5)? (STDERR)     at Array.forEach (native)

**Comment by aaronjudd** [comment]
Tracking in https://github.com/reactioncommerce/reaction/issues/363
