### ISSUE TITLE
Accessability review

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#405]
A thorough review of accessibility implementation (which is currently partial at best). 
A good start might be:
http://a11yproject.com/checklist.html

**Comment by vinh3928** [comment]
I might be interested in doing this as I am exploring the code base. Can you elaborate more on what you are looking for with this issue?

**Comment by aaronjudd** [comment]
What had I had in mind was just general run through of the important nav, forms, sectional elements and ensure they have role and aria properties.  See: http://w3c.github.io/aria-in-html/

I was trying to find a good intro doc, this might be helpful http://learn.shayhowe.com/advanced-html-css/semantics-accessibility/

We're in the process of making quite a few UI updates, which is one reason this is in a backlog right now, but this does needs some focus as the implementation has been a little haphazard.

**Comment by minimart** [comment]
I would be very interested in continuing work on this issue! 😃 

There is a very nice Chrome plugin called [aXe](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US) that we have been using for a while now that seems to do a pretty thorough job of finding violations.

 Would listing out each violation as a separate issue and PR be the best way to go about starting to make these changes? Or would keeping them all within this issue be better for the project?

**Comment by aaronjudd** [comment]
@mikemurray can you review as part of your Aria review, close this when done #3574 #3582, and create new issues for remaining tasks.

**Comment by mikemurray** [comment]
@aaronjudd will do

**Comment by mikemurray** [comment]
Closed by https://github.com/reactioncommerce/reaction/pull/3582 and additional tickets https://github.com/reactioncommerce/reaction/issues/3623 https://github.com/reactioncommerce/reaction/issues/2040
