### ISSUE TITLE
Convert `example-payment-plugin` to an NPM package 

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4055]
This is a pilot project for converting all non-core packages to npm packages. The goals would be:

1. A stand-alone npm package that has the exact same user-facing functionality as the existing plugin
1. Create a pattern can be used to convert other packages to NPM packages including any documentation explaining what needs to be done.
1. Add functionality to allow this plugin to support refunds
1. Convert with a look towards a "post-Meteor" world, eliminating any unnecessary Meteor dependencies, etc.
1. To the extent feasible, clean up any code so that this could be used as example of "best practices".
1. Create a repo that would stand as a template for other packages. Coordinate with @ticean  to see how this can be incorporated into the generator so that this is always standardized.
1. Update all appropriate documentation for how to create plugins/payment plugin tutorial
1. Give a talk/demo at a community call

My thinking is that this plugin would remain in the core project so that you can checkout "out of the box" and the other optional packages would be completely removed.

**Comment by zenweasel** [comment]
This plugin should also support marketplace/multishop so you don't need Stripe to be able to test/use marketplace.

**Comment by jshimko** [comment]
Initial work for this has started over at https://github.com/reactioncommerce/example-payments-plugin

And we need to have a bit more discussion about how API's will be structured.  See https://github.com/reactioncommerce/example-payments-plugin/issues/1

**Comment by spencern** [comment]
@zenweasel Any idea what the progress is on this ticket? Should we close it?

**Comment by zenweasel** [comment]
@spencern No, no progress. Closing. Thanks for checking.
