### ISSUE TITLE
Product Variant Scheme Extension Not Recognised Editing VariantForm.js

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4056]
## Issue Description
When trying to edit the extended productVariant field, using a new option created in variantForm.js nothing happens. However, if you manually extend the schema in lib/collections/schemas/products it works. 

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. **Extend productVariant Schema** 

i.e. 
```
export const ExtendedProductVariantSchema = ProductVariant.clone().extend({ "lotCode": { optional: true, type: String, defaultValue: "Not Supplied",    max: 30});
Products.attachSchema(ExtendedProductVariantSchema, { replace: true, selector: { type: "variant" } });
registerSchema("ProductVariant", ExtendedProductVariantSchema); }
```

2. **Add field in variantForm.js**

i.e.
```
                 <Components.TextField
                  i18nKeyLabel="productVariant.lotCode"
                  i18nKeyPlaceholder="productVariant.lotCode"
                  placeholder="lotCode"
                  label="Lot Code"
                  name="lotCode"
                  ref="lotCodeInput"
                  value={this.variant.lotCode}
                  onBlur={this.handleFieldBlur}
                  onChange={this.handleFieldChange}
                  onReturnKeyDown={this.handleFieldBlur}
                  validation={this.props.validation}
                />
```

3. **Run and see if you can edit**

I cannot 👎 

4. **Manually copy field into productVariant Schema**

Copy the field into productVariant in lib/collections/schemas/products

Now try and edit the field - I can 👍 

## Possible Solution

This has been an issue since 1.6 for me. I think it is due to an issue with how the schema is validated in variantFormContainer. However, no error is thrown.

I'm getting v. close to production so don't have time to dig into this. However, I thought you would like to take a look. It's not urgent, just annoying.

### Versions
Node: 8.9.0
NPM: 5.7.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.9.0
Reaction branch: 1.9-update
Docker: 17.12.0-ce

**Comment by zenweasel** [comment]
@willmoss1000 Do you have a sample repo or something where we can reproduce this?

**Comment by willmoss1000** [comment]
@zenweasel unfortunately it's private. I'll make a public one with just these amendments, and notify you here when it's up and reproduced.

**Comment by aldeed** [comment]
Will not be fixed in 1.x and no longer an issue in current release
