### ISSUE TITLE
Default variant selected is out of order if variants have been rearranged

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4059]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
When browsing the PDP of a product that has multiple variants, when the list of variants has been rearranged at some point, the default selected variant will be the first variant that was created, rather than the variant at the top of the list.

<img src="http://recordit.co/ZG6XmBTHv7.gif">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. As an admin: create a product with multiple variants. Drag the 2nd variant created into the first position on the variants list. Publish product
2.  As a customer browse the PDP for this product by clicking the product from the grid
3. Observe that the selected variant is not the variant at the top of the list, but the variant that was created first instead.

## Possible Solution
I think this is due to the way that we identify what the default variant is. Right now, that doesn't seem to be based on any positional data, but instead just whichever variant is returned first from the db.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.9.0
Reaction branch: master
Docker: 17.12.0-ce
```

**Comment by kieckhafer** [comment]
@spencern I don't believe this is relevant anymore, at least not in this repo. Can we close, or move to `example-storefront` if it's still an issue?
