### ISSUE TITLE
Order link in PDF receipt is broken

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4060]
## Issue Description
The ID displayed is correct but the link points to entirely different ID which of course doesn't work.

## Steps to Reproduce
1. Place an order
1. Approve/Capture and ship the order
1. View the "Print Invoice" screen
1. Click on the link for the Order
1. Observe you get a 404

## Possible Solution
The link just needs to use the same ID as the display

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: release-1.10.0
Docker: 17.12.0-ce
```

**Comment by ajporlante** [comment]
I can't see the order link in the invoice screen. Can you kindly provide a screenshot where the link is?

**Comment by zenweasel** [comment]
![2018-05-31_10-34-53](https://user-images.githubusercontent.com/72819/40758138-69655344-64be-11e8-915d-772f2924b24f.png)

**Comment by ajporlante** [comment]
The link for the order in the invoice screen is no longer there since the screen only intends to allow printing of the invoice.
