### ISSUE TITLE
Re-Sending Failed Email

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/reaction#4061]
## Issue Description
If the mail settings are incorrect and you send a marketplace invite; you cannot then fix the mail settings and re-send the invite to the same email address because the "re-send" uses the same original SMTP credentials used when the mail settings were incorrect. 

## Steps to Reproduce
1. Login as store admin and put dummy (invalid) data in the mail settings.
2. send a marketplace invite to xyz@xyz.com
3. Goto mail settings logs to verify that the email failed to be sent.
4. Then fix the mail settings to valid settings.
5. Then try to invite the same email address as a marketplace seller.  You will not be able to.
6. From the mail settings and logs area, try to re-send the failed email.  You will not be able to.

## Possible Solution
When re-sending failed emails edit the record to leverage the new / updated mail settings.  This fix might positively impact other use cases too where the email failed to be sent and that same email needs to be re-sent.  

### Versions
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0

**Comment by aldeed** [comment]
No longer an issue due to marketplace being removed
