### ISSUE TITLE
Task: Cleanup unused `enabled` property in plugins

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#4064]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
Each plugin has a property called `enabled`. This boolean originally was intended to control, if the plugin's setting form was displayed in the admin dashboard. It seems that this is no longer the case, i.e. the plugin is visible regardless of the state of this boolean property. This was tested with tax plugins (taxes-taxcloud, taxes-avalara) as well as with payment plugins (e.g. reaction-stripe).

Also this property would presumably be obsolete when we start to move individual plugins to NPM, because then the installation would be controlled through NPM itself.

This issue proposes to eliminate the property altogether, because it seems not to be used anyway right now.

![robo_3t_-_1_1](https://user-images.githubusercontent.com/1733229/37899510-fb3a904c-30eb-11e8-914a-b8d325b0cd81.jpg)

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.10.0
Reaction branch: master
Docker: 17.03.1-ce

**Comment by aldeed** [comment]
Done in 3.0
