### ISSUE TITLE
How can I add a payment gateway support?

### ISSUE THREAD

**Issue by dheerajbhaskar** [reactioncommerce/reaction#407]
## Problem
I'm from India and the payment gateways that you support don't work in India. The mentioned PGs(Payment Gateways):
1.  reactioncommerce:­reaction-braintree : Reaction Braintree - Braintree payments for Reaction Commerce
2. reactioncommerce:­reaction-stripe : Stripe payments for Reaction Commerce
3. reactioncommerce:­reaction-auth-net : Reaction Authorize.net - Authorize.net payments for Reaction Commerce
4. reactioncommerce:­reaction-paypal : Paypal

## Possible Solutions
I'm guessing one can modify existing PG packages to support a new. Please let me know easy/difficult this is for an intermediate level Meteor programmer who hasn't made packages before.

## Here are the PGs popular in India:
We already have subscribed to [**Atom**](http://www.atomtech.in/index.html) PG, so we'd be very inclined to get Atom working. Here are other popular gateways. Getting any of them them work is also a start (I guess):
1.  [Atom](http://www.atomtech.in/index.html)
2.  [CCAvenue](http://www.ccavenue.com/ccavenue_index.jsp)
3.  [Citrus](http://www.citruspay.com/index.html)
4.  [DirecPay](http://www.direcpay.com/direcpay/home.jsp)
5.  [EBS](http://www.ebs.in/en/)

Please let me know if I can create a package myself or is it better to wait till the community to develop these packages. BTW this is for a potential client. We'll be losing him if we don't do a PG integration.

Early responses would be appreciated

**Comment by dheerajbhaskar** [comment]
http://citruspay.com/ seems to offer nodejs support and also a checkout.js hosted checkout page like stripe. Will this help with an easier integration?

Why can't I call the checkout.js trigger method in the payment button in reaction commerce?

**Comment by abhisheksoni27** [comment]
Why cant Braintree work in India? Or PayPal? In the end you only want the a credit/debit card APi and checkout, and you can handl COD yourself. Why cant BrainTree be configured? They dont have location specific apis, I suppose.

**Comment by abhisheksoni27** [comment]
You might want to look at [paytm](//paytm.com). They have nodejs support.

**Comment by spencern** [comment]
I'd recommend looking through the existing payment gateway packages. They aren't too complicated, and you should be able to start by cloning the stripe or paypal package and modifying it to support one of your preferred payment gateways.

**Comment by dheerajbhaskar** [comment]
Thanks for your replies Abhishek and Spencer.

Braintree: Please note that they've not mentioned India in
https://www.braintreepayments.com/country-selection . Is there a different
resource which says they work with India?

Paypal: Fees are on the higher side at 4.4% + 20 rupees (30 cents) per
transaction.

Credit/debit card and Net banking are popular modes of payment. Is net
banking difficult to support?

Paytm: I spent quite some time figuring our their pricing. I couldn't find
it anywhere. Details are very sparse.

I shall indeed look through the existing payment packages to port them to a
different gateway.

**Comment by Gouthamve** [comment]
Just a little something to note:

Netbanking and most payment gateways in India require that the user be redirected to another page. I think you will find that implementation in one of Paypal's methods (I think express checkout). There is an open issue reactioncommerce/reaction-paypal#11 with that implementation.

Also being from India, I would love to help you with the payment gateway support, are you active on Gitter?

**Comment by dheerajbhaskar** [comment]
Hey Goutham, thanks for tip and the generous offer.

I just joined gitter for this. Let's figure this out.
I'm also waiting for our client to get back.

**Comment by abhisheksoni27** [comment]
I'd also like to contribute to this. Gitter URL?

**Comment by Gouthamve** [comment]
Actually, we were discussing this in private chat. But I now created a room on gitter: https://gitter.im/Gouthamve/indian-pg

**Comment by dheerajbhaskar** [comment]
Thanks Abhishek for stepping forward. I'm guessing Goutham has already
added you on gitter.

**Comment by HarshaVardhanPVK** [comment]
Hi Dheeraj did you get any clue for Payment Gateway support in India

**Comment by Gouthamve** [comment]
Hi @HarshaVardhanPVK,

I developed this package which currently works with razorpay: https://github.com/Gouthamve/reaction-razorpay.

**Comment by HarshaVardhanPVK** [comment]
Thank you Goutham for your quick replay, I will try to use it.

**Comment by dheerajbhaskar** [comment]
Yes Goutham's package should help :)

**Comment by HarshaVardhanPVK** [comment]
Hope so, thank you guys.

**Comment by chrisenytc** [comment]
I think is a better choice create a project like ActiveMerchant to create a interface to add any gateway ou payment service. I work in a payment service provider based on Brazil and I am interesting in contribute with this project. :+1:

**Comment by zenweasel** [comment]
I am adding this comment so that anyone searching for information on creating a payment package it can find it.

RC has added the package https://github.com/reactioncommerce/reaction-paymentmethod. This is a complete boilerplate and well as instructions for creating a payment-method package. For most server-side methods you should be able to just plug in your third-party module and go. Please feel free to contact me should you have any questions/concern/issues/complaints about this module. Or suggestions for making creating payment method packages easier.

**Comment by dheerajbhaskar** [comment]
Thanks for this Brent.

On Mon 18 Jan, 2016 11:04 am Brent Hoover <notifications@github.com> wrote:

> I am adding this comment so that anyone searching for information on
> creating a payment package it can find it.
>
> RC has added the package
> https://github.com/reactioncommerce/reaction-paymentmethod. This is a
> complete boilerplate and well as instructions for creating a payment-method
> package. For most server-side methods you should be able to just plug in
> your third-party module and go. Please feel free to contact me should you
> have any questions/concern/issues/complaints about this module. Or
> suggestions for making creating payment method packages easier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactioncommerce/reaction/issues/407#issuecomment-172430382>
> .
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---

**Comment by tomyo** [comment]
Hi, the link for payment method is broken, where can I find that info?
Thanks a lot!

**Comment by zenweasel** [comment]
That package is now included with RC. You can find the tutorial on writing a Payment Package here: https://docs.reactioncommerce.com/reaction-docs/master/creating-a-payment-provider

**Comment by hrath2015** [comment]
There is lot changed... you can refer the docs here
https://docs.reactioncommerce.com/reaction-docs/master/reaction-payments
