### ISSUE TITLE
Port & Convert "Bulk Product Importer" to an NPM package

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/reaction#4070]
## Issue Description
The current reaction-product-importer needs to be ported from its current state into our latest version.  https://github.com/getoutfitted/reaction-product-importer/blob/development/README.md

# reaction-product-importer
Product Importer allows you to bulk upload products from a CSV file. Each CSV requires a column called ProductId that groups variants together. Then you make the second level variant with whatever you want and the third variant with whatever you want. You can also control the mapping from one column to a corresponding DB field, or name your columns to correspond

Here's an example of what basic csv import file could look like

| productId | topProductType | productTitle           | pageTitle                                          | vendor               | handle          | variantTitle          | variantType | title                | optionTitle | price | qty | weight | taxable | hastags               | metatags                           | description                                                                        |
|-----------|----------------|------------------------|----------------------------------------------------|----------------------|-----------------|-----------------------|-------------|----------------------|-------------|-------|-----|--------|---------|-----------------------|------------------------------------|------------------------------------------------------------------------------------|
| 1         | simple         | Basic Reaction Product | This is a basic product. You can do a lot with it. | Example Manufacturer | example-product | Basic Example Variant | variant     | Option 1 - Red Dwarf | Red         | 19.99 | 19  | 35     | true    | Hashtags, Womens, Red | Material=Cotten, Quality=Excellent | Sign in as administrator to edit.You can clone this product from the product grid. |

### Custom Product Fields
Product Importer supports the importing of your custom fields, you just need to help us map them out. You need to tell us what the column name is, what the field name is on your products, what type of value you are inserting and finally where to put this (top level product, grouping variant or bottom variant)

![image](https://cloud.githubusercontent.com/assets/1203639/14441445/04ff190e-fff2-11e5-9fef-b4c273e44ad9.png)

### What kind of fields does Product Importer support?
- top level - there are certain fields that only apply to top level products (topProductType, pageTitle, handle, hastags, metafields, description) these need to be on the first of each product but can be filled out for each item.
- hashtags - each hashtag (tag) need to be separated by a ,
- metafields - each key value pair need to be separated by , and each key needs to be separated from value by =
- Custom Arrays - can be split by whatever symbol you enter into the delimiting field
- Custom Objects - can be delimited by any field but key values must be separated by =

_**Note:**_ Any custom field you have must be supported by your product schema or it will not import.

Here's an example of what a more complex csv import file would look like - _custom fields have *italicized* headers_

| productId | *topProductFunctionalType* | topProductType | variantType | *variantFunctionalType* | productTitle        | pageTitle                                        | vendor    | handle              | *variantTitle* | *title*       | optionTitle       | price | qty | weight | taxable | hastags                           | metatags                                             | description       | *productType* | *location* | *colors*               | *gender* | *cleaningBuffer* |
|-----------|----------------------------|----------------|-------------|-------------------------|---------------------|--------------------------------------------------|-----------|---------------------|----------------|---------------|-------------------|-------|-----|--------|---------|-----------------------------------|------------------------------------------------------|-------------------|---------------|------------|------------------------|----------|------------------|
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Small          | Light Acai    | Color-Acai        | 19.99 | 2   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Medium         | Light Acai    | Color-Acai        | 20    | 6   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Large          | Light Acai    | Color-Acai        | 25    | 8   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Extra Large    | Light Acai    | Color-Acai        | 30    | 2   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Small          | Ultramarine   | Color-Marine      | 19.99 | 2   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Medium         | Ultramarine   | Color-Marine      | 20    | 6   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Large          | Ultramarine   | Color-Marine      | 25    | 8   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 1         | rental                     | simple         | variant     | rentalVariant           | 3 in 1              | Womens Patagonia 3-in-1                          | Patagonia | patagonia-3-in-1    | Extra Large    | Ultramarine   | Color-Marine      | 30    | 2   | 35     | TRUE    | Jacket, Winter                    | included=functional pockets                          |ProductDescription | Jacket        | A1         | Acai,Marine            | Womens   | 0                |
| 2         | rental                     | simple         | variant     | rentalVariant           | Snowbelle           | Womens Patagonia Snowbelle                       | Patagonia | patagonia-snowbelle | Small          | Black         | Color-Black       | 20    | 6   | 35     | TRUE    | Pants, Winter                     | included=functional pockets                          |ProductDescription | Pants         | B2         | Black                  | Womens   | 0                |
| 2         | rental                     | simple         | variant     | rentalVariant           | Snowbelle           | Womens Patagonia Snowbelle                       | Patagonia | patagonia-snowbelle | Medium         | Black         | Color-Black       | 25    | 13  | 35     | TRUE    | Pants, Winter                     | included=functional pockets                          |ProductDescription | Pants         | B2         | Black                  | Womens   | 0                |
| 2         | rental                     | simple         | variant     | rentalVariant           | Snowbelle           | Womens Patagonia Snowbelle                       | Patagonia | patagonia-snowbelle | Large          | Black         | Color-Black       | 25    | 13  | 35     | TRUE    | Pants, Winter                     | included=functional pockets                          |ProductDescription | Pants         | B2         | Black                  | Womens   | 0                |
| 2         | rental                     | simple         | variant     | rentalVariant           | Snowbelle           | Womens Patagonia Snowbelle                       | Patagonia | patagonia-snowbelle | Extra Large    | Black         | Color-Black       | 35    | 5   | 35     | TRUE    | Pants, Winter                     | included=functional pockets                          |ProductDescription | Pants         | B2         | Black                  | Womens   | 0                |

**Comment by vwadher** [comment]
@zenweasel May be worth reviewing how they did it https://github.com/reactionimp/import-tool?files=1

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/solutions-engineering-tasks #10](https://github.com/reactioncommerce/solutions-engineering-tasks/issues/10) via [**ZenHub**](https://www.zenhub.com/)
