### ISSUE TITLE
Product changes are immediately displayed in PDP without "publish" process

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#4074]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
**Notice** This issue only occurs if `Product Revisions` are turned off

Any field changes in admin-PDP are immediately visible for all non-admin users. This renders the "Publish" button useless.

## Steps to Reproduce

1. As an admin, turn-off Revision control.
2. Open an incognito window and navigate to the example product's PDP
3. As an admin, navigate to the admin-PDP of the example product and change values there
4. See that the values in the incognito window are updating immediately.

## Possible Solution
This happens, because the non-admin PDP page is not using the Catalog collection for data retrieval. Once this is implemented, this issue should be addressed implicitly.

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.10.0
Reaction branch: master
Docker: 17.03.1-ce

**Comment by spencern** [comment]
closed in favor of #4319
