### ISSUE TITLE
Attach roles / permissions to each shop

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#4075]
## Issue Description
Currently, `roles`/`permissions` are all stored inside the `roles` database, with only an `id` and `name` field. They are not attached to a shop.

To determine what `roles`/`permissions` are on each shop, we use [this helper function](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/accounts/client/helpers/accountsHelper.js#L87) to populate the data.

This issue seeks to expand on the above function by using it to save the `roles`/`permissions` onto each `Shop` as well, for easier availability.

## Possible Solution
- Whenever a package is inserted or updated, we can run a modified version of the  [above mentioned function](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/accounts/client/helpers/accountsHelper.js#L87) and set `shop.permissions` on the shop for that package.
- `roles`/`permissions` would then be available by querying `Shops.findOne(shopId).permissions`

**Comment by aldeed** [comment]
This permission system is being removed for 3.0 so this will not be fixed
