### ISSUE TITLE
Receive error in Orders dashboard when using dollar discount codes

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4079]
## Issue Description
The Order dashboard is trying to treat Discounts like other payment methods (which technically it is) and call `refund/list` on it, but of course that doesn't exist. Get this error on the client side. Related to #4078 but a different part of the code.

```

{message: "Method 'code/refund/list' not found [404]", name: "Error", stack: "Error: Method 'code/refund/list' not found [404]↵ …7063aa833005aff7419b3f8c222e877582f1a3e0:2044:15)", code: undefined, signal: undefined}
hostname
```

## Steps to Reproduce
1. Login as admin
1. Go the Payments/Codes dashboard
1. Add a new discount code with the discount method "credit" and the code to be "DOLLAROFF" and the amount to 1.
1. Add to cart and apply this discount when checking out
1. Go to the order dashboard and select that order
1. Observe the errors in the console

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: master
Docker: 18.03.0-ce
```

**Comment by zenweasel** [comment]
Also after capturing order, see this problem with totals display:

![2018-03-28_13-37-59](https://user-images.githubusercontent.com/72819/38010820-443cb8ae-328d-11e8-94aa-440d6396b451.png)

**Comment by prinzdezibel** [comment]
This happens on my side only if I add the property `shopId` to the discount billing record.
Normally billing records would feature a `shopId` property, but not the discount record, though. Which looks to me like an error, because in a marketplace setup, the shopId should be specified.

**Comment by aldeed** [comment]
Fixed
