### ISSUE TITLE
Error meteor build

### ISSUE THREAD

**Issue by Cogiva** [reactioncommerce/reaction#408]
Having an issue running the build with meteor.  I pulled the latest repo from GitHub and ran with the 'meteor' command.  Got this error...

    I20150713-14:17:08.665(1)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
    W20150713-14:17:11.768(1)? (STDERR)
    W20150713-14:17:11.768(1)? (STDERR)         throw er; // Unhandled 'error' event
    W20150713-14:17:11.768(1)? (STDERR) events.js:72
    W20150713-14:17:11.768(1)? (STDERR)               ^
    W20150713-14:17:11.768(1)? (STDERR) Error: spawn ENOENT
    W20150713-14:17:11.769(1)? (STDERR)   at errnoException (child_process.js:1011:11)
    W20150713-14:17:11.769(1)? (STDERR)   at Process.ChildProcess._handle.onexit (child_process.js:802:34)
    W20150713-14:17:11.769(1)? (STDERR)
    => Exited with code: 8

Any ideas why it wouldn't build out of the box?

**Comment by spencern** [comment]
Which repo/branch did you pull?

**Comment by Cogiva** [comment]
https://github.com/reactioncommerce/reactions git master.

**Comment by Cogiva** [comment]
Sorry that should be https://github.com/reactioncommerce/reaction.git master (auto correct!)

**Comment by aaronjudd** [comment]
@Cogiva are you trying to run on Windows?  If so, see: https://github.com/reactioncommerce/reaction/issues/363

**Comment by Cogiva** [comment]
Yup. Darn Microsoft! ;-) Thanks.

**Comment by aaronjudd** [comment]
Closing, we'll just continue in #363
