### ISSUE TITLE
Search modal can't be opened

### ISSUE THREAD

**Issue by galpe** [reactioncommerce/reaction#4084]
## Issue Description
I created a new project with the 1.10 Reaction's version and the search modal can't be open now. It's important to say I'm using swag plugin.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Click on the search button in the navbar
2.Modal is not opened

### Versions
1.10

**Comment by zenweasel** [comment]
Hey @galpe. This might be something with the Swag Shop plugin as I have no problem opening the search modal in a stock reaction.

![2018-03-28_20-43-46](https://user-images.githubusercontent.com/72819/38029568-c2154008-32c8-11e8-97dc-541dd07165be.png)

**Comment by galpe** [comment]
Hey @zenweasel  I see... Do you think we should open it to the swag-project?
