### ISSUE TITLE
Is multi-vendor marketplace implementation ready with Reaction Commerce?

### ISSUE THREAD

**Issue by afour-deepakn** [reactioncommerce/reaction#4085]
Hi there,
I want to build a complete multivendor marketplace using Reaction Commerce.Is it feasible to do the same?.Please help me on this.

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but a general support question. We would be glad to help you with this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).

**Comment by afour-deepakn** [comment]
Thanks **zenweasel** .We will continue the discussion on the chat channel
