### ISSUE TITLE
Products created in one shop showing up in all shops

### ISSUE THREAD

**Issue by kathiresh-i2i** [reactioncommerce/reaction#4092]
## Issue Description
This issue only applies to a marketplace setup.

As a merchant admin, the product grid shows all products available. That is, you can see products from other merchants as well as the marketplace owner's products. You can't edit them though, so there's no direct security issue arising through this bug.

As a user, only those products that belong to the appropriate shop are displayed, which is the expected behaviour, IMHO.
E.g.
- <http://localhost:3000> shows all products from all merchants
- <http://localhost:3000/shop/merchant1> shows all products from merchant 1
- <http://localhost:3000/shop/merchant2> shows all products from merchant 2

## Steps to Reproduce
1. As marketplace owner, enable marketplace and create a product
2. Invite two merchants: merchant1 and merchant2
3. As merchant1 admin, create product
4. Observe that the logged-in merchant 2 can see products from marketplace owner and merchant 1

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: master
Docker: 17.03.1-ce

**Comment by willmoss1000** [comment]
I've notice this too. Seems to be that this section of code is not functioning: https://github.com/reactioncommerce/reaction/blob/138b9e84253c3d991327bd98dfbe9dffa89cf7d3/server/publications/collections/products.js#L141-L150

I put a logger either side, and they give the following outputs when viewing the customer grid on the reaction shop page.

Top logger gives: ` [ 'reaction' ] 'shopIdsOrSlugs'`
Bottom logger gives `[] 'shopIds'`

```
 Logger.info(shopIdsOrSlugs, "shopIdsOrSlugs");

  if (shopIdsOrSlugs) {
    // Get all shopIds associated with the slug or Id
    const shopIds = Shops.find({
      "workflow.status": "active",
      "$or": [{
        _id: { $in: shopIdsOrSlugs }
      }, {
        slug: { $in: shopIdsOrSlugs }
      }]
    }).map((shop) => shop._id);

    Logger.info(shopIds, "shopIds");
```

**Comment by kathiresh-i2i** [comment]
# **Issue Description and resolution**

### Products created in one shop showing up in all shops.

1) Logged in to 'Testshop1' as 'Testuser1' 

2) Created a product called 'Created on 'test shop 1' in 'Testshop 1'


![1](https://user-images.githubusercontent.com/6792204/38193419-9e86d2ee-368f-11e8-9603-11899fa01610.png)


![2](https://user-images.githubusercontent.com/6792204/38193424-a8d1ef9a-368f-11e8-98cd-f6c318099ba4.png)

​

3) Logged out 

4) Logged in as 'Testuser2' and was automatically redirected to 'Testshop2'

5) The product 'Created on test shop 1' was still visible in 'Testshop2'



​

![3](https://user-images.githubusercontent.com/6792204/38193434-b0af9762-368f-11e8-90f0-ecc500f4b84e.png)
## Changes:

## Filepath:
 imports/plugins/included/productvariant/containers/productsContainer.js

## Line No: 109
```
// const shopIdOrSlug = Reaction.Router.getParam("shopSlug"); // Commend this line replace with below code
const shopIdOrSlug = Reaction.getShopId(); 

```
After this change was made products were only visible in the stores they were created in.

@prinzdezibel is this solution valid?

**Comment by zenweasel** [comment]
@spencern Just want to verify that this is the expected behavior:

http://localhost:3000 shows all products from all merchants
http://localhost:3000/shop/merchant1 shows all products from merchant 1
http://localhost:3000/shop/merchant2 shows all products from merchant 2

**Comment by spencern** [comment]
That's how it's been designed to this point

**Comment by zenweasel** [comment]
@nithin-ideas2it I think you have misunderstood Spencer's comment. He is agreeing that the current implementation (assuming that this bug is reported correctly) is incorrect and needs to be fixed.

**Comment by nithin-ideas2it** [comment]
@zenweasel Sorry I thought to know the multi-tenant structure after the fix so that we can change few things on our side. Let us wait for the update. Thank you.

**Comment by spencern** [comment]
@nithin-ideas2it I think this is a legitimate bug in our marketplace product publication or subscription code likely and I'd look at a PR that identifies what the problem was and provides a good solution.

I think your proposed fix on line 109 is not ideal because it appears to remove the product filter from the URL and to hard-code it to the active shop.

I'd also look at a PR that creates a method to toggle this behavior on/off from the operator interface if this is the functionality that your multi-tenant marketplace needs, though I'd want to understand the use-case better.

@pmn4 I think you've been working on a multi-tenant marketplace, have you experienced similar issues with products showing up in grids that they aren't supposed to? Any other solutions come to mind?

**Comment by spencern** [comment]
I hadn't noticed that this was a client-side check. That's a good catch, the general rule should be that the client should never be sent data it doesn't need or shouldn't have and that those filters should take place in the database ideally, or on the server.
