### ISSUE TITLE
Unable to update reaction commerce to latest version

### ISSUE THREAD

**Issue by kathiresh-i2i** [reactioncommerce/reaction#4093]
How to update reaction commerce to latest version 
**reaction pull** is not updating the version

**Comment by prinzdezibel** [comment]
This does only work with a single remote. You can always use the bare metal git commands to update. What does `git remote -v` give you?
Normally `git pull origin master` should do the trick.

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but a support request. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).

**Comment by zenweasel** [comment]
Probably the documentation for `reaction pull` needs to be improved or we should just deprecate/remove that command.
