### ISSUE TITLE
Indian Payment Gateway

### ISSUE THREAD

**Issue by abhisheksoni27** [reactioncommerce/reaction#410]
Hey, @aaronjudd, Could you check this github repo: [reaction-razorpay](https://github.com/abhisheksoni27/reaction-razorpay), and tell how this can be integerated to one of the existing payment gateways?

It's just a js file, worth thirty lines of the code, but if you could provide the details as to which where whatis handled, it would be better.

Plus, knowing only js kills the coffee thing too.

**Comment by Gouthamve** [comment]
Hi,

As we spoke on Gitter, I am trying to to integrate this into Reaction here: https://github.com/Gouthamve/reaction-razorpay

Also I use http://js2.coffee for JS to Coffee conversion :smile:

**Comment by aaronjudd** [comment]
also - important note - you can use JS all you want in packages - no need at all to use Coffeescript.

**Comment by Gouthamve** [comment]
Done
do ```meteor add gouthamve:reaction-razorpay``` to get the package

**Comment by 1rohittiwari** [comment]
I get the following error when I try to add the pacakge:

meteor add gouthamve:reaction-razorpay
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_3.
Constraints on package "less":
* less@=2.5.0_3 <- top level
* less@2.5.0_1 <- reactioncommerce:core 0.9.2
* less@2.5.0_1 <- reactioncommerce:bootstrap-theme 1.7.0
* less@2.5.0_1 <- reactioncommerce:reaction-accounts 1.5.1
* less@2.5.0_1 <- reactioncommerce:reaction-shipping 0.6.1
* less@2.5.0_1 <- reactioncommerce:reaction-analytics 1.1.1
* less@2.5.0_1 <- reactioncommerce:reaction-social 0.4.1
* less@2.5.0_1 <- reactioncommerce:reaction-paypal 1.2.2
* less@2.5.0_1 <- reactioncommerce:reaction-stripe 3.0.1
* less@2.5.0_1 <- gouthamve:reaction-cod 1.2.0
* less@1.0.11 <- gouthamve:reaction-razorpay 1.0.0

**Comment by aaronjudd** [comment]
@Gouthamve looks like reaction-razorpay needs updating to Meteor 1.2

` less@1.0.11 <- gouthamve:reaction-razorpay 1.0.0`

**Comment by Gouthamve** [comment]
Yep. I did a version bump, but my package is broken. Hopefully will get time to fix it tomorrow.
