### ISSUE TITLE
How to access existing methods call like REST API?

### ISSUE THREAD

**Issue by nithin-ideas2it** [reactioncommerce/reaction#4108]
**How to access existing methods call like REST API?**

## Prerequisites
* [Y] Are you running the latest version?
* [Y] Are you able to consistently reproduce the issue?
* [Y] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

Refered: https://blog.reactioncommerce.com/our-take-on-rest-apis

We used 'simple:rest' to expose the APIs and also aware of https://github.com/kahmali/meteor-restivus.

We added new APIs, But How to use the existing exposed via 'simple:rest'?

http://localhost:3000/publications/api-routes

Ex.
```
{
  "_id": "/methods/shop/createTag",
  "methods": [
    "options",
    "post"
  ],
  "path": "/methods/shop/createTag"
}

```
server/methods/core/shop.js -> // LINE 607
```

  /**
   * @name shop/createTag
   * @method
   * @memberof Methods/Shop
   * @summary creates new tag
   * @param {String} tagName - new tag name
   * @param {Boolean} isTopLevel - if true -- new tag will be created on top of
   * tags tree
   * @since 0.14.0
   * @hooks after method
   * @return {String} with created tag _id
   */
  "shop/createTag"(tagName, isTopLevel) {
    check(tagName, String);
    check(isTopLevel, Boolean);
  ...
  }
```

Just would like to know, cant we call 'methods/shop/createTag' like REST API?

How to pass values through the request to get 'req.body' or 'req.param'?

Help us to achieve?

Or

**We need write our own logic to achieve this by implementing own API and need to call something like below?**

```
JsonRoutes.add('post', '/create/tag', function (req, res) {
  var tagName = req.body.tagName;
  const newTagId = Meteor.call("shop/createTag", tagName, false);
```

### Versions
Node: 6.11.0
NPM: 3.10.10
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: master

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but a question on how to use a third-party package.

We would be glad to answer your questions, provide you more help via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com). Closing this issue.
