### ISSUE TITLE
Dockerfile dies

### ISSUE THREAD

**Issue by faddat** [reactioncommerce/reaction#411]
Dockerfile dies as follows:

Removing intermediate container 9ec8b83536de
Step 20 : COPY . /usr/src/meteor
 ---> e345964d254a
Removing intermediate container 626317251b49
Step 21 : WORKDIR /usr/src/meteor/
 ---> Running in 0916cbea9909
 ---> ede36d13c7ef
Removing intermediate container 0916cbea9909
Step 22 : RUN bash /usr/bin/build-meteor.sh
 ---> Running in 3dc7c7a000d3
warning: less theme files not found!!
info: using development mode in an attempt to create missing files.

Docker v1.7
command used: docker build .

**Comment by aaronjudd** [comment]
it will take some time after this command appears "info: using development mode in an attempt to create missing files."  how long did you wait?  it's starting up a development version and compile meteor to create the missing *.less theme files.

**Comment by faddat** [comment]
must have been 10 minutes, but I just hit it again, and will wait longer.  
This time I followed this procedure:

We provide release images built from the master branch. These are the same images running on reactioncommerce.com. You can pull our latest build from the Docker Hub, or from the Reaction directory you can build your own Docker image:

docker build -t reactioncommerce/reaction-test.

Start a Docker/Reaction container using docker run:

docker run -p :8080 -it reactioncommerce/reaction-test

You can pass environment variables to Docker using -e, so to pass ROOT_URL you would do add -e ROOT_URL="<myhost>" to docker run.

Easy way to remove force-ssl for test builds:

git clone https://github.com/reactioncommerce/reaction.git
cd reaction
grep -v "force-ssl" .meteor/packages > .packages && mv .packages .meteor/packages
docker build -t ongoworks/reaction-test .
docker run -p :8080 -it ongoworks/reaction-test


From: https://github.com/reactioncommerce/reaction-core/blob/master/docs/deploying.md

Where can I find a script/what have you that builds the very bleeding edge for Docker?  Or is this that?
