### ISSUE TITLE
Create a way to fetch data for the tag navigation

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4118]
Working with the GraphQL API as defined and built out in #4104, create a navigation query component to fetch tag navigation data from our GraphQL API for the tag navigation.

User the `Query` component as described here: https://dev-blog.apollodata.com/introducing-react-apollo-2-1-c837cc23d926

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #10](https://github.com/reactioncommerce/reaction-next-starterkit/issues/10) via [**ZenHub**](https://www.zenhub.com/)
