### ISSUE TITLE
Product Grid Data Fetching

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4119]
Working with our Catalog Items GraphQL query as defined in #4105, create a query component to fetch data for the product grid.

Default pagination size: 24

This query component should work with the pagination ticket to load more/different data #4122 

Creating a query component: https://dev-blog.apollodata.com/introducing-react-apollo-2-1-c837cc23d926

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #11](https://github.com/reactioncommerce/reaction-next-starterkit/issues/11) via [**ZenHub**](https://www.zenhub.com/)
