### ISSUE TITLE
Product Grid Layout

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4120]
Create a product grid UI layout.

This layout should take into account the fact that grid items can have multiple sizes (currently small, medium, and large)

Small:
![image](https://user-images.githubusercontent.com/1203639/38231355-850bbb50-36cf-11e8-93f3-d361cc725c94.png)

Medium:
![image](https://user-images.githubusercontent.com/1203639/38231386-a34799ea-36cf-11e8-8618-0ea6e000eb24.png)

Large:
![image](https://user-images.githubusercontent.com/1203639/38231408-b2563324-36cf-11e8-8a3e-e909847ea4f7.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #12](https://github.com/reactioncommerce/reaction-next-starterkit/issues/12) via [**ZenHub**](https://www.zenhub.com/)
