### ISSUE TITLE
Product Grid Item

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4121]
Create a component to display a product grid item within the product grid layout. 

As mentioned in #4120 these items can have multiple sizes and this component should account for that.

Grid item should display inventory status badge appropriately:
- Low Inventory
- Sold Out
- Backordered

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #13](https://github.com/reactioncommerce/reaction-next-starterkit/issues/13) via [**ZenHub**](https://www.zenhub.com/)
