### ISSUE TITLE
Product Grid Document Head Meta Tags

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4124]
Add meta tags to the document head for the product grid.

The meta tags should update the meta-tag title, description, social tags (facebook og, twitter card) based on the information present in the grid such as which tag is currently being viewed.

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #16](https://github.com/reactioncommerce/reaction-next-starterkit/issues/16) via [**ZenHub**](https://www.zenhub.com/)
