### ISSUE TITLE
Product Detail Data Fetching

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4125]
Work with the GraphQL query for `catalogProduct` defined in #4106 to create a method to fetch the data for the product detail page.

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #17](https://github.com/reactioncommerce/reaction-next-starterkit/issues/17) via [**ZenHub**](https://www.zenhub.com/)
