### ISSUE TITLE
Product Detail Layout

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4126]
Create a layout for the product detail page

We currently have two layouts defined for the products, we should discuss how to keep PDP layouts extensible and customizable on a product-by-product basis.

![image](https://user-images.githubusercontent.com/1203639/38232202-42ff1546-36d3-11e8-872e-b4f5198dbd3b.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #18](https://github.com/reactioncommerce/reaction-next-starterkit/issues/18) via [**ZenHub**](https://www.zenhub.com/)
