### ISSUE TITLE
Product Detail Routing

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4127]
Implement routing for the Product Detail Page.

Example routes

`/products/:product-slug/`
`/:shop-slug/products/:product-slug`

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #19](https://github.com/reactioncommerce/reaction-next-starterkit/issues/19) via [**ZenHub**](https://www.zenhub.com/)
