### ISSUE TITLE
Product Detail Header

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4129]
Add the header to the product detail page within the product detail layout defined in #4126 

The header should include the `Title` and the `Page Title` of the product, where the `Page Title` appears as a subtitle.

![image](https://user-images.githubusercontent.com/1203639/38232868-e28514d8-36d5-11e8-8bd1-cf7cfed13d84.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #21](https://github.com/reactioncommerce/reaction-next-starterkit/issues/21) via [**ZenHub**](https://www.zenhub.com/)
