### ISSUE TITLE
EPIPE error when uploading image

### ISSUE THREAD

**Issue by abhisheksoni27** [reactioncommerce/reaction#413]
```
W20150716-17:12:10.251(5.5)? (STDERR)
W20150716-17:12:10.251(5.5)? (STDERR) events.js:72
W20150716-17:12:10.252(5.5)? (STDERR)         throw er; // Unhandled 'error' eve
nt
W20150716-17:12:10.252(5.5)? (STDERR) Error: write EPIPE
W20150716-17:12:10.252(5.5)? (STDERR)     at errnoException (net.js:905:11)
W20150716-17:12:10.252(5.5)? (STDERR)     at Socket._write (net.js:646:26)
W20150716-17:12:10.252(5.5)? (STDERR)     at doWrite (_stream_writable.js:226:10
)
W20150716-17:12:10.253(5.5)? (STDERR)     at writeOrBuffer (_stream_writable.js:
216:5)
W20150716-17:12:10.252(5.5)? (STDERR)               ^
W20150716-17:12:10.253(5.5)? (STDERR)     at Socket.Writable.write (_stream_writ
able.js:183:11)
W20150716-17:12:10.253(5.5)? (STDERR)     at Socket.write (net.js:616:40)
W20150716-17:12:10.253(5.5)? (STDERR)     at write (_stream_readable.js:602:24)
W20150716-17:12:10.253(5.5)? (STDERR)     at flow (_stream_readable.js:611:7)
W20150716-17:12:10.253(5.5)? (STDERR)     at PassThrough.pipeOnReadable (_stream
_readable.js:643:5)
W20150716-17:12:10.254(5.5)? (STDERR)     at PassThrough.emit (events.js:92:17)

```

**Comment by kefirchik** [comment]
Can u edit this output and put it into
<dl>
``` <br/>
{{code block}}<br/>
```
</dl>

**Comment by abhisheksoni27** [comment]
This happens only in Windows. When I checked the same package in linux, that is, by running the same reaction folder via Ubuntu,it showedthe image which generated this error in Windows and no problem appeared n uploading image from Ubuntu.

**Comment by kefirchik** [comment]
This what I've got with `childProcess.spawn` wrapper function:
```
spawn called
{ '0': 'convert', '1': [ '-', '-resize', '1000x1000', '-' ] }
spawn called
{ '0': 'convert', '1': [ '-', '-resize', '600x600', '-' ] }
spawn called
{ '0': 'convert',
  '1':
   [ '-',
     '-resize',
     '235x235^',
     '-gravity',
     'Center',
     '-extent',
     '235x235',
     'PNG:-' ] }
spawn called
{ '0': 'convert',
  '1':
   [ '-',
     '-resize',
     '100x100^',
     '-gravity',
     'Center',
     '-extent',
     '100x100',
     'PNG:-' ] }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Socket._write (net.js:646:26)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Socket.Writable.write (_stream_writable.js:183:11)
    at Socket.write (net.js:616:40)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at PassThrough.pipeOnReadable (_stream_readable.js:643:5)
    at PassThrough.emit (events.js:92:17)
```

**Comment by abhisheksoni27** [comment]
What does this mean?

**Comment by aaronjudd** [comment]
That looks like maybe it's the transformations in collectionFS (graphicsmagick / imagemagick ).  Do you have those installed?

**Comment by abhisheksoni27** [comment]
No, I don't have those installed.But I dont have those installed in Linux too.

**Comment by aaronjudd** [comment]
the `cfs:graphicsmagick` package is supposed to detect whether it's installed or not, and not run image transformations if those aren't installed.  I know this works on osx/linux but I'm not sure about windows.. The output that @kefirchik posted shows errors from a process spawn that are clearly related to the image resize functions, so that's why I'm questioning if that is working for windows.

**Comment by abhisheksoni27** [comment]
I will install it and see what happens then.

**Comment by abhisheksoni27** [comment]
Works.

**Comment by kefirchik** [comment]
Confirmed. I had to install x64 version of ImageMagick

**Comment by aaronjudd** [comment]
Issue is already reported at https://github.com/CollectionFS/Meteor-cfs-graphicsmagick/issues/12  - maybe we can work on the patch.

**Comment by aaronjudd** [comment]
@kefirchik if you have one machine without imagemagick installed,  could you test a local clone of https://github.com/CollectionFS/Meteor-cfs-graphicsmagick and see if the newest code (unreleased) works? If so, I'll work with @aldeed and help get a new packaged published.

**Comment by kefirchik** [comment]
Ok, I'll check it out this evening. I'll go throught all required steps for clean windows install.

**Comment by aaronjudd** [comment]
@kefirchik great - I feel like I probably missed a few detailed steps in the installation docs.  really appreciated :+1:

**Comment by kefirchik** [comment]
@aaronjudd Sorry, I can't clearly test it, but it actually throws erros without ImageMagick installed.

**Comment by aaronjudd** [comment]
ok I listed ImageMagick as required dependency in the docs, and there is a pending patch on the cfs:graphicsmagick so I think we're ok.
