### ISSUE TITLE
Product Detail Basic Information

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4130]
Add the basic information section to the Product Detail layout as defined in #4126 

![image](https://user-images.githubusercontent.com/1203639/38232925-1ef50dd8-36d6-11e8-8caa-b724f51a7527.png)

The product detail layout contains the product `price`, `vendor`, and `description`

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #22](https://github.com/reactioncommerce/reaction-next-starterkit/issues/22) via [**ZenHub**](https://www.zenhub.com/)
