### ISSUE TITLE
Product Detail Featured Image

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4131]
Within the Product Detail layout #4126, create a featured image section as part of the product detail media gallery.

This featured image section should show the image featured at the product level if no variant is selected, or if a variant is automatically selected or selected as part of the url, then, the featured image should show the primary image from that variant or option.

![image](https://user-images.githubusercontent.com/1203639/38233199-f1f777ac-36d6-11e8-9823-63c6363e143a.png)

The featured image should show a "zoomed" detail view when hovering.

![image](https://user-images.githubusercontent.com/1203639/38233208-faa27bd6-36d6-11e8-92c2-a1c842529dcc.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #23](https://github.com/reactioncommerce/reaction-next-starterkit/issues/23) via [**ZenHub**](https://www.zenhub.com/)
