### ISSUE TITLE
Product Detail Variant List

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4132]
Create a variant list for the Product Detail page, within the product detail layout #4126 

The variant list should display a clickable list of all variants that have the product as the only ancestor, along with the variant title and denormalized price. It should be ordered based on the variant index, with the variant in the first position being the default.

![image](https://user-images.githubusercontent.com/1203639/38233511-fcd05bc0-36d7-11e8-98f3-0c9490a59a0a.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #24](https://github.com/reactioncommerce/reaction-next-starterkit/issues/24) via [**ZenHub**](https://www.zenhub.com/)
