### ISSUE TITLE
Product Detail Options List

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4133]
Create an options list for the Product Detail page, within the product detail layout #4126 

The options list should display a clickable list of all options that have the currently selected variant as their parent, along with the option title and price. It should be ordered based on the index, with the option in the first position being the default. If a variant has no options, this list should not show.

![image](https://user-images.githubusercontent.com/1203639/38233616-5a565d30-36d8-11e8-9b2c-02d4ea0e092e.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #25](https://github.com/reactioncommerce/reaction-next-starterkit/issues/25) via [**ZenHub**](https://www.zenhub.com/)
