### ISSUE TITLE
Product Detail Inventory Status Badges

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4134]
Within the Variant List #4132  and the Options List #4133 of the Product Detail layout, create status badges that reflect the current status of each variant and option inventory status.

- Sold Out
- Backordered
- Low Inventory

![image](https://user-images.githubusercontent.com/1203639/38233782-084ed7c8-36d9-11e8-97dd-43b4669b5147.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #26](https://github.com/reactioncommerce/reaction-next-starterkit/issues/26) via [**ZenHub**](https://www.zenhub.com/)
