### ISSUE TITLE
Product Detail Metafield List

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4136]
Create a meta-field list on the product detail page.

Should show the key and the value for a set of meta fields that are present on the product.

![image](https://user-images.githubusercontent.com/1203639/38233969-9edda11a-36d9-11e8-909d-8b7ee56e5405.png)

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-next-starterkit #28](https://github.com/reactioncommerce/reaction-next-starterkit/issues/28) via [**ZenHub**](https://www.zenhub.com/)
