### ISSUE TITLE
Product Detail Add To Cart

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4137]
Create an Add To Cart button on the product detail page.

When clicked, the add to cart button should add a qty number of the currently selected variant/option to the cart for the active user or session if no user.

This ticket is only to create the UI for this button. Actions will be added later on when GraphQL is ready to accept them.

![pdp_-_standard_enterprise_-_storefront_-_zeplin](https://user-images.githubusercontent.com/4482263/40146447-677191d8-591a-11e8-9975-0247a5e2fb80.png)

**Comment by kieckhafer** [comment]
Closing this in favor of a ticket in the `reaction-next-starterkit` repo: https://github.com/reactioncommerce/reaction-next-starterkit/issues/98
