### ISSUE TITLE
addressBookAdd bug

### ISSUE THREAD

**Issue by abhisheksoni27** [reactioncommerce/reaction#414]
I think as far as deployment to DO or anyother provider is concerned, there is a way to retrieve the admin interface either by specifying a settings file, or settign environment variables or just resetting the password. However, I cant think of a way as to retrieve the admin credentials. I tried changing it using emteor mongo but then the error goes to `This user has not set a password`.

Maybe, we could put a deploy.md file with instructions about the most important interface of an ecommerce website?

Also,
Without getting the admin access, and trying to buy the example-generated product, this is what happens:

![capture](https://cloud.githubusercontent.com/assets/4340071/8722891/ccef6fee-2be6-11e5-89fa-5fa63c20d471.JPG)

I checked it using logs and this is what is returned:

`[Thu Jul 16 2015 12:37:17 GMT+0000 (UTC)] INFO Exception while invoking
method 'addressBookAdd' MongoError: Field name duplication not allowed
with modifiers`

The browser, as expected, files an Internal Server Error [500]. This is not a priority, but it could be something that happens when the app is deployed to meteor servers, just for testing.

**Comment by abhisheksoni27** [comment]
Any updates on this?

The console on the machine gives this error which appears on meteor servers. It works fine on developement machine though.

```
Error invoking Method 'addressBookAdd': Internal server error [500]
917be5d13a33c221b0721accc0280db446c36b94.js:3 Exception from Tracker afterFlush function:
917be5d13a33c221b0721accc0280db446c36b94.js:3 TypeError: this.$(...).tooltip is not a function
    at null.<anonymous> (917be5d13a33c221b0721accc0280db446c36b94.js:282)
    at 917be5d13a33c221b0721accc0280db446c36b94.js:72
    at Function.e._withTemplateInstanceFunc (917be5d13a33c221b0721accc0280db446c36b94.js:72)
    at n (917be5d13a33c221b0721accc0280db446c36b94.js:72)
    at null.<anonymous> (917be5d13a33c221b0721accc0280db446c36b94.js:72)
    at 917be5d13a33c221b0721accc0280db446c36b94.js:71
    at Object.c._withCurrentView (917be5d13a33c221b0721accc0280db446c36b94.js:71)
    at 917be5d13a33c221b0721accc0280db446c36b94.js:71
    at Object.t._runFlush (917be5d13a33c221b0721accc0280db446c36b94.js:17)
    at e (917be5d13a33c221b0721accc0280db446c36b94.js:3)
```

**Comment by abhisheksoni27** [comment]
It is about the Objects.Template.addressBookAdd.helpers.formId : Cannot find formId of undefined.
Selected Country and the address schema.

**Comment by aaronjudd** [comment]
@abhisheksoni27 there are a couple form errors left related to #349.  This `addressBook` error looks like one, I should be able to get this updated today. 

re deployment and setting the admin/user on deploy: https://github.com/reactioncommerce/reaction-core/blob/development/docs/fixtures.md

You can use environment variables to set the initial user pass.

**Comment by abhisheksoni27** [comment]
Yeah. That user thing is resolved. But, hopefully the `addressBook` error will be fixed today.

**Comment by aaronjudd** [comment]
I've recently pushed a bunch of minor updates, I've just completed a fair amount of orders both as admin and as guest, successfully through to order completion, and then processed the orders as admin. So I think your issue is resolved, but you'll need the `development` branches of all the reaction-* packages.

**Comment by abhisheksoni27** [comment]
What do you mean by I would need the development branch of all the reaction-* packages? 
I mean, how would I go about that? 

I have the reaction-core development branch, and this issue was about it too.

**Comment by aaronjudd** [comment]
**meteor list**
these are the reaction package versions I'm running. some of these aren't published to the meteor package repo yet and might need to be cloned from `development`. If you run this and see that your meteor versions are older than these, you could clone them to your `packages` directory if you want the very latest development stuff. 

```
reactioncommerce:bootstrap-theme     1.1.0+ Reaction Commerce Bootstrap theme builder
reactioncommerce:core                0.6.1+ Core - Reaction Commerce ecommerce Meteor package
reactioncommerce:reaction-auth-net   0.4.2+ Reaction Authorize.net - Authorize.net payments for Reaction Commerce
reactioncommerce:reaction-braintree  1.2.0+ Reaction Braintree - Braintree payments for Reaction Commerce
reactioncommerce:reaction-paypal     0.8.0+ Reaction Paypal - PayPal payments for Reaction Commerce
reactioncommerce:reaction-shipping   0.3.1+ Reaction Shipping - Flat Rate shipping for Reaction Commerce
reactioncommerce:reaction-social     0.2.1+ Reaction Social - Social Sharing Package for Reaction
reactioncommerce:reaction-stripe     1.3.0+ Reaction Stripe - Stripe payments for Reaction Commerce
```
*Note to readers of the future: if you think this is a something that should be published in the dev docs, maybe we can find an easy way to publish this info.  (some kind of version status - compatibility list would be cool)*

**Comment by abhisheksoni27** [comment]
Thanks. I cloned the packages. RC is awesome.

**Comment by abhisheksoni27** [comment]
The error does not appear on machine, but reappears after deployment. This time though, it is just an Internal Server Error. What could it be?

**Comment by abhisheksoni27** [comment]
any news?

**Comment by aaronjudd** [comment]
wasn't happening local, only on meteor deploy - which is a bit of a mystery.
