### ISSUE TITLE
Mixed Content: insecure XMLHttpRequest endpoint '/assets/uploads'.

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4146]
## Issue Description
Mixed content error when uploading images via https.

Mixed Content: The page at 'https://www.my.domain/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.my.domain/assets/uploads'. This request has been blocked; the content must be served over HTTPS.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Hosting reactioncommerce:latest with a valid SSL certificate (on elastic beanstalk)
2. Try to upload images to shop

I realise this could be to do with my configuration, however I have setup nginx as I've used it successfully previously on elastic beanstalk, and even added meteor force-ssl.

## Possible Solution
https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/files/server/fileCollections.js#L126-L129

 is being sent via http, although my browser is in https. This gives a mixed content error, and as such it's not possible for users to upload files.

### Versions
Node: 8.9.0
NPM: 5.7.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Docker: 18.03.0-ce

**Comment by zenweasel** [comment]
@willmoss1000 I tested this on one of our domains that we host and I did not see this error. So it would appear to be something in your configuration.

**Comment by willmoss1000** [comment]
@zenweasel ok thanks for checking!

**Comment by willmoss1000** [comment]
Incase anyone comes across this issue...

I was terminating my SSL at the load balancer and passing http back to the docker container. This usually isn't a problem because you pass on the header and the container knows to request over https. However, I couldn't get this to work.

All good now - I'm passing https back to the container and using the config suggested here: https://gist.github.com/jshimko/745ca66748846551692e24c267a56060
