### ISSUE TITLE
Reaction pull doesn't work

### ISSUE THREAD

**Issue by duongvu89** [reactioncommerce/reaction#4162]
## Description
The reaction pull command doesn't work. This is the screenshot:
<img width="1220" alt="screen shot 2018-04-08 at 5 13 25 pm" src="https://user-images.githubusercontent.com/9512917/38466351-1b00e6d6-3b52-11e8-83fb-06cedff1e36f.png">

**Comment by zenweasel** [comment]
`reaction pull` will only work when you have not modified your git remotes and it appears you have. To update if you have modified your git configuration you will need to fall back to raw git commands. `reaction pull` doesn't do anything really special besides pull/merge from the main repository, and removing and reinstalling your npm dependencies.

**Comment by dhonig** [comment]
For the benefit of others this can be worked around easily.
1. Delete the remote that is origin ( if it is anything other than the project home)
2. Re-add the reaction repository as origin
3. Add your own repository for tracking changes as git remote add <myrepo>  <myrepourl>
4. Update the tracking branch, in my case I did this with git push myrepo -u mybranch
