### ISSUE TITLE
Reaction run producing error. App failed to start

### ISSUE THREAD

**Issue by SuhailHassan** [reactioncommerce/reaction#4170]
![image](https://user-images.githubusercontent.com/38312046/38662612-8b1788a0-3e52-11e8-95ec-e483cda73414.png)

reaction -v produces this
![image](https://user-images.githubusercontent.com/38312046/38662648-a4485192-3e52-11e8-93d9-161267f6b0e4.png)

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).
