### ISSUE TITLE
[ISSUE] Publishing an archived product removes it instead

### ISSUE THREAD

**Issue by desirelabs** [reactioncommerce/reaction#4178]
Hello, I'm starting from the ground with Reaction Commerce, and here is something that sound like an issue to me :

## Issue Description
Publishing a new product with data, then archiving it, then republishing it ends in product removal.

## Steps to Reproduce
1. Create a new product
2. Publish the product
3. Archive the created product
4. Publish the archived product 

### Versions
Node: 8.10.0
NPM: 5.6.0
Meteor Node: 8.11.1
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: master

![peek 2018-04-14 17-44](https://user-images.githubusercontent.com/24223583/38769974-051a9538-400c-11e8-8853-616e12f04589.gif)

**Comment by aldeed** [comment]
Fixed in 2.0.0
