### ISSUE TITLE
Shop/Dashboard is never created

### ISSUE THREAD

**Issue by NearSingularity** [reactioncommerce/reaction#418]
![ex](https://cloud.githubusercontent.com/assets/3435986/8764570/4f75fff2-2d98-11e5-8086-d40bf3a7d8ee.PNG)

Continuously attempts to create the first shop to no avail (posting this after waiting an hour)

**Comment by aaronjudd** [comment]
Can you try again, we were having some issues with the alpha-test shop docker hosts.  Should be ok now.  It's a little unstable, and we're working on a production quality replacement for the upcoming beta. Thanks for the report!
