### ISSUE TITLE
catalogItem schema: migrate product to it's own property

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4192]
This issue came out of a discussion we had around #4185 which will become an epic
It should be completed in tandem with #4189 and refers to the renamed `catalogItem` schema which is to be the `catalog` schema until #4189 is completed.

In the `catalogItem` schema, create a new `product` field and move all existing schema fields that were previously associated with `product` into this new field.

e.g.
``` 
catalogItem: {
  product: {
    ...
    title,
    price,
    etc.
  }
}
```

**Comment by aldeed** [comment]
This is within the scope of #4196 and we've already done it in that branch, so I'm closing this.
