### ISSUE TITLE
catalogItem schema: update product field

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4193]
_This issue came out of a discussion we had around #4185 which will become an epic
It should be completed in tandem with #4189 and refers to the renamed catalogItem schema which is to be the catalog schema until #4189 is completed._

Change the following field names nested in the `product` field for the `catalogItem` schema
`hashtags` => `tagIds`
`handle` => `slug`

The data should be identical.

You will need to update anywhere in the Meteor UI that currently references the handle or the hashtags. Currently, the product grid is the only UI that uses the catalog.

**Comment by aldeed** [comment]
We've done this as part of #4196
