### ISSUE TITLE
catalogItem schema: Add fields to the catalog item root

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4194]
_This issue came out of a discussion we had around #4185 which will become an epic
It should be completed in tandem with #4189 and refers to the renamed catalogItem schema which is to be the catalog schema until #4189 is completed._

Add the following fields at the `catalogItem` root:
```
isDeleted: bool
isArchived: bool
isVisible: bool
tagIds: [String]  // changed from hashtags
updatedAt: date
createdAt: date
```

**Comment by aldeed** [comment]
I'm closing this. Some of this was done in #4218 and the rest can be done as necessary in the future, pending more schema discussions.
