### ISSUE TITLE
catalogItem schema: Move `positions` array to root

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4195]
_This issue came out of a discussion we had around #4185 which will become an epic
It should be completed in tandem with #4189 and refers to the renamed catalogItem schema which is to be the catalog schema until #4189 is completed._

Change the positions map into an array, move it to the catalogItem root (from the `product` field) and to add the other merchandising data into it. Maybe consider changing the name from positions to `merchandising` or something more clear that it involves positions, grid size (display weight), etc

E.g. 
```
merchandising: [ProductMerchandising]
```

Here's an example schema based on what we use for `ProductPosition` right now
Where product position looks similar to how it does now

I think we should update the tag => tagId and make it required
```
/**
 * @name ProductMerchandising
 * @memberof schemas
 * @type {SimpleSchema}
 * @property {String} tagId // renamed from tag which was a slug, let's consider using tagId instead?
 * @property {Number} position optional
 // Current position doc includes `pinned` which doesn't appear to be used used on current UI, so I'd vote to burninate.
 * @property {Number} displayWeight optional, default value: `0` // renamed from 'weight', open to other name suggestions
 * @property {Date} updatedAt required
 */
export const ProductMerchandising = new SimpleSchema({
  tagId: {
    type: String // Was optional before, don't think it should be
  },
  position: {
    type: SimpleSchema.Integer,
    optional: true
  },
  displayWeight: {
    type: SimpleSchema.Integer,
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 3 // Do we need a max?
  },
  updatedAt: {
    type: Date
  }
}
```

**Comment by aldeed** [comment]
Keeping this as a separate issue for now, but we've begun this in the branch for #4196
