### ISSUE TITLE
catalogItem schema: update product publication method

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4196]
_This issue came out of a discussion we had around #4185 which will become an epic
It should be completed in tandem with #4189 and refers to the renamed catalogItem schema which is to be the catalog schema until #4189 is completed._

Update the product publication methods and any code that pushes data to the catalog to set the data on the catalogItem correctly based on the changes to the schema made as part of #4185.

New fields created in #4192, #4193, #4194, and #4195 `on the catalogItem should be set when the product is published to the grid, along with any mappings of data that is in a different format on the product to the catalog item.

Additionally, create a filter that will strip out any deleted variants/options from the variants array. If a variant has `isDeleted: true` it should not be added to the catalog.

**Comment by aldeed** [comment]
This will be broken into two parts. First we will move and migrate everything we can while still keeping everything in the single `Catalog` collection.

The goals for this first step:
- Move all transformation that is currently happening in `resolvers/catalog/CatalogItemProduct/product.js` and `resolvers/catalog/CatalogItemProduct/positions.js` and `resolvers/catalog/CatalogProduct/variants.js` to instead happen when initially publishing a product and writing to the catalog collection. Ideally those resolvers will be completely unnecessary when done.
- Write a single migration for all of the schema changes.
- Change any client or server code that is directly reading from Catalog collection to use the new property names/paths.

All writing to the Catalog collection happens in /imports/plugins/core/catalog/server/methods/catalog.js.

To find where the changed properties are used, search for each of them, and search for `Catalog.find`. It may take some work to follow the trails, but in general, only the grid UI is currently using the Catalog collection.
