### ISSUE TITLE
import error when using case sensitive filesystem

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#4201]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. use linux
2. try to start reaction
3. errors will show up:
```
Error: Cannot find module './Query'
    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at index.js (imports/plugins/core/graphql/server/resolvers/account/index.js:1:755)
```
and
```
Error: Cannot find module './Mutation
    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at index.js (imports/plugins/core/graphql/server/resolvers/account/index.js:1:755)
```

## Possible Solution
Change directory name from reactioncommerce/reaction/imports/plugins/core/graphql/server/resolvers/account/`m`utation
to 
reactioncommerce/reaction/imports/plugins/core/graphql/server/resolvers/account/`M`utation

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.11.0
Reaction branch: release-1.11.0
Docker: 17.03.1-ce

**Comment by aldeed** [comment]
@prinzdezibel This is not an issue with the code. It's just that you need to manually uppercase the `query` and `mutation` folders to `Query` and `Mutation` because your OS does not "see" the change in Git. Or you can clone the repo into a new folder.
