### ISSUE TITLE
Migration 24 throws if name is not set in media record

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4207]
@mschipperheyn commented on [Sun Mar 25 2018](https://github.com/reactioncommerce/reaction-file-collections/issues/5)

Wanted to bring a migration issue to attention. 
```
=> Started proxy.                             
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
=> Started MongoDB.                           
15:43:34.517Z  INFO Reaction: Load default data from /private/data/
15:43:34.613Z  INFO Reaction: JobServer started
15:43:35.389Z  WARN Reaction: Skipped loading settings from reaction.json.
15:43:36.988Z  INFO Reaction: Reaction Version: 1.10.0
15:43:37.030Z  INFO Reaction: Migrating from version 19 -> 24
15:43:37.031Z  INFO Reaction: Running up() on version 20
15:43:37.038Z  INFO Reaction: Running up() on version 21
15:43:37.040Z  INFO Reaction: Running up() on version 22
15:43:37.054Z  INFO Reaction: Running up() on version 23
15:43:37.253Z  INFO Reaction: Running up() on version 24
15:43:37.284Z ERROR Reaction: FileRecord.url: filename is required
  Error: FileRecord.url: filename is required
      at getUrlForFileRecord (/test/reaction/node_modules/@reactioncommerce/file-collections/dist/common/FileRecord/url.js:20:29)
      at FileRecord.url (/test/reaction/node_modules/@reactioncommerce/file-collections/dist/common/FileRecord/FileRecord.js:331:32)
      at mediaArray.map.media (imports/plugins/core/catalog/server/methods/catalog.js:104:25)
      at Array.map (<anonymous>)
      at Promise.asyncApply (imports/plugins/core/catalog/server/methods/catalog.js:102:35)
      at /Users/me/.meteor/packages/promise/.0.10.2.6syjw.dgdz8s++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/Users/me/.meteor/packages/promise/.0.10.2.6syjw.dgdz8s++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/plugins/core/catalog/server/methods/catalog.js:147:20)
      at /Users/me/.meteor/packages/promise/.0.10.2.6syjw.dgdz8s++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

---

@aldeed commented on [Mon Apr 09 2018](https://github.com/reactioncommerce/reaction-file-collections/issues/5#issuecomment-379799175)

Thanks @mschipperheyn. This should be investigated but it looks like more of a Reaction-specific implementation issue rather than an issue with this package. Can you close this and open an issue in https://github.com/reactioncommerce/reaction repo instead? Thanks.

---

@htmllab commented on [Sun Apr 22 2018](https://github.com/reactioncommerce/reaction-file-collections/issues/5#issuecomment-383360300)

1+

**Comment by aldeed** [comment]
I moved this issue from the reaction-file-collections repo

**Comment by zenweasel** [comment]
@mschipperheyn Could you fill out the issue template for this? Specifically with steps to reproduce as I am not seeing this on any current versions of Reaction.


=====================

Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?
* [ ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Providing a clear description of the issue will enable a developer to quickly reproduce and understand the issue. Please provide a detailed description including images, animation and/or videos. For client issues, include browser console errors, for server issues please add terminal output and stack traces.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1.
2.
3.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug


### Versions
(run `reaction -v` from your reaction directory)

**Comment by aldeed** [comment]
@zenweasel The error would indicate a media record where the `name` is not set for some reason. Migration 24 creates catalog items, including creating the `media` array with URLs, which is where this is thrown. It's possible we could just try/catch and log errors due to bad existing data.
