### ISSUE TITLE
Create Shippo Package

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#421]
Create Shippo package, admin, and checkout template.
- create a `ongoworks:meteor-shippo` wrapper package for their NPM package, and export
- create a `reactioncommerece:reaction-shippo` package
- add shippo configuration UI for admin
- integration with existing rate lookup (see reaction-shipping) and implementation during checkout
- more functionality - TBD

**Comment by lcampanis** [comment]
Hi! 
I'd like to ask at what stage the Shippo integration is? 
As it looks like a substantial amount of work and we'll be using it as well, we'd like to assist in the development for this module. We are looking for a completion date around the beginning of October. Would that be something you'd be interested in? From our side we can start development towards the end of August. The new platform is called Artlimes and is a dedicated marketplace for Art using latest tech, like Reaction. :)
Thank you.

**Comment by aaronjudd** [comment]
@lcampanis we're looking to complete this in the second half of September.  Happy to work with you on this, we need to dig into a little on our side as well, but happy to answer any questions.

**Comment by lcampanis** [comment]
Hi @aaronjudd We are very close to picking up a number of modules that are needed for us, one of them being the GoShippo integration. Could we organise a chat in private or Skype better, in order for me to understand how we can work together on this one, as well as other modules and tools that might be useful to Reaction Core? 
Thank you.

**Comment by aaronjudd** [comment]
@lcampanis our chat room is a good place to start https://gitter.im/reactioncommerce/reaction, feel free to direct message me there as well.

**Comment by lcampanis** [comment]
Will start researching this properly over the weekend and get started with dev on Monday. 
Anything you can share on how the UI should behave or how you'd like this integrated, please do. We will start simple with a shippo package api_key integration and follow the same pattern as other core modules.

Also @aaronjudd you mentioned that get outfitters have developed some label functionality already? Where can I find this please?

**Comment by lcampanis** [comment]
@aaronjudd We've started analysis today on this, given your requirements above. 
It might a good idea to connect on this one if you have any resource available, so we can get started with the `meteor-shippo` wrapper in the next day or two.

**Comment by prosf** [comment]
Hi @aaronjudd as we get started a few things we noticed:
Meteor announced the plan to migrate all existing atmosphere packages to npm https://guide.meteor.com/atmosphere-vs-npm.html 
It seems that the trend of the meteor community nowadays is to publish packages directly to npm 
eg: https://forums.meteor.com/t/meteor-1-3-modules-when-to-use-a-meteor-package-vs-an-npm-package/16325

We have setup a sample reaction plugin using the Shippo npm package and the example code worked flawlessly.
A meteor wrapper is probably not needed anymore and we can simply go ahead and create a `reactioncommerece:reaction-shippo` package. 
Any thoughts let us know.

**Comment by aaronjudd** [comment]
@prosf that's great! -> and yes, that's been our strategy for a while to be move everything we can to npm.  Our "imports/plugins" are in fact, mostly a transition strategy to moving these to npm, and we are hoping to start tackling that in the next release or two.  We were hoping to see more progress from Meteor on the 1.5 release and their migration strategy to npm though.  Since the time that statement was added to the docs, the priorities within Meteor seem to have shifted somewhat, but regardless our goal is to move everything we can to npm, starting with modules that have no real Meteor dependencies.   I'm not sure what permissions, etc need to be setup to publish to reactioncommerce:reaction-shippo if any (gotta say, I'm still struggling to figure out the npm organizations).   Let me know that and I can add (and I can add to our org if you want to keep the repo here).

**Comment by lcampanis** [comment]
Hi @aaronjudd 
Here comes the Shippo plugin. @prosf has done a great job integrating Shippo into Reaction using the same structure as other reaction plugins with external APIs, ie. payments. 
Although the plugin has a dashboard card of its own, we did try to put it under shipping together with Flat Rates, but it seems Flat rates has a structure of its own and isn't following the same pattern as payments for us to easily put it there, so we put it out there to start.
As soon as the API key is added, the package creates a connection with Shippo with a simple function call to test the API key's validity and returns a successful message when connected. Only when connected it then saves the Key in the DB.
The user can also remove the key - something that's currently missing from other plugins like Paypal. It's a very basic implementation, but we thought we'd give you a head start with this one. 
You can get a test key for Shippo here: https://goshippo.com/docs/auth
PR https://github.com/reactioncommerce/reaction/pull/1618
Looking forward to your feedback..
