### ISSUE TITLE
Merchant Notifications Only Appear For Primary Shop Owner

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4211]
## Issue Description
Upon sale of an item by a merchant shop, no notification is shown to the merchant. The primary shop owner does however receive a notification. 

## Steps to Reproduce
1. Setup Marketplace and order an item from a merchant
2. Login as merchant
3. Observe no notifications

### Versions
1.10

**Comment by willmoss1000** [comment]
The issue here is that order.shopId is always set to that of the Primary Shop.

**Comment by spencern** [comment]
Closed by #4295
