### ISSUE TITLE
Very slow refreshes

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4212]
## Prerequisites
* [x] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When I start up the latest version of Reaction, change a file (in a brand new custom plugin), and save, Reaction takes about 2 minutes to rebuild on a client-side change, and around 4 minutes for a server change. It's actually easier to kill reaction & the node process, and restart reaction. It slows down development. Is there any solution to this?

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Start Reaction
2. Change any file and save
3. Note Meteor reload time - ~2m for client-side changes, ~4m for server-side changes

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
Node: 6.2.2
NPM: 5.0.3
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.11.0
Reaction branch: FLAN-46
Docker: 17.09.1-ce

**Comment by dancastellon** [comment]
@cindyfirestone I've updated the issue format - thank you!

**Comment by zenweasel** [comment]
@dancastellon Hey Dan. Yes, this is an issue we are aware of. There is no quick fix for this as it is a function of using the Meteor build tool. The long term plan is that we are moving up/out of Meteor as soon as we can. In meantime we have had some luck with setting this environment variable:
`METEOR_DISABLE_OPTIMISTIC_CACHING` to true. This seems to help a lot by stopping Meteor from searching for files that don't exist.

**Comment by dancastellon** [comment]
@zenweasel Thanks! Running reaction with `METEOR_DISABLE_OPTIMISTIC_CACHING=true reaction` has made it _much_ faster for me.
