### ISSUE TITLE
/imports/included/inventory/server/init.js Not suitable for large stores.

### ISSUE THREAD

**Issue by dhonig** [reactioncommerce/reaction#4215]
## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1.  Create a store 
2.  Import over a million products
3. Without tuning the node vm, RC will OOM and crash

## Possible Solution
Include  a flag to build inventory as a background job instead of inside of "afterCoreInit".  The job should pluck id's by the 1000's or 10 of 1000's and perform bulk updates of the inventory collection to be performant.

```
import { Hooks, Logger } from "/server/api";
import { Products, Inventory } from "/lib/collections";
import { registerInventory } from "../methods/inventory";

// On first-time startup init the Inventory collection with entries for each product
Hooks.Events.add("afterCoreInit", () => {
  // If we already have any inventory record, skip
  const inventory = Inventory.find().count();
  if (!inventory) {
    const products = Products.find().fetch();
    for (const product of products) {
      Logger.debug(`Registering product ${product.title}`);
      registerInventory(product);
    }
  }
});

```
In the above code, the dangerous method is Products.find().count(), for most e-commerce stores, this wont cause an issue, for those with millions of Products this code isn't suitable.     Perhaps a flag to turn this off is a good idea.  A larger deployment will likely need a custom means of managing inventory

**Comment by zenweasel** [comment]
Flagging this minor since the workaround is to just remove the `inventory` plugin and use your own which can be done without any modifications to core.
