### ISSUE TITLE
If All Variants Removed - Default Image Replaced By Brand Asset & Favicon

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4219]
## Issue Description
If all variants are removed for a product, and a brand asset exists the default image is replaced in that product by the brand asset & favicon (perhaps any images in the public folder). Whilst this is not really an issue for normal shops, this is more of an issue in marketplace where users are disconcerted by the bug.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Add brand assets
2. Go to a product
3. Remove all variants and try to publish

Note: **not yet reproduced without my customisation**. 

## Possible Solution
Uncertain. Would be worth looking into at the same time as https://github.com/reactioncommerce/reaction/issues/4051, which is clearly a greater priority.

### Versions
Node: 8.9.0
NPM: 5.7.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: master
Docker: 18.03.0-ce

**Comment by terrelltechsup** [comment]
I was able to reproduce this issue on accident and I am no longer able to reproduce it, but it did happen once to me.  In my case I already had a product open in edit mode and I switched to the general shop settings panel with the product still open and uploaded a logo.  The variant entry I had set was now missing and the images were replaced with the logo.  Once I added the variant back the issue resolved itself.

**Comment by willmoss1000** [comment]
Yes, I believe it happens if you archive the variant and it is then deleted.

**Comment by willmoss1000** [comment]
Yes, I've now been able to re-produce this. It happens if all variants are set to `not visible`, and then you sign-out as a customer.

**Comment by aldeed** [comment]
This should not be an issue anymore in current release, and will not be fixed in 1.x
