### ISSUE TITLE
For Prerender.IO make protocol type(https or http) to be load from env settings

### ISSUE THREAD

**Issue by amalan-shenll** [reactioncommerce/reaction#4224]
In RC 1.11.0, in prerender.js 
    prerender.set("prerenderToken", process.env.PRERENDER_TOKEN);
    prerender.set("host", process.env.PRERENDER_HOST);
    prerender.set("protocol", "https");
this is code for prerender.io configuration.
it allows to env variable for prerenderToken and host.

**issue**
    prerender.io always redirecting to https where our demo site support only http

**reason**
    prerender.set("protocol", "https");

**expecting change**
pls change hardcoded protocol to load from env setting like
**prerender.set("protocol", process.env.PRERENDER_PROTOCOL);**
https://github.com/reactioncommerce/reaction/blob/7a7612033fcb044156945f6949169f8019296186/server/startup/prerender.js#L9
which may allow developers to set protocol type in env settings

Thank You

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #46](https://github.com/reactioncommerce/reaction-feature-requests/issues/46) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zenweasel** [comment]
@amalan-shenll We would accept a PR for this change, but for right now I am going to move this to `feature-requests`
