### ISSUE TITLE
Cancelling Order Does Not Apply Refund

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4226]
## Issue Description
When you receive an order, and rather than accepting the order click "cancel" - then the order is not refunded. As shown in the image below.

## Steps to Reproduce
1. Order a listing from the admin shop - using example payment plugin
2. Login as admin and view your orders
3. Do not accept the order, but click the down arrow and cancel it
4. Click on the cancelled order, and the ability to "refund" is still shown, and the funds are shown as having been captured - which they are not. 
5. If you click refund at this stage it does not work - no amount is shown to refund, and you get a server error.

<img width="599" alt="screen shot 2018-05-01 at 13 32 29" src="https://user-images.githubusercontent.com/33007279/39472945-3115d75c-4d44-11e8-8bb7-8b323e19e8d4.png">

### Versions
(run `reaction -v` from your reaction directory)
1.10

**Comment by zenweasel** [comment]
@willmoss1000 please provide which payment method you are using

**Comment by willmoss1000** [comment]
I checked this with the example payment plugin, however I've also experienced this in marketplace using stripe connect. Apologies, I haven't yet verified on a clean install as I should.

**Comment by willmoss1000** [comment]
Verified this issue exists on a clean install of v1.10 using the example payment plugin.

**Comment by aldeed** [comment]
This code was reworked in 2.0 and I don't believe this issue exists anymore. If it does, we'll need an issue with more specific reproduction steps.
