### ISSUE TITLE
Payments need to be captured in `payments` array on billing records

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4229]
Since Marketplace we have decided that the array of billing/shipping records is to represent multiple shops and should not represent multiple payments or multiple shipments for the same order.

The billing record schema should be changed to reflect that multiple payments should be captured in a `payments` array on each billing record. The only way to currently do multiple payments on an order is through discount codes  and this methods creates multiple billing records which should be deprecated/removed.

I feel like this was the original intention but I don't see it manifest anywhere in the current schema and might just be something that we missed during the marketplace upgrade. In addition the `PaymentMethod` schema should be altered to reflect that `shopId` is always required.

This is sort of the pair of capturing shipments in a `shipment` array on the `shipping` record which should also happen to make this marketplace-safe.

**Comment by aldeed** [comment]
In 2.0-rc.1, a `payment` is now stored on each order fulfillment group, so I believe this issue is adequately addressed. Multiple fulfillment groups can now exist either for multiple shops, or for multiple shipments/fulfillment types, or some combination, and each one has its own payment/charge.
