### ISSUE TITLE
Error: Command failed: docker -v

### ISSUE THREAD

**Issue by fucata55** [reactioncommerce/reaction#4242]
## Issue Description
(Windows 10) I'm following installation for windows. "reaction init" has success for most of the part but at the end, it shows "Error: Command failed: docker -v , error: unknown option '-v'". I continue with "cd reaction, reaction" and got stuck in "Building for os.windows/x86_64" for more than an hour

![image](https://user-images.githubusercontent.com/30759367/39939015-79330e46-551a-11e8-9b7d-76aa11f9b9fa.png)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1.  (on Windows, admin command prompt) choco install git
2.  choco install meteor
3. npm install -g windows-build-tools
4. npm install -g reaction-cli
5. cd /users/myUserName/my-reaction-projects
6. reaction init

## Possible Solution
Perhaps something related to docker

### Versions
 reaction -v

  error: unknown option `-v'

C:\Users\fucat\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\yargs\yargs.js:1079
      else throw err
           ^

Error: Command failed: docker -v

  error: unknown option `-v'

**Comment by aldeed** [comment]
@fucata55 Do you have Docker installed on this computer? https://docs.docker.com/docker-for-windows/install/

The command should handle this case better (prompt you to install docker), but hopefully installing it fixes your problem.

**Comment by fucata55** [comment]
@aldeed thanks for getting back to me.  I might install different docker. I'm going to try to install the  "Docker Community Edition for Windows By Docker" mentioned by your link and come back to you.

**Comment by fucata55** [comment]
The Docker Community Edition for Windows is only for 10 Professional or Enterprise 64-bit. The one that I was using is coming from the Docker Toolbox. Apparently, activating virtual machine technology has to be enabled through BIOS for docker to work. However, during the starting installation, PowerShell is stuck on "Visual Studio Build Tools".

**Comment by aldeed** [comment]
@fucata55 Unclear if there is still a Reaction issue here, but if so, please submit a new issue.
