### ISSUE TITLE
Unable to allow users create theirs shops on Marketplace version

### ISSUE THREAD

**Issue by striletskyy** [reactioncommerce/reaction#4244]
When I'm trying to click "Allow merchant signup"

![screen shot 2018-05-15 at 4 29 30 pm](https://user-images.githubusercontent.com/5245787/40059707-77996b0c-585d-11e8-8503-4fc55ea7c0cf.png)

I'm getting following error 

![screen shot 2018-05-15 at 4 24 53 pm](https://user-images.githubusercontent.com/5245787/40059603-1d614bc8-585d-11e8-8d83-9f110b5f2d5a.png)

```
Node: 8.11.1
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.11.0
Reaction branch: master
```

**Comment by Marcosul** [comment]
Hello, the same problem is occurring for me.

Additionally, any changes to the store data are not saving, generating an error in the browser inspector console. (attachment)


Note: I have two RC applications. These problems only occur in the application that I installed the REST API (simple: rest).

Thank you.


![error-change-shop-field](https://user-images.githubusercontent.com/4714018/40077819-23de2d58-5859-11e8-8278-3cfc2ba1790e.png)

**Comment by nnnnat** [comment]
@Marcosul  I believe the `Promise.await is not a function` error isn't related to this issue. We do have a temporary workaround for that error outlined in this [issue](https://github.com/reactioncommerce/reaction/issues/4202).

**Comment by Marcosul** [comment]
Ok, @nnnnat !! I made my comment in there. ;)

Thanks

**Comment by andriy-styagar** [comment]
Cause of this problem is missing 'active' key in ShopTypes schema.
To fix that we must add this key in file 'plugins/included/marketplace/lib/collections/schemas' and set him Boolean type

**Comment by striletskyy** [comment]
@andriy-styagar it worked, thanks.
