### ISSUE TITLE
Login At Checkout Adds Items To Cart Without Notifying Customer

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4252]
## Issue Description
If you sign in at checkout, and already have a cart associated with your account the items are added (merged) without notification. If users have reached checkout with their current cart, this is what they intend to checkout, and therefore other items should not be added. This is major issue - customers are checking out carts with items they did not expect to be in there.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Sign in, and add items to cart
2. Sign out, and add something else to your cart, and go to checkout
3. Login at checkout, and the items in step 1 will have been added

## Possible Solution
"cart/mergeCart" could be simply modified such that if you have items in your cart already, no further items are merged into it.  I have fixed it locally by editing the `cart/mergeCart` method to set the items for currentCart to those from the cart with the the greatest `updatedAt` value.

### Versions
1.10

**Comment by willmoss1000** [comment]
@aldeed looking at your recent work replacing the `cart/mergecart` method with a GraphQL equivalent it seems the same issue will exist? If someone signs in at checkout, I would suggest the session cart should overwrite the cart associated with the account?

**Comment by aldeed** [comment]
@willmoss1000 While we still have merging as the default mode, you could now update client code to specify a different mode. In your case you are arguing for the "keepAnonymousCart" mode.

We have discussed this a few times, and I think the current plan is to eventually prompt the shopper to choose the merge mode in the UI, since we can't read their mind. I'm positive that there are people who are logging in not expecting their account cart items to be added, and I'm equally positive that there are people who are logging in expecting the opposite.

**Comment by willmoss1000** [comment]
@aldeed that's great that you've built in "keepAnonymousCart"! I'll make changes to my shop to use this when signing in at checkout.

That sounds like a good solution in the longer term. But, for now I think the key point here is at what point in time they choose to sign-in. If they sign in once they have chosen to head to the checkout page "keepAnonymousCart" mode is a must: currently users cannot see the items in the cart at checkout, so items are being merged in without any notice. There is also no way they could confidently remember what they had in their cart last time they signed in.

I realise this seems like a minor issue, but before fixing it locally I had numerous customers checking out with items they didn't expect to have in their cart, and it was pretty frustrating.

**Comment by aldeed** [comment]
@willmoss1000 We agree it's an issue. The new checkout flow is almost done and that should resolve most of these issues, the biggest one being that you'll now definitely see all of the items in your cart very clearly while checking out, and you can remove any you didn't expect while on the checkout page.

**Comment by willmoss1000** [comment]
@aldeed Fantastic! That will be great. Cheers for the help here.
