### ISSUE TITLE
Stripe plugin "stripe/payment/createCharges" call has a hard coded parameter : "authorize"

### ISSUE THREAD

**Issue by fabien-h** [reactioncommerce/reaction#4258]
[The stripe client script](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/payments-stripe/client/checkout/stripe.js) Line 144 :

`Meteor.apply("stripe/payment/createCharges", ["authorize", cardData, cart._id], {`

[The called method is there](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/payments-stripe/server/methods/stripe.js) and takes the `transactionType` as first parameter. But because this is hardcoded, we always have "authorize" and so we set capture to false all the time because of line 235 `const capture = transactionType === "capture";`.

This is a major issue because of [this](https://stripe.com/blog/auth-capture). If you send a charge request with `capture = false;`, the payment is not automatically completed and you have to go capture it by hand.

**Comment by aldeed** [comment]
Capture is a separate step that happens after shipping, so I think this is working as intended. Most companies are required to ship before capturing. If this is a feature request to support auto-capture when the order is placed, please file an issue here: https://github.com/reactioncommerce/reaction-feature-requests/issues
