### ISSUE TITLE
API.Core.loadPackages() runs takes too long with many shops and packages

### ISSUE THREAD

**Issue by zrisher** [reactioncommerce/reaction#4262]
## Prerequisites
* [X] Are you running the latest version? - No, but the relevant code is still present in master
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The `loadPackages()` function in [API.Core](https://github.com/reactioncommerce/reaction/blob/master/server/api/core/core.js#L953) takes approximately 83% of our 35 minute boot time in production. We have 71 shops and 62 packages, of which 13 packages are custom. 

After adding logging and watching the process, no particular shop/package combination takes a disproportionate amount of time. Rather it seems the number of times certain loops must be run that leads to the overall run length. 

The top level of the loop on lines 985-1038, for example, must run 4402 times for our app, because that is the number of entries in the `Packages` collection, since once is created for each Shop X Package combo.

## Steps to Reproduce
1. Start a new application
2. Add a large number of shops (at least 71) and packages (at least 13).
3. Run the application

## Possible Solution
Clearly one solution would be to use less Shops. We are definitely not currently using it as it was originally intended, and we do plan on moving to an implementation with less shops. However, this seems to be a structural issue with the code base if it provides an upper limit on the number of shops the application can use and still run well.

It's also possible that our version of the code is so outdated that this is no longer an issue in production - I've scanned through the differences of `git diff a70495c3c0fe3e3ca1a36d3c31ad075703d87d91 server/api/core/core.js` and it doesn't appear to me anything has changed that would significantly affect this, but I could be mistaken. Unfortunately it's not an easy task to update our whole project to the latest reaction, but if you believe this would make a major difference I can focus on upgrading this particular area of the code.

Another option would be to not run this function as often - it seems its only duty is to update the packages collection with the info from provided fixtures and register.js files. If we know for certain these things haven't changed (e.g. if you're starting any server after the first on a multi-server deploy), it shouldn't be necessary to run this function. Perhaps Reaction could store git hashes of previous loads and skip if already loaded (and git hash isn't dirty).

### Versions
```
Node: 4.8.4
NPM: 2.15.11
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.29.0
Reaction: 1.5.3
```

**Comment by aldeed** [comment]
Resolved in 3.0
