### ISSUE TITLE
Optimize landing page to render within 3 seconds

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4267]
Our agreed upon target for rendering the landing page is 3 seconds based on industry average/standard. (https://www.dynatrace.com/news/press-release/speedy-websites-bring-holiday-cheer-to-shoppers-with-global-retail-websites-ready-to-use-in-3-seconds-or-less/)

Based on our load testing the current "landing page" (the product grid) renders within 5-7 seconds (and even longer on mobile) when using production hosting best practices (CDN, etc). The goal here is to have "first load" be as quick as possible. The implementation of the Catalog brought a HUGE increase in performance but we need to squeeze these last few seconds down.

Note that ticket is focused on the existing Meteor app but I would like to agree on the 3 second target as being a sort of company-wide goal. Obviously open for discussion.

Possible solutions are:

1. Change default grid size to a smaller size
1. Look at what is slowing the current landing page down (using CDN reduces the initial bundle size load time to about 600ms, so it isn't this that is causing the lag any longer). Possibly there are other simple optimizations that could be done.
1. Add a less data-intensive landing page similar to what we do with the swag-shop plugin

**Comment by whimsycwd** [comment]
How to set up CDN? Could me throw me a link or code snippet?

**Comment by whimsycwd** [comment]
Thanks you for fast response. 

Could it works for media like
`https://store.snapmaker.com/assets/files/Media/8NHPPN5LgXTr4Hg5Y/01.jpg?token=eyJhdXRoVG9rZW4iOiJaZF9jSHUtaEpwV0F1NTFPQ1VWeVpBMDVKbm5LMEdsWjRYMmxpeHFjdXBTIn0%3D&store=large`?

Or just css & js file.

**Comment by zenweasel** [comment]
"Out of the box" it's just for the initial JS and CSS files. You would need to extend the media adapter to use Cloudfront/S3

**Comment by whimsycwd** [comment]
Understood. Thank you very much. 

```
  renderMedia() {
    if (this.props.media() === false) {
      return (
        <span className="product-image" style={{ backgroundImage: "url('/resources/placeholder.gif')" }} />
      );
    }
    return (
      <span className="product-image" style={{ backgroundImage: `url('${this.props.media().url({ store: "large" })}')` }}/>
    );
  }
```

I guess. I need to set set a variable. CDN_PREFIX. before  '${this.props.media().url({ store: "large" })}').

But I think for cdn to work there is a pre-condition: Same image of the same build for different session and different user have the same url .  token is different. I will do some trial. But I reckon it will cause problem.

```
First time:
https://store.snapmaker.com/assets/files/Media/8NHPPN5LgXTr4Hg5Y/01.jpg?token=eyJhdXRoVG9rZW4iOiJEQUVwZjY0VXh6M3RHTkphSFl6N2JJbjkxTFI2TFN0VlJOaENpT1VuZG11In0%3D&store=large

=====

Second time
https://store.snapmaker.com/assets/files/Media/8NHPPN5LgXTr4Hg5Y/01.jpg?token=eyJhdXRoVG9rZW4iOiJaZF9jSHUtaEpwV0F1NTFPQ1VWeVpBMDVKbm5LMEdsWjRYMmxpeHFjdXBTIn0%3D&store=large

```

**Comment by zenweasel** [comment]
Ok, this would be a great discussion to carry on in our Gitter channel or on the forums but not on this issue.

We are running our CDN without any issue using basically the instructions from that article.

**Comment by whimsycwd** [comment]
OK, https://forums.reactioncommerce.com/t/reaction-cdn-integration/969 open a thread in fourm.  Really appreciated to get tips from you.

**Comment by zenweasel** [comment]
Won't fix. Client optimization would be handled in the starter kit
