### ISSUE TITLE
Create a system that that allows you create indexes on Collections without modifying core

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4268]
Users should be able to add indexes to collection based on their individual needs without having to modify core code. It would be great if this was something that could be checked into a repo.

**Comment by ticean** [comment]
I understand the need for custom database operations. Cases beyond indexes would be useful, too. I worry that a settings file might be too specific. Versioning and rollback might be problematic.

If we do want to provide framework from core then a mechanism for plugins to hook into the migrations system could be a viable, generic solution?

**Comment by zenweasel** [comment]
Good point. A settings file is probably too simplistic. I've modified the description to be more generic.

**Comment by spencern** [comment]
@zenweasel @aldeed Is this resolved? Do we need docs around it? Is there more work to do here?
We've added the [`collectionIndex` method](https://github.com/reactioncommerce/reaction/blob/master/imports/utils/collectionIndex.js#L9) and that's been used in some plugins such as [shipping surcharges](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/surcharges/server/no-meteor/startup.js#L20)

We've also seen plugins that are using `createIndex` such as the [sitemap generator](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/sitemap-generator/server/index.js#L10)

**Comment by zenweasel** [comment]
@spencern I think as long as this is documented somewhere, this pretty much does the trick as it allows you to add indexes to existing Collections, not just collections you create in plugins

**Comment by aldeed** [comment]
It is in some ways done, but I do want to introduce a better system soon. There are flaws with the current system as far as being able to know when it's safe to access a collection added by another plugin. If your plugin loads first you may be trying to add an index to a collection that is not yet defined. Moving all collection and indexing definition to `registerPackage` and doing it as a separate startup step before running plugin startup functions will resolve this.

**Comment by spencern** [comment]
@aldeed we can revisit this during the Developer Experience pod coming up.

**Comment by aldeed** [comment]
Done in 2.0.0
