### ISSUE TITLE
Create "disable admin login" option for hosting consumer-only instances

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4269]
Many users may wish to host their consumer-facing and admin instances separately to enforce better security. A simple way to enforce this would be to allow settings a "disableAdminLogin" flag should would not allow anyone with any admin permissions set to login to a particular instance thus making the public instance (somewhat) hardened against any attack that requires admin access. I don't really see a need to an "adminLoginOnly" option as the inverse as usually this would be in a VPC.

A more hardened approach would be to do this checking at the method-level to harden against "elevation or privileges" attacks.

**Comment by aldeed** [comment]
Closing this as resolved by having split storefront UI into a separate instance in 2.0
