### ISSUE TITLE
PaginatedOrders db query is inefficiently formed

### ISSUE THREAD

**Issue by zrisher** [reactioncommerce/reaction#4271]
## Prerequisites
* [X] Are you running the latest version? - No, but the relevant code is still present in master.
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The `Orders` query produced by the `PaginatedOrders` publication takes a very long time with many orders, even if a limit is provided. The db average execution time for the query is scaling with the size of our orders collection (even though we provide a limit of `10`), and has steadily increased to the current 5.5 seconds after a few months of production use.

## Steps to Reproduce
1. Add about 10,000 orders to the database
2. Log in as admin
3. View the orders dashboard

## Possible Solution
In [`createAggregate()` at server/publications/collections/orders.js#L18](https://github.com/reactioncommerce/reaction/blob/master/server/publications/collections/orders.js#L18)
* The `limit` stage should come before the `projection` stage because projection is expensive.
* The `sort` stage should come before the `projection` stage so it can use indices.

### Versions
Much earlier version, but relevant code is the same in master.

```
Node: 4.8.4
NPM: 2.15.11
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.29.0
Reaction: 1.5.3
```

**Comment by zrisher** [comment]
I have a fix for this that we'll have live soon. If it works well I will submit as a PR.

**Comment by zenweasel** [comment]
@zrisher I think you might want to look at the current version, it handles orders differently so they are paginated and are responsive for me with way more then 10k orders. These comments about how the pipeline is formed still seem valid though.

**Comment by zrisher** [comment]
@zenweasel The `PaginatedOrders` publication uses the `createAggregate()` function directly - the above comments are all relevant to the latest code.

It's interesting that you have more orders and aren't experiencing this issue. The main place where this problem pops up for us is when admins try to view the Orders dashboard - it's limited to 10 entries, but the projection stage still runs on all 10k orders documents, and with 10 servers all using the same DB that really starts to slow down. 

Can you confirm you're able to load that page without issue with more than 10k orders? If so, would you mind providing a sample Order document so I can compare? Maybe we're storing too much data.

**Comment by zenweasel** [comment]
@zrisher You can use the [reaction-devtools](https://github.com/reactioncommerce/reaction-devtools) plugin to load in orders to see what I am seeing. The problem that was fixed (by @glmaljkovich)  was not in the query but in pushing ALL the data down to the client. The current code only sends the relevant data which made the order panel responsive with any number of orders. Maybe that's not the problem you are experiencing and it sounds like your slowdown is more server-side?

If you have ways of optimising the current order pipeline, I'd love to look at that too.

**Comment by zenweasel** [comment]
Also, i do believe @glmaljkovich made some some changes to the query as well. I'm pretty familiar with this code as I wrote most of it.

**Comment by zrisher** [comment]
@zenweasel Thanks for taking a look. Yes I saw you wrote much of this code. You added the limit and @glmaljkovich added the sorting and skipping:

![image](https://user-images.githubusercontent.com/1958130/40518215-5976eb64-5f6e-11e8-958a-eb959aea5483.png)

The slowdown we're experiencing is definitely on the DB side - the instigator for this investigation was the top Slow Query on our db:

![image](https://user-images.githubusercontent.com/1958130/40518343-f678fe70-5f6e-11e8-8597-fdd9c049c663.png)

As you can see, it's up to a 7 second execution time on average, which is pretty bad.

Here's mLab's guidance on the issue:

> For this query, we recommend reordering the aggregation so that the project stage is after the $limit stage in the pipeline. That way, the number of documents it needs to transform are as few as possible. Note, the $sort stage is also unable to use an index if it's preceded by a $project stage (https://docs.mongodb.com/manual/reference/operator/aggregation/sort/#sort-operator-and-performance).

My best guess as to why you're not experiencing the same issue with more orders is that your documents are smaller. Running `db.getCollection('Orders').stats()` on our production DB, I found our average object size to be 58,839 bytes. Can you confirm yours?

**Comment by zenweasel** [comment]
Yes, our test db average order object size is only 5111.

**Comment by zrisher** [comment]
That would do it. : ) It definitely looks like we have some optimizations to do on our object size, but regardless this change is a performance improvement. PR submitted.

**Comment by zenweasel** [comment]
Thanks. Great feedback!!

**Comment by aldeed** [comment]
I believe this has been improved since this issue was filed. It is still not great, but it won't be fixed because it's being replaced by orders GraphQL query.
