### ISSUE TITLE
update docker image page explanation

### ISSUE THREAD

**Issue by hbakhtiyor** [reactioncommerce/reaction#4275]
in [the page](https://hub.docker.com/r/reactioncommerce/reaction/) written that `MONGO_URL` env is optional, but it isn't

**Comment by aldeed** [comment]
@ticean

**Comment by aldeed** [comment]
@spencern The new task here is to go into every repository listed [here](https://hub.docker.com/u/reactioncommerce?page=1), edit the page content, and paste in the following content. Feel free to adjust. I think it should be short and use only link addresses that are unlikely to change.

---

Reaction Commerce is an open source commerce platform that allows anyone to customize, extend, and deploy an online store of any size. Find out more at [reactioncommerce.com](https://reactioncommerce.com) or our [documentation site](https://docs.reactioncommerce.com). Developers, check out our [development platform](https://github.com/reactioncommerce/reaction-development-platform) to get started.

**Comment by spencern** [comment]
On it.

**Comment by spencern** [comment]
Updated all Docker repo descritions.
