### ISSUE TITLE
Reaction-Accounts Issues In Marketplace

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4277]
## Issue Description
Reaction-Accounts can't have been tested for use in marketplace except as primary shop owner:

i) If you are not the primary shop owner and you invite a shop-manager they do not show up, and visa-versa.

ii) Then, as part of a wider issue, when acting as admin on behalf of another shop you are unable to edit anything except products, or accounts. You cannot see the shop-data for shipping, shop settings or anything from other packages.

## Steps to Reproduce
1. Create a shop (not primary) and invite shop manager - note they don't show up as a "shop manager" in the Accounts Table
2. Login as shop-manager. You first have to click the drop-down to make anything happen.
3.  Then try to change shop details, or shipping settings etc.

## Possible Solution
i) Changes to the accounts publication
ii) Fix for users acting as Admins of other shops (you face the same issue when acting as primary admin and trying to edit the shop-details for a particular shop.

### Versions
1.10

**Comment by aldeed** [comment]
Marketplace plugin no longer built in
