### ISSUE TITLE
Catalog collection needs proper schema

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#4283]
## Issue Description
The new Catalog collection needs a proper schema created. [current schema](https://github.com/reactioncommerce/reaction/blob/release-1.14.0/imports/collections/schemas/catalog.js)

**Comment by spencern** [comment]
@nnnnat @aldeed Do we have enough information about the catalog to create a proper schema at this point? I'd like to get this scheduled in the next sprint if so.

**Comment by aldeed** [comment]
@spencern Yes, the schema is pretty evident when looking at `/imports/plugins/core/catalog/server/no-meteor/utils/createCatalogProduct.js`

**Comment by kieckhafer** [comment]
@aldeed For the following itmes, do we just do an `Object` blackbox, or should I break them down into their own sub-schemas?

`media`
`price`
`pricing`
`primaryImage`
`socialMetadata`
`variants`

**Comment by aldeed** [comment]
@kieckhafer Everything should have subschemas, no blackbox, but you can have `variants` and `options` share a single schema, where `optionTitle` is optional. This is how we do it in the GraphQL schema.

I think the GraphQL schema is also the best place to see what should be required. The two schemas are a very close match now. Take your best guess and then I can review this and see if any jump out at me as incorrectly required/optional.
