### ISSUE TITLE
Create contextual and universal alerts framework

### ISSUE THREAD

**Issue by saralouhicks** [reactioncommerce/reaction#429]
New alerts framework should include:

1) a standard placement for user notification
2) contextual / inline placement for validation/specific event error

**Comment by aaronjudd** [comment]
@mikemurray We should consider potential reuse for #78 as well.

**Comment by rymorgan** [comment]
@mikemurray Next steps. Can you show me the different alert frameworks we're using and we can give them some visual polish and make them consistent.

**Comment by mikemurray** [comment]
### Bootstrap alerts (inline on page)
https://getbootstrap.com/components/#alerts

![screen shot 2016-12-09 at 11 42 44 am](https://cloud.githubusercontent.com/assets/42217/21062231/b67dd104-be04-11e6-8d8d-d30ff55956c8.png)

### Sweet Alert (alert popup / confirmation dialog)
http://t4t5.github.io/sweetalert/

![screen shot 2016-12-09 at 11 43 50 am](https://cloud.githubusercontent.com/assets/42217/21062249/cce6dca6-be04-11e6-8fab-8840f13b8745.png)

### S-Alert (toasts)
http://s-alert-demo.meteorapp.com/

![screen shot 2016-12-09 at 11 44 57 am](https://cloud.githubusercontent.com/assets/42217/21062286/f3b3c9e8-be04-11e6-8cb6-8c37e89da031.png)

### Tooltips
Custom

![screen shot 2016-12-09 at 11 45 41 am](https://cloud.githubusercontent.com/assets/42217/21062310/19d1e65a-be05-11e6-8ef1-dccf00955c0b.png)

**Comment by aaronjudd** [comment]
Closing - insufficient details.
