### ISSUE TITLE
Shop owner invite for existing user is still being asked to set password

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#4294]
## Issue Description
When a shop owner invite is sent to an existing user, clicking 'Get Started' in the email redirects to the website where user is asked to set password.

## Steps to Reproduce
1. Enable Marketplace feature.
2. Invite an existing user (possibly the marketplace admin.)
3. Click the 'Get Started' button in the email received.

## Possible Solution
Do not display the Set Password modal if user is not new.

### Versions
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.11.0
Reaction branch: master

**Comment by aldeed** [comment]
Marketplace no longer built in, and I don't see this happening with invites in general
