### ISSUE TITLE
Catalog migration fails when no position data exists

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4299]
## Issue Description
Migration fails on startup on first start after migration to v1.12.0

Get this error
```
0|reaction | TypeError: Cannot convert undefined or null to object
0|reaction |     at Function.keys (<anonymous>)
0|reaction |     at items.forEach (imports/plugins/core/versions/server/migrations/25_update_catalog_schema.js:28:12)
```

## Steps to Reproduce
1. Start Reaction with a previous version and load data
1. Upgrade to v1.12.0
1. Observe error on startup. Migrations become locked

### Versions

Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0

**Comment by aldeed** [comment]
@spencern We should probably hotfix this in 1.12.1. It fails the migration if you have products that were never manually positioned (or for some reason don't have a `positions` object on them).

**Comment by spencern** [comment]
@aldeed Let's plan on that.
