### ISSUE TITLE
Cannot save Open Exchange Rates API key without also setting Cleanup Schedule

### ISSUE THREAD

**Issue by loanlaux** [reactioncommerce/reaction#4303]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
As an admin, saving an Open Exchange Rates API key in the Shop settings pane without a Cleanup Schedule fails with the following error: "Shop external services settings update failed. Error: Cart is required."

## Steps to Reproduce
While logged in as an admin:
1. Open Shop pane from the admin sidebar
2. Past Open Exchange Rates API key in the appropriate field
3. Leave the Cleanup Schedule field empty
4. Error shows up as a toast

## Possible Solution
If Cleanup Schedule works hand in hand with the Open Exchange Rates API: output a more meaningful error message, such as "Shop external services settings update failed. Error: Cleanup Schedule is required." Or make sure that the default "older than 3 days" value is applied when the Cleanup Schedule field is empty.

If Cleanup Schedule isn't necessary for Open Exchange Rates to work, simply remove the "required" condition for the Cleanup Schedule field.

### Versions
```
Node: 8.7.0
NPM: 6.1.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.12.1
Reaction branch: master
Docker: 18.03.1-ce
```

**Comment by aldeed** [comment]
These are both removed in 3.0
