### ISSUE TITLE
Reaction not running on OS X with latest node (9.11.1).

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#4309]
@nicroto commented on [Thu Apr 12 2018](https://github.com/reactioncommerce/reaction-docs/issues/569)

I followed the Installation guide for OS X, but I was unable to run Reaction.

The first issue I hit was related to meteor breaking due to running out of memory. I found [this solution](https://github.com/reactioncommerce/reaction/issues/3023#issuecomment-342510093).

But then starting up reaction still wasn't working. This is the (summary of the) output on that run:

```
tsenkov$ TOOL_NODE_FLAGS="--max-old-space-size=2048" reaction
Setting up plugin imports...

Installing dependencies for connectors-shopify...

up to date in 0.083s
Setting up style imports...

Provisioning assets...

[[[[[ ~/build/reaction ]]]]]

=> Started proxy.

Unable to resolve some modules:

  "@babel/runtime/helpers/objectSpread" in /Users/tsenkov/build/reaction/imports/plugins/core/collections/lib/validation.js
(web.browser)

...

Unable to resolve some modules:

  "@babel/runtime/helpers/builtin/objectSpread" in
/Users/tsenkov/build/reaction/imports/plugins/core/collections/lib/validation.js (os.osx.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime

/Users/tsenkov/build/reaction/.meteor/local/build/programs/server/boot.js:475
}).run();
   ^

Error: Cannot find module '@babel/runtime/helpers/builtin/objectSpread'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.require (/Users/tsenkov/build/reaction/.meteor/local/build/programs/server/boot.js:288:32)
    at makeInstallerOptions.fallback (packages/modules-runtime.js:651:18)
    at require (packages/modules-runtime.js:244:16)
    at generator.js (/Users/tsenkov/build/reaction/.meteor/local/build/programs/server/packages/boilerplate-generator.js:26:45)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /Users/tsenkov/build/reaction/.meteor/local/build/programs/server/packages/boilerplate-generator.js:388:15
    at /Users/tsenkov/build/reaction/.meteor/local/build/programs/server/packages/boilerplate-generator.js:395:3
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

I asked about this in the [gitter room](https://gitter.im/reactioncommerce/reaction?at=5acf1d826bbe1d2739dab001) and after a couple of attempts at fixing it, it turned out the issue is related to me running latest version of node.

So trying to setup Reaction with the default instructions on OS X, doesn't work if you are running latest (9.11.1) node. The version that worked for me 8.9.4, was suggested in the gitter room. 

I thought this should be logged as an issue in Reaction (even if it is Meteor or Node issue, someone needs to keep track of it in Reaction, so you know what to suggest users to do during setup), but I was told this would be a more suitable place for the issue to be logged at. So perhaps the docs should be updated with a notice about the problem?

And the first thing I've hit (the meteor/node memory issue) - I think this is also a good candidate for either automation within the `reaction run` cli command, or if not possible - again, a note in the docs.

In any case, thanks for working on this project - just made an extensive research and (as I am sure you already know) there is nothing quite like it in the node ecosystem. If I end up using Reaction I will do my best to help out and contribute back to the project as much as I can.

Cheers!

---

@nicroto commented on [Thu Apr 12 2018](https://github.com/reactioncommerce/reaction-docs/issues/569#issuecomment-380810599)

This is should be relevant: https://forums.meteor.com/t/cannot-find-module-babel-runtime-helpers-builtin-objectspread-after-update-meteor-to-1-6-1-1/43034/3

**Comment by zenweasel** [comment]
I think there are known issues with Node 9. It's neither LTS nor current right? Meteor itself uses it's own version of Node which has to be 8.9.4

I think this is closed with either `will not fix` or it's not an issue

**Comment by zenweasel** [comment]
I think the reason this was in Docs was because the issue is just to document that it will not work with 9, you need to run the "Stable" version of Node.

**Comment by machikoyasuda** [comment]
@zenweasel Ah - got it. Will add a ticket specifying the latest stable Node version (8).
