### ISSUE TITLE
No native CDN support for production bundle in Reaction.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4315]
## Issue Description
After creating the production bundle from reaction, if the user wants to serve the bundled `js` and `css` files, there is not native way to do it.

## Steps to Reproduce
1. Build the production bundle from reaction using `meteor build --directory "<build dir>"` 
1. `cd "<build dir>"/bundle/programs/server`
1. `npm install`
1. `cd "<build dir>"/bundle`
1. `PORT=4000 ROOT_URL=http://localhost.com node main.js`

Browse to the URL and see that the `js` and `css` files are served from the server. But if you want to upload it to CDN and serve the files from there, there is no way to do it.

**Comment by zenweasel** [comment]
Closed via #4316
