### ISSUE TITLE
Celebrate Reaction Commerce gets 1000 stars

### ISSUE THREAD

**Issue by kefirchik** [reactioncommerce/reaction#432]
congrats and have fun! :+1: 
![reaction1kstars](https://cloud.githubusercontent.com/assets/6573628/8833848/92f44a44-30b9-11e5-8e37-c82fb90a526a.png)

**Comment by kefirchik** [comment]
:beers: Cheers!

**Comment by kefirchik** [comment]
Also will celebrate 0 issues count! :laughing:

**Comment by aaronjudd** [comment]
:+1: :100: 

@kefirchik then what would we do!?

**Comment by kefirchik** [comment]
I think we'll take some beer in the best bar ever in Los Angeles :wink: (actually I dont drink but it is special case)

**Comment by kefirchik** [comment]
If so I'll treat drinks for everybody :cocktail:

**Comment by psy21d** [comment]
Congratulations!

**Comment by kefirchik** [comment]
Ok, sorry for offtopic :thought_balloon: I'll close it for now and reopen when zero issues milestone will be reached :smile:

**Comment by aaronjudd** [comment]
Free beer??  Ok, we're in!
