### ISSUE TITLE
npm audit

### ISSUE THREAD

**Issue by jbolila** [reactioncommerce/reaction#4332]
## Prerequisites
* [Y] Are you running the latest version?
* [Y] Are you able to consistently reproduce the issue?
* [Y] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

Security issues found during `npm install -g reaction-cli`

## Steps to Reproduce

```bash
npm install -D reaction-cli
npm WARN deprecated command-exists@1.2.2: Potential security vulnerability fixed in v.1.2.4
#..

+ reaction-cli@0.29.0
added 46 packages from 37 contributors, updated 1 package and audited 27813 packages in 19.912s
found 109 vulnerabilities (66 low, 41 moderate, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

## Possible Solution

Update the decency tree.

### Versions

```text
Node: 10.4.1
NPM: 6.1.0
Reaction CLI: 0.29.0
Reaction: 1.12.1
Reaction branch: master
Docker: 18.03.1-ce
```

**Comment by spencern** [comment]
@jbolila Thanks for the report here. As part of our CI process, we're using `synk` to check for potential vulnerabilities in our dependency tree. We maintain a `.snyk` file which should catalog any vulnerabilities that we're waiting on updates for and the reasons that they have not been update yet.

**Comment by aldeed** [comment]
CLI is no longer used for 2.0.0
