### ISSUE TITLE
Update to Meteor 1.7.0.3

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4341]
## Goal

To get on latest Meteor release with Node security update.

https://github.com/meteor/meteor/blob/devel/History.md

## Work

- Update base docker image to Meteor 1.7.0.3 and Node 8.11.3
- Update both Dockerfiles in main repo to new base image, Meteor 1.7.0.3, and Node 8.11.3
- Run `meteor update` in main repo to Meteor 1.7.0.3

Merge all of this into `release-1.14.0` branch

**Comment by impactmass** [comment]
Prerequisite for this task is this https://github.com/reactioncommerce/base/issues/30 (currently in progress).
