### ISSUE TITLE
Catalog dashboard panel is empty

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4346]
## Prerequisites
* [x] Are you running the latest version? - release candidate 1.13.0
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The "Catalog" panel in the operator dashboard is empty since `v1.13.0` and should be removed.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Login as an operator
2. Open the "Catalog" dashboard panel

## Possible Solution
This seems to have been caused when we removed revision control as that was the only controller in the Catalog panel.

### Versions
```
Node: 9.11.1
NPM: 5.6.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.0
Reaction branch: release-1.13.0
Docker: 18.03.1-ce
```

**Comment by willopez** [comment]
@spencern the objective of this issue is just to remove the catalog menu item correct? not the plugin, as there is many functions in the catalog plugin
