### ISSUE TITLE
Ability to remove a product from home page & add a home page tag

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/reaction#4349]
## Issue Description
Currently, all products show up on the home page by default.  The operator can then add additional tags to categorize these products and have them show up on the nav as needed.  But there is no easy way for the operator to show or hide products from the home page.  Following the current navigation structure, since the products show up on the home page by default; it would be ideal if products have a default tag of "home".  This would allow operators to add or delete products from the home page as needed.

## Possible Solution
- Add "home" tag to products upon creation by default.
- Allow operators to add or delete "home" tag
- Don't show the "home" tag to the consumers when they hit the PDP (under the Tags section)

### Versions
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.0
Reaction branch: master
Docker: 18.03.1-ce

**Comment by aldeed** [comment]
In 2.0.0, there is an example storefront and you are expected to customize it with your own home page.
