### ISSUE TITLE
Share buttons always the primary shop's credentials in product pages

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#4352]
## Issue Description
Share buttons in product pages always use the social credentials of the active shop. So, if you are browsing as a guest, product pages will always use the primary shop's credentials.

## Steps to Reproduce
1. As admin, turn on the marketplace feature. Invite a shop owner and activate the new shop.
2.  As shop owner, create a product and publish.
3. As a guest, browse products from the primary and other shops. The credentials used in the social buttons are always those of the primary shop.

## Possible Solution
Some options:
1. Create a new publication for packages that should be public regardless of active shop, or
2. Modify the current global Package publication to include public packages independent of the active shop, or
3. Maybe have only 1 set of credentials for the entire marketplace and remove support for individual credentials per shop

### Versions
```
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.0
Reaction branch: fix-4205-ajporlante-marketplace-social-settings-permissions
Docker: 18.03.1-ce
```

**Comment by willmoss1000** [comment]
Option 3 is a great improvement on how it works currently - No marketplace user will input an API key for facebook to work.

**Comment by ajporlante** [comment]
For Facebook, I think you are correct @willmoss1000 . But for twitter for example, only the twitter user handle is required in the dashboard and it's nice to have the actual shop owner's twitter handle included in the tweet when product is shared by a customer.

**Comment by willmoss1000** [comment]
Is it possible to use the API key from the primary shop owner, so if they are a merchant they just have to put in their handle? It's pretty intimidating for users otherwise, and will stop them filling out any of the social details.

**Comment by aldeed** [comment]
Share buttons are no longer a built in feature
