### ISSUE TITLE
Rolling back to previous Reaction version causes app to not start

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4362]
## Issue Description
If you move to the current version and then decide you need to roll back for any reason, and that newer version contained a migration, the app will not start with the following error:

```
web_1  | 01:42:37.917Z  INFO Reaction: JobServer started
web_1  | 01:42:38.668Z  WARN Reaction: Skipped loading settings from reaction.json.
web_1  | 01:42:39.692Z  INFO Reaction: Reaction Version: 1.12.1
web_1  |
web_1  | /app/programs/server/node_modules/fibers/future.js:280
web_1  | 						throw(ex);
web_1  | 						^
web_1  | Error: [Can't find migration version 26]
web_1  |     at Object.Migrations._findIndexByVersion (packages/percolate_migrations.js:293:9)
web_1  |     at Object.Migrations._migrateTo (packages/percolate_migrations.js:209:23)
web_1  |     at Object.Migrations.migrateTo (packages/percolate_migrations.js:167:10)
web_1  |     at Hooks.Events.add (imports/plugins/core/versions/server/startup.js:18:14)
web_1  |     at /app/programs/server/npm/node_modules/@reactioncommerce/hooks/dist/main.js:71:14
web_1  |     at Array.reduce (<anonymous>)
web_1  |     at Object.Hooks.Events.run (/app/programs/server/npm/node_modules/@reactioncommerce/hooks/dist/main.js:70:22)
web_1  |     at Object.init (server/api/core/core.js:62:18)
web_1  |     at startup (server/startup/index.js:46:12)
web_1  |     at Function.time (/app/programs/server/profile.js:309:28)
web_1  |     at /app/programs/server/boot.js:427:13
web_1  |     at /app/programs/server/boot.js:472:5
web_1  |     at Function.run (/app/programs/server/profile.js:510:12)
web_1  |     at /app/programs/server/boot.js:470:11
```

## Steps to Reproduce
Using docker or a local installation roll forward to version 1.13.0, and then roll back to version 1.12.1.

## Possible Solution
The code that looks for migrations needs to be in a `try/catch` and throw an error but not stop the app from starting. Since the migration package we use is a Meteor package not sure if we want to either pull the package in or PR the change.

**Comment by aldeed** [comment]
This is another argument in favor of moving migrations out of the main app. Usually you would want the app to fail to start if the db is on an incorrect version. Then you would manually migrate up/down and then restart.

We could think about using this npm pkg: https://github.com/tj/node-migrate

The existing migrations would need to be adjusted a bit to not use Meteor code, but there is not very much code there.

**Comment by zenweasel** [comment]
Yeah, there are lots of non-Meteor packages that have a lot more features, one of the main ones being the ability to run the migrations manually from the command line. I don't even see a way to unlock the migrations once they lock without just editing the db manually

**Comment by aldeed** [comment]
There is an npm fork of the percolate package Reaction currently uses, so we maybe should start by switching to that. It has some newer fixes vs. the Meteor package. We will have to rewrite all of the existing migrations to be non-Meteor.

https://github.com/emmanuelbuah/mgdb-migrator

**Comment by aldeed** [comment]
For a quick fix to just this bug, I suggest we do something like this in `/imports/plugins/core/versions/server/startup.js`:

```js
Hooks.Events.add("afterCoreInit", () => {
  const currentDBVersion = Migrations._getControl().version;
  const latestVersionInList = Migrations._list[Migrations._list.length - 1].version;

  // This usually only happens in development when switching branches.
  if (currentDBVersion > latestVersionInList) {
    Migrations._setControl({ locked: false, version: latestVersionInList }); 
  } else if (!Meteor.isTest) {
    Migrations.migrateTo("latest");
  }
});
```

Someone can try this and verify that it fixes the issue. (The `Meteor.isTest` change is another unrelated change I've been thinking we should do.)

**Comment by impactmass** [comment]
Posting some PR comments about the direction of this task:

From @zenweasel: 
> I think @aldeed had also mentioned that stopping the app from running might be the expected behavior rather than letting the user run the app with the database in an unknown state. I see good arguments for each, but I would def bump the Log level to error or fatal because there is not-small chance your app will completely not work.

From me:
> Thinking (again) about the argument for & against this decision, I think I now lean towards the behaviour of preventing the app from starting (if the DB is in a different state).
Since Migrations are still built-in to the app right now, it makes sense that app startup is prevented. When Migrations becomes a separate entity, then the decision can change.

Zenweasel:
> Maybe it should not start but also not lock the db?

Me:
> Well... the locking is as a result of the failed attempt to run the Migration (which is also what prevents the app from starting). Except if we write code to check the versions before calling MigrateToLatest. And if we find that the DB version is not compatible, we then make the app exit (and add an error description about why).
That way it doesn't lock too. What do you think?

**Comment by zenweasel** [comment]
Maybe stop the app from loading but allow a command line flag to allow it to be forced to start?

**Comment by impactmass** [comment]
@zenweasel I've update the PR according to the discussion here so far plus a follow-up based on the command line flag.
