### ISSUE TITLE
Top Navigation Safari Missing Tag Navigation

### ISSUE THREAD

**Issue by stunjiturner** [reactioncommerce/reaction#4367]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [ x] Are you running the latest version?

* [ X] Are you able to consistently reproduce the issue?
* [ X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The top level navigation does not show in safari 11.1.1. Mac OS X High Sierra, I tested in firefox quantum on Mac OS X High Sierra works fine, as well as chrome

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Goto my heroku site tribevibe.herokuapp.com
2. After the shop name, looking for top level tag navigation
3.

## Possible Solution

<div class="tag-group"></div> is empty?

### Versions
Reaction: 1.13.0

**Comment by spencern** [comment]
Hi @stunjiturner is this reproducible with a stock installation of Reaction?

**Comment by stunjiturner** [comment]
Will power up a new one, and get back to you. It was a fresh one 1.13.0

S Tunji Turner
sightuary
@sightuary

**Comment by aldeed** [comment]
This UI is removed in 2.0.0
