### ISSUE TITLE
refactor location and currency lookups

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#437]
Refactor currency and location lookups to a stable solution for beta. These are both error prone, and rely on sub optimal solutions. Functionality should essentially remain the same, but optimized with #248

**Comment by queso** [comment]
@aaronjudd: With this one, the functionality current works, we just want to refactor it? Or are there known bugs? 

It looks like the second post in #248 outlines most of the work you want?

**Comment by aaronjudd** [comment]
yes, #248 covers a workflow that would at least be more reliable and not block/fail as easily, but I also think it'd be better to rely on on Google API might be more accurate.  Re the currency source, it's a tough call because I don't know of any good endpoints for currency conversion. There's some crazy hacks where google translate is used, by stripping out the html the translate page returns, as there isn't an officially supported api.  I'm open to new solutions because the current source is not trustworthy.

**Comment by aaronjudd** [comment]
also meant to investigate if aldeed:geocoder could replaced with the mdg: geolocation, but haven't really looked into it - only if it was something better/faster

**Comment by queso** [comment]
I have some experience with using the cordova geolocation package, which I think the mdg package relies on, will take a look.

**Comment by aaronjudd** [comment]
Also if we continue to use google, we should add some configuration for google api settings, to prevent:

```
I20150820-00:35:55.354(0)? {"name":"core","hostname":"box418","pid":11823,"level":30,"msg":"Error in locateAddress for latitude/longitude lookup (26.352498,-89.25293):Status is OVER_QUERY_LIMIT. You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/","time":"2015-08-20T00:35:55.354Z","v":0}
```

**Comment by spencern** [comment]
We should probably stub out those methods that are reliant on another API in our test regardless of which geolocation package we end up using.

**Comment by aaronjudd** [comment]
@spencern good point - I'm slowly slogging through some basic end to end tests (in the accounts branch) - I'll add a mock for this.
