### ISSUE TITLE
Approve or Cancel Invoice has no effect in the ability of sellers to ship products (Orders)

### ISSUE THREAD

**Issue by alexandros84** [reactioncommerce/reaction#4372]
## Issue Description
Sellers who are processing their orders are able to click "All Items Packed" and then "Shipped" without first having Captured Payment from the Approve button in Invoice. According to the logic described in Reaction Docs https://docs.reactioncommerce.com/reaction-docs/master/orders-admin this seems like an issue. 

## Steps to Reproduce
1. From Dashboard go to Orders
2. There click on the right-pointing arrow next to any order whose status is New or Processing
3. In the resulting Summary/Invoice/Shipping UI go straight down to Shipping
4. There click consequentially "All Items Packed" -> "Shipped" and the status of the Order will change to Completed without the seller ever having to approve the Invoice.

## Possible Solution
Possibly create a flag that will render the "All items packed" button disable if not approved.

### Versions
(run `reaction -v` from your reaction directory)

**Comment by kieckhafer** [comment]
@aldeed is this something that I should address in #5158 ? Or are we viewing payments and shipments completely separate now, where this ticket should be closed, and this should be addressed individually on a case-by-case basis if an operator wants this behavior?

**Comment by aldeed** [comment]
@kieckhafer Agree they should be completely separate. We do want to eventually add customizable workflows that could force things to happen in a certain order, but for now I don't think it makes sense to hard code such logic.
