### ISSUE TITLE
Users can't extend Catalog

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4373]
## Issue Description
Currently the `publishToCatalog` methods use hardcoded values for denormalizing products to the catalog which means that any additions to the Product schema/db are lost.

There needs to be some way to allows uses to extend the catalog schema along with the products schema

## Possible Solution
1. Provide a mapping schema that users can extend that combines with our mapping schema. Possibly using an external tool.
1. Allow the user to provide an optional mapping object that maps their additional fields to fields in the catalog including functions for transformations.

### Versions
All versions after 1.11

**Comment by dancastellon** [comment]
While not the solution to this issue, I've been able to get around this for the time being by creating an "after" method hook for the core "catalog/publish/products" method that copies my custom fields from the Products collection over to the Catalog.

**Comment by janus-reith** [comment]
@dancastellon Would you mind sharing your implementation?

**Comment by zenweasel** [comment]
Closing in favor of https://github.com/reactioncommerce/reaction/issues/4725 which has been solved.
