### ISSUE TITLE
Disable "Add to cart" button for sold out options on customer PDP

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#4376]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Sold out options are not marked as sold out and if you click "Add to cart" you'll see a message as if it had been added to the cart. The sold-out item is never added to the cart only a toast message appears.

## Steps to Reproduce
1. Spin up a fresh RC shop, log in as an admin and create a new Product with a sold out option.
2. In another browser as a customer view the new products PDP
3. See the sold out badge is not on the option
4. Select the sold out option and click "add to cart", see the toast that an item has been added to the cart.
5. view the cart to see it's actually empty

## Possible Solution
Now that #4342  has been merged the Catalog variants and options should have the correct "isSoldOut", "isLowQuantity" properties and should now be able to display sold out/backorder badges as well as disable the "Add to cart" button if a sold-out option has been selected.

### Versions
```sh
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
```

**Comment by aldeed** [comment]
Fixed in 2.0.0
