### ISSUE TITLE
Catalog query during "addToCart" is slow/inefficient

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4377]
## Issue Description
Using the "retailer" dataset when doing add to cart, this query is taking around 7 seconds to complete.

![catalog_query](https://user-images.githubusercontent.com/72819/42005750-ba9bdc42-7aa8-11e8-8daa-5c715482075f.png)

## Steps to Reproduce
1. Load the "retailer" dataset.
1. Add an item to the cart
1. Observe that the query takes too long (should at most be <1 second)

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
Reaction Version: 1.13.0

**Comment by Akarshit** [comment]
I have added the index to the `retailer` dataset to make this faster, So now the query time < 300ms.

**Comment by aldeed** [comment]
Note that this query has changed in PR #4412 

```js
const catalogProductItem = await Catalog.findOne({
    "product.productId": productId,
    "product.isVisible": true,
    "product.isDeleted": { $ne: true },
    "isDeleted": { $ne: true }
  });
```

An index on `"product.productId"` should be sufficient.

**Comment by zenweasel** [comment]
Outdated. From 1.X load testing
