### ISSUE TITLE
Redundant queries in "addressBookAdd".

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4379]
## Issue Description
Tracing the application under load we see that the `Cart` collection is fetched **at least** 32 times. Each individual query is very fast (~50ms) but repeating them over and over is still resource/time-intensive

## Steps to Reproduce
1. Add an item to cart when Kadira trace is enabled
2. Watch the trace 
3.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
Reaction 1.13.0

**Comment by aldeed** [comment]
This was fixed at some point
