### ISSUE TITLE
Number of documents in Account collection affecting startup time

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4384]
## Issue Description
As the number of documents(belonging to group "customer") are increased in the database, the startup time of reaction slows down.
Here are some stats
1. Number of Accounts - 100,000 - startup time - 30sec
1. Number of Accounts - 300,000 - startup time - 120sec
1. Number of Accounts - 500,000 - startup time - didn't start in 5 mins
1. Number of Accounts - 2,100,000 - startup time - got `Range Error` which is error when the you exceed the size limit of mongo.

## Steps to Reproduce
To reproduct these, you would have to connect the load-testing mongo server. Please contact me for that.

## Possible Solution
Maybe we are getting all Accounts somewhere during the startup or doing something similar.

**Comment by zenweasel** [comment]
Could this be Search trying to create the `AccountSearch` collection?

**Comment by Akarshit** [comment]
This issue is because of [this](https://github.com/reactioncommerce/reaction/blob/release-1.14.0/imports/plugins/core/core/server/Reaction/addRolesToGroups.js#L13) function that is called on startup.

**Comment by zenweasel** [comment]
@Akarshit Could this be moved into a job to be done async or is this method required to run before the app can start?

**Comment by Akarshit** [comment]
I didn't do much research on it, I was just looking for a quick way to fix this and found that commenting that function does that.

**Comment by zenweasel** [comment]
This is pretty impactful because this affects deployment time and can cause deployments to fail because the app takes so long to start.
