### ISSUE TITLE
Optimize db queries in "cart/submitPayment"

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4386]
## Issue Description
Under higher load this method gets really slow (> 90 seconds). Looking at the traces there are multiple places where this can be optimised:

1. Multiple redundant queries for `Packages` including looking for `reaction-taxes` and `taxes-avalara` even though neither are enabled.
1. Multiple queries for `Shop` even though Shop should not be modified during this operation
1. Multiple db operations on `Inventory` even though we don't use this data.
1. `Cart.update` takes > 43 seconds. Investigate why
1. `Orders.insert` takes > 30 seconds. Investigate why.

http://54.245.19.70:8000/mt/25a4b8bd-1a16-4deb-8b14-57bdeda64fb3/suNbDuiyabpFZccXa

I am pretty sure this trace includes not just thing explicitly in that method but anything else that runs as a result of this method (aka Hooks). This probably explains at least some of where the redundant queries are coming from.

## Steps to Reproduce
1. Using the load simulator run 1000 concurrent users
2. Examine slow methods in Kadira
3. Observe that this method gets very slow

## Possible solution
We might want to consider moving most of this operation to a background job rather than a sync server-side method. At least anything like updating inventory that is not necessary to render to the customer.

### Versions
Reaction: 1.13.0

**Comment by aldeed** [comment]
Since this method no longer exists in 2.0, I'm going to close this as fixed. If the new mutations for placing an order are still slow, we will need new performance tests and data collected in order to determine potential further fixes.
