### ISSUE TITLE
License Compliance ?

### ISSUE THREAD

**Issue by alexalghisi** [reactioncommerce/reaction#4389]
## Issue Description
Why do all opened PR's tests fail on `License Compliance` ? 

## Steps to Reproduce
1. Open a PR
2. License Compliance  failing on all opened RP's

**Comment by Bubbymathis** [comment]
https://github.com

**Comment by alexalghisi** [comment]
That's a really complex answer :))

**Comment by aldeed** [comment]
@ticean is still working to configure those checks properly
