### ISSUE TITLE
Product price shown as 0

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4393]
## Issue Description
When adding a new product and publishing it without any vairants, its price is shown as 0.00 on the home page.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create a product.
2. Set price as 10.00
3. Make it public and publish it.
4. Go to home page and see price as 0

<img width="1427" alt="screen shot 2018-07-02 at 5 12 21 pm" src="https://user-images.githubusercontent.com/7762605/42162106-233b3dcc-7e1b-11e8-8e27-872d03c4b087.png">
<img width="1044" alt="screen shot 2018-07-02 at 5 12 11 pm" src="https://user-images.githubusercontent.com/7762605/42162107-236fca38-7e1b-11e8-91e5-054bc45bcdb8.png">

### Versions
v1.13

**Comment by zenweasel** [comment]
I've seen this too, but only when signed in as admin? It seemed to be fine as guest

**Comment by rajanski** [comment]
+1

**Comment by aldeed** [comment]
Fixed in 2.0.0
