### ISSUE TITLE
Upgrade version of velocity-react

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4399]
## Issue Description
Snyk is reporting a low severity vulnerability introduced via our version of `velocity-react`. It appears that velocity-react version 1.4.1 has a version of lodash that does not suffer this vulnerability.

```
Low severity vulnerability found on lodash@3.10.1
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:lodash:20180130
- from: reaction@1.14.0 > velocity-react@1.3.3 > lodash@3.10.1
Upgrade direct dependency velocity-react@1.3.3 to velocity-react@1.4.0 (triggers upgrades to lodash@4.17.5)
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Run `snyk test` with the ignore line for `lodash` removed

## Possible Solution
Upgrade to the latest velocity react

**Comment by mikemurray** [comment]
`velocity-react` was removed in by PR: https://github.com/reactioncommerce/reaction/pull/4500
