### ISSUE TITLE
Dockerfile: Should we recommend that users build it themselves?

### ISSUE THREAD

**Issue by faddat** [reactioncommerce/reaction#440]
It is getting to look like the Dockerfile should be used by the users directly to make an image on their own.  Do others see it trending that way?

**Comment by jshimko** [comment]
I guess I have a few thoughts on the topic...

My experience with Docker in the Meteor community so far has been that Docker sounds really cool at first glance to a lot of developers.  However, unless they have at least a little ops experience, a really small percentage of them are still playing with it two weeks later.  I'd certainly never discourage developers digging in and getting to know the technology, but I'm not sure if recommending that everyone do that as the default is worth the support burden it could potentially create.  

Picture it... 
>_Github Issue #x: "How do I FTP up my docker container to my server?"_   

:)

In general, I've found that the people that want to be Docker/devops nerds already know where to look and the people that just need the fastest/easiest deployment solution will use the option that is closest to done already.  

So I definitely think it should be clearly described in the docs, but probably shouldn't be suggested as the default process for everyone.

But that's just me.  :)

**Comment by faddat** [comment]
total, 1000% agreement.

I know why, how, etc I'm using Docker and I know what advantages and
disadvantages it brings us.  TBH for the majority of people Docker is NOT
the solution maybe not even A solution-- "regular people docker" should
work like this:

"when you run this executable, N application runs, like a .exe"

It would have a great UX, because people get that.

Docker is incredibly good if you need it, and a boondoggle to everyone
else.  Seriously if you're a web frontend guy/gal reading this, I want to
make it clear that docker is so fundamentally different from running your
app the "normal" way that you are FAR better off ignoring it.

....And someone (yes I am personally trying) needs to define a standard for
a "common mans docker" which is stateful, and makes a full stack web app
including kernel, distro, dependencies, application, and database function
as though it is a single executable without pain in the ass configuration.

I've got my thing going on, so I'll gladly keep the dockerfile up to date,
but.... I just wanted to share the degree to which I concur with your
opinion on this matter.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by aaronjudd** [comment]
In my mind this means that the preferred method for development and testing will be developing local, building on a docker cluster and deploying the image from there. That's always what we expected it to be so I'm glad to say that I think this is the way it's going and what we've been designing for.  We need a couple different Dockerfile configurations right now, so it's not quite smooth enough, but I think in the next release or two (of meteor and docker) the current hassles will go away. 

I'm going to close this issue.. but feel free to continue discussing.
