### ISSUE TITLE
Marketplace - main brand title displays when viewing a shop (/shop/SLUG) as anonymous user

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4400]
## Prerequisites
* [x] Are you running the latest version? 1.14.0
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When viewing a marketplace shop (/shop/SLUG) as an anonymous user, the main shop's brand title displays, instead of the currently-viewed shop's title.

## Steps to Reproduce
1. Activate Marketplace
2. Create and activate a shop
3. View the shop as an anonymous user (/shop/SLUG) and confirm incorrect brand title in header

## Possible Solution
When viewing a marketplace shop, if I run `ReactionCore.shopId` or `ReactionCore._shopId.get()` in the browser console, the primary shop's _id is returned. `ReactionCore.isShopPrimary()` returns true. Running `ReactionCore.setShopId(SHOP_ID)` with the marketplace shop's _id, causes the correct brand title to appear. Potential solution is determining when `setShopId` should be triggered, and triggering it appropriately.

### Versions
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0
Docker: 18.03.1-ce

**Comment by spencern** [comment]
@dancastellon I'm not convinced that this isn't the desired behavior.
In many marketplaces, the marketplace itself is the dominant brand, with individual shops being identified with sub-headers.

**Comment by dancastellon** [comment]
@spencern that makes perfect sense to me. I wonder if it's worth adding a sub-header component. @aldeed seemed to think this was a bug. What do you guys think? Thanks!

**Comment by aldeed** [comment]
I wasn't thinking it through fully, but I do agree with @spencern that this is probably intended. I also thought you meant the page title, but it sounds like maybe you mean the shop name in the header. I could see the page title potentially needing to be `Primary Shop Name - Shop Name` when within the /shop route. But the one in the header most likely should remain the primary.

Nevertheless, there is clearly something to be done here, and that is to improve the marketplace documentation to explain the intended behavior. I think the only thing we have about marketplace right now is this: https://docs.reactioncommerce.com/docs/merchant-shop-setup

We should expand that into a fuller section about what marketplace is and how it works.

(Merchant cart vs. combined cart needs to be explained there, too. We have checks in the code for it, but I'm not sure it's well tested.)

**Comment by zenweasel** [comment]
I really, really strongly agree that we need to better document how exactly we expect things to behave in a marketplace setting. Every time an issue comes up we find it difficult to determine whether anything is actually broken or not and we waste a lot of time having these sorts of discussions over and over again.

I feel like there are a LOT of things that are broken about the way marketplace works (as it was alpha after all) but it's hard to know until we know what the desired behavior is. i think this needs to not just include how it behaves now but how we would expect it to behave in a complete implementation.

I realize this is a big task and nobody has time for it, but we need to get it on the calendar somehow.

**Comment by spencern** [comment]
@zenweasel @aldeed @machikoyasuda Some documentation around how the marketplace is intended to work and it's current state (Alpha) would be super helpful. Even if we don't have the luxury of blocking off time to spend on this exclusively, it's probably worth adding a marketplace section to our docs that we can document learning like this as it comes up. Would also give us a good place to take contributions from the community. At this point I think there are probably several community members with good experience building marketplaces on Reaction.

**Comment by aldeed** [comment]
Marketplace plugin is no longer built in
