### ISSUE TITLE
Too many categories hide the login button.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4406]
## Issue Description
If too many tags are added, the login button moves out of the screen and there is no way to get to it.
The screen looks like this
<img width="1680" alt="screen shot 2018-07-06 at 3 31 58 pm" src="https://user-images.githubusercontent.com/7762605/42373268-07a75cd4-8132-11e8-9a9f-3832315a29a5.png">

This would be a blocker in the load-testing as we need to load > 100 top level categories and then do browser tests.

## Steps to Reproduce
1. Login as admin
1. Add many top level categories.
2. Log out and navigate to homepage.

### Versions
v1.14

**Comment by aldeed** [comment]
Fixed in 2.0.0
