### ISSUE TITLE
Once increased `productScrollLimit` remains the same

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4409]
## Issue Description
If I scroll down so as to increase the `productScrollLimit`, that number is never reset when going to other categories/PDP so I end up loading all those extra products in my local miniMongo although I may never see/want to see them.

## Steps to Reproduce
1. Go to the home page of any site with a lot of products
2. Scroll down many times so you have added a lot of products to the local `Catalog` collection
3. Go to another category
4. Observe that it will try to load however many product were visible in your previous view, sometimes causing the browser to become unresponsive for reasons that aren't clear

## Possible Solution
Reset this number on route change

### Versions
Reaction version 1.13

**Comment by pardyot** [comment]
I'm trying to look into this, I'm able to reproduce the issue. Will try to do a PR soon.

**Comment by aldeed** [comment]
This UI was removed in 2.0.0
