### ISSUE TITLE
Tags are not visible for Products from Catalog View

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#4414]
## Prerequisites
* [ x] Are you running the latest version?
* [ x] Are you able to consistently reproduce the issue?
* [ x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)
I searched but could not find  any. If there is one already sorry.

## Issue Description
When Product Details are shown from Catalog (Customer View)  Tags are not visible.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1.Deploy latest from Master
2. visit the product grid
3. open Product and see no Tags are  shown.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug. 

### Versions
(run `reaction -v` from your reaction directory)
Node: 8.11.2
NPM: 6.0.1
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.1
Reaction branch: master

**Comment by zenweasel** [comment]
Hey, guess who's back? 🎉 Do you mean the tags within the detail page or the tags along the top. Either way I am seeing those right now.

![2018-07-10_14-38-27](https://user-images.githubusercontent.com/72819/42493272-f249c0dc-844e-11e8-8b84-60251bf5ce2a.png)

**Comment by hrath2015** [comment]
Thanks a lot @zenweasel for flower bookey.   OK let me try one more time on a fresh clone and  report back.

**Comment by hrath2015** [comment]
I tried it again on fresh clone and it is  same behavior.  After app starts Visit `localhost:3000` click  product and see it happening.
I know what is causing it and already  working on PR.  In Catalog we have tagIds and in Products (legacy) it is hashtags. 
Pic below
![image](https://user-images.githubusercontent.com/14071646/42494375-bc2ab684-843d-11e8-98c2-d9b648ec08b1.png)
