### ISSUE TITLE
Create navigation GraphQL query

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4418]
### Issue
The starter kit currently builds a navigation tree from multiple tags queries. The server could do this and reduce this to one query, plus this allows us to provide operators with more ways of defining navigation rather than just showing all of the tags.

### Work
Replicate the nav tree building in a `navigation` query resolver on the server. It should be a simple tree of nested arrays, with each item being an object with properties `label` and `tagSlug`.

The query should take one param, `language`, which must be a valid language code. The labels should come back translated to this language eventually, but for now the label will just be whatever the tag name is.

As part of this, we can also implement canonical nav for breadcrumbs as discussed in https://github.com/reactioncommerce/reaction-next-starterkit/issues/148

**Comment by zenweasel** [comment]
@dancastellon Will be handling this as part of building the `content` service.

**Comment by mikemurray** [comment]
Merged https://github.com/reactioncommerce/reaction/pull/4683. Closing.
