### ISSUE TITLE
AdressbookForm defaults to "US" - Throws "regions is not iterable" if "US" is not active

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4423]
## Issue Description
adressbookForm.js in [/imports/plugins/core/accounts/client/components/](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/accounts/client/components/addressBookForm.js) defaults to "US":
in L50: `country: this.props.editAddress.country || "US",`

The only known solution to me for limiting the available countries to choose from in the Address Form is to remove them from the Shops.json/Shop collection.

If the default "US" is removed, the component fails to render.
Setting it to "" will produce the same error.

## Steps to Reproduce
1. Remove the entry "US" from countries in Shops.json, or delete it in the Shops collection
2. Observe that the Adressform in Accounts and checkout fails to render and throws "regions is not iterable"

## Possible Solution
Default to the first entry in the countries array:
`this.props.countries[0].value`
Drawback: If geo detection fails, the default value could be an uncommon country.
A better solution could be to set it to the country code of the default business address, or create a separate setting to set it.

### Versions
1.13.1

**Comment by aldeed** [comment]
This component was removed in 2.0.0
