### ISSUE TITLE
I have an issue with google indexing my website

### ISSUE THREAD

**Issue by alexalghisi** [reactioncommerce/reaction#4424]
![screen shot 2018-07-11 at 17 45 34](https://user-images.githubusercontent.com/10101138/42580054-4d35cc3c-8532-11e8-99e6-a2e38e226ca0.png)

Here is the google result:
![screen shot 2018-07-11 at 17 46 36](https://user-images.githubusercontent.com/10101138/42580082-647fa5ac-8532-11e8-971f-5e01de444663.png)

I don't know if I'm allowed to put the link here but: edgeshop.ro

## Prerequisites
* [ yes ] Are you running the latest version?
* [ yes ] Did you search the issue queue for existing issue? [Search issues]

## Issue Description
The website is not indexed correctly.

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).
