### ISSUE TITLE
Custom product price based on formula

### ISSUE THREAD

**Issue by jmarceli** [reactioncommerce/reaction#443]
First of all great project. I'm really interested to use it in my future work.

Now I'm looking for the feature which allow me to calculate product price based on the information provided by the client and some formula. It will be really handy for shops selling highly customisable products. Do you have any plans for that kind of improvement?
In my case this would be used for selling customisable cupboards with variable sizes and number of shelves, but I'm sure there are many more use cases.

Requirements:
- saving multiple inputs (e.g. width, length, depth, number of shelves)
- price calculation (different price for different input values)

**Comment by aaronjudd** [comment]
we plan to support multiple product types.  Right now we're focused on one product type, but we'd like to add more, and it shouldn't be to difficult to replace with some custom product types. See #152 #368 as some background on this.  Pricing methods can be extended/replaced as well.

**Comment by zenweasel** [comment]
Closing to Review roadmap
