### ISSUE TITLE
`eslint-scope` v3.7.2

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#4431]
This is not a current issue, but a potential one.

`babel-eslint` uses a package called `eslint-scope` whose [version 3.7.2 appears to have a security issue](https://twitter.com/snyksec/status/1017430447092129792).

I'm sure the maintainers of `babel-eslint` will avoid this version, but it is worth keeping an eye on.
They currently have the package pegged to `3.7.1`, but if they were to change to allow a range of versions, `3.7.2` could creep in.

Maybe the takeaway is to add the following to package.json?
``` JSON
  "eslint-scope": "<=3.7.1"
```

so if a package updates it's version npm install will fail?

**Comment by aldeed** [comment]
Closing this since it was resolved by eslint folks long ago and Reaction has the fixed version.
