### ISSUE TITLE
ERROR Reaction: [product._id is not allowed by the schema]

### ISSUE THREAD

**Issue by stunjiturner** [reactioncommerce/reaction#4435]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [ ] Are you running the latest version?

release branch 1.14
* [ ] Are you able to consistently reproduce the issue?

* [ ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

yes

## Issue Description

`Error: [product._id is not allowed by the schema]
      at Function.SimpleSchema.defineValidationErrorTransform.error [as validationErrorTransform] (imports/plugins/core/core/server/startup/index.js:20:20)
      at /Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/reaction/node_modules/simpl-schema/dist/SimpleSchema.js:757:30
      at Array.forEach (<anonymous>)
      at SimpleSchema.validate (/Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/reaction/node_modules/simpl-schema/dist/SimpleSchema.js:730:15)
      at Promise.asyncApply (imports/plugins/core/catalog/server/no-meteor/utils/publishProductToCatalog.js:36:21)
      at /Users/stunjiturner/.meteor/packages/promise/.0.11.1.9oon0u.7wgb++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:`

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
Node: 10.4.1
NPM: 6.1.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0
Docker: 18.03.1-ce

**Comment by zenweasel** [comment]
@stunjiturner please don't close issues

**Comment by zenweasel** [comment]
@stunjiturner ooops sorry, my bad. You're right
