### ISSUE TITLE
Rename reaction-api Docker network to api.reaction.localhost

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4447]
Platform networks in the Docker environment should be named as *.reaction.localhost. The localhost TLD is reserved and guaranteed to not conflict with a real TLD.

Places to update:
- https://github.com/reactioncommerce/generator-reaction
  - approved PR: https://github.com/reactioncommerce/generator-reaction/pull/20
- https://github.com/reactioncommerce/reaction
  - PR: https://github.com/reactioncommerce/reaction/pull/4613
- https://github.com/reactioncommerce/reaction-next-starterkit
  - PR: https://github.com/reactioncommerce/reaction-next-starterkit/pull/277
- https://github.com/reactioncommerce/reaction-platform
  - PR: https://github.com/reactioncommerce/reaction-platform/pull/8

**Comment by focusaurus** [comment]
OK I think all the PRs for the network rename itself are open now.

**Comment by focusaurus** [comment]
We decided to pick the name "api.reaction.localhost" instead. The related PRs have been updated with that.

**Comment by focusaurus** [comment]
OK all 4 PRs are in a good state now using FQDN "api.reaction.localhost" and alias "api" appropriately for docker, docker-compose, readme, etc. Tested locally that reaction-next-starterkit talks to reaction correctly. Should be good to merge all 4 PRs. @aldeed can you confirm and coordinate that please?

**Comment by aldeed** [comment]
Yep, thanks @focusaurus
