### ISSUE TITLE
Users can fill up their screen with notifications

### ISSUE THREAD

**Issue by patrickblackjr** [reactioncommerce/reaction#4452]
## Issue Description
If you click on any button that produces a notification (i.e. the Publish product button), it will fill the screen until it runs out of viewport.

## Steps to Reproduce
Log in as an admin.

1. Edit a product.
2. Click publish.
3. Continue to click publish until the left side of your screen is filled with notifications.

## Possible Solution
Do not allow another identical notification when it's already being displayed.

### Versions
Node: 10.5.0
NPM: 6.1.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.1
Reaction branch: master

**Comment by aldeed** [comment]
This UI no longer exists in current version
