### ISSUE TITLE
HELP: How to extend "OrderBulkActionsBar" component to add a additional option.

### ISSUE THREAD

**Issue by anishtr4** [reactioncommerce/reaction#4453]
I am trying to customize the platform using the custom plugin. I need to extend OrderBulkActionsBar component to add an additional option in that. Can someone help me out, how to the extent the component?  Sorry if I am posting this query in the wrong section.

**Comment by nnnnat** [comment]
Hey @anishtr4, you should check out our [gitter channel](https://gitter.im/reactioncommerce/reaction) or ask your question in the [fourm](https://forums.reactioncommerce.com/). Github issues are mainly used for tracking bugs/development of the platform.
