### ISSUE TITLE
 core->settings->Localization->Locale seems unused

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#446]
Poking around a little bit, it seems that this setting is not used anymore, because getLocale makes usage  a geo location service to determine current locale (and currency).

Therefore this field should be eliminated, as there's much confusion how currency and locale is affected through these settings.

**Comment by aaronjudd** [comment]
Related to #437

**Comment by aaronjudd** [comment]
The Locale setting in the Shop settings was because we need a fallback if we cannot determine the shopLocale, but this is now using the shop address to determine the country for the default locale.
