### ISSUE TITLE
Create and use a registry NPM package prototype

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4461]
1. Move `registerPackage` to it's own folder in Reaction repo, simulating being in a separate package using Babel module resolver.

    API:
    `addQuery(name, func, [methodName])`
    `addMutation(name, func, [methodName])`
    `addMeteorMethod(name, func)`
    `addMeteorPublication(name, func)`
    `registerPlugin`

    And a function for getting all of the added things in core or another plugin.

2. Update core plugins to use the registry package. While doing so, find all other extraneous imports that come direct from other packages and rewrite.

**Comment by zenweasel** [comment]
@aldeed I know that we had talked about a way to "override" Meteor methods for something like `getPrice` where we may have a default implementation and then plugins may come with additional implementations. I wonder if we could use something like this to do that?

**Comment by aldeed** [comment]
This is old and no longer relevant.
