### ISSUE TITLE
Locale change does not affect price labels.

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#447]
Because getLocale is now (was always)? nonblocking, the template is rendered with default locale (US). Even though my returned locale (from getLocale server call) is "DE", the prices are not updated.

**Comment by aaronjudd** [comment]
See #437 #248 #366

**Comment by prinzdezibel** [comment]
See 

https://github.com/reactioncommerce/reaction-core/commit/940ad88f03e705837f8d1cd95efc58b7bac79bde


:)

**Comment by prinzdezibel** [comment]
Solved with merged PR: https://github.com/reactioncommerce/reaction-core/pull/168
