### ISSUE TITLE
Image names with spaces don't display in the homepage

### ISSUE THREAD

**Issue by maurop123** [reactioncommerce/reaction#448]
If a user uploads a photo that has spaces in the name, the image will not display on the homepage with the rest of the items. For example...

![image](https://cloud.githubusercontent.com/assets/1924900/9322402/6fe42a1a-4540-11e5-8e92-2e0bfc91c0c6.png)
The image of the t-shirt above shows since it's named "galliano.jpg".

![image](https://cloud.githubusercontent.com/assets/1924900/9322421/b094e4dc-4540-11e5-9fd9-a6d165b8fea1.png)
One image here is titled "galliano.jpg" and the other is titled "galliano shirt.jpg". I'll make "galliano shirt.jpg" the main image.

![image](https://cloud.githubusercontent.com/assets/1924900/9322439/f1b958d0-4540-11e5-8876-65d31e228345.png)
When "galliano shirt.jpg" is selected as the main image, the image no longer shows on the homepage.

**Comment by aaronjudd** [comment]
@maurop123 thanks for the detailed issue. @mikemurray this is one of those, could be easy, could be tough ones that we should look at right away.

**Comment by maurop123** [comment]
@aaronjudd no problem. I'd be interested in helping if @mikemurray could use a hand.

**Comment by mikemurray** [comment]
I'm going to take a quick look and see what the problem is.

**Comment by mikemurray** [comment]
The seems the issue is the names of the images aren't being URL encoded by the CollectionFS template helper.

I tried URL encoding the entire url for the image, but that doesn't seem to work. I'm going to try some other solutions tonight, and try to get a fix out
