### ISSUE TITLE
Sometimes Login Dropdown goes missing

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#4489]
## Prerequisites
* [x] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?
* [x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Sometimes Login Dropdown goes missing from Navigation Bar. It is not very consistent. But observed  it twice today. See image.
![dropdownmis](https://user-images.githubusercontent.com/14071646/43274117-e07dc8e2-911b-11e8-9b6a-995c90932118.PNG)

## Steps to Reproduce
Not sure as not very consistent.  Will see if can find a way to reproduce.
## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
Node: 8.11.2
NPM: 6.0.1
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0

**Comment by aldeed** [comment]
When I've seen this, it's usually due to errors in certain places in the app startup / login code. Closing this in favor of someone submitting an issue about whatever error is causing the visual issue.
