### ISSUE TITLE
Examine app startup behavior

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4492]
## Issue Description
Right now with a fully loaded database the app can take several  (5-10) minutes to start NOT counting build time. When deploying this causes a problem because when you create instances you need to account for this "dead" time while the app spins up. A lot of the things that run on startup are meant to initialise the app/database but when running a real site and deploying a code change this is not necessary and also causes a lot of db activity that's unnecessary. Also users may not want things like creating search collections to be kicked off immediately after a deploy and want to defer them to run manually or not at all.

## Steps to Reproduce
1. Use the data-loader to populate a db with the `ret` dataset or larger
2. Observe that the app takes a long time to start up.
3. Some of this time may be reduced when #4384 is merged

## Possible Solution
Possibly have some sort of "first run" flag that could then trigger all the one-time loading things that need to happen to a new db (e.g. loading package into the db) and when not in a "first run" state, skip those. Maybe this could be a simple as something similar to the `SKIP_FIXTURES` env variable.

### Versions
`release-1.14.0`

**Comment by aldeed** [comment]
Resolved in 3.0
