### ISSUE TITLE
ReactionError move to npm package

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#4493]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
We're replacing all `Meteor.Error` calls with the `ReactionError`, currently the ReactionError class is deeply nested inside `/imports/plugins/core/graphql/server/no-meteor/` directories. Should the ReactionError class be ported into it's own npm package?

## Possible Solution
Move ReactionError class into an npm package
`import ReactionError from "@reactioncommerce/reactionerror"`

### Versions
1.14

**Comment by aldeed** [comment]
Done
