### ISSUE TITLE
Create a Fulfillment pseudo-service

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4498]
## Goal
To establish some of the service/plugin patterns for server code.

## Work
1. Move the `shipping/server` core plugin and flat rate shipping plugin into an `/imports/services/fulfillment` folder with no Meteor dependencies.
1. Move fulfillment GraphQL schemas into that service. Update GraphQL plugin to stitch it in.
1. Move related cart mutations such as `setShippingAddressOnCart` into the service.
1. Export methods, pubs, and schemas, and have the core `init` code wire them up.
1. Update any direct method calling to operate based on hooks instead (simulate listening to event stream).

**Comment by spencern** [comment]
Closing in favor of the process described in #4622
