### ISSUE TITLE
Date is not shown in invoice

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#4504]
## Issue Description
Date is not shown in the invoice which used to work in `1.13.1`.

## Steps to Reproduce
1. As a consumer, create an order, checkout, and pay.
2. As admin, go to orders dashboard, approve the created order, and click Print.
3. See that the value for date is empty.

## Possible Solution
None

### Versions
```
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0
Docker: 18.03.1-ce
```

**Comment by zenweasel** [comment]
Closed via #4506
