### ISSUE TITLE
Checkout briefly shows that the cart is empty

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#4505]
## Issue Description
Checkout briefly shows that the cart is empty when signing in as a user in the checkout page if the user has an existing checked out cart.

## Steps to Reproduce
1. As a logged in consumer, create an order, checkout, fill in your address, and select a shipping method. Do not submit payment.
2. Log out.
3. As an anonymous user, add an item to your cart. Checkout. Click sign in and sign in with the same account in Step 1. See that for a moment, the page will display that you have no items in your cart.

Note that this will not occur if a shipping rate was not selected in Step 1.

## Possible Solution
None

### Versions
```
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0
Docker: 18.03.1-ce
```

**Comment by aldeed** [comment]
Closing. I believe this was referring to the old cart that was removed in 2.0.0
