### ISSUE TITLE
Internationalization: Wrong word order in phrases

### ISSUE THREAD

**Issue by lovetostrike** [reactioncommerce/reaction#452]
I have noticed wrong word order in languages which have opposite subject/object order. For example,
in English,
<span data-i18n="accountsUI.configure">Configure</span>
<span data-i18n="social.facebook">Facebook</span>. In some languaes, the order would be Facebook Configure. My suggestion is the same as  this apple's article. 
https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/InternationalizingYourCode/InternationalizingYourCode.html

We should probably create unique entries instead of using composable phrases.

**Comment by aaronjudd** [comment]
I like this idea, we don't have very many place where we compose a string so it'd probably be a pretty quick cleanup.

**Comment by lovetostrike** [comment]
I guess so. The language contributors might need to update their entries accordingly then.
