### ISSUE TITLE
No way to add multi-language eMail-Templates

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4522]
## Issue Description
The  `registerTemplate` method supports no way to add a template with a custom set language.
Also, templates are defined and "orders/new" updated with their name as identifier, eg. `orders/new`
Therefore, registering a new template for that case in a different language would still replace the original template with another language.

## Steps to Reproduce
1. Register a custom template in your code taking the included email templates as a base.
2. Notice how settings a custom language key won't be imported to the Template collection 
3. Notice how the original template with the same name describing its purpose was replaced by the new one.

## Possible Solution
To respect a language keys that was provided to `registerTemplate`:
As the field gets lost after it is passed to `processTemplateInfoForDatabase`, add it to the templateData object created there:
```
const templateData = {
   [...]
   language: templateInfo.language,
   [...]
};
```

After this fix, a templates language key will be importerd properly, but still replace other tempaltes with the same name, despite the different language.
Therefore, while replacing/adding a Template, dont just query for name, but also language.
Other idea, while not necessary here, could be to separate template name and template purpose.

### Versions
Probably all, including 1.13.1

**Comment by zenweasel** [comment]
@janus-reith Can you please complete the issue template?

**Comment by janus-reith** [comment]
done

**Comment by zenweasel** [comment]
@janus-reith thanks. That's very helpful

**Comment by janus-reith** [comment]
Closing this, as it is not relevant for the new demeteorized email-templates plugin.

1. Queries for language now: https://github.com/reactioncommerce/reaction/blob/64278df0e2c735d1133e5c703122648253b36236/imports/plugins/included/email-templates/server/util/seedEmailTemplate.js#L13
2. Can be easily extended by a custom plugin now to add further parsers or languages.
