### ISSUE TITLE
Template settings form doesn't save changes to email templates

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4523]
## Issue Description
The template settings form has a textarea where the HTML/Handlebars template for emails can be edited.
After editing and clicking the save button, no error is thrown, but the original template stays unaltered.

## Steps to Reproduce
1. Open the Template Settings Dashboard
2. Select a Template of type email.
3. Alter its Content in the HTML Textarea and click save.
4. Close and reopen, notice that the changes where not saved.

### Versions
1.13.1

**Comment by zenweasel** [comment]
@janus-reith Can you please complete the entire issue template?

**Comment by janus-reith** [comment]
done
