### ISSUE TITLE
Identity and Access Management with Keycloak Epic

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#4525]
## Goal
Replace Reaction’s usage of Meteor auth with an identity and authorization system based on OAuth2 and OpenID Connect.

## Stages
- Stage 1: Abstract existing identity & authorization code from Meteor (and other Meteor-related auth lib) into wrapper functions e.g `Meteor.userId()` `Roles.userIsInRole`. The wrapper functions will contain logic to determine the right auth system based on a set ENV.
- Stage 2: Implement Keycloak-based authentication and authorization (while keeping existing Meteor auth and `Roles` package. Selecting an auth system to be done with an ENV var)
- Stage 3: Remove Meteor accounts system and `Roles` package

### Stage 1

**Client code:** 
- Setup a wrapper function that returns the correct logged in user ID depending on the enabled authentication system (i.e either Meteor-Accounts or Keycloak). Replace all `Meteor.userId()` in client code with the new function.
- Replace direct usage of `Roles.userIsInRole` to `hasPermission` wrapper function to get us closer to be able to remove dependence on [Roles](https://github.com/alanning/meteor-roles) package.
- Setup a wrapper function to be used for authorization checks in the client code. This function will delegate to the correct authorization lib depending on the enabled authentication system. Replace usage of `hasPermission()` with the new function. 
- Remove current Anonymous login from the client code. It was mostly used for Cart setup which changed in master to use a cart token.
- Update _all_ Meteor.user() references to use the Accounts collection

**Server code:**
- Remove Meteor.userId() calls (to remove dependence on Meteor Accounts). Switch to this.userId. Confirm that this works across existing methods & publications.
- Unify hasPermission checks between the GQL server and Meteor server. Remove the old version.
- Setup a wrapper function to be used for authorization checks in the server code. This function will delegate to the correct authorization lib depending on the enabled authentication system. Replace usage of `hasPermission()` with the new function.  

**Both server & client:**
- Change usage of existing hasPermission extensions (e.g hasOwnerAccess, hasAdminAccess) to use just hasPermission function. Add a deprecation warning to those (hasAdminAccess etc) functions.

All work done at this stage should cause no breaking change.

### Stage 2

- Setup initialization of Keycloak-js lib and OAuth dance in the client code. Add Login / Logout button in the account dropdown. Completion of successful login should store the returned token in local storage. Also on successful login, set the userId context for all method calls
- Setup ‘token-parse’ function in the server code. On the client, this is handled by the Keycloak-js lib. There is a Keycloak-connect package that we can borrow from (we could just have used the package directly if not that it is “Connect-specific”
- Update all Meteor client method calls to send the Keycloak auth token as an extra argument of each call. (If a request interceptor concept can work for Meteor method calls that is even better)
- Add needed KeycloakAuth params in all isAuthorized calls (client and server). This will involve deciding how we’ll map existing roles in Meteor to Keycloak. For example, if the current hasPermission call checks for [“owner”, “admin”], what role check will that map to in Keycloak. Same for a check like [“guest”]. Also, add the decided roles to Keycloak in the process. 
- Setup util function to make calls to Keycloak server for resource authorization
- Extend KeycloakAuth function to perform resource authorization check
- Add needed KeycloakAuth params for resource authorization checks. This will involve deciding what resources to setup in Keycloak and the different scopes under each. This will also include setting up permissions and policies in Keycloak.
- Update the Apollo client where it is passing in a “meteor-login-token” header to also pass along Keycloak token

**Comment by spencern** [comment]
Moving this to a future milestone where we can check-in on it.

**Comment by spencern** [comment]
@impactmass @ticean should we close this ticket or come back to it in a few weeks?

**Comment by impactmass** [comment]
I think we can close it. Our _coming_ approach (though might use some of the ideas here) will take take a different from the details here.
