### ISSUE TITLE
GQL error accessing `totalCount` in `CartItemConnection`

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4526]
## Issue Description

When using the GraphQL api to access account cart items `totalCount` with the following query

```
accountCartByAccountId(accountId: <accountId>, shopId: <shopId>) {
  items: {
    totalCount
  }
}
```

I receive this error

```
  "errors": [
    {
      "message": "Cannot return null for non-nullable field CartItemConnection.totalCount.",
      "locations": [
        {
          "line": 51,
          "column": 4
        }
      ],
      "path": [
        "accountCartByAccountId",
        "items",
        "totalCount"
      ],
      "errorId": "cjklgl91200002sqo1o0azvbw",
      "type": "unknown"
    }
  ]
```

## Steps to Reproduce

1. With the devserver and reaction running
2. Sign into reaction as admin or a customer
3. Add items to the cart
4. With GraphiQL (desktop) pointed to http://localhost:3030/graphql-alpha and
4.1 ...and `meteor-login-token` set in the headers
5. Run a viewer query to get your `accountId` and `shopId`

```
  viewer {
    _id
    shop {
      _id
    }
  }
```

6: Use the `accountId` and `shopId` for the the `accountCartByAccountId` query

```
accountCartByAccountId(accountId: <accountId>, shopId: <shopId>) {
  items: {
    totalCount
  }
}
```

7. See the error in the result `Cannot return null for non-nullable field CartItemConnection.totalCount.`

### Versions

Node: 10.7.0
NPM: 6.2.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.15.0
Docker: 18.06.0-ce

**Comment by aldeed** [comment]
Fixed in #4622
