### ISSUE TITLE
Convert PDP for customers to consume data from GraphQL

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#4529]
## Work
Using the Apollo client set up in https://github.com/reactioncommerce/reaction/pull/4481, this work aims to convert the customer-facing PDP components into dumber components that do not have to interact with the admin dashboard and get and post data through GraphQL instead of Meteor subscriptions.

**Comment by zenweasel** [comment]
This work will not be done since 2.0 was successfully released.
