### ISSUE TITLE
Reaction-core [register.coffee]

### ISSUE THREAD

**Issue by dksharp** [reactioncommerce/reaction#453]
I have been struggling for over a day now and i am going nowhere with this. I am trying to add one more feature which is to be shown in drop-down menu and i am changing register.coffee like this,

       {
          route: 'createProduct'
          label: 'Add Product'
          icon: 'fa fa-plus'
          provides: 'shortcut'
       }

    {
      route: 'oneMorePower'
      label: 'MyPower'
      icon: 'fa fa-plus'
      provides: 'shortcut'
    }

changes taking place only when i reset meteor that too not every time i reset (meteor.reset) .  I have included reaction-core package in project. Tried everything. reinstall node, meteor, fresh reaction from github. It was working fine 2-3 days ago. In .meteor , i observe the changes i have made are reflecting there but web is not complying with that :( i m stuck.

**Comment by aaronjudd** [comment]
can't really think of anything that would have stopped that from working - but in some cases in the last development version we're seeing some different load orders of the packages. that could be something to look at.  I'd start with just checkout mongo manually (ie, robobmongo, shell)  to see if your updates made it into the db.  If it's clearly there, then it'd be template related at least, and not the registerPackage. 

I'd help debug this, but we're working on wrapping up 0.7.0 and are likely to get that done before I have a chance to look deeper into this.

**Comment by dksharp** [comment]
I have found something. I think these local binaries are not containing changes.
~/reaction/.meteor/local/db/local.1:
    <binary>

~/reaction/.meteor/local/db/meteor.0:
    <binary>

how do i resolve this?

**Comment by aaronjudd** [comment]
those are all local mongodb files, you don't need to touch them. `meteor reset` will empty them.  when do `meteor reset` those files should be removed, until you start meteor again with `meteor`.
