### ISSUE TITLE
How to get into owner/admin panel i.e. the back panel ?

### ISSUE THREAD

**Issue by nisarg-shah** [reactioncommerce/reaction#454]

**Comment by aaronjudd** [comment]
>The initial admin user for the site is auto generated, and displayed in your console (or see: env variables section to default these)

See: https://github.com/reactioncommerce/reaction-core/blob/development/docs/installation.md

**Comment by nisarg-shah** [comment]
This is what i Did.. 
I edited dev.settings.json file with the following code

{
  "ROOT_URL": "",
  "MONGO_URL": "",
  "MAIL_URL": "",
  "reaction": {    
    "METEOR_USER": "admin",
    "METEOR_AUTH": "qwerty123",
    "METEOR_EMAIL": "admin@gmail.com"
  },
  "isDebug": "info",
  "public": {
    "velocity:html-reporter": {
      "position": "bottom right",
      "tab-index" : 1
    }
  }
}

and ran : meteor --settings settings/dev.settings.json     on console
when I tried to login with credentials
 E: admin@gmail.com
 P: qwerty123

it would show error: Invalid password.

**Comment by aaronjudd** [comment]
try doing `meteor reset` first, then `meteor --settings settings/dev.settings.json`.  It won't reload just on change, it only sets the user/pass when there is no existing users.

**Comment by nisarg-shah** [comment]
Done. This worked. 
Thanks :)

**Comment by aaronjudd** [comment]
:+1:

**Comment by stevesaint** [comment]
thanks

**Comment by tuanlhn38** [comment]
thanks
