### ISSUE TITLE
Issue uploading product images in add product screen

### ISSUE THREAD

**Issue by umeshrs** [reactioncommerce/reaction#455]
I'm new to reaction commerce and meteor. I recently forked reaction commerce to experiment with it and I'm currently working on a local copy (windows machine).

Here's the issue- I want to create a product with 3 to 4 images. But when I try to add the images the image does not show up in the image section. Instead, I only see a tiny 'image not found' logo or the default placeholder. I have tried to upload images both ways - by clicking on the 'Drop file to upload' button, and by drag and drop method. The result is the same. 

![image](https://cloud.githubusercontent.com/assets/13485325/9491624/0bf0ef32-4c0e-11e5-89a4-50b8587b8e87.png)

Also, I noticed that after attempting to upload images, I get this error in my console where my server is running - 
```
W20150826-16:25:49.357(5.5)? (STDERR)
W20150826-16:25:49.357(5.5)? (STDERR) events.js:72
W20150826-16:25:49.357(5.5)? (STDERR)         throw er; // Unhandled 'error' event
W20150826-16:25:49.357(5.5)? (STDERR)               ^
W20150826-16:25:49.357(5.5)? (STDERR) Error: write EPIPE
W20150826-16:25:49.357(5.5)? (STDERR)     at errnoException (net.js:905:11)
W20150826-16:25:49.357(5.5)? (STDERR)     at Socket._write (net.js:646:26)
W20150826-16:25:49.357(5.5)? (STDERR)     at doWrite (_stream_writable.js:226:10)
W20150826-16:25:49.357(5.5)? (STDERR)     at writeOrBuffer (_stream_writable.js:216:5)
W20150826-16:25:49.357(5.5)? (STDERR)     at Socket.Writable.write (_stream_writable.js:183:11)
W20150826-16:25:49.357(5.5)? (STDERR)     at Socket.write (net.js:616:40)
W20150826-16:25:49.357(5.5)? (STDERR)     at write (_stream_readable.js:602:24)
W20150826-16:25:49.357(5.5)? (STDERR)     at flow (_stream_readable.js:611:7)
W20150826-16:25:49.357(5.5)? (STDERR)     at PassThrough.pipeOnReadable (_stream_readable.js:643:5)
W20150826-16:25:49.357(5.5)? (STDERR)     at PassThrough.emit (events.js:92:17)
W20150826-16:25:49.357(5.5)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20150826-16:25:49.357(5.5)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
=> Exited with code: 8
```

Any idea why I'm not able to upload images?

**Comment by umeshrs** [comment]
Issues is fixed. While installing reaction commerce, I forgot to install ImageMagick. After installing ImageQuick, I'm able to see the images that I upload.

**Comment by aaronjudd** [comment]
just curious, are you on windows or osx, linux?  there should have been a warning on install about imagemagick not being installed, and your images should have worked without an image library installed.  It think this might be a windows issue?

**Comment by umeshrs** [comment]
I'm on windows (windows 10, 64 bit). I don't recall seeing a warning about imagemagick not being installed. But then again, there were a lot of errors during the installation process. I had to refer to one of the earlier issues here about installation on windows to solve those errors. So, I might have missed the warning. If you want I can do a fresh installation and confirm if I get the warning about imagemagick?

**Comment by aaronjudd** [comment]
no, it's ok - the warning is actually broken on windows - which is why I guessed that you were on windows ;-) ....    on osx, linux it will not fail... see: https://github.com/CollectionFS/Meteor-cfs-graphicsmagick/issues/12

**Comment by umeshrs** [comment]
Oh ok. Always some issue with windows... Thanks for the help.
