### ISSUE TITLE
Can Not Remove Tags in Secondary Menu Navigation

### ISSUE THREAD

**Issue by stunjiturner** [reactioncommerce/reaction#4550]
## Issue Description
Can Not Remove Tags in Secondary Menu Navigation

<img width="862" alt="screen shot 2018-08-15 at 1 09 32 pm" src="https://user-images.githubusercontent.com/1497244/44162021-0173cf80-a08d-11e8-906b-8b03a28d09d3.png">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Navigate to the secondary navigation menu items from the main navigation
2. Click to delete tags
3.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
(run `reaction -v` from your reaction directory)

1.14.1

**Comment by aldeed** [comment]
This UI is gone in 2.0.0
