### ISSUE TITLE
isSoldOut field in catalog is incorrect when publishing a product

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#4552]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
`isSoldOut` values are incorrect for both variants and options. I see that it is only correct when variant has no options and has qty set to 0.

There is some discussion in  https://github.com/reactioncommerce/reaction/pull/4342 but it seems that this PR has been overwritten anyway.

## Steps to Reproduce
1. Create a product, with variant, and options.
2. Turn on inventory tracking for an option and set qty to 0.
3. Publish the product.
4. Check the catalog collection and see that the option has `isSoldOut` still set to false.

## Possible Solution
None

### Versions
```
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: master
Docker: 18.03.1-ce
```

**Comment by kieckhafer** [comment]
Fixed via #4551
