### ISSUE TITLE
Packages can get duplicated for the same shopId

### ISSUE THREAD

**Issue by loanlaux** [reactioncommerce/reaction#4553]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
In the event of a database rollback (for example if a replica set diverges due to a network split causing a primary node to rejoin as a secondary, typically with a `{ w: 1 }` write concern), I noticed that objects in the `Packages` collection can get duplicated (i.e.: multiple items with the same `name` *and* same `shopId`).

This results in the interface showing multiple times the same package inside a given shop (highlighted in red), and potentially a lot more undesired side effects:

![screen shot 2018-08-16 at 10 32 37](https://user-images.githubusercontent.com/2156504/44198472-d0a1a200-a141-11e8-8dce-07b178c0065e.jpg)

## Steps to Reproduce
1. Cause a MongoDB rollback (for example by abruptly shutting down the primary node)
2. Observe that packages were duplicated

## Possible Solution
Add a unique compound index to ensure that no two items in `Packages` can have the same `name` and `shopId`. In pure MongoDB terms, I would do it this way:

```
db.Packages.createIndex({ name: 1, shopId: 1 }, { unique: true })
```

### Versions
(run `reaction -v` from your reaction directory)

```
Node: 8.7.0
NPM: 6.3.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.1
Reaction branch: master
Docker: 18.06.0-ce
```

**Comment by aldeed** [comment]
Packages collection isn't used in 3.0. Won't fix for older versions
