### ISSUE TITLE
Merchant Dashboard On Login

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4557]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
When logging in as a merchant shop owner none of the packages load in the right hand dashboard. They are only visible following a refresh. This is a major issue for marketplace - making it unusable for anyone who isn't the primary shop owner.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Setup a merchant shop
2. Logout
3. Login as the merchant shop, and look at the right hand dashboard

### Versions
Node: 8.11.3
NPM: 5.6.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.1
Docker: 18.06.0-ce

**Comment by stunjiturner** [comment]
I have see this as well, the shop name pull down disappears as well.

**Comment by willmoss1000** [comment]
I no longer can see this issue after resetting my database locally. I'm not able to reproduce it, so I'm closing this issue.

**Comment by willmoss1000** [comment]
Re-opening - this has not been resolved. Looks like this a regression as a result of the toolbar refactor.

**Comment by willmoss1000** [comment]
Re-opening - this has not been resolved. Looks like this a regression as a result of the toolbar refactor.

**Comment by willmoss1000** [comment]
To reproduce:
1. Create a new shop
2. Look at the right hand dashboard, and see the packages don't show
Note: this issue only appears sometimes when you login, but always for newly created shops.

**Comment by aldeed** [comment]
No longer relevant for 3.0. Won't fix older versions
