### ISSUE TITLE
README doesn't reflect current product plus mislabeled link

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4559]
## Issue Description
* Both "Analytics" and "Drop and Drop Merchandising" have been removed from the product. (I have always understood DnD Merchandising to mean being able to rearrange products on the grid, which you can no longer do).

* Reaction Action RSVP link just takes you to a list of YouTube videos

## Steps to Reproduce
Visit the README

### Versions
Reaction 1.14.1

**Comment by loanlaux** [comment]
Reaction also doesn't rely on ImageMagick at all anymore as far as I know. It's been fully replaced by Sharp, right?

**Comment by zenweasel** [comment]
@loanlaux that's true. We can remove imagemagick as well
