### ISSUE TITLE
CartWorkflow loses status on checkout after refresh

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#456]
I noticed that the CartWorkflow looses it's status after the checkout page is refreshed or you navigate back on the hompage, add a new product to the cart and go back to the checkout page the cartworkflow is in the "addAddress" status though address has already been added and shipping has been also selected. 
In this case you can't change the shipping method because the following error appears:
`Cannot change methods while processing`
`Uncaught event shipmentMethod inappropriate in current state addAddress`

**Comment by aaronjudd** [comment]
we're reworking this in #248, #393  - those issues will close this one.
