### ISSUE TITLE
Getting tags from shop 2 in the main shop 1 in release 1.14.1

### ISSUE THREAD

**Issue by stunjiturner** [reactioncommerce/reaction#4561]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I disagree with the current functionality/approach that any add all tags created in any marketplace shop show up in the main navigation on the all shops.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create a second shop by the marketplace admin
2. login to second shop
3. create new main navigation tags

## Possible Solution
I suggest that main navigation tags only should be able to be displayed my marketplace owner.
there should be a second main navigation, within each individual shop, that sits below the main navigation/tags

### Versions
(run `reaction -v` from your reaction directory)

1.14.1 and 1.5

**Comment by aldeed** [comment]
This bug refers to a feature that is no longer part of newer releases. Will not be fixed in 1.x
