### ISSUE TITLE
Create GraphQL backend for notifications

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4568]
We want to rewrite the notification icon to use GraphQL but there's currently no backend.

**Comment by aldeed** [comment]
Work to be done in `/imports/plugins/included/notifications`:

- Add `Notification` GraphQL type to GraphQL schema
- Add `notificationsForAccount(accountId: ID!): NotificationConnection` query to GraphQL schema.
    - Include all the standard pagination params
    - Add `NotificationConnection` type to schema and return that, following established patterns
    - Allow sorting by "timeSent" field, ascending or descending
- Add `notificationsForAccount` internal query function
    - For now throw access denied unless the logged in account matches `accountId` param
    - Return `Notifications.find({ to: accountId })` cursor
- Write the `notificationsForAccount` resolver, calling through to internal `notificationsForAccount` function, following established patterns
- Create a Jest integration test file for the query and write tests:
    - When logged in, returns multiple pages of your own notifications successfully
    - Error if you query for a different account
    - Error if you query when not logged in

**Comment by brent-hoover** [comment]
@aldeed Was this work done or just y'all just decided to not work on it?

**Comment by aldeed** [comment]
@zenweasel My understanding is we decided to remove the old notifications implementation for now.
