### ISSUE TITLE
Theme for Bootstrap 4 & Sass

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#458]
New reaction theme that uses Bootstrap 4 & Sass.

**Comment by bluerabbbit** [comment]
+1

**Comment by bluerabbbit** [comment]
How about adding the fontawesome fontpicker for currency support as well?

**Comment by mikemurray** [comment]
project started here: https://github.com/reactioncommerce/reaction-main-street-theme

**Comment by rymorgan** [comment]
@mikemurray Is this still something we are planning on?

**Comment by aaronjudd** [comment]
Closing - insufficient details. (and we have a path forward in progress for separated client ui )
