### ISSUE TITLE
React Context vs MobX

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4580]
## Issue Description
We are currently using Meteor's session variables for any global UI state we need. It'd be neat if we could remove that dependency and replace UI state with either Mobx or React's Context API.

This ticket is to create 2 PRs - one for Context, one for Mobx - that implements the respective state library for a simple feature or two.

**Comment by aldeed** [comment]
The PRs were created and a core team discussion resulted in a decision to use MobX, which will be implemented as soon as it is needed for something. Closing this.
