### ISSUE TITLE
Issue install reaction 

### ISSUE THREAD

**Issue by adnaan07** [reactioncommerce/reaction#4591]
C:\Users\adnaa\my-reaction-projects>reaction init

Cloning the master branch of Reaction from Github...

Cloning into 'reaction'...
remote: Counting objects: 136102, done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 136102 (delta 49), reused 106 (delta 24), pack-reused 135896
Receiving objects: 100% (136102/136102), 49.60 MiB | 211.00 KiB/s, done.
Resolving deltas: 100% (77342/77342), done.
Checking out files: 100% (2373/2373), done.

Installing NPM packages...

> dtrace-provider@0.8.7 install C:\Users\adnaa\my-reaction-projects\reaction\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js

C:\Users\adnaa\my-reaction-projects\reaction\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Users\adnaa\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\adnaa\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

> fibers@2.0.2 install C:\Users\adnaa\my-reaction-projects\reaction\node_modules\fibers
> node build.js || nodejs build.js

`win32-ia32-57` exists; testing
Binary is fine; exiting

> sharp@0.20.5 install C:\Users\adnaa\my-reaction-projects\reaction\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp Windows x86 (32-bit) node.exe is not supported
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install

C:\Users\adnaa\my-reaction-projects\reaction\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\adnaa\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\adnaa\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
..\src\libvips\cplusplus\VError.cpp(33): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file or di
rectory [C:\Users\adnaa\my-reaction-projects\reaction\node_modules\sharp\build\libvips-cpp.vcxproj]
..\src\libvips\cplusplus\VImage.cpp(41): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file or di
rectory [C:\Users\adnaa\my-reaction-projects\reaction\node_modules\sharp\build\libvips-cpp.vcxproj]
..\src\libvips\cplusplus\VInterpolate.cpp(34): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file
 or directory [C:\Users\adnaa\my-reaction-projects\reaction\node_modules\sharp\build\libvips-cpp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\adnaa\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\adnaa\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_5\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\adnaa\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_5\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\adnaa\my-reaction-projects\reaction\node_modules\sharp
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.5 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.20.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adnaa\AppData\Roaming\npm-cache\_logs\2018-08-31T16_48_15_968Z-debug.log

Error: Node modules were not successfully installed. Exiting.

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).

**Comment by adnaan07** [comment]
Thanks Brent. I'm based in Tanzania but cant make TZS the default currency
or even get it to appear in the exchange currency list. Please help.
