### ISSUE TITLE
Multiple Packages Available to Client... Which to Choose?

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#4593]
## Prerequisites
* [ ] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
There are times where we need Packages corresponding to the Primary Shop and other times where we need Packages for the Marketplace Shop. To accomplish this, we subscribe to the Packages collection twice, once for each shop. The result is the `Packages` collection available to the client will have documents for each shop, meaning statements like this are not specific enough:
``` JavaScript
Packages.findOne({ name: "reaction-social" });
```
this query returns would return two documents, choosing the first one it finds, which is typically the Primary Shop's social settings, as reported in #4352. Often times, this is not what we want.

## Steps to Reproduce
1. as reported in #4352, go to any Marketplace Shop's Social Settings (not the OAuth settings for key/secret, but the place where you enter your twitter handle) and you will see the _Primary Shop's_ social settings.

## Possible Solution
Update _all_ calls to `Packages.findOne` to include a `shopId` key.
The tricky part will be deciding whether it should be `shopId: Reaction.getShopId()` or `shopId: Reaction.getPrimaryShopId()`

### Versions
```
Node: 6.11.3
NPM: 3.8.6
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.1
Reaction branch: master
Docker: 17.09.0-ce
```

**Comment by aldeed** [comment]
I agree that all queries should have `shopId`. I've been fixing this on the server side as I demeteorize and port things to GraphQL. I've also started some marketplace documentation (will push soon), where we can make clear what shop is expected to be used in various situations.

**Comment by aldeed** [comment]
Marketplace plugin is no longer built in. In general all GraphQL queries that need to take a `shopId` param.
