### ISSUE TITLE
Enable REST API in reaction docker image

### ISSUE THREAD

**Issue by mfaizanse** [reactioncommerce/reaction#4596]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [Y ] Are you running the latest version?
* [Y ] Are you able to consistently reproduce the issue?
* [Y] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I want to enable REST api's for reaction commerce. The [blog here](https://blog.reactioncommerce.com/our-take-on-rest-apis/) suggests to use simple:rest meteor pacakge. But I am unable to find any official docker image for reaction with simple:rest installed or any documentation for how to install it in the dockerfile?

If anyone can share the steps to install simple:rest in dockerfile. I tried to add "RUN meteor add simple:rest" in dockerfile but it gave me this error:

```
Step 8/21 : RUN meteor add simple:rest
 ---> Running in fb7da59f1f22
add: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.
```

## Possible Solution
There should be a flag in the docker image to enable the REST API for reaction.

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction. We would be glad to answer your questions, provide you more help via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com). Closing this issue.
