### ISSUE TITLE
Account Icon disappears after logging in

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4614]
## Issue Description
When you log in the "account" icon in the top nav disappears so you can log out

![login_disappears](https://user-images.githubusercontent.com/72819/45273698-6aacfe00-b4e6-11e8-8422-9d8e4872eeb0.gif)

## Steps to Reproduce
1. Start app in incognito or logged out
1. log in
1. Observe that Account icon disappears

### Versions
Reaction 1.15

**Comment by zenweasel** [comment]
This is only happening sometimes for me. If I `reaction reset -n` it seems to disappear

**Comment by loanlaux** [comment]
I've seen this happen as well but was never able to understand the cause.

**Comment by aldeed** [comment]
Faulty UI was removed in 2.0.0
