### ISSUE TITLE
Reaction freezes at this point 

### ISSUE THREAD

**Issue by Azambadar** [reactioncommerce/reaction#4615]
I am not sure either this is the right place for this issue ,so please bear with me as  I'm trying to run app on Docker and after doing all steps , app freezes at this point
 `reaction_1   | /home/node/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
reaction_1   |       throw error;
reaction_1   |       ^
reaction_1   |
reaction_1   | Error: EISDIR: illegal operation on a directory, unlink '/opt/reaction/src/.meteor/local/dev_bundle'
reaction_1   |     at Object.fs.unlinkSync (fs.js:1061:18)
reaction_1   |     at exports.makeLink (/tools/cli/dev-bundle-links.js:20:8)
reaction_1   |     at exports.ReleaseFile.ensureDevBundleLink (/tools/project-context.js:1529:7)
reaction_1   |     at exports.ReleaseFile._readFile (/tools/project-context.js:1463:10)
reaction_1   |     at new exports.ReleaseFile (/tools/project-context.js:1413:8)
reaction_1   |     at /tools/cli/main.js:932:22
reaction_1   | Failed to install npm dependencies for plugin: connectors-shopify
reaction_reaction_1 exited with code 1
mongo_1      | 2018-09-10T15:53:51.512+0000 I NETWORK  [listener] connection accepted from 172.18.0.4:40524 #1 (1 connection now open)
mongo_1      | 2018-09-10T15:53:51.524+0000 I NETWORK  [conn1] received client metadata from 172.18.0.4:40524 conn: { driver: { name: "nodejs", version: "3.0.5" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.93-boot2docker" }, platform: "Node.js v8.11.3, LE, mongodb-core: 3.0.5" }
devserver_1  | Connected to MongoDB
devserver_1  | GraphQL listening at http://localhost:3030/graphql-alpha
devserver_1  | GraphiQL UI: http://localhost:3030/graphiql`

Can someone look into this and let me know what this means ? many thanks

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time.
