### ISSUE TITLE
Ensure MongoDB replica set command is finished before starting Reaction

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4629]
## Background
In docker-compose, `reaction` depends on `mongo-init-replica` in order to initialize a replica set because Meteor reactivity needs oplog support.

## Problem
`mongo-init-replica` exits after running the mongo command, but it takes a bit of time for the replica set to fully initialize. This can cause Reaction to start up with errors.

## Solution
There are different possible solutions.
- Change the startup script for `reaction` to wait until there is a confirmed replica set before running `reaction` command
- Change `mongo-init-replica` to run a script that not only runs the command but won't exit until the replica set init is done.

**Comment by focusaurus** [comment]
So according to the docker docs on startup order, wating for mongo-init-replica to exit won't work as docker-compose only deals with start order and will start reaction after mongo-init-replica but without waiting for mongo-init-replica to start. Docker recommends the container application code itself deal with waiting for dependencies to be healthy OR using the health check mechanism. There are at least 2 reasonable approaches to try and probably more.  I have initial versions of both shell script and javascript flavors of this.  Here's what I'm proposing for discussion/review:

- Add a new script to the reaction container `waitReplica.js`
  - This will connect to mongo, exiting with an error if it cannot
  - poll for replica set status every 1s until healthy (`1`). Exit 0 when healthy.
  - Exit with an error if not healthy after 30s
  - Question for @aldeed is there a better place than `imports/node-app/core/util/waitReplica.js` for this to live?
- Add this script to the reaction container's start command with some `&&` so if it fails, `reaction` won't start

**Comment by focusaurus** [comment]
I'm leaning toward the startup script approach because it's one-and-done. Once it's done, it's out of the picture and reaction runs as normal. Seems like a more conservative choice whereas the docker health check mechanism is more actively checking in an ongoing poll, with more potential for operational surprises.

**Comment by aldeed** [comment]
@focusaurus That approach makes sense. I suggest `.reaction/waitForReplica.js`. The `.reaction` folder is where code that isn't part of the app proper goes.
