### ISSUE TITLE
Product search result has blank image

### ISSUE THREAD

**Issue by vchong88** [reactioncommerce/reaction#4639]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? 

## Issue Description
When accessing RC as non-login user, the Product Search results does not contain product image
<img width="600" alt="screen shot 2018-09-18 at 12 02 53 pm" src="https://user-images.githubusercontent.com/22272050/45663956-bf322800-bb3b-11e8-9707-9def9eb336a4.png">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Open browser as incognito mode
2. Search product based on product tag
3. Search result does not contain product image

Note: If you have previously login as user
1. Sign-out user
2. Refresh browser
3. Search product based on product tag
4. Search result does not contain product image

## Possible Solution
Allow product search images to be displayed to non-login user

### Versions
Node: 6.2.1
NPM: 6.1.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.16.0
Reaction branch: master
Docker: 18.03.1-ce

**Comment by dancastellon** [comment]
@vchong88 I noticed this while implementing our new `CatalogGrid` component in the Meteor app. Fix should be merged soon!

**Comment by dancastellon** [comment]
Closing this - merging the 2.0 version of the catalog grid PR fixed this.
