### ISSUE TITLE
Update SetEmailOnAnonymousCartInput to use cartToken instead of token param name

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#4642]
### Summary
`SetEmailOnAnonymousCartInput`, `RemoveCartItemsInput` and perhaps others  input types, use a param named `token` to required the request to provide an anonymous cart token, other input types use `cartToken` such as `SelectFulfillmentOptionForGroupInput`.  This inconsistency leads to unnecessary client code. Lets add consistency by using `cartToken` as the param name for all inputs.

**Comment by Aberman12** [comment]
I can take this issue on if its still available

**Comment by willopez** [comment]
It would be great to have either one of you work on this issue. Here is a tutorial on how to setup Reaction 2.0 https://docs.google.com/spreadsheets/d/11JNIp2pEowynT9iokzcKglOaW27bmaZAs6y4UjSjXew/edit#gid=0

**Comment by richPurba** [comment]
Please provide me the access to the spreadsheet above, as i am thinking to help as well

**Comment by willopez** [comment]
@richPurba I have updated the link to the getting started tutorial.

**Comment by willopez** [comment]
resolved in https://github.com/reactioncommerce/reaction/pull/5820
