### ISSUE TITLE
Add firstName and lastName to GraphQL Account type

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4646]
## Work
Add GraphQL resolvers that split `account.name` and return values for `firstName` and `lastName`. Client UI often needs these separated, and it doesn't make sense for every client to write that code.

Do a bit of research on whether we should be using different field names and how we should be splitting the `name`. Some cultures do not have last names or the surname is first. Is there a software schema best practice we can follow?

**Comment by zenweasel** [comment]
I feel like the generally accepted practice nowadays is to just do one "name" field. Also splitting fn/ln usually messes with people who use a middle initial or people with three names like Sarah Jessica Parker.

**Comment by aldeed** [comment]
@zenweasel That's correct, but it doesn't change the fact that in some places we need/want them split. Examples:
- Avatar circle shows first and last initials if no actual avatar
- Some places in UI design call for showing first name / given name / preferred name only. People might also want to do this in an email: "Hey Eric! Your order just shipped!" or "Dear Mrs. Robinson"

So for shipping/billing address purposes there is no doubt that we just need `name` but for general account purposes we need to either collect more types of names from the user or split the `name` or some combo of those.

A related issue is that the new designs have separated first name and last name fields for addresses, but it's unclear how you put c/o or company name to ship to your office for example.

**Comment by zenweasel** [comment]
Right. I think the point would be that the use of first name/last name is inherently Eurocentric and is a practice that should be deprecated from designs as well as code as part of our Code of Conduct. Maybe that needs to a separate issue for design to revisit?

**Comment by spencern** [comment]
@rymorgan let's have a discussion about first name / last name vs name and decide if this is something that's important to us.

**Comment by rymorgan** [comment]
@spencern Sounds good. I'll add to our product design meeting

**Comment by zenweasel** [comment]
@aldeed @spencern Can we close this now?

**Comment by machikoyasuda** [comment]
@aldeed @spencern Can we close this now?

**Comment by aldeed** [comment]
I don't remember what was decided for this, but if the decision is documented somewhere in case people ask about this again, then I'm ok with closing this.

**Comment by spencern** [comment]
@rymorgan I know we've made a decision on this - I believe it was to use Full Name and to introduce "preferred" name or "nickname" elsewhere. Not sure if/where this is documented.

**Comment by rymorgan** [comment]
@spencern TBH I don't remember (not to self to always take notes). I'm good with the solution of having Full name along with preferred name. I also don't think this is documented anywhere or executed.
