### ISSUE TITLE
Stripe payment form self resets

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4652]
## Issue Description
Stripe payment form will clear itself and you will receive an error in the browser console:

```
Error: No Template["examplePaymentForm"] exists.  If this template originates in your app, make sure you have the `templating` package installed (and not, for e.g. `static-html`)
```

http://recordit.co/tuRtq7BHwp

## Steps to Reproduce
1. Attempt to check out with Stripe payment enabled
1. Fill out info
1. Wait 10-15 seconds (YMMV)
1. Observe that the form is now empty

### Versions
Reaction: 2.0.0 on staging environment

**Comment by zenweasel** [comment]
Verified this doesn't happen on `master`

**Comment by aldeed** [comment]
@zenweasel That would happen only if the "example" payment method is also enabled AND migration 39 did not properly run for some reason. So I don't think there's anything to fix here.

**Comment by zenweasel** [comment]
This is happening on staging though

**Comment by zenweasel** [comment]
From staging:

![2018-09-21_12-05-19](https://user-images.githubusercontent.com/72819/45859807-a2ddf780-bd96-11e8-8efb-0f1d1fa1f203.png)

**Comment by zenweasel** [comment]
From staging

![2018-09-21_12-05-19](https://user-images.githubusercontent.com/72819/45859834-c0ab5c80-bd96-11e8-9d0f-0c3ad9c3fce3.png)
