### ISSUE TITLE
Can't checkout with Custom Rates enabled

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4654]
## Issue Description
If you enable "Custom Rates" tax method you basically can't get past the address book

## Steps to Reproduce
1. Enable custom rates and set a rate for State and one for Zipcode
1. Attempt to checkout either as anonymous or registered
1. Observe that shipping rates never appear except every once in a while they do but then you can't change rates.

### Versions
Reaction 1.16

**Comment by aldeed** [comment]
@zenweasel This is the manifestation of #4620. It's fixed in 1.17.0 and 2.0.0, but I don't think we're planning to fix for 1.16.0, as stated in that issue.
