### ISSUE TITLE
Product image doesn't show up in admin

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4656]
## Issue Description
Product image shows up in checkout, etc. but not in the order admin

## Steps to Reproduce
1. Place an order for a product that has an image
1. Visit the order in the order admin
1. Observe that the product image just shows the placeholder 

### Versions
Reaction: 2.0.0

**Comment by aldeed** [comment]
This will need more investigation because I cannot reproduce it. Might have something to do with which variant you ordered and whether that has an image?

**Comment by zenweasel** [comment]
This order on staging. I believe this product has no options.

![2018-09-21_12-14-45](https://user-images.githubusercontent.com/72819/45860083-fc92f180-bd97-11e8-9466-5aa3f364fdb3.png)

**Comment by aldeed** [comment]
I verified that as you click down the orders on staging, some have the image and some have the placeholder, but it's not correlated with having options or not. Need to investigate more tomorrow.

**Comment by aldeed** [comment]
I believe this is working in 2.0.0. Can re-open if not
