### ISSUE TITLE
Some prices ranges are shown as 0 in grid when logged in as Admin

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4658]
## Issue Description
When you log in as admin some of the prices are shown as 0.

![2018-09-21_10-38-30](https://user-images.githubusercontent.com/72819/45857259-80de7800-bd8a-11e8-8312-6275003c1220.png)

## Steps to Reproduce
1. Visit staging
1. Login as admin
1. Observe that some of the price ranges are 0

## Possible Solution
This could be related to sample data

### Versions
Reaction: 2.0.0 (on staging)

**Comment by aldeed** [comment]
This is an issue with the catalog sample data. As soon as you edit anything about those products, the price range gets recalculated and fixed. I will fix and push an updated 2.0 dataset.
