### ISSUE TITLE
Add a linter for maintaining code style

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#466]
I think we could increase readability and overall uniformity by enforcing a style guide especially now that we have both ES2015.

**The future goal is to have linting based check on the CI.**

But I don't think we have an established style guide yet:exclamation: 
So we could start with this: https://github.com/meteor/meteor/blob/devel/scripts/admin/eslint/.eslintrc and tweak it to fit our requirements.

**Comment by aaronjudd** [comment]
decent blog post on this: https://www.yauh.de/writing-clean-javascript-code-with-eslint-and-js-beautify/
He has a file here that works: https://github.com/yauh/meteor-with-style/blob/master/.eslintrc

I've been testing this https://www.npmjs.com/package/eslint-config-meteor-official (not really an offical package) but uses that meteor lint file.  (you'll find some forum post, this meteor dev .eslintrc file is a WIP)

Also for reference see: https://github.com/percolatestudio/development-guide

I''m having a hard time getting it to work well in Atom (my editor of choice at the moment) though, it seems like the Atom-linter is a little out of date. Using: https://github.com/AtomLinter/linter-eslint
and it seems to be unaware of the global meteor environment. I'm still looking into it, but I think it's not using my global installation of `eslint` and  `babel-eslint`.

**Comment by aaronjudd** [comment]
Closed in https://github.com/reactioncommerce/reaction/commit/23251967ed2cc87076ead3d532611b4dc10d9fc1

- adds .eslintrc - add beautify config
- updates editorconfig
- adds eslintrc

See: http://info.meteor.com/blog/set-up-sublime-text-for-meteor-es6-es2015-and-jsx-syntax-and-linting

For Atom installation use:
```
apm uninstall linter linter-eslint
npm i --save-dev eslint babel-eslint
apm install linter linter-eslint
```
