### ISSUE TITLE
Clicking on Tags on PDP doesn't take you to Tag page

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4661]
## Issue Description
Clicking on the tags on the Product Detail Page does not take you to the Tag page. It's marked as a link `<a>` and mousing over it shows it as clickable so I feel like that was the intent but it doesn't seem to work.

## Steps to Reproduce
1. Go the PDP for the "Basic Reaction Product"
1. Click on "Shop" under Tags
1. Observe that nothing happens

### Versions
Reaction: 1.16 (at least, might have been earlier)

**Comment by aldeed** [comment]
This is referring to a UI that was removed in 2.0.0
