### ISSUE TITLE
Orders stays dim after choosing an order for more details which blocks interaction

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction#4666]
## Issue Description
When you go click an order's > for more details within the Orders panel, it dims and loads information. However, once the information is loaded it stays dim which then blocks interaction with the detailed pop-up. Clicking the screen returns you back to orders.

Fixes itself if you resize the window smaller.

![Screen Shot 2018-09-21 at 10.36.09 AM.png](https://images.zenhubusercontent.com/59f9d6498a75884b9085a1b4/5cb58a52-6117-4c78-8fe1-96b24e332d51)

## Steps to Reproduce
a. Have a full sized browser window
1. Have an order 
2. Click the right arrow button for more details of specific order
3. Wait for loading
4. Click screen to un-dim

### Versions
```
node : 10.10.0
npm  : 6.4.1
Reaction : 2.0.0 (docker-compose up)
```

**Comment by nnnnat** [comment]
Reopening this issue because we've reverted the "fix" in #4772 .

**More info:**
In the admin dashboard orders panel, one would occasionally see an issue where the orders "sub" panel would either not render or be obscured by the "modal overlay". This issue only happened with screen sizes between `950px - 1100px`.

**Comment by nnnnat** [comment]
![screen shot 2018-10-26 at 1 32 50 pm](https://user-images.githubusercontent.com/1135948/47587209-c95bf900-d927-11e8-999e-82d0b1f73cbc.png)

**Comment by chrispotter** [comment]
@nnnnat Is this still an issue? Seems the interface for this has changed in the Operator.

**Comment by nnnnat** [comment]
@chrispotter yeah this issue is for the old UI, I'll close it
