### ISSUE TITLE
Order amount shown in incorrect format in Order Panel

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4675]
## Issue Description

When placing an order a float is being introduced somewhere

![2018-09-25_09-28-10](https://user-images.githubusercontent.com/72819/45987711-9e228780-c0a5-11e8-8dde-f0b08cf81e6c.png)

## Steps to Reproduce
1. Reset database
1. Enable shipping and either payment method
1. Place an order for the Basic Reaction Product (19.99) + 2.99 shipping
1. Go to the order panel and open up detail for an order
1. Observe that order amount shows an extended float

## Possible Solution
Needs to be converted to `account.toFixed` somewhere

### Versions
Reaction: 2.0.0-rc1

**Comment by chrispotter** [comment]
@zenweasel  Is this still an issue? I can't seem to recreate with reaction sample data.

**Comment by zenweasel** [comment]
@chrispotter If you have tested it thoroughly and can't reproduce it let's close it. We can always reopen if someone runs into it again.
