### ISSUE TITLE
Support wishlist during shopping

### ISSUE THREAD

**Issue by cooloney** [reactioncommerce/reaction#468]
Currently users can't save the products during shopping but only saving them into cart.

Wishlist is a good feature to support this.

**Comment by cooloney** [comment]
@mikemurray my friend @lhz516 Hanz will work on this feature. If he has some questions, please help to answer.

I think the right place is to add a similar solution to Cart into core package and we don't need to create a separated package for this wishlist feature, right? @mikemurray

**Comment by aaronjudd** [comment]
Closing - insufficient details.
