### ISSUE TITLE
Navigation Backend

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4682]
## Issue Description
Currently, the navigation only supports tags. In order to support our future CMS integration plans, we need a navigation that can support both tags and arbitrary links.

## Solution
The end goal is to create a UI that allows operators to easily manage the navigation and add tags and links. To start, we need a GraphQL backend that allows for the creation of navigation items and trees. Trees should allow navigation items to be nested up to 3 levels deep.

New NavigationItems and NavigationTrees collections will be created in core, replacing the existing tag nav logic. The NavigationItems collection will store basic information about links, and allow other parts of the app to store metadata about the link, if required. The primary use case for metadata is to store a tagId if an operator creates a tag and assigns it to be in the navigation.

The NavigationTrees collection will store the _ids of items that make up the tree, in a hierarchical tree structure.

**Comment by mikemurray** [comment]
Merged https://github.com/reactioncommerce/reaction/pull/4683. Closing.
