### ISSUE TITLE
Document how we round and total

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4692]
This issue is a spinoff of https://github.com/reactioncommerce/reaction/issues/4684#issuecomment-425473131

The outcome should be public documentation about how we round and total an order, and why. Development changes may be necessary after this discussion, in order for the system to match whatever documentation we write, so creating issues for those necessary changes is another outcome of this issue.

Considerations:
- At what points should rounding occur and how (floor/ceil/nearest)? E.g., does each item's tax get rounded to nearest and then totaled to get total tax? Or does tax get totaled and then rounded? These will yield slightly different amounts for total tax. Same question for discounts.
- What does "nearest cent" mean? There might be differences in which decimal place we should round to per currency? And some currencies do not have cents, but these could end up being fractional if cut in half by a discount or multiplied by a non-integer sales tax percentage.
- There may be legal requirements for how to apply and round taxes (multiply by each item subtotal vs multiply by order total)
- There may be business requirements for how to apply and round discounts
- We use `account.js` to format money values for display. It's readme lists "Add choice of rounding method for precision (up, down or nearest-neighbour)" as a future feature, but does not state the current rounding method. It appears to be rounding to nearest. It also has open issues about rounding errors (https://github.com/openexchangerates/accounting.js/issues/195). We may want to use something else if this library is not properly maintained.

cc @spencern @ticean I will add to architecture meeting agenda.

**Comment by aldeed** [comment]
Related: https://docs.mongodb.com/manual/tutorial/model-monetary-data/

It may be best to develop a plan to convert all floats to `NumberDecimal` in MongoDB

**Comment by zdanowiczkonrad** [comment]
Regarding problem with accounting.js that is unmaintained, consider using my lightweight alternative - [https://github.com/zdanowiczkonrad/number-currency-format](number-currency-format) - I developed it for my purpose initially, but seems like it gives more control about precision and rounding and there should be definitely a way to solve your issue (otherwise, I am open to extend it for your needs!).
