### ISSUE TITLE
GraphQL for Products create/update

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4698]
**Requirements:**

We need to be able to create a product, or replace an existing product via an API via HTTP and have that product validated using the GraphQL schema, or get back validation messages.

Also need to be able to add to Media records that point to a URL.

The API needs to be able to authenticate as a user with `createProduct` permissions (or however they are currently defined).

**Comment by nei** [comment]
Any idea on when it is planned to be done?

**Comment by aldeed** [comment]
It isn't planned yet, but we are fast approaching a need for it. Best guess sometime in the next 3 months.

**Comment by gmartinsribeiro** [comment]
Hello! Is this part of the short-term roadmap?
I'm trying to figure out how to bulk insert products and this feature would be an option.

Best regards,
Gonçalo

**Comment by aldeed** [comment]
#5404 recently started work in this direction, and more product mutations will be added in the coming months, starting with bulk update mutations similar to the add/remove tags ones. If you need it earlier than a few months from now, I'd suggest a plugin that directly uses Mongo bulk write API.

**Comment by aldeed** [comment]
These mutations were added in 3.0 branch
