### ISSUE TITLE
Create a mechanism for dynamically adding client routes

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4702]
#### Requirements

Routes are currently defined in plugins'`register.js` files, and only used in the main Reaction app. We need a way to dynamically define routes and the content they should render, for Storefront.

The initial use case is to be able to add routes for pages created in a third-party CMS.

The solution should likely not send all routes to Storefront at once, but rather have Storefront query the server right before a 404 would normally be displayed.

**Comment by aldeed** [comment]
Done in Reaction Admin
