### ISSUE TITLE
Option for whether products should appear in sitemap

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4705]
## Requirements
Currently, all published products are included in the generated sitemaps. We need a way to allow operators to choose whether a product should be included or not.

## Proposed Solution

- Add a checkbox in the PDP operator panel labelled "Include in sitemap?" that defaults to checked
- When changed, if the product is published, popup an alert: "Regenerate sitemap now?". If yes, trigger the sitemap generation job
- Convert the "sitemaps/generate" method to a GraphQL mutation so that external import jobs can trigger sitemap generation without using Meteor
- Add a migration that sets `shouldAppearInSitemap` to true for all current products

**Comment by zenweasel** [comment]
Closed via #4708
