### ISSUE TITLE
Not able to set tax on cart.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4710]
## Issue Description
There has been this change in 2.0 that `taxes/setRateByShopAndItem is replaced by non-Meteor getFulfillmentGroupItemsWithTaxAdded`.
But that function is not setting taxes in the cart. It basically gets taxes from `Taxes` collection and returns them merged with `cart.items`.
We need to have function that would set taxes in the cart, which can be used by tax-plugins.

I am blocked by this while writing a tax-plugin.

**Comment by Akarshit** [comment]
I am setting the taxes right now by updating the mongo collection. But we need a GraphQL mutation that would do this.

**Comment by Akarshit** [comment]
@spencern Does this sound like something that core could prioritise in their sprint?

**Comment by aldeed** [comment]
@Akarshit I'm beginning work on this and all related tax issues today.
