### ISSUE TITLE
Should `onCartUpdate` be called after updating tax in a plugin

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4712]
## Issue Description
The function to calculate the tax in tax-plugins are run on `afterCartUpdate` event. These functions get the tax an update the cart with the new tax. If `afterCartUpdate` is fire after this, it causes the function to run again.....
But shouldn't `afterCartUpdate` be called after updating the cart with tax rate?

**Comment by aldeed** [comment]
In the linked PR, this is fixed by emitting it, but with an `emittedBy` flag that prevents it from rerunning itself.
