### ISSUE TITLE
Checkout page is sometimes frozen

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#472]
Hi, 
It occurred to me several times that I go to the checkout page with a logged in user, but the second step is not active, (you can see it on the image), after refresh the second step is active and I can select the address. Before the refresh there is nothing you can do to move on.
![screenshot from 2015-10-02 14 47 30](https://cloud.githubusercontent.com/assets/9323474/10250081/7f3b7774-6931-11e5-85b9-1bc53a440050.png)

**Comment by aaronjudd** [comment]
Is resolved in pre-beta (0.9)

**Comment by aaronjudd** [comment]
This happens when the workflow is in the wrong state. This should be resolved now in v0.9.0, but the workflow may  a little stronger enforcement. I'll keep an eye on this, and appreciated any feedback or ideas.
