### ISSUE TITLE
CatelogItem: compareAtPrice does not have currency symbol. No displayCompareAtPrice exists

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4722]
## Issue Description

`displayCompareAtPrice` in the `pricing` object doesn't exist, so getting the `compareAtPrice` with the currency symbol as a string is not as easy as the `displayPrice`.

## Steps to Reproduce

1. Set the "compare at price" for a variant
2. Publish
3. Look in the DB or make a GQL query for that catalog item that contains the updated variant.
4. See only a `float` type for the "compare at price"

## Possible Solution

Add a `displayCompareAtPrice` with the proper currency symbol

### Versions

Node: 10.7.0
NPM: 6.2.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.2
Reaction branch: master
Docker: 18.06.1-ce

**Comment by aldeed** [comment]
We may want to change `compareAtPrice: Float` to `compareAtPrice: Money` instead. We use `Money` type everywhere else, but we just can't use it for the product price because it is sometimes a range.

**Comment by mikemurray** [comment]
In addition to the fix proposed by @aldeed, which is adding a new resolver for `compareAtPrice`, I'm seeing issues with `currencyExchangePricing`. It's `compareAtPrice` field and is also returning bad values. Going to try and address this as well.

**Result from GQL**
```
                "currencyExchangePricing": {
                  "displayPrice": "$NaN.undefined - $NaN.undefined",
                  "price": null
                },

```
