### ISSUE TITLE
Stripe 'Capture' Fails Quietly After 7 Days

### ISSUE THREAD

**Issue by willmoss1000** [reactioncommerce/reaction#4726]
## Prerequisites
* [ ] Are you running the latest version? NO - 1.4.1
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? 

## Issue Description
If the shop owner does not 'capture'  the stripe charge within 7 days it expires. 'Capture' then fails quietly. There is also no warning to the user that they needed to approve and capture within a given time period. 

### Versions
**1.4.1**

**Comment by willmoss1000** [comment]
Your suggestions would make a huge difference. In addition I think it could also be worth having a status of "expired"?

It's also a little confusing that the status shows as "Completed" when the payment still needs to be captured.

Agreed, this can be largely sorted by educating users. However, I've experienced some edge cases whereby the user was unable to capture an order (as I'd edited their items as the primary shop), and they were not made aware "Capture Payment" had failed. The most important fix here is making sure that the "Capture Payment" button fails loudly.

**Comment by spencern** [comment]
I see. Thanks for that additional bit of feedback. I didn't realize in my first read through your issue that the Capture Payment button was not notifying the user that the capture operation had failed. I'll update my note above to include that suggestion as well.

**Comment by aldeed** [comment]
@spencern Maybe the enhancement suggestions can be split to a new issue and this one can be labeled as bug? Not displaying the Stripe errors seems like a problematic issue to prioritize higher than the others.

**Comment by spencern** [comment]
Good idea @aldeed.
@willmoss1000 would you be willing to split this into two issues?

**Comment by willmoss1000** [comment]
Good idea. Please see:
i) Capture fails quietly: https://github.com/reactioncommerce/reaction/issues/4763
ii) Shop owners not warned they need to "capture" an order within 7 days: https://github.com/reactioncommerce/reaction/issues/4764

**Comment by spencern** [comment]
@willmoss1000 thank you for filing detailed issues for both of these!
