### ISSUE TITLE
publishToCatalog drops PDP Template selection

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4728]
## Issue Description
When publishing to catalog, the catalog item lacks the "template" field, if a PDP template has been set.

## Steps to Reproduce
1. Create a Product and set template to Two Column layout
2. Publish and revisit site as non-admin
3. Notice how the PDP of that product still has the same layout
4. Take a look at the db and notice that the catalog record lacks that field.

## Possible Solution
Include the template field in the publishToCatalog xforms.

### Versions
1.16 - Didn't test if 2.0.0 RCs are affected aswell.

**Comment by aldeed** [comment]
Won't fix. PDP templates are no longer supported in 2.0, and 1.x track is critical fixes only.
