### ISSUE TITLE
Dynamically referenced tags

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4734]
## Issue Description
The new Storefront displays a tag hierachy / breadcrumbs at the top, for example:
`Home > Accessories > Watches > Minimalist`
When I go into tag edit mode (in the meteor ui) and type a similar name, the already existing tag with a similar name  is suggested. So I go ahead and choose it.
The new route should therefore be
`Home > Shoes > Boots > Minimalist`
However the tag link will be the same, /tag/minimalist
The breadcrumbs still show as `Home > Accessories > Watches > Minimalist`

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Open the classic UI (I used https://storefront.staging.reactioncommerce.com/)
2. Enter tag edit mode and add an existing Tag somewhere else
3. Visit the Storefront (I used https://storefront.staging.reactioncommerce.com) and notice how the breadcrumbs show the orginal url

## Proposal
1. Make the tag page parse multiple tags at once, query the catalog for items that have all listed tag Ids.
2. Change the Tag navigation to build links that always include the parent tag(or parent/parent for three levels).

A route `Home > Accessories > Watches > Minimalist` would therefore display products that have all of the three mentioned tags.
Therefore, tags like `Minimalist` would really be universal and would not have to be recreated for each individual route.

This is mostly a matter of UI changes, as the underlying tag schema already supports such a way of handling tags with the `relatedTagIds`, and probably would not break existing configurations (except for when products do not already include all tags down their route)

The catalogItems graphQL query also already support an array of tags, but matches for one of, on not all of them.
When I implemented this feature, I duplicated that query as `catalogItemsRestrictive`, with a single change to the mongo query in there.

I sucessfully implemented that behaviour in 1.16, but at that time without the breadcrumbs in mind.

Blockers: The admin product grid in the meteor app is separated and doesn't use Apollo yet. So the feature needs to be reimplemented there, or the admin view needs be replaced.
I also was unsure how to handle routes: In my inital implementation they are separated by `%2C`/`,` and later separated by splitting the string - I'm unhappy with that solution.
Now with also the breadcrumbs in mind, I'd prefer a solution that separates by subroutes with slash, but I couldn't verify yet if the current router supports defining routes like /tags/n amount of tags/...
If that would not work out, we could atleast define routes that go down to /tags/taglevel1/2/3 to be in line with the current representation in the UI.

Please share your thoughts on this way of handling tags. :)

### Versions
Probably latest, 2.0.0-rc.2 according to the shops collection at https://reaction-catalog-sample.staging.reactioncommerce.com

**Comment by aldeed** [comment]
I believe this is no longer relevant since the introduction of a proper Navigation builder
