### ISSUE TITLE
Match products schema with catalog schema

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4737]
Currently, some fields in the schema differ for no appareant reason.
products.taxable became isTaxable in the Catalog,
products.handle became slug.
While for the products collection weight, length, width and height can only be set per variant,
Catalog allows them for both CatalogProduct and Variant.

Maybe it would be good to match these schemas and write a migration.

**Comment by aldeed** [comment]
This is definitely the plan. Catalog schema represents the desired state, while product revamp isn't done yet.

However, weight, etc. on CatalogProduct might be a mistake. If it can only be set on variants, then it shouldn't be on CatalogProduct. It's probably always null right now. Would you mind making a separate bug report issue about that?

**Comment by aldeed** [comment]
`product.isTaxable` is updated and migrated in 2.0 RC 7

**Comment by aldeed** [comment]
Leaving this open for tracking since this was not done in 3.0
