### ISSUE TITLE
Cart doesn't persist from guest user to registered user

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#474]
Fresh install with all local packages installed (via `bin/clone-packages.sh`)

If I add a product to my cart and subsequently register as a user my cart is emptied.

**Comment by aaronjudd** [comment]
:-1: mostly fixed in 0.9, still tracking down some issues though

**Comment by aaronjudd** [comment]
I believe this should now be resolved.

**Comment by aaronjudd** [comment]
There actually might be a merging bug with multiple products, I need to do more investigation. If you see anything strange, please open a new issue with steps to replicate.
