### ISSUE TITLE
Catalog variant `isSoldOut` and `isLowQuantity` are always false

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4741]
## Issue Description

The denormalized inventory flags for `isSoldOut` and `isLowInventory` are always `false` for variants in the catalog.

## Steps to Reproduce
1. Go to a product
2. Set variant to the quantity to 0
3. Turn off backorders
4. Publish
5. Look in mongo for that Catalog Variant
6. See that `isSoldOut` is `false` even though it should be true

## Possible Solution

In `createCatalogProduct.js` function `xformVariant(variant, variantPriceInfo, shopCurrencyCode, variantMedia)` always receives `undefined` for variants.

`xformVariant` will have to do some additional processing to determine the correct inventory flags and not assume they come from the params.

### Versions

Node: 10.7.0
NPM: 6.2.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.5
Reaction branch: fix-4722-mikemurray-compare-at-price
Docker: 18.06.1-ce

**Comment by spencern** [comment]
@mikemurray can we close this? I see we merged #4742.
