### ISSUE TITLE
[bug] UI - Social media icons too close to text connected to it.

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction#4756]
## Issue Description
The social media icons connected through authentication are too close to respective text.

Login:
![Screen Shot 2018-10-19 at 12.48.56 AM.png](https://images.zenhubusercontent.com/59f9d6498a75884b9085a1b4/81c3a021-4acc-468a-b24c-9c62a7f9248f)

Mobile:
![Screen Shot 2018-10-18 at 3.27.12 PM.png](https://images.zenhubusercontent.com/59f9d6498a75884b9085a1b4/09af1260-ad46-4977-a7e3-7e7265680f28)

Desktop: 
![Screen Shot 2018-10-18 at 3.22.47 PM.png](https://images.zenhubusercontent.com/59f9d6498a75884b9085a1b4/970cef1f-5dec-452e-bf5c-eb5169394de8)

## Steps to Reproduce
1. Enable Social Media Login Services under Admin Panel
2. Log-out
3. Attempt to log-in / guest checkout
4. Notice UI issue.

## Possible Solution
More spacing distance between icon and text.

### Versions
Reaction 2.0.0-rc.5

**Comment by spencern** [comment]
@jeffcorpuz was this resolved in rc.5?

**Comment by jeffcorpuz** [comment]
@spencern this was not resolved in rc.5 : 

<img width="392" alt="screen shot 2018-12-09 at 4 19 59 pm" src="https://user-images.githubusercontent.com/6117033/49704953-51434d00-fbce-11e8-8889-7a05f68bc138.png">
<img width="303" alt="screen shot 2018-12-09 at 4 19 30 pm" src="https://user-images.githubusercontent.com/6117033/49704954-51dbe380-fbce-11e8-889d-157c0024d638.png">

**Comment by chrispotter** [comment]
@spencern @jeffcorpuz now that storefront is separate from Catalyst, should I close this issue? If the issue still exists, we can recreate in the appropriate frontend example repo.

**Comment by jeffcorpuz** [comment]
@chrispotter sounds good to me.
