### ISSUE TITLE
[bug] Currencies non-alphabetical after enabling all via Localization

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction#4757]
## Issue Description
The currency drop-down list is non-alphabetical after enabling all the currencies.

![Screen Shot 2018-10-19 at 12.57.11 AM.png](https://images.zenhubusercontent.com/59f9d6498a75884b9085a1b4/8ea49723-ca76-4fab-b0a3-d08f3fed237f)

## Steps to Reproduce
1. Go to Localization on Admin Panel
2. Enable All Currencies
3. Refresh page
4. Press Drop Down menu for Currency on Nav Bar

### Versions
Reaction 2.0.0-rc.5

**Comment by chrispotter** [comment]
Solved by PR #5230
