### ISSUE TITLE
navigation missing on refresh

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#477]
before:
![screenshot 2015-10-07 22 20 20](https://cloud.githubusercontent.com/assets/439959/10358318/a7ee342c-6d41-11e5-9868-7ed9eac2f364.png)
after:
![screenshot 2015-10-07 22 20 29](https://cloud.githubusercontent.com/assets/439959/10358317/a7ed6380-6d41-11e5-94b5-932e8450c1e7.png)

**Comment by mikemurray** [comment]
Issue has been resolved. It was a variable scoping issue with the new ES6 "let" vars.
