### ISSUE TITLE
[bug] Custom Tax Rates Not Applying - 1.17 Port Fix

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction#4775]
**Solved/Resolved** : https://github.com/reactioncommerce/reaction/issues/4655

## Issue Description
Even though Custom Rates are enabled they are not applied on checkout, however when looking at "Orders" in detail, the tax will be applied.

## Steps to Reproduce
1. Enable Custom Rates for X
1. Attempt to checkout with an address in X
1. Observe that taxes are not applied in checkout

## Solution
Port 1.17 Fix (https://github.com/reactioncommerce/reaction/pull/4664)

### Versions
Reaction: 1.17 (https://github.com/reactioncommerce/reaction/pull/4761)

**Comment by spencern** [comment]
It does not seem like we can cherry-pick the fixes from #4664 as that relies on the 2.0.0 create order methods. We may be able to use the same concept, but will have to find the files that need to be fixed in the 1.17 release.

**Comment by spencern** [comment]
I believe this is only issue left blocking 1.17.0 I'll take a look at it tomorrow

**Comment by spencern** [comment]
Resolved by #4806
