### ISSUE TITLE
RTL UI Alignment issues

### ISSUE THREAD

**Issue by perpi** [reactioncommerce/reaction#478]
Please report issues with rtling here. Don't forget to add some screenshots.

    1. The Price is out of its field:

![fee_out](https://cloud.githubusercontent.com/assets/7093244/10375817/58dae6fc-6e07-11e5-87c0-23a2c737e6fe.png)

    2. In rtl mode, product image should be in right side of the page:
http://demo.reactioncommerce.com/product/HPCyrCcGAGyDPXbon (choose العربیه)

    3. The menu which is near the user icon, is not rtl:

![profile_menu](https://cloud.githubusercontent.com/assets/7093244/10375953/23a3b1ca-6e08-11e5-9bd4-e66f8af1d894.png)
Notice to the position of the word 'Profile' --> It should NOT be in left side of the menu

**Comment by aaronjudd** [comment]
If you want to keep reporting them here, we can do a cleanup pass on these and get them all taken care of at once very quickly.  Some are flexbox issues, others need to correct .rtl mixins applied. Should be easy to run through and clean them all up.

**Comment by mikemurray** [comment]
The product detail page has been updated and resolves its RTL issues.

The dropdown is going to be fixed now.
