### ISSUE TITLE
Babel doesn't transpile Jest tests files in custom plugins that have a package.json

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4781]
## Prerequisites
* [x] Are you running the latest version? 2.0.0-rc.6
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
Babel 7 doesn't transpile files in sub-directories that have a package.json when Babel is configured through package.json or .babelrc. This causes Jest test failures in custom plugins that have a package.json. It isn't an issue with non-test files because those are imported through the main Reaction app (see /server/plugins.js and client/plugins.js). Babel does transpile these files when it is configured through the new babel.config.js. Meteor currently only loads Babel config through .babelrc or package.json, though. 

## Steps to Reproduce
1. Create a folder inside `imports/plugins/custom`
2. In the folder, run `npm init` and create an empty package.json
3. Create a file named log.js with `console.log("test");` in it
3. Create a log.test.js file with the following content:
```
import "./log";
test("Simple test", () => { expect(true).toBe(true); });
```
4. Back in the reaction root dir, run `meteor npm run test:unit`
5. Observe `Unexpected token import...` error coming from log.test.js

## Possible Solution
Create a `babel.config.js` in the root dir that loads package.json->babel and exports it.

**Comment by zenweasel** [comment]
Closed via #4782
