### ISSUE TITLE
Google Search Console Plugin for Reaction 2.0

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/reaction#4784]
## Issue Description
The current Google Search Console plugin is not compatible with the new decoupled architecture of Reaction's back-end operator app and the Front-end app.  The current plugin also has a spot for google analytics integration, which is no longer needed due to the segment integration that already exists.  Note that segment does not contain a google search console integration. 

## Possible Solution
Build a new plugin for only google search console integration that is built for Reaction 2.0 and above.  It could have a similar UI/UX for entering the url code generated by the google search console account.  This would need to be processed and published by the front end graphQL API in order for google bots to register and reconcile the ownership of the front end URL and the google search account.

**Comment by zenweasel** [comment]
Closing as there are other/better options available
