### ISSUE TITLE
OAuth IDP Login Page returns a Not Found Page

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#4794]
Type: **bug|regression**

## Issue Description
OAuth IDP login pages created by the Hydra plugin are not showing up in the latest release candidate 6. So `/account/login` returns Not Found.

Going back a few commits (e.g `d37e12b2ea92`), the page shows up fine.

## Steps to Reproduce

1. Run the Starterkit latest, Reaction rc-6, and Hydra master
2. Try to login (or create account) on the Starterkit
3. You'll be shown a "Not Found" page on the Meteor app instead of Login form

## Possible Solution
My guess is that a new update to the Router is making it not find the needed template/component. (or maybe caused by the latest released patches?)

### Versions
Node: 8.11.3
NPM: 6.3.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.6
Reaction branch: release-2.0.0-rc.6

**Comment by impactmass** [comment]
oops. closed by mistake

**Comment by impactmass** [comment]
fixed in #4835. Log in on the Starterkit works now

**Comment by impactmass** [comment]
Well... not sure if the right thing is to close this now since it's still on a release-candidate branch

**Comment by zsimoes** [comment]
I was about to ask that. Is there a chance #4835 will go into master before the RCs are stable (as it's a regression)? Or should we use the rc7 branch until the 2.0.0 release?

We're using Reaction-Platform and everything is working wonderfully, except for the login flow (which prevents any acceptable usage).

**Comment by impactmass** [comment]
hey @zsimoes, because this is a crucial fix I'm certain it will be out [asap] in next release we're going to make (either a release candidate or stable release).
