### ISSUE TITLE
Make sitemap URLs/Data available through GraphQL

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4796]
Currently the sitemaps are generated on the server-side and available through the "classic UI". But since that has been deprecated we need to make this information available through GraphQl so that implementers can consume this info and implement this on the client-side.

**Comment by impactmass** [comment]
Added in https://github.com/reactioncommerce/reaction/pull/4927 and https://github.com/reactioncommerce/reaction-next-starterkit/pull/488
