### ISSUE TITLE
Shippo option not showing to add api key

### ISSUE THREAD

**Issue by mrkhanakia** [reactioncommerce/reaction#4797]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [ YES ] Are you running the latest version?
* [TES ] Are you able to consistently reproduce the issue?
* [ YES] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Shippo Option not showing in the Shipping so how do i add apikey as mentioned in the docs
https://docs.reactioncommerce.com/docs/shipping-admin

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Installed latest version
2. Logged into admin
3. Tried to add shippo api key but no option is showing

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
(run `reaction -v` from your reaction directory)
Node: 10.11.0
NPM: 6.4.1
Reaction CLI: 0.29.0
Docker: 18.03.0-ce

**Comment by aldeed** [comment]
@mrkhanakia Shippo plugin isn't yet updated to be compatible with Reaction 2.0

**Comment by machikoyasuda** [comment]
Shippo is no longer supported in Reaction.
