### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by ShwetaSridharan** [reactioncommerce/reaction#4804]
=> Started proxy.
Local package version is up-to-date: accounts-base@1.3.1
Local package version is up-to-date: accounts-facebook@1.2.1
Local package version is up-to-date: accounts-github@1.3.0
Local package version is up-to-date: accounts-google@1.2.0
Local package version is up-to-date: accounts-meteor-developer@1.3.0
Local package version is up-to-date: accounts-oauth@1.1.15
Local package version is up-to-date: accounts-password@1.4.0
Local package version is up-to-date: accounts-twitter@1.3.0
Local package version is up-to-date: aldeed:autoform@5.8.1
Local package version is up-to-date: aldeed:collection2@2.5.0
Local package version is up-to-date: aldeed:collection2-core@2.0.1
Local package version is up-to-date: aldeed:geocoder@0.3.8
Local package version is up-to-date: aldeed:simple-schema@1.5.3
Local package version is up-to-date: aldeed:template-extension@4.0.0
Local package version is up-to-date: allow-deny@1.0.6
Local package version is up-to-date: amr:parsley.js@2.0.4
Local package version is up-to-date: angular:angular@1.2.24
Local package version is up-to-date: anti:i18n@0.4.3
Local package version is up-to-date: aramk:collection-table@0.5.0
Local package version is up-to-date: aramk:q@1.0.1_1
Local package version is up-to-date: aramk:tinycolor@1.1.0_1
Local package version is up-to-date: arkham:comments-ui@1.4.3
Local package version is up-to-date: arkham:stars-rating-ui@0.2.9
Local package version is up-to-date: aslagle:reactive-table@0.8.42
Local package version is up-to-date: babel-compiler@6.19.4
Local package version is up-to-date: babel-runtime@1.0.1
Local package version is up-to-date: barbatus:stars-rating@1.1.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: bevanhunt:leaflet@3.1.1
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-html-templates@1.1.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.1.1
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: cfs:http-methods@0.0.32
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: cleandersonlobo:sweetalert2@1.4.0
Local package version is up-to-date: coffeescript@1.12.6_1
Local package version is up-to-date: cosmos:browserify@0.5.1
Local package version is up-to-date: crouck:mapbox@2.3.1
Local package version is up-to-date: dandv:caret-position@2.1.1
Local package version is up-to-date: dburles:collection-helpers@1.0.4
Local package version is up-to-date: ddp@1.3.0
Local package version is up-to-date: ddp-client@2.0.0
Local package version is up-to-date: ddp-common@1.2.9
Local package version is up-to-date: ddp-rate-limiter@1.0.7
Local package version is up-to-date: ddp-server@2.0.0
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: didstopia:admzip@0.1.0
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: dispatch:run-as-user@1.1.1
Local package version is up-to-date: dynamic-import@0.1.1
Local package version is up-to-date: ecmascript@0.8.2
Local package version is up-to-date: ecmascript-runtime@0.4.1
Local package version is up-to-date: ecmascript-runtime-client@0.4.3
Local package version is up-to-date: ecmascript-runtime-server@0.4.1
Local package version is up-to-date: ejson@1.0.13
Local package version is up-to-date: email@1.2.3
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: facebook-oauth@1.3.2
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: fortawesome:fontawesome@4.5.0
Local package version is up-to-date: fourseven:scss@4.5.4
Local package version is up-to-date: francocatena:status@1.5.3
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: github-oauth@1.2.0
Local package version is up-to-date: google-oauth@1.2.4
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.2.12
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: jalik:ufs@0.7.4_1
Local package version is up-to-date: jalik:ufs-gridfs@0.2.1
Local package version is up-to-date: jcbernack:reactive-aggregate@0.7.0
Local package version is up-to-date: jeffpatzer:jquery-payment@0.0.5
Local package version is up-to-date: jparker:crypto-core@0.1.0
Local package version is up-to-date: jparker:crypto-md5@0.1.1
Local package version is up-to-date: jparker:gravatar@0.5.1
Local package version is up-to-date: jplack:bootstrap-timepicker@0.1.1
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: kadira:blaze-layout@2.3.0
Local package version is up-to-date: kadira:flow-router@2.12.1
Local package version is up-to-date: konecty:change-case@2.3.0
Local package version is up-to-date: konecty:delayed-task@1.0.0
Local package version is up-to-date: konecty:mongo-counter@0.0.5_3
Local package version is up-to-date: konecty:multiple-instances-status@1.0.6_1
Local package version is up-to-date: konecty:nrr@2.0.2
Local package version is up-to-date: konecty:user-presence@1.2.9
Local package version is up-to-date: lamatyus:scrollreveal@3.3.2
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: lepozepo:s3@5.2.8
Local package version is up-to-date: less@2.7.9
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.1.1
Local package version is up-to-date: logging@1.1.17
Local package version is up-to-date: markdown@1.0.12
Local package version is up-to-date: matb33:collection-hooks@0.8.4
Local package version is up-to-date: mdg:geolocation@1.3.0
Local package version is up-to-date: mdg:validation-error@0.5.1
Local package version is up-to-date: meteor@1.7.0
Local package version is up-to-date: meteor-base@1.1.0
Local package version is up-to-date: meteor-developer-oauth@1.2.0
Local package version is up-to-date: meteorhacks:aggregate@1.3.0
Local package version is up-to-date: meteorhacks:async@1.0.0
Local package version is up-to-date: meteorhacks:collection-utils@1.2.0
Local package version is up-to-date: meteorhacks:inject-initial@1.0.4
Local package version is up-to-date: meteorhacks:npm@1.5.0
Local package version is up-to-date: meteorhacks:picker@1.0.3
Local package version is up-to-date: meteoric:autoform-ionic@0.1.6
Local package version is up-to-date: meteorspark:util@0.2.0
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minifier-js@2.1.1
Local package version is up-to-date: minimongo@1.2.1
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.9.2
Local package version is up-to-date: modules-runtime@0.8.0
Local package version is up-to-date: momentjs:moment@2.18.1
Local package version is up-to-date: mongo@1.1.22
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: mongo-livedata@1.0.12
Local package version is up-to-date: mrgalaxy:stripe@2.2.2
Local package version is up-to-date: mrt:external-file-loader@0.1.4
Local package version is up-to-date: mrt:moment@2.8.1
Local package version is up-to-date: mrt:moment-timezone@0.2.1
Local package version is up-to-date: mrt:nprogress@0.2.0
Local package version is up-to-date: mrt:reactive-store@0.0.1
Local package version is up-to-date: mystor:device-detection@0.2.0
Local package version is up-to-date: natestrauser:select2@4.0.3
Local package version is up-to-date: natestrauser:x-editable-bootstrap@1.5.2_4
Local package version is up-to-date: nilsdannemann:pdfmake@1.0.38
Local package version is up-to-date: nimble:restivus@0.8.12
Local package version is up-to-date: nooitaf:colors@1.1.2_1
Local package version is up-to-date: npm-bcrypt@0.9.3
Local package version is up-to-date: npm-mongo@2.2.30
Local package version is up-to-date: oauth@1.1.13
Local package version is up-to-date: oauth1@1.1.11
Local package version is up-to-date: oauth2@1.1.11
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: okgrow:analytics@3.0.5
Local package version is up-to-date: ongoworks:pdf@1.1.1
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: ostrio:cookies@2.2.2
Local package version is up-to-date: pauli:accounts-linkedin@2.1.3
Local package version is up-to-date: pauli:linkedin-oauth@1.1.0
Local package version is up-to-date: pcel:serialize@1.0.1
Local package version is up-to-date: peerlibrary:async@1.5.2_1
Local package version is up-to-date: peppelg:bootstrap-3-modal@1.0.4
Local package version is up-to-date: percolate:synced-cron@1.3.2
Local package version is up-to-date: pfafman:filesaver@1.3.2
Local package version is up-to-date: phund:angularjs-dropdown-multiselect@1.5.2
Local package version is up-to-date: promise@0.8.9
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: raix:eventstate@0.0.4
Local package version is up-to-date: raix:handlebar-helpers@0.2.5
Local package version is up-to-date: raix:push@3.0.3-rc.7
Local package version is up-to-date: raix:ui-dropped-event@0.0.7
Local package version is up-to-date: rajit:bootstrap3-datepicker@1.7.1_1
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: rate-limit@1.0.8
Local package version is up-to-date: rcy:nouislider@7.0.7_2
Local package version is up-to-date: reactive-dict@1.1.9
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: reywood:publish-composite@1.4.2
Local package version is up-to-date: rochal:slimscroll@1.3.3
Local package version is up-to-date: rosh93:slide-panel@0.1.6
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: service-configuration@1.0.11
Local package version is up-to-date: session@1.1.7
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.2.4
Local package version is up-to-date: simple:json-routes@2.1.0
Local package version is up-to-date: smoral:sweetalert@1.1.1
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.2
Local package version is up-to-date: srp@1.0.10
Local package version is up-to-date: standard-minifier-js@2.1.1
Local package version is up-to-date: stylus@2.513.9
Local package version is up-to-date: talos:basic-auth@1.0.1
Local package version is up-to-date: tap:i18n@1.8.2
Local package version is up-to-date: templates:forms@2.1.4
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.2
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: themeteorchef:bert@2.1.3
Local package version is up-to-date: timbrandin:slick@1.5.8_1
Local package version is up-to-date: tmeasday:check-npm-versions@0.3.1
Local package version is up-to-date: tmeasday:crypto-base@3.1.2
Local package version is up-to-date: tmeasday:crypto-md5@3.1.2
Local package version is up-to-date: todda00:friendly-slugs@0.6.0
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: twbs:bootstrap@3.3.6
Local package version is up-to-date: twitter-oauth@1.2.0
Local package version is up-to-date: udondan:jszip@2.4.0_1
Local package version is up-to-date: udondan:zipzap@2.2.2_1
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: underscorestring:underscore.string@3.3.4
Local package version is up-to-date: urbanetic:utility@1.2.3
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: webapp@1.3.17
Local package version is up-to-date: webapp-hashing@1.0.9
Local package version is up-to-date: xolvio:backdoor@0.2.1
Local package version is up-to-date: yasaricli:slugify@0.0.7
Local package version is up-to-date: zardak:soap@0.2.6
=> A patch (Meteor 1.5.4.2) for your current release is available!
   Update this project now with 'meteor update --patch'.

Unable to resolve some modules:

  "!!../../node_modules/css-loader/index.js!../../node_modules/sass-loader/index.js!./card.scss" in
/C/Users/Shweta Sridharan/Documents/GitHub/fitset/fitset/public/js/card_validator/card.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save !!..

   Linking                                   -
<--- Last few GCs --->

  177797 ms: Scavenge 696.5 (730.8) -> 696.5 (730.8) MB, 1.4 / 0 ms (+ 0.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  178146 ms: Mark-sweep 696.5 (730.8) -> 695.8 (730.8) MB, 345.3 / 0 ms (+ 0.0 ms in 2 steps since start of marking, biggest step 0.0 ms) [last resort gc].
  178510 ms: Mark-sweep 695.8 (730.8) -> 695.6 (730.8) MB, 365.6 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 29625599 <JS Object>
    1: new constructor(aka Variable) [C:\Users\Shweta Sridharan\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\escope\lib\variable.js:~35] [pc=1E7B72A1] (this=06FE05E9 <a Variable with map 2351C031>,name=33183D41 <String[13]: DEFAULT_PORTS>,scope=320EB1AD <a FunctionScope with map 2351C31D>)
    3: __defineGeneric [C:\Users\Shweta Sridharan\AppData\L...

**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory**

I am not able to run this application on my windows 10 machine. I tried increasing the heap size as well. Is there any other way I could do this?

**Comment by aldeed** [comment]
There are no plans to officially support Reaction 2.0 development on a Windows machine, but it should theoretically work since all development is now done within Docker. You may need to play with various settings for Docker CPU and memory: https://docs.reactioncommerce.com/docs/troubleshooting-development#memory-errors-or-errors-about-meteor-rawlogs
