### ISSUE TITLE
Uncaught Error: Encountered a sub-selection on the query, but the store doesn't have an object reference. This should never happen during normal use unless you have custom code that is directly manipulating the store; please file an issue.

### ISSUE THREAD

**Issue by fabien-h** [reactioncommerce/reaction#4809]
## Prerequisites
* [ OK  ] Are you running the latest version?
* [  OK ] Are you able to consistently reproduce the issue?
* [  OK ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

The front is not working. When I open the console, I get this message :

````
Uncaught Error: Encountered a sub-selection on the query, but the store doesn't have an object reference. This should never happen during normal use unless you have custom code that is directly manipulating the store; please file an issue.
````

It literally tells me to open an issue. So here am I.

## Steps to Reproduce

1. git clone https://github.com/reactioncommerce/reaction.git
2. cd reaction
3. meteor npm i
4. reaction

### Why

It looks like something coming from an issue between my environment and and reaction. All my other meteor projects are working well.

**Comment by fabien-h** [comment]
Last version. The one you have when you clone the repo.

And :

~ reaction -v

Node: 10.6.0
NPM: 6.4.1
Meteor Node: 8.11.4
Meteor NPM: 6.3.0
Reaction CLI: 0.29.0
Docker: 18.06.1-ce

**Comment by aldeed** [comment]
Nobody has reported this on recent releases. Closing
