### ISSUE TITLE
Navigation builder operator UI

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4810]
## Description
#4683 Introduces a GraphQL API for building and loading a navigation tree that supports both tags and arbitrary links. We need a UI that will allow operators to create navigation items and drag them into a hierarchical tree.

The current design prototype can be found here: https://projects.invisionapp.com/share/7NOSCIQH6JM#/screens

**Comment by mikemurray** [comment]
The navigation editor exists in the operator UI now. Closing.
