### ISSUE TITLE
isBackorder property needed on Catalog item's variants and options

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#4814]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The `isBackorder` property is only added to a top-level Catalog item and not added to the item's variants or options.

## Steps to Reproduce
View the [schema code](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/no-meteor/schemas/schema.graphql#L150) to see the `isBackorder` prop only on the top-level catalog item.

## Possible Solution
1. Add the property to the variant/option schema
2. Refactor `createCatalogProduct` [xform](https://github.com/reactioncommerce/reaction/blob/b49fbf03519fecd58925929a01ec17475d6d2e0c/imports/plugins/core/catalog/server/no-meteor/utils/createCatalogProduct.js#L131) functions to resolve the property for each variant/option.

### Versions
```sh
release-2.0.0-rc.7
```

**Comment by spencern** [comment]
@kieckhafer Can we close this now?

**Comment by kieckhafer** [comment]
Closed via #4855
