### ISSUE TITLE
Configure Payment Link not responding

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#483]
on a fresh build while checkout, not able to configure payment by clicking link. Before click router is **http://localhost:3000/checkout** and post click it changes to **http://localhost:3000/dashboard** but no screen to Login nor any message.

![image](https://cloud.githubusercontent.com/assets/14071646/10391087/2eed885c-6e9a-11e5-88c7-517c29f1f24b.png)

**Comment by aaronjudd** [comment]
I'm not able to replicate on development branch. Were you testing in development or master branch, I think this might have been patched by https://github.com/reactioncommerce/reaction/issues/477
