### ISSUE TITLE
Cannot create multiple tags with the same name

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4831]
## Issue Description
It's logical to want to use Tags to categorize Products like Clothing/Women's/Shoes but currently you can only have one Tag called shoes.

## Steps to Reproduce
1. Add a Tag called Women's with a Subtag called Shoes
1. Add a Tag called Men's with Subtag called Shoes
1. Observe that these both point to the same Tag/URL even though they should be separate

### Versions
Reaction: 2.0.0-rc.6

**Comment by spencern** [comment]
What is the expectation around how this should work? If you create two tags called shoes, how should the urls be differentiated?

I agree with your premise that there's a use case for multiple tags with the same name. I'd lean towards categorizing this as an enhancement as well, I don't believe that this functionality has worked before or been mapped out.

**Comment by zenweasel** [comment]
Just to close this out I think the idea is that the URL would reflect the hierarchy (e.g. `tags/clothing/womens/shoes` but the name would just reflect the display name 'Shoes". This would obviously involve some work to change how we route/parse URL's

**Comment by Akarshit** [comment]
Also a very small part of this is to also modify the code that imports data from `/private/custom` should be checking uniqueness of `slug` instead of `name`.
