### ISSUE TITLE
HIgh CPU Usage with Docker Hyperkit

### ISSUE THREAD

**Issue by carlosbaraza** [reactioncommerce/reaction#4832]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The CPU usage is really high and my 2015 Macbook Pro is not holding, becoming extremely slow and unstable. This is a well known Docker for Mac (Hyperkit) issue, due to I/O watching.

How do you overcome this issue? Don't you develop with under OSX?

## Steps to Reproduce
1. Using OSX
2. `docker-compose up`

## Possible Solution
I tried using a different docker-machine (Virtualbox). However, this was really slow to boot up Meteor. Another sort of workaround is to run everything locally, without Docker, but if this is the way to go, the docs should be updated to reflect it.

### Versions
```
Node: 9.3.0
NPM: 6.3.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Docker: 18.09.0
```

**Comment by carlosbaraza** [comment]
@calindotgabriel Interesting idea, although it would not allow offline development.

@spencern thank you. I'll check that out.

**Comment by aldeed** [comment]
This is being slowly avoided by moving away from Meteor and by running the Meteor projects from their built images, which are then only Node. There is still a cumulatively high CPU on Mac when running all the projects at once, but that's a general complaint about Docker for Mac, and I don't see anything else actionable here so I'm closing this.
