### ISSUE TITLE
Extend Tag schema to include new fields

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4837]
## Issue Description

I wanted to start a discussion on the best way to let clients add attributes to the Tags schema.
One way could be to write a plugin that basically modifies the Tags schema(by extending it), but we might want to add some of the SEO related fields to the core Tags Scehma like: `page-title`, `page-description`, `page-keywords`.

**Comment by spencern** [comment]
We'll be working on a more robust tag system in the coming weeks and adding SEO related fields is on the docket for that project.

We should consider how we'd like to address the need for custom attributes for tags, perhaps without requiring a separate plugin.

Thanks for getting the discussion started.

**Comment by zenweasel** [comment]
@Akarshit Can you look at the tickets that @machikoyasuda has created for the Tags pod? I feel like she created a ticket that covered this topic. If you can't find it let me know.

**Comment by machikoyasuda** [comment]
Hey @Akarshit 👋 

This is exactly what we're working on right now. We're adding these fields to `Tags`:
- `displayTitle`: to add a custom title on the tag's product listing page - https://github.com/reactioncommerce/reaction/pull/4856 ☑️
- `isActive`: to determine whether a tag's listing page should be public or not https://github.com/reactioncommerce/reaction/pull/4869 - in progress
- use the already-created `metafields` array to add metadata - just merged to starter-kit: https://github.com/reactioncommerce/reaction-next-starterkit/pull/453/files

**Comment by Akarshit** [comment]
@machikoyasuda Hey, is it possible now to add something to `metafields` that get's transferred to the page's `<title>`?

**Comment by machikoyasuda** [comment]
@Akarshit Take a look at this PR that we just merged in Starter Kit: https://github.com/reactioncommerce/reaction-next-starterkit/pull/453/files#diff-ba46cdd7e47e33e40dbab312b2adf504L107

Once the Starter Kit side pulls in any `metafields` from a `Tag`, you should be able to render it in the template anywhere you want. Here's the docs I wrote up: https://github.com/reactioncommerce/reaction-next-starterkit/blob/develop/docs/tags.md

Does this cover what you need?
