### ISSUE TITLE
Available Payment options are hardcoded for v2.x

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4841]
## Issue Description
The array for available payment templates is hardcoded in v2.x.
I noticed this while reimplementing my Paypal Express Integration.

In [imports/plugins/core/payments/client/checkout/payment/methods.js](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/payments/client/checkout/payment/methods.js#L11-L15
) there are template names defined for the included plugins, ignoring custom plugins that might be added.

## Steps to Reproduce
1. Simply take a look at the linked code above and notice why this won't work
#
**Or**
1. Create your own payment plugin, or copy the example plugin and replace all instances of example/Example to avoid issues, including file names.
2. Enable the new plugin in the dashboard
3. Try to checkout and notice how the new plugin doesn't show up as availabe payment option, while there is no error thrown (and no hint of it in reacts virtual dom inspector.)
4. Manually add paymentMethods.name as key + the name of the component you registered as value to the templates object in the file linked above.
5. Verify that the payment option is displayed now.

## Possible Solution
The `availablePaymentMethods` query already lists available payment options, including custom ones.
It returns name and pluginName.

Option A: add an additional field to be returned from the query, e.g. templateName
Option B: Enforce a naming convention like it is done for capture/authorize methods, and derive the component name from pluginName.

### Versions
v2.0.0-rc.7

**Comment by aldeed** [comment]
See comment: https://github.com/reactioncommerce/reaction/issues/4893#issuecomment-452813044
