### ISSUE TITLE
Add primary shop ID fallback to `primaryShopId` GraphQL query

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4842]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The `primaryShopId` GraphQL query returns `null` if the domain to which you make the request isn't in the `domains` array of any shop. While it's not usually hard to add all domains to the list in a production db, this is an unnecessary burden for CI staging deploys and local development.

## Steps to Reproduce
1. In MongoDB, clear the `domains` array for all shops.
2. Query with GraphQL `{ primaryShopId }`

## Possible Solution
`Reaction.shopId` falls back to `Shops.findOne({ shopType: "primary" })`, which the GraphQL query should also do.

### Versions
2.0

**Comment by spencern** [comment]
Could we permit wildcard domains for situations like this?

**Comment by kieckhafer** [comment]
Closed via #4862
