### ISSUE TITLE
Reaction Commerce Store (1.8.2) not showing in IE 11

### ISSUE THREAD

**Issue by kathiresh-i2i** [reactioncommerce/reaction#4857]
Reaction Commerce (1.8.2) is not loading in Internet explorer version 11. 

## Prerequisites
* [ ] Are you running the latest version?   
  No. Using Reaction Commerce 1.8.2
* [ ] Are you able to consistently reproduce the issue? 
  Yes. Store is not opening in IE 11

## Issue Description
When trying to open Reaction Commerce (1.8.2) store in Internet Explorer 11 the page showing blank and throwing the following errors in console.

HTML1300: Navigation occurred.
192.168.15.249:3000
SCRIPT1014: Invalid character
modules.js (28772,21)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
babel-runtime.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
promise.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
url.js (17,1)
SCRIPT5007: Unable to get property 'URL' of undefined or null reference
http.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
dynamic-import.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
ecmascript-runtime-client.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
webapp.js (17,1)
SCRIPT5007: Unable to get property 'WebApp' of undefined or null reference
server-render.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
es5-shim.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
base64.js (17,1)
SCRIPT5007: Unable to get property 'Base64' of undefined or null reference
ejson.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
diff-sequence.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
geojson-utils.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
id-map.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
random.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
mongo-id.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
ordered-dict.js (17,1)
SCRIPT5007: Unable to get property 'DiffSequence' of undefined or null reference
minimongo.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
check.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
retry.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
callback-hook.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
ddp-common.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
reload.js (17,1)
SCRIPT5007: Unable to get property 'Retry' of undefined or null reference
socket-stream-client.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
ddp-client.js (17,1)
SCRIPT5007: Unable to get property 'DDP' of undefined or null reference
ddp.js (14,1)
SCRIPT5007: Unable to get property 'LocalCollection' of undefined or null reference
allow-deny.js (17,1)
SCRIPT5007: Unable to get property 'AllowDeny' of undefined or null reference
mongo.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
reactive-dict.js (20,1)
SCRIPT5007: Unable to get property 'ReactiveDict' of undefined or null reference
session.js (18,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
logging.js (18,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
localstorage.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
jquery.js (17,1)
SCRIPT5007: Unable to get property 'MongoID' of undefined or null reference
observe-sequence.js (19,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
blaze.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
accounts-base.js (20,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
service-configuration.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
mdg_validated-method.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
srp.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
accounts-password.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
oauth.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
accounts-oauth.js (18,1)
SCRIPT5007: Unable to get property 'OAuth' of undefined or null reference
facebook-oauth.js (17,1)
SCRIPT5007: Unable to get property 'ObserveSequence' of undefined or null reference
spacebars.js (17,1)
SCRIPT5007: Unable to get property 'Blaze' of undefined or null reference
templating-runtime.js (18,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
templating.js (14,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
facebook-config-ui.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
accounts-facebook.js (17,1)
SCRIPT5007: Unable to get property 'OAuth' of undefined or null reference
google-oauth.js (17,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
google-config-ui.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
accounts-google.js (18,1)
SCRIPT5007: Unable to get property 'OAuth' of undefined or null reference
twitter-oauth.js (17,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
twitter-config-ui.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
accounts-twitter.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
alanning_roles.js (18,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
aldeed_simple-schema.js (20,1)
SCRIPT5007: Unable to get property 'DDP' of undefined or null reference
livedata.js (14,1)
SCRIPT5007: Unable to get property 'Blaze' of undefined or null reference
ui.js (14,1)
SCRIPT5007: Unable to get property 'SimpleSchema' of undefined or null reference
aldeed_collection2-core.js (17,1)
SCRIPT5007: Unable to get property 'Collection2' of undefined or null reference
aldeed_schema-index.js (17,1)
SCRIPT5007: Unable to get property 'Collection2' of undefined or null reference
aldeed_schema-deny.js (17,1)
SCRIPT5007: Unable to get property 'SimpleSchema' of undefined or null reference
aldeed_autoform.js (17,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
aldeed_template-extension.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
bozhao_accounts-instagram.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
cfs_base-package.js (20,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_storage-adapter.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_filesystem.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_gridfs.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
cfs_data-man.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_file.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_ui.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
dispatch_run-as-user.js (17,1)
SCRIPT5007: Unable to get property 'Mongo' of undefined or null reference
matb33_collection-hooks.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
meteorhacks_subs-manager.js (20,1)
SCRIPT5007: Unable to get property 'Mongo' of undefined or null reference
ongoworks_security.js (17,1)
SCRIPT5007: Unable to get property 'Blaze' of undefined or null reference
raix_ui-dropped-event.js (17,1)
SCRIPT5007: Unable to get property 'Mongo' of undefined or null reference
tmeasday_publish-counts.js (17,1)
SCRIPT5007: Unable to get property 'Blaze' of undefined or null reference
gadicc_blaze-react-component.js (17,1)
SCRIPT5007: Unable to get property 'LocalCollection' of undefined or null reference
dburles_factory.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_access-point.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_upload-http.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_collection.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_collection-filters.js (17,1)
SCRIPT5007: Unable to get property 'Retry' of undefined or null reference
autoupdate.js (19,1)
SCRIPT5007: Unable to get property 'Session' of undefined or null reference
global-imports.js (3,1)
SCRIPT5009: 'meteorInstall' is undefined
app.js (1,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
mdg_validation-error.js (17,1)

## Steps to Reproduce
1. Open Reaction commerce 1.8.2 in IE 11
2. See console. It will show errors.

## Possible Solution
Please let us know If any packages needs to be added

### Versions
Node: 9.3.0
NPM: 5.5.1
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.8.2
Reaction branch: master

**Comment by zenweasel** [comment]
@kathiresh-i2i Generally we don't fix bugs on previous versions, you should always update to the latest version. In addition, this problem doesn't look like a problem with Reaction but with your local installation. Those errors are usually about the build not running correctly.

**Comment by kathiresh-i2i** [comment]
Hi, @zenweasel I cloned Reaction Commerce 1.8.2 from GitHub and checked. It is also having the same problem. The problem with 1.8.0 to 1.8.2 versions are babel version issues. Babel is not compiled correctly for IE 11 browser. Now I fixed that issue in my local. Thanks for responding.
