### ISSUE TITLE
WARN core: Load Settings is not an array. Failed to load settings.

### ISSUE THREAD

**Issue by graforlock** [reactioncommerce/reaction#486]
Reading through your guide, this is a settings.json file:

{
  "ROOT_URL": "",
  "MONGO_URL": "",
  "MAIL_URL": "",
  "reaction": {
    "REACTION_USER": "",
    "REACTION_AUTH": "",
    "REACTION_EMAIL": ""
  },
  "isDebug": "info",
  "public": {
    "velocity:html-reporter": {
      "position": "bottom right",
      "tab-index" : 1
    }
  }
}

But when I run it using --settings as provided in docs, it throws me error like in the subject:

WARN core: Load Settings is not an array. Failed to load settings.

It doesn't matter if I wrap it in array, still throws an error.

**Comment by aaronjudd** [comment]
That error is referring to private/settings/reaction.json (reaction configs) vs the Meteor.settings (which is for meteor packages). Does this help?https://github.com/reactioncommerce/reaction/blob/development/docs/developer/fixtures.md
