### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by humsterman86** [reactioncommerce/reaction#4861]
## Issue Description
When I run make script (on Ubuntu Server 18.04), I got error message:

```
> mongodb-memory-server@1.8.0 postinstall /opt/reaction/src/node_modules/mongodb-memory-server
> node ./postinstall.js

mongodb-memory-server: checking MongoDB binaries cache...
Downloading MongoDB: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian81-latest.tgz
Killedading MongoDB latest: 62.3 % (53.6mb / 86.1mb)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! mongodb-memory-server@1.8.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the mongodb-memory-server@1.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2018-12-12T05_55_19_199Z-debug.log
ERROR: Service 'reaction' failed to build: The command '/bin/sh -c meteor npm install' returned a non-zero code: 137
Makefile:182: recipe for target 'build-reaction' failed
make: *** [build-reaction] Error 1
```

## Steps to Reproduce
1. cd reaction-platform
2. make

**Comment by focusaurus** [comment]
This bit of log output looks interesting:

```Killedading MongoDB latest: 62.3 % (53.6mb / 86.1mb)```

That makes me suspect a process was killed during the postinstall script for mongodb-memory-server. My first theory would be maybe the linux kernel out of memory killer (OOM killer) reaped that process. Could you keep an eye on free memory and the kernel log messages with `dmesg | egrep -i “killed process”` while retrying and see if that is happening?

**Comment by arawaklabs** [comment]
I am having the exact same problem.

`dmesg | egrep -i “killed process”` gives me this:

`[67286.099653] Out of memory: Kill process 8182 (node) score 414 or sacrifice child
[67286.101889] Killed process 8182 (node) total-vm:1471748kB, anon-rss:420864kB, file-rss:0kB, shmem-rss:0kB
[67286.144257] oom_reaper: reaped process 8182 (node), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[67289.627900] docker0: port 1(veth5f93a22) entered disabled state
[67289.630631] veth1a1cff6: renamed from eth0
[67289.671709] docker0: port 1(veth5f93a22) entered disabled state
[67289.676278] device veth5f93a22 left promiscuous mode
[67289.678022] docker0: port 1(veth5f93a22) entered disabled state`

**Comment by AaronZhangL** [comment]
----------OS: Fedora28------------------
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ uname -a
Linux localhost.localdomain 4.19.8-200.fc28.x86_64 #1 SMP Mon Dec 10 15:43:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ cat /etc/redhat-release
Fedora release 28 (Twenty Eight)
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ docker --version
Docker version 18.09.0, build 4d60db4
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ npm --version
6.4.1
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ node --version
v8.12.0
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ ls 
99_bakByAZ  CODE_OF_CONDUCT.md  config.mk  CONTRIBUTING.md  docs  LICENSE.md  Makefile  reaction  reaction-hydra  reaction-next-starterkit  README.md
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ git branch -a

* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/reaction-users


----------Issue----------------------------
Run [make] command under the [reaction-platform] folder, I got below errors:
===========
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json
npm WARN saveError EACCES: permission denied, open '/opt/reaction/src/package-lock.json.3285523079'
npm WARN react-taco-table@0.5.1 requires a peer of react@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-taco-table@0.5.1 requires a peer of react-dom@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 31419 packages in 17.447s
found 8 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
MongoDB replica set initialized and ready.
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json

**Comment by kodermax** [comment]
I got this error too.

**Comment by aldeed** [comment]
The only error I see is with the `mongodb-memory-server` NPM package post-install hook. It could be just a temporary issue, but if it consistently happens, I'd recommend submitting an issue on that repo.
