### ISSUE TITLE
eMail templates were not updated for the new order schema

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4864]
## Issue Description
The new order schema does not provide a variants object for items anymore.
The email Templates still relies on `{{variants.title}}` and `{{variants.displayPrice}}`

While `sendOrderEmail()` already works with the new schema,
e-Mails regarding orders (new, shipped, refunded, itemRefund) lack the variant title and the price per item.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Complete an order.
2. Notice that confirmation email lacks variant title and price.

## Possible Solution
Replace `{{variants.title}}` with `{{variantTitle}}`
Replace `{{variants.displayPrice}}`with `{{price.displayAmount}}`

### Versions
v2.0.0-rc.x - v2.0.0-rc.7

**Comment by zenweasel** [comment]
@machikoyasuda Is this fixed with all the changes to the new templates?

**Comment by machikoyasuda** [comment]
yes. the new order schema was updated for emails in this PR: https://github.com/reactioncommerce/reaction/pull/4998
