### ISSUE TITLE
Custom order/shipping status

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4865]
## Issue Description

1. How should plugins added to reaction modify the Order's Status. For example the client only has 3 order status, NEW, CANCELED, SHIPPED. How should these map/replace over the present status.

2. Revise the current status that we have. From what I could figure out we have the following status:
We have the current states of order in Reaction:
-  new
- processing
- completed
- cancel

And the following as shipping status:
- notStarted
- picked
- packed
- labeled
- shipped
- delivered

**Comment by aldeed** [comment]
#2984 is related
