### ISSUE TITLE
Cannot start reaction container(Fedora28)

### ISSUE THREAD

**Issue by AaronZhangL** [reactioncommerce/reaction#4880]
----------OS: Fedora28------------------
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ uname -a
Linux localhost.localdomain 4.19.8-200.fc28.x86_64 #1 SMP Mon Dec 10 15:43:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ cat /etc/redhat-release
Fedora release 28 (Twenty Eight)
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ docker --version
Docker version 18.09.0, build 4d60db4
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ npm --version
6.4.1
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ node --version
v8.12.0
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ ls 
99_bakByAZ  CODE_OF_CONDUCT.md  config.mk  CONTRIBUTING.md  docs  LICENSE.md  Makefile  reaction  reaction-hydra  reaction-next-starterkit  README.md
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ git branch -a

* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/reaction-users

----------Issue----------------------------
Run [make] command under the [reaction-platform] folder, I got below errors:
===========
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json
npm WARN saveError EACCES: permission denied, open '/opt/reaction/src/package-lock.json.3285523079'
npm WARN react-taco-table@0.5.1 requires a peer of react@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-taco-table@0.5.1 requires a peer of react-dom@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 31419 packages in 17.447s
found 8 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
MongoDB replica set initialized and ready.
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json

**Comment by aldeed** [comment]
@AaronZhangL I don't see any errors there. Just warnings and errors that don't matter. Everything should still work.

**Comment by aldeed** [comment]
I believe this was created by the reaction CLI which is no longer used. Should not be an issue anymore in 2.0.0
