### ISSUE TITLE
New navigation migration should copy existing tag menu stucture

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4881]
## Issue Description
2.0 introduces a new navigation API. There is a migration that creates a default navigation tree per shop. This migration should also migrate the existing tag nav structure so that when a shop upgrades to 2.0, the navigation appears the same.

**Comment by mikemurray** [comment]
Closing this ticket as https://github.com/reactioncommerce/reaction/pull/4882 was merged into `release-2.0.0-rc.8`
