### ISSUE TITLE
GraphQL error during first start

### ISSUE THREAD

**Issue by arawaklabs** [reactioncommerce/reaction#4886]
I've installed reaction-platform on Mac OS Mojave.
Build went fine and I can access reaction at localhost:3000.
Unfortunately I'm unable to access the front store at localhost:4000.
A `docker-compose logs -f` on reaction-next-starterkit gives me this log:
<img width="783" alt="screenshot 2018-12-21 at 11 43 10" src="https://user-images.githubusercontent.com/45892501/50326504-12968680-052e-11e9-849b-7113c64f379c.png">

I tried `make clean`, delete and reinstall from scratch but couldn't make it work.

`docker network ls` the required networks are created:
<img width="506" alt="screenshot 2018-12-21 at 14 40 03" src="https://user-images.githubusercontent.com/45892501/50326560-5ee1c680-052e-11e9-8cb3-8a3a23acc0e8.png">

## Steps to Reproduce
1. install reaction-platform
2. make
3. cd reaction-next-starterkit && docker-compose logs -f

### Versions
Node: 10.8.0
NPM: 6.4.1
Reaction CLI: 0.29.0
Docker: 18.06.1-ce

**Comment by anton6** [comment]
There are a number of people in gitter reactioncommerce chat who reported facing this issue.

**Comment by machikoyasuda** [comment]
Hi @arawaklabs and @traubisoda - Sorry about this mix-up. Try using this `release-2.0.0-rc.8` branch of reaction with the latest `develop` of `reaction-next-starterkit`: https://github.com/reactioncommerce/reaction/tree/release-2.0.0-rc.8

**Comment by anton6** [comment]
@machikoyasuda that worked, thanks!
