### ISSUE TITLE
Unexpected end of JSON input while parsing near '...2.5","eslint":"2.13.1'

### ISSUE THREAD

**Issue by anton6** [reactioncommerce/reaction#4888]
## Issue Description

Everytime I try to install node modules using **npm** I get the following error: `npm ERR! Unexpected end of JSON input while parsing near '...2.5","eslint":"2.13.1'`

## Steps to Reproduce

run `reaction init` (or `npm i` in the reaction directory).

I tried with latest master and few previous version such as "v2.0.0-rc.7"

## Possible Solution
Works using `yarn install`, but not sure if it leads to any side effects.

Also if I remove `react-container-query` from package.json - npm install seems to install without the error.

### Versions
macOS Hight Sierra

Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Docker: 18.09.0

**Comment by zenweasel** [comment]
No one is seeing this or able to reproduce so closing for now. Reopen if you can offer more detail.
