### ISSUE TITLE
ERROR: readlink /var/lib/docker/overlay2/l: invalid argument (MacOS 10.13)

### ISSUE THREAD

**Issue by michaelcukier** [reactioncommerce/reaction#4889]
## Issue Description
Hi, I am trying to set up Reaction Commerce by following, step-by-step, what is written in [those docs](https://docs.reactioncommerce.com/docs/installation-reaction-platform).

But I'm stuck at the very beginning, when I run the `make` command, here's what I get:
<img src="https://i.imgur.com/weyXtHm.png"/>
## Steps to Reproduce
(on MacOS 10.13.2 High Sierra)
1. `git clone git@github.com:reactioncommerce/reaction-platform.git`
2. `cd reaction-platform`
3. `make`

### Versions
Node: 11.6.0
NPM: 6.5.0-next.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.29.0
Docker: 18.09.0

**Comment by zenweasel** [comment]
Nobody else is seeing this error, so it would seem to be something with your local environment. You might want to try reinstalling Docker and trying again with the latest version.
