### ISSUE TITLE
about the doc

### ISSUE THREAD

**Issue by danywheeler** [reactioncommerce/reaction#489]
I think the doc is very hard to understand as a new ReactionCommerce developer after I read it  , it has no tutorial about how to DIY template and has no how to developer a new package , just some sample explanation , not a step by step show how it works , really hard to get started !

**Comment by aaronjudd** [comment]
Thanks @danywheeler - we'll post some updated docs soon.

**Comment by aaronjudd** [comment]
Docs are being moved to https://docs.reactioncommerce.com/ and now live in the repo: https://github.com/reactioncommerce/reaction-docs

PR's welcome.
