### ISSUE TITLE
Marketplace Shops on Different Domains

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#4890]
## Prerequisites
* [x] Are you running the latest version? (`master`)
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The Shop data model allows for shops to live on their own domains. As written, a user must have their preferences set in order to see a marketplace shop.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create a Marketplace Shop.
2. give this shop a named domain (requires a manually write to the DB)
3. Run your NextJS server on that named domain (suggestion on how to do that below)
4. visit named domain

expected: Marketplace Shop data
actual: Primary Shop data

## Possible Solution
Graph QL API to inspect the request's `"Origin"` header to determine `shopId`

### Versions
```
Node: 8.11.3
NPM: 6.5.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.7
Reaction branch: master
Docker: 18.09.0
```

**Comment by aldeed** [comment]
This feature is no longer built into the latest releases
