### ISSUE TITLE
[Bug] NaN Undefined on Store with Very Large Integers

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction#4900]
## Issue Description
When declaring a product's price more than 3 significant figures (1 x 10 ^ 3), NaN Undefined results up on the Store. 

Where as when in the product's detailed page, the real price will be shown.

Note: Does not matter if the Compare At Price is very large

**Examples** : 
<img width="858" alt="screen shot 2019-01-07 at 3 54 08 pm" src="https://user-images.githubusercontent.com/6117033/50792903-8659c280-1294-11e9-8c06-895b5315f6e4.png">

<img width="1121" alt="screen shot 2019-01-07 at 3 55 22 pm" src="https://user-images.githubusercontent.com/6117033/50792967-adb08f80-1294-11e9-9e3b-5bb5366b27aa.png">

<img width="1162" alt="screen shot 2019-01-07 at 3 50 57 pm" src="https://user-images.githubusercontent.com/6117033/50792788-2c58fd00-1294-11e9-96e2-5a5163a90548.png">

<img width="1410" alt="screen shot 2019-01-07 at 3 51 50 pm" src="https://user-images.githubusercontent.com/6117033/50792870-688c5d80-1294-11e9-91fd-44f748be5090.png">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create/Edit existing product's "Price" to have more than 3 significant figures, i.e. 1000, 10000 etc.
2. Go to storefront page, to see visual NaN

### Versions
2.0.0-release-rc.8

**Comment by spencern** [comment]
@jeffcorpuz nice find. Is this a regression introduced in rc.8?

**Comment by jeffcorpuz** [comment]
@spencern going through tags checkouts, seems it is introduced between rc.5 and rc.6.

**Comment by spencern** [comment]
@kieckhafer can you take a look at this?

**Comment by kieckhafer** [comment]
Seems to have something to do with `accounting.formatMoney`: https://github.com/reactioncommerce/reaction/blob/feat-kieckhafer-surcharges/client/modules/i18n/currency.js#L159

Logging through this file, everything is OK until it gets to this line, then it returns `NAN`. Looking into issues in their repo now, but it seems like that repo is not kept up.

**Comment by kieckhafer** [comment]
Closed via #4910 and #4916
