### ISSUE TITLE
How do I configure reaction 2.0 in production to work in my domain

### ISSUE THREAD

**Issue by Marcosul** [reactioncommerce/reaction#4901]
Hello

I installed reaction 2.0 with Docker on Digital Ocean and it works in development environment on port 3000.

I  created an .env file inside the reaction folder and change the ROOT_URL, I created a nginx virtual block,.

I already searched Gitter, but I do not find a clear instruction  for this.

Please, how do I configure reaction 2.0 in production to work in my domain?

**Comment by mahayash** [comment]
Hello @marcosul,
Please guide me what should be my next step in launching the complete reaction platform on my local machine. I been stuck for couple of weeks.
PFA

![screen shot 2019-01-08 at 11 22 11 am](https://user-images.githubusercontent.com/3906359/50813083-38e46080-133b-11e9-8a85-49577d50db51.png)

**Comment by Marcosul** [comment]
Hello @mahayash 

I understand that the reaction-next-starterkit project is a work in progress and should not be used in production at this time.

Just run the "make" command, wait a few minutes for the project to appear at http: // localhost: 3000

**Comment by aldeed** [comment]
Deployment article: https://docs.reactioncommerce.com/docs/deploying

The article needs some updating, which will be done by the 3.0.0 release, but this question is answered so I'm closing it.
