### ISSUE TITLE
Reaction-Web-Starterkit Crashes on Make Start - EACCES: permission denied

### ISSUE THREAD

**Issue by DevinODowd** [reactioncommerce/reaction#4902]
## Issue Description

Have an issue running reaction-web-starterkit.

After "Make Start" finishes it looks as it should. Running docker ps straight after will show all working - but after 10 secs reaction-web-starterkit will crash. 

The logs show the following error: 

yarn install v1.12.3
web_1  | warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error An unexpected error occurred: "https://registry.yarnpkg.com/@types/jss/-/jss-9.5.7.tgz: EACCES: permission denied, open '/home/node/.cache/yarn-offline-mirror/@types-jss-9.5.7.tgz'".
web_1  | info If you think this is a bug, please open a bug report with the information provided in "/usr/local/src/reaction-app/yarn-error.log".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Does anyone have any possible solutions to this issue.

Cheers,
Devin

### Versions
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.7
Reaction branch: master
Docker: 18.09.0

**Comment by aldeed** [comment]
This could be a random error, but I would try this in the starterkit dir

```
docker-compose down
docker-compose run --rm web rm -rf /home/node/.cache/yarn-offline-mirror
docker volume rm reaction-next-starterkit_web-yarn
docker-compose up --build
```

This should address any permission issues you might be having with the offline mirror folder. The `--build` will rebuild the image, and the `Dockerfile` creates that folder with proper ownership.

**Comment by joshu111** [comment]
Same issue.
after running "docker-compose run --rm web rm -rf /home/node/.cache/yarn-offline-mirror", 
 I get   "rm: can't remove '/home/node/.cache/yarn-offline-mirror': Permission denied"

**Comment by aldeed** [comment]
@joshu111 If nothing else works, try editing the `docker-compose.yml` file in that project's root and remove `- $HOME/.cache/yarn-offline-mirror:/home/node/.cache/yarn-offline-mirror`. This is just a performance optimization so it isn't needed.

**Comment by r0nan** [comment]
I solved the same issue by modifying the docker-compose.yml file !
Tx aldeed !
