### ISSUE TITLE
When admin switch from one shop to another shop using Shops dropdown the shortcut dashboard is not changing until doing manual refresh. 

### ISSUE THREAD

**Issue by amalan-shenll** [reactioncommerce/reaction#4905]
## Issue Description
When admin switch from one shop to another shop using Shops dropdown the shortcut dashboard is not changing until doing manual refresh. 

## Steps to Reproduce
1. Run the reaction commerce version 2.0 in your PC
2. Login as administrator (Consider you already have more than one shop approved in your application)
3. Click on the Shops drop down from toolbar at the top and try changing the shop.

## Expected behaviour
The dashboard shortcut icons should change based on the shop and the shop name should be changed in Shops drop down in top toolbar.

### Versions
Node: 8.11.1
NPM: 5.6.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.7
Reaction branch: master
Docker: 18.09.0

**Comment by kieckhafer** [comment]
Switching shops in the admin is no longer supported at this time. We will revisit if / when we add the feature back in the future.
