### ISSUE TITLE
Add information that oplog access must be enabled in order for the Addressbook to work properly

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#4906]
## Issue Description
In deployments of 2.0.0-rc.x, during checkout as guest entering an address doesn't work properly.
While entering and saving an address works properly, the component doesn't switch its state value mode to "grid".

when entering an address and saving, it seems like nothing was saved and the entered info discarded.
No error ist thrown, and when you maually refresh the page afterwards, the adressbook form goes into its supposed mode "grid", as the address exists.

Therefore this seems to be solely a problem of `this.state.mode` not being set properly somewhere around [/imports/plugins/core/accounts/client/components/addressBook.js#L251](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/accounts/client/components/addressBook.js#L251) 

**I could not reproduce this error on local instances, but only on deployed ones**, therefore I'd assume this could be related to callbacks, or some transpiling.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1 Make sure you are not logged in, or stay logged in and make sure that no address is saved for your account.
2. Add product to cart
3. Go to checkout
4. Choose guest and enter eMail address.
5. Enter address data and click save
6. Notice how the component doesn't switch to the grid view. After a small delay the Cancel button appears right to the save button, clicking that will lead to the grid view, where the proper address is selected.

## Possible Solution
Not sure yet, harder to debug as I couldn't reproduce locally

### Versions
(run `reaction -v` from your reaction directory)

**Comment by janus-reith** [comment]
Wonder if this is related somehow: [Checkout address issue #4394](https://github.com/reactioncommerce/reaction/issues/4394)

**Comment by spencern** [comment]
@janus-reith Where do you think this should be noted? Would you be willing to make a PR to our docs?

**Comment by janus-reith** [comment]
Im not sure if the nextjs UI is still affected/ if there is further meteor server code that needs Oplog.
The "Deploying" part of the docs already state:

> The database is included in development, and our containers also include a MongoDB instance inside the container, but it is only intended for development and testing. It’s not a production solution, and you should provide an external replica-set db instance with oplog access enabled for production deployment.

Maybe, if oplog is still necessary, that should go there as in its current form this sounds more like a recommendation to me than a requirement.
