### ISSUE TITLE
GraphQL: Navigation items content resolver shouldn't filter array by language

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4912]
## Issue Description
Discussion here: https://github.com/reactioncommerce/reaction-next-starterkit/pull/472#discussion_r246494205

Essentially, the content array of a navigation item shouldn't be filtered down by language. Instead we should have a separate `contentForLanguage: String` resolver.

**Comment by kieckhafer** [comment]
Closed by #4913
