### ISSUE TITLE
Load more products only works once

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4924]
## Issue Description
The "Load more products" only works once, if you click on it the second time it doesn't work.

## Steps to Reproduce
1. Make sure you have > 48 products in `Products` collection
1. Login as Admin
1. Click "Load more products", and observe more products are loaded
1. Scroll down and again click on "Load more products", observe that nothing happens.

**Comment by zenweasel** [comment]
Duplicate
