### ISSUE TITLE
Always got validation error when making product variants

### ISSUE THREAD

**Issue by yareyaredesuyo** [reactioncommerce/reaction#4926]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

Always got validation error when making product variants (and edit it). 

## Steps to Reproduce

1. login as admin
2. click Add product 
3. Edit variants and insert some contents 

<img width="971" alt="2019-01-18 20 07 06" src="https://user-images.githubusercontent.com/31843888/51383395-ade64000-1b5c-11e9-95b8-4d7ca0f2f237.png">

## Possible Solution

I do not know. 

### Versions

Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.8
Reaction branch: master
Docker: 18.03.1-ce

**Comment by mrkhanakia** [comment]
Same issue here.

**Comment by janus-reith** [comment]
Did you take a look at the server console log?
When you're using the `reaction-platform` docker configuration, you can probably find it by typing:
`docker logs -f reaction_reaction_1`

The client side error log in your browser could probably also be expanded to show details what failed.(e.g. Chrome has a dropdown for that in its log)

Also, did you start from scratch with an empty database, or did you migrate from a previous version?
If yes to the latter, then there should probably be an error in the log aswell, and you can lookup your current migration version in the control entry in the Migrations collection of your mongodb instance.
