### ISSUE TITLE
Cannot run the installation of docker. reaction_reaction_1 exited with code 1

### ISSUE THREAD

**Issue by soomro30** [reactioncommerce/reaction#4929]
I have installed the latest version of the reaction using the docker. Everything goes fine but when i run make start and check using docker ps -a | less -S the reaction-hydra_hydra-migrate_1 exits every-time.

I run  "cd reaction and docker-compose logs -f" and receive the following message

mongo_1     | 2019-01-21T20:10:38.579+0000 I NETWORK  [conn3] Error receiving request from client: SSLHandshakeFailed: SSLHandshakeFailed. Ending connection from 172.27.0.1:49024 (connection id: 3)

mongo_1     | 2019-01-21T20:08:54.367+0000 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 14, after backgroundFlushing: 242, after connections: 299, after dur: 320, after extra_info: 349, after globalLock: 675, after locks: 1641, after logicalSessionRecordCache: 1937, after network: 2177, after opLatencies: 2177, after opcounters: 2187, after opcountersRepl: 2187, after repl: 2619, after security: 2670, after storageEngine: 3061, after tcmalloc: 3693, after transactions: 3750, after wiredTiger: 15095, at end: 18057 }

It keeps loading and never ends and after 20 mins each time it ends with following messages.

reaction_1  | Killed
reaction_1  | { Error: Command failed: meteor --raw-logs
reaction_1  |     at checkExecSyncError (child_process.js:601:13)
reaction_1  |     at execSync (child_process.js:641:13)
reaction_1  |     at _callee$ (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:72:43)
reaction_1  |     at tryCatch (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:65:40)
reaction_1  |     at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:303:22)
reaction_1  |     at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:117:21)
reaction_1  |     at step (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:191)
reaction_1  |     at /usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:361
reaction_1  |     at <anonymous>
reaction_1  |     at process._tickCallback (internal/process/next_tick.js:188:7)
reaction_1  |   error: null,
reaction_1  |   cmd: 'meteor --raw-logs',
reaction_1  |   file: '/bin/sh',
reaction_1  |   args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
reaction_1  |   options: 
reaction_1  |    { stdio: [ [Object], [Object], [Object] ],
reaction_1  |      shell: true,
reaction_1  |      file: '/bin/sh',
reaction_1  |      args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
reaction_1  |      envPairs: 
reaction_1  |       [ 'TOOL_NODE_FLAGS=',
reaction_1  |         'NODE_VERSION=8.11.4',
reaction_1  |         'HOSTNAME=05d207e41d12',
reaction_1  |         'METEOR_WATCH_POLLING_INTERVAL_MS=10000',
reaction_1  |         'METEOR_VERSION=1.8',
reaction_1  |         'METEOR_DISABLE_OPTIMISTIC_CACHING=1',
reaction_1  |         'REACTION_EMAIL=admin@localhost',
reaction_1  |         'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor:/opt/reaction/src/node_modules/.bin',
reaction_1  |         'PWD=/opt/reaction/src',
reaction_1  |         'MONGO_URL=mongodb://mongo:27017/reaction',
reaction_1  |         'REACTION_USER=Admin',
reaction_1  |         'APP_BUNDLE_DIR=/opt/reaction/dist',
reaction_1  |         'ROOT_URL=http://localhost:3000',
reaction_1  |         'HYDRA_TOKEN_URL=http://hydra:4444/oauth2/token',
reaction_1  |         'SHLVL=1',
reaction_1  |         'HOME=/home/node',
reaction_1  |         'REACTION_AUTH=r3@cti0n',
reaction_1  |         'YARN_VERSION=1.6.0',
reaction_1  |         'OAUTH2_CLIENT_DOMAINS=http://localhost:4000',
reaction_1  |         'REACTION_DOCKER_BUILD=true',
reaction_1  |         'REACTION_USER_NAME=admin',
reaction_1  |         'REACTION_SECURE_DEFAULT_ADMIN=false',
reaction_1  |         'APP_SOURCE_DIR=/opt/reaction/src',
reaction_1  |         'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
reaction_1  |         'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
reaction_1  |         'HYDRA_ADMIN_URL=http://hydra:4445',
reaction_1  |         '_=/usr/local/bin/reaction' ],
reaction_1  |      killSignal: undefined },
reaction_1  |   envPairs: 
reaction_1  |    [ 'TOOL_NODE_FLAGS=',
reaction_1  |      'NODE_VERSION=8.11.4',
reaction_1  |      'HOSTNAME=05d207e41d12',
reaction_1  |      'METEOR_WATCH_POLLING_INTERVAL_MS=10000',
reaction_1  |      'METEOR_VERSION=1.8',
reaction_1  |      'METEOR_DISABLE_OPTIMISTIC_CACHING=1',
reaction_1  |      'REACTION_EMAIL=admin@localhost',
reaction_1  |      'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor:/opt/reaction/src/node_modules/.bin',
reaction_1  |      'PWD=/opt/reaction/src',
reaction_1  |      'MONGO_URL=mongodb://mongo:27017/reaction',
reaction_1  |      'REACTION_USER=Admin',
reaction_1  |      'APP_BUNDLE_DIR=/opt/reaction/dist',
reaction_1  |      'ROOT_URL=http://localhost:3000',
reaction_1  |      'HYDRA_TOKEN_URL=http://hydra:4444/oauth2/token',
reaction_1  |      'SHLVL=1',
reaction_1  |      'HOME=/home/node',
reaction_1  |      'REACTION_AUTH=r3@cti0n',
reaction_1  |      'YARN_VERSION=1.6.0',
reaction_1  |      'OAUTH2_CLIENT_DOMAINS=http://localhost:4000',
reaction_1  |      'REACTION_DOCKER_BUILD=true',
reaction_1  |      'REACTION_USER_NAME=admin',
reaction_1  |      'REACTION_SECURE_DEFAULT_ADMIN=false',
reaction_1  |      'APP_SOURCE_DIR=/opt/reaction/src',
reaction_1  |      'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
reaction_1  |      'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
reaction_1  |      'HYDRA_ADMIN_URL=http://hydra:4445',
reaction_1  |      '_=/usr/local/bin/reaction' ],
reaction_1  |   stderr: null,
reaction_1  |   stdout: null,
reaction_1  |   pid: 58,
reaction_1  |   output: [ null, null, null ],
reaction_1  |   signal: null,
reaction_1  |   status: 137 }
reaction_1  | 
reaction_1  | Error: App failed to start
reaction_reaction_1 exited with code 1

I am using mac OSX with latest version of node and docker in Majave

Attached is the screenshot of services. Is there a fix? It is taking hours and webpage keeps loading
<img width="1766" alt="screen shot 2019-01-22 at 12 13 39 am" src="https://user-images.githubusercontent.com/1238737/51496859-b21f9100-1dda-11e9-9a72-ff9bb66de295.png">

**Comment by pablofmorales** [comment]
I had the same issue and I fixed it, I don't remember the solution. 

But try to do *npm install* manually, try to have the node version 8.x in your machine first. 

I think I solved it like that.

**Comment by aldeed** [comment]
> reaction-hydra_hydra-migrate_1 exits every-time

This is expected. It just runs and stops itself.

As far as the API container error, be sure you have high enough memory and CPU settings in Docker. 

https://docs.reactioncommerce.com/docs/troubleshooting-development#memory-errors-or-errors-about-meteor-rawlogs

**Comment by soomro30** [comment]
It is solved now. Thanks. The main reason was docker needs good amount of memory on mac. So I had to give it 6GB and the containers were able to run smoothly.

**Comment by billginger** [comment]
That's useful for me. Recommend to put this description on the installation instructions page. Seems Docker only allocate 2G memory as default.

**Comment by aldeed** [comment]
https://github.com/reactioncommerce/reaction-docs/commit/ca4cb26d76bf8a9e0db3f5ea75a3ea7f1086d36d
