### ISSUE TITLE
Not being able to add any payment method

### ISSUE THREAD

**Issue by tritone11** [reactioncommerce/reaction#493]
After a fresh install, I am not able to add neither paypal or Stripe payment methods. Even if they are enable, when in the checkout, the 5th step says:

"No payment methods are configured. Configure now."

**Comment by aaronjudd** [comment]
Did you also configure the payment method credentials in the Dashboard->[Stripe]-> side panel, payment settings?

**Comment by tritone11** [comment]
After a reinstall the issue seems to be solved.
