### ISSUE TITLE
Store client's metadata in order.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4944]
Some of the clients might require to store/get client's metadata while exporting/processing the orders.
So we need to store this data on the order document.
The data I am looking for is:
```
  Locale: <like en_US>
  BroswerData:
    HostName
    IPAddress
    SessionId
    UserAgent
    Connection
    Cookies
    JavascriptData: Not sure what this is, but will figure out in a while.
    Referrer: Would map to Referer
    ContentType
    Encoding
    Language
    CharSet
```
All of these directly map to HTTP headers we get in the requests.

**Comment by spencern** [comment]
@Akarshit This data should be available on the client, what changes do you need in the core of Reaction to accomplish this?
