### ISSUE TITLE
Products item alert is overlap by control buttons on narrow viewport

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#495]
Hello, take a look:
![reaction_item_notice](https://cloud.githubusercontent.com/assets/11130487/10601394/d25c97b0-772a-11e5-802a-69eaa5e7e8b7.jpeg)
I think simplest solution is to add ```z-index: 1``` to ```product-grid-item-alerts``` class.

**Comment by aaronjudd** [comment]
Related to #579 and #429
