### ISSUE TITLE
Server crash on develop branch : needed for PR

### ISSUE THREAD

**Issue by Moumouls** [reactioncommerce/reaction#4952]
I run the last `develop` version for a PR on the GraphQL Subscription

## Issue Description
I use the Reaction Platform repo with the `config.mk` : 
```
define SUBPROJECT_REPOS
git@github.com:/reactioncommerce/reaction-hydra.git,reaction-hydra,v2.0.0-rc.9 \
git@github.com:/reactioncommerce/reaction.git,reaction,develop \
git@github.com:/reactioncommerce/reaction-next-starterkit.git,reaction-next-starterkit,v2.0.0-rc.9
endef
```
## Steps to Reproduce
1. `docker system prune -a`
2. `cd reaction-platform`
3. `make`
4. `docker stats`
5. After the build you can see that the reaction container has crashed

> Server freeze too when you try to launch `docker-compose up` in `reaction` folder

## Possible Solution
I think that a pull request on `develop` break the container

**Comment by zenweasel** [comment]
Cannot reproduce running the latest code. Please open a new issue with more detail if this is still happening
