### ISSUE TITLE
Missing shipping panel

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#4959]

**Comment by kieckhafer** [comment]
This has been resolved.

**Comment by rymorgan** [comment]
![3-up Catalyst UI](https://user-images.githubusercontent.com/20409254/61157613-791fc980-a4ab-11e9-8fa6-610b231e0d52.png)

**Comment by rymorgan** [comment]
![3-up Catalyst UI (1)](https://user-images.githubusercontent.com/20409254/61161477-bb033c80-a4b8-11e9-9c5e-4f4f6a68b8d0.png)
