### ISSUE TITLE
Graphql requests which return Shop fail if requesting any of these fields: administrators, groups, roles, and tags. 

### ISSUE THREAD

**Issue by noodle-t** [reactioncommerce/reaction#4961]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Graphql requests that return Shop objects returns an error if the query requests administrators, groups, roles or tags, which is also displayed on the server console:  Error: ID namespace must be reaction/shop

## Steps to Reproduce
1. Using GraphiQL, make a request such as (using a valid shopId for your system):
{
  shop(id:"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==") {
    description
    name
    tags {
      nodes {
        name
      }
    }
  }
}
2. The error message "ID namespace must be reaction/shop" is displayed in both the response and also on the server console.
3.

## Possible Solution
The sub queries (if that's what you call them) are all being passed the shop object or the _id of the shop object which has an unencoded id. They attempt to decodeShopOpaqueId() on the id which is where it fails. I have changed this in my version of the code to pass the id without decoding it, and it works fine. I believe this is appropriate, since the shopId which is passed in encoded is verified when getting the shop object.

### Versions
(run `reaction -v` from your reaction directory)
2.0.0-rc.7

**Comment by spencern** [comment]
@noodle-t thanks for this detailed bug report! We'll take a look.
