### ISSUE TITLE
App keeps crashing in Heroku right after successful build

### ISSUE THREAD

**Issue by shabin-slr** [reactioncommerce/reaction#4963]
## Prerequisites
* [x] Are you running the latest version?
Yes
* [x] Are you able to consistently reproduce the issue?
Yes
* [x] Did you search the issue queue for existing issue? [Search issues]
(https://github.com/reactioncommerce/reaction/issues)
Yes

## Issue Description
Deploying to Heroku succeeds. But app crashes immediately with following error
`Error: Cannot find module '/app/.meteor/heroku_build/bin/boot_proxy.js'`
` at Function.Module._resolveFilename (module.js:547:15)`
` at Function.Module._load (module.js:474:25)`
` at Function.Module.runMain (module.js:693:10)`
` at startup (bootstrap_node.js:191:16)`
` at bootstrap_node.js:612:3`

## Steps to Reproduce
Try publishing the latest version of code base to Heroku

## Possible Solution
Issue with Heroku buildpack or Procfile

### Versions
2.0.0-rc.9

**Comment by limacohen** [comment]
Same exact issue here, just following [this instructions](https://docs.reactioncommerce.com/docs/deploying-reaction-using-heroku).

**Comment by lisu9090** [comment]
There is a fork of meteor-buildpack-horse which solves this issue.

https://github.com/Zanobo/reaction-buildpack.git

**Comment by JeffJassky** [comment]
> There is a fork of meteor-buildpack-horse which solves this issue.
> 
> https://github.com/Zanobo/reaction-buildpack.git

This worked for me.

**Comment by zenweasel** [comment]
We no longer directly support running on Heroku. Closing.
