### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by tarek369** [reactioncommerce/reaction#4972]
I go error 
error Could not write file "/usr/local/src/reaction-app/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/reaction-app/yarn-error.log'"

And after that the container stops ,
I have used the latest version and using docker in new vps 16.04 

Any help ?

**Comment by 23hp** [comment]
yes  me to

**Comment by yeahyahoo** [comment]
Fix is in this topic:
https://forums.reactioncommerce.com/t/reaction-store-front-installation-error/1295

**Comment by mikemurray** [comment]
The issue seems to be resolved by the forum thread as an issue with permissions in an individual's node setup.

**Comment by aourika** [comment]
Did you try to run docker yarn as root ? like this "docker-compose run -u root [targets] yarn

**Comment by fredowisk** [comment]
You saved my life!!!!!

**Comment by fredowisk** [comment]
@aourika 
You saved my life!!!
