### ISSUE TITLE
'cart/setShipmentAddress' TypeError: undefined is not iterable

### ISSUE THREAD

**Issue by addzep** [reactioncommerce/reaction#4975]
I am also having this issue consistently. It is a previously closed issue. (#4928)

Steps to Reproduce:

1. Select a new added product or select any previous product.
2. Checkout using guest or registered user.
3. Add Address, and then error.

**reaction -v**
Node: 10.15.0
NPM: 6.4.1
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

Screenshot
![image](https://user-images.githubusercontent.com/18188651/52529040-a9064d80-2d10-11e9-91c0-b53f2cdb15c1.png)

![image](https://user-images.githubusercontent.com/18188651/52529049-d6eb9200-2d10-11e9-9f8d-869ecbec87af.png)

**Comment by williamespindola** [comment]
@addzep try clone this repository again and run `reaction pull` before `reaction`.

**Comment by addzep** [comment]
I tried multiple times, on Linux also. I have also tried docker on windows as well as on ubuntu 18.04. (Docker using the Reaction Platform "make" system).

**Comment by addzep** [comment]
@williamespindola Any status?

**Comment by aldeed** [comment]
This should not be an issue when using the example storefront checkout with 2.0.0 final.
