### ISSUE TITLE
[Feature] in "product edit" functionality

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#498]
Hello. I believe, you already have this feature in plans, but what do you think about  "product edit" functionality expansion by allowing a massive (group):
- item size changing;
- publishing, duplicating and deleting;

Visually this can be done by adding something like "+" button to gridControls, which can select an item or maybe this can be done by other way.

**Comment by aaronjudd** [comment]
Is this the feature you are referring to?  `Product Inheritance Management` https://github.com/reactioncommerce/reaction/issues/150

**Comment by newsiberian** [comment]
Hello, no this is not pretty similar. This feature is based on our experience. The people who manage content, they want the things should be easy. Imagine that you just select several products on your screen by clicking "+" button, or by ctrl + click on these products and one thing you want to do is change their size or delete them massively. It must be easy to do quickly.

**Comment by aaronjudd** [comment]
I think you're talking about UX here, not functionality then? Perhaps you'd like some to provide some sketches?  We've had quite a few discussions on how to make this a simple UI, but would love to hear some more ideas.  #150 is describing complex behaviour, but our goal is always to make as simple as possible from a admin UI perspective. We too have a lot of experience both as developers but as operators of stores with large catalogs, so the admin experience has always been important to us - in fact I personally believe it needs to be the most important UIX experience.

**Comment by newsiberian** [comment]
if I understood correct you are talking about illustration of my idea? Here is an explanation. Idea was taken from file manager:
![screencast-products-moving](https://cloud.githubusercontent.com/assets/11130487/10782657/fef3346a-7d73-11e5-8e0f-778d10e7aa30.gif)

It would be great, if we could take this selection feature to our grid, with the following visually changes:

![reaction_screen_1_mod](https://cloud.githubusercontent.com/assets/11130487/10782689/36638e86-7d74-11e5-8bc1-882ac8103f15.jpeg)

**Comment by mikemurray** [comment]
@newsiberian makes sense. 

Changes that would need to be made for the product grid
- Make product grid items bulk selectable
- Side panel should always accept 1 or more products for management

This is fine for just managing multiple products as they appear in the grid that share similar attributes. Like changing their size, or hiding / deleting.

**Comment by mikemurray** [comment]
Added the ability to select multiple products using (shift + click). This will allow you to mass toggle visibility, delete, clone and change size.

This feature is not yet complete, but has been rolled into development so everyone can test and give feedback.

In addition pagination has been added as well from #303.

**Comment by mikemurray** [comment]
Preview:
<img width="1118" alt="screen shot 2015-10-30 at 3 41 55 pm" src="https://cloud.githubusercontent.com/assets/42217/10859647/d1fcba9e-7f1c-11e5-9f57-42020ca45c2f.png">

**Comment by newsiberian** [comment]
Hello, @mikemurray, thanks for fast implementation. Looks good. Now it's far more native, I think.

**Comment by ramusus** [comment]
Good feature! But I found one problem: after submit action - hide/show or change size - right panel becomes inactive for the next actions. It make behaviour unfriendly and force to select products again:

http://cl.ly/373B3b1B3c01

**Comment by aaronjudd** [comment]
@ramusus yes, I noticed this as well, this might be a regression in the current release. I didn't think it was doing this before.

**Comment by aaronjudd** [comment]
@newsiberian @mikemurray this probably should have been closed already? (but now has a bug)

**Comment by newsiberian** [comment]
If you asking to me, I think we still could add some features here. I strongly believe there is not enough a functionality which will be unselect all selected items if user clicks on a free space around items in grid or press the button `esc`.

**Comment by ramusus** [comment]
@newsiberian, @mikemurray I think we should accomplish selecting behaviour:
* "cmd (ctrl?) + click" selects + one product (like now shift does)
* "shift + click" selects all products between clicked and already selected

What do you think? I can do PR

**Comment by mikemurray** [comment]
I believe this issue to been resolved a while ago. Closing for now. If there are more features please open a new ticket. 

Thanks!
