### ISSUE TITLE
Surcharge updating is delayed

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4984]
I noticed an issue with https://github.com/reactioncommerce/reaction/pull/4829 but didn't want to hold up merging it. When surcharges apply to only certain methods and you are switching between methods on the checkout page, the surcharge total is updated one time behind. In other words, you see what the surcharge total is for one method after you switch to a different method.

We had a similar issue before with taxes, and this may need a similar fix. If `updateFulfillmentOptionsForGroup` and/or `selectFulfillmentOptionForGroup` are changed to do a `Cart.findOne` after the `appEvents.emit("afterCartUpdate"`, this should result in correct data being returned.

This is not necessarily a good long term fix for async data issues, though. We could also consider implementing the cart graphql subscription as a more future-proof fix.

**Comment by chrispotter** [comment]
Looks like this was solved with #5016 @aldeed do you agree?

**Comment by aldeed** [comment]
@kieckhafer Is this fixed in develop?

**Comment by kieckhafer** [comment]
Yes I believe it is.
