### ISSUE TITLE
addToCart mutation incorrect subtotal calculation

### ISSUE THREAD

**Issue by vadym-vorobel** [reactioncommerce/reaction#4985]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for an existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Hi! I'm using Reaction Commerce Graphql API in my project. After updating to the latest version, I've found an issue in `addToCart` mutation.

The issue is in `subtotal` calculations [here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/cart/server/no-meteor/util/addCartItems.js#L134). It doesn't affect on the Reaction Commerce dashboard because it calculates with [getSubtotal](https://github.com/reactioncommerce/reaction/blob/master/lib/collections/transform/cartOrder.js#L106) method. But it stores incorrect data and affects my client application.

## Steps to Reproduce
Just add an item to a cart

![screen shot 2019-02-14 at 5 02 42 pm](https://user-images.githubusercontent.com/13135292/52795580-c160ca00-307a-11e9-94ff-cda715542882.png)

## Possible Solution
It should be calculated a new quantity value before subtotal calculating (quantity updates [here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/cart/server/no-meteor/util/addCartItems.js#L168))

### Versions
Node: 8.15.0
NPM: 6.4.1
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.9
Reaction branch: master
Docker: 18.09.1

**Comment by spencern** [comment]
@jeffcorpuz can you take a look at this?

**Comment by jeffcorpuz** [comment]
Hi @vadym-vorobel thanks for the report, will start investigating.

Which version did you update from?

**Comment by jeffcorpuz** [comment]
Assigning @kieckhafer

**Comment by spencern** [comment]
@kieckhafer @jeffcorpuz Does this impact the amount charged when an order is created? This may need to be escalated to an `impact-critical` if so.

**Comment by jeffcorpuz** [comment]
@kieckhafer @spencern 
This does not impact the amount charged when an order is created. 
The true sub-total is in the cart.

**Comment by kieckhafer** [comment]
@vadym-vorobel @spencern I might have fixed the same issue via another ticket.... does this look like it's the same to you?

https://github.com/reactioncommerce/reaction-next-starterkit/issues/462#issue-391229725

and the PR:

https://github.com/reactioncommerce/reaction/pull/5021

**Comment by kieckhafer** [comment]
@vadym-vorobel I believe this was closed via https://github.com/reactioncommerce/reaction/pull/5021, feel free to re-open if that's not the case.

**Comment by vadym-vorobel** [comment]
@kieckhafer yep, it seems the same. Thanks!
