### ISSUE TITLE
Connect shop with stripe returns success. In admin UI markeplace owner still sees "Start Accepting Payment"

### ISSUE THREAD

**Issue by TilenKreca** [reactioncommerce/reaction#4989]
## Issue Description
We are not able to connect our marketplace shop with stripe account. After stripe redirects we receive sucess message but in Admin UI it is not marked as success.

## Steps to Reproduce
1. Primary shop is connected with stripe account successfully.
2. Markeplace mode was enabled on primary shop and new shop owner was invited. 
3. New shop owner registred account and then connects his account with Stripe My shop settings -> "Start Accepting Payment"
4. Success response is returned, but users still sees label: "Start Accepting Payment"

## Possible Solution
After investigation I found out that in Packages collections there are 2 types stored: 
 - reaction-marketplace
 - reaction-stripe

Only reaction-stripe has valid connectAuth under packages collection. If we search reaction-marketplace this property is empty.

If we change value in file:
reaction/imports/plugins/included/markeplace/client/templates/settings/merchant-settings.js
```
const stripe = Reaction.getPackageSettingsWithOptions({
      shopId: Reaction.getShopId(),
      name: "reaction-marketplace"
    });
```
![slika](https://user-images.githubusercontent.com/6170179/52863812-1236f800-3139-11e9-80b9-c45e501193bb.png)

to
```
const stripe = Reaction.getPackageSettingsWithOptions({
      shopId: Reaction.getShopId(),
      name: "reaction-stripe"
    });
```
then it works, and we get correct info: Your Stripe Account is Connected
![slika](https://user-images.githubusercontent.com/6170179/52863629-b10f2480-3138-11e9-9c1d-fabf7517c38c.png)

So possible solution would be that we would replace name form reaction-marketplace to reaction-stripe in this code: (File: reaction/imports/plugins/included/markeplace/client/templates/settings/merchant-settings.js)
```
import { Template } from "meteor/templating";

import { Reaction } from "/client/api";

Template.stripeConnectMerchantSignup.helpers({
  stripeConnectIsConnected() {
    const stripe = Reaction.getPackageSettingsWithOptions({
      shopId: Reaction.getShopId(),
      name: "reaction-stripe"
    });
    return stripe && stripe.settings && stripe.settings.connectAuth && stripe.settings.connectAuth.access_token;
  }
});

```

Is this correct ?

## DB comparance: reactin-stripe VS reaction-marketplace
![reaction-marketplace](https://user-images.githubusercontent.com/6170179/52864322-31825500-313a-11e9-8964-de977d70e64a.png)
![reaction-stripe](https://user-images.githubusercontent.com/6170179/52864323-31825500-313a-11e9-8e6a-bf50df3c4a8a.png)

### Versions
Node: 8.15.0
NPM: 6.7.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Docker: 18.06.1-ce

**Comment by aldeed** [comment]
Marketplace stripe is no longer built in
