### ISSUE TITLE
new server plugin not detected when running in docker

### ISSUE THREAD

**Issue by aforty** [reactioncommerce/reaction#4991]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I'm running Reaction (2.0.0-rc9) locally through Docker (latest - Mac Docker Desktop version 2.0.0.3 (31259) - engine 18.09.2 - machine 0.16.1 - compose 1.23.2). Reaction works fine out of the box but it doesn't seem to pick up any file changes I make locally. It detects that files were changes (meteor restarts) but it always seems to load the same version of the file as it was when `docker-compose up` was first launched. For example I'm following the featured-product plugin tutorial from the site and if I put a blatant error into the register.js (or any other file) it won't detect it. I have to stop docker and restart it for it to pick up any changes which is slow.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Pull 2.0.0-rc9 as detailed here: https://docs.reactioncommerce.com/docs/installation-reaction-platform
2. Add a plugin into imports/plugins/custom
3. Watch docker logs, see the restart but notice that the running app has not picked up any changes.

## Possible Solution
n/a

### Versions
```$ reaction --version

Node: 8.11.4
NPM: 5.6.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.9
Reaction branch: HEAD
```

**Comment by zenweasel** [comment]
The Reaction CLI is what allows reaction to detect new plugins. So you have to fully stop and restart the app for that to happen

**Comment by aforty** [comment]
Sorry but what is the solution here for me? Am I not supposed to run it in docker or is during development the restarting of docker necessary and expected behavior?

**Comment by zenweasel** [comment]
The title of this issue says "new server plugin not detected when running in docker". Is the problem that your plugin is not being detected or that any file changes are not being picked up. Those are two completely different cases.

**Comment by aforty** [comment]
If I follow the instructions for `reaction-platform` (make, make start, etc) and then start the `featured-products` tutorial it won't detect the new plugin as I'm creating it leading to much confusion.

**Comment by aldeed** [comment]
In 3.0 this will no longer be an issue for the API. For Reaction Admin, it's still the case that you will have to `docker-compose down` followed by `docker-compose up -d` in that project directory after you have created or cloned in a new plugin.
