### ISSUE TITLE
calculateOrderTaxes triggered indefinitely

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4995]
The methods to calculate taxes are triggered indefinitely.

Add a `console.log("Calculating taxes");`
here: imports/plugins/included/taxes-rates/server/no-meteor/util/calculateOrderTaxes.js, line 48.

Go to the checkout page, select shipping methods. Look in the server console. You will see the message "Calculating taxes" print indefinitely.

**Comment by aldeed** [comment]
I can reproduce this on `develop`

**Comment by aldeed** [comment]
This is due to unnecessary `afterCartUpdate` emits from the surcharges plugin. I'll have a fix PR soon.
