### ISSUE TITLE
Backend method to fulfil order(shipment) after order is placed.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4999]
Since most of the clients have a separate order management/tracking system, the acknowledgement of shipping items in the order comes in later, after the order is placed.
These tracking numbers, status can be at unit level.
We need a method that a plugin can just call which will split the order based on the shipping information and also update the status of the units/items/orders.

**Comment by kkuzemka** [comment]
@spencern - this is directly blocking some work on the Radial order imports - let's prioritize this to the top of the list.

**Comment by Akarshit** [comment]
A part of this is already implemented in https://github.com/reactioncommerce/reaction/pull/5010
We have to implement the code now that can change status to shipping and add shipping information, change status to "open"(which means start).
I have doc withe a couple of use cases which would be helpful to look at. Let me know who is working on this and I will pass the doc to him/her.

**Comment by spencern** [comment]
Will you outline the use cases here in this ticket? GitHub issues are the preferred way to discuss these things

What part of this is implemented in #5010? - what remains?

**Comment by Akarshit** [comment]
What remains: Implementing Open, Shipped, Adjust(only for display purposes) status change to the orders.

Here is an explanation of the issue and use cases in detail.
Most of the clients provide shipping fulfilment information after the order has been placed. It is at this time only that we can know if the order would be split is multiple shipments or not. 

This is not for any calculation/payment/or any sensitive purposes. It is **just for displaying order's status to customers** and to **send email on update.**

**Items**: The final product that gets added to the cart. Example: A red 'M' jacket

**Units:** The number of units of the `item` added to the cart. Example: 5 units of red 'M' jacket.

**Tracking#:** The tracking information about the product. Every "shipment" in reaction should have the same `tracking#`.

**Order Status:** The status of the complete order. It is `new` by default, then should go to `coreOrderWorkflow/processing``, then to `coreOrderWorkflow/completed` when all items are shipped(or atleast 1 shipped and rest are canceled) or to `coreOrderWorkflow/canceled` when all the items have been canceled.

The current order is stored in reaction in the following way(simplified for readabbility):

    {
    	"shipping" : [
    		{
    			"_id" : "Ship1",
    			"items" : [
    				{
    					"_id" : "A",
    					"subtotal" : 64.95,
    					"workflow" : {
    						"status" : "coreOrderWorkflow/processing",
    						"workflow" : [
    							"coreOrderWorkflow/created",
    							"coreItemWorkflow/removedFromInventoryAvailableToSell"
    						]
    					}
    				},
    				{
    					"_id" : "B",
    					"quantity" : 2,
    					"shopId" : "J8Bhq3uTtdgwZx3rz",
    					"subtotal" : 59.97,
    					"workflow" : {
    						"status" : "coreOrderWorkflow/processing",
    						"workflow" : [
    							"coreOrderWorkflow/created",
    							"coreItemWorkflow/removedFromInventoryAvailableToSell"
    						]
    					},
    				},
    			],
    			"workflow" : {
    				"status" : "new",
    				"workflow" : [
    					"coreOrderWorkflow/notStarted"
    				]
    			}
    			"tracking" : "9205590189237474362848"
    		}
    	],
    	"totalItemQuantity" : 6,
    	"workflow" : {
    		"status" : "coreOrderWorkflow/processing",
    		"workflow" : [
    			"coreOrderWorkflow/created"
    		]
    	}
    }

The objective is to split shipments whenever we recive the status of individual items.

In context of client, these are the status I get:

**OPEN**: (`coreOrderWorkflow/processing` in reaction) Order is accepted by external service and now is in external service's system. This status is for the whole order. A example message is:

    {
      orderId: "agavnxofaldsf",
      status: "OPEN"
    }

**SHIP**: (`coreOrderWorkflow/completed` in reaction) Order is shipped by external service. We get `tracking#` in this feed. This message is at `unit` level. A example message is:

    {
      orderId: "agavnxofaldsf",
      status: "SHIP"
      lineItems: [
         {
            itemId: "A",
            quantity: 1,
            amount: 12.99,
            tracking#: "12314123234"
         },
    		 {
            itemId: "B",
            quantity: 2,
            amount: 19.99,
            tracking#: "979679570"
         },
      ]
    }

After this message the order should be split into multiple shipment based on the `tracking#` and `quantity` fields. All the items in the order need not be present in this message. The message comes only for the `units` that have been shipped.
A item can have different units shipped separately. So it could be the case that 2 jackets are shipped from Utah and 2 from Chicago.
After this call we have to check the status of the items and update `order status`

**CANCEL**: (`coreOrderWorkflow/canceled` in reaction) **Already implemented in #5010 ** Order is canceled by external service. We get the reason for cancellation in this feed. An example would be:

    {
      orderId: "agavnxofaldsf",
      status: "SHIP"
      lineItems: [
         {
            itemId: "A",
            quantity: 1,
            amount: 12.99,
            reason: "customer canceled"
         },
    		 {
            itemId: "B",
            quantity: 2,
            amount: 19.99,
    				reason: "out of stock"
         },
      ]
    }

A item can have different units canceled separately. So it could be the case that 2 jackets are shipped from Utah and 2 are canceled and then 2 days later 2 are canceled again.

After this call we have to check the status of the items and update `order status`

**ADJUST**: (doesn't map to anything in reaction) Order was shipped but then some payment was made to the customer(maybe to compensate for poor item/shipping).

    {
      orderId: "agavnxofaldsf",
      status: "SHIP"
      lineItems: [
         {
            itemId: "A",
            quantity: 1,
            amount: 12.99,
            reason: "customer canceled",
            type: "item credit"
         },
    		 {
            itemId: "B",
            quantity: 2,
            amount: 19.99,
    				reason: "out of stock",
            type: "freight credit"
         },
      ]
    }

We are not doing anything with this data right now. Because we don't handle refunds to the customer in reaction code. Maybe we should try to store this info for display purposes.
When the type is "freight credit", it's the refund(full/partial) of the shipping fees so we don't care about the `quantity` field.

When the type is "item credit", it's the refund(full/partial) of the cost of the item.

**Comment by aldeed** [comment]
Here’s the current status of the remaining order mutation PRs needed to resolve this issue. Everything is “done” as far as having a PR open for it. @kieckhafer is assigned as primary reviewer on all.

- [addOrderFulfillmentGroup PR](https://github.com/reactioncommerce/reaction/pull/5027) is ready for review. This is a larger one because I had to pull apart `placeOrder` to reuse chunks of it. This is now first priority.
- [splitOrderItem PR](https://github.com/reactioncommerce/reaction/pull/5024) needs some fixes, but I want to get `addOrderFulfillmentGroup` merged first because the util functions in that PR are needed for the fix.
- [moveOrderItems PR](https://github.com/reactioncommerce/reaction/pull/5018) needs some fixes, but I want to get `addOrderFulfillmentGroup` merged first because the util functions in that PR are needed for the fix.

After everything is merged, here is roughly how all of these mutations can be used to sync order item status changes:
- If all or part of order item is canceled, use `cancelOrderItem` mutation.
- If receiving tracking or status update for partial item quantity, use `splitOrderItem` to convert it into two items.
- If receiving tracking or status update for some but not all items in a group, use `addOrderFulfillmentGroup` to make a new group and move some items to it.
- If there's already another group items can be moved to, use `moveOrderItems` rather than `addOrderFulfillmentGroup`
- Use `updateOrderFulfillmentGroup` to set status or tracking info for a group
- Use `updateOrder` to set full order status.

It's possible there are still some gaps here, but we'll know more after someone tries it out.

**Comment by kieckhafer** [comment]
@aldeed Sounds good, moving `addOrderFulfillmentGroup` review to the top of my To-Do list so we can get all this done. Hopefully have it reviewed in the next couple hours.

**Comment by aldeed** [comment]
These are all merged and seem to be working as needed. If further needs arise, you can make a new issue for them.
