### ISSUE TITLE
Add support for more file types in media gallery

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#50]
Currently only image types are supported in the media gallery. It would be useful to be able to include videos as well.

**Comment by jamesdeantv** [comment]
Any update on this feature request?

**Comment by aaronjudd** [comment]
@kieckhafer @mikemurray we should review this while looking at new/alternate approaches for replacing CFS. I'm closing for now, because this will be revisited when we replace CFS and update the image gallery.

**Comment by zrisher** [comment]
FYI for those landing here from the docs, here is the new tracking issue - https://github.com/reactioncommerce/reaction/issues/1221
