### ISSUE TITLE
Products without Variants

### ISSUE THREAD

**Issue by mtclmn** [reactioncommerce/reaction#500]
Is there currently a way to post products that don't have Variants? Looks like it's the default (and required) method for posting, however, I can see many shops _not_ needing this functionality.

It seems a bit odd for a user to have to see the "Options/Variations" section if there's only 1 variant.

Perhaps variant fields could be not required, and only show on the front-end if an admin has filled them out?

**Comment by aaronjudd** [comment]
A product with only one variant is "single product". This is really a UI issue, with which I mostly agree.  However - you can add a single product / single variant to the cart - the current interaction isn't the same as when there are multiple variants, or with options. There are a few other things (such as the Tags and Details labels, displaying when there is not any data), that are minor UI updates that need updating as well.

**Comment by ramusus** [comment]
+1 for this simple option. I suppose it should be by default and products variants could be possible to switch on in dashboard

**Comment by aaronjudd** [comment]
Goal: remove all variants, all add to cart with no variants, pricing editing (variant details) for the top level product.  Resolve issues with deleting all variants.

![basic_reaction_product](https://cloud.githubusercontent.com/assets/439959/17034805/1ad5793a-4f39-11e6-96f9-435b8f6448b2.png)

**Comment by kieckhafer** [comment]
With the massive amount of changes to the PDP being pushed with #1178 (over 100 files related to the PDP), we are holding off diving into this ticket until #1178 is pulled into development and we can work off of those changes.

**Comment by mikemurray** [comment]
Resolved in PR #1572
