### ISSUE TITLE
ReactionError and getErrorFormatter - Messages not logged properly

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#5006]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
While implementing Sentry error logging in Reaction, I tried to take all places into account where errors could happen or were logged. I noticed that GraphQL errors are logged with Bunyan, but the relevant part, the message, was missing and is only sent to the client.

That is traceable to [imports/node-app/core/util/getErrorFormatter.js#L29](https://github.com/reactioncommerce/reaction/blob/master/imports/node-app/core/util/getErrorFormatter.js#L29) where it should probably be: `Logger.error(err.message, eventObj);`

But there are still some parts unclear to me, like the check for `err.originalError`

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Use any type of GraphQL query wrong on purpose
2. Notice how an error is logged to console, which has an errorId but lacks the actual message.
3. Sometimes the actual error mesage is logged to console directly after that, but is not part of the bunyan log message. These duplicates could probably be prevented when Logger gets the actual message, but I didn't investigate yet where they originate.

## Possible Solution
In the meantime I added Sentry directly to `getErrorFormatter.js`, but I'd prefer a general approach, where everything relevant is passed to Logger and I could just use that as is - Then I could decide on a higher scope what to pass to my logging solution (incoming GraphQL request body, stacktrace ).
Apart from that, the missing Logger message should probably be fixed, but I'm not entirely sure how `ReactionError` and `getErrorFormatter` are working together, and if there maybe is a reasoning for the current approach.

**Comment by focusaurus** [comment]
Bringing over @aldeed comment from a duplicate issue:

 > @focusaurus I agree there's something not quite right with the gql error logging. Hard to debug where errors originate sometimes.

> It makes sense to move the Logger.error lower. Apollo does do some of its own voodoo on the error before our formatter function is even hit, so hopefully it's not an issue on their side. I believe err is a GraphQL-style error object and originalError is the original Error or Error subclass that was thrown deeper in the code. The way GraphQL works is that multiple errors might be hit from multiple resolvers, and they are all combined into an errors array, and each error in that array goes through the formatter before being added to the response that the client sees.

**Comment by focusaurus** [comment]
OK that merge should resolve this in the next release or rc.
