### ISSUE TITLE
Eye icon functionality is confusing and doesn't make product not visible

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5009]
## Issue Description
The intended functionality of the "eye" button is unclear but one major implied functionality would be to make a product "not visible" after the product is published. Not to make the product unpublishable which is what it currently does.

## Steps to Reproduce
1. Select any existing product
1. Click on the "eye" icon
1. Click "publish"
1. Observe that you get an error saying that `Cannot publish to catalog: product has no visible variants`
1. Make all the options and the variants individually visible
1. Publish. The product in the catalog now has the `isVisible` attribute correctly set

## Possible Solution
The eye icon should just toggle the top-level visibility state, not the state for all variants and options. You can still do that separately if you like.

### Versions
`Reaction Version: 2.0.0-rc.9`

**Comment by aldeed** [comment]
Refers to a UI that has since been removed
