### ISSUE TITLE
`bin/setup` script fails then running make command, it can't find `imports/plugins/custom` under the reaction folder.

### ISSUE THREAD

**Issue by manueldelreal** [reactioncommerce/reaction#5023]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
`bin/setup` script fails then running make command, it can't find `imports/plugins/custom` under the reaction folder.

## Steps to Reproduce
Preconditions:
This one might be hard to reproduce as it depends on the setup with `make init` for reaction-platform having failed once and having more subrepos than the stock install

1. With preconditions met, run `make` or `make init` again to try to finalize the project setup
2. Look output from the make command.

```
 ⇒  make
Error response from daemon: network with name auth.reaction.localhost already exists
Error response from daemon: network with name api.reaction.localhost already exists
Error response from daemon: network with name streams.reaction.localhost already exists
Error response from daemon: network with name routing.reaction.localhost already exists
Running pre-build hook script for reaction-hydra.
reaction-hydra post-project-start script invoked.
postgres uses an image, skipping
hydra-migrate uses an image, skipping
hydra uses an image, skipping
Running post-build hook script for reaction-hydra.
reaction-hydra post-build script invoked.
Starting reaction-hydra_postgres_1 ... done
Starting reaction-hydra_hydra-migrate_1 ... done
Starting reaction-hydra_hydra_1         ... done
Running post-project-start hook script for reaction-hydra.
reaction-hydra post-project-start script invoked.
Running pre-build hook script for sd-reaction.
sd-reaction post-project-start script invoked.
find: imports/plugins/custom: No such file or directory
/Users/user/reaction-platform/sd-reaction/bin/setup: line 27: port: No such file or directory
make: *** [prebuild-sd-reaction] Error 1   

```

### Versions
Node: 8.11.1
NPM: 6.0.0
Reaction CLI: 0.29.0
Docker: 18.09.2

**Comment by focusaurus** [comment]
One note: We have `imports/plugins/custom/.gitkeep` in the git repository, so the `imports/plugins/custom` directory should always be present. @manueldelreal can you confirm when you hit this bug you had manually deleted that directory?

But in either case, specifying that path is redundant since we are already looking in `.`, so I'll just remove that path.

**Comment by manueldelreal** [comment]
@focusaurus I actually didn't remove it and I checked under the folders for the reaction app that was set to build via config.local.mk and the folder was indeed present

**Comment by DKAtgit** [comment]
When i tried compiling on CygWin environment on windows 10 .
/cygdrive/d/my-reaction-projects/reaction/reaction-platform
$ make init-reaction-hydra

Getting these errors

Running pre-build hook script for reaction-hydra.
 post-project-start script invoked.
reaction-hydra/.reaction/project-hooks/pre-build: line 21: /cygdrive/d/my-reacti/bin/setup: No such file or directorym/reaction-hydra
make: *** [Makefile:166: prebuild-reaction-hydra] Error 127
