### ISSUE TITLE
Add ENV for GraphQL Playground and introspection

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5025]
## Background

https://www.apollographql.com/docs/apollo-server/features/graphql-playground.html#Enabling-GraphQL-Playground-in-production

Currently Reaction uses default Apollo behavior:

> In development, Apollo Server enables GraphQL Playground on the same URL as the GraphQL server itself (e.g. http://localhost:4000/graphql) and automatically serves the GUI to web browsers. When NODE_ENV is set to production, GraphQL Playground (as well as introspection) is disabled as a production best-practice.

Reaction prefers to use individual env variables rather than NODE_ENV.

## Work
- In `createApolloServer.js`, add the `introspection` and `playground` options with value coming from new ENV variables
- Use `envalid` for parsing the variables. Default should be `false` for both.
- Add both variables to `.env.example` with values of `true` for both
- Variable names should be something like `GRAPHQL_INTROSPECTION_ENABLED` and `GRAPHQL_PLAYGROUND_ENABLED`

**Comment by brunoLehnen** [comment]
Hey @aldeed, I've already fixed this one. Could you grant me the proper permissions so I push the local branch I've created? Thanks!
