### ISSUE TITLE
Reaction 2.0.0-rc.10: Failed to reset plugins file

### ISSUE THREAD

**Issue by yannterzi** [reactioncommerce/reaction#5028]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

###Setup
**OS**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Docker**
Docker version 18.09.3, build 774a1f4
docker-compose version 1.17.1, build unknown

**NodeJS**
node v10.15.3
npm 6.4.1

**Folder**

> drwxrwxr-x 17 yann docker   4096 Mar 10 19:00 .
drwxrwxr-x  9 yann docker   4096 Mar 10 18:29 ..
-rw-rw-r--  1 yann docker   1226 Mar 10 18:26 babel.config.js
drwxrwxr-x  2 yann docker   4096 Mar 10 18:26 bin
-rw-rw-r--  1 yann docker 119870 Mar 10 18:26 CHANGELOG.md
drwxrwxr-x  3 yann docker   4096 Mar 10 18:26 .circleci
drwxrwxr-x  9 yann docker   4096 Mar 10 18:50 client
-rw-rw-r--  1 yann docker   4907 Mar 10 18:26 CODE_OF_CONDUCT.md
-rw-rw-r--  1 yann docker    486 Mar 10 18:26 CONTRIBUTING.md
drwxrwxr-x  4 yann docker   4096 Mar 10 18:26 custom
-rw-rw-r--  1 yann docker   1277 Mar 10 18:59 docker-compose.yml
-rw-rw-r--  1 yann docker   2014 Mar 10 18:26 Dockerfile
-rw-rw-r--  1 yann docker    698 Mar 10 18:26 Dockerfile-devserver
-rw-rw-r--  1 yann docker    166 Mar 10 18:26 .dockerignore
-rw-rw-r--  1 yann docker    295 Mar 10 18:26 .editorconfig
-rw-------  1 yann docker   1329 Mar 10 19:19 .env
-rw-rw-r--  1 yann docker    542 Mar 10 18:26 .env.example
-rw-rw-r--  1 yann docker    136 Mar 10 18:26 .eslintignore
drwxrwxr-x  8 yann docker   4096 Mar 10 18:26 .git
drwxrwxr-x  2 yann docker   4096 Mar 10 18:26 .github
-rw-rw-r--  1 yann docker    675 Mar 10 18:26 .gitignore
-rw-rw-r--  1 yann docker      0 Mar 10 18:26 .gitmodules
-rw-rw-r--  1 yann docker    191 Mar 10 18:26 .hadolint.yaml
drwxrwxr-x  8 yann docker   4096 Mar 10 18:26 imports
-rw-rw-r--  1 yann docker    543 Mar 10 18:26 .jsbeautifyrc
drwxrwxr-x  6 yann docker   4096 Mar 10 18:26 lib
-rw-rw-r--  1 yann docker  35019 Mar 10 18:26 LICENSE.md
drwxrwxr-x  3 yann docker   4096 Mar 10 18:29 .meteor
drwxr-xr-x  2 yann docker   4096 Mar 10 18:29 node_modules
-rw-rw-r--  1 yann docker      7 Mar 10 18:26 .nvmrc
-rw-rw-r--  1 yann docker  14464 Mar 10 18:26 package.json
-rw-rw-r--  1 yann docker 696850 Mar 10 18:26 package-lock.json
drwxrwxr-x  6 yann docker   4096 Mar 10 18:26 private
-rw-rw-r--  1 yann docker    137 Mar 10 18:26 Procfile
-rw-rw-r--  1 yann docker   2488 Mar 10 18:26 propel-feat.yaml
-rw-rw-r--  1 yann docker    830 Mar 10 18:26 propel.yaml
drwxrwxr-x  5 yann docker   4096 Mar 10 18:26 public
drwxrwxr-x  5 yann docker   4096 Mar 10 18:26 .reaction
-rw-rw-r--  1 yann docker   4475 Mar 10 18:26 README.md
drwxrwxr-x  2 yann docker   4096 Mar 10 18:26 server
-rw-rw-r--  1 yann docker    118 Mar 10 18:26 .snyk
drwxrwxr-x  9 yann docker   4096 Mar 10 18:26 tests

###Description
After A Proper install of reaction-platform with Make command, the container reaction_1 failed to start with this logs:

> reaction_1  | up to date in 21.173s
> reaction_1  |
> reaction_1  | real	0m25.177s
> reaction_1  | user	0m22.570s
> reaction_1  | sys	0m2.778s
> mongo_1     | 2019-03-10T17:59:33.853+0000 I NETWORK  [listener] connection accepted from 192.168.16.3:52906 #1 (1 connection now open)
> mongo_1     | 2019-03-10T17:59:33.865+0000 I NETWORK  [conn1] received client metadata from 192.168.16.3:52906 conn: { driver: { name: "nodejs", version: "3.1.13" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-generic" }, platform: "Node.js v8.11.4, LE, mongodb-core: 3.1.11" }
> mongo_1     | 2019-03-10T17:59:33.877+0000 I REPL     [conn1] replSetInitiate admin command received from client
> reaction_1  | MongoDB replica set initialized and ready.
> mongo_1     | 2019-03-10T17:59:33.884+0000 I NETWORK  [conn1] end connection 192.168.16.3:52906 (0 connections now open)
> reaction_1  | (node:52) ExperimentalWarning: The ESM module loader is experimental.
> reaction_1  | Setting up plugin imports...
> reaction_1  |
> reaction_1  | Failed to reset plugins file at /opt/reaction/src/client/plugins.js
> reaction_reaction_1 exited with code 1

I tried to manually add  plugins.json from other instance of reaction rc-10 hosted on my dev. mac, nothing change.

## Steps to Reproduce
1. git clone git@github.com:reactioncommerce/reaction-platform.git
1.  cd reaction-platform
2. make
3. cd reaction
4. docker-compose logs -f

### Versions
GIT checkout from Reaction Platform MAKE
active branch: HEAD detached at v2.0.0-rc.10

**Comment by yannterzi** [comment]
I puted some logs in loadPlugins.mjs and i got this error:
Error: EACCES: permission denied, open '/opt/reaction/src/client/plugins.js'

That normal because reaction use the user 'node' in order to read/write the files, and because the folder /opt/reaction/src/ is shared between the container and the computer, in case of a linux server, the container cannot read that folder.

### Quick fix

in docker-compose, remove volumes :
- .:/opt/reaction/src:cached
- ./.meteor/local:/opt/reaction/src/.meteor/local:delegated

**Comment by aldeed** [comment]
I believe this is a symptom of general file ownership issues with mapped volumes, which should be now resolved in recent releases.
