### ISSUE TITLE
Plugin assets are not copied over to private directory

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#5032]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
A custom plugin should be able to contain a `private` directory that is copied over to the application's `private` directory on startup. It looks like this no longer happens. The issue can be traced to `.reaction/run/provisionAssets.mjs`, line 39, which is calling `fs.copySync` - a function that does not exist.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create a custom plugin with a `private` directory
2. After line 35 in the file mentioned above, add `console.log("sourceDir", sourceDir)`
3. Startup Reaction. Observe your custom plugin's directory being listed, followed by an error about `fs.copyFile`

## Possible Solution
Node does have `fs.copyFileSync` but this doesn't work for directories. Write a function that recursively copies the plugin's `private` directory and files over.

**Comment by aldeed** [comment]
This is intentionally no longer a feature
