### ISSUE TITLE
Title in Admin always says "Not-found"

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5041]
## Issue Description
Title in admin always says "Not-found". Sort of a bummer if you want to bookmark things

## Steps to Reproduce
1. Go to the admin
1. Click around
1. Observe it always says "Not-found" in the tab title

### Versions
RC10

**Comment by focusaurus** [comment]
I tested this in the settings panel for a plugin and confirm the follow seems to work. Pseudo code with just the relevant bits:

```js
import { Helmet } from "react-helmet";

<Helmet>
  <title>{i18next.t(`${info.ns}.displayName`)}</title>
</Helmet>
```

That should work. Just a lot of busywork/boilerplate to do it in all the existing plugins.

**Comment by mikemurray** [comment]
I think this of this PR could provide a way to do it through `registerOperatorRoute`. Then if you want to change it dynamically, then @focusaurus's suggestion would be the way you'd go.

At the very least, the title should not be `Not-Found`. It should be `Shop Name | Reaction` or something like that.

@rymorgan any suggestion on what the default page title should be?

**Comment by rymorgan** [comment]
@mikemurray Yes, I think it should be - 
Shop Name | Home 
Shop Name | Orders
Shop Name | Tag Editor 

Etc. 

At the moment we don't have a home or dashboard so for the moment it's got to default to whatever is the top navigation item. Not having an operator home is something that needs to be addressed soon though...

**Comment by focusaurus** [comment]
@mikemurray Presumably for i18n the `registerOperatorRoute` approach would need the plugin to pass a function to get the title I think to take into account the current language/locale. Could be a normal JS function or maybe a react pure component function I guess. The `react-helmet` approach deals with that somewhat nicely as is, though. I think I should probably defer to you on how you want this API to work though.

**Comment by willopez** [comment]
@mikemurray what is your suggestion on what strategy to use to move this forward?
