### ISSUE TITLE
make fails after cloning the repository [help-wanted]

### ISSUE THREAD

**Issue by fhdalikhan** [reactioncommerce/reaction#5044]
I am using a fresh DO droplet using ubuntu 16.

After following the instructions on https://docs.reactioncommerce.com/docs/installation-reaction-platform,

when I clone the repository and issue the make command, it fails with below error, any help would be appreciated:

Creating reaction-next-starterkit_web_1 ... error

ERROR: for reaction-next-starterkit_web_1  Cannot start service web: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/usr/local/src/reaction-app/bin/start\": stat /usr/local/src/reaction-app/bin/start: no such file or directory": unknown

ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/usr/local/src/reaction-app/bin/start\": stat /usr/local/src/reaction-app/bin/start: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
Makefile:218: recipe for target 'start-reaction-next-starterkit' failed
make: *** [start-reaction-next-starterkit] Error 1

**Comment by spencern** [comment]
Hi @fhdalikhan 
We haven't tested running in development mode on DO as far as I know, but there isn't anything that should prevent it in theory. A quick google search of your error suggests that it may be a permissions issue with your machine: https://github.com/docker/compose/issues/4039

**Comment by spencern** [comment]
I'm going to close this issue for now as I don't believe it's related to `reaction`. Feel free to reopen if you have more information that points to this being a problem with Reaction

**Comment by fhdalikhan** [comment]
I have tried with another fresh droplet using 3gb ram, now the problem is when I run make start all of the 5 containers start, but after some seconds 2 containers stop running.

I ran sudo make start, which gave me below output

Starting reaction-hydra_postgres_1 ... done
Starting reaction-hydra_hydra-migrate_1 ... done
Starting reaction-hydra_hydra_1         ... done
Starting reaction_mongo_1 ... done
Starting reaction_reaction_1 ... done
Starting reaction-next-starterkit_web_1 ... done

Running sudo docker ps after a few seconds showed that only 3 were running, below is the output

CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
25343964c19b        mongo:3.6.3                       "docker-entrypoint.s…"   20 minutes ago      Up 3 minutes        0.0.0.0:27017->27017/tcp                                   reaction_mongo_1
7b06937ca0a1        oryd/hydra:v1.0.0-beta.9-alpine   "hydra serve all --d…"   21 minutes ago      Up 4 minutes        0.0.0.0:4444-4445->4444-4445/tcp, 0.0.0.0:5555->5555/tcp   reaction-hydra_hydra_1
0c8d64e2f4a2        postgres:10.3                     "docker-entrypoint.s…"   21 minutes ago      Up 4 minutes        0.0.0.0:32771->5432/tcp                                    reaction-hydra_postgres_1


Running docker-compose logs -f inside reaction-next-starterkit folder I can see below error in logs


Attaching to reaction-next-starterkit_web_1
web_1  | yarn install v1.13.0
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error Could not write file "/usr/local/src/reaction-app/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/reaction-app/yarn-error.log'"
web_1  | error An unexpected error occurred: "EACCES: permission denied, copyfile '/home/node/.cache/yarn/v4/npm-@material-ui-utils-3.0.0-alpha.3-836c62ea46f5ffc6f0b5ea05ab814704a86908b1/node_modules/@material-ui/utils/.yarn-tarball.tgz' -> '/home/node/.cache/yarn-offline-mirror/@material-ui-utils-3.0.0-alpha.3.tgz'".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
web_1  | yarn install v1.13.0
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error Could not write file "/usr/local/src/reaction-app/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/reaction-app/yarn-error.log'"
web_1  | error An unexpected error occurred: "EACCES: permission denied, copyfile '/home/node/.cache/yarn/v4/npm-@babel-runtime-7.3.1-574b03e8e8a9898eaf4a872a92ea20b7846f6f2a/node_modules/@babel/runtime/.yarn-tarball.tgz' -> '/home/node/.cache/yarn-offline-mirror/@babel-runtime-7.3.1.tgz'".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
web_1  | yarn install v1.13.0
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error Could not write file "/usr/local/src/reaction-app/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/reaction-app/yarn-error.log'"
web_1  | error An unexpected error occurred: "EACCES: permission denied, copyfile '/home/node/.cache/yarn/v4/npm-@babel-runtime-7.3.1-574b03e8e8a9898eaf4a872a92ea20b7846f6f2a/node_modules/@babel/runtime/.yarn-tarball.tgz' -> '/home/node/.cache/yarn-offline-mirror/@babel-runtime-7.3.1.tgz'".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
reaction-next-starterkit_web_1 exited with code 1



I can see that there is no folder at this location "/usr/local/src/reaction-app" named reaction-app, so what is this issue, please help.

**Comment by spencern** [comment]
This still seems to be an issue with your system configuration from the `EACCES: permission denied` errors you're getting

**Comment by fhdalikhan** [comment]
Well there is no folder at this location /usr/local/src/reaction-app

I have followed instructions here
https://docs.reactioncommerce.com/docs/installation-reaction-platform

I am using ubuntu 18.04.

Thank you for your continued responses.
