### ISSUE TITLE
Layout always shows default logo (does not check for shop logo before falling back)

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#5046]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Layout always uses default Logo image without checking shop images.
Shops with their own brandAssets do not see their logo on the home & OAuth login pages (which also uses the CoreLayout).

## Steps to Reproduce
- Visit home screen or OAuth login pages (/account/login). 
- Note that default Reaction Logo shows always (even in shops with their own image assets).

## Possible Solution
It looks like instead of setting the IMG src directly as a string below:
https://github.com/reactioncommerce/reaction/blob/85ab73cedae91f1af5214ba8540f286d6358ba45/imports/plugins/core/layout/client/components/coreLayout.js#L70-L74

It should probably be using a logic like this:
https://github.com/reactioncommerce/reaction/blob/85ab73cedae91f1af5214ba8540f286d6358ba45/imports/client/ui/components/ShopLogoWithData/ShopLogoWithData.js#L35-L47

### Versions
(run `reaction -v` from your reaction directory)
Node: 10.13.0
NPM: 6.7.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.9
Reaction branch: develop

**Comment by mikemurray** [comment]
This has been resolved in and is in the develop branch.
