### ISSUE TITLE
productDetail: Tags sortable bug

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#505]
Hello, small bug with sortable. detected in Chromium.
![tags_sorting_bug](https://cloud.githubusercontent.com/assets/11130487/10817284/9951cc74-7e5a-11e5-8f8c-f2fb396e9f58.gif)

**Comment by mikemurray** [comment]
Confirmed. Thanks for reporting.

**Comment by aaronjudd** [comment]
For posterity, resolved in https://github.com/reactioncommerce/reaction-core/commit/3b4ca653771d0eed0cb7ab4023d624466c7439f0
