### ISSUE TITLE
Invite markeplace owner - validation error: Order status labels is required

### ISSUE THREAD

**Issue by TilenKreca** [reactioncommerce/reaction#5057]
## Issue Description
When invitation to new markeplace owner is sent. We are getting error: Order status labels is required.

## Steps to Reproduce
1. Logged in as admin
2. Go to Shop menu
3. Turn on markeplace switch
4. Invite new markeplace owner

![marketplace](https://user-images.githubusercontent.com/6170179/54671255-dacfb880-4af5-11e9-9c4c-485f76660d53.jpg)

## Possible Solution
In file reaction/imports/plugins/core/orders/lib/extendShopSchema.js there is missing parameter for "optional: true". This was assumed while property was described as optional before (@property {Object} orderStatusLabels optional).

```
orderStatusLabels: {
    type: Object,
    blackbox: true,
    optional: true
  }
```

### Versions
Node: 8.15.0
NPM: 6.7.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.10
Reaction branch: develop
Docker: 18.06.1-ce

**Comment by aldeed** [comment]
Marketplace plugin is no longer built in
