### ISSUE TITLE
Navigation editor breaks when default navigation tree has no items

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5066]
## Issue Description

Navigation editor shows a white screen, and an error in the console when no navigation items exist

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Go to http://localhost:3000/operator/navigation
2. Delete all nav items
3. Refresh and see a white screen

## Possible Solution

Add better null checking for the navigation items/tree GQL queries.

### Versions

Node: 10.7.0
NPM: 6.5.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.10
Reaction branch: develop
Docker: 18.09.2

**Comment by manueldelreal** [comment]
confirmed locally (since I didn't want to destroy the data on staging), that my navigation editor is presented with no options after deleting all navigation items, it doesn't crash.
