### ISSUE TITLE
Tax code field not available when adding custom rate

### ISSUE THREAD

**Issue by derBretti** [reactioncommerce/reaction#5072]
## Issue Description
The tax code field is only available when editing a custom rate, but not when adding one in first place.

## Steps to Reproduce
1. Open the Taxes section
2. Click '+' under 'Custom Rates', compare with the fields displayed when selecting an existing custom rate

## Possible Solution
Add field to custom.html

### Versions
Reaction: 2.0.0-rc.10

**Comment by chrispotter** [comment]
Looks like this was solved with #5076. @aldeed do you agree?
