### ISSUE TITLE
Performance: in Calbre app - add more browsers and devices into testing

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5077]
In order to better track overall performance, we should add more browsers and different mobile devices into the testing suite.

Currently, only Chrome is available as a browser, but we've been told by Calibre that Safari and Firefox are coming soon.

**Comment by aldeed** [comment]
@kieckhafer  should this be transferred to `reaction-admin` or closed?

**Comment by kieckhafer** [comment]
This can be closed, and re-visited later on maybe more in sync with some of the deployed environments.
