### ISSUE TITLE
Performance: in Calbre app - add notifications to alert us when performance metrics degrade

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5078]
Look into adding notifications (email, slack) to alert the team when performance degrades in the app.

**Comment by aldeed** [comment]
@kieckhafer  should this be transferred to `reaction-admin` or closed?

**Comment by kieckhafer** [comment]
This can be closed, and re-visited later on maybe more in sync with some of the deployed environments.
