### ISSUE TITLE
Make custom tax codes available in product settings

### ISSUE THREAD

**Issue by derBretti** [reactioncommerce/reaction#5082]
## Issue Description
Custom tax codes are not available in product tax settings.

## Steps to Reproduce
1. Go to the Taxes section in operator ui
2. Add a custom rate with a tax code (e.g. "tx_10")
3. Open a product variant in operator ui
4. Note that the only "RC_TAX" is available in the dropdown menu for Tax code

## Possible Solution
Return possible tax codes for the shop in `getTaxCodes.js`.

### Versions
Reaction: 2.0.0-rc.10

**Comment by aldeed** [comment]
Done in Reaction Admin 3.0
