### ISSUE TITLE
Add unit test for xformCartItem transform

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#5086]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
xformCartItem does not have a unit test. Add unit test to ensure function works as expected. https://github.com/reactioncommerce/reaction/blob/99e5f1061a50fbe55d2e7950a91573b7c4c646d0/imports/plugins/core/graphql/server/no-meteor/xforms/cart.js#L45 

## Possible Solution
Add unit test

**Comment by urbangabbar** [comment]
@aldeed Is this issue available. Would like to make contribution.

**Comment by delagroove** [comment]
Hi @urbangabbar feel free to make the contribution by forking this repository and then doing a merge request.  by then @Akarshit or @MohanNarayana will take care of the rest of the process.
