### ISSUE TITLE
Image Gallery strange behavior

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#509]
Hello, In this video I'm just moving over image by guest.
![screencast_image_gallery](https://cloud.githubusercontent.com/assets/11130487/10850983/45e54700-7f4a-11e5-94a1-4180d3f62a54.gif)
I think this is pretty unexpected gallery behavior.

And bug: tags not displayed when not logged in on productDetail page

**Comment by Aesop7** [comment]
Could we simply change "mouseenter .gallery > li" to a click event in https://github.com/reactioncommerce/reaction/blob/153506a8052b5bde9c33be93855a9a9944110512/packages/reaction-product-simple/client/templates/productDetail/images/productImageGallery.js ?

**Comment by zenweasel** [comment]
I can reproduce this problem and I would definitely say it's not expected. I also noticed that I uploaded three images for a product and it only happened when mousing over the third one, but the normal behavior (moused-over image replaced the hero image) happens when mousing over the second.
