### ISSUE TITLE
Performance: Orders publication causes massive app slowdowns with many connected clients

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5094]
## Issue Description

Orders publication/UI causes massive app slowdowns with many connected clients.

## Steps to Reproduce

[TBD]

## Possible Solution

The publication is likely the issue so...
- Look at the reactive aggregation as the possible cause
- Look into fetching orders in a way that avoids the Meteor pub/sub model

**Comment by zenweasel** [comment]
The original reason for the `reactiveAggregate` was to be able to filter out queries for orders by shop (e.g. show only items for a particular shop while an order contained multiple shops)

This is no longer a requirement so this can just be a regular query now with pagination

**Comment by zenweasel** [comment]
I strongly doubt this is the cause of the slowdown but we should totally fix this before launch

**Comment by aldeed** [comment]
Yes my vote is to remove the orders subscription, add an orders GraphQL query and use that. Pretty much a straight copy of some of the other paginated collection resolvers we have for other collections.

**Comment by mikemurray** [comment]
Merged a PR attempting to address this: https://github.com/reactioncommerce/reaction/pull/5096
