### ISSUE TITLE
Publishing products causes performance issues

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#5098]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When products are published in the Catalyst UI an `afterPublishProductToCatalog` app event is emitted. The core cart plugin registers a function to update all carts that have a variant of the published products. This leads to noticeable performance degradation in the Catalyst UI.

Reference: 
https://github.com/reactioncommerce/reaction/blob/develop/imports/plugins/core/cart/server/no-meteor/startup.js#L144

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Load sample test data
2. Create multiple different carts and add various different products to it
3. Republished products that have been added to carts

## Possible Solution
Batch updates to cart on start up, don't use `Promise.all`

**Comment by spencern** [comment]
Thanks for raising this issue @willopez 

Some other questions/ideas to go along with this.

Should we be updating carts when a product has published at all? 
I think this should probably be an option for operators - perhaps a notification to customers? ("your cart has changed!", "Item `foo` has increased in price by `$0.52`. Possibly a prompt - Would you like to update your cart or remove the item?)

I don't think we should be doing this in the main thread though. Maybe this is something that could be delegated to a job/worker task?

Not sure what the best path forward here is, but in a scenario where a popular product is published you could have tens to hundreds of thousands of carts that all need to get updated, have their taxes, shipping, etc recalculated. Would be a very expensive operation to perform on the main app thread.

**Comment by aldeed** [comment]
I agree this should be moved to use a background queue. With the way the built-in pricing currently works, this is necessary because otherwise your cart will show the incorrect price. Now that we're moving toward a separate pricing engine, I would prefer to not have prices stored on anything. Whether it be catalog or cart, it can simply ask the pricing service for the current price whenever it is needed.

**Comment by willopez** [comment]
@aldeed Perhaps we could use the existing job manager, or this would be a good time to replace it with a better solution.
