### ISSUE TITLE
Product grid fails to load if product permalink is empty field

### ISSUE THREAD

**Issue by adrienshen** [reactioncommerce/reaction#5100]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [yes ] Are you running the latest version?
* [yes] Are you able to consistently reproduce the issue?
* [yes] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When change fields for a new product, if user clears the default permalink field and accidentally clicks outside the field area, the empty permalink is saved and now the product is bugged out. The product grid catalog also can not load because the `pdpPath()` now is not a string output.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Clear permalink field in a product
2. Click away or save changes
3. Navigate to product or product grid list views.

## Possible Solution
- Prevent users from saving an empty permalink.
- Try/catch in productGridItems.js render method, and return null.

### Versions
Node: 11.1.0
NPM: 6.4.1
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.10
Reaction branch: HEAD
Docker: 18.09.0

**Comment by mikemurray** [comment]
@adrienshen The product grid and PDP have been rebuilt and moved to the new admin experience in `2.0.0-rc.11`. Here are the release notes: https://github.com/reactioncommerce/reaction/releases/tag/v2.0.0-rc.11
