### ISSUE TITLE
Tags subscription / data issue

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#5101]
## Issue Description
Research how we're subscribing to Tags and how that scales as tags are added to the application. With a small number of connected clients `< 10` - I'm seeing very high numbers of documents published.

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/1203639/55587603-ed96df80-56e8-11e9-98b2-2ec103dad7d2.png">

**Comment by mikemurray** [comment]
@spencern we publish and subscribe to all tags in the application.

Sub: https://github.com/reactioncommerce/reaction/blob/develop/client/modules/core/subscriptions.js#L38

Pub: https://github.com/reactioncommerce/reaction/blob/develop/imports/plugins/core/core/server/publications/collections/tags.js#L8

**Comment by aldeed** [comment]
So yeah, that subscribe is in root client code, which means everyone including those just on the IDP route will get every tag in the system sent to their client. The first thing I'd try is just removing the subscription. We may no longer need them anywhere. If anything breaks, we can add back a more granular Tags subscription for that route only.

**Comment by aldeed** [comment]
I merged Mike's fix for this but @spencern I'll let you close after verifying the subscriptions go down as expected.
