### ISSUE TITLE
Move inventory data out of Product and into it's own collection

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5107]
Having inventory on product causes problems for trying to update it as it requires that an entire product be published just to update inventory.

It should be its own standalone collection

**Comment by spencern** [comment]
I agree that we should separate Inventory from Product (which contains mostly product information data). I think doing this is a significant change that should allocate time for designing the architecture and understanding the current and future requirements we'll have for inventory systems.

**Comment by ticean** [comment]
I would love to see this happen ASAP! Product the product collection runs hot. Inventory is a frequently changing field and doesn't need to be entangled with the entire product record.

**Comment by zenweasel** [comment]
I think moving the data from being on the product to being in it's own collection is a good first step that doesn't block any implementations in the future and would be a relatively simple change with a big gain in server load. GraphQL resolvers really free us up here...

**Comment by loan-laux** [comment]
Not only should it be in its own collection, but inventory figures should be returned by their own plugin IMO. Just like it's done with `simple-pricing`, allowing anyone to skip Reaction's inventory management and fetch that data from an ERP.
