### ISSUE TITLE
Allow for a more granular publish

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5110]
Right now if you change any piece of data on a product you need to republish the entire top level product. With things like inventory that may change hour by hour, re-publishing 10's of thousands of products is just not reasonable and adds a tremendous amount of load on Mongo.

Some sort of solution between writing directly to the catalog and having to re-publish. If we move inventory to a separate collection that would help with some of this.

**Comment by ticean** [comment]
Agree that a separate inventory would help. Also, aggregating the input events by product such that a catalog publish happens once for eligible events within a given window would help, too.
