### ISSUE TITLE
bin/setup should handle .env missing trailing newline

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction#5111]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

If your `.env` file ends without a trailing newline, `bin/setup` won't correct that and thus you'll end up with 2 variables jumbled on the same line.

**Example .env before**

```
A=a
B=b
OOPSNONEWLINE=oops
```

**Example .env after ./bin/setup**
```
A=a
B=b
OOPSNONEWLINE=oopsC=c
```

`C=c` should go on a new line, but it gets put on the end of the preceeding line.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Remove the final newline from your `.env` file.
  - This is actually somewhat tricky to do in normal editing since most editors add a final newline automatically
  - `echo -n FOO=foo >> .env`
2. Make sure your `.env` is missing at least one variable from `.env.example`
3. Run `./bin/setup`

## Possible Solution
`setup` could detect this explicitly and fix it.

### Versions
(run `reaction -v` from your reaction directory)

**Comment by focusaurus** [comment]
Might make a separate function that runs at the beginning and ensures `.env` has a final newline (via `tail -1 | grep -E` or something).

**Comment by aldeed** [comment]
Note that #5035 rewrites this script, but I didn't check to see whether that rewrite fixes this issue. I'm guessing probably not.

**Comment by mikemurray** [comment]
Resolved in #5156
