### ISSUE TITLE
Emails: Button in welcome email for customer user does not go to storefront

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5115]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The welcome email sent after a customer registers a new account has a button. When you click that button, it goes to the IDP sign-in form, but signing in does not work and does not redirect you to the storefront URL as expected.

### Setup
1. Log in as operator.
2. Edit Shop settings and make sure the shop email address is testing@reactioncommerce.com. This address is verified to send emails through the Reaction testing SES account. Other addresses may not work.
3. Go to the operator user profile page and make sure you have a real email address. You can use something like `<yourname>+admin@reactioncommerce.com`.
4. Enter correct email service credentials on Email page. Make sure the indicator is green.

### Reproduce
1. Register a new user from storefront UI.
2. Click the Get Started button in the email you receive.

## Possible Solution
Need to figure out what should happen or what previously happened when this worked, and then make it happen again.

### Versions
2.0.0 RC 11

**Comment by willopez** [comment]
Verified this issue has been resolved in a previous update.

**Comment by jm18457** [comment]
Sorry for writing this, but how is this issue solved?
Clicking Get Started button in email redirects user to `backend/#/verify-email/...` URL, where user only sees login page.

Data is gained through `sendWelcomeEmail.js` where there is no mention of storefront url.
