### ISSUE TITLE
Catalog Items query "featured" sort performs poorly with large dataset

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5116]
## Issue Description

Querying `catalogItems` with `sortBy featured` option has severe performance issues when there is a large number of products in the catalog.

## Possible Solution

Revert to the old aggregation, while it's not perfect, should perform better than the current implementation. This would be temporary while we reassess a more permanent solution.

**Comment by aldeed** [comment]
PR here but not sure yet if it's the full fix: https://github.com/reactioncommerce/reaction/pull/5136
