### ISSUE TITLE
Update Nav Tree in Operator UI to accommodate 10 levels 

### ISSUE THREAD

**Issue by kkuzemka** [reactioncommerce/reaction#5117]
We need to accommodate 10 levels of navigation for the Bobs site - see these tickets in SD Labs:
https://github.com/sportsdirect/reaction-storefront/issues/476
https://github.com/sportsdirect/reaction-storefront/issues/470

Once these are complete, Morgan and Rob can update the navigation on the Bobs site.

**Comment by mikemurray** [comment]
Closed by this issue: https://github.com/reactioncommerce/reaction/pull/5129
