### ISSUE TITLE
autoValue for product handle creates lowercase version of product id by default

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#513]
To reproduce:  
1. Create a new product using the navbar dropdown -> `+ Add Product`
2. Fill out product details
3. Make product visible without setting a new handle.
4. Try visiting product from index

From product creation page
![image](https://cloud.githubusercontent.com/assets/1203639/10954252/9b2c6aaa-8309-11e5-8b90-d8f9414aaf20.png)

Linked product
![image](https://cloud.githubusercontent.com/assets/1203639/10954261/a7e1b9a8-8309-11e5-8524-361c2368d56a.png)

**Comment by aaronjudd** [comment]
ah, yes this was a recent change.

**Comment by spencern** [comment]
I think #514 may address this.

**Comment by aaronjudd** [comment]
@spencern https://github.com/reactioncommerce/reaction-core/pull/206 took care of part of this, I merged this into development yesterday, but that PR didn't quite go all the way, so I agree #514 will probably take care of this.  @mikemurray if you want to close this in favor of #514 I think that'd make sense.

**Comment by spencern** [comment]
:+1:
