### ISSUE TITLE
Cannot connect merchant with stripe account - stripe redirect url "Not Found"

### ISSUE THREAD

**Issue by TilenKreca** [reactioncommerce/reaction#5131]
## Stripe redirect url "Not Found"

Redirect url from Stripe does not trigger meteor action `stripe/connect/authorizeMerchant`
I follow this instructions:
https://docs.reactioncommerce.com/docs/next/merchant-shop-setup

## Steps to Reproduce

1. Invite markeplace owner: FIX: https://github.com/reactioncommerce/reaction/issues/5057
2. Enabled marketplace in "Shop Settings"
3. Enabled the Stripe payment method in "Payment Methods"
4. Setting up stripe account redirect to: `https://<yourdomain>/stripe/connect/authorize`
5. Logged in as merchant shop
6. Shop->My Shop Settings->Start Accepting Payment

## Possible Solution

I have managed to establish stripe redirect url to work. Basically with RC11 this url is no longer relevant that is described in documentation:
https://docs.reactioncommerce.com/docs/next/merchant-shop-setup

This url should now be:
`https://<yourdomain>/operator/shop-settings/stripe/connect/authorize`

I also changed file: /reaction/imports/plugins/included/marketplace/register.js

From:
```
 // Redirect for Stripe Connect Sign-In
 {
    route: "/stripe/connect/authorize",
    template: "stripeConnectAuthorize"
 },
```
To:
```
// Redirect for Stripe Connect Sign-In
{
   route: "/stripe/connect/authorize",
   template: "stripeConnectAuthorize",
   provides: ["marketplaceMerchantSettings"]
},
```

After those changes account is marked as: "Your Stripe Account Is Connected". Only loading bar persists.

![slika](https://user-images.githubusercontent.com/6170179/56291702-0b6f3600-6126-11e9-9d70-d244fb77cc07.png)

### Versions
Node: 8.15.0
NPM: 6.7.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.11
Reaction branch: HEAD
Docker: 18.06.1-ce

**Comment by NoShadock** [comment]
@TilenKreca Thanks a lot for opening the road ! I need the marketplace too, I'll catch up soon ^^

**Comment by aldeed** [comment]
Marketplace stripe is no longer built in
