### ISSUE TITLE
Support fulfillment types other than "shipping"

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction#5139]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
It seems that everything is made in the back-end code to allow different fulfillment types, yet only "shipping" seems to be allowed.

## Possible Solution

Here's a starting point for the changes that I thing need to be made:

* In the following schemas/fields, allow for values `digital` and `pickup` in addition to `shipping`:
  * `Product` > `supportedFulfillmentTypes`
  * `FulfillmentMethod` > `fulfillmentTypes`
* Add a multi-select dropdown in the product variant admin to pick supported fulfillment types

I'm ready to work on a PR to implement this but I'd gladly appreciate guidance from the core team!

### Versions

Node: 8.15.0
NPM: 6.9.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.11
Reaction branch: develop
Docker: 18.09.2

**Comment by spencern** [comment]
A few next steps
1. Create another fulfillment type - such as `digital` or `pickup` - add it to the GraphQL API
2. Step through cart/checkout process with this new fulfillment type and see what breaks, identify what may need to be changed as additional fulfillment types are introduced

**Comment by loan-laux** [comment]
@spencern Step `1` done. However now we need UI changes to be able to pick an alternative fulfillment type on add to cart. I'm implementing @rymorgan's mockups into my fork of the Next.js starter-kit so we can move past this.

**Comment by misha-erm** [comment]
Are there any updates on this issue? As I can see it's still not possible to use any option except 'shipping'

**Comment by misha-erm** [comment]
Or maybe it's worth mentioning in the docs at least?
![image](https://user-images.githubusercontent.com/8783498/102222892-1549cd80-3ef5-11eb-8647-5f979bb47776.png)
