### ISSUE TITLE
Create bulk version of publication functions

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5141]
Currently the `publishProductToCatalog` function is optimized for doing one-at-a-time updates, however any update from an external source is going to be more than one a time and the current update is extremely slow.

We should look at trying to create functions like `publishProductsToCatalog` (notice the 's') that allows an array of products to be passed in and more importantly leverages the Mongo bulk operations API.

**Comment by zenweasel** [comment]
Assigning myself and Eric D. for discussion.

**Comment by rymorgan** [comment]
@zenweasel Will this end up having a UI?

**Comment by zenweasel** [comment]
@rymorgan 
It would probably be used by whatever bulk product edit we build, this issue is specifically about the backend API, not about any UI

We currently have a "Publish All" button that doesn't work which could also use it.

**Comment by aldeed** [comment]
- There is already a `publishProductsToCatalog`, but it's a util function so it isn't accessible on context. I could easily move it to `mutations.publishProductsToCatalog` so other plugins can call it BUT...
- `publishProductsToCatalog` is currently nothing more than a code loop over the singular version of it. There are no db optimizations.
- And there is currently no queue

I can focus on the following improvements in this order:

1. Expose `publishProductsToCatalog` to other plugins, and update it to do bulk DB lookups and writes.
2. Use the job queue for `publishProductsToCatalog` calls, and work it async and throttled.
3. Ensure manual Publish/Publish All buttons take advantage of these improvements.

**Comment by rymorgan** [comment]
@zenweasel Thanks for the context 👍

**Comment by janus-reith** [comment]
I wonder if some kind of debouncing could be implemented / makes sense for bulk publishing.

In a (probably common)scenario, an external api could send atomic product updates in real time when product data was changed. These changes would need to be published, but there would probably be no manual triggering involved.

But the API sending this would not know the "first" product is sent and when the last product was sent before a publish is required.
Publishing each individual change could be really resource intense, even more when `appEvents` are used which trigger additional functions after publish.

**Comment by aldeed** [comment]
@janus-reith Debounce is a good idea in theory. The main issue with it that I can think of is the potential desire of the API caller to know for sure that publishing is complete when the response comes. This is broadly the issue we're having everywhere: Reaction is moving toward being event driven, but trying to remain backwards compatible with API expectations for synchronous behavior.

But I definitely think a generic debouncing/batching pattern could be useful throughout the app, and we can keep that in mind when addressing this issue.

**Comment by zenweasel** [comment]
@aldeed Is this being done as part of the bulk-editing epic or do we still need this open?

**Comment by aldeed** [comment]
@aldeed It is not being done with bulk editing. Event-driven catalog publisher may make parts of this less necessary or possible, but it's a somewhat separate concern.

**Comment by zenweasel** [comment]
Closing as there is nothing actionable here
