### ISSUE TITLE
PDP Variant Layout UX update

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#515]
With inventory updates we'll not be automatically updating inventory qty for variants with children. 

This leads to a UI refactor, but rather than just replacing the inventory logic, we should update the product detail page.
- [x] Move variant control/setting template into the admin side bar.
- [ ] Simple Product View - 
  https://github.com/reactioncommerce/reaction/issues/500 with a "single variant / simple product view" 
- [x] Variants (with children) with images.
- [ ] Variant / Option View dropdown selector, with images. 
  ![amazon_com__giro_new_road_republic_shoes_lead_gum__41_0_-_men_s__sports___outdoors](https://cloud.githubusercontent.com/assets/439959/11104879/49186760-8880-11e5-8e1c-060a59a4f359.png)
  ![amazon_com___pearl_izumi_men_s_quest_jersey__white__x-large___cycling_jerseys___sports___outdoors](https://cloud.githubusercontent.com/assets/439959/11105155/02ee502c-8882-11e5-8611-e9a29308cc10.png)

**Comment by spencern** [comment]
This is HUGE. So looking forward to this UI update, something we discussed adding internally a few times @getoutfitted but have held off on so far.

**Comment by aaronjudd** [comment]
I will shed a few tears to see my progress bars gone ;-)

**Comment by spencern** [comment]
We will all mourn the loss of the progress bars. :cry:

**Comment by aaronjudd** [comment]
Closing - insufficient details.
