### ISSUE TITLE
Are there plans for Product Reviews / Comments?

### ISSUE THREAD

**Issue by rohanthacker** [reactioncommerce/reaction#516]
Greetings All,
First off thank you creating this platform. I hope I can help improve it along with the team. 

I have been trying to find out if reaction currently supports reviews and or comments on the product detail page. I have looked through the Milestones and Issues but I didn't find any information.

If we're yet to implement such a feature I'd be happy to create a package with this functionality.

**Comment by aaronjudd** [comment]
Not yet, but that would make a great package.

**Comment by rohanthacker** [comment]
@aaronjudd  Cool, I'll get to work on it then.

**Comment by bluerabbbit** [comment]
@rohanthacker How far along are you with that?

**Comment by rohanthacker** [comment]
@bluerabbbit Unfortunately I've not had the time to take this forward, as I am not actively working with reaction commerce any longer.

**Comment by kieckhafer** [comment]
This isn't currently in our product roadmap, but would love contributions towards making this happen.

Here's a great open source solution for reviews: https://www.yotpo.com/lp/request-a-demo1/?utm_medium=directory&utm_source=getapp&utm_campaign=feedback_reviews_management

**Comment by aaronjudd** [comment]
Closing - insufficient details.
