### ISSUE TITLE
replaceBlock does not work

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#5160]
## Issue Description
`replaceBlock` function does not work.

## Steps to Reproduce
In a plugin, call the `replaceBlock` function, e.g.:

```
replaceBlock({
  region: "VariantDetailMain",
  block: "OptionTable",
  component: OptionTable
});
```
See that there is an error in the browser console:
```
Cannot read property 'undefined' of undefined
```

## Possible Solution
`replaceBlock` function just needs renaming of some parameter/variable names.

### Versions
`develop`

**Comment by mikemurray** [comment]
Changes have been merged into `develop` from PR #5161
