### ISSUE TITLE
Server crashes when WebSocket upgrade request has wrong path

### ISSUE THREAD

**Issue by MaksimAniskov** [reactioncommerce/reaction#5170]
## Issue Description

WebSocket upgrade request with wrong path makes server crashing with `socket.close is not a function` error.

> 06:04:20.033Z  INFO Reaction: Reaction Version: 2.0.0-rc.11
06:04:21.289Z  INFO Reaction: Reaction initialization finished: 61527ms
06:04:21.399Z  INFO Reaction: GraphQL listening at http://localhost:3000/graphql-alpha
06:04:21.399Z  INFO Reaction: GraphQL subscriptions ready at ws://localhost:3000/graphql-alpha
06:04:24.950Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
06:04:24.987Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
meteor://💻app/app/app.js:44325
        socket.close();
               ^
> 
> TypeError: socket.close is not a function
    at Server.WebApp.httpServer.on (imports/plugins/core/core/server/startup/startNodeApp.js:133:7)
    at emitThree (events.js:141:20)
    at Server.emit (events.js:217:7)
    at onParserExecuteCommon (_http_server.js:508:14)
    at onParserExecute (_http_server.js:462:3)

## Steps to Reproduce
1. Run reaction v2.0.0-rc.11 Docker image available on Docker Hub (providing correct .env)
`docker run -p 3000:3000 reactioncommerce/reaction:v2.0.0-rc.11`
2. Use wscat to hit the endpoint
`wscat -c ws://localhost:3000`

**Comment by janus-reith** [comment]
Why hasn't this been flagged **impact-critica**l yet?

**Comment by willopez** [comment]
Resolved in https://github.com/reactioncommerce/reaction/pull/5255
