### ISSUE TITLE
Dead client-side import in product-admin

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction#5179]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
`/imports/plugins/included/product-admin/client/components/index.js` contains an import/export for `./productAdmin.js`, which doesn't exist anymore.

For some reason, it would **sometimes** make the Products link in the operator sidebar disappear, along with showing an error about this file not existing in the client-side console. I still can't understand why this behavior isn't consistent.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Open the operator.
2. Pray for the bug to be in the mood of manifesting itself.
3. Notice the error about `./productAdmin.js` not existing in the console, and the missing Products link in the sidebar.

## Possible Solution
Remove this dead import.

**Comment by mikemurray** [comment]
Fixed in #5180
