### ISSUE TITLE
Investigate adding security and DDoS packages

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5184]
https://leapgraph.com/graphql-api-security

This article mentions several add-on packages that Reaction may want to use. This issue is simply to investigate whether these vulnerabilities are present and try adding the packages to solve them.

**Comment by imroon1** [comment]
reduce DDOS attacks and seting to revers nginx ang 
#Specify adresses that are not allowed to access your server
    deny 192.168.1.1/24;
    deny 192.168.2.1/24;
    allow all;

**Comment by loan-laux** [comment]
@imroon1 Why revive a 2 year-old thread with a response that has nothing to do with the original topic?
