### ISSUE TITLE
Failed suddenly after docker compose up (the build was fine)

### ISSUE THREAD

**Issue by nntoan** [reactioncommerce/reaction#5188]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

```
reaction_1  | npm WARN react-taco-table@0.5.1 requires a peer of react-dom@^15.3 but none is installed. You must install peer dependencies yourself.
reaction_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
reaction_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
reaction_1  |
reaction_1  | up to date in 62.119s
reaction_1  |
reaction_1  | real	1m6.760s
reaction_1  | user	1m5.000s
reaction_1  | sys	0m3.320s
reaction_1  | MongoDB replica set initialized and ready.
reaction_1  | (node:52) ExperimentalWarning: The ESM module loader is experimental.
reaction_1  | Setting up plugin imports...
reaction_1  |
reaction_1  | Failed to reset plugins file at /opt/reaction/src/client/plugins.js
reaction_reaction_1 exited with code 1
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Use the steps in `reaction-platform` to install.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
(run `reaction -v` from your reaction directory)

**Comment by aldeed** [comment]
Since this is old, I'm going to assume this is resolved by more recent releases. If not we can reopen.
