### ISSUE TITLE
ENHANCEMENT: Integration w/ "Automation" apps... (Zapier, IFTTT, Tasker, Etc...)

### ISSUE THREAD

**Issue by oneezy** [reactioncommerce/reaction#519]
It would be great if _Reaction Commerce_ could integrate with automation apps like [Zapier](https://zapier.com/zapbook/)!

As a rule of thumb now (for me), I only use web apps from Zapier's "Zap Book" because of how well the integration works. It's key for making a 100% fully automatic business :)

**Comment by aaronjudd** [comment]
I've thought about this before, and like this idea.  Similar to the integration with segment.io/analytics.js that we do in the reaction-analytics package.

**Comment by bluerabbbit** [comment]
+1

**Comment by mschipperheyn** [comment]
I'm curious what the status is on this issue. I know that segment.io is used for analytics integration. And I'm wondering if there is a kind of generic integration with segment.io or Zapier. There doesn't seem to be. What is relevant for me is to be able to integrate certain shop events with Salesforce. Does this item have priority or is it a backlog item? IMHO It would really help overcome the lack of available plugins in various areas.

**Comment by zenweasel** [comment]
@mschipperheyn This issue is closed because we don't currently have plans to work on it. That said it would be relatively easy to create your own plugin that could do an integration by listening for [Event hooks](https://docs.reactioncommerce.com/reaction-docs/master/event-hooks). Combined with Collections hooks you can listen for pretty much any transaction in the system.

**Comment by mschipperheyn** [comment]
@zenweasel Ok, I wonder if it would be easy to use the Event hooks to create a more generic integration with Segment and / or Zapier to make the integration easier.

**Comment by zenweasel** [comment]
I believe we intend to create a generic integration with Segment as part of analytics but no plans for something like Zapier/IFTTT. But yes, using Event Hooks would allow you hook almost any server-side event to any external service. I think this is something we will hope will come from the community. If there is an event w/o a hook that you might want to add/track we would definitely open to a PR for it.
