### ISSUE TITLE
ProductGridItem is NaN when a price has > 3 digits

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#5191]
## Issue Description
If a product price range value is abobe 999.00 , e.g. 1,000.00, the Item in the Product Tabe shows NaN.

## Steps to Reproduce
1. In Operator, create a Product
2. Set the price of the first variant to 1000. (saved as 1,000.00)
3. Go back to Products, observe that Price is displayed as `NaN`.

## Possible Solution
The issue comes up here: https://github.com/reactioncommerce/reaction/blob/6629e25e018c4f536611d46db7267716c09b5d4a/client/modules/i18n/currency.js#L72

In this case, both `prices[0]` and `prices[1]` would be "1,000.00"
`Number("1,000.00")` is `NaN` ("1000.00" would work).

As we are already using `accounting-js` here it would work to use `unformat` here like this: `Number(unformat(prices[0]))` although that seems a bit weird, as this calls `getDisplayPrice` which then uses `formatMoney` again.

But as price on the toplevel product doesn't have information on the `currrencyCode` I'm not sure how to detemine if a conversion is actually necessary. We would also need that information to determine if a special decimal separator was used and pass it to `unformat`.

Any ideas? Could also be that I'm missing some of the changes due to the separated `simple-pricing` in my considerations.

### Version
`develop`

**Comment by aldeed** [comment]
@manueldelreal Can you try reproducing this when you have time?

**Comment by janus-reith** [comment]
Just noticed, I observed this behaviour with shop currency set to €.
I didn't test yet if it comes up on $ aswell, but it pobably does aswell.

**Comment by manueldelreal** [comment]
@aldeed I can reproduce it, see the attached screenshots. I used one of our demo sites for this.

![Screen Shot 2019-05-29 at 5 35 06 PM](https://user-images.githubusercontent.com/13787861/58596054-42159180-8238-11e9-99f9-f5121ee1f8de.png)

![Screen Shot 2019-05-29 at 5 34 46 PM](https://user-images.githubusercontent.com/13787861/58596056-42159180-8238-11e9-81bb-84af14241e2e.png)

**Comment by aldeed** [comment]
Fixed by #5193
