### ISSUE TITLE
Build badly broken on Debian bare metal

### ISSUE THREAD

**Issue by captnbli** [reactioncommerce/reaction#5194]
I ran the install script from https://docs.reactioncommerce.com/docs/installation-reaction-platform. Initially I had a couple of environment issues, then I ran a `make clean' then 'make'.

All seemed to be good but only half the containers stay up. Various logs and things attached. All sorts of things tried, including using `--unsafe-perm` on an `npm install`.

`reaction -v` doesn't work

node: v10.15.3
npm: 6.4.1
docker: Docker version 18.09.6, build 481bc77

[reaction-next-starterkit.log](https://github.com/reactioncommerce/reaction/files/3239088/reaction-next-starterkit.log)
[docker.ps.txt](https://github.com/reactioncommerce/reaction/files/3239089/docker.ps.txt)
[install.log](https://github.com/reactioncommerce/reaction/files/3239090/install.log)

**Comment by focusaurus** [comment]
Looks like filesystem permission issues with the yarn cache mount.

```
web_1  | error Could not write file "/usr/local/src/reaction-app/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/reaction-app/yarn-error.log'"
web_1  | error An unexpected error occurred: "https://registry.yarnpkg.com/brcast/-/brcast-3.0.1.tgz: EACCES: permission denied, open '/home/node/.cache/yarn-offline-mirror/brcast-3.0.1.tgz'".
```

Could you try (from your host OS) this command and see if that fixes it?

```sh
chmod -R a+r "${HOME}/.cache/yarn-offline-mirror"
```

**Comment by captnbli** [comment]
Didn't help. This sort of issue I overcame with fibers and yarn installs using `--unsafe-perm`. But changing the permissions didn't help (root had access already).

Also, the is no `/home/node` directory

**Comment by captnbli** [comment]
OH, and I believe the version of graphql is also an issue, as the latest version is not in the dependency list?

**Comment by focusaurus** [comment]
The error you are getting from yarn is about mismatched filesystem permissions between the container and the host. Our starterkit docker image runs as user `node` with uid `1000`. From the `reaction-next-starterkit` directory, we can take a peek:

```
docker-compose run web ls -ld /home/node/.cache/yarn-offline-mirror
# drwxr-xr-x    2 node     node        352256 May 31 04:22 /home/node/.cache/yarn-offline-mirror
docker-compose run web id
# uid=1000(node) gid=1000(node) groups=1000(node)
```

Your output from the first command above is probably different, and that's why you this error.

We have the following mount specified in our `docker-compose.yml` file:

```
$HOME/.cache/yarn-offline-mirror:/home/node/.cache/yarn-offline-mirror
```

What this means is that userid `1000` needs read/write access to that directory in your host filesystem (which will then also apply to the container). Currently in your host filesystem, that access isn't there, probably because your host userid is not coincidentally also 1000. Here's a little experiment to show how this plays out in a few userid/groupid situations.

```sh
# this is probably you're situation, essentially
sudo install --directory --owner 2000 --group 2000 --mode 755 /tmp/permtest/no-access-error
sudo install --directory --owner 1000 --group 1000 --mode 755 /tmp/permtest/rw-access-ok
sudo install --directory --owner 2000 --group 1000 --mode 775 /tmp/permtest/group-rw-access-ok   
docker run --rm --interactive --tty \
  --volume /tmp/permtest:/tmp/permtest \
  --user 1000:1000 \
  ubuntu \
  bash -c 'cd /tmp/permtest; touch rw-access-ok/file group-rw-access-ok/file no-access-error/file'
# touch: cannot touch 'no-access-error/file': Permission denied
ls -lR /tmp/permtest
```

Which prints:

```
/tmp/permtest:
total 12
drwxrwxr-x 2   2000 plyons 4096 May 30 22:41 group-rw-access-ok
drwxr-xr-x 2   2000   2000 4096 May 30 22:41 no-access-error
drwxr-xr-x 2 plyons plyons 4096 May 30 22:41 rw-access-ok

/tmp/permtest/group-rw-access-ok:
total 0
-rw-r--r-- 1 plyons plyons 0 May 30 22:41 file

/tmp/permtest/no-access-error:
total 0

/tmp/permtest/rw-access-ok:
total 0
-rw-r--r-- 1 plyons plyons 0 May 30 22:41 file
```

So if from your host OS you did:

```sh
sudo chgrp -R 1000 "${HOME}/.cache/yarn-offline-mirror"
sudo chmod g+rw "${HOME}/.cache/yarn-offline-mirror"
````

That should fix it. The node user in the container should be able to read/write to that cache directory during yarn installs.

**Comment by captnbli** [comment]
Did all that, and applied same to `/usr/local/src/reaction-app`

Attaching to reaction-next-starterkit_web_1
web_1  | yarn install v1.16.0
web_1  | warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error Could not write file "/usr/local/src/reaction-app/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/reaction-app/yarn-error.log'"
web_1  | error An unexpected error occurred: "https://registry.yarnpkg.com/brcast/-/brcast-3.0.1.tgz: EACCES: permission denied, open '/home/node/.cache/yarn-offline-mirror/brcast-3.0.1.tgz'".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Thanks for your help. However, I give up: I don't have days to spend to get a running system to evaluate the platform. It seems, by accident or design, the project has created a build/install environment that is full of fairly specific dependencies, and there even seems to be multiple dependency managers. All that makes the build/install process brittle, it seems.

Just a final thought, the node install instructions at https://github.com/nodejs/help/wiki/Installation do not mention creating a `node` user, which seems to be required here.
