### ISSUE TITLE
ENHANCEMENT: Live Chat Support (Package)

### ISSUE THREAD

**Issue by oneezy** [reactioncommerce/reaction#520]
It would be a great feature!

**Comment by spencern** [comment]
We've developed a package for zopim live chat that works pretty well. Haven't used it in production yet but it works for us in development - https://github.com/getoutfitted/reaction-zopim

**Comment by hbakhtiyor** [comment]
would be nice to add https://www.drift.com integration

**Comment by jshimko** [comment]
@hbakhtiyor Reaction already supports [Segment](segment.com) for analytics and other website integrations.  You could enable Segment and add any of the supported services they offer (Drift included)...

https://segment.com/catalog#integrations/livechat

**Comment by zenweasel** [comment]
Not currently on the roadmap, but we would welcome a plugin to add this feature.
