### ISSUE TITLE
Rename "optionTitle" to something more clear as to what it's purpose is

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5206]
I can't tell you how much time has been wasted and confusion caused because this field is poorly named. I don't know why it wasn't called `cartTitle` or `shortTitle` or something more clear in the first place but here we are.

**Comment by aldeed** [comment]
I don't know that `cartTitle` is 100% accurate either (the `title` becomes the cart item title), but `shortTitle` makes sense to me.

Related, in `CartItem`, I think it would make more sense if:
- `title` -> `productTitle`
- `optionTitle` deprecate it because it's in `attributes`
