### ISSUE TITLE
ENHANCEMENT: Pretty search results w/ Schema.org

### ISSUE THREAD

**Issue by oneezy** [reactioncommerce/reaction#521]
It would be great if [Schema.org](http://schema.org/) was integrated into Reaction Commerce! 

Here's an example of what that would look like:
![image](https://cloud.githubusercontent.com/assets/7369575/11165428/17571d38-8ad4-11e5-8369-20b92b8ca81f.png)

**Comment by mikemurray** [comment]
Addressing this as part of #515

**Comment by aaronjudd** [comment]
Closing - insufficient details.
