### ISSUE TITLE
simple-inventory and inventory plugin optimizations

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5215]
Two performance tweaks that should make updating simple-inventory faster:
- `updateSimpleInventory` calls `recalculateReservedSimpleInventory` only when an insert happened (product that hasn't had inventory stored yet). In this situation, `recalculateReservedSimpleInventory` emits "afterInventoryUpdate" and then `updateSimpleInventory` immediately emits that same event again. `updateSimpleInventory` function can rely on it being emitted by `recalculateReservedSimpleInventory` and skip emitting it for upserts.
- In the core `inventory` plugin, there is an `afterInventoryUpdate` appEvent listener. This does `Products.find` without a projection. I believe only the `_id`, `shopId`, and `ancestors` fields are ever used, so we can add a `projection` to that query to limit the data returned.

**Comment by rosshadden** [comment]
Solved in #5220.
