### ISSUE TITLE
Operator UI should load if no `storefrontURLs`

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#5217]
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
We're now throwing an error if the `storefrontURLs` haven't been set in a shop, however it's preventing the Operator UI to load. 

**Note:** I believe this is only happening if you've logged into the storefront as a shopper first and then try to log into the Operator as an admin.

## Steps to Reproduce
1. With a fresh RC create a "shopper" account in the Storefront (localhost:4000) and logout
2. From here load the Operator UI (localhost:3000) and login as an Admin
3. You should be met with a white screen and a reaction-error in the browser console about the `storefrontURLs` not being set.

## Possible Solution
It seems that the [Reaction.hasDashboardAccessForAnyShop()](https://github.com/reactioncommerce/reaction/blob/22bd646d57ff99738a28d25d987b345541b843e6/imports/plugins/core/layout/client/components/coreLayout.js#L41) method isn't returning true in this use case.

### Versions
`develop`

**Comment by mpaktiti** [comment]
Cannot be reproduced any longer. Tested both on `master` and `develop`.
