### ISSUE TITLE
Tag UI enhancements

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5218]
## Issue Description

There some UI issues with the tag editor that make it difficult to use for day-to-day operations.

1. ~~Tag filtering doesn't work. The filter applies after the query, so you will still have many pages to paginate through, but sometimes the pages will have fewer results.~~ Moved to #5224 
3. Adding tags to products is sometimes unclear whether the tag was added due to some UI hiccups.
4. There's no way to go directly to a tag from a product, and no way to go to a product from a tag.

## Possible Solution

1. ~~Explore using a regex search like is used in the product editor to find matches. This will admin only.~~ Moved to #5224 
2. Update the UI to be more clear when you are adding a tag
3. In the product admin. link the tags to their tag page. In the tag admin, link the products, directly to their product page in the admin

**Comment by kieckhafer** [comment]
Items 2 & 3 resolved here: https://github.com/reactioncommerce/reaction/pull/5223

**Comment by kieckhafer** [comment]
Closed issues in this PR via #5233

New issue, #5224, opened for the remaining issue listed in this ticket
