### ISSUE TITLE
Storefront PDP does not work on first load if Example Product hasn't been republished

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5219]
## Issue Description
When loading up the Storefront PDP for the first time, an error is shown:
![undefined___Reaction](https://user-images.githubusercontent.com/4482263/59709456-b39f8a80-91bb-11e9-99d2-882397caf16e.png)

This seems to stem from the Example Product not having the correct pricing data in the `Catalog` collection.

Once the product is published ( / re-published) via Catalyst, the error is no longer seen.

## Steps to Reproduce
- Start a fresh install of Reaction
- Go to the Storefront
- Click a PDP

## Possible Solution
Add price data to Example Product

**Comment by aldeed** [comment]
I modified this code in https://github.com/reactioncommerce/reaction/pull/5212 so I'll make sure this issue is fixed in that PR.

**Comment by aldeed** [comment]
Fix merged into develop
