### ISSUE TITLE
ENHANCEMENT: eCommerce API w/ Schema.io?

### ISSUE THREAD

**Issue by oneezy** [reactioncommerce/reaction#522]
I noticed that you guys are planning to create an API in the near future. [Schema.io](https://schema.io/) (created by [getFWD](http://getfwd.com/)) could be a good option for this! It's a ready-made eCommerce API that's built for Node. I think it would go really well with Reaction!

Here's a map view of [Schema's API](http://beta.dev.schema.io/docs/map)

**Comment by aaronjudd** [comment]
Thanks, I've looked at it a couple times, and will keep looking at it ;-) not sure if we can align up though, because their schema looks a little simpler than ours.
