### ISSUE TITLE
can't replace coreHead

### ISSUE THREAD

**Issue by maxlibin** [reactioncommerce/reaction#523]
in layout.js:
Template.testlayoutHeader.replaces("coreHead");
nothing happened.

**Comment by aaronjudd** [comment]
'coreHead'

**Comment by aaronjudd** [comment]
Sorry - didn't mean to close.  'coreHead' is the metaTags handler. if this is what you're looking to replace? I think you can just add your own head content outside of a template without replacing 'coreHead' and it should add to the head section.
```
<head>
  <title>title</title>
</head>
```

**Comment by jshimko** [comment]
That is correct.  You can add `<head>` tags anywhere in your app and Meteor will merge them with any others that already exist.

**Comment by maxlibin** [comment]
what about replacing 'layoutHeader'

**Comment by aaronjudd** [comment]
The `Template.myLayoutHeader.replaces('layoutHeader');` should work for that.

**Comment by maxlibin** [comment]
cool seems working, thanks guys.

**Comment by aaronjudd** [comment]
:+1:
