### ISSUE TITLE
About reaction-ui package

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#524]
Hello, @mikemurray, I'm glad you guys begin to move to react side. I've mentioned yesterday in chat about what I'm working on now. Please, take a look. [link](https://github.com/newsiberian/reaction-react). As you can see I'm making the copy of reaction blaze UI on react for some time.

I am thinking... you began to do something react'ish, I'm working on the same, but maybe from another side. I believe, it could be a clever step to somehow try to split our efforts, don't you think? For the begining we could just discuss it, if you interested, and maybe we could find some intersection points.

**Comment by aaronjudd** [comment]
@mikemurray is there anything we share / collaborate on here? @newsiberian does the current WIP take care of this sufficiently? Feedback is good.

**Comment by newsiberian** [comment]
@aaronjudd, I'm sorry, but I do not quite understand your question. It's too difficult combination of words for me;)

**Comment by aaronjudd** [comment]
@newsiberian just want to review this and close this issue if possible.
