### ISSUE TITLE
Update changelog.md for v2.0 official release

### ISSUE THREAD

**Issue by reaction-justin** [reactioncommerce/reaction#5256]
## Issue Description
Once Reaction v2.0 is officially released, the changelog.md text needs to be updated. @reaction-justin will provide a link to the approved Release Notes text in markdown format.

**Comment by reaction-justin** [comment]
Screenshots:

![Reaction-product](https://user-images.githubusercontent.com/42009003/60613775-6d802480-9d80-11e9-86b5-a1683732ee3f.png)

![Reaction-product-variant](https://user-images.githubusercontent.com/42009003/60613799-72dd6f00-9d80-11e9-9012-ca59f509e5e3.png)

**Comment by reaction-justin** [comment]
@jeffcorpuz Here's the text in markdown - let me know if you have any issues copying & pasting from GDocs https://docs.google.com/document/d/1T5MsKDGoFLPPiW7DfMAJxkgjNDazcYbBw7MNuDz7MgM/edit?usp=sharing

**Comment by spencern** [comment]
Closing - we did this in #5277
