### ISSUE TITLE
Update readme.md for v2.0 official release

### ISSUE THREAD

**Issue by reaction-justin** [reactioncommerce/reaction#5257]
## Issue Description
Once Reaction v2.0 is officially released, the related Readme file needs to be updated to reflect that. @reaction-justin will provide a link to the approved Readme text in markdown format.

**Comment by reaction-justin** [comment]
Screenshot - 

![3-up Catalyst UI lg](https://user-images.githubusercontent.com/42009003/60614171-4118d800-9d81-11e9-8bfd-d9b67a361459.png)

**Comment by reaction-justin** [comment]
@willopez Here's the text in markdown - let me know if you have any issues copying and pasting from GDocs.
https://docs.google.com/document/d/15QVGv33-OUJtp_tjGIOs5oXLDcxTVPCHhdMDndLMM-k/edit?usp=sharing

**Comment by willopez** [comment]
Thanks Justin, I already have a PR opened to update the screenshot here: https://github.com/reactioncommerce/reaction/pull/5254.

**Comment by reaction-justin** [comment]
> Thanks Justin, I already have a PR opened to update the screenshot here: #5254.

OK sounds good, I just included here since the Readme text has all been revised as well.

**Comment by willopez** [comment]
@reaction-justin README and screenshot PR created: https://github.com/reactioncommerce/reaction/pull/5254

**Comment by reaction-justin** [comment]
👍 Closing in favor of  #5277
