### ISSUE TITLE
Update various repo descriptions for v2.0 release

### ISSUE THREAD

**Issue by reaction-justin** [reactioncommerce/reaction#5258]
## Issue Description
Several Reaction repos need updated description text. The official release of v2.0 seems like a good time to make these updates. Updated description text can be found here:
https://www.notion.so/reactioncommerce/Reaction-Commerce-README-f814cf25f77846cc93593277c68c03da

**Comment by machikoyasuda** [comment]
@spencern I don't have sufficient GitHub permissions to update the descriptions. Can you do it?

**Comment by machikoyasuda** [comment]
I updated the `reaction-docs` description text. Thank you Justin!

**Comment by machikoyasuda** [comment]
this is done.

**Comment by spencern** [comment]
I've updated the descriptions for the repos that were locked as well. Thanks @machikoyasuda and @reaction-justin
