### ISSUE TITLE
Going from one product to another causes app to crash

### ISSUE THREAD

**Issue by matigda** [reactioncommerce/reaction#5263]
## Prerequisites
* [x] Are you running the latest version? ( I'm using develop branch )
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When I run reaction right now and try to go from one product to home page and then to the other product - it's throwing error. It is caused by VariantList component. In the 93rd line there is wrong condition. I didn't go deeper, just commented 94th line and it's working now

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Start reaction
2. Go to homepage
3. Go to product
4. Go back to home page
5. Go to other product

### Versions
"version": "2.0.0-rc.12" ( not sure if it is all you need ? )

**Comment by spencern** [comment]
Thanks for the report @matigda 
We're you running this with your own products? Did you migrate from an older version of Reaction?

**Comment by willopez** [comment]
@matigda did you load the sample catalog data? or did you create a product using the Catalyst UI, if so did you add an option to the product?

**Comment by spencern** [comment]
Should be closed by reactioncommerce/example-storefront#552
