### ISSUE TITLE
User documents are automatically being deleted from users collection

### ISSUE THREAD

**Issue by umeshrs** [reactioncommerce/reaction#527]
I have two meteor apps running on my system (reaction and foo on ports 3000 and 4000 respectively). I'm trying to register new users on the reaction app from the foo app using `DDP.conenct()` . To accomplish this, I defined a method called `addUser` inside the server folder of the reaction app as shown below. I did this because I could not find any other inbuilt method that was dedicated to user creation in the reaction app as well as reaction-accounts app.  

    Meteor.methods({
      addUser: function (options) {
        check(options, {
          username: String,
          password: {
            digest: String,
            algorithm: "sha-256"
          },
          email: String
        });

        Accounts.createUser({
          username: options.username,
          password: options.password,
          email: options.email
        });
      }
    });

In my foo app, I connected to the reaction app and invoked the `addUser` method as follows -

    var reactionConnection = DDP.connect("http://" + REACTION_DOMAIN + ":" + REACTION_PORT);
    reactionConnection.call("addUser", {
      username: "test1",
      password: Accounts._hashPassword("test123"),
      email: "test1@test.com",
    }, function (error, result) {
      if (error) {
        console.log("Error creating new user in reaction instance: ", error.message);
      } else {
        console.log("New user added to reaction instance.");
      }
    });

I created some more users `test2`, `test3` and `test4`. I got a success message after running the above code and when I examined reaction's database, I was able to see these new users added to the users collection. 

I opened the reaction app in my browser and tried logging in as each of the above users. I was able to successfully log in and log out of the app. There is no problem when I try to login the first time. 

The problem occurs when I try to login the **second time**. When I log in as `test1` for the second time, I noticed that another user's document is deleted from the users collection. Sometimes a single user's document is deleted and sometimes multiple documents are deleted. I noticed that when no user is logged in, a guest user account (without username, password and email) is created in the user's collection. The users that I created were getting deleted with some of these "guest" user accounts.

I don't understand why existing user documents (with username, password and email) are being deleted like this. Is this a bug or am I doing something wrong? If it is the latter, can you please suggest the best way to register new users on reaction app from *another* meteor app? 

Also, I noticed that I repeatedly get the following exception in my server console. I'm not sure if this has anything to do with user documents being deleted.

![reaction_error](https://cloud.githubusercontent.com/assets/13485325/11318483/26b0de4e-907a-11e5-99b8-21ccb1450b89.png)

I would really appreciate any help regarding this issue. Thank you in advance.

**Comment by aaronjudd** [comment]
See #494, the development branch has the offending code commented out.

**Comment by aaronjudd** [comment]
This should now be resolved in #494 as well as other related cart workflow issues #536 #650 #692.

**Comment by umeshrs** [comment]
I have tested the latest release and I am not encountering this bug anymore. Thank you for resolving this issue :)
