### ISSUE TITLE
multi-select and sidebar get out of sync 

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#528]
The sidebar and product grid contents selected by multi-select get out of sync.  Route change and back reliably replicates this.  I think expected behavior would be to either keep the selection and reload the side bar to match (preferable), or lose the selection and close the sidebar.

![reaction___products](https://cloud.githubusercontent.com/assets/439959/11321474/bb58cd18-9075-11e5-9e98-a0a9c29da6d6.png)
![reaction___products](https://cloud.githubusercontent.com/assets/439959/11321475/cba34ca2-9075-11e5-83da-60a5cdc304a0.png)

You are also unable to deselect (without shift-clicking each item).

**Comment by mikemurray** [comment]
Fixed in development
