### ISSUE TITLE
Deploy-docs step fails consistently during CI

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#5286]
## Summary
Our CI is reporting failure due to the `deploy-docs` step that happens when our `master` branch is updated. If we still rely on this step to deploy docs, let's fix this. If we don't, let's eliminate it please. I'd like Circle to report success for our `master` branch. Our CI process should give us and people looking at our projects confidence that the tests are passing and the project is maintained. 

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/1203639/60830872-69d01180-a175-11e9-84ab-d624cf72bf79.png">

```
Generating output files...
Finished running in 9.28 seconds.
Exited with code 1
```

**Comment by spencern** [comment]
@machikoyasuda do you know if we're still relying on this step for our documentation to stay up-to-date?

**Comment by machikoyasuda** [comment]
There must be a JSDoc that is not compiling correctly: https://app.circleci.com/jobs/github/reactioncommerce/reaction/47338 

The `deploy-docs` step builds this site: http://api.docs.reactioncommerce.com/ and if there's any JSDoc comment that causes the compile step to break, the job will fail.

**Comment by spencern** [comment]
Thanks. Lemme rerun via SSH and see if it will tell me what's broken

**Comment by spencern** [comment]
Interestingly - when running via SSH I was able to deploy the docs with no errors. 🤔

**Comment by spencern** [comment]
Building the docs connected via SSH returns `0`
```
circleci@4027eeda8d7e:~/reaction-app$ echo "$?"
0
```

**Comment by spencern** [comment]
Annnd. I think I found it. 
https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/product-admin/client/hocs/withVariant.js#L109

Fix incoming if it's what I suspect

**Comment by machikoyasuda** [comment]
@spencern Good catch!!

**Comment by aldeed** [comment]
I'd like to keep this and also have merges to `develop` deploy to a different bucket+url. Both should be linked to from the main docs site. Eventually we can roll this into the overall pattern for keeping versioned docs in each repo `/docs`.
