### ISSUE TITLE
De-Meteorize job control system

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction#5288]
This is part of the [EPIC Moving the API off Meteor](#4996). This issue is about de-meteorizing the background job system. Here are some initial notes I put together.

## How background jobs currently work in reaction

- Reaction includes a plugin (`imports/plugins/included/jobcontrol`) implementing job control
- `imports/utils/jobs` implements a job server and a job queue based on `@reactioncommerce/job-queue` which has a JobQueue class
  - This adds an event handler for meteor startup so the job server starts after meteor starts
- When the job server starts, some base jobs are scheduled
  - `jobControl/removeStaleJobs` runs daily
- `@reactioncommerce/job-queue` also includes our OpenExchangRates scraper job
  - Why?
- `@reactioncommerce/job-queue` has the base API and implementation
  - The API is medium sized, at least a dozen methods
  - Do we need to port all of these and maintain compatibility? (I presume yes)
  - Can we do this in a branch and convert off meteor
    - control flow with `async`/`await` instead of fibers
    - pure mongo collections instead of meteor ones
    - js `setTimeout` instead of `Meteor.setTimeout`
    - plain `Error` instead of `Meteor.error`

- There are 12 core or included plugins that use jobs
  - Note: presumably if none of these files imported `/imports/utils/jobs`, the job server would never install the meteor startup hook and thus never start.

## core & included plugins that use jobs

```
imports/plugins/included/jobcontrol/server/jobs/cleanup.js
imports/plugins/included/jobcontrol/server/jobs/exchangerates.js
imports/plugins/included/sitemap-generator/server/jobs/generate-sitemaps-job.js
imports/plugins/core/email/client/containers/emailLogs.js
imports/plugins/core/email/client/components/emailLogs.js
imports/plugins/core/email/server/methods/retryFailed.js
imports/plugins/core/core/server/startup/collection-security.js
imports/plugins/core/core/server/publications/email.js
imports/plugins/included/sitemap-generator/server/no-meteor/mutations/generateSitemaps.js
imports/plugins/core/email/server/no-meteor/util/processEmailJobs.js
imports/plugins/core/email/server/no-meteor/mutations/sendEmail.js
imports/plugins/core/core/server/methods/shop/updateShopExternalServices.js
```

**Comment by zenweasel** [comment]
The exchange rates job is in the job queue directory because originally that was the only background job that we ran and originally we were just going to put all jobs in that one dir before we were really doing discreet plugins. So it could be moved somewhere else that's more localized.

In addition I think multi-currency support is a feature that got lost in the move to 2.0 so I don't even know that that provides any value any more.

**Comment by focusaurus** [comment]
Note to self from Eric D: mongodb 3.6+ has change streams available as a potential alternative replacement for meteor `.observe()` (oplog tailing).
