### ISSUE TITLE
Redirect graphql-alpha to graphql-beta

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction#5293]
Developers have bookmarks, tools like postman, muscle memory around /graphql-alpha being where you go for graphql and graphiql. Please add a redirect to the new URL so developers don't hit a dead end.

**Comment by HarisSpahija** [comment]
I would like to try this one if you guys dont mind!

**Comment by focusaurus** [comment]
Here's some very rough high-level guidance. There's still a lot of details you'll need to fill in.

- Have a look at an integration test to understand how they create, start, and stop a `TestApp` instance: `tests/integration/api/mutations/updateOrderFulfillmentGroup/updateOrderFulfillmentGroup.test.js`
- Set up a similar integration test
- You may need to add a method so a test can ask the TestApp instance for it's URL
- Send an HTTP request to `${TEST_APP_BASE_URL}/graphql-alpha` and assert you get the expected response code and `Location` header.

**Comment by HarisSpahija** [comment]
This issue was solved in #5586
