### ISSUE TITLE
Wrong template reference for coreOrderShippingSummary and coreOrderShippingInvoice

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#5300]
## Issue Description
In migration [54_template_name_updates](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/versions/server/migrations/54_template_name_updates.js) the template `coreOrderShippingSummary` was changed to `OrderSummary` and `coreOrderShippingInvoice` was changed to `OrderInvoice`.

The orders plugin however still registers the old templates:
https://github.com/reactioncommerce/reaction/blob/185afb39dd633ec4ef5fece45a620ed49a6bbd35/imports/plugins/core/orders/server/no-meteor/register.js#L138
https://github.com/reactioncommerce/reaction/blob/185afb39dd633ec4ef5fece45a620ed49a6bbd35/imports/plugins/core/orders/server/no-meteor/register.js#L143

Everytime now that register.js file is avaluated again the tempalte is set to the old templates, resulting in errors thrown on the orders view.

Therefore, viewing and processing orders is currently broken in v2.0.0.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create Order
2. Visit your Order in the Operator
3. Observe that the relevant templates are missing, and the console throws an error.

## Possible Solution
Until the new orders panel is complete, fix [imports/plugins/core/orders/server/no-meteor/register.js](https://github.com/reactioncommerce/reaction/blob/develop/imports/plugins/core/orders/server/no-meteor/register.js) to register the correct panel.

### Versions
v2.0.0

**Comment by aldeed** [comment]
Fix was merged in `develop`
