### ISSUE TITLE
`simpl-schema` validate() method is slow on large payloads

### ISSUE THREAD

**Issue by alex-haproff** [reactioncommerce/reaction#5305]
## Prerequisites
* [✔ ] Are you running the latest version?
* [✔ ] Are you able to consistently reproduce the issue?
* [✔ ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Having spent some time analysing the response time of the GraphQL endpoint, particularly for the PLPs, I've come across an interesting issue with using `simpl-schema` validate method. Particularly here https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/inventory/server/no-meteor/queries/inventoryForProductConfigurations.js#L102 and here https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/inventory/server/no-meteor/queries/inventoryForProductConfigurations.js#L155. A single call to `validate` method with a moderately sized object takes ~40ms. This is not insignificant, as replacing `simpl-schema` validation with a custom one takes it down to ~2ms per call on a similar-sized payload, with the same validation rules. Considering this method gets called 10s of times per request it quickly adds up. I was able to shave off a few hundred ms on average with a custom validator.
Would be good to get @aldeed input on this as well as he authored `simpl-schema` module.

## Possible Solution
Implement custom validators to use in `inventoryForProductConfigurations()` method.

**Comment by aldeed** [comment]
Discussed this with @alex-haproff elsewhere but putting here for public visibility:

I did quite a bit of work to optimize SimpleSchema validate a couple years ago, so there is no low hanging fruit that I know of. The slowness comes from the fact that it is written in such a way as to understand and validate Mongo update objects. The remaining solution to fully optimize it is to write a different smaller validator for non-modifier objects, which would support fewer validation rules.

But as far as validating `pluginResultSchema`, the main idea there was just to ensure each array item has the correct fields with the correct data types. So I’m thinking maybe we just write a custom function to do that?

**Comment by aldeed** [comment]
Fix merged into develop
