### ISSUE TITLE
Emails do not work on rc 2.0.0

### ISSUE THREAD

**Issue by jm18457** [reactioncommerce/reaction#5312]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issues?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
No emails are sent.
[shopId is sent through inner field data](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/email/server/no-meteor/mutations/sendEmail.js#L66) but destructured as it is first field [renderEmail.js](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/email-templates/server/mutations/renderEmail.js#L14)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Start reaction
2. Make any event that causes email to be sent, such as reset password, order notification etc.
3. In reaction console logs you will receive error message saying example "No email template found for language en"

## Possible Solution
Do not destructure shopId and user `data.shopId`.

[changes](https://github.com/voyego/reaction/pull/3/commits/2555d6f8e7233cbb0fcaf25cb82ffc5681cc03a4)

**Comment by aldeed** [comment]
This does look wrong in the code but I know emails were working for people who tested 2.0.0 release, so there must be some configuration difference that masks the bug. Either way, we should fix it.
