### ISSUE TITLE
DataLoaders are not present in ETL consumer context

### ISSUE THREAD

**Issue by alex-haproff** [reactioncommerce/reaction#5313]
## Issue Description
I've recently introduced DataLoaders to reduce number of DB calls and improve performance of GraphQL endpoint. However, I've missed one very important use case when Reaction app is being ran as a consumer of a Kafka topic, and not a web request. This causes an error discovered by @focusaurus:
`{
  "hostname": "***********************************",
  "level": 50,
  "msg": "Error in \"afterInventoryUpdate\" consumer TypeError: Cannot read property 'SimpleInventoryByProductVariantId' of undefined\n    at Promise.asyncApply (imports/plugins/included/simple-inventory/server/no-meteor/utils/inventoryForProductConfigurations.js:22:31)\n    at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at Promise.asyncApply (imports/plugins/core/inventory/server/no-meteor/queries/inventoryForProductConfigurations.js:99:24)\n    at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at Promise.asyncApply (imports/plugins/core/inventory/server/no-meteor/queries/inventoryForProductConfigurations.js:174:16)\n    at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at Promise.asyncApply (imports/plugins/core/inventory/server/no-meteor/utils/startup.js:25:33)\n    at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at Promise.asyncApply (imports/node-app/core/util/appEvents.js:24:5)\n    at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40",
  "name": "Reaction",
  "pid": 1,
  "time": "2019-07-11T23:36:43.994Z",
  "v": 0
}`

## Steps to Reproduce
Run any of the consumers that update inventory information.

## Possible Solution
As DataLoaders are supposed to exist within the context of the web request, the best solution would be to fallback to Mongo collection to query inventory. Generally, DataLoaders are not designed to be used outside of web requests.
I've investigated and it seems we have a flag set -`isInternalCall`, which is relied upon in other parts of the application, like here for instance `imports/plugins/core/catalog/server/no-meteor/mutations/publishProducts.js`.

**Comment by aldeed** [comment]
Fix was merged to `develop` but not yet released.
