### ISSUE TITLE
Flakey CI timeout failures

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction#5315]
Our CI tests have flakey intermittent timeout failures. Most recently https://circleci.com/gh/reactioncommerce/reaction/48337

I believe this should be solvable in a good way we just need to dig in and work the problem. Will put this issue into the DevX pod backlog.

**Comment by focusaurus** [comment]
Comment from @mikemurray in slack:

> Maybe this test needs to be wrapped in a `Reaction.whenAppInstanceReady(() => { /* tests */ })`.

**Comment by kieckhafer** [comment]
Hate this error, happy to look into it.

**Comment by aldeed** [comment]
@mikemurray Is correct that first step should be to make sure all tests in every `app-test` file are wrapped in `Reaction.whenAppInstanceReady`.

Someone can also look through all the test files and remove any tests that are testing things that are no longer used. There may be some Meteor methods that client code no longer calls, which can be removed along with their Meteor tests.

**Comment by kieckhafer** [comment]
@aldeed Should the whole file be wrapped, or each individual test?

https://github.com/reactioncommerce/reaction/blob/ref-kieckhafer-ordersUiWithMultipleFulfillmentGroups/imports/plugins/core/core/server/util/connectionDataStore.app-test.js#L5

I'd wrap starting on line 5 here?

**Comment by machikoyasuda** [comment]
- https://github.com/reactioncommerce/reaction/issues/5246
related issue

**Comment by kieckhafer** [comment]
Resolved in #5317
