### ISSUE TITLE
Stripe API tokens provided in Operator UI do not work

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5325]
## Issue Description
API tokens provided in the Payments page of the Operator UI are not read. Instead, it seems like the field `STRIPE_PUBLIC_API_KEY` in the `env` file is the only one being read. I think this because the default in the `env.example` is `CHANGE_ME`, and that’s the value showing up in the error message

## Steps to Reproduce
1. Start Reaction WITHOUT the `STRIPE_PUBLIC_API_KEY` set in the `env` file
1. Add stripe keys into Operator UI
1. See error on `xsf` when trying to pay with a stripe card: `POST https://api.stripe.com/v1/tokens 401`

## Possible Solution
Make sure Operator UI provided API tokens override `env` provided tokens

**Comment by aldeed** [comment]
Only ENV should be used for security. The plan was to remove the field from UI but apparently that didn't happen.

**Comment by kieckhafer** [comment]
I'm still having some issues, it seems to accept the tokens, but this error message shows when trying to create an order:

![Checkout___Reaction](https://user-images.githubusercontent.com/4482263/61570453-78ee7380-aa41-11e9-8d27-5ba34f4904ca.png)

The blurred part isn't the API token, but it's `tok_xxxxxxxxxxxxxxxxxxxxxxxx`
