### ISSUE TITLE
Cart subscription not flush on user login/logout

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#536]
Hello, seems there is a bug with it.
How to reproduce:
1 way:
* before log in: leave a breakpoint somewhere on line 10 in cartDrawer.js;
* on breakpoint, type: `ReactionCore.Subscriptions.Cart.subscriptionId` in console;
* log in as admin and on breakpoint type again step 2;
* then log out and repeat step 2;
In my case every time `subscriptionId` was same;

2 way:
* before log in: leave a breakpoint somewhere on line 10 in cartDrawer.js;
* log in as admin and on breakpoint type: `Cart.findOne()`
* logout and on breakpoint type `Cart.findOne()` again.
In my case I see admin cart after logout.

**Comment by aaronjudd** [comment]
I believe this is resolved with #650, #636, #536.  We should re-open if necessary. I'm not able to duplicate now though.
