### ISSUE TITLE
Can't start GraphQL API (installation/initialization issue)

### ISSUE THREAD

**Issue by mauber91** [reactioncommerce/reaction#5361]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I was about to get started with Reaction Commerce following the installation steps (https://docs.reactioncommerce.com/docs/installation-reaction-platform) on macOS Sierra 10.12.6. The 'make' command build seemed to have went well with no apparent issues of errors as far as I could tell, and all containers were running as the installation guide shows. But after waiting some time for the app to get running once I hit localhost:4000 it just didn't load anything. Taking a look at the logs it showed me this:

![image](https://user-images.githubusercontent.com/53238425/61888872-f5fa6c80-aec9-11e9-8b5f-bfa8fa71f5fa.png)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. git clone
2. run "make" command
3. try to load localhost:4000

### Versions
2.0.0

Please let me know if there is any other data or info that I could provide to help solving this issue

**Comment by aldeed** [comment]
Most likely this was a temporary issue or has since been fixed. If anyone sees something similar, please submit a new issue.
