### ISSUE TITLE
How to add a currency? I a custom one.

### ISSUE THREAD

**Issue by assiomatica** [reactioncommerce/reaction#538]
Hi ,
I have seen the are in the Shops.json file, but how to reload only currencies?

THank YOu

**Comment by aaronjudd** [comment]
In the latest development branch: to persist, you can make your own `reaction-sample-data` and modify Shops.json or import your own using `ReactionImport`.

**Comment by assiomatica** [comment]
Perfect! Thank you.

Antonio Casula

mobile ch   +41 (0)79 9692274

   - ch.linkedin.com/in/antoniocasula/
   <https://mailtrack.io/trace/link/81d0859823098156b6c647708ae374b72da98f88?url=http%3A%2F%2Fch.linkedin.com%2Fin%2Fantoniocasula%2F&signature=a9183062006d1a90>
