### ISSUE TITLE
Bulk Tag/Product Feature: Back-end bulk action API

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#5384]
**New API: CSV parser + Bulk add/remove Tags from Products -**

- Mutations for bulk operations for adding/removing tags from products
- Live in the `core/products` plugin

1. Upload a .csv file to browser. (doesn't need to be saved to the server)
    1. Using some npm module for .csv parsing
2. Parse CSV file for product IDs
3. Send the list of Product IDs to the server to the bulk operation mutation as the input with the tags to apply to those products
    1. API should accept multiple product ids (for not the ui only has to support uploading one file for phase 1)
    2. API accept multiple tags ids (for now the ui only has to support one for phase 1)
    3. Support adding and removing tags form the products
4. Apply tags to products using mongo bulk operations
    1. Product have a `hashtags` field
        1. Array of ids
    2. Mongo `addToSet` if there's a bulk op for that
        1. `addToSet` can accept an array
        2. Reaction bulk example: imports/plugins/core/versions/server/no-meteor/util/findAndConvertInBatches.js
        3. [https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#bulkwrite-write-operations-updateonemany](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#bulkwrite-write-operations-updateonemany)

            bulk.find({
              _id: $in: [ /* array of product ids */]
            }).update({
              $addToSet: {
                hashtags: {
                  $each: [/* the tags */]
                }
              }
            });

**Comment by focusaurus** [comment]
Not sure if this is the right issue but @willopez based on your demo, I'd like to request instead of having a list of string operation names like `["BULK_ADD_TAGS", "BULK_DELETE"]` we make each of these a first-class named graphql mutation with fully-specified arguments names and types.

**Comment by willopez** [comment]
@Pete noted, after some thought, it would make for a cleaner API, will make them first class GraphQL mutations.
