### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by slepit** [reactioncommerce/reaction#539]
Hello,

I just downloaded the project and launch it with the meteor command. I get the following error:

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: Conflict: Constraint reactioncommerce:core@0.9.5 is not satisfied by
   reactioncommerce:core 0.9.2.
   Constraints on package "reactioncommerce:core":
   * reactioncommerce:core@0.9.2 <- reactioncommerce:reaction-accounts 1.5.1
   * reactioncommerce:core@0.9.5 <- reactioncommerce:reaction-inventory 0.1.0
   * reactioncommerce:core@0.9.2 <- reactioncommerce:reaction-shipping 0.6.1
   * reactioncommerce:core@0.9.2 <- reactioncommerce:reaction-analytics 1.2.0
   * reactioncommerce:core@0.9.2 <- reactioncommerce:reaction-social 0.4.1
   * reactioncommerce:core@0.9.2 <- reactioncommerce:reaction-paypal 1.2.3
   * reactioncommerce:core@0.9.2 <- reactioncommerce:reaction-stripe 3.0.1

I am on windows but do not think this matters.

thanks,

**Comment by aaronjudd** [comment]
I'd recommend switching to the `development` branch and using `reaction pull` to get all the local packages.  that should get you in synch with all the current stuff (and 0.10.0 will be released soon anyways).
