### ISSUE TITLE
Account scheme

### ISSUE THREAD

**Issue by github4f** [reactioncommerce/reaction#540]
Could you please let me know where is "Account scheme". I cannot find it in "reactions scheme" folder. Tnx

**Comment by aaronjudd** [comment]
In the latest `development` branch, you'll find schemas in https://github.com/reactioncommerce/reaction/tree/development/packages/reaction-schemas

Docs have been updated as well https://github.com/reactioncommerce/reaction/blob/development/docs/developer/schema.md

But this needs more work.
