### ISSUE TITLE
RestAPI

### ISSUE THREAD

**Issue by github4f** [reactioncommerce/reaction#541]
Is there any RESTAPI. I would like to develop and ios app with reaction as the backend. So I am looking for a way to connect the front-end to the back-end!

**Comment by aaronjudd** [comment]
Follow up from https://gitter.im/reactioncommerce/reaction?at=5662ce3fd2a5a7813cd45e3c

 I’d recommend using DDP if you can, there is an IOS library for https://github.com/boundsj/ObjectiveDDP, but you can package your own REST endpoints using https://github.com/kahmali/meteor-restivus.

**Comment by mikemurray** [comment]
Theres https://github.com/martijnwalraven/meteor-ios for DDP as well.

**Comment by aaronjudd** [comment]
For a more recent update on REST API see: https://blog.reactioncommerce.com/our-take-on-rest-apis/

I am closing this issue, but expect we'll address in a documentation task soon.
