### ISSUE TITLE
Not able to publish product

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#5414]
## Issue Description
When creating a new product, I am unable to publish it.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Start Reaction in latest develop
2. Create a new product and enable inventory tracking for an option
3. Attempt to publish product

Generates the following error:
```
Error in "afterInventoryUpdate" consumer TypeError: Cannot destructure property `product` of 'undefined' or 'null'.
reaction_1  |       at Promise.asyncApply (imports/plugins/core/catalog/server/no-meteor/mutations/partialProductPublish.js:9:88)
```
Scenario 2.
1. Start Reaction on latest develop
2. Create a new product and do NOT enable inventory tracking for variant nor option
3. Attempt to publish product

Generates the following error:
```
Exception while invoking method 'catalog/publish/products' Error: Input passed into "inventoryForProductConfigurations" was invalid: inventoryInputInvalidPropertyValue[productConfigurations]
reaction_1  |     at Promise.asyncApply (imports/plugins/core/inventory/server/no-meteor/queries/inventoryForProductConfigurations.js:120:11)
```

## Possible Solution
Before calling the new partial publish function, it's necessary to ensure that inventory tracking is actually enabled. Further, do not publish inventory props when inventory tracking is NOT enable. 

Just my quick thoughts, might be the solution, might not be.

**Comment by impactmass** [comment]
cc @aldeed @kieckhafer

**Comment by kieckhafer** [comment]
I actually don't think this is _directly_ inventory's fault.

It seems the root of the issue here is on this line: https://github.com/reactioncommerce/reaction/blob/develop/imports/plugins/core/catalog/server/no-meteor/mutations/partialProductPublish.js#L12

Because this is a new product, it hasn't yet been published to the Catalog, so that's why `catalogItem` returns no data, because it doesn't exist.

Possible solution, on `line 13`: 
`if (!catalogProduct) return;` to kill this process if it hasn't been published yet.

I'm not sure the overall consequences of that throughout other packages, but I'd start there.

**Comment by aldeed** [comment]
Yes, this was an oversight by Nat and I when we made `partialProductPublish`. I agree with @kieckhafer about how to fix. It would be a good idea to fix this in release-2.1.0 branch before that is released.

**Comment by willopez** [comment]
After some more research, the root issue is caused by attempting to publish a new product without setting a product its variants + options to be visible. If variants or products are not set to be visible, the publish function fails and the user is not notified regarding invisible variants + options. Guard login needs to be added to check for input to include variants or variants + options before attempting to publish.

**Comment by aldeed** [comment]
Pretty sure the fix @kieckhafer mentions is also needed, though, if you update any inventory fields before publishing for the first time.

**Comment by willopez** [comment]
@aldeed Yes, the checks @kieckhafer suggested are needed.

**Comment by willopez** [comment]
Resolved in https://github.com/reactioncommerce/reaction/pull/5433
