### ISSUE TITLE
Admin Sidebar UX Improvements

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#542]
There are a number of UX issues with the current implementation of the admin sidebar. 

With this I hope to improve the following
- easy of use
- consistency
- reliability
- keep open while signed in as admin (open, but smaller)

**Comment by aaronjudd** [comment]
<img width="1163" alt="reaction___example_product_and_slack" src="https://cloud.githubusercontent.com/assets/439959/11646263/10a0654a-9d11-11e5-91bd-d23bb3f5e0a9.png">

See logic in the current "createProduct" event handling of the dropdown.

**Comment by newsiberian** [comment]
Hi, I'd like the idea to make an additionally `createProduct` functionality like in browsers `speed dial` addons. For example take a look at Opera window:
![new_product](https://cloud.githubusercontent.com/assets/11130487/11647710/3ad22ee4-9d8d-11e5-923d-d7dcd15bf58a.png)
What if we move this `card` to the top left corner. It always will be "here" - ready to hand.

**Comment by aaronjudd** [comment]
@newsiberian :+1:  had discussed exactly this with @mikemurray  for this ticket.... so if you don't use the `sample-data` package, you'd just have that "+ product" card.

**Comment by mikemurray** [comment]
Fixed in development
