### ISSUE TITLE
Unable to check out properly

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction#5423]
## Issue Description
When checking out, a graphql error results from `placeOrder` mutation becuase `order.payments` returns as `null`.

## Steps to Reproduce
1. Check out and see that the order will be placed but there is a graphql error message.

## Possible Solution
Looking into this, there are 2 problems that need to be addressed:
1. Line below should probably `await Promise.all` else it will return a promise.
 https://github.com/reactioncommerce/reaction/blob/7c2a0ef0836c6ea911f9a9088c64b4461e41605f/imports/plugins/core/orders/server/no-meteor/resolvers/Order/payments.js#L14

2. Below line inhibits guests to checkout. I think this needs some redesigning.

https://github.com/reactioncommerce/reaction/blob/7c2a0ef0836c6ea911f9a9088c64b4461e41605f/imports/plugins/core/orders/server/no-meteor/queries/refundsByPaymentId.js#L21

**Comment by kieckhafer** [comment]
@ajporlante I believe this is fixed here: https://github.com/reactioncommerce/reaction/pull/5422

**Comment by ajporlante** [comment]
@kieckhafer Agreed.
