### ISSUE TITLE
Create process docs for using and developing for Catalyst 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#5443]
We need to create some documentation for how to use Catalyst Design System and Reaction admin to make the process seamless, consistent and clear. We need the following documentation. 

**Docs needed -** 

- [ ] 1. How to build and document a component (persona - Reaction client side devs) 
- [ ] 2. How to use a component in Reaction Admin (persona - Reaction dev is building adding new UI feature or flow) 
- [ ] 3. How to make Admin plugin UI (persona - customer dev building a custom UI for their project or wanting to contribute to Reaction Admin) 
- [ ] 4. For catalyst.reactioncommerce.com Intro to Catalyst covering what it is and who it's for.

**Comment by rymorgan** [comment]
@machikoyasuda Thinking about this more, the first step here is to compile from existing docs. I have notes for 4. @mikemurray has notes for 1. and 2., and @nnnnat Has notes for 3. I think if we compile and edit them down at least have drafts.

**Comment by rymorgan** [comment]
@machikoyasuda @reaction-justin I have a draft of #4 on this list here - would love edits/comments. 
https://www.notion.so/reactioncommerce/About-Catalyst-Design-System-8272c97d54e84f4d815fe0bb6d4705d8

**Comment by machikoyasuda** [comment]
Issue moved to [reactioncommerce/catalyst #81](https://github.com/reactioncommerce/catalyst/issues/81) via [**ZenHub**](https://www.zenhub.com/)
