### ISSUE TITLE
Catalyst: Split Button (new)

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#5446]
https://material-ui.com/components/buttons/#split-button

<img width="352" alt="Screen Shot 2019-08-13 at 10 25 59 AM" src="https://user-images.githubusercontent.com/3673236/62962914-c77afd80-bdb4-11e9-8c55-d06d91e32db3.png">
<img width="353" alt="Screen Shot 2019-08-13 at 10 25 55 AM" src="https://user-images.githubusercontent.com/3673236/62962915-c77afd80-bdb4-11e9-9858-3a2adfd3c6d4.png">

**Comment by mikemurray** [comment]
Added in version Catalyst 1.5.0 https://github.com/reactioncommerce/catalyst/releases
