### ISSUE TITLE
Navigation should gracefully handle No Data

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5495]
This may have been fixed in new code, just transferring this issue from a customer repo.

Currently if there are no Navigation items the server throws an error and there is a white screen of death. Between the front-end and the backend it should handle this error gracefully rather than just crashing.

**Comment by aldeed** [comment]
@zenweasel Do you know whether WSOD is referring to Reaction Admin or storefront UI?

**Comment by aldeed** [comment]
I fixed this in Reaction Admin 3.0 recently
