### ISSUE TITLE
Password validation issues

### ISSUE THREAD

**Issue by Sabst** [reactioncommerce/reaction#551]
Hi,

I got stuck on password validation as I had the bad idea to use uppercase characters (currently considered as invalid characters)!

BTW, if the rule is: *Password must contain at least one number or symbol*, is it correct that "symbol"-only or number-only strings are rejected?
What is a symbol exactly (using \w or \W metacharacters, underscore is alphanumeric)?
There might also be a concern with non-latin languages (a-z in those languages?).

So maybe the validation regexp should only check for the presence of at least one number or symbol (including underscore)... or even simpler, validation should only check the string length.

Here is a small unit test that might help (to be completed with more complex combinations, if needed).

Cheers.

```
/* TODO: move this test to reaction-accounts package when sub-package
         tests are taken into account...
         for now this can be put in toplevel tests */

describe("Password validation", function () {

  // As of 7-DEC-2015, validation rules are:
  // - Password must be at least 6 characters long.
  // - Password must contain at least one number or symbol
  // The other rules seen in localization files (pwOneDigit, pwOneLetter)
  // do not seem to be used anymore

  // Client validation function
  // Note that validation is currently done on client-side only, so nothing
  // seems to prevent storage of "invalid" passwords
  var validationFunction = window.LoginFormValidation.password;

  it("should validate those strings", function () {
    var validPasswords = [
      "abcde1",
      "a12345",
      "A12345", // This fails but A-Z should allowed
      "a_____", // This fails but there is at least one number or symbol
      "A=====", // This fails but there is at least one number or symbol
      "123456", // This fails but there is at least one number or symbol
      "______", // This fails but there is at least one number or symbol
    ];
    validPasswords.forEach(function (password) {
      if (validationFunction(password) != true) {
        fail(password + " should be a valid password");
      }
    });
  });

  it("should NOT validate those strings", function () {
    var invalidPasswords = [
      "a",
      "a1",
      "a12",
      "a123",
      "a1234",
      "abcdef",
      "ABCDEF",
    ];
    invalidPasswords.forEach(function (password) {
      if (validationFunction(password) == true) {
        fail(password + " should be an invalid password");
      }
    });
  });

});
```

**Comment by mikemurray** [comment]
You're correct, the regex overlooked uppercase characters.

**Below is an example of the same password in two different languages:**

Validates length, symbol and number. Tried with just the symbol, and just the number, and both seem to work.
```
LoginFormValidation.password("hamburgertostudy1@")  -> TRUE
```

Validates length, but the symbols don't match
(Japanese password using Kana and Kanji, with Number (1) and Symbol (@) - just in case you cant see the characters)
```
LoginFormValidation.password("ハンバーガー勉強しつる１@")  -> FALSE
```

Your suggestion to only validate the length might be our option, at least until we can properly localize the password validation checker.

**Comment by mikemurray** [comment]
Closing this issue as password currently only validate on length. (this was fixed a while ago)
