### ISSUE TITLE
Platform Installer Fails in reaction Container

### ISSUE THREAD

**Issue by ichtestemalwieder** [reactioncommerce/reaction#5510]
Hello, 

I am new to reactioncommerce. I tried to install according the [docs](https://docs.reactioncommerce.com/docs/installation-reaction-platform), but the creation/startup of the reaction container seems to fail with the following message:

```~/reaction-platform/reaction# docker-compose logs -f``` 

```
...
reaction_1  |
reaction_1  | npm WARN checkPermissions Missing write access to /opt/reaction/src/imports/plugins/included/email-templates
reaction_1  | npm WARN reaction-plugin-email-templates@1.0.0 No repository field.
reaction_1  |
reaction_1  | npm ERR! path /opt/reaction/src/imports/plugins/included/email-templates
reaction_1  | npm ERR! code EACCES
reaction_1  | npm ERR! errno -13
reaction_1  | npm ERR! syscall access
reaction_1  | npm ERR! Error: EACCES: permission denied, access '/opt/reaction/src/imports/plugins/included/email-templates'
reaction_1  | npm ERR!  { Error: EACCES: permission denied, access '/opt/reaction/src/imports/plugins/included/email-templates'
reaction_1  | npm ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/reaction/src/imports/plugins/included/email-templates\'',
reaction_1  | npm ERR!   errno: -13,
reaction_1  | npm ERR!   code: 'EACCES',
reaction_1  | npm ERR!   syscall: 'access',
reaction_1  | npm ERR!   path: '/opt/reaction/src/imports/plugins/included/email-templates' }
reaction_1  | npm ERR!
reaction_1  | npm ERR! Please try running this command again as root/Administrator.
reaction_1  |
reaction_1  | npm ERR! A complete log of this run can be found in:
reaction_1  | npm ERR!     /home/node/.npm/_logs/2019-09-01T14_44_38_504Z-debug.log
reaction_1  | Failed to install npm dependencies for plugin: email-templates
reaction_reaction_1 exited with code 1
...
```

Does anyone know how to fix this? Most likely a permission error, but at the moment I do not know how to fix this in the container itself...  As I used the standard installscripts, this seems to be a general issue/bug, that most likely also effects everyone else!? 

Thanks very much!

**Comment by aldeed** [comment]
@ichtestemalwieder Sorry to hear you're having trouble. What operating system?

The general answer is that you may have to adjust the permissions for `/imports/plugins/included/email-templates` either on host machine, in the container/volume, or both.

**Comment by focusaurus** [comment]
Try this for a fix. From your host machine cd into `reaction-platform/reaction` and run `chmod a+w imports/plugins/included/email-templates`. It looks like the npm install is unable to create the `node_modules` subdirectory. This happens on linux due to userid mismatch between the host OS and the container.

**Comment by ichtestemalwieder** [comment]
Thanks so many times for your help! 

The chmod did the trick. I then ran into another permission problem that is documented and solved here: https://github.com/reactioncommerce/reaction/issues/5028. (BTW was using debian/ubuntu)

Thanks again for your help!
