### ISSUE TITLE
Write a full checkout flow integration test

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5518]
Add a full checkout flow GraphQL integration test. It should create some initial catalog data, and then do all of the same GraphQL calls that the example storefront does, starting from add to cart, including each step of checkout, and ending with `placeOrder`.

This will help ensure that changes we make are not breaking the storefront checkout flow.

---

Tests cases needed

- createCart (with items)
- addCartItems (add more items)
- reconcileCarts (login flow)
- removeCartItems
- setEmailOnAnonymousCart
- setShippingAddressOnCart
- updateCartItemsQuantity
- updateFulfillmentOptionsForGroup
- selectFulfillmentOptionForGroup
- availablePaymentMethods
- placeOrder

**Comment by janus-reith** [comment]
I think it could he helpful here to have the full workflow in place to catch possible errors, like changing the shipping address / (mostly country), adding another item after you entered the shipping address.
