### ISSUE TITLE
Dropzone for image upload for Shop Logo is hard to recognize

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5526]
@reactioncommerce/design This is a dropzone for an image upload. It's hard to tell that this is what it is. We should design something a little more intuitive.

![](https://user-images.githubusercontent.com/4482263/64455277-237a2e80-d0a2-11e9-8684-e98a0a68bec5.png)

**Comment by rymorgan** [comment]
@machikoyasuda Would this be a candidate for a Catalyst component?

**Comment by machikoyasuda** [comment]
Possibly (?) Do we have a design for this? Otherwise, we can use a Catalyst Button here, like we do for other image upload areas.

**Comment by rymorgan** [comment]
We don't have designs for a dropzone.
