### ISSUE TITLE
Rewrite any code which calls getGraphQLContextInMeteorMethod to not use Meteor methods

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5529]
- Rewrite any code which calls `getGraphQLContextInMeteorMethod` to get context directly from being a passed variable.
- This will most likely consist of rewriting all places that use `getGraphQLContextInMeteorMethod` to no longer rely on meteor.

### Where is it used

- [x] `inviteShopMember.js`
- [x] `inviteShopOwner.js`
- [x] `sendResetPasswordEmail.js`
- [x] `sendVerificationEmail.js`
- [x] `sendWelcomeEmail.js`
- [x] `catalog.js`
- [x] `publishProducts.js` - PR #5528 
- [x] `cart.js`
- [x] `getLocale.js`
- [x] `index.js`
- [x] `verifySettings.js`
- [x] `generate-sitemaps.js`

**Comment by aldeed** [comment]
Done
