### ISSUE TITLE
broken product routes: lookup by ID if no title.

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#553]
Broken behaviour, products without title should lookup by id.

<img width="1427" alt="reaction___qsldexg77zvhp4abs" src="https://cloud.githubusercontent.com/assets/439959/11646369/3ca7d10e-9d12-11e5-9d19-a30d6cd1795d.png">

**Comment by newsiberian** [comment]
Hello, hmm... why not make a title mandatory?

**Comment by aaronjudd** [comment]
Title is required in the schema, but we bypass it when creating a new one. I think it would be too confusing to have a default title, but nothing else when you create a new product.

**Comment by aaronjudd** [comment]
It should be noted - that we create the product BEFORE the user edits it for the first time.

**Comment by newsiberian** [comment]
Ok, now I get it. I will take this.

**Comment by aaronjudd** [comment]
@newsiberian I added you to the "project collaborators".  That should let you assign issues to yourself, to help us track.
