### ISSUE TITLE
[v2.3.0] MongoError: Majority read concern requested, but it is not supported by the storage engine.

### ISSUE THREAD

**Issue by vigyano** [reactioncommerce/reaction#5554]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Running latest version v2.3.0 with docker build throws MongoDB error.
"MongoError: Majority read concern requested, but it is not supported by the storage engine."

## Steps to Reproduce
1. run latest docker build reactioncommerce/reaction:master (or) reactioncommerce/reaction:release-v2.3.0

2. Getting error:
```
MongoError: Majority read concern requested, but it is not supported by the storage engine.
    at queryCallback (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by aldeed** [comment]
You need oplog and replica set on your MongoDB. These were always requirements but they didn't throw a hard error until some recent changes to file-collections. If you're running locally for development the documented ways, it should be configuring the replica set for you. If the error is on deployed app, then you'll need to do it wherever your database is hosted.

**Comment by aldeed** [comment]
Alternatively, I believe the latest 4.x MongoDB does not have this limitation. Use 4.x at your own risk, though. Reaction hasn't been fully tested with it.

**Comment by vigyano** [comment]
Hi @aldeed thanks for the input. I tried different setup with MongoDB and as you said `only v3.6.x with replica set in WiredTiger engine works`. Since we are testing and bootstrapping our e-commerce site, we have been using mLab sandbox 3.6.12 (MMAPv1) without replica set and all worked fine so far until v2.3.0 reaction that breaks. 

Question:
- Going forward is MongDB + ReplicaSet + WiredTiger engine be basic requirement for reaction?

**Comment by aldeed** [comment]
@vigyano Yes. It has been the assumed database configuration since 2.0 or even earlier, but it needs to be better documented. It would be nice to eventually eliminate the replica set requirement when developing. The only reason for the requirement, as far as I know, is for change streams and oplog tailing. Latest Mongo does not need a replica set for these things, and Reaction is moving away from oplog tailing, but for now it's on Mongo 3.6.x and parts of the stack are still Meteor.
