### ISSUE TITLE
Feature: support multilingual emails based on account and order preferred languages

### ISSUE THREAD

**Issue by jm18457** [reactioncommerce/reaction#5555]
Emails should be based on account profile language or order language before shop language.
This way shop supports multilingual email sending.
Currently a shop will send emails only in the language that is set in `shop.language` field in the database. This means all emails from same shop will be in same language.

## Prerequisites
* [x ] Are you running the latest version?

**Comment by aldeed** [comment]
PR merged. Will be in the next 2.x release.
