### ISSUE TITLE
default width for product grid placeholders / products

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#556]
I think there should be a default width (or min. width)  applied to the product grid.

<img width="1051" alt="reaction___index" src="https://cloud.githubusercontent.com/assets/439959/11648795/ccbbe4d2-9d2c-11e5-98bc-6938402d39c1.png">

**Comment by aaronjudd** [comment]
@mikemurray also note the "account settings", probably shouldn't have persisted there (I was previously on the accounts settings page.)

**Comment by mikemurray** [comment]
I can default the width, but the grid as you know it will never be the same :wink: 
Simple solution (I hope) is to make them the same size as the medium sized products. 

I'll look into that menu item sticking around.

**Comment by tdecaluwe** [comment]
Side note/question: wouldn't it also be nicer if the product boxes had a fixed aspect ratio?

**Comment by mikemurray** [comment]
@tdecaluwe That depends. 

If all the content you're going to upload is the same size / aspect ratio, then a grid that maintains that would be best.

If your going to upload a bunch of different sized images, but still want the grid to look somewhat uniform, then this is what we have.

As we start adding more customization features, more improvements will be made to the product grid and how it handles sizes of items.

The product grid is another part of reaction that we're going to make a separate package, so you can swap in a different one. That has the potential to give everyone a product grid best suited for their needs.

**Comment by newsiberian** [comment]
Hi, I want to say about future product grid package. In `reaction-react` I choosing between two packages. I was trying [react-grid-layout demo](https://strml.github.io/react-grid-layout/examples/0-showcase.html), but it have one big minus for us - then moving products, they moving in some other kind of order on the grid, not in order we need.

A package that I probably will use is [react-absolute-grid demo](http://jrowny.github.io/react-absolute-grid/demo/). It acts on cart moving just like we need.

Try to play with browser resizing with both this examples. It's pretty cool.
