### ISSUE TITLE
Example storefront fail to build

### ISSUE THREAD

**Issue by moeghashim** [reactioncommerce/reaction#5573]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x] Are you running the latest version? Yes
* [x] Are you able to consistently reproduce the issue? Yes
* [x] Did you search the issue queue for existing issue? [Search issues]  (https://github.com/reactioncommerce/reaction/issues) Yes

## Issue Description
The store front build fails. It showing that it can't find a module module `cookie-parser`
I attached a screenshot.
## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Run `make` .

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
(run `npm run version --silent` from your reaction directory)
<img width="817" alt="Screenshot 2019-09-20 12 12 36" src="https://user-images.githubusercontent.com/23550100/65323066-53e0c300-dba0-11e9-801b-83aa514006ae.png">

**Comment by RoytenBerge** [comment]
Hey moeghashim,

I'm facing exactly this issue. 
Have you found out how to ressolve this issue?

I hope you can help me out. 
Spent 2 days on trying to fix this already.

Regards,
Roy

**Comment by moeghashim** [comment]
Hi Roy,

Try editing the file .reaction/entrypoint.sh in you storefront and change command=(node .) to command=(./bin/start) in Line 21.
Thank solved it for me.

Best,

Moe

**Comment by RoytenBerge** [comment]
Hey Moe,

Thanks a lot for the quick and useful response! 
This fixed my problem too!!!

Roy
