### ISSUE TITLE
Product Metadata not working - not able to delete or show in the storefront

### ISSUE THREAD

**Issue by vigyano** [reactioncommerce/reaction#5576]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
After installing latest reaction v2.3.0 or v2.4.0 platform, 
1. go to storefront and there is no metadata info in example product detail page. 
2. go to to reaction backend admin and delete not working. Adding copies the existing metadata new new line.

![image](https://user-images.githubusercontent.com/12378687/65362959-56521580-dbbe-11e9-8f81-e4f9744903c5.png)

![image](https://user-images.githubusercontent.com/12378687/65362776-a381b780-dbbd-11e9-89d3-6ef332f29209.png)

### Versions
v2.3.0, v2.4.0

**Comment by aldeed** [comment]
For storefront, it is only an example app. You may add product metadata wherever you want it on the page.

For not being able to add, edit, remove metadata in Reaction Admin, that would be a bug. cc @mikemurray

**Comment by mikemurray** [comment]
From my tests, there are some issues with the current experience.

- Can add metadata
- Cannot remove metadata
- Cannot have duplicate data, but no error message states that
- Create fields do not auto-clear once metadata key/value pair is created
- ...And the overall design could be improved with our more up-to-date components.
