### ISSUE TITLE
Main navigation UX improvements

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#558]
The main navigation and tag bar are in need of some responsive and usability updates.

- On small screen sizes the main nav bar breaks
- Its hard to quickly navigate through a series of nested tags, easy to get lost down the rabbit hole

Some ideas:
- Combined navigation / tagbar with drop down menu for a traditional tree of tags 
<img width="588" alt="screen shot 2015-12-08 at 2 30 44 pm" src="https://cloud.githubusercontent.com/assets/42217/11670716/528fca48-9db8-11e5-8e6f-7e82479b78b4.png">

- Have tags also show up in the footer
- Slide out menu on mobile for easy access

**Comment by ramusus** [comment]
What I'm doing wrong?
I'v got this strange html layout problems on fresh installation of there reaction: http://cl.ly/0E0H2G0z201X
And when I'm trying to add new tags or existed tag "Products" to the top navigation I'v got error **Tag already exists, duplicate add failed.**

**Comment by ramusus** [comment]
In terminal I see this 
```
I20160108-21:36:31.623(3)? Exception while invoking method 'shop/updateHeaderTags' Error: Match error: Failed Match.OneOf or Match.Optional validation
I20160108-21:36:31.623(3)?     at check (packages/check/match.js:33:1)
I20160108-21:36:31.624(3)?     at [object Object].Meteor.methods.shop/updateHeaderTags (server/methods/shop.js:372:5)
I20160108-21:36:31.624(3)?     at packages/check/match.js:103:1
I20160108-21:36:31.624(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160108-21:36:31.624(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:102:1)
I20160108-21:36:31.624(3)?     at maybeAuditArgumentChecks (livedata_server.js:1695:18)
I20160108-21:36:31.624(3)?     at livedata_server.js:708:19
I20160108-21:36:31.624(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160108-21:36:31.624(3)?     at livedata_server.js:706:40
I20160108-21:36:31.625(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160108-21:36:31.625(3)?     at livedata_server.js:704:46
I20160108-21:36:31.625(3)?     at tryCallTwo (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160108-21:36:31.625(3)?     at doResolve (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20160108-21:36:31.625(3)?     at new Promise (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20160108-21:36:31.625(3)?     at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
I20160108-21:36:31.625(3)?     at livedata_server.js:548:43
I20160108-21:36:31.626(3)? Sanitized and reported to the client as: Match failed [400]
I20160108-21:36:31.626(3)? 
```

**Comment by mikemurray** [comment]
@tdecaluwe I'm mashing a bunch of new ideas together. The UI issues you're seeing are the beginning works of making the tag navbar into a sidebar when you're on a mobile device, or configure it to be a sidebar from the dashboard (not yet implemented). It's still a little rough.

As for the issue in terminal. Theres a problem with the params being passed into the method `shop/updateHeaderTags`. A param is probably undefined or not the right type.

**Comment by mikemurray** [comment]
If you want to work on this then great! If not I would like to try an clean it up a little more so its at least functioning properly.

**Comment by ramusus** [comment]
@mikemurray thanks! I'm not ready to work on this, but will await to see this functionality in action

**Comment by tdecaluwe** [comment]
Yeah, I'll wait for a merge from `navigation-558` first, but I can iron out some issues from there if you'd like.

**Comment by mikemurray** [comment]
Made some progress on the new tag navigation. Built with React js, and moved to its own package, `reaction-ui-tagnav`, which depends on the new `reaction-ui` React based components.

Some things still needed:
- Mobile support
- Vertical version (which will be used on mobile)
- A way to force the vertical version
- Drag / drop sorting fixes.
- Tweak style of autocomplete form
- Translations (still figuring the best way to do that with React.js)
- Cleanup some issues with RTL
- Other various style improvements

![screen shot 2016-01-10 at 10 32 50 pm](https://cloud.githubusercontent.com/assets/42217/12228107/bfa027b6-b7eb-11e5-8d08-2c46e4ffc2d5.png)

<img width="841" alt="screen shot 2016-01-10 at 10 32 35 pm" src="https://cloud.githubusercontent.com/assets/42217/12228113/d09bd0f6-b7eb-11e5-8429-7fa289f6c85a.png">

<img width="845" alt="screen shot 2016-01-10 at 10 32 10 pm" src="https://cloud.githubusercontent.com/assets/42217/12228117/d7adb724-b7eb-11e5-9d63-c137c239c2fb.png">
