### ISSUE TITLE
Import products from Google spreadsheet

### ISSUE THREAD

**Issue by j2l** [reactioncommerce/reaction#565]
Since you already did the work at Ongo Work this would be dead simple for you :)
Phil M

**Comment by hsduk** [comment]
https://github.com/reactioncommerce/reaction/issues/358
https://github.com/reactioncommerce/reaction/issues/467
I wrote a method which uses papa parse to read a csv file and then create 2000+ Products.json which can be placed in the sample-data package. It also creates Tags.json. 
Keen to understand how I can import images into cfs now. I don't mind testing a Google sheet link with it before i share. My product.csv is 1 line per sku and had to derive products, colour variants and size variants to build the json.

**Comment by tdecaluwe** [comment]
Would a csv importer answer the question? If we can get some requirements on this, I'll try to implement something based on `ReactionImport`. IE, how would we import array fields from csv/google spreadsheet?

**Comment by j2l** [comment]
Sure, csv import sounds good! 
1 line per product with flexible mapping: Possibility to have additional columns to map to additional fields like discount, promo code, etc. This also means that the csv could be used as a feed, not a static "one time" import only, hence manage stock for different websites.

**Comment by tdecaluwe** [comment]
Yeah, one-t-one mappings are easy. Additional fields is more a question about validation than import. But how about arrays for example? A Product has a member `hashtags` which contains an array of tag id's. How would you map something like that to a csv structure?

**Comment by aaronjudd** [comment]
Also see: https://github.com/ongoworks/meteor-google-spreadsheets - this should actually be a pretty easy thing with the new imports..

**Comment by tdecaluwe** [comment]
Ah, looks interesting. I see you stumbled upon the same implementation difficulties around document structure. I was thinking arrays containing literals could be implemented by using empty header fields? Nested documents can be represented by their mongodb path representation. Only arrays of documents cannot be represented like this.

**Comment by j2l** [comment]
"flattening" arrays is always an issue. An index (tag001, tag002) could help fit in the additional column part? At least it is simple enough to help migrate from other dbs with simple regex.

**Comment by zenweasel** [comment]
Not currently on the roadmap, but we would welcome a PR that added this feature.
