### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by j2l** [reactioncommerce/reaction#566]
Hello,
May be I didn't find how but it's not obvious how to delete an account.

**Comment by aaronjudd** [comment]
No UX for deleting an account.  I guess we could/should add this however removing all permission from a user is effectively the same thing, as it would disable the account.  I guess the question is should you be able to delete a user?  If we do that, do we also clean up all related records?   It might be better that we don't actually delete the user, just remove all permissions and "archive" the user (for record keeping).

**Comment by mikemurray** [comment]
We could we just add the role "active" or "deactivated" the user's role and handle them accordingly; however, users have "the right to be forgotten".

**Comment by aaronjudd** [comment]
Yes,  maybe you wouldn't want to delete their actual order history - there are other laws requiring that information to be preserved.... so "forgotten" is not the same as "deleted".
