### ISSUE TITLE
[demeteorization] Update catalog.js meteor methods to GQL

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5679]
We need to update the all meteor methods in `imports/plugins/core/catalog/server/methods/catalog.js` to use GQL. Anything calling `updateCatalogProduct`, which calls `hashProduct`, and anything with an appEvent, 
 specifically.

#### Using only `appEvents`:

- [ ] products/archiveProduct [In progress: @kieckhafer] https://github.com/reactioncommerce/reaction/pull/5680

- [ ] products/deleteVariant [In progress: @kieckhafer] https://github.com/reactioncommerce/reaction/pull/5680

#### Using `updateCatalogProduct`, which uses `hashProduct`:

- [ ] products/updateProductTags

- [ ] products/removeProductTag

- [ ] products/setHandle

- [ ] products/setHandleTag

- [ ] products/updateVariantsPosition

- [ ] products/updateMetaFields

- [ ] products/removeMetaFields

#### Using both: 

- [ ] products/updateProductField  [In progress: @kieckhafer] https://github.com/reactioncommerce/reaction/pull/5686

- [ ] products/toggleVisibility  [In progress: @kieckhafer] https://github.com/reactioncommerce/reaction/pull/5686

**Comment by janus-reith** [comment]
@kieckhafer It seesm one of your changes reading this introcuded an error:
The `withProductForm` HOC defines a function `handleFieldChange`and passed a non-existent function  `handleProductFieldChange `:

https://github.com/reactioncommerce/reaction/blob/10ce7bb23cc4f71fe416e3115d0d119262f174d9/imports/plugins/included/product-admin/client/hocs/withProductForm.js#L143

**Comment by jackson-sandland** [comment]
Is this part of a larger effort to replace `meteor.js`? Having 2 different front end frameworks is a nightmare.

**Comment by kieckhafer** [comment]
@jackson-sandland Yes, we are moving away from Meteor, striving to get meteor completely removed within the next _major_ release. You can check out the `release-3.0.0` branch to see a meteor-free `api`, which will pair with a new repo for the UI.

**Comment by aldeed** [comment]
Confirmed all of these that are needed now have GQL equivalents in 3.0
