### ISSUE TITLE
Order page UI and workflow updates

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#570]
![reaction___j7nec8izsfrjczjmm](https://cloud.githubusercontent.com/assets/439959/11737511/b35b0752-9f8e-11e5-8df2-425411e8bd88.png)

**Comment by aaronjudd** [comment]
Also as discussed, let's change the steps to be:

`New`
`Pending`
`Captured`
`Shipped`
`Completed`

Hide canceled / refunded for now.

**Comment by mikemurray** [comment]
Updates to workflow diagramed:
![image](https://cloud.githubusercontent.com/assets/42217/11821759/fb4bd1b0-a31f-11e5-81de-bb5ebab7f535.png)

---
Order workflow reduced to 3 main states
- new (order was created by the user)
- processing (called `created` at the moment)
  * You'll click a start button to acknowledge that the order is being processed.
  * Can also the in processing if it is determined from the status of items that are in the process of being returned / replaced / refunded or otherwise not in a state of completion.
- completed
 * Will be added by a hook that will check the status of all items to determine if the order is `completed` when the order is updated.

Each line item has states:
- new
- tracking added (picked and packed)
- captured / refunded / canceled
- shipped
- completed

**Comment by mikemurray** [comment]
Items will now be split so each can be tracked individually.

![screen shot 2015-12-16 at 7 57 34 am](https://cloud.githubusercontent.com/assets/42217/11846089/cbc2f4b2-a3cb-11e5-8bc5-9b82e18f57ae.png)

**Comment by mikemurray** [comment]
Updates to order workflow (WIP)

Gist: https://gist.github.com/mikemurray/1111c0635ef73037ace7

**Pasted below of convenience:**
 
---
### Somewhere in reaction...
## STEP 1: meteor call to push a new workflow
**NOTE:** `coreOrderWorkflow`, `processing` will be combined into `coreOrderWorkflow/processing` and set as the status.

```js
Meteor.call("workflow/pushOrderWorkflow", "coreOrderWorkflow", "processing", order);
```

### On the server...
## STEP 2: workflow/pushOrderWorkflow tries to update the current status
```js
Meteor.methods({
  /**
   * workflow/pushOrderWorkflow
   * Push the status as the current workflow step,
   * move the current status to completed worflow steps
   * @summary Update the order workflow
   * @param  {String} workflow workflow to push to
   * @param  {String} status - Workflow status
   * @param  {Order} order - ReactionCore.Schemas.Order, an order object
   * @return {Boolean} true if update was successful
   */
  "workflow/pushOrderWorkflow": function (workflow, status, order) {
    check(workflow, String);
    check(status, String);
    check(order, Object); // TODO: Validatate as ReactionCore.Schemas.Order
    this.unblock();

    const result = ReactionCore.Collections.Orders.update({
      _id: order._id
    }, {
      $set: {

        // Combine (workflow) "coreOrderWorkflow", (status) "processing" into "coreOrderWorkflow/processing".
        // This combo will be used to call the method "workflow/coreOrderWorkflow/processing", if it exists.
        "workflow.status": `${workflow}/${status}`
      },
      $addToSet: {
        "workflow.workflow": order.workflow.status
      }
    });

    return result;
  }
});
```

### Somewhere common (client and server)...
## STEP 3: Order update before hook runs and calls a method named after the status (coreOrderWorkflow/processing) is allowed to be set on this order.

```js
ReactionCore.Collections.Orders.before.update(function (userId, order, fieldNames, modifier) {
  // if we're setting something on the order
  if (modifier.$set) {
    // Updating status of order e.g. "coreOrderWorkflow/processing"
    if (modifier.$set["workflow.status"]) {
      let status = modifier.$set["workflow.status"];
      let workflowMethod = `workflow/${status}`;

      if (Meteor.isServer) {
        if (Meteor.server.method_handlers[workflowMethod]) {
          const result = Meteor.call(workflowMethod, {
            userId,
            order,
            modifier
          });

          // Result should be true / false to all or disallow updating the status
          return result;
        }
      }
    }
  }
});
```

### On The server...
## Step 4: workflow/coreOrderWorkflow/coreOrderProcessing is called from the Orders.before.update Hook 

Checks if the user has dashboard/orders access, return true or false 

`false` in this situation will stop the Orders.before.update HOOK from updating the order document.

```js
Meteor.methods({
  /**
   * workflow/coreOrderWorkflow/coreOrderProcessing
   * Workflow method that checks permissions for a given user to allow them to
   * move an order into the processing phase.
   * @param  {Object} options An object containing arbitary data
   * @return {Boolean} true to allow action, false to cancel execution of hook
   */
  "workflow/coreOrderWorkflow/coreOrderProcessing": function (options) {
    check(options, Match.OrderHookOptions());
    const userId = options.userId;

    return ReactionCore.hasPermission(["dashboard/orders"], userId);
  }
});
```

## Other modifications

```js
// reaction-core/server/register.js
...
{
  template: "coreOrderProcessing",
  label: "Order Processing",
  // Added status so the template name is no longer tied to the status
  // This would allow you to use multiple templates for a given workflow status
  status: "processing",
  workflow: "coreOrderWorkflow",
  audience: ["dashboard/orders"]
}
...
```

```js
// reaction-schemas/common/schemas.js
...
status: {
  type: String,
  optional: true
},
...
```
