### ISSUE TITLE
Add Integration Tests for navigation GraphQL queries

### ISSUE THREAD

**Issue by mpaktiti** [reactioncommerce/reaction#5706]
Epic: #5310 

Queries to be implemented:
- [navigationItemsByShopId](https://github.com/reactioncommerce/reaction/blob/develop/imports/node-app/plugins/navigation/queries/navigationItemsByShopId.js)
- [navigationTreeById](https://github.com/reactioncommerce/reaction/blob/develop/imports/node-app/plugins/navigation/queries/navigationTreeById.js)

**Comment by mikemurray** [comment]
I'll be taking over this ticket
