### ISSUE TITLE
[3.0.0] Merge hydra stable PRs

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5707]
Merge hydra stable PRs into the 3.0.0 branches of the API and reaction-hydra. If they are not mergable as is, copy the code changes and verify everything works.

https://github.com/reactioncommerce/reaction/pull/5640
https://github.com/reactioncommerce/reaction-hydra/pull/28

**Comment by yashutanna** [comment]
Ill make the PR's stable as soon as possible. any ETA for when you plan to merge? kind of a busy week so will probably only get to updating my PR's on friday

**Comment by aldeed** [comment]
I was able to test, make a few changes, and merge them into 3.0 branches today. Thanks for getting it started @yashutanna
