### ISSUE TITLE
accounts management console exceptions

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#571]
There's a couple client console warnings:
``Exception in delivering result of invoking 'accounts/inviteShopMember': Error: Can't select in removed DomRange```

Also, not sure that the permissions functionality is correct, might need a little review.  I was thinking that invited users maybe should be showing in shopMembers? and there are no permissions displaying for guests, is this right?

![reaction___dashboard_accounts](https://cloud.githubusercontent.com/assets/439959/11737674/8eb9adde-9f90-11e5-9ff4-3f8038caf8a4.png)

**Comment by mikemurray** [comment]
Invited people can most definitely be added as a shop member. Just need to add the proper roles. I think we should add some checkboxes to the "Add Member" form to make it even more explicit that you're inviting someone that could potentially modify your shops content. For example a "Make admin" checkbox.

"Guest" ?? is that guest an anonymous user, or what it invited?

**Comment by aaronjudd** [comment]
That guest is an anonymous user, perhaps we just shouldn't even be displaying the "guest" here, and that's my confusion...
