### ISSUE TITLE
[3.0.0] Figure out proper Jest setup

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5716]
On 3.0.0 branch, I've tried a few things but so far can't get the right mix of ESM and/or Babel plugins to get all Jest tests to pass without errors. The main problem seems to be that nothing understands the `exports` mapping in the `api-utils` package, so it can't find any files because it doesn't know to look in `/lib`. I tried using Babel module resolver to tell it where to look, but it didn't seem to have any effect.

**Comment by kieckhafer** [comment]
I'm looking into this, but don't want to assign it to myself as the more eyes, the faster this will get resolved. If we could just keep status updates in this ticket if anyone else is looking that'd be great.

**Comment by kieckhafer** [comment]
I updated all import paths to add `lib` just to try it out, and now am getting the following:

```
/usr/local/src/app/node_modules/@reactioncommerce/api-utils/lib/decodeOpaqueIdForNamespace.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { createRequire } from "module";
```
