### ISSUE TITLE
Empty "Shipment" field in order

### ISSUE THREAD

**Issue by yataras** [reactioncommerce/reaction#572]
When you try to check out your products and click once on the field "Select a shipping address" (step 2), you can go further to the next steps without selecting shipping options. With this, you can omit shipping options (step 3). It causes to the empty "Shipment" field in submitted order.

**Comment by aaronjudd** [comment]
Was this with version 0.10.0 (development branch) or master when you tested this?

**Comment by YaTaras** [comment]
It was development branch.

**Comment by YaraYara** [comment]
User can make an order without shipping options. Is that a bug or a feature?

**Comment by aaronjudd** [comment]
@abaoaqus ideally - we'd want the option to be able to skip any step  (downloadable product, subscriptions,etc). However this workflow has been updated and we now select a shipping option by default so I think this bug is now resolved by #250
