### ISSUE TITLE
Write tests that we currently use `test.skip` on

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5729]
We have 7 cart related tests that aren't yet written, but use `test.skip` in `createCart.test.js`

```
test.skip("creates an account cart if logged in", () => {});

test.skip("throws if no items", () => {});

test.skip("creates if no items and shouldCreateWithoutItems is true", () => {});

test.skip("throws creating account cart if one already exists", () => {});

test.skip("if all items are invalid, does not create the cart", () => {});

test.skip("if all items are invalid and shouldCreateWithoutItems is true, creates the cart", () => {});

test.skip("throws if insertOne fails", () => {});
```

Instead of having the test run always say `7 skipped tests`, we are making this ticket and removing the `test.skip` from code.

**Comment by kieckhafer** [comment]
Searching the codebase, I find no results for `test.skip`. 

I'm going to close this ticket because of that, feel free to re-open if you feel it should be open.

**Comment by brent-hoover** [comment]
@kieckhafer Doesn't your original comment "we are making this ticket and removing the test.skip from code.". So you wouldn't find `test.skip` in the code you would need to ensure that those tests actually exist.

**Comment by kieckhafer** [comment]
🤦‍♀️Thanks @zenweasel I didn’t read my own ticket correctly.
