### ISSUE TITLE
Null pointer - second parameter 'payment' of 'stripeCaptureCharge()' is missing

### ISSUE THREAD

**Issue by preminfy** [reactioncommerce/reaction#5735]
Bug: Null pointer 
Description:
Value for the second parameter 'payment' of 'stripeCaptureCharge()' is missing. But its property is accessed in the function body at line 16 of
 imports/node-app/plugins/marketplace/util/stripeCaptureCharge.js.
#hacktoberfest  #infydiaries #CN447
Code: imports/node-app/plugins/marketplace/util/stripeCapturePayment.js
 
  // If discount is 100%, capture 100% and then refund 100% of transaction
  if (captureDetails.amount === accounting.unformat(0)) {
    const voidedAmount = unformatFromStripe(paymentMethod.transactions[0].amount);
    stripeCaptureCharge(paymentMethod);

## Possible Solution
include context property in the above function call.

**Comment by anusha5695** [comment]
Hi @preminfy : Does this bug still persist? If so can i pick this?

**Comment by kieckhafer** [comment]
Closed by https://github.com/reactioncommerce/reaction/pull/5764
