### ISSUE TITLE
[v2.7.0] Create user flow bug

### ISSUE THREAD

**Issue by YuuwakU** [reactioncommerce/reaction#5738]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
When you click on the `CREATE ACCOUNT` option from the storefront, it redirects to the login page, but shows the Sign in component, instead of the Sign Up component, which used to work before. Have to click on the register button to open the sign up form. On creating a user with email and password, doesn't redirect back to the homepage. On opening the homepage, after silent-auth, the graphQL `Account` resolver fails. Console shows this error:
```
21:22:38.947Z ERROR Reaction: Cannot return null for non-nullable field Account.primaryEmailAddress. (errorId=ck22cuj8j00012gmvechpa1i4)
reaction_1  |   path: [
reaction_1  |     "viewer",
reaction_1  |     "primaryEmailAddress"
reaction_1  |   ]
reaction_1  |   --
reaction_1  |   stack: Error: Cannot return null for non-nullable field Account.primaryEmailAddress.
reaction_1  |       at completeValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:568:13)
reaction_1  |       at completeValueCatchingError (/opt/reaction/src/node_modules/graphql/execution/execute.js:503:19)
reaction_1  |       at resolveField (/opt/reaction/src/node_modules/graphql/execution/execute.js:447:10)
reaction_1  |       at executeFields (/opt/reaction/src/node_modules/graphql/execution/execute.js:293:18)
reaction_1  |       at collectAndExecuteSubfields (/opt/reaction/src/node_modules/graphql/execution/execute.js:717:10)
reaction_1  |       at completeObjectValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:707:10)
reaction_1  |       at completeValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:598:12)
reaction_1  |       at /opt/reaction/src/node_modules/graphql/execution/execute.js:500:16
reaction_1  |       at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
reaction_1  | 21:25:11.997Z  WARN Reaction:
```
And store doesn't get any user data due to API failure. I tried this on an existing application and even on a clean install of `reaction-platform`. I see the user is created in `users` collection, as well as in `Accounts` collection.

## Steps to Reproduce
Running the `reaction-platform` with `make start`.
1. Click on `CREATE ACCOUNT` from header.
2. Register user with email and password.
3. Open homepage.

## Possible Solution
`users` collection stores email address with the key `provides` populated as `default` but the same key doesn't exist in the `Accounts` collection, which causes the `Account` resolver to fail.

### Versions
2.7.0

**Comment by joseabraham** [comment]
+1

**Comment by YuuwakU** [comment]
#5726

**Comment by YuuwakU** [comment]
On investigation, find out the underlying issue is the Packages subscription has no data to populate enabled packages data.

**Comment by alefemafra** [comment]
+1

**Comment by agustif** [comment]
I'm having the same problem on v2.9.0

https://github.com/reactioncommerce/example-storefront/issues/615

I reported it in storefront though, jjust find out it was a reaction/api problem from this issue, I don't see how it's related to #5726 and how can I fix it @YuuwakU 
?

Thanks guys!

**Comment by KaySchneider** [comment]
The Version 2.9 has also the Bug when you follow the steps with the recommended reaction-platform stuff.     
When you browse the operators backend then you see in the terminal of reaction docker container also the error:
```
10:02:40.983Z ERROR Reaction: Cannot return null for non-nullable field Account.primaryEmailAddress. (errorId=ck43zgdzq000054mw2nbk447x)
  path: [
    "viewer",
    "primaryEmailAddress"
  ]
  --
  stack: Error: Cannot return null for non-nullable field Account.primaryEmailAddress.
      at completeValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:568:13)
      at completeValueCatchingError (/opt/reaction/src/node_modules/graphql/execution/execute.js:503:19)
      at resolveField (/opt/reaction/src/node_modules/graphql/execution/execute.js:447:10)
      at executeFields (/opt/reaction/src/node_modules/graphql/execution/execute.js:293:18)
      at collectAndExecuteSubfields (/opt/reaction/src/node_modules/graphql/execution/execute.js:717:10)
      at completeObjectValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:707:10)
      at completeValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:598:12)
      at /opt/reaction/src/node_modules/graphql/execution/execute.js:500:16
      at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40

```
It seems there are tons of bugs when you run the Version 2.9 with reaction platform.... Is there any not documentated steps to do to get the reaction commerce running without bugs ?
Or is reaction commerce not stable at all ?  Or are you guys not working on 2.9.0 bugs ?

**Comment by chriscamplin** [comment]
+1
