### ISSUE TITLE
[v2.7.0] Logout button gone in admin UI

### ISSUE THREAD

**Issue by yashutanna** [reactioncommerce/reaction#5740]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Logout button does not exist on the newest version of the admin UI

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. navigate to Admin UI
2. Log in

**Comment by manueldelreal** [comment]
Have you tried the user menu on the upper right corner of the admin UI @yashutanna ? There should be a ` sign out ` option in there along with the profile link

**Comment by aldeed** [comment]
Closing this since there has been no response.

**Comment by manueldelreal** [comment]
@aldeed this is true for v2.7 and above.

**Comment by manueldelreal** [comment]
the suggestion on this comment actually brings back the user button on the admin ui https://github.com/reactioncommerce/reaction/issues/5805#issuecomment-566153649

**Comment by willopez** [comment]
resolved in #5927
