### ISSUE TITLE
[GQL][Last] Accounts (core/accounts)

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5748]
This should be done later in the conversion.

### Startup

- [x] Has logic for accounts `onCreateUser` and `validateLoginAttempt`. This probably doesn't need conversion.

### Collections

- [x] Groups
- [x] Accounts
- [x] Roles
- [x] ServiceConfiguration

### Meteor dependencies

- [x] meteor/alanning:roles
- [x] meteor/accounts-base
- [x] meteor/check
- [x] meteor/meteor (getting user `Meteor.user()`)

#### Account management
- [x] accounts/createFallbackLoginToken ( remove )
- [x] accounts/setActiveShopId (remove)
- [x] accounts/updateEmailAddress (remove, already have these methods)
- [x] accounts/updateServiceConfiguration (remove)
- [x] accounts/verifyAccount (email verification) (don't convert)

See Issue #5833

#### Permissions
- [ ] accounts/addUserPermissions (#5828)
- [ ] accounts/removeUserPermissions (#5830)
- [ ] accounts/setUserPermissions (#5829)
- [ ] group/createGroup ( #5831)
- [ ] group/updateGroup (#5832)

**Already has a GQL query, or is unnecessary**
- [x] reaction/getUserId (use viewer GQL query) (#5834)

### File structure
```
.
├── index.js
├── init.js
├── methods
│   ├── addUserPermissions.js
│   ├── createFallbackLoginToken.js
│   ├── getUserId.js
│   ├── group
│   │   ├── createGroup.js
│   │   ├── index.js
│   │   └── updateGroup.js
│   ├── index.js
│   ├── removeUserPermissions.js
│   ├── sendResetPasswordEmail.js
│   ├── setActiveShopId.js
│   ├── setUserPermissions.js
│   ├── updateEmailAddress.js
│   ├── updateServiceConfiguration.js
│   └── verifyAccount.js
└── util
    └── setUserPermissions.js
```

**Comment by quophyie** [comment]
@mikemurray @rosshadden @aldeed @spencern @kieckhafer ... With regards to #5828, #5830, #5829 I think that the names of these methods should be changed to `*Role` (e.g. `setUserRole`, `addUserToRole`, `removeUserFromRole`) or something similar possibly in a different ticket. My thinking is that in `reaction-authorization`, we dont add policies (permissions in `2.x`) for a specific user (although that is possible). Generally, tt the moment, we add a user/account to a role and then policies are applied to the role. So if we leave the names as (`*Permission`), in my opinion, there will be mismatch between what the method name and what the method actually does as we dont really add permissions to an account/user. These methods only add a user / account to a role. On the other hand I guess there is an argument that when you add a user / account to a role, you are effectively adding permissions but I digress. We can still leave the `groups(roles in reaction-authorization)` as it is at the moment.

**Comment by aldeed** [comment]
@quophyie It's true that we don't even currently allow applying individual permissions from UI, although you could directly call those methods. I don't know enough about the use cases to know whether that should remain the same with keto. But it's certainly easier to work only with groups (keto roles). Worst case, an admin could create a new group with a single permission in it and apply a single permission that way, right?

**Comment by quophyie** [comment]
@aldeed ... Yeah .. you are right.. a role can be created with a single policy applied to it
