### ISSUE TITLE
[discussion] Passing data to authorization functions

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5751]
As part of adding our Keto authorization service, we need to come up with a standardized way to pass data into the `checkPermissions` function that can be used with our default auth service, keto, or any others services you wish to use.

Currently, our `checkPermissions` function accepts two parameters: 
1. An array of permissions that is allowed to use the function, which we check against the permissions a user has
2. The shop ID we are trying to perform an action on
`checkPermissions(["permission1", "permission2"], shopId)`

`checkPermissions` is a new function, and a wrapper for `hasPermission, using the same params, so `hasPermission` will need to be updated as well.

In addition, `context` is available inside of `checkPermissions`/`hasPermission`, so any current user data is available via `context`.

Some options:
1. Keep the same params, and adjust the new auth functions accordingly
1. Turn the first param into an object, where we can pass different variables into the object. Instead of `checkPermissions({ permissions: ["permission1", "permission2"], otherParam: "otherValue" }, shopId)`. This would allow for extra params to be passed if specialized data was needed for each service.

This ticket is open for suggestions and discussion.

**Comment by aldeed** [comment]
Done
