### ISSUE TITLE
[GQL] Email SMTP (included/email-smtp)

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5759]
Updated email settings in the `Packages` collection.

### Collections

- [ ] Packages

### Meteor dependencies

- [ ] meteor/check
- [ ] meteor/meteor

### Methods

- [ ] email/saveSettings

### Publications

none

### File structure

```
.
├── index.js
└── methods
    ├── index.js
    └── saveSettings.js
```

**Comment by willopez** [comment]
closed via https://github.com/reactioncommerce/reaction/pull/5788
