### ISSUE TITLE
[GQL] Tax Rates (included/taxes-rates)

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5761]
### Collections

- [ ] Taxes

### Meteor dependencies

- [ ] meteor/check
- [ ] meteor/meteor

### Methods

- [ ] taxes/addRate
- [ ] taxes/editRate
- [ ] taxes/deleteRate

### Autoform fields

- [ ] shopId
- [ ] country
- [ ] region
- [ ] postal
- [ ] taxCode
- [ ] rate

### Publications

- [ ] Taxes (finds the list of taxes by shopId)

### File structure

```
.
├── index.js
├── methods.js
└── publications.js
```

**Comment by mikemurray** [comment]
@aldeed Seems the tax plugin I'm looking at in `reaction-admin`, and the one in the API both operate on different schemas for the `Taxes` collection.

It seems like (api)`core/taxes` got some of the fields renamed from the (reaction-admin)`included/taxes-rates` plugin.

`API`
```js
export const Taxes = new SimpleSchema({
  _id: String,
  /**
   * Custom key/value data that you need to store.
   * You'll need to extend GraphQL schemas if you
   * want to expose any of this data through the API.
   */
  customFields: {
    type: Object,
    blackbox: true,
    optional: true
  },
  jurisdictionId: {
    type: String,
    optional: true
  },
  sourcing: {
    type: String,
    allowedValues: ["destination", "origin"]
  },
  tax: {
    type: Number,
    min: 0
  },
  taxableAmount: {
    type: Number,
    min: 0
  },
  taxName: String,
  taxRate: {
    type: Number,
    min: 0
  }
});
```

`reaction-admin`
```js
export const Taxes = new SimpleSchema({
  shopId: String,
  taxCode: {
    type: String,
    label: "Tax Code",
    optional: true
  },
  taxLocale: {
    label: "Taxation Location",
    type: String,
    allowedValues: ["origin", "destination"],
    defaultValue: "destination"
  },
  region: {
    label: "State/Province/Region",
    type: String,
    optional: true
  },
  postal: {
    label: "ZIP/Postal Code",
    type: String,
    optional: true
  },
  country: {
    type: String,
    label: "Country",
    optional: true
  },
  rate: Number
}, { check, tracker: Tracker });
```

**Comment by aldeed** [comment]
@mikemurray The one with `taxCode`, `region`, etc. is the one for the `Taxes` collection and could be renamed to `TaxRates` maybe? That is the one that is defined by admin in the tax table. Then that is used to determine the taxes for an order, which is what the other `Taxes` schema represents.

So for the add/edit/delete stuff in this ticket, the `TaxRates` schema is the one you want.
