### ISSUE TITLE
[GQL] Stripe settings (included/payments-stripe)

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5767]
This plugin modifies the package settings for the Stripe plugin to set the API keys.

It has now been decided to move these settings out of Collection and into ENV  vars.

This can likely be handled by a single mutation either `package/update`, or `registry/update` as outlined in the https://github.com/reactioncommerce/reaction/issues/5750 issue.

### Collections

- [ ] Packages

### Autoform Fields

- [ ] settings.api_key
- [ ] settings.public.publishable_key

**Comment by willopez** [comment]
closed via https://github.com/reactioncommerce/reaction/pull/5771
