### ISSUE TITLE
[3.0.0] Update to Node 12 LTS version

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5770]
1. Make new prod and dev images in https://github.com/reactioncommerce/docker-base for the LTS (or higher) Node 12 version.
2. Update `.nvmrc`, "engines" in `package.json` file, and the image tags in `Dockerfile` and `docker-compose.yml` all to the same matching Node 12 LTS version.
3. Verify everything still works. I think they moved JSON import to be behind a flag so probably need to add that flag to our Node commands (see https://github.com/nodejs/node/pull/29754).

**Comment by aldeed** [comment]
Waiting for https://nodejs.org/en/blog/vulnerability/december-2019-security-releases/

**Comment by willopez** [comment]
closed via #6029
