### ISSUE TITLE
Why does reaction use 2 front end frameworks? Is there a react only release?

### ISSUE THREAD

**Issue by jackson-sandland** [reactioncommerce/reaction#5778]
Is it possible to only use one javascript framework - preferably `react.js` - when developing an eCommerce store using `reaction`?

**Comment by YuuwakU** [comment]
Hey @jackson-sandland - reaction is in the process of removing meteor from the platform; From 3.0.0 meteor will no more be a dependency in reaction.

**Comment by hamxabaig** [comment]
Thats great, @YuuwakU is there any document regarding `v3.0.0` milestone or docs etc? Like what to expect in that release. Also when is the timeline set for that version?

**Comment by aldeed** [comment]
@hamxabaig 3.0 beta should be out in a week or two. Docs are still in progress, but look for a 3.0.0 link to appear on https://docs.reactioncommerce.com/versions

**Comment by agustif** [comment]
> @hamxabaig 3.0 beta should be out in a week or two. Docs are still in progress, but look for a 3.0.0 link to appear on [docs.reactioncommerce.com/versions](https://docs.reactioncommerce.com/versions)

This is great news!!

I had discarded reaction in the past because of the meteor core, which I was too scared to touch.

Can't wait for v3. I'm trying to do a lightining launch of a firt version MVP for our ecommerce, should I wait to new release, or would there be a happy upgrade path for the current 2.9 users?

Thanks for all your great work, will try to give back!

**Comment by aldeed** [comment]
2.x to 3.0 will have quite a few breaking changes. If you don't have any custom or third-party plugins, it's probably pretty simple.

**Comment by aldeed** [comment]
Closing this as answered.

The first 3.0 alpha is released, and the separated admin UI repo is made public here: https://github.com/reactioncommerce/reaction-admin. That repo continues to rely on Meteor for some time and currently isn't fully functional but by the time the final 3.0.0 release is out, it should be fully functional and mostly, if not entirely, converted to React.

**Comment by agustif** [comment]
@aldeed sorry for the off-topic on a closed thread.

Great news on 3.0 alpha release, do you think I should try again if I had trouble with initiating a 2.9.0 store, or should I wait to a more release and meteor-free future release?

**Comment by aldeed** [comment]
@agustif 2.9 is a bit broken and there should be a patch release for that soon. If you're not in a rush, I'd wait for 3.0.0 final release in a month or so.
