### ISSUE TITLE
Create permission policies for all packages

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#5790]
A list of all packages in the `core-services` or `plugins` folders of Reaction 3.0.

### Core: Anything outside a plugin
It doesn't seem like we have any places outside of a plugin, but leaving here as a confirmation
- [ ] core

### Core Services
- [x] account
- [x] cart
- [x] catalog
- [x] core - none
- [x] discounts - none
- [x] email - none
- [x] files
- [x] i18n - none
- [x] inventory - none
- [x] orders
- [x] payments
- [x] product
- [x] settings
- [x] shipping  - none
- [x] shop
- [x] tags
- [x] taxes

### Plugins
- [x] address - none
- [x] address-validation-test - none
- [x] checkout - none
- [x] dashboard - none
- [x] discount-codes
- [x] email-smtp
- [x] email-templates - none
- [x] job-queue
- [x] legacy-authorization
- [x] navigation
- [x] notifications - none
- [x] [ayments-example - none
- [x] payments-stripe - none
- [x] product-admin - none
- [x] product-variant - none
- [x] shipping-rates
- [x] simple-inventory
- [x] simple-pricing - none
- [x] simpel-schema - none
- [x] sitemap-generator
- [x] surcharges
- [x] system-info
- [x] taxes-rates - none
- [x] templates - none
- [x] ui - none

**Comment by aldeed** [comment]
Done
