### ISSUE TITLE
[3.0.0] Better context auth switching

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5808]
In 2.x API, sometimes `context.isInternalCall = true` is used to skip authorization checks in individual functions. There are a few problems with this approach:

- It has to be checked explicitly in each function (`if (!context.isInternalCall)`). Some don't, which means they then cannot be called from other internal code.
- There is some slight chance that `isInternalCall` might be stuck to `true` in an unexpected way, which could result in security issues. This is unlikely since the context object is rebuilt on every request, but it would be best to avoid the potential issue entirely.
- We pass it like `{ ...context, isInternalCall: true }`, which is a little clumsy and non-intuitive

For 3.0, I propose the following better way of changing the auth context, which also allows easily simulating any user or no user.

- `context.getContextForUser(userId)`: returns `context` with `user`, `userId`, `account`, `accountId`, `userHasPermission`, and `checkPermissions` all adjusted as if `userId` had authenticated
- `context.getContextForUser(null)`: returns `context` with `user`, `userId`, `account`, `accountId`, `userHasPermission`, and `checkPermissions` all adjusted as if an unauthenticated request was made
- `context.getInternalContext()`: returns `context` with `user`, `userId`, `account`, `accountId`, `userHasPermission`, and `checkPermissions` all adjusted as if the user has all possible permissions

Before, when you want to call a function internally and bypass its permission checks:

```js
await context.mutations.createNavigationItem({ ...context, isInternalCall: true }, { /* ... */ });
```
Now, when you want to call a function internally and bypass its permission checks:

```js
await context.mutations.createNavigationItem(context.getInternalContext(), { /* ... */ });
```

**Comment by aldeed** [comment]
@kieckhafer @rosshadden how does this proposal sound?

**Comment by ticean** [comment]
There's currently work in progress to switch authorization responsibilities to Keto. When doing those checks we can pass information from the token, which contains the `sub` (subject) and claims. Keto can make authorizations decisions with that info and it's auth policies.

I don't think we'll local lookups for any of the account or permissions data prior to submitting the auth check, but can you think of a reason that we need to do that @aldeed?

If this only applies to the existing authorization system then I vote that we don't make any changes to that older authorization system and focus all efforts on the new model.

**Comment by aldeed** [comment]
@ticean This would apply to both systems, but it's at a level above Keto as far as I know. Essentially all we're doing here is changing the context user ID on the fly. So it's related to authorization but separate from any question of how we're looking up permissions.

**Comment by aldeed** [comment]
To maybe explain a little better:

1. Request comes in
2. *Authentication* code decorates the app context with request-specific properties, such as `userId`. These live only until a response is sent.
3. As functions are called, they might use `context.userId` to determine *authorization* (Meteor roles/Keto)
4. If one function has already checked *authorization* and now wants to call another function that normally also does its own *authorization* checks, we need to somehow tell the inner function to skip authorization. I'm proposing we do this by allowing the calling function to get a new copy of the context that essentially has a different `userId` associated with it (where internal/system user would be allowed to do everything).

**Comment by ticean** [comment]
I don't know why we'd want to change the identity context or even provide such a capability. Auditing that would be very difficult if not impossible.

We should authorize everything with Keto using information in the token. It wouldn't be correct to use `context.userId` in the checks because not all clients (token holders) are users. For example, the client-credentials flow results in a token for an OAuth2 client application, and that's likely what ETL's should be using. Policies can be created to grant the proper permissions to client apps.

I feel the same on disabling checks. The check is there for a reason and having a switch to bypass it from the outside doesn't sound like a good idea. If the concern is performance then we can memoize auth assertions for a very short time. But anytime a resource is accessed then we should authorize that the caller can do so.

**Comment by ticean** [comment]
But maybe I'm missing some of the trickier situations that we need to sort out? @aldeed do you have an concrete situation that we could look as an example? That might help us discuss the possible design options more specifically.

**Comment by aldeed** [comment]
@ticean I agree about ETL in theory but we don't have any concept of non-user auth yet, so this is the only way to bypass permission checks.

We can skip doing `getContextForUser` for now if we're uncomfortable with that. It was just a thought. But we do need `getInternalContext`. It's already used in many places, just with a less explicit pattern. It's just a way of re-using functions we have that do everything we need, but when they need to be called outside of the standard request flow. The only way we could avoid it would be to move permission checks out to a higher layer, or to add yet another layer of functions (e.g., `createAccount` fn could be wrapped by `createAccountWithPermissionChecks`). Since that would be a lot more files/functions for little benefit, not to mention a huge rewrite at this stage, I don't think it's feasible.

One non-ETL example is that when `createShop` mutation is called, we auto-create the default nav tree for it. Since permissions have already been checked and we want to ensure default nav tree is always created for all new shops, we call `context.mutations.createNavigationItem()` internally, adjusting the context to flag it as an "internal" call, which tells `createNavigationItem` that checking permissions again isn't necessary.

I don't see any security concerns here because, after the initial permission check, server code should be free and trusted to call any queries or mutations internally without checks.
