### ISSUE TITLE
Remove unused account management methods that are no longer used or have GQL equivalents

### ISSUE THREAD

**Issue by quophyie** [reactioncommerce/reaction#5833]
Please remove the account managements below that are no longer used or have GraphQL equivalents

#### Account management
- [ ] accounts/createFallbackLoginToken ( remove )
- [ ] accounts/setActiveShopId (remove)
- [ ] accounts/updateEmailAddress (remove, already have these methods)
- [ ] accounts/updateServiceConfiguration (remove)
- [ ] accounts/verifyAccount (email verification) (don't convert)

**Comment by rosshadden** [comment]
@mikemurray Do you have any insight on this?

**Comment by willopez** [comment]
resolved in #5748
