### ISSUE TITLE
Not able to see the error description

### ISSUE THREAD

**Issue by eusebiu-andrei9** [reactioncommerce/reaction#5836]
When firing an action I get only the message: (errorId=ck3ircsom000072rv45mr7hg8) path: [  "createCart"  ]. All that i see is the path of the error and the actual error doesn't get printed. How do i get the actual error description and eventually the source of it?

**Comment by aldeed** [comment]
@eusebiu-andrei9 Please don't delete the issue template. It has important info we need such as which version you are seeing the error on.

When you say "I get", what does that mean? Server logs or browser logs? What are you doing when it happens? Please copy/paste example output into this issue. It should be printing more than that in the server logs.
