### ISSUE TITLE
Newly created accounts are not  being published on accounts topic in dev environment

### ISSUE THREAD

**Issue by quophyie** [reactioncommerce/reaction#5837]
When an account is added, it is supposed to be published onto the topic `reaction.cdc.accounts.json-gen1` using mongo kafka connect in the `Dev` environment but this not happening at the moment. Please investigate and fix

**Comment by aldeed** [comment]
@griggheo Is this anything that is still relevant or can we close this?

**Comment by griggheo** [comment]
Let's close it please.
