### ISSUE TITLE
Error on product publishing - no product visible on list

### ISSUE THREAD

**Issue by dominik-myszkowski** [reactioncommerce/reaction#5838]
## Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you able to consistently reproduce the issue?
* [x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
After filling required fields for a new product and variant and making them visible, after "Publish" and getting back to products lists, there is an error and a loop which is being stopped by the browser.
`The above error occurred in the <Tracker(ProductsContainer)> component:
    in Tracker(ProductsContainer) (created by ProductTable)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by ProductTable)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by ProductTable)
    in ProductTable (created by Route)
    in Route (created by Reaction())
    in Reaction() (created by Route)
    in div (created by ContentViewExtraWideLayout)
    in ContentViewExtraWideLayout (created by WithStyles(ContentViewExtraWideLayout))
    in WithStyles(ContentViewExtraWideLayout) (created by Route)
    in Route (created by Dashboard)
    in Switch (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard (created by WithStyles(Dashboard))
    in WithStyles(Dashboard) (created by WithWidth(WithStyles(Dashboard)))
    in WithWidth(WithStyles(Dashboard)) (created by Route)
    in Route (created by withRouter(WithWidth(WithStyles(Dashboard))))
    in withRouter(WithWidth(WithStyles(Dashboard))) (created by Context.Consumer)
    in WithComponents(withRouter(WithWidth(WithStyles(Dashboard)))) (created by Reaction(App))
    in Reaction(App) (created by Tracker(Reaction(App)))
    in Tracker(Reaction(App))
    in ThemeProvider
    in ThemeProvider
    in TranslationProvider (created by Tracker(TranslationProvider))
    in Tracker(TranslationProvider)
    in Router (created by BrowserRouter)
    in BrowserRouter
    in ApolloProvider`

`Exception from Tracker recompute function:
Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

## Steps to Reproduce
1. Login as admin, create new product
2. Fill product name, make visible
3. Select default variant, set price and Attribute name
4. Click "Publish"
5. Click on "Products" on left menu to get back to the list.

Event though product is in DB and visible it is never on the list. Also the error occurs.

### Versions
2.9.0

**Comment by mathiasfc** [comment]
Same here, related [#5805](https://github.com/reactioncommerce/reaction/issues/5805)

**Comment by aldeed** [comment]
@manueldelreal Can you see whether you can reproduce this?

**Comment by manueldelreal** [comment]
@aldeed going to close this one in favor of #5805
