### ISSUE TITLE
OrderEmail missing fields

### ISSUE THREAD

**Issue by bjanssen-pon** [reactioncommerce/reaction#5849]
##  Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you able to consistently reproduce the issue?
* [ x ] Did you search the issue queue for existing issue? 

## Issue Description
When creating an order from the Storefront as a customer I receive an email without the fullname of the customer.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Add item to cart
2. Complete checkout procedure
3. Open email in mailbox

## Possible Solution
I think there might be two options to solve this:

1. (Most preferred solution). Currently you can create a plugin with the function 'getDataForOrderEmail'. When it is registered, it will be at the bottom of the registered functions. When the email is generated, it will select the first registered function of 'getDataForOrderEmail'. I would like to have the option to register the function 'getDataForOrderEmail' at the top of the list or have the core select the last registered function.

2. Extend the function 'getDataForOrderEmail' with custom fields so I can create a more complete and custom email message.  

### Versions
```2.9.0```

**Comment by aldeed** [comment]
@bjanssen-pon I'm guessing you are referring to what happens if the user hasn't yet entered a name in their profile. I thought the template had a fallback to show the email but I could be wrong.

Templates can be customized per shop, so the simplest solution would be to fix the template on the Reaction Admin Emails page. If you post the fix you make to the template here, someone can also update the built-in template that is used for new shops.

**Comment by bjanssen-pon** [comment]
@aldeed, thanks for the reply. Sorry for my delay in response.
Due to holidays and christmas i was not able to respond.

I tried to create a workaround, but was not able to.
What i try to do is the following:

1.  Created a plugin to register a new `getDataForOrderEmail` function.
2. Adjust the function to provide more fields.
3. Adjust the templates of the emails to have the fields supplied by the `getDataForOrderEmail` function.

Expected result:

1. The new `getDataForOrderEmail` function is triggered and supplies extra fields.
2. Email has been received and shows the fields.

Actual result:

1. Warning message is been shown in the backend:
"Plugins registered more than one function of type `getDataForOrderEmail`. Using the first one."
2. The default `getDataForOrderEmail` is been used.
3. Email does not have the extra fields supplied.

My opinion on this is to not touch the base code as much as possible. So when a new update is available for the backend, I just update it and keep using the base as is.
For the orderreferenceid I created the same kind op approch and that worked. The new `createOrderReferenceId` I inserted is been used by the CreateOrder function.
I thought it would work for the `getDataForOrderEmail` function as well.

Do you know if this should work or it works as intended?
I will try to find a solution as well in the mean time.
Thanks!

**Comment by bjanssen-pon** [comment]
@aldeed, The code I am talking about can be found in the following file:
/imports/plugins/core/orders/server/no-meteor/util/sendOrderEmail.js

18 .  const registeredFuncs = context.getFunctionsOfType("getDataForOrderEmail");
19 .  const getDataForOrderEmail = registeredFuncs[0];

It gets the first of the array, whilst all custom functions are added at the bottom of the list.
I would like to see my function on top or have the function injected on top of the array.
I will make a solution for this and create a PR ;)

**Comment by aldeed** [comment]
@bjanssen-pon Yes that's a limitation of Reaction 2.x plugin loading. You can work around it by prefixing your plugin folder name with an underscore, which will cause your override function to be first. In upcoming 3.0 release it's still problematic but plugin load order is explicitly defined in a file so you can force yours to load first without the workaround.

Eventually this should be rewritten in a better way, probably not even using `functionsByType`, but that's not a high priority at the moment.

**Comment by aldeed** [comment]
Clarification, in addition to prefix with `_` you need to put it in `core` plugin folder instead of `custom`.

**Comment by HarisSpahijaPon** [comment]
Should we atleast add some documentation somewhere? Or maybe flag this issue?

**Comment by aldeed** [comment]
@HarisSpahijaPon I haven't looked into this deeply yet, but I'll figure out what needs to be done before 3.0.0 is finalized.
