### ISSUE TITLE
Logging in from the storefront redirects back to login page

### ISSUE THREAD

**Issue by albertstartup** [reactioncommerce/reaction#5878]
## Prerequisites
* [yes] Are you running the latest version?
* [yes] Are you able to consistently reproduce the issue?
* [yes] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Login in from the storefront does not work.
The hydra flow is initiated but after submitting a valid password user is redirected to back to same page.
When user clicks sign in, they are redirected to the backend at /account/login?action=signin&login_challenge=abcdefg, but after login in correctly, they are redirected back to /account/login.
This can be reproduced with a fresh reaction-commerce repo.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Install and run fresh reaction-platform repo.
2. Go to example storefront and click Signin
3. Input correct email and password

## Possible Solution
This has worked before 2.9.0. Hydra is not producing any errors. The bug seems to be in the the reaction backend source.

### Versions
2.9.0

**Comment by albertstartup** [comment]
v2.5.0 does not have this bug.

**Comment by aldeed** [comment]
@manueldelreal Can you try to reproduce? I'm surprised this would have made it through release testing, but maybe it only happens in certain circumstances.

**Comment by kieckhafer** [comment]
I'm with @aldeed this seems very familiar and I believe I fixed it... trying to remember exactly where though.

**Comment by kieckhafer** [comment]
I believe this is fixed. Closing, feel free to re-open if you are still seeing this issue.
