### ISSUE TITLE
[3.0.0 alpha] Shop creation fails as shopId is not set when creating the first user and shop.

### ISSUE THREAD

**Issue by manueldelreal** [reactioncommerce/reaction#5894]
## Issue Description
right now is not possible to create the first shop as the authorization is requiring that the shopId must be provided for the `hasPermission` check, but without an existing shop there's no shopId set yet and can't be provided.

## Steps to Reproduce

1. Launch reaction-admin and reaction
2. visit the url for the admin (default is localhost:4080)
3. register the first user
4. Create the first shop

## Expected results
Shop is created

## Actual results
Error is thrown in the console for the auth error:
`Form "onSubmit" function error: Error: GraphQL error: shopId (roleGroup) must be provided`

### Versions
Release-3.0.0-alpha

**Comment by manueldelreal** [comment]
@kieckhafer this is the one we discussed this morning

**Comment by kieckhafer** [comment]
@aldeed @rosshadden Can you think of any reason to not remove this check?

https://github.com/reactioncommerce/reaction/blob/release-3.0.0/src/plugins/legacy-authorization/util/hasPermission.js#L38

I added it while refactoring this a bit, but I think this is causing the issue, and I think the rest of the function takes care of denying access, if needed, if there is no `shopId` (`roleGroup`) present.

**Comment by aldeed** [comment]
@kieckhafer I agree the check should be removed. Maybe long term each permission should have some kind of metadata indicating whether it needs a shop ID to properly check permissions (i.e. is it shop specific or global permission).

**Comment by aldeed** [comment]
@manueldelreal I think this is fixed now but feel free to reopen if you don't agree.
