### ISSUE TITLE
Account Groups is not returned in account GQL query 

### ISSUE THREAD

**Issue by quophyie** [reactioncommerce/reaction#5906]
## Issue Description
When running the GQL below, the `groups` attribute on the `account` is `null` even when the account has groups  

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.

1. You must be logged in to run this query i.e. use `meteor-login-token` http header to provide the logged in token

2. Run the query
```
query {
  account(id: "SOME_OPAQUE_ACCOUNT_ID") {
    _id
    groups {
      nodes {
        _id
        description
        name
        permissions
      }
    }
  }
}
```

**Comment by willopez** [comment]
resolved in #6060
