### ISSUE TITLE
Product variant price is always 0

### ISSUE THREAD

**Issue by CristianCucunuba** [reactioncommerce/reaction#5916]
## Prerequisites
* [ yes] Are you running the latest version?
* [ yes] Are you able to consistently reproduce the issue?
* [ yes] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When you want to create a products variants, the price and compare price can not be saved. All Product Variants end up with price 0

## Steps to Reproduce
1. Sign in to reaction-platform
2. Go to products and create a product
3. Create a variant of the product and add any price or compare price
4. Make the product variant visible
5. Publish the product
6. Go to products to see the new product and the price is alwalys 0

## Possible Solution
I think this is happening because the price and compare price are not in the ProductVariant schema, I added both of them and now is working. If you think this is the right solution tell me and i can submited a PR.

### Versions
2.9.0

**Comment by janus-reith** [comment]
I believe this error was introduced when `extendCoreSchemas` in the simple-pricing plugin was removed from the Meteor codebase:

https://github.com/reactioncommerce/reaction/blob/v2.6.0/imports/plugins/included/simple-pricing/server/extendCoreSchemas.js

**Comment by aldeed** [comment]
#5910 fixes this in the 3.x track, but I'm not sure we were aware it went back to 2.7. For 2.x track maybe we just need a simpler fix of restoring the lost file. cc @kieckhafer

**Comment by janus-reith** [comment]
@aldeed Restoring that file + the Meteor Server folder with an `index.js` file to import it works.

**Comment by janus-reith** [comment]
I think this can be closed, a fix was released in v2.9.1.
