### ISSUE TITLE
[2.9.x] /profile on operator tools does not resolve to current account

### ISSUE THREAD

**Issue by manueldelreal** [reactioncommerce/reaction#5948]
## Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you able to consistently reproduce the issue?
* [x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When logged in as the first user on the admin ui, going to profile via the link on the user button (upper right corner) the profile page displays `Guest` as the account rather than the current admin account.
Probably related but on the accounts section of the admin ui there's no account listed as the shop owner.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Login to admin ui
2. Click on user icon on the upper right corner
3. Select `Profile`

**Comment by delagroove** [comment]
we are dropping support for 2.X as we approach to the 4.0 release.
