### ISSUE TITLE
[2.9.x] Tags section of admin UI only displays first tag

### ISSUE THREAD

**Issue by manueldelreal** [reactioncommerce/reaction#5949]
## Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you able to consistently reproduce the issue?
* [x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Tag ui only displays the example tag, all other tags that are created or imported via the sample data set exist in the db but are not displayed via the admin ui

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Login to the admin ui
2. Go to the tags section, confirm the example-tag is displayed there
3. Create new tag
4. Come back to tags section of admin ui

**Comment by kieckhafer** [comment]
@manueldelreal I am seeing this issue, however, I'm also seeing that all the tags show after refreshing, meaning it's probably just a reactivity thing.

Can you confirm if you refresh the page you see all the tags?

**Comment by manueldelreal** [comment]
I wasnt seeing them after the refresh but with #5978 I see them regardless of the refresh state.
