### ISSUE TITLE
Remove one-user-per-group-per-shop constraint from addAccountToGroup mutation

### ISSUE THREAD

**Issue by quophyie** [reactioncommerce/reaction#5959]
## Issue Description
We need to remove the `one-group-per-user-per-shop` constraint found in `addAccountToGroup` found in https://github.com/reactioncommerce/reaction/blob/release-3.0.0/src/core-services/account/mutations/addAccountToGroup.js . The `one-group-per-user-per-shop` constraint  enforces that a user / account can only belong to one group per shop. This is a hangover from using `meteor` in `2.x`. Version `3.x` does not have such a constraint as we will eventually use  `reaction-authorization` which does not have such a constraint

## Possible Solution
remove the `one-group-per-user-per-shop` constraint found in `addAccountToGroup` mutation

**Comment by trojanh** [comment]
Is it only about removing this line [addAccountToGroup.js#L95](https://github.com/reactioncommerce/reaction/blob/release-3.0.0/src/core-services/account/mutations/addAccountToGroup.js#L95) and making sure tests are updated accordingly ?

**Comment by mikemurray** [comment]
This is more than just the `addAccountToGtoup` mutation. A bunch of other methods that deal with groups will have to be updated as well to support multiple groups on an account.

**Comment by trojanh** [comment]
great, thanks for the clarification @mikemurray
