### ISSUE TITLE
Make currency jobs rerun when openexchangerates configuration or currency settings are updated

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#598]
Ensure that currency jobs retrigger when the settings are updated in the admin. Ideally, the jobs should re-run anytime the settings are updated.

**Comment by zenweasel** [comment]
It runs if you update the OpenExchangeRates key, but **does not** run if you change your currency.

**Comment by aaronjudd** [comment]
And of course it should always check the user's current currency is loaded as well.

**Comment by newsiberian** [comment]
@aaronjudd, what do you mean by that:
> And of course it should always check the user's current currency is loaded as well.

**Comment by aaronjudd** [comment]
@zenweasel @Capt-Slow  I believe this should be resolved now, so this issue is now just to verify.

**Comment by zenweasel** [comment]
Took me a minute to remind myself what I was talking about but...

Aren't all rates relative to the base currency, not from every currency to every other currency? So once you change currency, all your rates need to be flushed and refresh relative to your new base currency.

**Comment by zenweasel** [comment]
Admittedly handling this on-the-fly is a pretty out-there use case. No one is going to be just changing their base currency on a live production server.

**Comment by kieckhafer** [comment]
Possibly done?

**Comment by zenweasel** [comment]
Confirmed that the Job is changed if you change the configuration, Closing.
