### ISSUE TITLE
variantForm error on empty value

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#599]
Reported by @boboci9 on Gitter [December 17, 2015 3:50 AM](https://gitter.im/reactioncommerce/reaction?at=5672a16d5155bfb75b1706ae)

> Hi, I found an issue on the product form -> variantForm.js:
```
childVariants: function () {
    let product = selectedProduct();
    if (!product) {
      return {};
    }
....
}
```
while on the temlate you have:
```
 {{#each childVariants}}
          {{>childVariantForm}}
        {{/each}}
```
and in case you don't have a selectedProduct() this error will be thrown:

`Error: {{#each}} currently only accepts arrays, cursors or falsey values.`

I think it should be `return null;` or `return [];` or anything else but an empty object

**Comment by zenweasel** [comment]
`childVariants` now returns an array (empty or otherwise)
