### ISSUE TITLE
[3.0.0] addAccountToGroup throws an error after account creation due to missing roles object

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6002]
## Issue Description
The new reaction-identity Meteor app does not take care of roles anymore, therefore new users in the `users` collection will not have an object `roles`.
Then in the `reaction-api` node server`createAccount` checks that the user to be created has no default groups, and will search for the Id of the customer group by slug `customer`.
It instructs `addAccountToGroup` to put the User to the customer group.

`addAccountToGroup` will try to fetch existing rules:
`const newAccountUserRoles = new Set(accountUser.roles[shopId] || []);`

This will fail, as for new users there is no `accountUser.roles` anymore.
As the `addAccountToGroup` calls are inside of an try catch block, `createAccount` will still finish and send an email.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create an account for the `users` collection in the identity app
2. When redirected to the storefront and the first GraphQL call is made, notice how the `reaction-api` container throws an error `TypeError: Cannot read property 'J8Bhq3uTtdgwZx3rz' of undefined`

## Possible Solution
There are multiple things here:
- First of all, if still needed at all, `accountUser.roles` should be checked to exist in `addAccountToGroup` to fix the current error
- This would result in the `customer` group being added to the user, which I read is considered deprecated.
- Should customer be removed? Stop creating it in `createAuthGroupsForShop` and in `createAccount` just leave an empty `groups` array as is, and don't try adding a customer group.

- Maybe something else to consider when keto is in place: Should `addAccountToGroup` try to add Meteor user roles at all with `newAccountUserRoles`? They should already be redundant for new customers, but might still be needed for admin users in the meantime(TODO, need to check: Are they? Or are they already assigned when a user becomes admin/owner?) Backwards-compatibility for existing accounts might be another consideration, although a migration probably is preferable here.

### Versions
latest release-3.0.0 branch

**Comment by aldeed** [comment]
@janus-reith @kieckhafer As it so happens, I fixed this last week but forgot to make a pull request for it. Here it is now: https://github.com/reactioncommerce/reaction-identity/pull/14

**Comment by janus-reith** [comment]
@aldeed Regarding that fix in the identity app, maybe it is still good to recheck here like: `accountUser.roles && accountUser.roles[shopId]` to prevent an error and assume [] if there are no roles, which also seems to be the original intention of that line, as [] is provided as fallback.

**Comment by aldeed** [comment]
@janus-reith Yes I agree
