### ISSUE TITLE
[3.0.0] Accounts query has duplicate field shopId 

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6017]
The `accounts` query includes the field `shopId` twice with different description:

https://github.com/reactioncommerce/reaction/blob/8ed0165a7ab2c07ddfa394317d12c34ca57c37ee/src/core-services/account/schemas/account.graphql#L444
https://github.com/reactioncommerce/reaction/blob/8ed0165a7ab2c07ddfa394317d12c34ca57c37ee/src/core-services/account/schemas/account.graphql#L447

### Versions
latest 3.0

**Comment by HarisSpahijaPon** [comment]
can `good first issue` tag be added?

**Comment by manueldelreal** [comment]
@spencern This looks like an easy cleanup that could be included in the current cycle.

**Comment by janus-reith** [comment]
@manueldelreal Indeed, however it's still there :D Would've sent a PR but thought one of you would be quicker.

**Comment by aldeed** [comment]
Taking this since I'm refactoring that query for #6006 anyway

**Comment by willopez** [comment]
resolved in #6060
