### ISSUE TITLE
Cannot fill in refund amount when in a Non-U.S. locale

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#603]
![image](https://cloud.githubusercontent.com/assets/72819/11887493/c24f0d4e-a56f-11e5-93d3-72eaabde364d.png)

**Comment by aaronjudd** [comment]
I wonder how well the validator is working for this situation @mikemurray  - this probably should be restricted to float number..

**Comment by zenweasel** [comment]
It's most obvious if your currency code is three characters, but I verified it happens with a $ as well.

Steps to Reproduce:

1. Fresh reaction
2. Switch currency to something besides USD (currency symbol only inserted when locale and currency don't match it seems like). USD and USD local this does not happen.
3. Place order
4. Capture Order
5. Try to enter a value in the refund input.

**Comment by aaronjudd** [comment]
And the amount is less than the total?

**Comment by zenweasel** [comment]
With a 3 character currency code you can’t input anything. With a dollar sign, you can input 1 digit. That what you mean?

**Comment by aaronjudd** [comment]
This validation https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/client/templates/dashboard/orders/workflow/shippingInvoice/shippingInvoice.js#L37  should probably just use http://openexchangerates.github.io/accounting.js/  

```
unformat() - parse a value from any formatted number/currency string

Takes any number and removes all currency formatting. Aliased as accounting.parse()

accounting.unformat("£ 12,345,678.90 GBP"); // 12345678.9
```

**Comment by newsiberian** [comment]
Hi, also, there was a part of currency logic missed. I'm talking about **base currency** changing, which was available only for premium accounts https://oxr.readme.io/docs/changing-base-currency,
but now I see, they upgrade this and now allow even Developer account to have access to change base-currency.

**Comment by aaronjudd** [comment]
@newsiberian wouldn't the only time you would need that was if you were selling product from multiple shops with different base currencies?

**Comment by newsiberian** [comment]
No, this is the most important question for non USD shops, because changing **base-currency**, means to allow your new base shop currency to get all rates against it.

Example: to get rates of Ruble to USD current settings are fine, but if you have a shop in Russia and customer from USA will want to buy your product, you will need to calculate USD to Ruble, which means you need to change base currency in exchangerates site.

This mean -- this site is useless if you want to open shop not in USA and you do not want to buy they account, which allow changing of a base currency.

**Comment by zenweasel** [comment]
So I am completely unable to put any amounts in the refund input box now. Is anybody else seeing this/having this problem? I used VPN to switch my location to LA and getting a dollar sign but cannot input any value except for 0.

**Comment by zenweasel** [comment]
Just want to bump this again as this causes me a lot of aggravation every day trying to input refund amounts to test.

**Comment by zenweasel** [comment]
@newsiberian Helped me debug this and it appears that somehow `options.maxValue` was being set to NaN. When I debug it sometimes it was being set correctly and sometimes being set to 0 (which is why I can't input a value)

At @newsiberian's suggestion I moved `const data = Template.currentData();` outside of Autorun and that seems to be solving it for now. I don't know what the side-effects will be but at least I can work without tearing my hair out.

**Comment by aaronjudd** [comment]
@mikemurray @zenweasel I'm still not sure why we have this functionality. What was the purpose?

**Comment by zenweasel** [comment]
@aaronjudd Which functionality are you speaking of? Having it validate that the value is not greater than the value of the order would seem to be a legitimate validation, no?

**Comment by aaronjudd** [comment]
@zenweasel not the validation, but the the $ currency display - I think it makes no difference to display currency as you are refunding always in the shop base currency.

@mikemurray and I duplicated that "Discounts" don't seem to be working.  However the refunds are being applied and that functionality seems to be working, at least with Stripe.  are you testing with all methods, or just the generic one?   We think that the generic payment method need to stub out some more for the refunds to work?

**Comment by zenweasel** [comment]
@aaronjudd Refunds on the Generic Payment method will never "work" as long as we don't store them on the order (see my ticket to that effect). We rely on the payment gateway to be our persistent storage there. Not sure how that relates to this ticket though. This ticket has nothing to do with issuing refunds except for that happens to be the only numeric input field I am using.

The error I am talking about occurs on all payment methods. I admit it's a little hard to duplicate though. Even for me it's intermittent, although it happens about 4/5th of the time.

I may have clouded this issue by saying it was the display of the currency symbol that was making it impossible to input values, but it turns out it's the validation. Although it only seems to happen to me where:

a) Currency rates are not downloaded so values cannot be converted to my local currency.
b) The front-end tries to format the values as my local currency anyway.

**Comment by aaronjudd** [comment]
Also need to look at: `Template.numericInput.onRendered(() => {`

where newsiberian introduced `result.shopCurrency` which we can use instead of result.currency.  result.currency I believe is the "users" currency, not the shop currency, which is what we want in this case. It appears these currency objects might not have all the required properties.



```        const options = Object.assign({},
          result.shopCurrency,
          {
            minValue: "0.00",
            maxValue: "999999999.99"
          },
          data
        );
        console.log(result);
        console.log(options);```

**Comment by aaronjudd** [comment]
I take back the comment about `result.shopCurrency`.. that all seems ok.

**Comment by aaronjudd** [comment]
> Currency rates are not downloaded so values cannot be converted to my local currency.
I think this should be using `ReactionCore.Locale.shopCurrency` -> ie this is _not_ "downloaded", but is the shop base currency. ie... no currency conversion or formatting should be occurring.

> The front-end tries to format the values as my local currency anyway.
See previous answer.

**Comment by zenweasel** [comment]
Fixed
