### ISSUE TITLE
Revisit owner role and migrations for permissions

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#6030]
This comment needs to be addressed, but we wanted to merge the [original ticket ](https://github.com/reactioncommerce/reaction/pull/6021)since it was so big and not have it handing around: 

https://github.com/reactioncommerce/reaction/pull/6021#issuecomment-574306926

@kieckhafer @rosshadden A few things I can think of at the moment:
- https://github.com/reactioncommerce/reaction-identity/pull/14/files will need to be changed somehow. Probably just global shop:create is needed there for the first user? (We'll also need similar code in Identity for keto auth for the first user, but that's a separate issue.)
- I vote to use this opportunity to remove the `"owners" should always have access` logic. As long as we give the first user `shop:create` and anything else they might need, we don't need the concept of an "owner" permission since "owner" is more of a role. This might expose a bunch of faulty permission checks that were previously hidden, but that's a good thing we can work through before the final release.
- What do you think about adding a just-in-time migration for this? In the legacy-authorization `hasPermission` function, you can check whether `roles` contains any old roles. Then use an old-to-new map to build a new roles list, and do a `users.updateOne` to "upgrade" that user. Then check the new list.

**Comment by aldeed** [comment]
There are still a few things to do in Identity and the API regarding owner permissions and first-user authorization flow.

In a nutshell:
- we don't want any such thing as a global "owner" permission anymore
- we don't want shop groups with "customer" or "guest" slugs anymore
- we don't want Identity to grant any special permissions or do anything authorization related
- we want groups to manage global permissions just as they manage shop permissions
- the two global groups will be "system-manager" and "accounts-manager"
- we want the first account created to be put in the "system-manager" global group

Specifically, this means the following changes:
- remove the `Accounts.onCreateUser` hook in Reaction Identity
- in `createAccount` mutation, remove code that defaults to "customer" group and remove `isGlobalOwner` check. Do not assign the account to any groups unless there's a specific invite for it.
- one exception to the previous point: If it's the first account in the system, put it in the global "system-manager" group. If the global "system-manager" group doesn't exist yet, create it first. If the global "accounts-manager" group doesn't exist yet, create that, too.
- in `createAuthGroupsForShop`, remove creation of "customer" and "guest" groups for each shop. Shops should have only "owner" and "shop manager" by default.
- `inviteShopMember` prevents directly inviting to the shop owner group. It seems like we could remove that limitation.
- in `canAddAccountToGroup`, remove the extra `isOwnerAccount` logic. If the user is in the correct group, we should be able to rely on just a normal permission check
- in `hasPermission`, delete the `"owners" should always have access` bit. Use only the permission list that is passed in
- search for "owner" in the API code and pretty much delete anything else we're doing with it

@kieckhafer Anything to add or change?

**Comment by kieckhafer** [comment]
This sounds like a good list to start from. I can't think of anything else off-hand, but wouldn't be surprised if we came across some other needed updates while making these changes.

**Comment by kieckhafer** [comment]
(will keep this comment updated as work continues)

Related PRs:

> remove the Accounts.onCreateUser hook in Reaction Identity
https://github.com/reactioncommerce/reaction-identity/pull/22

> in createAccount mutation, remove code that defaults to "customer" group and remove isGlobalOwner check. Do not assign the account to any groups unless there's a specific invite for it.
https://github.com/reactioncommerce/reaction/pull/6063 (https://github.com/reactioncommerce/reaction/pull/6063/commits/0bdc5dbe5d418b64c53fe08f01fc8d64156926dc & https://github.com/reactioncommerce/reaction/pull/6063/commits/0df8f2ed61ecd350115e7ede635ee30444448376)

> one exception to the previous point: If it's the first account in the system, put it in the global "system-manager" group. If the global "system-manager" group doesn't exist yet, create it first. If the global "accounts-manager" group doesn't exist yet, create that, too.
https://github.com/reactioncommerce/reaction/pull/6063 (https://github.com/reactioncommerce/reaction/pull/6063/commits/cc345ef3ff6b2bcf9eb80a184a556ac427b67f76) This seems messy, but I think accomplishes what we want. Is there a better way to do it?

> in createAuthGroupsForShop, remove creation of "customer" and "guest" groups for each shop. Shops should have only "owner" and "shop manager" by default.
https://github.com/reactioncommerce/reaction/pull/6063 
(https://github.com/reactioncommerce/reaction/pull/6063/commits/b7c908469d856fb9d4252e81681008f54ac4c200)

> inviteShopMember prevents directly inviting to the shop owner group. It seems like we could remove that limitation.
https://github.com/reactioncommerce/reaction/pull/6063 (https://github.com/reactioncommerce/reaction/pull/6063/commits/189273b3722f00ee9382351f56da2dd45f07b089)

> in canAddAccountToGroup, remove the extra isOwnerAccount logic. If the user is in the correct group, we should be able to rely on just a normal permission check
https://github.com/reactioncommerce/reaction/pull/6063
(https://github.com/reactioncommerce/reaction/pull/6063/commits/620ca46891957ea4b47a4f5f2a3a212686be3dfb)

> in hasPermission, delete the "owners" should always have access bit. Use only the permission list that is passed in
https://github.com/reactioncommerce/reaction/pull/6063
(https://github.com/reactioncommerce/reaction/pull/6063/commits/8b66b32472d173795052a64e0cdbfda92761cb8b)

> search for "owner" in the API code and pretty much delete anything else we're doing with it
https://github.com/reactioncommerce/reaction/pull/6063
(https://github.com/reactioncommerce/reaction/pull/6063/commits/41fbf30445989fe9133565d48aee1b44ab65ef00)

**Comment by aldeed** [comment]
Update: "owner" changes merged. Migration still in progress

**Comment by aldeed** [comment]
This migration lives here: https://github.com/reactioncommerce/api-migrations

Soon we hope to move both the legacy-authorization plugin code and the migration to an NPM package.
