### ISSUE TITLE
Add default sort for products API as createdAt ascending

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6044]
Submitting this here per @nnnnat 

## Issue Description
For the admin when listing Products (not consumer-side Catalog records), the list is more or less random. The more intuitive way is to list them by `createdAt` ascending so that the last created records show up first. So this should be added as the default sort when making a `getProducts` API call.

### Versions
3.0.0

**Comment by aldeed** [comment]
Done in next release
