### ISSUE TITLE
Remove price from product schema

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6048]
Currently, the price field in the Products collection can have two types, Float for actual prices on Variants and Object with min/max/range for Products.

While mongodb doesn't have issues with this as no schema is enforced and SimpleSchema can also differentiate between them using the `type` field, external solutions have a hard time guessing a right schema for this. (E.g when syncing to elastic search).

The field currrently seems to be used only for displaying the price range on the product table,
the catalog doesn't use it and calculates on publish.

It makes sense to keep this object to display the price in the product table without recalculating each time, and at some point to allow filtering prices in the product table using min/max, but it should be renamed.

Either to `pricing` similar to the Catalog Schema, but as the `pricing` there has a different structure I'd favor something more specific like `priceRange`.

### Versions
latest release-3.0.0

**Comment by janus-reith** [comment]
BTW, all neccesary api-side changes are inside of simple-pricing, so changing that should be an easy task, quickly noting it here:

src/plugins/simple-pricing/schemas/schema.graphql
src/plugins/simple-pricing/simpleSchemas.js
src/plugins/simple-pricing/startup.js
src/plugins/simple-pricing/util/mutateNewProductBeforeCreate.js

For the admin, the only neccesary change should be to fetch the new field, e.g. `priceRange` for products in the table instead of `price`.

Let me know what your thoughts are and if you want a PR for this.

**Comment by aldeed** [comment]
Changing it in the `extend type Product` in gql, 👍. This is something we want to do. `priceRange` sounds accurate.

Changing it in mongo, though, would require a data migration, and we don't have the new migration tool finished yet. So for now you'd need a resolver to map from the mongo field name to the gql field name and no changes to SimpleSchemas.

**Comment by janus-reith** [comment]
That's something atleast - Albeit the actual issue would certainly only be resolved if the actual field is changed. Will there be migrations in the final 3.0 release?

**Comment by aldeed** [comment]
@janus-reith Migrations won't live in the same repo or be versioned the same, but there may be at least one data version check in the 3.0 API release, which would require running the migration to avoid an error on API startup. Meaning we'd need to release the migrator about the same time.

Also, I realized that `price` is a range object for some `type: "variant"` products, if they have child variants. Only terminal nodes (sellable variants) have a float. So I don't think a straight check of `type` is sufficient. It's messy. I guess variants would just need to allow either `price` or `priceRange`.

**Comment by kieckhafer** [comment]
@mikemurray this seems related to the API price issue we were discussing. Just want you to be aware this is there.
