### ISSUE TITLE
[3.0.0] partialProductPublish shouldn't throw an error for not yet pulished Products

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6051]
Each time the configuration of an inventory item changes, an event `afterInventoryUpdate` is emitted. The startup function of the core inventory plugin will listen for these events and call `partialProductPublish` for the configuration.

There are cases when an inventory status could be updated before a product is published, resulting in an error about the failing desctructure from catalogItem;

## Possible Solution
After searching for the catalog product in `partialProductPublish`, simply skip if nothing is found, or just Log and info that publish was skipped. Another option might be to differentiate between implicit and explicit calls using the startFrom parameter, although "inventory" is the only value this is currently called with.

### Versions
release-3.0.0

**Comment by aldeed** [comment]
Should be fixed by https://github.com/reactioncommerce/reaction/pull/6059/commits/4f17e0dfd82e9a5065513947b3aa608925a55273 merged into 3.0 branch
