### ISSUE TITLE
Move app core to an NPM package

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#6058]
After 3.0.0 final release, we will be moving `/src/core` folder to be an NPM package, which will export the `ReactionAPI` class. This will make it easy to write microservices with the same API pattern for context, MongoDB, GraphQL, and plugin registration.

Working package name is `reactioncommerce/api-core`. If you have better name ideas, please comment.

**Comment by janus-reith** [comment]
What will be the license implications?
Will this stay GPL-3.0 or become Apache-2.0 like some of the other refactors?

**Comment by aldeed** [comment]
Done
