### ISSUE TITLE
Cart not display all items on a low res

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#607]
Hello,
![screencast1](https://cloud.githubusercontent.com/assets/11130487/11914231/34720ee4-a69c-11e5-93ca-f545936a67bc.gif)
browsers: Chromium, Opera

**Comment by aaronjudd** [comment]
@mikemurray @kieckhafer The swiping action is now broken in 0.14 -> there is no boundary bounce.  This needs review for 0.15rc
