### ISSUE TITLE
Users not being notified when logged out from other device or browser

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#608]
Hello, in my opinion, we should send a notification to all clients if user logged out. Something like modal to display that token was removed. The good example is Meteor forum. Please, try to to the same steps with it.
![screencast-1450586161](https://cloud.githubusercontent.com/assets/11130487/11916602/2d1760b8-a700-11e5-949c-1e802fa3505e.gif)

**Comment by aaronjudd** [comment]
The expected behaviour is that the interfaces changes roles (from editing, to viewing). You should not see a spinner and that console message looks like some other (new) bug.   If the page that you are on has new role that allows you to see the content you should get the sign in form.

**Comment by aaronjudd** [comment]
Related to #609

**Comment by zenweasel** [comment]
@newsiberian Are you saying that all clients should be logged out when one client logs out? E.g. if I log out on a desktop I should be logged out on a mobile device? If so I don't think we really want that behavior because I don't know of any other app that does that and would consider that an unwelcome "surprise". Or are you talking about logging out in one tab of one browser you should be logged out in all others? If so, I would agree that we should be doing that and I think this might be broken.

I am confused because in your example you are using two separate browsers and I would consider that expected behavior.

**Comment by newsiberian** [comment]
@zenweasel, hello, for the first time I was thinking exactly like you, but look at https://forums.meteor.com/... try to login to it from two devices, browsers, whatever and you will see alert that you logged out from all devices because, you logged out from one. And I'm not talking about that this is good, but this behavior that we have now and if I understand correct, this behavior comes from `accounts` package.

**Comment by zenweasel** [comment]
@newsiberian I do see that behavior on https://forums.meteor.com but I tried http://demo.telesc.pe/ (the Telescope demo site) and do not see that behavior. (just trying to think of semi-canonical Meteor sites) I think that behavior is so counter to what most people want that I can't see many websites implementing (imho of course) and would argue that we should not implement it here. Is there some upside to this that I am not seeing?

**Comment by newsiberian** [comment]
I totally agree, this is not the best feature that we need.
> Is there some upside to this that I am not seeing?

To answer this question, we need to do some extra debugging work, I suppose :wink:

**Comment by zenweasel** [comment]
@newsiberian So would it makes sense to change this issue to a bug of "users within the same browser not being notified when logged out" since that seems to be broken? Just trying to extract what exactly is the action item here.

**Comment by zenweasel** [comment]
@newsiberian So it looked like we were in agreement and then you changed your mind? Are we worried about people in the same browser or across devices?

**Comment by newsiberian** [comment]
@zenweasel, I'm apologize, it seems that I do not quite carefully read one of the questions. When issue was opened, it was about bug inside current behavior between devices/browsers , but I suppose that we agreed that this behavior should be changed. I'm not talking about user session between tabs in one browser.

**Comment by zenweasel** [comment]
Ok. It's true we don't agree. I don't believe that we should implement logging out all users across client/devices as I think it would lead to a terrible user experience and violates the principal of least surprise. I think a strong argument would need to be made why we would need/want this. But it's not my call. If you think I still don't understand please let me know.

**Comment by newsiberian** [comment]
Looks like we have here a misunderstanding because of the language barrier. I thought we agreed 2 hour ago :smile:

**Comment by zenweasel** [comment]
So to try and clarify once more, if you are saying that users using a different client (browser, device) should be logged out (and notified) if a user logs out on **any** client; then this is a behavior we (at RC) **do not** want and we will close this as WILL NOT FIX. I will open a separate bug for logout notification with the same browser.

If you are talking about notifications with the same browser then we can change the title of this bug (as you did earlier) to reflect that.

Sorry for the long, drawn out discussion.

**Comment by newsiberian** [comment]
Hi, @zenweasel, please, open a separate issue for first variant.
