### ISSUE TITLE
Can't see added products in operator CMS and graphQL error

### ISSUE THREAD

**Issue by chriscamplin** [reactioncommerce/reaction#6094]
Type: breaking

Describe the bug
I get the following error after running make on reaction-development platform, The install completes and is running but then any products i add never appear in operator. not even the example product.

`reaction_1  | in the root directory of your application.
reaction_1  | 11:58:37.213Z ERROR Reaction: Cannot return null for non-nullable field Account.primaryEmailAddress. (errorId=ck63jm2sc000055o14gvq7bq6)
reaction_1  |   path: [
reaction_1  |     "viewer",
reaction_1  |     "primaryEmailAddress"
reaction_1  |   ]
reaction_1  |   --
reaction_1  |   stack: Error: Cannot return null for non-nullable field Account.primaryEmailAddress.
reaction_1  |       at completeValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:568:13)
reaction_1  |       at completeValueCatchingError (/opt/reaction/src/node_modules/graphql/execution/execute.js:503:19)
reaction_1  |       at resolveField (/opt/reaction/src/node_modules/graphql/execution/execute.js:447:10)
reaction_1  |       at executeFields (/opt/reaction/src/node_modules/graphql/execution/execute.js:293:18)
reaction_1  |       at collectAndExecuteSubfields (/opt/reaction/src/node_modules/graphql/execution/execute.js:717:10)
reaction_1  |       at completeObjectValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:707:10)
reaction_1  |       at completeValue (/opt/reaction/src/node_modules/graphql/execution/execute.js:598:12)
reaction_1  |       at /opt/reaction/src/node_modules/graphql/execution/execute.js:500:16
reaction_1  |       at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40`

To Reproduce
git clone this repo.
make, wait until ready
visit http://localhost:3000/operator/products
then cd reaction && docker-compose logs -f to see the above error.

Expected behavior
I would expect to be able to add & remove products and for them to persist in the operator CMS

Screenshots
<img width="866" alt="Screenshot 2020-02-01 at 12 10 13" src="https://user-images.githubusercontent.com/342953/73591860-d9c82f80-44eb-11ea-8034-02e177662afe.png">

**Comment by bongster** [comment]
@chriscamplin 

i also got this kind of issue in my local machine.

because in admin@localhost account has no default providers so in primaryEmailAddress function they can't found a email address and return null.

but in scheme primaryEmailAddress data are non-nullable field

i just changed scheme `primaryEmailAddress: Email!` to `primaryEmailAddress:Email`

**Comment by MohanNarayana** [comment]
@chriscamplin @bongster if you are looking at reaction admin localhost:4080/<shopId>/products loads the product list. Any wrong/different value in place of shopId does not load any data.
Please let me know if the issue still persists or if I am missing any details.

**Comment by loan-laux** [comment]
@MohanNarayana Looking at the screenshot and @chriscamplin's explanation of the issue, it looks like this is Reaction 2.x. Pretty sure we can close.

**Comment by MohanNarayana** [comment]
@loan-laux thanks for your input. Closing the issue.
