### ISSUE TITLE
CreateProductInput & CreateProductVariantInput needs product data support

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#6103]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The new `createProduct` and `createProductVariant` mutations let users create product information via the GraphQL API. From the UI perspective these mutations work as expected, click the "create a product" button, it calls these mutations, creates an empty product in the DB then the user can add product data from the UI using the `updateProduct` or `updateProductVariant` mutation. From an API perspective this creates an the need for an extra request if I'm trying to import product data via an external service/lambda.  

## Steps to Reproduce
See [CreateProductInput](http://apidocs.v3.reactioncommerce.io/#definition-CreateProductInput) & [CreateProductVariantInput](http://apidocs.v3.reactioncommerce.io/#definition-CreateProductVariantInput) type definitions and see there is no way to provide product data to the mutation call.

## Possible Solution
Allow an optional product data object as part of the mutation's input types.

### Versions
3.x

**Comment by brent-hoover** [comment]
Strong +1 to this

**Comment by janus-reith** [comment]
This would really come in handy and actually was my first practical usecase for the GraphQL API back when it was introduced in the 2.0 RCs, to import and update external product data.

**Comment by aldeed** [comment]
Linked PR is in review and should solve this
