### ISSUE TITLE
Admin multiple errors in development environment

### ISSUE THREAD

**Issue by gabry12** [reactioncommerce/reaction#6113]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue?

## Issue Description
Running last version of Reaction installed from Dev. Platform (with 'make-init-dev'), whenever trying to use Reaction Admin to insert a new product or change shop information I get a continuously spinning icon and it's not possible to proceed.
Browser logs show the following errors (the first 2) and warning (the third one):

> Refused to load the script 'https://b.alicdn.com/@sc/list-buyer/lib/js/jquery.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' localhost: http://.facebook.com https://*.facebook.com http://*.fbcdn.net https://*.fbcdn.net http://connect.facebook.net https://connect.facebook.net http://*.googleusercontent.com https://*.googleusercontent.com http://*.cdninstagram.com https://*.cdninstagram.com http://assets.reactioncommerce.com https://assets.reactioncommerce.com http://cdnjs.cloudflare.com https://cdnjs.cloudflare.com http://fonts.googleapis.com https://fonts.googleapis.com http://fonts.gstatic.com https://fonts.gstatic.com http://enginex.kadira.io https://enginex.kadira.io http://*.stripe.com https://*.stripe.com 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

> err: {message: "Network error: Store reset while query was in flight (not completed in link chain)", name: "Error", stack: "Error: Network error: Store reset while query was …d4c8c3ffe31c79151497346411f04d2731eb29:219164:31)", code: undefined, signal: undefined}
hostname: "localhost:4080"
level: 50
msg: "Network error: Store reset while query was in flight (not completed in link chain)"
name: "reaction-client"
pid: undefined
time: Wed Feb 26 2020 12:41:51 GMT+0100 (Ora standard dell’Europa centrale) {}
v: 0
proto: Object
ConsoleRawStream.write @ modules.js:124817

> WebSocket connection to 'ws://localhost:3000/graphql' failed: WebSocket is closed before the connection is established.
SubscriptionClient.close @ modules.js?hash=58d4c8c3ffe31c79151497346411f04d2731eb29:320718

Also, when trying to focus on any product attributes textfields to edit them, I get a match 'failed [400]' error with the following additional console log:

> Exception in delivering result of invoking 'products/updateProductField': TypeError: this.forceUpdate is not a function
    at app.js:48054
    at MethodInvoker._callback (meteor.js:1234)
    at MethodInvoker._maybeInvokeCallback (ddp-client.js:194)
    at MethodInvoker.receiveResult (ddp-client.js:214)
    at Connection._livedata_result (ddp-client.js:1796)
    at Connection.onMessage (ddp-client.js:1962)
    at socket-stream-client.js:216
    at Array.forEach (<anonymous>)
    at ClientStream.forEachCallback (socket-stream-client.js:302)
    at SockJS.socket.onmessage (socket-stream-client.js:215)

## Steps to Reproduce

1. Install all Reaction services from the latest dev platform ("make-init-dev" command)
2. Register and then login in Reaction Admin panel and configure a main shop
3. Trying to add/edit products or shop information produces the errors 

### Versions
3.1.0

**Comment by manueldelreal** [comment]
I think this is the same issue as reported in https://github.com/reactioncommerce/reaction-admin/issues/220,
I will add you to the conversation there @gabry12 and close this one to keep a single point of traceability.
