### ISSUE TITLE
Implement api-utils method that accepts internal database ids as-is or decodes an opaque id

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#6116]
## Summary

We've been in talks on whether the field `_id` and other encoded id fields in responses from the Reaction API should be prefixed and base64 encoded as `opaque` ids. We've decided to support both values in the response, and accept both as input for queries and mutations.

As part of the solution to this problem, we have to consider a method that can accept both the database id and the encoded opaque id. This method would be a part of the https://github.com/reactioncommerce/api-utils package.

## Issue

Queries and mutations expect the ID to be the encoded opaque id. They need to accept both the database id and the encoded opaque id.

## Possible Solution

- Create a method in the `api-utils` package that will accept both the internal database id or the encoded opaque id as input. See this issue https://github.com/reactioncommerce/api-utils/issues/18
- Replace all instances of `decodeOpaqueId` with new selective decoder method

## Considerations

- This change may touch many files, with a small change depending on the results of https://github.com/reactioncommerce/api-utils/issues/18
- Some or all integration tests should be updated or created testing this change. If we expect the database id to be preferred format, should the tests reflect that?

**Comment by delagroove** [comment]
an update to api-core 1.13.0 and a new ENV variable will help with this situation.

[See this PR](https://github.com/reactioncommerce/api-utils/pull/36)
To support this, encodeOpaqueId now looks at the new environment variable REACTION_SHOULD_ENCODE_IDS. If set to false, encodeOpaqueId becomes a no-op function that passes through the ID unchanged. If set to true or not set, the current behavior remains unchanged (it will encode IDs).
