### ISSUE TITLE
New authorize.net package

### ISSUE THREAD

**Issue by OksentukVlad** [reactioncommerce/reaction#612]
Hello there. I forked reactioncommerce:reaction-auth-net package and changed it.
Here is list of changes I made:
- Rewrote entire package using es6 instead of coffeesctipt
- Changed file structure and added some views to match current package requirements
- Changed npm-package from "paynode" to "node-auth-net"
- Added .eslintrc

My implementation is rough and has a lot of wholes, but it works unlike old version.
Please look at it and tell what to improve. If it's acceptable I'll make a pull request.

Here's package(main branch is development): https://github.com/OksentukVlad/reaction-auth-net

**Comment by zenweasel** [comment]
I can take on doing the functional tests for this if you want.

**Comment by aaronjudd** [comment]
I ran into a couple issues testing this.  The UI elements aren't quite loaded correct - likely because some more updates are needed for the registry.  I wasn't able to added/edit the settings in the forms either.  I added the correct place in reaction.json, and got that to work - but I think that `api_id` should probaby be `api_key` (not sure if that changed).  

Once I got past adding the credentials, the whole actual auth net methods seemed to work well.

**Comment by aaronjudd** [comment]
working settings for reaction.json/Packages:

```
    "name": "reaction-auth-net",
    "enabled": true,
    "settings": {
      "api_id": "",
      "transaction_key": ""
    }
  }
```

**Comment by aaronjudd** [comment]
The errors I'm seeing in the UI:

![reaction___dashboard_authnet](https://cloud.githubusercontent.com/assets/439959/11944578/f0f5c00a-a7fb-11e5-956f-f7d5817bee4e.png)
![reaction___dashboard](https://cloud.githubusercontent.com/assets/439959/11944588/fc45aeca-a7fb-11e5-895c-b965652c749b.png)

**Comment by aaronjudd** [comment]
@OksentukVlad looks like the checkout works fine though, not sure if you're seeing the same issues.

  If you want to create a PR to: https://github.com/reactioncommerce/reaction-auth-net/tree/v0.11-reaction-refactor  we can help iron out the bugs on this.

**Comment by aaronjudd** [comment]
@zenweasel @OksentukVlad   There are also now additional payment methods this package will need to add.  See: https://github.com/reactioncommerce/reaction-stripe/blob/development/lib/stripe.js for reference.  I'd also like to see tests for these - hopefully tests for the other payment packages.

**Comment by OksentukVlad** [comment]
@aaronjudd I fixed settings and registry bugs.
I didn't quite understand about additional payment methods. I'll do it later.

**Comment by zenweasel** [comment]
@OksentukVlad payment methods should also implement `authnet/refund/create` and `authnet/refund/list`. I also noticed that the `authnetSubmit` method does `authCaptureTransaction`. The other payment methods separate out the `authorize` and `capture` phases. Is that possible here? If so then it would also implement `authnet/payment/capture`

**Comment by OksentukVlad** [comment]
@zenweasel Okay, got it. Thanks for explanation.

**Comment by OksentukVlad** [comment]
@zenweasel @aaronjudd I've almost finished.
But there're two issues:
- Authorize.net doesn't provide API method for getting list of refunds. Due to their "batch architecture" it's a bit complicated to get that list. I'll probably work on it later.
- Package tests. Can you help me out with testing? Or give me a link to an example of such tests, please.

**Comment by zenweasel** [comment]
@OksentukVlad re: Tests. You got me on that. I am supposed to be writing tests for all the payment packages but have run into issues with what exactly to test that would provide some real value. I will be writing some example tests in the https://github.com/reactioncommerce/reaction-paymentmethod repo early next week so you can look at those as a starting point.

Once again, thanks for updating/fixing this package. I'm sure a lot of people will get some use out of it.

**Comment by zenweasel** [comment]
@OksentukVlad I have updated https://github.com/reactioncommerce/reaction-paymentmethod with what the tests should look like for a payment package. I already have a ticket for writing tests for all the payment packages so I can take that if this is working for you otherwise. Writing tests will probably involve moving some things around to make them testable.

**Comment by zenweasel** [comment]
This has been merged into the rhttps://github.com/reactioncommerce/reaction-auth-net. Still WIP to add refund and refund list methods.
