### ISSUE TITLE
Do you have plan to support multistore/marketplace in Reaction commerce version 3 ? when?

### ISSUE THREAD

**Issue by delokman** [reactioncommerce/reaction#6120]
:)

**Comment by alefemafra** [comment]
+1

**Comment by SharadKumar** [comment]
Yes, this is an important question. I've been going through lots of videos and information and then installing v3 locally (dev platform docker) to realise that it is no more.

Yes, came across a plugin thats orphan now in v3. (Meteor)
https://docs.reactioncommerce.com/docs/core-plugins-marketplace

I have no been able to find any discussion on why it was dropped and community feedback, if any. I'd think given the crowded single-store ecommerce space, having a marketplace with Stripe Connect was a differentiation. Most of the building blocks seems to be available already (shops).

**Comment by StubyProjects** [comment]
So do you think reaction could be the right fit if you want to create such functionality or is another service like spree commerce a better solution ?

**Comment by loid345** [comment]
This function only attracted me to refuse magento. If the marketplace function is not developing, then reactioncommerce is not interesting for business. Half of the stores are built as a marketplace. I do not understand the developers, why they do not develop the main function. And the main function is the marketplace. Without it, reactioncommerce will be one and hundreds of ordinary scripts

**Comment by aldeed** [comment]
There's a related issue in which I posted [a comment](https://github.com/reactioncommerce/reaction-admin/issues/93#issuecomment-601233130) last week that hopefully answers the questions here. If this is resolved, please close this issue.

**Comment by delokman** [comment]
as @aldeed  said: 

I'll also clarify, for anyone following this, the difference between "multi-shop" and "marketplace":

Multi-shop refers to the fact that there is a Shops collection, every entity has one or more shopId associated with it, and therefore you can manage multiple shops in a single database. Multi-shop is supported in the open source API plugins and will continue to be improved.
Marketplace builds on multi-shop to allow creating and combining shops in interesting ways, shared payments with affiliate fees, and other such things. Marketplace has not been a supported part of the open source core since 2.0.0, and there are no plans to revive it. Reaction will make design decisions in a way that helps the community develop third-party marketplace solutions, but is not planning, merging, or prioritizing any marketplace features.
So this discussion is solely about changes to the admin UI to make multi-shop easier to administer.

-----

so this issue is closed
