### ISSUE TITLE
Settings.json not working with meteor reset

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#614]
Hi,

```
{
  "ROOT_URL": "",
  "MONGO_URL": "",
  "MAIL_URL": "",
  "reaction": {
    "METEOR_USER": "reaction@admin.com",
    "METEOR_AUTH": "q123456",
    "METEOR_EMAIL": "reaction@admin.com"
  },
  "isDebug": "info",
  "public": {
    "velocity:html-reporter": {
      "position": "top right",
      "tab-index" : 1
    }
  }
}
```
If I try to use the above settings.json after a meteor reset, so I would like to create the reaction admin as "reaction@admin.com" not a random email the settings are not considered. I used this same json in the previous versions and it worked. After the initialization the settings are read correctly after I changed the isDebug attribute and reaction considered the new value.

**Comment by aaronjudd** [comment]
The user/email/auth variables changed to `REACTION_EMAIL`, `REACTION_AUTH`, `REACTION_USER` in 0.9.0 release.

**Comment by boboci9** [comment]
Thank you, I mentioned this on gitter the other day but no one mentioned his change so I thought it could be a bug. Sorry.
