### ISSUE TITLE
Create reaction-paymentmethod package

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#616]
This should be a stub package that can show someone who wants to create a payment method which methods, etc. they need to implement. Could also serve as the default payment method in a new install so that nothing needs to be configured before you can test running orders through (including having not having to have a Paypal account).

Should be a "model" package with docs, tests, etc.

**Comment by aaronjudd** [comment]
For the UIX, I've been thinking that we should have a Payment Methods package, that acts more like a "payment methods group".  Main dashboard only displaying the Payment Methods package, but the package detail page displays the grid of payment packages. They have no further details, just sidebar settings.  Not suggesting we add that right away to this package, but I think that's a direction to think about as well.

**Comment by zenweasel** [comment]
This is probably an old topic, but it has occurred to me that the way we display payment options is confusing to the consumer since I don't think most people know what "Stripe" is or why they should care. And really what we are calling Payment Methods are really Payment Processors. Seems like each Payment Processor should have a "provides" of which payment methods (e.g. Credit Card, Check, Gift Card, etc) which is what should be shown to the consumer.

This has probably been planned and thought out elsewhere but I just thought I would throw that out there.

**Comment by aaronjudd** [comment]
I've thought about it and agree, just could never solve precisely what it should be. Even grouped by card would be confusing ...   however, the vast majority will only have one method enabled, for example, stripe, and then maybe paypal express as a backup..  in this case,  if stripe was open by default it probably make more sense...
