### ISSUE TITLE
Add currency symbol for displayPrice product property

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#6162]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The `pricing` prop in products/variants has a property `displayPrice` that is missing the currency symbol. 

## Possible Solution
Add current shop's settings to app context, which would include the shop's currency. With currency information available in the app context, it would be trivial to add the currency symbol the `displayProp`

**Comment by aldeed** [comment]
@willopez There is no such thing as a "current" shop. Shop always needs to be looked up based on the data in question. So for product pricing it would be something like.

```js
import getCurrencyDefinitionByCode from "@reactioncommerce/api-utils/getCurrencyDefinitionByCode.js";

const shop = await Shops.findOne({ _id: productOrVariant.shopId }, { projection: { currency: 1 } });
const currencyDefinition = getCurrencyDefinitionByCode(shop.currency);
const displayPrice = getDisplayPrice(minPrice, maxPrice, currencyDefinition);
```

**Comment by mikemurray** [comment]
Getting the currency was added in this PR: https://github.com/reactioncommerce/reaction/pull/6159 but, I think it could be improved further by, either...

- checking if `displayPrice` was requested then calculating it, only if it was
-  or, maybe by adding / update a separate resolver for display price to query when needed

**Comment by aldeed** [comment]
Agree. What I would really prefer is to store all of the pricing data, including `displayPrice`, in the database whenever the price is changed. Then nothing needs to be transformed at read time. But this would require a large initial migration plus a way to schedule a migration whenever someone changes the shop currency.
