### ISSUE TITLE
Mongo Encapsulation

### ISSUE THREAD

**Issue by set321go** [reactioncommerce/reaction#6164]
Hi Folks i'm looking at how feasible it is box mongo up behind some sort of api. I've already started some work on my fork https://github.com/set321go/reaction/tree/repo_shim but I had a few questions.

1. `plugin-simple-authorization` uses the db object from `context.app.db` to call `doesDatabaseVersionMatch`, I can't seem to find other places where this is used, is it something that is left over or is this something that is being adopted?
2. `plugin-payments-examples` uses `context.app.db` to access a collection, this seems like its not registering itself as a proper plugin is this correct?
3. Is there a good reason why your not using a library such as mongoose?

**Comment by focusaurus** [comment]
1. It's a new package: https://github.com/reactioncommerce/db-version-check/commits/trunk

2. I think it's registering a plugin-specific collection, which is fine

```
rg context.app.db
api-plugin-payments-example/src/startup.js
8:  context.collections.ExampleIOUPaymentRefunds = context.app.db.collection("ExampleIOUPaymentRefunds");
```

3. Any time we pick a tech and make it required, it's restrictive to our user base. We have to do it all the time out of necessity, but we try not to be overly prescriptive or opinionated. Thus we use the official node.js mongodb client library.

Trying to create a database abstraction layer is commonly regarded as difficult and ultimately limiting. I would not recommend. Developer's want full access to the database's capabilities, not some least-common-denominator abstraction layer that is guaranteed to have a highly limited query API. But that's, just, like, my opinion, man.
