### ISSUE TITLE
Adding EDI capabilities

### ISSUE THREAD

**Issue by tdecaluwe** [reactioncommerce/reaction#619]
EDI stands for Electronic Data Interchange allowing trading partners to exchange orders, invoices and all kinds of other stuff electronically. I think reaction could benefit in several places from some EDI capabilities. I'm thinking about the following use cases:
- Drop shipping for retailers, allowing orders to be automatically forwarded to the supplier.
- For suppliers: allow EDI links with trading partners to be integrated in the online webshop with order follow-up and delivery.

US based EDI is generally based on the X12 standard while elsewhere implementations are usually based around the UN/EDIFACT standard.

**Comment by aaronjudd** [comment]
Closing - insufficient details.
