### ISSUE TITLE
[discussion] addToCart refactor

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#621]
Hello, I've noticed terrible lags, by doing app client tests. The reason of this you could see on the screenshot. Look at the _quantity_.
![error2](https://cloud.githubusercontent.com/assets/11130487/12005713/f3bef7ba-abd5-11e5-842e-deeb1c666f6e.png)

This led me to idea to rewrite this method.
I added an additional function `quantityProcessing`:

``` javascript
function quantityProcessing(productId, variantId, itemQty = 1) {
  let quantity = itemQty;

... calculations

  return quantity;
}
```

 which supposed to decide how many item quantity we will add to the user cart according to the following conditions:
- check the minimum threshold of the order - #225. In due to what, we will need to add an additional field to product/productVariant schemas. Or maybe we already have something for that? What do you think?

If item from stock:
- check the `inventaryQuantity` against `itemQty` and if `itemQty` > `inventaryQuantity` - return all we have in stock. Right?
- anything else here?

if item not from stock (made on request/is delivered on request - custom tailorin, custom jewelry, etc): 
- only check availability of product. Here we have an individual approach to each order.

if item is a digital product or something similar:
- only check availability of product

To make all this changes possible, I think, we need to think about expansion of product `type` property, for example, or maybe about adding some new prop. I like this approach - #152. We could add `itemType` as the stub for now. @aaronjudd, any thoughts?

**Comment by aaronjudd** [comment]
@newsiberian thinking about this and will respond soon.

for reference: Related to #609

**Comment by newsiberian** [comment]
Hello, @aaronjudd, if you are interested in current progress, it could be found [here](https://github.com/newsiberian/reaction/blob/cleanup_mergeCart/packages/reaction-core/server/methods/cart.js#L1-L36) and [here](https://github.com/newsiberian/reaction/blob/cleanup_mergeCart/packages/reaction-core/server/methods/cart.js#L283)
