### ISSUE TITLE
Are there any payments processing for israel?

### ISSUE THREAD

**Issue by benag** [reactioncommerce/reaction#622]

**Comment by zenweasel** [comment]
Stripe supports payments in multiple countries and currencies. Was there a particular processor you were looking for?

**Comment by benag** [comment]
They dont work in Israel both stripe and BrainTree. I might need to create a plugin to work with local providers.

**Comment by aaronjudd** [comment]
@benag do you have a provider in mind that would work?  Also, @zenweasel  is working on https://github.com/reactioncommerce/reaction-paymentmethod which is just a basic outline - a shell for creating new payment methods from.  This should help to create new payment methods more easily.

**Comment by zenweasel** [comment]
@benag My mistake, I apologize. That package still needs a little polish (tests and docs mostly) but it should be good to try and create a payment method. I can try to help you through it if you want.

**Comment by zenweasel** [comment]
Now that https://github.com/reactioncommerce/reaction-paymentmethod is final anyone can use this to create their own payment package or anyone can contact me directly for help but we don't have any plans to add any "official" packages beyond the five we support. (although if we found one really good one that applied to a lot of developing nations we might reconsider).

I am closing this ticket for now as there is no work to be done.
