### ISSUE TITLE
Multiple product options for product

### ISSUE THREAD

**Issue by PaulSavignano** [reactioncommerce/reaction#623]
Hello, I am creating a package product that enables buyers to choose 8 out of a possible 10 items (and multiples of a given item if desired) for one package price. How can this be created using reaction commerce? To note, the product does not change price as each item is selected (for a minimum/maximum of 8). The package price is constant.

Any help would be greatly appreciated, thanks for the great platform!

**Comment by aaronjudd** [comment]
Closing - insufficient details.
