### ISSUE TITLE
Taxes don't get applied to the cart, always stay at 0

### ISSUE THREAD

**Issue by karbal** [reactioncommerce/reaction#6231]
## Setting Taxs
![alt](https://files.gitter.im/reactioncommerce/reaction/nfsm/image.png)
## Setting Product
![alt](https://files.gitter.im/reactioncommerce/reaction/FeSd/image.png)
## Cart
![alt](https://files.gitter.im/reactioncommerce/reaction/0Xyd/image.png)

**Comment by loan-laux** [comment]
Fixing as part of [api-plugin-taxes-flat-rate#3](https://github.com/reactioncommerce/api-plugin-taxes-flat-rate/issues/3).

**Comment by loan-laux** [comment]
Should be fixed now as part of `api-plugin-taxes-flat-rate@1.0.1`.
