### ISSUE TITLE
Ability to Process Returns 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#6241]
**Requirements** 

For iteration one, we are going to assume that the customer has initiated a return via email, phone or a 3rd party customer support platform. 

**Steps** 

- Generate RMA and trigger email to customer (How long they have to return the item, shipping info for where to ship, packaging instructions)
- Generate shipping label or attach shipping label to email
- Mark items as received (and QA items - damaged, not damaged etc) - trigger email
- Return to stock or not?
- Issue Refund  - trigger email

**Comment by Upinder123** [comment]
can i help ?
