### ISSUE TITLE
createMediaRecord with "tempStoreId: undefined" crashes api server

### ISSUE THREAD

**Issue by rogersoares** [reactioncommerce/reaction#6242]
## Issue Description
When calling graphql mutation createMediaRecord, and passing an invalid tempStoreId, the whole api server crashes with:

api_1    | 04:40:46.715Z  INFO Reaction: Stopping Reaction API...
api_1    | [Error: EISDIR: illegal operation on a directory, read] {
api_1    |   errno: -21,
api_1    |   code: 'EISDIR',
api_1    |   syscall: 'read'
api_1    | }
api_1    | [nodemon] app crashed - waiting for file changes before starting...

## Steps to Reproduce

        const queryCreateMediaRec = `mutation CreateMediaRecord($input: CreateMediaRecordInput!) {
          createMediaRecord(input: $input) {
            mediaRecord { _id }
          }
        }`
        console.log("tmpStoreId: " + **tmp**StoreId)
        client.request(queryCreateMediaRec, {
          input: {
            shopId: SHOPID,
            mediaRecord: {
              original: {
                name: "southpark1.jpg",
                size: 62698,
                type: "image/jpeg",
                updatedAt: "2020-05-05T05:12:07.000Z",
                uploadedAt: "2020-05-05T04:52:36.562Z",
                tempStoreId: **temp**StoreId,
              },
              metadata: {
                productId: "cmVhY3Rpb24vcHJvZHVjdDpSNExOcnoyOXZkbmtqWnBUZg==",
                priority: 2,
              },
            }
          }
        }).then(dataMediaRec => {
          console.log("Media Record: " + dataMediaRec.createMediaRecord.mediaRecord._id);
        })

## Possible Solution

Validate that tempStoreId file exists before creating the MediaRecord entry.

### Versions

3.7.0

**Comment by trojanh** [comment]
@aldeed I would like to know your take on this fix:
1. import `tempStore` from `setUpFileCollections` in `/api-plugin-files/src/mutations/createMediaRecord` . 
2. Check if `tempStore.exists(tempStoreId)` is false in `createMediaRecord` and send appropriate error response before validation
