### ISSUE TITLE
Make init-dev command in reaction-development-platform doesn't work 

### ISSUE THREAD

**Issue by Prodigy343** [reactioncommerce/reaction#6247]
## Issue Description
I'm trying to setting up the environment development but the admin container get down after 2 minutes and the log of the container says:

Failed to reset plugins file at /usr/local/src/app/client/plugins.js (image below)
![image](https://user-images.githubusercontent.com/19996197/82170376-3b8d8900-9892-11ea-9866-cfc2241930a0.png)

The other containers looks good.

Thanks in advance.

## Steps to Reproduce
1. git clone git@github.com:reactioncommerce/reaction-development-platform.git
2. cd reaction-development-platform
3. make init-dev

### Versions
3.7.1

**Comment by loan-laux** [comment]
@Prodigy343 This is related to `reaction-admin`. I would recommend moving the issue over there.

**Comment by Prodigy343** [comment]
[Continue here](https://github.com/reactioncommerce/reaction-admin/issues/281)
