### ISSUE TITLE
Linked packages don't get updated with new changes

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction#6250]
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Linking a package with `bin/package-link` works fine. However, linking this same package a second time, once changes were made locally, doesn't update the one in the container. It doesn't matter whether you unlink the package before re-linking it. The behavior is the same.

## Steps to Reproduce
1. Link a package with `bin/package-link`. For the sake of having something to compare, include a `Logger.info("Hello World")` in a query resolver, for example.
2. Call this query, and notice the `Hello World` being printed in the server logs.
3. Remove the `Logger.info` line from the local copy of the package.
4. Unlink this same package with `bin/package-unlink`, then re-link it with `bin/package-link`.
5. After the API has restarted, call the same query again and notice the `Hello World` being printed, even though the `Logger.info` call was removed.

## Possible Solution
Maybe this is due to some NPM cache or something. There's probably a `--no-cache` flag we can use when linking/unlinking packages.

**Comment by aldeed** [comment]
I saw this but it wasn't quite as straightforward as you describe. If I repeatedly tried different things like updating the log text and/or unlink/relink, it would sometimes work correctly a second time but then go back to not working.

**Comment by aldeed** [comment]
Another possibility is something to do with Docker volume links. I am on Mac OSX and I have sometimes seen weirdness that makes me think nested folders within `node_modules` can "bleed" through from the host machine even though all of `node_modules` is supposed to be a Docker volume.

And related to that, there is both a local volume for the run and the `node_modules` volume, and I think those sometimes get mixed up or clash with each other. I wish I could describe it better, but it's very confusing.

**Comment by loan-laux** [comment]
I've investigated this a bit deeper, and it looks like somehow, after re-linking the `api-plugin-products` package, it actually linked the newest version **inside of the previously linked one**:

<img width="819" alt="Screen Shot 2020-05-20 at 19 22 21" src="https://user-images.githubusercontent.com/45489203/82477108-3e28f200-9acf-11ea-8b78-9f739c9d8555.png">

If this screenshot isn't clear, this is what it looks like:

```
node_modules
 |- @reactioncommerce
 |   |- api-plugin-products
 |       |-api-plugin-products
 |          |- index.js
 |          |- src
 |          |- etc...
 |       |- index.js
 |       |- src
 |       |- package.json
 |       |- etc...
```

So instead of replacing the old version, the new one ended up inside of it. This could be an issue with symlinks not being replaced or something. Maybe we need `bin/package-link` to internally run `bin/package-unlink` before doing an `npm link`.

**Comment by loan-laux** [comment]
Back with some other observations... It's getting crazy, to the point that I can't work anymore.

I've tried to `rm -rf` my linked package from the API's `node_modules` through the container's bash shell. I also tried to `rm -rf` the package from `/home/node/copied-packages` to really make sure that there's no old copy left anywhere.

Then, re-linking this same package with `bin/package-link`, nothing changes even though now I can see my new files present in the API's `node_modules`!

I've even tried all of the above, did an `npm rm <package>` at the API's root, and then re-linked the same package. The result is the same. My old code gets ran and none of my modifications take effect.

Now that's an interesting mystery. But what I can say is that it's very problematic for my daily workflow, so I'm gonna hunt this down until I solve it.

**Comment by aldeed** [comment]
@loan-laux Good find. I actually think I probably fixed this in https://github.com/reactioncommerce/reaction/pull/6251 Were you using that branch when you saw it linked inside itself?

The reason it did that after the first time is because of the way `docker cp` works. See the `SRC_PATH` / `DEST_PATH` logic flow here: https://docs.docker.com/engine/reference/commandline/cp/#extended-description

When the `DEST_PATH` already exists after the first time, its behavior changes to copying the directory rather than the files in it. I fixed it by adding `/.` suffix here: https://github.com/reactioncommerce/reaction/pull/6251/files#diff-688f55156dbdbf1e940841ae5b0cc97cR32

Using that PR branch this morning, it seems to be working fine for me now. On packages that you linked prior to my fix, you'll probably need to delete the `reaction_api_node_modules` volume as well as all local volumes and relink before the fix will work.

**Comment by loan-laux** [comment]
@aldeed This (linking inside of itself and not updating) actually doesn't seem to happen anymore while using your branch. I think we're good to go with this! Thanks for fixing it. 👍🏻
