### ISSUE TITLE
Crash on start: MODULE_NOT_FOUND error with apollo-engine-reporting > uuid

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction#6254]
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

On startup (working on the v3.8.0 codebase prior to release), the node server is crashing with this error:

```
(node:285) ExperimentalWarning: The ESM module loader is experimental.
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/**/*
[nodemon] watching extensions: js,cjs,mjs,json,graphql
[nodemon] starting `node ./src/index.js`
(node:315) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/cjs/loader.js:457
  const e = new Error(`Package exports for '${basePath}' do not define a ` +
            ^

Error: Package exports for '/usr/local/src/app/node_modules/apollo-engine-reporting/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:457:13)
    at resolveExports (internal/modules/cjs/loader.js:390:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/src/app/node_modules/apollo-engine-reporting/dist/agent.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10) {
  code: 'MODULE_NOT_FOUND'
}
[nodemon] app crashed - waiting for file changes before starting...
```

Researching online, I think this may be related to [this recent update to the uuid npm package](https://github.com/uuidjs/uuid/issues/444#issuecomment-631663778).

Our dependency graph to this looks like

```
a47c90cf3dfe:/usr/local/src/app$ npx npm-remote-ls apollo-server-testing
└─ apollo-server-testing@2.14.1
   │  ├─ apollo-engine-reporting@2.0.0
   │  │  ├─ uuid@8.1.0
```

We have at least 2 versions of uuid (probably many more), which look at a glance like they should be OK.

```
a47c90cf3dfe:/usr/local/src/app$ grep '"version":' node_modules/apollo-engine-reporting/node_modules/uuid/package.json node_modules/uuid/package.json
node_modules/apollo-engine-reporting/node_modules/uuid/package.json:  "version": "8.1.0"
node_modules/uuid/package.json:  "version": "3.4.0"
```
## Steps to Reproduce
1. Try to start reaction core

Note sure what else may be involved yet, still triaging.

### Versions
3.8.0

**Comment by focusaurus** [comment]
I tried updating to apollo-server-testing 2.14.1 but got the same error. It looks like uuid v8.1.0 is properly ready to support ES Modules, but maybe apollo-engine-reporting 2.0.0 is not.

**Comment by nchopra** [comment]
What node version are you using?
I faced the same issue while using `apollo-server-express` @ `2.14.1` yesterday, coming from the same module `apollo-engine-reporting` as you.
I was using node `13.1.0`, downgrading it to node `12.8.0` made it work.
Trying to figure out why.

**Comment by Vercryger** [comment]
I'm having this issue as well using `reaction-api@3.7.1`, I haven't found a workaround yet.

**Comment by focusaurus** [comment]
I'm working on the reaction v3.8.0 release which runs node 12.14.1

**Comment by amaster507** [comment]
I am running Node 13.2.0 and am getting the same problem. Just updated babel and did a fresh update and install of all modules and started getting this error.

**Comment by focusaurus** [comment]
I can no longer reproduce this and I don't understand repeatable steps to reproduce at the moment. It's the kind of thing that I would think a `docker volume rm reaction_api_node_modules` would fix but I was having the problem after doing that earlier this week, so still 🤷‍♂️ .

**Comment by abhishiv** [comment]
I just hit this is well. Must be something to do with babel-node, and node when experimentalModules is on.

**Comment by jose31canizar** [comment]
Updating babel with `npx babel-upgrade --write` fixes the problem in my case.

**Comment by brent-hoover** [comment]
I am seeing this as well using the current 3.8.0 version. Glad this issue was here to let me know it's somewhat Reaction-related

**Comment by brent-hoover** [comment]
I've tried all the workarounds mentioned here and still no luck. Interesting to note that I do not get this issue when building from the `node-prod:12.14.1-v3` image but do when building from the node/alpine image based on the current dev dockerfile

**Comment by loan-laux** [comment]
@zenweasel Did you manage to find a workaround that works?

**Comment by brent-hoover** [comment]
No. Just went back to my method of restarting the container.

**Comment by rochadsouzaiit** [comment]
I know that this is not the "real" answer, but I got this error, cloned (my) repo into another folder, `docker-compose up -d` and everything works -  came up to this "solution" cause my project only has a couple diff packages from the original one (`trunk`), and cloning and running the original repo, works for me.

I Tried:
- delete all containers and create them again;
- replace all files with the files from `trunk`

... and nothing work. Didn't found a real solution but found something that "did the job".

p.s: As you can see, there are a lot of `".."` 🙃

**Comment by rochadsouzaiit** [comment]
My Reaction Project only have a couple of plugins installed (for aws s3 storage and a custom IDP). What I did was clone the original project (`trunk`) and tried to run without my plugins - it worked. After that I added my plugins and... it worked again. Just on my project branch it not works...

ps.: in my case, with `node-prod:12.14.1-v3` I still got the same error.

**Comment by bjanssen-pon** [comment]
I'm having the same issue only with the dev mode (override of compose file). Did `docker system prune`, removed container and volume but did not fix the issue. I had it before, but for some reason that error fixed itself. Now stuck on this and I don't know how to fix it. In dev-mode without custom plugins it also doesn't work.

Node version: 12.14.1

**Comment by brent-hoover** [comment]
fwiw I have build a project with a minimal number of built-in plugins and was still running into this issue
```
  "dependencies": {
    "@reactioncommerce/api-core": "~1.4.0",
    "@reactioncommerce/api-plugin-accounts": "~1.4.5",
    "@reactioncommerce/api-plugin-authentication": "~1.2.0",
    "@reactioncommerce/api-plugin-authorization-simple": "~1.3.0",
    "@reactioncommerce/api-plugin-settings": "~1.0.2",
    "@reactioncommerce/api-plugin-simple-schema": "~1.0.1",
    "@reactioncommerce/api-plugin-shops": "~1.1.2",
    "@reactioncommerce/api-utils": "~1.14.5",
    "@reactioncommerce/logger": "~1.1.3",
    "@reactioncommerce/random": "~1.0.2",
    "graphql": "~15.3.0",
    "semver": "~7.3.2"
  },
```

Still had the same. However when I upgraded the build to Node 14.8 the problem went away

**Comment by focusaurus** [comment]
OK my comment in that PR closed this, which is probably a fairly optimistic take. If anyone has time to pull down the latest trunk branch of reactioncommerce/reaction and test whether both dev and prod mode work without any npm errors, that would be valuable confirmation.
