### ISSUE TITLE
Catalog items are not displayed in PDP when using slug to query the API

### ISSUE THREAD

**Issue by manueldelreal** [reactioncommerce/reaction#6256]
## Issue Description

Catalog items are not displayed in PDP when using slug to query the API

## Steps to Reproduce

1. Open your storefront with items in the catalog (or create a product and publish it)
2. Click on your product from the listing page

Expected results
Product details page loads and displays product properties as stored in the DB

Actual results
An error is displayed instead of product details. data returned has  is {"data":{"catalogItemProduct":null}}

**Comment by focusaurus** [comment]
@manueldelreal OK to close this as fixed in v3.8.0 by Mike?

**Comment by manueldelreal** [comment]
execute order 66...I mean, yes, let's close it.
