### ISSUE TITLE
Missing env var when running `reaction` via standalone NPM script i.e. outside Docker

### ISSUE THREAD

**Issue by bayareacoder** [reactioncommerce/reaction#6258]
I want to run the GraphQL API outside Docker by executing `npm start:dev` in `reaction` folder after installing npm modules.
Error shown:
Missing environment variables:
STRIPE_API_KEY: A private Stripe API key
although this key is set in the .env file.

I inspected the API plugins and see in the Stripe plugin that this key is required and is filled out with a default value but only when in test mode.
I changed `NODE_ENV` from `development` to `test` and then indeed there is no error.

So it seems you are not reading in env vars and so this cannot run outside Docker (although doc says it is possible but 'not recommended') ?

Versions

ReactionCommerce 3.7.1
Node 12.18.0
NPM 6.14.4

**Comment by loan-laux** [comment]
@bayareacoder If you're running Reaction outside of Docker, you'll have to set the environment variables yourself. This is normal behavior. Try doing `source .env` maybe.

However I'm not sure that this would qualify for an issue as we're not actively supporting this method. Perhaps [the Gitter channel](https://gitter.im/reactioncommerce/reaction) would be a better fit.

**Comment by focusaurus** [comment]
The `.env` file sets shell variables but does not export them to the environment. You may need this as well:

```
 export $(grep -v '^#' .env | cut -d = -f 1 | xargs)
```

Closing as that should get you going and we don't provide support for running outside docker.

**Comment by bayareacoder** [comment]
I am meanwhile focusing on Docker Deploy and found the Gitter Deployment chat room. One suggestion: have concrete step by step instructions on your website to deploy on popular cloud providers. Its not trivial with v3 and based on the chatroom many folks are struggling with it.
