### ISSUE TITLE
The public folder is not accessible from the url

### ISSUE THREAD

**Issue by karbal** [reactioncommerce/reaction#6260]
```js
const api = new ReactionAPICore({
  serveStaticPaths: ["public"],
  version: packageJson.version
});
```
Url : http://localhost:3000/public/resources/avatar.gif

**Comment by focusaurus** [comment]
Omit "public" from the web path like this:

http://localhost:3000/resources/avatar.gif

"public" is a directory on the filesystem but it represents the root ("/") of the web app and is not included in web paths.

**Comment by karbal** [comment]
@focusaurus Thanks is working but after i added this line in docker-compose
```yaml
volumes:
      # Core
      - ./src/core/ReactionApiCore.js:/usr/local/src/app/node_modules/api-core/src/ReactionAPICore.js
```
