### ISSUE TITLE
discountCodes query does not report edges, only nodes

### ISSUE THREAD

**Issue by bayareacoder** [reactioncommerce/reaction#6261]
## Issue Description
`discountCodes` query does not report edges, only nodes

## Steps to Reproduce
See attached image for a query that returns nodes but no edges.

## Possible Solution
Add edges in query response

### Versions
reaction-api 3.8.0

<img width="1393" alt="Screen Shot 2020-06-10 at 10 17 13 PM" src="https://user-images.githubusercontent.com/8239955/84347746-27266e80-ab68-11ea-86e0-2f83f87b8ac8.png">

**Comment by loan-laux** [comment]
I'll try to fix this one. Shouldn't take too long.
