### ISSUE TITLE
Paypal Express Checkout with any other currency than USD fails.

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#627]
Branch: Development

Paypal express checkout fails when using any other currency than USD:

URL /paypal/done can't be completed and shows a never-ending spinner, because of an server error when calling Paypal API method "DoExpressCheckoutPayment". It seems that this API call needs the Paypal Parameter CURRENCYCODE as well. At the moment, it is not supplied though.

Reproducing the error is easy. Just choose another currency in the Core settings and perform an Express Checkout.

**Comment by zenweasel** [comment]
@prinzdezibel I believe this is the same as this bug https://github.com/reactioncommerce/reaction-paypal/issues/21
There is a PR already open with a fix.

**Comment by prinzdezibel** [comment]
@zenweasel: Yes, that was the message I got in the browser's console. But it originates from a server side exception, I believe.

**Comment by zenweasel** [comment]
@prinzdezibel Yes you are completely correct. If you look at the PR it is basically just adding the CURRENCYCODE parameter to the API calls as you mentioned.

https://github.com/reactioncommerce/reaction-paypal/pull/22
