### ISSUE TITLE
GraphQL access denied even when the service is running

### ISSUE THREAD

**Issue by hamza0200** [reactioncommerce/reaction#6277]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?

## Issue Description
Sometimes when we login GraphQL access denied option comes up even when service is up, we have to refresh multiple times to login or in some cases the login works but the inner pages of admin causes issues. 

Please see the errors of console [here](https://imgur.com/a/x8UsRvu) .

## Steps to Reproduce
1. Login to [reaction admin](http://localhost:4080)
2. Navigate pages

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
Thanks for the reported issue, @hasan-synavos.

The `reaction-development-platform` repository is used to bootstrap the project and get it up and running, but issues regarding the API, Admin, Storefront, or anything outside the initial build are better suited in their respective project repositories.

This issues seems like it probably stems from user permissions in the API itself, so I'm going to move this ticket to the `reaction` repository.

**Comment by aboelela924** [comment]
so I am having the same issues I followed the documentation step by step but I still get access denied so do we have a solution?

**Comment by MohanNarayana** [comment]
@hasan-synavos @hamza0200 , can you please provide more details on the reproduction steps if possible. 
Do you see a WebSocket error on Reaction Admin console (localhost:3000/graphql failed)?
Have you set up hydra-token for graphQL playground?

**Comment by loan-laux** [comment]
Safe to say we can probably close this one.
