### ISSUE TITLE
Help! Looking for a mentor who can help me understand the basics of reaction commerce..

### ISSUE THREAD

**Issue by codemarvel** [reactioncommerce/reaction#6280]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact us instead. We are active in gitter and twitter:

- [Gitter](https://gitter.im/reactioncommerce/reaction)
- [Twitter](https://twitter.com/getreaction)

**Comment by balibebas** [comment]
https://habd.as/post/reaction-commerce-getting-started/

**Comment by balibebas** [comment]
https://habd.as/post/reaction-commerce-getting-started/
https://www.codementor.io/@jhabdas

Best to contact by email.
