### ISSUE TITLE
I would like to update UI 

### ISSUE THREAD

**Issue by phearakthefoundry** [reactioncommerce/reaction#6299]
Hi @loan-laux , I would like to customize UI of reaction commerce. How could I do ?. 
Now I try to update UI but it's not see what I change I don't know why.
I would like you help to tell me stab by step.
Thank you.

**Comment by nnnnat** [comment]
@phearakthefoundry thanks for your interest in Reaction but this isn't a help forum and is our issue tracker for the open source project. If you're looking for extra help on getting started with Reaction please ask your questions in our [gitter](https://gitter.im/reactioncommerce/reaction) chat.
