### ISSUE TITLE
when viewing page with options in url, unable to add additional options to cart

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#630]
Add option to cart, then select the option in the cart drawer.  Attempt to add another (different) option.

<img width="1126" alt="reaction___bctmz6htxfsppjesk" src="https://cloud.githubusercontent.com/assets/439959/12054434/7b00296a-aed8-11e5-96bc-3b8166640fe9.png">

**Comment by tcheyne** [comment]
Can I try giving this a shot? Never worked on the project before, but interested in jumping in.

**Comment by aaronjudd** [comment]
@tcheyne never hurts to try! we'll gladly accept a PR for this.
 
Heads up though, this could range from a simple fix, to a lengthy tour of Reaction ;-).  I've not looked into this but I'd start by looking at product handling in packages/core/common/router.js, followed by the add-to-cart event hooks. 

This feels like a newly introduced bug, so we should probably require some level of testing as well. This may not have had tests yet as it's a bit of UI / edge case I suspect.

**Comment by tcheyne** [comment]
@aaronjudd I found a simple solution for fixing the bug! Only adding to a single line in router. I'll see if I can write a test or two to cover the bug and then issue a PR

**Comment by newsiberian** [comment]
I want to revert this changes in next PR, because, suddenly, I was faced with a bug, introduced, by #632. Short description: when user enters into PDP, variant is not selecting by `setCurrentVariant` method. It is reproducible in `development`. Just create few products and jump over them.

**Comment by aaronjudd** [comment]
Should be resolved in https://github.com/reactioncommerce/reaction/pull/783
