### ISSUE TITLE
reaction init not working

### ISSUE THREAD

**Issue by homero-gg** [reactioncommerce/reaction#6304]
I am trying to install reaction on Windows 10 but when I put the reaction init command its said that the branch is not found
![reactionproblem](https://user-images.githubusercontent.com/72879207/97602307-61ce5d80-19c8-11eb-93f5-21b6d9786d1a.PNG)

**Comment by nnnnat** [comment]
@homero-gg looks like you're trying to use the reaction cli that was [deprecated in v2](https://docs.reactioncommerce.com/docs/3.7.0/reaction-cli). We'd suggest trying the [reaction-development-platform](https://github.com/reactioncommerce/reaction-development-platform/tree/trunk) to get up and running with the latest version of Reaction Commerce.

**Comment by homero-gg** [comment]
Okey than. Now when I trying to run the make command its said that I don't have the cut command
![reactioncut](https://user-images.githubusercontent.com/72879207/97605655-22a20b80-19cc-11eb-9598-2fab931a4795.PNG)

**Comment by nnnnat** [comment]
You'll need to use something like cygwin for Windows to have access to the required unix commands the developer platform uses. While it's possible to run the developer platform on windows we're not explicitly supporting that OS at this time. Please ask your question in our [gitter](https://gitter.im/reactioncommerce/reaction) chat and you'll hopefully find better windows guidance there.
