### ISSUE TITLE
http://localhost:3000/ cannot GET/ error

### ISSUE THREAD

**Issue by eneskeremturan** [reactioncommerce/reaction#6305]
I uploaded the reaction commerce step by step according to the documents (https://docs.reactioncommerce.com/docs/installation-reaction-platform) .i use windows 10. i access all pages but when enter http://localhost:3000, it gives an error. Error is: 

![Ekran Alıntısı](https://user-images.githubusercontent.com/50349426/97864011-fa424600-1d18-11eb-93d2-bbbd38b54bc7.PNG)

what should i do to fix the error ?

**Comment by janus-reith** [comment]
Hi @eneskeremturan ,
http://localhost:3000/ is not supposed to show you anything, the graphql api however is available on http://localhost:3000/graphql (Shows GraphQL Playground if you open it in your browser).
The storefront listens on http://localhost:4000

Running `docker ps` should give you an overview on all running containers and the ports they're listening on.
