### ISSUE TITLE
Fresh Install, Admin Page Failing to Render

### ISSUE THREAD

**Issue by excisionhd** [reactioncommerce/reaction#6316]
## Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you able to consistently reproduce the issue?
* [ x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

Just did a fresh clone of the repository, and followed installation instructions at https://docs.reactioncommerce.com/docs/installation-reaction-platform 
(Some of the default ports need to be updated in the URL table.).
Subsequently after starting all the docker containers, registering an admin, and navigating to any of the pages seem to point to undefined (see images).

![image](https://user-images.githubusercontent.com/32623341/103994032-4d86a980-514b-11eb-92b5-1abb583aa98f.png)
![image](https://user-images.githubusercontent.com/32623341/103994383-c71e9780-514b-11eb-9ea1-300725eb6684.png)

## Steps to Reproduce

1. Fresh install with git clone and make.
2. Navigate to http://localhost:4080/
3. Created first admin account.
4. Clicking on Orders, Products, Tags, Accounts, and Navigation yields undefined redirects -> (http://localhost:4080/undefined/orders) or pages failing to render.

## Possible Solution

Not entirely sure if I followed legacy installation documentation and am not sure how to approach this.  Any help would be appreciated.  Thank you!

### Versions

Reaction-commerce: 3.0.0-beta.11

**Comment by Eduard-Hasa** [comment]
Instead of posting a bug the proper approach would be first troubleshooting your other services that the admin platform depends on. Nothing is rendering meaning the other service (reaction api) must not be functioning properly. You can troubleshoot this by looking into the docker container's logs. Start with the reaction container that hosts the api and im willing to bet you are facing the mango replica error that can be resolved with the following unpublished/temporary workaround.

https://github.com/reactioncommerce/reaction/issues/6315#issue-770501209

**Comment by excisionhd** [comment]
@Eduard-Hasa 
Thanks for the advice.  The issue was not exactly the same that you referenced. 
```
api_1    | 07:54:16.185Z  INFO Reaction: Initializing MongoDB replica set...
api_1    | 07:54:16.188Z  INFO Reaction: Connecting to MongoDB...
mongo_1  | 2021-01-10T07:54:16.221+0000 I  NETWORK  [listener] connection accepted from 172.19.0.7:34724 #35 (5 connections now open)
mongo_1  | 2021-01-10T07:54:16.235+0000 I  NETWORK  [conn35] received client metadata from 172.19.0.7:34724 conn35: { driver: { name: "nodejs", version: "3.6.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.125-linuxkit" }, platform: "'Node.js v14.15.0, LE (unified)" }
api_1    | 07:54:16.250Z  INFO Reaction: Connected to MongoDB. Database name: reaction
mongo_1  | 2021-01-10T07:54:16.259+0000 I  NETWORK  [listener] connection accepted from 172.19.0.7:34726 #36 (6 connections now open)
mongo_1  | 2021-01-10T07:54:16.260+0000 I  NETWORK  [conn36] received client metadata from 172.19.0.7:34726 conn36: { driver: { name: "nodejs", version: "3.6.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.125-linuxkit" }, platform: "'Node.js v14.15.0, LE (unified)" }
```

Though, your advice did help me pinpoint the issue related to migrations:
```
api_1    | 07:54:17.011Z  INFO Reaction: Running pre-startup function "preStartup" for plugin "authorization-simple"...
api_1    | 07:54:17.014Z ERROR Reaction: Database needs migrating. The "simple-authorization" namespace must be at version 5. See docs for more information on migrations: https://github.com/reactioncommerce/api-migrations
api_1    |   Error: Database needs migrating. The "simple-authorization" namespace must be at version 5. See docs for more information on migrations: https://github.com/reactioncommerce/api-migrations
api_1    |       at Object.preStartup [as func] (file:///usr/local/src/app/node_modules/@reactioncommerce/api-plugin-authorization-simple/src/preStartup.js:38:11)
api_1    |       at processTicksAndRejections (internal/process/task_queues.js:93:5)
api_1    |       at async ReactionAPICore.runServiceStartup (file:///usr/local/src/app/node_modules/@reactioncommerce/api-core/src/ReactionAPICore.js:371:9)
api_1    |       at async ReactionAPICore.start (file:///usr/local/src/app/node_modules/@reactioncommerce/api-core/src/ReactionAPICore.js:575:5)
api_1    |       at async runApp (file:///usr/local/src/app/src/index.js:19:3)
```

Thanks!
