### ISSUE TITLE
Squash.io integration?

### ISSUE THREAD

**Issue by emiquelito** [reactioncommerce/reaction#6322]
Hello Reaction Community!

I'm with [Squash.io](https://www.squash.io/) and we wanted to support the Reaction project by providing on-demand test environments for each Pull Request (i.e: a complete staging environment for each PR, running your full stack). Our service is free for Open Source projects like Reaction and we would be able to increase our standard limits as needed to provide great user experience for Reaction developers and contributors.

Here is how it works, you push a branch of code, create a Pull Request and Squash automatically posts a comment with a unique URL where you can test the branch changes in isolation (it usually takes just a few minutes for an environment to spin up):

![squash-url](https://user-images.githubusercontent.com/98694/108773052-0c8bfe00-751b-11eb-8fad-7334b11b80bf.png)

Squash can also spin up a new environment for each commit within a PR, and give you a pass or fail if it can receive a success HTTP response. You can also run any existing front-end tests (Selenium, TestCafe, etc.) on top of this Squash environment.

![squash-check2](https://user-images.githubusercontent.com/98694/108773348-6ee4fe80-751b-11eb-92e3-d9262192264e.png)

### Squash setup

Let me know if you like the idea of using Squash on this project. If so, we would be happy to create a Pull Request with a Squash YAML file so you don't have to invest any time on this.

**Comment by emiquelito** [comment]
@nnnnat @aldeed @focusaurus sorry but just wanted to confirm if closing this issue was intentional or by accident. If it was intentional would you mind providing any feedback? I love Reaction and was hoping to bring value and support the community, I'm not trying to sell anything here, Squash is free for Open Source.

With that being said I totally understand if you believe that creating this issue wasn't the best way to propose this idea or if it has created any annoyances, I will refrain from posting any other comments if that's the case. 

Have a great day.

**Comment by nnnnat** [comment]
Hey @emiquelito this issue was closed intentionally, mainly because this isn't the appropriate forum to solicit your product regardless of price point and we're not interested at this time.
