### ISSUE TITLE
Let plugins feat update happen automatically.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#6328]
## Current System:
Right now all the plugins in `package.json` have `~` before package version, which mean they only get patch updates.

### Cons:
1. Once we do a minor upgrade of a plugin, any patch update after that doesn't get fetched by reaction (because the patch update is only on the latest version)
2. Makes the release process hard since someone has to look for the latest version of plugin and make a PR into reaction.
3. Make the process of merging features and getting them deployed long because of the above reason.

### Pros:
1. Since the release is QAed, we are confident that the release works.
2. If someone messes up something in a plugin, the main product won't be harmed.

## Proposal:

Let's replace `~` with `^` and allow minor upgrades to plugins. This will help deliver features directly to the users faster.
But it would come with more responsibility of making sure that plugins are not broken while merging PRs.

In case they are broken by a PR, we can do a patch release to fix the issue and hopefully minify the damage.

Please let me know what people think about this in the comments.

**Comment by loan-laux** [comment]
I fully support this. Nothing to add.

**Comment by loan-laux** [comment]
One thought though: we have integration tests in the `reaction` repo that might break.
