### ISSUE TITLE
#629 broke reaction run/debug script

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction#633]
`./reaction` and `./reaction debug` no longer work on OSX after #629 was merged

**Comment by prinzdezibel** [comment]
@jshimko: Are you using settings.json or dev.settings.json. I ask because I realise I've vorgotten to remove the parenthesis when passing the ARGS variable for the first case (settings.json). I assume this is the reason.

**Comment by prinzdezibel** [comment]
@jshimko: Thanks for fixing. I should have tested it more thoroughly.

**Comment by jshimko** [comment]
I have both of those settings files.  That wasn't the only issue though.  There were several.  I'll start from the top...  :)

These should always be the top of the file...

```sh
set -u
set -e
```

Next, your `if` statement was broken.

This...

```sh
if [ $1 = 'debug' ]; then
```

needed to be this...

```sh
if [[ $1 = 'debug' ]]; then
```

However, I replaced it with the following because it allows _any_ of the args to be `debug` and still preserves the same behavior.

```sh
if [[ "$@" = *"debug"* ]]; then
```

After that, I found your arg processing to be a little more complicated to read than it needed to be, so I simplified it.  Your code...

```sh
if [ $1 = 'debug' ]; then
  cmd=debug
  # strip away the debug option
  TMP_ARGS=()
  for var in "$@"; do
     # strip out debug argument
     [ "$var" != 'debug' ] && TMP_ARGS+=("$var")
  done
  ARGS=${TMP_ARGS[@]}
else
  cmd=run
  ARGS=$@
fi
```

could be simplified to...

```sh
if [[ "$@" == *"debug"* ]]; then
  CMD=debug
else
  CMD=run
fi

# remove debug arg if it exists
ARGS="${@//debug}"
```

And then finally, yes, the quotes needed to be fixed in the Meteor commands.
