### ISSUE TITLE
Failed fetching exchange rates

### ISSUE THREAD

**Issue by marcimarc16** [reactioncommerce/reaction#6344]
Hi, I'm a newbie, using rotki since yesterday. Today I'm getting this message and the Dashboard won't show the total amount:

> Failed fetching exchange rates: {"currencies": {"6": ["Unknown asset CAD provided."], "9": ["Unknown asset BRL provided."]}}

I haven't even heard of "CAD" or "BRL" before but I deleted a bunch of assets in the tool, hoping to speed things up with that. Could this be the reason for the message?

BR

**Comment by loan-laux** [comment]
@marcimarc16 which version are you using? Support for exchange rates was removed in `3.0.0`, so you seem to be using a deprecated version of Reaction Commerce.

**Comment by marcimarc16** [comment]
Thanks for the answer, looks like I'm on 1.19.1. Not the latest?

**Comment by marcimarc16** [comment]
I think my question is displaced here - I'm also new to github and disoriented. Sorry, this "issue" can be regarded as closed.
