### ISSUE TITLE
CORS failiure in dev

### ISSUE THREAD

**Issue by meiremans** [reactioncommerce/reaction#6351]
Prerequisites
* [ X] Are you running the latest version?
* [ X] Are you able to consistently reproduce the issue?
* [ X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)
-->

## Issue Description
So i'm trying to make a new plugin.
For this i am following this guide. https://docs.reactioncommerce.com/docs/next/core-plugins-developing#switching-to-development-mode.

This guide mentions to bring everything up with make.
This works perfect and my admin panel and store are as expected.
after that i switch reaction to dev mode by "make dev-reaction"
now when i go to the store, the page loads but no products.
When i go to the admin panel, the panel loads,but no menu.

In the browser console i see multiple CORS errors on the graphql endpoint.

## Steps to Reproduce
1.make
2.make dev-reaction
3.go to admin panel
4. see the fault

### Versions
3.13.2

**Comment by MohanNarayana** [comment]
Hi @meiremans can you verify if all the services are up by running `docker ps` in your terminal. There are 7 reaction_api_1, example-storefront_web_1, reaction-admin_reaction-admin_1, reaction-identity_identity_1, reaction_mongo_1, reaction-hydra_hydra_1, reaction-hydra_postgres_1. 
Also, is GraphQL running on http://localhost:3000/graphql ?

**Comment by delagroove** [comment]
is this still an issue in v3.13.4? @meiremans

**Comment by delagroove** [comment]
please reopen in case CORS issues reveal again.
