### ISSUE TITLE
https://reactioncommerce.com/ is down

### ISSUE THREAD

**Issue by developez** [reactioncommerce/reaction#6360]
The website is https://reactioncommerce.com/, where can I find the documentation of the project?

**Comment by brent-hoover** [comment]
https://mailchimp.com/developer/open-commerce/

**Comment by developez** [comment]
There is a problem with the get starter kit.

![image](https://user-images.githubusercontent.com/1931408/132371108-d7fe95b8-0652-4ac8-adbf-856db7ff8b3d.png)

**Comment by Akarshit** [comment]
@developez If you need support with issues like this, our Discord server might be the best place to ask: https://discord.gg/Bwm63tBcQY

**Comment by iamzozo** [comment]
The description for the this repo still contains the wrong link.
