### ISSUE TITLE
build plugin for Mailchimp transactional

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#6361]
More details will be added as I find them.

**Comment by delagroove** [comment]
- being a full replacement of api-plugin-email (email-smtp)
- being able to send order confirmation emails
- being able to send order refund emails
- being able to send order shipment confirmation emails.

api-plugins:
email
email-smtp
email-templates

**Comment by brent-hoover** [comment]
@Akarshit Have you done any work on this? If not I want to either close it or move to the backlog for now

**Comment by brent-hoover** [comment]
@Akarshit Second call for the status on this. Can we close this for now until we revisit for Partner Integrations

**Comment by brent-hoover** [comment]
I think we just wrote a doc for this since it's just setting the SMTP_SERVER env var?
