### ISSUE TITLE
[Research] Building plugin for Marketing API

### ISSUE THREAD

**Issue by delagroove** [reactioncommerce/reaction#6370]
## Acceptance Criteria
The integration must cover most of the features that appear in other commerce integrations, such as the ones mentioned below.

## Elements to review

- purchase activity segmentation
- e-commerce tracking and reports... contents? (https://mailchimp.com/developer/marketing/api/location-reports/)
- Product content block ... how it will interact?
- Product Recommendation content block ... how it will interact?
- Promo Code content block ... how it will interact?
- Order notifications (notify to mailchimp)
- Abandoned cart email
- Product retargeting email... research
- Pop-up signup form
- Google remarketing ads

api-plugins involved:
api-plugin-cart
api-plugin-products

**Comment by MohanNarayana** [comment]
**Steps**

**User authentication:**
Set up OAuth communication on the store server via a plugin. https://mailchimp.com/developer/marketing/guides/access-user-data-oauth-2/


**Sync store data with MC.**
Bulk upload using batch operations to support the data load. https://mailchimp.com/developer/marketing/guides/run-async-requests-batch-endpoint/ 
Best order is to create a store and sync customer and product data, which is independent data. Next sync orders and carts which inturn references customer and product data using IDs

**Merge Field/ Merge Tags**
Required for organizing contacts and used for campaigning and targeting audiences. Shop owner creates tags. https://mailchimp.com/developer/marketing/guides/organize-contacts-with-tags/ 
https://mailchimp.com/developer/marketing/docs/merge-fields/

**Comment by brent-hoover** [comment]
No plans to work on integrations currently
