### ISSUE TITLE
Categorical Navigation in Reaction E-Commerce

### ISSUE THREAD

**Issue by price2b** [reactioncommerce/reaction#638]
Which is the best way to create Categorical Navigation for a tree of categories. For Categorical Navigation I mean: to Empower customers to quickly pinpoint products across the entire virtual storefront with guided navigation.

I have the following tree of categories:

Computers/
Computers/Computer Accessories/
Computers/Computer Accessories/Laptop Cases & Bags
Computers/Computer Accessories/Laptop Batteries
Computers/Apple Desktops
Computers/Apple Laptops & Notebooks

Checking Tags I found that its possible to create idle categories. I found that it displays field "isTopLevel" but I cannot find a field displaying -> "parentCategory" or similar. which is the best way to create a category tree. Thank you so much!
Sebastian.

**Comment by newsiberian** [comment]
Hi, I have an idea about categories. There's some work going slowly on the new flattened schema for products :smile: So where will be separate schemas for products and variants[options]. I thinking about adding additional schema for categories there. In my mind categories is the similar like products - they also have an image(s), description, title, maybe something more, but also have an internal list of products or subCatagories.

So I see the following process: if you want to create category - you just create/update new product. Then in right admin menu push the magic button - **transform product to category** and after that you'll get the same item on `productGrid` but without price and maybe with some border to distinguish category from product. As I said before, internally category could have the similar interface like product have with small difference.

So if Ongo folks approves this idea, maybe someday we will see something similar

**Comment by mikemurray** [comment]
@price2b Do you mean something like this: https://github.com/reactioncommerce/reaction/issues/558

Work has been stared on that in this branch
https://github.com/reactioncommerce/reaction/tree/navigation-558

**Comment by price2b** [comment]
yes @mikemurray that is what Im looking for. hope to see it soon. thank you!.
