### ISSUE TITLE
Error "Invalid username" in create user mutation 

### ISSUE THREAD

**Issue by blackspider1994** [reactioncommerce/reaction#6399]
CreateUser muation throws invalid username error when trying to create user with username and password, and username is only numbers.

1. Call createUser mutation with username and password fields only
2. Pass 03226776543 as username.

## StackTrace
{
  "errors": [
    {
      "message": "Invalid username",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createUser"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "InvalidUsername",
          "stacktrace": [
            "Error: Invalid username",
            "    at AccountsPassword.createUser (/usr/local/src/app/node_modules/@reactioncommerce/api-plugin-authentication/node_modules/@accounts/password/lib/accounts-password.js:321:19)",
            "    at AsyncFunction.createUser (/usr/local/src/app/node_modules/@reactioncommerce/api-plugin-authentication/node_modules/@accounts/graphql-api/lib/modules/accounts-password/resolvers/mutation.js:29:45)",
            "    at typeResolvers.<computed> (/usr/local/src/app/node_modules/@reactioncommerce/api-plugin-authentication/node_modules/@graphql-modules/core/dist/index.cjs.js:1159:65)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "createUser": null
  }
}

## Possible Solution
There is some sort of validation on username which only accepts alphanumerics. change it to accept numerics and alphabets also

**Comment by MohanNarayana** [comment]
@blackspider1994 This is a `accounts-js` condition. It accepts alphanumeric username but it has to start with a letter. The regex testing the username is `/^[a-zA-Z][a-zA-Z0-9]*$/`

**Comment by MohanNarayana** [comment]
@zenweasel I think we can close this since the validation happens in the accounts-js library. Kept it open to hear any feed back from the issue reporter. Any thoughts?

**Comment by brent-hoover** [comment]
@MohanNarayana I think it would be valuable to go back to the `accounts-js` team and get clarification on why that limitation exists. Also I don't think 3 days which spanned a weekend is enough time to get feedback from a user. Also if we want feedback from the user we should probably ask a specific question.

I have had a couple of interactions with the accounts-js team and they seem to be pretty responsive. Let's at least try that before we close this issue.

**Comment by MohanNarayana** [comment]
@blackspider1994 You can override the validation using [validateUsername](https://www.accountsjs.com/docs/api/password/interfaces/accountspasswordoptions/#optional-validateusername). Unfortunately I am not able to get it to work as expected. I am having a [discussion](https://github.com/accounts-js/accounts/discussions/1213) with accounts-js team to figure out how it should work. Maybe you will have better luck getting it to work. Please do let me know if you give it a shot.

**Comment by blackspider1994** [comment]
@MohanNarayana Thankyou for the help, I'll give it a shot

**Comment by MohanNarayana** [comment]
Closing as no fix/change is required.
