### ISSUE TITLE
Build reference implementation that is built from trunk and every PR

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6406]
Any time a PR is opened on any of the key projects (i.e. a PR gets merged to trunk) the CI/CD systems should build the all the apps (storefront/admin/core) and deploy them to a publicly available URL and validate that the apps load (no E2E testing now)

This can be similar to deployments under "Delightful Deployments" in that it does not need to be a production-ready deployment and can just use a long-standing mongo server that does not need to get rebuilt.

Please work with with @delagroove who can help you with figuring out how we we go about getting some resources allocated to us from MC.

**Comment by RickyHolland** [comment]
Hey @delagroove. 

As discussed by Brent above we are currently looking to create a permanent deployment of MOC that is based upon the latest container images available for API, Admin and Example-Storefront services. With the live deployment automatically updated as and when new container images become available.

There are a couple of things I believe that we will need to support this in the long term;

* Suitable hosting. We will require a VM/VPS of some form upon which MOC will be hosted. This VM doesn't need to be too powerful just the minimum required to host MOC and a MongoDB replica set. I can get more specific resource requirements if needed. 
* A suitable domain name (and external DNS records) to access this MOC deployment from, that supports subdomains. (e.g. api.domain.com, admin.domain.com, store.domain.com).

Would you be best placed to assist with the procurement of these resources or if not, could you please direct me at the relevant person at MailChimp? Thank you.

**Comment by brent-hoover** [comment]
This is now available here:

API URL: https://api.open-commerce.io/graphql
Admin URL: https://admin.open-commerce.io/
Storefront URL: https://storefront.open-commerce.io/en?
