### ISSUE TITLE
Create shop access denied

### ISSUE THREAD

**Issue by Giancarlo-Ma** [reactioncommerce/reaction#6424]
## ❓ Questions and Help

I clone the repo and run make. Then I  register a user on my local pc, but when I create shop an error occured showing that access denied. And I inspect the log of the reaction container, I found that token invalid. But my request indeed has a bearer token there. I am curious that whether or not I do sth wrong. Hoping your help

### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact us instead. We are active on Discord:

- [Discord](https://discord.gg/Bwm63tBcQY)

**Comment by brent-hoover** [comment]
Try clearing all your cookies and local cache and try again. If you have more issues please contact us on Discord, do not open another issue
