### ISSUE TITLE
SPIKE: Discovery work on NextJS Storefront

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6425]
This ticket is for Discovery work only, does not include any implementation

1. Define the level of effort in creating an Open Commerce package underneath[@vercel/commerce/packages](https://github.com/vercel/commerce/tree/main/packages) This should include a rough time estimate.
2. Lay out a high-level roadmap and the elements involved in this exercise.
3. What platform/package specific decisions do we need to make?
4. How can we extend the Next.js storefront to ensure we can introduce components beyond what may be in Next.js’s base implementation? Redeeming discount codes for example.
5. Should the Open Commerce package use Tailwind CSS given their eCommerce components? Is that even a decision we have as a package within @vercel/commerce?
6. How should we structure out repos so that it's easy to maintain this project over time
7. How do we structure the implementation to allow for integration with things like Contentful?
8. Determine which, if any of the requirements below will require any custom work or components 

The bare minimum for an implementation should include at least:

1. There is a "home page" that shows featured products
1. You can browse categories that are dynamically created in OC
1. You can view a detail page for a product
1. PDP displays all images
1. PDP displays price
1. PDP displays description 
1. You can add to cart, remove items from cart, or change quantity of items ordered 
1. You can check out using whatever shipping methods are configured
1. You can check out using whatever payment methods are configured. We can ship with just Stripe and the "Example Payment Method" but it should show whatever methods are configured to be available)
1. Checkout via anonymous user

Additional implementation should allow for:

1. Using discount codes
1. Address validation
1. Create account and checkout as logged in user
1. You can view order status for a logged in user or from the email that is sent.
1. PDP displays stocks status (out of stock or low stock)

**Comment by vannguyenn** [comment]
1. Creating a new provider to NextJS commerce storefront will need to complete all the items in the checklist in this guide. https://github.com/vercel/commerce/blob/main/packages/commerce/new-provider.md. The final output will be a PR to the repo and a working preview. Estimation: end of May 2022.

2-3. We need to create an open commerce provider inside the packages folder. We need to define the list of API endpoints/operators/hooks to work with OC APIs. We don't need to introduce any new packages/platform.

4. We can disable or enable a specific feature as well as introduce a feature. All we need to do is define those features inside the file `commerce.config.json` inside our provider. Also, a UI implementation is required if Nextjs has not been supported yet.

5. The new provider only contains the logic of fetching and displaying the data consumed from the server. The UI/components will be placed in different packages. And we can contribute to the repo if we need any new pages/features/components and they will help to review our PRs.

6-7. The structure of the new provider should follow the standard of the repo to make everything work.

8. We might need to develop some custom components with discount codes

**Comment by brent-hoover** [comment]
@vannguyenn Thank you for this work, I am going to consider this complete since work on the provider has begun
