### ISSUE TITLE
Access Denied While Creating Shop

### ISSUE THREAD

**Issue by OlehObodin** [reactioncommerce/reaction#6427]
## Issue Description
I have got error Access Denied when  try  create shop

## Steps to Reproduce

1. Sign Up https://admin.mdopencommerce.fastep.pl/graphql
2. Create Shop
3. Access Denied
Services:
https://api.mdopencommerce.fastep.pl/graphql
https://admin.mdopencommerce.fastep.pl/graphql
https://mdopencommerce.fastep.pl/graphql

### Versions

4.1.5

**Comment by OlehObodin** [comment]
ERROR Reaction: Tokens are not valid

**Comment by brent-hoover** [comment]
@OlehObodin You probably need to clear your cookies and re-login. This is not a bug in Reaction

**Comment by OlehObodin** [comment]
@zenweasel  I have installed  the brand new browser, the same problems.
The problem appears when I registered another user and start to create shop.

**Comment by nikitodss** [comment]
> @zenweasel I have installed the brand new browser, the same problems. The problem appears when I registered another user and start to create shop.

Tell me, did you manage to solve the problem?
