### ISSUE TITLE
Create provider for NextJS Commerce

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6431]
This work would entail creating a PR into the vercel that would create a "provider" for the NextJS Commerce product

The bare minimum (aka v1) for an implementation should include at least:

 - There is a "home page" that shows featured products
 - You can browse categories that are dynamically created in OC
 - You can sort and search products in the PLP
 - You can view a detail page for a product
 - PDP displays all images
 - PDP displays price
 - PDP displays description
 - You can add to cart, remove items from cart, or change quantity of items ordered
 - You can check out using whatever shipping methods are configured
 - You can check out using whatever payment methods are configured. We can ship with just Stripe and the "Example Payment Method" but it should show whatever methods are configured to be available)
 - Checkout via anonymous user

Additional implementation should allow for:

 - Using discount codes
 - Address validation
 - Create account and checkout as logged in user
 - You can view order status for a logged in user or from the email that is sent.
 - PDP displays stocks status (out of stock or low stock)

**Comment by brent-hoover** [comment]
@vannguyenn created [this PR](https://github.com/vercel/commerce/pull/759) for this which is still awaiting review since May

**Comment by loan-laux** [comment]
There's a response on the PR. Need to implement Dynamic API Routes and updated TS types. @zenweasel

**Comment by brent-hoover** [comment]
Vercel is end-of-lifing the multi-backend so this project is dead unfortunately. Hopefully work on Spark can begin soon.

**Comment by loan-laux** [comment]
Such a shame, but looking forward to Spark!
