### ISSUE TITLE
SPIKE: Document what work needs to be done to make fulfillment types work

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6432]
From the original docs

> ## Fulfillment Types
> A fulfillment type is an identifier that categorizes a certain way in which an order for an item can be fulfilled. The built-in fulfillment types are “shipping”, “pickup”, and “digital”.

> Every product variant (catalog item) has a list of available fulfillment types. If a catalog item can be fulfilled in more than one way (e.g., shipping or pickup), then a shopper is shown a selector during checkout, allowing them to choose the preferred fulfillment type.

> The fulfillment type also determines which user interface components are shown to a shopper during checkout. For example, a client may show a shipping address form for items with the “shipping” type, and a pickup time and location form for items with the “pickup” type.

Most of the work for this has been done, but currently you cannot place an order for any fulfillment type besides "shipping". If you add an additional fulfillment type manually through the database the second entry in the shipping array is never created. I believe because the code strips out this data when an item is added to cart. But that is probably not the only place that it's missing. Right now I believe the system is made to essentially "hardcode" to shipping. It might explicitly do this or it could simple be removing any other method and the system defaults to shipping. If you go to [this code](https://github.com/reactioncommerce/api-plugin-carts/blob/77fc19f2f4c6bbb1c573b76f251a0f2a4511f511/src/util/updateCartFulfillmentGroups.js#L32) you will see that the `supportedFulfillmentTypes ` variable is always `undefined`

The definition of done for this ticket is that when a product has multiple fulfillment types, two fulfillment records are created in the cart, and any one of these types can have methods. An example would be that a product can have both `shipping` type with a method of Ground and a `pickup` type with method of "Pickup in Store" and you can place an order for either of these types. 

Since the current storefront does not support multiple fulfillment types you will need to exercise the API directly via GraphQL and appropriate integration tests should be written. Some changes to the API may be necessary to be able to make this change. However, the scope of this ticket does not currently include any changes to the admin.

**Comment by sujithvn** [comment]
The  `supportedFulfillmentTypes` was showing up as `undefined` since it was not present in the Cart schema
Currently testing after locally updating the schema for `CartItem` to include `supportedFulfillmentTypes`
Also updated the code in the _addCartItem.js_ to populate this new field.

Seems like we would need more fixes to be done. Current groups are assigned directly as `cart.shipping || []`. Need to check if this has to be generalized to add other options like pickup, digital etc.

**Comment by brent-hoover** [comment]
Completed
