### ISSUE TITLE
As an admin I want to be able to apply a discount to an order via a trigger

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6458]
example : $10 off $50 or more

trigger qualifier: Cart Value ( i.e $50 )

This discount would have exclusion criteria. So we can apply the discount to items that meet criteria:

- Brand
- Class
- Tag

- Price Type : Full Price ( not on sale )
- Price Type : On Sale (sale or member pricing)
- Price Type : On Clearance (Perm Pricing)

**Comment by brendan-shea-pm** [comment]
@zenweasel Should I create a separate ticket in Kinetic for the FE of the discount action? I'm not able to edit this one

**Comment by brent-hoover** [comment]
Not sure why you can't edit those one but yes, all FE tickets should be in the Kinetic Repo

**Comment by brendan-shea-pm** [comment]
Looks I can edit this one now, probably user error on my part somehow. Anyway yes I will add new tickets for the outstanding Kinetic stories tomorrow, just wanted to check with you first as they will overlap some of the Reaction tickets but makes sense that we'd want to track the work separately.

**Comment by brent-hoover** [comment]
Completed
