### ISSUE TITLE
As an admin I want order discounts to be pro-rated across items in the cart

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6468]
For a $10 discount where there are two items of $50 a piece, each item would be discounted $5

**Comment by sushmitha-malae** [comment]
@zenweasel I would like to work on this, could you please assign this to me?

**Comment by brent-hoover** [comment]
This work is already part of a much larger project that is already underway. So it doesn't make sense as a one off ticket. It would be better to focus on the tickets that have the `hacktoberfest` tag.

**Comment by brendan-shea-pm** [comment]
@zenweasel Does the user have other options on how to calculate the discount or will this be the standard? Asking because if there are other options I'll want to mock that up in the UI, otherwise I think this would just be a backend issue

**Comment by brent-hoover** [comment]
No, no other options

**Comment by brent-hoover** [comment]
Completed
