### ISSUE TITLE
Add courier payment option. Need a null payment plugin or something like that

### ISSUE THREAD

**Issue by rkhunter** [reactioncommerce/reaction#647]
Customer cannot complete the order without payment. 
Client asks for courier payment option.
In need of null payment plugin or something like that.
Thank you in advance

**Comment by tdecaluwe** [comment]
Duplicate of #129?

**Comment by rkhunter** [comment]
[gouthamve:reaction-cod](https://github.com/Gouthamve/reaction-cod) package solves this issue.
Reference in documentation to Cash on Delivery payment method as well as it's installation would be nice for newbies :smile:
In short we need to build it from source instead of pulling from atmosphere.
Installation process:
- Clone the git repo
```
https://github.com/Gouthamve/reaction-cod
```
into the reaction/packages directory
- Run inside the reaction root directory
```
meteor add gouthamve:reaction-cod
```
- Enable COD payment in admin dashboard
