### ISSUE TITLE
find discounts within the same shop when applying?

### ISSUE THREAD

**Issue by marcneander** [reactioncommerce/reaction#6487]
Hello!

Just reading through the code so disregard please if this is somehow guarded by other code but it seems to me that you can apply a discount code created in another shop as long as it is in the database.

https://github.com/reactioncommerce/api-plugin-discounts-codes/blob/trunk/src/mutations/applyDiscountCodeToCart.js#L55

Should probably be, no?

```
const discount = await Discounts.findOne({ code: discountCode, shopId });
```

**Comment by marcneander** [comment]
Same with https://github.com/reactioncommerce/api-plugin-discounts-codes/blob/trunk/src/mutations/applyDiscountCodeToCart.js#L42

edit: nvm on this one. Seems to be handled here https://github.com/reactioncommerce/api-plugin-discounts-codes/blob/trunk/src/mutations/applyDiscountCodeToCart.js#L47

**Comment by brent-hoover** [comment]
Closing as this bug is in the existing discount code implementation which will be deprecated/removed in Release 5
