### ISSUE TITLE
context.mutations.publishNavigationChanges is not awaited

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6490]
In the publishNavigationChanges mutation resolver:
https://github.com/reactioncommerce/api-plugin-navigation/blob/a786b91ea9b333e8600e9b527c64c6975c03a62e/src/resolvers/Mutation/publishNavigationChanges.js#L21

`context.mutations.publishNavigationChanges` should be awaited.

I believe this currently still works as Apollo waits for outstanding promises to resolve.

**Comment by janus-reith** [comment]
Thinking again, might be ok this way as that resolver code probably wouldn't be reused outside the Query context, but not sure if there was a general discussion about this.

**Comment by brent-hoover** [comment]
Closing since this issue is two years old and no additional input
