### ISSUE TITLE
Recursive createHandle call should be awaited

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6496]
## Issue Description
`createHandle` is a recursive function to determine an available product handle.
It is async due to the database queries which need to be awaited.
The recursive call should be awaited aswell:
https://github.com/reactioncommerce/api-plugin-products/blob/cfe03ad3064d431018d1e30750c4ea16f1e775dc/src/utils/createHandle.js#L69

## Steps to Reproduce (untested)
1. Have a product with slug in your db, and another product with the same slug + "-copy" at the end
2. Try adding a new product with that slug

## Possible Solution
Await `createHandle`.

### Versions
trunk

**Comment by smriti0710** [comment]
@janus-reith i would like to fix this issue. Can you please assign this to me ?

**Comment by delagroove** [comment]
@smriti0710 done
