### ISSUE TITLE
With two sessions, cart publication fails after order completed

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#650]
Related to https://github.com/reactioncommerce/reaction/issues/536

With two **authenticated user** sessions, cart publication fails after order completed (user doesn't get a cart), to replicate:

- First session add item to cart, goto checkout.  
- Second session, go to checkout.
- First session, complete checkout with any payment method..
- Second session, attempt to add to cart.  

--> Failure, we don't have a new cart (as we should have).

Note: first session gets a new subscription fine in my tests.

This may also be leading to a broken workflow, where if this user then refreshed the session things appear ok, but then went through checkout again, the workflow is broken at the address book.

<img width="1542" alt="reaction___basic_reaction_product" src="https://cloud.githubusercontent.com/assets/439959/12133371/ca0c7878-b3d9-11e5-98f8-e2be1d0fda95.png">

This is related to https://github.com/reactioncommerce/reaction-paypal/issues/11 (which might not be valid anymore, but is manifested in this issue).

The expected behaviour is that you'd get the new cart that is created in session one, immediately and, in all other  **user** sessions that may be open.

This is probably happening with guest sessions as well (although the impact would be less critical)

**Comment by newsiberian** [comment]
Hi, when you are talking about two sessions, you actually mean two browsers or...?
assign me to this issue, please.

**Comment by zenweasel** [comment]
@newsiberian No, two tabs in the same browser.

**Comment by newsiberian** [comment]
I can't replicate this in #636 which is good, but there is another bug related with "after order completed".
That's why I'll leave my thoughts in this issue.

I think it is not the best way - to remove cart each time after order completed. This cause for some additional difficulties with making up to date new cart. The problem here - we need to replicate addresses object in new cart.

Is there any underling cases which were missed by me why we remove cart?

For now I think we should just remove items from existing cart and leave it, no?

**Comment by hrath2015** [comment]
It is really behaving Wierd today.  Esp Check out and Payment Steps. I created 1 successful Order using Admin Login.  Fine.  Added 2 more products to Cart (in same session as admin).  When checking  out getting below (Which is not expected):
![image](https://cloud.githubusercontent.com/assets/14071646/12141234/d4e4225e-b493-11e5-93e4-319511a80cbc.png)

**Comment by newsiberian** [comment]
Thanks for report. This is my fault. This is fixed in #636

**Comment by hrath2015** [comment]
thanks

**Comment by zenweasel** [comment]
Verified fixed in https://github.com/reactioncommerce/reaction/pull/636

**Comment by aaronjudd** [comment]
@newsiberian verified. this is now fixed (v0.11)
