### ISSUE TITLE
Attribute checks in shipping restrictions don't work for nested item properties (e.g. parcel.*)

### ISSUE THREAD

**Issue by derBretti** [reactioncommerce/reaction#6501]
## Issue Description
The checks for shipping restrictions based on an item's properties only work top for level properties such as price. An attribute deny rule that uses the property "weight", as mentioned in the documentation (https://docs.reactioncommerce.com/docs/concepts-fulfillment), does not work, since the property "weight" is nested in "parcel".

## Steps to Reproduce
1. Create a product with the parcel.weight attribute set
2. Create a shipping method
3. Create a shipping restriction with the attribute "weight" which would exclude the shipping method for the product if it was applied (as explained in the documentation)
4. See that the shipping method is available for the product in checkout process

## Possible Solution
Access item properties with `_.at(item, attribute.property)` in attributeDenyCheck.js. Change the property in the documentation to "parcel.weight"

### Versions
api-plugin-shipments-flat-rate@1.0.4
reaction@3.11.0

**Comment by range123** [comment]
@zenweasel I'd like to work on this

**Comment by brent-hoover** [comment]
@range123 assigned to you. Let me know if you have any questions

**Comment by range123** [comment]
The fix would involves a change in docs here - https://github.com/reactioncommerce/docs/blob/trunk/docs/fulfilling-orders.md#shipping-restrictions right? @zenweasel

**Comment by brent-hoover** [comment]
Not sure what you mean, the fix would be to make it work with nested properties? Do you mean to update the docs in addition to the fix?

**Comment by range123** [comment]
Yes, I meant in addition. So I would fix the logic here - https://github.com/reactioncommerce/reaction/blob/trunk/packages/api-plugin-shipments-flat-rate/src/util/attributeDenyCheck.js#L28-L34
and then the docs to use `parcel.*` for weight, height, width, length

**Comment by brent-hoover** [comment]
@range123 got it, yes. We would want to update the docs as well

**Comment by range123** [comment]
@zenweasel This exact issue seems to not exist anymore, the items objects contain the fields height, weight, width etc at the `item` level as well as the `item.parcel` level. Find below a sample `items` object.
```json
[
    {
        "_id": "pLjwLniF4wq89kmox",
        "attributes": [
            {
                "label": "Large Book",
                "value": "Large Book"
            }
        ],
        "isTaxable": true,
        "parcel": {
            -> "weight": 100,
            "height": 100,
            "width": 100,
            "length": 100
        },
        "price": {
            "amount": 100,
            "currencyCode": "USD"
        },
        "productId": "WDZkKCJXWxZ49eoaX",
        "productVendor": "Me",
        "quantity": 1,
        "shopId": "gr6fJ3ZD893f9YwTR",
        "subtotal": {
            "amount": 100,
            "currencyCode": "USD"
        },
        "taxCode": null,
        "title": "Large Book",
        "variantId": "pLjwLniF4wq89kmox",
        "variantTitle": "Large Book",
        "barcode": null,
        "createdAt": "2022-10-19T14:32:52.070Z",
        "description": "The book",
        "height": 100,
        "isDeleted": false,
        "isVisible": true,
        "length": 100,
        "metaDescription": null,
        "originCountry": "IN",
        "pageTitle": null,
        "primaryImage": null,
        "productType": null,
        "sku": null,
        "slug": "book-copy",
        "supportedFulfillmentTypes": [
            "shipping"
        ],
        "tagIds": null,
        "type": "product-simple",
        "updatedAt": "2022-10-19T14:34:33.724Z",
        "vendor": "Me",
        -> "weight": 100,
        "width": 100,
        "pricing": {
            "USD": {
                "compareAtPrice": null,
                "displayPrice": "$100.00",
                "maxPrice": 100,
                "minPrice": 100,
                "price": 100
            }
        },
        "isBackorder": false,
        "isLowQuantity": false,
        "isSoldOut": false,
        "attributeLabel": "Large Book",
        "index": 0,
        "metafields": null,
        "minOrderQuantity": null,
        "optionTitle": "Large Book",
        "taxDescription": null
    }
]```

**Comment by range123** [comment]
However, the restrictions on the fields `price`, `subtotal` still don't work. ([from the docs](https://mailchimp.com/developer/open-commerce/docs/fulfilling-orders/#shipping-restrictions))
So, I think implementing this fix would be required to make sure restrictions can be placed on these fields and any such nested fields.

**Comment by range123** [comment]
I'll work on raising a PR for this.
does this sound good to you? @zenweasel

**Comment by range123** [comment]
PR for this issue - https://github.com/reactioncommerce/reaction/pull/6578

**Comment by range123** [comment]
I'd like to update the docs as well, Should I add all the properties from the `item` object (posted above) to the docs?. Or will it be sufficient to update the `price` and `subtotal` properties to `price.amount` and `subtotal.amount`?. @zenweasel

**Comment by brent-hoover** [comment]
I think just a couple of examples would be fine

**Comment by range123** [comment]
Cool, I've raised a PR!
