### ISSUE TITLE
Surcharge resolver treats amount zero als falsy value

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6507]
This Resolver checks `node.amount` : https://github.com/reactioncommerce/api-plugin-surcharges/blob/43707f9ae1f2272123a8100d9f72ef1c43c01bc4/src/resolvers/Surcharge/index.js#L8
While the intention here is to check if node.amount is defined, which would be the case for a value `0`, it will instead translate to `false`. 

## Steps to Reproduce
1. Create a surcharge with amount 0.
2. Try to query it

## Possible Solution
Switch to e.g. `typeof node.amount !== "undefined"` instead of `node.amount`.

### Versions
latest

**Comment by shwetha263** [comment]
@zenweasel could you assign this issue to me ?

**Comment by brent-hoover** [comment]
@shwetha263 done
