### ISSUE TITLE
updateSurcharge should return the full item from db

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#6508]
## Issue Description
The `updateSurcharge `Mutation will only return the updated fields instead of returning the full item from db including the changes here: https://github.com/reactioncommerce/api-plugin-surcharges/blob/98cb4ca48fcd53edbfd36dedbe6986bfe8bf795c/src/mutations/updateSurcharge.js#L40

The mutation will fail to return properly, if mandatory fields like `createdAt` are not part of the update.

## Steps to Reproduce
1. Create a surcharge
2. Use updateSurcharge to update e.g. the amount and query all Surcharge fields in the return
3. Observe that `Cannot return null for non-nullable field Surcharge.createdAt.` is thrown.

## Possible Solution
Use `findOneAndUpdate` with `returnOriginal: false` would probably be a better fit here, to return the full upldated item

### Versions
trunk

**Comment by sushmitha-malae** [comment]
@zenweasel @janus-reith @delagroove  I am a first time contributor, i would like to work on this issue, could you please assign this to me?
