### ISSUE TITLE
Add match operator to support regular expression matching

### ISSUE THREAD

**Issue by alex-haproff** [reactioncommerce/reaction#6512]
Current set of operators is pretty basic and we already have a couple of production use-cases where regular expression matching for Surcharge and Fulfillment restrictions is vital.

https://github.com/reactioncommerce/api-utils/blob/trunk/lib/operators.js

Add `match` operator akin to this:
```
match(varA, varB) { return RegExp(varB, "ig").test(varA); }
```

**Comment by brent-hoover** [comment]
This was done already
