### ISSUE TITLE
getPaginatedResponse does not work with latest Mongo drivers

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6516]
This method depends on several mongo cursor properties which have been renamed. For example `cursor.cmd.filter` and `cursor.options`

Note that the latest version of the mongo driver (4.x) is required to work with the latest version of Mongo (5)

**Comment by brent-hoover** [comment]
@vanpho93  Can you confirm that this has been resolved in your PR for new Mongo drivers

**Comment by vanpho93** [comment]
> @vanpho93 Can you confirm that this has been resolved in your PR for new Mongo drivers

Yes, that's correct.

**Comment by brent-hoover** [comment]
Closed as fixed in Mongo driver PR
