### ISSUE TITLE
SPIKE: Doing Filtering/Search across Products/Customers/Orders

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6528]
Initial investigation into what it would take to provide filtering/search functionality and provide a consistent pattern/interface across all Data objects where it makes sense, but for now focused on Products/Customers/Orders.

The definition of done for this ticket is that we provide:
* A specific, detailed proposal for how this would be done
* Preferably a simple proof-on-concept of some subset of the functionality (e.g. just Orders without saving)

Basically broken down into two groups of functionality:

# Filtering
* Be able to filter for records (with pagination) based on any field and a value or subvalue (e.g. a partial match) including NOT. e.g. Orders where date_created > Sep 1 and NOT status = shipped
* Be able to combine filters in AND/OR pairs with (debatable how complex we want these groupings to be)
* Be able to sort this filtered result by any field
* Be able to name and save these filters and use them by name
* Be able to filter search results based on a list of IDs (Orders, Products)
* Be able to filter from product attributes such as Brand
* Be able to see and filter on slug in the search results
* Be able to filter (include or exclude) by Tags
* Be able to sort and filter a list of IDs entered via CSV

**Comment by brendan-shea-pm** [comment]
I added a few bullets under Filter based on some user feedback (starting with the "list of IDs" bullet) Happy to provide additional context if needed on any of them.
