### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by Listyc92** [reactioncommerce/reaction#6553]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact us instead. We are active on Discord:

- [Discord](https://discord.gg/Bwm63tBcQY)

reaction-cli: Creating API project: {"projectName":"test","options":{}}
reaction-cli: Error: ENOENT: no such file or directory, stat 'C:\Users\listy\Desktop\Nouveau dossier\test'
reaction-cli: Error: Cloning into 'C:\Users\listy\AppData\Local\Temp\reaction-cliVfjb21'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by brent-hoover** [comment]
You need to have SSH verification with Github set up for this to work

**Comment by brent-hoover** [comment]
[I've added a note about this](https://github.com/reactioncommerce/cli/pull/123) to the prerequisites
