### ISSUE TITLE
How to remove Sample Product?

### ISSUE THREAD

**Issue by bbogeul** [reactioncommerce/reaction#658]
Hi there Reaction Community,

Fairly new here. I am testing something and the sample product seems to reappear after a certain period of use and was wondering if there is a package that I might need to delete or uncomment on,
Again sorry for the simple question and Happy New Year!

**Comment by aaronjudd** [comment]
You could remove - `reaction-sample-data` and that will prevent the sample data from reappearing.  
You can clone that package to make your own fixtures as well. 

On meteor reset / restart -> that package will attempt to merge/import that data if you deleted it, which is probably why are seeing a "certain period" then it repopulates.
