### ISSUE TITLE
Remove Semantic Release badge from the READMEs of all the packages

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6580]
Not a huge priority but it looks bad

**Comment by akhilchoudhary2k** [comment]
Hii @zenweasel, can you describe a little bit more about the issue?

**Comment by brent-hoover** [comment]
It's pretty much just like it says. We no longer use semantic release so we should remove the badges from all the READMEs for the plugin.

**Comment by skodamarthi** [comment]
@zenweasel Can I work on this as part of hacktoberfest?

**Comment by brent-hoover** [comment]
@skodamarthi sure. Assigned to you.

**Comment by skodamarthi** [comment]
@zenweasel Raised https://github.com/reactioncommerce/reaction/pull/6595. Happy to make any additional changes if needed.

**Comment by skodamarthi** [comment]
@zenweasel Closed the previous PR and raised https://github.com/reactioncommerce/reaction/pull/6598 to clean up and address the review comments.
