### ISSUE TITLE
need to be able to select multiple product options and input quantities

### ISSUE THREAD

**Issue by PaulSavignano** [reactioncommerce/reaction#659]
I need a variation of your current product layout that would allow for 10 options under a single product. The user should be able to select multiple options and then provide the quantity. I have a meal package which includes selecting up to 4 dishes out of 10 choices/options. Once the user has selected 4, either by selecting 4 of one item or 1 of 4 different items, the other selections should be greyed out from use.

![pauls-reaction-spec 001](https://cloud.githubusercontent.com/assets/11730201/12159063/3f53f182-b494-11e5-8961-afd8b9c9e25d.jpeg)

![pauls-reaction-spec 002](https://cloud.githubusercontent.com/assets/11730201/12159074/556089d6-b494-11e5-83c8-b1749cc427fa.jpeg)

![pauls-reaction-spec 003](https://cloud.githubusercontent.com/assets/11730201/12159079/5e4fc3ea-b494-11e5-91b1-953e5db43b7b.jpeg)

**Comment by zenweasel** [comment]
We are closing any feature requests which have not been active and are not on our current roadmap. If you are interested in possible improvements to Reaction, we suggest you create a new topic on the [forums](https://forums.reactioncommerce.com)

Thanks for your contribution
