### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by bbogeul** [reactioncommerce/reaction#660]
Image upload is working great but dumps it in the wrong product.
any lead where to start?

**Comment by aaronjudd** [comment]
not been able to replicate. Perhaps it was a case of the variant upload not leading to expected results.  (if you don't have a variant selected, the image is associated with the product, but that's not what is selected, so that's a confusing issue.

**Comment by zenweasel** [comment]
Could not duplicate this problem. If you are still experiencing this, please provide detailed steps to replicate and reopen. Thanks.
