### ISSUE TITLE
Promotions should use timezone in shop settings for time calculations not server time

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6603]
Time zone is set here in the shop settings

![image](https://user-images.githubusercontent.com/72819/198920034-ce32b6fc-8c78-42d6-adb6-76e8fc7a5d96.png)

I think this probably only involves changing `const now = new Date()` to something like `const now = new Date().toLocaleString("en-US", { timeZone: "America/Chicago" });` where "America/Chicago" would be the timezone from ShopSettings. And probably want to define that function globally and maybe cache the timezone.

**Comment by brent-hoover** [comment]
This should use the `getShopTimeZones` util that I added for state. I was thinking that we could just use state for the query but I think the addition of #6668 means that we need to have more flexibility in how we query based on time. We should think about that as we build this.

**Comment by vanpho93** [comment]
FE transformed input dates into UTC before sending to server so we don't need to convert before using.
