### ISSUE TITLE
User is not notified they are logged out in other tabs when logging out of one tab

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#664]
Hello,

we have an issue with unexpected behavior on user logout when using several tabs [here](https://github.com/reactioncommerce/reaction/issues/656), but the most strange thing that the admin user have different behavior in the same situation.

When you attempt to logout by admin with several browser tabs, only active tab interact with server as expected. Other tabs not have such interaction. After you successfully logout, you could still see admin account inside non-active tabs by doing `Accounts.user()` or `ReactionCore.Collections.Cart.findOne()`.

**Comment by aaronjudd** [comment]
Related to #656

**Comment by zenweasel** [comment]
From @newsiberian Steps to reproduce:

1. Open more than 3 tabs with http:/localhost:3000
2. In one of these tabs log in as admin or register someone
3. Check all tabs. You should see that all tabs now logged in by user
4. Open developer tool in Resources tab (Chrome) and look at LocalStorage. You should see you sessionId, userId
5. Now, in this log out from this user and look at changes in LocalStorage
6. Check another tabs. They should show admin. You even could call all admin Collections (cart, user etc)
but it is dead page. you can't interact with UI. refresh will help

**Comment by zenweasel** [comment]
I think this duplicates https://github.com/reactioncommerce/reaction/issues/643 but I am keeping this one open since it has better documentation.
