### ISSUE TITLE
Editing tags - "Enter" and "Esc" buttons doesn't works

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#665]
"Enter" button doesn't works while editing or adding new tags of product by admin. I think it should save current tag and move cursor to the new tag. Now only loosing mouse focus is working

The same situation with top tags: only click to the products area help to exit from the editing mode. "Esc" button and click at the top tags area doesn't works.

**Comment by ramusus** [comment]
I tested in safari and chrome in mac osx

**Comment by tdecaluwe** [comment]
I checked in the code, and indeed, it's not there, can be solved by wrapping the inputs in a form or listening to `keypress` events.

@mikemurray If I got some spare time I'll look into it.

**Comment by mikemurray** [comment]
Related to #558 (a redesign of the tag navigation)
see branch https://github.com/reactioncommerce/reaction/tree/navigation-558
