### ISSUE TITLE
Unable to delete tags from navigation line

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#666]
I'm trying to remove tags from navigation line, but I'v got error **"Tag is in use. It must be deleted from products first."** I don't want to delete tag from the whole site, just from navigation line.

**Comment by tdecaluwe** [comment]
Tags have an `isVisible` field in their schema. Setting it to false will result in the tag not being displayed in the navigation.

**Comment by ramusus** [comment]
That's good to know, but I want to be able do it via UI

**Comment by mikemurray** [comment]
Related to #558 (a redesign of the tag navigation)
see branch https://github.com/reactioncommerce/reaction/tree/navigation-558
