### ISSUE TITLE
Can move forward in checkout without Shipping

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#669]
In the Cart workflow at the checkout page if you select a shipping address the state will got to coreCheckoutShipping which is good but after this even if you don't select a shipping but change the address or select an other address the cart status will move to the checkoutPayment state and the payment option becomes available even though you don't have shipping.

**Comment by zenweasel** [comment]
I am not able to replicate any longer. (I never see Payment options become available no matter what I click on). @boboci9  Please reopen if you are still seeing this.
