### ISSUE TITLE
Filtration functionality in products list pages

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#670]
I'm thinking about implementation of products filtering. It should be definitely external package, for example as reaction-search. This functionality might be helpful on any page with list of products - main and tag pages.
From the beginning I want to have filtration by fields: 
* price
* weight
* hashtag 
* search query

Only for admins:
* visibility 
* taxable
* inventoryManagement
* inventoryPolicy
* inventoryQuantity ranges

And optionally by any metafields. Also search field could be one of the filtration criteria.

I'm thinking how to implement it and i'm not sure about right way. Perhaps we need denormalization of Product table and make new table with only filtration fields and structure - variant per row. Filtration by this table will get the link back to the real Product.

Any advices are appreciated.

**Comment by newsiberian** [comment]
Hi, nice idea. Just my thoughts... Maybe it could be implemented via different publications, like so:
select some sorting option => send params to router => inside router: unsubscibe from previous subscription; subscribe to new one.

**Comment by ramusus** [comment]
Hi @newsiberian what reason of multi publications idea?

**Comment by newsiberian** [comment]
@ramusus, hello, I'm not sure I could be helpfull, but if you want - PM me in Gitter

**Comment by ramusus** [comment]
Finally I implemented Reaction FIltration package https://github.com/ramusus/reaction-filtration
and open this PR to show how to integrate it with the dev core https://github.com/reactioncommerce/reaction/pull/743

**Comment by ramusus** [comment]
For now I implemented almost all features from my original idea. I will close this issue, for discussing additional ideas, everybody is welcome here https://github.com/ramusus/reaction-filtration/issues

**Comment by newsiberian** [comment]
I just now noticed that it comes to filtering. Why I was thinking about sorting? :innocent:

**Comment by aaronjudd** [comment]
@ramusus this looks really great.. :+1:  for distributing in core, let me review more for the next release..

**Comment by newsiberian** [comment]
This version of a package is not compatible with #741, because, in #741 we are subscribing only on product docs in `productGrid`. Any thoughts on this?

**Comment by ramusus** [comment]
@newsiberian I didn't check this PR. When do you plan to merge it to the core?

**Comment by newsiberian** [comment]
@ramusus, I'm not from RC team, so I can't answer on a second part of your question, but it will be good to discuss about the first part in gitter. So, PM me, if it possible.

**Comment by ramusus** [comment]
@newsiberian I came there, but didn't find how send you private message, please, can you right me the first

**Comment by newsiberian** [comment]
I sent you a message from [here](https://gitter.im/reactioncommerce/reaction)
