### ISSUE TITLE
Static flat pages package for reaction commerce. Any recommendations?

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#671]
I need to have ability to make static pages with basic needs, title, slug, content fields. Content field with  wysiwyg editor, something like Django's flatpages application.
For now I found this package https://github.com/dukeondope/reaction-static-pages but it's perhaps very outdated, buggy and unstable. 

How the community handle this issue? May be it's easier to plug any Meteor based CMS in to Reaction?

**Comment by abhisheksoni27** [comment]
Check out https://github.com/abhisheksoni27/blanketcoffee

**Comment by kefirchik** [comment]
@ramusus In former times reaction-static-pages was good enough to solve simple static page management :smiley: I'll try to update it in a few days :wink:

**Comment by ramusus** [comment]
I'm working on new version of package and hope to release it today later

**Comment by ramusus** [comment]
released beta version
```
meteor add ramusus:reaction-flat-pages
```

**Comment by zenweasel** [comment]
@ramusus Hey, I tried out this package. I can see where you can add pages but I don't see where I can make them visible or edit them. (I would add this question to the repo but you don't have issues enabled)

**Comment by ramusus** [comment]
Hi @zenweasel! I enabled issues for the project. You can make them visible and edit on the page of every flat page in the same very familiar "reaction product page" style. Also I implemented few minutes ago wysiwyg and autosaving during editing.

**Comment by ramusus** [comment]
released 0.0.9, add README with features and screens
https://atmospherejs.com/ramusus/reaction-flat-pages

Guys, what do you think about adding this package to official repo and plug by default instead of static html "Lorem ipsum.."?

**Comment by aaronjudd** [comment]
@ramusus @kefirchik nice! glad to see that package updated. We're testing it now.  here's the choices -> we can import the repo into the reaction repo (make this a core package), or we can just leave as an independant package and include in the Reaction `./meteor/packages`  (see options here: https://docs.reactioncommerce.com/reaction-docs/development/including)

What's your thoughts?

**Comment by aaronjudd** [comment]
@mikemurray  we can tie this into #558 as well, adding pages to the navigation using tag management. (plan is to replace the footer links with the updated navigation tool as well).

**Comment by ramusus** [comment]
@aaronjudd I didn't check #558, but it seems required to be merged asap. Good idea to be able to choose links to the page in footer and header via UI! Do I have choices between Foundation and Community groups?

**Comment by BenjaDev** [comment]
Hey! I think it's a nice package, thx! But there's an issue with the route, as i created a new page it had automatically an invalid route attached to it, but when i copied its ID from console it worked. Is this a known issue?

**Comment by ramusus** [comment]
@BenjaDev no, it's unknown. Could you make new one here https://github.com/ramusus/reaction-flat-pages/issues with steps how to reproduce? Screenshots are appreciated!

**Comment by aaronjudd** [comment]
Closing discussion in favor of https://github.com/reactioncommerce/reaction/pull/805 for now as that is a direct answer to this question.
