### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by dheerajbhaskar** [reactioncommerce/reaction#673]
## Problem
demo.reactioncommerce.com is not working. The site never loads.

## The *Real* Problem
Can we maintain a demo site for RC which is the latest stable version (or deployed from master)?
The purpose is 
1. to be able to show RC to someone
2. To follow the progress of development, 
  - I know there's a waffle board but that's not the same as seeing it
  - I know one can pull and deploy, but...

  ![ain t nobody got time for that - imgur](https://cloud.githubusercontent.com/assets/2944909/12224343/f8a94f1a-b813-11e5-860c-e684ad6dd91d.jpg)

In all seriousness, it would be very nice to have a demo site which is deployed from the latest code. 
What do you people think?

**Comment by aaronjudd** [comment]
@dheerajbhaskar We'll be adding this feature on Reaction Commerce in the very, very near future. Stay tuned.

**Comment by dheerajbhaskar** [comment]
Fantastic. +1

On Mon, Jan 11, 2016 at 4:20 AM Aaron Judd <notifications@github.com> wrote:

> @dheerajbhaskar <https://github.com/dheerajbhaskar> We'll be adding this
> feature on Reaction Commerce in the very, very near future. Stay tuned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactioncommerce/reaction/issues/673#issuecomment-170402916>
> .
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---
