### ISSUE TITLE
Cannot complete checkout on second visit when using Anonymous user

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#674]
When I try to check out a second time using the Guest account, the shipping options never load and I am stuck on this screen.
![bad_checkout](https://cloud.githubusercontent.com/assets/72819/12228020/7c0c6692-b870-11e5-9287-aa8d19cab3df.jpg)

Steps to reproduce:
1. Fresh checkout, clean install
2. Checkout first time using the "continue as guest" option (doesn't matter what payment method you use)
3. Complete checkout
4. Return to home page
5. Place item in cart and checkout again
6. Get selected default address but shipping options never populate and checkout can't be completed.

If you checkout multiple times using an authenticated user (e.g. admin) everything works fine

**Comment by aaronjudd** [comment]
Related to #650

**Comment by zenweasel** [comment]
Verified fixed in https://github.com/reactioncommerce/reaction/pull/636

**Comment by zenweasel** [comment]
Verified fix in current version
