### ISSUE TITLE
 As an operator I want to determine a limit to the number of times a discount can be used by a customer

### ISSUE THREAD

**Issue by vannguyenn** [reactioncommerce/reaction#6751]
Kinetic tickets https://app.zenhub.com/workspaces/moc-main-board-62fd8e881686130027eafc31/issues/gh/reactioncommerce/kinetic/132

**Comment by brent-hoover** [comment]
@brendan-shea-pm can we confirm that this limitation is only applicable to coupons? If it isn't only coupons can you clarify what non-coupon use cases there are?

**Comment by brendan-shea-pm** [comment]
@zenweasel You are correct, coupons are the only use case for this one
