### ISSUE TITLE
kinetic: Promotions: Discount is not being reflected in Cart Session

### ISSUE THREAD

**Issue by node82** [reactioncommerce/reaction#6757]
https://www.loom.com/share/8a6cc993db1c485e8d2cd829a1464a3e

built an active order Level promotion that would take off $17 off $25 or more
but am not seeing that discount reflected in the storefront or in the cart session ( mongo db : reaction.Cart)

the only active promotion in Kinetic is the $17 off Promotion, every other promotion is disabled
example: add an item to the cart, see a discount of $5 taken off ( in storefront cart, and in mongo reaction.Cart), not $17, double quantity in cart, see the discount update to $10 in storefront cart and mongo: reaction.Cart 

having all promotions disabled, I still see the $5 per item discount on the Rugged Outdoor Running Shoe

**Comment by node82** [comment]
on branch `feat/enable-promotions`
all promotions have been `disabled`
and initiated a new cart, 
and am seeing a promotion still apply, 
the promotion in the database says says `enable = false` which matches the UX, but it says the promotion is still applying
![image](https://user-images.githubusercontent.com/26560026/212183983-fc386120-3abc-487a-b9b8-56f1d93cc02a.png)

**Comment by brent-hoover** [comment]
@vanpho93 Can you take a look at this ASAP?

**Comment by brent-hoover** [comment]
This is in the Kinetic repo but it does not seem like a UX issue so transferring it to Reaction

**Comment by node82** [comment]
here is a copy of all promotions found in my local db :  reaction.Promotions
[promo.json.zip](https://github.com/reactioncommerce/reaction/files/10412894/promo.json.zip)
