### ISSUE TITLE
Discount is applying with no enabled/active promotions

### ISSUE THREAD

**Issue by node82** [reactioncommerce/reaction#6759]
Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)
-->

## Issue Description
in testing promotions, disabled all promotions in UX, and seeing similar enabled = false in database , but still am seeing a promotion being applied in the storefront and in the database: 
![image](https://user-images.githubusercontent.com/26560026/212359951-4a9a07d8-b54d-4790-83e9-7b3a043c2f84.png)

![image](https://user-images.githubusercontent.com/26560026/212360543-ce8b3868-f9b3-4bdf-8eb1-07af851a6f60.png)

Here is a copy of all promotions in the current state from local db : reaction.Promotions 
[promo.json.zip](https://github.com/reactioncommerce/reaction/files/10412980/promo.json.zip)

## Steps to Reproduce

1. setup a few promotions ,
2. enable promotion until active, then disable those promotions in UX , 
3. add item in storefront that meets at least one of the promotional qualifiers 

### Versions
npm version : 8.19.2
branch: feat/promotions

**Comment by brent-hoover** [comment]
@node82 waiting for confirmation that this is fixed

**Comment by node82** [comment]
LGTM
