### ISSUE TITLE
As an operator I want Shipping Discount promotions to stack unless they are actioned on the same Shipping Method

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/reaction#6767]
By default an operator will want promos of the Shipping promotion type to stack with each other unless the stacking promos have their action set for the same Shipping Method

**Comment by jrphilo** [comment]
@jrphilo

**Comment by brent-hoover** [comment]
Waiting for input from @jrphilo before moving into Sprint

**Comment by brendan-shea-pm** [comment]
@zenweasel For Item level stackability, are we checking at the item level whether a promotion stacks or is it only checked at the order level (meaning by default one order can only have one Item Discount)? I was under the impression it was checked at the item level, and if this is the case I think Shipping Discounts would behave in a similar way (but rather than check stackability at the item level, it's checked at the Shipping Method)
