### ISSUE TITLE
Format issue in i18n.js

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#679]
Hi,

After a while of testing around the system I got to a phase where the ReactionCore.Currency.formatNumber function is not returning the correct value but always 0.
I tried debugging it but it seems the issue is coming from the fact that the ` ReactionCore.Locale.currency.rate` which should be done in the main.js but it's not because `typeof Locale.locale.currency === "string"` condition from main.js. line 28 is never true in my case. 
Can you tell me how to fix this issue, it's possible the issue is only in my version due to the shop not being set correctly.

Thanks.

**Comment by aaronjudd** [comment]
is this resolved in https://github.com/reactioncommerce/reaction/pull/681?

**Comment by boboci9** [comment]
I pulled the new version, I will make some tests and close the issue if it is fixed with the new commits.

**Comment by aaronjudd** [comment]
@boboci9 how did your tests go? Should we close?

**Comment by boboci9** [comment]
Yes the fix is working, it didn't happen since I updated. I will close it,
