### ISSUE TITLE
Remove old api-plugin-discount and api-plugin-discount-codes

### ISSUE THREAD

**Issue by vanpho93** [reactioncommerce/reaction#6792]
These plugins are redundant after we created new plugins for promotions / coupons / discounts so we should remove them.

Step 1:

Remove these from reaction app package.json / plugin.json
Add deprecation note into readme of these two plugins.

Step 2:

Remove completely from the code base => This will be covered in another ticket later.

**Comment by brent-hoover** [comment]
@vanpho93 we might not want to remove them from the code base for a while, just in case someone wants to do a code fix.
