### ISSUE TITLE
Sponsored issue: Shopping Cart Data Sync Issue Affecting Checkout Page

### ISSUE THREAD

**Issue by chieduchineme** [reactioncommerce/reaction#6860]
The shopping cart does not update correctly on the checkout page. 
When a user adds or removes items from the cart on other pages of the website, the cart total and item count do not reflect these changes when the user proceeds to the checkout page. 
It seems like the cart data is not syncing properly between different parts of the site.

## Priority Support

- @chieduchineme is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=057b3e98-e1dc-4130-9f41-fe06c1d75cdc&owner=reactioncommerce&name=reaction).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by brent-hoover** [comment]
@chieduchineme This sounds more like a storefront issue than an API issue.

**Comment by iwint** [comment]
Hey guys , I would like to contribute to this , can anyone assign me to this issue ?

**Comment by delagroove** [comment]
@iwint I can assign you to this task, but it might be more related to the storefront than the API as @zenweasel says, let us know.
