### ISSUE TITLE
change "Twitter" to "𝕏 (Twitter)" in README.md

### ISSUE THREAD

**Issue by BandhiyaHardik** [reactioncommerce/reaction#6863]
## Issue Description

Twitter is now known as 𝕏
## Steps to Reproduce

1. Goto Reaction Repository
2. Read README.md you will see Twitter there 

## Possible Solution

Change the name of it.

**Comment by vishwas-babar** [comment]
if issue is solved then please close it

**Comment by BandhiyaHardik** [comment]
@vishwas-babar the issue is not solved yet. 

My PR is not merged and you can see in README.md that Twitter's name is not updated yet.

**Comment by amasoft** [comment]
can you assign it to me if not yet resolved

**Comment by BandhiyaHardik** [comment]
@amasoft I closed my PR.

If you want to work on it go ahead.
