### ISSUE TITLE
Add media directly from web sources

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#69]
Ability to pick and add files from Facebook, Google Drive, Dropbox, Image URL, and other popular file repositories for use in the product gallery.

**Comment by aaronjudd** [comment]
Closing, pursuing alternate approaches.

**Comment by zrisher** [comment]
FYI for those landing here from the docs, here is the new tracking issue - https://github.com/reactioncommerce/reaction/issues/1221
