### ISSUE TITLE
Add "Log out all other devices" functionality

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#690]
Similar to what you have in Gmail. Really meant just for admins so it could just be a button in the dashboard. Also on a password change it should do this too. (for when you fire that guy)

**Comment by aaronjudd** [comment]
This would be a ui enhancement to run / toggle use of http://docs.meteor.com/#/full/meteor_logoutotherclients on logout.

Which we just removed as it was unexpected for default behaviour.

**Comment by aaronjudd** [comment]
Closing - insufficient details.
