### ISSUE TITLE
logging out of one session when logged into multiple browsers breaks

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#692]
1 login into same account, two + different browsers sessions
2 add item to cart  - see replicated
3  login out of session 1
4 session 2 destroyed.

![multiple-browser-session-afterlogout](https://cloud.githubusercontent.com/assets/439959/12288795/2a345be6-b98c-11e5-8029-29ea8186c634.gif)

Maybe duplicate issue?

**Comment by aaronjudd** [comment]
Duplicate of #656 ?

**Comment by newsiberian** [comment]
Hi, for me this one is duplicate of #664.

**Comment by aaronjudd** [comment]
Closed by https://github.com/reactioncommerce/reaction/pull/705
