### ISSUE TITLE
Translation files of dependent packages - where is right location?

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#696]
I implement package https://github.com/ramusus/reaction-flat-pages with some translation strings. For now, AFAIK, translation strings of dependent packages should be pasted manually inside reaction package translation files. This is not good - I suppose translations should be located inside dependent packages and used from there.

May be we need the way to build result translations from several file sources of different packages with using `namespace` arguments of `i18next` library?

**Comment by aaronjudd** [comment]
There's two methods -> insert into the Translation collection with ReactionImport,  or with a direct import into db.  If they are maintained in independant packages we'll have a tough time keeping the initial data translated and up to date.

**Comment by aaronjudd** [comment]
I'm closing this as we've been discussing else where.. but you can now load package specific  name spaced translation files as well..

**Comment by aaronjudd** [comment]
Created ticket for docs https://github.com/reactioncommerce/reaction-docs/issues/22
