### ISSUE TITLE
Issue adding Templates to checkout

### ISSUE THREAD

**Issue by Aesop7** [reactioncommerce/reaction#700]
I'm currently trying to add a template to the checkout page, using the following code:
```
ReactionCore.registerPackage({
  name: 'custompackage',
  autoEnable: true,
  settings: {
  },
  registry: [{
    route: "dashboard/settings/shop",
    provides: 'custom-dashboard',
    label: 'Custom Package',
    description: 'Custom package that does All of the Things',
    icon: 'fa fa-th',
    cycle: 1,
    container: "dashboard",
    permissions: [{
      label: "Dashboard",
      permission: "dashboard"
    }]
  }, {
    route: "dashboard",
    provides: 'shortcut',
    label: 'Dashboard',
    icon: 'fa fa-th',
    cycle: 1
  }],
  layout: [{
    template: "myCustomTemplate",
    label: "Custom Info",
    workflow: 'coreCartWorkflow',
    container: 'checkout-steps-main',
    audience: ["guest", "anonymous"],
    priority: 3,
    position: "3"
  }]
});
```
This is based on what I read here:  https://github.com/reactioncommerce/reaction/blob/development/docs/developer/workflow.md

After running the registry code above, the document gets added to the Packages collection, but when looking at the checkout page, rather than being in position #3 (as specified toward the end in "layout") it's appended to the end.

Please note, I am still relatively new to development, Javascript, Meteor and Reaction, so this could very well be a user error!

Any help would really be appreciated, thanks!

**Comment by mikemurray** [comment]
At first glance, it seems to be an issue with our system. The neither priority or position is used so its reliant on the array position of the layout items; which will always make your templates last.

The fix here will be to implement the usage of priority and also allow you to disable the default workflow and craft your own using a mixture of our core checkout templates and yours.

**Comment by Aesop7** [comment]
Unless more people are looking for this feature, would an interim fix be to simply modify the ''layout" array in the reaction core document to include the additional step?  (Just via mongo directly)

**Comment by aaronjudd** [comment]
Priority is now used with https://github.com/reactioncommerce/reaction/pull/783, and the layout structure has been redefined as well.

**Comment by aaronjudd** [comment]
Closing this as the layout and workflow should be resolving this.
