### ISSUE TITLE
A minor pagination issue on "product/tag" route

### ISSUE THREAD

**Issue by uniquarkD** [reactioncommerce/reaction#703]
Its infinite scrolling is reloading the page because we are returning its subscription on "waitOn" which triggers the global loading hook: 
waitOn: function () {
      return this.subscribe("Products", Session.get("productScrollLimit"));
    },

The problem will be solved if we move it to subscription hook. 
subscriptions: function () {
//not returning the subscription
      this.tagSubsription = this.subscribe("Products", Session.get("productScrollLimit"));
      return this.subscribe("Tags");
    },

**Comment by aaronjudd** [comment]
@uniquarkD :+1:  happy to take a PR for this.
