### ISSUE TITLE
Store refunds along with other transactions on the order

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#709]
While there is some value to querying the API every time I don't think this is a scalable solution once somebody gets a significant amount of orders and could possibly lead to a merchant getting temporarily shut down. A first step might be to at least store whether there were ever any refunds before making the query. Or maybe make this configurable per Payment method?

(my secret agenda is that this method is not very testable)

**Comment by kieckhafer** [comment]
Just a thought on this, since I've been digging into refunds, I don't think we can definitively store whether or not any refunds were made, because techincally a store owner never needs to create a refund through the Reaction UI, they can do all of that through the payment providers UI.

**Comment by zenweasel** [comment]
That's true, but once we have a record we don't need to go back to the provider every time someone clicks on that order. I know for a fact that both Stripe and Braintree have API limits that could easily get be surpassed by doing this in a production environment.

BTW, Braintree and Paypal don't have a lot in common except for Corporate ownership. And I am pretty sure that's on purpose.

**Comment by aaronjudd** [comment]
We're now storing discounts as payment.method = "debit", while all credit cards are "credit".  refunds could be stored in the same manner.  Handling for most parts of the billing methods should be able handle this as well with few updates.

**Comment by aaronjudd** [comment]
@zenweasel do you think this issue should remain open?

**Comment by zenweasel** [comment]
I thought this was going to be a big deal but apparently nobody but me has cared about it for almost a year and a half so I'm closing.
