### ISSUE TITLE
We need a clarification of some aspects with product quantity

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#719]
Hello, there is something unclear to me in the product quantity logic and I want to figure it out. I want to show you how I see it.

We can have at least two situations with creating product. Admin can combine only top-level variants for his product:
![top_variant_2](https://cloud.githubusercontent.com/assets/11130487/12475229/4cd4b08e-c043-11e5-86d9-fab200849ab5.png)

or he could add an options:
![top_variant](https://cloud.githubusercontent.com/assets/11130487/12475235/523f4a16-c043-11e5-89b5-8071ab183a80.png)

First method looks good. We have top-level variants with 15, 10 and 20 items in each. They have their representation in `Inventory` collection. Everything looks correct to me.

If we look closely on the second picture, we will see that our T-shorts quantities now moved into `options`. We have here 20, 42 and 15. These items also has their representation in `Inventory`. BUT, we can notice that top-level variant also have 15 items. These 15 items also represented in `Inventory` collection. This is not correct from my point of view and could lead to various side effects.

So, I would like to clarify our view on the product quantities. If we add `options` to our top-level variant, we should remove `inventoryQuantity` from his doc completely or top-level `variant` could contain common quantity of all his options [with a second idea we don't need to do changes in client side at all] - some kind of denormalization -, and additionally remove all `Inventory` representations of this variant. Like on this pictures:
way 1:
![new_top_var_step_3_mod](https://cloud.githubusercontent.com/assets/11130487/12475365/525698d2-c044-11e5-81da-668a5b2859eb.png)

way 2:
![new_top_var_step_3_mod2](https://cloud.githubusercontent.com/assets/11130487/12475376/5b5672fe-c044-11e5-8656-bbad2437ada3.png)

What do you think? Or I missed something here?

**Comment by newsiberian** [comment]
Additionally let's make it more clear, what the following terms mean for us. We are now talking about `productGrid` and products.

We have some notice helpers with methods:

* `isLowQuantity` – this method should return `true` if only one of many variants `quantity` < `lowInventoryWarningThreshold`? Or if every variants have a low `quantity`. I think if this notice suppose to be displayed for customer, we should use second logic, because if you want to buy an XXL size, but notice shows that one of variants (i.e. L size) has low quantity – it just will confuse.

* `isBackorder` – I'm not sure I understand correctly this word “backorder”. Does this mean that seller have some product in stock, but he doesn't want to sell it now, so he freezes an ability to buy this product, is this correct? And again the product become “backordered” if only one of it's variants has `inventoryPolicy = false` or if all variants has `inventoryPolicy = false`?


Also, it will be good to hear the description of the following fields (because it is not completely clear):
1. `inventoryManagement`
2. `inventoryPolicy`

**Comment by aaronjudd** [comment]
So this is probably a little broken because of all the recent inventory work, and because we wanted to rework some of this with new product types (as new packages).

The original behavior was that if you had child variants, the top level variant would display the sum of all the child variants. 

> If we look closely on the second picture, we will see that our T-shorts quantities now moved into options. We have here 20, 42 and 15. These items also has their representation in Inventory. BUT, we can notice that top-level variant also have 15 items. These 15 items also represented in Inventory collection. This is not correct from my point of view and could lead to various side effects.

> re: `common quantity of all his options`
 
Here the **UI** is broken, I think it should be updated to reflect the sum of child variants.  

However, I'm not sure the actual top level inventory record _HAS_ to be removed, but I guess that would be ok. Might be useful for some other product type in the future to keep it.


>isLowQuantity – this method should return true if only one of many variants quantity < lowInventoryWarningThreshold

Should be if ANY of the variants  < top level lowInventoryWarningThreshold.

Users are encouraged to buy when there is a sense of urgency.  Maybe something we could make configurable though.

> isBackorder – I'm not sure I understand correctly this word “backorder”.

A seller can choose whether each item is available to be ordered when then ``qty <  available inventory``

 The `inventoryPolicy = false` with no inventory in stock should not be sale-able.

**Comment by aaronjudd** [comment]
this statement `The inventoryPolicy = false with no inventory in stock should not be sale-able.` is incorrect. It should be backordered if inventoryPolicy = false.

inventoryPolicy = false means items should always be sale-able regardless of inventory (we take backorders).  if inventoryPolicy = true then we warn when less than threshold, and stop accepting orders at 0.

**Comment by tdecaluwe** [comment]
Perhaps, if we aren't actually merging the schemas, we should have both objects in the database? I mean, a one-option product would have both a `ProductVariant` and a `Product` document in the database. This would make the design more extendable, making it possible to associate more documents with the same product.

Further, in this issue we're mixing UI and schema issues, and I think we should first get the schema straight. The UI will adapt, for example checking the number of variants before displaying an option selection interface.

Just an idea to think about...

**Comment by aaronjudd** [comment]
Closing, moving to: https://github.com/reactioncommerce/reaction-docs/issues/24
