### ISSUE TITLE
Unclear global subscription to Products collection

### ISSUE THREAD

**Issue by OksentukVlad** [reactioncommerce/reaction#723]
Hello, I found "bold" (not route and not template level) subscription here:
https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/client/templates/dashboard/import/import.js#L1

Do we need it? Maybe we should move it to template?

**Comment by aaronjudd** [comment]
I'm not sure why that's in that spot, but I agree - I don't think it should be there.

**Comment by aaronjudd** [comment]
Fixed in v0.12
