### ISSUE TITLE
Error when running install on Ubuntu

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#726]
If I follow the development instruction on Ubuntu 14.10 (Desktop) I get the following error when I run `./reaction install`. I know @newsiberian has run into this issue as well.

```brent@least-weasel:~/Projects/js/reaction$ ./reaction install
cp: cannot create regular file ‘/usr/local/bin/clone-packages.sh’: Permission denied```

**Comment by TwixtedChaox** [comment]
when running the install on a production system.. i find i have to manually install npm. I know the error isn't the same for you as it was for me but maybe under the ubuntu script change from
`sudo apt-get install -y nodejs build-essential git` 
to
`sudo apt-get install -y nodejs npm build-essential git`

it seems the ubuntu version of nodejs doesnt correctly install the npm on its own.

**Comment by zenweasel** [comment]
The line `cp bin/clone-packages.sh /usr/local/bin/` should probably be `sudo cp bin/clone-packages.sh /usr/local/bin/` when running on Linux systems what it is not for OSX systems.

**Comment by jshimko** [comment]
`./reaction install` has been deprecated.
