### ISSUE TITLE
User profile enhancements

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#739]
- Allow the ability to register users with a display name
- Allow users to change their profile name for their account
- Allow sign in / sign up with username, configurable in dashboard
- Allow users to upload a custom profile image

**Comment by bluerabbbit** [comment]
Why not use nova:users for most of it?

**Comment by jshimko** [comment]
@bluerabbbit because it has a bunch of dependencies on other parts of Telescope.  It wasn't designed to be Meteor app agnostic.  It was only published publicly to Atmosphere for convenience of distribution (not unlike several Reaction packages).

**Comment by paulgrever** [comment]
@spencern looks like this is a known issue.

**Comment by komyg** [comment]
Hi, I would like to contribute to this bug. Is it still a problem?

**Comment by mikemurray** [comment]
Yes, this issue is stil relevant, and any contribution is welcome.

**Comment by aaronjudd** [comment]
Closing - insufficient details.
