### ISSUE TITLE
Product tags bookmark icon and tags visibility on product page

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#742]
I found 2 unclear things with tags management on product page for me:

* Strange bookmark icon for tags in case, when slug of tag is equal to slug of product. It's here 
https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/client/templates/products/productDetail/tags/tags.js#L14-L26
What is it for? Any hidden purpose?

* Tags area is not visible on product page for non-admins. That's because, condition `currentHashTags` is always true. https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/client/templates/products/productDetail/tags/tags.js#L6 What is this condition for? It's seems senseless for me.

**Comment by aaronjudd** [comment]
`hashtagMark `displays which one of the product's tags are in use as the current url, and is for the admin user.

The second part here, tags should be visible when not admin, unless there are no product tags. There is  know bug here that "Tags" header label should not display if there are no tags.

The product.handle to lower case it to make sure that we can always do a comparison to the slug in lower case.

**Comment by ramusus** [comment]
> hashtagMarkdisplays which one of the product's tags are in use as the current url, and is for the admin user.

thanks @aaronjudd, but what is it for? why admin should mention equality of urls between product and tag?

About tag section. Why just don't show tags with links for non-admins?

**Comment by zenweasel** [comment]
@ramusus You're right, the tags should show in non-admin. That's why we assigned it to @mikemurray to fix it. :)

**Comment by aaronjudd** [comment]
Resolved in https://github.com/reactioncommerce/reaction/pull/783
