### ISSUE TITLE
There is event 'pin product', but no any layout for it

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#745]
I found event for pinning product, but there is no any layout for this in the whole project https://github.com/reactioncommerce/reaction/search?utf8=✓&q=pin-product

Why is that? Do we need this any more?

Event is here https://github.com/reactioncommerce/reaction/blob/4580eb5338f8a50d91583f84929a789a40b17c9c/packages/reaction-core/client/templates/products/productGrid/item/item.js#L157-L173

**Comment by ramusus** [comment]
The same for "clone-product" event https://github.com/reactioncommerce/reaction/search?utf8=✓&q=clone-product&type=Code

**Comment by mikemurray** [comment]
Thanks for catching this. Need to do some cleanup.
