### ISSUE TITLE
Translations of Alerts - i18nKey doesn't work

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#746]
During investigation why all alerts don't want to be translated I found these strange lines in the code:

```
      if (options.i18nKey) {
        if (options.i18nKey === i18n.t(options.i18nKey)) {
          i18nMsg = i18n.t(options.i18nKey);
          if (i18nMsg !== options.i18nKey) {
            message = i18n.t(options.i18nKey);
          }
        }
      }
```

I don't understand how it should works. @aaronjudd what is the purpose of this change
https://github.com/reactioncommerce/reaction/commit/ec6b56c3e725ca5b4f2bcc7178786d092fdab217#diff-ff99ac671c39f6220593dcea3e9ef06dR78 ?

Got these lines from here
https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/client/templates/layout/alerts/bootstrapAlerts.js

**Comment by aaronjudd** [comment]
Looks like "if i18n doesn't translate a message then use the field name as the message.".  A fallback perhaps, for i18n failure.. and a visible way to know that the label is incorrectly configured?

**Comment by ramusus** [comment]
If I'm not mistake this is equal to:
```
a = options.i18nKey
b = i18n.t(options.i18nKey)

if a and a == b and b != a, then message = b
```

**Comment by aaronjudd** [comment]
You're right, that's wrong.

**Comment by mikemurray** [comment]
maybe needs to be.

```
      if (options.i18nKey) {
        if (options.i18nKey !== i18n.t(options.i18nKey)) {
          message = i18n.t(options.i18nKey);
        }
      }
```

**Comment by zenweasel** [comment]
Approved
