### ISSUE TITLE
Update i18next to the latest 2.0 version

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#747]
During making new translations for Alerts I found that it's better to use sprintf plugin of i18next lib. I see we are using very outdated version of lib - 1.10.2. And I didn't find the way how to do it with current version. What do you think about upgrade this to the latest version with support of plugins?

**Comment by aaronjudd** [comment]
good idea. I've been talking about moving the i18n into it's own package as well. I'd probably like to do this all at once..

**Comment by ramusus** [comment]
I can extract i18n from the core and publish it as separate package, If you want this help. And update to latest version as well. I'm really interested in decomposition tasks as long as I propose this idea in #731.

**Comment by aaronjudd** [comment]
let's leave it as is for now, but happy to take PR's for updated libs. I think when I move it out, it will be a package that includes administration, and maybe localization.  I don't want to get too granular with the packages, so need to decide what the right functionality would be to include.

**Comment by aaronjudd** [comment]
@ramusus i18n is now it's own package, if you want to update..

**Comment by newsiberian** [comment]
Oops, looks like current i18next version doesn't understand such constructions:
```js
Alerts.toast(
  i18n.t("gridPackage.pkgDisabled", { app: i18n.t(self.i18nKeyLabel) }),
  "warning"
);
```
:+1:  for updating.

**Comment by aaronjudd** [comment]
I will update and move the lib from core into the i18.

**Comment by ramusus** [comment]
Yes, support of sprint was one of the main reason of my proposal
