### ISSUE TITLE
Unable to create new admin user (clicking "Access" does nothing)

### ISSUE THREAD

**Issue by ViktorNova** [reactioncommerce/reaction#75]
Hello! I just installed a new instance of Reaction without a hitch, sweet!
I don't see a way to change my admin user from the gibberish that was auto generated on the first run, am I missing something? 

I tried clicking on "Access" in the dashboard, and it didn't have any effect

**Comment by abhisheksoni27** [comment]
Can you explain again how  to create a new admin user, because the answer above did not work.

**Comment by aaronjudd** [comment]
@abhisheksoni27 are you using the `development` branch? 0.6.0 has a new permissions setup ( but may still require the email server to be configured, `localhost` might work though depending on your setup)

**Comment by gcaracuel** [comment]
So sorry to re-live this old issue. But is a mess to be forced to validate email for example when just validating from a Docker container, There is no way to bypass this verification? as the default admin creation does but setting the email and password using ENV variables.

**Comment by aaronjudd** [comment]
@gcaracuel  our docker images are running a production image.  it's always going to verify the first admin user created.  However in `development` mode, we don't verify the email.  You could either build a development docker image, run locally, or we could add an additional env flag to suppress email validation.

**Comment by hydrotik** [comment]
Any update on the ENV flag to suppress email validation? I'm using this on Heroku and have been using env settings within Heroku to set the admin user settings. I was able to manually change the validate flag to true through mLab.

**Comment by jshimko** [comment]
The initial admin email is [set to validated by default when in development](https://github.com/reactioncommerce/reaction/blob/master/server/api/core/core.js#L297-L299) and you should receive a [validation email when in production](https://github.com/reactioncommerce/reaction/blob/master/server/api/core/core.js#L305), so there shouldn't be a need to manually override anything.  Worst case, you could edit the record in the database, but I don't really see why that would be necessary when all you have to do is click the validation link that gets emailed to you.

**Comment by hydrotik** [comment]
Maybe I am missing something here, but how do you get a verification email through the initial deployment if you have to login as admin and hook something like Sendgrid in order to get said verification email?

**Comment by jshimko** [comment]
You can set the mail with the a `reaction.json` registry import, or the [`MAIL_URL` Meteor settings key](https://github.com/reactioncommerce/reaction/blob/master/settings/dev.settings.json#L3), or the `MAIL_URL` environment variable.

https://github.com/reactioncommerce/reaction-docs/blob/development/admin/email.md#advanced

**Comment by stunjiturner** [comment]
hey guys, i am running on heroku, i created the environment variables on my running app, but i cannot get a admin user? i looked into the mongodb but the created password is encrypted. How to create a new admin user?
