### ISSUE TITLE
[suggestion] Move Inventory computations to server side

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#752]
Hi,
I think, we need to consider the possibility of moving all common inventory methods to server side and additionally rethink the subscription policy.
For now I see the following different ways:
1. We could completely remove inventory subscription.
2. We could leave a subscription for PDP and for products in cart.
3. We could leave a subscription for dashboard page where it needed.

**Comment by aaronjudd** [comment]
@newsiberian there's a lot of refactoring on this going on in the v0.12 branch, and I had a TODO regarding `inventory` subscriptions.  If you could could always answer  "why" on your issue that would really help explain the context.

**Comment by newsiberian** [comment]
Hi, I'm sorry for that :smile:, you're right.
When testing with 300 products, I notice a long loading time (~8 seconds maybe even more) on first page. This is inventory subscription which loads. Just imagine how much data it contains if we have 300 products * 3 variants * 40 items per variant and user subscribe to all this data.

So, I don't know yet if the user really need even one product inventory data. I haven't dive into it yet, but common sense says, we need to do something with it, maybe, as I suggest earlier, move all computation to server side.

For people who want to make a lot of products, but don't know how:
```javascript
var product2 = ReactionCore.Collections.Products.findOne({_id : "BCTMZ6HTxFSppJESk"});
for (var i = 0; i < 300; i++) {
  Meteor.call("products/cloneProduct", product2)
  console.log(i)
}
```
run this in browser's console

**Comment by aaronjudd** [comment]
Note that this subscription only publishes when you are an owner/admin - a "regular" user wouldn't get this data and for an admin user a slower load isn't necessary a big disadvantage, since that's also preventing recurring subscription updates,etc.

**Comment by newsiberian** [comment]
Oh.. I missed that. I've been logged in as admin while this tests all the time.

**Comment by aaronjudd** [comment]
without digging into what changes need to be made, or why that sub is even needed ..  I really didn't want that subscription on the client, so I'm ok if we can make everything server side.

**Comment by aaronjudd** [comment]
Believe this to be resolved.
