### ISSUE TITLE
Proposition of using mdg:validated-method package for Meteor methods

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#759]
In Meteor Guide http://guide.meteor.com/methods.html there are recommendations to use package https://atmospherejs.com/mdg/validated-method for writing Meteor methods.

Benefits of ValidatedMethod
* Have an object that represents your method. Refer to it through JavaScript scope rather than by a magic string name.
* Built-in validation of arguments through aldeed:simple-schema, or roll your own argument validation.
* Easily call your method from tests or server-side code, passing in any user ID you want. No need for two-tiered methods anymore!
* Throw errors from the client-side method simulation to prevent execution of the server-side method - this means you can do complex client-side validation in the body on the client, and not waste server-side resources.
* Get the return value of the stub by default, to take advantage of consistent ID generation. This way you can implement a custom insert method with optimistic UI.
* Install Method extensions via mixing.

**Comment by zenweasel** [comment]
@ramsus I have already started using mdg:validated-method as I am rewriting the payment packages. (nothing I have committed yet) We plan on migrating our code over as we touch it basically. Our main purpose is to make the code more testable.

We are already sold on the idea as it's come up several times.

**Comment by zenweasel** [comment]
This is ongoing.
