### ISSUE TITLE
Email Template functionality

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#76]
Need to fix email sending functionality.  Used to work with Handlebars parsing on server side, this no longer works, nor is it the ideal solution.  Need to move into database, and manage email  from admin interface.

**Comment by aaronjudd** [comment]
@aldeed I can actually take a portion of this in the guest_checkout branch. I propose to start,  rather than reading files for the email templates, we move email templates into a collection, with a config object. The config object might just be a placeholder for now.  I'll load the templates as fixtures, as with languages,etc.  This will setup to an editable interface, and additional config properties for a scheduler / service mapping later.

**Comment by aldeed** [comment]
Makes sense
