### ISSUE TITLE
[Products] Add new product type: product bundle

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#762]
Hello, in this issue I am requesting a new product type. Let's call it "bundle". It's purpose is to hold another products as top-level variants or child variants.
#### Live example:

We have a list of products: pendants and chains.
We could create a product bundle with top-level variant: pendant and several chains as child variants.
Also product bundle could presents a line (brand or group) of pendants - via different top-level variants and each could contain few chains on customer choice.

**Comment by newsiberian** [comment]
Hello, **Spencer**. How urgently do you need this functionality?

I have some ideas about implementation.
I think we need new package for this with similar schema like `Product`, but with differences. Let's call it **Bundle**  We don't need `ancestors` in it, but we need an array of descendants ids, which will be ids of products. Also we could implement two optional choices for sellers: `discount` field, which will be calculate bundle price depend on `%`, or just fixed `price`, like `$999`.

`addToCart` method should understand which type of product it receives and acts accordingly. Perhaps we will have to modify `cart.items.variants`.

`products/createProduct` should create clean product without variants inside for `bundle` type. In PDP we should see `Add Product` against `Create Variant` with all logic.

It would be cool to have feature like: selecting several products in `productGrid` now opens setting bar with settings. We could add button here, like "Build Bundle" with selected products, but to make it fully functional this settings bar should keep it's state when route changes, because usually you want to put inside bundle products from different categories.

`Bundle` type could have it's own media. Currently `simple` type couldn't.

**Comment by spencern** [comment]
Hi @newsiberian, we are looking to implement this functionality by May 1 ideally.

I agree that a new package is needed, similar to Product.

I like your `addToCart` and `products/createProduct` suggestions as well as your ideas for the build bundle UI. I think that a `%` based discount or a fixed `price` would be satisfactory for our needs.

It seems like the time consuming and potentially difficult part of this implementation will probably be the UI and it sounds like we are of similar thought in terms of the functionality.

**Comment by newsiberian** [comment]
I'm in, but I need to build the same UI for my `react`-dependent project, so, I'm going to build server part + UI for `react`. Could you do the most part of `blaze`-dependent changes by yourself?

**Comment by newsiberian** [comment]
@spencern, what do you think about the expansion of this idea to something like `nested bundle`? By this I mean the following:
Let's say you have two entities: 1. product with a pair of skis. and 2. bundle with a different pairs of boots  (let's say this bundle contains 3 brands (products) of boots. Each products (boots) contains different sizes).

Now imagine what we can build a bundle from 1st and 2nd, from `product` and `productBundle`. And customer could select different brands of boots to ski when he come to this bundle page.

**Comment by newsiberian** [comment]
I do not understand a few moments in UI realization. How these changes we want to make will be implemented to current reaction PDP (UI)?

I mean, we don't build entire new type of product, even more, `bundle` is a good addition to current system. How `simple` type and `bundle` type could coexist together?
I mean, we have a route `/product/bla-bla-bla` which is suitable for type `simple`, but the same route will be suitable for a `bundle` type too, am I right? So how could system will understand which template to load? Maybe @aaronjudd brings clarity on this? Or @spencern, do you understand, how this stuff works?

**Comment by aaronjudd** [comment]
@newsiberian the product type will determine the layout...  (structure from Shops.layouts)

**Comment by spencern** [comment]
@newsiberian I think I understand the UI well enough to implement a bundle type of product. I'm in the middle of creating the UI for GetOutfitted and it's involved some significant customizations to the PDP UI.

I'm not ready to commit to a `nested bundle` yet where a bundle is defined by tag or product type, but I do see where it could be valuable. For now, my goal is to get a simple bundle working that permits selection of variant options of each component of a bundle product.

I do think that `bundle` will need to be a brand new type of product in addition to `simple` and `variant` and that `bundle` by default will be a container of `simple` (or other types) products. I think that the current routing structure will be sufficient for bundles.

Here's my checklist of what needs to happen for Bundles to exist

- [ ] Schema definition
- [ ] inventory update method
- [ ] inventory check method (qty available)
- [ ] Admin UI for creating a bundle (select from existing products) + all helpers
- [ ] Customer UI for selecting a bundle and bundle variant + all helpers
- [ ] Cart UI for displaying bundle in cart

Is there anything else you can think of that will need to be considered?

**Comment by newsiberian** [comment]
Hello,
> Is there anything else you can think of that will need to be considered?

I like this list. If you don't mind, lets work inside your repos.

**Comment by spencern** [comment]
That's fine with me. We haven't started this repo yet, but have had some internal discussion. We should be starting work on it in the next week and a half or so.

**Comment by aaronjudd** [comment]
@spencern @newsiberian @paulgrever you now have write privileges now on the reaction repo.  You can make branches and commit directly without forks,etc.  The `master` and `development` branches are protected, and will only accept PR when fully passing.

**Comment by newsiberian** [comment]
@spencern, hello, I'm sorry, but I can't help you right now with this task, because, suddenly, today I've known that our project should be launched into production in several months, so I need to focus on it. I've already write to @aaronjudd about this.

**Comment by spencern** [comment]
@newsiberian thanks for letting me know. I'll still be working on this as we will still need it. 
@aaronjudd thanks for the privileges.

**Comment by spencern** [comment]
@newsiberian and @aaronjudd we are in progress on this issue. Anyone interested can follow along at https://github.com/getoutfitted/product-bundler

**Comment by aaronjudd** [comment]
Closing - insufficient details.
