### ISSUE TITLE
Cannot complete checkout on second visit when using Authenticated user

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#765]
Testing this on my store: https://weaselworld.reactioncommerce.com

Steps to reproduce:

1. Register a new user via the "Sign In" dialog
2. Complete an order
3. Return to home screen and add an item to cart
4. Click on "Checkout"
5. Receive the message "Woah, your cart is empty"
6. Receive this error message in the client console:

```  Exception from Tracker afterFlush function:
68ba19816c0c76ce784cdd7543d3969f14ed59d4.js?meteor_js_resource=true:5 TypeError: Cannot read property 'workflow' of undefined```

Running through the exact same scenario as an anonymous user works fine.

**Comment by zenweasel** [comment]
This is the same topline error as https://github.com/reactioncommerce/reaction/issues/730 but a very different scenario.

**Comment by zenweasel** [comment]
Verified this is still happening in v12. If you refresh or add another item to the cart and then checkout you can complete checkout without problems. Also subsequent checkouts (after completing second checkout) complete without problems. I can only recreate it by doing a `reaction reset` and starting over.

Error in console:

```
TypeError: Cannot read property 'workflow' of undefined
    at null.<anonymous> (checkout.js:19)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:457)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:192)
    at fireCallbacks (view.js:279)
    at Object.Tracker.nonreactive (tracker.js:589)
    at view.js:276
    at Object.Blaze._withCurrentView (view.js:538)
    at Object.Blaze._fireCallbacks (view.js:275)
```

**Comment by zenweasel** [comment]
This error is being caused by the fact that `const cart = ReactionCore.Collections.Cart.findOne();` yields nothing even though the cart exists in Mongo. (I get the same result doing it in the console).

**Comment by aaronjudd** [comment]
What happens if you re-subscribe to the cart at that point?

**Comment by zenweasel** [comment]
`sessionId = Session.get("sessionId");`
"ahHdSqRnCPNh9QxLZ"
`ReactionCore.Collections.Cart.findOne();`
undefined
`ReactionCore.Subscriptions.Cart = Meteor.subscribe("Cart",
    sessionId,
    Meteor.userId()
  );`
Object {subscriptionId: "3yzQKZ4s9WsQpbR74"}
`ReactionCore.Collections.Cart.findOne();`
Object {_id: "RyX4jft62gQsiDJeq", sessionId: "ahHdSqRnCPNh9QxLZ", userId: "tumsvApvgB6y7xwxb", shopId: "J8Bhq3uTtdgwZx3rz", createdAt: Mon Feb 29 2016 10:48:36 GMT+0800 (PHT)…}
```

**Comment by zenweasel** [comment]
So does that mean that the `ReactionCore.Subscriptions.Cart.ready()` event is firing before it's actually ready?

**Comment by aaronjudd** [comment]
yes, and should be checking that the subscription is ready first. a couple things.. bear in mind that the templates now control their subscriptions, so it might be that in normal workflow it's subscribing to Cart before it gets here, and in this scenario it never subscribed.   if you are doing a reaction reset, and not refreshing the browser then this is expected, and likely because it didn't get a fresh subscription to the new session.  if it happens just in the normal course after a checkout, it's likely that the subscription isn't updating when the existing cart gets deleted during the order process.  in all cases though, sounds like a subscription issue...

**Comment by zenweasel** [comment]
Yeah, since this only happens when placing a second order (but not a third??) it must be something with subscribing to the wrong thing

**Comment by hrath2015** [comment]
Hey Guys,
Are u able to complete Order with Product image(s) uploaded on Create Product.  Looks like this is not working for me and getting in to below error:
![image](https://cloud.githubusercontent.com/assets/14071646/13386225/1f9ed026-ded0-11e5-99e8-cabb40814ccc.png)
I tried calling subscription as suggested by Aaron, but no luck. Looks like similar problem.
""  const ccoMed=Meteor.subscribe("Media");
    if(ccoMed.ready()){
      if (defaultImage === ReactionCore.Collections.Media.findOne({
        "metadata.variantId": this.variants._id
      })) {
        return defaultImage;
      }
    }""

If I do this from Browser Console All return fine.  See:
![image](https://cloud.githubusercontent.com/assets/14071646/13386285/a866ef38-ded0-11e5-8869-eea1e2d34b5a.png)

**Comment by zenweasel** [comment]
@hrath2015 Is this issue related to the title here? Looks to be unrelated? Can you give me steps to reproduce the error you are seeing?

**Comment by hrath2015** [comment]
I believe underlying cause is subscription which is what makes it related.  Though u found it in different part of workflow.  Steps:  Create A product and upload some images.  Create and Order.  On complete checkout screen u will be shown blank screen with error message in browser console as url not defined.

**Comment by zenweasel** [comment]
You're probably correct that these are both subscriptions but I think it's a really different scenario as the error I get only happens under one particular circumstance. So I think this error is specifically about just one subscription at one time. Could we open a separate issue for the problem you are seeing? You can reference this item in that item if you want to show they are related.

**Comment by zenweasel** [comment]
@hrath2015 FWIW, I was just able to recreate that error, I created a new issue for it.
https://github.com/reactioncommerce/reaction/issues/831

**Comment by hrath2015** [comment]
Thanks a lot.
