### ISSUE TITLE
Error when signing out

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#766]
If I sign out after registering a user I get this error in the console and the "Ooops! You don't have permission to view this content"

```Exception in template helper: TypeError: Cannot read property '_id' of null```

Steps to reproduce:

1. Register a new user
2. Go to "Profile" page to view your orders
3. Select "Sign Out"
4. Receive error messages above.

Probably it just needs to redirect away from the profile page on signout? This might be a good "starter bug" for somebody who wants to contribute?

**Comment by aaronjudd** [comment]
still valid in v0.12?

**Comment by zenweasel** [comment]
Verified fixed in 12.
