### ISSUE TITLE
Alert shows "undefined is not visible/is now hidden" when toggling show/visible in product settings

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#767]
Trivial bug

Steps to reproduce:

1. `reaction reset && reaction`
2. Go to home screen
3. Click on gear icon
4. Click on "eye" icon (which says "Publish" even though the product is already visible)
5. A toast alert pops up saying "undefined is now hidden"

**Comment by ramusus** [comment]
I can not reproduce "undefined is not visible/is now hidden" alert.
Installation from development branch gives me "BASIC REACTION PRODUCT is now visible/is now hidden"
And icon in Edit Product panel is always with crossed eye and title "Publish", which sometimes is not right of course. But it's for group editing and I didn't see any functionality for adjusting this icon depends on which products are selected.

**Comment by zenweasel** [comment]
I can't reproduce this error any longer either. Closing.
