### ISSUE TITLE
Currency always USD

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/reaction#77]
After editing "Currency" and "Money Format" in settings and changing "fa-usd" in productDetail.html:48 to fa-eur for testing, there are many occurrences of "$" while running the app. So obviously currency changing does not work as expected yet. In the meantime, is there any way to manually change the currenry? Where do i have to hack in? Thanks and keep up the good work guys, great stuff!

**Comment by abhisheksoni27** [comment]
This is not fixed. Even after changing it in the settings, the currency is still shown as USD.
