### ISSUE TITLE
Add `Reaction.` namespace and deprecate ReactionCore

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#772]
To avoid overpopulating of random Reaction camel cased exports we should adopt a cleaner convention using `Reaction.`   

Add exportable `Reaction` and move to a convention of:
```
Reaction.Core.
Reaction.Collections.
Reaction.Subscriptions
Reaction.Checkout
Reaction.Import
```
etc...

Existing namespace of  `ReactionCore`,` ReactionImport`, etc  can be wrapped, mapped with a warning added.

**Comment by ramusus** [comment]
Completely agree with this decision. I will start support it in my packages

**Comment by spencern** [comment]
Also agree with this decision. :+1:
