### ISSUE TITLE
Add Tour on First Launch

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#78]
The interface is pretty intuitive, but I feel like there should be a short tour for the admin the first time the app is launched, maybe with some way to replay it later. Key points would be:
- How to access dashboard
- Explain the "click anything to edit it" paradigm
- Maybe a few other tips based on whatever the most common newb questions you're getting are

**Comment by aaronjudd** [comment]
I'm closing this Tour issue.  It will happen someday.  Maybe. It will deserve it's own fresh epic on that day.
