### ISSUE TITLE
Edit Product page template alignment issue in Arabic language

### ISSUE THREAD

**Issue by saad91** [reactioncommerce/reaction#780]
I have found some minor alignment issue when i switch to Arabic language in the product edit page. Check the attached images to see the difference between the English version and Arabic version
<img width="1157" alt="screen shot 2016-02-16 at 10 15 14 pm" src="https://cloud.githubusercontent.com/assets/17137214/13087924/10f441ac-d4fb-11e5-9c0e-c83c9fcb08e8.png">
<img width="1140" alt="screen shot 2016-02-16 at 10 15 03 pm" src="https://cloud.githubusercontent.com/assets/17137214/13087925/10f8d0aa-d4fb-11e5-81a4-6f53a0570569.png">

**Comment by aaronjudd** [comment]
Related to #478, @mikemurray both should be quick updates.
