### ISSUE TITLE
Edit Product Pane in the Main page Product Grid "No controls for this view." issue

### ISSUE THREAD

**Issue by saad91** [reactioncommerce/reaction#781]
I have noticed a weird behaviour when following this sequence of actions:
1- Go to the main page (product grid).
2- Click on the settings gear on one of the products.
3- Change the the size of the product.
4- Notice that all the controls on the pane goes missing.
5- Click on the product setting gear icon again.
6- They are back!

Check the attached images for more details.
<img width="1263" alt="screen shot 2016-02-16 at 10 18 51 pm" src="https://cloud.githubusercontent.com/assets/17137214/13088160/24690b18-d4fc-11e5-9434-45f2662d6e76.png">
<img width="1269" alt="screen shot 2016-02-16 at 10 19 02 pm" src="https://cloud.githubusercontent.com/assets/17137214/13088080/e0ba5462-d4fb-11e5-9ded-1203d5d8a00a.png">
<img width="1277" alt="screen shot 2016-02-16 at 10 19 15 pm" src="https://cloud.githubusercontent.com/assets/17137214/13088079/e0b8415e-d4fb-11e5-9dbd-81bfe39e2b30.png">

**Comment by aaronjudd** [comment]
@saad91 thanks for reporting, some tune-up in progress with v0.12 on this.

**Comment by zenweasel** [comment]
@saad91 I cannot reproduce this error/behavior. Can you verify if this is still happening for you in the current `development` branch. TIA!

**Comment by aaronjudd** [comment]
unable to reproduce.
