### ISSUE TITLE
Error when checking out via Paypal Express

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#784]
Not sure if I should enter this here or against the PayPal package so...

After completing Paypal Express checkout I am getting this error in the console and the confirmation page never renders. The order does seem to complete and reloading the page forces it to render.

```Exception from Tracker recompute function:
debug.js:41 Error: Can't set timers inside simulations```

Steps to reproduce:

1. Place an order using Paypal Express.
2. Once the modal closes the page clear and the above error message appears.
3. Observe that confirmation page never loads.

**Comment by aaronjudd** [comment]
The full error that I am seeing is
 ```
Exception from Tracker recompute function:
debug.js:41 Error: Can't set timers inside simulations
    at withoutInvocation (timers.js:5)
    at bindAndCatch (timers.js:13)
    at Object._.extend.defer (timers.js:68)
    at layout.js:17
    at Object.Meteor.startup (startup_client.js:63)
    at Object.render (layout.js:13)
    at layout.js:40
    at Tracker.Computation._compute (tracker.js:323)
    at new Tracker.Computation (tracker.js:211)
    at Object.Tracker.autorun (tracker.js:562)
```
debugging leads to 
```
BlazeLayout.render = function render(layout, regions) {
  regions = regions || {};
  Meteor.startup(function() {
    // To make sure dom is loaded before we do rendering layout.
    // Related to issue #25
    if(!_isReady) {
      Meteor.defer(function() {
        _isReady = true;
        BlazeLayout._render(layout, regions)
      });
    } else {
      BlazeLayout._render(layout, regions);
    }
  });
};
```

I suspect this `Meteor.defer` is the root cause here. 

Googling leads to a couple of open issues on Meteor as well as some recommendations to use check this block with `if(Meteor.isServer)` or `if(!this.isSimulation)`.  We could see if modifying the flow-router fixes..

**Comment by aaronjudd** [comment]
Also note, this error doesn't appear 100% of the time, there are some successful loads, and if you get the error a refresh will load the completed page properly - which I think backs up the `defer` being the culprit.

**Comment by zenweasel** [comment]
Closed via:
https://github.com/reactioncommerce/reaction-paypal/pull/39
