### ISSUE TITLE
Error when viewing new orders in the the Dashboard

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#785]
I get this error in the console:

```Uncaught Error: Must be attached```

Steps to Reproduce:

1. Place an order via any means (must be a NEW order)
2. Have the sidebar already open for any reason
3. Click on the green "Start" button
4. Order does not change and the above message appears in the console.

**Comment by aaronjudd** [comment]
The order does change for me, but I've seen the error....
