### ISSUE TITLE
UI issue when using language selector

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#786]
Trivial bug.
What language am I using?

<img width="202" alt="localhost_3000_reaction_dashboard_orders_filter_processing__id_e8gjyrqc32eh7a45e" src="https://cloud.githubusercontent.com/assets/72819/13131719/6f5d66d2-d628-11e5-92d8-4f313f96dadc.png">

**Comment by aaronjudd** [comment]
fixed in my i18n branch.
