### ISSUE TITLE
No icon for "Dashboard" in sidebar

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#787]
<img width="171" alt="localhost_3000_reaction_dashboard_accounts" src="https://cloud.githubusercontent.com/assets/72819/13131786/d4f3273e-d628-11e5-8790-8fc874e371b2.png">

**Comment by aaronjudd** [comment]
any particular browser,etc.. steps to replicate?   I don't see this...   did you pull "reaction" itself, not just the packages?  because the font is declared in `reaction/public`, not a package.

**Comment by zenweasel** [comment]
I am only seeing it in Chrome (shows up in Safari and FF). The steps to replicate are just go to Dashboard, see no icon. The style for the icon is there, but the icon itself does not appear. If nobody is seeing this but me we can just close but it's 100% reproducible for me.

I start every morning with `reaction pull && reaction reset && reaction` so I am pretty sure I have the recent code.

<img width="1429" alt="localhost_3000_reaction_dashboard" src="https://cloud.githubusercontent.com/assets/72819/13207676/0accd5f0-d94c-11e5-9fed-ca731ed9252b.png">

**Comment by aaronjudd** [comment]
Does this exist on your local? https://github.com/reactioncommerce/reaction/tree/development/public/font

**Comment by spencern** [comment]
I'm seeing this as well on both my local machine and @paulgrever's local machine

I have the public/font directory on mine.

![image](https://cloud.githubusercontent.com/assets/1203639/13233512/2bdebc34-d971-11e5-8918-c3f47c9cb532.png)

**Comment by zenweasel** [comment]
@aaronjudd Yes, I have the font file. I've tried flushing every cache I can think of.

**Comment by aaronjudd** [comment]
@zenweasel @mikemurray has this been resolved?

**Comment by zenweasel** [comment]
Not for me. Works in 0.11.1, broken in 0.12

**Comment by aaronjudd** [comment]
@mikemurray I debugged this a few weeks ago with @zenweasel and the font is loading twice, the first time it's loading with a bad path.. meteor is looking in the packages dir, and not the public/font dir.  Chrome is cool and ignores the first error, but FF/Safari take a dive.

**Comment by zenweasel** [comment]
Actually it's the opposite. FF and Safari handle it correctly. Chrome chokes.

**Comment by aaronjudd** [comment]
Closed with https://github.com/reactioncommerce/reaction/pull/900
