### ISSUE TITLE
Getting Theme is Required Error on Dev V0.12.0 Branch 

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#790]
Getting Below Exception During Start up:

(STDERR)                                           throw(ex);
(STDERR)                                                 ^
(STDERR) Error: Theme is required
(STDERR)     at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:345:1)
(STDERR)     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:328:1)
(STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:83:1

(STDERR)     at [object Object].Mongo.Collection.upsert (packages/mongo/collection.js:624:1)
(STDERR)     at packages/matb33_collection-hooks/upsert.js:96:1
(STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
(STDERR)     at Object.directOp (packages/matb33_collection-hooks/collection-hooks.js:18:1)
(STDERR)     at [object Object].CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/upsert.js:95:1)
(STDERR)     at [object Object].collection.(anonymous function) [as upsert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
(STDERR)     at Object.registerTheme (server/processTheme.js:102:37)

To make it work commented method call "ReactionUI.registerTheme("  both in reaction-ui and reaction-ui-navbar package, register.js file.

**Comment by aaronjudd** [comment]
Was this with a fresh install/ reset db?

**Comment by hrath2015** [comment]
I will try with Fresh install and report back.  When u say fresh u mean clone all over again right?

**Comment by aaronjudd** [comment]
`meteor reset`

**Comment by hrath2015** [comment]
No luck. reset did not work. Then tried  a Fresh clone and Install on dev branch. Still Same error.

**Comment by aaronjudd** [comment]
@hrath2015 do you have customized startup data? shops, etc?

**Comment by hrath2015** [comment]
The issue is coming from registerTheme() method where it parses  style file   
`const annotations = cssAnnotation.parse(styles)`
I think the cause is node version mismatch. postcss  need >12 and what  I have is 10.36.
see below:
npm WARN engine postcss@5.0.16: wanted: {"node":">=0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
