### ISSUE TITLE
[Marketplace] - checkout

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#798]
[Marketplace] - checkout
- verify and calculate shipping per shop for a cumulative rate as an option
- allow the parent shop rates to be used, or calculate a per shop/item rate. - #2781
- purchase items from more than one shop, verify shopId in cart items 

See: https://github.com/reactioncommerce/reaction/issues/357

> We were discussing with @mikemurray some cart.shipping details. I have some suggestions for when the multi vendor is implemented. With the current cart.shipping schema you can't identify from which shop was the particular shippingMethod selected. I needed to add cart.shipping.$.shopId to my schema in order to have different shipping selected for different shops participating in the same order. I didn't need the cart.shipping.$.items as you have in the order but not in the cart because using this shopId you can identify which items are considered for this shop.

This issue replaces/resolves #154

**Comment by spencern** [comment]
Reviving this Milestone. Will be using it for updating the checkout page @rymorgan @zenweasel @aaronjudd

**Comment by rymorgan** [comment]
Here are some designs around this issue. I have designs that also take into account seeing estimated shipping if we are adding that ability at this stage. I'm basically imagining this as a 

https://zpl.io/2jo7M4V

**Comment by aldeed** [comment]
Closing as fixed in 2.0
