### ISSUE TITLE
[Marketplace] - shop selection

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#799]
**Marketplace - shop selection**

See #357
- navigation selector for shop selection, should be admin and user menu 
- owners should select and view any shop
- admin can see only their shop admins (if they select another shop, reactive permissions update)
- should use getShopId and change to a ReactiveDict that sets the shopId on selection.
- review publications / etc.

**Comment by ramusus** [comment]
@aaronjudd what do you think about making shop selector as one of the products filtration criteria?
Anyway I think we should have opportunity to see all products from all shop in one page (custom eBay). And of course get products of any exact shop

**Comment by Capt-Slow** [comment]
@aaronjudd This is blocking #797 for Milestone v0.15.0.

**Comment by lcampanis** [comment]
We have started working towards getting a guest user to become a seller.
Product `gridControls` are now fixed to allow editing of products belonging to the restricted loggedIn seller with `admin` perm.
Owner can edit/control all products. 
New products have the correct shopId via shopIdAutoValue.

We'll send over a PR for review very soon to make sure we're moving in the right direction based on all the requirements and issues around Marketplace.

Sending an invitation for becoming a seller is okay for new users. We will not be covering this.
We will however look into `owners should select and view any shop`.

**How about Registered users without invitation?** 
They should be able to become a seller, say by clicking a `Become a seller` button from the Profile page? Or something else you have in mind?

The above could be enabled following the same pattern as `Allow Guest checkout`, with `Allow Guests to create Shops`? Or something else?

**Comment by lcampanis** [comment]
When publishing Product detail in /server/publications/collections/product.js, Only the parent shop is taken with const shop = Reaction.getCurrentShop();
Then, the permissions are always checking for owner, which makes it impossible to get a product for sub-sellers with just admin perm.
So far my understanding is that each seller gets his own shopId with the highest perm being admin for his shop, right?
In which case can we proceed with altering that publication with first checking if the current user is in the group for this product, and keep owner perm as a fallback?

**Comment by aaronjudd** [comment]
@lcampanis I think we want really want to check there would be `createProduct` +  shop(group), right? Doesn't necessarily need to be admin, but you are correct that should be the highest permission for each shop.

**Comment by aaronjudd** [comment]
re: Registered users without an invite, a button on the profile page, as well as in the Accounts admin would be fine, but this would be something that we'd want disabled in most shops, so either a settings "can guests become sellers", or an additional role to grant to all default users (in Shops.defaultRoles), that checked for the existence of "permit to become a seller" permission would be necessary to hide these options the permission/settings isn't enabled.

**Comment by lcampanis** [comment]
> I think we want really want to check there would be createProduct + shop(group), right? 
Yes exactly, happy with that.

Re- UI, it feels like `a settings "can guests become sellers"` might be easier to do and maintain. I'll keep you posted on that one. Thanks!

**Comment by aaronjudd** [comment]
Also, I think my original thoughts were that Reaction.getCurrentShop() would always return an active shop, and that this is where we'd incorporate "shop switching" logic (with a setter method).  Views that had more than one shop's data, like a marketplace product grid, etc would be developed specifically without needing getCurrentShop, but as is, should be the source of truth for views.  Also, keep in mind that many client views are not specifically filtering data, but are instead relying on Publications to the the work. 

re: settings.   store in the package registry as `{settings.<seller package>.enabled: true}` when you do.

**Comment by lcampanis** [comment]
> Also, I think my original thoughts were that Reaction.getCurrentShop() would always return an active shop, and that this is where we'd incorporate "shop switching" logic (with a setter method).

Yes that makes sense and for that we have amended `Reaction.getCurrentShop()` to do just that with a new `getCurrentSellerShopCursor`. I'll try and consolidate those and send you a PR soon to make sure we're moving in the right direction.

> Views that had more than one shop's data, like a marketplace product grid, etc would be developed specifically without needing getCurrentShop

That's a good point. We will keep that in mind now thanks!

**Comment by lcampanis** [comment]
Hey @aaronjudd When you guys get a moment, can you code review this for me. 
This allows users with `admin` permission to Add Products.
It's not ready to merge, just need to make sure we are heading in the right direction. https://github.com/reactioncommerce/reaction/commit/bae1f548b770408e691bcc742f21b9150f703807
Thank you!

**Comment by aaronjudd** [comment]
@lcampanis your direction looks good.  I'm thinking we might want to introduce another array of permissions (see defaultRoles in shops), the defined default permissions for seller/admin/shop owners, might need to be more flexible than "admin", "createProduct" -> such as orders, etc.

**Comment by aaronjudd** [comment]
also, if you put [WIP] in the title of the PR, it will be marked as work in progress by pull approve, etc as well, so we'll know it's not ready...

**Comment by lcampanis** [comment]
Hi @aaronjudd! The set of permissions is what we're currently looking at, and we thought a `defaultSellerRoles` could be a good approach to the set of permissions you mention. The set will be applied upon the user clicking the `Become a seller` button in the profile page (only when the new `marketplace` package is enabled). 
In that case, we:
1. Add a new shop for the loggedIn user
2. We add the new set of permissions to the user, replacing the existing `defaultRoles` with `defaultSellerRoles`. He is now `admin` + (all other perms for sellers we decide on ie. orders).

Additional role-based perms ie. `moderator`, `manager`, etc, could be added individually for each user based on account management for each individual shop, ie the shop admin adds a user to become a `manager` for that shop? Food for thought..
How does that sound? We carry on with a new `marketplace` package to take care of shop switch, seller button, etc.

**Comment by aaronjudd** [comment]
Yes, that all makes perfect sense to me, and is how I'd approach it.

**Comment by lcampanis** [comment]
Hi all! I have just pushed an update with the new `reaction-marketplace` module. Feel free to code review when you can. I have also updated the description in the PR https://github.com/reactioncommerce/reaction/pull/1591 in detail. It seems to be working well now, and with the amended shop functions being more flexible on shopIds we could start looking at the admin switch UI. 

So now, if you run a fresh instance on the `799-marketplace` branch, We've got the marketplace module with autoEnable on, so you can register a test user as usual, once logged in go to the profile page, scroll down and become a seller, your dropdown menu should be updated with new perms and you can go ahead and add a product in your new shop. We kept all the existing product flows in the code intact. The `defaultSellerRoles` perms will need to be looked at, probably quicker by you directly if you don't mind, as we haven't had the chance to handle all parts of the platform just yet in order to decided which one are needed.
We'll spend more time testing and optimising our code as we go along, but really looking forward to your feedback. ;)

**Comment by lcampanis** [comment]
@aaronjudd We'll pick this up today, just need to know if the direction is still okay with you mainly for the core changes and plugin structure. Happy for us to continue as is? Thanks!

**Comment by aaronjudd** [comment]
@lcampanis  just finished testing #1591 out, great progress there.  We're on exactly the same page here, the approach is solid to me and how I intended to go about this.  I'll add specific comments on the PR itself about any potential issues I see.  Roles looked good as well, we're going to review the Accounts/roles in 0.19 as well, we're aware of some inconstancies (broken stuff) that need cleanup, so it will get another review then as well.

All the next steps here make sense - I think the bulk of the work will be testing product publication, checkout/cart, and order fulfillment.  We briefly testing the architecture with a multiple-seller item cart, single order workflow, but decided the UI was too complicated in the order fulfillment workflow and never finished that, so I can at least say that should be not too bad, but likely the majority of the work todo here. 

Re: domains: it was always the intention to support multiple domains/ aliases, but I think we really only ever implemented [0].  That may still be fine, but something to take a deeper look at that and how the shop prefix route is being used.  Ideally we're supporting the combination of domains and routing to provide: _marketplace.com/shopname/_, _shopname.marketplace_, shopname.com. 

Background that might be useful:  The "launchdock-connect" module should make a call to a LaunchDocker server when a Reaction shop is running on LaunchDock, that will generate a new SSL certificate and proxy the new url and create a new running shop stack.  LaunchDock is meant provide multi-tenant (vs marketplace) to Reaction, and launches new Reaction shops from env/configuration data.  ie, we can preconfigure packages, shop name, create an ssl cert with a DDP call to LaunchDock.  This is an important part of the workflow to keep in mind.

**Comment by lcampanis** [comment]
@aaronjudd All ready-ish ;)
- PR task list updated
- Comments in #1591 at the bottom

**Comment by spencern** [comment]
This is somewhat done. Shop selection dropdown is built in #1934 and the admin permissions are issues in the Marketplace Permissions project described here: #2183
