### ISSUE TITLE
Make dashboard settings menu options clickable

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#80]
On the first square of the dashboard, the labels ("Shop" and "Access") should also be clickable, not just the icons.

I would also like a hover/active border or background shading around the whole row (e.g., from "Shop" label all the way to it's icon on the right).

**Comment by aaronjudd** [comment]
Click ability added,  configuration in Package.registry.  There will be graphs going to the dashboard eventually. I think it's good at this stage.
