### ISSUE TITLE
Dashboard layout problems in Safari 9

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#803]
I see in dashboard this situation in Safari 9:

![bad](https://s3.amazonaws.com/f.cl.ly/items/3c0y0T2Z3h180C0u3R1Z/Image%202016-02-21%20at%209.50.41%20PM.png?v=3fa42d20)

In Chrome everything much better

**Comment by aaronjudd** [comment]
I believe this is resolved now, in Safari 9.0.3.. looking good to me. can you confirm?

**Comment by zenweasel** [comment]
Looks good to me as well FWIW

**Comment by ramusus** [comment]
Yes, everything is perfect now
