### ISSUE TITLE
[specification] i18n management improvement

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#804]
Hello, I hope Aaron forgive my arrogance. By this issue I want to asking for help in building i18n management system.

From my point of view it should:
- pick up translation files from custom packages. (i.e. from folder `pkgName/private/data/i18n/`);
- automatically update `translations` collection, each time packages added/removed;
- or at least update collection by clicking button in dashboard settings. Something like "Sync translations"
- or maybe you could offer another syncing mechanism for our purpose.

For better understanding: Why we are using such strange way for keeping translation? Because of SimpleSchema. [More info](https://github.com/aldeed/meteor-autoform/issues/483)

But the best decision I see is to write a `i18next-meteor-backend` like [this](https://github.com/i18next/i18next-node-fs-backend). With help of this package we could hold our translations inside minimongo + use all delights of i18next functionality. It could be pretty native way.

Feel free to self-assignment to this issue :wink:

**Comment by ramusus** [comment]
I already thought about picking translations up from custom packages and merging everything in one big JSON. And tune i18next to use namespaces, variables inside strings and other cool stuff, But in case we will decide to use external tool for managing translations, I will completely support this decision, because this task is very complex.

And +1 for button "Sync translations" in admin. Also it would be helpful "Sync packages" (because of registry items) and "Sync shops" (because of layout features)

**Comment by tdecaluwe** [comment]
@newsiberian Since the translations are currently stored as a nested tree, perhaps we could use similar approach to the new product/variant structure? :)

**Comment by newsiberian** [comment]
@tdecaluwe, hello, could you explain more widely your suggestion? Why, you think we should do so?

**Comment by tdecaluwe** [comment]
Now each language is a document in the db, I was just wondering if the collection wouldn't be easier to work with if we'd store each translation string as a separate document. For one thing, I know imports would be a lot easier.

**Comment by aaronjudd** [comment]
let me think more about this, I'm reworking the i18n to use i18next 2.0.  2.0 brings some interesting stuff, like reading direct from files, and caching,  sprintf and interpolation... 

but let me get the current stuff working and then we can look into it some more what we should improve. 

re:  the structure - we're using the same structure as the i18n library (and with the upgrade it's now a 1-to-1 direct use of the json from the collection with no map necessary.  It's the lib that drove the schema of this.

**Comment by newsiberian** [comment]
:+1:
