### ISSUE TITLE
add child loggers for packages

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#808]
move logging to a new package,  for cleanliness, and namespaces child loggers for reaction packages. See #772

**Comment by jshimko** [comment]
Progress on this has begun with #837 and I'll be building out the rest of it this week.

**Comment by aaronjudd** [comment]
@jshimko how much of this should we consider completed with module refactor?

**Comment by jshimko** [comment]
None of it.  :)  

Creating separate namespaced loggers for packages obviously doesn't need to happen anymore, but creating child loggers for things like methods and hooks would likely be useful.  It makes debugging a _lot_ easier when you know what method triggered the log and what arguments were passed to that method (and by whom).

Like this...

```js
  Meteor.methods({
    'someMethod'(options, someString) {

      const logger = Logger.child({
        meteor_method: 'someMethod',
        meteor_method_args: [options, something],
        userId: this.userId
      });

     logger.info('Something happened!');

     logger.error('Oh no!');
      ...
```
Then...
```js
const options = {
  some: "thing",
  goes: "here"
};

Meteor.call("someMethod", options, "something");
```
Which then outputs...
```sh
INFO Reaction: Something happened! (meteor_method=someMethod, userId=d2dsVh78f48d89)
  meteor_method_args: [
    {
      "some": "thing",
      "goes": "here"
    },
    "something"
  ]

ERROR Reaction: Oh no! (meteor_method=someMethod, userId=d2dsVh78f48d89)
  meteor_method_args: [
    {
      "some": "thing",
      "goes": "here"
    },
    "something"
  ]
```

**Comment by zenweasel** [comment]
If we create some sort of super class for Meteor methods that allows for the Microservice architecture, this seems like something we could do there.

**Comment by aaronjudd** [comment]
Closing without further motion, re-open with a PR ;-)
