### ISSUE TITLE
UI Edit Mode button is not pushed (grey), when it's on

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#812]
@mikemurray, In version 0.12 Dashboard, Accounts and Orders buttons in right side bar stays pushed (became grey), when I go to such pages. But Edit Mode button behave different - it stays always the same (white).

Also settings buttons in the bottom of sidebar should behave the same, as we discussed here https://github.com/reactioncommerce/reaction/pull/744#discussion_r51514930

**Comment by aaronjudd** [comment]
note, we discussed and agreed the color scheme is the teal active.. in case anyone thinks the bug is that its not gray anymore..
