### ISSUE TITLE
Right sidebar styles problems in Safari, Chrome

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#813]
There are 2 problems with styles of right sidebar in Safari:

* Translated title of dashboard doesn't fit to width of sidebar. For some reason space doesn't work as break line. (in safari, chrome)
* For "Add" and "Edit mode" buttons different html code is used. And as result icon is not in the centre of button. On the screenshot I did hovering specially to make it visible. Also if I click on the side of "Add" button, it doesn't work. (in safari)

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/0H1h3s223Y2e2l3z2m2E/Image%202016-02-23%20at%203.41.09%20PM.png?v=cc9db476)

**Comment by mikemurray** [comment]
Looking at your screenshot, and thinking about similar issues in other languages, it might be better to put the title for the buttons in a tooltip on hover. That way spacing will not be an issue. At the moment I think theres some CSS preventing spaces in the label from breaking in some of the buttons.

As for the other bugs, I'm on it in branch `murray-813`
