### ISSUE TITLE
i18n not all phrases translated while normal navigation

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#814]
When I go to product page using different language some parts stays in english. I can force to translate page completely by switching "Edit Mode" on and all phrases will be immediately translated. 

@aaronjudd I remember there was a bug, which you already solved https://github.com/reactioncommerce/reaction/issues/235 Possibly this issue is related

**Comment by aaronjudd** [comment]
I'm  working on the update to i18n lib, I'll take a look.

**Comment by aaronjudd** [comment]
I think these are all resolved now, except where there are missing translations. We'll be getting all the translation files and labels reviewed and updated prior to v.14
