### ISSUE TITLE
Send messages sent to "Logger.fatal" to email or other more visible means

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#818]
We want to notify sysadmin if we hit a `fatal` error so that they can get their site back up. Probably just need to create a new stream. Possibly pump this to a collection?

Would be great to have it go to console for development and then to email/monitoring in production.

**Comment by aaronjudd** [comment]
If we inserted the json from bunyan into a collection, we'd be able to have real time logging, and could add to some admin dashboard notifications..

**Comment by aaronjudd** [comment]
See #808 as well

**Comment by jshimko** [comment]
Yep, I was thinking a Mongo stream would be a great addition (with stdout and Loggly).  Realtime server logs on the client side would be pretty slick.  

Also, see how I conditionally add the Loggly stream in production on Launchdock...

https://github.com/reactioncommerce/launchdock/blob/development/packages/launchdock-lib/lib/server/logger.js#L26-L36

(which uses this NPM lib: https://www.npmjs.com/package/bunyan-loggly)

Adding an additional stream destination would look exactly like that.  I was considering doing Mongo too back when I wrote that, but didn't have an immediate need.  I'll definitely add that to my todo list for #808.  

There are a few packages that use other Node drivers for Mongo...

https://www.npmjs.com/package/bunyan-mongo
https://www.npmjs.com/package/bunyan-mongodb-stream

We'll obviously have to use Meteor's Mongo client implementation, but you can look at the source of those packages above and see that it'll be a fairly simple process.

On a related note, Slack integration for errors would be awesome too...
https://github.com/qualitybath/bunyan-slack

**Comment by aaronjudd** [comment]
Closing - insufficient details.  Other logging / notifications approaches (non meteor) are in review.

**Comment by zenweasel** [comment]
Comment from Taxjar ticket:

@zenweasel @spencern : I'd suggest for any such API Login / Key credential errors for such 3rd party connectors:

Show a notification on the admin tool when an admin user logs in

And / or trigger an email to the admin (which can be toggled on/off). This would be preferred by retailers that are not logging in to the admin tool regularly.

 @spencern
 Member
spencern commented 6 hours ago
@zenweasel @vwadher the client application is used by admins as well. I don't think we should be notifying customers of an error, but we should do as @vwadher suggests and notify admins in some way, and I like the idea of triggering an email as well.

This does get into the idea of triggering events for things like this where we could then from the event trigger a client application notification as well as an email notification.

 @vwadher
 Member
vwadher commented 6 hours ago
@spencern @zenweasel how about we create a configurable service for the admin to setup for all such 3rd party connectors. For example they can create unlimited notifications via something like this:

Notify [User / Group] via [Admin Tool Notification / Email] when [Connector Name] triggers [WARN / ERROR / SUCCESS] logs upto [X] times per [Day / Week / Month]

We create this and it gives the admins flexibility to auto parse logs and trigger such notifications.

**Comment by zenweasel** [comment]
@vwadher For a first pass of an implementation of this ticket can we just say that we are sending an email to the admin for anything that does a `Logger.fatal`? We could probably also write to some sort of system log if that existed. I know there are lot of different of how to implement that so for now just sending to email to the shop admin may give us a lot of what we need.

Writing some sort of system-wide logger with retention is probably something that would require some architecture input.

**Comment by vwadher** [comment]
@zenweasel That should be fine as a starting point.  But ideally they should be able to toggle on/off these email alerts. And perhaps give them an option to use a different email address for these alerts. It could end up flooding their primary email.  I do think the longer term solution is a system loggers and a more robust workflow for admins to select what alerts they want via what method and in what time intervals.

**Comment by prinzdezibel** [comment]
Current state: I wanted to move this functionality in our new  @reactioncommerce/logger NPM package, but couldn't finish it yet. If I find time, I'll finish that up on the weekend.

**Comment by spencern** [comment]
@zenweasel We merged https://github.com/reactioncommerce/reaction/pull/4110 in v1.11.0 - how does that affect the work being done here or the requirements?

**Comment by prinzdezibel** [comment]
@spencern  The corresponding PR addresses the new NPM package already: https://github.com/reactioncommerce/reaction/pull/4179

**Comment by spencern** [comment]
@zenweasel based on @prinzdezibel's comments, should we close this issue?

**Comment by zenweasel** [comment]
@spencern No. His PR noted above has errors and since he's no longer here I've been trying to fix them myself but with no luck yet.

**Comment by zenweasel** [comment]
@vwadher I spoke with @ticean today and he explained to me that this is probably not the correct approach re: adding more functionality to the Logger. Probably what would be better is have some sort of log facility (Logentries, Papertrail, etc) and then use that service to surface alerts to email or whatever the client prefers. Probably an audit of logging entries would be good as well. Also, some sort of documentation covering how one can use something Logentries to set up that alerting would be appropriate but this is something that anyone deploying a site would normally do.

Closing this ticket as there is nothing more actionable

**Comment by ticean** [comment]
I closed the original PR with the comment below. This can be handled outside app scope with a log aggregator. It's a solved problem as the aggregators can all send alerts. We can add guidance to the docs.

> Log driven alerts can be easily handled outside of the application scope, so I'd prefer that we don't merge any more custom functionality into the logging system. PR's to improve the data that's logged, add timing, additional context, etc. will be 💖.

> There are many cloud based log aggregation services out there that can send an alert based on the content of a log message. Most have free tiers for light usage. [Logentries](https://logentries.com/product/alerting-and-reporting/) has some of the best alerting capabilities in the space. [Loggly](https://www.loggly.com/docs/adding-alerts/), [Papertrail](https://help.papertrailapp.com/kb/how-it-works/alerts/), [AWS CloudWatch](https://aws.amazon.com/cloudwatch/details/) and others are capable as well.

> And while it's generally better practice to aggregate logs to a centralized location, you could also handle this directly on the server with a process manager or some other log analyzer.
