### ISSUE TITLE
Address Book Display in Cart Checkout- unusual Behavior

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#827]
Adding the address is working fine.  I could see in Database.  When Created a new order I am asked to create address again though there is one address already available. 
 **Now the fun begins while debug**
After I put 2 console.log statement in add.js and addressbook.js oncreated() method, it starts working fine and shown the grid with addresses.  Not sure if it is due to Flow Router change or something else?? .  Will continue to debug and see if I found something will send a PR.

**Comment by zenweasel** [comment]
@hrath2015 Can you provide us with the steps to reproduce?

**Comment by aaronjudd** [comment]
is this with a logged in user or a guest?

**Comment by hrath2015** [comment]
Logged in user(Admin).

**Comment by hrath2015** [comment]
It is happening again while I am testing PR#741.  on step 2 , Instead of showing Address Grid after click of Save and Continue button, add Address screen is shown.  Could this be similar to to below conversation.
![image](https://cloud.githubusercontent.com/assets/14071646/13355447/7c0cc64e-dcc6-11e5-9ee0-13b493dea222.png)

**Comment by hrath2015** [comment]
One time It showed me the Below screen.  Very Unpredictable.  Thus far It was  showing some times Add screen or Address Grid,(not reproducible consistently though).  But this one is showing only Headline div. Rest of the part is gone. Also note I was able to place the order.
![image](https://cloud.githubusercontent.com/assets/14071646/13386346/772599b4-ded1-11e5-91d7-bc12ad9e239d.png)

**Comment by zenweasel** [comment]
I have seen some weird behavior like this in the past but it has cleared up in the last couple of releases. I've been trying for a while and cannot reproduce. Any clue you could give me about anything unique to your installation?

**Comment by zenweasel** [comment]
Could not duplicate this problem. If you are still experiencing this, please provide detailed steps to replicate and reopen. Thanks.
