### ISSUE TITLE
Docker build on master fails

### ISSUE THREAD

**Issue by rhalff** [reactioncommerce/reaction#828]
When I try to build the Dockerfile from the master branch I get the following error:
```
*****************************************************************
=> Errors while initializing project:

While selecting package versions:
error: unknown package: reactioncommerce:reaction-router
Required by: reactioncommerce:reaction-paypal 1.3.0
```

**Comment by aaronjudd** [comment]
I think we're updating to newer packages, and those are incompatible with 0.11 (master). 
@jshimko I think this is a case where `reaction pull` is an issue - we really should only be pulling when building in development.

**Comment by aaronjudd** [comment]
@jshimko I'm also getting this error following our Docker build instructions:

```
reaction/ (development✗) $ docker run -p :8080 -it reaction                
Starting local MongoDB...
about to fork child process, waiting until server is ready for connections.
forked process: 8
child process started successfully, parent exiting
/usr/bin/entrypoint.sh: line 30: /var/www/src/reaction: No such file or directory
```

**Comment by aaronjudd** [comment]
Also see potentially related Mongo issue in #865

**Comment by aaronjudd** [comment]
@jshimko https://github.com/reactioncommerce/reaction/commit/0dc0d2972f4c5f1f38c4111b6cef745fec57f28b  looking really good, want to close this?

**Comment by jshimko** [comment]
Once we merge to master, yeah, this should be all set.

**Comment by jshimko** [comment]
This should be all set.  Reopen if you run into the issue again.
