### ISSUE TITLE
i18n or flexbox issue with Safari/ FF in admin

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#842]
![screenshot_3_1_16__11_56_am](https://cloud.githubusercontent.com/assets/439959/13439995/db58dff8-dfa4-11e5-889c-77c7aecd4a1e.png)

**Comment by mikemurray** [comment]
Think it might be an i18n label issue. Manually entering the text, in web inspector, makes it show up properly.

![screen shot 2016-03-02 at 10 18 02 am](https://cloud.githubusercontent.com/assets/42217/13470266/39ff3bf4-e060-11e5-8090-d5c41b14c062.png)

**Comment by mikemurray** [comment]
And to add to this, the tooltips for the toolbar don't show up, nor do button labels that use 118m keys.
