### ISSUE TITLE
Remove from Cart not Working

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#853]
Remove any item added to Cart.  Server Console prints success messages.  Mongo cart doc still not deleted. In cart drawer it continues to show.

**Comment by newsiberian** [comment]
I've debug this and this is our nightmare. It is repeats the behavior of "should remove item from cart" broken test. It fires `cart.update` and return `result: 1` but item is still there.

**Comment by newsiberian** [comment]
I discover the reason. It is in fact that we can't make `$pull` and `$set` operation at once. But this happens with the help of `shopIdAutoValue` method. It was fixed few months ago, but now I see the old version again.

**Comment by hrath2015** [comment]
It is further complicated as all messages are shown to be success.  Is it because of  Minimongo or local cache . Prior to V11  removeFromCart method was in common and available on both client and server.

**Comment by newsiberian** [comment]
hm... you're asking why all messages comes with "success"? If so - this is because they really all was successful, but without real effect on database))

**Comment by hrath2015** [comment]
Thanks a lot. Working fine.

**Comment by zenweasel** [comment]
@hrath2015 @newsiberian So is this still broken?

**Comment by hrath2015** [comment]
@zenweasel  on Dev branch yes it broken.  However @newsiberian  already submitted  PR #856. Please merge to fix on Development branch.

**Comment by hrath2015** [comment]
Closed with PR#856
