### ISSUE TITLE
Issues with reaction install

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#861]
If I clone reaction and then do `reaction install` (like the instruction in the reaction README say to do) it installs reaction the "master" version to a completely different location and then runs that, not the one I just cloned, causing user confusion (especially with an 11/12 disparity).

I think we need to talk about a better way to bootstrap installs.

**Comment by aaronjudd** [comment]
for anyone stumbling on this issue, we've updated all the docs to show a manual installation. The install script is used for some of our tools, but has been an unreliable experience for users.


See: https://github.com/reactioncommerce/reaction-docs/pull/14

To install and run Reaction locally:

```bash
curl https://install.meteor.com | /bin/sh
git clone https://github.com/reactioncommerce/reaction.git
cd reaction
reaction pull
reaction
```

**Comment by zenweasel** [comment]
References to `reaction install` are now removed from the repo and the docs.
