### ISSUE TITLE
[PDP] Product title issue / 17 Character Regex Matching

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#869]
Hello, I think product `title` should be client side validated by two rules:
- not allow `title` without text;
- not allow `title` with 17 chars (number of chars in `_id` as I remember) to prevent error with finding product by `handle`.

**Comment by aaronjudd** [comment]
Partially resolved in #1127, @mikemurray will add additional logic so that if a 17 character ID isn't found, we'll do an additional search for a 17 character name.

**Comment by mikemurray** [comment]
A few things seem to be happening here.

1. The publication needs to be updated to better handle the checks for handle as a `slug`, as an `id`, and as a 17 character string that looks like an `id`.
2. `/lib/api/products`  `Reaction.setProduct` needs a more robust check as well.
3. The product handle is being reset for product `BCTMZ6HTxFSppJESk` every time meteor restarts. This seems to only apply to the default product, so maybe its happening on import.

**Comment by aaronjudd** [comment]
Resolved in #1659
