### ISSUE TITLE
Product Image Keeps Changing on Firefox

### ISSUE THREAD

**Issue by blacktea3937** [reactioncommerce/reaction#871]
Hi All,

Not sure whether this issue was mentioned before. On Firefox, found the below issue when onmouseover the product image. Images keep changing. 

![issue1](https://cloud.githubusercontent.com/assets/16403260/13560782/be1f262c-e45e-11e5-973b-b1b589f51fdb.gif)

**Comment by aaronjudd** [comment]
I'm honestly not sure if this isn't the expected behaviour. @mikemurray ?

**Comment by mikemurray** [comment]
This should be resolved. Please reopen if you're still having issues.
