### ISSUE TITLE
[Marketplace] Merge P2P marketplace extensions into RC repo

### ISSUE THREAD

**Issue by ScyDev** [reactioncommerce/reaction#883]
I've extended RC to allow users to be sellers on this fork:
https://github.com/ScyDev/reaction

Core:
- Separate docker file for development which allows to run a docker container using Reaction Commerce source instead of bundle
- Users can choose to be sellers during registration (new field isSeller on user account schema).
- Sellers can create products (products schema has new userId field).
- Sellers can de/activate their products.
- Changes to server/methods/products.js to allow sellers actions on their own products.

Packages:
- reaction-p2p-marketplace
  -- inject view switcher for grid, list, map view.
- reaction-p2p-marketplace-locations
  -- inject map overview with all products
  -- inject map on product detail displaying only its location
  -- resolve product location from seller profile address
- reaction-p2p-marketplace-ratings
  -- currently: just displaying 5 star rating on product
  -- planned: save rating on products, sellers and buyers
- reaction-p2p-marketplace-sell-date
  -- "for sale on date" field for products that are only sold on a specific day
  -- injecting date field into product detail with calendar date picker
  -- planned: filter products by date
- reaction-p2p-marketplace-seller
  -- show list of sellers products
  -- show list of sellers orders
  -- planned: public profile for seller, with avatar images
- reaction-p2p-marketplace-simplified-products
  -- hide variants on products detail
  -- checkout without shipping (auto-select free shipping and hide the options)
  -- allos seller to choose from tags, but not create new ones

Dependencies:
- should all be configured in the packages.js files

**Comment by zenweasel** [comment]
@ScyDev Hey Lukas, if you want to have something merged into core, you would want to open a PR not an issue. But without looking at this more, is there a reason these couldn't be standalone add-on packages? I think some of this stuff has broad appeal (ratings, etc), but some of it seems like it might be more specific to certain implementations.

Maybe we can discuss what's the best way to move this info core.

**Comment by ramusus** [comment]
@ScyDev nice work! I'm also thinking about implementing marketplace for one of my project. And I completely agree with @zenweasel, many features could be packaged as independent packages. And used for many other reaction-based systems.

For example: 
* product locations
* view switchers for grid, list, map view.
* ratings
* simplified variant less products

All this features could be independent from each other and used anybody, who wants this functionality.

**Comment by ScyDev** [comment]
@zenweasel Aaron said I should create an issue first. I asked him if he thought these changes could be merged into core and he said yes. 

As you can see, most things I already implemented in separate, optional packages.

But for allowing users to be sellers, I had to check product ownership in most of the methods in `server/methods/products.js`.
Do you think this could be done in a separate package?

**Comment by ScyDev** [comment]
I'm working on putting all the changes I made in core to separate packages. I think it's possible to do it after all. When I started this I didn't know enough to prevent core hacks.

**Comment by ramusus** [comment]
@ScyDev If I'm not mistaken the original idea was attach every product to the shop. And give some users rights to create they own shops in the marketplace. So you can get owner of shop and he is will be owner of all products in his shop. But your implementation also could work, we just need to make clarification of marketplace design. @aaronjudd do you have some schemas or thoughts, how it should be implemented ?

**Comment by ramusus** [comment]
Here are few related issues https://github.com/reactioncommerce/reaction/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Amarketplace+

**Comment by spencern** [comment]
I'm closing this issue for now. Feel free to open it back up if there is movement towards creating a PR out of any of these packages. These packages would need to be migrated from the old Meteor Package style to the new Reaction `imports` style of package.

We've got a newer `marketplace` branch that is under active development right now.
Check on progress on the [marketplace project board](https://github.com/reactioncommerce/reaction/projects/9)
Chat with us regarding Marketplace in our [marketplace gitter channel](https://gitter.im/reactioncommerce/marketplace)
