### ISSUE TITLE
UI Edit mode for everything, not only for top tags

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#885]
Edit mode works for top tags very well, and I think it could works for product page as well. Also It will give ability for administrators to see the site as regular guest do. 

@aaronjudd @mikemurray, what do you think?

**Comment by aaronjudd** [comment]
We're working towards exactly that..  moving the tags, variants, and other editable "properties" into the sidebar, while still using inline edit for the fields.

**Comment by ramusus** [comment]
That's great! :+1:

**Comment by mikemurray** [comment]
After living with it for a while, we believe that having inline edit buttons for editable components that open in the admin sidebar for administration is probably for the best. This way you can view the item you are modifying as a normal user while you update it as an administrator.

The new product detail page is a good example of this:

![screen shot 2016-07-13 at 11 51 56 am](https://cloud.githubusercontent.com/assets/42217/16815926/c5148048-48f0-11e6-9a76-197eae01f9e1.png)

**Comment by mikemurray** [comment]
Adding a global edit toggle fits well with moving the publish bar for the new PDP page to the top.
https://github.com/reactioncommerce/reaction/issues/1624

Then the `preview` switch could apply to the whole app and resolve this ticket.
