### ISSUE TITLE
UI strange behaviour of hovering eye icon on ProductGrid

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#886]
In current development branch I started to see strange behaviour in Safari

![eye](https://s3.amazonaws.com/f.cl.ly/items/2X1Y300p1D371K1L3m1R/Screen%20Recording%202016-03-09%20at%2001.49%20PM.gif?v=e305b507)

**Comment by zenweasel** [comment]
I think this is a duplicate of https://github.com/reactioncommerce/reaction/issues/860 ?

**Comment by ramusus** [comment]
yep, closing
