### ISSUE TITLE
UI popup alert for changing visibility of products on ProductGrid is always the same

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#887]
UI popup alert for changing visibility of products on ProductGrid is always the same. When you make the product or products visible on invisible it always green and "is now visible"

**Comment by ramusus** [comment]
I think it's time to implement tests for such UI behaviour. Because it's broke quite often in recent time and it takes time to get all those bugs known for developers.

**Comment by aaronjudd** [comment]
@ramusus re: tests --> yes, agreed @zenweasel is taking the lead on that, but we're all waiting for some clarity in the Meteor testing for 1.3...
