### ISSUE TITLE
UI strange visible defect in dashboard CoreThemes page

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#888]
tested in Safari
![](https://s3.amazonaws.com/f.cl.ly/items/2N1G0b24081O2g0L3T1E/Image%202016-03-09%20at%204.54.07%20PM.png?v=ae1d6550)

In chrome everything ok, but there doesn't work back button from inner page http://localhost:3000/reaction/dashboard/ui/etWv4KmZ3AYv2Qr2F (content remains the same, but URL changes)

**Comment by aaronjudd** [comment]
back history should be resolve now in v0.12.. can you reproduce / close?

**Comment by aaronjudd** [comment]
I can verify the UI error exists in safari though. @mikemurray

**Comment by aaronjudd** [comment]
![reaction-ui_uidashboard](https://cloud.githubusercontent.com/assets/439959/16471119/95783834-3e0f-11e6-8f7f-7047fc75a768.png)


More strange ui defects...
