### ISSUE TITLE
UI Edit Product panel doesn't close, when I go from product grid to product page

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#891]
How to reproduce:
1. go to product grid,
2. click to gear icon - Edit Product panel appears
3. go to product page - Edit Product still visible, but useless here

**Comment by aaronjudd** [comment]
The control panel should still be functional, and should work.  We're moving PDP(product detail page) settings into this panel so it should be contextual to the current selected PDP.

**Comment by aaronjudd** [comment]
(aware, of this, but making other UI updates soon that will make this all flow)
