### ISSUE TITLE
UI Clone product from product page

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#892]
We have block called "Product management" now with functions:
* Change product visibility
* Delete product

What to you think about adding "Clone Product" functionality there?
And also I think it would be nice to use this unified icons for management products anywhere on the site.

![](https://s3.amazonaws.com/f.cl.ly/items/2B3f2R2S1v2e0Y011E3k/Image%202016-03-09%20at%208.31.50%20PM.png?v=155d8575)

**Comment by aaronjudd** [comment]
We're going to be moving all the product settings into the "Edit Product" sidebar soon, the control panel is just the start..
