### ISSUE TITLE
2 Icons for same function in Accounts Dashboard

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#893]
Not sure if this is on purpose. Looks like mix up with react components and old template.
![image](https://cloud.githubusercontent.com/assets/14071646/13648486/de9b905a-e65e-11e5-8bfa-7261bae89352.png)

**Comment by aaronjudd** [comment]
:+1:  Yup, we need to remove the "Add Member" @mikemurray is aware of it.  A leftover from 11....
