### ISSUE TITLE
Create "Community Code of Conduct"

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#894]
Better to get this in now (IMHO) while there are just a few of us.  Inspired by a few of the ugly conflicts I have seen on some open-source projects. And also this article:
https://medium.com/@shanselman/bring-kindness-back-to-open-source-90ed7d3ac76b#.1s921fov1

I think a good one that I have seen in use is: https://www.djangoproject.com/conduct/

**Comment by aaronjudd** [comment]
Of interest: http://blog.discourse.org/2013/03/the-universal-rules-of-civilized-discourse/

**Comment by spencern** [comment]
:+1: on getting this done early
