### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by emaddoma** [reactioncommerce/reaction#907]
How does one change their own password and email?  How about forgot passwords?

**Comment by mikemurray** [comment]
You can change your own password from the "Profile" section in the user dropdown.
Forgotten passwords are reset from the sign in dropdown (not logged in) "reset password" link.

You cannot change your email at the moment, but its on the roadmap: https://github.com/reactioncommerce/reaction/issues/739

**Comment by emaddoma** [comment]
Thanks!
