### ISSUE TITLE
Default product can not be removed

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#921]
For bugs, please fill out the three following sections completely

### Expected behavior
after been removed, this product shouldn't appears again after server restart/update
### Actual Behavior
it is appears again or if it was modified, it resets to default state after server update/restart
### Steps to Reproduce the Behavior
1. remove default product
2. restart server

**Comment by tdecaluwe** [comment]
Did you remove the sample data package?

**Comment by newsiberian** [comment]
Hello, No) Without this package all works correctly.
