### ISSUE TITLE
Convert existing tests to run under Meteor test runner

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#923]
Obviously a child/related-to https://github.com/reactioncommerce/reaction/issues/848

**Comment by aaronjudd** [comment]
we could start with the broken client tests.. - I'm assuming we're thinking those go to chimp tests?

**Comment by zenweasel** [comment]
We don't want to start with the tests that we know work?

re: Moving to Chimp
Some will, but some should probably go in the "full app" test mode I think.

**Comment by spencern** [comment]
Is the plan to switch to Mocha for native testing, or is there anticipated support for Jasmine?

**Comment by aaronjudd** [comment]
There is anticipated support for Jasmine, but not sure we want to wait, and Mocha is pretty darn close (switched from Mocha to Jasmine a while ago, so I don't think it will be that hard to switch back to Mocha).  I'd rather be using the most common & supported.   However, we're still testing the waters right now.. any preferences?

**Comment by zenweasel** [comment]
Since Chimp currently only supports Mocha I am thinking probably it makes sense to switch. But when I sit down to rewrite 150+ tests I may have a change of heart.

**Comment by spencern** [comment]
I don't have a strong attachment to either, our tests are also currently written in Jasmine as well, and if Mocha has better Meteor support or if Jasmine takes too long to get ready then I'd be for a switch.

**Comment by zenweasel** [comment]
My last comment I promise:

I much prefer Mocha because of:
1. Better coverage support (AFAIK Jasmine has none)
2. Support for both TDD and BDD assert styles (via Chai, but also the plugability of using different assert libraries)
3. Better docs (I despise the Jasmine docs because there is no real detailed API doc)
4. More responsive devs for support/issues
5. Better console reporting and plugins for JUnit-style output for CI
6. Plugins provide superior mocking/stubbing via things like Sinon
7. Plugins for things like Growl notifications for test results.
8. Dumb plugins for things like cowsay, which don't make me a better developer but do make me a little happier.

**Comment by zenweasel** [comment]
Actually this title is now inaccurate. The point of this was to eliminate Velocity, not Jasmine and use the native Meteor tests. That could be Jasmine if support is forthcoming. It also requires more than just rewriting but restructuring the tests to fit the test/app-test/chimp model.

**Comment by aaronjudd** [comment]
Well I was confused, then if you are not converting all the tests, but only select `app/tests` client tests to use with chimp, (I assume this was "native").   The title implied to me a larger project to convert all existing velocity tests.  feel free to rename.

**Comment by zenweasel** [comment]
Sorry I must not be using the right terms. No, Chimp is not what I am calling native. The native test runner runs `test` and `app.test` files which most of the existing tests could probably converted to run as one of those two types of tests. Currently they need to be converted to Mocha to do that (but that could change at any second). I am mostly focusing on the existing 150+ server tests that currently run. This is what would allow us to no longer use Velocity.

Chimp is really for doing "blackbox" acceptance testing which is important but something I am still mostly working on on my own. So it's not a part of this ticket.

**Comment by zenweasel** [comment]
So based on the progress of the Jasmine test modules and the support that the Meteor team is putting behind Mocha it looks like we are going to switch to Mocha so that we can get CI support in the near term and better testing support in the long term. So I will be rewriting all these tests. :(

**Comment by zenweasel** [comment]
Xolvio has officially dropped support for Jasmine but you can use the `expect` and `spyOn` libraries, so that should make the conversation just a matter of renaming/moving files and change `beforeAll/afterAll` to `before/after`. (I believe)

**Comment by zenweasel** [comment]
Completed
