### ISSUE TITLE
Failed to get currency exchange rates error

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#924]
### Expected behavior
When I have a valid Open Exchange Rates API key Reaction should fetch exchange rates between my base currency and all other currencies

### Actual Behavior
Receive "Failed to get currency exchange rates." in console. Prices never show in Locale currency.

### Steps to Reproduce the Behavior

1. Start a Reaction session where you locale currency is not USD. (if in the US, a VPN is the easiest) 
2. Receive error message at console
3. Observe prices are shown in USD even though that's not your local currency.

**Comment by newsiberian** [comment]
Hello, did you read [this](https://docs.openexchangerates.org/docs/changing-base-currency)?
> Changing Base Currency is currently available for clients on the Developer, Enterprise and Unlimited plans.

**Comment by zenweasel** [comment]
Yes, but it's not relevant as I am not trying to change my base currency.

**Comment by newsiberian** [comment]
exchange rate base currency and reaction base currency is a different terms. ER base currency is USD. If you're using non-USD currency in your shop, this mean you need to change ER base currency to yours shop base currency, but system could do this only if you have at least "developer" plan. Am I wrong with that?

**Comment by zenweasel** [comment]
That is not my issue. The issue I am reporting is getting the standard exchange rates from USD -> All Other Currencies which is included in the free plan. My base currency is USD. I am talking about the **locale** currency (the currency displayed on the client side based on the user's locale). That's why the steps to reproduce don't mention anything about changing the base currency from the stock USD.

This works for other people. For some reason it does not work for me (and has not for quite a while)

**Comment by newsiberian** [comment]
Oh, I'm sorry for that. I misunderstood this issue

**Comment by nialexsan** [comment]
packages/reaction-core/server/methods/shop.js:149 tries to get currency rate from the ReactionCore.Collections.Shops, but there is not field 'rate'

**Comment by zenweasel** [comment]
@nialexsan In order for the field to be populated you need to fill in the OpenExchangeRate API key field. It needs this in order to populate that field. Do you have that filled?

**Comment by nialexsan** [comment]
Yes, I had set this API key, but still this field hadn't been populated. 
Do I need to run something to update rates from the service?

**Comment by zenweasel** [comment]
The job for fetching was not being added to the queue. Now both the "fetchRates" and "flushRates" jobs should be running if you have the OpenExchangeRates API key in your settings.
