### ISSUE TITLE
UI Editing tags on product page, when no tags - no title

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#954]
### Expected behavior

For admin there is should be Tags title

### Actual Behaviour

For admin there is no Tags title if no tags are selected

![](https://s3.amazonaws.com/f.cl.ly/items/3r3k1X002c0M1O1N3P1z/Image%202016-04-05%20at%2011.06.01%20PM.png?v=a1640505)

**Comment by aaronjudd** [comment]
@mikemurray resolved in 0.14?

**Comment by mikemurray** [comment]
Yes
