### ISSUE TITLE
Changing shop name breaks urls

### ISSUE THREAD

**Issue by CameronSima** [reactioncommerce/reaction#955]
For bugs, please fill out the three following sections completely

### Expected behavior
Changing shop name in admin section should change urls in a manner that does not break urls.

### Actual Behavior
When changing the site name in the admin panel to a name containing spaces, urls do not work.

The workaround I've been using is to change the name of the shop in the admin UI to a url friendly one("my_shop_name") and then manually enter the correct display name ("My Shop Name") in the brand.html file.

**Comment by aaronjudd** [comment]
@CameronSima thanks for this report. We probably need to add a "slugged" version of the shop name for the url handling.  ie: getSlug(shop.name).

**Comment by zenweasel** [comment]
I was able to reproduce this. Changing the shop name to "Brent's House of Things" makes all the links not work. Changing it to "brents-house-of-things" makes it work again. Also changing the title to contain a unicode character like "ཨ" seems to break everything as well.

**Comment by albertpak** [comment]
Ran into this issue last night - is there a timeline on when the fix will be provided?
