### ISSUE TITLE
Tests fails with `Error: HTTP.methods not implemented on client-side`

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#956]
### Expected behavior
Testing should not have errors for HTTP.methods as it's included

### Actual Behavior

```
W20160406-13:45:03.825(-7)? (STDERR) Error: HTTP.methods not implemented on client-side
W20160406-13:45:03.826(-7)? (STDERR)     at Object.HTTP.methods (/private/var/folders/z5/lhsfpjqs47qc5lbybyzqj6p80000gn/T/meteor-test-run1uryfoz/.meteor/local/build/programs/server/packages/cfs_http-methods.js:688:9)
```
### Steps to Reproduce the Behavior

Works with cfs:http-methods@0.0.30 but release 0.0.31 introduces this issue. 

@spencern reported as https://github.com/CollectionFS/Meteor-http-methods/issues/52

**Comment by spencern** [comment]
A workaround if you need testing immediately is to clone `cfs:http-methods@0.0.30` into your apps packages directory.

**Comment by zenweasel** [comment]
Verified fixed by fix in https://github.com/CollectionFS/Meteor-http-methods/issues/52
All tests pass again.
