### ISSUE TITLE
Completing order does not succeed with real PayPal

### ISSUE THREAD

**Issue by sphvn** [reactioncommerce/reaction#96]
Testing without using the sandbox for PayPal, the `confirm order` returns an error,

`Exception in delivering result of invoking 'paypalSubmit': TypeError: Cannot read property 'length' of undefined`

Though this could be due to PayPal Australia from the PayPal developer REST API eligibility:
```text
Note: Direct credit card processing is not available for you when using REST APIs.
Your live credentials are inoperable for direct credit card processing for your country
but your test credentials are enabled for sandbox testing.
```

**Comment by aaronjudd** [comment]
I'm closing this now, as we have paypal express which adds a lot of countries, and beyond that it's up to paypal support for a specific country.
