### ISSUE TITLE
shopID is not available for `createDefaultAdmin` when running RC in separate containers

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#960]
This bug is currently blocking running the most recent version of RC in LaunchDock so it's probably a P1 bug. I am putting this here just so we have a place to track it.

### Expected behavior
Since import methods are run before `createDefaultAdmin`, the function `getShopId` should return a shopId.

### Actual Behavior
In some configurations of Docker (any configuration where you have separate app and db containers on separate machine, and on my local machine as well) either the shopId is not available for several seconds, or in the case of separate containers, not available at all.

### Steps to Reproduce the Behavior
If you remove the current workaround, I am able to replicate this locally by running `docker-compose` against my local version of the app. The problem in LD however would seem to be either different or more serious since `shopId` never becomes available.

**Comment by zenweasel** [comment]
At @aaronjudd's suggestion I initially tried putting the call to `createDefaultAdmin` in a callback from flush, but this didn't seem to do anything. So I put in a sleep https://github.com/reactioncommerce/reaction/pull/952 which solves it locally (but interestingly it takes 7-8 seconds for shopId to appear) However this doesn't seem to fix the issue when running app and db on separate machines such as our LD configuration.

Probably the first step would be to determine where the bug was introduced and try to see what the change was. One theory I had is that it was waiting for Mongo to create indexes from data that is inserted during import, but that would not explain why shopId is never returning in a 2 container config.

**Comment by zenweasel** [comment]
I'd love to work on this but I don't currently have a way to duplicate the error that is occurring (that I know of)

**Comment by aaronjudd** [comment]
@jshimko we should review for v0.14.0

**Comment by aaronjudd** [comment]
if this is a blocker for docker and launchdock, and I’d call keeping our deployment stuff working a must have….  if it’s not really a blocker of that ( @jshimko ? ).. then I’d say this isn't critical and doesn't need to be reviewed for 0.14, we should add to the 0.15 milestone though.

The main reason I think we should look at this for 0.14 is that  I suspect this is also not likely valid anymore, or at least debuggable now because of the module loading, and we should test to know one way or another for changed behaviour here.

**Comment by mikemurray** [comment]
This is also causing an issue with translations. The `Arabic` language gets imported with a `null` shopId, making it un-selectable as a desired language.

**Comment by zenweasel** [comment]
Closed by 1145
