### ISSUE TITLE
In fresh clone, Braintree is enabled by default

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#970]
### Expected behavior
By default only the "Example Payment Provider" should be enabled

### Actual Behavior
Example and Braintree are enabled, but of course Braintree doesn't work because it's not configured (which it should not display without an API key present anyway)

### Steps to Reproduce the Behavior
Run a fresh clone

I would just fix this but it wasn't immediately obvious where this value is getting stored, so this is just a reminder.

**Comment by zenweasel** [comment]
I'm going to comment in this issue because nobody cares about it

**Comment by zenweasel** [comment]
Again commenting here because no one is probably subscribed to this issue.

**Comment by aaronjudd** [comment]
Test comment.

**Comment by zenweasel** [comment]
Just did a fresh clone and this is still happening. Reopening.

**Comment by aaronjudd** [comment]
@zenweasel might as well resolve while "modularizing the package"
