### ISSUE TITLE
Tax Implementation

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#972]
Provide a basic flat rate tax implementation package (reaction-taxes) and a provider package (reaction-taxcloud)

Basic steps are likely something like:
- [x] Implement Taxes collection, update schemas as needed. 
- [x] Add hook after shipping, prior to cart review return and save tax rates to the cart
- [x]  Ensure taxes added to cart totals / charges
- [x] Display Tax in review and order dashboards.
- [x] Create as reaction-taxes package
- [x] Create generic method (similiar to payments, shippings) in core for calling specific tax packages
- [x] Add one specific tax vendor (suggest we start with TaxCloud) (additional package?)
- [x]  UI and Settings configurations for Tax API for initial provider
- [ ]  implement tax refund / return order handling
- [ ] Auth / Trans payment hooks for tax auto-filing requirements

# Tax 
We should accommodate these initial taxation types:

 *  Manual / Flat Tax
    * match address fields (ie: state, city, country)
 *  US Nexus Sales Tax
    * implement as taxcloud 
       * requires taxcloud and usps id

In a future release we could add providers:
* VAT / GST (Value Added Tax)
    * implement as avatax 
* Marketplace taxes
   * implement TaxJar marketplace api

## Options

* Include Shipping in tax total (can vary by origination locale)
* Tax by Destination
* Tax by Origination
* Product options
  *  `Tax Included` at product
  *  `Tax Exempt ` at product
  *  `Taxable Goods` product tax category array

## Providers

These seem to be the most common API providers in the US market right now:

* [TaxCloud](https://dev.taxcloud.com/)  (free rates, automated filings)
* [TaxJar] (http://www.taxjar.com/)
* [Avalara](https://www.avalara.com/) (US and EU Vat))
* [Taxify](http://taxify.co/) (automated filings)

Some random notes:

- If you are VAT registered, then the prices displayed on the website should be VAT inclusive.
- Discounts / coupons should be applied before tax calculations.  Perhaps an option?

**Comment by owenhoskins** [comment]
Here's a overview of my needs for a VAT Registered client in the UK. Granted this might all change with the BREXIT vote today...

1. Where a client/business is in the UK – Charge 20% VAT
2. Where a client/business is outside the scope of VAT (Client/business outside UK and EU)– NO VAT
3. Where a client/business is based in the EU and NOT REGISTRED for local VAT in their country – Charge 20% VAT
4. Where a client/business is based in the EU and REGISTRED for local VAT in their country – Charge Zero rate VAT BUT you must have your customers VAT number in the local country before you Zero rate the invoice.
