### ISSUE TITLE
Name does display properly after registering a user

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#973]
### Expected behavior
After registering an account, should see the "Guest" name in the header

### Actual Behavior
Immediately after registering the name is displayed, but if you refresh the name becomes `undefined` at line 80 in `reaction/packages/reaction-accounts/client/helpers/helpers.js`. Also if you go in and add an address, etc. the name still shows up as `undefined`.
<img width="950" alt="reaction" src="https://cloud.githubusercontent.com/assets/72819/14578757/c58de860-03c3-11e6-87bc-949c46b85064.png">

### Steps to Reproduce the Behavior
1. Register an account
2. Refresh the page
3. Observe the name field is empty.

**Comment by nialexsan** [comment]
It seems like i18next causes this trouble:
packages/reaction-accounts/client/helpers/helpers.js:80
i18next.t is called but inside there this.translator is undefined

**Comment by zenweasel** [comment]
Fixed in https://github.com/reactioncommerce/reaction/pull/1109
