### ISSUE TITLE
Blank screen and console errors on fresh install

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#974]
Numerous people have reported this in Gitter and I have been able to replicate it on Linux (Ubuntu 14.04). I cannot replicate it on OSX but was able to see the issue with another user (for him, a fresh clone/reinstall fixed it)

### Expected behavior
Reaction starts as normal upon a fresh install

### Actual Behavior
Nothing renders in the browser.  A ton of errors are show in the console starting with:
`Uncaught Error: Cannot find module 'bunyan-format/package.json'` in check-npm-version.js then a bunch of errors that cascade from there.

### Steps to Reproduce the Behavior
On Ubuntu 14.04 just doing a fresh clone, `meteor npm install` and running `./reaction` allowed me to see the behavior.

**Comment by fisherman818** [comment]
facing the same issue on Ubuntu 15.10 as well

**Comment by aaronjudd** [comment]
what  if you do `meteor npm install --save bunyan-format`?  (forcibly installing in the app package.json)

**Comment by nialexsan** [comment]
./reaction reset
./reaction pull
helps with this issue

**Comment by fisherman818** [comment]
@aaronjudd , `meteor npm install --save bunyan-format` doesn't solve the problem

**Comment by vkmrishad** [comment]
./reaction reset
 says "unable to find files in pakage/......"

**Comment by aaronjudd** [comment]
ok so all reaction reset is doing is a `meteor reset`

can you try::
```
meteor reset
meteor npm install
meteor
```

**Comment by aaronjudd** [comment]
If you have previously ran `reaction pull` that's pulling the latest development branch version of all our packages.  Also many of the packages are just in the repo, so I suspect the error is 

```
find: ./node_modules: No such file or directory
find: ./packages/reaction-auth-net/.npm/package/node_modules: No such file or directory
find: ./packages/reaction-braintree/.npm/package/node_modules: No such file or directory
find: ./packages/reaction-checkout/.npm/package/node_modules: No such file or directory
find: ./packages/reaction-core/.npm/package/node_modules: No such file or directory
```

which is, um,  actually not an error.. just some notifications from the script that we should suppress.

**Comment by fisherman818** [comment]
@aaronjudd , with ./reaction reset and ./reaction pull, the issue was resolved on Ubuntu 15.10 

I also saw those notifications showing "no such files or directory", for some node modules. Ignored them, and proceeded with the ./reaction pull, and no more blank screens

**Comment by ewallteam** [comment]
Hi,

We are using ubuntu 16.04 and getting the blank screen on product detail page from customer interface when there is any edit on product details from the admin login. It remains blank even after refreshing the page on browser. However, it is fine when we go to "Shop" menu and then go back to the product page again.

Below is the console warning which are getting on browser.

_WARNING: npm peer requirements (for reactioncommerce:reaction-logger) not installed:
 - bunyan-format@0.2.x not installed._

Tried all the below three but nothing helps,

1.Installing in the app package.json
meteor npm install --save bunyan-format

2.Resetting meteor
meteor reset
meteor npm install
meteor

3.Resetting reaction
./reaction reset
./reaction pull

**Comment by jujes** [comment]
Hi, I'm using docker reactioncommerce/reaction and have the same issue:
**with chrome:**
![screen shot 2016-06-30 at 15 24 47](https://cloud.githubusercontent.com/assets/2881017/16489806/63d8abec-3ed7-11e6-997f-3135099a56eb.png)

**with firefox:**
![screen shot 2016-06-30 at 15 27 53](https://cloud.githubusercontent.com/assets/2881017/16489810/688ee7c8-3ed7-11e6-90fb-99f1263b59a6.png)

someone know how fix it?

**Comment by aaronjudd** [comment]
You could try
```
Npm.depends({
  "bunyan": "1.8.0",
   "bunyan-format": "0.2.1",
   "bunyan-loggly": "0.0.5"
 });
```
back into  `packages/reaction-logger/package.js`.  I believe that should resolve the dependency warning. 

This is only applicable to the `master` branch, as the  `development` branch is completely refactored in the way packages and modules are loaded.

**Comment by jujes** [comment]
@aaronjudd no success; my **packages/reaction-logger/package.js** is

```
Package.describe({
  summary: "Reaction Logger - core logging libs for Reaction Commerce",
  name: "reactioncommerce:reaction-logger",
  documentation: "README.md",
  version: "0.2.1"
});

Npm.depends({
  "bunyan": "1.8.0",
   "bunyan-format": "0.2.1",
   "bunyan-loggly": "0.0.5"
 });

Package.onUse(function (api) {
  api.versionsFrom("METEOR@1.3");
  api.use("tmeasday:check-npm-versions@0.3.1");
  api.use([
    "ecmascript",
    "underscore"
  ]);

  api.mainModule("server/main.js", "server");
  api.mainModule("client/main.js", "client");

  api.export("bunyan", "client");
  api.export("Logger", "server");
});

Package.onTest(function (api) {
  api.use("tinytest", "client");
  api.addFiles("tests/bunyan-test.js", "client");
});
```

even I add  **"bunyan-loggly": "0.0.5"**

in **/packages.json**

```
{
  "scripts": {
    "reaction": "./reaction",
    "reaction reset": "./reaction reset",
    "reaction pull": "./reaction pull",
    "reaction install": "./reaction install"
  },
  "name": "reaction",
  "description": "Reaction is a modern reactive, real-time event driven ecommerce platform.",
  "version": "0.13.0",
  "main": "main.js",
  "directories": {
    "test": "tests"
  },
  "homepage": "https://github.com/reactioncommerce/reaction",
  "url": "https://github.com/reactioncommerce/reaction",
  "email": "reaction@reactioncommerce.com",
  "repository": {
    "type": "git",
    "url": "https://github.com/reactioncommerce/reaction.git"
  },
  "author": "Reaction Commerce <hello@reactioncommerce.com>",
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/reactioncommerce/reaction/issues"
  },
  "dependencies": {
    "bunyan": "^1.8.0",
    "bunyan-format": "0.2.1",
    "bunyan-loggly": "0.0.5",
    "meteor-node-stubs": "^0.2.1",
    "react": "15.1.0",
    "react-dom": "15.1.0"
  }
}
```
