### ISSUE TITLE
Firefox websocket loading errors

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#979]
### Expected behavior
When using FireFox, pages should load quickly, and reload, should also work.

### Actual Behavior
In FF, watch console..  initial page load produces repeating console warning:
`The connection to ws://localhost:3006/sockjs/231/zjsp5870/websocket was interrupted while the page was loading.`

until the page slowly loads. 

If you reload the page, you'll get a white screen, no data, and it will not reconnect the websocket until the websockets errors complete - the page will eventually load, but it takes a while.

if you run meteor/reaction with `DISABLE_WEBSOCKETS=1` the problem doesn't occur.

Tested with other Meteor apps in FF, and the issue isn't replicable there.

**Comment by aaronjudd** [comment]
This seems to be less of an issue with FF 46.0.1, however I do see if eventually return after multiple application (server) reloads.

**Comment by jshimko** [comment]
I do occasionally see that warning in Firefox, but I don't see any difference in page load time.  It seems like FF might just be failing to make the [initial websocket handshake](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#The_WebSocket_Handshake), but it always successfully connects a few milliseconds later.  After that point, everything works fine with no errors.  

I'm thinking it's possible that FF may be failing to connect with standard Websockets and [SockJS](https://github.com/sockjs/sockjs-client) is using a fallback (which is the entire reason Meteor uses SockJS for DDP).  I also used [Websocket Monitor](https://github.com/firebug/websocket-monitor/wiki) to dig in further and I don't see any errors anywhere.

**Comment by aaronjudd** [comment]
It seems to be performing well.. I think FF has always had that behaviour.. this is much better, and at least it seems at first glance to be resolved.  I just updated to the latest FF and I don't even see the single warning anymore.

**Comment by jshimko** [comment]
Going to close this for now.  Feel free to reopen if this becomes an issue in the future.
