### ISSUE TITLE
Support additional payment methods

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#99]
Add support for additional payment methods, including a provider oriented toward international markets.

**Comment by aaronjudd** [comment]
v0.2.2 adds reaction-braintree, reaction-stripe, reaction-shipping packages. 
*These are feature incomplete feature packages (not tested, just migrated and updated inline to current codebase).*

This release also adds functionality to allow multiple payment provider templates (loop and display). #246 suggests a more elegant payment interface. 

#129 is the issue for COD/Cash.

Please feel free to create a new issue for new payment providers, services that you'd feel would be useful.

**Comment by jchiocchio** [comment]
I humbly recommend adding support for Mercado Pago (http://www.mercadopago.com/) which is used by 90,000,000 customers in Latin America.
