### ISSUE TITLE
Blaze or React, or Angular.js, for the future development?

### ISSUE THREAD

**Issue by fisherman818** [reactioncommerce/reaction#990]
Hi, I am just curious that, since it looks like from Version 1.3 on, Meteor will lean toward using React as the front end (well, just my 2 cents), rather than Blaze, so for the future development, Reaction Commerce is going to stick with Blaze, or change to React too?

Cheers!

**Comment by mikemurray** [comment]
Moving towards React. Its really clear that Blaze will only get updates if the community contributes them, and that the Meteor team leaning more towards React.

At the moment we're actually a hybrid of Blaze and React components, with newer ones being written in React, and older ones converted bit by bit.

**Comment by fisherman818** [comment]
Thanks for the clarification!
