### ISSUE TITLE
Incorrect totals in Admin Dashboard

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#992]
### Expected behavior
Amounts in the admin dashboard should show correctly in the stores base currency

### Actual Behavior
It appears that the admin dashboard is attempting to show the totals in the locale currency but failing. As you can see in the screenshot it is showing 0.00 for all totals.
<img width="1427" alt="orders" src="https://cloud.githubusercontent.com/assets/72819/14945013/9f516a1a-1038-11e6-8820-ba3993b43a0b.png">

### Steps to Reproduce the Behavior
1. Use VPN or some other way of simulating that you are in a different locale, or alternately change your base currency to something besides USD.
2. Place an order and go to the "Order" dashboard
3. Observe that amounts for orders display as if they are in the locale currency, but are in fact incorrect.

Note that while this happens pretty regularly, sometimes it will stop doing it and show in the base currency.

**Comment by aaronjudd** [comment]
Agree that we should not be formatting admin currency values, they are presumed to be in the Shops base currency.

**Comment by mikemurray** [comment]
This could be fixed in the `numericInput component`  by loading the shop's currency vs doing a currently lookup.
