### ISSUE TITLE
Items in order not being merged

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#996]
### Expected behavior
If an item is added to the cart more than once, it should be merged into a single line item when the order is completed.

### Actual Behavior
Identical line items are not being merged.
<img width="1177" alt="cart_completed" src="https://cloud.githubusercontent.com/assets/72819/14975560/81da83f6-1135-11e6-895a-858eeba3bbfc.png">

### Steps to Reproduce the Behavior
1. Add an item to the cart
2. Add the same item to the cart again
3. Complete the order
4. Observe that there are two entries in the database.

**Comment by newsiberian** [comment]
Hello, I've spend some time by investigating this issue and it is work exactly how it designed. Look at [this](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/server/methods/cart.js#L561) line. This changes was added by this commit: 021dfd4e4894d58b5a587402fcdbf0c309aacc13

**Comment by zenweasel** [comment]
Then it's designed incorrectly. No shopping cart should behave like that. The scenario of having 10 of the item on one line and then 3 of the same item on another will lead to confusion which will lead to chargebacks.

**Comment by aaronjudd** [comment]
@zenweasel it's the **order**, not the **cart** behaving this way. the cart seems fine.  - but yes order items should be grouped, unless they are from diffferent shops

**Comment by zenweasel** [comment]
My mistake, you are correct. Changing the issue title.

**Comment by prinzdezibel** [comment]
Not sure, but it seems this happened with this commit:

https://github.com/reactioncommerce/reaction/commit/1eca97bf5245e83ac3807a35bc734ab6743b852e
