### ISSUE TITLE
When using layout override, sometimes `coreLayout` is still used

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#998]
### Expected behavior
When you override a layout you should always get the same layout.

### Actual Behavior
Sometimes when you first load the site and very often (maybe always) when you use the back button it will fall back to using the `coreLayout`. Added a console.log here in `layout.js`.
<img width="521" alt="easywine" src="https://cloud.githubusercontent.com/assets/72819/14977386/fc3401b2-1145-11e6-9850-162810bfd379.png">

### Steps to Reproduce the Behavior
1. Make changes to override coreLayout
2. Load the site.
3. Navigate away from this route.
4. Hit the back button
5. `coreLayout` is used.
6. If you refresh it will use the custom layout again.

**Comment by prinzdezibel** [comment]
This was a bug in easywine's specific route handling. See: easyweasel/client/routes.js

It was fixed and should not occur any longer.

**Comment by prinzdezibel** [comment]
@zenweasel: ticket can be closed

**Comment by zenweasel** [comment]
Closed per @prinzdezibel
